### ISSUE TITLE
Work on my AMD but not with gtx1060 gb

### ISSUE THREAD

**Issue by Patseb33** [UnamSanctam/SilentCryptoMiner#1]
hi, thanks for your tool it's amazing but the gpu miner don't work on my gtx 1060gb, the miner launch and close everytime, I can see the rig on nicehash but it doesn't mine ! Works fine on my other computer with AMD vega.

**Comment by Patseb33** [comment]
The processor mining seems to work with monero but I don't see the btc on nicehash using nicehash monero pool.

**Comment by Patseb33** [comment]
But it works on cpu mining.

**Comment by UnamSanctam** [comment]
How much VRAM does the GTX 1060 have? If you mine Ethereum then it needs at least 4.5GB of free VRAM.

**Comment by Patseb33** [comment]
It's a 6GB but 0 are used when the miner is turned on !

**Comment by UnamSanctam** [comment]
How are you checking that? MSI Afterburner? Can you run the {MINER]-checker.exe that was generated with your miner and post that?

**Comment by Patseb33** [comment]
![screenshot](https://user-images.githubusercontent.com/93942893/140813447-35dffee0-8fda-4b3b-b72f-b5db65a91da3.png)

**Comment by Patseb33** [comment]
![screenshot](https://user-images.githubusercontent.com/93942893/140813728-e831b0ab-b3e3-4def-92b5-f0fc343c93f6.png)

**Comment by UnamSanctam** [comment]
The miner isn't running so I would guess that your miner (ETH) settings are incorrect.

**Comment by Patseb33** [comment]
I put daggerhashimoto.eu-west.nicehash.com:3353 for the pool and my Nicehash wallet
I try with different algorythm like cryptonighR and kowpow and it does'nt work too, the same parameters worked fine on my Vega 64 and The nicehash miner (excavator) for GTX 1060 6gb works fine.

**Comment by UnamSanctam** [comment]
Go to the "Main" tab and press "Save", then send the file here.

**Comment by Patseb33** [comment]
[Testminerxml.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7500216/Testminerxml.zip)

**Comment by Patseb33** [comment]
I don't put my wallet into this but I do when building.

**Comment by UnamSanctam** [comment]
Yeah that works fine for me when I enter my NiceHash BTC wallet.

**Comment by Patseb33** [comment]
Strange maybe a windows issue ?

**Comment by UnamSanctam** [comment]
No that should be fine, can you disable "Startup" and try that?

**Comment by Patseb33** [comment]
Same problem.

**Comment by UnamSanctam** [comment]
That only really happens if the connections settings are wrong or if the drivers are old.

**Comment by Patseb33** [comment]
Ok it's strange because the same connections work well with AMD and the drivers are the latest.

**Comment by UnamSanctam** [comment]
Can you check the driver version in the Task Manager (press the "Performance" tab and then select the GPU and it will say the version)? Also, do you use "Hide File" or not?

**Comment by Patseb33** [comment]
The version is 30.0.14.9649, I didn't use Hide File.

**Comment by UnamSanctam** [comment]
Yeah that should work fine, did you use "Install Rootkit" or not?

**Comment by Patseb33** [comment]
I don't

**Comment by UnamSanctam** [comment]
Can you try the new miner version after running all the uninstallers generated by the previous builds?
