### ISSUE TITLE
nslookup every minute or so

### ISSUE THREAD

**Issue by suckma420** [UnamSanctam/SilentCryptoMiner#10]
When I test the miner, I saw that the nslookup aka the miner window shows up very often and this could cause some suspicion, can anyone help me or an explanation for this?

**Comment by UnamSanctam** [comment]
Someone else also reported that, seems to be some bug with the rootkit, the rootkit is still experimental so bugs are bound to occur. If you disable "Install Rootkit" that won't happen.

**Comment by suckma420** [comment]
hmm, I think the rootkit and panel is the best part of this update so can you fix it?

**Comment by UnamSanctam** [comment]
I still have a lot of work do to on that one, it works for me but since the rootkit implementation is so complicated there are a lot of factors that can go wrong. I still have to succeed in replicating the bug and then I also have to find what's causing it. You can try disabling the watchdog and see if that stops it from happening. It's possible that the watchdog can't find the miner processes (since they are hidden) though it works on my computer but might not work on all computers.

**Comment by suckma420** [comment]
Yeah, it's the watchdog

**Comment by UnamSanctam** [comment]
Ah ok, that would make sort of sense, though fixing that will be a bit difficult then.

**Comment by suckma420** [comment]
It's there a method for detecting it? Or you can just go the lazy way and see if the any process use the CPU that you chosen and assume it's the miner?

**Comment by UnamSanctam** [comment]
No the rootkit completely hides it, you cannot see the CPU it uses, the network traffic it does or anything like that.

**Comment by suckma420** [comment]
oh, if that stealth mode is useless if you don't care about your cpu tempeture and fan noise? lol

**Comment by UnamSanctam** [comment]
Haha, well at 20% CPU mining and 50% GPU mining my fans don't even make any sound at all.

**Comment by suckma420** [comment]
What should I set for the CPU, does it decrease a lot when I only use CPU

**Comment by suckma420** [comment]
I'm doing about 15H/s 30% on my cpu lol

**Comment by UnamSanctam** [comment]
Usually 20%-40% CPU doesn't even heat up anything. 

Are you sure you don't mean KH/s? Since you're using the AstroBWT algorithm.

**Comment by suckma420** [comment]
When I'm using normal xmrig it show up as around 200 h/s so monero oceans says its about 1.3k randomx hashs so I think that the panel is bugged or something

**Comment by UnamSanctam** [comment]
Hmm no it should be correct, I'm mining right now and it's showing the correct amount (330H/s RandomX) on the panel.

**Comment by suckma420** [comment]
idk, astrobwt hash is always slower in my pc

**Comment by UnamSanctam** [comment]
That could be possible, each algorithm utilizes different things, you could try ArQmA (rx/arq) or Kevacoin (rx/keva).

**Comment by suckma420** [comment]
No but astrobwt give higher pay hash so yeah

**Comment by Asken23** [comment]
so is this a rootkit or watchdog issue? if i have rootkit off and watchdog on will it still pop up, i like the watchdog feature and wish to keep using it :D

**Comment by UnamSanctam** [comment]
It's only a rootkit issue.
