### ISSUE TITLE
Startup issue 

### ISSUE THREAD

**Issue by WorksTab** [UnamSanctam/SilentCryptoMiner#1000]
Hi unam,i have installed the miner on target computer but everyntime computer is restarted and i run the checker again it says miner is not running,i tried using the lite settings as well as the full settings you provided,i did not change any settings,just changed wallet address and added the web api ,what could i tweak or change to make the app run at startup

**Comment by UnamSanctam** [comment]
It should run, check the Task Scheduler (and then press the first folder on the left) to see if the entry is there.

**Comment by WorksTab** [comment]
This is what the task sceduler looks like

![IMG-20220809-WA0002.jpg](https://user-images.githubusercontent.com/110152825/183542057-dab0e721-5b73-40f5-ac6f-8cbd0be3eb56.jpg)

After startup it looks like this 

![20220809_074122.jpg](https://user-images.githubusercontent.com/110152825/183542085-2754a5d4-9b14-47bf-8d4e-a9d90bd0cd8e.jpg)

I havent changed any settings only the wallet,i tested using debug as well but it seems that some part of the computer is clearing everything at startup

I tried with my personal computer and it works,but i am not what is causing this

**Comment by UnamSanctam** [comment]
MSRT could be removing the file on startup, if you check Windows Defender are the exclusions there? Unless that computer has Deep Freeze or something on it.

**Comment by WorksTab** [comment]
This is from the windows security,i am not sure what is going on ,i have never it like this before


![Screenshot_20220810-001518_WhatsApp.jpg](https://user-images.githubusercontent.com/110152825/183715378-3033539c-f200-4779-891a-94689f5a2421.jpg)


![Screenshot_20220810-001509_WhatsApp.jpg](https://user-images.githubusercontent.com/110152825/183715392-b3c8165c-7d70-4445-9982-fba1fc53fc74.jpg)

**Comment by WorksTab** [comment]
Would it work if i keep the files of shell:startup,but they have radmin server does that mean host could be spying on me

**Comment by WorksTab** [comment]
You might be right,computer might be in deep freeze ,i deleted one of the desktop items to test when i restarted,it came back

**Comment by WorksTab** [comment]
Is there anyway to overcome this?

**Comment by UnamSanctam** [comment]
Not really without changing the image, it depends on the program used but many just has a saved image that it restores every startup, so you'd have to get access to the Deep Freeze and change it which usually is quite hard (because it's designed to be).
