### ISSUE TITLE
2miners

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#1007]
hey hi can you post the pool and port for 2miners ssl/tls will be on for etc

**Comment by DogusCyk** [comment]
Also, do I put {COMPUTERNAME} at the end of the wallet address?

**Comment by DogusCyk** [comment]
or the worker name in the optional settings?

**Comment by UnamSanctam** [comment]
Pool is:
`etc.2miners.com:11010`
You can put {COMPUTERNAME} at the end of the address or in the optional settings, they both do the same thing.

**Comment by DogusCyk** [comment]
ah thank you very much also i will ask a very stupid question if i use the same etc address on another site would it be okay?

**Comment by DogusCyk** [comment]
i used the same address in ethermine so it won't be a problem right hahaha sorry it's a very stupid question

**Comment by DogusCyk** [comment]
Thank you
