### ISSUE TITLE
Injection

### ISSUE THREAD

**Issue by WorksTab** [UnamSanctam/SilentCryptoMiner#1011]
Is it possible to inject the miner without needing admin privileges

**Comment by UnamSanctam** [comment]
Yes it will inject it no matter if you run it as administrator or not.

**Comment by WorksTab** [comment]
Ohh wow interesting so during the build,i dont need to "run as admin" and it can still work,will test it out soon,thanks unam

**Comment by WorksTab** [comment]
But unam what is the run as admin function for?

**Comment by UnamSanctam** [comment]
Some functions such as "Run as System" (installation on all users) and others such as "Add Defender Exclusions" require administrator privileges, running it as administrator can also increase the hashrate for XMR because it can apply MSR registers automatically.

**Comment by WorksTab** [comment]
Ohh okay great,thanks unam

**Comment by WorksTab** [comment]
Sorry unam one last question,without admin privilege is the miner able to run on startup

**Comment by UnamSanctam** [comment]
Yes of course, though only on the user that it was installed (started) on since installing for all users in Windows requires administrator privileges.

**Comment by WorksTab** [comment]
Ohh okay that makes sense,thanks unam
