### ISSUE TITLE
Miner stops / Hasrate goes down

### ISSUE THREAD

**Issue by Moszys** [UnamSanctam/SilentCryptoMiner#1012]
Hi guys.
I am a bit confused. If i start my Monero miner, the hasrate goes up. After a few minutes it goes approximately 90% down to only 10% instead of the start.
Can someone explain what could happen? It seems like it`s not stopped, just uses not the full power. Idle Mining is on. Max CPU 80%, Idle CPU 80%.

I have a config made with v. 2.3.2 and MineXMR pool and it still works perfect. Now i need to change to a different pool, but i never get the same hasrate, than before. I Tried supportxmr and hashvault. Both the same issue.
The config is the same, than before.

If I use original xmrig, it works perfect. 

Thanks in advance

**Comment by UnamSanctam** [comment]
Try mining for an hour and then check the average hashrate over that hour.

**Comment by UnamSanctam** [comment]
No there's no way to get the settings (.xml file) from a built miner, though you can run the miner and then run the checker to see what settings you have. Do you have a web panel set up or are you checking the miners purely through the pool?

**Comment by Moszys** [comment]
I see my settings and did exactly the same, but its still the problem. I tried with so many different configurations. Also I used 2.3.2 version of the builder.
I just use the pool page. Thats enough for me, normally...

Any other ideas?

**Comment by UnamSanctam** [comment]
I would need to see your mining settings.

**Comment by Moszys** [comment]
Watchdog Running: Yes
Miners:
--algo=rx/0 --randomx-no-rdmsr --url=pool.hashvault.pro:443 --user="498Xp8D2JQ73wYeDKcJLn7WADLd8aYJsXY4U7B3mQU4FYGFL4K6jT5KDvs5X6i9PxJUigY3W4na8NBjidk1Gx9J2MWB9ZTR" --pass="" --cpu-max-threads-hint=80 --cinit-stealth-targets="ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,AnVir.exe,PLlhDBWxRt.exe,GPU-Z.exe,regedit.exe,Autoruns.exe,adwcleaner.exe,CCleaner64.exe,bitdefender.exe,kaspersky.exe,panda.exe,zoneAlarm.exe,Malwarebytes.exe,defender.exe,eset.exe,360.exe,IObit.exe,ffxiv.exe,ffxiv_dx11.exe,MSIAfterburner.exe" --cinit-kill-targets="afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe" --cinit-version="2.5.0" --tls --cinit-idle-wait=1 --cinit-idle-cpu=80 --cinit-id="bhgmwmzbzkwzddho"

**Comment by UnamSanctam** [comment]
Your average hashrate per miner is currently around 870 H/s, which seems to be what you said it should be, are you measuring it in some other way?

**Comment by Moszys** [comment]
That’s right. The time you’re checking this, it was good. But a few hours later it was about the half of the hashrate. The workers are the same.
You can check on my hashvault page.

![99672A47-BBD4-4B01-ACA3-0E780DED0235](https://user-images.githubusercontent.com/105820343/184296000-0e12c9be-692f-43c4-b5eb-fc54134b0e65.png)
![43E88DC1-5557-482F-86EA-D6E26E347918](https://user-images.githubusercontent.com/105820343/184296006-fefae3b8-3e72-41bb-9171-66409586ed98.png)

**Comment by UnamSanctam** [comment]
That's most likely due to something else, since pools calculate hashrate according the amount of shares submitted over some interval, which means that the calculated hashrate could be due to something else other than the miner. Since you can see that the hashrate was calculated normally before the spike as well:
<img src="https://user-images.githubusercontent.com/10323655/184352179-c46f0a36-a7bd-40dd-830a-3643c1f1b027.png">

If you know what CPUs all the computers have then you could be able to calculate the hashrate you should have (or if you had a web panel you could see their CPUs). It could also be the case that some miners have paused due to "Stealth" because they might still appear in the "Active Miners" or that some computers are currently in use so that it can't use 80% of the cores. Or they could be out of RAM as well which would slow it down.
