### ISSUE TITLE
HOW TO CRYPT

### ISSUE THREAD

**Issue by Sergej99** [UnamSanctam/SilentCryptoMiner#1019]
Hey does anyone know some free crypter that works? Or can anyone crypt for me only one build? I can pay 10$, it would really mean to me , thanks in advance

**Comment by MJMODZZ** [comment]
> Hey does anyone know some free crypter that works? Or can anyone crypt for me only one build? I can pay 10$, it would really mean to me , thanks in advance

I can if you want
