### ISSUE TITLE
an advice needed

### ISSUE THREAD

**Issue by sudspoon** [UnamSanctam/SilentCryptoMiner#102]
currently the build are base on 64bit right and do you have for the 32bit? by the way your project are really good for us that are currently under learning thanks XD

**Comment by UnamSanctam** [comment]
No, none of the miners (XMRig or ethminer) are 32-bit.

**Comment by fl1ckert** [comment]
Unam, if I did remote config for XMR, Ind I'm mining on GPU and CPU, do I need to add "max-gpu": x, parameter, if yes, send me please configuration, thanks

**Comment by UnamSanctam** [comment]
No it's not possible to set the "Max GPU" in XMRig (the XMR miner). You don't even want to mine XMR with the GPU in then first place though.
