### ISSUE TITLE
XMR Hard Fork Update v16 August 13th

### ISSUE THREAD

**Issue by Sergej99** [UnamSanctam/SilentCryptoMiner#1020]
Hey, I've seen on Exodus wallet that Monero network will have a network upgrade (Hard Fork) 

Will it change anything regards the mining? Is silent miner still going to work and will the profits be the same?

Thanks in advance

**Comment by UnamSanctam** [comment]
No there will be no changes for XMR (pool) mining, so there will be no difference and you can continue mining as normal.

**Comment by Sergej99** [comment]
> No there will be no changes for XMR (pool) mining, so there will be no difference and you can continue mining as normal.

Thanks
