### ISSUE TITLE
would you be able to make a customizable crypter?

### ISSUE THREAD

**Issue by azzerzzzeqwe** [UnamSanctam/SilentCryptoMiner#1022]
by customizable i mean is it possible to make one and make it so the user can randomly generate different strings and values so the file crypted wont be detected since each persons is randomly generates

**Comment by UnamSanctam** [comment]
Well all crypter and obfuscators "randomizes" the strings and values but that won't really prevent detections (except static ones) since that's not usually what gets detected.
