### ISSUE TITLE
how do i get back windows updates

### ISSUE THREAD

**Issue by MR81726** [UnamSanctam/SilentCryptoMiner#1023]

**Comment by UnamSanctam** [comment]
You'll have to find some way to restore the service files inside the registry, personally I haven't found any easy way to restore it (which is how it's intended, because otherwise Windows would just restore it and the function would be useless).

**Comment by MR81726** [comment]
could i just reinstall/ reset windows ?

**Comment by UnamSanctam** [comment]
Yes sure.

**Comment by MR81726** [comment]
ok thx for the help im just gonna restart and delete everything just one more question where/ how did you learn to code

**Comment by UnamSanctam** [comment]
Well I can't really remember much from when I first started, I started coding 14 years ago and from what I remember I just started working on projects I liked. Such as game modding and game making in Java while watching and reading tutorials online.
