### ISSUE TITLE
Ethereum 2.0 (MINING ETH GONE FOREVER) ?

### ISSUE THREAD

**Issue by Sergej99** [UnamSanctam/SilentCryptoMiner#1024]
Hey , I've seen all over the internet that in Ethereum 2.0 the Ethereum network will no more be PoW and it will turn to PoS, also I've seen news articles saying that this will be end of Ethereum mining and on Eth 2.0 , mining will no longer be supported! Does someone know if this is true?

**Comment by UnamSanctam** [comment]
Yes of course, they have been planning to migrate to ETH 2.0 since like 2018, they have just delayed it over and over again. Not sure when the actual update will happen since it has been delayed every time for several years, but the last testnet finally moved to PoS a few days a go I think so it's getting closer. I think it's expected to merge (move to PoS) this September.

**Comment by shainodev** [comment]
> he internet that in Ethereum 2.0 the Ethereum network will no more be PoW and it will turn to PoS, also I've seen news articles saying that t

that will mean no Ethereum mining? what about Ethereum coin?

**Comment by UnamSanctam** [comment]
Yes Ethereum will move away from PoW to PoS which means that you can't mine it, you can still mine any other ethash algorithm coins though of course, and you can still mine ETC and UBQ as well.

**Comment by elraiqq** [comment]
Can i change my online miners from mining eth to any another coin from webpanel 
??

**Comment by UnamSanctam** [comment]
> Can i change my online miners from mining eth to any another coin from webpanel ??

Yes, just change the configuration of them, either through "Remote Configuration" if you have one or directly through the web panels "Configurations" tab.

**Comment by Sergej99** [comment]
Is Ethereum Coin called etchash?

**Comment by UnamSanctam** [comment]
Ethereum Classic (ETC) uses the etchash algorithm, Ethereum uses the ethash algorithm.

**Comment by xzunknownzx** [comment]
> Yes of course, they have been planning to migrate to ETH 2.0 since like 2018, they have just delayed it over and over again. Not sure when the actual update will happen since it has been delayed every time for several years, but the last testnet finally moved to PoS a few days a go I think so it's getting closer. I think it's expected to merge (move to PoS) this September.
-----------
Unam!!! How can I get in touch with you... I know you had said you may add your telegram back but I never heard from you!  It's quite important and I would sincerly appreciate an add...  @michaelweston21
@UnamSanctam
