### ISSUE TITLE
Defender and Anti Virus 

### ISSUE THREAD

**Issue by WorksTab** [UnamSanctam/SilentCryptoMiner#1026]
Iam able to inject virus on my computer that i own as i can add the exclude on windows defender prior to attack but when i bind the virus on put ot on my usb for 1 click installations on internet cafe i often come across issues like defender deleting the program before it is even run ,do you have any tips to install workers in public quickly or binding that doesnt lead to detections by windows defender,thanks

**Comment by azzerzzzeqwe** [comment]
> Iam able to inject virus on my computer that i own as i can add the exclude on windows defender prior to attack but when i bind the virus on put ot on my usb for 1 click installations on internet cafe i often come across issues like defender deleting the program before it is even run ,do you have any tips to install workers in public quickly or binding that doesnt lead to detections by windows defender,thanks

look up how to disable windows defender via the registry. if its blocked use this https://breakingsecurity.net/administrator-switchboard/
also make sure to turn off windows defender real time protection before downloading it
