### ISSUE TITLE
steals from GH/s !!!

### ISSUE THREAD

**Issue by BlackBrazilianHacking** [UnamSanctam/SilentCryptoMiner#1033]
Hello UmanSanctam,

we put rats on the machines to see who was stealing gh/s from us ...

whether you fly 200 mh/s or even take 50% don't care, it's normal after all you wrote the code.

except that it's all of the 10 gh/s on the pool that have disappeared, and that's way too much!

the anti virus has not been reactivated because our rats are still there, there are thousands of machines in different countries, the pool has not blocked the eth address, who remains apart from you who put update your virus remotely?

I really hope for you that you are using tor... explain yourself, give us back the gh/s or we will try to find you, we are ready to invest a lot of money to find you!

**Comment by UnamSanctam** [comment]
Run the checker on one of the computers and post what it returns here.

**Comment by Brainshot** [comment]
Same i am worried aswell i keep losing everything, even though they didn't delete the miner or install any antiviruses.

**Comment by UnamSanctam** [comment]
> Same i am worried aswell i keep losing everything, even though they didn't delete the miner or install any antiviruses.

Run the checker and post what it returns if you can, it could be due to https://github.com/UnamSanctam/SilentCryptoMiner/issues/1034

**Comment by Brainshot** [comment]
> > Same i am worried aswell i keep losing everything, even though they didn't delete the miner or install any antiviruses.
> 
> Run the checker and post what it returns if you can, it could be due to #1034

k I will wait for the new update I guess, I have lost all my hashrates no idea what to do anymore so much loss.

**Comment by UnamSanctam** [comment]
>k I will wait for the new update I guess, I have lost all my hashrates no idea what to do anymore so much loss.

Even with the definition update you shouldn't have lost all your hashrate since updates _usually_ don't get rolled out at the same time, when you say "all" how much specifically? And what pool are you using?

**Comment by Brainshot** [comment]
> > k I will wait for the new update I guess, I have lost all my hashrates no idea what to do anymore so much loss.
> 
> Even with the definition update you shouldn't have lost all your hashrate since updates _usually_ don't get rolled out at the same time, when you say "all" how much specifically? And what pool are you using?

nanopool, just many of my miners dont come online after some time anymore. I have given up man there is no hope.

**Comment by UnamSanctam** [comment]
>nanopool, just many of my miners dont come online after some time anymore. I have given up man there is no hope.

Oh, so it's not the same problem as the original post then I assume? It sounds like he lost it all instantly from what he writes but he hasn't explained much in his post so that could be what he's saying as well maybe. Can you show a screenshot of your web panel if you have one?

**Comment by Brainshot** [comment]
> > nanopool, just many of my miners dont come online after some time anymore. I have given up man there is no hope.
> 
> Oh, so it's not the same problem as the original post then I assume? It sounds like he lost it all instantly from what he writes but he hasn't explained much in his post so that could be what he's saying as well maybe. Can you show a screenshot of your web panel if you have one?

Just the status online miners? or a single miner to see settings?

**Comment by UnamSanctam** [comment]
Both preferably, I just want an overview look, you can also screenshot an offline miner (that has been offline for long) as well if you have one.

**Comment by Brainshot** [comment]
> Both preferably, I just want an overview look, you can also screenshot an offline miner (that has been offline for long) as well if you have one.
![gefwfqwf](https://user-images.githubusercontent.com/93741208/185177204-fcb09e6e-de02-45c3-8e09-110f2087318f.PNG)


![fwqdxqw](https://user-images.githubusercontent.com/93741208/185177225-8d08e9f1-d964-43d1-8c8e-e09ed6b612ae.PNG)

All are offline btw i have like 40 new miners.

**Comment by UnamSanctam** [comment]
Seems like in the new update all `C:` exclusions are getting removed, this could be the reason why.

**Comment by Dlkuric** [comment]
> nanopool, just many of my miners dont come online after some time anymore. I have given up man there is no hope.

dude don't count on it for your future i know it hurts i have been streaming cryptominer for 7 months i bought 19 servers and today i lost everything because of microsoft defender i know what it is but n never forget that money does not buy happiness



I think I have identified the problem, indeed when running the cryptominer it removes exclusions from Microsoft Defender, in my opinion therefore it is enough to change the signature of the .exe and exclude another folder

**Comment by Brainshot** [comment]
> > nanopool, just many of my miners dont come online after some time anymore. I have given up man there is no hope.
> 
> dude don't count on it for your future i know it hurts i have been streaming cryptominer for 7 months i bought 19 servers and today i lost everything because of microsoft defender i know what it is but n never forget that money does not buy happiness
> 
> I think I have identified the problem, indeed when running the cryptominer it removes exclusions from Microsoft Defender, in my opinion therefore it is enough to change the signature of the .exe and exclude another folder

Stopped reading at "money does not buy happiness" fuck off with your bullshit retard.

**Comment by Brainshot** [comment]
> Seems like in the new update all `C:` exclusions are getting removed, this could be the reason why.

I see i understand thanks for help, gonna wait for new update.
