### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1034]
Good afternoon Unam. Today I checked the work of the miner And found that Windows Defender does not allow creating a task in the scheduler, and detects task creation as a virus. Screenshot attached
![1](https://user-images.githubusercontent.com/36513967/185124969-69bacdb5-22d7-448f-8231-2c3026200a88.jpg)
He manages to detect everything before the miner adds himself to the defender exceptions.

**Comment by UnamSanctam** [comment]
Seems like a new detection then, the exclusions happens before the task does but since it's detecting CmdLine it ignores that. If you build a new build of the miner and install that do you get the same detection? Since the command line will change a bit, also try changing from the normal "File Name" in "Startup".

**Comment by masterjek** [comment]
I created a new miner with a new name in the builder. The result of an unsuccessful defender still does not allow you to create a task.

**Comment by masterjek** [comment]
Just checked version 2.3.2 This version was able to create a task in the scheduler. The defender found it, but the miner itself started up. Everything works when I restart the computer, the defender issues a warning and no exceptions are created.

**Comment by UnamSanctam** [comment]
Yes, the new obfuscated string was to avoid that, because that Windows Defender notification was causing people to download new antiviruses from what people told me.

**Comment by masterjek** [comment]
As I understand it, it's better to use version 2.3.2. This version can run. Because 2.5.0 cannot start when the defender is enabled.

**Comment by UnamSanctam** [comment]
Maybe, version 2.3.2 has some other "problems" if you check the change log for versions after that.

**Comment by masterjek** [comment]
Thanks for the quick replies. I will wait for the new version, I hope you can bypass the new defender detection.
