### ISSUE TITLE
watchdog

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1036]
Why does the watchdog write the miner into a random path in temp instead of the original payload location that was specified? the miner will go to the payload location anyway so whats the point?

**Comment by UnamSanctam** [comment]
To make it reinstall, if you write it directly to the installed location then it won't run any of the installation code.

**Comment by shainodev** [comment]
> To make it reinstall, if you write it directly to the installed location then it won't run any of the installation code.

why dont u make it run the installation code anyway?

**Comment by UnamSanctam** [comment]
>why dont u make it run the installation code anyway?

What would be your idea on how to make it run anyways? Or do you mean that it should run on every start.

>what if they didnt remove the file but removed the startup

There isn't really any way to detect this from what I know, except through using external libraries or by running a powershell command and try to read the output of the command to see a task list.

**Comment by shainodev** [comment]
i mean my way is just running the startup command every launch it doesnt hurt to do it and detections wont matter anyway since the apps dont run 2 times on AV's sandboxes

**Comment by UnamSanctam** [comment]
Yes that's what I'm doing in the new version, the problem is that the rootkit won't get reinstalled then if it was removed (you don't want to install that on every run) which is why it was done that way. But reinstalling the rootkit isn't too important which is why it's also changed in the new (upcoming) version.

**Comment by shainodev** [comment]
> Yes that's what I'm doing in the new version, the problem is that the rootkit won't get reinstalled then if it was removed (you don't want to install that on every run) which is why it was done that way. But reinstalling the rootkit isn't too important which is why it's also changed in the new (upcoming) version.

when will it approximately be released?

**Comment by shainodev** [comment]
> Right now I'm trying to bypass the new detection, and I also want to finish the VRAM work I'm doing. But I'm trying to expediate it as much as possible right now.

goodd, also wouldnt it be better to make it download the ethminer from the internet?

**Comment by UnamSanctam** [comment]
That's what I had before when the "Online Download" feature existed but my website got taken down after VirusTotal reported it to SpamHaus which reported it to my domain registrar (which was supposedly "bulletproof") so the feature was removed (and if I set it to download it from GitHub then my account would get banned).

**Comment by shainodev** [comment]
> That's what I had before when the "Online Download" feature existed but my website got taken down after VirusTotal reported it to SpamHaus which reported it to my domain registrar (which was supposedly "bulletproof") so the feature was removed (and if I set it to download it from GitHub then my account would get banned).

what about bitbucket?

**Comment by UnamSanctam** [comment]
>what about bitbucket?

Problem is that if it gets taken down (we don't know if they do or not yet) then all new miners would stop working, which is why I had a website to be able to change the link if it happened.

**Comment by shainodev** [comment]
> Problem is that if it gets taken down (we don't know if they do or not yet) then all new miners would stop working, which is why I had a website to be able to change the link if it happened (the file itself was hosted on BitBucket).

why isnt it possible just to use a vpn's ip instead of a domain?

**Comment by UnamSanctam** [comment]
Because the IP could change or you could get banned if reported. Which is why bulletproof domains are used.

**Comment by shainodev** [comment]
> Because the IP could change or you could get banned if reported. Which is why bulletproof domains are used.

you can get banned on mullvad?? and i thought mullvads ip's didnt change

**Comment by UnamSanctam** [comment]
Sure there's no confirmation that you can't, also I have lost ports with Mullvad once before (they aren't guaranteed to be permanent anyways), and the server I used before has been down for like half a year now (the icon is red and you can't connect).

**Comment by shainodev** [comment]
> Sure there's no confirmation that you can't, also I have lost ports with Mullvad once before (they aren't guaranteed to be permanent anyways), and the server I used before has been down for like half a year now (the icon is red and you can't connect).

![image](https://user-images.githubusercontent.com/77803435/185172013-7508d312-38b2-4eb1-bb98-ca60736d0f00.png)
why does it kill the watchdog process? i dont get it, it kills it then it checks if its open

**Comment by UnamSanctam** [comment]
Because they're checking two different things, it only kills the non-injected one, the injected one is what it searches for. That's because you can't be certain that the current non-injected watchdog is for your current miner build.

**Comment by shainodev** [comment]
> Because they're checking two different things, it only kills the non-injected one, the injected one is what it searches for. That's because you can't be certain that the current non-injected watchdog is for your current miner build.

so even if i have memory watchdog i have to use that just incase?

**Comment by UnamSanctam** [comment]
You don't specifically need it no.

**Comment by shainodev** [comment]
> You don't specifically need it no.

also whats the difference between using the "more advanced" task scheduler startup technique? rather than just using the win7taskschadd

**Comment by UnamSanctam** [comment]
You can configure the settings a lot more in-depth, such as making it start on computer startup instead of any user logon, allowing it to start if on laptop batteries (not charging) and a few others:
```
-AllowStartIfOnBatteries -DisallowHardTerminate -DontStopIfGoingOnBatteries -DontStopOnIdleEnd -ExecutionTimeLimit (New-TimeSpan -Days 1000))
```

**Comment by shainodev** [comment]
> 

what does the executiontimelimit do?

**Comment by UnamSanctam** [comment]
How long it allows it to execute for, there was some bug on early Windows 11 that someone reported which that fixed, the second part is for the powershell obfuscation I'm pretty sure (though they added some kind of detection for it now).

**Comment by shainodev** [comment]
> How long it allows it to execute for, there was some bug on early Windows 11 that someone reported which that fixed, the second part is for the powershell obfuscation I'm pretty sure (though they added some kind of detection for it now).

so should i just make it run the "{0}" for better detection rate?

**Comment by UnamSanctam** [comment]
Maybe, the reason the obfuscated start was added was because Windows Defender was giving notifications for the non-obfuscated one, it didn't remove anything but people were downloading new antiviruses because of it.

**Comment by shainodev** [comment]
![image](https://user-images.githubusercontent.com/77803435/185182091-30ce3ab6-6838-4299-bb28-6e923993a03c.png)
maybe this is why -EncodedCommand didnt work on my pc but powershell -EncodedCommand did when i did Process.Start

**Comment by UnamSanctam** [comment]
Yes it works different if you run it manually in a powershell window compared to if you start a powershell process with that argument.

**Comment by shainodev** [comment]
> Yes it works different if you run it manually in a powershell window compared to if you start a powershell process with that argument.

i mean it still didnt work when i ran it with shellexecute or process.start, will it not work if i would add powershell -EncodedCommand instead of -EncodedCommand? or there wont be any difference right

**Comment by shainodev** [comment]
![image](https://user-images.githubusercontent.com/77803435/185182939-d1b933b2-df7d-49f8-b136-4ef317dd6202.png)
andd also are these settings bad

**Comment by shainodev** [comment]
![image](https://user-images.githubusercontent.com/77803435/185183107-2673721c-3e96-407f-ba67-6cc89c4ef41c.png)
uhh

**Comment by UnamSanctam** [comment]
> i mean it still didnt work when i ran it with shellexecute or process.start, will it not work if i would add powershell -EncodedCommand instead of -EncodedCommand? or there wont be any difference right

Probably won't be a difference, you'd have to test it.

>andd also are these settings bad

They should be good

>uhh

Yes it's a small bug that was hotfixed. Change this line:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/fff3bd0656bc308c6efea79239058b9f9b0e96cb/SilentCryptoMiner/Forms/Builder.cs#L748
To:
```
else if(txtInstallPath.Text == "Program Files")
```

**Comment by shainodev** [comment]
if you can could you give me the code for the watchdog bsod on kill by any chance?

**Comment by UnamSanctam** [comment]
It's not just some code inside the watchdog since that would be easily detected, I have made a native library for setting files to critical using their PID in the main program, so the whole process has been reworked, it's best just to wait for the next version for that.

**Comment by shainodev** [comment]
> It's not just some code inside the watchdog since that would be easily detected, I have made a native library for setting files to critical using their PID in the main program, so the whole process has been reworked, it's best just to wait for the next version for that.

ohh i see ill wait then

**Comment by Dlkuric** [comment]
I'm waiting for the next version with impatience I'm currently poor xd

**Comment by shainodev** [comment]
> I'm waiting for the next version with impatience I'm currently poor xd

patience gets you money dude
