### ISSUE TITLE
lost etc miners

### ISSUE THREAD

**Issue by pcflux** [UnamSanctam/SilentCryptoMiner#1037]
I lost etc miners but the same computer/ip is mining xmr?
And its not virtual machine because they were mining etc few days ago
what could be the problem?

**Comment by UnamSanctam** [comment]
Can you show a screenshot of the web panel?

**Comment by pcflux** [comment]
I changed my web server few days ago and not all of the miners came back but i know that computer name was mining etc and now its only  mining xmr (in pool)

**Comment by pcflux** [comment]
off topic: 
![image](https://user-images.githubusercontent.com/110896305/185191384-c24eb174-3554-4f18-b00d-b8808aa1a072.png)
![image](https://user-images.githubusercontent.com/110896305/185191441-ec5dd840-f174-4670-9fb9-52f8b093191d.png)
what could be the problem?

**Comment by pcflux** [comment]
I see. thanks for helping
