### ISSUE TITLE
Idea Disabling Windows Defender

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1039]
Good evening Unam. I don’t understand programming well, so I’ll write, but I don’t know if it can be implemented - If you make it possible for the miner to disable or limit some of the functions Windows Defender, Using the Group Policy Editor Windows or using the registry.

**Comment by UnamSanctam** [comment]
It's not really possible to disable/limit Windows Defender (anymore) unfortunately, you can turn off some things but not the major ones, and even then it reenables some of the things you disable sometimes.

**Comment by masterjek** [comment]
Thanks for the answer
