### ISSUE TITLE
ethermine or 2miner?

### ISSUE THREAD

**Issue by Trkyyyy** [UnamSanctam/SilentCryptoMiner#1040]
I'm currently using ethermine and for some reason if several people start a miner, they can't mine at the same time with the same username and then I have to create a new miner for each one... Is the situation the same on 2miner...

**Comment by UnamSanctam** [comment]
You should be able to mine with the same worker name, on the pool the hashrates will just combine under the same worker name (so it will just show one worker name for all the miners). It should work on both ethermine and 2miners.

**Comment by qxzusero** [comment]
if your country isn't in black list ethermine choose ethermine
