### ISSUE TITLE
Interesting Fact Windows Defender

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1044]
Just experimented with a batch file and adding exceptions for Windows Defender. Before starting the miner, the bat file adds the entire disk "C" to the exceptions. After starting miner, the defender removes the disk "C" from the exceptions. The most interesting thing is that if I do not run the miner, then the defender does not remove the disk "C" of the exceptions.

**Comment by UnamSanctam** [comment]
Yes it removes it because of the ExcludeProc detection, and it doesn't seem to remove the other exclusions from my tests.
