### ISSUE TITLE
Could a file mutator work?

### ISSUE THREAD

**Issue by grisuIIARCHLINUX** [UnamSanctam/SilentCryptoMiner#1052]
Would it be possible to randomly mutate every generated .exe file to bypass windows defender? some other viruses do this to stay undetected.

**Comment by UnamSanctam** [comment]
`That's what an obfuscator does, so you can use a .NET obfuscator to do it and it already has one built it (string, variable and function name obfuscation and resource encryption), as you can see if you check the assembly code after it has been built.
