### ISSUE TITLE
WriteAllBytes Error

### ISSUE THREAD

**Issue by Spectrum735** [UnamSanctam/SilentCryptoMiner#1053]
Hi, Unam! I made a third watchdog process, that will be just hung in memory and do nothing. It's need to protect my installation folder from deletion, when two mains watchdog runs in memory only. I got error on `File.WriteAllBytes` method, parameter `bytes` cannot be `null`. But i define new compiler method in Codedom, add file to resources and parameter, add compiler method to the builder, but i get error anyway. How to run two watchdogs in memory and third file from folder at the same time?
PS: third watchdog file is not empty.

**Comment by UnamSanctam** [comment]
If it says that it's null then that means that it can't get the resource, so the problem appears when you add the resource or that the resource ID is pointing wrong.

**Comment by Spectrum735** [comment]
accurately! i forgot add it to install condition and rename data variable in codedom. Thanx!
