### ISSUE TITLE
ETC NO WORK

### ISSUE THREAD

**Issue by gtachina** [UnamSanctam/SilentCryptoMiner#1054]
HEY
POOL - 2 MINERS ETC
mining goes on and loads the video card - but the new worker does not appear on the pool
, I tried even with an ssl and a regular stratum
![image](https://user-images.githubusercontent.com/111654631/185758955-9e90e142-d1d2-4b79-a7db-004684dad85d.png)

**Comment by UnamSanctam** [comment]
I can see that you're mining with `sslwork` right now.

**Comment by gtachina** [comment]
ye bro - stratum ssl - worl
regular stratum - dont work)

**Comment by UnamSanctam** [comment]
Great, also mind that the regular startum port is 1010 while the SSL stratum port is 11010.
