### ISSUE TITLE
Fake error

### ISSUE THREAD

**Issue by Danito28** [UnamSanctam/SilentCryptoMiner#1058]
Is it possible to add a fake error message?

**Comment by Danito28** [comment]
For example, I use this tool ([https://github.com/Sploups21/extension-spoofer]) to spoof the extension of the executable by extension ".rar", as it could add a false error message, type "the file is damaged "?

**Comment by azzerzzzeqwe** [comment]
> Is it possible to add a fake error message?

already possible https://github.com/UnamSanctam/UnamBinder
