### ISSUE TITLE
Problem with latest versions

### ISSUE THREAD

**Issue by icemaxxx** [UnamSanctam/SilentCryptoMiner#1059]
Hello!

Thanks for your product.

In the latest version, I encountered the following problem: the miner does not start after restarting the PC. On version 2.5.0 everything works fine, but on the latest version (2.6.1) this problem occurs even after a build with the same settings.

I also tried to create builds with other settings, changed some parameters, but the miner still does not start after restarting the PC.

The build on version 2.5.0 still works fine.

**Comment by UnamSanctam** [comment]
And "Startup" is enabled? Can you save your settings by pressing "Save" in the "Main" tab and then zip them and send them here (drag it into the reply box)?

**Comment by icemaxxx** [comment]
[issue.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9390894/issue.zip)
I removed my miners from these settings.
I also tried some other settings.

**Comment by icemaxxx** [comment]
[working 2.5.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9390911/working.2.5.zip)
Here is also the settings file with which it works successfully on version 2.5. The settings are almost the same.

**Comment by UnamSanctam** [comment]
Yes "Startup" is not enabled in that save, some form controls can change between version so some settings from old save files might not apply (because they apply to old references), the "Startup" toggle checkbox being one of them.

**Comment by icemaxxx** [comment]
![startup](https://user-images.githubusercontent.com/111716629/185831366-c7002afe-41cd-45ec-b373-e85074b67ef1.png)
Do you mean it?

**Comment by icemaxxx** [comment]
That's it, now I understand)
After loading the settings, I tried to check them, but I did not notice the checkbox. Indeed, in the old version, when loading the same settings, it is active.

**Comment by UnamSanctam** [comment]
Alright great.

**Comment by icemaxxx** [comment]
Thank you!
