### ISSUE TITLE
nanopool settings

### ISSUE THREAD

**Issue by faqu1** [UnamSanctam/SilentCryptoMiner#106]
![image](https://user-images.githubusercontent.com/95179319/143854075-0b352d11-a8bb-4bf6-a384-18fec407d871.png)

These are the correct settings for nanopool?

**Comment by UnamSanctam** [comment]
You should surround the wallet address (and worker names and password) with ` like so:
```
stratum://`Wallet.Worker/Password`@eth-eu1.nanopool.org:9999
```
So that it all gets encoded.

**Comment by 1aminov** [comment]
@UnamSanctam https://rentry.co/unamtest/raw is everything right here?

**Comment by UnamSanctam** [comment]
Yes that should work.
