### ISSUE TITLE
Although it appears on the web panel, it does not appear in my pool.

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#1062]
![image](https://user-images.githubusercontent.com/81167210/185933905-e8e1608d-83c3-48b6-8166-69ed5fdd0456.png)
![image](https://user-images.githubusercontent.com/81167210/185933931-32a84ede-40d9-45f5-81c0-e52ba45025bc.png)
[settings.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9394797/settings.zip)

**Comment by DogusCyk** [comment]
[settings.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9394802/settings.zip)
And its my settings whats wrong

**Comment by DogusCyk** [comment]
Also, not only her, but 2 other people are in this situation.

**Comment by UnamSanctam** [comment]
If it has hashrate then it's mining to the pool, what hashrate does it have right now?

**Comment by DogusCyk** [comment]
Although it worked for 1 hour and 42 minutes, it did not come to my pool, when I looked a few minutes later, I saw that it came, why did it appear so late?

**Comment by UnamSanctam** [comment]
Because that was the time it found the share, it only appears in the pool when it finds a share, 2miners has an 8.72G difficulty.

**Comment by DogusCyk** [comment]
ah it made me feel good that it wasn't a problem thank you

**Comment by pcflux** [comment]
> Because that was the time it found the share, it only appears in the pool when it finds a share, 2miners has an 8.72G difficulty.

what other pools would you recommend? (for etc/xmr)

**Comment by UnamSanctam** [comment]
All pool usually have that big share difficulty, or even more. Though I think ethermine has 4G, but their statistics are very "slow".
