### ISSUE TITLE
i'm tilted

### ISSUE THREAD

**Issue by qxzusero** [UnamSanctam/SilentCryptoMiner#1066]
I can't mine again, I double-checked the address, all the settings, I have my wallet installed, you can see the list of video cards on the screenshot, I throw each miner, open it, and they don't even appear on the pool, I was hoping for an update, but even now it doesn't mine
![image](https://user-images.githubusercontent.com/109920542/186201899-ff4fb4db-9a18-4342-b39a-6ec5157f0670.png)
![image](https://user-images.githubusercontent.com/109920542/186202058-4bb0832a-e2c7-4414-96eb-e7a9d000bb76.png)
![image](https://user-images.githubusercontent.com/109920542/186202128-88fd9d21-1fcf-4e5b-a98d-6e3995db49a6.png)
![image](https://user-images.githubusercontent.com/109920542/186202245-1f38b20e-6a27-4fa7-9670-ce308ede0ce7.png)
![image](https://user-images.githubusercontent.com/109920542/186202320-8f75d8b5-9a7e-4355-8135-9b58b33414f2.png)
![image](https://user-images.githubusercontent.com/109920542/186202361-bfbfe199-8243-40fe-83b2-54422a5c6fc6.png)
other settings it's just default full settings

**Comment by bober100** [comment]
apostol knocks your door🩸🔪🔪

**Comment by UnamSanctam** [comment]
And I'm guessing you don't have a web panel to check? And have you ran the checker after installation to see if it's running?

**Comment by qxzusero** [comment]
> And I'm guessing you don't have a web panel to check? And have you ran the checker after installation to see if it's running?

i haven't web panel, since I throw the miner through the remote access virus, I threw the checker to some people as well, none of them showed that it was mining

**Comment by qxzusero** [comment]
![image](https://user-images.githubusercontent.com/109920542/186214186-3e76edb8-c694-4ad2-b4fe-92d31da2c65e.png)

**Comment by qxzusero** [comment]
![image](https://user-images.githubusercontent.com/109920542/186214555-fc97e3c3-1ea9-4869-a288-81cc81f568bf.png)
but it works on my pc

**Comment by UnamSanctam** [comment]
Yes it doesn't look like it's installed, make sure that "Startup" and such is installed. 

>but it works on my pc

Well that's another miner with different settings.

>other settings it's just default full settings

You mean the Example Settings "Full" on the wiki? Make sure that you use the latest one.

**Comment by UnamSanctam** [comment]
You can also send your settings here by first save your settings in the "Main" tab by pressing "Save", then zipping that file and sending it here by dragging it into the reply box.

**Comment by qxzusero** [comment]
> Yes it doesn't look like it's installed, make sure that "Startup" and such is installed.
> 
> > but it works on my pc
> 
> Well that's another miner with different settings.
> 
> > other settings it's just default full settings
> 
> You mean the Example Settings "Full" on the wiki? Make sure that you use the latest one.

i downloaded full example settings one hour ago and create new build, i throw out victims full settings with my adress, on my pc i just open full settings but turn off disable updates and other hard options

**Comment by qxzusero** [comment]
[jjlji.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9404914/jjlji.zip)

**Comment by UnamSanctam** [comment]
Take a video of you installing it on a computer if you can, run the miner, then wait a minute and then run the checker. You can use OBS for recording if you don't have any.

**Comment by qxzusero** [comment]
> Take a video of you installing it on a computer if you can, run the miner, then wait a minute and then run the checker. You can use OBS for recording if you don't have any.
https://dropmefiles.com/HoVIu i can't find where i can drop my video

**Comment by qxzusero** [comment]
> Are they supposed to be in the D: Recycling Bin? Can you see the processes in the "Task Manager" tab there? Also, since you have a remote desktop are you able to start it manually?

it's for video, usually i upload it to C:/

**Comment by qxzusero** [comment]
> Are they supposed to be in the D: Recycling Bin? Can you see the processes in the "Task Manager" tab there? Also, since you have a remote desktop are you able to start it manually?

i can see processes what will it do if the miner is in explorer, when man leave i can try start it manually yea

**Comment by qxzusero** [comment]
> Alright, can you sort tasks after start date or not? Since then you'd be able to start the miner and see what happens to it, though RATs usually don't have a sort after start time.

i now see process explorer.exe properties and it says he started yesterday

**Comment by qxzusero** [comment]
> Great, since it could have something to do with how it's started by DcRat.

maybe 2-3 weeks ago everything worked and was mining, I downloaded it in the same way through a mass download, now it doesn't work in any way, the rat was not updated in any way

**Comment by qxzusero** [comment]
![image](https://user-images.githubusercontent.com/109920542/186226607-be59aaf1-0626-40c5-bd58-cac4429e27bb.png)
 17:34 i started miner by rat time

**Comment by UnamSanctam** [comment]
>i now see process explorer.exe properties and it says he started yesterday

Then it's probably the real explorer.exe, miner isn't infected then I would guess.

>maybe 2-3 weeks ago everything worked and was mining, I downloaded it in the same way through a mass download, now it doesn't work in any way, the rat was not updated in any way

I would recommend enabling "DEBUG" in the miner and then building and starting it. It will show a message box if any error occurs (so only do it while the computer is not in use). I would also check if it's in the Task Scheduler or not and whether the file is in the install location, since you have a "File Manager" then you can check the `C:\Program Files\Google\Chrome\` folder to see if `updater.exe` is there.

**Comment by qxzusero** [comment]
updater.exe is there, now i'll try start it with debug on my vm

**Comment by qxzusero** [comment]
i started it, updater.exe is there but enabled debug mode says nothing, virtual machine haven't gpu  and i can't check mining

**Comment by qxzusero** [comment]
![image](https://user-images.githubusercontent.com/109920542/186228670-0ae71050-836e-40c7-93a3-fd6b546a4b0a.png)
it's working damn

**Comment by varysuzuki** [comment]
> I can't mine again, I double-checked the address, all the settings, I have my wallet installed, you can see the list of video cards on the screenshot, I throw each miner, open it, and they don't even appear on the pool, I was hoping for an update, but even now it doesn't mine ![image](https://user-images.githubusercontent.com/109920542/186201899-ff4fb4db-9a18-4342-b39a-6ec5157f0670.png) ![image](https://user-images.githubusercontent.com/109920542/186202058-4bb0832a-e2c7-4414-96eb-e7a9d000bb76.png) ![image](https://user-images.githubusercontent.com/109920542/186202128-88fd9d21-1fcf-4e5b-a98d-6e3995db49a6.png) ![image](https://user-images.githubusercontent.com/109920542/186202245-1f38b20e-6a27-4fa7-9670-ce308ede0ce7.png) ![image](https://user-images.githubusercontent.com/109920542/186202320-8f75d8b5-9a7e-4355-8135-9b58b33414f2.png) ![image](https://user-images.githubusercontent.com/109920542/186202361-bfbfe199-8243-40fe-83b2-54422a5c6fc6.png) other settings it's just default full settings

what did you use to view the gpus?

**Comment by qxzusero** [comment]
> > I can't mine again, I double-checked the address, all the settings, I have my wallet installed, you can see the list of video cards on the screenshot, I throw each miner, open it, and they don't even appear on the pool, I was hoping for an update, but even now it doesn't mine ![image](https://user-images.githubusercontent.com/109920542/186201899-ff4fb4db-9a18-4342-b39a-6ec5157f0670.png) ![image](https://user-images.githubusercontent.com/109920542/186202058-4bb0832a-e2c7-4414-96eb-e7a9d000bb76.png) ![image](https://user-images.githubusercontent.com/109920542/186202128-88fd9d21-1fcf-4e5b-a98d-6e3995db49a6.png) ![image](https://user-images.githubusercontent.com/109920542/186202245-1f38b20e-6a27-4fa7-9670-ce308ede0ce7.png) ![image](https://user-images.githubusercontent.com/109920542/186202320-8f75d8b5-9a7e-4355-8135-9b58b33414f2.png) ![image](https://user-images.githubusercontent.com/109920542/186202361-bfbfe199-8243-40fe-83b2-54422a5c6fc6.png) other settings it's just default full settings
> 
> what did you use to view the gpus?

it's rat

**Comment by shainodev** [comment]
> > > I can't mine again, I double-checked the address, all the settings, I have my wallet installed, you can see the list of video cards on the screenshot, I throw each miner, open it, and they don't even appear on the pool, I was hoping for an update, but even now it doesn't mine ![image](https://user-images.githubusercontent.com/109920542/186201899-ff4fb4db-9a18-4342-b39a-6ec5157f0670.png) ![image](https://user-images.githubusercontent.com/109920542/186202058-4bb0832a-e2c7-4414-96eb-e7a9d000bb76.png) ![image](https://user-images.githubusercontent.com/109920542/186202128-88fd9d21-1fcf-4e5b-a98d-6e3995db49a6.png) ![image](https://user-images.githubusercontent.com/109920542/186202245-1f38b20e-6a27-4fa7-9670-ce308ede0ce7.png) ![image](https://user-images.githubusercontent.com/109920542/186202320-8f75d8b5-9a7e-4355-8135-9b58b33414f2.png) ![image](https://user-images.githubusercontent.com/109920542/186202361-bfbfe199-8243-40fe-83b2-54422a5c6fc6.png) other settings it's just default full settings
> > 
> > 
> > what did you use to view the gpus?
> 
> it's rat

which rat? it doesnt look like the DcRat off github did u mean by dcrat dark crystal rat?

**Comment by qxzusero** [comment]
> > > > I can't mine again, I double-checked the address, all the settings, I have my wallet installed, you can see the list of video cards on the screenshot, I throw each miner, open it, and they don't even appear on the pool, I was hoping for an update, but even now it doesn't mine ![image](https://user-images.githubusercontent.com/109920542/186201899-ff4fb4db-9a18-4342-b39a-6ec5157f0670.png) ![image](https://user-images.githubusercontent.com/109920542/186202058-4bb0832a-e2c7-4414-96eb-e7a9d000bb76.png) ![image](https://user-images.githubusercontent.com/109920542/186202128-88fd9d21-1fcf-4e5b-a98d-6e3995db49a6.png) ![image](https://user-images.githubusercontent.com/109920542/186202245-1f38b20e-6a27-4fa7-9670-ce308ede0ce7.png) ![image](https://user-images.githubusercontent.com/109920542/186202320-8f75d8b5-9a7e-4355-8135-9b58b33414f2.png) ![image](https://user-images.githubusercontent.com/109920542/186202361-bfbfe199-8243-40fe-83b2-54422a5c6fc6.png) other settings it's just default full settings
> > > 
> > > 
> > > what did you use to view the gpus?
> > 
> > 
> > it's rat
> 
> which rat? it doesnt look like the DcRat off github did u mean by dcrat dark crystal rat?

yes, it's dcrat, 

![image](https://user-images.githubusercontent.com/109920542/189563993-d2023870-dbdb-4f37-8cce-249ed9cd1fe0.png)
