### ISSUE TITLE
Miner isn't working

### ISSUE THREAD

**Issue by bober100** [UnamSanctam/SilentCryptoMiner#1067]
I can't mine cryptocurrency. The wallet is specified correctly, the port is also specified correctly. I send the miner to the victim with the antivirus turned off, but even after an hour nothing happens. On 2 miners, he writes that the last share was 7 days ago. What could be the problem?

**Comment by UnamSanctam** [comment]
What GPU does he have? And what settings do you have?

**Comment by bober100** [comment]
> 

At the moment I do not have access to a PC to view the settings, I am writing from my phone. My settings are the same as my friend's except for the wallet address, which has the same problem. He has the nickname qxzusero, he has already asked a question about this problem. GPU nvidia gtx 1060 6GB

**Comment by bober100** [comment]
> Какой у него GPU? А какие у вас настройки?

Can you help me?

**Comment by UnamSanctam** [comment]
You'll need to run the checker on the computer that it's not working on to see if it's installed and running. And if not then you should build a miner with "DEBUG" enabled inside "Advanced Options" and run that to see if you get any error messages.

**Comment by bober100** [comment]
> 

things got even worse. I can't open miner on the victim's PC. I use dcrat and when the miner is openethings got even worse. I can't open it at all on the victim's PC. I use dcrat and when the miner is opened, the message appears the operation cannot be completed because the program contains a virus or other unwanted soft. Тhe new build doesn't help

**Comment by UnamSanctam** [comment]
Take a screenshot and show it.

**Comment by bober100** [comment]
> Take a screenshot and show it.

will a screenshot help in any way? This message appears in Dcrat and not in miner

**Comment by UnamSanctam** [comment]
Probably not then, though there isn't really anything I can do about that if it appears inside DcRat.

**Comment by bober100** [comment]
what about obfuscation?  Will it help?

**Comment by UnamSanctam** [comment]
Depends on what reason it shows that for, since it's in DcRat. You can turn off "Do built-in obfuscations" in the miner (inside "Advanced Options") and then try to obfuscate it in some obfuscator and see what happens when you try to use that one.

**Comment by bober100** [comment]
> Зависит от того, по какой причине он это показывает, так как он находится в DcRat. Вы можете отключить «Выполнять встроенные обфускации» в майнере (внутри «Дополнительных параметров»), а затем попытаться запутать его в каком-нибудь обфускаторе и посмотреть, что произойдет, когда вы попытаетесь использовать его.

the error still appears. By the way, the build that my friend made with my wallet runs normally without detecting a virus. But the share is not sent to pool 2miners and monero.hashvault

**Comment by UnamSanctam** [comment]
You'll have to take a screenshot and show it then, I can't really know how your DcRat works internally. To appear in the pool has to find a share first, what hashrate are you mining at and for how long? Also make sure that you don't have the Task Manager open or anything while you have "Stealth" enabled. You can set up a local webpanel to get information from the miner https://github.com/UnamSanctam/UnamWebPanel#for-local-testing.
