### ISSUE TITLE
Does 2miners share take so long?

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#1070]
So i switched pools and I have a miner i am testing the pool on its mining at 35mhs idle and has been mining for 5 - 10 hours but there hasn't been a share or any mining shown in the pool.

Is this normal or do i have to wait more til i get a share?

**Comment by Brainshot** [comment]
Btw I have the miner on webpanel so I can see the mining and everything, but nothing on 2miners pool.

**Comment by UnamSanctam** [comment]
Are you sure that it's mining continuously? I mean that if you check constantly over an hour does it always mine?

**Comment by Brainshot** [comment]
> Are you sure that it's mining continuously? I mean that if you check constantly over an hour does it always mine?

Yes its idle and mining online and hashrate is at 35mhs. Maybe its the pool issue and i have to wait a bit more??

**Comment by Brainshot** [comment]
![Captugwre](https://user-images.githubusercontent.com/93741208/186273922-fcf104f4-526c-4e89-816b-3afbfc22ffb6.PNG)

Here is a image

**Comment by UnamSanctam** [comment]
Your algorithm is wrong, it's set to `ethash`.

**Comment by Brainshot** [comment]
> Your algorithm is wrong, it's set to `ethash`.

Okay thanks got it, is there anyway i can change it in the webpanel?

**Comment by UnamSanctam** [comment]
You can change it through "Configurations" and then apply the configuration to that miner, or change the "Default ethminer" to change all of them.

**Comment by Brainshot** [comment]
> You can change it through "Configurations" and then apply the configuration to that miner, or change the "Default ethminer" to change all of them.

Do you have code for that?

The reason it was set to ethash was because i used a save and for some reason it wasn't changed to etchash

**Comment by UnamSanctam** [comment]
You can create a miner in the builder, then go to the "JSON" tab and use that.

**Comment by Brainshot** [comment]
> You can create a miner in the builder, then go to the "JSON" tab and use that.

Ok thank you so much for help!
