### ISSUE TITLE
rvn configuration example

### ISSUE THREAD

**Issue by mazafakaDZ** [UnamSanctam/SilentCryptoMiner#1074]
hi uname
can you provide me with worked json file for mining rvn 
cuz i try normale configuration 
but ist fail
the bot connect to the panel and say that is active but there is no hashrat 
the hashrat is 0
i try it on many machine and the probleme stay the same
i think my configuration is wrong
can you attach xml configuratin or json files for rvn example 
i use 2miners.com
i try many solution but all of them fail
thank you

**Comment by UnamSanctam** [comment]
Sure, here's a working Ravencoin (KawPow) example for the builder using 2miners: [RVN.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9420670/RVN.zip). 

Also, KawPow doesn't always work, or at least not a single KawPow miner that exists works on my computer for some reason (so it's not just xmrig).
