### ISSUE TITLE
Lates version is not working [ETC]

### ISSUE THREAD

**Issue by GhostwareC** [UnamSanctam/SilentCryptoMiner#1075]
Hello, Unam!

After last update new worker just no appear in my pool. 2.5.0 worked good, without any problems. But I still can't set up 2.6.1.
Can you please help me?

Im using 2miners ETC.

**Comment by UnamSanctam** [comment]
Run your checker and post it here, or take a screenshot of your web panel if you're using one.

**Comment by malcikin** [comment]
![asdasd](https://user-images.githubusercontent.com/108231577/186788400-a4789300-cacd-481e-91d9-a44074c999f4.PNG)
what is the problem here?

**Comment by UnamSanctam** [comment]
Not enough free VRAM to mine. I also recommend to update it to 2.6.1 if you can.

**Comment by malcikin** [comment]
im using 2.6.1 already. at least 3gb gpu is not required?
i think 3050 ti is enough for etc mining

**Comment by UnamSanctam** [comment]
>im using 2.6.1 already. at least 3gb gpu is not required?
i think 3050 ti is enough for etc mining

You sure? It says 2.6.0. 

The 3050 Ti Laptop has enough total VRAM to mine ETC (it has 4GB I believe), doesn't mean that it has enough free VRAM though

**Comment by malcikin** [comment]
> 

i updated 2.6.1 its old ss

**Comment by malcikin** [comment]
![image](https://user-images.githubusercontent.com/108231577/186790264-a903d73e-046a-4648-938b-985409713868.png)
and i need help this. It says full screen even though it's not full screen

**Comment by UnamSanctam** [comment]
>i updated 2.6.1 its old ss

Alright, since that GPU has 4GB of VRAM and it needs 3GB of free VRAM then most likely it's currently using more than 1GB of VRAM, or it's disabled at the moment because of Nvidia optimus.

>and i need help this. It says full screen even though it's not full screen

If it says than then an application is currently in "Fullscreen", you can read more of what that means here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#pause-on-fullscreen.
