### ISSUE TITLE
Windows Defender detection

### ISSUE THREAD

**Issue by Zeevsq1** [UnamSanctam/SilentCryptoMiner#1084]
Windows Defender detection
An exception has been added, but the species is still removed and does not allow the miner to start. Latest version
![Annotation 2022-08-30 164432](https://user-images.githubusercontent.com/101643042/187392917-a676e68d-ed04-4b51-a9d9-9565e58beea0.png)

**Comment by Zeevsq1** [comment]
detected after reboot and removed

**Comment by UnamSanctam** [comment]
Haven't seen that before, though it doesn't really look like it's from the miner. Do you have "Run as System" disabled? Are you using a binder or something?

**Comment by Zeevsq1** [comment]
Run as System" disabled - yes
using a binder - no

**Comment by UnamSanctam** [comment]
Hmm, guess I'll have to wait until Microsoft serves me the new update naturally then to see.

**Comment by Zeevsq1** [comment]
to give you a dedicated server with an installed update to check?

**Comment by UnamSanctam** [comment]
I'm trying to update one of my test VMs to see, haven't gotten the definition update yet though.

**Comment by masterjek** [comment]
I just checked on my computer where installed the latest version Windows Defender with new databases and the miner does not detect me. After installation, I rebooted the computer 3 times and there is no detection.
