### ISSUE TITLE
Win 32 

### ISSUE THREAD

**Issue by Danny-K02** [UnamSanctam/SilentCryptoMiner#1087]
Can i do something to launch it on windows xp/7/8 32 bit?

**Comment by UnamSanctam** [comment]
No the miners are made for 64-bit.

**Comment by Danny-K02** [comment]
Noway?...

**Comment by UnamSanctam** [comment]
Yes the miner (xmrig and ethminer) aren't compiled for 32-bit and the process hollowing is currently only designed for 64-bit. And then other parts are also designed for 64-bit.

**Comment by Danny-K02** [comment]
Thank you

**Comment by CarlosLoboxyz** [comment]
@UnamSanctam I was looking for a way to deploy the binary in a windows 7 32bits, i've found that you can actually compile and run xmrig on x86 architecture [see here](https://github.com/xmrig/xmrig/issues/1062). How can one go about modifying the compile flags to make it run on x86?

**Comment by UnamSanctam** [comment]
You can't in this project, but that PR is from 2019 anyways, and ethminer would also need to be compiled with 32-bit. Then you would also need to change the injector to 32-bit as well. And you would maybe also need to introduce pathing support between the two.
