### ISSUE TITLE
files in source

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/SilentCryptoMiner#1088]
question regarding obfuscation/encryption of files in source code

what can be touched and what can not?
Well, the miners themselves understand this, but what about the other files?

**Comment by UnamSanctam** [comment]
You mean the resources? You can touch (obfuscate or anything else) any of them, just make sure they work after.

**Comment by anbu-squad** [comment]
yes in resources
I just don't know if you can touch the dll?

**Comment by UnamSanctam** [comment]
Yes you can obfuscate DllLoader.dll, the other two are native files but they shouldn't really need anything to be done.

**Comment by anbu-squad** [comment]
that is, the other two dlls do not need to be encrypted?

by the way, another question

after obfuscation / encryption of resources in the builder, do you also need to gradually encrypt the build?

**Comment by UnamSanctam** [comment]
>that is, the other two dlls do not need to be encrypted?
by the way, another question
after obfuscation / encryption of resources in the builder, do you also need to gradually encrypt the build?

Yes they shouldn't be needed to, what do you mean with "do you also need to gradually encrypt the build"? Do you mean if you "have" to encrypt the final built file? Then yes that would be good.

**Comment by anbu-squad** [comment]
clear, so first we work with resource files
namely:
- xmrig
- ethminer
- DllLoader.dll
- rootkit-i (of necessity)

then turn on the pause for obfuscation and crypt build


Am I missing anything in resources?

  sorry for my english
this is probably a translation error

**Comment by UnamSanctam** [comment]
No those are all, you can also crypt the other two .dll files if you have a good program for it (since you're doing it on xmrig, ethminer and rootkit-i).
