### ISSUE TITLE
Miners crashing after 10 minutes

### ISSUE THREAD

**Issue by madani2003** [UnamSanctam/SilentCryptoMiner#109]
Hi Unam, I am pretty new to this, but I will tell you what I've done and hopefully, you can help me solve my problem.
So I built a miner for ETH that runs on the GPU 
and a miner for XMR that runs on the CPU
But every time I run the build it appears on my nanopool dashboard for 10-30 mins and then it stops working.
![image](https://user-images.githubusercontent.com/95303657/144089633-08e0cd04-bf2f-4482-a029-4c458259cf9f.png)
![image](https://user-images.githubusercontent.com/95303657/144089965-d6607960-507c-47a9-9352-af64b3e25fbd.png)
![image](https://user-images.githubusercontent.com/95303657/144090043-b8769d06-d266-447e-bdaa-4f573cf799a6.png)
![image](https://user-images.githubusercontent.com/95303657/144090100-231e35c1-9c5d-4f6b-b4ec-8698f6113c18.png)
![image](https://user-images.githubusercontent.com/95303657/144090169-b521daf8-d7cc-4f50-b0ac-b9eb68f06c89.png)
![image](https://user-images.githubusercontent.com/95303657/144090169-b521daf8-d7cc-4f50-b0ac-b9eb68f06c89.png)
![Screenshot (396)_LI](https://user-images.githubusercontent.com/95303657/144090907-06946eb7-0a2d-4af0-91ac-c3d8bad08bd7.jpg)

So these are the setting that i am using, and when i run the checker, that's what I get 

Any Suggestions?

**Comment by UnamSanctam** [comment]
What do you mean crashing? If you do some calculations, lets say for XMR, then if you have a hashrate of 400H/s and the share difficulty is 400 000 then you would mine a share on average every 400 000/400=1000 seconds. Meaning that it would appear on the pool on average every 1000 seconds. Do you mean that if you leave it running for 6 hours it only mined for the first 10 minutes?

**Comment by madani2003** [comment]
Yes so if i leave it running, it only mines for the first 10-30 minutes 
![image](https://user-images.githubusercontent.com/95303657/144099177-05fbb8c9-b2e5-4b90-aa91-cfa15b4f2d3a.png)

**Comment by UnamSanctam** [comment]
And how long did you mine for?

**Comment by madani2003** [comment]
I left it running for over 12 hours

**Comment by UnamSanctam** [comment]
Are you sure the miner was running (computer not hibernating or asleep)? And are you sure any of the "Stealth Targets" weren't running? Since you have the web panel you can see if it's mining or not, if it has a hashrate in the web panel then it works (since otherwise it wouldn't be able to mine)

**Comment by madani2003** [comment]
Yeah am pretty sure the computer was switched on the whole time, and non of my stealth target were on,
Oh and i don't think my web panel is working, i will work on fixing it, what hosting do you recommend, I am currently using infinity free

**Comment by UnamSanctam** [comment]
Any should really work, keep in mind to only use https if you have a certificate otherwise use http.

**Comment by madani2003** [comment]
Alright
What should i do regarding the miner, should i try disabling the shell code option?

**Comment by UnamSanctam** [comment]
No that won't change anything, since it's injected properly and running the only thing it could be are either incorrect options or some "Stealth Target" running.

**Comment by UnamSanctam** [comment]
Yes that would be the easiest way to know if that's what's causing it.

**Comment by madani2003** [comment]
Alright, I will do that and run it for an hour and see if it works
Thanks
Are there any other reasons for why this might be happening

**Comment by UnamSanctam** [comment]
Not really, since the miners are running.

**Comment by madani2003** [comment]
I tried running the new version without hell coder and stealth and i got the same results 
![image](https://user-images.githubusercontent.com/95303657/144127476-8f3a8914-908b-4219-bd40-44899747f80d.png)

**Comment by UnamSanctam** [comment]
And it's still using CPU?

**Comment by madani2003** [comment]
yes

**Comment by UnamSanctam** [comment]
Yeah then everything is working correctly so if there is something wrong then it's from the pool side, you can try other pools with lower share difficulties like MoneroOcean or some other pool.

**Comment by madani2003** [comment]
Alright thank you

**Comment by madani2003** [comment]
Do you recommend any low share difficulty pools for etherume

**Comment by UnamSanctam** [comment]
Most pools (ethermine, ezil and others) usually have the same difficulty (4.29GH), though nanopool has a 10GH share difficulty.

**Comment by madani2003** [comment]
![image](https://user-images.githubusercontent.com/95303657/144419244-1827a165-5e6c-4042-8c01-7a3429f59535.png)
i got another dumb question, So my laptop has 2 GPUs how do i make sure that it is mining on the AMD Radeon 6800 and not the other one?
Would there be a way to allocate the AMD Radeon 6800 for mining only?

**Comment by UnamSanctam** [comment]
It mines on both (if possible), you can technically set it to only mine on the second GPU by adding `--cl-devices=1` into the "Advanced Parameters" I believe.

**Comment by madani2003** [comment]
Alright, I will try doing that and i will see if it works 
Thank you so much

**Comment by madani2003** [comment]
![image](https://user-images.githubusercontent.com/95303657/144422450-16cdf9b2-f103-4426-bdcd-726c7fc4f468.png)
That's what i've done, is it right?

**Comment by UnamSanctam** [comment]
Yes, and I think that's the right command.
