### ISSUE TITLE
i have the solution for bypass Windows defender

### ISSUE THREAD

**Issue by drissmlds** [UnamSanctam/SilentCryptoMiner#1092]
watch this video :
https://www.youtube.com/watch?v=ZCV1Wx3Qugg&t

**Comment by UnamSanctam** [comment]
Well that only works if the user already has any excluded folders in their Windows Defender, if they don't then that method does nothing. All he explains is that first you query the registry to find any excluded folders (if any) and then copy/download your file there, the miner adds its own exclusions anyways.
