### ISSUE TITLE
question on miner version v2.6.0

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#1094]
As you say on the release note [v2.6.0](https://github.com/UnamSanctam/SilentCryptoMiner/releases/tag/scm-v2.6.0) of your miner release, it have a bypasses for new windows defender exclusion detection. Does these mean windows defender removes miners that uses miner version [v2.4.1](https://github.com/UnamSanctam/SilentCryptoMiner/releases/tag/scm-v2.4.1) even if the miner buildes with disable windows update?

Tnx

**Comment by UnamSanctam** [comment]
Yes probably, though it's very possible that it won't as well.

**Comment by DerXanRam** [comment]
> Yes probably, though it's very possible that it won't as well.

Sorry bro...can u explain in simple England ?
Tnx

**Comment by UnamSanctam** [comment]
Yes they will probably get detected, but there is also a chance that the older version has enough difference compared to newer ones that it might avoid the new detection in case it targets a newer version of a script.

**Comment by DerXanRam** [comment]
> Yes they will probably get detected, but there is also a chance that the older version has enough difference compared to newer ones that it might avoid the new detection in case it targets a newer version of a script.

Ok bro. Tnx
