### ISSUE TITLE
Quick question. 

### ISSUE THREAD

**Issue by thatboytonio33** [UnamSanctam/SilentCryptoMiner#110]
I have added a XMR miner and an ETH miner. Is it ok for both of them to inject into explorer.exe, or should they inject into different ones. Also, what is the next project that you are working on. Your work is great. Thankyou.

**Comment by UnamSanctam** [comment]
Injecting them both into the same process is fine, currently I'm focusing updating the miner and the web panel.

**Comment by thatboytonio33** [comment]
Also, is there a way to prevent the pop up that says windows does not recognize the publisher of the app?

**Comment by UnamSanctam** [comment]
No, you would have to have to sign it (pay Microsoft money) or have to try and steal another programs signature (difficult to do).
