### ISSUE TITLE
Etherium Dead Add Scrypt Algorithm Please

### ISSUE THREAD

**Issue by SieraMondorez** [UnamSanctam/SilentCryptoMiner#1100]
it would be epic if u can add Scrypt Algorithm aka LTC Since etherium mining is dead now and Scrypt aka ltc is a really good alternative

**Comment by UnamSanctam** [comment]
You don't mine the Scrypt algorithm with normal computers, you use ASIC miners for that. And most here don't mine Ethereum anyways but instead Ethereum Classic.
