### ISSUE TITLE
update

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#1104]
when will you release new update ?

**Comment by malcikin** [comment]
UNAM UPDATE THIS PROGRAM MEEN PLSS

**Comment by DogusCyk** [comment]
sat ap he is busi

**Comment by UnamSanctam** [comment]
I also said it in the other post but I'll write it here too, right now I'm testing different ways to do the "Startup" procedure with the least amount of detections (such as reading and writing the file or copying it by different commands, adding Tasks before or after copying, sleeping between calls and other things). Then after that I will finish the watchdog (which isn't very difficult), and after that I have to try different methods of embedding the different files that the miner will use.

**Comment by DogusCyk** [comment]
So how long will it take you to do these?

**Comment by DogusCyk** [comment]
(approximately)

**Comment by UnamSanctam** [comment]
Not sure, depends on how much they detect, the majority of everything is done though, should at most be a few days.
