### ISSUE TITLE
System

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1107]
I have a problem, my rat has System privileges on all clients so i cant keylog nor remote desktop. i also cant NOT use the /ru System on my downloader cause when i try running the downloader on their pc without /ru System then it just does not work. do you have any fix to this?

**Comment by shainodev** [comment]
i also tried using powershell to run it but it still runs it as system so it cant do it

**Comment by UnamSanctam** [comment]
Since you're running it on the System user then even if you don't use "/ru System" then it will install (or run) as System because that's your current user. You could enter whatever username they have into "/ru USERNAME" to make it install under their user.

**Comment by varysuzuki** [comment]
> Since you're running it on the System user then even if you don't use "/ru System" then it will install (or run) as System because that's your current user. You could enter whatever username they have into "/ru USERNAME" to make it install under their user.

nono it will give me some sort of error when i try to create it without user and its hard to manually find each and every ones username

**Comment by varysuzuki** [comment]
also how much more will the downloader and miner take?

**Comment by UnamSanctam** [comment]
A few days more probably, it's a bit hard to know exactly since it's a complete rewrite.

**Comment by varysuzuki** [comment]
> A few days more probably, it's a bit hard to know exactly since it's a complete rewrite.

would you say if i manage to make the program self-morphing would it be undetected? and is it even worth it
