### ISSUE TITLE
miners tasks and registry keys are getting detected by malwarebytes

### ISSUE THREAD

**Issue by Azzerzz** [UnamSanctam/SilentCryptoMiner#111]
im running the miner right now and when i ran malwarebytes it detects all the tasks and services used by the miner
i have exclude for windows defender on also
do i need to enable process killer for malwarebytes if it detects all the services? because if somoene finds them and removes them the miner wont work anymore?

**Comment by JayCrax** [comment]
Oh no! How we pity you! Pwease someone get @Azzerzz some help! He knows how to do a 'Hello World' in Python. He's worth it!

**Comment by JayCrax** [comment]
You're literally using open-source malware and asking why Malwarebytes is detecting it... Reflect on your actions.

**Comment by Azzerzz** [comment]
> You're literally using open-source malware and asking why Malwarebytes is detecting it... Reflect on your actions.

im wondering why its getting detected because i enabled rootkit you dumbfuck   a "RootKit" is supposed to hide the processes and info, and malwarebytes doesnt detect rootkits unless you enable that which i did not
arrogant fuck
