### ISSUE TITLE
when update?

### ISSUE THREAD

**Issue by malcikin** [UnamSanctam/SilentCryptoMiner#1110]
when will you release new update

**Comment by UnamSanctam** [comment]
In a few days, I don't want to rush it too much and release it with bugs.

**Comment by DogusCyk** [comment]
> when will you release new update

![image](https://user-images.githubusercontent.com/81167210/188513919-51b0e6ea-d65d-40e2-b1fe-e15b4b5df75a.png)

**Comment by malcikin** [comment]
> In a few days, I don't want to rush it too much and release it with bugs.

my friend you say always few days few days 🙄🙄

**Comment by UnamSanctam** [comment]
>my friend you say always few days few days 🙄🙄

Well yeah, it hasn't been a few days yet, it's quite an ambiguous amount and even then it's hard to know exactly how long it will take. Why don't you tell me exactly how long it would take you to remake the miner and watchdog in C++?

**Comment by malcikin** [comment]
alrighttt 😏😏 you are king unam i love you man i can wait a few days for you <3
