### ISSUE TITLE
Enabling CPU + GPU In RVN Possible?

### ISSUE THREAD

**Issue by SieraMondorez** [UnamSanctam/SilentCryptoMiner#1111]
Uhm so  i configured my miner as here but i readed in a post says if u wana mine gpu u should turn of cpu .d cant i enable them to make a good profit i saw in a pool site raven is most profitable by 100 mhs and gives u 4.5 usd a day better then etherium! heres how i configured can i earn more if i also enable cpu? or how it works

![image](https://user-images.githubusercontent.com/92208108/188502657-2d782686-53b0-4401-9619-8fac2cf784cf.png)

**Comment by UnamSanctam** [comment]
You can't mine Ravencoin with the CPU in the miner and it wouldn't be profitable at all either to do so. Right now Ravencoin is pretty profitable but I think you're misunderstanding how it works. Ravencoin uses the KawPow algorithm and Ethereum uses the ethash algorithm, this means that comparing hashrates between the two isn't really possible, 100 MH/s on Ravencoin is not the same as 100 MH/s on Ethereum. Right now an RTX 3070 gets around 60 MH/s when mining ethash (Ethereum) and around 27 MH/s when mining KawPow (Ravencoin).

**Comment by SieraMondorez** [comment]
> You can't mine Ravencoin with the CPU in the miner and it wouldn't be profitable at all either to do so. Right now Ravencoin is pretty profitable but I think you're misunderstanding how it works. Ravencoin uses the KawPow algorithm and Ethereum uses the ethash algorithm, this means that comparing hashrates between the two isn't really possible, 100 MH/s on Ravencoin is not the same as 100 MH/s on Ethereum. Right now an RTX 3070 gets around 60 MH/s when mining ethash (Ethereum) and around 27 MH/s when mining KawPow (Ravencoin).

thanks for answer so ill keep the config shown in ss aka disabling the cpu seems like raven is good u recomend any better once to mine? eth will be dead soon

**Comment by UnamSanctam** [comment]
Yes you can keep the configuration like that, most silent miners mine ETC and not ETH since it has less requirements and also won't move to PoS.
