### ISSUE TITLE
startup tab question

### ISSUE THREAD

**Issue by parabola20** [UnamSanctam/SilentCryptoMiner#1118]
hello, an update is out, I'm re-creating all the miners. I'm interested in the "Run as System" function, which changes the path to program files. what does it give? preferentially turn it on or off? I didn't pay attention to it before

**Comment by UnamSanctam** [comment]
It makes it so that the miner can run on all users and not just the user that started the miner.

**Comment by parabola20** [comment]
> It makes it so that the miner can run on all users and not just the user that started the miner.

but which path is better and will live longer?

**Comment by UnamSanctam** [comment]
I would say running it as System would be better since it can run on the System user and can start when the computer starts.

**Comment by parabola20** [comment]
> I would say running it as System would be better since it can run on the System user and can start when the computer starts.

ok. ty
