### ISSUE TITLE
obfuscations

### ISSUE THREAD

**Issue by drissmlds** [UnamSanctam/SilentCryptoMiner#1119]
hi thank you for this update
but i have question why you remove Do built-in obfuscations in this update

**Comment by UnamSanctam** [comment]
Because the miner is now made in C++ so you can't obfuscate it

**Comment by Pedrolito666** [comment]
So we need to crypt the miner itself with pause ?

**Comment by UnamSanctam** [comment]
Yes though it's not really needed right now since it's undetected by like 95% of antiviruses.

**Comment by drissmlds** [comment]
> So we need to crypt the miner itself with pause ?

what is pause Crypt ?

**Comment by Pedrolito666** [comment]
Pause for obfuscation*

**Comment by Pedrolito666** [comment]
Unam do you think it will be detected soon ?

**Comment by UnamSanctam** [comment]
No idea, since it's completely new I don't really have any previous data on it.
