### ISSUE TITLE
miner not working

### ISSUE THREAD

**Issue by parabola20** [UnamSanctam/SilentCryptoMiner#1120]
hi again. I try to run the updated miner, the "Updater.exe" is created, the watchdog is launched in the checker, but the mining does not work. the old miner worked with approximately the same settings, except for changes in the names of the folders in the startup, remote configuration, svchost to conhost.

could you check my settings please?
https://drive.google.com/u/0/uc?id=103JKHkp5zrSt0lC1OjkPf5sNffRnuhPS&export=download

![photo_2022-09-07_14-40-44](https://user-images.githubusercontent.com/94918344/188858765-7cb7ec70-c8e8-40de-9063-2855b78059d2.jpg)

**Comment by DogusCyk** [comment]
yes, I was going to ask this question now, mining does not work as etc.

**Comment by UnamSanctam** [comment]
You have a pastebin link as the worker name, are you sure that works? Also try rebuilding it. otherwise maybe it isn't finding your GPU, can you check Process Hacker to see if the injected process is there?

**Comment by UnamSanctam** [comment]
@parabola20 Can you run this and post what it says: [ListGPU.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9505511/ListGPU.zip)?

**Comment by parabola20** [comment]
> @parabola20 Can you run this and post what it says: [ListGPU.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9505511/ListGPU.zip)?

I made a mistake in the title, fixed it, still doesn't work...
also ran your file: 
![photo_2022-09-07_15-08-17](https://user-images.githubusercontent.com/94918344/188864275-9052060b-dd39-48e3-9ea3-c31b7607f7d4.jpg)

**Comment by UnamSanctam** [comment]
Yeah then it should be detecting your GPU in the miner, could be something else with AMD. Can you try running this [AMDTest.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9505654/AMDTest.zip) to see if you can mine with the ethminer at all? Start the "start etc.bat" file and then check MSI afterburner if it's mining.

**Comment by parabola20** [comment]
> Yeah then it should be detecting your GPU in the miner, could be something else with AMD. Can you try running this [AMDTest.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9505654/AMDTest.zip) to see if you can mine with the ethminer at all? Start the "start etc.bat" file and then check MSI afterburner if it's mining.

I always tested etc on this pc, there were no problems. stopped working with the new update

start etc.bat:
![photo_2022-09-07_15-31-03](https://user-images.githubusercontent.com/94918344/188868415-1a1fbb67-0d7e-48e4-a1ef-781e05022291.jpg)

**Comment by UnamSanctam** [comment]
Hmm weird, it's working on the 3 computers I've tested. Does it work if you disable "Startup"? In case it's something weird with the System user or something.

**Comment by parabola20** [comment]
> Hmm weird, it's working on the 3 computers I've tested. Does it work if you disable "Startup"? In case it's something weird with the System user or something.

I just changed the startup folder to AppData (turned off the Run as System) and it worked

**Comment by UnamSanctam** [comment]
So maybe it's because of the System user on some computers, maybe it can't create the D3D9 devices.

**Comment by parabola20** [comment]
> So maybe it's because of the System user on some computers, maybe it can't create the D3D9 devices.

hi Unam, just created miner version 3.0.2 with my default settings, does not work, although 3.0.1 works with the same settings. tested on radeon r9 380

**Comment by UnamSanctam** [comment]
You mean that your XMR miner works but not your ETC miner? Also, run `wmic PATH Win32_VideoController GET Name, VideoProcessor` in cmd and post the results here.

**Comment by parabola20** [comment]
tried changing the startup path - didn't help

**Comment by parabola20** [comment]
> 

only tested on ETC

**Comment by UnamSanctam** [comment]
Test with the Lite example settings and see.

**Comment by parabola20** [comment]
> You mean that your XMR miner works but not your ETC miner? Also, run `wmic PATH Win32_VideoController GET Name, VideoProcessor` in cmd and post the results here.

AMD Radeon (TM) R9 380 Series  AMD Radeon Graphics Processor (0x6939)

**Comment by parabola20** [comment]
> Test with the Lite example settings and see.

sry I don't understand what this setting is?

**Comment by UnamSanctam** [comment]
I mean try with these settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite and see.

**Comment by parabola20** [comment]
> I mean try with these settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite and see.

these settings work. strange. compare them with mine and look for the reason

**Comment by parabola20** [comment]
> I mean try with these settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite and see.

could it be because of the spaces in the words in the startup "Entry name"?

**Comment by UnamSanctam** [comment]
Possibly, try loading the example settings and put a space in the "Entry Name" and see. Powershell/cmd commands formatting is always "buggy" like that so it wouldn't surprise me.

**Comment by parabola20** [comment]
> Possibly, try loading the example settings and put a space in the "Entry Name" and see. Powershell/cmd commands formatting is always "buggy" like that so it wouldn't surprise me.

tried to remove spaces from my settings - it worked. thanks for the quick help

**Comment by UnamSanctam** [comment]
Alright great, I'll see what causes that not to work as well for the next update.
