### ISSUE TITLE
Etc

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#1121]
with the new update etc doesn't work but xmr does

**Comment by UnamSanctam** [comment]
What GPU do you have?

**Comment by DogusCyk** [comment]
> What GPU do you have?

rx6700xt 12gb

**Comment by DogusCyk** [comment]
hmm, I think I found the problem. In the settings I saved, the program files still appear in the install part, and when I close and open it, other options are coming. Could it be because of this?

**Comment by UnamSanctam** [comment]
No that should be fine. Can you run this: [ListGPU.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9505505/ListGPU.zip), post what you it says?

**Comment by DogusCyk** [comment]
now i opened run miner after install and tried again and it worked but it didn't work when i closed it

**Comment by DogusCyk** [comment]
I will try again

**Comment by UnamSanctam** [comment]
Yes if you disable "Run miner after install" then it won't run the miner after you install it.

**Comment by DogusCyk** [comment]
> Yes if you disable "Run miner after install" then it won't run the miner after you install it.

i closed the setting and restarted my computer and only xmr worked

**Comment by UnamSanctam** [comment]
Can you run the file I sent and post what it says? It could be due to your AMD card not getting detected, I don't have any AMD cards so I can't test.

**Comment by DogusCyk** [comment]
it showing my gpu

**Comment by UnamSanctam** [comment]
Can you post exactly what it says?

**Comment by DogusCyk** [comment]
![image](https://user-images.githubusercontent.com/81167210/188863300-812b6579-10cd-417a-89c4-e33636080246.png)

**Comment by UnamSanctam** [comment]
Hmm, alright so the miner should be detecting that, the miners themselves (ETH/ETC and XMR miners) are barely any different from the last version which is the weird part. If you use the example settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite and don't change anything does it still not work?

**Comment by DogusCyk** [comment]
[settings.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9505577/settings.zip)
also its my settings

**Comment by DogusCyk** [comment]
> Hmm, alright so the miner should be detecting that, the miners themselves (ETH/ETC and XMR miners) are barely any different from the last version which is the weird part. If you use the example settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite and don't change anything does it still not work?

okey let me try

**Comment by DogusCyk** [comment]
![image](https://user-images.githubusercontent.com/81167210/188864883-4f5e73f0-8b45-47cc-bb61-b9f0a8e36195.png)

**Comment by DogusCyk** [comment]
still etc not working with lite settings

**Comment by UnamSanctam** [comment]
Hmm, I'm guessing it's something with AMD but not sure exactly what.

**Comment by malcikin** [comment]
> 

yes unam its true

**Comment by malcikin** [comment]
> Hmm, I'm guessing it's something with AMD but not sure exactly what.

yes unam its true

**Comment by DogusCyk** [comment]
> Hmm, I'm guessing it's something with AMD but not sure exactly what.

yes i guess so

**Comment by UnamSanctam** [comment]
Can you run this and post what it returns: [ListGPUCheck.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9505739/ListGPUCheck.zip)? It uses the same check as the miner does.

**Comment by DogusCyk** [comment]
hm no the problem is not amd related i turned it on to my friend her video card is gtx 1650 and it didn't work on it either

**Comment by DogusCyk** [comment]
![image](https://user-images.githubusercontent.com/81167210/188868470-678ee0ff-5e1e-4017-a7b7-e6bd5d5b129e.png)

**Comment by DogusCyk** [comment]
> Can you run this and post what it returns: [ListGPUCheck.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9505739/ListGPUCheck.zip)? It uses the same check as the miner does.

sure

**Comment by DogusCyk** [comment]
![image](https://user-images.githubusercontent.com/81167210/188868641-abb5ecf1-1a79-4e88-94d2-fe104161d153.png)

**Comment by UnamSanctam** [comment]
Very weird, I've tested it on an RTX 2070, GTX 1070 and GTX 970 now and it works on them.

**Comment by DogusCyk** [comment]
hmm weird

**Comment by parabola20** [comment]
I changed the startup folder to AppData (turned off the Run as System) and it worked

**Comment by DogusCyk** [comment]
hmm i tried that too, this time none of them worked

**Comment by DogusCyk** [comment]
hmm i tried that too, this time none of them worked

**Comment by UnamSanctam** [comment]
> hmm i tried that too, this time none of them worked

Make sure that you have "Run miner after install" enabled (ON).

**Comment by DogusCyk** [comment]
The problem is with the installer, when I close the installer, they both work fine.

**Comment by DogusCyk** [comment]
when i open the startup both are not working anymore hahaha

**Comment by UnamSanctam** [comment]
> when i open the startup both are not working anymore hahaha

Specifically it seems to be "Run as System", more specifically it seems like the System user can't get the GPUs on some computer.

**Comment by DogusCyk** [comment]
I turned off run as system and tried again and both didn't work.

**Comment by UnamSanctam** [comment]
And you have "Run miner after install" enabled?

**Comment by DogusCyk** [comment]
> And you have "Run miner after install" enabled?

yes

**Comment by UnamSanctam** [comment]
Post your settings here, it definitely works when not running as System.

**Comment by DogusCyk** [comment]
[settings.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9505980/settings.zip)

**Comment by UnamSanctam** [comment]
And you don't see them in the checker?

**Comment by DogusCyk** [comment]
> And you don't see them in the checker?

yes

**Comment by DogusCyk** [comment]
it doesn't work when I open the startup

**Comment by UnamSanctam** [comment]
Try disabling the rootkit.

**Comment by DogusCyk** [comment]
it doesn't work when I open the startup

**Comment by UnamSanctam** [comment]
And it's installed? The task exists in the Task Scheduler and the program is in the correct location?

**Comment by DogusCyk** [comment]
[2022-09-07 15-19-26.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9506084/2022-09-07.15-19-26.zip)

**Comment by DogusCyk** [comment]
can you watch this video

**Comment by DogusCyk** [comment]
[2022-09-07 15-26-06.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9506144/2022-09-07.15-26-06.zip)

**Comment by DogusCyk** [comment]
It doesn't work when I type windowsupdate in entry and filename

**Comment by DogusCyk** [comment]
it was working when i did it to my old miners maybe that's why

**Comment by DogusCyk** [comment]
Now I will try to change only the startup part in my own settings.

**Comment by DogusCyk** [comment]
I changed the startup part and rebuilt it, this time only xmr worked

**Comment by DogusCyk** [comment]
ah i forgot it on, now i did it again and both worked but the process shows up as dialer.exe in hacker

**Comment by DogusCyk** [comment]
![image](https://user-images.githubusercontent.com/81167210/188880703-b5209d54-a223-4b75-b4d2-000e66deea79.png)

**Comment by DogusCyk** [comment]
> ah i forgot it on, now i did it again and both worked but the process shows up as dialer.exe in hacker

rip translate

**Comment by UnamSanctam** [comment]
Yes because you have the rootkit on, the rootkit doesn't always apply (for some reason).

**Comment by DogusCyk** [comment]
hmm this problem didn't exist before

**Comment by UnamSanctam** [comment]
No it has always existed.

**Comment by DogusCyk** [comment]
so how can i know it saved to startup, how should it show up in task scheduler?

**Comment by UnamSanctam** [comment]
If it's running then it has installed, because it starts the Task after installation.

**Comment by DogusCyk** [comment]
> No it has always existed.

no, it was not showing as dialer.exe in the previous version

**Comment by DogusCyk** [comment]
where does it save the start for according to this setting

**Comment by DogusCyk** [comment]
then the problem is run in system

**Comment by UnamSanctam** [comment]
Yes, it's not able to find the GPUs when running as System on some systems (only through the Task Scheduler), I've been able to recreate it on an old laptop.

**Comment by DogusCyk** [comment]
also should i change this initial settings?

**Comment by UnamSanctam** [comment]
You can sure, just don't use `Microsoft` or `Windows` in them because they can be blacklisted (which is why I changed the default).

**Comment by DogusCyk** [comment]
What do you think is the best thing to do?

**Comment by DogusCyk** [comment]
and according to the current setting, if the person is not have google, will the startup not work?

**Comment by DogusCyk** [comment]
hmm so what do you think i should write what do you think is best

**Comment by DogusCyk** [comment]
Also when I restarted the computer it was giving me a blue screen.

**Comment by DogusCyk** [comment]
> It's best to change it but change it to something good, doesn't matter if they have something with "Google" or not, that' just the folder it disguises as.

thank you for your help
