### ISSUE TITLE
Version in Web Panel

### ISSUE THREAD

**Issue by UnaFactura** [UnamSanctam/SilentCryptoMiner#1122]
Hey, I just set the new version but new miners in web panel don't show that they use 3.0.0. Is it supposed to be like that?

**Comment by UnamSanctam** [comment]
It should say 3.0.0, the version is taken directly from the builder. What are they showing for you?

**Comment by UnaFactura** [comment]
2.6.1

**Comment by UnamSanctam** [comment]
Are you 100% sure that you built it with the latest version? The miner takes the builder version from the same place as the builder form title:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/95b4f62465d265aedce989b4af221f1c22af58ce/SilentCryptoMiner/Forms/Builder.cs#L167
And that one says 3.0.0.

**Comment by UnaFactura** [comment]
Yeah, I built it with new version. It might be that the new build didn't work.

**Comment by UnamSanctam** [comment]
The only way it should say 2.6.1 is if the build was from the 2.6.1 builder or if you manually entered `--cinit-version="2.6.1"` into the "Advanced Parameters". So most likely that's an old build running.

**Comment by UnaFactura** [comment]
New build doesn't work as it should be. It creates an empty folder for miner files but with no files in it and watchdog doesn't get installed as well.

**Comment by UnamSanctam** [comment]
What does it say when you run the checker?

**Comment by UnaFactura** [comment]
Okay, but the checker says that there is no watchdog now

**Comment by UnamSanctam** [comment]
Does it say "Watchdog Running: No" in a checker whose miner you're certain is installed?

**Comment by UnaFactura** [comment]
> Does it say "Watchdog Running: No" in a checker whose miner you're certain is installed?

It broke completely again. It creates an empty folder and nothing in checker at all.

**Comment by UnamSanctam** [comment]
Empty folder where? The install path?

**Comment by UnaFactura** [comment]
> Empty folder where? The install path?

Yes

**Comment by UnaFactura** [comment]
Task Scheduler is empty too. No tasks created.

**Comment by UnamSanctam** [comment]
Try the example settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite if you haven't.

**Comment by UnaFactura** [comment]
I got almost the same settings. Everything worked with 2.6.1 and works till now, I got ~2k bots.

**Comment by UnamSanctam** [comment]
You'll have to find out why then, take a video or something like it from when you build it to when you run it. It works for me on my Windows 7, Windows 8, Windows 10 and Windows 11 VMs and also on my main computer and laptop so I can't really find the problem myself. Currently there's only one confirmed bug which is GPU checking when running as the System user and I'd preferably want your bug fixed before releasing a new minor version if we can find it.

**Comment by UnaFactura** [comment]
I removed whole path from path and left it with Program Files and now it works

**Comment by UnamSanctam** [comment]
Ok great, what did you have as a path?

**Comment by UnaFactura** [comment]
> Ok great, what did you have as a path?

It didn't work because I used '/' instead of '\'

**Comment by UnamSanctam** [comment]
Oh yeah, it's quite strict and finicky.
