### ISSUE TITLE
check cmd work miner

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/SilentCryptoMiner#1124]
Tell me how to check the work of the miner by the command through the console?

it is necessary when you test the work of the miner through RAT

**Comment by anbu-squad** [comment]
`C:\Windows\System32\conhost.exe "cwcwgqhdffsz"`

Yes thank you

The result is higher

It's right?

**Comment by UnamSanctam** [comment]
Yes that's the (older version) watchdog, so that's running, I'm not sure what you chose to inject the miners into but if you chose explorer.exe then you can do:
```
wmic process WHERE "name like 'explorer.exe'" get commandline
```
To try and find the miners as well if you want to.
