### ISSUE TITLE
i Can change my Miners ?

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1125]
i can change my miner to mine  like  etc ? from xmr to etc ??? from pastebin  settings ?

**Comment by UnamSanctam** [comment]
You can change the algorithms within each miner but not from XMR to ETC since they are different miners, so if you don't build the program with an ETC miner added then there won't be any ETC miner code inside the program.

These are the two different miners available:
ETH miner: Ethash, Etchash and Ubqhash algorithms
XMR miner: All other available algorithms
And with the pastebin you can swap between the algorithms inside the individual miners.

**Comment by tarekxxx** [comment]
so i can change from xmr to etc from pastebin ? and if so which pool is good for your miner and how settings will be look like ?

**Comment by UnamSanctam** [comment]
No not XMR to ETC since they are two different miners, if you didn't build your miner with an ETC miner added then your miner doesn't have any ETC mining code inside it, and any pool should work though most use 2miners, ethermine or nanopool.

**Comment by tarekxxx** [comment]
oh okay what about new version 3.0.1 when i build i get error C:\UCompilers\logswindres.log then
Error compiling Watchdog!

**Comment by UnamSanctam** [comment]
Try building it in another location, preferably in a short path and I believe they prefer the C: as well.

**Comment by Nippyebudum34** [comment]
Still get the could not find C:\UCompilers\logswindres.log error

**Comment by UnamSanctam** [comment]
> Still get the could not find C:\UCompilers\logswindres.log error

Hmm, I can't get the error no matter how much I try on any of my virtual machines or main computer. Can you try running the builder as administrator?

**Comment by UnamSanctam** [comment]
> Still get the could not find C:\UCompilers\logswindres.log error

> oh okay what about new version 3.0.1 when i build i get error C:\UCompilers\logswindres.log then Error compiling Watchdog! i Injected into DWM.exe

Seems like this is just due to some weird thing about relative paths on some computers, you can use this which only uses absolute paths: https://anonfiles.com/l8bcj77ayc/Silent_Crypto_Miner_Builder_exe
