### ISSUE TITLE
switch current eth miners to etc miners ?

### ISSUE THREAD

**Issue by elraiqq** [UnamSanctam/SilentCryptoMiner#1130]
hello unam 
i already have active eth miners 
when i build this miners i dont add etc algorithm  
can i switch from eth to etc mining easy by editing config in webpanel ? and how  ? 
thanks

**Comment by UnamSanctam** [comment]
Yes you can change the algorithm to `etchash`, ETH miners can switch freely between the ethash, etchash and ubqhash algorithms. For easier configuration you can open the builder, create an ETC miner in the builder and then go to the JSON tab, you can then copy-paste that JSON text into the "Configurations" in the web panel.

**Comment by elraiqq** [comment]
thanks man you are a legend 
that is work
