### ISSUE TITLE
Startup builder - video inside

### ISSUE THREAD

**Issue by helpingfriend90** [UnamSanctam/SilentCryptoMiner#1131]
Notice save path changes and locks only after toggling "run as administrator" in build options.

I think this causes people issues when they trying startup as system but also run as administrator and they don't know they path is changed etc.

Sorry the English.

P.S. Thankyou for hard work brother. Your projects are very fun to learn with.

**Comment by helpingfriend90** [comment]
https://user-images.githubusercontent.com/113107883/189111403-6f8b86d5-0caa-4fb0-907b-f425aed75b0a.mp4

**Comment by UnamSanctam** [comment]
Yes it will install to "Program Files" only if both "Run as System" and "Run as Administrator" is enabled, because if they don't run it as administrator then it can't write to "Program Files".

**Comment by helpingfriend90** [comment]
I think maybe users don't see this change because the options tab come after startup tab. Maybe they can getting confuse where the save. :)

**Comment by UnamSanctam** [comment]
Maybe, though there isn't really much I can do about it, since I can't make it switch to `Program Files` with only "Run as System" enabled because then you can't make miners that won't run as administrator.
