### ISSUE TITLE
Best Coin To Mine

### ISSUE THREAD

**Issue by SieraMondorez** [UnamSanctam/SilentCryptoMiner#1136]
Hello so as you guys know etherium will end soon what is the best coin to mine now? and how much would i earn most liekely i get 1.5ghs min in etherium i earn like 26 usd

**Comment by UnamSanctam** [comment]
Probably ETC, it's what most people silent mine anyways since it requires less VRAM. The profits are about the same as ETH over time, and it also requires less VRAM so it can mine on more GPUs than ETH.

**Comment by xanaxsys** [comment]
> 

Maybe RVN is better then ECT because it brings more Profit.

**Comment by UnamSanctam** [comment]
> Maybe RVN is better then ETC because it brings more Profit.

Not really (at least in my opinion), RVN uses the KawPow algorithm which causes a lot more lag and heat which makes it harder to silent mine. RVN also requires more VRAM than ETC, ETC needs 3GB while RVN needs 3.5GB. Mining RVN is usually also a lot more unstable, and RVN is only more profitable right now, the market goes up and down all the time and ETC is sometimes more profitable than RVN and vice versa.

**Comment by xanaxsys** [comment]
> > Maybe RVN is better then ETC because it brings more Profit.
> 
> Not really (at least in my opinion), RVN uses the KawPow algorithm which causes a lot more lag and heat which makes it harder to silent mine. RVN also requires more VRAM than ETC, ETC needs 3GB while RVN needs 3.5GB. Mining RVN is usually also a lot more unstable, and RVN is only more profitable right now, the market goes up and down all the time and ETC is sometimes more profitable than RVN and vice versa.

That RVN is lagging i saw it some years ago but i will use ETC then. Thank you.
