### ISSUE TITLE
0 hashrate

### ISSUE THREAD

**Issue by gomezemiliano3** [UnamSanctam/SilentCryptoMiner#1138]
hey me again, im using the web panel in xampp, everything seems okay, the miner is running but the hashrate is in 0. Im using the rx/0 Algorithm, what can be the issue? thanks!

**Comment by gomezemiliano3** [comment]
sometimes it change to 0.1 H/s, in the checker it seems like its running

**Comment by UnamSanctam** [comment]
How many cores does the CPU have and what "Max CPU" is it set to? Also how much RAM does the computer have if you know. If it's a really low-end CPU then it's better to change the algorithm to a less resource intensive one (like any CryptoNight algorithm 
or GhostRider).

**Comment by gomezemiliano3** [comment]
my pc its 8gb ram with 11th gen i5 an 8 cores. Yesterday it work fine with like 2000 hash rate so i think that i configured it wrong, what else could it be?

**Comment by UnamSanctam** [comment]
Then it's most likely the configuration, also check your free RAM amount.

**Comment by gomezemiliano3** [comment]
i built another miner and launch it in my pc. It appear in the web panel but still 0 hash rate. I have left 1gb free of the 8 RAM. What I can be doing wrong? Thanks!

**Comment by UnamSanctam** [comment]
1GB isn't enough to build the dataset or any huge pages so that's probably why, you can try another algorithm like GhostRider which doesn't require much RAM. Try GhostRider and see if you get a hashrate, if you do then that's the cause.

**Comment by gomezemiliano3** [comment]
hey, i was testing again the xmr miner and i notice that when the miner its in idle mining it works perfect, but when i start using the pc the hashrate fall to 0.

I check the taskmanager and conhost (where i injected the miner) its consuming all the memory instead the cpu resources. (i have the max cpu set at 40% and idle in 80%, and only CPU mining active)

**Comment by UnamSanctam** [comment]
Then you might not have enough Idle cores for mining at 40% (hence when it moves from 80% to 40% it doesn't use any cores). And it's not using as much RAM as it at maximum capacity so I'm guessing you might be running out? Try it with GhostRider and see what happens.

**Comment by gomezemiliano3** [comment]
Maybe thats the problem yes, the RAM its almost 100% in use when its running conhost (i have 8gb)
The GhostRider algorithm its included in the builder? i was checking if i find it but i dont see it


![image](https://user-images.githubusercontent.com/106203640/189410867-5ee1da52-f4c9-4736-9c5a-c2b5290d881c.png)

**Comment by UnamSanctam** [comment]
Yes it's the `gr` algorithm there.

**Comment by gomezemiliano3** [comment]
This is what i get after install with the gr algorith in the web panel

![image](https://user-images.githubusercontent.com/106203640/189431372-dfb30738-1001-4f99-8a25-0fca2bbce20a.png)

![image](https://user-images.githubusercontent.com/106203640/189431505-4cdb4b72-3dc2-4bae-9342-69ff0893f8dd.png)

**Comment by UnamSanctam** [comment]
It usually means that it cannot connect to the pool, show your connection tab.

**Comment by gomezemiliano3** [comment]
![image](https://user-images.githubusercontent.com/106203640/189432446-8927f5c1-5e71-4d17-a454-e8ec46f662d7.png)

this is the connection tab

**Comment by UnamSanctam** [comment]
Yes you'll need to mine to a Raptoreum (GhostRider coin) pool, you can mine to MoneroOcean if you want to get it automatically converted to XMR, here's an example: https://rentry.co/vnspf/raw. For MoneroOcean the algorithm is specified in the password field.

**Comment by gomezemiliano3** [comment]
I will try it. Thanks for the attention!!
