### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by unmastered1** [UnamSanctam/SilentCryptoMiner#1139]
i have a problem if you guys can explain i downloaded all the 4 pinned projects but i cant find any .exe like how to open each project .exe i cant find them i get .sln file sorry im new to this thing i dont know anything

**Comment by UnamSanctam** [comment]
You can find pre-built versions on the releases pages https://github.com/UnamSanctam/SilentCryptoMiner/releases.

**Comment by unmastered1** [comment]
yes i downloaded these files and cant find .exe

**Comment by UnamSanctam** [comment]
Download "Silent.Crypto.Miner.Builder.zip" on that page and then extract the .zip file, it has an .exe in it.

**Comment by unmastered1** [comment]
ok do i just download this project or do i need to download other files?

**Comment by UnamSanctam** [comment]
You only need to download "Silent.Crypto.Miner.Builder.zip" to use the miner.
