### ISSUE TITLE
error when building exe

### ISSUE THREAD

**Issue by sadandnab** [UnamSanctam/SilentCryptoMiner#1142]
i am getting an error when building the exe miner version 3.0.2
![Capture](https://user-images.githubusercontent.com/87695790/189334753-8c96240d-7e98-47ff-8cb9-5ae6262c405a.PNG)

**Comment by MJMODZZ** [comment]
> i am getting an error when building the exe miner version 3.0.2 ![Capture](https://user-images.githubusercontent.com/87695790/189334753-8c96240d-7e98-47ff-8cb9-5ae6262c405a.PNG)

Better try to build it from the Source code version or just reinstall this builder and in the folder where the builder is located, make a secound folder called "Miners" and in this folder make the miner folders like Miner1, Miner2 ... and build yours miner there

**Comment by UnamSanctam** [comment]
It says why you get the error right in the message, you can't have a space in your build path, your username has a space in it so build it somewhere other than your user profile.

**Comment by sadandnab** [comment]
Thanks for the helped it i build in C:\path and it worked 

Helped by Zebi friend of mine
