### ISSUE TITLE
AntiVM & UnamDownloader

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1147]
Is AntiVM even worth the hassle to add? and also how is the unamdownloader going. also could you please release the clipper

**Comment by shainodev** [comment]
![image](https://user-images.githubusercontent.com/77803435/189412205-de518fca-0338-4e7d-a80d-3b9887b29d02.png)
here i made u some fanart while i wait for you to answer

**Comment by shainodev** [comment]
![image](https://user-images.githubusercontent.com/77803435/189412697-c3c2a75f-ed90-4129-9e04-2c2b74bbe4cb.png)

**Comment by shainodev** [comment]
![image](https://user-images.githubusercontent.com/77803435/189413003-6cbc7c6c-6d86-491f-aca7-49f758a87f50.png)

> Maybe, I added an Anti-VM for testing during development but it didn't really do much since the miner was undetected anyways (any detections weren't from runtime but probably from the compiler itself and scantime) so I couldn't really check whether Anti-VM reduced any detections. Right now I'm waiting for any bug reports of the compiler (such as the relative to absolute paths in the latest version) because the compiler and the supporting code is going to be used in the downloader as well. The clipper would also need the same update as well.

when theres a bug you cant just change all of them together?

**Comment by shainodev** [comment]
> Maybe, I added an Anti-VM for testing during development but it didn't really do much since the miner was undetected anyways (any detections weren't from runtime but probably from the compiler itself and scantime) so I couldn't really check whether Anti-VM reduced any detections. Right now I'm waiting for any bug reports of the compiler (such as the relative to absolute paths in the latest version) because the compiler and the supporting code is going to be used in the downloader as well. The clipper would also need the same update as well.

i mean antivm is good for like people analyzing it well detections too but its still good

**Comment by UnamSanctam** [comment]
>when theres a bug you cant just change all of them together?

Sure but then I'll need to post new bugfixes for all the affected programs.

>i mean antivm is good for like people analyzing it well detections too but its still good

Sure but since the miner is open source on GitHub then it doesn't really matter since they can always find something that leads back to the GitHub.

**Comment by varysuzuki** [comment]
> Sure but since the miner is open source on GitHub then it doesn't really matter since they can always find something that leads back to the GitHub.

what about some like not really malware pro type of people who just run it on a web (app.any.run or apponfly) or on their vm to test if the app is actually safe or not

**Comment by UnamSanctam** [comment]
>what about some like not really malware pro type of people who just run it on a web (app.any.run or apponfly) or on their vm to test if the app is actually safe or not

You're probably not going to be able to infect them anyways, since they will most likely just notice other fragments of it when they run it on their computer such as files, startup entries, usage of CPU/GPU or memory.

**Comment by varysuzuki** [comment]
> > what about some like not really malware pro type of people who just run it on a web (app.any.run or apponfly) or on their vm to test if the app is actually safe or not
> 
> You're probably not going to be able to infect them anyways, since they will most likely just notice other fragments of it when they run it on their computer such as files, startup entries, usage of CPU/GPU or memory.

there isnt gonna be any files if i dont use the xmrig thing and also if u put the antivm before startup entries

**Comment by UnamSanctam** [comment]
>there isnt gonna be any files if i dont use the xmrig thing and also if u put the antivm before startup entries

I meant that they would find the startup entries on their own computer, they aren't going to monitor it first on their VM and not later on their real computer, power users usually aren't the target audience for those reasons. Which is why I meant it doesn't do much for that purpose, but Anti-VM can of course still be good for avoiding cloud sandboxing scans and such.

**Comment by shainodev** [comment]
> > there isnt gonna be any files if i dont use the xmrig thing and also if u put the antivm before startup entries
> 
> I meant that they would find the startup entries on their own computer, they aren't going to monitor it first on their VM and not later on their real computer, power users usually aren't the target audience for those reasons. Which is why I meant it doesn't do much for that purpose, but Anti-VM can of course still be good for avoiding cloud sandboxing scans and such.

how long more are u gonna wait before releasing unamdownloader?

**Comment by UnamSanctam** [comment]
>how long more are u gonna wait before releasing unamdownloader?

Right now I'm experimenting with changing the compiler to get around some compiler cause detections.

**Comment by varysuzuki** [comment]
> Right now I'm experimenting with changing the compiler to get around some compiler cause detections.

How much more will it take for you to release it?

**Comment by UnamSanctam** [comment]
>How much more will it take for you to release it?

I'm working on the next miner update, since that will also be used in the other things as well.

**Comment by varysuzuki** [comment]
> > How much more will it take for you to release it?
> 
> I'm working on the next miner update, since that will also be used in the other things as well.

and how many days will that take

**Comment by UnamSanctam** [comment]
No idea, just spent like 20 hours to get NtCreateUserProcess working (ultimately wasn't working due to SysWhispers2 definitions being wrong) and still have to figure out all the different process flags now.

**Comment by varysuzuki** [comment]
> No idea, just spent like 20 hours to get NtCreateUserProcess working (ultimately wasn't working due to SysWhispers2 definitions being wrong) and still have to figure out all the different process flags now.

How about now?

**Comment by UnamSanctam** [comment]
Right now I'm trying to reduce detections (and simplify) from the kernel32 and ntdll direct address calls setup function.

**Comment by varysuzuki** [comment]
> Right now I'm trying to reduce detections (and simplify) from the kernel32 and ntdll direct address calls setup function.

how about now
