### ISSUE TITLE
Paused (Stealth - Fullscreen)

### ISSUE THREAD

**Issue by svox07** [UnamSanctam/SilentCryptoMiner#1148]
Unam hello, why is this happening, I turned off Fullscreen when I collected
![Screenshot_20220910-231840](https://user-images.githubusercontent.com/70852343/189494790-c8bcd30d-a210-44fe-8b50-4fbaa244e8c7.jpg)

**Comment by UnamSanctam** [comment]
Then it means that "Stealth on Fullscreen" is enabled for your XMR miner and something is currently in fullscreen, if you have a "Remote Configuration" or a configuration in the web panel then you can add `"stealth-fullscreen": false`

**Comment by svox07** [comment]
this function was not included when I collected the miner.  Did as you said
