### ISSUE TITLE
These MH/s values make no sense

### ISSUE THREAD

**Issue by LokeYourLord** [UnamSanctam/SilentCryptoMiner#115]
So how come a PC (I built both of these Machines IRL) with a RTX 2070 at 31.6 MH/s is getting nearly DOUBLE the hashrate over the RTX 2080 Super at only 16.7 MH/s? I am seeing equally weird values with for example the RTX 3060 (as seen in the picture) achieving only 8.4 MH/s (which should achieve equally as much as the RTX 2070 in regards to the specs level being practically identical), and the RTX 3070 as seen in this picture (the top of the line for all of these), achieving only a mere 11.3 MH/s? None of these values make any sense, especially since they are also reflected the same way on Nanopool so they are correct. But how come that the lower tier cards (lowest tier on this list aside from the 5# which is a GTX 1080) achieve the highest MH/s, while the top tier cards do the opposite?

**Comment by UnamSanctam** [comment]
They are most likely LHR cards.

**Comment by LokeYourLord** [comment]
RTX 2080 Super never had LHR versions, and I know that the RTX 3070 also isn't LHR. The RTX 3060 MIGHT be, but the others are 100% not.

**Comment by LokeYourLord** [comment]
I mean, if they are, is there a way for you to test that and report a value in the Web Panel or so like "LHR: Yes/No"? But again, other than the RTX 3060 which only MIGHT be one, the others were bought before LHR was a thing.

**Comment by UnamSanctam** [comment]
Do you have access to all the cards? In that case can you see how much GPU they're using? Also, what Max GPU percentage do you have set?

> I mean, if they are, is there a way for you to test that and report a value in the Web Panel or so like "LHR: Yes/No"? But again, other than the RTX 3060 which only MIGHT be one, the others were bought before LHR was a thing.

Not really possible to know if it's LHR or not so it wouldn't be able to display that.

**Comment by LokeYourLord** [comment]
The GPU percentage is the same for all of them, 30% and 50% on Idle. But that shouldn't matter in that case as the RTX 2070 achieves the most, while the RTX 2080 Super is actually supposed to do that.

**Comment by LokeYourLord** [comment]
Again, I built ALL of these systems, and none we picked had LHR in their description when buying, which they are obligated to have if they have it.

**Comment by UnamSanctam** [comment]
Doesn't have to say LHR, they can also say V2 which also means LHR. But the RTX 2080 Super usually has around 45MH/s at 100% I believe so at 30% it should have around 14MH/s. The RTX 3060 has around 35MH/s at 100% so at 30% it should have around 11MH/s.

**Comment by LokeYourLord** [comment]
> Doesn't have to say LHR, they can also say V2 which also means LHR. But the RTX 2080 Super usually has around 45MH/s at 100% I believe so at 30% it should have around 14MH/s. The RTX 3060 has around 35MH/s at 100% so at 30% it should have around 11MH/s.
> 
> My RTX 2070 gets around 37MH/s at 100% and around 12MH/s at 30%.

I mean none of them are V2 either, again, RTX 3070 was before LHR was a thing, same as for mine. And uhm, I thought you said the % only affects fan speed. And if that is the case as you say, how can the RTX 2070 at 30% achieve double of what the RTX 2080 Super can achieve at 30%? Again, makes no sense.

**Comment by UnamSanctam** [comment]
Yes the CUDA usage affects fan speed since it mines slower, otherwise there would be no reason to not always mine at 1%. What it doesn't do is reduce VRAM usage since that is always static. The 2070 at 31.6 MH/s is mining at 90%-100%.

**Comment by LokeYourLord** [comment]
> Yes the CUDA usage affects fan speed since it mines slower, otherwise there would be no reason to not always mine at 1%. What it doesn't do is reduce VRAM usage since that is always static. The 2070 at 31.6 MH/s is mining at 90%-100%.

The problem is that they both run the same config and are both on idle, again, should be equal or higher value for the RTX 2080 Super. Does the Lockscreen affect the mining rate in any way?

**Comment by UnamSanctam** [comment]
No the lockscreen shouldn't affect anything, try running any other normal miner and see what hashrates you get.

**Comment by LokeYourLord** [comment]
I was stupid and forgot to post the picture. Here you go
![Untitled](https://user-images.githubusercontent.com/5807595/144423876-0894e38d-ca74-4fb4-baef-814e888ad5d1.png)
:

**Comment by UnamSanctam** [comment]
The RTX 2080 SUPER hashrate looks correct (mining at 50%) but the RTX 2070 looks like it's mining at 100%.

**Comment by LokeYourLord** [comment]
> The RTX 2080 SUPER hashrate looks correct (mining at 50%) but the RTX 2070 looks like it's mining at 100%.

I mean that can easily be quickly tested, I will just make a 90% config and push them to both, see what values I get then. If the RTX 2070 stays around the same values, then it is somehow for some reason mining at 90% or 100% even though I set it to 30% & 50% (meaning it ignores the config in regards to the applied values). If not, something else is wrong.

**Comment by LokeYourLord** [comment]
Also, may I add that is there no way to OC/Tweak the card somehow? Because, when I run my NiceHash miner on my rig, I apply a "Mining" profile I made for the RTX 3070 that achieves 57.xx MH/s, with the Core Clock reduced by 400 MHz, Memory Clock increased by 1204 MHz, Power Limit set to 60% and Temperature Limit set to 65°C. That way, the fans are still quiet but it achieves a really high hashrate. I feel like if I set the Miner speed to 90% or 100% the PC will get REALLY LOUD and that people will notice that.

**Comment by LokeYourLord** [comment]
> > The RTX 2080 SUPER hashrate looks correct (mining at 50%) but the RTX 2070 looks like it's mining at 100%.
> 
> I mean that can easily be quickly tested, I will just make a 90% config and push them to both, see what values I get then. If the RTX 2070 stays around the same values, then it is somehow for some reason mining at 90% or 100% even though I set it to 30% & 50% (meaning it ignores the config in regards to the applied values). If not, something else is wrong.

The values are in:
RTX 2070 @ 90% = 32 MH/s
RTX 2080 Super @ 90% = 24 MH/s
Something is absolutely wrong here. Again, this also happens to the RTX 3070 in a similar manner, although most of the time it is used for gaming Genshin Impact. Yet, since the card has enough VRAM the Miner can run both without problems. Of course I expect a diminished return, but when the RTX 3070 is Idle, the hash rate also does not surpass the RTX 2070. Something is definitely wrong here.

**Comment by UnamSanctam** [comment]
> Also, may I add that is there no way to OC/Tweak the card somehow? Because, when I run my NiceHash miner on my rig, I apply a "Mining" profile I made for the RTX 3070 that achieves 57.xx MH/s, with the Core Clock reduced by 400 MHz, Memory Clock increased by 1204 MHz, Power Limit set to 60% and Temperature Limit set to 65°C. That way, the fans are still quiet but it achieves a really high hashrate. I feel like if I set the Miner speed to 90% or 100% the PC will get REALLY LOUD and that people will notice that.

It's technically possible to set some things but you would have to change it to different values for every card and vendor possible since it's different for each one. But for thorough customization like the screenshot it should always be done manually since it's quite a sensitive subject.
 
> The values are in: RTX 2070 @ 90% = 32 MH/s RTX 2080 Super @ 90% = 24 MH/s Something is absolutely wrong here. Again, this also happens to the RTX 3070 in a similar manner, although most of the time it is used for gaming Genshin Impact. Yet, since the card has enough VRAM the Miner can run both without problems. Of course I expect a diminished return, but when the RTX 3070 is Idle, the hash rate also does not surpass the RTX 2070. Something is definitely wrong here.

Your RTX 2070 at 90% hashrate is accurate though the RTX 2080 SUPER one isn't, it's weird that the RTX 2070 doesn't decrease the hashrate when set to a lower Max GPU because I test everything on my RTX 2070 so it definitely isn't the card type itself.

I asked a person I have on Discord to look at the GPU miners he has in his web panel (he has around 2300 running the ETC miner, the majority are GTX 1000 cards though). For the RTX 2080 SUPERs that he has in his web panel, he has about 40 of them and they usually mine at about 20MH/s at 50% which is normal (since they are 40-45MH/s cards). He has about 50 RTX 3070 and they mine at about 25-30MH/s at 50% (which is normal) and then he has about 130 RTX 2070 and they usually mine at around 14MH/s (which is normal). He does have some outliers (around 90% are normal) that have lower or higher hashrates, usually due to how the computers are configured or if something is running.

I can't really tell what the issue is for you since I can't look at the computers or anything but you can try creating an ETC ethermine configuration at 50% and see

**Comment by LokeYourLord** [comment]
Do you mind asking him how he's gotten so many rigs LOL? And I'll check again but I am unaware of any issues that are related to either of the rigs.

But seriously ask him, I dead on wanna know.

**Comment by UnamSanctam** [comment]
I think he has his own game cheat and spreads it through that, he's Chinese so he spreads it in that market which is very different from the western markets, I'm pretty sure he has his own website, forums and everything. He also has like 130 000 XMR miners (not in the panel though, most are from the "old" miner) that I had to help him fix when his VPS got taken down (hosted his xmrig-proxy).

**Comment by LelouchViBri** [comment]
130.000 xmr miners? wtf?
