### ISSUE TITLE
Recompile the miner installer with another setup ?

### ISSUE THREAD

**Issue by Pedrolito666** [UnamSanctam/SilentCryptoMiner#1153]
Hi Unam ! Is it possible to recompile both miner install and a program without binder ?? Thanks for your time !

**Comment by Pedrolito666** [comment]
Or can we create a repack for a program and inject the miner in it ?

**Comment by UnamSanctam** [comment]
Not fully sure what you're asking, but you can code other programs to be injected or dropped from the miner if that's what toy mean.
