### ISSUE TITLE
Unable to mine on unmineable

### ISSUE THREAD

**Issue by murkas1** [UnamSanctam/SilentCryptoMiner#1155]
Hello! Unable to start mining on https://unmineable.com
Maybe the reason is in the bat file. They have the format: 
"xmrig.exe -o rx.unmineable.com:3333 -a rx -k -u COIN:YOUR_ADDRESS.WORKER_NAME -p x
pause"
Is it possible to set this type of settings in your miner?
Or maybe it's something else? 
Thank you!
![miner](https://user-images.githubusercontent.com/75254232/189741105-5f291f8f-4a47-4fe2-a779-6630360a7589.jpg)

**Comment by UnamSanctam** [comment]
Yes you need to add the `COIN:` part before your wallet address, so enter the coin that you want to convert your XMR into there (unmineable works by mining XMR/ETH/ETC or anything else and then exchanging that to whatever coin you put in).

**Comment by murkas1** [comment]
I did that too, it doesn't work.
The usual, not modified xmrig works, it's checked.

**Comment by UnamSanctam** [comment]
I just tried and it works fine, post your checker again.

**Comment by murkas1** [comment]
![Screenshot_20220913-091953](https://user-images.githubusercontent.com/75254232/189824922-ddd40c35-d84f-4275-81b1-2de6c3564d39.png)

**Comment by UnamSanctam** [comment]
Since you have SSL/TLS enabled you should use the SSL port 443 as well (it says on their website in small letter just underneath the normal one).

**Comment by murkas1** [comment]
Thanks for the tips, I'll try.
