### ISSUE TITLE
UBQ

### ISSUE THREAD

**Issue by Ahmedzx555** [UnamSanctam/SilentCryptoMiner#1158]
![issue2](https://user-images.githubusercontent.com/52262281/189830370-019ddcda-b7c8-4cb6-83af-14ea64a73741.PNG)
![issu1](https://user-images.githubusercontent.com/52262281/189830375-0a93bc71-3e13-41d4-94ec-2bf3db708a88.PNG)

tried eth,etc and the same hashrate!

**Comment by UnamSanctam** [comment]
It it has enough VRAM available? It could be out of VRAM after start and not report it since it's version 2.4.1.
