### ISSUE TITLE
0.2 H/s

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1163]
Unam Some workers have problems with the transmitted hashrate. The screenshot shows that the processor is not weak. load 30%. With such a load, it clearly should show more hash than 0.2 H/s. I did not take a screenshot, but I switched it to the algorithm GhostRider and it showed the hash 0,3 H/s
![1](https://user-images.githubusercontent.com/36513967/189952611-5dfe61e3-2b75-42b2-84df-18b1b56cb18d.jpg)

**Comment by UnamSanctam** [comment]
Hmm, could be some "problem" with xmrig maybe (the transmitted hashrate is what xmrig is reporting), I'm not the creator of xmrig (obviously) so I'm not 100% sure of everything it does (nor what could go wrong). Or the CPU could be at 100% due to something of course, can you post the configuration here?

**Comment by masterjek** [comment]
Here is the configuration on which it works.
![2](https://user-images.githubusercontent.com/36513967/189955223-5f7e353a-244f-47d0-9f67-c441f35743c7.jpg)

**Comment by UnamSanctam** [comment]
Alright, check later if the hashrate has gone up or not so that we know whether it's not a temporary thing (such as something running).

**Comment by masterjek** [comment]
You wrote, I just went to check the worker is still online hash changed 0.3 H/s.
![3](https://user-images.githubusercontent.com/36513967/189983660-83d9eafa-7786-4069-8346-d9c2408ddf9c.jpg)
I understand that it is possible to determine what is wrong only by having access to a computer. I don't have access to this computer. Therefore, all that remains is to leave it as it is, let it work.

**Comment by UnamSanctam** [comment]
Alright, could be something with NiceHash then.

**Comment by masterjek** [comment]
Unam Sorry for the stupid question. How to understand in the database editor which worker is online and which is offline. In the screenshot, both workers have the number 2, but in the web panel one of them is online and the other is offline.
![6](https://user-images.githubusercontent.com/36513967/189994698-4f055614-f4b0-4ec2-a898-8a32fb50a0eb.jpg)

**Comment by UnamSanctam** [comment]
You compare the lastConnection date and if it's longer than 3 minutes ago then the web panel counts it as offline.
