### ISSUE TITLE
0 hashes again

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#1164]
I dont know anymore what to do 

very good GPUs like 3070 yet 0 hashes and doesnt even show out of vram.

**Comment by UnamSanctam** [comment]
And you've tried it with UBQ? It will only show "Out of free VRAM" if it gets that during DAG creation, and is that happening with version 3.0.2?

**Comment by Brainshot** [comment]
> And you've tried it with UBQ? It will only show "Out of free VRAM" if it gets that during DAG creation, and is that happening with version 3.0.2?

I am mining ETC and build it with the 3.0.2 version.

**Comment by Brainshot** [comment]
> And you've tried it with UBQ? It will only show "Out of free VRAM" if it gets that during DAG creation, and is that happening with version 3.0.2?

No idea what is happening but just the hashrate is at 0 with many miners with the new version.

**Comment by UnamSanctam** [comment]
Can you try with UBQ? The ethminer is basically the same as earlier except with mutex creation (to stop multiple from starting).

**Comment by Pedrolito666** [comment]
Same thing with ubq, etc or eth, I have a 3070 and a 3080 and they show 0 h/s in idle, but sometimes they work when the computer boot then Its showing 0h/s After some times ! Same thing with 3.0.2, 3.0.0 , 2.6.1 , 2.5.0

**Comment by UnamSanctam** [comment]
Do you have access to any of the computers?

**Comment by Pedrolito666** [comment]
Yes but it's very strange, when I boot my pc I see the hash in the panel and after sometimes 0h/s all the day, so my config work for sure !

**Comment by UnamSanctam** [comment]
Can you check the VRAM and such with MSI Afterburner?

**Comment by Pedrolito666** [comment]
It strange cause with my computer (Vega 64) It mine when I boot the pc and after 20-30min the hash going down to 0 without touching anything on my PC

**Comment by UnamSanctam** [comment]
Can you post a screenshot of MSI Afterburner while it's at 0 H/s? Since I can't recreate it with my RTX 2070 or laptop with GTX 1070 it's hard to know why. Also remember not to have MSI Afterburner inside the "Stealth Targets" while checking since then it will pause.

**Comment by Brainshot** [comment]
> Can you post a screenshot of MSI Afterburner while it's at 0 H/s? Since I can't recreate it with my RTX 2070 or laptop with GTX 1070 it's hard to know why. Also remember not to have MSI Afterburner inside the "Stealth Targets" while checking since then it will pause.

Maybe it could be a windows thing not letting it start, since almost all versions got it and it didnt use to happen

**Comment by UnamSanctam** [comment]
Yeah maybe, I know xmrig got some (technically unfixable unless Microsoft fixes it) problem which has to to with some sort of memory task that Microsoft added so it's not impossible that Microsoft did something. I haven't gotten it to happen for me yet though so I'm unsure of what exactly causes it, I wish it would happen to me since then I would be able to try and fix or bypass it.

**Comment by Pedrolito666** [comment]
I'll post a screenshot but my gpu isn't in use, I have no problem with xmr only with etc, ethash and ubq.

**Comment by UnamSanctam** [comment]
>Well most of us are mining etc and eth and only have issues with these two coins and some other ones that require GPU mining. Xmr I never had any issues even now I have miners running from a year ago.

Yes since they are different miners that should be the case but that's not what I meant, I meant that Microsoft does add things which causes problems (as proven by the xmrig problems Microsoft caused on some computers). You can also try mining with this [Normal Miner Test.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9576522/Normal.Miner.Test.zip) and see what it says when it goes to 0 H/s (stops using the GPU) and post it here. That's just a version of my miner compiled with a console and not everything inside it. Only thing I can really think of is that somehow your CUDA crashed or something.

**Comment by Pedrolito666** [comment]
It work for now I can't reproduce lol.

**Comment by Brainshot** [comment]
> > Well most of us are mining etc and eth and only have issues with these two coins and some other ones that require GPU mining. Xmr I never had any issues even now I have miners running from a year ago.
> 
> Yes since they are different miners that should be the case but that's not what I meant, I meant that Microsoft does add things which causes problems (as proven by the xmrig problems Microsoft caused on some computers).
> 
> > I'll post a screenshot but my gpu isn't in use, I have no problem with xmr only with etc, ethash and ubq.
> 
> You can also try mining with this [Normal Miner Test.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9576522/Normal.Miner.Test.zip) and see what it says when it goes to 0 H/s (stops using the GPU) and post it here. That's just a version of my miner compiled with a console and not everything inside it. Only thing I can really think of is that somehow your CUDA crashed or something (though it should just recreate everything).

Hey unam since you have members who talk to you that have huge miners, can you give me their exact settings? I just wanted to see if my settings are wrong or not.
