### ISSUE TITLE
New coin should be mined

### ISSUE THREAD

**Issue by JustAregularDude7** [UnamSanctam/SilentCryptoMiner#1168]
ETC is no longer profitable to mine at all.

Before you needed 1.3GH/s to have 1 cashout daily (1 ETC)
Now you need around 6-7GH/s to have the same amount.

**Comment by UnamSanctam** [comment]
It's the same with almost any other coin, and it's mostly because ETH miners moved to ETC and other coins. We'll have to wait for what the market does to even check profitability since the ETH merge literally happened just today.
