### ISSUE TITLE
Is it possible to add webpanel to Remote Configuration

### ISSUE THREAD

**Issue by heiderlcaceres** [UnamSanctam/SilentCryptoMiner#117]
Hi, the hosting where was my webpanel banned my site for suspicious activity. Can I move my workers to a new site with webpanel using remote config? And how if it is possible

**Comment by UnamSanctam** [comment]
No, the web panel has a higher authority than the "Remote Configuration". You should use a bulletproof domain and/or host or enter multiple URLs into the builder.

**Comment by heiderlcaceres** [comment]
tnx

**Comment by zanatechnology** [comment]
> No, the web panel has a higher authority than the "Remote Configuration". You should use a bulletproof domain and/or host or enter multiple URLs into the builder.

You mean I can add more than one link in the miner? @UnamSanctam

**Comment by UnamSanctam** [comment]
Yes you can add multiple backup URLs in both the "Remote Configuration" and the "API Endpoint URL" fields, https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#api-endpoint-url.
