### ISSUE TITLE
you found bug in compiler

### ISSUE THREAD

**Issue by tigros** [UnamSanctam/SilentCryptoMiner#1171]
my main OS is win7 so tried VS 2017 first, got syntax errors because of string interpolation lines 401 etc of codedom.cs, so tried VS 2019, 2022 and compiles fine. But they're all supposed to be LangVersion 7.3, my guess is 2019/2022 is too forgiving.

just putting that out there.

**Comment by UnamSanctam** [comment]
It's because VS 2017 only supports the strict version of interpolated verbatim strings and not the dynamic token order support added in VS 2019.

**Comment by tigros** [comment]
thanks! idk what the language specs say about it, but that's what you'd expect them all to follow. guess i can close this.
