### ISSUE TITLE
Etc

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#1172]
i guess because of eth now etc mining is not as profitable. What should we mine as gpu instead of etc

**Comment by drissmlds** [comment]
> Everything is at about the same profitability or is decreasing rapidly, because people move to more profitable coins which brings the profitability down. You can see it for example with Ergo (which many have been talking about in issues), it has gone down to almost the exact same profitability as ETC and it's happening to the other ones as well. ETC was the most popular one which is why it went down the most first but every other one is following behind.

what about Monero ??

**Comment by UnamSanctam** [comment]
>what about Monero ??

Won't get affected of course because ETH was only mined by GPUs so the move from ETH to other coins only affects GPU coins. So since Monero is a CPU coin no ETH miner will move to mine that.

**Comment by xanaxsys** [comment]
Do you think Bitcoin Gold will Profitable with some gpus?

**Comment by UnamSanctam** [comment]
> Do you think Bitcoin Gold will Profitable with some gpus?

There isn't very much of a difference, you can check WhatToMine and you'll see.

**Comment by xanaxsys** [comment]
Yes but Grin makes 3$ and etc only 1,5$ so its 50% more profit then etc or no?

> > Do you think Bitcoin Gold will Profitable with some gpus?
> 
> There isn't very much of a difference, you can check WhatToMine and you'll see.

**Comment by UnamSanctam** [comment]
>Yes but Grin makes 3$ and etc only 1,5$ so its 50% more profit then etc or no?

Sure but then you'll have to find a miner that can mine Cuckatoo32.
