### ISSUE TITLE
Please unam fix the 0 hashrate thing

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#1174]
it is a big problem

**Comment by UnamSanctam** [comment]
You're going to have to report something about it like what the computer it's happening on is doing, I can't fix what I can't recreate.

**Comment by drissmlds** [comment]
> You're going to have to report something about it like what the computer it's happening on is doing, I can't fix what I can't recreate. But I am also reworking a lot of the CUDA code to a form that I like more, so maybe that problem miraculously becomes solved as well.

![0](https://user-images.githubusercontent.com/16104583/190861025-e911139a-54da-42e6-9434-997d30f800e9.PNG)
hi what is the problem her why is 0 h/s ??

**Comment by UnamSanctam** [comment]
>hi what is the problem her why is 0 h/s ??

Either can't connect to the pool, doesn't have enough RAM, doesn't have enough cache or doesn't have enough free cores.
