### ISSUE TITLE
Is there an option to switch to alternative cryptocurrencies with the ethash miner?

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentCryptoMiner#1175]
Used remote configuration so I can change the pool and algorithm. Ethereum switched to a new scheme, so now it does not generate income.

**Comment by UnamSanctam** [comment]
The ethminer can currently mine any cryptocurrency that uses the ethash, etchash or ubqhash algorithms.

**Comment by Toxenskiy** [comment]
What cryptocurrency should you switch to?

**Comment by UnamSanctam** [comment]
ETC or UBQ (even maybe ETHPoW), you can see GPU coin profitability here: https://whattomine.com/.

**Comment by Toxenskiy** [comment]
ETC is now mined 5 times less, just like ether

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/192140047-004a9159-24e0-4667-aaa6-df1219f3aaf2.png)

**Comment by UnamSanctam** [comment]
Every cryptocurrency is.
