### ISSUE TITLE
Pastebin 

### ISSUE THREAD

**Issue by svox07** [UnamSanctam/SilentCryptoMiner#1177]
hello unam in pastebin.com I wanted to change xmr to another wallet but it hasn’t changed for more than 3 hours and I wanted to know xmr how can I put the name of the worker Pastebin, otherwise I didn’t find it on the wiki

**Comment by UnamSanctam** [comment]
Make sure that you configuration is correct and that your JSON formatting is correct. To change the worker you'll have to check your pool on how they do it, most pools do it by putting it in the wallet like `WalletAddress.WorkerName` though.
