### ISSUE TITLE
Obfuscation/Encryption !!?

### ISSUE THREAD

**Issue by zanatechnology** [UnamSanctam/SilentCryptoMiner#118]
@UnamSanctam can you just give us a right methods to encrypt the miner and make it FUD bc really as much am searching in Obfuscate methods and algorithms the minimum antivirus detected my miner are 19 otherwise there is no benefit bc all the antiviruses are those are famous type,so  if you help me I'll be thankfull 🙏🏻

**Comment by Dex0xm** [comment]
you have to figure out yourself because there is nothing public that can make your miner fud

**Comment by zanatechnology** [comment]
@Dex0xm How to figure it then?

**Comment by Dex0xm** [comment]
you can use shellter https://www.shellterproject.com/
it might help or you can do it on your own you have the full source code of the miner

**Comment by zanatechnology** [comment]
How I can learn to do it myself @Dex0xm , and sorry for that I'll take a look on shelter but if you told me how ill learn my self in that field of obfuscation and encrypting methods and what it's called in its field

**Comment by Dex0xm** [comment]
Try to see how other crypters or obfuscator works go and see on github find one crypter which u think is good see its source code how it's working modify it according to your needs
