### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by svox07** [UnamSanctam/SilentCryptoMiner#1181]
Hi Unam Windows Defender detects, you can add .exe, C: WD exception.  Manually added .exe, C: and not detected

**Comment by UnamSanctam** [comment]
It already adds the UserProfile and ProframFiles with "Add Defender Exclusions", do you mean that it still gets detected with those? And manually adding it is also different from using commands to do it.

**Comment by Bobdidit69** [comment]
> It already adds the UserProfile and ProframFiles with "Add Defender Exclusions", do you mean that it still gets detected with those? And manually adding it is also different from using commands to do it.

Will windows defender exclusions not work if you use a crypter with startup feature

**Comment by UnamSanctam** [comment]
> Will windows defender exclusions not work if you use a crypter with startup feature

It will still work.

**Comment by Bobdidit69** [comment]
> > Will windows defender exclusions not work if you use a crypter with startup feature
> 
> It will still work.

Thanks are there settings we can play about to reduce detections? Windows defender mainly since it warns before you even download. Is there anywhere you would recommend I should have my program injected to on my crypter?

**Comment by UnamSanctam** [comment]
>Thanks are there settings we can play about to reduce detections? Windows defender mainly since it warns before you even download. Is there anywhere you would recommend I should have my program injected to on my crypter?

You can try, for scantime detections it usually doesn't matter too much since it has most likely detected some common part of the binary (that's how it is with all programs). You should be able to choose any program for the injection really, it's usually only cosmetic (with some exceptions).

**Comment by Bobdidit69** [comment]
> > Thanks are there settings we can play about to reduce detections? Windows defender mainly since it warns before you even download. Is there anywhere you would recommend I should have my program injected to on my crypter?
> 
> You can try, for scantime detections it usually doesn't matter too much since it has most likely detected some common part of the binary (that's how it is with all programs). You should be able to choose any program for the injection really, it's usually only cosmetic (with some exceptions).

Thanks for reply. Its just I saw you say if your crypter (I use data encoder if you have any comments on it please let me know) has an injection tool dont use startup. So am I meant to crypt the downloader file or the miner? I've been having problems with downloading the miner but now I'm realising the downloader would help bypass windows defender. Does defender detect automated exclusions being added or nah?
