### ISSUE TITLE
Miners not appearing

### ISSUE THREAD

**Issue by varysuzuki** [UnamSanctam/SilentCryptoMiner#1182]
I changed my downloaders file from the miner to a rat (the miner was still on startup as for the downloader) and then like 8 people with good gpus appeared (nvidia rtx 3080 - 1060's) but on the pool theres always only like 3 people mining what could be the reason?

**Comment by UnamSanctam** [comment]
Are you using a web panel? Since otherwise there isn't much I can help with (because there isn't any information about the actual miners).

**Comment by shainodev** [comment]
i tried using powershell to see if the miner is open and it wasnt so the web panel wouldnt help

**Comment by UnamSanctam** [comment]
Well then the miner isn't running so you'd have to check the computer to see why.

**Comment by varysuzuki** [comment]
> Well then the miner isn't running so you'd have to check the computer to see why.

hows the miner going?

**Comment by shainodev** [comment]
> Well then the miner isn't running so you'd have to check the computer to see why.

also what pool should i use if i am going to mine UBQ cause 2miners dont support it

**Comment by UnamSanctam** [comment]
> hows the miner going?

Good, I just changed the GPU memory (VRAM) checking from the normal CUDA API to NVML for more accurate results, the CUDA API is the standard but doesn't really return the correct GPU memory values most of the time (thanks Nvidia), so now I changed it to NVML which it's 10 times harder than using the CUDA API which is why it's not normally the standard way, but it's working well.

>also what pool should i use if i am going to mine UBQ cause 2miners dont support it

You can try picopool, which is just the nanopool beta pools.

**Comment by shainodev** [comment]
> Good, I just changed the GPU memory (VRAM) checking from the normal CUDA API to NVML for more accurate results, the CUDA API is the standard but doesn't really return the correct GPU memory values most of the time (thanks Nvidia), so now I changed it to NVML which it's 10 times harder than using the CUDA API which is why it's not normally the standard way, but it's working well.

thats great to hear!
how long will it take for release? same question for the clipper and downloader?

> You can try picopool, which is just the nanopool beta pools.

it has like 63 workers and 23 miners are you sure it wont ban me? and is it better to mine than etc (i think it may be riskier since its like 0.03 usd and not that well known coin and it might dip 100% and im not sure if there are UBQ to XMR exchangers)

**Comment by UnamSanctam** [comment]
>thats great to hear!
how long will it take for release? same question for the clipper and downloader?

Not sure, Windows Defender has added some new sort of weird detection, only Windows Defender is detecting it (all other antiviruses aren't) so I've no idea what they've done. It's even detecting just a simple "Hello World" compiled with gcc as either CobaltStrike or Wacatac.

>it has like 63 workers and 23 miners are you sure it wont ban me? and is it better to mine than etc (i think it may be riskier since its like 0.03 usd and not that well known coin and it might dip 100% and im not sure if there are UBQ to XMR exchangers

Don't think they will, ETC and UQB has about the same profitability at the moment so it doesn't really matter much. Though UBQ only require 1.6GB VRAM which is the advantage.

**Comment by shainodev** [comment]
> Not sure, Windows Defender has added some new sort of weird detection, only Windows Defender is detecting the new miner at scantime (all other antiviruses aren't) so I've no idea what they've done. It's even detecting just a simple "Hello World" compiled with gcc as either CobaltStrike or Wacatac.

try changing the language on the computer, ive seen the detections being based off of the language/region set on the pc

**Comment by UnamSanctam** [comment]
>try changing the language on the computer, ive seen the detections being based off of the language/region set on the pc

Hmm, I'll try building it on one of my VMs set to English and see if there's any difference.

**Comment by shainodev** [comment]
what do u have left to do now?

**Comment by shainodev** [comment]
hello?

**Comment by UnamSanctam** [comment]
I'm trying to fix CUDA/OpenCL disconnecting on a new connection when using an updated ethash implementation. I haven't had time to work on the miner for 3 days due to work so I'm just starting to work on it again.

**Comment by shainodev** [comment]
> I'm trying to fix CUDA/OpenCL disconnecting on a new connection when using an updated ethash implementation right now. I haven't had time to work on the miner for 3 days due to work so I'm just starting to work on it again.

What about the UnamClipper and stuff cant you finish them first?

**Comment by UnamSanctam** [comment]
>What about the UnamClipper and stuff cant you finish them first?

I could but then they would just be instantly detected since it would by large use the same functions for starting programs and such as the miner. So preferably I'd want the miner undetected first.

**Comment by shainodev** [comment]
> I could but then they would just be instantly detected since it would by large use the same functions for starting programs and such as the miner. So preferably I'd want the miner undetected first.

it wont be instantly detected anyway by people uploading it to virustotal?

**Comment by UnamSanctam** [comment]
>it wont be instantly detected anyway by people uploading it to virustotal?

Not really, the miner was largely undetected for a few weeks (depending on your settings of course), and VirusTotal haven't really added too many detections yet either, only problem really is Windows Defenders new weird updates.

**Comment by shainodev** [comment]
> Not really, the miner was largely undetected for a few weeks (depending on your settings of course), and VirusTotal haven't really added too many detections yet either, only problem really is Windows Defenders new weird updates.

Oh. And also how could i possibly exchange or sell ubiq??? theres literally no websites made for it

**Comment by UnamSanctam** [comment]
>Oh. And also how could i possibly exchange or sell ubiq??? theres literally no websites made for it

https://ubiqsmart.com/en/markets

**Comment by shainodev** [comment]
> https://ubiqsmart.com/en/markets

and what about a wallet for phone (IOS)

**Comment by UnamSanctam** [comment]
>and what about a wallet for phone (IOS)

No idea, I neither really use phones nor iOS. Most wallets are browser extensions but I don't think iOS supports that.

**Comment by shainodev** [comment]
> No idea, I neither really use phones nor iOS. Most wallets are browser extensions but I don't think iOS supports that.

Oh alright ill go with guarda wallet. Also should i use 50% Max GPU at all times or 100% Max GPU at all times? (No idle gpu, no stealth, no anti task manager)

**Comment by UnamSanctam** [comment]
> Oh alright ill go with guarda wallet. Also should i use 50% Max GPU at all times or 100% Max GPU at all times? (No idle gpu, no stealth, no anti task manager)

You can go 50% or 90% (better to leave maybe 5%-10%) depending on how much you want it to mine, the upside is the higher hashrate but the downside is that the GPU will become warmer (higher fan sound) and might cause some lag in things such as videos on low-end GPUs.

**Comment by shainodev** [comment]
> You can go 50% or 90% (better to leave maybe 5%-10% free) depending on how much you want it to mine, the upside is the higher hashrate but the downside is that the GPU will become warmer (higher fan sound) and might cause some lag in things such as videos on low-end GPUs.

Hi, i tried the webpanel, and then changed the layout (where the GPU is and so on) and then one and only miner there went from active to error even tho he is still mining and the hashrate is changing

**Comment by shainodev** [comment]
> Alright, error means that it couldn't connect to the pool, so maybe the pool disconnected you or something.

how did it disconnect from the pool just cause i stopped the webpanel and opened the webpanel again?

**Comment by UnamSanctam** [comment]
>how did it disconnect from the pool just cause i stopped the webpanel and opened the webpanel again?

No the web panel won't cause any pool disconnects, only the pool itself will do that.

**Comment by shainodev** [comment]
> No the web panel won't cause any pool disconnects, only the pool itself will do that (or your ISP, internet itself or similar things).

it isnt my pc, idk what could have caused that then

**Comment by UnamSanctam** [comment]
>it isnt my pc, idk what could have caused that then, there should be more specific logs and such

Wouldn't really work that well (and wouldn't really tell you much, would just say disconnected), but the pool can cause disconnects sometimes, nanopool occasionally does that.

**Comment by shainodev** [comment]
> Wouldn't really work that well (and wouldn't really tell you much, would just say disconnected), but the pool can cause disconnects sometimes, nanopool occasionally does that.

is there not anything better to use than picopool to mine ubq? that doesnt ban ofc

**Comment by UnamSanctam** [comment]
>is there not anything better to use than picopool to mine ubq? that doesnt ban ofc

Here are all the pools: https://miningpoolstats.stream/ubiq, I haven't really ever tested any other of them so I'm not really sure.

**Comment by shainodev** [comment]
ubiqpool.io?

**Comment by UnamSanctam** [comment]
You can try it, I remember someone trying it and writing here that they were changing to another one but I don't remember the reason why they did.

**Comment by shainodev** [comment]
What if i use zergpool.com
![image](https://user-images.githubusercontent.com/77803435/194925386-368748bf-f342-46a9-99cc-7f7b1dbf645e.png)
i can make it payout in xmr so i dont need to use exchangers and stuff

**Comment by UnamSanctam** [comment]
Yes you can try it though zergpool did have its occasional problems for me when I was test mining normally before (not with the silent miner).

**Comment by shainodev** [comment]
> Yes you can try it though zergpool did have its occasional problems for me when I was test mining normally before (not with the silent miner).

damn every pool has problems, what about crazypool

**Comment by UnamSanctam** [comment]
>damn every pool has problems, what about crazypool

No idea, but all pools will have some problems such as high share difficulties, disconnects, IP blocks, bad statistics, high payout limits, or high latencies. There aren't really any perfect pools though some will have fewer problems than others.

**Comment by varysuzuki** [comment]
> No idea, but all pools will have some problems such as high share difficulties, disconnects, IP blocks, bad statistics, high payout limits, or high latencies. There aren't really any perfect pools though some will have fewer problems than others.

Alright, what are you currently working on?

And also what c# gui framework do u suggest for me to use what would be the best for making a really modern and good looking cheat loader, i need it to be orginized and stuff and have animations and idk what to use
