### ISSUE TITLE
i have a problem with client when i compile the miner 

### ISSUE THREAD

**Issue by mrrat1337** [UnamSanctam/SilentCryptoMiner#1183]
![image](https://user-images.githubusercontent.com/39533194/190909846-6383ad84-5a43-46f2-b494-810722686195.png)

**Comment by UnamSanctam** [comment]
If you're compiling with XMR "GPU Mining" then it currently doesn't work due to the compiler limitations, though you can try with the beta version (https://anonfiles.com/hdNbS977y9/Silent_Crypto_Miner_Builder_exe) if you want (the compiler is updated there and can compile over 2GB)
