### ISSUE TITLE
Some miners not connecting after restart

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#1184]
is it windows detecting this? or not fully disabled WD deleting it?

**Comment by UnamSanctam** [comment]
Not that I know of, you can try it yourself but I can restart my VMs any amount of times without any detections. Maybe it could be MSRT of whatever it's called.

**Comment by Brainshot** [comment]
> Not that I know of, you can try it yourself but I can restart my VMs any amount of times without any detections. Maybe it could be MSRT of whatever it's called.

I see thanks, i switched to RTM with hope for now and once I start making big I will donate you. Sadly I have lost alot of money lately which is why I couldn't donate.
