### ISSUE TITLE
Do I have to share all the folders when I share files?

### ISSUE THREAD

**Issue by jh0425** [UnamSanctam/SilentCryptoMiner#1187]
After you create the file, a folder called UCompilers is also created. Does this folder also need to be in the same location as the file when sharing?

**Comment by alam0111** [comment]
No. You only need the exe.

**Comment by UnamSanctam** [comment]
Yes as @alam0111 said, you only need to share the .exe. The UCompilers doesn't get removed after build since it's large and thus extracting and removing it on every build wouldn't be very good for performance and would waste disk writes.
