### ISSUE TITLE
do i need to disable watchdog if i am going to make the file a rootkit?

### ISSUE THREAD

**Issue by Azzerzz** [UnamSanctam/SilentCryptoMiner#119]
should i disable startup or watchdog if i am going to make the file a rootkit, and if i do have to delete watchdog, will the file still run on startup even if its a rootkit? or will the  miner just be deleted if pc restarts

**Comment by UnamSanctam** [comment]
Some have reported issues on some computers with the watchdog+rootkit yes. It will always run on startup if "Startup" is enabled.

**Comment by Azzerzz** [comment]
thx
