### ISSUE TITLE
Bug on Fullscreen Stealth

### ISSUE THREAD

**Issue by xanaxsys** [UnamSanctam/SilentCryptoMiner#1195]
Hi, the miner does stop mining if im watching a yt video for exp. but i never used the feature Stealth Fullscreen

![unknown](https://user-images.githubusercontent.com/113245879/191593432-bc8ef332-6647-4b90-ba83-545469260f8b.png)

![unknown2](https://user-images.githubusercontent.com/113245879/191593653-30a9ae0f-5baf-494e-9d1f-9b61321bca20.png)

**Comment by UnamSanctam** [comment]
I think it's an API configuration bug (much of it has been rewritten in my current code so I can't check if there was without going back in backups) where it reads the wrong default value setting from the configuration, but you can add `"stealth-fullscreen": false` into your configuration.

**Comment by xanaxsys** [comment]
Okay Thank you.

But why is here 5 times the same pc? Its because of a new Miner build?
![unknown](https://user-images.githubusercontent.com/113245879/191595407-3c00fcfa-a6a0-4fff-9e5d-749099865f6f.png)

**Comment by UnamSanctam** [comment]
Yes it creates a new one for each build, it has to do that because you can have multiple XMR or ETH miners inside a single miner and not just one each, so each miner build has its own ID for that reason.

**Comment by xanaxsys** [comment]
Ah Okay 👍

**Comment by xanaxsys** [comment]
I use the Username as Password but why it only shows a 0 on 2miners?

**Comment by xanaxsys** [comment]
Okay Thank you
