### ISSUE TITLE
0 hashrates only for GPUs 

### ISSUE THREAD

**Issue by xanaxsys** [UnamSanctam/SilentCryptoMiner#1199]
Hi, as the title says only the GPUs or etc miners have 0 hashrates even my PC with a 1070 has 0 hashrate. I know that I have enough free ram because my gpu has 8 gb and no game or program is blocking my gpu!

**Comment by xanaxsys** [comment]
![Screenshot_2022-09-25-09-25-59-721_com opera touch~2](https://user-images.githubusercontent.com/113245879/192132938-112c291b-e499-43b4-99f9-3ae58f8e8bd2.jpg)

**Comment by UnamSanctam** [comment]
Hmm, with the latest version?

**Comment by xanaxsys** [comment]
Yes

**Comment by xanaxsys** [comment]
I'm using the rootkit maybe that's why the miner not work correctly?

**Comment by UnamSanctam** [comment]
It should still work correctly, I can send you a beta version of the next version in a few hours if I can get it working.

**Comment by xanaxsys** [comment]
> It should still work correctly, I can send you a beta version of the next version in a few hours if I can get it working.

I think now its working but still the Pc username is bugging i use {USERNAME} and its not correct with the Username in my Loader

**Comment by UnamSanctam** [comment]
Can you post a screenshot? If you use username then it should show something like USysadmin (U + username) as the worker name.

**Comment by xanaxsys** [comment]
Always USystem it will use but in my rat they are other names like Admin or malik

**Comment by UnamSanctam** [comment]
Because you're running it as the System user, if you want it to run on the local accounts then disable "Run as System".

**Comment by xanaxsys** [comment]
Okay but Computername schould be work?

**Comment by UnamSanctam** [comment]
Yes because the computer name is global and will say the same on every account.

**Comment by xanaxsys** [comment]
![Unbenannt](https://user-images.githubusercontent.com/113245879/192138616-04ca92a9-2507-43f0-8d1d-84bd64e0165a.png)

but what is this name here?

**Comment by UnamSanctam** [comment]
Probably their username then, looks like either some sandbox, random name or possibly some utf8 name.

**Comment by xanaxsys** [comment]
Hm okay because the exact random name i saw yesterday too

**Comment by xanaxsys** [comment]
Can you maybe add for the worker name {GPUNAME} ?

That would be great too

**Comment by UnamSanctam** [comment]
Yes that has been planned, only issue was that the pool connection gets created before getting the GPU name (so it didn't know the GPU name yet) but it might be possible now that I've restructured things, I'll test and see how it goes.

**Comment by xanaxsys** [comment]
Sounds well keep going that great job 👍

**Comment by xanaxsys** [comment]
Then i use RVN Mining the panel will use the default xmr mining config is there a way to fix that it will use a rvn config?

**Comment by xanaxsys** [comment]
My Vram goes up but i dont see any hashrate or anyworker on rvn 2miners since 15 mins is this normal?

**Comment by Brainshot** [comment]
> Because you're running it as the System user, if you want it to run on the local accounts then disable "Run as System".

If i stop using run it as system will I get more miners?

**Comment by UnamSanctam** [comment]
Sorry for the slow response I have a lot of real life work at the moment.

>Then i use RVN Mining the panel will use the default xmr mining config is there a way to fix that it will use a rvn config?

No it will use the xmrig config by default, though you can code it to use another one in the endpoint.

>My Vram goes up but i dont see any hashrate or anyworker on rvn 2miners since 15 mins is this normal?

RVN has it's problems, mainly because it's in xmrig. But right now UBQ is more profitable and ETC is only around 10% less profitable than RVN, or even more because ETC requires less VRAM.

>If i stop using run it as system will I get more miners?

No you shouldn't, technically it could give more miners because it installs it for all users (so if they change account or if their main account isn't an administrator it will still run).

**Comment by dashboard23** [comment]
> UBQ

How profitable is UBQ compare to ETC ? 
and why I can not find UBQ in your builder ?

**Comment by UnamSanctam** [comment]
> How profitable is UBQ compare to ETC ? and why I can not find UBQ in your builder ?

It changes every day: https://whattomine.com/, right now they're almost the same profitability (though UBQ only uses 1.6GB of VRAM). UBQ is Ubiq which is mined with the ubqhash algorithm.
