### ISSUE TITLE
Does Rootkit Affect Antivirus Detection? 

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentCryptoMiner#12]
?

**Comment by UnamSanctam** [comment]
It shouldn't really though I'm not sure, the rootkit is still experimental so there will probably be bugs (hence why it's marked in red in the builder) so just be aware of that.

**Comment by Toxenskiy** [comment]
well, is he just better at hiding from the user?

**Comment by UnamSanctam** [comment]
Yes the rootkit causes the miner processes, miner usage, startup entry, miner traffic and the watchdog to be completely invisible.

**Comment by Toxenskiy** [comment]
where is your new domain?

**Comment by UnamSanctam** [comment]
Currently it's https://sanctam.su/ though I haven't done much on it.

**Comment by Toxenskiy** [comment]
it is not in the project ..

**Comment by UnamSanctam** [comment]
What?

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/140974253-641f9c14-c7a9-4f55-a828-7e71363dfb68.png)

**Comment by UnamSanctam** [comment]
Yes, why would it be inside the project?

**Comment by Toxenskiy** [comment]
and what is this for? 
![image](https://user-images.githubusercontent.com/55586522/140974795-d7f6f2a3-117b-4520-8fb2-89e6bb08bbfe.png)

**Comment by UnamSanctam** [comment]
> well, you talked so much about him ..

Yes, I am going to upload a demo panel that people can use to test if it works. I was planning on allowing people to use a panel that I host instead (so that they don't have to set it up themselves) but am still unsure whether I should.

> and what is this for? ![image](https://user-images.githubusercontent.com/55586522/140974795-d7f6f2a3-117b-4520-8fb2-89e6bb08bbfe.png)

That's for encrypting the miner command line, as you can see when you look at the miners command line arguments it's all encrypted.

**Comment by Toxenskiy** [comment]
Then three questions.
1) Can you enter your string there?
2) How do I handle the miner launch parameter string in program.cs?
3) How do I add the online downloader back?

**Comment by UnamSanctam** [comment]
1. You can't since it's hardcoded in the compiled miner, it has to be since the only other option would be to send the decryption key in the command line but that's technically more insecure than just hardcoding it.
2. You can see it where it uses it in the `_rRun_ `function.
3. You can re-add the code I sent you before and use that.

**Comment by Toxenskiy** [comment]
at the expense of the third, I do not understand at all how bytes are arranged and what could go wrong.

**Comment by UnamSanctam** [comment]
Can you retranslate that?

**Comment by Toxenskiy** [comment]
I just don't understand how your startup code and bytes work. So I can't add the online downloader myself / something might go wrong. If you do not want to publish here, you can send me the code in the discord zBanned # 6253

**Comment by UnamSanctam** [comment]
Here is the byte array variables that you should download the files into:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/211adc1f956a7e5be427d8f60191f99d840189f1/SilentCryptoMiner/Resources/Code/Program.cs#L151

As you can see in all the `using (var _rarchive_ = new ZipArchive` parts below that it's just extracting the miner files from memory. You can remove all those (line 155 to 229) functions and then just assign the values from the download to `_rxmr_  `and `_reth_ `.

**Comment by Toxenskiy** [comment]
True?
![image](https://user-images.githubusercontent.com/55586522/141508596-7f40d5be-0646-42ac-be6e-2b35a276372a.png)

**Comment by UnamSanctam** [comment]
Yes that would work depending on what your site will return.

**Comment by Toxenskiy** [comment]
When you had a website, I looked at the connection, it downloaded xmrig.txt, and not xmrig.exe, does it somehow affect something?

**Comment by UnamSanctam** [comment]
No file extensions don't do anything by themselves, the bytes of the file will still be the exact same.

**Comment by Toxenskiy** [comment]
I think it's worth encrypting the bytes in base64 and modifying it so that my hosting doesn't ban me).

**Comment by UnamSanctam** [comment]
Sure you could do that, though usually what gets you banned is virus scanners reporting the traffic itself no matter what it actually sends or receives.

**Comment by Toxenskiy** [comment]
can you tell me in which part of the code I need to set conditions for the launch line?

**Comment by Toxenskiy** [comment]
?

**Comment by UnamSanctam** [comment]
In Program.cs the command line arguments are already fully encrypted so to be able to do that you will first have to remove the encryption of the command line arguments in the builder, then move the encryption function into Program.cs (Unamlib_Encrypt), then modify the unencrypted arguments inside Program.cs and then finally encrypt it before starting the miner.

**Comment by Toxenskiy** [comment]
Then such a question, encryption of one and the same text is always the same?

**Comment by UnamSanctam** [comment]
Yes, since it needs to decrypt it inside the actual miner itself. So the only real two options are to either hardcode it or to include the decryption key in the arguments.

**Comment by Toxenskiy** [comment]
and in which part of the code is the variable with the startup string located?

**Comment by Toxenskiy** [comment]
program.cs

**Comment by UnamSanctam** [comment]
https://github.com/UnamSanctam/SilentCryptoMiner/blob/bb4afa492760e3cbbd5c7853b602f95e3fc31d9f/SilentCryptoMiner/Resources/Code/Program.cs#L235
It's `_set_[2]`, which is located in the _rminerset_ array of string array which then gets looped through in that foreach.
The minerset in the builder gets set here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/bb4afa492760e3cbbd5c7853b602f95e3fc31d9f/SilentCryptoMiner/Forms/Builder.cs#L201

**Comment by Toxenskiy** [comment]
And how can you find out in the cycle which miner XMR or ETH is currently running

**Comment by UnamSanctam** [comment]
The first part in `(_set_[1] == _rGetString_("#XID") ? _rxmr_ : _reth_)` so `_set_[1] == _rGetString_("#XID")` will return true if the current miner in the loop is the xmrig or false if it's the ethminer.

**Comment by Toxenskiy** [comment]
Will this work? If there will be an encrypted string with different settings? 
![image](https://user-images.githubusercontent.com/55586522/141682443-0087d727-906d-4c02-a9a0-f7c76978fb16.png)

**Comment by UnamSanctam** [comment]
Yes probably.

**Comment by Toxenskiy** [comment]
So when creating a build, different encryptions are always generated, that is, another encrypted string will not work ..

**Comment by UnamSanctam** [comment]
No the Unamlib_Encrypt which encrypts the command line argument is always the same due to what I said before:
>Yes, since it needs to decrypt it inside the actual miner itself. So the only real two options are to either hardcode it or to include the decryption key in the arguments.

But the other normal string encryption is always different.

**Comment by Toxenskiy** [comment]
ok

**Comment by Toxenskiy** [comment]
is this the encrypted string right? 
new string[] {"AJ+8iYXCEgLOmU0aOGQoPA==","c","TBOPePdNGsC90BCGDcIT4q5Qjts6UTrZ01XTO9noR71yG3o64oA0n8fRIoJLWU3kbIJAxJTpVuemHdrKlN+A2LrZEOG1j/H97cV1BxCAiaLJGyY1fKbkV+nTOggikoxz8dWI3da3gcQT+m2VhaT+BdxxiD8QWmVlaNuxYjwghyUu8zyRwTyvPey23YHg6hNfiSZrAyJcEFaGroEaCavV6vT/G+PF11BulJULDeDe9jz8VCL6SSOfYq21uV8lIw2tSqOCRm7Gqk9AUB8dNdWXeUxgjXP7Fr/vWqLQpr6/Jyt3K9t9Jf2ZNDh26XoTIR4xk4GdG1SjqcEzptnJjaH4sBCHjrSYvEHf8uAYHcxpQCbolesHCcKcgdyg8oJRjOXT4738tFj2hyRePY43u834Z34TKx5ii10JL9ldtY6gKmI=","HBHfkfwnnanOJWCDxlYi9A==","pM5OboWVJvAmQTB/cPq6BAnT6+GRolcmwHCfrrXU/tk="}

**Comment by UnamSanctam** [comment]
I can't know since it's first Unamlib encrypted and then encrypted with normal string encryption on top of that.

**Comment by Toxenskiy** [comment]
how do i get a clean string with just your encryption?

**Comment by Toxenskiy** [comment]
how can I transfer a string from a builder to program.cs

**Comment by UnamSanctam** [comment]
You replace it during the compilation inside Codedom.

**Comment by Toxenskiy** [comment]
How do I get a clean string?

**Comment by UnamSanctam** [comment]
Depend on what you want to do. if you want to send it to me then only encrypt it with Unamlib_Encrypt.

**Comment by Toxenskiy** [comment]
I just can't think of how to edit the parameters in the .cs program with the conditions to turn off encryption, this is very problematic. I think the best option is to encrypt the string in the builder and pass it to program.cs

**Comment by UnamSanctam** [comment]
What are you exactly doing for it to have to edit the parameters inside the program?

**Comment by Toxenskiy** [comment]
Well, I need to change the parameters, if there is a certain string in the name of the PC.

**Comment by UnamSanctam** [comment]
Then the easiest way would probably be to remove the encryption from the builder and then add it into the Program.cs and then encrypt the parameters after you have combined the parameters with your parameter you want to add.

**Comment by Toxenskiy** [comment]
In _set_ [2] is this EncryptString (minerid + argstr.ToString ())?

**Comment by UnamSanctam** [comment]
Yes.

**Comment by Toxenskiy** [comment]
ok

**Comment by Toxenskiy** [comment]
minerid is it like a decryption key?

**Comment by UnamSanctam** [comment]
No, minerid is used by the miner and watchdog to see if any miners are active, it's a randomized version of the old `--cinit-find` (so that other miners can find them easily).

**Comment by Toxenskiy** [comment]
why do you add it to the arguments? EncryptString (minerid + argstr.ToString ())

**Comment by UnamSanctam** [comment]
So that the miner and watchdog can find it to see if that miner is already running.

**Comment by Toxenskiy** [comment]
ok

**Comment by Toxenskiy** [comment]
Little three з))

**Comment by Toxenskiy** [comment]
Кстати, TurtleCoin так и не выросла хотя вы ставили на неё)

**Comment by UnamSanctam** [comment]
Yes v2 got delayed.

**Comment by Toxenskiy** [comment]
Well, she really didn't seem to be popularized. It rallied when other currencies rallied and immediately fell back to the same level.

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/142044856-63089374-4d72-41d1-a691-237e0fdc6a4b.png)

**Comment by UnamSanctam** [comment]
Yes that's how small currencies do, that's why it's also a form of gambling. Currently the "small" "gamble" mining currencies I can see are ArQmA, Kevacoin, Kryptokrona and Haven. You should only mine any altcoin for maybe a month before changing to something else unless you like the project.

**Comment by Toxenskiy** [comment]
You can't argue, but here I think it's worth using the analysis before choosing a coin.

**Comment by UnamSanctam** [comment]
Yes of course, which is why I've never been wrong in choosing an investment so far.

**Comment by Toxenskiy** [comment]
Well, which coin is promising at the moment?

**Comment by UnamSanctam** [comment]
Depends on how long you want to hold the coins, ArQmA will soon release staking nodes I think (so they will become both a PoW (mining) and PoS (staking) coin). Kevacoin is a really small cryptocurrency and their marketing is kind of bad but it does have a lot of potential. Kryptokrona is also a kind of small cryptocurrency but it already has a working "product" (privacy messenger) that works and the coin is promising, I haven't mined any myself but I have heard good things about it from others. Haven is also a good alternative which crashed before (think there was some hack?) but has recovered. So choosing any of those for mining is probably what I would do.

**Comment by Toxenskiy** [comment]
What to choose ssl / tls1.2 or ssl / tls? 
![image](https://user-images.githubusercontent.com/55586522/142204420-141efe33-6097-4f02-8465-68da6dd92e0a.png)

**Comment by UnamSanctam** [comment]
Normal SSL/TLS is fine.

**Comment by Toxenskiy** [comment]
my pool eu1-etc.ethermine.org:5555

**Comment by UnamSanctam** [comment]
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration
```
{
    "url": "stratums://Wallet.Worker@eu1-etc.ethermine.org:5555",
    "algo": "etchash"
}
```

**Comment by Toxenskiy** [comment]
this ssl?

**Comment by UnamSanctam** [comment]
Yes, it has the `stratums` protocol.

**Comment by Toxenskiy** [comment]
Hello, what did you decide about the "Panel" example?
