### ISSUE TITLE
Could not run on Windows 11

### ISSUE THREAD

**Issue by grandepremo** [UnamSanctam/SilentCryptoMiner#120]
Hi! Thank you for the work you put into the development of the silent miner. I tested it on windows 11 and only managed to run it twice. Do I only have this problem? Does the miner need any changes?

**Comment by UnamSanctam** [comment]
No it works on Windows 11, what do you mean by only managed to run it twice?

**Comment by grandepremo** [comment]
So maybe I made a mistake with the setup. Once I have the file ready, I test it on Windows 10 and the miner is always visible in the Web Panel. On Windows 11, on the other hand, I can try to run the miner many times and it does not give any results. The situation is similar on other Windows 11 computers.

**Comment by UnamSanctam** [comment]
Try to change the "Startup" "Filename".

**Comment by grandepremo** [comment]
I always use a different name than the default - unfortunately it still doesn't work. No its not running.

**Comment by UnamSanctam** [comment]
Try building one without "Startup" to see if you're having problems installing or injecting it.

**Comment by grandepremo** [comment]
Now it works :) Thank you :)
