### ISSUE TITLE
Ortak arıyorum (Looking for partners)

### ISSUE THREAD

**Issue by corsair550** [UnamSanctam/SilentCryptoMiner#1201]
TR :  Merhaba eth merginden sonra çok hashrate kasamadım kurban kasma işini bilen youtube videolarını pumplayabilecek ya da kendi yöntemleri olan ortağa ihtiyacım var.
Sunabileceklerim:private sahte yazılimlar . Video editing , landing pages ve daha fazlası.

En: Hi after the eth merge  i couldnt get users at all im looking for someone to provide me some users or can pump up my youtube videos or people who has his own methods .

I can provide: Private fake softwares,Videos , landing pages and more.

detaylar için(For the details)
Discord : ZUR1S#2374

**Comment by Gopnitsa** [comment]
@corsair550  contact with me im send a friend request on discord

**Comment by lunar12a** [comment]
add me lotuscicegi_48871
