### ISSUE TITLE
enabling gpu

### ISSUE THREAD

**Issue by citadin88** [UnamSanctam/SilentCryptoMiner#1203]
hello when i enable the gpu and build it take 100% of my ram i havea  6gb ram why its doing this and it send a error in the log its says not enough memory allocated how is 6gb not enough?

**Comment by UnamSanctam** [comment]
You can download the "old" beta if you want to enable "GPU Mining" (it's red for a reason): https://anonfiles.com/hdNbS977y9/Silent_Crypto_Miner_Builder_exe, but 6GB probably isn't enough RAM to compile the embedded files (one is 30MB and using that much memory is just how the gcc C++ compiler works when compiling it), but you can increase your page file size to compensate.

**Comment by UnamSanctam** [comment]
You need to increase your page file since you don't have enough RAM, but what are you trying to mine with the XMR GPU mining, Ravencoin?

**Comment by citadin88** [comment]
no xmr and i tried raising the page file to the max even and its not working same error.cc1plus.exe: out of memory allocating 2147487743 bytes
cc1plus.exe: out of memory allocating 2147487743 bytes
cc1plus.exe: out of memory allocating 2147487743 bytes
cc1plus.exe: out of memory allocating 2147487743 bytes
cc1plus.exe: out of memory allocating 2147487743 bytes


    Le vendredi 30 septembre 2022 à 18:21:06 UTC+1, Unam Sanctam ***@***.***> a écrit :  
 
 


You need to increase your page file since you don't have enough RAM, but what are you trying to mine with the XMR GPU mining, Ravencoin?

**Comment by UnamSanctam** [comment]
Don't mine XMR with the GPU, it's barely profitable at all, you should mine something like ETC or UBQ if you're going to mine with the GPU.

**Comment by citadin88** [comment]
and can i make it mine diffrent coins in 1file? like cpu xmr and gpu eth in one file 
    Le samedi 1 octobre 2022 à 02:00:17 UTC+1, Unam Sanctam ***@***.***> a écrit :  
 
 


Don't mine XMR with the GPU, it's barely profitable at all, you should mine something like ETC or UBQ if you're going to mine with the GPU.

**Comment by UnamSanctam** [comment]
Yes you can, you can add two miners, check the example settings how I did it with XMR+ETC: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite.

**Comment by b1naryTR** [comment]
@citadin88 have you solved the issue? If you really want to compile the kawpow miner you can send me the config and I can compile it for you.
