### ISSUE TITLE
Notice Something

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1207]
In Some Windows Defender and maybe in servers like datacenter or else and have this icon different then normal WD   i notice many time this defender take no effect from kill or put C  safe side what should i change to take effect with this WD in servers ?
![Windows Defender](https://user-images.githubusercontent.com/20240556/193829370-8249715b-8caf-4b41-8e84-4df916051ebf.PNG)

**Comment by UnamSanctam** [comment]
Hmm, well I have that icon on one of my VMs as well but otherwise maybe that's Microsoft Defender for Endpoint or whatever it's called, but I think the only way to add exclusions for that is through the Group Policy Editor.

**Comment by xanaxsys** [comment]
> Hmm, well I have that icon on one of my VMs as well but otherwise maybe that's Microsoft Defender for Endpoint or whatever it's called, but I think the only way to add exclusions for that is through the Group Policy Editor.

is there a code to add exclusion via Group Policy?

**Comment by tarekxxx** [comment]
Yea there code for it because when i try disabled it not take any effect by miner Disable WD  or exclusions  with  correct commands

**Comment by UnamSanctam** [comment]
>is there a code to add exclusion via Group Policy?

No you can't really change the Group Policies by command in any easy way that I know of, but I don't have any VM with that WD version to test it on either so I can't be sure, the normal commands works fine for me on all my VMs (servers included) so it's most likely due to how the servers are set up.
