### ISSUE TITLE
XMR pool pass

### ISSUE THREAD

**Issue by BITIW** [UnamSanctam/SilentCryptoMiner#1210]
Howdy! I gave a question. I mine on 2miner(example) pool and for every user i need different username(pass). Can i use {RANDOM} or {COMPUTERNAME} to create new pass?

**Comment by UnamSanctam** [comment]
Yes you can, so for example you can change the "Wallet Address" to `WalletAddress.{COMPUTERNAME}`

**Comment by BITIW** [comment]
I think it might help. Thanks

Сб, 8 окт. 2022 г. в 13:38, Unam Sanctam ***@***.***>:
