### ISSUE TITLE
( Stratm. Proxy)Need Help. 🙏/ Нужна помощь.🙏

### ISSUE THREAD

**Issue by Nikolsky22** [UnamSanctam/SilentCryptoMiner#1211]
-----------------------------------------------------------------------
Rus🇷🇺
-----------------------------------------------------------------------
Здравствуйте, очень надеюсь на вашу помощь, уже два дня сижу ломаю голову. 
Купил хостинг на ubuntu, настроил xmrig stratum proxy для майнинга Monero, в итоге получил айпи адрес, к которому должен подключаться майнер. 
Xmrig майнер настраивается через файл конфигурации, там всё просто. 
Вопрос как настроить подключение к прокси стратум через Silent Miner? 
Помогите прошу😿
-----------------------------------------------------------------------
Eng🇱🇷
-----------------------------------------------------------------------
Hello, I really hope for your help, I've been sitting and scratching my head for two days. I bought hosting on ubuntu, set up xmrig stratum proxy for Monero mining, as a result I got an IP address to which the miner should connect. Xmrig miner is configured through the configuration file, everything is simple there. The question is how to set up a connection to a stratum proxy through Silent Miner? Please help me😿

**Comment by UnamSanctam** [comment]
To connect the miner to the proxy server all you have to do is enter the IP and port of the xmrig-proxy server into the miner "Pool", so enter IP:PORT into the "Pool" field in the builder and it will work.

**Comment by Nikolsky22** [comment]
> To connect the miner to the proxy server all you have to do is enter the IP and port of the xmrig-proxy server into the miner "Pool", so enter IP:PORT into the "Pool" field in the builder and it will work. Make sure that the port you use for the xmrig-proxy is port f
orwarded and open as well.

-------
My hands are already really sinking, can you advise what guides? Or people who give a little time? Installed everything correctly. I configured it in the config.json file, opened ports through commands ( ufw allow; iptables ) the miner still does not want to connect to the proxy.

**Comment by UnamSanctam** [comment]
Use an online port checker, do they say that your port for the xmrig-proxy is open?

**Comment by Nikolsky22** [comment]
> Use an online port checker, do they say that your port for the xmrig-proxy is open?

thanks for the advice, I'm grateful to you, you answer more often than xmrig technical support, look at the port is open, it says "port open", I dropped my build and the concentration of the config file below. json , there may be evil lurking somewhere![Screenshot_2022-10-09-00-14-41-347_com.microsoft.rdc.androidx.jpg](https://user-images.githubusercontent.com/115353300/194719603-dc422f48-bb7b-4e5a-9876-dd6652e020a5.jpg)

**Comment by Nikolsky22** [comment]
Test build: 

{
 "access-log-file": null,
 "background": false,
 "bind": [
 {
 "host": "89.208.105.253",
 "port": 4828,
 "tls": false,
 }
 ],
"tls": {
 "cert": "fullchain.pem",
 "cert_key": "privkey.pem",
 "dhparam": null,
 "protocols": null,
 "ciphers": null,
 "ciphersuites": null
},
"colors": true,
 "donate-level": 0,
 "log-file": null,
 "mode": "nicehash",
 "pools": [
 {
 "url": "pool.hashvault.pro:443",
 "user": "88fh2myVEn9betNfX5N6zhfMFcYPrNRj2Ja7Rj7DCtxX6aBWWSn1j2cAvyZpjkyboyN2wPiLVAwXJ64L3TT5JUmz8yuX9hf",
 "pass": "ProxyUser",
 "keepalive": true,
 "variant": -1,
 "algo": "rx/0",
 "tls": true,
 "tls-fingerprint": null
 }
 ],
 "retries": 2,
 "retry-pause": 1,
 "syslog": false,
 "verbose": true,
 "workers": true
}

**Comment by Nikolsky22** [comment]
Xmrig config.json

{
 "access-log-file": null,
 "background": false,
 "bind": [
 {
 "host": "89.208.105.253",
 "port": 4828,
 "tls": false,
 }
 ],
"tls": {
 "cert": "fullchain.pem",
 "cert_key": "privkey.pem",
 "dhparam": null,
 "protocols": null,
 "ciphers": null,
 "ciphersuites": null
},
"colors": true,
 "donate-level": 0,
 "log-file": null,
 "mode": "nicehash",
 "pools": [
 {
 "url": "pool.hashvault.pro:443",
 "user": "88fh2myVEn9betNfX5N6zhfMFcYPrNRj2Ja7Rj7DCtxX6aBWWSn1j2cAvyZpjkyboyN2wPiLVAwXJ64L3TT5JUmz8yuX9hf",
 "pass": "ProxyUser",
 "keepalive": true,
 "variant": -1,
 "algo": "rx/0",
 "tls": true,
 "tls-fingerprint": null
 }
 ],
 "retries": 2,
 "retry-pause": 1,
 "syslog": false,
 "verbose": true,
 "workers": true
}

**Comment by UnamSanctam** [comment]
Try changing your "bind" field to:
```
"bind": [
    {
      "host": "0.0.0.0",
      "port": 4828,
      "tls": false
    },
    {
      "host": "::",
      "port": 4828,
      "tls": false
    }
  ],
```

**Comment by Nikolsky22** [comment]
> Try changing your "bind" field to:
> ```
> "bind": [
>     {
>       "host": "0.0.0.0",
>       "port": 4828,
>       "tls": false
>     },
>     {
>       "host": "::",
>       "port": 4828,
>       "tls": false
>     }
>   ],
> ```


I tried it, nothing, it turns out I compiled a bill with an ip and an open port in the line (pool) I go to the pool and the worker is not displayed there and it is not in the proxy terminal, but the checker says that the miner is running

**Comment by UnamSanctam** [comment]
Can you screenshot the checker and post it here?

**Comment by Nikolsky22** [comment]
tired already, 3 days breaking the brain

**Comment by UnamSanctam** [comment]
Can you take a screenshot of the checker and post it here so that I can see if all the settings are correct? If the xmrig-proxy is working then that should be the problem. Can you also post the xmrig-proxy again since you've changed it now?

**Comment by Nikolsky22** [comment]
![checker](https://user-images.githubusercontent.com/115353300/194720784-d5134b15-ad0e-4a94-b89e-8c8b749eed3f.PNG)

**Comment by Nikolsky22** [comment]
![config.json](https://user-images.githubusercontent.com/115353300/194720796-3007f915-f7b7-4d6e-a56b-bf79a7629bd8.png)

**Comment by UnamSanctam** [comment]
You're trying to connect to xmrig-proxy with "SSL/TLS" enabled in the miner but you have it disabled in xmrig-proxy. So either change `"tls"` inside the `"bind"` in the xmrig-proxy to `true` or disable "SSL/TLS" in the miner.

**Comment by Nikolsky22** [comment]
> You're trying to connect to xmrig-proxy with "SSL/TLS" enabled in the miner but you have it disabled in xmrig-proxy. So either change `"tls"` inside the `"bind"` in the xmrig-proxy to `true` or disable "SSL/TLS" in the miner.

thanks you are the best, the miner is displayed in the proxy terminal and the hash is not working
![image](https://user-images.githubusercontent.com/115353300/194721127-2d1a6aca-8cab-45f5-8a7c-2d70f6207009.png)

**Comment by Nikolsky22** [comment]
and everything, everything is fine, it was worth the wait a bit

**Comment by UnamSanctam** [comment]
Ok great!

**Comment by Nikolsky22** [comment]
long life to you, good luck, more children, all the best to you

**Comment by Nikolsky22** [comment]
❤you best
