### ISSUE TITLE
somtimes when install

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1213]
sometimes when install miner with rootkit in some servers working but XMRig appear as proccess in task manager this bug in rootkit and also the hashrate down 60%

**Comment by UnamSanctam** [comment]
Yes it's something with the rootkit, though hashrate shouldn't go down (because the rootkit doesn't have anything to do with that).

**Comment by tarekxxx** [comment]
![Cap5ture](https://user-images.githubusercontent.com/20240556/194729304-cff93049-7e92-4bcc-9350-fe6748b346fe.PNG)

this happen after rootkit get bugged
