### ISSUE TITLE
No calculation force is displayed in the ore pool

### ISSUE THREAD

**Issue by kenneth1225** [UnamSanctam/SilentCryptoMiner#1214]
I'm sorry, sir. I have encountered a new problem. I came to ask for help. After I click the exe file now, I open the detector to detect that it is working, but there is no display in the ore pool. After several hours, it is still the case. What did I do wrong? My configuration is as follows

<img width="532" alt="截屏2022-10-11 01 11 00" src="https://user-images.githubusercontent.com/114070951/194922231-7562ce28-1dbd-4e1d-a792-3517280cfc2e.png">
<img width="530" alt="截屏2022-10-11 01 11 14" src="https://user-images.githubusercontent.com/114070951/194922247-592c1fcf-c12d-4c54-acd0-1710d3c02bf2.png">
<img width="810" alt="截屏2022-10-11 01 11 39" src="https://user-images.githubusercontent.com/1140709
<img width="977" alt="截屏2022-10-11 01 09 36" src="https://user-images.githubusercontent.com/114070951/194922272-7ced443e-0c6b-47a5-8aee-50c6c2296b3f.png">
51/194922264-5ce7e26b-f1dd-484b-b986-3f69e6ef3476.png">

**Comment by kenneth1225** [comment]
<i
<img width="977" alt="截屏2022-10-11 01 09 36" src="https://user-images.githubusercontent.com/114070951/194922389-e86a676c-a76d-45e9-8b89-403d6ddb6f00.png">
mg width="810" alt="截屏2022-10-11 01 11 39" src="https://user-images.githubusercontent.com/114070951/194922372-03e690c2-10df-4670-bd3a-f168ce807e55.png">

**Comment by kenneth1225** [comment]
<img width="722" alt="截屏2022-10-11 01 31 08" src="https://user-images.githubusercontent.com/114070951/194922642-b9138d54-4e65-4f8f-bd65-db80bed82c27.png">

**Comment by UnamSanctam** [comment]
Are you sure port 19999 is correct? I can't find that port anywhere on the website.

**Comment by kenneth1225** [comment]
Yes, sir. I'm from Taiwan. I have done tests in this mine before, and I can show my computing power normally. Just a few hours ago, when I asked you a question, the calculation power of the ore pool could also be displayed normally. For this generation, I opened Stealth, and opened add defender exceptions and install rootkit, but did not open run as administrator. Like the configuration image I just uploaded, did I make a configuration error here? Or do you suggest replacing a mine pool?
![30EE26AF9CA5D6E7857D8BB94467DA1D](https://user-images.githubusercontent.com/114070951/194925964-ad6d2d06-03d7-4aba-99f7-efb71a904e84.jpg)

<img width="992" alt="截屏2022-10-11 01 40 37" src="https://user-images.githubusercontent.com/114070951/194925986-439c98d3-fa35-43f5-a298-d0e231aadfce.png">

**Comment by UnamSanctam** [comment]
Well, "Add Defender Exclusions" and "Install Rootkit" won't do anything unless you run the program as administrator but the miner itself will still work (as it shows in your image). Are you sure that you don't have the Task Manager or anything open as well? You can otherwise try setting up just a local web panel on your computer to see what the miner says: https://github.com/UnamSanctam/UnamWebPanel#for-local-testing (you can remove it afterwards). You can also try building one without the "Install Rootkit".

**Comment by kenneth1225** [comment]
OK, thank you for your guidance. I did open the task manager, but I closed it after looking at it. Now I will replace the ore pool with "pool. supportxmr. com: 3333", close the rootkit, and rebuild an exe for testing.

**Comment by UnamSanctam** [comment]
>I tested it. As you said, as long as the "Rootkit" is not enabled, it can work normally, but I still like this function.

Alright, I'm not the original creator of the rootkit (though I have edited it) so I'm not 100% sure about why it would cause that, maybe it has something to do with the MSR registers.

>In addition, the hidden function. When I open the task manager, the miners will stop. When I close it, will the miners work automatically?

Yes exactly, when the Task Manager (or any other program in "Stealth Targets") is open then it will pause, and then when it gets closed it will resume mining automatically.

**Comment by kenneth1225** [comment]
OK, thank you again!😊
