### ISSUE TITLE
Please add back the System feature

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#122]
it was useful and didnt allow some or most antiviruses delete the miner

add to system folder feature

**Comment by UnamSanctam** [comment]
Yes it's planned, it was removed since some were having problems with it because some computers have the Windows folder completely protected.

**Comment by masterjek** [comment]
I fully support it. The installations went very well and the miner was delayed for a long time when installing into a folder system32.

**Comment by Brainshot** [comment]
> Yes it's planned, it was removed since some were having problems with it because some computers have the Windows folder completely protected.

Yeah but if it cant install in system folder just make it install in the Startup appdata? i thought thats how your other builders worked

**Comment by UnamSanctam** [comment]
Yes but it's not that easy, since it doesn't always say that it can't install.
