### ISSUE TITLE
Windows defender updated

### ISSUE THREAD

**Issue by Clarkx1** [UnamSanctam/SilentCryptoMiner#1220]
Hi, "windows defender" was updated to version 1.377.33.0 today. The current miner builder cannot be used normally. If you manually add it to the security project, it will still be killed, including the startup item. Secondly, please try to repair the "Rootkit" function😉

**Comment by fakiat** [comment]
I have this issue too, the resulting executable to deploy the miner is detected by windows defender as a trojan:
"Detected: Trojan:Win64/CobaltStrike.SY! MTB"
Is this expected ?
Generated 3 different miner, each time I got this when moving it to the usb storage.
Then I tried on a second computer and the file was deleted by Windows Defender

**Comment by UnamSanctam** [comment]
Yes Syswhispers2 got detected (what does the direct system calls).

**Comment by Brainshot** [comment]
> Yes Syswhispers2 got detected (what does the direct system calls).

When will the update be out?

**Comment by UnamSanctam** [comment]
>When will the update be out?

When I succeed in changing Syswhsipers2 until it's undetected.

**Comment by Brainshot** [comment]
> > When will the update be out?
> 
> When I succeed in changing Syswhsipers2 until it's undetected.

alr cool will be waiting thanks!

**Comment by fakiat** [comment]
Hey, seems it is still detected by Windows Defender : Trojan:Win64/CoinMiner.ES!MTB
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin64%2fCoinMiner.ES!MTB&threatid=2147834882
Pretty new though, updated 7 days after your update
