### ISSUE TITLE
UBIQ

### ISSUE THREAD

**Issue by Ahmedzx555** [UnamSanctam/SilentCryptoMiner#1222]
Do you have a suggestion to convert ubq to usdt or something else?
Because Bittrex bans my country.

**Comment by UnamSanctam** [comment]
Here are all the markets listed on their website https://ubiqsmart.com/en/markets. I guess the easiest would maybe be to use QuickSwap, you might have to bridge the UBQ to the polygon chain using Redshift (https://redshift.ubiqsmart.com/#/transfer) first and then you'd need some MATIC to swap it on QuickSwap for WETH.
