### ISSUE TITLE
How do i use the remote configuration and advanced parameters

### ISSUE THREAD

**Issue by akargokay4** [UnamSanctam/SilentCryptoMiner#1229]
![whatdoineedtodo](https://user-images.githubusercontent.com/98610770/195976805-1ffec029-5d62-4eda-b22e-b932d175dbcb.PNG)

how do i use these 2 setting if i enabled them. can you help me unam ?

**Comment by akargokay4** [comment]
![thisone](https://user-images.githubusercontent.com/98610770/195976900-216f443b-f9ad-47e2-9174-1e54405dac47.PNG)

and the this one too how do i use i dont know

**Comment by xanaxsys** [comment]
Read the wiki then you should be fine

**Comment by akargokay4** [comment]
i will be definetely fine if you send me the link of the wiki. :) @xanaxsys

**Comment by akargokay4** [comment]
> Read the wiki then you should be fine

I read the wiki but there is no information about how do i use the remote configuration thing. It just says you can use remote configuration for bla bla. I created this issue because there is no information about that. Please don't give an answer to a question without being aknowledged.

**Comment by xanaxsys** [comment]
Advanced parameters are for advanced and iq dudes and  remote configuration is for a wen config like over pastebin

**Comment by akargokay4** [comment]
> Advanced parameters are for advanced and iq dudes and remote configuration is for a wen config like over pastebin

I AM NOT ASKING WHEN DO I USE THEM. I AM ACTUALLY ASKING FOR "HOW" DO I USE THEM.

**Comment by xanaxsys** [comment]
You sound really mad why should some body help you?

**Comment by akargokay4** [comment]
dude because you are kidding with me like how can a person ask a question like that. i am mad about that
