### ISSUE TITLE
Assembly issue

### ISSUE THREAD

**Issue by 1eyo** [UnamSanctam/SilentCryptoMiner#1239]
Need help
![image](https://user-images.githubusercontent.com/102640530/197892115-39f0af07-7104-43b0-8cf9-50645091eca9.png)

**Comment by UnamSanctam** [comment]
Remove the letters or spaces from the assembly version numbers.

**Comment by 1eyo** [comment]
> Remove the letters or spaces (non-numbers) from the assembly version numbers.

![image](https://user-images.githubusercontent.com/102640530/197892590-93589471-64d6-4c78-b60e-3df86217c8f7.png)
like this?

**Comment by UnamSanctam** [comment]
Yes, you might need to enter a number into all fields since I believe versioning requires that.

**Comment by 1eyo** [comment]
> Yes, you might need to enter a number into all fields since I believe versioning requires that.

![image](https://user-images.githubusercontent.com/102640530/197892974-6bcc1aa0-e589-4f75-b739-e85f5f90239a.png)
still bro :/

**Comment by UnamSanctam** [comment]
Go in each version number field, press Ctrl+A to select everything and then enter the number to make sure that there's nothing else there.

**Comment by 1eyo** [comment]
> Go in each version number field, press Ctrl+A to select everything and then enter the number to make sure that there's nothing else there.

Got it to work I think, Do you have telegram by any chance bro?

**Comment by UnamSanctam** [comment]
Great, not at the moment I don't.

**Comment by 1eyo** [comment]
> Great, not at the moment I don't.

Ok no worries, does this look correct to you?

![image](https://user-images.githubusercontent.com/102640530/197895596-f6eb67f4-21cb-4f52-b430-e9d2b6cfd704.png)

**Comment by UnamSanctam** [comment]
Yes everything except the pool address, you should use the ETC pool address https://etc.ethermine.org/start.

**Comment by 1eyo** [comment]
> Yes everything except the pool address, you should use the ETC pool address https://etc.ethermine.org/start.

Is this not the pool address? 

![image](https://user-images.githubusercontent.com/102640530/197897324-a3273a69-fa02-4273-aa63-7567219d821d.png)

**Comment by UnamSanctam** [comment]
The US ETC pool address is `us1-etc.ethermine.org:5555`

**Comment by 1eyo** [comment]
> The US ETC pool address is `us1-etc.ethermine.org:5555`

Yup had that typed in as well

![image](https://user-images.githubusercontent.com/102640530/197900120-359d9f60-5a02-49d4-8563-bdbdb7a46d57.png)

**Comment by 1eyo** [comment]
Think I got it to work man thank you! one question tho, Does the cloned application not run while the miner runs? or is it supposed to just be a decoy

**Comment by UnamSanctam** [comment]
It just clones the assembly information data, so that the miner file has the same information (you can for example see it in the "Properties" of the file) as the program you cloned it from.
