### ISSUE TITLE
veery quick question

### ISSUE THREAD

**Issue by Jackysmiths** [UnamSanctam/SilentCryptoMiner#124]
Do you have a discord server? If you do, can you give me the link?

**Comment by UnamSanctam** [comment]
There is one, though I technically neither made it nor own it: https://discord.gg/zbaws3pB

**Comment by Jackysmiths** [comment]
Thankss thats all

**Comment by Jackysmiths** [comment]
well actually. In your server I don't have the permission to verify myself throught the captcha bot

**Comment by Jackysmiths** [comment]
you need to re invite him or let members use / commands

**Comment by Jackysmiths** [comment]
ok now got in

**Comment by UnamSanctam** [comment]
You probably have DMs disabled so I manually added the role now.

**Comment by Jackysmiths** [comment]
oh :V I didn't get any dms but thanks

**Comment by Brainshot** [comment]
> There is one, though I technically neither made it nor own it: https://discord.gg/zbaws3pB

expired link

**Comment by UnamSanctam** [comment]
> > There is one, though I technically neither made it nor own it: https://discord.gg/zbaws3pB
> 
> expired link

Yes I always generate limited links: https://discord.gg/eTQv8Evy

**Comment by Brainshot** [comment]
> > > There is one, though I technically neither made it nor own it: https://discord.gg/zbaws3pB
> > 
> > 
> > expired link
> 
> Yes I always generate limited links: https://discord.gg/eTQv8Evy

cannot verify myself in the server

**Comment by madani2003** [comment]
can you drop a new link i also want to join

**Comment by Jackysmiths** [comment]
https://discord.gg/wkYjUs7C

**Comment by thebesthunta** [comment]
can you drop a link plss

**Comment by 0xZikoo** [comment]
@UnamSanctam Hey, can you give new link please?

**Comment by UnamSanctam** [comment]
Here: https://discord.gg/jbKgsyVD

**Comment by thebesthunta** [comment]
@UnamSanctam hey its telling me that the link is expired,would you mind posting one again

**Comment by UnamSanctam** [comment]
My Discord account just got banned so I can't unfortunately.

**Comment by thebesthunta** [comment]
well shit. do you know if the server went down as well?

**Comment by UnamSanctam** [comment]
I don't think so, though I can't check.

**Comment by Jackysmiths** [comment]
the server got banned I think :v Discord sent me a message about being in some kind of server.

**Comment by thebesthunta** [comment]
Slightly off topic, @UnamSanctam have you thought about making something using the Log4Shell vuln?

**Comment by UnamSanctam** [comment]
Not really, don't have enough time to really start any new projects.
