### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JordiNolla** [UnamSanctam/SilentCryptoMiner#1244]
Can someone help me? When I open the silent miner into a virtual machine it isn't working, even on my main pc, any discord help or smt like that will we apreciated.
Thanks

**Comment by UnamSanctam** [comment]
Run the checker and post what it returns, if it's blank then post your settings.

**Comment by JordiNolla** [comment]
It says 
Watchdog Running: No
Miners: 
GPU's:
NVIDIA GeForce RTX 3050 Laptop GPU
AMD Radeon(TM) Graphics 
Compatible GPU found: True

Then, what's wrong?

**Comment by UnamSanctam** [comment]
Then the miner is not installed, post your settings here. You can press "Save" in the "Main" tab, then you can zip that file and send it here.

**Comment by JordiNolla** [comment]
[Config.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9884449/Config.zip)

**Comment by JordiNolla** [comment]
Done

**Comment by UnamSanctam** [comment]
That's not all the settings you use (most likely you have some setting in "Startup" wrong), but nevertheless you have it set to mine ETH, but ETH moved from PoW to PoS last month which means that you can no longer mine ETH at all and you have to mine something else like ETC. You can find some example settings here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings

**Comment by JordiNolla** [comment]
So the solution is using another crypto currency?
And if it isnt please tell  me wich thing I have wrong, I have been trying by my self like 1 week and Im paranoic xd
If you only want we can use discord or smt or if you want trough here

**Comment by UnamSanctam** [comment]
Yes you can't mine ETH anymore since they changed from mining to staking only. You can download the lite example settings here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite and load it into the builder, those settings work just fine. Then you can change the wallet addresses or anything else you'd want to change and test it.

**Comment by JordiNolla** [comment]
Ok, thanks for telling me, I didn't jnew I couldn't mine wry anymore! I will copy the setting and get some money, even donate some! Have a great day!
