### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#1246]
Hey I have a question when I enter the settings in the startup section like this
Entry name: Update
File name: Program Files\Common Files\System\Updater.exe
Should updater.exe be in this file location?
But it's not there or am I doing something wrong

**Comment by DogusCyk** [comment]
And Run as system is on

**Comment by UnamSanctam** [comment]
It should be `Common Files\System\Updater.exe`
