### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by furkanmetin** [UnamSanctam/SilentCryptoMiner#1247]
ı try dont working can you help me

**Comment by UnamSanctam** [comment]
Sure what is it that isn't working for you? If it's the settings then you can find some example settings here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings to try.

**Comment by furkanmetin** [comment]
ı try example settings still not working

**Comment by furkanmetin** [comment]
https://lifeboxtransfer.com/s/b7e7ec9d-1dc4-4893-adb3-4896ee18352c this is my example

**Comment by UnamSanctam** [comment]
Run the checker that got created together with your miner and post here what it returns.

**Comment by furkanmetin** [comment]
Watchdog Running: Yes
Miners:
--cinit-algo=etchash --pool=stratum://`0x73529e625909144CC1379B5129F16F186A641456`@eu1-etc.ethermine.org:4444  --cinit-max-gpu=100 --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-version="3.0.2" --cinit-idle-wait=5 --cinit-idle-gpu=100 --cinit-id="jpzxcyslzjgbycga"
GPUs:
 NVIDIA GeForce GTX 960
Compatible GPU found: True

**Comment by UnamSanctam** [comment]
Looks like it's working then, though your GPU doesn't have enough VRAM to mine ETC.

**Comment by furkanmetin** [comment]
İ try my friend computer and not still working we try eth classic and monero maybe i am wrong Can you controlle my settings pool gulf.moneroocean.stream:20128 wallet:42gp6Nzjcpvi4iZgkhubHkVuiHytRZf4b3vWMRr9nntP2MStCzsEukRfUCzeKCr7xnBy2wAfozr1wdgb7k5rRHJ3DM2h2nC

**Comment by UnamSanctam** [comment]
It says that you last submitted a share on MoneroOcean 16 minutes ago so that looks like it's working. Run the checker and post what it says here again.

**Comment by furkanmetin** [comment]
ı click web miner because

**Comment by UnamSanctam** [comment]
Run the checker again and post what it says so that I can see if any settings are wrong.

**Comment by furkanmetin** [comment]
Watchdog Running: Yes
Miners:
--cinit-algo=etchash --pool=stratum://0x73529e625909144CC1379B5129F16F186A641456.1@eu1-etc.ethermine.org:4444  --cinit-max-gpu=100 --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-version="3.0.2" --cinit-idle-wait=5 --cinit-idle-gpu=100 --cinit-id="oatiicgnkgnftfqv"
GPUs:
 NVIDIA GeForce GTX 1660 Ti
Compatible GPU found: True

**Comment by UnamSanctam** [comment]
You don't have an XMR miner running there so if you want that then add one, for the ETC miner make sure that you don't have Task Manager or similar programs open on that computer (since you have "Stealth" enabled).
