### ISSUE TITLE
"kill target" and "Stealth target" please!

### ISSUE THREAD

**Issue by zanatechnology** [UnamSanctam/SilentCryptoMiner#125]
hello guys, can anyone provide me a list of kill target and a list of stealth target be fully benefit.
thank you previously 🙏

**Comment by UnamSanctam** [comment]
There are some here:
https://github.com/UnamSanctam/SilentCryptoMiner/discussions/30
and here:
https://github.com/UnamSanctam/SilentCryptoMiner/discussions/28

**Comment by zanatechnology** [comment]
@UnamSanctam  what will happen for example if i added csgo.exe in kill targets and the user played csgo ? will it kill the game and close it or it will kill my miner? i dont understand that bc if it will kill the game directly the gamer will use an anti-virus and kill me otherwise what will happen?

**Comment by UnamSanctam** [comment]
It would kill CSGO, you wouldn't want to add any games into the "Kill Targets".

**Comment by zanatechnology** [comment]
@UnamSanctam
![Capture](https://user-images.githubusercontent.com/89279699/144870862-b5a95660-1d19-4ae2-9517-3cfd2ea4a06c.PNG)

**Comment by UnamSanctam** [comment]
Ah yeah I just copy-pasted it.

**Comment by zanatechnology** [comment]
dudeeeee 🤣
