### ISSUE TITLE
Startup item

### ISSUE THREAD

**Issue by kenneth1225** [UnamSanctam/SilentCryptoMiner#1251]
Hello, I'm facing a problem now. After encrypting your program, the main program can bypass Windows defender. But after running, it will generate a new boot program. Although I have encrypted the miner, he will be killed when the computer restarts, causing him to fail to work normally. Can the startup program and the miner be integrated into one program? And I need your contact information, I can pay you, thank you

**Comment by UnamSanctam** [comment]
The miner and the startup program are the same, are you sure that's the problem?

**Comment by kenneth1225** [comment]
Are you talking about the latest version? I still stay in the last version. First of all, I'm sorry for my poor English. When creating miners, I checked "startup" and defaulted your address in the builder. I encrypt the generated miner and send it to other computers. After running the miner, "startup" will generate a new exe program, which will be killed. As a result, the miner cannot run after the computer restarts

**Comment by kenneth1225** [comment]
I used the previous version, 3.0.0

**Comment by UnamSanctam** [comment]
The previous version adds 1 bit when installed and nothing else (it avoided Windows Defender startup detections due to that), so that shouldn't really do much though the new version doesn't do that. So I would suggest using the new version 3.1.0.

**Comment by kenneth1225** [comment]
Ok, thank you. I'm going to test the latest version now. I want your contact information, such as TG?

**Comment by UnamSanctam** [comment]
I can't use my Telegram at the moment, the number I was using got suspended or something I think. And my Discord got banned for helping with the miner.

**Comment by kenneth1225** [comment]
Sorry, I just ran into a lot of problems in testing the latest version, which can't be expressed in words. That's why I want to talk to you privately

**Comment by kenneth1225** [comment]
For example, it cannot be generated on the desktop, but can only be generated on the disk. Before running the miners, they must also be on disk C, not on the desktop. Including errors reported when I create miners
<img width="589" alt="截屏2022-11-02 01 09 45" src="https://user-images.githubusercontent.com/114070951/199294529-a8c4a8b9-5f27-4ba4-a7dc-d0726ff636fa.png">

**Comment by UnamSanctam** [comment]
That's just saying that you don't have access to "Program Files", to get access to that you'll need to run the program as administrator. And don't build it in any location with spaces in the name because windres (the resource compiler) doesn't support that.

**Comment by kenneth1225** [comment]
Thank you. I have solved the generation problem, but after running it, the program disappeared. Ten seconds after disappearing, I used the detection software, and the miners had already worked. But then the miners stopped working. I didn't open the task manager
<img width="724" alt="截屏2022-11-02 01 18 27" src="https://user-images.githubusercontent.com/114070951/199297905-915d8b46-9378-4961-b555-6e251c1db1ee.png">

**Comment by kenneth1225** [comment]
Do you have any other social accounts? I want to send you a generated video, please check if there are any errors when I generate

**Comment by UnamSanctam** [comment]
You can send it directly to my email: unams@protonmail.com.

**Comment by kenneth1225** [comment]
Thank you very much. I will record the video and send it to your email later
