### ISSUE TITLE
Example setting Ports

### ISSUE THREAD

**Issue by hey000hey** [UnamSanctam/SilentCryptoMiner#1258]
The Lite and Full example settings are both connected to 2miner.com, but the ports are 5 digits (11010 for etc and 12222 for xmr), but the website says the ports are 4 digits (2222 for xmr and 1010 for etc). The miner connects, but I'm curious how you got the ports

**Comment by UnamSanctam** [comment]
Those are the SSL ports, you can find them on the bottom of the same page.
