### ISSUE TITLE
ı try creating ethpow but not working

### ISSUE THREAD

**Issue by furkanmetin** [UnamSanctam/SilentCryptoMiner#1262]

**Comment by furkanmetin** [comment]
Watchdog Running: Yes
Miners:
--cinit-algo=ethash --pool=stratum://`0x5C51BBc205342c2f5E3c126BAf7f8f71Cc2B997E`.Worker1@ethw.2miners.com:2020  --cinit-max-gpu=100 --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-stealth-fullscreen --cinit-kill-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-version="3.1.0" --cinit-idle-wait=5 --cinit-idle-gpu=100 --cinit-id="mtdzwvohqfyvarnt"
GPUs:
 NVIDIA GeForce GTX 960
Compatible GPU found: True

**Comment by UnamSanctam** [comment]
Unless you already know your GTX 960 does not have enough VRAM to mine ETHW, ETHW requires 5.1GB of VRAM (https://minerstat.com/dag-size-calculator) while your GPU only has 4GB.
