### ISSUE TITLE
Isssue coming

### ISSUE THREAD

**Issue by jhaa91156** [UnamSanctam/SilentCryptoMiner#1263]
Sir I have done all steps in rdp and then clicked the. Exe but in the etc ethermine website it's not showing 
Please help 
I also checked in 2 miner website 

And Thanks for providing such great thing free
And how to avoid detection from various antivirus

**Comment by UnamSanctam** [comment]
Run the checker and post a screenshot of it here. To get around antiviruses you'd either need to use a crypter or change the code yourself.

**Comment by jhaa91156** [comment]
Sir before sending i loaded your example setting and replaced with my address but still not showing in 2miner website 
![Screenshot 2022-11-12 223038](https://user-images.githubusercontent.com/118067945/201485607-6f154d08-bc7a-4113-ba3a-370a2770f957.png)

**Comment by UnamSanctam** [comment]
It's because the RDP has a GT 710 as the GPU, it doesn't have enough VRAM to mine ETC.

**Comment by jhaa91156** [comment]
How to check vram , and how i know the victim vram and its solution sir

**Comment by UnamSanctam** [comment]
The GT 710 has either 1GB or 2GB of VRAM, you can find that online. ETC requires at least 3.1GB of VRAM to be mined (https://minerstat.com/dag-size-calculator). So the GPU would have to be replaced with a GPU with at least 4GB of VRAM to be able to mine ETC.

**Comment by jhaa91156** [comment]
is there another nice currency for low vram sir

**Comment by UnamSanctam** [comment]
The lowest VRAM coin that is still pretty profitable is probably UBQ (Ubiq) which requires 1.8GB of VRAM. Which means that the GT 710 can't really mine that either, though the GT 710 would have a really low hashrate anyways because it's not really a GPU meant for any usage. The GT 710 is a card only really meant for simple graphics processing since not all computers have an integrated CPU (GPU inside the CPU) and thus require a simple and cheap GPU.

**Comment by jhaa91156** [comment]
Okay Sir 
Thanks a lot for telling 
can i get sir your personal contact like telegram Or any other as we need tutor like you sir 
My first mine profit I will send you it's my promise sir 

Sir this vram was of rdp that's why I think it has low I will try to send to infected conputer and see what happens 

Also sir crypter where to get and how to use it please upload crypter also if possible

**Comment by UnamSanctam** [comment]
Unfortunately I don't have a Telegram or anything else at the moment. You can find crypters on forums such as Hack Forums or any other popular forums, but they aren't free so you'd have to pay for one. But even then the miner currently has a low amount of detections without a crypter since the last release had a ton of improvements.

**Comment by DerXanRam** [comment]
> Unfortunately I don't have a Telegram or anything else at the moment. You can find crypters on forums such as Hack Forums or any other popular forums, but they aren't free so you'd have to pay for one. But even then the miner currently has a low amount of detections without a crypter since the last release had a ton of improvements.

But todays defender update detectes the miner.

**Comment by UnamSanctam** [comment]
>But todays defender update detectes the miner.

Hmm, not mine and not VirusTotal either. Maybe neither me nor VirusTotal has gotten the update yet.

**Comment by DerXanRam** [comment]
> > But todays defender update detectes the miner.
> 
> Hmm, not VMs and not VirusTotal either. Maybe neither me nor VirusTotal has gotten the update yet.

Yaa ... i got the update few hours ago

**Comment by DerXanRam** [comment]
> > > But todays defender update detectes the miner.
> > 
> > 
> > Hmm, not VMs and not VirusTotal either. Maybe neither me nor VirusTotal has gotten the update yet.
> 
> Yaa ... i got the update few hours ago

also can i askm one question
can I fill address field like these for moneroocean pool to split hash rate

AddressOne%split_amount%AddressTwo

**Comment by UnamSanctam** [comment]
>also can i ask u one question
can I fill address field like these for moneroocean pool to split hash rate
AddressOne%split_amount%AddressTwo

Yes exactly, that's the correct format for splitting the hashrate.

**Comment by DerXanRam** [comment]
> 

ok thanks very much

**Comment by jhaa91156** [comment]
> > > > But todays defender update detectes the miner.
> > > 
> > > 
> > > Hmm, not VMs and not VirusTotal either. Maybe neither me nor VirusTotal has gotten the update yet.
> > 
> > 
> > Yaa ... i got the update few hours ago
> 
> also can i ask u one question can I fill address field like these for moneroocean pool to split hash rate
> 
> AddressOne%split_amount%AddressTwo

What hash rate you getting? And your vram bro

**Comment by jhaa91156** [comment]
Sir Ravencoin when i went through there in 2miners.com they showing for nicehash also , can i use that for cpu mining ?

**Comment by UnamSanctam** [comment]
>Sir Ravencoin when i went through there in 2miners.com they showing for nicehash also , can i use that for cpu mining ?

You mean the NiceHash port? That only increases the share difficulty and nothing else, it only for those that purchase hashrate from NiceHash. Ravencoin cannot (or shouldn't) be mined by CPU anyway and only the GPU.

**Comment by UnamSanctam** [comment]
>but in ravencoin setting you have given cpu mining option

Because it's the xmrig miner and it supports both CPU and GPU mining, but the Ravencoin algorithm itself does not support CPU mining and neither would you want to mine that with the CPU since it would be extremely unprofitable.

**Comment by jhaa91156** [comment]
so monero is only cpu mining currently that too it is now unprofitable ?
this means we have to compulsory infect gpu systems ?

**Comment by UnamSanctam** [comment]
>so monero is only cpu mining currently that too it is now unprofitable ?
this means we have to compulsory infect gpu systems ?

CPU mining overall is pretty much the same in profitability across coins due to many algo-switching and coin-switching miners and pools. But CPU mining is still profitable if you have a large amount of miners, it's not too different from how it has always been in terms of profitability. Though if you want more profit per computer then you would do GPU mining, but normally you do both CPU and GPU mining at the same time. For example mining Monero and ETC at the same time.

**Comment by jhaa91156** [comment]
Yes that right sir . Thanks sir 
and I seen in hackforum.net there is purecrypter but he saying it wont bypass WD , so any crypter you can suggest 
also i want to ask if i start mining both monero and etc and i spead around thousands of computer my identity is not leaked ? and if yes then what are measures to be safe

**Comment by UnamSanctam** [comment]
>Yes that right sir . Thanks sir
and I seen in hackforum.net there is purecrypter but he saying it wont bypass WD , so any crypter you can suggest
also i want to ask if i start mining both monero and etc and i spead around thousands of computer my identity is not leaked ? and if yes then what are measures to be safe

I'm not sure which crypters are good unfortunately, I haven't tested any in a long time. In terms of anonymity then the miner itself will never leak anything, but the mining pools most likely log IPs that visit so if you check your wallet address on their sites then they might be logging the IP you're visiting with. So either use Tor or a good privacy VPN when visiting the pools. Also, the Monero blockchain is private so you don't have to worry much about that (but preferably you should only use that wallet address for mining to the pool and nothing else), but for the ETC blockchain then it's not private (like most blockchains) so it's best to exchange the ETC to Monero before doing anything with it to ensure that you stay anonymous. To exchange the ETC to Monero then you can use a non-KYC exchange or some fast swap like FixedFloat, SimpleSwap or ChangeNOW. Don't forget to use Tor or a VPN when exchanging/swapping as well.

**Comment by jhaa91156** [comment]
Thanks a lot for this deep knowledge sir 
I will note all your points somewhere 
for such things poeple charge high , and you giving miner and info also so quick and deep 
hats of you sir 
if i got any another question i will again ask you 
Thanks again 
good peoples are still there in this world

**Comment by jhaa91156** [comment]
Sir same monero mining i ran in my rdp it working , then i copied that and try to run in my another laptop but its not showing in mining pool 2miner
![Capture](https://user-images.githubusercontent.com/118067945/201961594-5e1b08ea-a36f-40bd-8d9e-a84aad6e5ad2.PNG)

**Comment by UnamSanctam** [comment]
>Sir same monero mining i ran in my rdp it working , then i copied that and try to run in my another laptop but its not showing in mining pool 2miner

Does it show now? You have to find a share first before the pool will show anything. Also make sure that you don't have the Task Manager or any of the other "Stealth Targets" open since then it will pause since "Stealth" is enabled.

**Comment by jhaa91156** [comment]
No Sir its not showing 
Find a share means what i have to do ?

**Comment by UnamSanctam** [comment]
>No Sir its not showing
Find a share means what i have to do ?

It means that you have to mine until you find a share, it depends on your hashrate and the pools share difficulty. How long have you left it to mine and what CPU (and how many cores) does the RDP have? Also make sure that Task Manager isn't open.

**Comment by jhaa91156** [comment]
As you told i clicked yesterday and leave then whole day so that it can find share but still its not showing there in pool
my rdp it is showing 
my laptop not showing it is 2 core
