### ISSUE TITLE
Uninstaller problem

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#1265]
When i open uninstaller that builds with specific miner, it removes the miner from task scheduler. But it doesn't remove miner file(in my condition from "program files" folder). Also it doesn't remove blocking website links from host file. run it with admin permission.

**Comment by UnamSanctam** [comment]
Hmm, I just tested it and both does for me, both the file and the hosts redirects gets removed. It also looks alright in the uninstaller code. Does it only happen on that computer?

**Comment by DerXanRam** [comment]
Now it removes after 5 min. Sorry

and thanks

**Comment by UnamSanctam** [comment]
Alright great.
