### ISSUE TITLE
Diffculty

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#1266]
Now a day cup mining is increasing and xmr difficulty increases. My question is

I have 120Kh/S and before 2 month ago it makes approximately $90/month. So now xmr difficulty is increasing,  does it will affect the income?

**Comment by UnamSanctam** [comment]
Yes, the difficulty means the amount of competition in finding a block that you have, so when the difficulty increases then the chances of you finding a block decreases as well. The difficulty actually just means the total amount of hashrate in the network, and since the block amount per minute is fixed then the difficulty will increase together with the total hashrate to ensure that more blocks aren't found per minute than intended.

**Comment by DerXanRam** [comment]
> Yes, the difficulty means the amount of competition in finding a block that you have, so when the difficulty increases then the chances of you finding a block decreases as well. The difficulty actually just means the total amount of hashrate in the network, and since the block amount per minute is fixed then the difficulty will increase together with the total hashrate to ensure that more blocks aren't found per minute than intended.

So how to over come this situation? Any solution? like increasing hash rate or switching to other coin?

**Comment by UnamSanctam** [comment]
>So how to over come this situation? Any solution? like increasing hash rate or switching to other coin?

Yes either get more miners or increase the usage settings (though that might not always be a good idea, since it will interfere with the user more). You could also switch to another coin though most CPU coins have a similar profitability because algo-switching and coin-switching is quite common, which means that the profitability becomes equalized between popular coins. What most experienced people do is to mine low market cap coins that they believe will increase in price in the future, but of course this can be risky.

**Comment by DerXanRam** [comment]
> > So how to over come this situation? Any solution? like increasing hash rate or switching to other coin?
> 
> Yes either get more miners or increase the usage settings (though that might not always be a good idea, since it will interfere with the user more). You could also switch to another coin though most CPU coins have a similar profitability because algo-switching and coin-switching is quite common, which means that the profitability becomes equalized between popular coins. What most experienced people do is to mine low market cap coins that they believe will increase in price in the future, but of course this can be risky.

Now, my miners work with max CPU:40 and idle CPU:80. increasing usage is not good idea. I will try more miners.
But which coin do u recommend by profitability after XMR?

**Comment by DerXanRam** [comment]
> > > So how to over come this situation? Any solution? like increasing hash rate or switching to other coin?
> > 
> > 
> > Yes either get more miners or increase the usage settings (though that might not always be a good idea, since it will interfere with the user more). You could also switch to another coin though most CPU coins have a similar profitability because algo-switching and coin-switching is quite common, which means that the profitability becomes equalized between popular coins. What most experienced people do is to mine low market cap coins that they believe will increase in price in the future, but of course this can be risky.
> 
> Now, my miners work with max CPU:40 and idle CPU:80. increasing usage is not good idea. I will try more miners. But which coin do u recommend by profitability after XMR?

bro???

**Comment by UnamSanctam** [comment]
>Now, my miners work with max CPU:40 and idle CPU:80. increasing usage is not good idea. I will try more miners.
But which coin do u recommend by profitability after XMR?

There aren't really any special ones I'd recommend right now, maybe mining on Zergpool using the GhostRider algorithm (all coins) could be more profitable.

**Comment by DerXanRam** [comment]
> > Now, my miners work with max CPU:40 and idle CPU:80. increasing usage is not good idea. I will try more miners.
> > But which coin do u recommend by profitability after XMR?
> 
> There aren't really any special ones I'd recommend right now, maybe mining on Zergpool using the GhostRider algorithm (all coins) could be more profitable.

ok Thanks. I will check it.

**Comment by DerXanRam** [comment]
> 

can i mine all coins in moneroocean?

**Comment by DerXanRam** [comment]
> > > Now, my miners work with max CPU:40 and idle CPU:80. increasing usage is not good idea. I will try more miners.
> > > But which coin do u recommend by profitability after XMR?
> > 
> > 
> > There aren't really any special ones I'd recommend right now, maybe mining on Zergpool using the GhostRider algorithm (all coins) could be more profitable.
> 
> ok Thanks. I will check it.

bro??

**Comment by UnamSanctam** [comment]
Most of them yes, though it doesn't have coin-switching like Zergpool.

**Comment by DerXanRam** [comment]
> Most of them yes, though it doesn't have coin-switching like Zergpool.

ok. can u send me remote config example for coin-switching for zergpool?

Thanks

**Comment by UnamSanctam** [comment]
Sure, here I set the payout currency to BTC but you can change it to something else:
```
{
	"algo": "gr",
	"pool": "ghostrider.mine.zergpool.com",
	"port": 15354,
	"wallet": "WALLET",
	"password": "c=BTC,mc=BBC/BTRM/FITA/GSPC/JGC/RTM/YERB",
	"ssltls": true
}
```

**Comment by DerXanRam** [comment]
> {
> 	"algo": "gr",
> 	"pool": "ghostrider.mine.zergpool.com",
> 	"port": 15354,
> 	"wallet": "WALLET",
> 	"password": "c=BTC,mc=BBC/BTRM/FITA/GSPC/JGC/RTM/YERB",
> 	"ssltls": true
> }

What is c= and mc=   ?

**Comment by DerXanRam** [comment]
> `c` is the payout currency and `mc` is the coins it will mine depending on profitability. On the zergpool site there is a miner command line configuration generator on the left side.

I think these coins

`BBC/BTRM/FITA/GSPC/JGC/RTM/YERB`

you mention have good profitability. Right?

**Comment by UnamSanctam** [comment]
I just marked all the coins, zergpool will automatically make you mine the most profitable one of them. You can even remove the `mc` option and it will select all of those automatically. You can see the overall profitability per algorithm on the zergpool site in the right panel.

**Comment by DerXanRam** [comment]
> I just marked all the coins, zergpool will automatically make you mine the most profitable one of them. You can even remove the `mc` option and it will select all of those automatically. You can see the overall profitability per algorithm on the zergpool site in the right panel.

I was watching the diff and profit factor on zergpool. but i can't interpret it.  Can u give some explanation pls?

very sorry for lot of question and disturbing....

![Screenshot (10)](https://user-images.githubusercontent.com/101794261/201526814-aa270de6-36ef-4e49-aa2c-bab6491c49fc.png)

**Comment by UnamSanctam** [comment]
That part is automatic, you don't really have to pay much attention to the coins themselves only the algorithm on the main page.

**Comment by DerXanRam** [comment]
yeaa it say the profit factor mBTC/kh/day..... what does these means ?

![Screenshot (11)](https://user-images.githubusercontent.com/101794261/201527161-3a28f599-e756-4ea6-a62b-5a1962cfd7ec.png)

**Comment by UnamSanctam** [comment]
It means that you would get on average 0.00554 mBTC per day for each KH you have if you mine the GhostRider algorithm.

**Comment by DerXanRam** [comment]
> It means that you would get on average 0.00554 mBTC per day for each KH you have if you mine the GhostRider algorithm.

what ??? for 1k/h, i will get 0.00554BTC on average 😨 .... dud i have 120kh/s on daily avarage.......

**Comment by UnamSanctam** [comment]
You'd have to see what hashrate you'd get with GhostRider first, since they are different algorithms you will also get different hashrates when mining.

**Comment by DerXanRam** [comment]
> It means that you would get on average 0.00554 mBTC per day for each KH you have if you mine the GhostRider algorithm.

Ok thanks very much. you are very kind.
