### ISSUE TITLE
Miner not working

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#1268]
On some computers miner is not starting after the installation. When I check it it's status on scheduled task, it says "queued" and will never starts. but when I test it, Some times it works like 6 min and stops. sometimes it will not. I check it. it is not the windows defender or permission issue. 
For more info the miner attached to conhost

Thanks

**Comment by UnamSanctam** [comment]
Is it on Windows 7 laptops?

**Comment by DerXanRam** [comment]
> Is it on Windows 7 laptops?

no...it is win 10 21H2

**Comment by UnamSanctam** [comment]
It usually says queued if the program is already running and the Task is trying to start a new instance. But it sounds more like you have something weird going on on that computers since obviously that's not a miner issue itself (the Task Scheduler is part of Windows). so I would advice you to repair the Windows of that computer. I have tested the latest miner thousands of times on Windows 7, 8, 10 and 11 VMs and that has never happened to me so far so I would guess that's the reason. And are you using the checker to see if it's working?

**Comment by DerXanRam** [comment]
> It usually says queued if the program is already running and the Task is trying to start a new instance. But it sounds more like you have something weird going on on that computers since obviously that's not a miner issue itself (the Task Scheduler is part of Windows). so I would advice you to repair the Windows of that computer. I have tested the latest miner thousands of times on Windows 7, 8, 10 and 11 VMs and that has never happened to me so far so I would guess that's the reason. And are you using the checker to see if it's working?

Ok I will try to repair the window and try to figure out the issue.....for now I will leave the issue open. cause I will return for results.

Thanks

**Comment by DerXanRam** [comment]
> It usually says queued if the program is already running and the Task is trying to start a new instance. But it sounds more like you have something weird going on on that computers since obviously that's not a miner issue itself (the Task Scheduler is part of Windows). so I would advice you to repair the Windows of that computer. I have tested the latest miner thousands of times on Windows 7, 8, 10 and 11 VMs and that has never happened to me so far so I would guess that's the reason. And are you using the checker to see if it's working?

Bro when i look the miner task scheduler setting it says "configured for windows 7, Windows server 2008 R2"....see the screensgot below


![Screenshot (17)](https://user-images.githubusercontent.com/101794261/201853283-e8967a0e-ed04-4bfd-ae16-6d1281c34da5.png)

**Comment by UnamSanctam** [comment]
Yes that's the default, either that or Vista is the default.

**Comment by DerXanRam** [comment]
Finally I got it. The problem is on the attached program. I build miners for each available attachable process found in miner builder and CMD works the best 👍 . So the problem was on the conhost or the miner unable to attach it self with it.(for those specific computers).
