### ISSUE TITLE
How Can Istart İn Ethermine ?

### ISSUE THREAD

**Issue by nomad1420** [UnamSanctam/SilentCryptoMiner#127]
![ether](https://user-images.githubusercontent.com/95175778/145106282-d8c6ab15-accf-40a3-bc43-b23609e46401.jpg)
Hi Unam Sanctum. I want to mining Etherium.  How Can Start it in Ehermine ?Icant find and fill this area. Can you send me an example ?

 https://ethermine.org/

![1](https://user-images.githubusercontent.com/95175778/145104722-6a5da938-c51d-4bbb-8451-760493373913.jpg)
![2](https://user-images.githubusercontent.com/95175778/145104735-c22d2cf8-5641-46fb-9ebb-83441fedff52.jpg)
![3](https://user-images.githubusercontent.com/95175778/145104742-0561f65f-39d4-4afa-bc77-4cacf19a1b88.jpg)

**Comment by UnamSanctam** [comment]
What you entered was correct (pool: eu1.ethermine.org:4444). Can you run the miner and then run the checker (and post what it says here)?

**Comment by nomad1420** [comment]
I want to use ethermine and this is correct  ?

![sil](https://user-images.githubusercontent.com/95175778/145260089-2affe405-a4d9-404c-813d-fd1f8403948a.jpg)
![sil 2](https://user-images.githubusercontent.com/95175778/145260110-7f3dec31-32eb-4801-837d-a9407bb05c33.jpg)
![sil3](https://user-images.githubusercontent.com/95175778/145260121-839cdd62-d8bb-4377-91c3-019b820edf01.jpg)
![werong](https://user-images.githubusercontent.com/95175778/145260139-4514abde-84f6-42fd-8972-1d9017ed1c54.jpg)

**Comment by nomad1420** [comment]
I fill this type ''ethermine.org:eu1.ethermine.org:4444

Its that correct ? Sorry for my dummyies question ,forgive me :)

**Comment by DogusCyk** [comment]
> I fill this type ''ethermine.org:eu1.ethermine.org:4444
> 
> Its that correct ? Sorry for my dummyies question ,forgive me :)

dc varmi yardim edim

**Comment by DogusCyk** [comment]
> I fill this type ''ethermine.org:eu1.ethermine.org:4444
> 
> Its that correct ? Sorry for my dummyies question ,forgive me :)

Varsa Ekle Doğuş#9236

**Comment by nomad1420** [comment]
> 

dogus 9236 mı dostum ?

**Comment by nomad1420** [comment]
ahm#0116 ekle beni brom

**Comment by nomad1420** [comment]
![image](https://user-images.githubusercontent.com/95175778/145266578-ae52eed9-46fa-415f-9e84-479239da7956.png)

**Comment by DogusCyk** [comment]
bir sayi eksik

**Comment by nomad1420** [comment]
ahm#0116

**Comment by nomad1420** [comment]
> bir sayi eksik

**Comment by nomad1420** [comment]
ahm#0116

> > bir sayi eksik

**Comment by nomad1420** [comment]
ahm# 0116

**Comment by anbu-squad** [comment]
just enter - eu1.ethermine.org:4444

**Comment by anbu-squad** [comment]
"ethermine.org:" -  no need to enter
