### ISSUE TITLE
ETC

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#1273]
hay bro.  I want to mine ETC on moneroocean. previously, as u know, monero needs the miner to specify the algo in the password field like this

`worker∼rx/0`

the above example is, u give 3 months a go for the issue i raised. So i think the moneroocean pool requires these filed. otherwise the miner shows error in API end. so what is for ETC?

Thanks

**Comment by UnamSanctam** [comment]
The algorithm is etchash so it would be `worker∼etchash`

**Comment by DerXanRam** [comment]
> The algorithm is etchash so it would be `worker∼etchash`

Ok thanks bro  And i think etc is the best profitable coin and relatively use low vram like 3.9GB right?

**Comment by UnamSanctam** [comment]
Yes, and it uses 3.1GB of VRAM.

**Comment by DerXanRam** [comment]
> Yes, and it uses 3.1GB of VRAM.

OK thanks very much
