### ISSUE TITLE
Smart mining

### ISSUE THREAD

**Issue by varysuzuki** [UnamSanctam/SilentCryptoMiner#1274]
is there any way you could add some sort of smart mining feature? i mean like it will tweak the usage settings dependent on how the system is, so if the gpu or cpu is at 30% then the miner would be at 50% or something (so in total 80% to not make mining too obvious), when the gpu or cpu is at 10% then the miner will go to 70%. and so on we will just input a number that the miner is not allowed to go over of (in this example 80%).

Or could you also add something that boosts the gpu speed at startup (like killing unnecessary bloat apps, or modifying something that may slow down the pc, or putting the battery save mode to max performance and stuff like that)

Or you could also add something that makes the miner low priority mode and then make the gpu 80% so it wont lag when something else is needing the gpu but it will also use the gpu alot when something else doesn't need it

**Comment by shainodev** [comment]
hello?

**Comment by UnamSanctam** [comment]
>is there any way you could add some sort of smart mining feature? i mean like it will tweak the usage settings dependent on how the system is, so if the gpu or cpu is at 30% then the miner would be at 50% or something (so in total 80% to not make mining too obvious), when the gpu or cpu is at 10% then the miner will go to 70%. and so on we will just input a number that the miner is not allowed to go over of (in this example 80%).

Well not really, the difficulty of calculating the CPU and GPU usage aside it's not really that easy to do. 

>Or could you also add something that boosts the gpu speed at startup (like killing unnecessary bloat apps, or modifying something that may slow down the pc, or putting the battery save mode to max performance and stuff like that)

It's possible though it won't really make much difference overall.

>Or you could also add something that makes the miner low priority mode and then make the gpu 80% so it wont lag when something else is needing the gpu but it will also use the gpu alot when something else doesn't need it

Unfortunately this isn't possible with GPUs, you can't really know when something else needs the GPU or anything like that.

**Comment by varysuzuki** [comment]
thank you
