### ISSUE TITLE
How do I mine ETC on already infected PCs

### ISSUE THREAD

**Issue by wnetMC** [UnamSanctam/SilentCryptoMiner#1276]
Hello, I've been using this for a while and I have the web panel running as well. I want to thank you for making this open source first of all.

I currently have around 50 computers mining for me, but the problem is when I installed the miner, I only added one miner, Monero. If I want to make the switch to ETC, can I just change the config in the web panel, or do I have to reinstall the miner on the boxes?

**Comment by shainodev** [comment]
> Hello, I've been using this for a while and I have the web panel running as well. I want to thank you for making this open source first of all.
> 
> I currently have around 50 computers mining for me, but the problem is when I installed the miner, I only added one miner, Monero. If I want to make the switch to ETC, can I just change the config in the web panel, or do I have to reinstall the miner on the boxes?

u cant just switch to etc by changing the config cause etc uses ethminer, and when u built it with only monero then the miner only has xmrig
