### ISSUE TITLE
Can I mine with NiceHash (BTC)

### ISSUE THREAD

**Issue by wnetMC** [UnamSanctam/SilentCryptoMiner#1278]
Hello, does anyone know if I can mine Bitcoin with Nicehash using this?

**Comment by UnamSanctam** [comment]
You can use the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite and then replace the póol and wallet addresses. You'll mine Monero with the CPU and ETC with the GPU.

First open the rx/0 (Monero miner) and replace the info:
Pool: `randomxmonero.auto.nicehash.com:443`
Wallet: Your NiceHash wallet address

Then open up the etchash miner and replace the info:
Pool: `etchash.auto.nicehash.com:443`
Wallet: Your NiceHash wallet address

**Comment by wnetMC** [comment]
> You can use the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite and then replace the póol and wallet addresses. You'll mine Monero with the CPU and ETC with the GPU.
> 
> First open the rx/0 (Monero miner) and replace the info: Pool: `randomxmonero.auto.nicehash.com:443` Wallet: Your NiceHash wallet address And enable "NiceHash Mining".
> 
> Then open up the etchash miner and replace the info: Pool: `etchash.auto.nicehash.com:443` Wallet: Your NiceHash wallet address

Thank you so much, this is exactly what I needed.
