### ISSUE TITLE
How do I add a second api endpoint url through the web panel

### ISSUE THREAD

**Issue by wnetMC** [UnamSanctam/SilentCryptoMiner#1279]
title

**Comment by UnamSanctam** [comment]
Separate them by a comma, so `"api-endpoint: "url1,url2"`

**Comment by wnetMC** [comment]
> Separate them by a comma, so `"api-endpoint: "url1,url2"`

In the configurations section?

**Comment by UnamSanctam** [comment]
Yes in the "Configurations" or "Remote Configuration", whatever you use. Best would be to put it in the "Remote Configuration" if you have one since if you specify a backup API endpoint through the panel then the miner will only know about it as long as the first web panel is running (and until their next restart).

**Comment by wnetMC** [comment]
> Yes in the "Configurations" or "Remote Configuration", whatever you use. Best would be to put it in the "Remote Configuration" if you have one since if you specify a backup API endpoint through the panel then the miner will only know about it as long as the first web panel is running (and until their next restart).

Okay, can you give me a remote config with every possible setting if possible?

**Comment by UnamSanctam** [comment]
All the options can be found here:
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration

**Comment by wnetMC** [comment]
> All the options can be found here:
> 
> https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration
> 
> https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration

 Okay so do if I have a dual miner (etc and xmr), do I need to create a different remote config in the miner builder for both of the miners (etc and xmr)?

Im asking because I see an algorithm field in the remote config.

**Comment by UnamSanctam** [comment]
Yes that's correct.

**Comment by wnetMC** [comment]
Okay, thank you very much for your help.
