### ISSUE TITLE
Does running an infecter file on an already infected computer delete the ancient miner?

### ISSUE THREAD

**Issue by wnetMC** [UnamSanctam/SilentCryptoMiner#1281]
title

**Comment by UnamSanctam** [comment]
It overwrites it if you have the same "Startup" settings yes.

**Comment by wnetMC** [comment]
Do the computers need to reboot in order for the new miner to overwrite the old one or evrything will work after I just run the file?

**Comment by UnamSanctam** [comment]
The miner file will be overwritten but both miners will be running (because the new miner won't kill the old one since the injected miners are hidden) so it would be best to restart since then only the new miner will be running.

**Comment by wnetMC** [comment]
Okay thanks.
