### ISSUE TITLE
KASPA Coin (KAS)

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1282]
Is it worth mining? better than UBQ? safer than UBQ? if so what pool should I use?

**Comment by UnamSanctam** [comment]
It uses the kHeavyHash algorithm so you can't mine it with this miner (and out of all miners I only believe lolminer and gminer supports it).

**Comment by shainodev** [comment]
> It uses the kHeavyHash algorithm so you can't mine it with this miner (and out of all miners I only believe lolminer and gminer supports it).

ohh okay. also just so i dont ask the same question twice could you check your email
