### ISSUE TITLE
How do I change my API Endpoint if it got suspended by my host

### ISSUE THREAD

**Issue by wnetMC** [UnamSanctam/SilentCryptoMiner#1284]
Hello, how do I change my api endpoint if it got suspended by my host? I set the endpoint in the builder but I also have remote configuration so could I just set it in there and it will work?

**Comment by UnamSanctam** [comment]
Yes you can change it in your "Remote Configuration" and it will work.

**Comment by wnetMC** [comment]
Okay, it seems like it works for my old miners but I infected around 7 computers yesterday and they are not showing up. Is it possible they are simply offline and once they come online they will show up?

**Comment by wnetMC** [comment]
^^

**Comment by UnamSanctam** [comment]
Yes, it would be best to wait a day or two since most people keep their computers turned off most of the time.

**Comment by wnetMC** [comment]
okay but they should show up if they get turned on?

**Comment by UnamSanctam** [comment]
Yes, when the miners start they will contact the "Remote Configuration" and change the endpoint URL to what you specified and then contact the web panel.

**Comment by wnetMC** [comment]
Alright perfect. Thanks!

**Comment by wnetMC** [comment]
Okay, so it turns out there was a typo in my remote config, I fixed it and all the slaves appeared as expected, thanks!
