### ISSUE TITLE
GPU Mining not working

### ISSUE THREAD

**Issue by GhostShot3** [UnamSanctam/SilentCryptoMiner#1286]
CPU Mining is working, but GPU mining isn't

**Comment by UnamSanctam** [comment]
You can use the example settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings, they definitely work.

**Comment by GhostShot3** [comment]
I want to setup on nanopool

**Comment by UnamSanctam** [comment]
Yes then you can just change the pools in the example to nanopool.

**Comment by GhostShot3** [comment]
Now is working on CPU but not working on GPU

**Comment by GhostShot3** [comment]
![12312](https://user-images.githubusercontent.com/18537420/204622646-67109ed2-0dc4-4e30-9a63-e37a433a54ff.png)

**Comment by UnamSanctam** [comment]
What isn't working? Or rather how are you checking?

**Comment by GhostShot3** [comment]
HWInfo CPU Usage, CPU is hitting 100% after 5 min, but the GPU is not

**Comment by UnamSanctam** [comment]
Not sure which specific usage HWiNFO measures, try MSI Afterburner and see. Not sure if MSI Afterburner is in the "Stealth Targets" but I don't think so from looking briefly.

**Comment by GhostShot3** [comment]
On MSI Afterburner GPU usage is showing 100%

**Comment by UnamSanctam** [comment]
Alright then it's working, not all programs monitor the GPU usage that the miner uses (Task Manager doesn't).
