### ISSUE TITLE
NiceHash not find any algoritm

### ISSUE THREAD

**Issue by TopSpammer** [UnamSanctam/SilentCryptoMiner#129]
Good afternoon, I have such a problem, I compile the build, it appears in the nicehash`s dashboard, but does not see the miner's algorithms and does not show profit at all
![изображение](https://user-images.githubusercontent.com/67190825/145399260-ec4a7c0d-9c82-454e-bb3e-c23e84bd9860.png)
![изображение](https://user-images.githubusercontent.com/67190825/145399469-97d78ef8-ba4c-4b94-88a1-eb6283171052.png)
![изображение](https://user-images.githubusercontent.com/67190825/145399555-390d8a99-50e2-4bed-bf5d-afafd0a82bc0.png)
I don't understand what the problem is with this fucking site

**Comment by UnamSanctam** [comment]
Where does it not see the algorithm? In the screenshot it says it (RandomX), it looks like it's showing hashrate.

**Comment by TopSpammer** [comment]
> Where does it not see the algorithm? In the screenshot it says it (RandomX), it looks like it's showing hashrate.

yep, but it in computer version, in mobile nicehash it write "0 algoritm"
![изображение](https://user-images.githubusercontent.com/67190825/145401007-0db8caac-97c6-44bf-9914-de2f461b8c2a.png)
Even if the problem is not in the algorithm and not in nicehash, then what is it?

**Comment by TopSpammer** [comment]
> 

But the fact is that mining does not work, if you look at the estimated profit in computer nicehash, then it is zero

**Comment by UnamSanctam** [comment]
It says that it's mining in the screenshot, it looks like the estimated earnings is calculated by the average hashrate over the last 24 hours, I'm guessing you haven't been mining for 24 hours so the estimation will be really low which could be why.

**Comment by TopSpammer** [comment]
> 

![изображение](https://user-images.githubusercontent.com/67190825/145402811-b5578b5a-b299-4f61-ac4a-eb1b022aaedc.png)
Lol, in fact, I wrote to you and it started mining, a strange thing is this nicehash, but it worked, the problem was that even on the chart it was not displayed that it started working

**Comment by TopSpammer** [comment]
Thank you very much for your promptness
