### ISSUE TITLE
One builder file not working many pc...

### ISSUE THREAD

**Issue by Kaka9437** [UnamSanctam/SilentCryptoMiner#1291]
@UnamSanctam UnamSanctam i did a build file in builder and put it in 3 pc but it is not working. When i put file in my personal pc it's working and if i put that file several pc only one pc is running mining and shows in the pool other pc has installed but not showing list in mining pool.One file works only in one pc??

**Comment by UnamSanctam** [comment]
Which pools are you using and what worker name did you enter?

**Comment by Kaka9437** [comment]
Im using nanopool and type this format :address of xmr.worker1/password123... And build file then install same file in 3 pc but working only one pc and pool shows online worker only 1...where go other 2pc mining...that didn't showed...

**Comment by UnamSanctam** [comment]
Because that's not how worker names work, if you enter `worker1` as the worker name then on the pool the 3 miners will appear under the same worker name. So the worker1 you see is all 3 miners combined.

**Comment by Kaka9437** [comment]
@UnamSanctam if i install worker 1 file 100 pc can that still mining it combined under worker 1 in the pool ??

**Comment by UnamSanctam** [comment]
Yes it will combine all 100 miners hashrate under one worker, if you want each miner to have its own worker then you need unique worker names for each one. In the builder you can enter `{COMPUTERNAME}` as the worker name and it will use the computers name as the worker name which most of the time is unique.

**Comment by Kaka9437** [comment]
If i use worker 1 build file in 1000 pc can still working mining on 1000 pcs ??

**Comment by Kaka9437** [comment]
@UnamSanctam Can I use one build file in running 1000 pc ??

**Comment by Kaka9437** [comment]
Ok bro thankyou

**Comment by Kaka9437** [comment]
@UnamSanctam bro when I'm install file on pc it running and became offline after few mins...and hashrate is becaming low ....why it's problem happening....

**Comment by UnamSanctam** [comment]
Run the checker and post what it says, also post your builder settings.

**Comment by UnamSanctam** [comment]
It probably didn't succeed in installing then, post your "Startup" tab settings.

**Comment by Kaka9437** [comment]
Where i found startup tab setting??

**Comment by UnamSanctam** [comment]
In the builder there is a "Startup" tab where you enabled the "Watchdog", take a screenshot of your settings there and post it here.
