### ISSUE TITLE
the exe gets dead

### ISSUE THREAD

**Issue by floof989763** [UnamSanctam/SilentCryptoMiner#1293]
the exe i made through the silent crypto miner accidently stops mining and i dont know why. it was running perfectly for about 4 to 5 hours and then it showed me offline on the pool but it was still mining and then it accidently stopped mining
.

**Comment by UnamSanctam** [comment]
Run the checker and post a screenshot of it.

**Comment by mrwick008** [comment]
I am also facing same issues floof bhaiya

**Comment by UnamSanctam** [comment]
Run the [MINER]-checker.exe while your miner is running and post a screenshot of it here.

**Comment by floof989763** [comment]
Watchdog Running: Yes
Miners:
--algo=rx/0  --url=xmr-asia1.nanopool.org:14433 --user="45qwC12Ri68RYJnuoDSi7AY4HCdcuKPL21JBiCSWixsjCtnmWTgtr7Z3FZ7zSNxMNbZwLDBWVVmq9QL63iVk688BVcf7ykD" --pass="" --cpu-max-threads-hint=80 --cinit-remote-config="" --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-version="3.1.0" --tls --cinit-idle-wait=5 --cinit-idle-cpu=50 --cinit-id="hpziwvnbgsbwfswo"
GPUs:
 Intel(R) Iris(R) Xe Graphics
Compatible GPU found: False

**Comment by floof989763** [comment]
the exe is running but the mining is too slow

**Comment by floof989763** [comment]
in the pool mostly it shows me offline when i am online

**Comment by UnamSanctam** [comment]
Then it's because of your CPU, the pool only shows hashrate when you find a share, and nanopool has a 400 000 share difficulty which means that if you have a slow CPU then it won't show shares very often. Or you have some "Stealth" program open like Task Manager which pauses the miner.

**Comment by floof989763** [comment]
exactly like this my hashrate is 0

>

**Comment by jhaa91156** [comment]
> I am also facing same issues floof bhaiya

bhai telegram id kya hai

**Comment by floof989763** [comment]
yes

**Comment by floof989763** [comment]
https://t.me/flooftg

**Comment by floof989763** [comment]
sir my cpu is good but still thw hashrate shows 0
![Screenshot 2022-12-10 164726](https://user-images.githubusercontent.com/120167143/206853100-f005d2e1-87a1-4e0c-9ca8-92c888d55513.jpg)
![Screenshot 2022-12-10 164746](https://user-images.githubusercontent.com/120167143/206853103-469c96d8-0e39-48ad-9fde-3d3b813cda83.jpg)
my system is mining but at a very very low speed

**Comment by floof989763** [comment]
please tell me what to do

**Comment by floof989763** [comment]
> 

https://t.me/flooftg

**Comment by UnamSanctam** [comment]
What CPU do you have? And are you running it as administrator? The pool hashrate is also not the same as the miner hashrate: 
https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining
https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-the-hashrate-shown-on-the-pool-different-from-what-i-expect-or-from-what-is-shown-in-the-web-panel

**Comment by floof989763** [comment]
> Then it's because of your CPU, the pool only shows hashrate when you find a share, and nanopool has a 400 000 share difficulty which means that if you have a slow CPU then it won't show shares very often. Or you have some "Stealth" program open like Task Manager which pauses the miner.

hello sir! 
i checked there was task manager running in the background. i have closed it, will now the issue of slow mining be resolverd
?

**Comment by floof989763** [comment]
> What CPU do you have? And are you running it as administrator? The pool hashrate is also not the same as the miner hashrate: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-the-hashrate-shown-on-the-pool-different-from-what-i-expect-or-from-what-is-shown-in-the-web-panel

yes sir i am running it as the administrator

**Comment by floof989763** [comment]
i have intel i5 core 11th generation

**Comment by UnamSanctam** [comment]
Yes if you had Task Manager open in the background the the miner would have been paused since you have "Stealth" enabled. So if you've closed it then it should start mining again.

**Comment by floof989763** [comment]
sure sir thank you soo much

**Comment by floof989763** [comment]
sir and please tell me one more thing .... which pool should i use?

**Comment by UnamSanctam** [comment]
2miners, nanopool or MoneroOcean usually.

**Comment by UnamSanctam** [comment]
You haven't entered a worker name, that's why.

**Comment by floof989763** [comment]
but sir its showing me in the list as worker one and offline ....... and it had shown me online several times

**Comment by UnamSanctam** [comment]
In the checker you sent you did not enter worker1 as the worker name, so it won't show any worker name when you mine.

**Comment by floof989763** [comment]
![Uploading Screenshot 2022-12-10 164746.jpg…]()

**Comment by floof989763** [comment]
![Uploading Screenshot 2022-12-10 164746.jpg…]()

**Comment by UnamSanctam** [comment]
Wait for it to upload before pressing "Comment".

**Comment by floof989763** [comment]
okay sir i will look into that
sir can you please contact me on tg or any other social platform.https://t.me/flooftg

**Comment by floof989763** [comment]
![Screenshot 2022-12-10 164746](https://user-images.githubusercontent.com/120167143/206854942-351d5d0b-5606-4a70-bad5-42c9ef34063d.jpg)

**Comment by mrwick008** [comment]
My telegram id is Adamppi please text me

**Comment by floof989763** [comment]
sir hashrate again went to 0

**Comment by floof989763** [comment]
![Screenshot 2022-12-10 164726](https://user-images.githubusercontent.com/120167143/206855736-04ed2b07-ecac-4723-977e-2c954b2fab91.jpg)

**Comment by UnamSanctam** [comment]
It will only show hashrate when you find a share so it won't show constant on the pool. Since that's how pools work.

**Comment by UnamSanctam** [comment]
Yes that would be normal, on pools you only really look at the average hashrate over a long time, such as the "Average Hashrate for last 6 hours", but you also need to mine that long for it to be accurate. You can run that 1 exe on any amount of computers really.

**Comment by floof989763** [comment]
that you soo much sir. that was really helpful by your side. i am soo gratefull

**Comment by floof989763** [comment]
sir do you have any other social media platforms like telegram where i can contact you?

**Comment by UnamSanctam** [comment]
No problem, don't have any other platforms right now since I got banned from Discord and lost my Telegram number.

**Comment by floof989763** [comment]
no problem sir. i am really very thankful to you.

**Comment by floof989763** [comment]
hello sir!
I was randomly looking at the pool. most of the people have a very high hash rate of around 200k, and about 100 workers which have the same hashrate, what should i do to achive such a high rate?

**Comment by UnamSanctam** [comment]
No, they just have multiple miners under one worker name. There's no single CPU that can reach 200k, and Monero (RandomX) is a CPU-"only" coin so no GPU. You can find benchmarks for different CPU's here: https://xmrig.com/benchmark (by default it shows it mining on all threads/cores meaning 100%).

**Comment by mrwick008** [comment]
> > I am also facing same issues floof bhaiya
> 
> bhai telegram id kya hai

Bro t.me/Adamppi

**Comment by mrwick008** [comment]
> No, they just have multiple miners under one worker name. There's no single CPU that can reach 200k, and Monero (RandomX) is a CPU-"only" coin so no GPU. You can find benchmarks for different CPU's here: https://xmrig.com/benchmark (by default it shows it mining on all threads/cores meaning 100%).

Sir what is web panel....and what is the importance of that... please explain me

**Comment by UnamSanctam** [comment]
> Sir what is web panel....and what is the importance of that... please explain me

It's something optional you can host (https://github.com/UnamSanctam/UnamWebPanel) to monitor your miners, it's not necessary and fully optional.

**Comment by floof989763** [comment]
hello sir!
sir i m really not getting how to install your web panel even after reading the information you have given. please help me here sir
