### ISSUE TITLE
Remote Web panel configuration

### ISSUE THREAD

**Issue by tentacen** [UnamSanctam/SilentCryptoMiner#1295]
Is it possible to set API Endpoint URL in pastebin remote configuration file? My case is: when my host will die i will not have acces to the domain anymore and wont be able to use panel but if there would be an option to change API Endpoint URL on pastebin then i would set a new one for the pannel to connect

**Comment by UnamSanctam** [comment]
Yes you can add `"api-endpoint": "API Endpoint URL"` into the "Remote Configuration" and it will change what current API Endpoint URL(s) it uses.

**Comment by tentacen** [comment]
Ok thanks, also i dont know if u saw my last emails about the miners getting disconnected, meaby my crypt is just fud for windows defender

**Comment by UnamSanctam** [comment]
Yes I saw, sorry forgot to respond. That could be it, if other antiviruses detects it during runtime then the injected miner might survive but would go offline on the next restart (since it would remove the startup and miner file) which could be one reason they stop after some time.

**Comment by tentacen** [comment]
Ok, no worries. I guess i my target should be only windows defender users for now. And my goal to crypt runtinme for other av's. Btw these 3 miners that i showed you are still running (i guess those are windows defender users.

**Comment by tentacen** [comment]
![image](https://user-images.githubusercontent.com/120128395/206874935-afd3b410-b284-4daf-8688-6133d5116265.png)
![image](https://user-images.githubusercontent.com/120128395/206874944-a5c399d7-8c55-4019-97db-cad3930d5ddb.png)
Is this correct? can i just paste it anywhere

**Comment by UnamSanctam** [comment]
Yes that would work.

**Comment by mrwick008** [comment]
@tentacen can i contact you? Sir
