### ISSUE TITLE
Miner error

### ISSUE THREAD

**Issue by tentacen** [UnamSanctam/SilentCryptoMiner#1297]
![image](https://user-images.githubusercontent.com/120128395/206906951-18fc7264-77eb-41ae-8688-bc0868a1e834.png)
It happened couple times now. Why?

**Comment by UnamSanctam** [comment]
Error means that it cannot connect to the pool, that pool are you using?

**Comment by tentacen** [comment]
> Error means that it cannot connect to the pool, that pool are you using? And that might also be a VM.

I use 2miners pools
for xmr and etc

**Comment by UnamSanctam** [comment]
Then either that computer can't contact 2miners (blocked IP or something like it), the connection settings are wrong, or that's a sandboxing VM (which is what it looks like). That one is actually offline and has been for 7h (which is why it says that), it was only online for 1 API call.
