### ISSUE TITLE
Why my pool is not showing active worker

### ISSUE THREAD

**Issue by mrwick008** [UnamSanctam/SilentCryptoMiner#1298]
Why my pool is not showing active worker please help me what i am doing wrong... correct me
![Uploading Screenshot_20221211-201824.jpg…]()

**Comment by UnamSanctam** [comment]
Wait for it to finish uploading before pressing "Comment". But did you enter a worker name when making the miner?

**Comment by mrwick008** [comment]
> Wait for it to finish uploading before pressing "Comment". But did you enter a worker name when making the miner?

Sir it doesn't give the option for worker name i am mining for XMR only

**Comment by mrwick008** [comment]
Sir are you saying like this
![Uploading IMG-20221211-WA0002__03.jpg…]()

**Comment by mrwick008** [comment]
![IMG-20221211-WA0002__03](https://user-images.githubusercontent.com/120228720/206912043-e0113991-4e8f-40fb-b60b-96f270019497.jpg)
Sir are you saying like this

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by mrwick008** [comment]
> Yes exactly.

Ok sir i have done like this....sir does pool take 1 or 2 hour to update ? Worker name and hashrates?

**Comment by UnamSanctam** [comment]
First you have to find a share, which depends on your hashrate (and the pool share difficulty, which for nanopool is 400 000). And then the pool statistics has to update which can be around 30 minutes for nanopool sometimes.

**Comment by mrwick008** [comment]
Thanku so much sir....for your help 
![Screenshot_20221211-210852__01](https://user-images.githubusercontent.com/120228720/206913137-5812b89b-b1ba-4d7c-88ab-7619cc3e382b.jpg)

**Comment by UnamSanctam** [comment]
No problem, glad that it worked out.
