### ISSUE TITLE
how to change default language in code?

### ISSUE THREAD

**Issue by FreeM1ne** [UnamSanctam/SilentCryptoMiner#1299]
how to change default language in code?

**Comment by UnamSanctam** [comment]
First move the new default language up first in the language combobox, then change the `en` here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/1df8bae3c9b7f68cdf7b2602414d9884b7f5ca42/SilentCryptoMiner/Forms/Builder.cs#L32
And also change the `en` here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/1df8bae3c9b7f68cdf7b2602414d9884b7f5ca42/SilentCryptoMiner/Forms/Builder.cs#L653

**Comment by FreeM1ne** [comment]
not work

**Comment by UnamSanctam** [comment]
What did you enter instead of `en`?

**Comment by FreeM1ne** [comment]
pl

**Comment by UnamSanctam** [comment]
And you also moved Polish to the top of the "Language" combobox? Technically that's all you should have to do I believe.

**Comment by FreeM1ne** [comment]
yes

**Comment by FreeM1ne** [comment]
![image](https://user-images.githubusercontent.com/83845767/206925489-feaa5abb-9248-4da6-a2d8-3eacb72a1148.png)

**Comment by FreeM1ne** [comment]
![image](https://user-images.githubusercontent.com/83845767/206925514-9a47b4f0-2d32-4606-8004-74affe4e1414.png)

**Comment by UnamSanctam** [comment]
Try adding `TranslateForms();` at the end of the Builder `Form1_Load`, it might not be running the translate function on start since it's normally not needed.

**Comment by FreeM1ne** [comment]
it worked, that's what I wanted to do, I just didn't know which function to insert

**Comment by UnamSanctam** [comment]
Great.
