### ISSUE TITLE
Is process killer good?

### ISSUE THREAD

**Issue by T3Toxic** [UnamSanctam/SilentCryptoMiner#13]
I don't really know what to kill with it so would it be worth finding out what I should kill?

**Comment by UnamSanctam** [comment]
Yes, you can kill some antivirus UI .exe's and things like that.

**Comment by Brainshot** [comment]
> 
> 
> Yes, you can kill some antivirus UI .exe's and things like that.

hey unam i was wondering if you had a good list for process killer for antiviruses 

thanks in return

**Comment by UnamSanctam** [comment]
Here are some that other people have told me and also what I have gathered myself, I have not tested all of them to see if they are correct: `SecHealthUI.exe,MsMpEng.exe,NisSrv.exe,mbam.exe,mbamtray.exe,avp.exe,avpui.exe,AVGSvc.exe,afwServ.exe,avgnt.exe,ProductAgentUI.exe,MMSSHOST.exe,McShield.exe,mcafee.exe`

**Comment by Brainshot** [comment]
> 
> 
> Here are some that other people have told me and also what I have gathered myself, I have not tested all of them to see if they are correct: `SecHealthUI.exe,MsMpEng.exe,NisSrv.exe,mbam.exe,mbamtray.exe,avp.exe,avpui.exe,AVGSvc.exe,afwServ.exe,avgnt.exe,ProductAgentUI.exe,MMSSHOST.exe,McShield.exe,mcafee.exe`

Yeah thats my list that i made

only thing thats messing is avast and no idea how to stop avast, since it doesnt allow for you to end its process

**Comment by UnamSanctam** [comment]
Yeah it's your list but I added the Windows Defender processes. Most antiviruses runs as "drivers" meaning you cannot kill them.
