### ISSUE TITLE
4 Hour sleep?

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1301]
https://github.com/UnamSanctam/SilentCryptoMiner/blob/1df8bae3c9b7f68cdf7b2602414d9884b7f5ca42/SilentCryptoMiner/Resources/Code/watchdog.cpp#L45

why does this sleep for 15000 + 15 SECONDS SO 15 = 15010 seconds or 250 minutes or 4 hours?

**Comment by UnamSanctam** [comment]
It's not milliseconds, it's specified in what Microsoft calls ticks, which is 100 nanoseconds. And to convert 100 nanoseconds into milliseconds you need to multiply it by 10000.

**Comment by varysuzuki** [comment]
> It's not seconds, it's specified in what Microsoft calls ticks (though it's an ambiguous term), which is 100 nanoseconds. And to convert milliseconds into units of 100 nanoseconds you need to multiply it by 10000. So it does 15000 milliseconds + STARTINTERVAL (in milliseconds) and then multiplies it by 10000 to convert the delay in milliseconds into ticks (100 nanoseconds).

but why is it like that in watchdog but not in miner.cpp?

**Comment by UnamSanctam** [comment]
It's the same in miner.cpp, the default value for $STARTDELAY is 15000 milliseconds.
https://github.com/UnamSanctam/SilentCryptoMiner/blob/1df8bae3c9b7f68cdf7b2602414d9884b7f5ca42/SilentCryptoMiner/Classes/Codedom.cs#L325
