### ISSUE TITLE
how does this work?

### ISSUE THREAD

**Issue by Aszpect** [UnamSanctam/SilentCryptoMiner#1302]
any vids to show how this works? or an explanation to say how to set up?

**Comment by UnamSanctam** [comment]
You can find out what each option does on the wiki: https://github.com/UnamSanctam/SilentCryptoMiner/wiki.

**Comment by Aszpect** [comment]
i set it up and i made a download thing and then is it meant to show me if a guy is using it? because i downloaded it on a vm and it shows absolutely nothing about anything

**Comment by UnamSanctam** [comment]
No, hence why it's called silent. You can use the checker to see if it's running on the local computer or you can set up a web panel (https://github.com/UnamSanctam/UnamWebPanel) if you want to actually monitor the miners.

**Comment by Aszpect** [comment]
what checker tho?

**Comment by UnamSanctam** [comment]
The one that gets built together with the miner, you'll see one called [MINERNAME]-checker.exe in the same folder.

**Comment by Aszpect** [comment]
![image](https://user-images.githubusercontent.com/120339805/206939481-e252cd23-b8f6-44d6-af87-862935d2a4d0.png)

on here?

![image](https://user-images.githubusercontent.com/120339805/206939499-09041649-08a0-4c7d-adcc-e5a480136d08.png)

and also whats all this?

and last, how do i get a pool and what password in the connection tab?

**Comment by UnamSanctam** [comment]
When you build the miner .exe at the end then you will also build a checker .exe. For a pool you'll have to find one that you'd like to use, the common ones are 2miners, nanopool and MoneroOcean. You can find some example settings here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings. And you can see what the "Advanced" options do here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#advanced.

**Comment by Aszpect** [comment]
can we speak on discord?

**Comment by Aszpect** [comment]
or element

**Comment by UnamSanctam** [comment]
I'm banned on Discord for helping people with the miner, and I don't have Element. At the moment people usually contact me through my mail: unams@protonmail.com, though it's not a very fast method of communication.

**Comment by Aszpect** [comment]
do i put gulf.moneroocean.stream as the pool and the wallet address as my metamask wallet? and what does it mean by password?

**Comment by UnamSanctam** [comment]
Yes URL:PORT (need mining port, there are several ones), for the wallet you enter the wallet address for a wallet that supports whatever cryptocurrency you're mining. If you're mining Monero then you can't use MetaMask of course so use a Monero wallet, the Monero GUI Wallet is the most common in terms of standalone wallets but Monero is also in some multi-wallets. Every pool uses the password field differently, most pools don't use it but MoneroOcean uses it for the worker name, so enter a worker name into it.

**Comment by Aszpect** [comment]
so what password do i have to put into this? 
![image](https://user-images.githubusercontent.com/120339805/206944037-3f83ee44-f00c-4b68-a14d-ad1fb156dc73.png)

**Comment by UnamSanctam** [comment]
If you're using MoneroOcean then enter the worker name you want, it can just be something like `worker`. If you're using some other pool like 2miners, nanopool and others then leave it blank.

**Comment by Aszpect** [comment]
and the pool is gulf.moneroocean.stream ?

**Comment by Aszpect** [comment]
whyd this show up when i try building it? 
![image](https://user-images.githubusercontent.com/120339805/206946073-c84cb909-1869-40d7-935d-259e7bd3f0c2.png)

**Comment by UnamSanctam** [comment]
>and the pool is gulf.moneroocean.stream ?

Depends on what port you want, the default non-SSL is 10128, so it would be: `gulf.moneroocean.stream:10128`

>whyd this show up when i try building it?

Are you trying to build it in System32 or something? Not sure where the resource writer writes it, but try starting the builder as administrator.

**Comment by Aszpect** [comment]
im not trying to build it in system32 im building it in C:\Users\AppData\Local\Temp\Temp2_Silent.Crypto.Miner.Builder.zip but it just keeps saying that

**Comment by Aszpect** [comment]
bro nah

**Comment by Aszpect** [comment]
didnt mean to complete it

**Comment by UnamSanctam** [comment]
Extract the builder into a folder first and also build the miners into that.

**Comment by Aszpect** [comment]
extract what builder tho?

**Comment by UnamSanctam** [comment]
The miner builder that you're currently putting all the settings in.

**Comment by Aszpect** [comment]
wdym extract it?

**Comment by UnamSanctam** [comment]
From the zip file it's in if you haven't, extract the miner builder .exe into a folder and then also build the miners into that folder as well.

**Comment by Aszpect** [comment]
![image](https://user-images.githubusercontent.com/120339805/206948796-50dc729c-cd4e-434e-8cde-548c2b03837e.png)
![image](https://user-images.githubusercontent.com/120339805/206948811-9b696b97-39b8-4ef7-baf2-3ca7e73bbf09.png)

**Comment by UnamSanctam** [comment]
Yes, that's a zip file, if you were to "run" it there then it will temporarily extract it into a random temporary folder and do things from there which you don't want to do. So first extract the zip archive and then directly run the unzipped .exe.

**Comment by Aszpect** [comment]
like this? 
![image](https://user-images.githubusercontent.com/120339805/206949389-11ccd7b5-77b8-4ca7-9752-ba8d3c1f28a8.png)
![image](https://user-images.githubusercontent.com/120339805/206949405-f50a5478-4652-46d2-8340-c0826c3edb32.png)

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by Aszpect** [comment]
if a guy installs it, do they have to install the whole folder or just the exe?

**Comment by Aszpect** [comment]
how do i see if someone has their pc on, and they are running it, and the miner is running

**Comment by UnamSanctam** [comment]
Either run the checker on that computer, or you'd have to use the web panel.

**Comment by Aszpect** [comment]
wdym run a checker on the pc? how do i run a checker on the pc?

**Comment by UnamSanctam** [comment]
You'd have to run the checker .exe that gets built with together the miner on that computer, so you'd need to have access in some way to that computer. The other method is to host a web panel (https://github.com/UnamSanctam/UnamWebPanel) that the miners connects to and reports information about the mining and computer.
