### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ZSIkK** [UnamSanctam/SilentCryptoMiner#1303]
Hey can you add kaspa and i have a Issue when i want to create a build with ravencoin on gpu it appears a message that i have to less memory space but when i increase my Windows pagefile IT dont Change anythink.

**Comment by UnamSanctam** [comment]
It will always say that information message every time you build, that's why it's just an information box and not warning or an error. Or do you mean that you get a compiler error when you build it? I probably won't consider adding KHeavyHash (Kaspa algorithm) for quite some time since I don't have much free time at the moment.

**Comment by ZSIkK** [comment]
> It will always say that information message every time you build, that's why it's just an information box and not warning or an error. Or do you mean that you get a compiler error when you build it? I probably won't consider adding KHeavyHash (Kaspa algorithm) for quite some time since I don't have much free time at the moment.

I get a Compiler error when i want to build it but when i increase my Windows page file dont solve tje Problem

**Comment by UnamSanctam** [comment]
How big is your pagefile? And did you restart the computer?

**Comment by ZSIkK** [comment]
> How big is your pagefile? And did you restart the computer?

I have try it with 200 gb and yes

**Comment by UnamSanctam** [comment]
Don't make it 200GB, but I tested on a VM with 2GB of RAM and a 12 GB pagefile worked for me.

**Comment by ZSIkK** [comment]
> Don't make it 200GB, but I tested on a VM with 2GB of RAM and a 12 GB pagefile worked for me.

Okay thank you for your help  bro maybe my hdd is broke or somethink
