### ISSUE TITLE
updater part not installed

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1309]
updater part not installed i dont know why there no anti virus  appears in proccess or in machine totally but cant execute updater part what should i do ?

**Comment by UnamSanctam** [comment]
What do you mean by updater part?

**Comment by tarekxxx** [comment]
Google\Chrome\updater.exe i mean i dont found in my case program files only there program files (x86) because i cant install it even no anti virus at all only ccleaner !

**Comment by tarekxxx** [comment]
its there but not working  what should problem it was working but suddenly not working what should i check in this case even checker say not installed !

**Comment by UnamSanctam** [comment]
First of all, try with the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite and change nothing in them to make sure it has nothing to do with yoursettings.

**Comment by tarekxxx** [comment]
same settings working on many Computers and there no problem but i dont know what should be problem even dialer.exe not appear

**Comment by tarekxxx** [comment]
but what the problem in my settings with this specific pc ?l

**Comment by UnamSanctam** [comment]
Do you use the rootkit? Try disabling it, the r77 rootkit is very complex and could cause something. Also check if your "Startup" settings are any different from the example settings.

**Comment by tarekxxx** [comment]
![Screenshot (156)](https://user-images.githubusercontent.com/20240556/207139842-10266c0d-d377-46f9-b2bf-089bcb6894f4.png)
there the different from my setting in this specific pc and example without root and defender + disable WU + enabled startup administrator but without rootkit it will be easy to detect i think but thanks for helping unam

**Comment by tarekxxx** [comment]
![Screenshot (156)](https://user-images.githubusercontent.com/20240556/207140537-aebda450-4140-4639-8f1a-b23f0833e840.png)

there the different from my setting in this specific pc and example without root and defender + disable WU + enabled startup administrator but without rootkit it will be easy to detect i think but thanks for helping unam
