### ISSUE TITLE
I've mined for around 30 minutes with a test build on my machine, and no workers showing on pool

### ISSUE THREAD

**Issue by abc7895556** [UnamSanctam/SilentCryptoMiner#131]
I've mined for around 30 minutes with a test build on my machine, and no workers showing on pool

![image](https://user-images.githubusercontent.com/35849826/145559233-2a9a7342-31c8-4391-9441-d360e0951603.png)

**Comment by UnamSanctam** [comment]
The time for it to appeardepends on your hashrate, the pool difficulty, luck and the pool update interval. https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining

**Comment by stefexec** [comment]
i got the same problem. if i start the normal xmrig everything shows up in a matter of seconds. With this tool CPU is at 80% as instructed but no shares arrive

**Comment by UnamSanctam** [comment]
If it's using CPU then it's working correctly, what share difficulty are you mining at?
