### ISSUE TITLE
Workers all disappeared from Nanopool and new ones aren't showing up.

### ISSUE THREAD

**Issue by tyler-time** [UnamSanctam/SilentCryptoMiner#1310]
Basically what the title says. I thought it was a Windows Defender thing but after reinstalling it, I'm still not getting any of them to show up on my Nanopool dashboard. The checker says they're running too.

**Comment by UnamSanctam** [comment]
You mean the worker names aren't appearing? Can you post a screenshot of the checker?

**Comment by tyler-time** [comment]
I mean the worker names aren't showing up and/or I'm not getting a Hashrate at all.

https://i.imgur.com/BvQCyoC.png

**Comment by UnamSanctam** [comment]
And you don't have any of the "Stealth Targets" open such as Task Manager? How long have you been mining? You also don't need to use your email address as the password, you can use whatever you want, such as `Password123`. I don't think you've been banned at least since I've never seen nanopool do that before.

**Comment by tyler-time** [comment]
No, no remote config or web panel. I'm gonna try a different pool and also try a different wallet address on Nano.

**Comment by tyler-time** [comment]
Same address on a different pool seems to be working so I guess maybe Nanopool banned my wallet. Reached out to their support to see if there's any way of confirming this but I guess I'll be switching to this new pool in the meantime (noooo my .11 XMR nanopool payout ;~;)

**Comment by UnamSanctam** [comment]
Alright, haven't seen a ban before but it's definitely possible then, maybe nanopool has changed something, hope the support will explain something or at least be able to pay out the current amount.

**Comment by tyler-time** [comment]
I'm not really experienced enough to comment on whether it's odd or not but my average hashrate was like under 10kH/s, I can't imagine I was making waves.

**Comment by mrwick008** [comment]
> Same address on a different pool seems to be working so I guess maybe Nanopool banned my wallet. Reached out to their support to see if there's any way of confirming this but I guess I'll be switching to this new pool in the meantime (noooo my .11 XMR nanopool payout ;~;)

How do you spread your exe? Sir for mining
