### ISSUE TITLE
Gpu nvidia bug infections 

### ISSUE THREAD

**Issue by Sindicate100** [UnamSanctam/SilentCryptoMiner#1311]
Hello , i try to run the .exe on 3 pcs , 1 that have amd , and 2 that have nvidia . My problem is on the nvidia pcs,when i start the miner  the gpu go 100% but i dont see the worker on https://etc.2miners.com/  but on the amd when i  open i see the worker. Also on nvidia its work  only the cpu  for some reason . when i open the .exe i see the worker only on https://xmr.2miners.com/      (cpu)

**Comment by UnamSanctam** [comment]
Hmm, well I'm sure it works on Nvidia since that's the only GPU I have, so that's the only one I can test it on. What GPUs are they and what driver version do they have? Also, what are you using the check the Nvidia usage, MSI Afterburner?

**Comment by Sindicate100** [comment]
yeah gpu mining its work only on some Nvidia. can you drop your telegram to sent you photo of the settings and everything? maybe its my issue

**Comment by UnamSanctam** [comment]
You can send it to my email: unams@protonmail.com. Make sure that the Nvidia cards have enough free VRAM to mine ETC as well.
