### ISSUE TITLE
watchdog error

### ISSUE THREAD

**Issue by blueskycloud137** [UnamSanctam/SilentCryptoMiner#1313]
watch dog gcc error

**Comment by UnamSanctam** [comment]
Post the specific error here.

**Comment by NaNasuuAkiaa** [comment]
I will
![image](https://user-images.githubusercontent.com/72937334/223518740-ce8a235c-fd87-4893-9b3c-31b33e526bf2.png)
So, as seen here, on compiling, the watchdog doesnt compile because of windresa aparently

**Comment by UnamSanctam** [comment]
Did you build it yourself or are you using the pre-built binary? And check the log (that is says in your error) for the error message. windres is the resource compiler.

**Comment by NaNasuuAkiaa** [comment]
I downloaded the prebuilt version from the release page, yes, and the log just says this:
`C:\Users\x\x\x\x\UCompilers\gcc\bin\windres.exe: preprocessing failed.`
this is why i didnt attach it at first

**Comment by UnamSanctam** [comment]
Hmm, do you already have some version of GCC installed on your computer or something? That's the only thing I can really think of, do you have a virtual machine or something to try and build it on? Or a separate computer?

**Comment by NaNasuuAkiaa** [comment]
I have gcc 12.2.0, i can uninstall it if you want, and I could try to build it on an other computer, but not today sadly
