### ISSUE TITLE
ETC not mining

### ISSUE THREAD

**Issue by tentacen** [UnamSanctam/SilentCryptoMiner#1315]
![image](https://user-images.githubusercontent.com/120128395/207349495-5c06b2db-a7b5-4dae-b8b8-158ebb5fc0ec.png)
Today miners arent mining etc, but xmr they do. Here you se a worker with gpu and cpu active.
This is the cpu running:
![image](https://user-images.githubusercontent.com/120128395/207350026-026d54bc-a463-417a-a7d8-8eabe1fe0707.png)
And here is gpu:
![image](https://user-images.githubusercontent.com/120128395/207350121-168171b2-93ab-4e54-bf55-9cd46bbc680c.png)
I know it takes time to register a share on a pool but it has been running for 4 hours now
![image](https://user-images.githubusercontent.com/120128395/207351021-48e372c9-b16c-4ee7-b9ac-afa3f0dd671d.png)
![image](https://user-images.githubusercontent.com/120128395/207351181-32d09038-e550-45cb-91c3-d63ebba7980e.png)

**Comment by tentacen** [comment]
Does 2miners ban ? That is what i am using
It doesnt make any sense, 2 gpu's are running for past 5 hours and no hashrate detected on the pool

**Comment by tentacen** [comment]
https://www.klgrth.io/paste/8aqzm/raw these is my cfg for etc

**Comment by UnamSanctam** [comment]
How many GPU miners, and what GPUs are they? What miner version? Have they been mining before? And "Active" doesn't necessarily mean that they have enough free resources (for example VRAM) to mine.

**Comment by tentacen** [comment]
> How many GPU miners, and what GPUs are they? What miner version? Have they been mining before? And "Active" doesn't necessarily mean that they have enough free resources (for example VRAM) to mine.

yea i figured out that the worker was playing a game that i dont have on stealth target list

**Comment by tentacen** [comment]
Btw Unam what can i do to my crypt for it to be better? Should i encrypt the code somehow or obfuscate it?

**Comment by tentacen** [comment]
and if my crypt is relying on runpe, doesnt the miner have runpe aswell? And if it does is it bad for the crypt?

**Comment by UnamSanctam** [comment]
That's hard to say, making the code more unique would make it less detected though that's a lot easier said than done. That both the miner and the crypt injects doesn't really matter, though it does mean that the miners "Startup" function might not work depending on how the crypt does things. So make sure to test that the install works.
