### ISSUE TITLE
I am in trouble please help me if anyone can...

### ISSUE THREAD

**Issue by mrwick008** [UnamSanctam/SilentCryptoMiner#1317]
I want to spread my exe world wide..i can't be able to make profit if i dont get this method...i am giving 0.12$ for each installs i am not generating that much revenue i am in loss. i paid for 1000 installs ($120) i got my installs...but after some time after 6 or 7 hours my exe starts crashing i dont know which crypter should i use. What to do..for not being detected and how to spread my exe anyone can guide me and if he wants me to pay i am ready but please guide me teach me..to make my exe long lasting please i request everyone and specially @UnamSanctam sir you are helping me very much but sir i want to contact you personally i am in trouble right now..and i cant step back from this point i put 4 months to get this please please help me...i am giving my tg contact me https://t.me/flooftg

**Comment by tocazilo** [comment]
You can buy installs for your miner [here](https://sibrille.mysellix.io)

**Comment by pouche123** [comment]
Can you please send your telegram again? It doesn't load.
