### ISSUE TITLE
High RAM usage 

### ISSUE THREAD

**Issue by Chainski** [UnamSanctam/SilentCryptoMiner#1322]
Why does the miner takes up 2GB of RAM while in stealth mode ?

![high-ram-usage](https://user-images.githubusercontent.com/96607632/208213173-b45cf330-8edc-4ef3-852d-86646f8d218d.png)

Miner Configuration
```
"algo": "rx/0",
"pool": "pool.hashvault.pro",
"port": 80,
"wallet": "45eXMeKx4Q1N[REDACTED]LLmprMYmzum6.{COMPUTERNAME}",
"password": "",
"nicehash": false,
"ssltls": true,
"max-cpu": 40,
"idle-wait": 2,
"idle-cpu": 70,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe"
"kill-targets": "",
"stealth-fullscreen": true
```

**Comment by UnamSanctam** [comment]
Because it isn't clearing the huge pages, because there is a weird random bug on some computers when you do that hasn't been solved which is why it's disabled. You can mine an algorithm that doesn't require much RAM to avoid it.

**Comment by Chainski** [comment]
> Because it isn't clearing the huge pages, because there is a weird random bug on some computers when you do that hasn't been solved which is why it's disabled. You can mine an algorithm that doesn't require much RAM to avoid it.

Thanks for the reply hope you'll fix that soon , In the meatime I googled something and found [EmptyStandbyList](https://www.downloadcrew.com/download/35741/empty_standby_list) that clears memory very well. Could this be of any use if I bind it with the miner ?

**Comment by UnamSanctam** [comment]
No since the memory is still used and valid.
