### ISSUE TITLE
error on webpanel 

### ISSUE THREAD

**Issue by Sindicate100** [UnamSanctam/SilentCryptoMiner#1324]
hello sir ,
 
 i test the miner on my vps and i get this error on the panel . what is the issue? https://prnt.sc/W6FCHiXH-uKY
![image](https://user-images.githubusercontent.com/120419250/208246302-347cf6ac-caa5-448c-9cea-d0883f064df4.png)

**Comment by masterjek** [comment]
I've asked a similar question before. Answer - The miner cannot connect to the pool.

**Comment by Sindicate100** [comment]
yeah but why?

**Comment by masterjek** [comment]
Ip address of the country is blocked in the connection pool. I have a lot of these errors. I looked at the geolocation and almost ip from China.

**Comment by Sindicate100** [comment]
so its device issue right? the miner works perfect?

**Comment by masterjek** [comment]
Yes, most likely with the miner everything is in order. It's just that your ip is blocked by the pool.

**Comment by Sindicate100** [comment]
maybe because its vps and they are blocked

**Comment by masterjek** [comment]
Some countries have banned mining. And most of the pools blocks the connection of the IP from these countries.
