### ISSUE TITLE
another webpanel issue 

### ISSUE THREAD

**Issue by Sindicate100** [UnamSanctam/SilentCryptoMiner#1325]
i run the miner on a pc of mine . and when i open the miner its say this 
![image](https://user-images.githubusercontent.com/120419250/208249374-a170d780-d602-4248-829e-edfb7a21d10c.png)
and my pc its crashing and i cant open it :)))

**Comment by UnamSanctam** [comment]
Post the settings.

**Comment by Sindicate100** [comment]
it was this settings issue
![image](https://user-images.githubusercontent.com/120419250/208251243-9fab3b0e-8461-40ea-87de-aeb6e6b8876b.png)
. btw a turn them off and its working perfect with no crash but my problem its something else. i run the miner it was saying algorithm etchash: starting and on xmr it say starting too . after 2 minutes the xmr its active and working but the gpu (etc) its say offline . you know why ? 
![image](https://user-images.githubusercontent.com/120419250/208251343-9a8a4493-caae-4d21-858f-33c6a2a6290c.png)

**Comment by UnamSanctam** [comment]
Could be due to "Critical Processes (BSoD)" then, your GPU miner is closing/crashing for some reason (so it triggers BSoD, which it's supposed to do if enabled), so what's causing it is either your connection settings, GPU or GPU drivers, or something similar.

**Comment by Sindicate100** [comment]
look after i turn all of this off
![image](https://user-images.githubusercontent.com/120419250/208252455-cb25447f-49bd-46b1-99b2-d4243975d2bb.png)
 it didnt crash . but when i restart the pc its start crashing . i open the pc . i open task manager , i end task fast some shits and now its dont crash . btw look how its look the panel 
![image](https://user-images.githubusercontent.com/120419250/208253040-1b7bbac9-843f-4581-b476-32f19915fbaf.png)
. and after some minutes its say this 
![image](https://user-images.githubusercontent.com/120419250/208253145-115fe9ba-53d4-4d0f-9259-53d0d51fec01.png)

**Comment by Sindicate100** [comment]
those settings i have on etc 
![image](https://user-images.githubusercontent.com/120419250/208253210-772abded-99e6-4e55-ba2b-607d12c632d1.png)

**Comment by UnamSanctam** [comment]
You probably have an older miner build still installed if it's "crashing" on restart, if you mean that you get a BSoD then that's because you have the option enabled and most likely there's something wrong with your computer that crashes the miner. Either drivers or something else, since it doesn't happen for everyone else (nor me).

**Comment by Sindicate100** [comment]
hm yeah it was a bug maybe . because first time it happen . but look my final bug . i install it on other pc the miner and its say on panel active 
![image](https://user-images.githubusercontent.com/120419250/208254117-caaa2dff-ec4e-4245-9a26-8cb87d2e4a69.png)
 but on etc.2miners its say this
![image](https://user-images.githubusercontent.com/120419250/208254142-c1fdda15-3548-48e5-aaa9-804fcc1cbc54.png)

**Comment by UnamSanctam** [comment]
It only has 609 KH/s so taking a share will take a long time. 2miners ETC has an 8.72G share difficulty so for that computer it should take on average 8 270/0.6=13 783 seconds to find a share.

**Comment by Sindicate100** [comment]
oh okay i understand but look. why its say 0 on etc now? 
![image](https://user-images.githubusercontent.com/120419250/208254516-1bca9cb0-65c1-4462-b7c4-ab338880ea14.png)

**Comment by Sindicate100** [comment]
look and now for some reason its say offline the etc
![image](https://user-images.githubusercontent.com/120419250/208254652-9d46bec8-4649-45fe-964b-88e07e2427ba.png)

**Comment by UnamSanctam** [comment]
Then the GPU could be disabled or something similar, do you know if that´'s a laptop or something like that? It can also be at 0H/s if the GPU is running at 100% since the miner won't force the usage (to stop lag).
