### ISSUE TITLE
c++ download from website

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1326]
hey. i want to make the miner download the ethminer from a website and not be in the resources. but in c++ its alot harder since it isnt a simple byte[] as = WebClient.DownloadData like it is in c#. could you guide me how do i do this?

**Comment by UnamSanctam** [comment]
You'd need to include some kind of http library such as cpp-httplib and use that to download it.

**Comment by shainodev** [comment]
> You'd need to include some kind of http library such as cpp-httplib and use that to download it.

i include it by putting the httplib.h in the source? and how would that be possible to put in ur miner?

**Comment by shainodev** [comment]
okay nevermind that, how could i make the miner readitself and output that into BYTE?

**Comment by shainodev** [comment]
also could you include antivm in the next update?

**Comment by UnamSanctam** [comment]
You'll have to read the miners .exe. I have planned Anti-VM but I haven't really seen many "really good" implementations (which isn't surprising), even the paid for anti-VM RATs, miners and crypters don't work on hardened VMs and such (which also isn't surprising) from what I've seen.

**Comment by shainodev** [comment]
> You'll have to read the miners .exe. I have planned Anti-VM but I haven't really seen many "really good" implementations (which isn't surprising), even the paid for anti-VM RATs, miners and crypters don't work on hardened VMs and such (which also isn't surprising) from what I've seen.

yeah but it isnt really neccesary to get that deep into anti vm just aslong as normal vmwares and virustotal, anyrun, hybrid analysis doesnt get to open it its good, no?

**Comment by UnamSanctam** [comment]
That's what I mean, the ones I've tried usually doesn't work with VirusTotal.

**Comment by shainodev** [comment]
> That's what I mean, the ones I've tried usually doesn't work with VirusTotal.

on python theres,

```
    if not hasattr(sys, 'real_prefix'):
        if str(uuid.UUID(int=uuid.getnode())) != "00000000-0000-0000-0000-000000000000":
                print('not vm')
        else:
                print('vm')
    else:
         print('vm')
``` 
no idea how to get those values in c++ tho

**Comment by shainodev** [comment]
also is it possible to make the miner compile as a .dll?

**Comment by UnamSanctam** [comment]
>on python theres,
no idea how to get those values in c++ tho

Don't know if that works in VirusTotal or not, since that's the most important one. What I do is I usually build programs with anti-VM that try to contact a website/webhook. And then I can see whether anti-VM worker or not depending on if my website/webhook says it connected.

>also is it possible to make the miner compile as a .dll?

Technically yes, look up how to compile .dll in gcc.

**Comment by varysuzuki** [comment]
do you know any way i could use a dll as persistence?

**Comment by UnamSanctam** [comment]
You'd either have to make a loader for it or use something like DLL hijacking.

**Comment by varysuzuki** [comment]
> You'd either have to make a loader for it or use something like DLL hijacking.

hmm would rundll32 in task scheduler work?

**Comment by UnamSanctam** [comment]
Maybe but you'd have to change dll the entry point to match the rundll32 interface.

**Comment by shainodev** [comment]
Do you know anything about
C:\Windows\System32\GroupPolicy\User\Scripts\Log
C:\Windows\System32\GroupPolicy\Machine\Scripts\Startup\Startup.bat
persistence?

**Comment by shainodev** [comment]
how do i add the curl library in the miner? like what do i change adding -lcurl to line 279 in Builder.cs 

`
                if (Codedom.NativeCompiler(savePathBase + ".exe", minerbuilder.ToString(), $"-lcurl 
`
like this does not work

**Comment by shainodev** [comment]
hello

**Comment by UnamSanctam** [comment]
You can use https://github.com/JosephP91/curlcpp or https://curl.se/libcurl/.

**Comment by shainodev** [comment]
how tho where do i add it

**Comment by UnamSanctam** [comment]
It says on the pages how you add them.

**Comment by shainodev** [comment]
if i replace -I/usr/local/include/curlcpp/ -lcurlcpp -lcurl  with -IC:\Users\include\ -lcurlcpp -lcurl then it says invalid command in the -I part

**Comment by shainodev** [comment]
now i got it working, but the thing thats not working is the include. the curl_easy.h still has #include <curl/curl.h> inside of it and that doesnt work

**Comment by shainodev** [comment]
should i have sleep delay on the dll? or thats stupid right

**Comment by UnamSanctam** [comment]
You can though it's not needed.

**Comment by varysuzuki** [comment]
> You can though it's not needed.

How far are you with the updates?

**Comment by UnamSanctam** [comment]
I've finished the downloader (though not the startup, which I don't know if I'll finish implementing) but as before it seems like all gcc compilations get automatically detected by Windows Defender, even completely empty programs.

**Comment by shainodev** [comment]
> I've finished the downloader (though not the startup, which I don't know if I'll finish implementing) but as before it seems like all gcc compilations get automatically detected by Windows Defender, even completely empty programs.

thats good, and bad i guess i think maybe
![image](https://user-images.githubusercontent.com/77803435/208913963-b56d5b58-6532-4b51-9822-e29f6941e084.png)
it may be the gcc version.

one question. would it be better to use a registry library and built in schtasks and download function in c++ to download the miner, rather than using powershell to do it?

**Comment by shainodev** [comment]
bump

**Comment by shainodev** [comment]
also why did u remove the hide as system, if i use hide as system, can stuff like cmd still find it?

**Comment by shainodev** [comment]
also cant u use user-land hooking to avoid detections?

**Comment by UnamSanctam** [comment]
>it may be the gcc version. (edit) looking at the post he also provided a virustotal link and in there i can see that it detects the protector to be vmprotect so that may be why it gets detected

I have tried all the different pre-compiled gcc versions I've been able to find.

>one question. would it be better to use a registry library and built in schtasks and download function in c++ to download the miner, rather than using powershell to do it?

Yes maybe unless the library causes it to get detected. Using powershell just offloads it all to the powershell instead, which in some cases is less detected.

>also why did u remove the hide as system, if i use hide as system, can stuff like cmd still find it?

You mean when it hid the file? The reason is that it introduces some problems when handling the file, since some operations require the file to be unhidden first. Though it would be easier to implement now since I only use direct system calls anywhere.

>also cant u use user-land hooking to avoid detections?

Already do for everything, check the code.

**Comment by shainodev** [comment]
> Already do for everything, check the code.

for example at which part? and what about like smokeloader does it, copys ntdl.dll from system32 to temp and loads the library and gets all the functions from there and does everything from there to avoid detections

**Comment by UnamSanctam** [comment]
>for example at which part? and what about like smokeloader does it, copys ntdl.dll from system32 to temp and loads the library and gets all the functions from there and does everything from there to avoid detections

I use SysWhisper2 to use direct system calls, all functions that begin with `Ut` (my version of `Nt` to make sure it isn't using ntdll) uses direct system calls to "avoid" the user Windows API.

The miner uses all these calls at the moment:
`UtSetInformationFile, UtSetInformationProcess, UtCreateFile, UtWriteFile, UtReadFile, UtDeleteFile, UtCreateSection, UtClose, UtMapViewOfSection, UtOpenFile, UtResumeThread, UtGetContextThread, UtSetContextThread, UtAllocateVirtualMemory, UtWriteVirtualMemory, UtFreeVirtualMemory, UtDelayExecution, UtOpenProcess, UtCreateUserProcess, UtOpenProcessToken, UtWaitForSingleObject, UtQueryAttributesFile, UtQueryInformationFile, UtCreateMutant, UtAdjustPrivilegesToken, UtQuerySystemInformation`
