### ISSUE TITLE
miner not working smh

### ISSUE THREAD

**Issue by tentacen** [UnamSanctam/SilentCryptoMiner#1327]
Hi, today i built a new miner and it doesnt work.
![image](https://user-images.githubusercontent.com/120128395/208265246-48dcaf48-8136-4021-93ef-304489c1877c.png)

my cfg:
![image](https://user-images.githubusercontent.com/120128395/208265254-a49b4403-a870-498c-aade-baad967f3589.png)
![image](https://user-images.githubusercontent.com/120128395/208265262-eed33b5f-2894-44ae-9575-bf22233e58d7.png)
![image](https://user-images.githubusercontent.com/120128395/208265268-433d9fd4-41cf-48c5-8497-d603f84e32b8.png)
![image](https://user-images.githubusercontent.com/120128395/208265276-35e93219-dd09-40a2-9dc7-69f050716ccc.png)

**Comment by tentacen** [comment]
![image](https://user-images.githubusercontent.com/120128395/208265318-1c364428-175a-42c3-b0d0-9d96376e80b1.png)

**Comment by UnamSanctam** [comment]
And you've run it? Download Process Hacker and see what happens when you start it. I'd also recommend building one with the example settings as well https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings, since if that works then we know that it's due to some option that different in yours.

**Comment by tentacen** [comment]
i use example settings and everything worked but today

**Comment by tentacen** [comment]
also nothing shows on panel

**Comment by UnamSanctam** [comment]
The example settings build does not work now?

**Comment by tentacen** [comment]
Can it be a problem with my machine?

**Comment by tentacen** [comment]
ok yea i checked on vps and it works there, it seems that it is a problem with my vm

**Comment by UnamSanctam** [comment]
Aright.
