### ISSUE TITLE
Worker never mines etc but it does xmr

### ISSUE THREAD

**Issue by tentacen** [UnamSanctam/SilentCryptoMiner#1328]
![image](https://user-images.githubusercontent.com/120128395/208297561-bdfd9397-2c26-49f5-bfaf-98717061121b.png)
![image](https://user-images.githubusercontent.com/120128395/208297565-e4bb8a57-e5b4-40ae-b813-1d1f80130140.png)
Why is that? it never mines etc even when idle.

**Comment by LaRevoltage** [comment]
I think that is because ETH is now Proof Of Stack?

**Comment by UnamSanctam** [comment]
Either it's because the GPU is being used (100%) by something else, or it's due to the VRAM, since it's a 4GB card.

**Comment by wnetMC** [comment]
getting the same issue, and the pc has nothing open and is idle
