### ISSUE TITLE
exe to bin

### ISSUE THREAD

**Issue by tentacen** [UnamSanctam/SilentCryptoMiner#1329]
I know how to get hex with HxD
but how do u get binary from exe?

**Comment by UnamSanctam** [comment]
Depends on what you're trying to do, the binary is just what you see if you open the file with notepad++ or some other text editor.

**Comment by tentacen** [comment]
![image](https://user-images.githubusercontent.com/120128395/208312202-7430b2a2-ff0f-42de-bb83-d17a3c7e481f.png)
this is calc exe, is it binary or base64 or what?

**Comment by UnamSanctam** [comment]
That's in hexadecimal.

**Comment by tentacen** [comment]
my program hex looks a bit diff

**Comment by tentacen** [comment]
```
{
	0x4D, 0x5A, 0x90, 0x00, 0x03, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00,
	0xFF, 0xFF, 0x00, 0x00, 0xB8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0xE8
};

```

**Comment by UnamSanctam** [comment]
Well they're just different ways of representing hexadecimal.

**Comment by tentacen** [comment]
Ok thanks
