### ISSUE TITLE
Root kit not working anymore

### ISSUE THREAD

**Issue by Sh4r3catyt** [UnamSanctam/SilentCryptoMiner#1330]
Hi im trying to use the Root kit but i can see Dailer.exe always in the Taskmanager or in Processhacker.
Even after restart.

![grafik](https://user-images.githubusercontent.com/77161107/208474426-b304475a-62a5-4660-944d-68d844fe8e98.png)

**Comment by UnamSanctam** [comment]
Try reinstalling it or building a new build.

**Comment by Sh4r3catyt** [comment]
I already did it multiple times :/

**Comment by UnamSanctam** [comment]
Is it only on that computer or on others?

**Comment by Sh4r3catyt** [comment]
I tested on my main and VM

**Comment by Sh4r3catyt** [comment]
Also i uploaed the miner After some tests on my main pc to my clients 700+ clients but i can only see 6 on RVN
![grafik](https://user-images.githubusercontent.com/77161107/208485188-40172138-fb43-4e55-914a-5cbd22d4ee08.png)
I waited now 40 minutes

**Comment by Sh4r3catyt** [comment]
and xmr is the same 700+ workers in panel but only have 200 Workers on 2miners xmr
![grafik](https://user-images.githubusercontent.com/77161107/208485489-51ab2bd5-49d0-430b-83b2-00e50c85707f.png)

**Comment by UnamSanctam** [comment]
Well they have to find a share, and then they count as offline after some time if they don't find a share within the interval. They might also have the same worker name. For RVN I wouldn't recommend mining that anyways since it causes a lot more lag and heat, and it doesn't work on my GPU so I can't test it either.

**Comment by Sh4r3catyt** [comment]
Okay thanks

**Comment by Sh4r3catyt** [comment]
But got the root kit fixed by windows?

**Comment by UnamSanctam** [comment]
Don't know, it worked for me a few days ago on a fully updated Windows 11 VM.

**Comment by Sh4r3catyt** [comment]
Hm crazy i use newest Windows 10 :/

**Comment by unameddev** [comment]
@Sh4r3catyt Hey, can you message me on telegram? I have a question about the rootkit and you are the only one i've found that uses it, thanks. 
t.me/x02r88

**Comment by Sh4r3catyt** [comment]
> @Sh4r3catyt Hey, can you message me on telegram? I have a question about the rootkit and you are the only one i've found that uses it, thanks. [t.me/x02r88](https://t.me/x02r88)

as you can see its not working for me

**Comment by unameddev** [comment]
> as you can see its not working for me

That's a bummer, i thought you got it working again, well, would you mind helping me with questions regarding how to spread and make the person execute the file? i'm new to this and it's really hard to learn by myself, i would appreciate anything you could teach me, thanks again!

**Comment by Sh4r3catyt** [comment]
The root kit is still not workin :/
