### ISSUE TITLE
How to crypt the miner correctly?

### ISSUE THREAD

**Issue by cutnets** [UnamSanctam/SilentCryptoMiner#1332]
Recently, I bought a private crypt for a miner and unfortunately discovered that the miner does not work under it. I've already realized that it was necessary to disable the startup.
@UnamSanctam Could you tell me what other functions should be turned off for the crypt (if necessary)? Or what functions stop working under the crypt?

**Comment by UnamSanctam** [comment]
Only really the startup that I can think of, that's because the crypter injects the miner. And is also why most crypters have their own startup feature. Make sure that the crypter supports 64-bit.

**Comment by anesd2** [comment]
> Only really the startup that I can think of, that's because the crypter injects the miner. And is also why most crypters have their own startup feature. Make sure that the crypter supports 64-bit.

thanks it saved me. But i wanna know one thing that u said most crypters have their own startup feature. So does miner run on startup now or this feature will not work ?

**Comment by UnamSanctam** [comment]
>thanks it saved me. But i wanna know one thing that u said most crypters have their own startup feature. So does miner still run on startup now or this feature will not work ?

If you disable "Startup" in the miner then you have to enable it in the crypter, if you have it enabled in the crypter then it will start the miner on startup. You can test it on a virtual machine.

**Comment by anesd2** [comment]
@cutnets bro plz can u provide me private crypter that you bought ?
