### ISSUE TITLE
injection problem

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1334]
I know this is unrelated, but when I changed the miner from ethminer.exe to lolminer.exe then it will show a conhost.exe as a child process of the lolminer.exe/injected, even tho in common.cpp -> create_new_process_internal, the ConsoleHandle is set to HANDLE_CREATE_NO_WINDOW and stuff. what could i do to make it not show?

**Comment by UnamSanctam** [comment]
It doesn't show due to the handle flag but lolminer will still start the window because that is what it was compiled to do. Not sure if you can prevent that, you could try other handles or flags but good luck finding them.

**Comment by shainodev** [comment]
> It doesn't show due to the handle flag but lolminer will still start the window because that is what it was compiled to do. Not sure if you can prevent that, you could try other handles or flags but good luck finding them.

on powershell it worked with Start-Process -FilePath "lolminer" -NoNewWindow, but i cant use powershell to load it since the lolminer.exe will get insta detected, but idk, is it even possible? im so sure i remember when i tried a couple months ago it didnt do the conhost.exe child process, maybe something was different in the older version of SilentCryptoMiner c# version inject.dll?

**Comment by UnamSanctam** [comment]
>on powershell it worked with Start-Process -FilePath "lolminer" -NoNewWindow, but i cant use powershell to load it since the lolminer.exe will get insta detected, but idk, is it even possible? im so sure i remember when i tried a couple months ago it didnt do the conhost.exe child process, maybe something was different in the older version of SilentCryptoMiner c# version inject.dll

Yes, they are completely different, the current process creation I do I achieved through reverse engineering and reading obscure "documentation", there might be some flag to avoid it spawning but I don't know which one, and it would be too much effort for me to find it (since it doesn't happen in my miner since it's compiled without a console). What you can do is create a console program that reads the program PEB (see my process creation function) and writes out the flags and everything to a file somewhere. Then you can start that program through powershell (so that the console does not spawn) and see if you can find some variable/flag that causes that conhost.exe not to appear. Could also be due to the injection, though you'd have to experiment with that then.

**Comment by shainodev** [comment]
> > on powershell it worked with Start-Process -FilePath "lolminer" -NoNewWindow, but i cant use powershell to load it since the lolminer.exe will get insta detected, but idk, is it even possible? im so sure i remember when i tried a couple months ago it didnt do the conhost.exe child process, maybe something was different in the older version of SilentCryptoMiner c# version inject.dll
> 
> Yes, they are completely different, the current process creation I do I achieved through reverse engineering and reading obscure "documentation", there might be some flag to avoid it spawning but I don't know which one, and it would be too much effort for me to find it (since it doesn't happen in my miner since it's compiled without a console). What you can do is create a console program that reads the program PEB (see my process creation function) and writes out the flags and everything to a file somewhere. Then you can start that program through powershell (so that the console does not spawn) and see if you can find some variable/flag that causes that conhost.exe not to appear. Could also be due to the injection, though you'd have to experiment with that then.

where can i view all flags that there are?

**Comment by UnamSanctam** [comment]
>where can i view all flags that there are?

No idea, I reverse engineered the one I use, not sure there is any documentation since I'm only using undocumented calls.

**Comment by shainodev** [comment]
> No idea, I reverse engineered the one I use, not sure there is any documentation since I'm only using undocumented calls.

Oh, should i even be worried about people finding the conhost child process at all? and is the .exe itself undetected? anddd why do people still complain about your miners stability and saying that pureminer is better? in what way is pureminer any better

**Comment by UnamSanctam** [comment]
>Oh, should i even be worried about people finding the conhost child process at all? and is the .exe itself undetected?

Probably doesn't matter no, there are tons of conhost processes running. You mean if the injected .exe is undetected? Then no, though it's harder to detect than more common process creation/injection techniques.

>anddd why do people still complain about your miners stability and saying that pureminer is better? in what way is pureminer any better

No idea, maybe because it's less detected (easier to crypt) since it's paid and private? Though that usually applies to any paid miner/program. I've had to help a lot of people set up their PureMiner and crypter when they've asked me for help and it was not a fun experience so I'm not the biggest fan of it though. I guess they also have marketing and people also feel a need to justify their purchases. But I shouldn't say too much since then the PureMiner dev might contact me about it again.

**Comment by shainodev** [comment]
> Probably doesn't matter no, there are tons of conhost processes running. You mean if the injected .exe is undetected? Then no, though it's harder to detect than more common process creation/injection techniques.

But if it does get detected it just BSOD's right?

> No idea, maybe because it's less detected (easier to crypt) since it's paid and private? Though that usually applies to any paid miner/program. I've had to help a lot of people set up their PureMiner and crypter when they've asked me for help and it was not a fun experience so I'm not the biggest fan of it though. I guess they also have marketing and people also feel a need to justify their purchases. But I shouldn't say too much since then the PureMiner dev might contact me about it again.

Ohh, alright. does it change anything detection wise when i make the miner a dll? and make it work with only one function that is called at startup by rundll32

**Comment by varysuzuki** [comment]
And one more thing, how do i see if the lolminer is already injected, i tried using ur has_gpu method but just with it searching for wmic path win32_process caption, commandline get etc, but idk how to check if the text file CONTAINS a command line

**Comment by varysuzuki** [comment]
Hello

**Comment by shainodev** [comment]
![image](https://user-images.githubusercontent.com/77803435/209440106-4e47704d-185a-4c19-9fbf-69b14528bcb8.png)
Could you tell me why this doesnt work?

**Comment by shainodev** [comment]
also one more question. does your injection work with a c# app aswell, if i would for example inject to regasm

**Comment by shainodev** [comment]
sorry but hallo

**Comment by UnamSanctam** [comment]
Haven't tested any Regasm injection with it, so I'm not sure. If you were to inject a C# app and then load the DLL then if you use `Assembly.Load` then any assembly that gets loaded does get scanned by Windows Defender, so you'd have to make sure that the loader that you load is undetected.

**Comment by shainodev** [comment]
Alright, What are you working on now btw?

**Comment by UnamSanctam** [comment]
Just released the new update of the web panel so now I'm going to be trying to get the downloader undetected, since that would also help with the miner as well (because they use some similar parts).

**Comment by shainodev** [comment]
Cool, thank you for your good job!
