### ISSUE TITLE
Error to execute the file

### ISSUE THREAD

**Issue by joaquin2009** [UnamSanctam/SilentCryptoMiner#1335]
I have a problem running the Builder
It doesn't appear as an executable file, it just tells me SilentCriptoMiner.vbproj and I can't ru
![ERROR](https://user-images.githubusercontent.com/30941367/209451450-21da8f36-1e8c-45f2-b7c1-16eea606411a.png)
n it

**Comment by UnamSanctam** [comment]
You can download a pre-built one here: https://github.com/UnamSanctam/SilentCryptoMiner/releases.

**Comment by MJMODZZ** [comment]
> I have a problem running the Builder It doesn't appear as an executable file, it just tells me SilentCriptoMiner.vbproj and I can't ru ![ERROR](https://user-images.githubusercontent.com/30941367/209451450-21da8f36-1e8c-45f2-b7c1-16eea606411a.png) n it

Its because you dont have any Compiler like visual studio installed. You can install Visual Studio and open the .sln file in visual studio and compile it
