### ISSUE TITLE
Miner is not working. Information about mining does not come to the site.

### ISSUE THREAD

**Issue by haker2029** [UnamSanctam/SilentCryptoMiner#1337]
Hi all! Faced the problem that the miner is fully configured correctly, but does not work (((
On a site with a pool, information about the pool simply does not come, no matter how much time passes, and the miner simply does not appear.
From the screenshot below, you can see that the video card is suitable. Mainyu Ethereum classic. What could be wrong. I beg you to help... Help me pls
![image](https://user-images.githubusercontent.com/121291113/209480127-947ad82c-95a5-4d83-aef8-2cf11de3171a.png)

**Comment by haker2029** [comment]
> 

![image](https://user-images.githubusercontent.com/121291113/209480181-977c3307-311c-4cb0-9cc7-81564688981d.png)

**Comment by UnamSanctam** [comment]
Download and open MSI Afterburner and check if the GPU is being used (and also the amount of memory being used).

**Comment by haker2029** [comment]
I already checked, it does not affect the power of my computer in any way.

**Comment by UnamSanctam** [comment]
How much free VRAM does it say you have?

**Comment by haker2029** [comment]
Personally, on my version of the video card 4VRAM, but on the video card of a friend the same story, but there is 8VRAM.

**Comment by UnamSanctam** [comment]
Yes but how much of it is not being used? You can check in the Task Manager, press the "Performance" tab and then select your GPU in the list. It will then say how much dedicated GPU memory (VRAM) is being used. You could also set up a local web panel (https://github.com/UnamSanctam/UnamWebPanel#for-local-testing) and see what it's reporting.

**Comment by haker2029** [comment]
And, usually 20-30% of the capacity is used.

**Comment by haker2029** [comment]
a friend at this time uses 10-15% of the capacity.

**Comment by UnamSanctam** [comment]
Can you post your specific numbers? How much of your VRAM are you using? Check your Task Manager. Otherwise you could also set up the web panel locally and connect the miner to it.

**Comment by haker2029** [comment]
I would love to, but now it's night, I'll go to sleep.  I will write to you tomorrow.  By the way, I remembered that I also have a problem with moner mining.  Monero is mined on my virtual PC and server PC, but Monero is not mined on a friend's PC at all.  Tomorrow I will throw off the load on my video card.

**Comment by haker2029** [comment]
The memory is loaded in the region of several hundred mb, no more than 500. I don’t know what the problem is, but it seems to be unrelated to the PC’s power.  Again, a friend has an rtx 3060 on 8VRAM, 6VRAM is just free ... Can I upload a video on YouTube of the process of creating a miner?  Maybe I did something wrong?

**Comment by haker2029** [comment]
Here. I recorded a video of how I made the miner, please check if I did everything correctly. https://youtu.be/00qlxrteiBc

**Comment by UnamSanctam** [comment]
That looks alright, try it once with the example settings as well: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings. I would recommend setting up a local web panel: https://github.com/UnamSanctam/UnamWebPanel#for-local-testing to see what the miner reports.

**Comment by haker2029** [comment]
Hm. It is very strange. I almost quit doing this. Today I installed windows home virtual system. I realized that everything works on the Dedik because the antivirus simply does not resent or what? But nothing works on windows home viression ... That is, is it because of the antivirus or what? Maybe you need to encrypt the file?

**Comment by UnamSanctam** [comment]
You mean that it can't install? Or that there's no hashrate?

**Comment by haker2029** [comment]
I mean it's not visible at all. The checker even says that it does not work. On the Windows server at this time everything functions as it should.

**Comment by UnamSanctam** [comment]
And it's not a 32-bit OS? Can you try installing it on that machine with only the example settings and no changes?

**Comment by haker2029** [comment]
No, both there and there is a 64-bit system.

**Comment by UnamSanctam** [comment]
And it doesn't work with only the example settings? Can you see the entry in the Task Scheduler or the file in the install location?

**Comment by haker2029** [comment]
You mean... Will Windows Defender see it?

**Comment by UnamSanctam** [comment]
If Windows Defender detects it then you should be able to see that it does inside Windows Defender.

**Comment by haker2029** [comment]
No. It doesn't work at all, both with the example and with my settings. The file is not deleted (if you meant it). Everything works identically on both systems. 
When you disable windows defender, nothing changes, as it was and remains.

**Comment by UnamSanctam** [comment]
Can you open the Task Scheduler and see if you can find the entry `GoogleUpdateTaskMachineQC` there? Also check if the miner file was copied successfully into `%ProgramFiles%\Google\Chrome\updater.exe` or not. Also download Process Hacker and sort it by "Start time" (https://www.youtube.com/watch?v=EkXSRm8-DdQ), then try starting the miner and see what happens with the processes.

**Comment by haker2029** [comment]
The hacker process shows that the console is opening or that it is, in general, a miner, and after a few seconds it closes.

**Comment by haker2029** [comment]
To make it more clear, I shot a video and posted it on YouTube, please see if everything is as it should be ... https://youtu.be/OBsadyx05k4

**Comment by UnamSanctam** [comment]
Alright so it looks like it installs everything correctly, and the process creation looks like it works as well. And it looks like the watchdog is working as well and possibly even the miner (one of the conhost.exe there could be the miner). Looks like it's just that  your WMI or something is broken in your VM, possibly even mutexes as well. So I would recommend fixing your Windows or creating a new VM and testing it there.

**Comment by Danill2** [comment]
I join to this issue, I have a web panel and about 5-6 real computers with 64 bit Windows and RTX 3050, GTX 1660 Ti, GTX 1650 Ti and RX 560, when connected to a 2miners pool using STRATUMS hashrate on computers with RTX, GTX shows 0, while RX 560 shows ~**1.5-2.2**Mh/s however, on the 2miners pool, there is ABSOLUTELY no information about the miner, no matter how much I try. I use example configs (replaced only with my wallet), **as far as I understand, this problem is ONLY on the 2miners pool**, since all of the above computers are easily connected to ethermine.org.

**Comment by Danill2** [comment]
**Solved a problem**. It turns out that to connect to the 2miners pool, you had to use STRATUM**SS** (SSL / TLS **1.2**) instead of STRATUM**S**
