### ISSUE TITLE
how to mine btg ( bitcoin gold)

### ISSUE THREAD

**Issue by Sindicate100** [UnamSanctam/SilentCryptoMiner#1339]
Hello, Merry Christmas, i take a look and i cant find bitcoin gold 
![image](https://user-images.githubusercontent.com/120419250/209572486-7e479d51-b73c-47d1-9b91-7564b2c004b8.png)

**Comment by UnamSanctam** [comment]
Yes it does not have the Zhash algorithm that BTG uses.

**Comment by Sindicate100** [comment]
and how can i add it?

**Comment by UnamSanctam** [comment]
If you want to add it yourself then you'd have to implement it into https://github.com/ethereum-mining/ethminer (or any other open-source GPU miner) and then replace it in the miner builder or send your implementation to me for me to add into the miner.

**Comment by Sindicate100** [comment]
here : https://github.com/BTCGPU/BTCGPU

**Comment by UnamSanctam** [comment]
I mean that you'd have to implement the Zhash algorithm into ethminer, that's what I'd have to do to implement it as well.

**Comment by Sindicate100** [comment]
i dont have any idea about coding bro . you cant impliment it yourself because you have experience?

**Comment by UnamSanctam** [comment]
In a few months maybe sure, it would take quite a long time to implement it and test it on most cards.
