### ISSUE TITLE
Really low hashrates, shows only 1 workers

### ISSUE THREAD

**Issue by ducksucker** [UnamSanctam/SilentCryptoMiner#134]
hey so i checked the specs of the pc and
![image](https://user-images.githubusercontent.com/73056239/145673346-bf44a34f-bb09-4e16-a2eb-63d2c9f2344d.png)
and its only 4.2 KH/s 
also on 2miners the site i use it shows that there is only 1 worker, when i got like 10 people mining right now
![image](https://user-images.githubusercontent.com/73056239/145673389-4c73f986-17d0-4759-9db1-c7aa90aa849b.png)
i use monero, could u help me please? maybe we can talk on discord

**Comment by UnamSanctam** [comment]
What "Max CPU" do you set it to? And do you have different worker names for all miners? Since otherwise they will just combine on the pool.

**Comment by ducksucker** [comment]
i dont know how to set different worker names, also i set cpu to 30% and idle to 100% or 90%

**Comment by ducksucker** [comment]
also when it was online it was still on 4.2kh/s for like 5 hours

**Comment by UnamSanctam** [comment]
The hashrate for an AMD R9 3900X is around 12KH/s so 30% of that is around 4KH/s, meaning it's correct. It's an insane hashrate anyways since 99% of CPUs only maybe has 300H/s ar 30%.

**Comment by ducksucker** [comment]
but isnt that like low?
![image](https://user-images.githubusercontent.com/73056239/145673746-ae018376-8968-47b1-8482-6cf0e7ffcb3d.png)
on 2miners it says 0.13$ estimated per day

**Comment by ducksucker** [comment]
ive heard that people normally get like 8 bucks per day

**Comment by UnamSanctam** [comment]
And if you don't set a worker name (on most pools usually by adding it into the "Wallet Address" like so `WalletAddress.WorkerName`) then it will all gather under one worker name.

And that estimate is correct, as you can see by entering 4200 hashrate here: https://minerstat.com/coin/XMR

**Comment by ducksucker** [comment]
is there any way i can edit that worker thing now that i have 27 miners? while theyre mining

**Comment by UnamSanctam** [comment]
To earn $8/day using CPU mining (Monero) you would need around 220000H/s which is on average around like 550 miners. What you mean is probably GPU mining (Ethereum or Ethereum Classic) where an `RTX 3090 can mine around $7.5/day.

You can edit the connection settings if you use "Remote Configuration" or the web panel, otherwise no (of course).

**Comment by ducksucker** [comment]
![image](https://user-images.githubusercontent.com/73056239/145673922-c4d39616-769a-42f7-93b6-d8ba6493bc56.png)
where is the remote configuration feature?

**Comment by UnamSanctam** [comment]
You add the "Remote Configuration" when you compile the miner https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration but I can see that you didn't. But you can still use the "Configurations" tab with the same JSON configuration settings as the "Remote Configuration" on the wiki and then apply those configurations to your miners.

**Comment by ducksucker** [comment]
ohh okay cool, thanks. Also would u recommend me to start mining eth to get more money? since this monero cpu mining is like 0.13$ per day which is 3$ per month which is nothing

**Comment by ducksucker** [comment]
its probably not possible to add a new miner to my workers now huh? so that i could add ethereum

**Comment by UnamSanctam** [comment]
No your miners weren't compiled with the Ethereum miner in it so you can't mine that without building a new miner. I usually recommend ETC instead since it requires less VRAM so it's harder to detect though the profit is lower. But the positive with Monero mining is that it's hard to detect and can run on nearly any computer, the largest miner I know has around 130 000 miners which gives him around 85 000 000H/s (I think from what I remember), which is around $3200/day.

**Comment by ducksucker** [comment]
damn thats insane, whats the most profitable thing to mine now?

**Comment by ducksucker** [comment]
i mean monero is really good cuz its nearly undetectable as u said above but i only get 0.13$ per day

**Comment by UnamSanctam** [comment]
Well Monero is one of the best CPU coin unless you want to mine a low market cap one that you believe has a lot of potential. For GPU coins you can see the profitability here: https://whattomine.com/coins

**Comment by ducksucker** [comment]
btw how do i make the workers thing?

**Comment by ducksucker** [comment]
there arent any settings in 2miners site cuz u cant log in there afaik

**Comment by UnamSanctam** [comment]
On most pools it's usually by adding it into the "Wallet Address" like so `WalletAddress.WorkerName`

**Comment by ducksucker** [comment]
but where do i type that? into builder at silent miner? or where

**Comment by UnamSanctam** [comment]
Yes the builders "Wallet Address", where you enter your wallet. Or in the "Remote Configuration" (or in the web panel) wallet address.

**Comment by ducksucker** [comment]
"algo": "rx/0",
	"pool": "xmr-eu2.nanopool.org",
	"port": 14433,
	"wallet": "8BbApiMBHsPVKkLEP4rVbST6CnSb3LW28hwaSjnsg2N.WorkerName",
	"password": "",
	"rig-id": "",
	"keepalive": false,
	"nicehash": false,
	"ssltls": true

like this? for example? also, can i just leave it at ".WorkerName" or do i  have to change something?
also what do i type in "rig-id": "",
and "keepalive": false,
^ havent seen those 2 features in the silent miner so im asking

**Comment by UnamSanctam** [comment]
Yes that's correct, "rig-id" is another field for it that can be used as well on some pools. Keepalive does exactly what it sounds like, it keeps the connection alive, not all pools support it like nanopool so don't enable it for nanopool.

**Comment by ducksucker** [comment]
should i enable it for 2miners?

**Comment by ducksucker** [comment]
![image](https://user-images.githubusercontent.com/73056239/145676596-beb55c0b-1383-4110-bd32-ad9a369c0631.png)
also the rates are getting better when people are joining

**Comment by UnamSanctam** [comment]
It works for 2miners yes, you can use {COMPUTERNAME} for each miner to use their own computer name as the worker name. And the more hashrate (miners) you get the more profit you will get of course.

**Comment by ducksucker** [comment]
"wallet": "8BbApiMBHsPVKkLEP4rVbST6CnSb3LW28hwaSjnsg2N.{COMPUTERNAME}", 
should look like this from what ive understandood right?

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by ducksucker** [comment]
also, which one should i be using?
![image](https://user-images.githubusercontent.com/73056239/145676861-131d0b85-1de7-44ce-a082-b6a3d6e3093e.png)
im pretty new to crypto mining so i dont know what those 2 circled numbers mean and change

**Comment by UnamSanctam** [comment]
It's the difficulty for the shares, so a share with a higher number takes longer to find so I would recommend the 120K difficulty one.

**Comment by ducksucker** [comment]
so i added the configuration, now did it apply automatically? or how do i enable it on the panel

**Comment by UnamSanctam** [comment]
If you added a new configuration then you can open any miner and change the configuration.

**Comment by ducksucker** [comment]
okay, so i did that but theres still only 1 worker
![image](https://user-images.githubusercontent.com/73056239/145677649-e62bab95-4c13-431c-bc25-ddd0550c0f45.png)

**Comment by UnamSanctam** [comment]
You need to wait one minute for the configuration to take effect, then it also needs to mine a share (120K difficulty) for it to appear on the pool.

**Comment by ducksucker** [comment]
okay, ill give it 5 minutes and ill let u know

**Comment by ducksucker** [comment]
nothing changed, only that my hashrate got lower

**Comment by UnamSanctam** [comment]
You will see if the configuration worked in the web panel.

**Comment by ducksucker** [comment]
looks like this in the panel 
![image](https://user-images.githubusercontent.com/73056239/145678113-df92590e-421c-48a1-a267-7c3da779fc20.png)

**Comment by ducksucker** [comment]
{
	"algo": "rx/0",
	"pool": "xmr.2miners.com",
	"port": 12222,
	"wallet": "42rqPYHZGfj8omqNtGGmfdmWViWojKxeSPXvocU.{COMPUTERNAME}",
	"password": "",
	"rig-id": "",
	"keepalive": true,
	"nicehash": false,
	"ssltls": true
	"max-cpu": 40,
	"idle-wait": 4,
	"idle-cpu": 100,
	"stealth": true,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"process-killer": false,
	"kill-targets": ""
}
this is what i used

**Comment by UnamSanctam** [comment]
Your configuration is invalid, you forgot a comma (,) after `"ssltls": true`

**Comment by ducksucker** [comment]
thanks brother
![image](https://user-images.githubusercontent.com/73056239/145678596-385efcca-59d7-4e5b-8bea-287033390372.png)
now its working like a charm, because i turned cpu max to 50%

**Comment by ducksucker** [comment]
hello, sorry to bother you but i wanted to ask a question:
why is my Balance not updating? its been on 0.05$ this whole day when the calculations are 0.56$ per day
![image](https://user-images.githubusercontent.com/73056239/145683756-f1a8e235-6c8a-42a1-b63d-8765b12a5741.png)
just wanted to ask that because im really new to this mining system and these sites and stuff, i was just ratting back in the day, thats why i have 70 miners now

**Comment by UnamSanctam** [comment]
Your unpaid balance is $0.05, your unconfirmed balance (haven't been long enough since the blocks were found) is $0.09 meaning  you've mined $0.14 so far as you can see in your "Last 24 Hours Reward".

**Comment by ducksucker** [comment]
hey, so my website is getting shut down because it received 24k visits which unfortunately suspended my hosting account. The website still works but it will work for just few hours after shutdown. Is there any way to change configuration of users but automatically? Meaning I won't have to go on the site and change configuration of new miners but it will automatically assign chosen config? Because I soon wont be able to go on the site and change it manually.

**Comment by UnamSanctam** [comment]
With "Remote Configuration" yes, though you didn't build them with that. Otherwise there won't be any way to give them an automatic configuration (of course) since there's nothing that can give them the configuration (if the site shuts down).

**Comment by ducksucker** [comment]
the site still works but I'm guessing it will get shutdown any time soon, so what do I do at the panel?

**Comment by UnamSanctam** [comment]
If the website gets shut down then the miners won't be able to contact it, so the next time the computer restarts the miner will have to use the settings you set in the builder, since it can't contact the web panel and you don't have a "Remote Configuration" added into it.

**Comment by nomad1420** [comment]
> the site still works but I'm guessing it will get shutdown any time soon, so what do I do at the panel?

can you contact me discord ahm#0 116

**Comment by nomad1420** [comment]
ahm#0116

**Comment by nomad1420** [comment]
ahm#zero,one,one,six
