### ISSUE TITLE
how to make the file silent and fud

### ISSUE THREAD

**Issue by floof989763** [UnamSanctam/SilentCryptoMiner#1342]

**Comment by floof989763** [comment]
i need a crypter on i need someone to crypt my file . please help sir

**Comment by floof989763** [comment]
i need my miner to pass av

**Comment by floof989763** [comment]
please help unam sir

**Comment by shainodev** [comment]
I dont think unam is the guy to ask. u should buy PRIVATE CRYPTS on hackforums and hear me out private crypts do not buy the public shared stub crypters or something like that

**Comment by floof989763** [comment]
hello @shainodev ... sir please can you guide me?
on tg https://t.me/flooftg
