### ISSUE TITLE
etc+kaspa

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1343]
kindof offtopic question.

is it better to mine etc+kaspa than just kaspa?

and is it possible to dualmine with ur miner by adding UBQ miner and then a ETC miner in the same miner? and is it good to do so?

also i was wondering, does having a tcp connection to the client. for example putting a tcp connection to connect to me in the watchdog does it make anything more.. stable or something?

does your miner have flux coin?

and does a tcp rat need a server certificate or is there something else i can do?

and could you add amsi bypass? or is it not needed

**Comment by shainodev** [comment]
does your miner have flux coin?

**Comment by shainodev** [comment]
and does a tcp rat need a server certificate or is there something else i can do?

**Comment by shainodev** [comment]
and could you add amsi bypass? or is it not needed

**Comment by UnamSanctam** [comment]
>is it better to mine etc+kaspa than just kaspa?

Don't know since I don't know much about KASPA.

>and is it possible to dualmine with ur miner by adding UBQ miner and then a ETC miner in the same miner? and is it good to do so?

You could dual mine UQB and ETC though it wouldn't be any more profitable, only difference is that it would use more VRAM (ETC + UQB VRAM).

>also i was wondering, does having a tcp connection to the client. for example putting a tcp connection to connect to me in the watchdog does it make anything more.. stable or something?

Not really, why would it be more stable?

>does your miner have flux coin?

No it doesn't have ZelHash (their own algorithm).

>and does a tcp rat need a server certificate or is there something else i can do?

No it doesn't need a certificate, though it's good to use of course.

>and could you add amsi bypass? or is it not needed

There was one before but it increased detections.

**Comment by shainodev** [comment]
> Not really, why would it be more stable?

like even more undetected for example, i make the miner itself inject the watchdog only, then i make the watchdog listen for the host connection, and then when connected it waits for a command that contains the ciphered bytes of lolminer and if it gets it it saves the bytes, injects it and starts watchdoging. wouldnt that be better?

> No it doesn't need a certificate, though it's good to use of course.

What does a certificate change?

> There was one before but it increased detections.

so its worse to add it?

**Comment by UnamSanctam** [comment]
>like even more undetected for example, i make the miner itself inject the watchdog only, then i make the watchdog listen for the host connection, and then when connected it waits for a command that contains the ciphered bytes of lolminer and if it gets it it saves the bytes, injects it and starts watchdoging. wouldnt that be better?

Sure that could most likely be better for both scantime and runtime detections.

>What does a certificate change?

Makes the connection (more) secure.

>so its worse to add it?

Depends on the implementation, though I haven't seen any detections caused by AMSI yet either.

**Comment by shainodev** [comment]
> Makes the connection (more) secure.

arent there other ways to do that?

**Comment by shainodev** [comment]
also i was wondering can you cipher function work with a char* instead of unsigned char*?

**Comment by shainodev** [comment]
![image](https://user-images.githubusercontent.com/77803435/210004357-893c5e64-23ae-463a-b07b-8695760a49e8.png)
does this code look right to you

**Comment by shainodev** [comment]
also whats the difference between createprocess and shellexecute. is shellexecute non tracable or less detected?

**Comment by UnamSanctam** [comment]
>arent there other ways to do that?

Sure but a certificate is the most common one.

>also i was wondering can you cipher function work with a char* instead of unsigned char*?

Possibly, in this case it shouldn't matter, unless I'm too tired to think correctly.

>does this code look right to you

Sure, that looks right.

>also whats the difference between createprocess and shellexecute. is shellexecute non tracable or less detected?

Both are about equally detected and traceable. Though sometimes antiviruses find ShellExecute less suspicious.

**Comment by shainodev** [comment]
Oh okay. Also I was wondering. Is it even worth it to make the watchdog have a TCP Connection between me and the PC or is it better to just make it download from a website. Or is it riskier to use a website?

**Comment by shainodev** [comment]
And also, if the ethminer for example is ciphered. what would be the extension of the ciphered code? like .bin or .txt?

**Comment by shainodev** [comment]
Should I mine RVN or Flux? is there anything wrong with flux

**Comment by shainodev** [comment]
or should i mine ubq even tho it is alot less profitable

**Comment by shainodev** [comment]
hello
