### ISSUE TITLE
how can i contact you

### ISSUE THREAD

**Issue by dawnsgrave** [UnamSanctam/SilentCryptoMiner#1348]
you got discord or telegram?

**Comment by UnamSanctam** [comment]
Right now really only through email: unams@protonmail.com. My Discord was banned for helping people with the miner and I lost access to my Telegram account.

**Comment by dawnsgrave** [comment]
> Right now really only through email: [unams@protonmail.com](mailto:unams@protonmail.com). My Discord was banned for helping people with the miner and I lost access to my Telegram account.

thank you, ill send you an email
