### ISSUE TITLE
vram

### ISSUE THREAD

**Issue by tentacen** [UnamSanctam/SilentCryptoMiner#1350]
![image](https://user-images.githubusercontent.com/120128395/210438721-fec53c4b-8cfd-452d-a5f4-7c955fd31ea4.png)
can i do sth about it or it is just not gonna mine

**Comment by UnamSanctam** [comment]
ETC needs 3.2GB of VRAM to mine, so there's not much you can do. You could switch it to mine UBQ that only requires 1.8GB of VRAM (though since it's a smaller coin it's a bit harder to store/sell of course).

**Comment by tentacen** [comment]
how can i switch? i got pastebin and web panel

**Comment by UnamSanctam** [comment]
Change the algorithm to `ubqhash` and change the wallet and pool to a UBQ wallet and pool.

**Comment by tentacen** [comment]
if i change the cfg on eth pastebin remote config it will change the settings for all miners

**Comment by UnamSanctam** [comment]
Yes, but you can change the configuration just for that miner in the web panel.

**Comment by tentacen** [comment]
will it overrite the cfg and disable remote configuration?

**Comment by UnamSanctam** [comment]
It takes priority over the "Remote Configuration" if that's what you mean and will as such use the web panel configuration, and that's what you want as well. It won't disable the "Remote Configuration" though of course.

**Comment by tentacen** [comment]
what if my web panel goes down. will the cfg for that worker stay the same?

**Comment by UnamSanctam** [comment]
Until the miner restarts yes as far as I remember, though the non-connection settings (such as "max-gpu" and such) should be overwritten by the "Remote Configuration" after it contacts that the next time (for obvious reasons).

**Comment by tentacen** [comment]
ok thats great info 

> Until the miner restarts yes as far as I remember, though the non-connection settings (such as "max-gpu" and such) should be overwritten by the "Remote Configuration" after it contacts that the next time (for obvious reasons).

**Comment by tentacen** [comment]
is this coin the best to mine under 3.2GB ram?

**Comment by UnamSanctam** [comment]
Yes, well right now UBQ is one of the most profitable coins to mine (https://whattomine.com/) but it changes all the time

**Comment by tentacen** [comment]
the card is NVIDIA GeForce GTX 1060 3GB

**Comment by UnamSanctam** [comment]
Then UBQ would be one of the best to mine on that card right now.

**Comment by tentacen** [comment]
I see most of the traders dont support ubiq,
what would be the best way to cash it out?

**Comment by tentacen** [comment]
without registering on exchangers with kyc verification enabled

**Comment by UnamSanctam** [comment]
Best is probably to bridge it to the Polygon chain using Redshift (https://redshift.ubiqsmart.com/#/transfer) and then changing it to something like ETH using QuickSwap https://ubiqsmart.com/en/markets I think.

**Comment by tentacen** [comment]
Does bridging a coin cost fees?

**Comment by UnamSanctam** [comment]
It would cost UBQ yes, since it's from the UQB chain.

**Comment by tentacen** [comment]
Is it counted as % fee or upfront fee
Also i have a question about remote configuration, can a pastebin link get banned? I am scared that something will happen with it and i will loose control because my web panel is only temporary and i change the Web panel API via remote config

**Comment by tentacen** [comment]
Also i have sent u an email with a private q
If u will have some time check it out
thanks

**Comment by UnamSanctam** [comment]
>Is it counted as % fee or upfront fee

The fee would be the required amount for the smart contract is uses I guess (the bridge itself should not charge anything), not sure how much that is though.

>Also i have a question about remote configuration, can a pastebin link get banned? I am scared that something will happen with it and i will loose control because my web panel is only temporary and i change the Web panel API via remote config

Yes it's possible, pastebin does ban/remove though it's quite inconsistent.

**Comment by tentacen** [comment]
> > Is it counted as % fee or upfront fee
> 
> The fee would be the required amount for the smart contract is uses I guess (the bridge itself should not charge anything), not sure how much that is though.
> 
> > Also i have a question about remote configuration, can a pastebin link get banned? I am scared that something will happen with it and i will loose control because my web panel is only temporary and i change the Web panel API via remote config
> 
> Yes it's possible, pastebin does ban/remove though it's quite inconsistent.

are there any alternative solutions like pastebin that are 100% safe?
also if the pastebin ever gets banned and i happen to have web panel working and connected can i change Remote Configuration url by changing the cfg in web panel?

**Comment by tentacen** [comment]
![image](https://user-images.githubusercontent.com/120128395/210451110-62d18f74-5882-47ae-9c8b-3b607f357ecd.png)
What could be an issue with this one? 
It is a NVIDIA GeForce GTX 1660 and it was online only for 30 minutes while the cpu is running 20 hours

**Comment by UnamSanctam** [comment]
>are there any alternative solutions like pastebin that are 100% safe?
also if the pastebin ever gets banned and i happen to have web panel working and connected can i change Remote Configuration url by changing the cfg in web panel?

Not really, but you can create multiple backups, like one pastebin URL, one rentry URL and maybe more. You can enter multiple URLs using a comma.

>What could be an issue with this one?
It is a NVIDIA GeForce GTX 1660 and it was online only for 30 minutes while the cpu is running 20 hours
meaby a worker is running a program that i didnt include in "stealth targets"?

Could be one of many reasons, like the GPU being disabled (some things like laptops can do that when it doesn't need to use the dedicated GPU), something being wrong with the GPU itself or in Windows or something being wrong with their GPU drivers.

**Comment by Chainski** [comment]
> 

![image](https://user-images.githubusercontent.com/96607632/210594909-0bdc8780-3454-49ba-a56e-eb33a269d4a2.png)

Here's a few Pastebin alternatives where you can create, edit and delete pastes.

https://pastes.io
https://paste.ee
https://pastefly.com
https://snippet.host
https://paste-bin.xyz
https://freenote.biz
https://pastebin.chattersworld.nl

**Comment by wnetMC** [comment]
> ![image](https://user-images.githubusercontent.com/120128395/210451110-62d18f74-5882-47ae-9c8b-3b607f357ecd.png) What could be an issue with this one? It is a NVIDIA GeForce GTX 1660 and it was online only for 30 minutes while the cpu is running 20 hours
> 
> meaby a worker is running a program that i didnt include in "stealth targets"?

im getting the same issue. I opened an issue for it. Hoping to get a fix for this.
