### ISSUE TITLE
Help me Unam

### ISSUE THREAD

**Issue by gurice** [UnamSanctam/SilentCryptoMiner#1351]
Hello Unam Sanctam,
I have remote control siteadress.com/json that i will siteadress.com/json.php i did it and I can't update json.when it's php, it's like in the picture, I'm waiting for your help.
Respects.

![Capture](https://user-images.githubusercontent.com/113937184/210846810-69318772-8dc4-4730-9952-b8c6d4b2f793.PNG)

**Comment by UnamSanctam** [comment]
You mean that the miner doesn't update with that? How is the HTML formatted? Since that's the most probable cause.

**Comment by gurice** [comment]
I did siteadress.com/data/json.php when I should have made siteaddress.com/data/json to remote control

**Comment by UnamSanctam** [comment]
You mean that you entered the wrong URL when making the miner? In that case you can just make the page that you entered wrongly. Both `siteadress.com/data/json.php` and `siteaddress.com/data/json` leads to the same page anyways.

**Comment by gurice** [comment]
Let me explain everything from the beginning. My English is not very good so I couldn't explain it properly.
I wrote the Remote Config section of the builder as example.com/data/json.php. But when I create this json.php file on my hosting, miners can not read. Would it cause this problem if I write the extension of this file as .php? So do I have to create a file with no extension called example.com/data/json? Can Miners extract data from source with .php file extension?

**Comment by UnamSanctam** [comment]
Yes of course, `example.com/data/json.php` would work fine, the web panel endpoint is a .php file as well. Make sure that the HTML formatting is correct, what you see on the page is not the same as what the miner sees.

**Comment by gurice** [comment]
Thanks in advance for all your help. Your software really makes my work easier. If I am successful, I want to donate.

**Comment by gurice** [comment]
I directly pasted the new settings into json.php, now when I say "View Page Source" I only see the codes I pasted. It should work after 100 minutes, right?

**Comment by gurice** [comment]
![Capture](https://user-images.githubusercontent.com/113937184/210855829-725457b4-2427-41f5-ad2c-05e35f664b1a.PNG)

**Comment by UnamSanctam** [comment]
Alright great, that should work.

**Comment by gurice** [comment]
thank you. I felt so stupid.

**Comment by UnamSanctam** [comment]
Haha no problem, it can be difficult to figure out. Just write here again if something doesn't work.

**Comment by gurice** [comment]
Hello Unam,
I'm sorry again for that. Even though I'm doing as we discussed, there is still a problem. Miners can't read data, I can't do Api Endpoint URL either. This is how I wrote siteadress.com/api/endpoint.php builder. But the miners do not appear there either. I need help on this.
![Screenshot_2023-01-06-07-20-45-811_com opera browser](https://user-images.githubusercontent.com/113937184/210929968-d57dcfcb-63d8-4751-8fc7-cdd69f890fd0.jpg)
![Screenshot_2023-01-06-07-22-34-726_com opera browser](https://user-images.githubusercontent.com/113937184/210929999-1bd9e1fd-5411-4c2f-8f43-781faa4d36b8.jpg)

**Comment by gurice** [comment]
![IMG_20230106_072553](https://user-images.githubusercontent.com/113937184/210930408-39f8413e-7953-45c4-879b-600288ab90fa.jpg)

**Comment by gurice** [comment]
I check from updater (.exe checker) url is correct but not working

**Comment by UnamSanctam** [comment]
And you' have entered `https://siteadress.com/api/endpoint.php` ?

**Comment by gurice** [comment]
Yes

**Comment by gurice** [comment]
I use infinityfree free hosting

**Comment by UnamSanctam** [comment]
Then either your hosting might be forcing something like having JavaScript enabled, or might be blocking the miner traffic (with something like the User-Agent). Try checking if there's any option that's forcing the visitor to enable JavaScript in your web host.

**Comment by destylul** [comment]
> Is there a hosting you can recommend? Free if possible.

use awardspace  .com
