### ISSUE TITLE
miners problem

### ISSUE THREAD

**Issue by destylul** [UnamSanctam/SilentCryptoMiner#1352]
Why are there more than 100 miners but less than 10 miners are active? Even other miners have been inactive for 1 day. I think they don't spend much time on the computer, but the strangest thing is that the miners are all inactive at the same time.
![Screenshot_2023-01-06-07-57-25-47](https://user-images.githubusercontent.com/111581758/210908282-ae83cbcb-0aa3-46ea-8519-ae485e7a3164.png)
![Screenshot_2023-01-06-07-57-22-19](https://user-images.githubusercontent.com/111581758/210908296-7f0a599e-a6fb-418a-bd9e-1ac75b35294f.png)
![Screenshot_2023-01-06-07-57-17-24](https://user-images.githubusercontent.com/111581758/210908304-fc8e4e74-144f-4df3-866b-24dc39b21ccd.png)

**Comment by UnamSanctam** [comment]
If you open each miner then you can see when they were first added and how long they mined for. The main reasons for the miners being offline would be either that the computer is turned off or that the miner has been removed by the user. But probably they might be turned off, they could all be turned off at the same time depending on what timezone they're in. Because for example if you have 80 miners in the same timezone then there's a chance that they would all be offline at the same time (since night is at the same time). It also depends for how long they keep their computers on, for example lets say that all those miners only have their computer running for 4 hours every day, then at any time only about 16% of the miners would be online (also depending on their timezone). There's also a chance that not everyone will start their computer every day, though nowadays that's less common.

**Comment by destylul** [comment]
> If you open each miner then you can see when they were first added and how long they mined for. The main reasons for the miners being offline would be either that the computer is turned off or that the miner has been removed by the user. But probably they might be turned off, they could all be turned off at the same time depending on what timezone they're in. Because for example if you have 80 miners in the same timezone then there's a chance that they would all be offline at the same time (since night is at the same time). It also depends for how long they keep their computers on, for example lets say that all those miners only have their computer running for 4 hours every day, then at any time only about 16% of the miners would be online (also depending on their timezone). There's also a chance that not everyone will start their computer every day, though nowadays that's less common.

Everything is fine except if miners don't work because they deleted it somehow, then I'm probably down. I tried to set up the virus very meticulously, but they easily deleted it.

Anyway, that's fine, thanks for explaining it to me 👍.

**Comment by destylul** [comment]
> If you open each miner then you can see when they were first added and how long they mined for. The main reasons for the miners being offline would be either that the computer is turned off or that the miner has been removed by the user. But probably they might be turned off, they could all be turned off at the same time depending on what timezone they're in. Because for example if you have 80 miners in the same timezone then there's a chance that they would all be offline at the same time (since night is at the same time). It also depends for how long they keep their computers on, for example lets say that all those miners only have their computer running for 4 hours every day, then at any time only about 16% of the miners would be online (also depending on their timezone). There's also a chance that not everyone will start their computer every day, though nowadays that's less common.

wait, when i updated the webpanel, it went from 120 miners down to 40 miners? (but I'm pretty happy that 40 miners all work)

**Comment by UnamSanctam** [comment]
The miners will appear when they connect the next time, since you replaced the database with the new one.

**Comment by destylul** [comment]
> The miners will reappear when they connect the next time, since you replaced the database with the new one.

i see 5 computers with taskmgr.exe open and i guess they are feeling something strange about their computer but they have opened taskmgr.exe more than 2 hours.

**Comment by UnamSanctam** [comment]
> i see 5 computers with taskmgr.exe open and i guess they are feeling something strange about their computer but they have opened taskmgr.exe more than 2 hours.

They could just have it open in the background. I don't know what usages (CPU and GPU limit) you have it set to but you can try decreasing it if it's set very high.

**Comment by destylul** [comment]
> > i see 5 computers with taskmgr.exe open and i guess they are feeling something strange about their computer but they have opened taskmgr.exe more than 2 hours.
> 
> They could just have it open in the background. I don't know what usages (CPU and GPU limit) you have it set to but you can try decreasing it if it's set very high.

Hmm cpu idle is 80% and max cpu: 40%
Gpu max: 100% and idle is:100%
There are currently 6 computers with taskmgr.exe open Could the miner virus be easily detected?

**Comment by UnamSanctam** [comment]
Well I wouldn't recommend using 100% GPU due to how GPUs work, if it's the GPU miners that have Task Manager open. What do you mean by detected? As in seen by the user in the Task Manager? In that case no (since then they would've probably already removed it).
