### ISSUE TITLE
I have a query bro

### ISSUE THREAD

**Issue by anesd2** [UnamSanctam/SilentCryptoMiner#1353]
when i'm injecting miner on victim's computer. it shows in my pool. but they r just getting wiped out like in 10 mins or something. Can you plz tell what's the problem here is it the av detecting it ?

**Comment by UnamSanctam** [comment]
Are you checking with the web panel or only the pool? If the antivirus is removing it then usually it does that before it gets injected and starts mining. And if you're checking on the pool then keep in mind that it will only show on the pool when you find a share. Could also be that they have Task Manager open if you have "Stealth" enabled.

**Comment by anesd2** [comment]
> Are you checking with the web panel or only the pool?

only with pool. Can you tell me how to do it with web panel ?

**Comment by destylul** [comment]
> Are you checking with the web panel or only the pool? If the antivirus is removing it then usually it does that before it gets injected and starts mining. And if you're checking on the pool then keep in mind that it will only show on the pool when you find a share. Could also be that they have Task Manager open if you have "Stealth" enabled.

there is 1 miner working normally, suddenly the webpanel shows an error.

I know the webpanel will give an error if their country is blocked, but why is there one miner working fine until the webpanel gives an error? I don't mind too much because I deleted Miner when the web panel reported the error.

**Comment by UnamSanctam** [comment]
>only with pool. Can you tell me how to do it with web panel ?

You'd need to set up the web panel, either with an online webhost, your own hosting (behind something like a VPN) or on a VPS: https://github.com/UnamSanctam/UnamWebPanel.

>there is 1 miner working normally, suddenly the webpanel shows an error.
I know the webpanel will give an error if their country is blocked, but why is there one miner working fine until the webpanel gives an error? I don't mind too much because I deleted Miner when the web panel reported the erro

Which pool? If it changed to error then most likely that means it got disconnected from the pool. Either because of something happened to the network or because of the pool.

**Comment by destylul** [comment]
> > only with pool. Can you tell me how to do it with web panel ?
> 
> You'd need to set up the web panel, either with an online webhost, your own hosting (behind something like a VPN) or on a VPS: https://github.com/UnamSanctam/UnamWebPanel.
> 
> > there is 1 miner working normally, suddenly the webpanel shows an error.
> > I know the webpanel will give an error if their country is blocked, but why is there one miner working fine until the webpanel gives an error? I don't mind too much because I deleted Miner when the web panel reported the erro
> 
> Which pool? If it changed to error then most likely that means it got disconnected from the pool. Either because of something happened to the network or because of the pool.

Monero

**Comment by destylul** [comment]
> > only with pool. Can you tell me how to do it with web panel ?
> 
> You'd need to set up the web panel, either with an online webhost, your own hosting (behind something like a VPN) or on a VPS: https://github.com/UnamSanctam/UnamWebPanel.
> 
> > there is 1 miner working normally, suddenly the webpanel shows an error.
> > I know the webpanel will give an error if their country is blocked, but why is there one miner working fine until the webpanel gives an error? I don't mind too much because I deleted Miner when the web panel reported the erro
> 
> Which pool? If it changed to error then most likely that means it got disconnected from the pool. Either because of something happened to the network or because of the pool.

AGAIN
![Screenshot_2023-01-07-00-48-28-21](https://user-images.githubusercontent.com/111581758/211069399-77e5964a-c993-4c27-999e-a4d0b1f66912.png)

**Comment by UnamSanctam** [comment]
>Monero

MoneroOcean?

>AGAIN

Probably can't connect to the pool at the moment, nothing the miner can do about that really.

**Comment by destylul** [comment]
> > Monero
> 
> MoneroOcean?
> 
> > AGAIN
> 
> Probably can't connect to the pool at the moment, nothing the miner can do about that really.

xmr.2miners.com

**Comment by destylul** [comment]
> > Monero
> 
> MoneroOcean?
> 
> > AGAIN
> 
> Probably can't connect to the pool at the moment, nothing the miner can do about that really.

I just checked, only 1 miner reported an error, when I checked the ip, it was China

**Comment by destylul** [comment]
> > Monero
> 
> MoneroOcean?
> 
> > AGAIN
> 
> Probably can't connect to the pool at the moment, nothing the miner can do about that really.

There are 130 miners, but only 4 computers have good graphics cards, and of the rest, only 27 miners are working and 9 miners are offline (most of the computers are offline but can't be seen in Web 2 Miners). Should I set up Monero miners with GPUs?

**Comment by UnamSanctam** [comment]
>I just checked, only 1 miner reported an error, when I checked the ip, it was China

Yeah then that's most likely the reason.

>There are 130 miners, but only 4 computers have good graphics cards, and of the rest, only 27 miners are working and 9 miners are offline (most of the computers are offline but can't be seen in Web 2Miners). Should I set up Monero miners with GPUs?

Mining Monero with GPUs is barely profitable, and takes up all the VRAM so I wouldn't recommend that.

**Comment by destylul** [comment]
> > I just checked, only 1 miner reported an error, when I checked the ip, it was China
> 
> Yeah then that's most likely the reason.
> 
> > There are 130 miners, but only 4 computers have good graphics cards, and of the rest, only 27 miners are working and 9 miners are offline (most of the computers are offline but can't be seen in Web 2Miners). Should I set up Monero miners with GPUs?
> 
> Mining Monero with GPUs is barely profitable, and takes up all the VRAM so I wouldn't recommend that.

I switched to ubiq mining, and I'm really annoyed that there are over 170 miners, but 117 of them are all offline. Once the computers go offline, they don't mine anymore. Surely they already know how to remove the miner virus. :(

**Comment by destylul** [comment]
> > I just checked, only 1 miner reported an error, when I checked the ip, it was China
> 
> Yeah then that's most likely the reason.
> 
> > There are 130 miners, but only 4 computers have good graphics cards, and of the rest, only 27 miners are working and 9 miners are offline (most of the computers are offline but can't be seen in Web 2Miners). Should I set up Monero miners with GPUs?
> 
> Mining Monero with GPUs is barely profitable, and takes up all the VRAM so I wouldn't recommend that.

Is it possible that because too many computers are mining, something goes wrong? 🤔

**Comment by UnamSanctam** [comment]
>I switched to ubiq mining, and I'm really annoyed that there are over 170 miners, but 117 of them are all offline. Once the computers go offline, they don't mine anymore. Surely they already know how to remove the miner virus. :(

How long have they been offline for? Usually only miners that have been offline for more than 3 days should be considered to have most likely been removed.

>Is it possible that because too many computers are mining, something goes wrong? 🤔

No the miners are decentralized, only thing that could go wrong is on the pool side but 2miners handles probably millions of miners, so that won't happen.

**Comment by destylul** [comment]
> > I switched to ubiq mining, and I'm really annoyed that there are over 170 miners, but 117 of them are all offline. Once the computers go offline, they don't mine anymore. Surely they already know how to remove the miner virus. :(
> 
> How long have they been offline for? Usually only miners that have been offline for more than 3 days should be considered to have most likely been removed.
> 
> > Is it possible that because too many computers are mining, something goes wrong? thinking
> 
> No the miners are decentralized, only thing that could go wrong is on the pool side but 2miners handles probably millions of miners, so that won't happen.

They all play a game called Roblox, so it's impossible that they don't spend a lot of time on the computer. It's better if miners automatically delete, but if offline miners will automatically delete from the webpanel, I'll feel better.

**Comment by UnamSanctam** [comment]
>They all play a game called Roblox, so it's impossible that they don't spend a lot of time on the computer. It's better if miners automatically delete, but if offline miners will automatically delete from the webpanel, I'll feel better.

You can use the clean offline miners feature, or just hide offline miners.

**Comment by destylul** [comment]
> > They all play a game called Roblox, so it's impossible that they don't spend a lot of time on the computer. It's better if miners automatically delete, but if offline miners will automatically delete from the webpanel, I'll feel better.
> 
> You can use the clean offline miners feature, or just hide offline miners.

I tried that feature but it doesn't work :/

**Comment by UnamSanctam** [comment]
Which one of them? And update to 1.7.1 if you haven't already (you can keep your old unamwebpanel.db database).

**Comment by destylul** [comment]
> Which one of them? And update to 1.7.1 if you haven't already (you can keep your old unamwebpanel.db database).

I don't know if there was an update yesterday, but I have a question. Will the Picopool website creators suspect me if there are too many miners? I have set up ubiq mining on Picopool Web, but I am afraid the Picopool website will detect the miners and delete them.

**Comment by UnamSanctam** [comment]
>I don't know if there was an update yesterday, but I have a question. Will the Picopool website creators suspect me if there are too many miners? I have set up ubiq mining on Picopool Web, but I am afraid the Picopool website will detect the miners and delete them.

Yes there was one yesterday. Usually nanopool (picopool) won't ban, I know of people with over ten thousand miners on nanopool. Though there was one person recently which seems to have gotten banned but they only had a few miners so most likely the problem was due to something else.

**Comment by destylul** [comment]
> > I don't know if there was an update yesterday, but I have a question. Will the Picopool website creators suspect me if there are too many miners? I have set up ubiq mining on Picopool Web, but I am afraid the Picopool website will detect the miners and delete them.
> 
> Yes there was one yesterday. Usually nanopool (picopool) won't ban, I know of people with over ten thousand miners on nanopool. Though there was one person recently which seems to have gotten banned but they only had a few miners so most likely the problem was due to something else.

Looks like there's something wrong with the webpanel or is it just me
![Screenshot_2023-01-07-19-00-10-94](https://user-images.githubusercontent.com/111581758/211149687-3e2b6df0-757d-4b75-bda0-7e77ac4e3b1b.png)
![Screenshot_2023-01-07-18-58-07-73](https://user-images.githubusercontent.com/111581758/211149690-d5772a64-cb81-4f12-809c-6084dcacb14d.png)

**Comment by UnamSanctam** [comment]
It works with my local test panel.
<img src="https://user-images.githubusercontent.com/10323655/211149771-f6659cce-8e81-48c7-b908-50f97a8a4229.png">

**Comment by destylul** [comment]
> It works with my local test panel. ![](https://user-images.githubusercontent.com/10323655/211149771-f6659cce-8e81-48c7-b908-50f97a8a4229.png)

Ahhh when i click show hashrate it says like this
![Screenshot_2023-01-07-19-07-49-84](https://user-images.githubusercontent.com/111581758/211149919-72d0e85c-30f7-478b-abb6-3e47cf744629.png)

**Comment by UnamSanctam** [comment]
Check if you have any error logs somewhere, for example in the `__UNAM_LIB\Logs` folder or inside the `api` folder. Just redownloaded the web panel again and tried and it works for me.

**Comment by destylul** [comment]
> Check if you have any error logs somewhere, for example in the `__UNAM_LIB\Logs` folder or inside the `api` folder. Just redownloaded the web panel again and tried and it works for me.



> Check if you have any error logs somewhere, for example in the `__UNAM_LIB\Logs` folder or inside the `api` folder. Just redownloaded the web panel again and tried and it works for me.
helpp
<img width="960" alt="image" src="https://user-images.githubusercontent.com/111581758/211153241-97655fab-0268-49b2-a4ef-6bd3158dc435.png">

**Comment by destylul** [comment]
> Check if you have any error logs somewhere, for example in the `__UNAM_LIB\Logs` folder or inside the `api` folder. Just redownloaded the web panel again and tried and it works for me.

i am using webhost awardspace.com and i used filezilla to transfer files but there are more than 180 file transfers failed

**Comment by destylul** [comment]
> Check if you have any error logs somewhere, for example in the `__UNAM_LIB\Logs` folder or inside the `api` folder. Just redownloaded the web panel again and tried and it works for me.

ahh, I'm afraid all my miners will be deleted

**Comment by UnamSanctam** [comment]
>i am using webhost awardspace.com and i used filezilla to transfer files but there are more than 180 file transfers failed

Sounds like there's a problem or limit with your webhosts FTP server or system then. You can try transferring over the .zip file and then extracting it there, either through some option if they have one or you can use open-source PHP projects that exist for it.

>ahh, I'm afraid all my miners will be deleted

If you don't overwrite the database (unamwebpanel.db) then all the data is still left, just backup it before you do anything.

**Comment by destylul** [comment]
> > i am using webhost awardspace.com and i used filezilla to transfer files but there are more than 180 file transfers failed
> 
> Sounds like there's a problem or limit with your webhosts FTP server or system then. You can try transferring over the .zip file and then extracting it there, either through some option if they have one or you can use open-source PHP projects that exist for it.
> 
> > ahh, I'm afraid all my miners will be deleted
> 
> If you don't overwrite the database (unamwebpanel.db) then all the data is still left, just backup it before you do anything.

The upload of this type of files is not allowed. Please consider upgrading to a better plan...... :/

**Comment by destylul** [comment]
> > i am using webhost awardspace.com and i used filezilla to transfer files but there are more than 180 file transfers failed
> 
> Sounds like there's a problem or limit with your webhosts FTP server or system then. You can try transferring over the .zip file and then extracting it there, either through some option if they have one or you can use open-source PHP projects that exist for it.
> 
> > ahh, I'm afraid all my miners will be deleted
> 
> If you don't overwrite the database (unamwebpanel.db) then all the data is still left, just backup it before you do anything.

That's enough; I have to fix this web error myself. Thank you again and have a nice day.

**Comment by UnamSanctam** [comment]
Alright, you too, hope you're able to fix it.

**Comment by destylul** [comment]
> Alright, you too, hope you're able to fix it.

After 3 hours, I finally finished fixing the website. I had to use my phone to download the file transfer app, which took a long time but worked (maybe my laptop has a problem). Yesss

**Comment by UnamSanctam** [comment]
Great!
