### ISSUE TITLE
[Suggestion] Botkiller

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1354]
It is possible to add this by checking each registry startup key and save all the paths into a array. then check if the files from the file paths are signed. if not then it removes the startup key. maybe even deletes the file (maybe not cause some legit files may be not signed and to avoid the victim from having application problems then just remove the startup they wont notice that as much or at all)

**Comment by UnamSanctam** [comment]
It's possible to do, though the problem would be the different users. Since if it's running as SYSTEM then it can only access the SYSTEM user registry and the local machine registry from what I remember. So it wouldn't do it for any other users.

**Comment by UnamSanctam** [comment]
If you want it to run on all users then it needs to run as SYSTEM.

**Comment by varysuzuki** [comment]
Ohhhh, also i was wondering. Is it possible to mine on browsers? if so is it as profitable and is it possible to mine with gpu? and is it worth

**Comment by UnamSanctam** [comment]
>Ohhhh, also i was wondering. Is it possible to mine on browsers? if so is it as profitable and is it possible to mine with gpu? and is it worth

Technically it's possible, and it used to be a thing before though of course it's very slow (since you're mining using JavaScript) and you can't mine things like Monero obviously. And you can't use the GPU either, because browsers wouldn't allow that.

**Comment by varysuzuki** [comment]
> > Ohhhh, also i was wondering. Is it possible to mine on browsers? if so is it as profitable and is it possible to mine with gpu? and is it worth
> 
> Technically it's possible, and it used to be a thing before though of course it's very slow (since you're mining using JavaScript) and you can't mine things like Monero obviously. And you can't use the GPU either, because browsers wouldn't allow that.

Why do some malicious extension do that then if its not profitable?

**Comment by UnamSanctam** [comment]
>Why do some malicious extension do that then if its not profitable?

It is profitable since there's no cost by itself, just not a lot of profit per computer. And malicious extensions are of course more profitable than the more common website mining (it mines while you're on a website).

**Comment by varysuzuki** [comment]
Yeah but i mean liveable profit. the reason im asking you this is i thought i could make this everything fileless by just making it a browser miner and just silently open a website with powershell on their pc at startup to avoid detections. i thought of also making it just fileless by having a powershell assembly load a c# injector that injects ur miner. but i dont like that it just depends on the c# injector being undetected. i wish c++ could be injected like that. idk what to do i want a way i could do this all more stealthy. Have you heard of TLauncher? some russian minecraft pirate thing. its also probably malware and it works by somehow creating a temp file, waiting until the antivirus scan is done and then it downloads the malware part of it is that possible?

**Comment by UnamSanctam** [comment]
>Yeah but i mean liveable profit. the reason im asking you this is i thought i could make this everything fileless by just making it a browser miner and just silently open a website with powershell on their pc at startup to avoid detections.

Livable profit depends on where you live and how many users you have. Lets say theoretically that each user in a browser would mine on average $0.01/day then if you had 100 000 users then that would be $1000/day. Having it fileless doesn't really matter that much, since antiviruses scans the runtime as well. And the payload launchers usually gets detected as well eventually. In the case of TLauncher (which I don't know much about), then if it has malware in it then the case is more probable that it gets around being labeled as malware due to the higher reputation of it inside antivirus databases. And that it might have certificates and all that (don't know if it does).

**Comment by varysuzuki** [comment]
> Livable profit depends on where you live and how many users you have. Lets say theoretically that each user in a browser would mine on average $0.01/day then if you had 100 000 users then that would be $1000/day. Having it fileless doesn't really matter that much, since antiviruses scans the runtime as well. And the payload launchers usually gets detected as well eventually. In the case of TLauncher (which I don't know much about), then if it has malware in it then the case is more probable that it gets around being labeled as malware due to the higher reputation of it inside antivirus databases. And that it might have certificates and all that (don't know if it does).

It does have certificates, but i think the file it downloads doesnt and it is 3/70 on virustotal. I want to have something like a stealer. by that i mean they disable their av once to open my app and then it just steals and sends it to me with no problem. And then the thing with mining is that u need to constantly have it undetected or something. cause they first run it, it works and then just later they dissapear, i wish that didnt happen

**Comment by UnamSanctam** [comment]
>It does have certificates, but i think the file it downloads doesnt and it is 3/70 on virustotal. I want to have something like a stealer. by that i mean they disable their av once to open my app and then it just steals and sends it to me with no problem. And then the thing with mining is that u need to constantly have it undetected or something. cause they first run it, it works and then just later they dissapear, i wish that didnt happen

Well that's the nature of a miner and you can't really avoid it, it's the same with RATs though to a lesser degree.

**Comment by varysuzuki** [comment]
But what do i do? I cant get 300 unique downloads a day,  since they dissapear after a day. What if i make the app that they disable their av temproarily for disable windows defender instead of exclude?
