### ISSUE TITLE
Delay?

### ISSUE THREAD

**Issue by destylul** [UnamSanctam/SilentCryptoMiner#1356]
why i switched to mining ubiq but miner still mining etc?
![Screenshot_2023-01-08-09-31-39-65](https://user-images.githubusercontent.com/111581758/211178036-442993c3-1864-478f-b30a-9c540fbc2ffe.png)

**Comment by destylul** [comment]
Uhh
![Screenshot_2023-01-08-09-35-42-67](https://user-images.githubusercontent.com/111581758/211178063-674b85ed-f949-4886-8973-0ad35dc3b9a5.png)

**Comment by UnamSanctam** [comment]
Is your configuration correct? Did you remember to set it to `stratums` since your using SSL?

**Comment by destylul** [comment]
> Is your configuration correct? Did you remember to set it to `stratums` since you're using SSL?

uh, the other miners are all fine mining ubiq, there may have been a problem with the victim's computer

**Comment by destylul** [comment]
> stratums

If I use ssl do I have to set it to `**stratums**`?

**Comment by UnamSanctam** [comment]
Yes that's correct.

**Comment by destylul** [comment]
> Yes that's correct.



> Yes that's correct.

this?
<img width="144" alt="image" src="https://user-images.githubusercontent.com/111581758/211197575-719ffe27-cf9a-4ec3-97bd-799a146c625f.png">

**Comment by UnamSanctam** [comment]
Yes.

**Comment by destylul** [comment]
> Yes.
there are some miners like this but most of the other miners are doing pretty well
<img width="764" alt="image" src="https://user-images.githubusercontent.com/111581758/211197650-ef86e9c7-d100-4ac0-9a03-5ae722de255e.png">

**Comment by destylul** [comment]
> Yes.

a damn, it's because the gpu is pretty weak because there's only 512MB of vram

**Comment by UnamSanctam** [comment]
Yeah that could happen, usually it would say "Not enough free VRAM", but with such old GPUs anything can happen (probably can't even proceed to the VRAM check).

**Comment by destylul** [comment]
> Yeah that could happen, usually it would say "Not enough free VRAM", but with such old GPUs anything can happen (probably couldn't even proceed to the VRAM check).

I've asked too many questions today, so I'll close the issue. (Now, what bothers me the most is that when offline miners won't come online anymore, I hope those victims are just busy with something and not due to a deleted miner virus.) Have a nice day!
