### ISSUE TITLE
Hashrate

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1357]
Is 9.4 MH/s on ubqhash normal with a NVIDIA GeForce RTX 3070 Ti?

**Comment by UnamSanctam** [comment]
At 100%? Then no something else is using the GPU in the background.

**Comment by shainodev** [comment]
90%, and hes playing a truck game i think

**Comment by UnamSanctam** [comment]
Yes then the game is most likely taking a lot of the GPU, games try to use around 100% of the GPU since that's what they are designed to do. The card could also be an LHR card as well.
