### ISSUE TITLE
GPU workers not logging

### ISSUE THREAD

**Issue by tentacen** [UnamSanctam/SilentCryptoMiner#1358]
![image](https://user-images.githubusercontent.com/120128395/211194825-dc04b8c3-3b12-4c34-860c-4b9995c1ccd8.png)
![image](https://user-images.githubusercontent.com/120128395/211194837-8b5beec9-34ee-4427-9dca-0e96e2a3982d.png)
Those are 2 new workers, they mine only cpu and the gpu didnt even show up on web panel.

**Comment by UnamSanctam** [comment]
Then it's due to something on/with their computer, I don't have access to them so I can't really know.

**Comment by wnetMC** [comment]
I have 2 workers that were mining fine for around an hour and then gpu mining stopped, with cpu miner still running.
![image](https://user-images.computersgithubusercontent.com/37955902/211747425-e2afa4c4-d839-412c-b07a-9dcbf495123c.png)
The boxes have  the same specs as @tentacen weirdly.

**Comment by wnetMC** [comment]
yeah I'm getting the same issue, GPU miners aren't logging
