### ISSUE TITLE
Plsss helpp unamm

### ISSUE THREAD

**Issue by destylul** [UnamSanctam/SilentCryptoMiner#1360]
![Screenshot_2023-01-08-23-04-52-57](https://user-images.githubusercontent.com/111581758/211206838-2dac6472-312a-4847-90e3-0d856b4faf6f.png)
Damn it damn itdamn it

**Comment by destylul** [comment]
the creator of the site discovered and banned my web, now i can't back it up anymore?

**Comment by destylul** [comment]
Although miners are still mining, is there a way to back it up?

**Comment by destylul** [comment]
even so I can't use any webhosting anymore. Is there any webhosting that is most suitable? or is there any other way?

**Comment by destylul** [comment]
actually my site has been banned 3 times. 1st time is 000webhost 2nd time is infinitytree 3rd time is this time

**Comment by UnamSanctam** [comment]
If you can't connect to their server then you won't be able to backup your database (obviously), but if you have a "Remote Configuration" set then you can point the miners to another web panel URL. Or if you own the URL then you can point it somewhere else. When the miners connect to that they will be re-added. I'm not sure which webhosts are the best since I've only ever hosted things myself.

**Comment by destylul** [comment]
I have to delete all the miners and start over and over again?

**Comment by destylul** [comment]
![Screenshot_2023-01-08-23-17-15-83](https://user-images.githubusercontent.com/111581758/211207371-3217b086-daa0-4690-a101-3bc5cf3fe292.png)

**Comment by UnamSanctam** [comment]
Do you have a "Remote Configuration" set? If you do then you can change the settings from there (including the web panel URL). If not then the miners will just keep mining like how they are now.

**Comment by destylul** [comment]
> Do you have a "Remote Configuration" set? If you do then you can change the settings from there (including the web panel URL). If not then the miners will just keep mining like how they are now.

damn, I didn't set it up because it wasn't very useful but now.. a hope

**Comment by destylul** [comment]
> Do you have a "Remote Configuration" set? If you do then you can change the settings from there (including the web panel URL). If not then the miners will just keep mining like how they are now.

if i make a website again, the creator of that website will continue to ban my site

**Comment by destylul** [comment]
> Do you have a "Remote Configuration" set? If you do then you can change the settings from there (including the web panel URL). If not then the miners will just keep mining like how they are now.

hmm maybe i'll find another webhost but i'm afraid my site will keep getting banned.

Uhh, how to backup web using remote configuration?

**Comment by UnamSanctam** [comment]
With the "Remote Configuration" it's possible to change the web panel URL using the `"api-endpoint": "API Endpoint URL"` option.

**Comment by destylul** [comment]
> With the "Remote Configuration" it's possible to change the web panel URL using the `"api-endpoint": "API Endpoint URL"` option.

so the line "remote-config": "Remote Configuration URL", "api-endpoint": "API Endpoint URL" will put in pastebin?

**Comment by destylul** [comment]
> With the "Remote Configuration" it's possible to change the web panel URL using the `"api-endpoint": "API Endpoint URL"` option.

i created new webpanel and this time i will be more careful

**Comment by destylul** [comment]
> With the "Remote Configuration" it's possible to change the web panel URL using the `"api-endpoint": "API Endpoint URL"` option.

like this? https://pastebin.com/raw/Wa2Twbs2
:/?

**Comment by UnamSanctam** [comment]
Yes though you'll only need to enter `"api-endpoint": "API Endpoint URL"` into it when you want to change web panel. Since you won't need to use the `"remote-config"` option there because that's already the "Remote Configuration".

**Comment by destylul** [comment]
> Yes though you'll only need to enter `"api-endpoint": "API Endpoint URL"` into it when you want to change web panel. Since you won't need to use the `"remote-config"` option there because that's already the "Remote Configuration".

Okay, thank you. Will WebPanel work with the web host, byet.com?

**Comment by UnamSanctam** [comment]
>Okay, thank you. Will WebPanel work with the web host, https://byet.host/?

It will work with any webhost that supports PHP and the SQLite PHP driver, so nearly any webhost.
