### ISSUE TITLE
Crypter ?

### ISSUE THREAD

**Issue by anesd2** [UnamSanctam/SilentCryptoMiner#1362]
Bro I used a crypter to encrypt miner but after that it was not opening and says"This app can't run on your pc" ? why is this happening ?
and using a crypter bypass uac ?

**Comment by UnamSanctam** [comment]
>Bro I used a crypter to encrypt miner but after that it was not opening and says"This app can't run on your pc" ? why is this happening ?

Well it's your cryper that's causing that, so check that the options in the crypter are correct. And make sure that it's crypting 64-bit.

>and using a crypter bypass uac ?

Depends on your crypter, it might have a UAC bypass or not.

**Comment by floof989763** [comment]
https://t.me/flooftg
this is my telegram

> > Well it's your cryper that's causing that, so check that the options in the crypter are correct. And make sure that it's crypting 64-bit.
> 
> Bro i am using powershell script and aes encryption with 128 bit block size. do u think this is the reason ?? and if yes how can i fix it ?

https://t.me/flooftg 
this is my telgram. msg me i can sort your issue

**Comment by UnamSanctam** [comment]
>Bro i am using powershell script and aes encryption with 128 bit block size. do u think this is the reason ?? and if yes how can i fix it ?

No it would be your implementation of whatever you're doing probably that creates an invalid file.

**Comment by AMERWARD** [comment]
Не удаётся обфусцировать и закриптовать майнер, с чем это может быть связано?  прошлые версии криптовались кофузером.
