### ISSUE TITLE
Help me pleaseee

### ISSUE THREAD

**Issue by hotsky786** [UnamSanctam/SilentCryptoMiner#1364]
Hey there... 

Can you please suggest me something... As the miner is getting detected by the defender while running.

Please help....

**Comment by UnamSanctam** [comment]
While starting or while the miner is running? If while starting then yes you'd need a crypter or something similar since obviously it won't be undetected for very long after each version release. If while running then make sure that you have "Add Defender Exclusions" enabled.

**Comment by kabuchi391** [comment]
I will give you my telegram and send you link to some crypters on github.
Contact me through telegram.
My Username is MechaXT

**Comment by hotsky786** [comment]
@UnamSanctam can you please suggest any crypter so that the file can be undetectable when it starts... Pleaseee

**Comment by hotsky786** [comment]
@UnamSanctam can you please suggest any crypter so that the file can be undetectable when it starts... Pleaseee

**Comment by UnamSanctam** [comment]
>@UnamSanctam can you please suggest any crypter so that the file can be undetectable when it starts... Pleaseee

I haven't really tested any crypter for the last few years so I don't know which ones are good at the moment.
