### ISSUE TITLE
Run as SYSTEM patched ?

### ISSUE THREAD

**Issue by Chainski** [UnamSanctam/SilentCryptoMiner#1365]
The **RUN AS SYSTEM** option in startup tab no longer works for me , I think there's a patch for it or something so i changed it to **RUN AS ADMIN** in the options tab. review this and let me know if there's really a patch.

![image](https://user-images.githubusercontent.com/96607632/211576187-91673b44-8792-40a4-9e08-c382fc5039e3.png)

**Comment by UnamSanctam** [comment]
It works fine for me, but you need "Run as Administrator" to be enabled for the installed miner to run as SYSTEM, hence the administrator shield next to the option. Since it can't install it as the SYSTEM user unless it has administrator permissions.

**Comment by Chainski** [comment]
Go it fixed thanks !

> It works fine for me, but you need "Run as Administrator" to be enabled for the installed miner to run as SYSTEM, hence the administrator shield next to the option. Since it can't install it as the SYSTEM user unless it has administrator permissions.
