### ISSUE TITLE
Watch dog running: No

### ISSUE THREAD

**Issue by destylul** [UnamSanctam/SilentCryptoMiner#1366]
I just realized that one day has passed, but there are no miners added to the list in Webpanel.
When I try it on my computer, it shows these lines:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/111581758/211722674-4e897eea-2a33-4b4a-bdec-4c89068f8e51.png">

**Comment by UnamSanctam** [comment]
That means it didn't install, make sure that the "Startup" settings and such are correct.

**Comment by destylul** [comment]
> That means it didn't install, make sure that the "Startup" settings and such are correct.

**Comment by destylul** [comment]
> That means it didn't install, make sure that the "Startup" settings and such are correct.

Okay, I don't understand why it's like this, but when I create a new one, sometimes it works and sometimes it doesn't.
