### ISSUE TITLE
GPU miner stopping after a while, with CPU continuing.

### ISSUE THREAD

**Issue by slezercc** [UnamSanctam/SilentCryptoMiner#1367]
I have 2 workers that were mining fine for around an hour and then gpu mining stopped, with cpu miner still running.
![image](https://user-images.githubusercontent.com/37955902/211748629-8683c78d-de6e-425f-af6d-f9c0a2ce2406.png)

**Comment by UnamSanctam** [comment]
It's something specific with those computers most likely, what are the specs of them?

**Comment by wnetMC** [comment]
Both are:
GPU NVIDIA GeForce GTX 1660 Ti
CPU Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

And all of my miners have the same IP, i thought that was a bug :/

![image](https://user-images.githubusercontent.com/37955902/211770661-216cca07-1988-41cf-bc4e-d282df4ab6b1.png)

**Comment by UnamSanctam** [comment]
Are you using some sort of reverse proxy? Since then that could be correct, because if you are then it is showing the reverse proxy IP (the web panel cannot know the original IPs unless the reverse proxy tells it to the web panel). But the GTX 1660 should work fine, the longest I've test mined on one is 2 days until I stopped the test, so it's most likely due to something with the computer. If it's a laptop then it could be due to that, since most laptops "disable" the dedicated GPU when not needed (my laptop does that as well), though to varying degrees. But I can't really know why unless I had access to it. How many does it happen for?

**Comment by wnetMC** [comment]
Im not using a reverse proxy afaik, im hosting the web panel on repl.it. and the computers are desktops

**Comment by UnamSanctam** [comment]
Then the host must have one built-in or something, since that's a private IP address. I can't really tell what's different with that computer unless I had access to it. Since it doesn't happen for any of mine (obviously).

**Comment by wnetMC** [comment]
Could I somehow give you access?

**Comment by Frax-Python** [comment]
can you give me the website link? thanks @wnetMC

**Comment by wnetMC** [comment]
you want my panel link? what the fuck? no?

**Comment by wnetMC** [comment]
@Frax-Python you want my panel url? what the fuck? no?

**Comment by wnetMC** [comment]
> hi i wan a using for GPU AND IP ,,DO HELP ME....

man stfu and make your own issue

**Comment by wnetMC** [comment]
I'm still getting this issue with all of my miners. The GPU miner simply stops after a few hours and the cpu keeps mining. Some of the GPU miners keep going but they're stuck at 0H/s

**Comment by UnamSanctam** [comment]
>I'm still getting this issue with all of my miners. The GPU miner simply stops after a few hours and the cpu keeps mining. Some of the GPU miners keep going but they're stuck at 0H/s

Some or all of them? Longest I've tried mining was 3 days and I didn't see any issues, how long is the "Runtime" of those miners? And do you have hashrate history enabled? In that case show that one for the longest running miner as well.

**Comment by wnetMC** [comment]
> > I'm still getting this issue with all of my miners. The GPU miner simply stops after a few hours and the cpu keeps mining. Some of the GPU miners keep going but they're stuck at 0H/s
> 
> Some or all of them? Longest I've tried mining was 3 days (with the newest version) and I didn't see any issues, how long is the "Runtime" of those miners? And do you have hashrate history enabled? In that case show that one for the longest running miner as well.

Okay so, I ran my miner on around 10 PCs and 3 of them are still GPU mining, but with 0H/s, the other ones stopped after around 6-9 hours. The hashrate history for the ones that kept going at 0H/s shows no history (empty) and the other ones are like this: ![image psd](https://user-images.githubusercontent.com/37955902/219713948-0b5101cc-46e8-4345-b056-ebba46399703.png)

**Comment by UnamSanctam** [comment]
Hmm, are they all 1660 or 1660 Ti's?

**Comment by wnetMC** [comment]
> Hmm, are they all 1660 or 1660 Ti's?

They all have these exact specs.

**Comment by UnamSanctam** [comment]
Is there something special with those computer or are they just normal personal home computers? Otherwise I guess there could also be something wrong with the 1660/1660 Ti GPU line itself, I'll have to run the miner for a few days myself (though I don't have a 1660) to see if anything happens.
