### ISSUE TITLE
the problem of the program self-starting

### ISSUE THREAD

**Issue by enfy3nb** [UnamSanctam/SilentCryptoMiner#1370]
Hi UnamSanctam, on some machines, the program is not automatically added to scheduled tasks and registry startup entries.

**Comment by UnamSanctam** [comment]
Even with the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings? Can you give some more information? Since otherwise there isn't really anything I can do about it.

**Comment by enfy3nb** [comment]
Hey bro, I generated the miner using the configuration file "ExampleSettings_Full.xml" and nothing happens when I run it, neither the watchdog nor the miner is running and no startup items are created in the scheduled tasks.

**Comment by UnamSanctam** [comment]
Download Process Hacker, then sort it by "Start time" (https://www.youtube.com/watch?v=EkXSRm8-DdQ) and then start the miner and see what happens in Process Hacker.

**Comment by enfy3nb** [comment]
I followed the steps you said to debug, after double-clicking to run miner, it started powershell, after powershell finished running, the miner installer exited and no more response, I tested 5 servers, only one was installed successfully.

**Comment by UnamSanctam** [comment]
Double-click the powershell that opens, copy the command line and then open powershell as administrator, then paste the command and run in.

**Comment by enfy3nb** [comment]
powershell printed an error ： "New-ScheduledTaskAction : Cannot connect to CIM server."

**Comment by UnamSanctam** [comment]
Alright then it's due to your servers, do you not get the specific error after "Cannot connect to CIM server"? Either I would guess the administrator account you have does not have the required permissions, something has been disabled or the WMI is corrupt.

**Comment by enfy3nb** [comment]
Thanks bro, it should not be a problem with SilentCryptoMiner.
