### ISSUE TITLE
I need a help for HiveOS

### ISSUE THREAD

**Issue by Frax-Python** [UnamSanctam/SilentCryptoMiner#1371]
does anyone know how to setup hiveOS with the silent miner? thanks in advance for all those who will answer me

**Comment by UnamSanctam** [comment]
Depends on what you mean, do you mean the Hiveon pool or the operating system, if you mean the Hiveon Pool then just set it up like normal. If you mean the operating system then you can't since HiveOS is a separate Linux based operating system.

**Comment by Frax-Python** [comment]
> Depends on what you mean, do you mean the Hiveon pool or the operating system, if you mean the Hiveon Pool then just set it up like normal. If you mean the operating system then you can't since HiveOS is a separate Linux based operating system.

can you contact me on discord because i cant do it thanks diasofaSOFPW23#5530

**Comment by UnamSanctam** [comment]
Unfortunately I'm banned on Discord for helping people with the miner, my only real private contact method at the moment is my email: unams@protonmail.com.
