### ISSUE TITLE
Remote Configuration issue

### ISSUE THREAD

**Issue by msfcon5ol3** [UnamSanctam/SilentCryptoMiner#1373]
Does this support multiple remote configurations ?

for example separating each config  with comma 

```
https://rentry.co/kffo8/raw,https://pastebin.com/raw/BNDpzG0p
```

**Comment by UnamSanctam** [comment]
Yes, you can add any amount like that, if the first one doesn't work then it will continue trying all of them until one works.

**Comment by msfcon5ol3** [comment]
> Yes, you can add any amount like that, if the first one doesn't work then it will continue trying all of them until one works.

Thanks.
