### ISSUE TITLE
virustotal

### ISSUE THREAD

**Issue by destylul** [UnamSanctam/SilentCryptoMiner#1374]
Should I scan virus files with VirusTotal? Will it have any effect on my miner virus file? If it affects my files, can I use other virus scanning websites?

**Comment by Cheater-Hub** [comment]
Never scan you own files with virustotal virustotal sends the results to a lot of anti viruses and it effects the detection rate

**Comment by destylul** [comment]
> Never scan you own files with virustotal virustotal sends the results to a lot of anti viruses and it effects the detection rate

Thx!
