### ISSUE TITLE
Setup Default Name

### ISSUE THREAD

**Issue by jansdnfhudf** [UnamSanctam/SilentCryptoMiner#1375]
Hello. I would like to know how is possible to set one worker name for multiple devices. So far so good everything works with {RANDOM} and the other features. However, I want to set one default name.

Thank you in advance!

**Comment by UnamSanctam** [comment]
Yes if you just enter a worker name, like `Worker` for example then they will mine under that worker name.

**Comment by jansdnfhudf** [comment]
Thank you for your reply. So basically. 42747458376743etgbcdfvgt357.User1 and the worker name will be shown as User 1 in the mining pool? And one more question. I use the remote url as domain.com/file.txt where all details are mentioned. It is opened in the browser and it acts same as the pastebin url. That should be fine?

**Comment by UnamSanctam** [comment]
Yes that's correct. And using that for the "Remote Configuration" should work just fine.

**Comment by jansdnfhudf** [comment]
It's me again. When I add jf738727384rtreterter172818.User1 and install it is shown as jf738727384rtreterter172818.User1 under the user field in the webpanel. However, it is like that while it is shown as stopped. Once is became active the jf738727384rtreterter172818.User1 has been replaced like jf738727384rtreterter172818.ksdkfssu - some random characters. Not sure how it will show in the pool. I do not user {RANDOM} or anything other.

**Comment by UnamSanctam** [comment]
And you don't have a "Remote Configuration" or a web panel configuration that uses `{RANDOM}`?

**Comment by jansdnfhudf** [comment]
Oh I am so stupid. I have RANDOM in the remote file. Let me try updating it there too.
