### ISSUE TITLE
Add a randomize password on install feature

### ISSUE THREAD

**Issue by grisuIIARCHLINUX** [UnamSanctam/SilentCryptoMiner#1378]
I mine on moneroocean.stream, but passwords there are names for the miners
But i install the same .exe on like 5 diffrent devices so it would be nice to make a randomize pw on install so they dont all mine under the same name

**Comment by UnamSanctam** [comment]
You can use `{COMPUTERNAME}` or `{RANDOM}` as the worker name.

**Comment by grisuIIARCHLINUX** [comment]
Oh nice thanks
