### ISSUE TITLE
help anyone please !!!

### ISSUE THREAD

**Issue by zanatechnology** [UnamSanctam/SilentCryptoMiner#138]
hello @UnamSanctam i hope you doing well, bro can you just tell me or advice me how i can make discord RAT please or an github works properly really i used almost github reps. all not work properly, please help me in that.
thank you previously🙏
![143451026-b123bd56-59d4-4bd2-8afc-f6194f573c7f](https://user-images.githubusercontent.com/89279699/145863035-e3f6defd-f00d-48d9-badc-b648a8c0b509.PNG)
like that 👆

**Comment by Sh4r3cat** [comment]
nice this is my pic lol and its not a discord rat but okay

**Comment by zanatechnology** [comment]
So what it is ? @Sh4r3cat 
And also I've asked you about it you didn't answered 😑
