### ISSUE TITLE
Multiple Stuff again

### ISSUE THREAD

**Issue by MJMODZZ** [UnamSanctam/SilentCryptoMiner#1380]
I know you already hate me because I create so many tickets, but I always have new Suggestions and Ideas to improve the miner and profit for me.

Whats the best settings i can setup to make the most profit, means algorythm, extra parameters...

Im mining 50% on GPU , 100% Idle mining GPU, ETC
30% CPU , 100% Idle CPU XMR

I have no extra parameters and im mining with the default XMR and ETC algorythm. Would be cool if you show me how to improve the profit, as pool i use xmr.2miners and ethermine, my current profit is about 1900-2200$ in a month.
Another thing is, could you maybe add a update function in the Unam panel? It could use a tunnel to connect the Server PC

**Comment by edizan** [comment]
Unam Sanctam which eth wallet is the best regarding staying anonymous? And is it good to make 50% on GPU , 100% Idle mining GPU, ETC and 30% CPU AND 100% IDLE CPU XMR? I see you have different values in your full settings file. Also, shall I enable to kill targets and enter that long list posted here? Also what about the rootkit? I see it not enabled by default aswell. Is it better to have it enabled?

**Comment by MJMODZZ** [comment]
> Unam Sanctam which eth wallet is the best regarding staying anonymous? And is it good to make 50% on GPU , 100% Idle mining GPU, ETC and 30% CPU AND 100% IDLE CPU XMR? I see you have different values in your full settings file. Also, shall I enable to kill targets and enter that long list posted here? Also what about the rootkit? I see it not enabled by default aswell. Is it better to have it enabled?

You can use the miner for different ways, the suspicios way and the legit way. Legit way means lower CPU usage and all that so the victimmy doesnt notice he ran into a CoinMiner. The suspicios way is to run a miner which makes more profit in short time, for example the rootkit will change settings on the computer, manipulate things and stuff. Same as for disable windows updates will disable windows updates. Thats really suspicios because the user will notice that if he wants to update the PC

**Comment by edizan** [comment]
Thank you for your reply. Would you mind to send your telegram or any other place where we can chat? I would like to exchange some experiences.

**Comment by MJMODZZ** [comment]
> Thank you for your reply. Would you mind to send your telegram or any other place where we can chat? I would like to exchange some experiences.

Join my DC server. I normally dont use telegram

**Comment by varysuzuki** [comment]
Yo, do u use the normal silentcryptominer or do u crypt it at all? and do u spread the silentcryptominer directly? also u mine xmr even though its not that profitable, u said u earn 2000 a month how much of that is xmr and how much is etc?

**Comment by MJMODZZ** [comment]
> Thank you for your reply. Would you mind to send your telegram or any other place where we can chat? I would like to exchange some experiences.

Attention to this guy, will just waste your time and try to scam you
185.244.242.73 is his IP adress

**Comment by MJMODZZ** [comment]
> Yo, do u use the normal silentcryptominer or do u crypt it at all? and do u spread the silentcryptominer directly? also u mine xmr even though its not that profitable, u said u earn 2000 a month how much of that is xmr and how much is etc?

1300 is ETC, 700 is XMR. As Long you mine XMR on CPU, its ok profitable. And I do not use unam silent miner directly, i have build it into my RAT and added some Funktions and Stuff. I spread it as backdoor in a well known Software, provided by idiots and im their dev.

**Comment by varysuzuki** [comment]
> 1300 is ETC, 700 is XMR. As Long you mine XMR on CPU, its ok profitable. And I do not use unam silent miner directly, i have build it into my RAT and added some Funktions and Stuff. I spread it as backdoor in a well known Software, provided by idiots and im their dev.

Custom rat? and when you use it in ur rat. Do you make it drop and execute the unams miner or make it load in memory?

**Comment by MJMODZZ** [comment]
> > 1300 is ETC, 700 is XMR. As Long you mine XMR on CPU, its ok profitable. And I do not use unam silent miner directly, i have build it into my RAT and added some Funktions and Stuff. I spread it as backdoor in a well known Software, provided by idiots and im their dev.
> 
> Custom rat? and when you use it in ur rat. Do you make it drop and execute the unams miner or make it load in memory?

Both is possible. I made the CPU and GPU usage controllable in the RAT panel, means at any time i can lower or higher the usage for all online clients at the same time. I also use my own RAT watchdog as watchdog.

**Comment by varysuzuki** [comment]
> Both is possible. I made the CPU and GPU usage controllable in the RAT panel, means at any time i can lower or higher the usage for all online clients at the same time. I also use my own RAT watchdog as watchdog.

your rat is c#? thank you btw! and also cause you have your own type of system does that mean that you dont use critical process?

**Comment by MJMODZZ** [comment]
> > Both is possible. I made the CPU and GPU usage controllable in the RAT panel, means at any time i can lower or higher the usage for all online clients at the same time. I also use my own RAT watchdog as watchdog.
> 
> your rat is c#? thank you btw! and also cause you have your own type of system does that mean that you dont use critical process?

Its made in VBNet, Visual Basic is really windows internal, only works for Windows too. You can simply use already satisfied consts and includes which you normally have to code in other languages

**Comment by varysuzuki** [comment]
> Its made in VBNet, Visual Basic is really windows internal, only works for Windows too. You can simply use already satisfied consts and includes which you normally have to code in other languages

isnt that the same for c#? both use .NET. but okay, why wouldnt you use c++ tho?

**Comment by MJMODZZ** [comment]
> > Its made in VBNet, Visual Basic is really windows internal, only works for Windows too. You can simply use already satisfied consts and includes which you normally have to code in other languages
> 
> isnt that the same for c#? both use .NET. but okay, why wouldnt you use c++ tho?

C# and VBNet already have their own designer, for C++ you need backends and ImGui first to make an UI. And also the file size in C++ will be lot bigger. Its easy to get a Compiler for the .NET but harder to get a compiler for C++ you can build into Apps.
In Final its also easyer and better to make it in VBNet instead of C++. Have you ever seen a **GOOD** RAT made in C++?

**Comment by varysuzuki** [comment]
Have you ever seen a **GOOD** RAT made in C++?

Remcos, Bitrat. And cause its a rat its less detected if its c++ so i think really it makes it better but of course vbnet is easier. But thank you for help!

**Comment by msfcon5ol3** [comment]
> > > 1300 is ETC, 700 is XMR. As Long you mine XMR on CPU, its ok profitable. And I do not use unam silent miner directly, i have build it into my RAT and added some Funktions and Stuff. I spread it as backdoor in a well known Software, provided by idiots and im their dev.
> > 
> > 
> > Custom rat? and when you use it in ur rat. Do you make it drop and execute the unams miner or make it load in memory?
> 
> Both is possible. I made the CPU and GPU usage controllable in the RAT panel, means at any time i can lower or higher the usage for all online clients at the same time. I also use my own RAT watchdog as watchdog.

can you send me your miner ?

**Comment by MJMODZZ** [comment]
> 

Remcos RAT is written in C++, but its not good. I asked you if you know a GOOD Rat in C++. And I Dont know about BitRAT, never used it

**Comment by MJMODZZ** [comment]
> > I asked you if you know a GOOD Rat in C++.
> 
> and i told you the good C++ rats. remcos may be a little detected but its really stable from what i've heard.

In fact, its detected (mine is completely undetected) and the functions are also not really good. No reason to spend money on it

**Comment by MJMODZZ** [comment]
> > In fact, its detected (mine is completely undetected) and the functions are also not really good. No reason to spend money on it
> 
> well of course its gonna be detected. i was talking about the stability, so technically the rat is GOOD just not good for detections. but yeah i guess your kinda right. but still my point was that c++ is better

Maybe better for game cheats, but not for rats

**Comment by shainodev** [comment]
> Maybe better for game cheats, but not for rats

are you talking about the client? or the server part of the rat since how is not a more low level language be better for rats?

**Comment by shainodev** [comment]
also what is your idle wait ?

**Comment by MJMODZZ** [comment]
Yo im confused, who is [shainodev](https://github.com/shainodev) and who is [varysuzuki](https://github.com/varysuzuki), [msfcon5ol3](https://github.com/msfcon5ol3) guys im confused, get some pfps

**Comment by shainodev** [comment]
> Yo im confused, who is [shainodev](https://github.com/shainodev) and who is [varysuzuki](https://github.com/varysuzuki), [msfcon5ol3](https://github.com/msfcon5ol3) guys im confused, get some pfps

Im shainodev and varysuzuki. One is a account on my phone and the other is a account on my pc

**Comment by MJMODZZ** [comment]
so we dont have to write using GitHub issues. This is not an issue anymore

**Comment by MJMODZZ** [comment]
I personally prefer discord

**Comment by varysuzuki** [comment]
> @shainodev @varysuzuki if you have discord, message me on [Discord](https://discord.gg/mjmodzz) (open a ticket and ask for MJMODZZ) or [Telegram](https://t.me/mjmods)

im not joining ur token logging discord server lmfao

**Comment by msfcon5ol3** [comment]
> Yo im confused, who is [shainodev](https://github.com/shainodev) and who is [varysuzuki](https://github.com/varysuzuki), [msfcon5ol3](https://github.com/msfcon5ol3) guys im confused, get some pfps

I just want a sample of your coinminer if you don't mind. What's your spreading method btw ?

**Comment by msfcon5ol3** [comment]
> > @shainodev @varysuzuki if you have discord, message me on [Discord](https://discord.gg/mjmodzz) (open a ticket and ask for MJMODZZ) or [Telegram](https://t.me/mjmods)
> 
> im not joining ur token logging discord server lmfao

![image](https://user-images.githubusercontent.com/122618951/213247781-9e793fe8-7c17-42c3-8789-c6214866f5ed.png)

Yea true , don't join just make the discussion here.

**Comment by MJMODZZ** [comment]
@msfcon5ol3 @varysuzuki well this is not a token logging discord, in fact this is just a restore discord. In Case if the server gets deleted, i can make a new one and restore everyone who has been verified.
If you want to read the Terms and Conditions, read this https://restorecord.com/terms

**Comment by MJMODZZ** [comment]
If you guys dont mind, i will close the ticket now

**Comment by MJMODZZ** [comment]
> > Yo im confused, who is [shainodev](https://github.com/shainodev) and who is [varysuzuki](https://github.com/varysuzuki), [msfcon5ol3](https://github.com/msfcon5ol3) guys im confused, get some pfps
> 
> I just want a sample of your coinminer if you don't mind. What's your spreading method btw ?

What do you mean by sample and what do you mean by spreading method?

**Comment by msfcon5ol3** [comment]
> > > Yo im confused, who is [shainodev](https://github.com/shainodev) and who is [varysuzuki](https://github.com/varysuzuki), [msfcon5ol3](https://github.com/msfcon5ol3) guys im confused, get some pfps
> > 
> > 
> > I just want a sample of your coinminer if you don't mind. What's your spreading method btw ?
> 
> What do you mean by sample and what do you mean by spreading method?

I want your malware to test in my VM. How do spread the miner that's what i'm asking.

**Comment by MJMODZZ** [comment]
> > > > Yo im confused, who is [shainodev](https://github.com/shainodev) and who is [varysuzuki](https://github.com/varysuzuki), [msfcon5ol3](https://github.com/msfcon5ol3) guys im confused, get some pfps
> > > 
> > > 
> > > I just want a sample of your coinminer if you don't mind. What's your spreading method btw ?
> > 
> > 
> > What do you mean by sample and what do you mean by spreading method?
> 
> I want your malware to test in my VM. How do you spread the miner that's what i'm asking.

private methods

**Comment by MJMODZZ** [comment]
> > > > > > Yo im confused, who is [shainodev](https://github.com/shainodev) and who is [varysuzuki](https://github.com/varysuzuki), [msfcon5ol3](https://github.com/msfcon5ol3) guys im confused, get some pfps
> > > > > 
> > > > > 
> > > > > I just want a sample of your coinminer if you don't mind. What's your spreading method btw ?
> > > > 
> > > > 
> > > > What do you mean by sample and what do you mean by spreading method?
> > > 
> > > 
> > > I want your malware to test in my VM. How do you spread the miner that's what i'm asking.
> > 
> > 
> > and my "malware" (Call it Remote Administration Tool) is private too, means only people who want to buy it will get it.
> 
> Where do you actually sell your malware if so be the case....?

If you pay me a fee, I will sell you the software + tutorial + the fud crypters and all that. Ofc i will also share my spreading methods and how to get 1K+ victimmys

**Comment by MJMODZZ** [comment]
> I have FUD crypters myself just need your miner to test something. You can send it to my [Email](mailto:strik3d4090@proton.me)
im not interested into your FUD crypter.

**Comment by msfcon5ol3** [comment]
> 

Why are you so hard to understand ? 

If you want to send the miner kindly reach me [here](mailto:strik3d4090@proton.me)


> > I have FUD crypters myself just need your miner to test something. You can send it to my [Email](mailto:strik3d4090@proton.me)
> > im not interested into your FUD crypter.

**Comment by MJMODZZ** [comment]
> > 
> 
> Why are you so hard to understand ?
> 
> If you want to send the miner kindly reach me [here](mailto:strik3d4090@proton.me)
> 
> > > I have FUD crypters myself just need your miner to test something. You can send it to my [Email](mailto:strik3d4090@proton.me)
> > > im not interested into your FUD crypter.

and I told you, the miner is not for sale

**Comment by MJMODZZ** [comment]
> > > > 
> > > 
> > > 
> > > Why are you so hard to understand ?
> > > If you want to send the miner kindly reach me [here](mailto:strik3d4090@proton.me)
> > > > > I have FUD crypters myself just need your miner to test something. You can send it to my [Email](mailto:strik3d4090@proton.me)
> > > > > im not interested into your FUD crypter.
> > 
> > 
> > and I told you, the miner is not for sale
> 
> Is any of your GitHub repositories infected with the miner ?

none of these

**Comment by msfcon5ol3** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Why are you so hard to understand ?
> > > > If you want to send the miner kindly reach me [here](mailto:strik3d4090@proton.me)
> > > > > > I have FUD crypters myself just need your miner to test something. You can send it to my [Email](mailto:strik3d4090@proton.me)
> > > > > > im not interested into your FUD crypter.
> > > 
> > > 
> > > and I told you, the miner is not for sale
> > 
> > 
> > Is any of your GitHub repositories infected with the miner ?
> 
> none of these

Ok

**Comment by MJMODZZ** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > Why are you so hard to understand ?
> > > > > If you want to send the miner kindly reach me [here](mailto:strik3d4090@proton.me)
> > > > > > > I have FUD crypters myself just need your miner to test something. You can send it to my [Email](mailto:strik3d4090@proton.me)
> > > > > > > im not interested into your FUD crypter.
> > > > 
> > > > 
> > > > and I told you, the miner is not for sale
> > > 
> > > 
> > > Is any of your GitHub repositories infected with the miner ?
> > 
> > 
> > none of these
> 
> Ok

Buy it, test it, use it
dont buy it, dont test it, dont use it

**Comment by msfcon5ol3** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > Why are you so hard to understand ?
> > > > > > If you want to send the miner kindly reach me [here](mailto:strik3d4090@proton.me)
> > > > > > > > I have FUD crypters myself just need your miner to test something. You can send it to my [Email](mailto:strik3d4090@proton.me)
> > > > > > > > im not interested into your FUD crypter.
> > > > > 
> > > > > 
> > > > > and I told you, the miner is not for sale
> > > > 
> > > > 
> > > > Is any of your GitHub repositories infected with the miner ?
> > > 
> > > 
> > > none of these
> > 
> > 
> > Ok
> 
> Buy it, test it, use it dont buy it, dont test it, dont use it

Ok Mr.Misunderstood

**Comment by MJMODZZ** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > Why are you so hard to understand ?
> > > > > > > If you want to send the miner kindly reach me [here](mailto:strik3d4090@proton.me)
> > > > > > > > > I have FUD crypters myself just need your miner to test something. You can send it to my [Email](mailto:strik3d4090@proton.me)
> > > > > > > > > im not interested into your FUD crypter.
> > > > > > 
> > > > > > 
> > > > > > and I told you, the miner is not for sale
> > > > > 
> > > > > 
> > > > > Is any of your GitHub repositories infected with the miner ?
> > > > 
> > > > 
> > > > none of these
> > > 
> > > 
> > > Ok
> > 
> > 
> > Buy it, test it, use it dont buy it, dont test it, dont use it
> 
> Ok Mr.Misunderstood

You are the Person who missunderstood. I fully understand what you mean but well you dont understand that you have to buy it

**Comment by MJMODZZ** [comment]
And by this, i will also close the ticket (too many retards) 
[Discord](https://discord.gg/mjmodzz) [Telegram](https://t.me/mjmods)
