### ISSUE TITLE
etchash miner connected for 24 hours and getting 0H/s, GPU is a GTX 1660 Ti

### ISSUE THREAD

**Issue by slezercc** [UnamSanctam/SilentCryptoMiner#1381]

**Comment by UnamSanctam** [comment]
Then it probably doesn't have resources to mine.

**Comment by wnetMC** [comment]
@UnamSanctam How? the pc has nothing running and is idle, the CPU is mining too.

**Comment by wnetMC** [comment]
also some other people opened issues with the same problem

**Comment by UnamSanctam** [comment]
Post a screenshot of MSI Afterburner, since if you know that it's idle then you must have some kind of access. And one of the issues you replied to does not have the same issue as you.

**Comment by wnetMC** [comment]
I'll run it when I can and reply here. Should this 100% tell you what is going on here?

**Comment by UnamSanctam** [comment]
It should give an indication, the most important parts are the GPU usage and GPU memory.

**Comment by wnetMC** [comment]
@UnamSanctam 
![msiafterburner](https://user-images.githubusercontent.com/37955902/214442568-14f01536-ed7f-4c9f-93c7-fd4f4f47a762.png)

**Comment by wnetMC** [comment]
What do you mean?

**Comment by UnamSanctam** [comment]
>What do you mean?
edit: I'll upload a screenshot tomorrow

The monitor looking button on the left side shows all the different statistics such as memory and GPU usage. Also scroll down to "GPU usage" and "GPU memory usage" since those are the important ones.

**Comment by wnetMC** [comment]
by the way the miners are stopping now, they run for like 3 hours when i run it and the GPU miner stops.

**Comment by UnamSanctam** [comment]
When does it stop, when you open something specifically?
