### ISSUE TITLE
Detections

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1382]
I noticed that. When I enable startup it goes from 7/26 to 5/26 how is that even begin to be logical??????

**Comment by UnamSanctam** [comment]
The whole installation process could be bypassing them.

**Comment by shainodev** [comment]
But antiscan scans only scantime not runtime?

**Comment by shainodev** [comment]
also what is weird is that when i dont enable startup i get a Malware.AI.463480657, C:\USERS\LITTL\APPDATA\ROAMING\GOOGLE\CHROME\UPDATER.EXE detection from malwarebytes? that doesnt make sense since thats the path for the STARTUP and when i disable startup then that detection comes? weird

**Comment by UnamSanctam** [comment]
>But antiscan scans only scantime not runtime? And does that technically mean that in the long run its gonna be more detected at runtime? (if i use startup)

For some antiviruses it could be scanning both. As long as the runtime scan does not share anything. Or the "Startup" could add something (like just more bytes) which makes them not detect it.

>also what is weird is that when i dont enable startup i get a Malware.AI.463480657, C:\USERS\LITTL\APPDATA\ROAMING\GOOGLE\CHROME\UPDATER.EXE detection from malwarebytes? that doesnt make sense since thats the path for the STARTUP and when i disable startup then that detection comes? weird

It's probably just remembering some bytes of the file which it uses to identify it, and in that case both the "Startup" and the one without it share those bytes.

**Comment by shainodev** [comment]
Ohhhh right. Also would there be a difference in detections if I would RegKeyOpen, etc to make the startup instead of using shellexecute? And would there be a difference if i would make the downloader work thru a TCP connection and then download and run on my command? or would that only work if i would make it run in memory or use process hollowing? since currently i just make it drop and i dont think it has a difference if i would manually make it drop since it still gets scanned i think

**Comment by UnamSanctam** [comment]
RegKeyOpen probably has less scantime detections, not sure though since I've never used it I think. Though if you have some other ShellExecute as well then it shouldn't matter. It wouldn't really make a difference if you download it like that, it will still scan all files anyways.

**Comment by shainodev** [comment]
> It wouldn't really make a difference if you download it like that, it will still scan all files anyways.

It will even scan stuff ran in memory or process hollowed?

**Comment by UnamSanctam** [comment]
Yes unless you use an undetected method for it, but the scans and detections are different for it. But if you were to drop it then it wouldn't matter.

**Comment by shainodev** [comment]
Is idle wait 2 minutes good?

**Comment by UnamSanctam** [comment]
>Isn't it more important for the CPU mining since they can see the CPU being used? Should I enable Stealth Targets for GPU mining but for ONLY games not task manager and such, and then maybe put only task manager and such in the CPU mining?

Which one is more important depends on if you think visible CPU usage or potential lag is more important. I'd say structuring the stealth targets like that (games for GPU, monitors for CPU) would be fine.

**Comment by varysuzuki** [comment]
Im also gonna ask is it the same in c# (is it gonna change the detections if i use Registry.LocalMachine.OpenSubKey instead of Process.Start and there encrypted strings, with a EncodedCommand to do the windows exclusion? since i put this in a c# dll the method i use needs to be 100% undetected.

**Comment by shainodev** [comment]
"Also, it's important to note that Windows Defender has a feature called "controlled folder access" which blocks potentially harmful apps from making changes to files in protected folders, so even if you add a folder to the exclusion list it could still be blocked by this feature." is this true

**Comment by shainodev** [comment]
?

**Comment by shainodev** [comment]
bump

**Comment by UnamSanctam** [comment]
>Im also gonna ask is it the same in c# (is it gonna change the detections if i use Registry.LocalMachine.OpenSubKey instead of Process.Start and there encrypted strings, with a EncodedCommand to do the windows exclusion? since i put this in a c# dll the method i use needs to be 100% undetected.

Probably not going to matter in C# (the adding itself is monitored), but not sure which calls are more detected if that's what you mean.

>"Also, it's important to note that Windows Defender has a feature called "controlled folder access" which blocks potentially harmful apps from making changes to files in protected folders, so even if you add a folder to the exclusion list it could still be blocked by this feature." is this true

If they have added the miners install folder (Program Files or AppData for example) then sure it might not be able to install, but not many use the feature because it's terrible (it blocks most legitimate programs as well).

**Comment by shainodev** [comment]
Oh okay. Also since you know c# and c++. Is there something that would make the connection between a c# server and c++ client not function?

**Comment by shainodev** [comment]
nvm stupid question. Thanks!
