### ISSUE TITLE
What Pool should i use?

### ISSUE THREAD

**Issue by Razzy52** [UnamSanctam/SilentCryptoMiner#1386]
I need a pool that does automactic payouts? Also what wallet should i use for monero, the one i've got is abit shite to say the least.
{I know this sounds abit cringy but idk what to do}

**Comment by UnamSanctam** [comment]
All pools do automatic payouts, the difference is usually just in the minimum payout threshold (that you can also normally change). For Monero you should probably use the Monero GUI Wallet (https://www.getmonero.org/downloads/#gui), or alternatively you could use Feather Wallet (https://featherwallet.org/)

**Comment by Razzy52** [comment]
Ah okay, I didn't know that sorry.
