### ISSUE TITLE
XMR and GPU mining

### ISSUE THREAD

**Issue by R3dacted00** [UnamSanctam/SilentCryptoMiner#1389]
Hello Unam, quick question this time (yeah, sorry it's still me, the ghostrider guy), since the majority of my workers are low-end PCs and can't mine etc at all I was thinking on compiling a new miner with GPU mining enabled on the xmr miner (or gr miner in this case).

The question is, If I'd do that, will the miner mine both with CPU and GPU on gr algo or only with GPU? I didn't understand if it switches the mining method from cpu to gpu or if it enables both to mine.

**Comment by UnamSanctam** [comment]
It would mine with both the CPU and GPU, but GPU mining isn't supported for the GhostRider algorithm. And GPU mining XMR is very unprofitable and uses a lot of resources. Both the GhostRider and RandomX (XMR) algorithms are designed to be mined with the CPU.

**Comment by R3dacted00** [comment]
I see, I'll try to get some use for the etc miner or disable it entirely then, thanks again Unam

**Comment by UnamSanctam** [comment]
No problem, good luck with the mining.
