### ISSUE TITLE
Rootkit configuration 

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/SilentCryptoMiner#1392]
Question about the configuration of rootkit in the resources of the source

As far as I understood the version of Bild of Ratkin from the source and the version of the Bild from the Baitkod repository after launch, it is reduced

  and as a result, at the same time it will not be possible to use two builds of routitics to conceal different processes

Can I get the source of the Rutkin Bild from miner resources to enable the ability to hide files for $ 77?

(I honestly don’t know how to correctly configure the Rutkin configuration for miner from the source of the buzzd rutkin)

Moreover, it would not be bad to hide the path and file of the most installed miner for $ 77

------------------------------------------- ------------------------------------------- ------------

Perhaps in the Bild of Rutkita from resources, instead of $ 77, there is another unique marker behind which is hidden processes of miner?

**Comment by UnamSanctam** [comment]
Sorry, not fully sure what you mean. The rootkit used is https://github.com/bytecode77/r77-rootkit, and the marker prefix has been changed from $77 to dialer in the current build. Which was mainly done to avoid a bug, in the future it will be something else.

If you want to build your own r77-rootkit build that can hide the miner then just make sure that you add `WmiPrvSE.exe` and `dialer.exe` into the `PROCESS_EXCLUSIONS` definition.

**Comment by anbu-squad** [comment]
Yes, thanks, now I realized that it was in the prefixes

If you run the miner with a rootkit, then the miner is not visible through the checker, however, if you run another build with rootkit, the latter updates the prefix and you can observe the work of the installed miner through the checker


However, the current rootkit is a very interesting implementation, I only now understood its purpose, after so much the use of the miner

And I had a need to hide other processes, such as the path and file of the rat, and I think it will be useful and everyone else

Regarding the prefix, it would be very good to add the opportunity to install the prefix on your own, then you can also hide the path with the miner file in 

-----------------------------------------------------------------------------------------------------------------------------------

So far, the easiest method is to hide other processes is to add to the name - current build

-----------------------------------------------------------------------------------------------------------------------------------

However, how to hide the path of the installed miner also then?
if the current of the build will be known after installing the miner

**Comment by anbu-squad** [comment]
--cinit-id = "current build" ??

where to see current build?

I'm confused

**Comment by UnamSanctam** [comment]
It's the randomized miner ID that gets generated on each build
https://github.com/UnamSanctam/SilentCryptoMiner/blob/1df8bae3c9b7f68cdf7b2602414d9884b7f5ca42/SilentCryptoMiner/Forms/Builder.cs#L206
And it also gets specified as the first argument in the injected miner
https://github.com/UnamSanctam/SilentCryptoMiner/blob/1df8bae3c9b7f68cdf7b2602414d9884b7f5ca42/SilentCryptoMiner/Forms/Builder.cs#L209

**Comment by anbu-squad** [comment]
Thank you

I tried to hide other processes

following the example: ffdfdklds_test.exe 

But according to the prefix - minerid, rootkit does not hide other processes

**Comment by UnamSanctam** [comment]
You mean that you added `ffdfdklds_test.exe` into `PROCESS_EXCLUSIONS`? Then it should hide it. If you want to hide the file with the built-in rootkit then you can name it dialer_test.exe

**Comment by anbu-squad** [comment]
No, I did not compile rootkit 

Since it is difficult for me to understand where to edit, without a clear example

I decided to try a simpler method

I just recognized the minerid in the check

And I tried to just add this minerid on the path and name of the file of another process

Now I will try to make a test
It turns out everything is much easier than I thought )

**Comment by anbu-squad** [comment]
**dialer_test.exe** - It works successfully ! =)

However, I have several questions left regarding the configuration

### PROCESS_EXCLUSIONS must be edited in the file **r77def.h** ?

Prefix should be edited?

Can I look at the source of rootkit in the resources of the miner?

(I thought in the source of rootkit, it is necessary to enter the variables of the miner, and the matter was limited to two files)

What is the role of files **WmiPrvSE.exe** and  **dialer.exe**?

**Comment by UnamSanctam** [comment]
Yes the exclusions should be edited in that file, the prefix should preferably be `dialer` to make sure to hide the miner process (in the current version since it does not use signatures). The current miners rootkit source only has those two changes, as well as also changing the builds to build everything as 64-bit (so that the miner can inject them) so you'd have to make that change as well.

>What is the role of files WmiPrvSE.exe and dialer.exe?

`WmiPrvSE.exe` is the WMI that the miner (though not in the latest version), checker and uninstaller uses to check if the miner is running. `dialer.exe` is what the process that the miner gets injected to when the rootkit is enabled.
