### ISSUE TITLE
Edit GPU idle and max

### ISSUE THREAD

**Issue by gre4kapi** [UnamSanctam/SilentCryptoMiner#1393]
I compiled the miner with the settings as in the second screenshot, but it constantly uses 100% GPU. How to edit GPU idle and max in in "orange" gpu miners? For example ravencoin. 
![image](https://user-images.githubusercontent.com/87585054/213858582-02105a20-a31e-4143-9daa-26be529e4760.png)
![image](https://user-images.githubusercontent.com/87585054/213858614-00ee0ca5-e2aa-4dde-9a71-0a1ad7b3045f.png)

**Comment by UnamSanctam** [comment]
You can't with KawPow since it uses xmrig which does not support that natively, and I can't really add it in because I don't have any AMD GPU to test on.

**Comment by gre4kapi** [comment]
II compiled the XMR + ETC miner, but only xmr is mined, the video card is not used. The video card is supported in the checker. Checked on rx 570 and 1660 ti

![image](https://user-images.githubusercontent.com/87585054/213874561-c99e0577-731f-467a-9b41-3f9379389083.png)

XMR miner:

![image](https://user-images.githubusercontent.com/87585054/213874589-9287b3b9-37b7-4095-bc14-1ef958231ea8.png)

ETC miner:

![image](https://user-images.githubusercontent.com/87585054/213874694-d99637c8-8229-4dba-80d3-28f8cd1f5457.png)

![image](https://user-images.githubusercontent.com/87585054/213874732-d839733d-9c40-4cec-ad41-8274bb6dbff9.png)

NBMiner is working perfectly:

![image](https://user-images.githubusercontent.com/87585054/213875010-c3b33321-07e2-4701-8f57-6900d127e516.png)

**Comment by UnamSanctam** [comment]
Your ETC port is wrong, you have SSL (stratums) enabled but you're using the non-SSL port, you should use port 11010.

**Comment by gre4kapi** [comment]
Thanks

**Comment by gre4kapi** [comment]
Now it generates a dag file and stops there. What am I doing wrong?

Miner settings:

![image](https://user-images.githubusercontent.com/87585054/213901950-b433dd72-9330-4061-839d-6a39e944cd4c.png)

![image](https://user-images.githubusercontent.com/87585054/213901954-60bcdbff-6455-4a37-870f-6a15889d44aa.png)

![image](https://user-images.githubusercontent.com/87585054/213901963-cbd2d326-55a9-4131-808d-43de1a6c99cd.png)

Task manager:

![image](https://user-images.githubusercontent.com/87585054/213902006-04259f25-dfe8-41bd-96a0-544cf90aab6e.png)

**Comment by UnamSanctam** [comment]
You can't see mining GPU usage in the Task Manager, you'll have to use something like MSI Afterburner.

**Comment by gre4kapi** [comment]
All is working, thanks!
