### ISSUE TITLE
mobile compatible? 

### ISSUE THREAD

**Issue by Necro-Crow** [UnamSanctam/SilentCryptoMiner#1395]
Hello Unam, first I would like to congratulate you for the excellent work. Would it be feasible in the near future for SilentCryptoMiner to be compatible with mobile? I still couldn't find something similar that is in .Apk.. could you enlighten my little empty head on the subject? I thank you for your attention.

**Comment by UnamSanctam** [comment]
Not really, I would have to remake it for Android so that's not really something I have planned.

**Comment by Necro-Crow** [comment]
So a hidden miner for Mobile would be impossible?

**Comment by Necro-Crow** [comment]
So a hidden miner for Mobile would be something impossible?
