### ISSUE TITLE
Couldn't able to figure out

### ISSUE THREAD

**Issue by harshitrajj** [UnamSanctam/SilentCryptoMiner#1398]
Hey I tested this in my own pc and my frnds pc it was working alot right connecting to pool and showing active status at webpanel with showing hash rate
When I install it in my university desktop running with run as  administration and even disable real time protection it is install properly but not showing any hash rate and on web panel it is showing Error on the status 
Any help will be appreciated 👍

**Comment by UnamSanctam** [comment]
The pool could be blocked on your university internet.

**Comment by harshitrajj** [comment]
yeah i also think same bro can u suggest any possible whitelist pool I can try if u have 1.
Or other way to bypass it rather then using VPN which gonna hard to install in each pc and probably detectable by ISP admins

**Comment by UnamSanctam** [comment]
You'd either have to try all the different pools and pool addresses for each oiik to find one they haven't blocked or if you're mining XMR or something similar then you could set up an xmrig-proxy on a VPS or on your own computer behind a port-forwarding VPN.

**Comment by harshitrajj** [comment]
Yes I am mining xmr can I explain little bit briefly port forwarding VPN using with miner how can i do that
Thank for response tho ☺️

**Comment by UnamSanctam** [comment]
I also responded in the other issue.
>Either you would have to get a VPS or a VPN with port forwarding, but both options usually costs money (since they're a service). Alternatively since you're using the web panel then you could try changing the mining pool from the "Configurations" until you find one that isn't blocked by your internet.
