### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by CheaterHubYT** [UnamSanctam/SilentCryptoMiner#1399]
I have been getting a lot of those lately what can I do to make it work?

![image](https://user-images.githubusercontent.com/123104983/214618207-59e54856-7831-415e-a422-ba5f819cd204.png)

**Comment by UnamSanctam** [comment]
Is it a 32-bit operating system?

**Comment by CheaterHubYT** [comment]
yes

**Comment by UnamSanctam** [comment]
Then yes that's why, 64-bit programs can't run on 32-bit systems. I'm not planning on making the miner 32-bit ever really at this point, if you want to know why then you could try compiling both xmrig and ethminer as 32-bit and then also injecting them to see why.

**Comment by CheaterHubYT** [comment]
ok Thanks but I also got someone who has the same problem but is on 64-bit os

**Comment by CheaterHubYT** [comment]
ok thanks a lot
