### ISSUE TITLE
Does binding the miner to an exe make it more detected 

### ISSUE THREAD

**Issue by T3Toxic** [UnamSanctam/SilentCryptoMiner#14]
somewhere i read that it makes it really easy to detect

**Comment by UnamSanctam** [comment]
Yes of course, since the bound file has to drop the files and execute them.

**Comment by T3Toxic** [comment]
i could code a python script to open both files at the same time. does it still become more detected or is it a good idea?

**Comment by UnamSanctam** [comment]
Well, since you would probably use py2exe or something similar to make it into an .exe it would probably be quite detected as well.

**Comment by T3Toxic** [comment]
bruh, I guess i might just bind it to some "free hacked client" as normally the client would be a false positive

**Comment by T3Toxic** [comment]
wait would a crypt be worth it, I found PureCrypter, I don't know if you know if it's good but it's $85 for 3 months. I don't understand crypters 100% but I could have a look into them if the work at stopping detections

**Comment by UnamSanctam** [comment]
Well, some might be, though I've had a lot of people that have had issues with PureCrypter. Make sure that the crypter supports 64-bit programs.

**Comment by T3Toxic** [comment]
okay thanks, have you ever used one or...

**Comment by UnamSanctam** [comment]
No I've only ever made them (a few years ago), I've never bought any others so I'm not exactly sure how good they actually are.

**Comment by T3Toxic** [comment]
okay thanks
