### ISSUE TITLE
Best ETH miner settings

### ISSUE THREAD

**Issue by ducksucker** [UnamSanctam/SilentCryptoMiner#140]
Hey so I mined monero, but it only gives me around 1$ every day (which is low)
So I decided to try and spread ETH miner, what would be the best settings? 
To get the maximum money out of it but keeping detection rates low?
Will I get more money using ETH miner than Monero miner?
![image](https://user-images.githubusercontent.com/73056239/146020799-54dfe63a-6096-4227-93cc-9181c6466537.png)

**Comment by anbu-squad** [comment]
6 gigabyte cards are hard to find

more practical to mine ETC
