### ISSUE TITLE
Run As System

### ISSUE THREAD

**Issue by ThomasTubato** [UnamSanctam/SilentCryptoMiner#1403]
can you add the 'Run as System' function in UnamBinder?

**Comment by UnamSanctam** [comment]
Well I'm not planning on adding installation at the moment I don't think, so that function wouldn't do much, or could technically be detrimental since if you run something as System then it can't have a GUI if bound programs.

**Comment by floof989763** [comment]
> can you add the 'Run as System' function in UnamBinder?

message me on tg @Samtg123
