### ISSUE TITLE
[Suggestion] Remote Configuration

### ISSUE THREAD

**Issue by ThomasTubato** [UnamSanctam/SilentCryptoMiner#1404]
You could change and instead of using .json use pastebin links, so you don't need webhosting but only need to create a pastebin account where you can change the various values (so each miner can have different settings by entering different links)

**Comment by UnamSanctam** [comment]
Yes you can already do that, that's what the "Remote Configuration" is for.
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration
