### ISSUE TITLE
windows update

### ISSUE THREAD

**Issue by floof989763** [UnamSanctam/SilentCryptoMiner#1406]
hello sir!
i used your silent crypto miner builder to build an exe and ran it in my pc for mining....  i used the disable windows update option........ now that i have used the uninstaller to uninstall the exe ....  but i cant update my windows .... please suggest me what to do sir

**Comment by shainodev** [comment]
It's permanent, you have to reset your PC probably

**Comment by DogusCzk** [comment]
> hello sir! i used your silent crypto miner builder to build an exe and ran it in my pc for mining.... i used the disable windows update option........ now that i have used the uninstaller to uninstall the exe .... but i cant update my windows .... please suggest me what to do sir

same thing happened to me and i guess i have no choice but to format it

**Comment by mrwick008** [comment]
@samogost sir can you contact me on telegram i need your help https://t.me/Samtg123
