### ISSUE TITLE
showing active but not hashing

### ISSUE THREAD

**Issue by harshitrajj** [UnamSanctam/SilentCryptoMiner#1407]
Its is showing active in webpanel but not hashing any idea why so

**Comment by UnamSanctam** [comment]
Usually it's if something is using all of the GPU.

**Comment by harshitrajj** [comment]
I am mining with cpu tho monero

**Comment by UnamSanctam** [comment]
Either not enough free RAM or not enough idle cores (or "Max CPU" is set too low for the amount of cores the computer has).
