### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by svox07** [UnamSanctam/SilentCryptoMiner#1408]
hi Unam Miner v2.6.1 not detected conhost.exe is good but conhost.exe is detected by Miner v3.1.0 why C++ Antivirus detects C# memory everything is fine

can you apply this I checked and it works well for memory
https://github.com/skahwah/encrypt

**Comment by UnamSanctam** [comment]
Version 2.6.1 should be detected, or it was detected before at least, it could have gone down over time if it's ML detections but they would increase if it became used more. The reason 3.1.0 is detected (and all other before it as well) is because many use it, it's the same for all other programs in existence. And the embedded bytes are already encrypted, that's not what the detections are from.

**Comment by svox07** [comment]
can you update so that we can make a choice in memory ourselves

**Comment by UnamSanctam** [comment]
You mean choose between C# and C++? Then no since that would be way to hard to maintain. Also means that I would have to necessarily add any function/option I add into both versions.

**Comment by svox07** [comment]
make separate functions of the build without embedding in memory pure exe without embedding in memory

**Comment by UnamSanctam** [comment]
Don't know what you mean, both 2.6.1 and 3.1.0 runs everything in memory. And most of the versions before that did the same as well. Not really sure what you're asking for then.

**Comment by svox07** [comment]
make a clean exe build without memory when I start the exe so that it does not inject into memory

**Comment by UnamSanctam** [comment]
You want it to drop the miners and then run those? That would be 100% detected by probably all antiviruses, what would be the point of doing so?

**Comment by svox07** [comment]
I want to embed into memory with my honey, so I need a clean exe so that there was a choice to embed into memory ourselves, make an update so that we can collect the miner without embedding into memory as a separate function

**Comment by UnamSanctam** [comment]
Are you talking about the upx compressed miners? You want an uncompressed one? Since otherwise what you're asking for doesn't make much sense.

**Comment by svox07** [comment]
I want to inject into memory with my own method

**Comment by UnamSanctam** [comment]
Then you can change that in the code, how else would it be done? Those files are in here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/Files.zip.

**Comment by svox07** [comment]
unam what resource do you make payload.bin for C++ can you send

**Comment by UnamSanctam** [comment]
>unam what resource do you make payload.bin for C++ can you send

I directly write the bytes of the program into the program https://github.com/UnamSanctam/SilentCryptoMiner/blob/1df8bae3c9b7f68cdf7b2602414d9884b7f5ca42/SilentCryptoMiner/Forms/Builder.cs#L271
And perform the XOR encryption before writing in the bytes
https://github.com/UnamSanctam/SilentCryptoMiner/blob/1df8bae3c9b7f68cdf7b2602414d9884b7f5ca42/SilentCryptoMiner/Classes/Codedom.cs#L247

>@UnamSanctam can you make self injection , don't start new process and inject as conhost , svchost etc , Self Inject inside same process , Thanks in Advance , i made the miner bypass Defender for 3.1 and 2.6 , and Currently Working on other EDR's , thanks alot for you work , top quality as always keep it up

Great to hear, but the original process is not conhost or svchost so self-injection would just inject it into the original [MINERNAME].exe that was started, and it might have to inject into two processes as well (for example if you have both an XMR and ETC miner) so it wouldn't work that well. It's already starting a parent spoofed child process under `explorer.exe` with how it is currently.
