### ISSUE TITLE
Can I use the config.json locations locally on the machine?

### ISSUE THREAD

**Issue by Omnividente** [UnamSanctam/SilentCryptoMiner#1409]
I have a bash script that creates a config file depending on the availability of pools, can I use a third-party config file forcibly?

**Comment by UnamSanctam** [comment]
Possibly if you add the `--config=` option into "Advanced Parameters", though I don't know if it will mess with anything.

**Comment by Omnividente** [comment]
the --url parameter modifies the url in the config file, if you replace the url after the launch, then everything works as it should. Without the --url parameter, during assembly, the miner does not work at all

**Comment by UnamSanctam** [comment]
Yes you would have to modify the builder so that it does not pass pool and such to the miner.

**Comment by Omnividente** [comment]
I really liked the implementation of your miner, is it possible to change your program for my tasks for money? if so, contact me in telegram @Omnividente
