### ISSUE TITLE
Project build warnings

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#141]
Good evening. Tell me when assembling your project in Visual Studio. I get warnings like this when building. I am attaching a screenshot. English translation errors from the screenshot - Missing XML comment for publicly visible type or member. In this case, the project undergoes compilation. Can you tell me these warnings are critical at the side?
![1](https://user-images.githubusercontent.com/36513967/146055177-9acc853b-0f1d-4d17-ba25-682c4d7af98e.jpg)

**Comment by UnamSanctam** [comment]
They are just documentation warnings and don't matter at all.

**Comment by masterjek** [comment]
Thank you
