### ISSUE TITLE
AntiVM

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1410]
Would it be detected to compare the computer username to known virustotal or antivirus computer usernames?

**Comment by UnamSanctam** [comment]
It mostly depends on how you do it, if you want to be certain then you can hash the usernames beforehand (compile the program with the usernames pre-hashed) and then when you get the username from the computer then you can hash that and compare that to the pre-hashed usernames.

**Comment by shainodev** [comment]
> It mostly depends on how you do it, if you want to be certain then you can hash the usernames beforehand (compile the program with the usernames pre-hashed) and then when you get the username from the computer then you can hash that and compare that to the pre-hashed usernames.

how do u hash something?
