### ISSUE TITLE
Not quiet an issue but more an idea

### ISSUE THREAD

**Issue by PeppyOnTop** [UnamSanctam/SilentCryptoMiner#1412]
Can you implement in the .exe that downloads the miner that it uses a powershell command to make it bypass windows defender.
I know it would need to start as an admin but it would bypass windows defender.

**Comment by UnamSanctam** [comment]
You mean inside the builder? Since it already exists in the miner itself.

**Comment by PeppyOnTop** [comment]
No I mean the file they start (needs to be run as administrator) executes 3 powershell commands (1.disables windows defender 2. downloads the miner 3. executes. the miner) this is a way to get it trough windows defender

**Comment by UnamSanctam** [comment]
You mean like the UnamDownloader? Or something different?

**Comment by mrwick008** [comment]
> Can you implement in the .exe that downloads the miner that it uses a powershell command to make it bypass windows defender. I know it would need to start as an admin but it would bypass windows defender.

https://t.me/Samtg123 please ping me on tg

**Comment by PeppyOnTop** [comment]
> You mean like the UnamDownloader? Or something different?

Oh I completely forgot about that. 
Thanks a lot <3
