### ISSUE TITLE
Antivirus skipping files

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1415]
![image](https://user-images.githubusercontent.com/77803435/216424287-c8e5ba93-d6aa-431d-a71d-1ad1f9568388.png)

Why cant i just make my file 2gb and in result it cant get virustotalled or scanned by antiviruses. What are the downsides of doing this?

**Comment by UnamSanctam** [comment]
You can though it's not too common except through game torrent spreading and similar ones because people would need to download 2GB.

**Comment by shainodev** [comment]
How is it easier to find it? and is there anything i could do about it. isnt it really smart to make a rootkit 2gb? then its never gonna get found, no? 

Also, should i put an AntiVirustotal to my fake app, my downloader (that the fake app drops) and the miner OR should i make the downloader 2gb, and the fake app just have antivirustotal or something

**Comment by UnamSanctam** [comment]
>How is it easier to find it? and is there anything i could do about it. isnt it really smart to make a rootkit 2gb? then its never gonna get found, no?

Since the file is so large then any tools like WinDirStat (if they're cleaning up space) would show it quite prominently. All antiviruses don't have a limit at 2GB either (Kaspersky I'm pretty sure does not have one).

>Also, should i put an AntiVirustotal to my fake app, my downloader (that the fake app drops) and the miner OR should i make the downloader 2gb, and the fake app just have antivirustotal or something

You'd need anti-VirusTotal on the fake app at least, but it can't really hurt on all of them unless your anti-virustotal is triggering on too many legitimate computers.

>Also, which would be better pumping the files with 0 bytes at the end, would antiviruses remove that? or should i embed a game into the resources or something?

Pumping that way can get it detected as malware, so it could be better to embed something.

**Comment by shainodev** [comment]
> You'd need anti-VirusTotal on the fake app at least, but it can't really hurt on all of them unless your anti-virustotal is triggering on too many legitimate computers.

i dont have to worry about getting detected?

my code uses a std::string function that uses Wincrypt.h and SHA512 to hash something. then it has a vector full of hashed and then xorstr-d names of known virustotal pc usernames, and then it gets the current pc username and hashes it and if it isnt then it jumps to "no:" using "goto no;", skipping the malware downloader part of it. is that gonna be detected?

**Comment by shainodev** [comment]
is the ntdll.dll hooking bypass method that smokeloader uses detected? if you dont know what it does, i think it was called usermode hooking bypass or something (i guess its like how you do the delay execution stuff), smokeloader copies the C:\Windows\System32\ntdll.dll to temp and then from the temp file it getprocaddresses it. would it be detected to do? for my case i wanna make it do ShellExecute so it wont be detected

**Comment by UnamSanctam** [comment]
>i dont have to worry about getting detected?
my code uses a std::string function that uses Wincrypt.h and SHA512 to hash something. then it has a vector full of hashed and then xorstr-d names of known virustotal pc usernames, and then it gets the current pc username and hashes it and if it isnt then it jumps to "no:" using "goto no;", skipping the malware downloader part of it. is that gonna be detected?

The comparison itself shouldn't get detected.

>is the ntdll.dll hooking bypass method that smokeloader uses detected? if you dont know what it does, i think it was called usermode hooking bypass or something (i guess its like how you do the delay execution stuff), smokeloader copies the C:\Windows\System32\ntdll.dll to temp and then from the temp file it getprocaddresses it. would it be detected to do? for my case i wanna make it do ShellExecute so it wont be detected

Yes that way is usually detected.

**Comment by shainodev** [comment]
so should i add a antivirustotal to only my fake app? or to the downloader aswell, and is it a good idea to make the downloader check if the file path is the one that i chose so (c:/app.exe) and then i hashed it. so is that a good idea or no?
