### ISSUE TITLE
Invisible {COMPUTERNAME}

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1416]
![Screenshot_20230203_091400](https://user-images.githubusercontent.com/77803435/216535901-a56f5917-a54a-4067-a9c6-20450d295734.jpg)
Should this happen?

**Comment by UnamSanctam** [comment]
Means that the computer name is not alphanumeric, could be in Cyrillic or something similar. It removes all non-alphanumeric since not all pools support it.
