### ISSUE TITLE
hvnc

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1418]
have u considered making unamhvnc?

**Comment by sa6ta6ni6c** [comment]
stop making new useless issues

**Comment by shainodev** [comment]
> stop making new useless issues

why would i stack up all questions in one issue? maybe when i make multiple and some people see it, they might have the same question and this will help them

**Comment by shainodev** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
Not at the moment no.
