### ISSUE TITLE
nanopool issue

### ISSUE THREAD

**Issue by harshitrajj** [UnamSanctam/SilentCryptoMiner#1422]
i was try to hash on nanopool on pool it was not showing any worker active  or hashrate but on web panel it was showing that its hashing and 1 worker connected any help regarding this?

**Comment by UnamSanctam** [comment]
How long have you been mining? You need to find a share first for the pool to show your miner https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining.

**Comment by mrwick008** [comment]
> i was try to hash on nanopool on pool it was not showing any worker active or hashrate but on web panel it was showing that its hashing and 1 worker connected any help regarding this?

Ping me bro on tg https://t.me/Samtg123
