### ISSUE TITLE
I want to change my panel's hosting, and therefore need to change the endpoint url

### ISSUE THREAD

**Issue by wnetMC** [UnamSanctam/SilentCryptoMiner#1427]
can i simply change the api endpoint url on my xmr and etc remote configs??

**Comment by UnamSanctam** [comment]
Yes you can do that, the `"api-endpoint": "API Endpoint URL"` option will change the web panel URL.

**Comment by wnetMC** [comment]
> Yes you can do that, the `"api-endpoint": "API Endpoint URL"` option will change the web panel URL.

Do i have to copy over the db folder to my new hosting?

**Comment by UnamSanctam** [comment]
If you want the current data you have then yes, if not then panel will be empty and the miners will be re-added the next time they connect.

**Comment by wnetMC** [comment]
> If you want the current data you have then yes, if not then panel will be empty and the miners will be re-added the next time they connect.

can i change the endpoint url from the panel with the config tool?

**Comment by UnamSanctam** [comment]
Yes but the settings only last until the next miner restart both for practicality and security reasons. So it would be best to change it through the "Remote Configuration" as well.
