### ISSUE TITLE
Help me  urgently

### ISSUE THREAD

**Issue by Yasuosaa** [UnamSanctam/SilentCryptoMiner#1429]
Hi, I'll tell you, I've been trying on my pc with different configurations but I forgot to uninstall one and tried to close the miner from task manager, delete it from appdata, delete it with the antivirus and nothing, when I delete a file called update.exe It restores itself and the miner is executed again, please help me.
I inject the miner in Windows explorer and I don't know if doing that also affects my Windows explorer :(
@UnamSanctam

**Comment by wnetMC** [comment]
I think you need to delete the registry key somewhere, check the wiki, i think its all the way down in the wiki.

**Comment by Yasuosaa** [comment]
I inject the miner in Windows explorer and I don't know if doing that also affects my Windows explorer :(

**Comment by shainodev** [comment]
if u didnt enable Protect Process you could just use process hacker to kill the watchdog and miner and then remove it and its startup keys (from registry or task scheduler) if u did enable protect process you could boot into safe mode and remove the file and startup keys from there

**Comment by UnamSanctam** [comment]
As the others have said, you can uninstall it manually https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner. The easiest way would be to remove the startup entry from either the Task Scheduler or the Registry, first remove that entry and then instantly restart your computer.

**Comment by mrwick008** [comment]
> if u didnt enable Protect Process you could just use process hacker to kill the watchdog and miner and then remove it and its startup keys (from registry or task scheduler) if u did enable protect process you could boot into safe mode and remove the file and startup keys from there

Sir i am in need of help can we talk on telegram https://t.me/Samtg123
