### ISSUE TITLE
wallet adress

### ISSUE THREAD

**Issue by floof989763** [UnamSanctam/SilentCryptoMiner#1430]
hello unam sir! sir i have been mining through your miner for  along time..  and i was using "mymonero" to get my monero's wallet address and it worked properly and now i want to mine ethirium classic and i pasted my wallet adress form binance and it is not working .... so sir please guide me from where can i get my wallet to mine ethirium classic

**Comment by UnamSanctam** [comment]
Almost all multi-wallets support ETC usually, it really depends on what wallet you want to use. The Binance wallet supports ETC as well.

**Comment by floof989763** [comment]
sir but i added my monero wallet by binance and ran the exe in my pc and it did not work at all.. and did not reflect at nanopool.org 
on the other hand when i use the walllet adress of mymonero it reflects

**Comment by floof989763** [comment]
well it showed me active on the webpanel with the binance panel ... but nothing reflected on nanopool

**Comment by UnamSanctam** [comment]
As long as the Monero address is formatted correct it should work, but for ETC you can just use any other multi-wallet that exists such as MetaMask, Exodus, ZelCore, Trust Wallet, Atomic Wallet or tons of others.

**Comment by floof989763** [comment]
and sir which is the best nanopool you suggest?

**Comment by floof989763** [comment]
i mean mining pool

**Comment by UnamSanctam** [comment]
Probably 2miners or nanopool, though MoneroOcean works as well (but I do know that they can ban). You can find all pools here: https://miningpoolstats.stream/ethereumclassic.

**Comment by floof989763** [comment]
sir i am having trouble creating a miner because of my pc which has low power ..... can you suggest someone who can build a miner for me 
or it would be an honour for me if you build a miner for me sir i would be really greatful

**Comment by floof989763** [comment]
https://t.me/peterp1231
here is my telegram account or tell me any  social platform on which you are availabe on i will be really grate ful sir 
i have been working on this since s6 years and aced complete loss. please help me sir

**Comment by floof989763** [comment]
anyone who  could help me through this matter 
please ping me

**Comment by UnamSanctam** [comment]
Building a miner shouldn't really require much, I can build one though I don't really know what settings you want. Currently I don't have access to my Telegram (number seems to be blocked or something as well so I haven't been able to get it back) and my Discord is banned, so I don't really have many ways of contact. My main one I use "temporarily" is unams@protonmail.com.
