### ISSUE TITLE
GPU mining in xmr

### ISSUE THREAD

**Issue by floof989763** [UnamSanctam/SilentCryptoMiner#1431]
sir i will close this issue as soon as i get my answer ... sir i have been using your SilentCryptoMiner for mining monero and the files dont compile when i turn on the gpu mining in xmr. so sir will it help mining any faster if i turn on the gpu mining in xmr and spread

**Comment by UnamSanctam** [comment]
Yes a bit, but it will use a lot of the GPU, Monero is designed to be bad for anything other than CPU mining so mining it with a GPU is not very profitable.
