### ISSUE TITLE
Is Mining is not profitable anymore?

### ISSUE THREAD

**Issue by mrwick008** [UnamSanctam/SilentCryptoMiner#1433]
@UnamSanctam sir ..i have been trying from 7 Months to earn some money from mining i haven't earn 1$ yet i am just investing till now...some people says that mining is not profitable anymore...say i spread my miner exe into 100 pcs but it runs only in 30 pcs and i crypted that file also but it gots detected in 2 days ..sir how can i make my file FUD for a long time i use private crypter also but file got detected in 2 3 days only this is big issue sir i am not spreading miner myself i am purchasing installs for it i invested lot of money 🤷 but i am still at 0......my telegram id is.   https://t.me/Samtg123

**Comment by shainodev** [comment]
listen. dont spread the miner directly. use a loader, and even with that dont spread it directly. make a fake app that is binded with your loader that will go into some other directly and start on startup. and then from the loader make an autotask to run your miner in memory. and it all depends on what you mine, what settings you have and so on. this isnt easy its all about being creative

**Comment by mrwick008** [comment]
> listen. dont spread the miner directly. use a loader, and even with that dont spread it directly. make a fake app that is binded with your loader that will go into some other directly and start on startup. and then from the loader make an autotask to run your miner in memory. and it all depends on what you mine, what settings you have and so on. this isnt easy its all about being creative

Sir can i have your telegram id or you can message me on https://t.me/Samtg123 its very urgent please i request you to contact me personally

**Comment by pouche123** [comment]
Can you please send your telegram again, It doesn't work for me and I'd like to ask you a few questions if you don't mind.
