### ISSUE TITLE
Add back Overwrite old miners option

### ISSUE THREAD

**Issue by MJMODZZ** [UnamSanctam/SilentCryptoMiner#1434]
title says everything, really important because of a misstake i did

**Comment by UnamSanctam** [comment]
You don't want it to overwrite old miners?

**Comment by MJMODZZ** [comment]
> 

i want to overwrite a old miner

**Comment by MJMODZZ** [comment]
you did had this function in the past, i didnt

**Comment by UnamSanctam** [comment]
Yes it always overwrites old miners by default, the option was just for disabling that since some didn't want it to overwrite old miners.

**Comment by MJMODZZ** [comment]
ok so this means when i update the miner it will overwrite the old one?

**Comment by UnamSanctam** [comment]
Yes it will overwrite the old file by default.
