### ISSUE TITLE
Windows Service

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1435]
why not use windows services to start the miner instead of task scheduler? i bet its waaaay more harder to find no?

**Comment by shainodev** [comment]
and just a question, will adding a firewall rule to allow the miner, gonna change anything?

**Comment by UnamSanctam** [comment]
>why not use windows services to start the miner instead of task scheduler? i bet its waaaay more harder to find no?

Not really, and there are quite a few downsides of making it a service instead.

>and just a question, will adding a firewall rule to allow the miner, gonna change anything?

Only on some computers where the firewall has been set extremely strictly.

**Comment by shainodev** [comment]
> Not really

how? i have never seen anyone look at services

> and there are quite a few downsides of making it a service instead.

like?

**Comment by UnamSanctam** [comment]
>how? i have never seen anyone look at services

Not that many look at the Task Scheduler either.

>like?

Some of the downsides would be more antivirus scrutiny since services are usually monitored more strictly, having to structure the miner into a service program (services aren't just normal programs) and having to support both the Registry (User), Task Scheduler (Administrator) and Service (System) since services can only run as System (without knowing any user passwords), unless I were to remove the "Run as System" option and instead always force it to run as System. Making sure that the miner is installed correctly also becomes a bit harder, since in the current one it just reruns the command but with services it becomes a bit harder.

I have thought about making it into a service before when I added support for running it as System (since Windows APIs like idle time and such doesn't work with that) but decided against it since it introduces more potential points of failure (which are also harder to identify).

**Comment by shainodev** [comment]
what about programmatically adding the scheduled task and regkey, or that makes it detected?

**Comment by UnamSanctam** [comment]
It's possible to do, but since your using the Registry and Task Scheduler API calls then antiviruses can clearly see them both during scantime and runtime, so it really depends on whether antiviruses consider adding things into the Registry or Task Scheduler as suspicious. The reason I chose commands are because I chose to focus on scantime detections because then at least for Windows Defender the exclusions will make it ignore any runtime detections. I haven't tested it all in C++ though since it's quite complicated to do (the Task Scheduler, the Registry is quite easy).

**Comment by shainodev** [comment]
> I haven't tested it all in C++ though since it's quite complicated to do (the Task Scheduler, the Registry is quite easy).

Yeah I agree with that creating a scheduled task in C++ programmatically made me go insane and at the end I couldn't even make it work

> The reason I chose commands are because I chose to focus on scantime detections

so commands are more detected at runtime? what should I do what would be better? or atleast instead of programmatically or using powershell, for task scheduler just open schtasks.exe instead or for registry open reg.exe?

**Comment by shainodev** [comment]
would it be better to add exclusions with regkeys tho and not powershell?

**Comment by UnamSanctam** [comment]
>so commands are more detected at runtime? what should I do what would be better? or atleast instead of programmatically or using powershell, for task scheduler just open schtasks.exe instead or for registry open reg.exe?

Well everything you do gets monitored during runtime, there isn't really a best solution. But running it throughy cmd instead of powershell is often better since then there's no AMSI.

>would it be better to add exclusions with regkeys tho and not powershell? cause i think there are alot of yara rules for powershell commands containing base64 or something

I have added registry writing into the next version using NtCreateKey and NtSetValueKey and am testing some things but I don't believe any users have access to the exclusion registry paths (only WinDefend from what I can see).

**Comment by shainodev** [comment]
> Well everything you do gets monitored during runtime, and commands are as obvious as it can be, there isn't really a best solution but many antiviruses don't really care about commands. And running it through cmd instead of powershell when possible is often better since then there's no AMSI.

what about directly and not cmd?

**Comment by UnamSanctam** [comment]
>what about directly and not cmd?

Depends on how you do it, if you use NtCreateKey and NtSetValueKey then I'd say running it directly would be less detected. If you're using the normal Windows API calls then it doesn't really make much difference except that using cmd might have have less scantime detections.

**Comment by shainodev** [comment]
> Depends on how you do it, if you use NtCreateKey and NtSetValueKey then I'd say running it directly would be less detected. If you're using the normal Windows API calls then it doesn't really make much difference except that using cmd might have have less scantime detections.

do you mean using NtCreateKey as in i GetProcAddress from the ntdll or do you mean that i need to usermode hook or something?

**Comment by shainodev** [comment]
i meant directly as in ShellExecute("schtasks.exe", "/ru System etcetc") and not ShellExecute("powershell", "schtasks create etcetc"), so did u mean that doing it programmatically (ntcreatekey) is less detected?

**Comment by UnamSanctam** [comment]
>do you mean using NtCreateKey as in i GetProcAddress from the ntdll or do you mean that i need to usermode hook or something?

Doing it with direct syscalls via something like SysWhispers would be optimal.

>i meant directly as in ShellExecute("schtasks.exe", "/ru System etcetc") and not ShellExecute("powershell", "schtasks create etcetc"), so did u mean that doing it programmatically (ntcreatekey) is less detected?

NtCreateKey would be less detected, but I don't think you can edit the Task Scheduler directly through the registry since I believe Windows keeps hashes of the Tasks somewhere to make sure none get modified.

**Comment by shainodev** [comment]
> Doing it with direct syscalls via something like SysWhispers would be optimal.

is syswhispers not detected? and is it possible to do that without having to have another .exe compile something like you have right now? also is it as detected as RegOpenKeyEx if i would for example use this

`OBJECT_ATTRIBUTES objAttr;
UNICODE_STRING keyName;
HANDLE hKey;
NTSTATUS status;

RtlInitUnicodeString(&keyName, L"NewKey");
InitializeObjectAttributes(&objAttr, &keyName, OBJ_CASE_INSENSITIVE | OBJ_KERNEL_HANDLE, hKeyParent, NULL);

status = NtCreateKey(&hKey, KEY_ALL_ACCESS, &objAttr, 0, NULL, 0, NULL);
if (!NT_SUCCESS(status)) {
    // handle error
}`

?
and final question, how does powershell have access to making exclusions but ntcreatekey not?

**Comment by shainodev** [comment]
![image](https://user-images.githubusercontent.com/77803435/219100358-f723b024-3697-4444-b119-8e613d07feb8.png)
and how do i do this? theres no place to edit prefix or something

**Comment by UnamSanctam** [comment]
>is syswhispers not detected?

It's not really detected in itself no.

>and is it possible to do that without having to have another .exe compile something like you have right now? 

You mean the SysWhispers2.exe? That's just the SysWishpers2 python script turned into an .exe since otherwise I would have to require each user to install Python.

>also is it as detected as RegOpenKeyEx if i would for example use this

Doing that would be a lot less detected, though I prefer not using APIs such as RtlInitUnicodeString.

>and how do i do this? theres no place to edit prefix or something

He means just adding the `dialer` prefix to the path name and exe name in the "Startup" tab, that would make the rootkit hide the miner file as well. The reason the miner doesn't do that automatically is because there was an issue with doing that a long time ago and I haven't retested it since then (sadly time is limited).

**Comment by shainodev** [comment]
> You mean the SysWhispers2.exe? That's just the SysWishpers2 python script turned into an .exe since otherwise I would have to require each user to install Python.

Yeah but it still uses another executable/script to add the includes, can i do it without?

> He means just adding the `dialer` prefix to the path name and exe name in the "Startup" tab, that would make the rootkit hide the miner file as well. The reason the miner doesn't do that automatically is because there was an issue with doing that a long time ago and I haven't retested it since then (sadly time is limited).

should i add it to my downloader's startup then too? what if the rootkit doesnt work on one's pc and then some suspicious dialer_GoogleUpdateCQ is on their startup

**Comment by UnamSanctam** [comment]
>Yeah but it still uses another executable/script to add the includes, can i do it without?

You can just use the generated files directly sure, the difference would be that it won't generate new seeds and hashes for each build.

>should i add it to my downloader's startup then too? what if the rootkit doesnt work on one's pc and then some suspicious dialer_GoogleUpdateCQ is on their startup

You could, the string at the beginning is also one of the reasons I didn't do so in the miner. But you could add the paths to hide inside the registry and the rootkit will hide those https://docs.bytecode77.com/r77-rootkit/Technical%20Documentation.pdf.

**Comment by shainodev** [comment]
> You could, the string at the beginning is also one of the reasons I didn't do so in the miner. But you could add the paths to hide inside the registry and the rootkit will hide those https://docs.bytecode77.com/r77-rootkit/Technical%20Documentation.pdf.

wouldn't that be detected? and why cant you just release the source? it isnt hard to compile at all like ethminer is

**Comment by UnamSanctam** [comment]
>wouldn't that be detected? and why cant you just release the source? it isnt hard to compile at all like ethminer is

The rootkit creates the registry paths anyways I think, the rootkit isn't exactly undetected. The source is here: https://github.com/bytecode77/r77-rootkit. The only change I've made in the newest version of it (the older rootkit version didn't have all the features so had to make some myself) is changing the PROCESS_EXCLUSION definition to `{ L"MSBuild.exe", L"WmiPrvSE.exe", L"dialer.exe" }` and then changing the HIDE_PREFIX to `L"dialer"`.

**Comment by shainodev** [comment]
how could i modify it to hide my file and startup

**Comment by UnamSanctam** [comment]
Download it and modify it, I don't have the source open, I just wrote the changes from memory. You could probably hardcode it to hide some path if you want that. Otherwise just set the prefix to something you want and then use that in the file and startup.

**Comment by shainodev** [comment]
> Download it and modify it, I don't have the source open, I just wrote the changes from memory. You could probably hardcode it to hide some path if you want that. Otherwise just set the prefix to something you want and then use that in the file and startup.

yeah but then i have to make it hide conhost probably and i dont wanna do that, could you tell me in which folder (project) atleast its supposed to be modded in?

**Comment by shainodev** [comment]
I read the documentation and if im not mistaken, it says if I hide (the downloader thats on startup for me for example) then it doesnt start on startup cause windows cant find it since its hidden by the rootkit. So what do I do? do I only hide the startup of the downloader?

**Comment by shainodev** [comment]
also will mining with the xmr.2miners.com direct ip rather than using the DNS change something?

**Comment by UnamSanctam** [comment]
>I read the documentation and if im not mistaken, it says if I hide (the downloader thats on startup for me for example) then it doesnt start on startup cause windows cant find it since its hidden by the rootkit. So what do I do? do I only hide the startup of the downloader?

I think Windows might still start it, I'm not sure. Otherwise you can add the startup into the rootkit registry and it will handle that instead.

>also will mining with the xmr.2miners.com direct ip rather than using the DNS change something?

Probably won't matter but you can try it. In case they only blocked the domain.

**Comment by shainodev** [comment]
> Probably won't matter but you can try it. In case they only blocked the domain.

does mining even work if i dont use the dns?

**Comment by UnamSanctam** [comment]
>does mining even work if i dont use the dns? and could their ip change?

Yes it would work, and yes it could change.

**Comment by shainodev** [comment]
> NtCreateKey would be less detected, but I don't think you can edit the Task Scheduler directly through the registry since I believe Windows keeps hashes of the Tasks somewhere to make sure none get modified.

just another question. Which one should i use then for startup? ShellExecute("powershell", "schtasks /create") or ShellExecute("schtasks", "/create")?
