### ISSUE TITLE
rootkit

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1438]
Does it still work? should i use it? and which windows versions they work on FORSURE (ill add a check that checks if the victims OS isnt unstable for the rootkit)

**Comment by shainodev** [comment]
is it a good idea to use?

**Comment by shainodev** [comment]
how do i use it without startup

**Comment by UnamSanctam** [comment]
>is it a good idea to use?

Maybe, I would recommend testing it on a VM first since some has said that it doesn't work.

>how do i use it without startup

It's set to only install the rootkit during "Startup" so that it doesn't have to install on every run. Though you can change that in the code if you want.

**Comment by shainodev** [comment]
> It's set to only install the rootkit during "Startup" so that it doesn't have to install on every run. Though you can change that in the code if you want.

the Miner rootkit doesnt use the fileless startup?

**Comment by UnamSanctam** [comment]
>the Miner rootkit doesnt use the fileless startup?

It does, but you still have to install it.

**Comment by shainodev** [comment]
why is it like that tho? wouldnt just running the rootkit with the miner instead of the rootkit having its own startup be more stealthy and less detected?

**Comment by shainodev** [comment]
wait what type of stability issues am i risking by using the rootkit?

**Comment by UnamSanctam** [comment]
>wait what type of stability issues am i risking by using the rootkit?

Not really sure, the reports aren't very detailed so I only know that some reported problems, not really what the actual problems are. The only one I really know is that the rootkit might not apply on some startups which isn't really that bad (it doesn't influence stability). One person reported lower rx/0 hashrates but that only seems to happen on that one computer (and that could have been in the older version).

**Comment by shainodev** [comment]
> One person reported lower rx/0 hashrates but that only seems to happen on that one computer (and that could have been in the older version).

how could someone even report that cause it may be cause of alot of different reasons? but okay thanks!

**Comment by shainodev** [comment]
oneeeeeeeeeeeeee more question about the rootkit. If a person opens the miner 2 times does the rootkit get opened 2 times aswell? since it has no mutex check when injecting

**Comment by UnamSanctam** [comment]
It runs the install twice yes, normally that doesn't really matter since it only runs it during the startup install.

**Comment by shainodev** [comment]
Oh okay, also is there any way to hide powershell? since i thought of making my fake app, inject the rootkit first and then it injects the miner into memory and the miner read bytes of itself somehow from memory and then it drops itself, i also thought that at that point i could just include the miner inside the rootkit but then comes problems like it not working or it gettign detected so i still want the miner to stay, but the problem is that once rootkit is injected then they cant see me dropping it, but they can still see the powershell getting opened and then get sussed out, should i make it hide all powershell processes or what should i do

**Comment by UnamSanctam** [comment]
>Oh okay, also is there any way to hide powershell? since i thought of making my fake app, inject the rootkit first and then it injects the miner into memory and the miner read bytes of itself somehow from memory and then it drops itself, i also thought that at that point i could just include the miner inside the rootkit but then comes problems like it not working or it gettign detected so i still want the miner to stay, but the problem is that once rootkit is injected then they cant see me dropping it, but they can still see the powershell getting opened and then get sussed out, should i make it hide all powershell processes or what should i do

I haven't tested hiding powershell before with the rootkit so there's a chance that things might stop working. You'd have to test it to see if something stops working. But the powershell when the rootkit first installs will still be visible of course.
