### ISSUE TITLE
Project Suggestion

### ISSUE THREAD

**Issue by slezerr** [UnamSanctam/SilentCryptoMiner#1444]
I found a windows botnet that has a very similar builder and panel to this. ([https://github.com/AndroVirus/BlackNET](https://github.com/AndroVirus/BlackNET)). The problem with that project is that alot of features are broken and it would be really nice to get this thing working.

**Comment by DogusCzk** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
Well I'm not really going fix someone's quite large codebase. Especially since I'd have to remake most of it due to how I work.
