### ISSUE TITLE
Does this mean the miner is running?

### ISSUE THREAD

**Issue by StroobWasTaken** [UnamSanctam/SilentCryptoMiner#1446]
Hello,
I used the checker program and found that my gpu was listed
even though I did not run the miner
does this mean that the miner is running on my pc? I hope not because its already slow
and the miner would make it even slower, ![image](https://user-images.githubusercontent.com/100789011/219714487-ba984cd2-c226-4a5b-b029-888759d46b9a.png)

**Comment by UnamSanctam** [comment]
No it's not running, the `Compatible GPU found: True` just means that a GPU was found so it will try GPU mining when run.

**Comment by StroobWasTaken** [comment]
Ok thanks
If it is listed in miners does it mean its running? or how do I tell if its running

**Comment by StroobWasTaken** [comment]
And does it list miners from other PC or only mine

**Comment by UnamSanctam** [comment]
Yes if they are running then they will be listed under the "Miners:" title. It only shows the ones running on your computer.

Just hypothetically, to be able to show other PCs in it then the checker would have to start a server on your computer and then all the other PCs would have to connect to your server via your IP.
