### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1449]
im having trouble modifying the code. like i added a c# stealer that is themida-d (so its c++ basically) and i inject it to dialer.exe and it works. the problem is that its the only thing that works, the miner just doesnt want to work anymore but it seems to reach the inject part of the miner, but idk how to get the exception or error code that it might recieve?

**Comment by UnamSanctam** [comment]
What exactly have to modified?

**Comment by shainodev** [comment]
nvm i found the issue. the problem was that watchdog was not built, but still included, and that somehow made ONLY the miners silently not work but everything else work (i used messageboxes to track the flow of the program) so that was weird probably the app trying to inject null bytes disabled the process hollowing. but the "Debug" feature like there was in the C# version would be nice, also maybe try catches since there seems to not be any but idk if they are needed in c++

**Comment by shainodev** [comment]
also what will happen if i make it inject the rootkit but i dont have admin on the app

**Comment by shainodev** [comment]
and how do i test the rootkit on my own pc (can i use the normal r77 testconsole on your modified version?)

**Comment by UnamSanctam** [comment]
>also what will happen if i make it inject the rootkit but i dont have admin on the app

Probably won't be able to run.

>and how do i test the rootkit on my own pc (can i use the normal r77 testconsole on your modified version?)

I usually just test it by making a file called dialer, if it gets hidden then it's running. But I think the r77 Test Console would work, since it's it's using the special PE header bytes.

**Comment by shainodev** [comment]
> Probably won't be able to run.

the miner at all or the rootkit only?

> I usually just test it by making a file called dialer, if it gets hidden then it's running. But I think the r77 Test Console would work, since it's it's using the special PE header bytes.

and how do i get rid of it?

**Comment by UnamSanctam** [comment]
>the miner at all or the rootkit only?

The rootkit.

>and how do i get rid of it?

Run the rootkit uninstaller.

**Comment by shainodev** [comment]
oh, it seems that when i have blocked dialer.exe from internet access, eth miner runs, but the xmr miner doesnt. how is that logical, since when i block it when its running then nothing happens

**Comment by shainodev** [comment]
im guessing that its xmr miner that is not running cause of the longer commandline btw so im not sure which one it really is, but should this happen?

**Comment by UnamSanctam** [comment]
No, but I'm not sure of everything that you've changed.

**Comment by shainodev** [comment]
I've removed the checkbox checks and made functions i need hardcoded
![image](https://user-images.githubusercontent.com/77803435/219865565-3b861ea7-5895-4923-9224-236733813df5.png)
![image](https://user-images.githubusercontent.com/77803435/219865605-94d335ee-215e-417d-bfb3-df4b610a00a8.png)
![image](https://user-images.githubusercontent.com/77803435/219865614-2b21db9a-3518-49fb-95ca-b2610bf637cf.png)

maybe the fix to this would be to hardcode the xmr and eth injecting (not make it a for loop)? or what should i do. and also should i make the rootkit injection at the end of the app

**Comment by shainodev** [comment]
weird now it works (with a firewall that disables internet connections on the miner) when i put the injection in this order miners -> watchdog -> stealer -> rootkit

**Comment by UnamSanctam** [comment]
I'd guess it has something to do with the rootkit (or the stealer).

**Comment by shainodev** [comment]
but how does it only do that when i have the firewall?

**Comment by shainodev** [comment]
also weirdly enough the stealer seems to still be in C# but successfully injects to dialer.exe
