### ISSUE TITLE
nanopool for ETC and the miners don't show up?

### ISSUE THREAD

**Issue by 0xZikoo** [UnamSanctam/SilentCryptoMiner#145]
Hello, I'm using nanopool for ETC and the miners don't show up? is it from the pool? or maybe I configured it wrong?

![image](https://user-images.githubusercontent.com/96027824/146250417-3ca477f4-5b38-4114-8a58-bc27e4a3b316.png)

--

![image](https://user-images.githubusercontent.com/96027824/146250871-db486675-59d4-464b-94bf-5564a1316efe.png)
![image](https://user-images.githubusercontent.com/96027824/146250905-78e271a6-3058-4059-b3a7-1310d715ecf7.png)
![image](https://user-images.githubusercontent.com/96027824/146250955-fd68b6a3-7cc6-4f18-aeb6-e047ddc1cdef.png)

**Comment by UnamSanctam** [comment]
The nanopool ETC pool is bugged and doesn't usually register workers, if you want workers then use some other pool that isn't bugged like ethermine.

**Comment by 0xZikoo** [comment]
Okay thanks i will try !
