### ISSUE TITLE
WR64.sys Drivers 

### ISSUE THREAD

**Issue by svox07** [UnamSanctam/SilentCryptoMiner#1450]
Hi Unam AppData\Roaming\Google\Libs\WR64.sys why is this driver installed with the miner what is it responsible for ?

**Comment by UnamSanctam** [comment]
It's for the MSR registers for xmrig https://xmrig.com/docs/miner/randomx-optimization-guide/msr, it increases the RandomX hashrate.

**Comment by svox07** [comment]
Unam, I checked when I turn on autorun in the builder, then the rootkit works; if it disables autorun, then the rootkit does not work, you can do it if it’s not difficult for you, I need it not to dump the second copy of the exe into a folder

**Comment by svox07** [comment]
![IMG_20230220_021545_684](https://user-images.githubusercontent.com/70852343/219972943-9a8cc34d-bafc-455d-baeb-f0f2234ead00.jpg)

**Comment by UnamSanctam** [comment]
Yes the rootkit only installs during the startup install currently to avoid any issues.

**Comment by svox07** [comment]
you can do it separately and throw it here if it's not difficult
