### ISSUE TITLE
Not more than 1 miner

### ISSUE THREAD

**Issue by LostMySpirit** [UnamSanctam/SilentCryptoMiner#1451]
Can someone explain why i cant have more than 1 miner in my 2miners.com pannel?

**Comment by UnamSanctam** [comment]
Are you using the same worker name? Then 2miners will just combine the hashrate of it all into one, a worker can be a group of miner and not just one.

**Comment by LostMySpirit** [comment]
Ah that's the problem. But how do i give them different names for everynew miner without creating new miner everytime?

**Comment by UnamSanctam** [comment]
You can use {COMPUTERNAME} as the worker name it will replace that with the computers name, so it will appear under that in the pool.

**Comment by LostMySpirit** [comment]
should i use {COMPUTERNAME} after my wallet adress or at the password line?

**Comment by UnamSanctam** [comment]
Where you put the worker name so for 2miners it's in the wallet address field: 
`Wallet.Worker` so in this case it would be `Wallet.{COMPUTERNAME}`

**Comment by LostMySpirit** [comment]
Finally it's working. Thank you!
