### ISSUE TITLE
viruses

### ISSUE THREAD

**Issue by mishav78** [UnamSanctam/SilentCryptoMiner#1452]
virus total says it has many viruses. How do I get it on the target computer? 
https://www.virustotal.com/gui/file/7693c65a929d67b80825dfd1eea650ef0bb4af102a06f394579d8401a432e28d

**Comment by svox07** [comment]
fools will not understand why you leaked there fool fool you do not know how do not go here

**Comment by tarekxxx** [comment]
why upload to virustotal ????

**Comment by mishav78** [comment]
it already had 25 flags, so you can't call it a leak. How do you obfuscate it?

**Comment by mishav78** [comment]
explain please

**Comment by masterjek** [comment]
What is the point of telling you how to encrypt a file if you then throw it on the total virus and in a few days even the encrypted file will have a lot of detections.

**Comment by mishav78** [comment]
i won't throw it. Please tell me

**Comment by rnesheiksilvestre** [comment]
already played in virustotal, burned the file if there was 15 detection, now there will be 30, never pass a virus/trojan in virustotal... and for that reason nobody will teach you how to encrypt because if you do that you will burn the crypter

**Comment by rnesheiksilvestre** [comment]
don't put it in virustotal, burn the file if there were 15 detections, now there will be 30, never pass a virus/trojan in virustotal... and that's why nobody will teach you how to encrypt because if you do that, you'll burn the crypter

**Comment by mishav78** [comment]
where do you upload to check?

**Comment by svox07** [comment]
antiscan.me

**Comment by mishav78** [comment]
how can you be sure it doesn't distribute?
