### ISSUE TITLE
Antivirus

### ISSUE THREAD

**Issue by StroobWasTaken** [UnamSanctam/SilentCryptoMiner#1453]
Hello,
does the antivirus need to be off all the time for the miner to work because i see some infected computers stay for a few hours but they never come back again. Also is there a way to make it undetectable by windows defender other than using a crypter

**Comment by operationalguy** [comment]
> Hello, does the antivirus need to be off all the time for the miner to work because i see some infected computers stay for a few hours but they never come back again. Also is there a way to make it undetectable by windows defender other than using a crypter

You can use my miner, it is undetected by windows deffender
