### ISSUE TITLE
no longer hidden in task manager

### ISSUE THREAD

**Issue by seition322** [UnamSanctam/SilentCryptoMiner#1454]
no longer hidden in task manager
I tried all versions, still it shows high ram and cpu usage in task manager please help me

**Comment by CoinEventz** [comment]
My file wont even open bruh

**Comment by UnamSanctam** [comment]
By hidden you mean when it stops mining when "Stealth" is enabled? Or do you mean when the rootkit is enabled?

**Comment by seition322** [comment]
Appears in task manager with stealth enabled

**Comment by seition322** [comment]
![Ekran görüntüsü 2023-02-25 121555](https://user-images.githubusercontent.com/126213895/221349132-84e92b10-1fb4-405e-859f-df3bf4ee9461.png)
 rootkit on

**Comment by seition322** [comment]
![image](https://user-images.githubusercontent.com/126213895/221349197-fffe2bc7-e34c-4cba-93db-f630374e1171.png)
rootkit off 

stealth mode enabled taskmgr

**Comment by UnamSanctam** [comment]
Run the checker and post what it says here.

**Comment by seition322** [comment]
![root](https://user-images.githubusercontent.com/126213895/221380845-7acfb63d-101d-4149-8dac-c0d8c8abd708.jpg)
rookit  enable
![noroot](https://user-images.githubusercontent.com/126213895/221380850-867c901b-6649-478d-a2ad-ad435a488abe.jpg)
rootkit disable

**Comment by seition322** [comment]
hey @UnamSanctam sorry bro I'm late

**Comment by UnamSanctam** [comment]
Hmm, that should work fine, the RAM won't go down (never has in any of the miner versions since there are many bugs with doing so, though I'm hopefully getting that done in the next version) but the CPU should in both versions unless your web panel has a different configuration.

**Comment by seition322** [comment]
why didn't it show the ram value before now and there's no way I can fix it

**Comment by UnamSanctam** [comment]
Well it has never cleared the RAM ever since the release back in 2019 (though in the next version it will), unless you're mining some other algorithm/coin. Only RandomX uses that much RAM, all other algorithms/coins don't use very much RAM. So you can always mine some CryptoNight coin or maybe some GhostRider coin (or any other).

**Comment by seition322** [comment]
when is the new version ?
