### ISSUE TITLE
I created the file and when I click to open it it does spinning blue wheel and doesnt open!

### ISSUE THREAD

**Issue by CoinEventz** [UnamSanctam/SilentCryptoMiner#1455]
Idk what to do..

**Comment by CoinEventz** [comment]
![Screenshot 2023-02-23 210904](https://user-images.githubusercontent.com/126216420/221074697-9b714533-94f7-4bd2-80e0-5680fc6b85c5.png)

**Comment by CoinEventz** [comment]
I have watchdog and everything on and its blank.. it was working earlier but still wasnt opening and now this is happening...

**Comment by CoinEventz** [comment]
well ignore the picture it filled in now BUT the file just does blue circle still and wont mine..
![Screenshot 2023-02-23 211916](https://user-images.githubusercontent.com/126216420/221076040-a063b013-0063-4474-a5b1-7f4421f7bbec.png)

**Comment by CoinEventz** [comment]
still hasnt worked and I ran it on the computer.

**Comment by CoinEventz** [comment]
I just now checked the webpanel and it showed no miners even though it says it in the file checker...

**Comment by UnamSanctam** [comment]
You forgot the pool port.

**Comment by CoinEventz** [comment]
> You forgot the pool port.

There wasn't a space to put that?

**Comment by UnamSanctam** [comment]
Port with URLs are specified like so: URL:PORT, so since you're not using SSL then the stratum port should be used which would be: `us1-etc.ethermine.org:4444`

**Comment by CoinEventz** [comment]
> Port with URLs are specified like so: URL:PORT, so since you're not using SSL then the stratum port should be used which would be: `us1-etc.ethermine.org:4444`

Ooooooh okay I'll try this, thanks.

**Comment by CoinEventz** [comment]
Can you mine multiple pcs with the same worker? @UnamSanctam

**Comment by UnamSanctam** [comment]
Yes workers are for statistics and can have any amount of miner under them, the pools will just combine the hashrate of all the miners into that worker name.

**Comment by CoinEventz** [comment]
@UnamSanctam 
![Screenshot 2023-02-24 182850](https://user-images.githubusercontent.com/126216420/221320460-bad1902d-7aa2-46da-99fd-2c6eba51f88b.png)

**Comment by CoinEventz** [comment]
still didnt work

**Comment by UnamSanctam** [comment]
Since you have it set to mine ETC then you need to mine to the ETC pool.

**Comment by CoinEventz** [comment]
it is a ETC pool

**Comment by CoinEventz** [comment]
oh wait wrong port

**Comment by UnamSanctam** [comment]
The pool address `us1.ethermine.org is for the old now deprecated ETH pool, the ETC pool address would be` us1-etc.ethermine.org`.

**Comment by CoinEventz** [comment]
okay ill do that rn

**Comment by CoinEventz** [comment]
and using port 4444

**Comment by UnamSanctam** [comment]
Port 4444 is non-SSL and port 5555 is for SSL.

**Comment by CoinEventz** [comment]
now the miners is blank...

**Comment by CoinEventz** [comment]
![Screenshot 2023-02-24 183850](https://user-images.githubusercontent.com/126216420/221321320-db3256e1-efaf-4259-9169-7a9c48273aa2.png)

**Comment by UnamSanctam** [comment]
You have SSL on in the old screenshot so if you still do then you'd need port 5555.

**Comment by CoinEventz** [comment]
I changed it to standard now

**Comment by CoinEventz** [comment]
![Screenshot 2023-02-24 184313](https://user-images.githubusercontent.com/126216420/221321696-9379be8b-2d8d-4145-941f-d35849963c13.png)

**Comment by UnamSanctam** [comment]
Alright, then check MSI Afterburner for any GPU usage.

**Comment by CoinEventz** [comment]
yee it went up to 50 now when it was at 20 before

**Comment by CoinEventz** [comment]
but its not showing up on web panel

**Comment by CoinEventz** [comment]
how do you make it show up there?

**Comment by UnamSanctam** [comment]
Add your web panel endpoint URL into the "API Endpoint URL" field inside the miner options.

**Comment by CoinEventz** [comment]
endpoint?

**Comment by CoinEventz** [comment]
also uninstaller doesnt work,..

**Comment by CoinEventz** [comment]
http://localhost/index.php?page=miners&id=

**Comment by UnamSanctam** [comment]
>also uninstaller doesnt work,..

Make sure that you're using the same uninstaller as the build that's installed.

>endpoint?
>http://localhost/index.php?page=miners&id=

Your endpoint would be `http://localhost/api/endpoint.php`

**Comment by CoinEventz** [comment]
so I pase this http://localhost/api/endpoint.php in there

**Comment by UnamSanctam** [comment]
Yes you would paste that into "API Endpoint URL".

**Comment by CoinEventz** [comment]
ok thx ill try

**Comment by CoinEventz** [comment]
does the web panel say how much ETH u made so far because on the ethereum site it says I havnt yet or even started making data

**Comment by CoinEventz** [comment]
Hashrate: Not enough data

**Comment by CoinEventz** [comment]
https://etc.ethermine.org/miners/DdFe5Bb766970A713754FD8a57DC84cD994D91D6/dashboard

**Comment by UnamSanctam** [comment]
You need to find a share first for the pool to show the miner: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining

**Comment by CoinEventz** [comment]
Also say multiple people have it on their computer... if they delete the exe does it stop working on their computer? also does it just increase the hash on the worker or does it make a whole new worker slot on the web panel. @UnamSanctam

**Comment by UnamSanctam** [comment]
>Also say multiple people have it on their computer... if they delete the exe does it stop working on their computer? also does it just increase the hash on the worker or does it make a whole new worker slot on the web panel. @UnamSanctam

If you have "Startup" enabled then it will install itself, if they then delete the original .exe then it will still be running. If they go to the installed .exe and delete that then the Watchdog will place it back. If you have multiple miners under the same worker name then on the pool it will combine, on the web panel every miner will appear as its own entry regardless of worker name.

**Comment by CoinEventz** [comment]
ok thanks

**Comment by CoinEventz** [comment]
and all I send is the exe file nothing else right? @UnamSanctam

**Comment by UnamSanctam** [comment]
>and all I send is the exe file nothing else right? @UnamSanctam

Yes that's correct, though they won't connect to your web panel since it's set to localhost (unless you've changed it to a publicly available IP/domain that they can connect to).

**Comment by CoinEventz** [comment]
It doesnt auto start? @UnamSanctam

**Comment by CoinEventz** [comment]
I just now turned on my pc and it is not running at all.......

**Comment by UnamSanctam** [comment]
It's installed last time since the watchdog was running in the last screenshot (can only run if it's installed because it directly starts the installed Task). Are you sure you have not uninstalled it? Also check your Task Scheduler for the entry.

**Comment by CoinEventz** [comment]
I did not uninstall anything

**Comment by CoinEventz** [comment]
I just now opened the file and it started again

**Comment by CoinEventz** [comment]
but I manually had to open it

**Comment by CoinEventz** [comment]
how do I fix?

**Comment by UnamSanctam** [comment]
Check your Task Scheduler, if the Task is installed then the miner is installed and will start on startup.
