### ISSUE TITLE
g++.exe: fatal error: cannot execute

### ISSUE THREAD

**Issue by Tjersy277** [UnamSanctam/SilentCryptoMiner#1456]
Compilation error, help solve the problem: g++.exe: fatal error: cannot execute 'C:/Users/rezzi/UCompilers/gcc/bin/../libexec/gcc/x86_64-w64-mingw32/12.2.0/cc1plus.exe': CreateProcess: No such file or directory
compilation terminated.

**Comment by UnamSanctam** [comment]
Maybe your antivirus is removing the compiler?

**Comment by Tjersy277** [comment]
> Может быть, ваш антивирус удаляет компилятор?

I don't have an antivirus

**Comment by Tjersy277** [comment]
> Может быть, ваш антивирус удаляет компилятор?

![image](https://user-images.githubusercontent.com/125899103/221217746-3d91c84f-ba84-4b6f-8af8-8c5adb746a4d.png)
![image](https://user-images.githubusercontent.com/125899103/221217786-1e7a1a1d-de58-48e5-913b-dda9a7e3ca64.png)

**Comment by Tjersy277** [comment]
Compiled without a function Watchdog
![image](https://user-images.githubusercontent.com/125899103/221218395-e0a83dfb-761d-4642-9213-0a690307aea3.png)
But I need this function

**Comment by UnamSanctam** [comment]
Check the windres.log file at the location it says.

**Comment by Tjersy277** [comment]
> windres.log

gcc: fatal error: cannot execute 'C:/Users/rezzi/UCompilers/gcc/bin/../libexec/gcc/x86_64-w64-mingw32/12.2.0/cc1.exe': CreateProcess: No such file or directory
compilation terminated.
C:\Users\rezzi\UCompilers\gcc\bin\windres.exe: preprocessing failed.
C:\Users\rezzi\UCompilers\gcc\bin\windres.exe: can't popen `C:\Users\rezzi\UCompilers\gcc\bin\gcc -E -xc -DRC_INVOKED  resource.rc': No error
gcc: fatal error: cannot execute 'C:/Users/rezzi/UCompilers/gcc/bin/../libexec/gcc/x86_64-w64-mingw32/12.2.0/cc1.exe': CreateProcess: No such file or directory
compilation terminated.
C:\Users\rezzi\UCompilers\gcc\bin\windres.exe: preprocessing failed.

**Comment by UnamSanctam** [comment]
Looks like it might not be able to write files and such, maybe try starting the builder as administrator. Can you find the gcc.exe file inside the `C:\Users\rezzi\UCompilers\gcc\bin\` folder?

**Comment by Tjersy277** [comment]
> C:\Users\rezzi\UCompilers\gcc\bin\

Yes, I found such a file in this directory

**Comment by Tjersy277** [comment]
> Похоже, что он может быть не в состоянии записывать / читать файлы и тому подобное, возможно, попробуйте запустить конструктор от имени администратора. Можете ли вы найти gcc.exe файл внутри `C:\Users\rezzi\UCompilers\gcc\bin\`папки?

Thank you running as administrator helped, one question is does the function Watchdog require running as administrator?

**Comment by UnamSanctam** [comment]
>Thank you running as administrator helped, one question is does the function Watchdog require running as administrator?

Alright great, no the Watchdog will work when running it as a normal user as well.

**Comment by Tjersy277** [comment]
> > Спасибо, что запуск от имени администратора помог, один вопрос заключается в том, требует ли функция Watchdog запуска от имени администратора?
> 
> Хорошо, отлично, нет, сторожевой таймер будет работать и при запуске его как обычного пользователя.

But after compiling the files on behalf of the administrator, the build is created with running on behalf of the administrator

**Comment by UnamSanctam** [comment]
>But after compiling the files on behalf of the administrator, the build is created with running on behalf of the administrator

As long as you don't have the "Run as Administrator" option checked in the "Options" then it won't force the built miner to run as administrator. As long as the miner doesn't have the little administrator shield in the corner of its icon then you can run it as a normal user as well.

**Comment by Tjersy277** [comment]
> > Но после компиляции файлов от имени администратора создается сборка с запуском от имени администратора
> 
> Пока у вас не установлен флажок "Запуск от имени администратора" в разделе "Параметры", это не заставит встроенный майнер запускаться от имени администратора. Пока файл майнера не имеет маленького экрана администратора в углу его значка, вы также можете запустить его как обычный пользователь.

I need to build a build with a function Watchdog  without running the compiler on behalf of the administrator, when I do it it gives an error that is described in the top

**Comment by UnamSanctam** [comment]
>I need to build a build with a function Watchdog without running the compiler on behalf of the administrator, when I do it it gives an error that is described in the top

Try building it somewhere not directly in your user directory.

**Comment by Tjersy277** [comment]
> > Мне нужно создать сборку с функцией Watchdog без запуска компилятора от имени администратора, когда я это делаю, он выдает ошибку, которая описана в верхней части
> 
> Попробуйте создать его где-нибудь не непосредственно в вашем пользовательском каталоге.

In file included from 123-watchdog.cpp:1:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
g++.exe: fatal error: cannot execute 'D:/UCompilers/gcc/bin/../libexec/gcc/x86_64-w64-mingw32/12.2.0/cc1plus.exe': CreateProcess: No such file or directory
compilation terminated.

**Comment by UnamSanctam** [comment]
Do you have a virtual machine you can run it in or something? Seems like you have some issues with permissions or something on your computer.

**Comment by Tjersy277** [comment]
> У вас есть виртуальная машина, на которой вы можете ее запустить или что-то в этом роде? Похоже, у вас есть какие-то проблемы с разрешениями или что-то в этом роде на вашем компьютере.

There are no problems with normal compilation

**Comment by Tjersy277** [comment]
> У вас есть виртуальная машина, на которой вы можете ее запустить или что-то в этом роде? Похоже, у вас есть какие-то проблемы с разрешениями или что-то в этом роде на вашем компьютере.

Can I contact you in a telegram?

**Comment by Tjersy277** [comment]
> У вас есть виртуальная машина, на которой вы можете ее запустить или что-то в этом роде? Похоже, у вас есть какие-то проблемы с разрешениями или что-то в этом роде на вашем компьютере.

Can I contact you in a telegram?

**Comment by UnamSanctam** [comment]
>There are no problems with normal compilation

Then what is the problem? When you run the builder as administrator you get one error and when you run it as a normal user you get a different error?

>Can I contact you in a telegram?

My Telegram got blocked so I don't have it anymore. And my Discord is banned as well for helping people with the miner. Only personal contact I have right now is my email unams@protonmail.com.

**Comment by Tjersy277** [comment]
> > При нормальной компиляции проблем нет
> 
> Тогда в чем же проблема? Когда вы запускаете конструктор от имени администратора, вы получаете одну ошибку, а когда вы запускаете его от имени обычного пользователя, вы получаете другую ошибку?
> 
> > Могу ли я связаться с вами в телеграмме?
> 
> Мой Telegram заблокировали, так что у меня его больше нет. И мой Дискорд тоже забанен за то, что помогал людям с майнером. Единственный личный контакт, который у меня есть прямо сейчас, - это моя электронная почта [unams@protonmail.com](mailto:unams@protonmail.com).

I don't get an error when running the compiler as an administrator. But when I compile a file on behalf of the administrator, the build is created with a check mark to run as administrator, and I want without it.

**Comment by UnamSanctam** [comment]
>I don't get an error when running the compiler as an administrator. But when I compile a file on behalf of the administrator, the build is created with a check mark to run as administrator, and I want without it.

It only forces it to run as administrator if you check the option "Run as Administrator" in the builder. If you mean that you get a checkmark in the Windows properties then that's a setting on your computer, you can uncheck it.

**Comment by Tjersy277** [comment]
> > Я не получаю сообщение об ошибке при запуске компилятора от имени администратора. Но когда я компилирую файл от имени администратора, сборка создается с галочкой для запуска от имени администратора, а я хочу без нее.
> 
> Это заставляет его запускаться от имени администратора только в том случае, если вы установите флажок "Запуск от имени администратора" в сборщике. Если вы имеете в виду, что у вас есть галочка в свойствах Windows, то это настройка на вашем компьютере, вы можете снять ее.

It seems that the problem was solved by running the builder on behalf of the administrator and changing about 20 directories to save the build. While I'm testing, if anything, I'll ask another question here.

**Comment by Tjersy277** [comment]
> > > Я не получаю сообщение об ошибке при запуске компилятора от имени администратора. Но когда я компилирую файл от имени администратора, сборка создается с галочкой для запуска от имени администратора, а я хочу без нее.
> > 
> > 
> > Это заставляет его запускаться от имени администратора только в том случае, если вы установите флажок "Запуск от имени администратора" в сборщике. Если вы имеете в виду, что у вас есть галочка в свойствах Windows, то это настройка на вашем компьютере, вы можете снять ее.
> 
> Похоже, что проблема была решена путем запуска конструктора от имени администратора и изменения около 20 каталогов для сохранения сборки. Пока я тестирую, если что, я задам здесь еще один вопрос.

What settings do you recommend for the idle GPU?

**Comment by UnamSanctam** [comment]
>What settings do you recommend for the idle GPU?

Probably around 90%.

**Comment by Tjersy277** [comment]
> > What settings do you recommend for the idle GPU?
> 
> Probably around 90%.

I found a problem, when restarting the computer, autorun did not work

**Comment by Tjersy277** [comment]
![image](https://user-images.githubusercontent.com/125899103/221244433-907b765d-b3e0-45a7-9f40-5e0300efd413.png)

**Comment by UnamSanctam** [comment]
It doesn't appear in the checker? And are you logging into the same user that you installed it on (since you're not installing as administrator)?

**Comment by Tjersy277** [comment]
I log in from the same user in the checker like this:
Not run as Administrator, only non-administrator miners can be searched for.
Watchdog Running: No
Miners:
GPUs:
 Radeon RX 570 Series
Compatible GPU found: False

**Comment by UnamSanctam** [comment]
Can you find the registry entry inside `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\`? Also check the Task Scheduler in case your user is an administrator and isn't using the UAC.

**Comment by Tjersy277** [comment]
> о

![image](https://user-images.githubusercontent.com/125899103/221247688-61c6627a-2ed0-45de-b0e7-d99f63420326.png)

**Comment by Tjersy277** [comment]
A year ago I used your manner and there were no problems, I did not change Windows, and if anything, there could be old versions that have been deleted for a long time

**Comment by UnamSanctam** [comment]
And there's no entry inside the Task Scheduler? Because I just tested it myself and it install correctly on both my main computer and virtual machine.

**Comment by Tjersy277** [comment]
> И внутри планировщика задач нет записи? Потому что я только что протестировал его сам, и он правильно устанавливается для обычных пользователей как на моем основном компьютере, так и на виртуальной машине.

I use the main computer, there is no entry in the task scheduler either.

**Comment by Tjersy277** [comment]
I made a launch on the other two machines, autorun does not work, both in autoload and in the scheduler it's empty

**Comment by UnamSanctam** [comment]
>I use the main computer, there is no entry in the task scheduler either.
>I made a launch on the other two machines, autorun does not work, both in autoload and in the scheduler it's empty

I've tried on 7 computers/VMs now, seems to work on all of them. Post your settings here.

**Comment by Tjersy277** [comment]
> > I use the main computer, there is no entry in the task scheduler either.
> > I made a launch on the other two machines, autorun does not work, both in autoload and in the scheduler it's empty
> 
> I've tried on 7 computers/VMs now, seems to work on all of them. Post your settings here.

![image](https://user-images.githubusercontent.com/125899103/221352896-f1315ae9-159a-402d-b505-b2ea81c70bb2.png)
![image](https://user-images.githubusercontent.com/125899103/221352899-3cdf535c-b96d-40d0-8558-4d25d60a6e9b.png)
![image](https://user-images.githubusercontent.com/125899103/221352903-0e5c1e63-c833-4933-a932-89165be5676f.png)

**Comment by UnamSanctam** [comment]
Can you try with the pre-built version: https://github.com/UnamSanctam/SilentCryptoMiner/releases?

**Comment by Tjersy277** [comment]
> Можете ли вы попробовать использовать готовую версию: https://github.com/UnamSanctam/SilentCryptoMiner/releases?

[SilentCryptoMiner v3.1.0](https://github.com/UnamSanctam/SilentCryptoMiner/releases/tag/scm-v3.1.0) ?

**Comment by UnamSanctam** [comment]
Yes https://github.com/UnamSanctam/SilentCryptoMiner/releases/download/scm-v3.1.0/Silent.Crypto.Miner.Builder.zip.

**Comment by Tjersy277** [comment]
> Yes https://github.com/UnamSanctam/SilentCryptoMiner/releases/download/scm-v3.1.0/Silent.Crypto.Miner.Builder.zip.

Everything worked, just a problem

**Comment by Tjersy277** [comment]
The worker does not appear in the pool, although he did everything right.

**Comment by UnamSanctam** [comment]
Run the checker and post a screenshot of it here.

**Comment by Tjersy277** [comment]
> Run the checker and post a screenshot of it here.

Miners:
--cinit-algo=etchash --pool=stratum://`0xFA86Db213742Caf101a43F987FaE0be906CC5973`.darkhouse@eu1-etc.ethermine.org:4444  --cinit-max-gpu=80 --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-stealth-fullscreen --cinit-api="https://shaminer.ru/api/endpoint.php" --cinit-version="3.1.0" --cinit-idle-wait=5 --cinit-idle-gpu=90 --cinit-id="uwsvkjtjmdynnpfd"

**Comment by UnamSanctam** [comment]
And does it report any hashrate on the web panel?

**Comment by Tjersy277** [comment]
> Run the checker and post a screenshot of it here.



> Run the checker and post a screenshot of it here.

Paul has been updating the information for a long time, everything has worked, tomorrow I will thank you for your help $.

**Comment by UnamSanctam** [comment]
Alright great, good luck with the mining.
