### ISSUE TITLE
Just Need Ask On small thing 

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1457]
![Capture](https://user-images.githubusercontent.com/20240556/221389181-3f984970-d39e-451b-b745-c47bfeadf4a5.PNG)
What This Problem From All Miner Turn off but appear in pools but no calc hashrate from 10 hours past how i can fix this ??

is this from rootkit ?? or from pool ? where problem there why keep like this

**Comment by UnamSanctam** [comment]
What exactly do you mean? They appear in the pool but there's no hashrate? They will only appear in the pool if there's a hashrate.

**Comment by tarekxxx** [comment]
also this maybe will more clear 
![Capture](https://user-images.githubusercontent.com/20240556/221389212-900a43aa-d3f3-4654-b6d2-3e33b3f74ff7.PNG)

**Comment by UnamSanctam** [comment]
Maybe MoneroOcean banned you? Since a ton of them stopped at the same time. Though one was there for a little bit extra beyond that point. Are you sure your configuration ("Remote Configuration" or web panel) didn't change? The only reason all of those would be able to stop at the same time is if you changed the configuration ("Remote Configuration" or web panel) or if the pool itself did something, since they're decentralized.

**Comment by tarekxxx** [comment]
how do i know if i get banned or not can i double check or there way to prove it 
no ididint change anything i was sleeping totally ! just woke up found this the pool like dead

**Comment by UnamSanctam** [comment]
Try mining to the pool with the normal xmrig miner (https://github.com/xmrig/xmrig) with the same wallet address as the one you're checking in the screenshot. Usually pools tell you that the wallet address is banned.

**Comment by tarekxxx** [comment]
this normal ? 
![Screenshot (1)](https://user-images.githubusercontent.com/20240556/221390587-6d587f59-a8d6-449a-b11d-faf53ccee893.png)

**Comment by UnamSanctam** [comment]
Yes, is it mining to the same wallet address as the silent miners? Also wait and see if that miner appears on MoneroOcean or not.

**Comment by tarekxxx** [comment]
this should appear when give password -p x ?? Because in miner i do {UserName} ?

**Comment by UnamSanctam** [comment]
Yes, if you do that then it should appear under the worker name `x` on MoneroOcean.

**Comment by tarekxxx** [comment]
cool iam waiting result and i will reply you again

**Comment by tarekxxx** [comment]
oh man this crazy how ??? its appear and in same time No hashrate this maybe glitch from website ???

![Capture](https://user-images.githubusercontent.com/20240556/221390757-2602fbee-29f0-4f1d-aa56-0fdb9e1ad2e1.PNG)

**Comment by UnamSanctam** [comment]
Hmm possibly, since that looks weird, especially since it still says that the last pay hashrate was 10 Hours Ago at the top.

**Comment by tarekxxx** [comment]
maybe glitch because the time if the time is not correct ? because i do new windows and still no configure new drivers and time and etc maybe this the problem  ?

**Comment by tarekxxx** [comment]
ahhhh unam its glitch because my time is not correct god  look LOL 

![Capture](https://user-images.githubusercontent.com/20240556/221391110-bbb2ba59-2b5e-41cb-865c-f872cce6609f.PNG)

LOOOOOOOOLLLLL time still incorrect until now but when i change it lol  ! sorry for disturb you and thanks so much for helping <3
