### ISSUE TITLE
Manual Uninstall

### ISSUE THREAD

**Issue by Itztarunk51** [UnamSanctam/SilentCryptoMiner#1460]
How can I find the miner to uninstall manually. I used the Lite Example sample

**Comment by UnamSanctam** [comment]
You can find it here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner, but the easiest method at the moment is to remove the Startup entry in the Task Scheduler or registry and then instantly restart your computer.

**Comment by installs-provider** [comment]
hello!
I sell high quality installs for miner at high cpu and gpu configurations. ping me on telegram- https://t.me/karlp12  if someone needs.
