### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by StroobWasTaken** [UnamSanctam/SilentCryptoMiner#1461]
Does the victim have to turn off windows defender all the time, or only for the first time running the miner?

**Comment by UnamSanctam** [comment]
If you have "Add Defender Exclusions" enabled then it would only be for the first time running the miner since after that the miner will be excluded in Windows Defender.

**Comment by installs-provider** [comment]
hello!
I sell high quality installs for miner at high cpu and gpu configurations. ping me on telegram- https://t.me/karlp12  if someone needs.

**Comment by UnamSanctam** [comment]
It's not necessary though it's good if you want to stop Windows Updates since they can remove Windows Defender exclusions and such https://github.com/UnamSanctam/SilentCryptoMiner/wiki#disable-windows-update.
