### ISSUE TITLE
Inject into dvm.exe

### ISSUE THREAD

**Issue by ThunderX-HUB** [UnamSanctam/SilentCryptoMiner#1463]
![process_dwm exe_](https://user-images.githubusercontent.com/104974936/223025321-15c72bcb-ca9d-4674-b357-8c64f6f8c9f4.png)

Why, when I end the dvm.exe, it doesn't cause the Blue Screen of Death?

**Comment by UnamSanctam** [comment]
Are you killing the correct one? And do you have both "Critical Processes (BSoD)" and "Run as Administrator" enabled? And do you have "Startup" enabled or not?

**Comment by ThunderX-HUB** [comment]
> Are you killing the correct one? And do you have both "Critical Processes (BSoD)" and "Run as Administrator" enabled? And do you have "Startup" enabled or not?

I will try again

**Comment by ThunderX-HUB** [comment]
> Are you killing the correct one? And do you have both "Critical Processes (BSoD)" and "Run as Administrator" enabled? And do you have "Startup" enabled or not?

Ahh I checked again and everything is ok, but why did I end DWM 1 and DWM 2 and it still isn't causing the blue screen of death?

**Comment by ThunderX-HUB** [comment]
> Are you killing the correct one? And do you have both "Critical Processes (BSoD)" and "Run as Administrator" enabled? And do you have "Startup" enabled or not?

![Uploading Screenshot_2023-03-06-12-51-14-91.png…]()

**Comment by ThunderX-HUB** [comment]
> Are you killing the correct one? And do you have both "Critical Processes (BSoD)" and "Run as Administrator" enabled? And do you have "Startup" enabled or not?

![Screenshot_2023-03-06-12-51-14-91](https://user-images.githubusercontent.com/104974936/223029472-daead8f5-c8cf-4166-a2de-24e5b2eb8bec.png)

**Comment by UnamSanctam** [comment]
Can you post your miner builder settings here?

**Comment by ThunderX-HUB** [comment]
> Can you post your miner builder settings here?

https://files.catbox.moe/12totv.xml

**Comment by ThunderX-HUB** [comment]
> Can you post your miner builder settings here?

I have more than 200 victims, so please check quickly.

**Comment by ThunderX-HUB** [comment]
> Can you post your miner builder settings here?

Although it still works very well, if there is an error, I can't rest assured.😐

**Comment by ThunderX-HUB** [comment]
> Can you post your miner builder settings here?

cohost.exe, svhost.exe, notepad.exe, nslookup.exe work properly except dwm.exe

**Comment by ThunderX-HUB** [comment]
> Can you post your miner builder settings here?

Pls reply

**Comment by UnamSanctam** [comment]
You have "Install Rootkit" enabled in those settings so the miner will inject into an invisible dialer.exe process (the rootkit hides it). If I disable "Install Rootkit" and start the miner then if I kill the dwm.exe it injected into then it blue screens for me.

**Comment by ThunderX-HUB** [comment]
> You have "Install Rootkit" enabled in those settings so the miner will inject into an invisible dialer.exe process (the rootkit hides it). If I disable "Install Rootkit" and start the miner then if I kill the dwm.exe it injected into then it blue screens for me correctly.

Thanks for telling me; it's been a while. Why haven't you updated the silent miner, binder, and downloader? I'm still waiting for your update. Have a nice day!
