### ISSUE TITLE
Government question

### ISSUE THREAD

**Issue by unameddev** [UnamSanctam/SilentCryptoMiner#1466]
Hello Unam, I hope you are well, my question is the following... I work in the government, I am the head of IT in the building, where there are dozens and dozens of pcs... The building's network passes through a firewall server, which can monitor traffic. Putting the miner on the computers, would they be able to somehow track that the miner is on the pcs through the network? Is there any chance I'll get caught? I await your reply, best regards.

**Comment by shainodev** [comment]
if u actually were the "head it of the goverment" i think you'd know the answer to ur queston and realize urself, also the sound and av detections. and they can easily see that there is traffic going to a mining pool

**Comment by UnamSanctam** [comment]
Yes they would see the mining traffic to the pool, it is unavoidable since the miner needs to talk to a pool (or at least the blockchain) to be able to mine.
