### ISSUE TITLE
Error: An error occured while compiling

### ISSUE THREAD

**Issue by xsuperblyx** [UnamSanctam/SilentCryptoMiner#1470]
Hi, a have an error every time when i try to Build miner: Error: An error occured while compiling - the specified executable file is not a valid application for this operating system. 

I tried to change config - didn't help

How can I solve this problem? I tried to search it in Google - many people write that I need to reinstall Visual Studio. But I'm downloading the Pre-Compiled miner builder. I don't need Visual Studio at all to compile, right?

**Comment by UnamSanctam** [comment]
No you don't need Visual Studio. Make sure that your operating system is 64-bit, if it is then also make sure to exclude the build folder from any antiviruses so that they don't remove the compilers or any files.

**Comment by xsuperblyx** [comment]
Thank you, it turned out that I have a 32-bit system, I will reinstall Windows. I also wanted to clarify about the pool. I use the f2pool pool. My pool looks like this: 
stratum+tcp://etc.f2pool.com...... 
Do I need to delete "stratum+tcp://" from the string that I write to field "pool"?

**Comment by UnamSanctam** [comment]
Yes only enter the pool URL and port (URL:PORT), the miner will automatically add the stratum protocol.

**Comment by xsuperblyx** [comment]
Thank you very much! I didn't expect you to answer so quickly :)

**Comment by hey000hey** [comment]
I'm using the newest version 3.20 with the Lite settings. I disabled my antivirus and restsarted my computer, and I am running 64 bit windows. Is there anything else I can do to prevent this problem?

**Comment by UnamSanctam** [comment]
>I'm using the newest version 3.2.0 with the Lite settings. I disabled my antivirus and restsarted my computer, and I am running 64 bit windows. Is there anything else I can do to prevent this problem?

Try running it as administrator, most likely it cannot find or cannot access the file either due to permissions or something similar.
