### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Frido-Cpp** [UnamSanctam/SilentCryptoMiner#1471]
Hello Everyone, I wanna ask this questions..

1. Anyone who has bots(computers) currently mining, what is your estimated H/S for about 100bots? which are just normal computers mining xmr  with cpu only(Not High Gaming PC) mining at 50% max cpu and 80% idle?

2.  What is the estimated amount of H/S you think 100 High end gaming PCs can produce with 50% max cpu and 80% idle?

I'm asking all this because I had to test the miner on 5bots(not gaming PC's) and are 100% always online and they only produced 3000H/S(as currently calculated H/S) and 1500H/S(As Average H/S) using nanopool so it got me thinking if it's mining well.

3. And I don't see my 5 tested workers on the pool darshboard and it's been 1 week now.  why?

4. Unam do you accept contributions on the source?

I'll appriciate all your answers ..||.. And I hope the answers help others with my same doubts too...... Thanks

**Comment by UnamSanctam** [comment]
1. I don't have any bots mining but it depends really on what exact CPUs they have, usually a normal computer has between 200H/s-1000H/s at 50%.
2. High-end gaming computer is quite broad, it's usually around 1000H/s-10000H/s depending on if their CPU is really good or not, you can find many Monero CPU hashrate benchmarks here: https://xmrig.com/benchmark.

>I'm asking all this because I had to test the miner on 5bots(not gaming PC's) and are 100% always online and they only produced 3000H/S(as currently calculated H/S) and 1500H/S(As Average H/S) using nanopool so it got me thinking if it's mining well.

Yes that's not a bad hashrate for 5 (non high-end) computers.

3. It should appear on the pool as soon as it finds and submits a share. Make sure that the pool settings are correct and that they mine long enough to find a share (depends on the hashrate and pool share difficulty).
4. Sure though much of the source is already changed in the development of the next version so I might not be able to use it.

**Comment by UnamSanctam** [comment]
1. No it would use a ton of the GPU without getting a lot of hashrate.
2. Yes that would be better than using it for Monero at least.
