### ISSUE TITLE
Any update ?

### ISSUE THREAD

**Issue by DogusCzk** [UnamSanctam/SilentCryptoMiner#1472]
Will there be an update? It's been 5 months.

**Comment by UnamSanctam** [comment]
>I think if I encrypt it it will be undetectable, right?
>Will the miner viruses in the victim's computer be removed by windows defender?

Depends on how good your crypter is but yes that's their intended effect. Right I'm just looking to make the foundation (uncrypted miner) as undetectable as possible, I'm also working on my anti-VirusTotal/sandbox feature which I think is working but I need to build a separate test program to make sure.

**Comment by DogusCzk** [comment]
> It's detected by Windows Defender right now, I can release the one I'm working on but it will be detected. I haven't finished the changelog yet (since I'm still changing this) but this is the draft I've written down so far:
> 
> * Changed miner settings from being passed through the command line to instead be passed through the PEB
> * Changed XMR miner to clear RAM when "Stealth" is triggered
> * Removed some API calls by instead directly reading the PEB
> * Updated compiler command options to reduce detections
> * Changed encryption method to avoid new Windows Defender detection
> * Changed GPU checking to directly reading the registry for the GPU information instead of using a WMI command with a file buffer
> * Moved administrator checks from powershell directly into the C++ code
> * Added Task Scheduler Startup entry checking into the Watchdog
> * Added custom made SysWhispers3 direct system call generator
> * Removed SysWhispers2
> * Readded explorer.exe as injection option
> * Made explorer.exe the default injection option again
> * Updated uninstaller to find the miner processes to kill by enumerating system mutex handles to find the owner process
> * Updated checker to instead check if the mutex is active to ascertain whether the miner and watchdog is running or not
> * Merged many C++ files together to be able to store them unzipped in order make code changes visible in commits
> * Updated miners

very cool update thank you for your hardworks 👌

**Comment by svox07** [comment]
Unam when you make an update, write everywhere on the main page of github and where it downloads, don’t merge VIRUSTOTAL, otherwise you’re tired of these shkolota who scans there
