### ISSUE TITLE
obfuscating source code question

### ISSUE THREAD

**Issue by Amittere1** [UnamSanctam/SilentCryptoMiner#1475]
if i obfuscate the source code from this repo in visual studio then build will it work and bypass antivirus? I cant obfuscate the exe because its not full C#

**Comment by UnamSanctam** [comment]
You'd have to "obfuscate" the C++ code inside Resources/Code though that's quite advanced.

**Comment by Amittere1** [comment]
Also if i didnt enable api endpoint in the builder can i enable it in the remote config?

**Comment by UnamSanctam** [comment]
Yes you can add the `"api-endpoint": "API Endpoint URL"` option into it.

**Comment by Amittere1** [comment]
Thanks sir for fast response
