### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by MigrantBirdd** [UnamSanctam/SilentCryptoMiner#1476]
hey guys;

thanks for good jobs; btw i didnt get how to run this program? any help plz

**Comment by UnamSanctam** [comment]
You can download the pre-compiled builder here: https://github.com/UnamSanctam/SilentCryptoMiner/releases

**Comment by MigrantBirdd** [comment]
already did but after setting up, i didnt get how must run it? it has dfrnt option but no function to start or run or etc.

**Comment by UnamSanctam** [comment]
After you build the miner then you get an .exe file that you start to start the miner.

**Comment by MigrantBirdd** [comment]
have u any clip to get it? i used the simple light for as test to understand the project but it hasnt any exe file
sorry if bother u

**Comment by UnamSanctam** [comment]
In the builder you go to the "Build" tab and press "Build" then you can choose the name for the .exe, enter whatever name you want and press "Save". Then the builder will compile a miner called the name you entered before, you can then start that file to start the miner, if you want to check if the miner is running then you can run the checker that also got built.

**Comment by MigrantBirdd** [comment]
thank u so much;  its built already but after runnig the exe. nothing appears as new window or anything else to understand works or not. so after checking by checker; the result to apper is just the miner info and my gpu. thats it .
do i must wait to other actions or its done?

**Comment by UnamSanctam** [comment]
If it's showing the miner settings inside the checker (the pool and everything) then that means the miner is running correctly and doesn't need any other actions. No window will appear when you start the miner since it's a silent miner.
