### ISSUE TITLE
Pool 

### ISSUE THREAD

**Issue by floof989763** [UnamSanctam/SilentCryptoMiner#1478]
Hello unam!
I have been using your miner and it is perfect ..... i want to thank you about putting such an expensive tool for free ....sir i wanted to ask that many people told me that if you use many pc's for silent crypto mining ...... then the pool will ban your addresss and you will get nothingg..... and people told me to use proxies and all... i am a bit confused .... pleasee guide me unam sir .

**Comment by UnamSanctam** [comment]
Yes some pools can do that, but it's generally accepted that some pools like nanopool and 2miners won't ban you. You can also set up "Remote Configuration" for your miners and then in the unlikely situation that you do get banned then you can just switch the miners directly to another pool.
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration
