### ISSUE TITLE
defender updated (lot of disconnected)

### ISSUE THREAD

**Issue by parabola20** [UnamSanctam/SilentCryptoMiner#1479]
hi Unam, 30-50% of my users are disconnected, it looks like a global update of the WD. will there be a miner update soon?

ps i had 15-20ghs on 2miners, now 7-10ghs and the values keep dropping

*using translator*

**Comment by UnamSanctam** [comment]
Yes I'm always working on it, right now I'm trying to change it from using XOR encryption (in obfuscate.h and the resource cipher) since that seems to be triggering Windows Defender.

**Comment by Wooyme** [comment]
Hi,UnamSanctam. Thank you for your work very much. Your program helps me pass a tough life. And here is my sulotion to against Windows Defender, maybe it will help you.
https://github.com/Wooyme/fucking-av
