### ISSUE TITLE
Mine RVN or ETC

### ISSUE THREAD

**Issue by uscgbuzzman** [UnamSanctam/SilentCryptoMiner#1482]
Hello, I want to know how can I make the miner to mine ETC if there arent enough VRAM or mine RVN is there are enough VRAM

**Comment by UnamSanctam** [comment]
You'll have to code it into the miner, first you'll have to check the VRAM (only real way to do it is by using the registry, and that only shows the total VRAM so you'll have to make to with that) and then if there is enough VRAM to mine RVN then you'll have to start the RVN miner and if there isn't enough then you'll have to start the ETC miner.

**Comment by uscgbuzzman** [comment]
I code the SilentCryptoMiner.sln with Microsoft Visual Studio?

**Comment by UnamSanctam** [comment]
Yes and then you'd have to code that inside https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/miner.cpp.

**Comment by uscgbuzzman** [comment]
I dont know how to code it, can you teach me?

**Comment by UnamSanctam** [comment]
It's quite complicated to do, and RVN isn't very good for silent mining in my opinion which is why it's not very prioritized in the miner.

**Comment by shainodev** [comment]
> only real way to do it is by using the registry.

you can do it with WMI, no?

**Comment by UnamSanctam** [comment]
>you can do it with WMI, no?

The WMI VRAM variable is an unsigned 32-bit integer, which means that it maxes out at 4GB, so if you have more than 4GB VRAM it will still only show 4GB.
