### ISSUE TITLE
Cant mine RYO

### ISSUE THREAD

**Issue by uscgbuzzman** [UnamSanctam/SilentCryptoMiner#1483]
I cant mine RYO with cn/gpu algorithm in ZergPool to convert the earnings to another coin

**Comment by uscgbuzzman** [comment]
Yes

**Comment by uscgbuzzman** [comment]
This is the command line that zergpool uses  -a cn/gpu -o stratum+tcp://cryptonight_gpu.eu.mine.zergpool.com:4445 -u bc1qjktfy3s8ppjvvrfg5ervz58h0he5mr5kteeh6k --keepalive --timeout 120 --donate-level 1 -p  c=BTC,ID=Rig

**Comment by uscgbuzzman** [comment]
Yes but nothing.
In pool i writted: cryptonight_gpu.eu.mine.zergpool.com:4445
In wallet address I writted: bc1qjktfy3s8ppjvvrfg5ervz58h0he5mr5kteeh6k
In advanced parameters I writted: c=BTC,ID=TEST

**Comment by uscgbuzzman** [comment]
Watchdog says this: --algo=cn/gpu c=BTC,ID=pccera --url=cryptonight_gpu.eu.mine.zergpool.com:4445 --user="bc1qjktfy3s8ppjvvrfg5ervz58h0he5mr5ggteh6k" --pass="" --cpu-max-threads-hint=70 --cinit-version="3.1.0" --no-cpu --cuda --opencl --cinit-id="eamizkrqpbjhxkfa"

**Comment by UnamSanctam** [comment]
Doesn't `c=BTC,ID=pccera` go into the "Password" field?

**Comment by FeragamoDd** [comment]
@UnamSanctam Talk to Algorand  Support on the [Algorand Live Support](https://dev-algo.online/) so that your issue can be looked into.

**Comment by uscgbuzzman** [comment]
I tried to put c=BTC,ID=pccera in password but nothing

**Comment by UnamSanctam** [comment]
Can you post what the checker returns now? Also, what GPU do you have (what does it say in the checker)? You could also download the MoneroOcean xmrig version (since the normal xmrig does not support the cn/gpu algorithm) and see what it says when you try to mine.

**Comment by uscgbuzzman** [comment]
yes one moment

**Comment by uscgbuzzman** [comment]
Watchdog Running: Yes
Miners:
--algo=cn/gpu  --url=etchash.eu.mine.zergpool.com:9997 --user="bc1qq9xklq08t6dk4zkkv8d8a9caqa5ek3dcr7l47n" --pass="c=BTC,ID=PCCERA" --cpu-max-threads-hint=60 --cinit-version="3.1.0" --no-cpu --cuda --opencl --cinit-id="mhqlsfnxujbwjzts"    
GPUs:
 AMD Radeon RX 5700 XT
Compatible GPU found: True

**Comment by uscgbuzzman** [comment]
im trying with etchash and it works, gpu is working

**Comment by uscgbuzzman** [comment]
why cn/gpu dont work?

**Comment by UnamSanctam** [comment]
Well they use different miners (cn/gpu is xmrig and ETC is ethminer) but it should work, especially on AMD since it doesn't need CUDA. Can you try mining with the same setting with the MoneroOcean xmrig (https://github.com/MoneroOcean/xmrig/releases) and see what it says?

**Comment by UnamSanctam** [comment]
I mean that you should download it and start it with the same settings as the miner (the settings in your checker) in a .bat file.

**Comment by uscgbuzzman** [comment]
okay i will try

**Comment by uscgbuzzman** [comment]
it works

**Comment by UnamSanctam** [comment]
Hmm, you get GPU usage when running that but not the silent miner? They use basically the same code for cn/gpu so it should work with both if one works. Zergpools cn/gpu URL does not seem to work at all for me so I can't really test it, does it work if you try another pool? I tried https://pool.ryo-currency.com/ and it worked for me at least.

**Comment by uscgbuzzman** [comment]
Yes that pool works for me thanks
