### ISSUE TITLE
Silent crypto miner dont work

### ISSUE THREAD

**Issue by Alberticomakina96** [UnamSanctam/SilentCryptoMiner#1485]
Hello, I created the .exe with all the startup and options but when I open it to test it, windows defender deletes it. Also when I have Windows Defender off.

**Comment by UnamSanctam** [comment]
Yes it's a public project so it's going to be detected pretty fast after each release. If you exclude the miner file/folder where you first start it then it won't be deleted when installed if you have "Add Defender Exclusions" enabled.

**Comment by Alberticomakina96** [comment]
But when the victim open the .exe, windows defender delete it automatically

**Comment by Alberticomakina96** [comment]
ok thx sir
