### ISSUE TITLE
Cant mine ETC in 2miners

### ISSUE THREAD

**Issue by Alberticomakina96** [UnamSanctam/SilentCryptoMiner#1486]
I cant mine ETC in 2miners and get paid in BTC. When I set my BTC wallet address in the miner and test it, the gpu usage goes from high to 0-5%. I also tried the same config but my ETC wallet instead of BTC wallet

**Comment by UnamSanctam** [comment]
It should work fine, if it's not working then it's due to something on their side. Run the checker and post what it says here and I'll check.

**Comment by Alberticomakina96** [comment]
Watchdog Running: Yes
Miners:
--cinit-algo=etchash --pool=stratums://`bc1qnkyhslv83yyp0q0suxw0uj3lg9drgqq9c0auzc`.{COMPUTERNAME}@etc.2miners.com:11010  --cinit-max-gpu=60 --cinit-version="3.1.0" --cinit-id="tuzgeywrthhwlfmo"
GPUs:
 AMD Radeon RX 6700 XT
Compatible GPU found: True

**Comment by UnamSanctam** [comment]
Hmm I just tried that and it works for me, the only reason that wouldn't work for you is if the pool is refusing your connection for some reason.
