### ISSUE TITLE
Rootkit and BSoD

### ISSUE THREAD

**Issue by Alberticomakina96** [UnamSanctam/SilentCryptoMiner#1487]
Hello, do I have to use BSoD and rootkit at the same time or not?

**Comment by UnamSanctam** [comment]
No they are not required for each other, the only requirement is to run it as administrator.

**Comment by UnamSanctam** [comment]
Maybe it didn't install correctly, maybe it didn't apply just that time or a Windows update could have broke something with it. The rootkit itself (r77-rootkit) haven't gotten any new updates so I'll have to investigate and see if I can reproduce and solve the problem myself. I'm just focused on the more important parts first for the next update.

**Comment by Alberticomakina96** [comment]
okay thx
