### ISSUE TITLE
Unam, hey! When will u drop a release?)))

### ISSUE THREAD

**Issue by ssk666** [UnamSanctam/SilentCryptoMiner#149]

**Comment by UnamSanctam** [comment]
Currently I have a lot of real life work though I'm working on the miner with all the free time that I have and I've completed a lot of the work so far (such as adding the ghost rider algorithm and such), sorry if I miss any messages as well.

**Comment by ssk666** [comment]
Thank u very much for your answer! We really appreciate your work! I hope there will be a gift for the NY in the form of a release)))
