### ISSUE TITLE
VirusTotal bypass

### ISSUE THREAD

**Issue by sa6ta6ni6c** [UnamSanctam/SilentCryptoMiner#1492]
Hello UnamSanctam!

Can you add a built-in option to increase the file size to over 650MB to prevent uploading the stub into Virustotal?

Regards

**Comment by sa6ta6ni6c** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
Maybe, but you can just use a file pumper if you want that.

**Comment by parabola20** [comment]
I think this function will be useful if the size of the file increases after infection, because it will be difficult to distribute such a large file

**Comment by UnamSanctam** [comment]
>I think this function will be useful if the size of the file increases after infection, because it will be difficult to distribute such a large file

Well that wouldn't really help with VirusTotal nor the antivirus so what would be the purpose then? In case the upload the installed file after it gets installed? One problem with modifying the installed file (like how it did originally in 3.0.0 beta) is that some antiviruses like Avast will rerun the sandbox on the file since the MD5 gets changed so the user gets notified about it.

>hey Unam, the part of editing the version of UnamBinder and UnamDownloader is broken or something. Please check again

What do you mean? Though in the binder I think you need to move one line (the resource ID line) down into the loop,

**Comment by UnamSanctam** [comment]
>i don't understand, it is currently "file version: 0.0.0.0"
>I edited version 2.2.9.4 but when I finished editing and checked the file again, it was "file version: 2.0.0.0".

Oh you mean the vanity version for the Managed (C#) build? You might need to change the delimiter from a comma to a dot then if you're up for changing the code.

In this line:
https://github.com/UnamSanctam/UnamDownloader/blob/3deb02a9e38dea2c11c11dcd502b3d6c4c42fe1e/UnamDownloader/Forms/Builder.cs#L61
Change the `","` to `"."`

**Comment by UnamSanctam** [comment]
>uhhh... but can you give me the source code for this?

Not sure where it is, I might've removed it since it was just for a quick question. But you can disassemble the program with any .NET disassembler and see the powershell code changes I made

**Comment by sa6ta6ni6c** [comment]
> Maybe, but you can just use a file pumper if you want that.

The issue arises because individuals rely on VirusTotal to examine the Miner's stub. Including this in the default settings might be beneficial while allowing disabling it within the configuration (somewhere in the files). This way, it would deter users from uploading the miner on VirusTotal solely for verification purposes.
