### ISSUE TITLE
earnings per day average per infected user 

### ISSUE THREAD

**Issue by mishav78** [UnamSanctam/SilentCryptoMiner#1494]
please post your earnings per day average per infected user. Say whether you use cpu, gpu or both and at what percentages? Thanks. I would like to understand the possible earning potential. if you want include the coins that you mine, voluntary. Thanks again.

**Comment by LostMySpirit** [comment]
1 worker have a averge of 1.7khs for me.
I am mining cpu only monero the percentage is 60/80

**Comment by mishav78** [comment]
so five cents a day per user https://www.coinwarz.com/mining/monero/calculator?h=1.7&p=450.00&pc=0.10&pf=0.00&d=315172950804.00000000&r=0.65000000&er=0.00590780&btcer=27713.83800000&ha=KH&hc=0.00&hs=0&hq=1

1. You mine at 60% just for the miner cpu usage or total cpu usage when the computer is not idle? 
2. i know you can probably get to twenty cents per day if you mine with gpu also, maybe more. I know a high percentage of users have gpus.

**Comment by LostMySpirit** [comment]
> 

i have 60% normal and 80% idle it depends on the client i got pc's who are having more than 3kh's only cpu.
I personaly dont like mining monero with gpu because the pc will be way slower as it would be with only cpu mode and the people will be noticing it.

**Comment by mishav78** [comment]
you can mine other coins on the gpu. How many infected users do you have?

**Comment by LostMySpirit** [comment]
Yea that would be posible. On monero i have currently 10 people infected.

**Comment by mishav78** [comment]
did you crypt the silent miner? Is it being detected by Antivirus programs?

**Comment by LostMySpirit** [comment]
no i dont crypt it and its by the most av's detected.

**Comment by mishav78** [comment]
how do you spread it?

**Comment by LostMySpirit** [comment]
almost all posible ways

**Comment by xyzssx** [comment]
> almost all posible ways

have you got telegram or discord? i need to contact u asap

**Comment by LostMySpirit** [comment]
> > almost all posible ways
> 
> have you got telegram or discord? i need to contact u asap

мтгox#9673
sure you can dm me.

**Comment by mishav78** [comment]
> > > almost all posible ways
> > 
> > 
> > have you got telegram or discord? i need to contact u asap
> 
> мтгox#9673 sure you can dm me.

dm you on what platform? Github doesn't have dm.

**Comment by mishav78** [comment]
with cpu and gpu running can you make 20 cents usd per day per infected user?
