### ISSUE TITLE
crypter

### ISSUE THREAD

**Issue by mishav78** [UnamSanctam/SilentCryptoMiner#1495]
if I crypt it and it is already on the infected computer, do I have to update the encryption on the infected computers or it will eventually be detected by Antivirus programs?

**Comment by UnamSanctam** [comment]
Yes like how it is with any other program, that crypt will probably eventually be detected unless you were to recrypt it before that, but that only works if you have access to the computer somehow (to replace the old one). Normally people just hope for the best.

**Comment by rootfast** [comment]
does miner work with crypter made in vb.net or c++ or also made in vb6 does it work?

**Comment by UnamSanctam** [comment]
>what is the difference between native and dot net?

Native is a normal program in machine code that runs natively on Windows, a .NET assembly is a program that gets interpreted in the .NET virtual machine that you have installed (the .NET framework) much like how it works for Java as well.

**Comment by mishav78** [comment]
can native use win api and Com api?

**Comment by UnamSanctam** [comment]
>can native use win api and Com api?

Yes of course, that's what the APIs are really made for.

**Comment by UnamSanctam** [comment]
>so it is just without the dot net framework?

Yes it's a compiled program that runs natively in the operating system without needing anything installed such as .NET, Java or whatever else.
