### ISSUE TITLE
how to add ETC to metamask? using chainlist?

### ISSUE THREAD

**Issue by Yakuuuuuuuu** [UnamSanctam/SilentCryptoMiner#1497]
how to add ETC to metamask? using chainlist?

**Comment by UnamSanctam** [comment]
Yes you simply add a new chain (RPC network).

- Network Name: Ethereum Classic
- RPC URL: https://etc.rivet.link/
- Chain ID: 61
- Symbol: ETC
- Block Explorer URL: https://blockscout.com/etc/mainnet/
