### ISSUE TITLE
UnamWebpanel and Silent Crypto Miner

### ISSUE THREAD

**Issue by Alberticomakina96** [UnamSanctam/SilentCryptoMiner#1498]
Hello, do you know a secure host to use with UnamWebpanel and Silent Crypto Miner? 000webhost is safe?

**Comment by Alberticomakina96** [comment]
some examples to buy? @UnamSanctam

**Comment by UnamSanctam** [comment]
>some examples to buy? @UnamSanctam @samogost

Not sure, some have written a few services in some issues but I don't know if they're good or not. Many host it with a VPS.

**Comment by Alberticomakina96** [comment]
Okay, is safe to buy a domain in Google Domains? By safe I mean if they can link those miners to me

**Comment by UnamSanctam** [comment]
>Okay, is safe to buy a domain in Google Domains? By safe I mean if they can link those miners to me

No they will most likely ban you, and you'll also have to disclose your identity since you cannot own a domain otherwise by law. Though there are some services that will legally own the domain for you and give you full control over it, I'll repost what I said in your other issue here as well.

>I wouldn't recommend that since they'll probably ban your domain (and by law you cannot be anonymous), if you want a domain then you'll probably have to get one from something like https://xuid.ru/. But even if you have a domain you still need a webhost of course, the good thing with having a domain is that if your website ever gets banned by your webhost then you can just point the domain to a new webhost.

**Comment by Alberticomakina96** [comment]
Which webhost do you recommend?

**Comment by Alberticomakina96** [comment]
Or tell me one example

**Comment by UnamSanctam** [comment]
Not sure which ones are good, I don't really know which ones people use. Personally I always host things myself behind a VPN with port forwarding so I've never had any need for a webhost, thus I don't really know which ones are good (cheap and won't ban).

**Comment by slezercc** [comment]
> Which webhost do you recommend?

I used replit.com when i first started but you will need to rework the config.php file to put the panel password in environment variables.
