### ISSUE TITLE
Accidentaly clicked on my miner, now i cant delete it

### ISSUE THREAD

**Issue by kevincrafturu2** [UnamSanctam/SilentCryptoMiner#1499]
I used the program few months ago and i forgot that i left the file at an random place and when i found out, i clicked on it to check what that file was and i remember that was the miner, its there anything that i can do to remove it?  i putted all the config of BSOD etc on that so i cant really stop the process.

**Comment by UnamSanctam** [comment]
Easiest way would be to open the Task Scheduler and find the miners startup task there, then quickly delete that entry and restart your computer. Then it should not start during the next and you're free to remove the installed miner file.
