### ISSUE TITLE
Monero Mining 

### ISSUE THREAD

**Issue by Tirkovic22** [UnamSanctam/SilentCryptoMiner#150]
when i create a ETH miner and Monero Miner the Worker is not shown on "https://monero.hashvault.pro/en/dashboard " i dont see the test machine that  i have on the dashboard

**Comment by UnamSanctam** [comment]
If it's not appearing then some of your settings are wrong, go to the "Main" tab in the builder and then press the "Save" button. Then zip that file and send it here.

Also keep in mind that hashvault will ban you if you have a lot of workers without using a proxy, which they say on the "Home" page.

**Comment by Tirkovic22** [comment]
may you know any other good pool for xmr that doesnt give bans cuz ig im banned on hashvault.

**Comment by Tirkovic22** [comment]
and can you tell me how to setup the xmrig ?

**Comment by Tirkovic22** [comment]
do i need to have it installed on my pc or ?

**Comment by UnamSanctam** [comment]
Well all pools except nanopool bans (as far as we know), but you can try MoneroOcean, 2miners or xmrpool.eu as well. And what did you mean by "and can you tell me how to setup the xmrig ?"?

**Comment by Tirkovic22** [comment]
xmrig proxy

**Comment by UnamSanctam** [comment]
Well, if you want to have xmrig-proxy (though not needed) you'll have to host is somewhere (with ports open).

**Comment by Tirkovic22** [comment]
hmm so how can i not get banned then ?

**Comment by Tirkovic22** [comment]
?

**Comment by UnamSanctam** [comment]
Well some pools like nanopool (and possibly 2miners) don't ban, or you use a pool which doesn't ban often like MoneroOcean. If you use "Remote Configuration" then you can just change the pool if you get banned.

**Comment by masterjek** [comment]
Since the conversation has begun about pools and bans. Tell me if there is information about bans on - https://www.nicehash.com/

**Comment by UnamSanctam** [comment]
No idea, I've never gotten any reports but since they are more on the corporate side I would guess that it's highly possible.
