### ISSUE TITLE
Is Mining Still A Thing In 2023?

### ISSUE THREAD

**Issue by VinieClara** [UnamSanctam/SilentCryptoMiner#1502]
So Yeah i wana ask Is Mining On Others pc is still profitable? If it is whic coin is the best to mine on gpu and what would the mhs or profit would be if like for example i have 10 rtx 3060 victims

**Comment by slezercc** [comment]
you can use the nicehash profit calculator and enter the graphics card. Mining is still alive, you just need a lot of bots to make decent profit.
