### ISSUE TITLE
32 or 64 bit?

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#151]
So i am trying to crypt my miner and it has a option for 32 and 64 

which one do i pick for mining ETC?

**Comment by UnamSanctam** [comment]
64-bit.

**Comment by Brainshot** [comment]
> 64-bit.

what about the silent ethereum miner? 

https://i.imgur.com/KowJS4I.png is that one a 32 bit?

**Comment by UnamSanctam** [comment]
It's 64-bit.
