### ISSUE TITLE
Error Build

### ISSUE THREAD

**Issue by sakaren** [UnamSanctam/SilentCryptoMiner#1515]
if the directory name is not in English, there will be an error Compiling
![image](https://user-images.githubusercontent.com/129770899/229550099-f2cfaeae-3c7c-4c95-bc54-63e43feefd7c.png)

**Comment by UnamSanctam** [comment]
Yes that's a limitation within the compilers (which has been well known for many many years) but there should be an error informing you about that limitation when you try to compile into a non-ASCII folder, so weird that that didn't appear. But just build them in a folder path that's only in ASCII (latin) characters or numbers and it should work.
