### ISSUE TITLE
zergpool password

### ISSUE THREAD

**Issue by Amittere1** [UnamSanctam/SilentCryptoMiner#1516]
![image](https://user-images.githubusercontent.com/109173080/229556237-a9739122-0794-4884-be78-5dd95b3a4a51.png)
Hello again Unam, I just switched to zergpool is the password field normally looking like this?
Also here are my settings
```
{
    "algo": "gr",
    "pool": "ghostrider.mine.zergpool.com",
    "port": 15354,
    "wallet": "(WALLET)",
    "password": "c=BTC,mc=BBC/BTRM/FITA/GSPC/JGC/RTM/YERB,ID=Worker",
    "nicehash": false,
    "ssltls": true
}
```

**Comment by UnamSanctam** [comment]
Yes that's how the password can look like for zergpool, the payout coin, the mining coins and the worker ID.

**Comment by Amittere1** [comment]
Thanks, will this make more than mining xmr?

**Comment by UnamSanctam** [comment]
It can potentially make more, it's very hard to compare easily and there aren't really any lists in order to do it automatically.
