### ISSUE TITLE
install rootkit

### ISSUE THREAD

**Issue by 1aminov** [UnamSanctam/SilentCryptoMiner#152]
Should I enable this feature?

**Comment by 1aminov** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
If you want to, the feature is experimental and if you do enable it I recommend disabling the watchdog since people have had issues on some computers.

**Comment by 1aminov** [comment]
thanks for the answer

I have one more question, for a remote eth configuration I also need to put a `sign between the wallet address?

**Comment by UnamSanctam** [comment]
Depends, it will URL encode everything between the ` so if it's just the wallet address and nothing more then no.

**Comment by 1aminov** [comment]
@UnamSanctam and if the wallet address and worker name do you need to put it?

**Comment by UnamSanctam** [comment]
Only if you need the worker name encoded into the wallet address field (such as the worker name and password combination for nanopool).
