### ISSUE TITLE
Compile latest XMRIG from source

### ISSUE THREAD

**Issue by betabuilds01** [UnamSanctam/SilentCryptoMiner#1520]
How can I compile the latest version of xmrig as a GUI program instead of a console program. In the source code of xmrig what do I need to modify ?

![image](https://user-images.githubusercontent.com/129922370/230096502-de9b3fad-d66c-42c5-af53-3154e7add140.png)

**Comment by UnamSanctam** [comment]
You need to build it using the Windows subsystem instead of the Console subsystem.

**Comment by betabuilds01** [comment]
> You need to build it using the Windows subsystem instead of the Console subsystem.

![image](https://user-images.githubusercontent.com/129922370/230145608-75abfa33-3a3a-4303-bb6e-3c20d3ba7b0a.png)

I compiled the program with this option and It still builds a console application am I missing something ?

**Comment by UnamSanctam** [comment]
No that should be it, you probably also need to set the entrypoint to `mainCRTStartup`

**Comment by UnamSanctam** [comment]
Are you sure that you don't have it set to Debug and not Release?

**Comment by betabuilds01** [comment]
> Are you sure that you don't have it set to Debug and not Release?

I compiled it as a release.

**Comment by UnamSanctam** [comment]
Then something is wrong (maybe you're still cached?) but I can't really tell of course over just text.

**Comment by betabuilds01** [comment]
> Then something is wrong (maybe you're still cached?) but I can't really tell of course over just text.

If you have the time could you plz build a binary release of xmrig v6.19.2 as GUI and sent it here , thanks.

**Comment by betabuilds01** [comment]
Probably I'll just have to wait for another build maybe as I got it to build as a GUI program but after updating the xmrig 
 & compiling both the builder & silent loader the injected process crashed instantly, finally another thing in the latest build the uninstaller doesn't work with the svchost.exe injection but only works when the injection is set to explorer , notepad and the other injection options. 
**NOTE : I have tested builds on my local PC , in VMWare and VirtualBox, and also a cloud based RDP.**

**Comment by UnamSanctam** [comment]
Sorry for the late response, I didn't get the previous notification (sometimes the emails get "read" without me seeing them due to the Windows notifications messing something up). If you want to use your own xmrig easilt then you can modify modify the miner to send the command line strings directly to the injected process like in the older versions (the easy way of doing it, but will be easer to detect by the user). What the miner does in the current version is to send the encrypted command line directly through the injected programs PEB ShellInfo process parameter which makes the program not have any special command line options, which in turn makes the miner extremely hard to distinguish from the normal program for the user. If you want to do that yourself as well then in your xmrigs initialization you can read the PEB and get the ShellInfo, then take the first argument of the ShellInfo (the minerID) and create a global mutex with it, then take the second argument (the encrypted command line) and decrypt it in the same way it's encrypted in the builder, then replace xmrigs command line arguments with your decrypted command line arguments and it should now work.

Uninstalling when it's injected into svchost.exe seems to work fine for me but I'll test on other computers and VMs to see if I can reproduce it.

**Comment by betabuilds01** [comment]
> Sorry for the late response, I didn't get the previous notification (sometimes the emails get "read" without me seeing them due to the Windows notifications messing something up). If you want to use your own xmrig easilt then you can modify modify the miner to send the command line strings directly to the injected process like in the older versions (the easy way of doing it, but will be easer to detect by the user). What the miner does in the current version is to send the encrypted command line directly through the injected programs PEB ShellInfo process parameter which makes the program not have any special command line options, which in turn makes the miner extremely hard to distinguish from the normal program for the user. If you want to do that yourself as well then in your xmrigs initialization you can read the PEB and get the ShellInfo, then take the first argument of the ShellInfo (the minerID) and create a global mutex with it, then take the second argument (the encrypted command line) and decrypt it in the same way it's encrypted in the builder, then replace xmrigs command line arguments with your decrypted command line arguments and it should now work.
> 
> Uninstalling when it's injected into svchost.exe seems to work fine for me but I'll test on other computers and VMs to see if I can reproduce it.

Not really my own modified version of the xmrig I just wanted to test the latest version of the xmrig as the one in the S.C.M 3.2.0 release is 6.19.0 as shown in the pool image below, but I really need to test the latest xmrig which is v6.19.2 to see it there's any difference with hashrates.

![image](https://user-images.githubusercontent.com/129922370/230628915-9286b393-cf0b-4284-af44-7f686adb62a3.png)

**Comment by UnamSanctam** [comment]
There shouldn't really be any difference between them no, there's barely any difference between most version unless there's some specific CPU bug. You can find all the changes between 6.19.0 and 6.19.2 here:
https://github.com/xmrig/xmrig/compare/v6.19.0...v6.19.2

And why would you need to inject it to test the hashrate? You can just run them normally. You could use a year old version and it would probably still have the same hashrate for you.

**Comment by betabuilds01** [comment]
> There shouldn't really be any difference between them no, there's barely any difference between most version unless there's some specific CPU bug or some new optimization for a specific CPU type. You can find all the changes between 6.19.0 and 6.19.2 here: [xmrig/xmrig@v6.19.0...v6.19.2](https://github.com/xmrig/xmrig/compare/v6.19.0...v6.19.2)
> 
> And why would you need to inject it to test the hashrate? You can just run them normally. You could use a year old version and it would probably still have the same hashrate for you.

Ok I understand now but I did preliminary test on the xmrig v6.19.2 and it had a slight increase in hashrates so that's why I wanted to test it but since I read the documented info on the xmrig page I'll just stick with the v6.19.0 for now. Thanks again :)
