### ISSUE TITLE
P2Pool

### ISSUE THREAD

**Issue by Alberticomakina96** [UnamSanctam/SilentCryptoMiner#1521]
Hello, how can I mine on P2Pool without reveal my public IP address?

**Comment by UnamSanctam** [comment]
When mining to P2Pool you mine to your own node, do you mean that you want to avoid exposing your node IP to the Monero network? That shouldn't really be a problem. Or do you mean exposing the IP for all the client that will be connecting to your computer (node)? In that case you would need to host it behind something like a VPN (with port forwarding probably) or host it on some sort of VPS.

**Comment by Alberticomakina96** [comment]
Okay thanks
