### ISSUE TITLE
error compilling it has a space 

### ISSUE THREAD

**Issue by lolbodoo** [UnamSanctam/SilentCryptoMiner#1522]
![image](https://user-images.githubusercontent.com/126403185/230200810-f05d209f-14c7-4f37-87ab-b3b7133fe449.png)
 
 
 
 idk why its not working when i try to compile
i tried on my dexkstop and even in my file

**Comment by UnamSanctam** [comment]
Your username has a space in it as you can see, compile it somewhere outside your user folder.

**Comment by lolbodoo** [comment]
oohhh thank you

**Comment by lolbodoo** [comment]
and how do i change my user folder name cause i cant it wont let me

**Comment by UnamSanctam** [comment]
You can try building it directly on the C: drive to make it easy. Go to your C: drive and create a new folder called something like Build, then start the builder as administrator and then build the miner inside that folder.
