### ISSUE TITLE
Can't crypt miner payload :v

### ISSUE THREAD

**Issue by pepe123456789-cmyk** [UnamSanctam/SilentCryptoMiner#1526]
Before I explain my issue I just want to say thank you Unam for making such an awesome miner for free :)
I love the latest version, especially the persistance and watchdog; they are on point even better than pureminer which cost like 200$ Thank you good sir :)
Now here is my issue: 
I can't seem to actually crypt the miner payload; I have tried with 2 different crypter providers (.bat output) and nothing; someone once told me that there was some crypting already involved in the miner payload itself; maybe that's why I can't seem to crypt it right? How could I make the miner payload be generated without any type of integrated crypter? That's way I would be able to crypt it with no problem; I think the integrated crypter in the miner payload is preventing me from crypting it with a private stub crypter. What would be your suggestion to fixing this issue mr Unam? 
And just for reference the crypter was able to crypt other hidden miners like pure but not unams; even though yours is way better by miles.

Thanks you in advance :)

**Comment by UnamSanctam** [comment]
There was a "Pause for Obfuscation" back in earlier versions when the miner was made in C#, but since the miner is in C++ now there's no such option. The miner does not perform any crypting by itself now (since the miner is public the crypt would get detected quickly and thus wouldn't help much) so it should work with any crypters just fine.

**Comment by UnamSanctam** [comment]
>I am facing the same issue sir .... i am unable to fud the exe file .... the crypter is incompetable with the miner ...... do you suggest any crypter ??? .... is purecrypter good for the exe ???

As long as it supports 64-bit it should work fine, and also of course make sure to use the crypters "Startup" instead of the miners (unless in some cases where the crypter supports self-injection, then the miner "Startup" could be used instead).

**Comment by floof989763** [comment]
Any crypter that would suggest for me ???

**Comment by floof989763** [comment]
I have been using jy's crypter, jy himself said that its not compitable .... his crypter is 64 bit native

**Comment by floof989763** [comment]
????

**Comment by UnamSanctam** [comment]
>Any crypter that would suggest for me ???
>I have been using jy's crypter, jy himself said that its not compitable .... his crypter is 64 bit native

Not sure which ones are good or working since I don't regularly buy crypters for testing, as long as the crypter is 64-bit native then it should theoretically work fine, unless the crypter does something special which breaks something. I don't know anything specific about that crypter. When crypting did you make sure to turn of "Startup" inside the miner and enable it inside the crypter?

**Comment by floof989763** [comment]
Hello sir..... some one i know is selling me a crypter of which we can change the encryption key anytime we want ..... he claims that whenever the stub is detected .... you can just simply change the encryption key and crypt it ..... which will make the file fud again ..... is that true sir ???

**Comment by floof989763** [comment]
![IMG_20230418_080152_549](https://user-images.githubusercontent.com/120167143/232712692-cc240c53-9ac3-4468-a271-525edc6a22a7.jpg)

**Comment by floof989763** [comment]
He also shared this image of his crypter

**Comment by floof989763** [comment]
Please respond to me sir

**Comment by UnamSanctam** [comment]
I don't know whether that's true or not, I guess theoretically it could be though usually it's not that simple.

**Comment by floof989763** [comment]
Okay okay thank you soo much sir
