### ISSUE TITLE
Miner working but connected to pool but not minning despite 10 minutes passing

### ISSUE THREAD

**Issue by SawyerHere** [UnamSanctam/SilentCryptoMiner#1527]
Ive made multiple miners and used the checker too to make sure they're running but for some reason whenever I check the pools they are visible but doing anything, I even made a new exe with stealth off but still nothing
![image1231231113212312311312](https://user-images.githubusercontent.com/129390324/230501477-6c4d61f7-5fc1-4068-b488-3a5a32f6275b.png)
![123123142123523122](https://user-images.githubusercontent.com/129390324/230501482-963ab522-c610-4ac3-aae6-83c912d37da1.png)

**Comment by UnamSanctam** [comment]
That's the wrong port, the nanopool XMR non-SSL port is `14444`

**Comment by SawyerHere** [comment]
Thank you for responding quickly!, I did use the 14444 port with everything else being the same and still I haven't seen anything on the hashrate 
![ImageChecker](https://user-images.githubusercontent.com/129390324/230505045-7a98e0dc-a582-4f62-9616-426446b7f27e.png)
![ImageEUROpool](https://user-images.githubusercontent.com/129390324/230505050-68db24f0-b051-4a3e-b0ad-bbea0c446cca.png)

**Comment by UnamSanctam** [comment]
That doesn't look like nanopool, are you sure that's correct?

**Comment by SawyerHere** [comment]
God bless your soul for tolerating my dumbass, I genuinely appreciate your quick and tolerance since I'm new to all of this so keep up the good work :))

**Comment by SawyerHere** [comment]
I hate to re-open this and bother you once more, it worked initially but I tried it again with the same file and i cant help but notice its not working and not being able to figure out whats going on
![Lasttrychecker](https://user-images.githubusercontent.com/129390324/230520365-52df18eb-b20c-4b0c-b84b-70e81906a92d.png)

**Comment by UnamSanctam** [comment]
If you check the Task Manager then is it using any CPU and RAM? How much free RAM does the computer have and how many cores does the CPU have? And also for how long have you been mining?

**Comment by SawyerHere** [comment]
The laptop im testing it on has 4 cores and 8gigs of ram, The initial testing was on a vmware had 2 processors and 2 gigs of ram, they have been on that laptop for a good 20 minutes now

**Comment by UnamSanctam** [comment]
Is it using CPU? If it is then the miner is working, since nanopool has a share difficulty of 400 000 then it can take some time to find a share depending on your hashrate, nanopool can also be slow at refreshing the statistics.

**Comment by SawyerHere** [comment]
It shows the CPU and ram being used, Im booting up the VM and launching one of the old EXEs on there to see if it works, also its been now another 10 minutes since I started waiting as soon as you replied and nothing, ill also try to uninstall and reinstall the exes on the laptop as i work on the vm and see what happens

**Comment by UnamSanctam** [comment]
I'm not sure what your hashrate is but let's say it's 200 H/s (since you're using 20%, depends on the specific CPU) and since nanopool has a 400 000 share difficulty then the average time to find a share would be 400 000/200=2 000 seconds.

**Comment by SawyerHere** [comment]
The thing is even the ones on vmware arent even showing up now so could it really be the hashrate?, I dont think its even showing up in the pool i think, im not sure ill keep poking around and re-reading the wiki for abit as i wait for everything

**Comment by UnamSanctam** [comment]
I can see it in the pool now, looks like it found a share.

**Comment by SawyerHere** [comment]
Really? for me the hashrates just 0% percent and nothing going on for the longest time

**Comment by UnamSanctam** [comment]
It has found shares: https://xmr.nanopool.org/account/48A5VUEf7yL4D7jrBaNokvHYdFb8ux84i5bUGWLXD8U9gzDRctF17bQBQ3UKvq69tgRxq6kYKbust2rwWwxTUtEMSMjbKeu. The pool will only show "hashrate" whenever it finds a share due to how pools calculate hashrate (more information here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-the-hashrate-shown-on-the-pool-different-from-what-i-expect-or-from-what-is-shown-in-the-web-panel). Technically what you should do to get an accurate hashrate on the pool side is to mine for 6 hours and then check the "Average Hashrate for last 6 hours" field.

**Comment by SawyerHere** [comment]
I see well just to make sure I understood correctly, the pool name with port is inserted as follows: pool.hashvault.pro:443 with 443 being the port and TLS enabled, pass is for the worker name and thats it sorta? I tried to do it once more on monero hashvault and yeah it worked!
![image](https://user-images.githubusercontent.com/129390324/230610436-567bcea5-6a4f-4e84-a0d3-811966f89c97.png)

the worker name "workerhere" was on port 443 while the other X workers where on port 80 and if I understood the X workers show up because they have successfully mined and submitted shares to the pool and for  the workerhere the accurate hashrate readings it should be using 6 hour intervals and ofc once they submit something to the pool

is there anything I got wrong?

**Comment by UnamSanctam** [comment]
That is correct, and since hashvault has very fast statistics and low share difficulties the statistics gets updates really quickly , bute also since you're using hashvault remember that according to their rules you cannot have too many miners without having your own xmrig-proxy server to proxy the miners through.

<img src="https://user-images.githubusercontent.com/10323655/230620983-a493481f-9343-4ab0-8dbb-b0c29e612f86.png">

**Comment by SawyerHere** [comment]
Hmmm I might try that then and check if everything still works, I'm not sure if Ill have alot of miners although it wouldn't be a bad thing to check, ill try that. again thank you so much for tolerating me
