### ISSUE TITLE
add oxen

### ISSUE THREAD

**Issue by 5hgdn83fbd5hgddf3fbd5hgdn83fbd5h6dn83fb** [UnamSanctam/SilentCryptoMiner#1528]
a fork of monero, that contributes to a based network better than tor by mining.

**Comment by UnamSanctam** [comment]
Isn't Oxen a PoS (staking) project now rather than a PoW (mining) project, how would it be mined?

**Comment by 5hgdn83fbd5hgddf3fbd5hgdn83fbd5h6dn83fb** [comment]
> Isn't Oxen a PoS (staking) project now rather than a PoW (mining) project, how would it be mined?

it used to be PoS, it is now PoW

**Comment by UnamSanctam** [comment]
Are you sure? Can you link it?

**Comment by 5hgdn83fbd5hgddf3fbd5hgdn83fbd5h6dn83fb** [comment]
> Are you sure? Can you link it?

https://www.marketbeat.com/cryptocurrencies/oxen/
https://github.com/oxen-io/oxen-core
https://oxen.io/
https://www.bing.com/search?q=is+oxen+proof+of+work&cvid=bc7f30b935dc473c8666922107b48f9a&aqs=edge..69i57.12487j0j9&FORM=ANAB01&PC=U531

**Comment by UnamSanctam** [comment]
On the official  website it only talks about staking and not about mining. But if MarketBeat (CryptoCOmpare) is correct in that it uses the CryptoNight-Heavy algorithm then you can already mine it using the miner.

**Comment by 5hgdn83fbd5hgddf3fbd5hgdn83fbd5h6dn83fb** [comment]
> On the official website it only talks about staking and not about mining. But if MarketBeat (CryptoCompare) is correct in that it uses the CryptoNight-Heavy algorithm then you can already mine it using the miner.

is it worth mining over monero?

**Comment by UnamSanctam** [comment]
No idea, I can't find any mining calculators or anything at all online so you would have to test it yourself to see what your earnings would be.

**Comment by 5hgdn83fbd5hgddf3fbd5hgdn83fbd5h6dn83fb** [comment]
> On the official website it only talks about staking and not about mining. But if MarketBeat (CryptoCompare) is correct in that it uses the CryptoNight-Heavy algorithm then you can already mine it using the miner.

so your miner? theres multiple entry's which should i choose (for that algo)? or is it not possible

**Comment by UnamSanctam** [comment]
Does not matter, any of them that says `cn-heavy/0` will work (unless it's using some variation but then you'll have to find out which one it uses), the coins listed are just examples for the algorithm.

**Comment by 5hgdn83fbd5hgddf3fbd5hgdn83fbd5h6dn83fb** [comment]
also whats critical process, and process killer? didnt see them on the wiki, sorry for so many questions

**Comment by UnamSanctam** [comment]
You can find them here:
https://github.com/UnamSanctam/SilentCryptoMiner/wiki#critical-processes-bsod
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#kill-targets

The Critical Processes option will mark the programs as critical to the system, which means that the computer will BSoD if they are killed. The Process Killer feature is there in case you want it to specifically kill any programs when they are started.

**Comment by 5hgdn83fbd5hgddf3fbd5hgdn83fbd5h6dn83fb** [comment]
thank you

**Comment by 5hgdn83fbd5hgddf3fbd5hgdn83fbd5h6dn83fb** [comment]
> You can find them here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#critical-processes-bsod https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#kill-targets
> 
> The Critical Processes option will mark the programs as critical to the system, which means that the computer will BSoD if they are killed. The Process Killer feature is there in case you want it to specifically kill any programs when they are started.

do you think i should go for the highest starting difficulty on monero if i intend on infecting thousands of pc's?

**Comment by UnamSanctam** [comment]
>do you think i should go for the highest starting difficulty on monero if i intend on infecting thousands of pc's?

If you're going to use your own xmrig-proxy then yes, if you're going to connect to the pool directly from the miners then no since the difficulty applies individually to every miner.

**Comment by 5hgdn83fbd5hgddf3fbd5hgdn83fbd5h6dn83fb** [comment]
> > do you think i should go for the highest starting difficulty on monero if i intend on infecting thousands of pc's?
> 
> If you're going to use your own xmrig-proxy then yes, if you're going to connect to the pool directly from the miners then no since the difficulty applies individually to every miner.

do i need to actually host the proxy or are there ones available?

**Comment by UnamSanctam** [comment]
>do i need to actually host the proxy or are there ones available?

If you want an xmrig-proxy then you would need to host it yourself yes, most people just mine directly to the pool though.

**Comment by 5hgdn83fbd5hgddf3fbd5hgdn83fbd5h6dn83fb** [comment]
> 

40% non idle, 80% idle? or could i get away with 90% or 100% idle?

**Comment by UnamSanctam** [comment]
>40% non idle, 80% idle? or could i get away with 90% or 100% idle?

40%-80% is fine, 90%-100% could cause some problems for the user most likely but the biggest potential issue would be that the fans might make a lot of sound at that level due to the heat.
