### ISSUE TITLE
term :/

### ISSUE THREAD

**Issue by KratosMiner** [UnamSanctam/SilentCryptoMiner#153]
Any telegram or other account ?
Is kratos

**Comment by UnamSanctam** [comment]
No I don't have any other yet, not sure what service to use.

**Comment by KratosMiner** [comment]
Telegram bro

**Comment by UnamSanctam** [comment]
Well I'd have to buy some number then.

**Comment by KratosMiner** [comment]
You got a account ?

**Comment by Dex0xm** [comment]
Use **Session**

**Comment by KratosMiner** [comment]
> Use **Session**

not a lot use :/ telegram more "universal"

**Comment by Dex0xm** [comment]
Telegram isn't open-source

**Comment by Dex0xm** [comment]
and requires phone number

**Comment by UnamSanctam** [comment]
Yeah I haven't found a reliable (and cheap enough) phone number yet, since you need a fully private number unless you want your account stolen.

**Comment by Dex0xm** [comment]
@UnamSanctam  you can try **phoner** it's an android app which provides cheap phone numbers when I say cheap I mean it 
you can get a phone number for like 2 years and it will only cost you 50$

**Comment by grandepremo** [comment]
@KratosMiner how can i contact with you?

**Comment by KratosMiner** [comment]
> @KratosMiner how can i contact with you?

Telegram @KratosDev

**Comment by KratosMiner** [comment]
@UnamSanctam send 60 to your ltc

**Comment by UnamSanctam** [comment]
I have a Telegram now at @UnamSanctam.

**Comment by KratosMiner** [comment]
> I have a Telegram now at @UnamSanctam.

I am back :) check your telegram

**Comment by UnamSanctam** [comment]
> > I have a Telegram now at @UnamSanctam.
> 
> I am back :) check your telegram

Right now I can't access it, the hard drive I had the Virtual Machines on died so I've had to order new ones. Though those new ones haven't arrived yet even though its been quite some time.
