### ISSUE TITLE
StartUp have problem 

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1532]
in some pcs when they restart or just spend days online the miner become not in task manager anymore even totally the pc is not have any kind of antivirus but keep rediler turn off it self how i can avoid this prroblem even try test checker when disappear like not installing

**Comment by UnamSanctam** [comment]
Is the Task Scheduler task still there? And have you disabled Windows Updates? Since some updates run MSRT (Windows Malicious Software Removal Tool) on the computer which could remove it.

**Comment by tarekxxx** [comment]
but was do like this in old version i know when get updater.exe deleted i know this from antivirus and dll also but in this case dll keept in appdata and also the exe

**Comment by UnamSanctam** [comment]
You mean that the updater.exe didn't get removed in this update but it did before? If so then it just be because the new version is better than the old one. Is it just the Task Scheduler Task that was removed for you then?

**Comment by tarekxxx** [comment]
no not removed but sometimes the problem get killed automaticly or something happen in program get killed then i back run it again on machine like this one
![Uploading Capt4ure.PNG…]()

**Comment by UnamSanctam** [comment]
Hmm then something is killing it most likely (since you say you can't see it in the checker then it's not "Stealth"), if the miner is somehow getting killed then the watchdog should start it again. Do you have the watchdog enabled? Is the watchdog getting killed as well? If so then there should be some program doing it since that's the only way that would happen really.

**Comment by tarekxxx** [comment]
yea its enabled same version i install in many pc and they restart and working fine and some of them do the same keep killed and i keep check process if dialer is working or not

**Comment by UnamSanctam** [comment]
Does it happen without the rootkit?

**Comment by tarekxxx** [comment]
i didint try yet but i will try then tell you

**Comment by tarekxxx** [comment]
in fact when stop there only one dialer in default there 2 dialer but in my case i see only 1 dialer its working totally but i dont know only one dialer i see i
![Uploading Ca5pture.PNG…]()
n task manager

**Comment by tarekxxx** [comment]
i move to older version much better then this one keep turn off and crash itself

**Comment by jamiekarvans** [comment]
> i move to older version much better then this one keep turn off and crash itself

to which version you have moved?

**Comment by tarekxxx** [comment]
3.1.0 much stable then this version

**Comment by tarekxxx** [comment]
when use proxy its bypass it how i can do it staticly from computer it self ? if there possible ?
