### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by gif12** [UnamSanctam/SilentCryptoMiner#1537]
`miner : `RTM
`user : `RCQAijerjwhj45b9EWygAUXULCUeYaSQEZm/m001
`pool :` stratum+ssl://rtm-stratum.pukkapool.com:3053

`pass : `xx

NOT work miner ! 
can you help me? 
We run it and it stops immediately without any error

**Comment by UnamSanctam** [comment]
Remove `stratum+ssl://`

**Comment by gif12** [comment]
> Remove `stratum+ssl://`

OK
Can you put the user as below?
`   RCQAihBrNuWGdb9EWygAukXULCUeYaSQEZm.m001  `

**Comment by gif12** [comment]
Chuk suggested the extraction of this model

**Comment by UnamSanctam** [comment]
You're trying to connect to the SSL port of the pool but you have SSL/TLS turned off inside the miner, so either enable SSL/TLS or use the non-SSL port `3052`. Personally I am not able to connect to that pool at all (not with the normal xmrig either) so I cannot test whether it works or not.

**Comment by gif12** [comment]
Again could not connect to the pool
Or make a change in the amount of cpu consumption...
It is not even displayed in the list of running programs?!
The
I think it is obvious from the pool
Do you know a better pool that you have tested for RTM currency?

**Comment by UnamSanctam** [comment]
You can try flockpool, it's the biggest RTM pool and I know that it should work.

**Comment by gif12** [comment]
I usually use your programs and have never seen any problems...

It didn't work again.

If we do not choose an icon for the program when creating the miner, will the icon of your program be placed on it by default?
If so, we must say that even the default symbol is not placed on it!
In this case, we conclude that the problem is with my computer, which did not have the ability to make the program correctly

And is it about 5 MB in size?

Because even when I click on the created program, I don't see it in the list of running programs

**Comment by UnamSanctam** [comment]
No there will be no icon if no icon is chosen. If you just choose the xmrig miner (RTM) and no other miners (like ETC) then the miner should be about 5MB. In the running programs it will show up as svchost.exe because that's what you chose, you can see if it's running by running the checker program that gets built together with your miner. Here are your settings you sent before that I modified for flockpool that works fine for me: [RTM.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/11209849/RTM.zip)

**Comment by gif12** [comment]
tested again
And when I clicked on it, it was shown in the list of programs with the name of the program written below it, and it was closed after 3 seconds.

I am testing it on a vps that I bought from the following website : 
https://apponfly.com
What is the problem ?
Can you send me the `miner RTM` that you made and it worked properly?

**Comment by UnamSanctam** [comment]
Sure here is the built miner: [RTM.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/11211772/RTM.zip). First it will run as RTM.exe for 15 seconds since that's the "Start Delay" that was chosen inside the builder, then after those 15 seconds it will inject the miner into svchost.exe.

**Comment by gif12** [comment]
What is the problem ?

**Comment by gif12** [comment]
It worked and used the cpu for a minute
Must the program injected into it be running?
to work

**Comment by UnamSanctam** [comment]
No it starts a new program for injection, are you saying it stopped using the CPU? Can you take a screenshot?

**Comment by gif12** [comment]
ok
![۲۰۲۳۰۴۱۲_۲۱۴۵۰۸](https://user-images.githubusercontent.com/91024081/231548510-b8ba7d0c-d3fc-4378-a560-9bd4b19bc846.jpg)

**Comment by gif12** [comment]
You can go to the following site to test and better understand the problem and get free vps for one hour

https://app.apponfly.com/trial

Check whether it is connected or not from the link below
https://flockpool.com/miners/rtm/RCQAihBrNuWGdb9EWygAUXULCUeYaSQEZm

**Comment by UnamSanctam** [comment]
I would try installing it instead [RTM-Install.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/11214644/RTM-Install.zip) and see if it makes a difference for you.

**Comment by gif12** [comment]
ok

**Comment by gif12** [comment]
Did it change for you? And did you test through that vps?

**Comment by UnamSanctam** [comment]
Yes it's always working for me, but the reason it might not be working in the VPS is that possibly the VPS might only have a single CPU core (and if so then obviously the miner should use it all). Try it on a normal computer and see if it works for you.

**Comment by UnamSanctam** [comment]
I just changed it to install the miner, I included the settings in the .zip. Could possibly be the case that since the process was a "System" process when installed it got a higher priority. It really depends on the specific CPU to know how much RTM it will mine, you can find the benchmark of some CPUs here: https://mineraptoreum.com/. For 16 core CPUs I believe RTM is more profitable compared to XMR.

**Comment by gif12** [comment]
> I just changed it to install the miner, I included the settings in the .zip. Could possibly be the case that since the process was a "System" process when installed it got a higher priority. It really depends on the specific CPU to know how much RTM it will mine, you can find the benchmark of some CPUs here: https://mineraptoreum.com/. For 16 core CPUs I believe RTM is more profitable compared to XMR.

Have you tested that RTM is more profitable than XMR and through Cpu you can get more profit and income than XMR by mining RTM currency?

**Comment by UnamSanctam** [comment]
>Have you tested that RTM is more profitable than XMR and through Cpu you can get more profit and income than XMR by mining RTM currency?

I believe it depends on the specific CPUs, and since there aren't really many public updated comparisons then my information might also be out-of-date. You would have to find both RTM and XMR benchmarks for a specific CPU, then you would need to use both and RTH and XMR mining calculator, input the hashrates and see which would be more profitable for that CPU.

**Comment by gif12** [comment]
Hi 
can you add EPIC cash(randomX) and other Algo randomX?

**Comment by gif12** [comment]
> Last time I tried adding their specific RandomX variation it made the miner unstable, though I could try again when I get the time. And which other RandomX variation coins are you referring to?

I mention Epic cash because it is the most popular after monero, which uses the RandomX algorithm

And if I understand the problem you mentioned correctly, then you can make a separate miner like Ethereum or Monero miner that you put on your github page? I don't think there will be any problem

Also, usually all Epic currency pools say that instead of putting the payment link in your miner, you should enter the username; password ; and enter the name of the worker

**user or wallet :**
`username_pool.worker_name `

**Comment by gif12** [comment]
> 

I mention Epic cash because it is the most popular after monero, which uses the RandomX algorithm

And if I understand the problem you mentioned correctly, then you can make a separate miner like Ethereum or Monero miner that you put on your github page? I don't think there will be any problem

Also, usually all Epic currency pools say that instead of putting the payment link in your miner, you should enter the username; password ; and enter the name of the worker

**user or wallet :**
`username_pool.worker_name `
