### ISSUE TITLE
Self injection

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#154]
Hey unam i am using a crypter and when binding files it has many injection options

like automatic, vbc, csc, regasm, explorer and finally self

should i use self injection ? 

the crypter has install option aswell could i just use the miners own startup installer and just use self injection

**Comment by UnamSanctam** [comment]
You can try the self-injection and see if it works, if you use any other method then most likely you will need to use the crypters install option (since the miner will be injected and have no idea where it is and thus can't install).

**Comment by Brainshot** [comment]
> You can try the self-injection and see if it works, if you use any other method then most likely you will need to use the crypters install option (since the miner will be injected and have no idea where it is and thus can't install).

So self injection would be the miners own installation ? its own injection i am correct

**Comment by UnamSanctam** [comment]
Yes probably the miners installation, since then the miner would most likely still know where it's located.

**Comment by Brainshot** [comment]
> Yes probably the miners installation, since then the miner would most likely still know where it's located.

there is also a option called "run once" should i enable that aswell or that wouldnt affect the miner? its really hard to test things my VM is very laggy

**Comment by Brainshot** [comment]
"If you enable run once then the file wont run again after you restart your PC"

**Comment by UnamSanctam** [comment]
Uh, that's a pretty ambiguous description of it, it shouldn't really affect the miner I don't think.

**Comment by Brainshot** [comment]
> Uh, that's a pretty ambiguous description of it, it shouldn't really affect the miner I don't think.

lets say i dont enable run once, it wouldnt create too many miners right when the PC is restarted?

**Comment by UnamSanctam** [comment]
No, the miner closes down if it already exists so that shouldn't matter.

**Comment by Brainshot** [comment]
> No, the miner closes down if it already exists so that shouldn't matter.

Alright thank you!

**Comment by Pedrolito666** [comment]
Hi how can I use self injection in the miner I don't find it !

**Comment by UnamSanctam** [comment]
>Hi how can I use self injection in the miner I don't find it !

He's talking about a crypter and not the miner.

**Comment by Pedrolito666** [comment]
Can I disable the injection of miners and use only the crypter one ? Because it seems to don't work with double injections

**Comment by UnamSanctam** [comment]
>Can I disable the injection of miners and use only the crypter one ? Because it seems to don't work with double injections

The miners have to be injected to be able to run and won't be a problem with the crypter injection either since they are for different things. Make sure that you have "Startup" in the builder disabled since you're using a crypter.

**Comment by Pedrolito666** [comment]
Ok thanks it seems to be an issue with my crypter then...
