### ISSUE TITLE
Change remote config algo

### ISSUE THREAD

**Issue by Alberticomakina96** [UnamSanctam/SilentCryptoMiner#1540]
Hello, i have a miner with XMR and ETC options with remote config, how can i replace ETC mining to RYO with cn_gpu algorithm in remote config? I want to mine XMR and RYO.

**Comment by Alberticomakina96** [comment]
Okay and is recommendable to mine RYO or UBQ? Which is more silent in GPU?

**Comment by UnamSanctam** [comment]
Depends on what you want, UBQ (uqbhash) is more memory oriented while cn/gpu is more core oriented. So UBQ would probably be more silent in terms of actual GPU usage and would not require the xmrig CUDA libraries.

**Comment by Alberticomakina96** [comment]
okay thanks
