### ISSUE TITLE
Sentinelone

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1543]
BLocking Traffic not let mining anything there anyway to can bypass it ? when start only sent few packets then drop all again

**Comment by tarekxxx** [comment]
![Screenshot (44)](https://user-images.githubusercontent.com/20240556/231941481-14727aeb-f041-4f5c-ac08-e6d75c3a8b12.png)
have any idea what the problem ?

**Comment by UnamSanctam** [comment]
So something on the computer finds and blocks the connection? Firstly make sure that you're using SSL for the connection if you already are then in that case you would probably need to host your own xmrig and connect it to that to be able to bypass it. Or if you found whatever program is blocking it and add an exception.

**Comment by tarekxxx** [comment]
how host my own xmrig how ? any info ?

**Comment by UnamSanctam** [comment]
First you'll need something to host it on, like a computer or a VPS. Then you download xmrig-proxy and edit the xmrig-proxy config, change the input ports to whatever you want and then add the pool connection. After that you can connect the miners to the proxy using the IP of the computer or VPS that's hosting it and the port selected in the config.

**Comment by tarekxxx** [comment]
with your program ?

**Comment by UnamSanctam** [comment]
xmrig-proxy is found here: https://github.com/xmrig/xmrig-proxy. You'll need a computer or VPS to host the proxy for the miners to connect to.

**Comment by tarekxxx** [comment]
there any guide sir i can understand from any resources ? First time i hear i can host XMRIG proxy

**Comment by UnamSanctam** [comment]
I don't know if there are any guides, xmrig-proxy itself is quite simple.
It acts a proxy between the miners and the pool.
Normally it would be like this:
`Miner <-> Pool`
While with xmrig-proxy it will be like this:
`Miner <-> Proxy <-> Pool`
So the miners will only ever connect to the proxy and then the proxy will connect to the pool, the proxy then gives the miners the jobs that the pool gives the proxy. Setting up xmrig-proxy requires you to download the program, edit the config and then just start it. Since the proxy is the one communicating with the pool then that means that to change the pool connection settings you only have to change it inside the proxy and not in the miners.

**Comment by tarekxxx** [comment]
so i can include this one to your software ? or it normal XMR it will be appear ?

**Comment by UnamSanctam** [comment]
You host the xmrig-proxy somewhere, then in my miner you just enter the proxy IP and port as the pool. That's all you have to do.

**Comment by tarekxxx** [comment]
can give me example when i setup the xmrig-proxy so how it will intract with command in your program ?
like my ip is 127.0.0.1:5555 port  then the pool is moneroocean.stream

**Comment by UnamSanctam** [comment]
Then in the miner you would input `127.0.0.1:5555` as the pool URL, and in the proxy you would add the MoneroOcean pool under the "pools" section in the config.

**Comment by tarekxxx** [comment]
so i can do it with example ngrok to test it before move to VPS ? and see if it work or nah ?

**Comment by tarekxxx** [comment]
ohh xmrig proxy its set like server ohh i was thinking wrong totally i will try this sir thanks so much and also i have to move all my miner to this proxy ? or just this one who not working ?

**Comment by UnamSanctam** [comment]
You can move either just the one that's not working or all of them, it depends on what you want to do.

**Comment by tarekxxx** [comment]
i can do it with http ?

},
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 3333,
            "tls": false
        },
        {
            "host": "::",
            "port": 3333,
            "tls": false
        }
    ],
    i see http

**Comment by UnamSanctam** [comment]
The http is just if you want to connect some sort of xmrig-proxy website to the program I believe.

**Comment by tarekxxx** [comment]
thanks bro you the best
