### ISSUE TITLE
Make the unam site api thing support onion site connectivity?

### ISSUE THREAD

**Issue by FU3X** [UnamSanctam/SilentCryptoMiner#1546]
to remain hidden

**Comment by UnamSanctam** [comment]
Would be quite difficult since then the miner would have to install a Tor proxy onto the computer.

**Comment by UnamSanctam** [comment]
Not as far as I know or can find at least, the libraries are usually just socks5 libraries that interact with an installed Tor proxy.

**Comment by GitHubUser5672** [comment]
You can run clearnet sites over tor, the only difference is that they are centralized (and could be taken down by the hosting provider), but the anonymity still applies.
