### ISSUE TITLE
Hello, may I ask what is the donation proportion of the generated Xmrig?

### ISSUE THREAD

**Issue by nonomoney** [UnamSanctam/SilentCryptoMiner#1547]
Hello, may I ask what is the donation proportion of the generated Xmrig?

**Comment by UnamSanctam** [comment]
It should be set to 0% by default, though it can also be set by adding `--donate-level=N` inside the "Advanced Parameters" option.

<img src="https://user-images.githubusercontent.com/10323655/233060565-801ba385-d241-40f7-92e3-aaeb1536d8ca.png">

**Comment by possessed-client** [comment]
> It should be set to 0% by default, though it can also be set by adding `--donate-level=N` inside the "Advanced Parameters" option.
> 
> ![](https://user-images.githubusercontent.com/10323655/233060565-801ba385-d241-40f7-92e3-aaeb1536d8ca.png)

You mean to say you're doing all this coding and answering mostly trivial questions for fun? Or that the cohort of questionable morals interested in this repository (me included :D) voluntarily donate enough to you? The miner itself is closed-source, you must be monetising this somehow. How?

**Comment by UnamSanctam** [comment]
>You mean to say you're doing all this coding and answering mostly trivial questions for fun? Or that the cohort of questionable morals interested in this repository (me included :D) voluntarily donate enough to you? The miner itself is closed-source, you must be monetising this somehow. How?

Yes the miner is mostly a hobby project, just like UnamBinder, UnamDownloader (though haven't had time to update them yet) or others projects when they ask for help, which I work on to get away from real-life work. Which is also why updates can take some time and also why I can't always answer issues fast (used to be able to answer faster before when I had less work). I used to have it set to 1% like the default xmrig has (this was way back in the days of SilentXMRMiner) but my domain that I had the donation proxy on was taken down and since then it's been at 0%. I never really expected the miner to get as big as it is.

**Comment by NeGoblin1** [comment]
UNSANCTAM,  then why not open the code? Without negativity, it's just interesting to know the answer. And I'm still grateful to you for your work

**Comment by UnamSanctam** [comment]
>UNSANCTAM, then why not open the code? Without negativity, it's just interesting to know the answer. And I'm still grateful to you for your work

Well I don't really have the time to maintain them, in a day I usually work around 12-16 hours and then I respond to issues/emails and work on the hobby projects (such as the miner) for around 1-4 hours, so in the end it's hard to fit in more time for both xmrig and ethminer. Last time (around 2-3 years back during the time of SilentXMRMiner/SilentETHMiner) when I was helping people with the miner (compiling the source) then I was maybe spending 2-6 hours a day just responding to and guiding people on how to do it and I don't have time for it in the current schedule. I could release it without any support offered at all but I really do not like doing so (and people would still ask anyways, so I would have to ignore and decline helping), and if the hobby results in negative feelings then the hobby probably wouldn't be worth it. I already feel bad enough about not having enough time to finish the UnamBinder and UnamDownloader updates.
