### ISSUE TITLE
Injection detection, Avast/AVG and crypting questions

### ISSUE THREAD

**Issue by possessed-client** [UnamSanctam/SilentCryptoMiner#1549]
Are there crypters on the market that bypass Avast/AVG blocking injection and doing sandboxing? I just need to know if it's worth trying, or should I just drop injection and run the miner(xmrig) directly.

Also, should it be possible to inject xmrig in the process itself that is carrying the xmrig as a resource? I think I tried pe2shc with TikiTorch - didn't work. Maybe TikiTorch is the problem. In 2.x versions you had self injection code, but I think it was used on the NET part after using donut on it. Will the same self injection code work for the xmrig itself?

**Comment by UnamSanctam** [comment]
>Are there crypters on the market that bypass Avast/AVG blocking injection and doing sandboxing? I just need to know if it's worth trying, or should I just drop injection and run the miner(xmrig) directly.

Not sure, there could be one that bypasses it but most likely not.

>Also, should it be possible to inject xmrig in the process itself that is carrying the xmrig as a resource? I think I tried pe2shc with TikiTorch - didn't work. Maybe TikiTorch is the problem. In 2.x versions you had self injection code, but I think it was used on the NET part after using donut on it. Will the same self injection code work for the xmrig itself?

You could theoretically inject xmrig into a remote thread of the process that injects it using some form of remote thread injection or thread hijacking.
