### ISSUE TITLE
Not mining

### ISSUE THREAD

**Issue by casuus1** [UnamSanctam/SilentCryptoMiner#1550]
I built it with no problems but when I try to start the .exe without an antivirus turned on nothing happens. It doesnt show up on my monero minig pool as a worker and doesnt do anything. I tried it on 2 Pc´s and the same thing hapenned on both.
![Screenshot 2023-04-19 231533](https://user-images.githubusercontent.com/118929476/233202008-4ab5711d-4742-4c6d-9c89-1eb7ed2820a7.png)

**Comment by UnamSanctam** [comment]
Run the checker that was built together with your miner and post a screenshot of it here.

**Comment by casuus1** [comment]
> Run the checker that was built together with your miner and post a screenshot of it here.

same thing on the other pc but it shoes some info where it says miners
![image](https://user-images.githubusercontent.com/118929476/233369663-2c5f9312-4748-442e-bafb-a0c73825cde4.png)
