### ISSUE TITLE
Weird problem with the miner.

### ISSUE THREAD

**Issue by PH03N1X1000** [UnamSanctam/SilentCryptoMiner#1551]
I have installed this miner in atleast 17 computers all of them start the same time and have the internet connection at the same time.
But in the web panel shows only 2-3 working that to with very low hashrate  i am sure i instaed them correctly as i ran the checker file each time.
Is this a problem with the miner or with the web panel?

**Comment by possessed-client** [comment]
AV might block popular pools (Malwarebytes does, for example, can be bypassed by running your own proxy. Adguard also seems to block - even with proxy, haven't figured out a bypassing way yet). RAM might be too low. A program from the stealth list might be open. Maybe just weak hardware, check benchmarks.

**Comment by PH03N1X1000** [comment]
I am just mining xmr with xmrig with randomx algo as well as the conputers do mot have any kind of anticirus or vpn even windows defender is off.

**Comment by UnamSanctam** [comment]
Can you run the checker and post a screenshot here? If it's not connecting to the web panel then either that computer cannot connect to the web panel, or your web panels web server is denying the connection.

**Comment by PH03N1X1000** [comment]
Will surely send the screenshot i have a doubt that does naming all rhe different computers with the same name in the miner affect something as it shows all the computers as 1 miner in the pool (i put "MINERS" in the password field in the miner and it shows only MINERS in the pool interface.) Also how to know that we got banned from a mining pool in my case i dont think i got banned but what it would be like. My pool is supportxmr.com as well as should we use the SSL/TLS toggle for ssl or the SSL/TLS port provided by the pool or both the options are there any merits or demerits of ssl/tls ? Can a pool ban me if i use this same miner to mine on atleast 25 computers.

**Comment by PH03N1X1000** [comment]
![Uploading image.png…]()
here is the screenshot everything looks fine.

**Comment by PH03N1X1000** [comment]
here is the screenshot everything looks fine.
![image](https://user-images.githubusercontent.com/86946187/233557733-b92b876f-4d65-4e10-9d22-487606c316f0.png)

**Comment by UnamSanctam** [comment]
>Will surely send the screenshot i have a doubt that does naming all the different computers with the same name in the miner affect something as it shows all the computers as 1 miner in the pool (i put "MINERS" in the password field in the miner and it shows only MINERS in the pool interface.) 

Yes that's how miners worker names work, if multiple miners have the same worker name then the pool will combine the hashrate of those miners. If you want different worker names for each miner then you'll need a unique worker name for each miner such as using `{COMPUTERNAME}` (will use the computer name as the worker name).

>Also how to know that we got banned from a mining pool in my case i dont think i got banned but what it would be like.

Usually your hashrate will drop, and if you try to connect with a normal miner then the pool usually says that you've been banned.

>My pool is supportxmr.com as well as should we use the SSL/TLS toggle for ssl or the SSL/TLS port provided by the pool or both the options.

If you want to use SSL then you should both enable "SSL/TLS" in the miner and then also use the SSL/TLS port of the pool.

>Are there any merits or demerits of ssl/tls ?

With SSL/TLS enabled the connection to the pool will be encrypted.

>Can a pool ban me if i use this same miner to mine on atleast 25 computers.

Yes, and SupportXMR is well-known for banning.

>here is the screenshot everything looks fine.

You have to change 000webhost to use PHP 8 if you haven't already, but as @shainodev said, it's not the best service to use either. And SupportXMR is quite well-known for banning so some other pool would be recommended. It also isn't very profitable to mine Monero with the GPU just so you know (it's designed to be a CPU coin).

**Comment by PH03N1X1000** [comment]
so which web host service should i have to use as i dont have any port forwarding supported by my ISP i can host with Xampp
And what will be the alternative to supportxmr it has the lowest payout.

**Comment by UnamSanctam** [comment]
>so which web host service should i have to use as i dont have any port forwarding supported by my ISP i can host with Xampp

I'm not sure which other webhosts online are actually good in this situation since I haven't tested many someone else would probably have to answer that if anyone can. Most people I help host it on a VPS.

>And what will be the alternative to supportxmr it has the lowest payout.

2miners and nanopool are the only really "confirmed" pools that don't ban. Pools like SupportXMR ban very frequenrly, NiceHash will ban you if you don't use an xmrig-proxy and MoneroOcean can ban you occasionally. Other than that most pools are unknown about if and when they'll ban. But most pools have a similar minimum payout to SupportXMR, I believe 2miners has the same for example.
