### ISSUE TITLE
Can anyone pls explain the MaX Cpu Usage concept.

### ISSUE THREAD

**Issue by PH03N1X1000** [UnamSanctam/SilentCryptoMiner#1552]
Sorry for amateur question but can anyone explain the MAX cpu percentage i am not able to understand from the WIKi.
What would 100% of max cpu use in a.8 core and a 10 core cpu pls tell or 100% means full usage?

**Comment by possessed-client** [comment]
Yes, the percentage is calculated from the core count (sometimes thread count on strong CPUs, if they're suitable for mining, as determined by xmrig automatically). 100% Max CPU is using all usable cores, all the time.

**Comment by PH03N1X1000** [comment]
Thanks for your help its clear now.
