### ISSUE TITLE
silent miner connecting to panel, but showing 'error' as status

### ISSUE THREAD

**Issue by noahmajors** [UnamSanctam/SilentCryptoMiner#1554]
using the default 'full' .xml preset provided. disabled stealth so that it can be monitored within the web panel. after testing on my own machine, and running checker, this is what i am shown.
![Screenshot 2023-04-20 162415](https://user-images.githubusercontent.com/62274829/233480640-b502b4dd-0d9a-4887-81be-20d3e9c50d1d.png)
![Screenshot 2023-04-20 163159](https://user-images.githubusercontent.com/62274829/233481274-566e63a5-e153-4de3-ab43-7e4720bf3737.png)

any ideas?

**Comment by UnamSanctam** [comment]
That's because you have SSL enabled for the pools but you're using the non-SSL ports for the pools.

**Comment by noahmajors** [comment]
So the default ports that were set were actually correct? I couldn’t find anything on 2miners that referenced the SSL port being different from the non-SSL ports. Would you recommend leaving SSL on, or disabling it for the non-SSL pools?Sent from my iPhoneOn Apr 21, 2023, at 12:55 PM, Unam Sanctam ***@***.***> wrote:﻿
That's because you have SSL enabled for the pools but you're using the non-SSL ports for the pools.

**Comment by UnamSanctam** [comment]
Yes the default ports in the example settings are correct if that's what you mean, you can find the SSL ports at the bottom of the page where the ports are listed. SSL is usually recommended if it's available.
