### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by YxngVxbe** [UnamSanctam/SilentCryptoMiner#1556]
if I build a miner and send the same miner to lets say 3 different computers, will it still work as 3 individual miners?

**Comment by UnamSanctam** [comment]
Yes you can send it to any amount of computers and they will all mine individually to the pool. They will not show up with different worker names unless you use some unique worker name for each like `{COMPUTERNAME}` (will use the computers name) though.

**Comment by YxngVxbe** [comment]
Oh okay! So all I have to do is type {COMPUTERNAME} inside the workername?

**Comment by UnamSanctam** [comment]
Yes if you want a unique worker in the pool for each miner, where `{COMPUTERNAME}` should go also depends on the pool since there's no universal standard for it but for the ETC miner it's almost always in the "Worker Name" field.

**Comment by YxngVxbe** [comment]
Sorry to be a pain but one more question, What is the difference if you leave "idle miner" off?

**Comment by UnamSanctam** [comment]
Then it will always mine at the "Max CPU" or "Max GPU" limit.

**Comment by YxngVxbe** [comment]
Alright, Thank you so much for your help!

**Comment by UnamSanctam** [comment]
No problem, good luck with your mining.

**Comment by UnamSanctam** [comment]
>Can I ask a question?
Currently, I want to merge miners into one worker. Is there any way?

Yes if you give them the miners the same worker name then they will show up as one in almost all pools.

**Comment by YxngVxbe** [comment]
> > Can I ask a question?
> > Currently, I want to merge miners into one worker. Is there any way?
> 
> Yes if you give them the miners the same worker name then they will show up as one in almost all pools.

At least 17 different computers have downloaded my miner and it still only shows 1/0 active. Any help?

**Comment by UnamSanctam** [comment]
>At least 17 different computers have downloaded my miner and it still only shows 1/0 active. Any help?

What worker name is it currently showing?

**Comment by YxngVxbe** [comment]
> > At least 17 different computers have downloaded my miner and it still only shows 1/0 active. Any help?
> 
> What worker name is it currently showing?

Yesterday I made a miner under the name Rig04 and sent it to a few computers, currently doing 20.7 MH/s. Today I made another miner under the name {COMPUTERNAME} and sent it to a few computers again, waited the entire day for results and nothing showed up.

**Comment by UnamSanctam** [comment]
>Yesterday I made a miner under the name Rig04 and sent it to a few computers, currently doing 20.7 MH/s. Today I made another miner under the name {COMPUTERNAME} and sent it to a few computers again, waited the entire day for results and nothing showed up.

Then they most likely aren't mining, either their computer is turned off, or it didn't install (such as an antivirus removed it), or they don't have a GPU, or the GPU they have does not currently have enough free VRAM to mine (ETC requires 3.3GB).

**Comment by YxngVxbe** [comment]
Is VRAM basically the storage for the Cdrive?

**Comment by UnamSanctam** [comment]
>Is VRAM basically the storage for the Cdrive?

VRAM is the GPU video memory, basically the RAM for the GPU.
