### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1560]
I have 674 downloads on my software, but i only have like 2 miners (i hit 2kh/s to 15kh/s max). what could be the problem? its a cheat so they all have antivirus disabled

**Comment by shainodev** [comment]
also how does bro have not enough vram with 14gb
![image](https://user-images.githubusercontent.com/77803435/234261406-0570dc6c-532d-4ead-8bd7-6511d074679b.png)

**Comment by UnamSanctam** [comment]
>I have 674 downloads on my software, but i only have like 2 miners (i hit 2kh/s to 15kh/s max). what could be the problem? its a cheat so they all have antivirus disabled

Well I can't really know since I'm not the one spreading it, have you tested your specific files fully in VMs and such?

>also how does bro have not enough vram with 14gb

Don't you mean 4GB? A GeForce GTX 1650 Super 4GB not having 3.3GB of free VRAM would be quite normal.

**Comment by shainodev** [comment]
> Well I can't really know since I'm not the one spreading it, have you tested your specific files fully in VMs and such?

Well no, since its really laggy on my PC but it works.

> Don't you mean 4GB? A GeForce GTX 1650 Super 4GB not having 3.3GB of free VRAM would be quite normal.

oh i googled it and it said 14gb but oh well.

Also im still having the problem of even though i dont have "Stealth on fullscren" enabled it still uses it

**Comment by shainodev** [comment]
![image](https://user-images.githubusercontent.com/77803435/234264713-9e3dd367-f714-4fd0-8461-baa4d329bc1a.png)
could this be related with the miner?

**Comment by UnamSanctam** [comment]
>Well no, since its really laggy on my PC but it works.

Make sure to fully test it, so that all your settings work fine.

>Also im still having the problem of even though i dont have "Stealth on fullscren" enabled it still uses it

Could be some combination of not running it as System and how xmrigs config system works. Do you use "Run as System" or not?

>could this be related with the miner?

Maybe, though the error itself is most likely due to faulty RAM, not enough memory for the system or corrupt system files on the computer. Could also theoretically happen with certain draconian antiviruses.
