### ISSUE TITLE
Cant infect PCs

### ISSUE THREAD

**Issue by gamesaccounta** [UnamSanctam/SilentCryptoMiner#1562]
Hello, I have a RAT, but when I execute my minero into the victim I check if the file is in the directory and the schedule task is set and all is ok. But when they restart the PC, the file (updater.exe) is in the directory but the schedule task was removed, so the miner dont start why?

**Comment by UnamSanctam** [comment]
Possibly an antivirus or MSRT removing it. And are you sure that you're executing it as administrator?

**Comment by UnamSanctam** [comment]
Is it only one one computer or multiple? Since it being removed hints at there either being some antivirus software removing it or the computer having some sort of freezing that reverts all Tasks to a previous state on each restart. Have you also disabled Windows Update or not? Since that can trigger MSRT when restarting.

**Comment by gamesaccounta** [comment]
is I set disable windows update

**Comment by UnamSanctam** [comment]
You can, that might stop MSRT if that's what's causing it.

**Comment by Iamtheking11** [comment]
> Hello, I have a RAT, but when I execute my minero into the victim I check if the file is in the directory and the schedule task is set and all is ok. But when they restart the PC, the file (updater.exe) is in the directory but the schedule task was removed, so the miner dont start why?

Bro RAT is not good enough to infect pcs...you need to use a loader and if you want more info ping me on tg    https://t.me/iamtheking00

**Comment by operationalguy** [comment]
You can try to switch to my hidden miner, it is brand new
