### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by Brawllol** [UnamSanctam/SilentCryptoMiner#1564]
Hey! Can I make this miner autostart when Windows is turned on? I just often have power outages, there is no way to always turn on the Miner on a new

**Comment by GitHubUser5672** [comment]
If installed on an administrator account, will it also run on a normal user account when the administrator is logged off?

**Comment by UnamSanctam** [comment]
>If installed on an administrator account, will it also run on a normal user account when the administrator is logged off?

If you have "Run as System" enabled then it will run on all users.
