### ISSUE TITLE
Stealth Targets & idle mining option not working

### ISSUE THREAD

**Issue by aminur199** [UnamSanctam/SilentCryptoMiner#1567]
which part of source i can find this code related to Stealth Targets, and idle mining, so that i can modify it and make it working

**Comment by UnamSanctam** [comment]
They work fine, which part isn't working? As long as you have "Stealth" enabled then the miner will go into stealth when any program on the "Stealth Targets" list is open. And for idle mining it will be using the "Max CPU" amount of CPU cores until the keyboard and mouse has been idle for the "Idle Wait" amount of minutes, at which point it will start using the "Idle CPU" amount of CPU cores. And for the GPU miner it does the same but just with the GPU usage instead.

**Comment by aminur199** [comment]
Stealth on Fullscreen is ON
Stealth Targets: Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe

But still miner running at full cpu power when task manager open, i also have test with another program nothing work

**Comment by UnamSanctam** [comment]
Run the checker and post a screenshot of it here, and also post a screenshot of the Task Manager (sorted by CPU).

**Comment by aminur199** [comment]
ok bro thanks now its working, but please can you share me the source code of xmrig

**Comment by UnamSanctam** [comment]
>ok bro thanks now its working, but please can you share me the source code of xmrig

Right now I don't have the repositories for those because I don't have the time to maintain them (haven't even had enough time to finish UnamBinder and UnamDownloader updates yet), and some of the code is private as well, so I'd also have to make the miners a bit worse for a public code release.
