### ISSUE TITLE
Could not connect to the pool.

### ISSUE THREAD

**Issue by karolszkotak** [UnamSanctam/SilentCryptoMiner#1569]
Why i get error like this

![1CFF9A50-4F39-40BE-A6FC-AC0354C152C7](https://user-images.githubusercontent.com/132330244/235587549-0b900017-aeab-4d39-8937-96a3d71b26a7.jpeg)

**Comment by UnamSanctam** [comment]
Post the pool you're trying to connect to, run the checker and take a screenshot and then post that here.
