### ISSUE TITLE
If any one needs help ping me

### ISSUE THREAD

**Issue by Iamtheking11** [UnamSanctam/SilentCryptoMiner#1575]
Hey guys...if anyone of you wants to start silent mining from unams tools ping me on telegram i will guide you in a right way...i am not asking for money..or anything..i also start from somewhere if i can help someone i ll be happy...thanks 
My telegram id https://t.me/iamtheking00

**Comment by masterjek** [comment]
This is also a scammer. Do not believe him, he has no evidence, only the payment of money in advance and that's it.

**Comment by UnamSanctam** [comment]
>This is also a scammer. Do not believe him, he has no evidence, only the payment of money in advance and that's it.

Thank you again, I didn't notice this one, I'll remove this too.

**Comment by masterjek** [comment]
> > This is also a scammer. Do not believe him, he has no evidence, only the payment of money in advance and that's it.
> 
> Thank you again, I didn't notice this one, I'll remove this too.

Thanks Unam. I just checked these scammers. But I just didn't get paid. There and without payment it is clear that this is a scammer. Please remove their posts so people don't get scammed.
