### ISSUE TITLE
New Feature To Add

### ISSUE THREAD

**Issue by we-script** [UnamSanctam/SilentCryptoMiner#1579]
Hey, please add a feature that lets you run programs thru the web ui (into the infected users pc) ie, install discord or smth else.

**Comment by karolszkotak** [comment]
+1

**Comment by UnamSanctam** [comment]
The problem with that is that the web panel is not built like a RAT or botnet, since that's not what it's meant for. I can technically introduce a system like that but it will have a ton of caveats. It would be easier to use a RAT or botnet client to do that.
