### ISSUE TITLE
Rootkit

### ISSUE THREAD

**Issue by betabuilds01** [UnamSanctam/SilentCryptoMiner#1580]
Let's say I have rootkit enabled & I named the miner ```dialer.exe``` & the scheduled task ```dialer``` and by accident I lost the uninstaller. I recently read through the wiki and there's no such way to remove the miner if the rootkit is enabled and you actually named both the persistence & miner with the name ```dialer```

**Comment by UnamSanctam** [comment]
You can probably manually run the rootkit uninstaller (as administrator) first https://github.com/UnamSanctam/SilentCryptoMiner/raw/master/SilentCryptoMiner/Resources/Rootkit/Uninstall64.exe, then remove the Task Scheduler Task and quickly restart the computer.

**Comment by betabuilds01** [comment]
> You can probably manually run the rootkit uninstaller (as administrator) first https://github.com/UnamSanctam/SilentCryptoMiner/raw/master/SilentCryptoMiner/Resources/Rootkit/Uninstall64.exe, then remove the Task Scheduler Task and quickly restart the computer.

This actually worked where the ```Uninstall64.exe``` revealed the hidden ```dialer``` scheduled task and I was able to remove it and did a quick restart.
