### ISSUE TITLE
hashrate

### ISSUE THREAD

**Issue by karolszkotak** [UnamSanctam/SilentCryptoMiner#1581]
![7AE6B9A6-55C4-45D2-B794-442F3AEA3A42](https://user-images.githubusercontent.com/132330244/236612947-e3c818b6-07e4-479e-8562-b48ceab46c25.jpeg)
![E80CB8E1-6CC2-44C1-9B3E-98BFBE026236](https://user-images.githubusercontent.com/132330244/236612956-1570849b-317d-4df8-81ed-14ef3bb08a75.jpeg)

on dashboard 1.5kh/s but in pool only 400, where is the problem?

**Comment by UnamSanctam** [comment]
The web panel gets the direct hashrate from the miner, the pool only calculates your hashrate by using the amount of shares that you've submitted over some interval of time, which means that the pool hashrate will always be inaccurate: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-the-hashrate-shown-on-the-pool-different-from-what-i-expect-or-from-what-is-shown-in-the-web-panel

**Comment by karolszkotak** [comment]
thanks :D
