### ISSUE TITLE
Unam i Can Do this in Configuration ?

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1582]
"pool": "address1,address2",
"port": port1,port2,

**Comment by UnamSanctam** [comment]
No, xmrig configurations are too complicated for that really. Right now there's three different pools you can have at once (one main pool and two backup pools):
1. Builder pool
2. "Remote Configuration" pool
3. Web panel pool

**Comment by tarekxxx** [comment]
okay thanks sir
