### ISSUE TITLE
If anyone wants to spread miner 

### ISSUE THREAD

**Issue by Iamtheking11** [UnamSanctam/SilentCryptoMiner#1583]
Hello guys...i saw that many of US are stuck on how to spread their miner file...if anyone still stuck on this issue can ping me on my TG i can help him...thanks..
My TG https://t.me/iamtheking00

**Comment by masterjek** [comment]
This is cheating users for money. You will not receive any installations. Do not believe me, I personally checked this person and made sure that he was deceiving. They also demand payment in advance without any proof.

**Comment by UnamSanctam** [comment]
>This is cheating users for money. You will not receive any installations. Do not believe me, I personally checked this person and made sure that he was deceiving. They also demand payment in advance without any proof.

Alright thank you, I will remove the issue.
