### ISSUE TITLE
Etc is not mining

### ISSUE THREAD

**Issue by Fructose3481** [UnamSanctam/SilentCryptoMiner#1585]
![firefox_7iNOh87ixc](https://user-images.githubusercontent.com/132773671/236646642-c867af51-98c4-4a11-8e00-cce0f82b319d.png)
I have 2 workers with supported gpu, and they both don't mine etc even when idle.
Their gpu's are NVIDIA GeForce GT 730 and NVIDIA GeForce GTX 1660 SUPER.

**Comment by UnamSanctam** [comment]
Probably not enough free VRAM (the GT 730 does not ever have enough total VRAM to mine ETC), though usually the status should say so unless something causes it not to.

**Comment by Fructose3481** [comment]
What about next one with 1660 super? I saw him with 13mh/s one time, but usually it's 0h/s

**Comment by UnamSanctam** [comment]
Probably not enough free VRAM, ETC requires 3.3 GB of VRAM. The 1660 Super has 6GB, so if he's using more than 2.7 GB of VRAM then there's not enough free to mine. Since you've seen it with hashrate before then that's most likely the reason.

**Comment by Fructose3481** [comment]
Okay, thank you.
