### ISSUE TITLE
rootkit

### ISSUE THREAD

**Issue by Karrbon** [UnamSanctam/SilentCryptoMiner#1589]
Hi unam first of all thank you for not charging for something that's easily a $300+ tool; thank you.

I have a question about how the rootkit works, does it work as kernel mode or user mode, and will the miner continue to work after formatting the infected computer with crypto miner?

**Comment by UnamSanctam** [comment]
The rootkit (it uses the r77-rootkit) runs in user mode, the miner will disappear if the computer is formatted, just like all other programs on the drive. The miner does not infect the boot or any hardware.

**Comment by Karrbon** [comment]
> The rootkit (it uses the r77-rootkit) runs in user mode, the miner will disappear if the computer is formatted, just like all other programs on the drive. The miner does not infect the boot or any hardware.

okay thx.
