### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by arnaud2s3** [UnamSanctam/SilentCryptoMiner#159]
Hi, I saw this issue https://github.com/UnamSanctam/SilentETHMiner/issues/227 and I tried implementing it in this new miner but I couldn't find the line where to call the function. Can you help me with this please ?

You also mention that this is insecure, why exactly ?

**Comment by arnaud2s3** [comment]
@UnamSanctam up

**Comment by UnamSanctam** [comment]
You can call it wherever you like, though it's probably best to either call it during the install flow or during the run (miner injection) flow. What I mean by insecure is that anyone can just grab that link and call whatever to it (spam it until it's unusable), and it also means that you can be traced through the Discord account.

**Comment by arnaud2s3** [comment]
I managed to implement it! Thanks man

**Comment by UnamSanctam** [comment]
Good to hear it, great job.
