### ISSUE TITLE
Change algo in remote config

### ISSUE THREAD

**Issue by RCT133** [UnamSanctam/SilentCryptoMiner#1591]
Hello. I am using rx/0 algo but I want to try out kawpow so can I change it from the remote config?

**Comment by UnamSanctam** [comment]
Not really per say, some coins can be more profitable on some CPUs or during some times but CPU coins are generally over time either the same profitability as others or less. To see whether it would be more profitable for you then you would have to test it and see what the difference in profit would be for you between different coins (such as RTM or others).
