### ISSUE TITLE
Anyone needs help? 

### ISSUE THREAD

**Issue by Iamtheking11** [UnamSanctam/SilentCryptoMiner#1592]
Anyone needs help in spreading miner file or crypting or anything else ping me on my Tg https://t.me/iamtheking00

**Comment by Iamtheking11** [comment]
> @UnamSanctam The scammer returned, he didn’t even change telegrams, he is trying to deceive people from the same address.

I am not a scammer bro thats why i didn't change my id

**Comment by masterjek** [comment]
@UnamSanctam I'll tell you what a scammer is:
1. He will not provide any proof that he will distribute and encrypt the miner.
2. When communicating, he referred me to another person.
3. In proof, another person throws off a link to a random site with programs and says this is my site. All programs on the site are associated with the miner and when they are installed, the victim will be infected.
4. Immediately after the site, the person insists on payment.
5. I went to the site and see that most of the programs there are just from the official developer sites.
6. I downloaded one of the programs and installed it on a virtual machine and made sure that the regular program just installed. I didn't see any sign of the miner being installed even after rebooting the machine.
7. I wrote to the person who has been persistently writing about payment all this time. And he asked why not a single program is infected on the site?
8. He tells me to pay money, I will start infecting programs. But before that, before my check, he told me that the programs on the site were already combined with the miner. And the person who advertises it here claims that he has already bought 2,000 installations on the site and now infected computers are connecting to it at full speed.
9. When asked to provide normal proofs, the answer is one, pay faster.
Conclusion one person is a scammer who does not provide a single proof. And only asks for payment in advance. Such a proof about a site with programs can be provided even by me. Just copy any site with programs and send it to a person with the phrase here is my site.

**Comment by UnamSanctam** [comment]
@masterjek Thank you for the full explanation, I will remove the issue.
