### ISSUE TITLE
UnamWebPanel issue

### ISSUE THREAD

**Issue by DonXirus** [UnamSanctam/SilentCryptoMiner#1594]
hello, thanks for the effort you setting on this project,
my issue is that i think the UnamWebPanel is not compatible yet with the new update of SilentCryptoMiner v3.2.0 when i tested it i didn't get the active miner on the panel untill i switched back to v 3.1.0 then it works,

**Comment by UnamSanctam** [comment]
It works fine with the new version, make sure that the URL is correct. You can run both miners and then run the checkers and post a screenshot of both here.

**Comment by UnamSanctam** [comment]
And you aren't using https or something while not having a certificate? If you compile it with the exact same settings (in the "Main" tab use "Save"/"Load") using the 3.1.0 builder does it connect? I know that it should work since I help people with their panels and I know of thousands of 3.2.0 clients on their panel so the problem should be something else.

**Comment by DonXirus** [comment]
ohh so you mean i create the file with the v 3.1.0 then i save the xml file then i use v 3.2.0 to import it and test again ? 
i didn't use this way i will test it now and see.
for the panel it's http with no ssl just running from vps ip with no ssl it's working well
so i will test this way and see  thanks

**Comment by DonXirus** [comment]
works good now thanks i want to ask you if there is some new entryname and filename for startup option ? instead of using default one 
GoogleUpdateTaskMachineQC
Google\Chrome\updater.exe

**Comment by UnamSanctam** [comment]
Ok great, you can use any name or path for the "Startup" options if you don't want to use the default ones (wouldn't recommend using the words `Microsoft` or `Windows` though since they can be blacklisted).

**Comment by masterjek** [comment]
> Ok great, you can use any name or path for the "Startup" options if you don't want to use the default ones (wouldn't recommend using the words `Microsoft` or `Windows` though since they can be blacklisted).

(wouldn't recommend using the words `Microsoft` or `Windows` though since they can be blacklisted). - I want to ask if the antivirus is blacklisted, or the miner will not start from these folders.

**Comment by UnamSanctam** [comment]
>(wouldn't recommend using the words Microsoft or Windows though since they can be blacklisted). - I want to ask if the antivirus is blacklisted, or the miner will not start from these folders.

Some game anti-cheats and some antiviruses will block all access to those folders, so the miner won't be able to install there (because you can't copy or move any files there).

**Comment by UnamSanctam** [comment]
>Tell me more words by type - System, Securyty or Protection - Also don't use it?

You can probably use those, the only ones I've really seen (or had reported to me) are `Microsoft` and `Windows` so far.

**Comment by DonXirus** [comment]
i noticed another issue the statistics not  working well i'm not sure what was the prbolem exactly, it show only the total miners but it don't filter them well like 
total
100
Active
0
Active (Idle)
0
Starting
0
Paused
0
Not enough free VRAM
0
Error
0
Offline
100
but on the miners panel there is some active some offline and some paused ...
is there any fixor i'm missing something ?
thanks for the support keep up the good work <3

**Comment by DonXirus** [comment]
> Ok great, you can use any name or path for the "Startup" options if you don't want to use the default ones (wouldn't recommend using the words `Microsoft` or `Windows` though since they can be blacklisted).

got it thanks everything works well now but i still have some probelms with the panel 
i noticed another issue the statistics not working well i'm not sure what was the prbolem exactly, it show only the total miners but it don't filter them well like
total
100
Active
0
Active (Idle)
0
Starting
0
Paused
0
Not enough free VRAM
0
Error
0
Offline
100
but on the miners panel there is some active some offline and some paused ...
is there any fixor i'm missing something ?
thanks for the support keep up the good work <3

**Comment by UnamSanctam** [comment]
Did you downloads the UnamWebPanel.zip from the releases page (https://github.com/UnamSanctam/UnamWebPanel/releases)? I believe there was one line wrong and I hotfixed it in that one (since I can't release a new version for just one line change).

**Comment by DonXirus** [comment]
no i used git to clone from github directly

**Comment by UnamSanctam** [comment]
Yes then that line isn't changed, you can see the change in the UnamWebPanel.zip in the statisticsAjax.php file.

**Comment by DonXirus** [comment]
can you please send that line and where to edit it because i have already some bots  on the panel and i don't won't to reinstall it again maybe i can lose all bots

**Comment by UnamSanctam** [comment]
Sure, there are only two small changes but I can just send you the fixed file, replace the `internalPages/statisticsAjax.php` file with this file: [statisticsAjax.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/11469902/statisticsAjax.zip) (zipped since GitHub doesn't allow attached .php files).

**Comment by DonXirus** [comment]
alright thanks bro i really apreciate it <3 will test it now
