### ISSUE TITLE
What is profitable to mine now?

### ISSUE THREAD

**Issue by Driadasasa** [UnamSanctam/SilentCryptoMiner#1596]
Please tell me what is the best way to mine? Is it one or the other, or is it used in a bundle?

**Comment by UnamSanctam** [comment]
Usually its still XMR + some GPU coin, like ETC, UQB or maybe some sort of cn/gpu coin like RYO or CCX (though those requires the large xmrig CUDA GPU libraries).

**Comment by Driadasasa** [comment]
ETC now brings a little money, no?

**Comment by UnamSanctam** [comment]
Depends on what you compare it to.
