### ISSUE TITLE
disable sleep setting

### ISSUE THREAD

**Issue by GitHubUser5672** [UnamSanctam/SilentCryptoMiner#1597]
Does it completely block the device from going into sleep/hibernation? Like the sleep button on the start menu doesn't work, or just disables sleep after inactivity?

**Comment by UnamSanctam** [comment]
It disables hibernation and also sleep after inactivity, it doesn't (or rather shouldn't) disable the normal sleep button since many use it so it going missing could be a problem.

**Comment by GitHubUser5672** [comment]
Just tried using the sleep button with that option on, and it just turned off the screen. After removing the miner it worked normally. Is that how it should be?

**Comment by UnamSanctam** [comment]
Yes I think so, and well the miner does not revert those settings when uninstalled because it does not know what the original settings were.

**Comment by GitHubUser5672** [comment]
After installing the miner again with the sleep option off, same thing happened.
So, having the miner running breaks the sleep function.
I'm guessing it happens because windows won't turn off the miner process until it finishes it's work (which will never happen) and just keeps it running.
It would be nice if I could still use sleep mode while having the miner on.

**Comment by UnamSanctam** [comment]
Hmm, manual Sleep mode is working fine for me even with "Disable Sleep" enabled both on Windows 10 and Windows 11, are you using some other Windows version?

**Comment by GitHubUser5672** [comment]
Using windows 10

**Comment by GitHubUser5672** [comment]
It happens when it's mining. If it's starting/not working it doesn't happen.

**Comment by GitHubUser5672** [comment]
Btw, I've noticed kawpow has a 50/50 start up chance so would be nice if the miner would relaunch when an error happens (it stays at 0H/s until the PC is rebooted). [image](https://ibb.co/QH7LLwZ)

Also, does the miner keep attempting to connect when it cannot connect to a pool? Or just gives up until next run?

**Comment by UnamSanctam** [comment]
>Btw, I've noticed kawpow has a 50/50 start up chance so would be nice if the miner relaunched when that happens (it stays at 0H/s until the PC is rebooted). [image](https://ibb.co/QH7LLwZ)
[it did not work for a whole day yesterday lol](https://ibb.co/N2ZYTCg)

That's just a problem with KawPow itself, there are a million different errors and reasons for it, personally I cannot mine KawPow at all with any miner due to an error which it seems like no one else gets but me.

>Also, does the miner keep attempting to connect when it cannot connect to a pool? Or just gives up until next run?

It attempts it forever, if you have multiple pools (such as the builder settings, "Remote Configuration" and web panel) then it will cycle through them until one works.

>It happens when it's mining. If it's starting/not mining it doesn't happen.
(cpu mining xmr)

Then it has nothing to do with the "Disable Sleep", in your case then it might be because the miner might prevent it from going into true sleep and is instead running in away mode.

**Comment by GitHubUser5672** [comment]
> I cannot mine KawPow at all with any miner due to an error which it seems like no one else gets but me.

It doesn't work with my GPU either, you're not alone lol.

> That's just a problem with KawPow itself.

It works half of the time, I think it just doesn't launch properly and therefore relaunching it would fix it, so please could you implement that when the hashrate stays at 0 for a few minutes, it resets the miner process? For all algorithms preferably since I believe it also happened a few times when cpu mining XMR, though I'm not sure. Overall, it's a very useful feature as it would save up lots of not-mining time, as you can see I missed out on a whole day because of it (and more on other PCs).

> in your case then it might be because the miner might prevent it from going into true sleep and is instead running in away mode.

Yes, that is what I meant. If you could add a fix for that in the new update that would be great, as this way the sleep function is basically useless.

**Comment by GitHubUser5672** [comment]
[found a bug in the webpanel](https://ibb.co/thwjBQf)

**Comment by UnamSanctam** [comment]
>It works half of the time, I think it just doesn't launch properly and therefore relaunching it would fix it, so please could you implement that when the hashrate stays at 0 for a few minutes, it resets the miner process? For all algorithms preferably since I believe it also happened a few times when cpu mining XMR, though I'm not sure. Overall, it's a very useful feature as it would avoid lots of not-mining time, as you can see I missed out on a whole day because of it (and more on other PCs).

Yeah, though that would only work when installed and with the "Watchdog" enabled, since otherwise it wouldn't be able to relaunch. I will try out a few things.

>Yes, that is what I meant. If you could add a fix for that in the new update that would be great, as this way the sleep function is basically useless.

Yes I can try, though it doesn't happen for me so I'll have to guess that it fixes it.

>also [found a bug in the webpanel](https://ibb.co/thwjBQf) (displaying empty space for an algorithm I no longer use)
[also for its total hashrate](https://ibb.co/mc3jLNT)

The algorithm hashrate history still exists, it's just outside of the scope (probably due to an offline miner), unless you've already made sure to remove any miners that used the KawPow algorithm.

**Comment by GitHubUser5672** [comment]
> please could you implement that when the hashrate stays at 0 for a few minutes, it resets the miner process? For all algorithms preferably since I believe it also happened a few times when cpu mining XMR, though I'm not sure.

Just came to confirm that it does also happen when mining XMR.
