### ISSUE TITLE
Miner does not mine

### ISSUE THREAD

**Issue by gray-pear** [UnamSanctam/SilentCryptoMiner#1601]
When i try with XMRig, in about 100 seconds the miner immediately shows up but i tried for about 10 minutes on this and nothing happened. The "wallet address" shown on the checker is different than my actual wallet address, that may be it. I checked both the "fake" and real address and both were empty.
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/130860348/62d2947e-0ba3-4568-97ff-3d29e8b8abfc)

**Comment by UnamSanctam** [comment]
SupportXMR requires a password (worker name) to accept any connection, though SupportXMR isn't recommended since they ban a lot. The wallet address shown in the checker is the one you entered into the builder, so if it's wrong then you entered the wrong wallet address.

**Comment by gray-pear** [comment]
Something is wrong. I DIRECTLY copy the wallet address, paste it in the miner, build it and it's different when i run it. I also tried hashvault pro but that did not work either

**Comment by gray-pear** [comment]
Oh wait. When i checked the "incorrect" wallet address on hashvault, it showed up. the issue seems to be that i can't build the miner. I swear i copy the correct address directly from my wallet, DOUBLE CHECK the address, but it shows up as different.

**Comment by UnamSanctam** [comment]
You could have a crypto clipper malware on your computer, what that does is that it replaces any wallet address you copy with their own (the one that made the clipper). The aim of a crypto clipper is for you to accidentally send any crypto to their address instead of what you intend.

**Comment by gray-pear** [comment]
Yes i do have clipper malware. what the fuck, how dumb am I 💀

**Comment by UnamSanctam** [comment]
>Yes i do have clipper malware. what the fuck, how dumb am I 💀

Haha, well it's better to find it out now than finding out after accidentally sending anything to their address (hope you haven't done so already). Unless it's your own one and you're scamming yourself haha.
