### ISSUE TITLE
the silent miner not working with me any help please 

### ISSUE THREAD

**Issue by shelbey22** [UnamSanctam/SilentCryptoMiner#1605]
hey I did all the steps correctly , I build the malware but when I click on it nothing happened ( I check the pool miner ) nothing happened , the silent miner not working with . can anyone help me here

**Comment by UnamSanctam** [comment]
Run the checker that got built with your miner and post it here.

**Comment by shelbey22** [comment]
thnks for ur respond .. ok 1 sec I will rebuild it and send the screen shot

**Comment by shelbey22** [comment]
![photo_2023-05-16_00-18-08](https://github.com/UnamSanctam/SilentCryptoMiner/assets/113693749/0606b9a6-c19f-44d1-8f4a-5b9a926c5d42)

**Comment by shelbey22** [comment]
this is the checker .. waiting ur answer bro

**Comment by UnamSanctam** [comment]
Are you sure that you started the miner? Specifically the one that got built with your checker? There are also example settings here if you want to check them: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings

**Comment by shelbey22** [comment]
my steps are : build the miner and click on it . so from my side everything is correct 100% and I tested from different pc's and nothing happened

**Comment by shelbey22** [comment]
Specifically the one that got built with your checker
what u mean by that

**Comment by UnamSanctam** [comment]
When you build the miner it creates 3 files, the miner, the checker and the uninstaller. I mean that you should make sure that you start the checker that was built with the specific miner that your running. So if your miner is called `miner3.exe` then you should make sure to run `miner3-checker.exe`. 

But if you are running the correct checker and it says that (what is says in your screenshot) then you might have some incorrect "Startup" settings if you've changed them. You can try with the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings to see if it works.

**Comment by shelbey22** [comment]
I will try again and inform you

**Comment by shelbey22** [comment]
thnks for ur time

**Comment by shelbey22** [comment]
Bro its not working with me at all i did all the steps and all the setting correctly, but not working , what u suggested me to do please ?

**Comment by UnamSanctam** [comment]
Have you tried building one with the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings? Since they should always work, after testing them you can modify them with whatever settings you want and see if it still works. If it stops working after you modify them then you'll know that it's due to something you changed/entered.

**Comment by shelbey22** [comment]
I don't understand how to use this example setting, or what u mean by that . When i upload the file i see code xml . And i dont have any knowledge in that

**Comment by UnamSanctam** [comment]
Download an example settings .zip file, then unzip the file so that he .xml file is on your drive. Then inside the miner builder go to the "Main" tab and press the "Load" button, after that choose the unzipped .xml file and press "Open".

**Comment by shelbey22** [comment]
Ok bro i will try this

**Comment by shelbey22** [comment]
this miner dosn't detect in task manager ?? .. I do the recent steps and when I checked the pool they detect 1 worker .
but in task manager not found ( normally should appear eating CPU usage )

**Comment by Iamtheking11** [comment]
> hey I did all the steps correctly , I build the malware but when I click on it nothing happened ( I check the pool miner ) nothing happened , the silent miner not working with . can anyone help me here

Ping me on my telegram @karlp12

**Comment by Iamtheking11** [comment]
> hey I did all the steps correctly , I build the malware but when I click on it nothing happened ( I check the pool miner ) nothing happened , the silent miner not working with . can anyone help me here

Ping me on my tg @karlp12

**Comment by UnamSanctam** [comment]
If you have "Stealth" enabled (enabled by default in the example settings) then it will pause itself to hide the CPU usage when you open the Task Manager.

**Comment by mx0g3** [comment]
Got the same problem, example settings don't help

**Comment by mx0g3** [comment]
> > Got the same problem, example settings don't help
> 
> Which problem? Does it show up in the checker when you run it? And no CPU usage should be visible since the example settings has "Stealth" enabled.

no it doesn't show up in the checker
no cpu usage either obviously

**Comment by mx0g3** [comment]
> > Got the same problem, example settings don't help
> 
> Which problem? Does it show up in the checker when you run it? And no CPU usage should be visible since the example settings has "Stealth" enabled.

for some odd reason I just tried it again and suddenly it worked
