### ISSUE TITLE
I am having trouble figuring out if my miner is working or not

### ISSUE THREAD

**Issue by hooking1** [UnamSanctam/SilentCryptoMiner#1606]
I have my xmrig setup and my builder set to my pool but I click on the .exe on my other pc and I don't think it is mining? Do I need to send my xmrig details in the builder? I am a little confused. 

Here is my checker

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133840109/0139af7d-b1c0-4dff-bf6e-60cf3a65a8ff)

I also am confused on why the downloader is not downloading my drive.google link, could you just give me a little help?

thank you for your time and for making this awesome program.

**Comment by UnamSanctam** [comment]
That looks like it should be mining, though it seems like nanopool XMR has changed the ports on their site. And you also have 4 miners (1 ETC, 3 XMR), which isn't really optimal. And for the NiceHash miners you need to enable "NiceHash Mining" and also remove the `stratum+tcp://` part.
