### ISSUE TITLE
Code questions

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1607]
Good afternoon Unam. Can you please tell me what part of the code is responsible for creating a task in the scheduler? And is it possible to remove this part of the code so as not to disrupt the performance of the rest of the program's functions. I just want to check something.

**Comment by UnamSanctam** [comment]
Here is where it runs inside the miner:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Resources/Code/miner.cpp#L137
And here is the string that gets placed into it:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Classes/Codedom.cs#L381

You can remove it from miner.cpp but then it won't install and start when run as admin.

**Comment by masterjek** [comment]
Did I understand correctly? Can't I just turn off task creation in the scheduler? By removing the line in the code, I will also turn off the run as administrator, right?

**Comment by UnamSanctam** [comment]
Well if you remove the Task creation then you'll have to run it without administrator permissions in order to install it using the registry instead. Or disable "Startup" to run it without installation. What the miner does when installing as an administrator is: create the Task in the Task Scheduler, copy the miner file to the install location, and then start the Task. So if there's no Task then the miner won't be started´.

**Comment by masterjek** [comment]
I am creating a task with a file xml. And the miner file itself is copied to the folder by another program. So the function of creating a task and placing the miner in the right folder is performed by another program. So I want to try turning this feature off. But I need the miner file itself to run as administrator, since it adds itself to the defender exceptions.

**Comment by UnamSanctam** [comment]
Yes then you can remove that part of the code, and also when the miner copies itself if you want that (and also when it starts the Task if yours already does so). As long as you start the program as administrator ("Run as Administrator" option forces that) then the exceptions and everything will work.

**Comment by masterjek** [comment]
Thank you very much. You are doing amazing things. I removed the line and this solved the issue of heuristic analysis of some antiviruses for me. Once again, many thanks.

**Comment by masterjek** [comment]
I apologize for the confusion, but I want to clarify once again. I removed the line in miner.cpp In the screenshot, I circled this area.
![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/f93a22f2-3415-4ccf-8dc0-b74cd8ae04b7)
Nothing else needs to be corrected. I'm worried, I didn't mess up all the other miner functions.

**Comment by UnamSanctam** [comment]
Yes that's correct, if you also don't want the miner to also copy itself and run the Task then you can remove the lines below that, such as the `write_file` line and the `run_program` line that contains `#STARTUPSTARTADMIN`

**Comment by masterjek** [comment]
After running the program for stealth purposes. The miner does not start after closing the program, is this due to editing in the code? And sometimes it starts after 5-10 minutes, each time a different time. The delay before the start is less than a minute.

**Comment by UnamSanctam** [comment]
Do you mean that the watchdog does not start it? Is the miner in the same path as in the "Startup" settings? Since otherwise the watchdog won't be able to start it.

**Comment by UnamSanctam** [comment]
It has to generate the dataset and will start mining after that, the "Start Delay" is only for the miner injector/installer itself and not for anything inside the XMR or ETH miner. If it does not resume producing hashrate quickly after a "Stealth Target" is closed then make sure that there's enough RAM free I guess. As soon as the "Stealth Target" is closed it will immediately try to start mining again (for RandomX it has to generate the dataset first).

**Comment by masterjek** [comment]
Well, I just checked 5 times. After stealthing the target, the miner returned to work every time after a different period of time. As I understand it, it still depends on what you wrote above, but it does not depend on one line that I removed from the code. RAM is enough for 10 GB. While the miner enters the mode of operation after the stealth target, the web panel will show it as active, but with a mining speed of 0.

**Comment by UnamSanctam** [comment]
Yes then that's just xmrig taking time to rebuild the dataset, it's the part that usually takes some time when you normally start xmrig. For me on my main computer the time to rebuild it after exiting "Stealth" is around 5-10 seconds usually, so I assume it depends a lot on the CPU and RAM specifications on the computer.

**Comment by masterjek** [comment]
I checked it on my computer. CPU - i9-13900k RAM - 64 GB. the miner started to work every time in different ways from 1 to 2 minutes. What does the waiting time, as I saw, depend on how long the stealth target was open in time. If you open the stealth target and immediately close it, the miner quickly enters the operating mode, and if the stealth target is left open for a couple of minutes, then the miner returns to the working mode for a couple of minutes too.

**Comment by UnamSanctam** [comment]
>I checked it on my computer. CPU - i9-13900k RAM - 64 GB. the miner started to work every time in different ways from 1 to 2 minutes. What does the waiting time, as I saw, depend on how long the stealth target was open in time. If you open the stealth target and immediately close it, the miner quickly enters the operating mode, and if the stealth target is left open for a couple of minutes, then the miner returns to the working mode for a couple of minutes too.

Sorry for the late response, I've been very busy with work. I can't really recreate the problem, I paused the miner with "Stealth" for one hour and then resumed it by closing the "Stealth Targets" program and it continued mining after about 30 seconds. So this one might be a bit difficult to solve then.
