### ISSUE TITLE
flagged

### ISSUE THREAD

**Issue by hooking1** [UnamSanctam/SilentCryptoMiner#1609]
![7](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133840109/9fcef5a8-49bd-448a-8176-16342387c8eb)

Can someone help me? My .exe keeps being flagged as a virus. Do I need to spread the downloader or the builder itself?

This is my checker
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133840109/851dac98-01bf-4248-a064-5fcf5ff099c0)

**Comment by UnamSanctam** [comment]
You spread the built miner, but getting detected as malware is normal since the miner is public and open source and it's also been more than a week or two since the latest update. If you want it undetected then you'd need a crypter. Though I don't know if it's detected by Windows Defender yet or not.

As I also said in your other issue you also have 4 miners running which you can see in the list.

**Comment by UnamSanctam** [comment]
If they are currently undetected (they aren't I believe) then they can be used by bypass Windows Defender since those programs can add exclusions into Windows Defender before downloading/dropping and running the miner.

**Comment by hooking1** [comment]
I see, and being able to be undetected is by using a crypter?

**Comment by hooking1** [comment]
I just load the crypter with the exe of the builder correct, meaning the payload? What sort of injection do I use?

**Comment by UnamSanctam** [comment]
Yes exactly, you would spread the .exe file that the crypter generates. Also make sure to test run the crypted file to make sure everything works.

**Comment by hooking1** [comment]
How do i know if it has worked? I open the file and nothing happens

**Comment by UnamSanctam** [comment]
It means that the crypter isn't undetected in that case, to know if it works then you can use the checker as you did before. (Also make sure to fix your miner unless you haven't already, with you previously running 3 XMR miners).

**Comment by hooking1** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133840109/e1679c92-fb4a-4c42-bb9f-323db75b8d8d)
My checker

**Comment by hooking1** [comment]
I also have xmrig on my macbook do I need to link them in any way

**Comment by hooking1** [comment]
Is my checker all good?

**Comment by UnamSanctam** [comment]
Since you're using SSL you should use port `10343` for XMR nanopool, and since you're using SSL for NiceHash as well you should change the port to `443` (the SSL port). Though I'm not sure why you're running two XMR miners at the same time.

**Comment by hooking1** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133840109/2f6d4b58-dc78-40cc-aa5f-47ed5f3814bd)
So I built the crypter to inject to the miner itself and launch the crypter but it doesn't open the miner, do I need to inject to the registry or do I need to run the miner myself first?

**Comment by UnamSanctam** [comment]
Can you post a screenshot of the crypter?

**Comment by hooking1** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133840109/d073a0eb-54a5-472c-961f-cd85f3159079)

**Comment by UnamSanctam** [comment]
I'm not sure if Lime Crypter works with 64-bit or not, if you try to crypt putty (64-bit) does it work? Usually putty is used for testing https://www.putty.org/.

**Comment by hooking1** [comment]
How do I use putty to load a file?

**Comment by hooking1** [comment]
So using bytecode77's crypter I was able to execute the file and I think its working now

**Comment by hooking1** [comment]
How do you inject putty to it?

**Comment by UnamSanctam** [comment]
Yes then that's working, though most free crypters will not be undetected of course (since it commonly has to update it every few days or weeks to make it undetected again) so you'll have to test it.

>How do you inject putty to it?

If it's already working with the miner then there's no need to, putty is just a common example program to test with because it should always work.

**Comment by hooking1** [comment]
Is there a way I can check who has used the miner?

**Comment by UnamSanctam** [comment]
On the pool or if you have a web panel.

**Comment by UnamSanctam** [comment]
Does it show any hashrate on the pool at all? And since you're mining at 20% with nanopools 400 000 share difficulty it can take a while to find a share (so that it appears on the pool).

**Comment by UnamSanctam** [comment]
And it's running in the checker? If you build a miner with "Stealth" off (or use some program not inside the "Stealth Targets") then you will be able to see the CPU usage, if CPU is being used then it's mining correctly.

**Comment by hooking1** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133840109/32d8fbbc-17cf-4c5b-a3c4-607e3a19d526)
with 840 current hashrate

**Comment by UnamSanctam** [comment]
Alright then it's working, since nanopool has a share difficulty of 400 000 then the average share time is 400 000/hashrate=share time. Also remember that the hashrate on the pool is simply calculated as the amount of shares submitted over some interval so it will really never be accruate.

**Comment by hooking1** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133840109/5ca0796f-255d-4927-af17-e77ec6c01e6f)
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133840109/0c8c6b12-0b55-4961-912f-777443b7d650)


Pool and checker as of today, how is it looking?

Thanks for your patience

**Comment by UnamSanctam** [comment]
Yes then that's working as it should.
