### ISSUE TITLE
Task Scheduler

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#161]
Good afternoon. Is it possible to implement a function that would add the miner to the task scheduler from a folder other than the default folder AppData? Let's say the miner is in the folder C/Windows/system32 And do you need to add this miner location path to the task scheduler?

**Comment by UnamSanctam** [comment]
Well if you add that into the "Startup" code (where AppData, Temp and UserProfile is available by default) then it will add that path to the Task Scheduler automatically.

**Comment by masterjek** [comment]
Yes, he will do it. But he's in a folder AppData will create a folder AppData/Windows/system32 - And this path will be registered in the task scheduler. And I need the path from the system folder, which is located C/Windows/System32 is it possible to implement?

**Comment by UnamSanctam** [comment]
You would have to code it into the install folder options.
https://github.com/UnamSanctam/SilentCryptoMiner/blob/bb4afa492760e3cbbd5c7853b602f95e3fc31d9f/SilentCryptoMiner/Classes/Codedom.cs#L481

**Comment by masterjek** [comment]
If it's not difficult, you can tell what needs to be changed in the line - So that the path to the scheduler is set from the system folder C/Windows/system32?

**Comment by UnamSanctam** [comment]
Well you don't just have to set the Task Scheduler path to that, you also have to install the actual miner inside System32 as well of course.

You can add a new switch option and probably use this value `Environment.SystemDirectory` for it.

**Comment by masterjek** [comment]
The miner will be in the folder system32, I will do it without any problems. I only have a problem adding the given path to the Task Scheduler.

**Comment by masterjek** [comment]
I changed the lines in the code, in the screenshot I emphasized what I changed. 
![1](https://user-images.githubusercontent.com/36513967/146763071-67af1173-0658-44a9-9976-32cecbdebce3.jpg)
Now, when assembling the miner, I get an error
![2](https://user-images.githubusercontent.com/36513967/146763146-b4279b9c-2f3e-4702-bb3b-b00ff9907230.jpg)
Translation error - The referenced assembly mscorlib.dll is intended for a different processor.

**Comment by UnamSanctam** [comment]
Replace the entire string and not just the argument.

**Comment by UnamSanctam** [comment]
Use Environment.SystemDirectory instead.

**Comment by masterjek** [comment]
Thanks for the help. Something doesn’t work for me. Better wait for the miner to update. Maybe it will return the default installation path to the system directory.
