### ISSUE TITLE
Crypt file

### ISSUE THREAD

**Issue by Driadasasa** [UnamSanctam/SilentCryptoMiner#1610]
Hello, Unam. Can you please tell me how to crypt the file

**Comment by UnamSanctam** [comment]
You would need to find a crypter (that works with 64-bit native files), though if you're looking for a free one then almost all of them won't be undetected of course.

**Comment by Driadasasa** [comment]
> You would need to find a crypter (that works with 64-bit native files), though if you're looking for a free one then almost all of them won't be undetected of course.

Is this the right setting? Do I just have to script the file?
https://imgur.com/a/Kelb3CG

**Comment by Iamtheking11** [comment]
> > You would need to find a crypter (that works with 64-bit native files), though if you're looking for a free one then almost all of them won't be undetected of course.
> 
> Is this the right setting? Do I just have to script the file? https://imgur.com/a/Kelb3CG

If you want any help in crypting you can ping me on my telegram https://t.me/iamtheking00

**Comment by UnamSanctam** [comment]
I have tried waiting but I only get an error anytime I visit imgur on any device or IP:
>{"data":{"error":"Imgur is temporarily over capacity. Please try again later."},"success":false,"status":403}

**Comment by Driadasasa** [comment]
> I have tried waiting but I only get an error anytime I visit imgur on any device or IP:
> 
> > {"data":{"error":"Imgur is temporarily over capacity. Please try again later."},"success":false,"status":403}

https://dropmefiles.com/KWI3n

**Comment by UnamSanctam** [comment]
If you're going to crypt it then most likely it will be an injection crypter, so you should disable "Startup" in the miner builder and then enable "Startup" (or whatever they call it) inside your crypter instead.

You do also use the wrong ports for the pools, you are using the non-SSL ports while having SSL enabled. The ports should have an extra 1 in front of them for the SSL ports, so: `12222` and `11010`

Other than that it should be fine.

**Comment by Driadasasa** [comment]
> If you're going to crypt it then most likely it will be an injection crypter, so you should disable "Startup" in the miner builder and then enable "Startup" (or whatever they call it) inside your crypter instead.
> 
> You do also use the wrong ports for the pools, you are using the non-SSL ports while having SSL enabled. The ports should have an extra 1 in front of them for the SSL ports, so: `12222` and `11010`
> 
> Other than that it should be fine.

Correct me if I'm wrong, but are you asking whether the auto-start feature should be implemented on the cryptocurrency's side?

**Comment by UnamSanctam** [comment]
The autostart should usually be implemented on the crypters side yes, because it injects the miner (or any other program you crypt). Which means that the miner (or other programs) cannot really install themselves because they do not know where they are, but there is some exceptions to this, for example if the crypter injects into itself or something similar then you can in many cases still use the miners "Startup" function.
