### ISSUE TITLE
0 H/s

### ISSUE THREAD

**Issue by THEKILERFRIEND** [UnamSanctam/SilentCryptoMiner#1614]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/32984678/c834972a-73c0-4343-ad01-1a51b436bf6c)
I have been mining for half an hour but it just says 0 hash rate. is there a way to fix it? its a good pc btw 3060ti

**Comment by UnamSanctam** [comment]
Post your mining settings.

**Comment by THEKILERFRIEND** [comment]
[tester.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/11524361/tester.zip)

**Comment by UnamSanctam** [comment]
And the status is "Active"?

**Comment by THEKILERFRIEND** [comment]
yes. btw it does mine now but it only mines for 4 minutes then pauses for 1 hour then 4 minutes again then 1 hour pause again.

**Comment by UnamSanctam** [comment]
Then I would recommend changing the pool, that sounds like a pool issue.

**Comment by THEKILERFRIEND** [comment]
do you know any good mining pools?

**Comment by THEKILERFRIEND** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/32984678/918df382-14e3-477c-a573-63fcb0702e1e)
yeah I think its a problem with pool. can u pls recommend me some good pools for any cryptocurrency thats supported?

**Comment by UnamSanctam** [comment]
You can try 2miners.

**Comment by THEKILERFRIEND** [comment]
I did and now it stopped mining completely

**Comment by THEKILERFRIEND** [comment]
how long will it take on avg to start mining? im using kawpow

**Comment by UnamSanctam** [comment]
Well KawPow isn't inside the ETC miner if you're using that, or did you build a new KawPow miner?

**Comment by THEKILERFRIEND** [comment]
built a new one

**Comment by UnamSanctam** [comment]
Can you post your settings? And generally KawPow isn't recommended since it's not very good for silent mining (causes more lag and heat since it is more core heavy than other algorithms). And all KawPow miners (all on the internet) also usually have quite a lot of issues.

**Comment by THEKILERFRIEND** [comment]
[kawpow.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/11524805/kawpow.zip)

**Comment by THEKILERFRIEND** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/32984678/1e744f34-1f13-4d3b-9e7d-d10c98a12aaa)
40 mins passed and its still not mining

**Comment by UnamSanctam** [comment]
Yes I would not really recommend KawPow, I cannot mine it at all on my computers with any miner that I've been able to find online so it does have its issues. Do you get a hashrate if you mine ETC instead?

**Comment by THEKILERFRIEND** [comment]
yes but the pool I had was limiting me

**Comment by UnamSanctam** [comment]
You could try mining ETC on 2miners and see if it works for you.

**Comment by THEKILERFRIEND** [comment]
they only got ethash which doesnt work i think. so do you think I could mine monero? but there's a problem. they only got europe mining server and i got usa pcs

**Comment by THEKILERFRIEND** [comment]
wait nvm they do have etc thx

**Comment by THEKILERFRIEND** [comment]
<3

**Comment by THEKILERFRIEND** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/32984678/c33f7e3f-2c55-48a0-9423-05b2b2b54af7)
one last question: do you think I can mine on europe servers while using usa pc or asia?

**Comment by UnamSanctam** [comment]
Yes that's fine, you'll just have some higher ping. It can increase the stale share rate but usually it doesn't really change much, you can also find the SSL pool addresses at the bottom of the page if you want an encrypted connection.

**Comment by THEKILERFRIEND** [comment]
Okay thank you!

**Comment by THEKILERFRIEND** [comment]
works now perfectly! much thanks!
