### ISSUE TITLE
How to start this script 

### ISSUE THREAD

**Issue by Sudococommunity** [UnamSanctam/SilentCryptoMiner#1616]
Anyone pls help me
How to start the script and setup the script that can run on  windows silently and how to make this script run whenever system boots

**Comment by UnamSanctam** [comment]
Download the builder here: https://github.com/UnamSanctam/SilentCryptoMiner/releases, then enter all the settings you want and build it. You can also find some example settings here on the wiki: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings. To make it start on boot you just need to enable "Startup" in the builder.

**Comment by Sudococommunity** [comment]
I want to mine eth with ethash algo that can easily run rtx 1650 ti graphic how to setup the script accordingly

**Comment by UnamSanctam** [comment]
You cannot mine ETH anymore, they moved to PoS (proof of staking) so you can only stake it and not mine it.

**Comment by Sudococommunity** [comment]
I want to mine monero with ethhash algo that can easily run rtx 1650 ti graphic how to setup the script accordingly

**Comment by UnamSanctam** [comment]
Well Monero is mined with the RandomX algorithm, and is mined on the CPU. If you load the example settings from the wiki into the builder then there are two pre-configured miners there, one Monero miner (CPU) and one Ethereum Classic miner (GPU). You can change the wallet addresses of those two miners to your own address and build the miner and it will work.

**Comment by Sudococommunity** [comment]
How to change the settings of miner

**Comment by UnamSanctam** [comment]
Start the builder, download the example settings and unzip the .zip file. Then in the builder on the "Main" tab press the "Load" button and select the xml example settings file that was unzipped. Then you can select the XMR and ETC miners and press "Edit".
