### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Nebzouz** [UnamSanctam/SilentCryptoMiner#162]
yo i want to know how i get an ip to mine cause i tryed eu1.ethermine.org:4444 but it's not working

**Comment by UnamSanctam** [comment]
eu1.ethermine.org:4444 will work fine, how are you checking that it's not working?

**Comment by Nebzouz** [comment]
i tryed on my pc and another one with task manager(stealth mode disabled) and the checker.Exe

**Comment by UnamSanctam** [comment]
And it didn't appear in the list? What GPUs do your PCs have?

**Comment by Nebzouz** [comment]
Watchdog Running: No
Miners:
GPUs:
 AMD Radeon RX 6700 XT
Compatible GPU found: True
It was saying that and i got ryzen 5 5600x & 6700xt

**Comment by UnamSanctam** [comment]
Go to the "Main" tab of the builder and press "Save", then zip the file and post it here so I can see your settings.

**Comment by Nebzouz** [comment]
[Yoo.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7744897/Yoo.zip)

**Comment by UnamSanctam** [comment]
Try changing the "Startup" "Filename", if you have things like Riot Vanguard installed then it's been reported that those programs block the Microsoft folder, which would cause it to fail to install.

**Comment by Nebzouz** [comment]
so what should i write cause i have vanguard rn

**Comment by UnamSanctam** [comment]
Any that's not Microsoft, you could try something innocuous like `Service Manager` (replace Microsoft with `Service Manager` in the "Filename" field).

**Comment by Nebzouz** [comment]
it's working! thank you so much bro

**Comment by UnamSanctam** [comment]
No problem, good luck with mining.

**Comment by Nebzouz** [comment]
i have another question, is there a way that when i restart my pc, the software start with the pc cause rn it's not working

**Comment by UnamSanctam** [comment]
As long as "Startup" is enabled it should do that.

**Comment by Nebzouz** [comment]
so weird it doesnt work do you have any fix?

**Comment by UnamSanctam** [comment]
If you run it as administrator then check your Task Scheduler or if you run it a as a normal user check the startup registry entries and see if the miner is there.

**Comment by Nebzouz** [comment]
i see it it is said : The Task has not run yet and at log on any user

**Comment by Nebzouz** [comment]
oh ok i see now it says the system cannot find the file specified

**Comment by UnamSanctam** [comment]
Maybe due to the space, try building the miner with something like `Chrome\updater.exe` as the "Startup" tabs "Filename" and see if that works.

**Comment by Nebzouz** [comment]
ok it's working ty but is that still working if chrome isn't installed on the computer?

**Comment by Nebzouz** [comment]
ok thank you so much bro love u
