### ISSUE TITLE
question

### ISSUE THREAD

**Issue by THEKILERFRIEND** [UnamSanctam/SilentCryptoMiner#1627]
hey is it normal for my miner to only mine gpu? when I get a good pc it usually only mines using gpu and not cpu too even though I have both setup.

**Comment by UnamSanctam** [comment]
No, can you run the checker and post a screenshot?

**Comment by THEKILERFRIEND** [comment]
its not my pc sorry but basically: I got 10 new pcs very legally and I can't really let them know. but basically: when they have a good gpu and a meh cpu (like someone had a i7-10 something k and a rtx 4060) it would mine on their gpu and their cpu wont pop up.

**Comment by THEKILERFRIEND** [comment]
but there is a guy who has a shitty gpu and a decent cpu
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/32984678/9660ea43-1e23-4c33-8799-65cd32059d0c)
and for him it mines on the cpu not the gpu!

**Comment by UnamSanctam** [comment]
Can you show a screenshot of the CPU miner inside the web panel?

**Comment by THEKILERFRIEND** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/32984678/da67b3a2-4b1e-4bc6-9ff7-520b9cf5372e)

**Comment by THEKILERFRIEND** [comment]
I know but its the only one thats mining out of the 7 new pcs i got using cpu.

**Comment by THEKILERFRIEND** [comment]
would it possibly work better if I made 2 different exes and binded them?

**Comment by UnamSanctam** [comment]
No, but try starting the miner on your computer or a VM if you have one and then run the checker. You don't have SSL enabled or anything right? Since you're using the non-SSL port.

**Comment by THEKILERFRIEND** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/32984678/20601f55-412a-4303-85c3-37d5bf0205da)
this is the one without protection

**Comment by THEKILERFRIEND** [comment]
idle wait normally is 3 minutes btw I just wanted it to work quickly on my pc so i could test

**Comment by UnamSanctam** [comment]
Yes then that should work correctly, there has never been a problem with the CPU miner not starting before, only the GPU one (when they don't have a GPU). What happens if you start the one with all your other settings? Do you have a VM to test on?

And you mean that the other XMR miners don't show up in your web panel right?

**Comment by THEKILERFRIEND** [comment]
Okay! sorry for this big amount of problems I just am kinda dumb 💀

**Comment by THEKILERFRIEND** [comment]
wait could it be the issue that I changed the exe it injects to on the 2 miners? I changed the cpu miner to nslookup.exe

**Comment by THEKILERFRIEND** [comment]
and I left the gpu miner (etchash) on explorer.exe

**Comment by THEKILERFRIEND** [comment]
cause the pc that the protected exe mined cpu on so far ran it as admin

**Comment by UnamSanctam** [comment]
You could be having a problem with nslookup.exe itself yes, it's possible that there's either something wrong with theirs or some weird permissions.

**Comment by THEKILERFRIEND** [comment]
Okay would it work if both miners were on explorer.exe?

**Comment by THEKILERFRIEND** [comment]
Thanks and last question: would it let me inject 2x or would it just break?

**Comment by UnamSanctam** [comment]
You mean injecting both with explorer.exe? Then that's totally fine.

**Comment by THEKILERFRIEND** [comment]
Wow thanks bro ill be sure to dono you after I get some money for the amazing stuff you make :D might take a while tho cause im broke rn 💀

**Comment by THEKILERFRIEND** [comment]
thx 4 help sir
