### ISSUE TITLE
Error compiling miner!

### ISSUE THREAD

**Issue by CauseMan** [UnamSanctam/SilentCryptoMiner#1630]
I get this log.

In file included from WindowsUpdateTaskMachineQC-watchdog.cpp:1:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from UFiles\common.cpp:3:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from UFiles\inject.cpp:3:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cc1plus.exe: fatal error: UFiles\Syscalls\*.c: Invalid argument
compilation terminated.
Assembler messages:
Error: can't open UFiles\Syscalls\syscallsstubs.std.x64.s for reading: No such file or directory
In file included from WindowsUpdateTaskMachine-watchdog.cpp:1:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from UFiles\common.cpp:3:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from UFiles\inject.cpp:3:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cc1plus.exe: fatal error: UFiles\Syscalls\*.c: Invalid argument
compilation terminated.
Assembler messages:
Error: can't open UFiles\Syscalls\syscallsstubs.std.x64.s for reading: No such file or directory
In file included from WindowsUpdateTaskMachineQC.cpp:1:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from UFiles\common.cpp:3:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from UFiles\inject.cpp:3:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cc1plus.exe: fatal error: UFiles\Syscalls\*.c: Invalid argument
compilation terminated.
Assembler messages:
Error: can't open UFiles\Syscalls\syscallsstubs.std.x64.s for reading: No such file or directory
In file included from WinUpdateTaskMachineQC-watchdog.cpp:1:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from UFiles\common.cpp:3:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from UFiles\inject.cpp:3:
UFiles\ntddk.h:4:10: fatal error: Syscalls\syscalls.h: No such file or directory
    4 | #include "Syscalls\syscalls.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cc1plus.exe: fatal error: UFiles\Syscalls\*.c: Invalid argument
compilation terminated.
Assembler messages:
Error: can't open UFiles\Syscalls\syscallsstubs.std.x64.s for reading: No such file or directory

**Comment by CauseMan** [comment]
> I'm guessing it couldn't write the files, try starting the builder as administrator or building the miner in another location.

Already running as admin.
Tried a couple locations, same thing.

**Comment by UnamSanctam** [comment]
Also make sure to create an exclusion in your antivirus for the location so that it does not remove it. Also make sure that your OS is 64-bit.

**Comment by CauseMan** [comment]
> Also make sure to create an exclusion in your antivirus for the location so that it does not remove it. And then also make sure that your OS is 64-bit.

Windows 7 64 bit indeed
No antivirus installed

**Comment by UnamSanctam** [comment]
Make sure that you have all the Windows updates for Windows 7 installed, since otherwise Python won't work correctly (which is why the Syscalls generator fails). Or you can try building it on a newer version of Windows.

**Comment by CauseMan** [comment]
> Make sure that you have all the Windows updates for Windows 7 installed, since otherwise Python won't work correctly (which is why the Syscalls generator fails). Or you can try building it on a newer version of Windows.

Yeah I think I'll just try again on another PC
