### ISSUE TITLE
RVN mining

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1639]
how does it work like, if i use rvn mining with gpu how do i do that and also mine xmr on cpu can i not? and should i use different max gpus as to ETC?

**Comment by shainodev** [comment]
can i not build the RVN miner with 1.8gb of free ram?

**Comment by UnamSanctam** [comment]
No you need around 10GB maybe, you can increase your filepage size. You can change the CUDA settings if you want https://xmrig.com/docs/miner/command-line-options#cuda-backend.

**Comment by shainodev** [comment]
> No you need around 10GB maybe, you can increase your filepage size. 

so you mean 10GB free of the "Available" RAM in Task Manager -> Performance -> Memory?

> You can change the CUDA settings if you want https://xmrig.com/docs/miner/command-line-options#cuda-backend.

i dont get it what do i do with those? and i dont get how RVN mining works at all, does it use CPU then? or what

**Comment by UnamSanctam** [comment]
>so you mean 10GB free of the "Available" RAM in Task Manager -> Performance -> Memory?

Yes, or by increasing your page file (the virtual disk RAM).

>i dont get it what do i do with those? and i dont get how RVN mining works at all, does it use CPU then? or what

In xmrig the CUDA usage is controlled by `--cuda-bfactor-hint` and `--cuda-bsleep-hint` and by default in my miner they are set to `12` and `100` I believe. What they mean is quite complicated and you'll have to look it up. I haven't created a "Max GPU" option yet since it's quite complicated and xmrig GPU mining isn't very commonly used (because it isn't very "good").

**Comment by shainodev** [comment]
> In xmrig the CUDA usage is controlled by `--cuda-bfactor-hint` and `--cuda-bsleep-hint` and by default in my miner they are set to `12` and `100` I believe. What they mean is quite complicated and you'll have to look it up. I haven't created a "Max GPU" option yet since it's complicated and xmrig GPU mining isn't very commonly used (because it isn't very "good").

so to mine RVN with the gpu only and no CPU since i want to mine monero with it. i have to enable GPU Mining and set the max cpu to 0?

**Comment by UnamSanctam** [comment]
>so to mine RVN with the gpu only and no CPU since i want to mine monero with it. i have to enable GPU Mining and set the max cpu to 0?

Well RVN doesn't support CPU mining so it doesn't matter really but you can just disable the "CPU Mining" option.

**Comment by shainodev** [comment]
is rvn.2miners.com:6060 TLS or not?

**Comment by UnamSanctam** [comment]
That's the Non-SSL port, the SSL port is `rvn.2miners.com:16060`

**Comment by shainodev** [comment]
> my miner they are set to `12` and `100` I believe. 

is 12 gonna be better than mining with 50% max on etc?

also i wanted to ask is it possible to have the random process injection feature like pureminer does?

**Comment by shainodev** [comment]
also for the password on the settings thing do i put it to blank or "x"

**Comment by UnamSanctam** [comment]
>is 12 gonna be better than mining with 50% max on etc?

Hehe it's complicated.

>also i wanted to ask is it possible to have the random process injection feature like pureminer does?

Sure it's possible, doesn't really change anything though does it?

>also for the password on the settings thing do i put it to blank or "x"

Either one works.

**Comment by shainodev** [comment]
> Hehe it's complicated.

is it more a yay or nae

> Sure it's possible, doesn't really change anything though does it?

i guess not now that i think of it

**Comment by UnamSanctam** [comment]
>is it more a yay or nae

You'd have to check on the computer, seems like it depends.

**Comment by shainodev** [comment]
> You'd have to check on the computer, seems like it depends.

the only reason im switching to RVN is cause it seems to have 2x the profit of ETC on whattomine.org. should i change the --cuda-bfactor-hint to 30?

**Comment by UnamSanctam** [comment]
>the only reason im switching to RVN is cause it seems to have 2x the profit of ETC on whattomine.org. should i change the --cuda-bfactor-hint to 30?

12 is probably the highest you should go, you can reduce it if you want higher usage. The xmrig default is bfactor 6 and bsleep 25 I think.

**Comment by shainodev** [comment]
> 12 is probably the highest you should go, you can reduce it if you want higher usage. The xmrig default is bfactor 6 and bsleep 25 I think.

oh wait does this not work like Max GPU?

**Comment by shainodev** [comment]
?

**Comment by UnamSanctam** [comment]
No it does not, it has to do with the blocks and sleep.

**Comment by shainodev** [comment]
so the lower it is the better (as in more hashrate)

**Comment by UnamSanctam** [comment]
Yes that's correct.

**Comment by shainodev** [comment]
so the default 100 bsleep means that it doesnt mine at all while sleeping or what

**Comment by UnamSanctam** [comment]
No, the bfactor is how many subjobs it should split each job into, and the bsleep is for how many milliseconds it should sleep between each job.

**Comment by shainodev** [comment]
why is the default 100 as to 25?

**Comment by UnamSanctam** [comment]
In my miner the default is 100 to reduce the GPU usage to try and make the computer usable while mining. With the normal xmrig default of 25 it often causes a lot of lag, so I increased the default from 25 to 100 and kept it at that level since that worked fine for me when testing on a GTX 970, GTX 1070 and an RTX 2070.

**Comment by shainodev** [comment]
okay i understand everything now. thank you very much have a blessed day!
