### ISSUE TITLE
When update with Reptoreum will be released? 

### ISSUE THREAD

**Issue by teraso11** [UnamSanctam/SilentCryptoMiner#164]

**Comment by teraso11** [comment]
Please can you answer?

**Comment by UnamSanctam** [comment]
Currently I'm focusing on real life work so that I can get all that done before Christmas, for the miner while I have implemented Ghost Rider (the Raptoreum algorithm) itself there are still other things I have to do, mainly I have to rework the loader since the system calls get detected now.

**Comment by teraso11** [comment]
Can you just upload here xmrig with reptoreum so I can replace in current miner?

**Comment by teraso11** [comment]
?

**Comment by UnamSanctam** [comment]
I have to migrate it out of debug and everything first.

**Comment by teraso11** [comment]
Ok, thank you.
