### ISSUE TITLE
Miner not working as far as I can see

### ISSUE THREAD

**Issue by hooking1** [UnamSanctam/SilentCryptoMiner#1641]
![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133840109/528d1be9-19ea-41d8-add4-f04fde154e68)
This is the loader I am using

![2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133840109/7027837e-e0ca-42af-a258-0ec58cb72bda)

**Comment by UnamSanctam** [comment]
That looks fine, how ling did you mine for before checking the pool?

**Comment by hooking1** [comment]
It's been an hour, I'm not seeing any change in cpu usage in task manager

**Comment by UnamSanctam** [comment]
You have "Stealth" enabled and "Taskmgr.exe" is in the Task Manager, so it will pause whenever you open the Task Manager in order to look normal.
