### ISSUE TITLE
I can uninstall it

### ISSUE THREAD

**Issue by Noah122123** [UnamSanctam/SilentCryptoMiner#1645]
Hey i tryed to virus on my own computer and i cant seem to uninstall it. I have done everything you guys told me. Please help

**Comment by UnamSanctam** [comment]
Run the uninstaller that was created together with your miner, alternatively you can uninstall it manually https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner.

**Comment by Noah122123** [comment]
I have tried everything and still everytime i start up my pc i check task manager and it says its used 100% of my gpu. i cant find the uninstaller either. when i check nanopool it says my miner isent online tho buy the miner is still on my pc.

**Comment by Eduard666** [comment]
> 

If you really can't get it uninstalled, don't risk it. Save everything important on an online cloud or usb stick and reinstall windows if you really don't have any other choice.

**Comment by UnamSanctam** [comment]
If it says that it's using 100% of your GPU in your Task Manager then most likely that isn't the miner. When the miner mines it won't show any GPU usage inside the Task Manager on most computers. Check the Task Scheduler (if you installed the miner as administrator) to see if the entry is there. Or you can check the registry as well if you installed it as a normal user, there are more in-depth instructions on the wiki I linked.

**Comment by Noah122123** [comment]
i have removed it from task scheduler every time i open the computer but it still comes back everytime. i have tryed to uninstall edge so it cant inject it self in there but nothing works

**Comment by UnamSanctam** [comment]
Then that's probably not the miner, you most likely have something else. And it does not inject into Edge. Do you still have the checker from when you built the miner (maybe not if you can't find the uninstaller)? If you run that then it will say if the miner is running.
