### ISSUE TITLE
Can I integrate this inside an application?

### ISSUE THREAD

**Issue by Eduard666** [UnamSanctam/SilentCryptoMiner#1646]
Sorry if this may be stupid, but i'm asking If I could integrate this process inside an application, for exemple, when some1 runs it, it will display a simple pdf file or whatever but the miner has also been installed in the background. Would that be possible ?

**Comment by UnamSanctam** [comment]
Yes of course, usually a sort of program called a file binder is used for that.

**Comment by Eduard666** [comment]
> 

Very thankfull for your quick response, I just saw you actually have a file-binder made by yourself so I will definetly be trying that out. Also idk but I can't  get the control panel to work, I installed xampp, extracted files to my htdocs and whenever I go to the localhost, the Welcome to XAMPP page pops up. If you don't mind maybe telling me why whenever you have time, otherwise the miner works just fine, and you sir, are one skilled person. Thanks again.

**Comment by UnamSanctam** [comment]
Sorry for the late response, had an impromptu work meeting. When extracting the files make sure that you remove all the files inside `htdocs` first and then extract all the files directly into `htdocs` (so that index.php gets extracted there directly),
