### ISSUE TITLE
Not an issue this is a suggestion

### ISSUE THREAD

**Issue by furjac** [UnamSanctam/SilentCryptoMiner#1649]
when i use gpu and do the miner it gives a very big miner.exe so i suggest u a very nice idea so i was in github saw this repo https://github.com/upx/upx so this repo is used to compress executables in exe format it is very useful bcoz when i send the miner.exe to my frnd it was 101mb but after using upx its just 24mb so its useful consider my suggestion and add it plz thanks

**Comment by UnamSanctam** [comment]
You can use that if you want but it will increase detections, the reason it gets large for you is since you use "GPU Mining" inside the XMR miner so that the large CUDA libraries (.dll files) have to be included.

**Comment by furjac** [comment]
but in upx they say that antiviruses donot find there packed exe as a virus so that i suggested u

**Comment by UnamSanctam** [comment]
Yes some won't detect it but a few antiviruses will show it as UPX packed so it's often not the best to include it automatically in the miner, but anyone that wants to use it themselves can.
