### ISSUE TITLE
Silent Miner Pro

### ISSUE THREAD

**Issue by Driadasasa** [UnamSanctam/SilentCryptoMiner#1653]
Unam, we need to create a private version of the miner, which will be enhanced, but access to it will be granted to members who bring a large number of miners. What do you think? xD This version is for everyone, and the private one is for those who bring a good flow of people, and you will increase the reward percentage there. I think everyone would be pleased.

**Comment by FU3X** [comment]
> Unam, we need to create a private version of the miner, which will be enhanced, but access to it will be granted to members who bring a large number of miners. What do you think? xD This version is for everyone, and the private one is for those who bring a good flow of people, and you will increase the reward percentage there. I think everyone would be pleased.

what's your intention on this 💀💀 do you even know c++ or are you just a skid who leaches off of other developers. two people working on a project won't make a difference anyway. maybe slightly faster but it's such a straightforward process of reading documentation then piecing together blocks
