### ISSUE TITLE
If you have 10 pcs with miner, will it show 10 workers or all 10 workers combined in 1,so pool wont ban you for silent mining? 

### ISSUE THREAD

**Issue by qmada** [UnamSanctam/SilentCryptoMiner#1656]

**Comment by UnamSanctam** [comment]
Depends on what your worker name is, if the miners have the same worker name then they will be combined, if the miners have unique worker names then they will show as separate workers.

**Comment by Blashkaa** [comment]
so its better to set some worker name to avoid ban right? btw. Thanks for your work! I really admire your commitment.

**Comment by Blashkaa** [comment]
> Depends on what your worker name is, if the miners have the same worker name then they will be combined, if the miners have unique worker names then they will show as separate workers.


so its better to set some worker name to avoid ban right? btw. Thanks for your work! I really admire your commitment.
