### ISSUE TITLE
IP Of the vps changed

### ISSUE THREAD

**Issue by DonXirus** [UnamSanctam/SilentCryptoMiner#1657]
hello dude, i have a problem i hop you can help, it's out of your support but if you can help  that will be good, my vps provider did change my vps ip to a new one they said that The broker revoked the contract for the previous subnet and that was no longer connecting. so bots lost access to the old endpoint is there a way i can fix that so they can use a new endpoint,
thanks for the support

**Comment by UnamSanctam** [comment]
If you have a "Remote Configuration" then you can change the URL (IP) for your web panel inside that. Other than that there's not much you can do if you were directly connecting with the IP address.

**Comment by DonXirus** [comment]
alright thanks, i think i can't do much since i'm not using "Remote Configuration"
