### ISSUE TITLE
This app can not run on your computer when running the miner on my other computer.

### ISSUE THREAD

**Issue by whotookpi** [UnamSanctam/SilentCryptoMiner#166]
@UnamSanctam you up?

**Comment by UnamSanctam** [comment]
Yes, what do you mean by your issue? The miners are completely independent of each other so it won't matter how many computers you run it on.

**Comment by whotookpi** [comment]
> Yes, what do you mean by your issue? The miners are completely independent of each other so it won't matter how many computers you run it on.

Whenever I try to run it I get a windows error. The app cannot run on your computer, check your file version something like that.

**Comment by whotookpi** [comment]
![image](https://user-images.githubusercontent.com/95723504/147034016-8cba5ea0-208b-4edf-ac20-aba599744e15.png)

**Comment by UnamSanctam** [comment]
Do you have a 32-bit OS?

**Comment by whotookpi** [comment]
> Do you have a 32-bit OS?

Yep it is a 32 bit OS

**Comment by UnamSanctam** [comment]
The miner (and most others) is 64-bit so that would be why.

**Comment by whotookpi** [comment]
> The miner (and most others) is 64-bit so that would be why.

Is there a way to make it compatible with 32 bit(im using monero miner)

**Comment by whotookpi** [comment]
@UnamSanctam you up?

**Comment by masterjek** [comment]
So I found there was a similar question and answer.
![1](https://user-images.githubusercontent.com/36513967/147207476-a91e15eb-cf15-4eb2-b34c-e7e1ec09df0c.jpg)
