### ISSUE TITLE
Hashrate Speed Down

### ISSUE THREAD

**Issue by BugCatch-maker** [UnamSanctam/SilentCryptoMiner#1660]
I am XMR 10~12MH speed

I am using the program fine but there is a bug as described below

There is a bug where the hash rate drops when apache can't fetch information due to server issues.

Even if there is a problem with the server, please fix it so that the hashrate does not drop and operates with the information received from Apache before.

Or make it work well with the information you entered when compiling

please!

**Comment by UnamSanctam** [comment]
There shouldn't really be, the connection should be gathered on a separate thread. And even if it wasn't then the timeout is pretty fast. Can you send some screenshots or anything?

**Comment by BugCatch-maker** [comment]
> There shouldn't really be, the connection should be gathered on a separate thread. And even if it wasn't then the timeout is pretty fast. Can you send some screenshots or anything?

What screenshots will help solve this problem? Tell me in detail

**Comment by UnamSanctam** [comment]
I mean, where do you see a hashrate drop? In the pool? In that case a screenshot of when the hashrate goes down and then rises again when the site goes up again.

**Comment by BugCatch-maker** [comment]
> I mean, where do you see a hashrate drop? In the pool? In that case a screenshot of when the hashrate goes down and then rises again when the site goes up again.

You can't understand this problem from the screenshots
I want to show it as a video, but I hate it because this is an open community

Is there no way to contact you personally?
I can show current problem with anydesk

**Comment by UnamSanctam** [comment]
Only real private contact method I have right now is my email: unams@protonmail.com. But the miner should continue working with the information received from the last time it was able to contact your web panel until the next restart of the miner, and if that information stops working then it will try the settings from when the miner was compiled instead (and also the "Remote Configuration" settings first if you have that).
