### ISSUE TITLE
for rootkit

### ISSUE THREAD

**Issue by FU3X** [UnamSanctam/SilentCryptoMiner#1661]
if infected do you need to reflash your bios?

**Comment by FU3X** [comment]
> No, with the new rootkit (in the newest version) you simply need to uninstall the miner, the rootkit now gets injected when it starts to avoid any of the possible issues with a fully installed rootkit.

@UnamSanctam so i was working with this a while ago and did a windows reinstall, it should be gone right?

**Comment by UnamSanctam** [comment]
>@UnamSanctam so i was working with this a while ago and did a windows reinstall, it should be gone right?

Yes then it's definitely gone.

**Comment by FU3X** [comment]
> >@UnamSanctam so i was working with this a while ago and did a windows reinstall, it should be gone right?
> 
> 
> 
> Yes then it's definitely gone.

btw so all this is—is dropping for let's say the xmrrig binary on the victim's pc and injecting it into another process or something?

**Comment by UnamSanctam** [comment]
Well it's quite a bit more complicated then that, but that's how the miners themselves are run yes. If you know C++ then you can check out the source code in the repository to see what it does.

**Comment by FU3X** [comment]
> Well it's quite a bit more complicated than that, but that's how the miners themselves are run yes. If you know C++ then you can check out the source code in the repository to see what it does.

yeah ik c++, if i were you i would checkout rust, the language itself is engineered in a way that it's actually better for malware development because of rare detection. i had the most obvious malware in rust that did so many pc fuckery, no measures to hide the fact that it's malware and it had very impressive scores from several virus scan apis.

anyway what scripts and lines contain the av disabler? i wonder if it's just commands invoked

**Comment by UnamSanctam** [comment]
>yeah ik c++, if i were you i would checkout rust, the language itself is engineered in a way that it's actually better for malware development because of rare detection. i had the most obvious malware in rust that did so many pc fuckery, no measures to hide the fact that it's malware and it had very impressive scores from several virus scan apis.
anyway what scripts and lines contain the av disabler? i wonder if it's just commands invoked

Well I really dislike the Rust community (that I've seen online so far) which is why I've stayed away from it, but I have thought about testing it. I did see that someone created a SysWhispers version for Rust as well, since I need to bypass all Windows API calls (like the current miner) to avoid detections.

The Windows Defender exclusions commands are located here, it's using the normal calls since they are the most reliable (other methods tend to get patched quickly):
https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Classes/Codedom.cs#L277
https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Resources/Code/miner.cpp#L85

**Comment by FU3X** [comment]
> >yeah ik c++, if i were you i would checkout rust, the language itself is engineered in a way that it's actually better for malware development because of rare detection. i had the most obvious malware in rust that did so many pc fuckery, no measures to hide the fact that it's malware and it had very impressive scores from several virus scan apis.
> 
> anyway what scripts and lines contain the av disabler? i wonder if it's just commands invoked
> 
> 
> 
> Well I really dislike the Rust community (that I've seen online so far) which is why I've stayed away from it, but I have thought about testing it. I did see that someone created a SysWhispers version for Rust as well, since I need to bypass all Windows API calls (like the current miner) to avoid detections.
> 
> 
> 
> The Windows Defender exclusions commands are located here, it's using the normal calls since they are the most reliable (other methods tend to get patched quickly):
> 
> https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Classes/Codedom.cs#L277
> 
> https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Resources/Code/miner.cpp#L85

yeah it is a shitty community , ngl but you don't really need human support for troubleshooting for rust because its made a more complete language compared to others. with the goal of it being used for everything instead of just systems level programming, it can replace javascript, swift and several others. yeah i encourage you to do a good test as it was designed to be the perfect language.

and yes it is really funny 😂 you can't speak in any chat room of the rust topic without 25 year old gay f***ot lovers trying to erp with you in dms

**Comment by FU3X** [comment]
> The Windows Defender exclusions commands are located here, it's using the normal calls since they are the most reliable (other methods tend to get patched quickly):


so i can 
```rust

use std::process::Command;

Command::new("ls")
        .arg("-l")
        .arg("-a")
        .spawn()
        .expect("ls command failed to start");```
with the exclusion command is the "normal" way? i don't need to do anything fancy to make it undetected

**Comment by UnamSanctam** [comment]
Yes that's right though spawning programs using the Windows API is normally pretty detected. But maybe it doesn't matter for only the exclusions. In the miner I use a custom NtCreateUserProcess system call to bypass the Windows API:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Resources/Code/Includes/common.cpp#L8

**Comment by FU3X** [comment]
> Yes that's right though spawning programs using the Windows API is normally pretty detected. But maybe it doesn't matter for only the exclusions. In the miner I use a custom NtCreateUserProcess system call to bypass the Windows API:
> 
> https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Resources/Code/Includes/common.cpp#L8

hmm im starting to wonder if you used a specific resource or forum to find stuff like this, or any search engines?

**Comment by UnamSanctam** [comment]
>hmm im starting to wonder if you used a specific resource or forum to find stuff like this, or any search engines?

Well you can find some user documented things that people have reversed engineered, though that function I had to create myself by reverse engineered and testing for a long time. Trying to figure out what `totalsize` was supposed to be was not fun (had to create a custom RTL_USER_PROCESS_PARAMETERS to make it work on Windows 7). Figuring out the the privilege token spoofing and parent process spoofing parts thankfully didn't take too long though.

**Comment by FU3X** [comment]
@UnamSanctam wanna checkout one of my private projects? it has pretty good and unique concepts apart of it. if you're interested after getting a quick overview maybe you can help a bit or give advice if you want.
as its in early stages, its not the end of the world if its leaked, its like 70% done with little optimizations. if you agree to seeing it first ill invite you to the repo, k?
(i cant say much about it here, but i typed out how it works and other documentation in the repo)
