### ISSUE TITLE
i want to do arabic translation ...

### ISSUE THREAD

**Issue by KK2T** [UnamSanctam/SilentCryptoMiner#1662]
hi unam i want to do arabic translation for this software ... im a native arabic speaker btw . but how can i contribute ???

**Comment by UnamSanctam** [comment]
Thank you, you can find the localization here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/LocalizedControls.xml, what you do is add a `<Text>` block inside each `<Control>` block. For example within the `<Control Name="tabMain">` block you would add `<Text Lang="ar">Arabic Text</Text>` just underneath `<Text Lang="ptbr">Principal</Text>`.
