### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by khayummm** [UnamSanctam/SilentCryptoMiner#1663]
Hello ... it's not showing mining pool...can anyone tell me...why

**Comment by UnamSanctam** [comment]
Do you mean that it's not showing in the mining pool? Can you run the checker that was built together with your miner and then take screenshot of it and post here (you can censor the wallet address if you want)?

**Comment by khayummm** [comment]
![1686997203806490722169025407983](https://github.com/UnamSanctam/SilentCryptoMiner/assets/136894311/7f0b2ffd-6f0a-4d6c-bb6f-b0b39900060b)
Checker is showing everything is running...but in pool...my miner isn't showing

**Comment by UnamSanctam** [comment]
It will only show up when it first finds a share a submits it to the pool https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining but for hashvault that's usually very quick (a few minutes). Are you sure that you don't have anything like the Task Manager or something open? Since because you have "Stealth" it will be paused if so.

**Comment by khayummm** [comment]
I don't know... I'm new to this...should I send you photo of task manager?

**Comment by UnamSanctam** [comment]
No Task Manager should always be closed, that build has "Stealth" enabled which means that the miner will pause when Task Manager is open so that no CPU or RAM usage is visible from the miner while it's open.

**Comment by khayummm** [comment]
So I should create new miner again?

**Comment by UnamSanctam** [comment]
No that's fine, just make sure to close Task Manager if it's open.

**Comment by khayummm** [comment]
How long it will take to show in mining pool?

**Comment by UnamSanctam** [comment]
For hashvault it should be pretty quick, make sure that SSL is enabled and that your network isn't blocking the pool.

**Comment by khayummm** [comment]
![16869986148418266546964773255004](https://github.com/UnamSanctam/SilentCryptoMiner/assets/136894311/54c2cd6f-8312-4558-bb0e-ed534f437376)
Ssl is on

**Comment by UnamSanctam** [comment]
Can you try another pool? Are you on a public network or private one? Since if it's a public one then the pool mining server itself might be blocked.

**Comment by khayummm** [comment]
Oh okay...so I should create private pool from hash vault?

**Comment by khayummm** [comment]
![16869997424332768437549929656416](https://github.com/UnamSanctam/SilentCryptoMiner/assets/136894311/36ad70d6-c35d-455e-96fd-b00786cf9d23)
This setting are right...I don't need to change anything else?

**Comment by UnamSanctam** [comment]
Yes the settings should be alright, I would suggest trying another pool or increasing the "Max CPU" temporarily (to make it show up in the pool faster).

**Comment by khayummm** [comment]
Okay fine I will try to do it ...btw if I change the settings again...do I need to create new miner?

**Comment by UnamSanctam** [comment]
Yes, so run the uninstaller, build the new miner and then run the new one.

**Comment by khayummm** [comment]
What about full settings....I can use them for better results? Or stick with lite?

**Comment by UnamSanctam** [comment]
Full is just somewhat better for persistency (harder for user to detect or remove), so for testing the pool connection you don't need to use it.

**Comment by khayummm** [comment]
Okay...so I can use exodus wallet or make new pool or increase the CPU mining right...after this it should work perfectly

**Comment by UnamSanctam** [comment]
Yes that's correct, try mining to 2miners: `xmr.2miners.com:12222` and see if your miner appears (it might take like 30 minutes of mining depending on your hashrate).

**Comment by khayummm** [comment]
Okay I will try now..let you know the results soon

**Comment by khayummm** [comment]
![16870025334233442909484172410713](https://github.com/UnamSanctam/SilentCryptoMiner/assets/136894311/2ff600e6-b256-4b3a-9645-db4df8d40770)
It's optional to add name of computer?

**Comment by UnamSanctam** [comment]
Yes it's optional.

**Comment by khayummm** [comment]
![16870026691235806771878980655701](https://github.com/UnamSanctam/SilentCryptoMiner/assets/136894311/e057cfa7-81c7-4edd-8517-37e06d609715)
I can just mine with xmr...I can remove etchash?

**Comment by UnamSanctam** [comment]
Yes if you're not planning on GPU mining ETC then you can remove it.

**Comment by khayummm** [comment]
Hello... it's been more than one hour...still it's not showing in miner

**Comment by UnamSanctam** [comment]
On 2miners it says that your address has not submitted any shares? Can you try building the miner without "Stealth" and see if you get any CPU usage in the Task Manager?

**Comment by khayummm** [comment]
All good thanks brother...it showed up in miner...it took 2 hours but still it showed up... but it's mining per day too little..I thinky laptop is worst..so now I can make new miner with finish setting and inject into another pc?

**Comment by UnamSanctam** [comment]
Yes build a new miner with the settings you want and you can use that on other computers, (I would recommend enabling "Add Defender Exclusions" as well).

**Comment by khayummm** [comment]
In settings it's already on add defender....I have question....once I make a file of miner...I can close application? Or application has to open to run miner?

**Comment by UnamSanctam** [comment]
You mean the builder? If so then you can close that. The miner will run all on its own.

**Comment by khayummm** [comment]
Computer will produce 0.5 to 1 USD per day? It's possible?

**Comment by UnamSanctam** [comment]
It depends on the specific CPU of the computer, but the majority would never reach that high because of competition (you are competing against all other miners).

**Comment by khayummm** [comment]
If I have private pool... it's possible?

**Comment by UnamSanctam** [comment]
No the pool does not really matter much.

**Comment by khayummm** [comment]
Hello... it's possible to upgrade this software and try to earn 1 USD per day from gaming computers?

**Comment by UnamSanctam** [comment]
What do you mean by upgrade? But if you mine with the GPU then you can technically get closer to $0.5/day on a really good GPU (if they run their computer 24/7). Here's a GPU mining calculator https://whattomine.com/coins.

**Comment by khayummm** [comment]
I saw one website...he was selling your software but he said he did some chance and coding in software so it can mine more like 1 to 2 USD per day...it can be possible or he is faking?

**Comment by UnamSanctam** [comment]
No then that's probably fake, you can check any websites online for what the hashrates are for different CPUs and GPUs and then put them into mining calculators to see how much you'd earn.

**Comment by khayummm** [comment]
Okay got it...yeah I will check...how much percentage GPU or CPU I have to keep to get like 0.5 per day?

**Comment by UnamSanctam** [comment]
Depends fully on what CPU and/or GPU the computer has.

**Comment by khayummm** [comment]
80% would be good right...?

**Comment by UnamSanctam** [comment]
Sure depends on how much usage you want the miner to use, since the user using the computer will have less resources left for whatever else they're doing.

**Comment by khayummm** [comment]
What settings I should on...so miner will automatically start when computer is be on

**Comment by UnamSanctam** [comment]
For that you should enable "Startup" (in the "Startup" tab).

**Comment by khayummm** [comment]
Startup is enable...I shutdown my pc for 2...and on the pc ..in pool it showed miner is off...and I run for 2 more hours...still in mining pool it's didn't show up...why it's like that ..? Very time it have had to submit shares to show up in pool?

**Comment by UnamSanctam** [comment]
The way pools work is that they only count shares submitted to the pool, that's how they do everything such as calculator hashrate and such. Every time it submits a share is when it will appear in the pool until the interval runs out (for example 10-30 minutes, and the pool only shows miners who have submitted a share within that time). But it should not take 2 hours to find a share, for example if your hashrate is 200H/s then finding a share with 2miners new 480 000 share difficulty (used to be 120 000) would take around 480 000/200=2400 seconds or 40 minutes. Most likely you don't have enough RAM, or maybe CPU cache or free CPU cores to mine, or possibly a "Stealth Targets" program is open.

**Comment by khayummm** [comment]
How to bypass "Stealth tragets"?

**Comment by UnamSanctam** [comment]
>How to bypass "Stealth tragets"?I have installed in someone else computer...so it's not showing properly in pool it's showed up once and miner then got off

You can disable "Stealth" in the miner if you don't want that feature if that's what you mean https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#stealth. But it will only appear in the pool when it finds a share and then remain until the end of the pools statistics interval (and if another share is found then it will appear again).

**Comment by khayummm** [comment]
If I gave 2 miners with different cup percentages.... both will work?or just one will work?

**Comment by UnamSanctam** [comment]
Both will work just fine.

**Comment by khayummm** [comment]
Hello I have connected to 5 or 6 computer....why it's not showing in pool? When I install I checked with checker and all was good and stealth traget is of so no files can stop miner....and rootkit enable so it can hide properly....what I did worng ... I'm not understanding

**Comment by UnamSanctam** [comment]
Can you run the checker again and post what it says now? And can you link the pool page with your wallet address (unless you want to keep it anonymous)?

**Comment by khayummm** [comment]
I didn't take photo of it... because I injected in another computer....watch dog show yes...and all was good...what mistake I did..I don't understand

**Comment by UnamSanctam** [comment]
Can you send a link to the pool and wallet address? And if you run the checker on a test computer/VM that has the miner installed that will work as well. I just need to know the settings.

**Comment by khayummm** [comment]
https://xmr.2miners.com/account/4AjgLzHN6XSWnhHce2rzUGjbwsjxrquupPQcnd2HYhp2V35H2k97TTmBLjYcQQHhyX2u66B9pDNtW84Zp4PHnrCz3ivcfbA#farms this the link and wallet address 4AjgLzHN6XSWnhHce2rzUGjbwsjxrquupPQcnd2HYhp2V35H2k97TTmBLjYcQQHhyX2u66B9pDNtW84Zp4PHnrCz3ivcfbA

**Comment by UnamSanctam** [comment]
And the computers that are supposed to be mining are on and running?

**Comment by khayummm** [comment]
They are running...did you check the settings?

**Comment by UnamSanctam** [comment]
Since you have disabled "Stealth" does it use any CPU if you open the Task Manager? Also, what CPU and how much RAM does the computer have? Since the RandomX algorithm has requirements. You could also install a local web panel to see what it's doing: https://github.com/UnamSanctam/UnamWebPanel.

**Comment by khayummm** [comment]
![IMG-20230625-WA0002](https://github.com/UnamSanctam/SilentCryptoMiner/assets/136894311/791051f0-1653-4872-ba2b-af0f2928b48e)
Hel
![Screenshot_2023-06-25-11-18-59-040_com whatsapp](https://github.com/UnamSanctam/SilentCryptoMiner/assets/136894311/cdbd389a-93da-4c5e-b9f8-d5b33e578760)
lo it's  showing error like this...why?

**Comment by UnamSanctam** [comment]
>lo it's showing error like this...why?

Try adding your build folder to your antivirus exceptions, usually that happens when your antivirus is removing the compilers or build files.
