### ISSUE TITLE
I`m new and need some clearification

### ISSUE THREAD

**Issue by BigGod12** [UnamSanctam/SilentCryptoMiner#1664]
Hi everyone, I have  a new hp pavilion 14 core i7. which minner can i used that could be profitable for me and can i install virtualbox to run it in some ubuntu and windows, i already upgraded the laptop to 64gb ram also, thank you

**Comment by UnamSanctam** [comment]
Sure you can mine on that, though if you run it in a VM then you can't mine on the GPU (because most VMs do not support GPU usage). Though mining on a single computer is usually not too profitable, you can find Monero hashrate benchmarks here https://xmrig.com/benchmark that you can input into any Monero mining calculator. And for GPU mining you can look here: https://whattomine.com/coins.

**Comment by BigGod12** [comment]
thank you
after checking through the https://xmrig.com/benchmark and checking my processor from the list with the monero mining calculator.. this is showing making $193/day profit,
![Screenshot_2023-06-18_21_15_16](https://github.com/UnamSanctam/SilentCryptoMiner/assets/89391838/b31a19ad-e2e0-4928-90ba-24309d894291)
And after checking the hash rate in the calculator i got this ..
![Screenshot_2023-06-18_21_21_57](https://github.com/UnamSanctam/SilentCryptoMiner/assets/89391838/7a9abd74-5263-4d39-b3a2-a116572bf847)
please is this correct ??thank you

**Comment by UnamSanctam** [comment]
You need to wait a bit before posting for the screenshots to upload, but no that profitability is not correct. Make sure that you have the calculator set to the correct unit (H/s and not something like MH/s).

**Comment by BigGod12** [comment]
oh okay...this is the pic
![photo1687138949](https://github.com/UnamSanctam/SilentCryptoMiner/assets/89391838/816f7b0d-c88a-4019-b74d-de97188eea43)
![photo1687138949 (1)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/89391838/91fcd130-c67b-4f2b-8b67-ce4b68360000)

**Comment by BigGod12** [comment]
it shows i cant have any profit when i change it to H/s

**Comment by UnamSanctam** [comment]
The values on the site are in H/s so that would be correct (if you change it to H/s), you have it set to 1200 W energy consumption though.
