### ISSUE TITLE
ravencoin failing

### ISSUE THREAD

**Issue by neveronsere** [UnamSanctam/SilentCryptoMiner#1668]
im mining xmr + ravencoin, xmr works but ravencoin does not, ive also tried disabling xmr and mining cpu + gpu on ravencoin but it doesnt use either, not sure whats going on but i hope theres a fix

**Comment by UnamSanctam** [comment]
Do you have a GPU that can mine it? And KawPow tends to not work very often, but not a single KawPow (Ravencoin) miner on the internet works for me on any of the 3 computers I've tested them on so no one else have been able to fix it either.

**Comment by neveronsere** [comment]
yes ive tried many, pretty much all the nvidia ones up to 3080

**Comment by neveronsere** [comment]
what would you recommend mining for gpu if rvn doesnt work?

**Comment by UnamSanctam** [comment]
UBQ or ETC probably, they also cause a lot less lag and heat than KawPow usually does (since they are less core heavy).

**Comment by neveronsere** [comment]
alright ill try them out, thanks for the help
