### ISSUE TITLE
Couple of questions since I'm dumb

### ISSUE THREAD

**Issue by A3ima** [UnamSanctam/SilentCryptoMiner#167]
For the Startup option if i were to select temp
and put this in the file name would it work ? 
1ED3B533-AABC-4388-BA37-F9111B49292E\Windows-Defender\Svchost.exe

**Comment by AspectKraken** [comment]
Im using Nano Pool to make my miner for Ethereum
 so where is asks for Wallet Address 
Would this work?
0x535899C84jf04j6b14bb2B4c21FBc598361E37cB.ETH-Miners/tTLY8sfjfsjfhsfsVkZuSFrwsec7tkXetUZqprNxKgbBAuFYArbKmPc5t9

Im not using my real password or Monero Wallet in this example

**Comment by UnamSanctam** [comment]
Yes that filename should work fine, and yes entering that into the "Wallet Address" field would be correct though I believe that password might be too long.

**Comment by AspectKraken** [comment]
what is the maximum a password could be

**Comment by AspectKraken** [comment]
and if i selected bypass windows defender
would they be able to go to excluded files and see it?

**Comment by UnamSanctam** [comment]
Password should be at least 6 characters or longer, but they haven't written any maximum on the site at least. And yes they can see the excluded folders inside Windows Defender, though if they remove them and the miner gets removed then the watchdog will re-add the exclusions and restore the miner.

**Comment by AspectKraken** [comment]
and lets say if i hypothetically ran the miners on dozens of people that are neither happy or ok with me running the miner
would rootkit truly make it invisble in task manager?

**Comment by AspectKraken** [comment]
and if so what are the chances it will run into bugs and or cause other problems like the miner not running?

**Comment by UnamSanctam** [comment]
Yes it would be fully invisible in the Task Manager (and everything else), though the rootkit feature is still experimental (since it requires testing on a lot of computers) so some features like the watchdog have bugs on some computers in the current version.

**Comment by AspectKraken** [comment]
are u working on the next update and would donations speed up the time until the next update

**Comment by UnamSanctam** [comment]
> are u working on the next update and would donations speed up the time until the next update

Yes I'm always working on the next update/new features. Generally donations can speed up the process (since I can allocate more time towards it) but not really in this instance since the reason it has taken longer than normal is due to a lot of real life work which can't be prioritized away even if I were to get donations.

**Comment by UnamSanctam** [comment]
New update has now been released.
