### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1670]
Good evening Unam. Do you plan to release new updates? I checked today and it looks like the miner was detected by windows defender

**Comment by UnamSanctam** [comment]
I'm currently working on trying to implement KawPow/ProgPow directly into the ETH/ETC/UQB miner using only OpenCL to avoid having to use the huge CUDA NVRTC library for Nvidia. To do that I've had to rewrite most of the miner, not sure when I'll fully be done but right now I just finished getting the kernel to fully work so hopefully I'm getting close. In terms of the injector/installer I've already gotten that undetected again as far as I can tell.

This is my current preliminary change log:

- Added new ProgPow (progpow) algorithm
- Added the KawPow (kawpow) algorithm directly into the GPU (ETH/ETC/UBQ) miner
- Implemented KawPow and ProgPow using only OpenCL for both Nvidia and AMD to bypass the large CUDA NVRTC library
- Rewrote much of the GPU miner to improve reliability and support for multiple algorithm families
- Removed KawPow (kawpow) algorithm from the XMR miner
- Re-added the Panthera (rx/xla) algorithm
- Greatly improved reliability of miners
- Removed unused common helper functions
- Changed unicode string initialization from a macro to a function to reduce final code
- Changed string formatting from using the built-in Windows API to instead use a much smaller custom function
- Improved RandomX database regeneration speed when leaving "Stealth" on pools with infrequent new jobs
- Modified some miner builder build tools to allow spaces and unicode character inside paths
- Fixed weird default "Stealth on Fullscreen" configuration value when "Run as System" was disabled
- Fixed possible null terminator string length counting problem inside the GPU checking function
- Reduced unnecessary recursive directory creation stack size
- Changed miners execution state to no longer always semi-block sleep mode on some computers
- Updated the rootkit to a new version
- Updated miners
