### ISSUE TITLE
[enchancement] Stealthy process killer (based on idleness or window visibility)

### ISSUE THREAD

**Issue by possessed-client** [UnamSanctam/SilentCryptoMiner#1672]
I haven't really checked how the current process killer works, but I never used it because I assumed it kills the target processes periodically and very quickly (ignore/delete this post if this is not actually the case), which is very noticeable and will cause the user to fix the issue.
A better way would be triggering the killer only after a customizable idleness period (for example, some people like keeping the Task Manager open - it usually is in the stealth list, so mining never happens).

Next level would be killing the target process even if the PC is not idle, but based on heuristics on whether the killing will be noticed by the user - how soon after process was started, whether it's visible on the screen etc.
But just the idleness based killing would be a significant improvement, and shouldn't be too hard to implement or cause performance issues. Don't know about the latter option, though.

**Comment by UnamSanctam** [comment]
Sure making it only kill during idle is doable (heuristically isn't though in any good way I can think of), but where would that be located inside the builder GUI? And what would it be called? Since it would need to be a separate feature from the current one because the current one is needed by some people.

**Comment by possessed-client** [comment]
> Sure making it only kill during idle is doable (heuristically isn't though in any good way I can think of), but where would that be located inside the builder GUI? And what would it be called? Since it would need to be a separate feature from the current one because the current one is needed by some people.

I suppose above Stealth On Fullscreen there could be a toggle for Idle Kill with a small field to enter minutes after idle. If toggled, it would replace the standard instant process killer and use the same process names from the currently existing process kill targets list.
