### ISSUE TITLE
Big botnet problem ( human error ) 

### ISSUE THREAD

**Issue by pepe123456789-cmyk** [UnamSanctam/SilentCryptoMiner#1673]
Hey Unam I desperately need your help so my exodus wallet has been compromised; the XMR wallet I’m using for the miner is in that exodus wallet. 
I'm totally fucked. So basically the wallet is compromised and my 500KH are basically being gifted to the crook. I still have access to the bots on my loader but I don’t have the uninstalled anymore AHHHH IM actually so frustrated :( 
So my questions would be: do you have a general miner uninstaller? Something universal? I tried making another miner payload with the same name and it didn’t uninstall :( 
Do do you have any kind of general uninstaller executable? please and thank you! 
Unam I swear you help me resolve this I’m donating some XMR immediately.

**Comment by UnamSanctam** [comment]
A full general uninstaller can technically be possible with some false positives but it's quite difficult to create. What you can do is remove the entry inside the "Task Scheduler" that belongs to the miner and then instantly restart the computer, are you able to do that on the computers?

**Comment by pepe123456789-cmyk** [comment]
The problem is I don’t have rat access to these PCS so I have to crate an executable to run on the bots so they can uninstall; I don’t mind if it’s a hard process just please tell me how if you don’t mind I would really appreciate it :) 
Thank you for responding so quick!

**Comment by pepe123456789-cmyk** [comment]
I’m basically fucked

**Comment by pepe123456789-cmyk** [comment]
God I should have added remote control I’m an idiot

**Comment by UnamSanctam** [comment]
Is crashing the computer(s) acceptable or not?

**Comment by pepe123456789-cmyk** [comment]
What if I create a new miner and run it on the bots; would it replace the old miner payload?

**Comment by UnamSanctam** [comment]
If it has the same "Startup" settings then yes, but both miners will still be running until the computer is restarted. And if something happens to the old miner that's still running before the next restart then the old watchdog could replace the new miner with the old one.

**Comment by pepe123456789-cmyk** [comment]
So you’re telling me as long as the startup settings are the same the new miner will basically override the startup settings of the old miner correct?

**Comment by UnamSanctam** [comment]
Yes that's correct, if the "Entry Name", "File Name" and "Save Path" are the same then it will overwrite both the Task Scheduler (or registry) entry and the miner file itself.

**Comment by pepe123456789-cmyk** [comment]
I will let you know if it works :)
