### ISSUE TITLE
GPU mining 0 H/s.

### ISSUE THREAD

**Issue by moshiax** [UnamSanctam/SilentCryptoMiner#1675]
XMR mining on the processor works well, but mining on the video card does not work at all, and if I mine monero with GPU mining enabled, the processor also stops mining (0 H / s.), that is, it consumes 50% of the processor power but the hashrate is all still 0. And yes, the video card has 6 GB of video memory, I tried different pools and different coins, but everywhere I got 0 H / s. if GPU mining enabled. Is there a way to fix this?

**Comment by UnamSanctam** [comment]
Please run the checker and post a screenshot of it here.
