### ISSUE TITLE
Pastebin and Server Problems

### ISSUE THREAD

**Issue by Gomez1996** [UnamSanctam/SilentCryptoMiner#1676]
Hello, I have two questions.
Anytime I want to add the configuration of the JSON files I get an error message that the JSON file is invalid

These are my settings
{
    "algo": "rx/0",
    "pool": "stratum+ssl",
    "port": //[randomxmonero.auto.nicehash.com](http://randomxmonero.auto.nicehash.com/),
    "wallet": "3EUwWe4P6CN33K7jftuwNyApp7gevY8r43.{COMPUTERNAME}",
    "password": "x",
    "nicehash": true,
    "ssltls": true,
    "max-cpu": 50,
    "idle-wait": 1,
    "idle-cpu": 90,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}

And also when I enable remote configurations the miner won't start. but when I disable the miner starts I don't know why I have tried it multiple times  

Here are my Pastebin settings https://pastebin.com/raw/Bbh1FyvH

My unampanel is [earn.onlinesero.com](http://earn.onlinesero.com/) which is working correctly 

![Support](https://github.com/UnamSanctam/SilentCryptoMiner/assets/70133137/98c79278-b041-4c5a-ba7c-5807e0b5e41a)

**Comment by Gomez1996** [comment]
![Support](https://github.com/UnamSanctam/SilentCryptoMiner/assets/70133137/a9587e52-2c63-40f9-9b4a-27037139b786)

**Comment by Gomez1996** [comment]
![Support 2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/70133137/5c756b4d-34c4-444a-829b-2cda24ebac24)

**Comment by UnamSanctam** [comment]
It's because your pool is wrong, remove the `stratum+ssl://` part.

**Comment by Gomez1996** [comment]
That means on the builder the json part has a bug. i have also seen at the port area it doesn't add the two quotation marks

**Comment by Gomez1996** [comment]
![support 4](https://github.com/UnamSanctam/SilentCryptoMiner/assets/70133137/dcea5d16-8829-476b-b1c6-694062b1de0e)

**Comment by UnamSanctam** [comment]
That's because the `stratum+ssl://` has a `:` in it which is usually for the separation of the pool and port. It doesn't matter because your pool is wrong anyways, you need to remove `stratum+ssl://` (that is only for some types of miner, for example the ETC miner uses that format but does it automatically).

**Comment by Gomez1996** [comment]
I have done the changes. but seems I have no luck in firing it up. below is the screenshot and I copied the exact json files. i just saw an unrecognized device connecting on my end were you able to connect?

![support 5](https://github.com/UnamSanctam/SilentCryptoMiner/assets/70133137/2564b09a-dc03-4e25-9b07-9ae4158a84be)

**Comment by Gomez1996** [comment]
And also on the dashboard. The miners are active on the miners page but on statistics, it shows all the devices are offline

**Comment by UnamSanctam** [comment]
Does it show a hashrate on the web panel? It needs to find a share before it appears on the "pool" (NiceHash isn't technically a pool but it works pretty much the same from the user end) https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining.

**Comment by Gomez1996** [comment]
My problem only comes when I enable the remote configuration.
That's when it doesn't appear

**Comment by UnamSanctam** [comment]
It does not show any hashrate in the web panel when you enable "Remote Configuration"?

**Comment by Gomez1996** [comment]
Yes.
It's completely offline.

**Comment by UnamSanctam** [comment]
Can you post a screenshot of your checker now (so I can see the new settings)?

**Comment by Gomez1996** [comment]
![support 7](https://github.com/UnamSanctam/SilentCryptoMiner/assets/70133137/e793089f-860e-40f6-bd90-cbcb31048bc8)


I have tried mimicking almost every  code 

my webpanel is earn.onlinesero.com  password i have set back to Unamsanctam
Please check what might be wrong

**Comment by Gomez1996** [comment]
The active machine is a different one but i have removed it for easier troubleshooting

**Comment by UnamSanctam** [comment]
It is working right now on your web panel, did it start working?

**Comment by Gomez1996** [comment]
It's not working. I have just disabled the remote configuration. I can work
well without it. I really appreciate you taking your valuable time and
answering my questions

**Comment by UnamSanctam** [comment]
Well if you remove `raw` then it can't read it and will just skip it, so yes it would make it the same as not having it enabled. But it looks like it works with the correct "Remote Configuration" enabled just fine, or what is the problem?

**Comment by Gomez1996** [comment]
The problem is when I enable it it won't show in my webpanel or add raw

**Comment by UnamSanctam** [comment]
Can you build one with the raw address and then run the checker and post a screenshot here (or the latest build)? Everyone usually has both the "Remote Configuration" and web panel at the same time (mostly in case something happens to the web panel).

**Comment by Gomez1996** [comment]
![support 8](https://github.com/UnamSanctam/SilentCryptoMiner/assets/70133137/078c8e5c-a7c6-4ca5-acef-f959c127b921)

unfortunately, when I add raw the miner doesn't pop up in the web panel

**Comment by UnamSanctam** [comment]
Hmm, that is weird, the two systems are not connected so it shouldn't matter. It should only matter if it contains the `"api-endpoint"` option but yours doesn't so I'm not sure why.

**Comment by Gomez1996** [comment]
It's okay. Let's be hopeful nano pool settings won't change soon

**Comment by Gomez1996** [comment]
hello someone logged in to my account and changed settings. Am so dumb I didn't change the password after sharing it on here.  they were mining for someone else.
they changed the json files at the configuration area
![support 11](https://github.com/UnamSanctam/SilentCryptoMiner/assets/70133137/567d056a-5a5c-47dd-b6e6-18c009a3a83c)

the 2miner pool isn't mine I think is for the person who logged into my account. that means if something happens to nano pool I can easily change it in my web panel the Pastebin one is not that important.

**Comment by UnamSanctam** [comment]
Haha, that should be fine. You can just change the configuration back to your own. If they also changed the "Remote Configuration" or web panel URL ("API Endpoint URL") via the configuration (there are two options to do that) then those will also go back to your web panel and "Remote Configuration" the next time the miners are restarted.

**Comment by Gomez1996** [comment]
Thanks for the tip!

**Comment by Gomez1996** [comment]
Hello, everything worked well. The Pastebin with raw included also worked. the miners have been updating continuously. I think the web host was blocking or something. am locally hosting with my pc and port forwarding so that I can reach the panel remotely.
