### ISSUE TITLE
Plz help with this doubt

### ISSUE THREAD

**Issue by furjac** [UnamSanctam/SilentCryptoMiner#1682]
bro u said that there is xmrig proxy in this miner how to and where can i enable it help me im unable to find it

**Comment by masterjek** [comment]
Xmrig Proxy this is a separate program, it is not in the silent miner. As far as I know and do it myself, you can send all workers to the pool using Xmrig Proxy.

**Comment by UnamSanctam** [comment]
Yes as @masterjek said xmrig-proxy is a separate program that you run as a proxy between the pool and the miners, you simply connect the miners to the proxy instead of the pool.

**Comment by furjac** [comment]
like how plz tell me

**Comment by masterjek** [comment]
I do it like this:
1. Buy vps server.
2. On the VPS server I run Xmrig Proxy
3. In config Xmrig Proxy indicate the following:
- "host": "Ip Adress Your VPS Server",
- "port": Any Port,
- "tls": false or true - if your use ssl connection
- "pools": [
        {
            "algo": "rx/0",
            "coin": "monero",
            "url": "Your Pool:Port pool",
            "user": "Your Wallet Address",
            "pass": "x",
            "rig-id": 1,
            "keepalive": true,
			"enabled": true,
            "tls": true,
            "tls-fingerprint": null,
            "daemon": false
4. In the builder, when you collect the miner, in the pool field, specify the IP address of your VPS server and port.
![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/17ead6be-b757-4292-9e0c-e1d62f75ae37)
That's all now the miners will connect to your VPS server where it is launched Xmrig Proxy, and the proxy, in turn, will unite all the workers and send the mined balls to the pool.
