### ISSUE TITLE
not mining

### ISSUE THREAD

**Issue by qmada** [UnamSanctam/SilentCryptoMiner#1684]
checker says that miner is running, but it uses 0% cpu in task manager(its not stealth) and nothing on pools too
![screen of checker](https://github.com/UnamSanctam/SilentCryptoMiner/assets/110357110/b5e3e75e-4d71-40ba-97f8-66a10e534120)

**Comment by UnamSanctam** [comment]
You are you using the non-SSL port `2222` while you have SSL enabled. You should use the SSL port `12222` instead.

**Comment by qmada** [comment]
thank you
