### ISSUE TITLE
what pool do you recommend for etc?

### ISSUE THREAD

**Issue by zuzuste** [UnamSanctam/SilentCryptoMiner#1690]
and do i need to add any settings ?

**Comment by UnamSanctam** [comment]
Usually 2miners, though they did increase their share difficulty recently so now I'm not sure which is the best really. All of them have their own downsides.

**Comment by zuzuste** [comment]
does it need any special worker name?

**Comment by UnamSanctam** [comment]
No, nothing extra is needed.

**Comment by zuzuste** [comment]
thank you for the quick response, so i just put the pool and adress? i leave everything blank?

**Comment by UnamSanctam** [comment]
Yes that's enough, you can see how it's done in the example settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings.

**Comment by zuzuste** [comment]
tysm for the help. ill tell you if everything works !

**Comment by zuzuste** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/117950912/e322b1ed-74c8-4053-b20d-93d38fd00e6d)
is this ok?

**Comment by UnamSanctam** [comment]
Yes that's fine, though you can change the "Connection Scheme" to `stratums` and the "Pool" to `etc.2miners.com:11010` if you want to use SSL (a secure connection) to the pool.

**Comment by zuzuste** [comment]
is there a problem if the gpu is not supported? its a rx5500xt

**Comment by UnamSanctam** [comment]
Does it say that it's not supported in the checker? And the miner has some different checks for the GPU name so possibly it might still work in the miner because some AMD card don't include AMD as the vendor.

**Comment by zuzuste** [comment]
yes it said its not supported,

**Comment by zuzuste** [comment]
i forgot to say, if i try to mine xmr it works perfectly.

**Comment by UnamSanctam** [comment]
You can try mining ETC and see if the GPU usage goes up in something like MSI Afterburner (Task Manager does not show that kind of GPU usage).

**Comment by zuzuste** [comment]
im trying on a supported gpu rn with stratums and the new pool adress. i hope it works

**Comment by zuzuste** [comment]
it doesnt seem to go up on msi afterburner, maybe its because its a older gpu but it still shows that it supports it in the checker. + the miner still doesnt work. should i try putting a worker name and the password x?.
let me know any other solutions.

**Comment by UnamSanctam** [comment]
Can you post a screenshot of the checker? How much free VRAM does the GPU have (GPU memory in MSI Afterburner)?

**Comment by zuzuste** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/117950912/c81cb572-c290-4b03-a4d0-f7e32ad8658d)
is this ok?

**Comment by UnamSanctam** [comment]
Hmm well the miner isn't running there, and scroll down to GPU usage and/or GPU memory down in the box below (that's where you see usage and memory). Can you show a screenshot of your builder (or send the save file)? And does it work if you use the example settings?

**Comment by zuzuste** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/117950912/fb67b75f-e41e-477e-8238-e5a3c8b6f94f)
*this is what it says on the other gpu* should be mining right?

**Comment by UnamSanctam** [comment]
Yes then that GPU should be mining, you can see the GPU usage and GPU memory in MSI Afterburner in the graphs area.

**Comment by zuzuste** [comment]
you want a screenshot of that?
 on the newer gpu

**Comment by UnamSanctam** [comment]
Sure, and also make sure that you don't have Task Manager or anything like it open since then the miner will pause due to "Stealth" (because Task Manager is inside the "Stealth Targets").

**Comment by zuzuste** [comment]
task manager is off, 1 second

**Comment by zuzuste** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/117950912/446dc1b8-f328-4530-9629-ae8bc8916592)
he is also playing league so idk it might cause problems

**Comment by UnamSanctam** [comment]
Can you scroll down to GPU usage and GPU memory?

**Comment by zuzuste** [comment]
it appeared in 2miners now.
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/117950912/e9017ff1-3245-41fb-abdc-d9f729f45bec)
i just had to wait 30 minutes+ ig

**Comment by zuzuste** [comment]
does it look fine?

**Comment by zuzuste** [comment]
hashrate is 0 btw

**Comment by UnamSanctam** [comment]
Alright great then it's working. It will show up in the pool whenever it finds a share, which can be a while since 2miners has quite a high share difficulty now.

>hashrate is 0 btw

The hashrate shown in the pool isn't the actual hashrate of the miner https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-the-hashrate-shown-on-the-pool-different-from-what-i-expect-or-from-what-is-shown-in-the-web-panel. Since it did appear in the pool then we know it's mining.

**Comment by zuzuste** [comment]
perfect, thank you so much for the help. now i just set up the web panel

**Comment by zuzuste** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/117950912/c17649e0-4f32-4c2e-8411-41adb615004b)

**Comment by zuzuste** [comment]
should i see anything here?

**Comment by UnamSanctam** [comment]
If you want the miner to appear in the web panel then you should enter the URL to the web panel inside the miners "API Endpoint URL" option. If the web panel is just on your local computer (only for local miners) then you can enter `http://localhost/api/endpoint.php` into the option.

**Comment by zuzuste** [comment]
oh, okay ill keep it in mind

**Comment by zuzuste** [comment]
off topic question, do you have a twitter?

**Comment by UnamSanctam** [comment]
No I don't have a Twitter, or really anything else like that either.

**Comment by zuzuste** [comment]
oh okay, i just wanted to ask you some questions about coding and stuff since i really want to learn.

**Comment by zuzuste** [comment]
didnt mean to close oops
