### ISSUE TITLE
Ravencoin GPU settings

### ISSUE THREAD

**Issue by Blashkaa** [UnamSanctam/SilentCryptoMiner#1691]
Hello, as i know RVN coin is GPU coin but there is no option to select MAX GPU usage instead of Max CPU
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/98757977/dcc687c3-5ab5-4e60-8280-fda38d817887)

**Comment by UnamSanctam** [comment]
Yes because it uses the xmrig miner so there is no inherent GPU control there. Though in the next miner version KawPow gets directly into the ETH/ETC/UBQ GPU miner instead.
