### ISSUE TITLE
Text is not showing up

### ISSUE THREAD

**Issue by NullRien** [UnamSanctam/SilentCryptoMiner#1692]
im trying to run the exe but all the words and text are just blocks
![Screenshot from 2023-07-04 15-17-16](https://github.com/UnamSanctam/SilentCryptoMiner/assets/27176622/b9f238c5-80d7-4b43-ab0c-f242c78735fb)

**Comment by NullRien** [comment]
its not only on that page its on all of them

**Comment by UnamSanctam** [comment]
Maybe you don't have the font? I've never seen that happen, are you using some kind of VM?

**Comment by NullRien** [comment]
i am using debian and launching it with wine, can you send me the font you use?

**Comment by UnamSanctam** [comment]
Sorry of the late response, I have not been at home. It's using the standard Windows Segoe UI font I believe.
