### ISSUE TITLE
Question Auto Start

### ISSUE THREAD

**Issue by Fluffy-Horse** [UnamSanctam/SilentCryptoMiner#1694]
Does the miner really starts when windows gets booted?

**Comment by UnamSanctam** [comment]
If you enable "Startup" then yes it will.

**Comment by noOne90** [comment]
Hi Unam,

For some reason miners are not running when "Startup" is selected i.e. 

When I build the miner with exactly the same config as startup but not enabling it, miners mine fine and I can see it in the pool and checker.exe 

But if I rebuild with exactly the same config just enabling startup, miners are not mining and checker.exe shows nothing.

**Comment by UnamSanctam** [comment]
Sorry for the very late response, my notifications stopped working.

Could you show a screenshot of your "Startup" settings? There aren't any known problems with the installation so that should work fine. Did you accidentally disable the "Run miner after install" inside the "Advanced Options"?

**Comment by Fluffy-Horse** [comment]
No worries man. Yes I disabled  "Run miner after install" inside the "Advanced Options", but manually ran the program after.

I'll send a screenshot across whenever I get around to it - thanks

**Comment by Fluffy-Horse** [comment]
Hi Unam screenshot below with the "Startup" settings I use.
As mentioned only startup seems to not work, if i run with exactly the same settings but disabling start-up it works.

![Screenshot 2023-08-05 164529](https://github.com/UnamSanctam/SilentCryptoMiner/assets/138724692/b64e4faa-6234-4774-8cb0-2007f5182b78)

**Comment by UnamSanctam** [comment]
Try removing "Windows" from the folder name, some game anti-cheats and other similar programs can blacklist those sorts of names. And you should have "Run miner after install" set to "On" if you want it to start directly after installation and not only when the computer starts.

**Comment by Fluffy-Horse** [comment]
Removing "Windows" didn't help I'm afraid. Not sure what could be wrong...

**Comment by UnamSanctam** [comment]
Is the Task present inside the Task Scheduler?

**Comment by Fluffy-Horse** [comment]
Bollocks. Right, so I could see the Task in the taskschd.msc and after running a reboot of the VM I can confirm the file ran and can see it in the checker as well.

Problem was not restarting the machine after running the miner. Appreciate your time and help.
