### ISSUE TITLE
Why isn't Ethereum Classic being mined?

### ISSUE THREAD

**Issue by kolvyXD** [UnamSanctam/SilentCryptoMiner#1695]
I'm running a pool on 2miners "etc.2miners.com:11010" with a "stratums (SSL/TLS)" connection. In the end, I waited for about an hour and there were still no statistics and mining etc on 2miner.

**Comment by UnamSanctam** [comment]
Sorry for the late response, I've not been home. Can you run the checker and then post a screenshot of it here?

**Comment by kolvyXD** [comment]
Yes

**Comment by UnamSanctam** [comment]
The miner does not seem to be installed there.
