### ISSUE TITLE
Point miners to P2pool

### ISSUE THREAD

**Issue by gamesaccounta** [UnamSanctam/SilentCryptoMiner#1697]
Hello Unam, I want to run a P2pool node to point my miners there but I dont want to expose my public IP, what can I do?

**Comment by UnamSanctam** [comment]
Sorry of the late response, I have not been at home. There isn't much you can do about exposing your IP, since p2pool uses your own hosted node for it. But you can you a VPS or a VPN that supports port forwarding to get around that, though that costs money which might not be feasible for you. If you only have a small amount of miners then using a "normal" public pool might be better.

**Comment by gamesaccounta** [comment]
Yes but I cant find a VPN with custom port forwarding because I need to forward the 18080, 18081 and 37889 ports

**Comment by UnamSanctam** [comment]
Only the p2pool mining port actually needs to be open (though opening the other ones can make the connectivity better), and that can be changed to whatever you want as far as I'm aware. You could also host an xmrig-proxy between the p2pool and the miners, but directly mining to the p2pool is better.

**Comment by gamesaccounta** [comment]
Okay I will test to change the P2pool port. Thanks I will relpy you later

**Comment by gamesaccounta** [comment]
How can I change P2pool port?

**Comment by UnamSanctam** [comment]
I think it's this command `--stratum 0.0.0.0:PORT` with `PORT` being whatever port you want to use.

**Comment by gamesaccounta** [comment]
So, p2pool.exe --stratum 0.0.0.0:PORT --wallet 492525....?

**Comment by UnamSanctam** [comment]
Yes, try that and see, just change `PORT` to whatever port you can forward and then try and connect a miner to it.

**Comment by gamesaccounta** [comment]
Okay, and monerod is this? monerod --zmq-pub tcp://0.0.0.0:18083 --out-peers 64 --in-peers 32 --add-priority-node=node.supportxmr.com:18080 --add-priority-node=nodes.hashvault.pro:18080 --disable-dns-checkpoints --enable-dns-blocklist

**Comment by gamesaccounta** [comment]
Or should I add --p2p-bind-ip 0.0.0.0 --rpc-bind-ip 0.0.0.0 and --confirm-external-bind?

**Comment by UnamSanctam** [comment]
>Okay, and monerod is this? monerod --zmq-pub tcp://0.0.0.0:18083 --out-peers 64 --in-peers 32 --add-priority-node=node.supportxmr.com:18080 --add-priority-node=nodes.hashvault.pro:18080 --disable-dns-checkpoints --enable-dns-blocklist

Yes I believe that should work.

>Or should I add --p2p-bind-ip 0.0.0.0 --rpc-bind-ip 0.0.0.0 and --confirm-external-bind?

That's for a public node, since you don't have the ports forwarded then I don't think it matters

**Comment by gamesaccounta** [comment]
Okay, finally the 3333 port to connect miners?

**Comment by UnamSanctam** [comment]
Well you connect the miners to whatever port you chose in this command: `--stratum 0.0.0.0:PORT`

**Comment by gamesaccounta** [comment]
Ohh, and the 37889 port? P2pool says this: Download the latest P2Pool [release](https://github.com/SChernykh/p2pool/releases/latest)
[Optional] Open port 37889 (P2Pool port) or 37888 (P2Pool mini port) in your firewall to ensure better connectivity
Run ./p2pool --host 127.0.0.1 --wallet YOUR_WALLET_ADDRESS
It should take no more than 5-10 minutes to synchronize

**Comment by gamesaccounta** [comment]
Should I open 37889 port?

**Comment by UnamSanctam** [comment]
Well it's optional (as it says in what you pasted), so you can do it if you potentially want better connectivity.

**Comment by gamesaccounta** [comment]
It works sir, thanks a lot. One more thing, where should I set "x+10000" for custom difficulty on p2pool?

**Comment by UnamSanctam** [comment]
Great. You can set it but it should otherwise change the difficulty automatically normally.

**Comment by gamesaccounta** [comment]
Okay sir, a lot of thanks again

**Comment by UnamSanctam** [comment]
No problem, good luck with the p2pool mining.
