### ISSUE TITLE
I got 330 executions, but only 23 Are mining

### ISSUE THREAD

**Issue by blackbeard1990** [UnamSanctam/SilentCryptoMiner#1699]
Hi Unam
I expected, to have like at least 100 out of 330, to be online and mining (online in the panel)
The build is not Encrypted
Traffic is private
All of them excluded via windows Defender, and don't have other AV installed

Any solution!
and thanks in advance

**Comment by notdidi69** [comment]
Someones got a decent botnet

**Comment by possessed-client** [comment]
Maybe there isn't 2.3GB of RAM available.
Also, might be Defender still blocking some step (most likely injection) even despite exclusion. If you can execute cmd commands on the clients, try checking Windows Defender info on the ones with working miner with this command **powershell -command "Get-MpComputerStatus"** Maybe those have some part of Defender turned off, or aren't updated.
Another thing might be a VPN or some sort of system-wide adblocker or firewall that blocks the connection to the pool.

**Comment by blackbeard1990** [comment]
Yes Despite exclusion, WD seems blocking injection, (saw something like that in my VM)
Any solution for that

**Comment by possessed-client** [comment]
> Yes Despite exclusion, WD seems blocking injection, (saw something like that in my VM) Any solution for that

I remembered that in the past not using the inbuilt startup options also helped against some AVs (with a different tool/script to set persistence). But if it's injection, then you'll need to find/buy/make a crypter. Or mod SCM itself till it bypasses WD. Or extract the xmrig component from SCM and run it without injection (with the arguments generated by SCM) - but xmrig is very detectable, so you'd still need to crypt it or use one of those cracked VM protectors like Themida, VMProtect (some people have managed to find working settings - https://github.com/UnamSanctam/SilentCryptoMiner/issues/1638).

**Comment by Anthonyawad45** [comment]
> Hi Unam I expected, to have like at least 100 out of 330, to be online and mining (online in the panel) The build is not Encrypted Traffic is private All of them excluded via windows Defender, and don't have other AV installed
> 
> Any solution! and thanks in advance

How can I contact you i have a great idea for both of us if you are interested ofcourse
