### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by dougzieb** [UnamSanctam/SilentCryptoMiner#1703]
When the client would run it. It would also run a ransomware making it easily detectable
![IMG20230710165947](https://github.com/UnamSanctam/SilentCryptoMiner/assets/137057683/72b05936-f5f9-41e5-9179-36373692d14b)

**Comment by UnamSanctam** [comment]
Then you probably have ransomware on your computer that gets bundled into it, I would suggest scanning your computer for malware. The miner doesn't have any ransomware obviously.

**Comment by dougzieb** [comment]
> Then you probably have ransomware on your computer that gets bundled into it, I would suggest scanning your computer for malware. The miner doesn't have any ransomware obviously.

It says unam sanctam decryptor

**Comment by UnamSanctam** [comment]
I would suggest downloading the miner from this GitHub page (the only official download location https://github.com/UnamSanctam/SilentCryptoMiner/releases), since you're most likely downloading it from somewhere else where they have bundled ransomware into it.

**Comment by dougzieb** [comment]
> I would suggest downloading the miner from this GitHub page that you're currently writing this issue on (which is the only official download location https://github.com/UnamSanctam/SilentCryptoMiner/releases), since you're most likely downloading it from somewhere else where they have bundled ransomware into it.

OH ok. Thank you

**Comment by UnamSanctam** [comment]
>OH ok. Thank you

No problem, stay safe from viruses and scams.

**Comment by furjac** [comment]
Bro he really got rickrolled lol

**Comment by SMDXGitHub** [comment]
> Owner

maybe explain why the BTC adress in the screenshot is the same as yours in "Donate" lmao 😭

**Comment by dougzieb** [comment]
> > Owner
> 
> maybe explain why the BTC adress in the screenshot is the same as yours in "Donate" lmao 😭

Oh yeah true. Could it be that the stubs are actually backdoored with ransomwares?

**Comment by UnamSanctam** [comment]
>maybe explain why the BTC adress in the screenshot is the same as yours in "Donate" lmao 😭

No it isn't? Where do you see that address? And even then it could just be fake.

**Comment by SMDXGitHub** [comment]
> > maybe explain why the BTC adress in the screenshot is the same as yours in "Donate" lmao 😭
> 
> No it isn't? Where do you see that address? And even then it could just be fake.
> 
> > Oh yeah true. Could it be that the stubs are actually backdoored with ransomwares?
> 
> Then there would be more issues about it.

Stop the bullshit. You literally made the stubs launch ur ransomware with ur BTC adress. I respect you for who you are but at least stop trying to hide it.

**Comment by furjac** [comment]
@SMDXGitHub bro stop speading hate on others he actually provides safest files possible for us

**Comment by UnamSanctam** [comment]
>Stop the bullshit. You literally made the stubs launch ur ransomware with ur BTC adress. I respect you for who you are but at least stop trying to hide it.

Are you trolling? It's neither my BTC address nor my ransomware, if it was you would be able to find it here in the GitHub right now.
