### ISSUE TITLE
Does this pool bans?

### ISSUE THREAD

**Issue by LostMySpirit** [UnamSanctam/SilentCryptoMiner#1704]
Does this pool bans for a a lot of pc mining?

-> https://monero.hashvault.pro/en/

**Comment by UnamSanctam** [comment]
Yes, on that page they say this:
>You're required to run [XMRig Proxy](https://github.com/xmrig/xmrig-proxy) if you operate lots of low hash rate workers on hashvault's mining pool. A Proxy has an added benefit of allowing you to move workers between mining pools quickly, and multiple workers will appear to the mining pool as one high difficulty worker.

**Comment by LostMySpirit** [comment]
Hm okey ty bro.

Quick other question
![grafik](https://github.com/UnamSanctam/SilentCryptoMiner/assets/72671296/6af178aa-2845-4a59-a950-28191bc47788)
so there is a diff of 36k
![grafik](https://github.com/UnamSanctam/SilentCryptoMiner/assets/72671296/9d241188-aa19-43eb-a91b-7b81ad9243a1)
and here 480k diff
where is it better to mine on?
