### ISSUE TITLE
Miner connection settings

### ISSUE THREAD

**Issue by DODO1223** [UnamSanctam/SilentCryptoMiner#1705]
Hi, dear. Can you solve my problem. I have started miner for 3 times in Virtual Box. But I cant see anything on HashVault pool. So, please, send me a full connection set up duide or another pool with easyer set up. I cant find in readme.  PLEASE! (Im collecting money for new piano lol)

**Comment by UnamSanctam** [comment]
Can you post a screenshot of your current settings? Otherwise here are some example settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings, they are currently set to the 2miners pool.

**Comment by DODO1223** [comment]
One second, thank you for your response

**Comment by DODO1223** [comment]
![Снимок](https://github.com/UnamSanctam/SilentCryptoMiner/assets/58740434/64bf3e51-dc62-4258-aa56-c848d00dc2b7)

**Comment by DODO1223** [comment]
XMR adress is correct. I have write password or working name?

**Comment by UnamSanctam** [comment]
That should work, try enabling "SSL/TLS" in the "Mining" settings.

Also, hashvault will probably ban you if you have too many miners (without hosting your own proxy), this is what they say on their main page:
>You're required to run [XMRig Proxy](https://github.com/xmrig/xmrig-proxy) if you operate lots of low hash rate workers on hashvault's mining pool. A Proxy has an added benefit of allowing you to move workers between mining pools quickly, and multiple workers will appear to the mining pool as one high difficulty worker.
