### ISSUE TITLE
When I try to test the miner on my computer it does not seem to be working, I have no idea what I am doing wrong

### ISSUE THREAD

**Issue by tomosel** [UnamSanctam/SilentCryptoMiner#1706]
<img width="669" alt="image" src="https://github.com/UnamSanctam/SilentCryptoMiner/assets/68920006/ce849fd2-b4af-4be9-a5f8-6b069ea06296">

**Comment by UnamSanctam** [comment]
You should remove the `stratum+tcp://` part of the pool. And it doesn't seem like your have it set to a Monero pool (since that's what you're trying to mine).

**Comment by tomosel** [comment]
so how do I put in a correct pool?

**Comment by UnamSanctam** [comment]
What are you planning on mining? Monero? In that case you need to find a Monero pool and then also mine to a Monero wallet address.

**Comment by tomosel** [comment]
i want to mine BTC and I have an exodus wallet

**Comment by tomosel** [comment]
so how do i mine with a standard computer and what pool and wallet should i use?

**Comment by tomosel** [comment]
https://xmr.nanopool.org will this pool work?

**Comment by tomosel** [comment]
I've edited the pool to the one I linked but it still seems to be not working

**Comment by tomosel** [comment]
<img width="693" alt="image" src="https://github.com/UnamSanctam/SilentCryptoMiner/assets/68920006/2a42af4b-6d9c-4810-8bb6-04d903c36d96">

**Comment by UnamSanctam** [comment]
You need to add the port to the pool after the address, and you should also not have "GPU Mining" enabled for Monero. Then you also need to replace the wallet address with your Monero wallet address inside your Exodus wallet.

**Comment by tomosel** [comment]
xmr-eu1.nanopool.org:10343

like this right?

**Comment by UnamSanctam** [comment]
Yes that's correct, and since that's the SSL port then you should enable "SSL/TLS" inside the "Mining" tab.

**Comment by tomosel** [comment]
is it ok if i just use a monero wallet?

**Comment by UnamSanctam** [comment]
Yes what would work fine.

**Comment by UnamSanctam** [comment]
Yeah that looks correct. It should show up on the pool after your find your first share, since the share difficulty of nanopool (and most pools honestly) is quite high then it might take some time depending on the hashrate of your CPU. Also make sure that you don't have any "Stealth Target" programs open like the Task Manager so that the miner isn't paused.

**Comment by tomosel** [comment]
I have this task manager alternative which usually doesn't get detected by any malware or miners and it's not really showing any action, I waited around 5mins before opening it but I don't see anything going on
<img width="587" alt="image" src="https://github.com/UnamSanctam/SilentCryptoMiner/assets/68920006/1d107a6b-33ae-404c-af90-c57efe7e30f9">

**Comment by UnamSanctam** [comment]
Maybe try disabling "GPU Mining" in the miner (since you're mining Monero which is a CPU focused coin). Other then that all your settings look correct.

**Comment by tomosel** [comment]
the peek is 8%

**Comment by UnamSanctam** [comment]
And you don't have any of the programs inside "Stealth Targets" open (you can see the names in the checker)?

**Comment by tomosel** [comment]
oh i think the miner recognizes my task manager alternative but still when i have it closed nothings happening

**Comment by UnamSanctam** [comment]
You could also try with another pool, in case your ISP or country may have blocked nanopool.

**Comment by tomosel** [comment]
I tried a different pool but it's still not working

**Comment by tomosel** [comment]
<img width="678" alt="image" src="https://github.com/UnamSanctam/SilentCryptoMiner/assets/68920006/2aa3eea9-ff1f-4e84-8904-6b9b4882f595">

**Comment by UnamSanctam** [comment]
That should work just fine unless your CPU isn't capable of mining Monero (the RandomX algorithm) but I don't think your CPU is that low-end. Can you try disabling "Stealth" and then see if there's any CPU usage in the Task Manager when it's mining?

**Comment by tomosel** [comment]
I'll try it rn

**Comment by tomosel** [comment]
my cpu is a 12 core i9 so i don't think my cpu is the problem

**Comment by tomosel** [comment]
do you maybe have a discord we could chat on?

**Comment by tomosel** [comment]
<img width="546" alt="image" src="https://github.com/UnamSanctam/SilentCryptoMiner/assets/68920006/9c127e19-78b6-445e-9ca5-a76b9d91a6b3">
might be working rn

**Comment by UnamSanctam** [comment]
>do you maybe have a discord we could chat on?

I got banned for helping people with the miner unfortunately.

>might be working rn

Yes your screenshot shows that it's working, seems like the cause then was that some "Stealth Targets" program was open.

>although my computer is not slowing down at all and the fans arent going fast at all

It will not take everything so it should never really lag, fans might start going faster after some time though since it's at 100%.

**Comment by tomosel** [comment]
yeah well the fans are still not going for some reason
