### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gamesaccounta** [UnamSanctam/SilentCryptoMiner#1709]
Hello Unam, how can I add --daemon and --coin monero in remote config?

**Comment by UnamSanctam** [comment]
Instead of coin you specify the algorithm directly, so specify the algorithm of the coin you choose. There isn't one for the daemon option though, what specifically are you trying to do?

**Comment by gamesaccounta** [comment]
Im trying to mine in my node

**Comment by UnamSanctam** [comment]
Which coin?

**Comment by gamesaccounta** [comment]
monero

**Comment by UnamSanctam** [comment]
Then you probably shouldn't solo mine it in your node, since then it will probably take your months to find a single block unless you have a very large hashrate.

**Comment by gamesaccounta** [comment]
Im just testing, which would be the config?

**Comment by UnamSanctam** [comment]
You would just point it to your node, though there isn't a specific option to enable daemon in the "Remote Configuration" since no one really uses it.

**Comment by gamesaccounta** [comment]
Okay thanks

**Comment by gamesaccounta** [comment]
Hello Unam sorry but I have another question, is monerod good configured for solo mining? monerod.exe --rpc-bind-ip 0.0.0.0 --rpc-bind-port 35489 --confirm-external-bind --prune-blockchain --no-igd --no-zmq --restricted-rpc --out-peers 64 --in-peers 64 --limit-rate-up 1048576 --limit-rate-down 1048576

**Comment by UnamSanctam** [comment]
Sure, though it doesn't really matter much since you'll most likely never find a block anyways. You can find a Monero mining calculator that also shows solo mining here: https://www.cryptunit.com/coin/XMR.

**Comment by gamesaccounta** [comment]
I cant solo mine if I point my miners to my node, I tested it by infecting antoher PC withouth stealth enabled to check. Only works if I compile the miner with --daemon and --coin monero in Advanced Parameters

**Comment by UnamSanctam** [comment]
Sure, but you really don't want to solo mine anyways, and if you somehow need to then you can just run an xmrig-proxy on simple mode between the miner and the node.

**Comment by gamesaccounta** [comment]
Okay thanks
