### ISSUE TITLE
Profile is not created in Nanopool

### ISSUE THREAD

**Issue by gosha1239** [UnamSanctam/SilentCryptoMiner#171]
Hi, no profile is being created in nanopool. It seems that I indicated everything correctly - according to this pattern:
_wallet.WorkerName/pass_
**stratums://`wallet.WorkerName/password`@eth-eu1.nanopool.org:9433**
[https://i.imgur.com/aMSxpQL.png](url)
After a day of mining, the profile is not created on the nanopool:
[https://i.imgur.com/67Wteqs.png](url)

The same situation with XMP:
_wallet.WorkerName/pass_
xmr-eu1.nanopool.org:14433 --user=wallet.WorkerName/password
[https://i.imgur.com/XwrenOR.png](url)

Screenshot from the check to launch the miner:
[https://i.imgur.com/ZLCTUDv.png](url)

@UnamSanctam What is the problem? Thanks in advance!

**Comment by UnamSanctam** [comment]
You have a GTX 1050, I don't think it's good enough to mine ETH, ETH needs at least 4.5GB of VRAM.

**Comment by gosha1239** [comment]
I tested earlier on separate miners for xmr and eth and everything was successful, but in the new miner this is the problem.  Disregarding the graphics card, is the configuration written correctly for this pool?

**Comment by UnamSanctam** [comment]
Yes it should be correct.

**Comment by gosha1239** [comment]
Moreover, a profile in the pool for xmr should have been created, but this did not happen either.

**Comment by gosha1239** [comment]
> 

Any idea why then xmr won't connect?

**Comment by UnamSanctam** [comment]
Then the only reason would be that you cannot connect to the nanopool servers.

**Comment by gosha1239** [comment]
> 

This is strange, because when using a separate miner on xmr, where I used the same pool, everything worked fine.  Thank you very much for your answer!  I'll write it off in a few days of tests if the problem persists.  If everything works, I'll close the topic.  Thanks again!

**Comment by gosha1239** [comment]
Everything was displayed, thanks for the answer.
