### ISSUE TITLE
Huge Pages

### ISSUE THREAD

**Issue by gamesaccounta** [UnamSanctam/SilentCryptoMiner#1710]
Hello Unam, if I uncheck "Run as system" and "Run as administrator", will XMRig enable Huge Pages to get more hashrate or not?

**Comment by UnamSanctam** [comment]
As long as the miner is run as administrator it can use the huge pages.

**Comment by gamesaccounta** [comment]
Okay, im using a RAT but when i execute the miner with run as system, run as admin, rootkit and bsod, the miner will cause bsod with no reason or on the next startup the miner will not start, but the updater.exe file is there

**Comment by UnamSanctam** [comment]
Then something is probably killing the miner which causes the BSoD, and it's also maybe removing the installed Task.

**Comment by gamesaccounta** [comment]
I have WD exclusions enabled

**Comment by UnamSanctam** [comment]
Sure but there might be something else that kills it, you can try it without the rootkit (and maybe BSoD).

**Comment by gamesaccounta** [comment]
So with a RAT with admin permissions on my clients, there shouldn't be any problem when activating run as system, run as admin, rootkit and bsod?

**Comment by UnamSanctam** [comment]
Usually not, though the rootkit is very complex and can cause problems of course (hence the warning in the wiki). BSoD won't cause problems unless somehow crashes. If it BSoDs when something kills the miner (either the user or a program) then that is technically working as intended.

**Comment by gamesaccounta** [comment]
Okay, and does the rat with admin permissions execute the miner (without check run as system and run as admin) as admin? To use MSR MOD to apply more hashrate

**Comment by UnamSanctam** [comment]
It depends on how the RAT as implemented their execution.
