### ISSUE TITLE
Is RTM BUG ? 

### ISSUE THREAD

**Issue by vampyy9** [UnamSanctam/SilentCryptoMiner#1715]
I did everything right but it still not working at all it won’t mine

**Comment by UnamSanctam** [comment]
No RTM works fine, can you run the checker and post a screenshot of it here?

**Comment by vampyy9** [comment]
Ok hold on at work but do your miner work on windows 11 ?

**Comment by UnamSanctam** [comment]
Yes it works on all versions from Windows 7 and newer.

**Comment by vampyy9** [comment]
Ooh cuz I ask that because every time I use the miner it work on windows 10 but not windows 11

**Comment by UnamSanctam** [comment]
Hmm, all my main testing is done on my Windows 11 VM so that is the OS that is the most tested.

**Comment by vampyy9** [comment]
Yea i had to make like 20 miners to get to work on windows 11 then I thought I finally got it to work and try put on my other computer it didn’t mine

**Comment by UnamSanctam** [comment]
Then most likely some setting is wrong.

**Comment by vampyy9** [comment]
![4BD596F3-4198-4AB5-ACC3-F0D941B62C84](https://github.com/UnamSanctam/SilentCryptoMiner/assets/133830487/30a53af6-7add-4d0c-815a-094db0be0fbf)

**Comment by UnamSanctam** [comment]
That should work fine on any computer as long as they're able to connect to `usa-east.raptoreumzone.com`, how are you checking whether it works or not?

**Comment by vampyy9** [comment]
The task manager

**Comment by vampyy9** [comment]
U have a discord?

**Comment by UnamSanctam** [comment]
No, it got banned for helping people with the miner. If it isn't mining with those base settings then most likely the computer can't connect to the pool or there is something with the CPU, though for GhostRider that is usually never the case.

**Comment by vampyy9** [comment]
Yea that what I was thinking something wrong with the pc cuz they work on my other pc
