### ISSUE TITLE
2miners question

### ISSUE THREAD

**Issue by Amittere1** [UnamSanctam/SilentCryptoMiner#1717]
Hi Unam i found out that 2miners region is germany and most of my miners are not in europe
So does that affect my earnings? should i switch to another pool like one with "auto geo" feature?

**Comment by UnamSanctam** [comment]
The higher ping can affect your stale share rate, on 2miners check your "Valid Share Rate" and see if it's close to 100%, if it is then there's no problem. And even then there aren't that many pools with an auto-geo feature.
