### ISSUE TITLE
Im new , pls help 

### ISSUE THREAD

**Issue by KOHnani1** [UnamSanctam/SilentCryptoMiner#172]
How can i set the worker's names ? i try to put walletaddress.name but it is not working , what can i do

**Comment by UnamSanctam** [comment]
Depends on the pool, check the pools documentation to see how to do it for the specific pool you're using.

**Comment by KOHnani1** [comment]
But the tool dont have any blank to fill the worker's name , what i should do ?

**Comment by UnamSanctam** [comment]
The way to enter a worker name depends on a pool, some do it by entering `Wallet.Workername` into the "Wallet Address" while some pools do it by using the "Password" field as the worker name.
