### ISSUE TITLE
Remote Configuration

### ISSUE THREAD

**Issue by Tamshi27** [UnamSanctam/SilentCryptoMiner#1721]
i just wanted to ask how the option "Remote Configuration" is working?

**Comment by UnamSanctam** [comment]
Sorry for the very late response, my notifications stopped working.

The "Remote Configuration" feature allows you to remotely change settings of the miner, it checks the "Remote Configuration" on first start and then every 100 minutes after that.

https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner
