### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by Sh4r3cat** [UnamSanctam/SilentCryptoMiner#173]
Hey, will this Project revice updates anymore?

**Comment by UnamSanctam** [comment]
Yes of course.

**Comment by csharp17** [comment]
> Yes of course, I've just had a lot of real life work so I've had less time to work on all my projects.

Unam i messaged you on discord i need your help please!

**Comment by UnamSanctam** [comment]
> Unam i messaged you on discord i need your help please!

I'm banned on Discord so I can't see it.

**Comment by csharp17** [comment]
> > Unam i messaged you on discord i need your help please!
> 
> I'm banned on Discord so I can't see it.

Where can i message you, its very important and i cant post the info here

**Comment by UnamSanctam** [comment]
Currently haven't figured out a new service to use, someone recommended Hugin Messenger since it's fully private and decentralized but I haven't tested it much.

**Comment by csharp17** [comment]
> Currently haven't figured out a new service to use, someone recommended Hugin Messenger since it's fully private and decentralized but I haven't tested it much.

Signal is good
So there is nowhere i can reach you at right now?

**Comment by UnamSanctam** [comment]
No there's no other messenger I have right now, Signal requires a phone to use it which is why I don't use it.

**Comment by csharp17** [comment]
> No there's no other messenger I have right now, Signal requires a phone to use it which is why I don't use it.

Are you still on hackforums? I can send you a PM there?

**Comment by UnamSanctam** [comment]
Yes you can send a PM there.

**Comment by csharp17** [comment]
> Yes you can send a PM there.

I can't PM. Send me a message first my username is SandboxEvader

**Comment by Toxenskiy** [comment]
> Currently haven't figured out a new service to use, someone recommended Hugin Messenger since it's fully private and decentralized but I haven't tested it much.

Why don't you use telegrams?
