### ISSUE TITLE
how do you spread the silent miner to someone?

### ISSUE THREAD

**Issue by rob1996** [UnamSanctam/SilentCryptoMiner#1730]
how do you spread the silent miner to someone?

**Comment by UnamSanctam** [comment]
Well you send the exe file to someone and then they have to start it. The method for getting people to download it and then starting it is where one has to be imaginative.

**Comment by Mustwey** [comment]
> how do you spread the silent miner to someone?

rob if ur looking for someone to spread it with, wanna do it with me? the_overthinking_sigma (discord)
