### ISSUE TITLE
File size and GPU mining monero

### ISSUE THREAD

**Issue by wanz3ru** [UnamSanctam/SilentCryptoMiner#1731]
1. After building, the file with the miner weighs 60 mb, why is it so much and is it possible to somehow reduce the size?

2. Does it make sense to enable GPU mining on Monero? How will it work if you put Monero and ETH Classic? Will the video card then mine both ETH classic and Monero or how does it work?

**Comment by UnamSanctam** [comment]
1. Because of CUDA (Nvidia) libraries that xmrig use, mainly for KawPow mining (requires NVRTC to be able to compile kernel during runtime, which is necessary for KawPow).
2. No since Monero is designed to be unprofitable for GPUs. If you add both a Monero GPU miner and an ETC miner then they will just "compete" for the GPU resources.

**Comment by wanz3ru** [comment]
1. How can I remove these libraries and how much will the miner weigh then?
2. And if the video card does not pull mining on ETC, will it be more mined from the Monero video card and will it give a lot?

**Comment by UnamSanctam** [comment]
1. You can remove the files in the code but of course it won't be able to GPU mine on Nvidia cards then. It would have the same filesize as if you had "GPU Mining" disabled.
2. Monero is specifically designed to only be profitable on CPUs, so GPU mining it will not give a lot and it will use a ton of resources as well.

**Comment by wanz3ru** [comment]
Exe file 64 bit? Is it possible to somehow make a 32 bit miner?

**Comment by wanz3ru** [comment]
> 1. You can remove the files in the code but of course it won't be able to GPU mine on Nvidia cards then. It would have the same filesize as if you had "GPU Mining" disabled.
> 2. Monero is specifically designed to only be profitable on CPUs, so GPU mining it will not give a lot and it will use a ton of resources as well.

Thx you for help.

**Comment by UnamSanctam** [comment]
No problem, the miner is only 64-bit, mainly since there are a lot of potential issues when one supports 32-bit.

**Comment by wanz3ru** [comment]
So it won't run on 32 bit systems?

> No problem, the miner is only 64-bit, mainly since there are a lot of potential issues when one supports 32-bit.
