### ISSUE TITLE
Infection by USB

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/SilentCryptoMiner#1732]
How about the function of infection on USB?

I think to try to add a function yourself
However, I doubt that something will come out for me

**Comment by UnamSanctam** [comment]
Depends on what you mean, do you mean that it should spread to any connected USB devices by binding itself to all the programs on it or do you mean that you want an "autostart" that starts the miner whenever the USB it's on gets plugged in (though the Windows USB "autostart" isn't actually automatic)? It's possible for the program to bind itself to any programs on the USB but then you have to create both a loader and a binder inside the miner which it will use to do that.

**Comment by anbu-squad** [comment]
I thought just that the miner would copy yourself on the flash drive

Is it essentially able to implement?
I saw a similar function in other builders

**Comment by UnamSanctam** [comment]
Yes that's possible, but would that actually do much?

**Comment by anbu-squad** [comment]
If there is little use, then perhaps the function is really superfluous

I honestly do not know

Please answer in the topic
In which file it is necessary to redate the invoctions method

most likely it is necessary to make some fragments of the code confidential in order to avoid detection
https://github.com/UnamSanctam/SilentCryptoMiner/issues/1718

**Comment by UnamSanctam** [comment]
The injection code is all here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/Includes/inject.cpp

**Comment by anbu-squad** [comment]
Thank you
I will study

**Comment by possessed-client** [comment]
> The injection code is all here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/Includes/inject.cpp

I see you have changed process hollowing type to something called transacted hollowing. Is it any less detectable? Also, is it theoretically possible to port this to C#? (I am still using the C# versions and need to know whether it's worth trying to port)

**Comment by UnamSanctam** [comment]
>I see you have changed process hollowing type to something called transacted hollowing. Is it any less detectable? Also, is it theoretically possible to port this to C#? (I am still using the C# versions and need to know whether it's worth trying to port)

Yes specifically it's Ghostly Hollowing, it is less detecatble than some more common ones but of course many can still detect it (only private ones are mostly undetected anyways). It's possible to port it but it can be pretty difficult depending on experience.
