### ISSUE TITLE
What port should I specify when creating a miner?

### ISSUE THREAD

**Issue by moshiax** [UnamSanctam/SilentCryptoMiner#1736]
There are two ports on the nanopool, SSL Stratum Port and Stratum Port, should I also specify this as xmr-eu1.nanopool.org:port?

**Comment by UnamSanctam** [comment]
Yes that's correct, and usually the recommended port is SSL since that make the connection secure. So xmr-eu1.nanopool.org:`10343` (and don't forget to enable SSL/TLS in the settings).

**Comment by moshiax** [comment]
ok thanks
