### ISSUE TITLE
What other safe pools are there for Monero botnet mining besides 2miners and nanopool?

### ISSUE THREAD

**Issue by moshiax** [UnamSanctam/SilentCryptoMiner#1737]
It's just that I often heard that 2miners were banned for a botnet and nanopull has a minimum payout of 1 xmr without registration, which is too much for me

**Comment by UnamSanctam** [comment]
I haven't seen any actual proof of anyone getting banned yet from 2miners so I don't know if that happens. You can lower the payout on nanopool by just adding a "password" when you mine, so you would just put this: `WalletAddress.WorkerName/Password` and then you can use `Password` to lower the minimum payout.
