### ISSUE TITLE
Hey Unam… just another boring question 👉👈

### ISSUE THREAD

**Issue by pepe123456789-cmyk** [UnamSanctam/SilentCryptoMiner#1742]
Hi Unam hope you’re having a great day!
I can’t believe how active you are; you respond everybody’s question no matter how nooby the questions are… come to thing of it your miner is 10x better than pureminer or other miners out there that cost money! Thank you big time for all your patience and for making this tool FREE :)

ok now here is my question😂 
I’m working with a buddy of mine and we made a partnership 50/50 partners just like Jesse and Walter from Breaking Bad. We are using the same Loader, Rat, Stealer, and sharing the same RDP. Now we want everything to be as even as possible and we where wondering if there’s any chance for us to make the Unaminer be able to mine to 2 different addresses with 50% of the hashrate going to 1 wallet and the other 50% going to another wallet. Maybe we could adjust the “donation” and put my buddy’s wallet there and set the donation rate to 50%… would something like that work? 
Anyways thank you big time, take care friend❤️

**Comment by UnamSanctam** [comment]
Haha thank you, I'd say the easiest way to do this would be to use a pool that supports "splitting" the hashrate between wallets. For example MoneroOcean supports this by entering this into the "Wallet Address" field: `Wallet1%50%Wallet2` which would split the hashrate 50%/50% between `Wallet1` and `Wallet2`.

**Comment by tarekxxx** [comment]
> Haha thank you, I'd say the easiest way to do this would be to use a pool that supports "splitting" the hashrate between wallets. For example MoneroOcean supports this by entering this into the "Wallet Address" field: `Wallet1%50%Wallet2` which would split the hashrate 50%/50% between `Wallet1` and `Wallet2`.

how it will be look like in json ? unam ?

**Comment by UnamSanctam** [comment]
In the JSON it would look like: `"wallet": "Wallet1%50%Wallet2",`
