### ISSUE TITLE
Crypter

### ISSUE THREAD

**Issue by Tamshi27** [UnamSanctam/SilentCryptoMiner#1747]
Hey, i just wanted to ask you if you may know some free crypters who work good with the miner.

**Comment by UnamSanctam** [comment]
Not really that I'm aware of, free crypters usually aren't undetected of course either (since they're public). There are some free crypters on GitHub but you usually have to find more obscure ones since they might not be as detected.

**Comment by Tamshi27** [comment]
Oh ok, but thx
