### ISSUE TITLE
Windows Defender Exceptions

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1748]
Good afternoon Unam. Please tell me, I used to add exceptions to the defender with such a command.
powershell Add-MpPreference -ExclusionPath $env:ProgramFiles
powershell Add-MpPreference -ExclusionPath $env:SystemDrive
Now I found that it stopped working.

**Comment by masterjek** [comment]
Here is what I get when executing. And earlier, when performing this operation, exceptions were successfully created in Windows Defender.

Add-MpPreference : Operation failed. Error: 0x800106ba. Operation: MpPreference. Target: ConfigListExtension
.
line:1 sign:1
+ Add-MpPreference -ExclusionPath $env:ProgramFiles
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0x800106ba,Add-MpPreference

Add-MpPreference : Operation failed. Error: 0x%1!x!
line:1 sign:1
+ Add-MpPreference -ExclusionPath $env:ProgramFiles
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Add-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0x800106ba,Add-MpPreference

**Comment by UnamSanctam** [comment]
I believe that usually happens when Windows Defender is disabled/"broken" on the computer. Is the Windows Defender fully working and enabled on the computer?

**Comment by masterjek** [comment]
Yes, Windows Defender is enabled. Installed the latest updates to the operating system. And the Windows Defender itself has been updated to the latest version. At what I check on the same computer on which everything worked. This stopped working today after updating windows defender and the operating system itself.

**Comment by UnamSanctam** [comment]
You could try to repair your Windows, it could be that some files/settings were corrupted during the update. It happens occasionally.

**Comment by masterjek** [comment]
You were 100 percent right. This was due to damage to Windows itself. I would never have thought that an update could break windows and their defender.

**Comment by UnamSanctam** [comment]
Alright, yeah that has happened to me too a few times.
