### ISSUE TITLE
Quick newb questions

### ISSUE THREAD

**Issue by xwyattyx** [UnamSanctam/SilentCryptoMiner#1749]
For legal reasons I have not used this and have no intentions of using it.

Coding isn’t really my forte, so I got some dumb questions to ask.

How do I download this? Can I just use the builder.zip, or do I have to clone it into something like visual studio, and then download it that way?

I’m mainly (hypothetically) going to have access to CPU’s, what coin do you recommend I mine? 

And is there anything I need to do to make it not detected, I’d hate to, in theory, waste all my time spreading this to different computers and then for some reason all of them get detected. 

I've also read some about crypting, which is that necessary and how do I add that?

**Comment by Tamshi27** [comment]
Hey, i used the pre code (https://github.com/UnamSanctam/SilentCryptoMiner/releases) and then i just run the builder. I mine with cpu´s Monero coin.

**Comment by xwyattyx** [comment]
> Hey, i used the pre code (https://github.com/UnamSanctam/SilentCryptoMiner/releases) and then i just run the builder. I mine with cpu´s Monero coin.

thank you! i'll do that then!
