### ISSUE TITLE
Cryptographer

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#175]
Good evening. Can you please tell me if the Cryptographer can remove antivirus detections in the dynamics at startup? It's just that the other day a lot of miners just fell off and stopped working. And as I understand it, antivirus detections appeared in the dynamics when the miner was launched and implemented. The file itself is not detected after encryption. But as I understand it, the reason for everything is dynamic detections.

**Comment by Toxenskiy** [comment]
antiviruses have properties to update
