### ISSUE TITLE
2miners

### ISSUE THREAD

**Issue by Tamshi27** [UnamSanctam/SilentCryptoMiner#1751]
Hey, i wanted to try my miner with a pool from 2miners (pool: xmr.2miners.com:2222). But when i run it, it is not mining? Only hashVault is working?

**Comment by UnamSanctam** [comment]
2miners works fine but make sure that you use port 12222 if you have SSL/TLS enabled.

**Comment by Tamshi27** [comment]
ohhh ty xd
