### ISSUE TITLE
Old miners do not appear in the web panel

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1756]
Good afternoon Unam. I have old miners that were created before the release of 3.0.0. The domain with the web panel to which they connected was blocked. I waited a year and the previous registrar who blocked the domain released it. I registered the same domain with another registrar. The entire domain is active, I set everything up and launched the web panel, but the miners do not connect to it. There, all the miners worked for the nicehash pool. I can see them in the nicehash office, but they are not connected to the web panel.
I can't figure out what could be the reason?

**Comment by UnamSanctam** [comment]
Is the SSL certificate correct and such for the current website if you were using https when you made the miner? Do any miners connect at all if you build and test one?

**Comment by masterjek** [comment]
yes certificate ssl I just bought and installed it on apache. That all miners were created in the old builder, even before the release of builder version 3.0.0. yes, the builder used the endpoint with https. The fact is that everything worked fine before the domain was blocked, I saw all these miners in the web panel. After the domain was blocked, I didn’t change anything in Apache, I just stopped the server and waited a year until the domain was freed from the old registrar. Now the same domain is registered with a foot registrar and all the miners do not connect to the web panel as it was a year ago.
The only thing I did not check is now to build the miner with this endpoint and check if it connects to the panel, then I will check it now.

**Comment by masterjek** [comment]
Yes, I just built a test miner with this endpoint and it was immediately displayed in the web panel.

**Comment by UnamSanctam** [comment]
Hmm, then that is weird. How long has it been since you changed the domain DNS settings to your new server? And do you have a "Remote Configuration" for those miners where the web panel URL might be set to something else?

**Comment by masterjek** [comment]
A day has not passed since the change of records DNS. I don't use remote configuration. Or maybe another reason is that the old registrar, before blocking the domain, sent it to Virus Total. They then flagged the site as phishing. Could this be the reason why many antiviruses simply block miners from accessing the web panel?

**Comment by UnamSanctam** [comment]
Could be that the DNS hasn't propagated yet everywhere or something, but at least some miners should still connect. And even if some antiviruses did block your domain then at least some should still connect to it as well. It's difficult to know why they're not connecting, could possibly be that something on the server is causing a 301 redirect or something which could be a problem if the miners are really old versions.

**Comment by opget** [comment]
> Добрый день Унам. У меня есть старые майнеры, которые были созданы до выхода 3.0.0. Домен с веб-панелью, к которой они подключались, был заблокирован. Я подождал год и предыдущий регистратор, который заблокировал домен, освободил его. Я зарегистрировал этот же домен у другого регистратора. Весь домен активен, я все настроил и запустил веб-панель, но майнеры к ней не подключаются. Там все майнеры работали на пул nicehash. Я вижу их в офисе nicehash, но они не подключены к веб-панели. Не могу понять в чем может быть причина?

Can you please tell me why you got your domain blocked?

**Comment by masterjek** [comment]
> > Добрый день Унам. У меня есть старые майнеры, которые были созданы до выхода 3.0.0. Домен с веб-панелью, к которой они подключались, был заблокирован. Я подождал год и предыдущий регистратор, который заблокировал домен, освободил его. Я зарегистрировал этот же домен у другого регистратора. Весь домен активен, я все настроил и запустил веб-панель, но майнеры к ней не подключаются. Там все майнеры работали на пул nicehash. Я вижу их в офисе nicehash, но они не подключены к веб-панели. Не могу понять в чем может быть причина?
> 
> Can you please tell me why you got your domain blocked? For the web panel on the domain?

The domain registrar told me that the domain was used for phishing attacks. How it happens, if a user finds a miner on his computer, he uploads it to the virus total. They analyze and find the site to which the miners connect, and this is the site on which the web panel is installed. Then the virus total  sends this information to the domain registrar and they block it. It was like this for me.

**Comment by opget** [comment]
Thanks for the detailed response! It's good that Unam came up with remote configurations, in which case it's certainly worth using them
