### ISSUE TITLE
Watchdog

### ISSUE THREAD

**Issue by Tamshi27** [UnamSanctam/SilentCryptoMiner#1762]
Hey, its not a real problem for me but when i run my checker.exe its doesnt show anything but my miner is running on a "test" pc if yk xd. Is that bc i build my miners on a vm? And keep up with that great work ma man👌

**Comment by UnamSanctam** [comment]
Hey, can you try with the newest release? On VMs CPU miners should show up since VMs have CPUs but any GPU miners won't appear since (usually) VMs don't have any GPUs.

**Comment by Tamshi27** [comment]
Hey, so i tested the new version and its still not working but its not that important for me. But my mining perfomance droped much since the new version is mining on that pc. any ideas to fix it or is it because the person had already installed 2 miners from me and it's bugging now?

**Comment by UnamSanctam** [comment]
What is it that you're mining? And are you sure that there aren't multiple miners installed at the moment?

**Comment by Tamshi27** [comment]
Well im mining monero rn and yes, the person was kinda stupid and bc it didnt open something she opend it like 3 times and then today she opend the new version i send so i think its kinda bugging bc of that

**Comment by UnamSanctam** [comment]
Alright then the hashrate is probably lower since it has multiple different miners running, so it's sharing the resources between the miners.

**Comment by Tamshi27** [comment]
damn ok still ty

**Comment by Tamshi27** [comment]
Can I delete them somehow? xd

**Comment by UnamSanctam** [comment]
If you run the uninstaller from the older miner that you built then it will be removed, or if the "Startup" settings was the same in the old miner as they are in your new miner then the new miner should have replaced the old one (just the file). If that's the case then on the next computer restart then only the new miner should run.

**Comment by Tamshi27** [comment]
and if dont have have the uninstaller anymore?
