### ISSUE TITLE
Remote configuration

### ISSUE THREAD

**Issue by opget** [UnamSanctam/SilentCryptoMiner#1765]
Unam, could you please tell me how to change the web panel address using remote configuration? If it is possible

**Comment by UnamSanctam** [comment]
Yes you can use `"api-endpoint": "API Endpoint URL",` to change the web panel URL using the "Remote Configuration".

**Comment by opget** [comment]
> Да, вы можете `"api-endpoint": "API Endpoint URL",`изменить URL-адрес веб-панели с помощью «Удаленной настройки».

Thank you, Unam, you have no equal! Success to you in all your endeavors! Your update is a work of art :)

**Comment by opget** [comment]
> Да, вы можете `"api-endpoint": "API Endpoint URL",`изменить URL-адрес веб-панели с помощью «Удаленной настройки».

Thank you, Unam, you have no equal! Success to you in all your endeavors! Your update is a work of art :)
