### ISSUE TITLE
I have a mistake

### ISSUE THREAD

**Issue by Krismaty505** [UnamSanctam/SilentCryptoMiner#1770]
Please help me. I have an error in the "windres" file

**Comment by UnamSanctam** [comment]
What's the error in the log file? And can you try building the miner in another location?

**Comment by Krismaty505** [comment]
> Что за ошибка в файле журнала? И можете ли вы попробовать создать майнер в другом месте?

I have already tried many places
![photo_5427365514587524796_y](https://github.com/UnamSanctam/SilentCryptoMiner/assets/126063809/7962852a-4f23-45c9-a379-af32a5023ecb)

**Comment by UnamSanctam** [comment]
I would guess it's because your path contains Cyrillic characters (and it's also inside the OneDrive folder). Try it in a path that does not have any Cyrillic characters in it and also not in the OneDrive location.

**Comment by UnamSanctam** [comment]
What does it say inside the windres.log file?

**Comment by Krismaty505** [comment]
> What does it say inside the windres.log file?

![Screenshot_20230826-191150](https://github.com/UnamSanctam/SilentCryptoMiner/assets/126063809/c64ba6a5-ebf5-4dad-b230-ced54d0f80be)

**Comment by UnamSanctam** [comment]
In that one it couldn't read the Cyrillic characters from what it looks like, what error did you get inside the windres.log file inside the other folder which didn't have any Cyrillic?

**Comment by UnamSanctam** [comment]
>I'll take a look. By the way, can I mine monaro on a processor and a video card at once? Just when creating there, you can enable these two functions at once

You can but Monero is designed to be a CPU only coin, so it would be unprofitable to mine it using a GPU (on purpose).

**Comment by Krismaty505** [comment]
> > Я посмотрю. Кстати, могу ли я майнить monaro на процессоре и видеокарте одновременно? Просто при создании там вы можете включить эти две функции одновременно
> 
> Вы можете, но Monero спроектирован так, чтобы быть монетой только для процессора, поэтому было бы невыгодно майнить его с использованием GPU (специально).

**Comment by Krismaty505** [comment]
> > Я посмотрю. Кстати, могу ли я майнить monaro на процессоре и видеокарте одновременно? Просто при создании там вы можете включить эти две функции одновременно
> 
> Вы можете, но Monero спроектирован так, чтобы быть монетой только для процессора, поэтому было бы невыгодно майнить его с использованием GPU (специально).

![IMG_20230828_172046_231](https://github.com/UnamSanctam/SilentCryptoMiner/assets/126063809/46eb7494-d6fd-4677-94f3-36b518f28bd3)
That's what you asked for

**Comment by UnamSanctam** [comment]
Oh, do you have anything set in the "Assembly" settings? I believe what you've input into "Version" might be invalid.

**Comment by Krismaty505** [comment]
> Oh, do you have anything set in the "Assembly" settings? I believe what you've input into "Version" might be invalid.

I set a delay of 3 seconds

**Comment by UnamSanctam** [comment]
I mean in the "Assembly" tab, most likely what you've wrote into the "Version" field is invalid.

**Comment by Krismaty505** [comment]
> I mean in the "Assembly" tab, most likely what you've written into the "Version" field is invalid.

And yes. The error was there. Thank you so much for helping me to the end. Thank you. However, I have another mistake

**Comment by Krismaty505** [comment]
> Я имею в виду, что на вкладке "Сборка", скорее всего, то, что вы написали в поле "Версия", недопустимо.

![Uploading IMG_20230828_174915_764.jpg…]()

**Comment by Krismaty505** [comment]
> Я имею в виду, что на вкладке "Сборка", скорее всего, то, что вы написали в поле "Версия", недопустимо.
![Screenshot_20230828-181333](https://github.com/UnamSanctam/SilentCryptoMiner/assets/126063809/9dc91559-8408-42be-bc47-67aea63f9de3)

**Comment by UnamSanctam** [comment]
Are you building it inside System32?

**Comment by Krismaty505** [comment]
> Вы создаете его внутри System32?

No. To the desktop

**Comment by UnamSanctam** [comment]
Hmm, because that's what it's saying there. Can you try running the builder as administrator?

**Comment by Krismaty505** [comment]
> Hmm, because that's what it's saying there. Can you try running the builder as administrator?

it turned out. Thank you very much!
