### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by Tamshi27** [UnamSanctam/SilentCryptoMiner#1773]
Hey, i wanted to test the icon once but when i use my .ico file i get this error:
https://github.com/UnamSanctam/SilentCryptoMiner/assets/136450765/fbaaf99f-a848-4acb-9127-b96a55202edb

**Comment by UnamSanctam** [comment]
Check the windres.log file that it specifies to see the error.

**Comment by Tamshi27** [comment]
windres.exe: icon file `C:\Users\h\Downloads\starry_sky_stars_milky_way_galaxy_4k_hd_space-1920x1080 (1).ico' does not contain icon data

**Comment by UnamSanctam** [comment]
Then the file is not a valid icon file, did you convert the file probably into the ico format?

**Comment by Tamshi27** [comment]
i saved it as a .ico file?

**Comment by UnamSanctam** [comment]
The .ico file format is a specific format and not a normal image format (https://en.wikipedia.org/wiki/ICO_(file_format)), you will have to create or convert an image to the format using some tool.
