### ISSUE TITLE
About cryptography

### ISSUE THREAD

**Issue by Krismaty505** [UnamSanctam/SilentCryptoMiner#1779]
Hi, it's me again)). I forgot to ask if there are any preferences on cryptography? Well, what can and what shouldn't be done to make everything work well

**Comment by UnamSanctam** [comment]
You mean if there's some specific crypter? Then no not really, you should be able to use any that supports 64-bit native programs. If you do use one then remember to disable "Startup" in the miner and enable the corresponding "Startup" option in the crypter instead.

**Comment by Krismaty505** [comment]
> Вы имеете в виду, есть ли какой-то конкретный криптограф? Тогда нет, не совсем, вы должны иметь возможность использовать любой, который поддерживает 64-разрядные собственные программы. Если вы используете его, не забудьте отключить "Запуск" в майнере и вместо этого включить соответствующую опцию "Запуск" в криптографе.

And why do I have the luck of round 0%
