### ISSUE TITLE
Why is my hashrate very low , where is the hashrate going ?

### ISSUE THREAD

**Issue by toxic4a** [UnamSanctam/SilentCryptoMiner#1782]
Why are these addresses corresponding with mine. Provide an explanation ASAP.

**NOTE : If something is free you are the product.**

```xmr-eu2.nanopool.org```
```4Aw8Echp2Hrhc5ussZ5cX1bKS6AFJUqFMJH9373M819NCLMVs4DctwGgtTg1ixc8oqVhZNeKCSTS776xoihXmX8SNYx7vtv```

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/141258662/586f49fb-7529-4eae-b2b2-6209d43a83e2)

```37.203.243.102:443```
[Hashvault](https://monero.hashvault.pro/en/dashboard/84becQNTHchWj9A5LkdNrnZFPiV9NBAmrNcRv7KfonctGLRzSydwpRMiBSUbxCSL2BZZyDwW4hicX9GL6YXTjRfg4ZiB4hk) 
```84becQNTHchWj9A5LkdNrnZFPiV9NBAmrNcRv7KfonctGLRzSydwpRMiBSUbxCSL2BZZyDwW4hicX9GL6YXTjRfg4ZiB4hk```

**Comment by toxic4a** [comment]
> Depends on the CPUs, and are you running it as administrator or not? And which version of the miner is it?

s.c.m [v3.2.0](https://github.com/UnamSanctam/SilentCryptoMiner/releases/tag/scm-v3.2.0)

**Comment by toxic4a** [comment]
> Then it shouldn't have a low hashrate, can you provide any specific CPU and what hashrate it's mining at (and also the "Max CPU")?

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/141258662/4e464d9b-f8e0-4a7e-807a-f626a6903d67)

I really find it sus but why is it in memory since its not mine

```
{
    "algo": "rx/0",
    "pool": "37.203.243.102",
    "port": 443,
    "wallet": "84becQNTHchWj9A5LkdNrnZFPiV9NBAmrNcRv7KfonctGLRzSydwpRMiBSUbxCSL2BZZyDwW4hicX9GL6YXTjRfg4ZiB4hk",
    "password": "x",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 60,
    "idle-wait": 1,
    "idle-cpu": 90,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,GenshinImpact.exe",
    "kill-targets": "",
    "stealth-fullscreen": true
}
```

**Comment by toxic4a** [comment]
But fr why do you have to do this ?

**Comment by UnamSanctam** [comment]
The HashVault mining isn't yours? Are you using some sort of modified version of the miner downloaded from somewhere else?

**Comment by toxic4a** [comment]
> The HashVault mining isn't yours? Are you using some sort of modified version of the miner downloaded from somewhere else?

Downloaded it directly from here bro , nowhere else.

**Comment by UnamSanctam** [comment]
Sorry, can you explain better what your issue is? Is `84becQNTHchWj9A5LkdNrnZFPiV9NBAmrNcRv7KfonctGLRzSydwpRMiBSUbxCSL2BZZyDwW4hicX9GL6YXTjRfg4ZiB4hk` someone else's address and not yours? Do you have a "Remote Configuration" or web panel set in the miner?

**Comment by toxic4a** [comment]
> The HashVault mining isn't yours? Are you using some sort of modified version of the miner downloaded from somewhere else?

Not mine I know my address but my hashrate has dropped significantly since the past month, everything was ok since the start of the year but for the month of August was a total rip off from me , seriously !!!!

**Comment by toxic4a** [comment]
> Sorry, can you explain better what your issue is? Is `84becQNTHchWj9A5LkdNrnZFPiV9NBAmrNcRv7KfonctGLRzSydwpRMiBSUbxCSL2BZZyDwW4hicX9GL6YXTjRfg4ZiB4hk` someone else's address and not yours? Do you have a "Remote Configuration" or web panel set in the miner?

only the remote configuration

**Comment by toxic4a** [comment]
> And that address is not set in your "Remote Configuration"? Since the JSON array you provided is from a "Remote Configuration" or web panel configuration. The hashrate shouldn't really fluctuate much over a larger period of time. Can you provide your address then or a screenshot of the hashrate?

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/141258662/326b9828-660b-4230-b7b4-6ca477408a65)
[The Address](https://monero.hashvault.pro/en/dashboard/84becQNTHchWj9A5LkdNrnZFPiV9NBAmrNcRv7KfonctGLRzSydwpRMiBSUbxCSL2BZZyDwW4hicX9GL6YXTjRfg4ZiB4hk)

The address in my remote config is totally different from the one above mining on hashvault and my remote config is set to mine on nanopool.

**Comment by toxic4a** [comment]
> Can you run your miner and then the checker and take a screenshot of it? There are fake versions of my miner out there which replaces the "Remote Configuration" and/or web panel with theirs, are you sure you didn't download it from anywhere else (even one that tries to look the same)? There is also a newer miner version out (3.3.0) just so you know.
> 
> The XMR miner that mine is based on (https://github.com/xmrig/xmrig) does have a default dev donation but that should be disabled (set to 0%) and that doesn't use the JSON format anyways so what you linked before should be coming from some "Remote Configuration" or web panel.

I really don't keep the checker, I deleted it , I only keep the uninstaller , if i want to know if my miner is running i simply open up process hacker and search for my miner in memory strings. Afaik I downloaded the miner from here and I didn't fall for any typo-squatting or any fake link of any sort. Yes i saw the new version but I have this problem to rectify first before moving on.

**Comment by UnamSanctam** [comment]
Hmm, then it's a bit difficult, preferably we would check the options passed to the miner to see what the "Remote Configuration" (or web panel) is set to but since that's stored inside the ShellInfo of the PEB of the program then that's quite difficult to retrieve. Are you able to find any pastebin link to that JSON array inside the memory strings of the program?

**Comment by toxic4a** [comment]
> Hmm, then it's a bit difficult, preferably we would check the options passed to the miner to see what the "Remote Configuration" (or web panel) is set to but since that's stored inside the ShellInfo of the PEB of the program then that's quite difficult to retrieve. Are you able to find any pastebin link to that JSON array inside the memory strings of the program?

No but the problem is that I find that address in memory and my remote configuration isn't compromised as its set to my address only, I know about the debug stuff but I will have to investigate further. That address is not on my remote configs i just see it in memory along with mine recently since this month as I said earlier.

**Comment by UnamSanctam** [comment]
Yes the `84becQNTHchWj9A5LkdNrnZFPiV9NBAmrNcRv7KfonctGLRzSydwpRMiBSUbxCSL2BZZyDwW4hicX9GL6YXTjRfg4ZiB4hk` address is the most mysterious. It's not one of mine at least since I never use or recommend HashVault because they ban you if you have too many miners. I can't find that anywhere in memory when running the miner myself either which is why I suspected before that it might've been some "fake" version of the miner.

**Comment by toxic4a** [comment]
> Yes the `84becQNTHchWj9A5LkdNrnZFPiV9NBAmrNcRv7KfonctGLRzSydwpRMiBSUbxCSL2BZZyDwW4hicX9GL6YXTjRfg4ZiB4hk` address is the most mysterious. It's not one of mine at least since I never use or recommend HashVault because they ban you if you have too many miners. I can't find that anywhere in memory when running the miner myself either which is why I suspected before that it might've been some "fake" version of the miner.
> 
> I should probably also clean up some of the old debug, help and feature strings, maybe they might possibly cause a heuristic detection in some antivirus some day.

Ok I hope I get this thing resolved, thanks for the assistance.
