### ISSUE TITLE
semi-CLI functionality 

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/SilentCryptoMiner#1785]
How to collect through the command line?

**Comment by UnamSanctam** [comment]
You start the program through the command line like this:
`"Silent Crypto Miner Builder.exe" <PathToConfig> <PathToOutput>`

So if I have a saved configuration called Test.xml then I can do this:
`"Silent Crypto Miner Builder.exe" Test.xml Test.exe`
And it should compile an .exe called Test.exe

**Comment by anbu-squad** [comment]
just great!
Thank you!
