### ISSUE TITLE
SysWhisper

### ISSUE THREAD

**Issue by CarterSullivan** [UnamSanctam/SilentCryptoMiner#1786]
Hi, where can I find your custom SysWhisper? I've only been able to locate a compiled version, I'm curious what the source looks like.

**Comment by UnamSanctam** [comment]
Here's my modified version: [SysWhispersU.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/12489226/SysWhispersU.zip)

**Comment by CarterSullivan** [comment]
Thank you!

**Comment by CarterSullivan** [comment]
I can't seem to get this to compile with msvc. What compiler will it work with? It seems the original syswhispers2 has an option for compiler.

**Comment by UnamSanctam** [comment]
You can just run it python script directly to use it, if you want to "convert" it to an .exe file then you can use something like PyInstaller or auto-py-to-exe (which I use).

**Comment by CarterSullivan** [comment]
I mean the generated syscalls.c/h aren't compiling with msvc (after I use the python script to generate). I saw that the miner compiles with g++.exe, is there any way that I could generate the syscalls.c/h for use with msvc?

**Comment by UnamSanctam** [comment]
Aha, did you follow the original guide from the original SysWhispers2 (https://github.com/jthuraisamy/SysWhispers2#importing-into-visual-studio)? You also need to specify `-l masm` (I think) when running SysWhispers to generate the format for MSVC,

**Comment by CarterSullivan** [comment]
Oh, I did not follow that guide. Thanks for the info!
