### ISSUE TITLE
The miner needs Admin rights at startup, Although UAC option is unchecked

### ISSUE THREAD

**Issue by blackbeard1990** [UnamSanctam/SilentCryptoMiner#1788]
I have set the drop path in APPDATA, and unchecked the "run with system" option
like that:
https://ibb.co/9NJt84Z
But the miner still need Admin rights to run at startup, which prevent it from running if the windows UAC settings are set to High/Max

**Comment by UnamSanctam** [comment]
Did you disable "Run as Administrator" too?

**Comment by blackbeard1990** [comment]
No, since I am enabling "add to windows exculsions

**Comment by UnamSanctam** [comment]
Yes, so then it still needs administrator rights. All you're doing now is running the miner on the administrator account (that started the miner) instead of the System account.

**Comment by blackbeard1990** [comment]
is there a way to make it needs admin rights only at install, and not at startup ?

**Comment by UnamSanctam** [comment]
No not really, though you could technically modify the miner to do that (but you would technically lose some features of course). But the miner can run at startup no matter what the UAC settings are set to anyways so I'm not sure what the point is.

**Comment by blackbeard1990** [comment]
So after testing the previous version (3.2) , I come to conclude that the issue comes from the task scheduler,  not related to UAC, here's how:

I tested both version 3.2 and 3.3, on the same pc , and with the same miner settings

the 3.2 version works fine and run at startup without any issue, like shown in these images

https://ibb.co/DKHP3Bg
https://ibb.co/bvMcFq3

However  the 3.3  installs the miner successfully, and adds it to startup , but it didn't run after I restarted my pc

https://ibb.co/4fthCvT
https://ibb.co/xzKYDCv

That was tested on Max and Min UAC settings, and still had the same issue

So I tried to change the task trigger from "system startup" to "log on of any user", and then it worked

**Comment by UnamSanctam** [comment]
Hmm, does it work with "Run as System" enabled?

**Comment by blackbeard1990** [comment]
I didn't check to be honest

**Comment by blackbeard1990** [comment]
I tested it with "Run as System" enabled, and now it works fine and runs at startup

**Comment by UnamSanctam** [comment]
Aha, alright then. I guess "System Startup" doesn't work for administrator users on some computers then, I'll change it to use "log on of any user" again in the next version 3.3.1 when "Run as System" is disabled.
