### ISSUE TITLE
Everything is working

### ISSUE THREAD

**Issue by ARMANDTAKER** [UnamSanctam/SilentCryptoMiner#1793]
![20230905_022503.jpg](https://github.com/UnamSanctam/SilentCryptoMiner/assets/123572937/03f2d5d8-7365-4fcb-bd3d-0853d980d304)

- [ ] ![20230905_023147.jpg](https://github.com/UnamSanctam/SilentCryptoMiner/assets/123572937/19fe7b49-d585-4527-b13f-b13b72d4f3e7)

![20230905_023020.jpg](https://github.com/UnamSanctam/SilentCryptoMiner/assets/123572937/dfcf976b-f1e8-4930-a3e7-b3746076ebc3)

I tried even saving config file than editing it to add socks5:9050 line with diff synt

**Comment by UnamSanctam** [comment]
I saw you changed the issue title, but just in case anyone reads the issue then the correct command would be `--proxy=127.0.0.1:9050` in this situation (https://xmrig.com/docs/miner/command-line-options).
