### ISSUE TITLE
you can

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1795]
its Possible to add epic cash coin its same algo ?
randomx ?

**Comment by UnamSanctam** [comment]
Epic uses multiple different algorithms, for example RandomX and ProgPow so mining it is quite difficult since you would need to switch between miners to do it. It also has some extra weird things I think, there aren't a many useful resources online about it.

**Comment by tarekxxx** [comment]
aha i hope you can do it soon more profit like 500% more
