### ISSUE TITLE
any method for servers?

### ISSUE THREAD

**Issue by Roronoa-Z0RO** [UnamSanctam/SilentCryptoMiner#1800]
Hello dear unam, i wonder about that is there any method to do crypto miner on servers not only windows, linux as well, any way? hope you replay ASAP :)

**Comment by UnamSanctam** [comment]
No since that would require a full rewrite of the miner to work with Linux instead (nearly everything would have to work differently). Currently I sadly don't really have enough free time to build a completely new miner that works on Linux.

**Comment by Roronoa-Z0RO** [comment]
ok, what pools now are supported for this miners and not block my address ?! @UnamSanctam

**Comment by UnamSanctam** [comment]
All pools are supported really, if by "block" you mean ban then only still only nanopool and 2miners are known not to ban.
