### ISSUE TITLE
Question on code

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1801]
Good afternoon Unam. Tell me please. What part of the code to remove so that the miner does not copy itself into the folder?

**Comment by UnamSanctam** [comment]
This is the code that writes the miner to the installation folder:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Resources/Code/miner.cpp#L169

**Comment by masterjek** [comment]
If I use a private crypto. Can I disable the cryptor you made with the default miner?

**Comment by UnamSanctam** [comment]
As long as you disable "Startup" in the miner and use the "Startup" option in the crypter then any crypter (that supports 64-bit native programs) should theoretically work with the miner.

**Comment by masterjek** [comment]
The private encryptor worked fine with all previous versions. Starting from version 3.3.0 and version 3.3.1, the miner stops working after encryption. I use the same settings as in previous versions. But versions 3.3.0 and 3.3.1 become completely inoperable after encryption. I cannot understand what is the reason.

**Comment by UnamSanctam** [comment]
And you have disabled "Startup" in the miner? The miner installer/injector didn't really have that many changes in 3.3.0 and 3.3.1, the compiler is different (to lower detections) but that shouldn't matter. Can you post your miner settings? And the settings of the crypter?

**Comment by masterjek** [comment]
Can we discuss this by email?

**Comment by UnamSanctam** [comment]
Sure.

**Comment by masterjek** [comment]
I wrote to you by mail.

**Comment by possessed-client** [comment]
> Sure.

I'm gonna hijack this thread a bit for my code questions as well. Unam, do you have any idea as to whether the current 3.x injection method is allowed by AVG/Avast? Because I can get the file to run and live through the sandbox popup, but it gets runtime detected somewhere at the old 2.5 version's injection, so I need to know whether you new code is worth mimicking.
Another question is about the AMSI bypass - is it still in use in 3.x versions? What about ETW&WLDP? If not, why? Are these public methods not useful any more against any AVs?

**Comment by UnamSanctam** [comment]
>I'm gonna hijack this thread a bit for my code questions as well. Unam, do you have any idea as to whether the current 3.x injection method is allowed by AVG/Avast? Because I can get the file to run and live through the sandbox popup, but it gets runtime detected somewhere at the old 2.5 version's injection, so I need to know whether you new code is worth mimicking.
Another question is about the AMSI bypass - is it still in use in 3.x versions? What about ETW&WLDP? If not, why? Are these public methods not useful any more against any AVs?

I think so, I've gotten mixed results when testing. Sometimes Avast doesn't detect anything and sometimes it does.

The AMSI bypass and other bypasses aren't used in the miner anymore, the biggest problems are that the bypasses usually get detected before anything else gets detected. They also didn't seem to help much with detections in the long rung.
