### ISSUE TITLE
XMR mining using GPU

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#1810]
Hello bro...Sorry for rasing issue for this question. ...i just installed the miner on PC that have GPU and have a good hash when it mines ETC. My question is can i mine XMR using GPU? does the H/s will be the same as the hash i mine ETC ? when  mining ETC, my hash is 4.44MH/s

**Comment by UnamSanctam** [comment]
It's possible to do so but it won't be any profitable at all, XMR is a CPU coin by design, so it would be very unprofitable to mine it using a GPU. The hashrate would not be the same as ETC since it's a different algorithm (and algorithm family).

**Comment by DerXanRam** [comment]
ok tnx... but if i want, can i add randomx algo configuration using the web panel inside the miner that have only etc configuration?

**Comment by UnamSanctam** [comment]
No, because they are different miners. If you didn't include an XMR miner then the installed miner won't have the XMR miner inside of it.

**Comment by DerXanRam** [comment]
Ok thanks very much... have a nice day bro
