### ISSUE TITLE
GUI Framework

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1824]
I remember that you mentioned somewhere in a issue that you couldn't find any C# framework that you really liked besides the current one. What about using WPF? That could make it look alot better and i recently tried it and WPF is really easy to learn. only things u would have to recode is just the gui nothing else u can use the same functions on buttons and so on.

**Comment by UnamSanctam** [comment]
Well I don't really like WPF either since everything is in XAML, and permissions aren't very fun to work with either.

**Comment by UnamSanctam** [comment]
Sometimes you can need certain application security permissions to do some things on the computer, though I don't think that's the case usually for standalone applications.

**Comment by shainodev** [comment]
Oh alright, i just felt like c# and the framework ur using has become too old and basic, but aslong as u like it its fine

**Comment by UnamSanctam** [comment]
Well, WPF is C#, WPF is just the "newer version" of WinForms (what the miner uses).
