### ISSUE TITLE
Payload

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1834]
Hello Unam. Can you tell me which part of the code contains the miner's payload? Or is this the part of the code where the injection occurs?

**Comment by UnamSanctam** [comment]
The miner payloads themselves get created here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Forms/Builder.cs#L300
Using this function which adds the file data as an encrypted (XOR) char array into the program using a header file:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Classes/Codedom.cs#L234
The miner then accesses the miner payloads when calling the injection:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Resources/Code/miner.cpp#L207

**Comment by masterjek** [comment]
Is it possible to ask an extended question about this, but by email?

**Comment by UnamSanctam** [comment]
Yes of course.

**Comment by masterjek** [comment]
I wrote everything to you by email, I just posted it in a previously discussed question.
