### ISSUE TITLE
How to setup xmrig-proxy?

### ISSUE THREAD

**Issue by ThunderX-HUB** [UnamSanctam/SilentCryptoMiner#1836]
Pls

**Comment by masterjek** [comment]
You will run xmrig-proxy on vps server?

**Comment by ThunderX-HUB** [comment]
> You will run xmrig-proxy on vps server?

Yes

**Comment by ThunderX-HUB** [comment]
> You will run xmrig-proxy on vps server?

Can you send me the config.json of xmrig-proxy? I don't know what to do in that file

**Comment by UnamSanctam** [comment]
In that config there is only 2 things you need to change, first the pool connection inside the "pools" section and then also the ports inside the "bind" section which miners will connect to.

**Comment by masterjek** [comment]
Below is the screenshot I have highlighted everything that needs to be changed.
![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/34f18812-38ac-4b38-b25b-29cfdd2d4f04)

**Comment by masterjek** [comment]
tls - true - if the pool uses a secure connection
tls - false - if the pool uses an unsecured connection.

**Comment by ThunderX-HUB** [comment]
> Below is the screenshot I have highlighted everything that needs to be changed. ![1](https://user-images.githubusercontent.com/36513967/271304182-34f18812-38ac-4b38-b25b-29cfdd2d4f04.jpg)

it worked, thank you very much!
