### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1848]
Hello Unam. Tell me if I disable the miner start option in the builder, highlighted in red in the screenshot

![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/3e61e4b8-4efd-4a5f-9e9c-b1abc673d0e9)

Will the options underlined in blue work? Or are they also automatically ignored?

**Comment by UnamSanctam** [comment]
They can only work if "Startup" is enabled so those options will be disabled.

**Comment by masterjek** [comment]
Well understood. If I remove from the code the part that creates a task in the scheduler and copies the miner to a folder. But in the builder I leave launch enabled, then will those options that are underlined in blue work or not?

**Comment by UnamSanctam** [comment]
The "Run as System" is done by the Task (it starts the miner as System) so your replacement way of starting the miner would have to start the miner as System instead. The watchdog can work as long as you copy the miner to the same place as the "Startup" would.

**Comment by masterjek** [comment]
Thanks, I understand.

And another question: when do I disable the miner?

![2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/f52b490d-4b71-4d12-bc09-217d8f7c9a59)

File - WinRing0x64.sys - appears in the temp folder with a random name

When I enable the miner start option

![3](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/101eec18-0362-44ec-819c-b48ab23c6cf0)

then file - WinRing0x64.sys does not appear in the temp folder. This is fine? As I understand it, then with a random name it is located somewhere in another folder?

**Comment by UnamSanctam** [comment]
Yes, since it gets written into the users temp folder automatically, and since miner would be running as "System" when you have it enabled then it will be in the System users temp folder instead.

**Comment by masterjek** [comment]
Unnam I have this problem. I inject the miner into explorer.exe - it starts without problems. I select injection in conhost.exe the miner stops starting. I don’t understand what could be the reason?

**Comment by UnamSanctam** [comment]
Is the path correct? Does it fail injection with the normal miner (without any modifications)?

**Comment by masterjek** [comment]
I'm turning off the path. It should run from any folder. Miner xmrig.exe encrypted

**Comment by UnamSanctam** [comment]
I mean, if you have modified anything in the miner is the path to conhost.exe correct? Since explorer.exe is inside the Windows folder while conhost.exe in inside the Windows\System32 folder.

**Comment by masterjek** [comment]
In code has removed the creation of a task in the scheduler and copying the miner to a folder. 

![4](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/23e73488-dc2f-47be-b867-1eba348b4e59)

**Comment by UnamSanctam** [comment]
And does it work with an unmodified builder?

**Comment by masterjek** [comment]
I'm using builder version 3.2.0. xmrig.exe - I am using version 3.3.1. It doesn’t even work with the original builder in the code of which I didn’t remove anything. But it started successfully when injected into explorer.exe, cmd.exe - I haven't checked the other options.
As I understand it, the problem is related to using the builder version 3.2.0 with the miner from the new version 3.3.1.

**Comment by UnamSanctam** [comment]
Possibly, though I can't think of a specific reason why that would be the case.

**Comment by masterjek** [comment]
I tested the miner on my computer - But I can't find the file WinRing0x64.sys - \Users\UserName\AppData\Local\Temp - I know that it is created with a random name, but it is not in this folder. I'm looking for these files to delete them.

**Comment by UnamSanctam** [comment]
Check either `C:\Windows\Temp` or `C:\Windows\System32\config\systemprofile\AppData\Local\Temp` and see if you can find it there.

**Comment by masterjek** [comment]
Thanks, this worked for me. I found the files.

**Comment by masterjek** [comment]
I checked, the miner works without this file - WinRing0x64.sys - Why is it even needed? Some antiviruses detect it. As I understand it, xmrig.exe can work without this file?

**Comment by UnamSanctam** [comment]
It increases the RandomX hashrate by quite a bit https://xmrig.com/docs/miner/randomx-optimization-guide/msr, though you can mine without it of course, you'll just get a lower hashrate.

**Comment by masterjek** [comment]
The most interesting thing is that I just checked on my computer with a processor i9 -13900k at 20 percent usage, I got the same speed of 6.5 KH/s with file WinRing0x64.sys and and without him - For me the speed is the same in both cases.

**Comment by UnamSanctam** [comment]
Did you restart the computer before checking? Since otherwise the values might already have been set.

**Comment by masterjek** [comment]
After reboot the speed is still the same - 6.5 KH/s. I checked all three paths where the file can be installed - WinRing0x64.sys. And this file is not there. So for me the speed doesn't slow down.

**Comment by UnamSanctam** [comment]
Yes maybe not, though for most computers that will be the case.
