### ISSUE TITLE
Web Panel And VPS Server

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1854]
Hello Unam. I have approximately 10,000+ workers i have already changed three different service providers for VPS servers. I launch the web panel on the VPS server and after a couple of minutes the CPU load is 100%. I transferred the web panel to my computer with CPU i9-13900k and it works great.
It turns out I need to look for a VPS server with only a processor i9-13900. It turns out that other processors cannot service the web panel when the number of workers reaches 10,000+
I just want to understand for myself which VPS server I should choose so that the web panel can work properly. You said earlier that the web panel is not resource-demanding at all. But all the VPS where I run it have an 8-core processor and it is immediately loaded at 100%. I'm getting errors Endpoint error db locked. File - unamwebpanel.db-wal - becomes larger than a gigabyte.
As I understand it in my case, only buy a VPS server with i9-13900k?

**Comment by UnamSanctam** [comment]
Hmm, it sounds like a more probable cause might be a slow read/write speed of the disk, is it possible for you to check what it is? Since if the database write is bottle-necking then so will the CPU.

**Comment by masterjek** [comment]
So I measured the disk speed. I'm attaching a screenshot.

![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/b355d7bc-0fb9-46b9-b66a-2ac6f9336d13)

**Comment by UnamSanctam** [comment]
Alright that should definitely be more than fine then, is the RAM fine too? In the Task Manager (or something similar) is a lot of RAM being used or is a lot of disk being written?

**Comment by masterjek** [comment]
Screenshot of resource monitoring.

![2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/7e6f47ed-dc1e-488c-9ee2-a60793ada43e)

**Comment by masterjek** [comment]
I can take a screenshot when the web panel freezes and turns off. Just when the web panel loads the processor at 100%. I delete the database and copy the empty one again, it works for about 1-2 days.

**Comment by UnamSanctam** [comment]
Hmm, then that's quite strange, can you try with this [UnamWebPanel.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/12840499/UnamWebPanel.zip) version? It's some parts of the next version.

**Comment by masterjek** [comment]
Thank you. I installed everything and will test it. The problem usually appeared after two days of running the web panel and restoring all workers to the database. Based on the results of the tests, I’ll post how everything works.

**Comment by masterjek** [comment]
There were approximately 10,000 workers and the web panel froze, even the new version.

![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/2d3b6876-1f03-4783-abae-a66f3837f984)

**Comment by masterjek** [comment]
When I stopped the web panel the file size became 238 MB

![2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/c71718b4-91bb-462f-b31c-ba8cabe73ce3)

This is still a small size, usually it becomes a couple of gigabytes.
