### ISSUE TITLE
Always Face Same Problem

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#1856]
![Screenshot (209)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/20240556/c58121f8-3178-425f-9169-e880db1d132e)

Worker totally idle no antivirus at all no block traffic everything fine but miner keep to 0 Hashrate even when change from normal connection to proxy connection its same nothing change :( how i can pass this one so annoying pool sayed have 23 worker but in panel 38 39 ++ alot of them not working and i double check in config in panel working fine and also pastebin everything working fine as syntax aswell

**Comment by notevil1337** [comment]
Possible reasons
1) Double click your build checker executable.
2) Make sure you have enabled Watchdog.
3) Their PC should be restarted.
4) Not enough cores enabled.

**Comment by tarekxxx** [comment]
Its CPU not GPU have enough everything was gain more then 3k

**Comment by UnamSanctam** [comment]
Is that something like a server? Since it seems to have quite atypical specifications. Do you know if it has enough free RAM to mine RandomX (like 2.3 GB)? I've probably asked you to check before but does it work if you mine something less resource demanding than RandomX?

**Comment by tarekxxx** [comment]
64 Giga Ram free and always 0 hashrate
