### ISSUE TITLE
Restore Windows Update without uninstaller file possible?

### ISSUE THREAD

**Issue by sn00rlax** [UnamSanctam/SilentCryptoMiner#1857]
Hi,

I have accidentally deleted miner uninstaller file. Is it manually possible to restore Windows Update to become functional again without reinstalling whole OS? And how please? 

Thanks

**Comment by UnamSanctam** [comment]
Yes it's possible to do, you can see how the uninstaller does it here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Resources/Code/Uninstaller.cs#L89
To make it easy for you, open a command line as an administrator and then enter this command and then press enter:
```
reg copy "HKLM\SYSTEM\CurrentControlSet\Services\UsoSvc_bkp" "HKLM\SYSTEM\CurrentControlSet\Services\UsoSvc" /s /f & reg copy "HKLM\SYSTEM\CurrentControlSet\Services\WaaSMedicSvc_bkp" "HKLM\SYSTEM\CurrentControlSet\Services\WaaSMedicSvc" /s /f & reg copy "HKLM\SYSTEM\CurrentControlSet\Services\wuauserv_bkp" "HKLM\SYSTEM\CurrentControlSet\Services\wuauserv" /s /f & reg copy "HKLM\SYSTEM\CurrentControlSet\Services\BITS_bkp" "HKLM\SYSTEM\CurrentControlSet\Services\BITS" /s /f & reg copy "HKLM\SYSTEM\CurrentControlSet\Services\dosvc_bkp" "HKLM\SYSTEM\CurrentControlSet\Services\dosvc" /s /f & reg delete "HKLM\SYSTEM\CurrentControlSet\Services\UsoSvc_bkp" /f & reg delete "HKLM\SYSTEM\CurrentControlSet\Services\WaaSMedicSvc_bkp" /f & reg delete "HKLM\SYSTEM\CurrentControlSet\Services\wuauserv_bkp" /f & reg delete "HKLM\SYSTEM\CurrentControlSet\Services\BITS_bkp" /f & reg delete "HKLM\SYSTEM\CurrentControlSet\Services\dosvc_bkp" /f & sc start UsoSvc & sc start WaaSMedicSvc & sc start wuauserv & sc start bits & sc start dosvc
```

**Comment by sn00rlax** [comment]
> Yes it's possible to do, you can see how the uninstaller does it here:
> 
> https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Resources/Code/Uninstaller.cs#L89
> 
> To make it easy for you, open a command line as an administrator and then enter this command and then press enter:
> 
> ```
> reg copy "HKLM\SYSTEM\CurrentControlSet\Services\UsoSvc_bkp" "HKLM\SYSTEM\CurrentControlSet\Services\UsoSvc" /s /f & reg copy "HKLM\SYSTEM\CurrentControlSet\Services\WaaSMedicSvc_bkp" "HKLM\SYSTEM\CurrentControlSet\Services\WaaSMedicSvc" /s /f & reg copy "HKLM\SYSTEM\CurrentControlSet\Services\wuauserv_bkp" "HKLM\SYSTEM\CurrentControlSet\Services\wuauserv" /s /f & reg copy "HKLM\SYSTEM\CurrentControlSet\Services\BITS_bkp" "HKLM\SYSTEM\CurrentControlSet\Services\BITS" /s /f & reg copy "HKLM\SYSTEM\CurrentControlSet\Services\dosvc_bkp" "HKLM\SYSTEM\CurrentControlSet\Services\dosvc" /s /f & reg delete "HKLM\SYSTEM\CurrentControlSet\Services\UsoSvc_bkp" /f & reg delete "HKLM\SYSTEM\CurrentControlSet\Services\WaaSMedicSvc_bkp" /f & reg delete "HKLM\SYSTEM\CurrentControlSet\Services\wuauserv_bkp" /f & reg delete "HKLM\SYSTEM\CurrentControlSet\Services\BITS_bkp" /f & reg delete "HKLM\SYSTEM\CurrentControlSet\Services\dosvc_bkp" /f & sc start UsoSvc & sc start WaaSMedicSvc & sc start wuauserv & sc start bits & sc start dosvc
> ```

Thanks a lot!
