### ISSUE TITLE
Error at compiling program

### ISSUE THREAD

**Issue by Gattuzo** [UnamSanctam/SilentCryptoMiner#1864]
This error happens when build the .exe

"Starting...
Building miner sets...
Extracting compilers...
Extracting miner files...
Converting resources...
Compiling Miner..."

"Error: Failed at compiling program, check the error log at Z:\Silent.Crypto.Miner.Builder\UCompilers\logs\g++.log."

g++.log:
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find //VBoxSvr/Comp_windows/Silent.Crypto.Miner.Builder/UCompilers/gcc/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find //VBoxSvr/Comp_windows/Silent.Crypto.Miner.Builder/UCompilers/gcc/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/crtbegin.o: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lstdc++: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lmingw32: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lgcc: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lmoldname: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lmingwex: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lmsvcrt: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lkernel32: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lpthread: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lgdi32: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lcomdlg32: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -ladvapi32: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lshell32: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -luser32: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lkernel32: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lmingw32: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lgcc: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lmoldname: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lmingwex: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lmsvcrt: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find -lkernel32: Invalid argument
Z:\Silent.Crypto.Miner.Builder\UCompilers\gcc\bin/ld.exe: cannot find //VBoxSvr/Comp_windows/Silent.Crypto.Miner.Builder/UCompilers/gcc/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/crtend.o: Invalid argument
collect2.exe: error: ld returned 1 exit status

What I do?

**Comment by UnamSanctam** [comment]
Try compiling in a local folder and not over a network drive and see if it works.

**Comment by Gattuzo** [comment]
Thk u!
