### ISSUE TITLE
Different pools

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1871]
Hello Unam. Please tell me will this work:
1. If I specify several pools in the builder, here is an example - pool1,pool2,pool3 - If the miner fails to connect to pool 1 will it try to connect to pool 2? all pools have the same port 443.
2. Option two pools have different ports - pool1,pool2,pool3 
                                                                    port1,port2,port3
Is this how it will work?
Write which of the two options will work?

**Comment by masterjek** [comment]
I realized that I wrote it wrong - will this work? - pool1:port1,pool2:port2,pool3:port3

**Comment by masterjek** [comment]
Tell me how to add a backup pool to the builder? Or it can't be done.

**Comment by UnamSanctam** [comment]
You can't directly in the builder since that would require being able to add a comma separated to all pool fields, like Pool, Wallet Address, Password, SSL/TLS and NiceHash mining. But you can have 3 total pools (two failover) if you use the "Remote Configuration" and web panel configuration, when you add a pool with those they get added into the pool list like so:
1) Web panel configuration pool
2) "Remote Configuration" pool
3) Builder pool

**Comment by masterjek** [comment]
1. WebPanel difficult to use. I was blocked from the domain where it was located. I transferred it to the VPS server, a month later complaints were filed against the server and it was blocked.
2. Can a remote configuration be blocked based on complaints?

**Comment by UnamSanctam** [comment]
1. Yes that can happen, the least likely to get banned method is to host it yourself behind a port forwarding VPN (like many do for RATs).
2. Sure though it doesn't usually happen from what I've seen, one miner I know still has all their Pastebins up and they've been mining for 3 years, each Pastebin paste they have up have on average about 30 000 000 views each. But since it's so easy to set up a "Remote Configuration" then it's quite easy to create a lot of backup links to use. For example there are hundreds if not thousands of different paste websites online.

**Comment by masterjek** [comment]
1. I just can't find any VPN that supports port forwarding. I find a VPN service, I write to technical support, they answer that port forwarding is disabled, for better anonymity and connection security. If you know at least one VPN service that allows port forwarding, please tell me what kind of service it is?
2. Do I understand correctly that I can specify at least ten remote configurations in the builder? Do I just need to separate them with a comma?

**Comment by UnamSanctam** [comment]
1. Usually I recommend PureVPN, they've had some connectivity problems for me in the past on their dedicated IP servers but now that they support OpenVPN on those servers I have not had any problems. I think you can get the VPN with a dedicated IP and port forwarding (any port can be opened) for 5 years for around $150 (around $30/year).
2. Yes that will  work fine, there's no real limit to the amount that you can enter. The only limit is the Windows string length limit that ShellInfo can take, which is 32 767 characters, so as long as all the options (the string shown in the checker) are below that then it will work.

**Comment by masterjek** [comment]
Thanks for the help. Another off-topic question. If I don't use:
1. Rootkit
2. Block Websites
3. Watchdog
Can I remove all this from the code? Without damaging other functions of the miner?

**Comment by UnamSanctam** [comment]
Sure you can do that, though all of it is already removed from the miner code if you don't have it enabled.

**Comment by masterjek** [comment]
Unam Please tell me:
1. I buy a VPS server, after which I receive login information: IP address, login and password.
2. When I install a VPN on the VPS server and turn it on, should I connect to the server using the VPN IP?

**Comment by UnamSanctam** [comment]
1. Yes do that or host it yourself.
2. Usually you would do that yes, it can depend but for most setups that will be the case.

**Comment by masterjek** [comment]
I bought a VPS server and installed it on it Purevpn, got a dedicated IP address, opened port 443. I enabled VPN on the server and after connecting I was disconnected from the server. Now using RDP I cannot connect to the server either through its IP address, which I received after the purchase, or through the IP address of the VPN. I was only able to connect through the emergency console in the browser. I see that the VPN is working there, the port is open, but why can’t I connect via RDP?

**Comment by UnamSanctam** [comment]
Did you also open the RDP port? Usually it's port 3389.

**Comment by masterjek** [comment]
I didn't know this, I just opened port 3389

![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/6999f344-cb56-4afc-824c-8f03a287bd7e)

But this didn’t help, I still can’t connect to the server.
I also chose this option as in the screenshot below.

![2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/24da4f8f-bd47-4c5d-b28c-1151ed9e0be3)

This didn't help either.

**Comment by UnamSanctam** [comment]
And you're connected to the correct PureVPN server? If you connect to the VPS using the emergency console and check the IP on some IP checking site then does it show your dedicated IP?

**Comment by masterjek** [comment]
In VPN I bought a dedicated IP address from Canada. The IP address checking service shows my purchased Canadian IP to which I connected.

**Comment by masterjek** [comment]
Sorry to bother you. I couldn't come in because of my stupidity and carelessness. I was assigned port 51378 to connect to the server.

**Comment by UnamSanctam** [comment]
Aha alright it's no problem, I forgot that some do it that way.

**Comment by masterjek** [comment]
The web panel is very demanding on the speed of the Internet connection when there are, say, 10,000 workers?
The screenshot below shows the speed test.

![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/8010e72e-e0cd-4cbf-ba72-a6f7415aa54e)

Will this be enough for a web panel with a large number of workers?

**Comment by UnamSanctam** [comment]
Sure that should be fine, 10 000 miner is about 166 miners per second and each connections data is usually less than 1kb of traffic, so on average it should be about 150 KB/s transferred.

**Comment by UnamSanctam** [comment]
It can take a little while for the VPN changes to propagate, try disconnecting and reconnecting the VPN. Port 80 is http and port 443 is https, and to be able to get a certificate for the site then it will need to contact the normal site (port 80). Is the webserver also listening on port 80 at the moment? It should be listening to both 80 (for http) and 443 (for https).

**Comment by masterjek** [comment]
The most interesting thing is that I opened port 80 in the VPN, but did not open port 443. On startup XAMPP I check the ports in the browser, it shows that port 443 is open, but port 80 is closed.

**Comment by masterjek** [comment]
I rebooted the server and VPN and everything worked. But another interesting thing appeared. Unam This could be the case: there is a VPN running on the server, the browser shows the VPN IP, but I can connect to the server via RDP using its native IP address?

**Comment by UnamSanctam** [comment]
Okay great. Generally the native IP address will still work for incoming connections unless the server has been configured to block them. So connecting using the real IP will work unless configured specifically to not work. That's because the server is just routing all of its traffic through the VPN server (like a layer in front of it) but the native server can still be connected to if you know its IP.

**Comment by masterjek** [comment]
Thanks for the help. When I set multiple remote configurations. Do I just separate them with a comma? remote1,remote2
No space needed between them - remote1, remote2

**Comment by UnamSanctam** [comment]
Yes that's correct, only a comma between them: `remote1,remove2,remote3`
