### ISSUE TITLE
CPU low hashrate 

### ISSUE THREAD

**Issue by Xrdem** [UnamSanctam/SilentCryptoMiner#1872]
I tried with my own system (Ryzen 5 2600x) .Normally I get 3000H/s with xmrig , if I enable huge pages I get even more..But if I use config that below active 900H/s , idle 1500H/s  that I get .CPU usage changes between %20-60 at the time..

>{
    "algo": "rx/0",
    "pool": "xmr-eu1.nanopool.org",
    "port": 10343,
    "wallet": "*****************************************************************************************.{COMPUTERNAME}/password",
    "password": "password",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 1,
    "idle-cpu": 80,
    "stealth-targets": "ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,AnVir.exe,PLlhDBWxRt.exe,GPU-Z.exe,regedit.exe,Autoruns.exe,adwcleaner.exe,CCleaner64.exe,bitdefender.exe,kaspersky.exe,panda.exe,zoneAlarm.exe,Malwarebytes.exe,defender.exe,eset.exe,360.exe,IObit.exe,ffxiv.exe,ffxiv_dx11.exe,MSIAfterburner.exe,steam.exe,origin.exe,upc.exe,GOG Galaxy.exe,EpicGamesLauncher.exe,Discord.exe,RiotClientServices.exe,XboxPcApp.exe",
    "kill-targets": "kpf4gui.exe ,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe,afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,msmpeng.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,MRT.exe",
    "stealth-fullscreen": true,
"remote-config": "https://pastebin.com/raw/********,https://rentry.co/*****/raw",
"api-endpoint": "https://******.000webhostapp.com/api/endpoint.php"
}

I changed "max-cpu": 100 and "idle-cpu": 100  but difference is at the start CPU usage is %60-70 and Hashrate is when active 1500H/s , when idle 1700H/s..I also tried Advanced parameters but doesn't effect to much.

**Comment by Xrdem** [comment]
I get hashrate information from UnamWebPanel btw

**Comment by UnamSanctam** [comment]
And are you running it as administrator?

**Comment by Xrdem** [comment]
Yes always I

**Comment by Xrdem** [comment]
GPU have same probem as well..According to "https://www.kryptex.com/en/hardware/nvidia-gtx-1050-ti" I need to get 13.9 MH/s But I get 1.1 MH/s ,When idle I get 2 MH/s

![Capture](https://github.com/UnamSanctam/SilentCryptoMiner/assets/116120205/636a87d0-2bf3-40a2-82ee-f110ed15ee3b)

btw GPU working weird..Up and down I mean

**Comment by UnamSanctam** [comment]
Yes it's supposed to go up and down, since that's how using 50% works. For example, to use 50% it would do this: first use 100% (can't use less) for maybe 10 milliseconds and then 0% for 10 milliseconds, and this would mean it's using 50% GPU over those 20 milliseconds. It's only noticeable either because the interval of your checking is very low or because the GPU isn't fast enough to finish each mine and sleep cycle within the interval period, probably the latter. But you can try mining something other than ETC such as some coin using KawPow and see what your hashrate is https://whattomine.com/.

**Comment by Xrdem** [comment]
Possibly I m not gonna use GPU part but what do you think about MH/s ? Because it weird.."https://whattomine.com/gpus/31-nvidia-geforce-gtx-1050-ti?cost=0.1&cost_currency=USD&sort=revenue24_desc" also say I need to get 13MH/s.Even with "max-gpu": 50 I need to get 6 ish..Am I right??

**Comment by UnamSanctam** [comment]
It can depend on a few different factors, try mining a coin with a lower VRAM requirement and see if there's a difference. I have a few GPUs I test on and the hashrate is all good on those, the ones I have for testing are: GTX 970, GTX 1070, RTX 2070, RTX 4090, Radeon RX 6700 XT and Radeon RX 5700.

**Comment by Xrdem** [comment]
I compiled miner a lot, I will try some other day. This is my last question ,do you know any good crypter or obfuscator??

**Comment by UnamSanctam** [comment]
Not really, whenever someone tells me about one it usually isn't positive, though I know that most people seem to have the most success with those that do virtualization (like professional software protection software) but they also have their own issues.
