### ISSUE TITLE
add Zephyr coin algorithm

### ISSUE THREAD

**Issue by Lastik2288** [UnamSanctam/SilentCryptoMiner#1881]
In general, Zephyr coin is written in RandomX - it’s like Monero, only the complexity is lower and the price is lower. If you have few miner users and therefore a small hashrate, for example 2kH/s per month, you will already receive 2 dollars, and according to my calculations, 1 user 1-2 kH/s. It is much more profitable than Monero. If you have 60 users, then that’s 2 dollars every day, which is very good! Monero will give much less, or more precisely $1.59 I tested a miner on my PC, but instead of a Monero wallet, I specified a marshmallow wallet and another pool. It was in the dispatcher and was even in the checker, but mining was not displayed on the site. I think this currency is worth adding. If you add a big thank you!
I used this site https://zephyr.hashvault.pro/en/ as a pool.

**Comment by UnamSanctam** [comment]
You can mine Zephyr already, just select RandomX and it will work (I currently mine Zephyr).

**Comment by Lastik2288** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/99122688/f2c70986-5c09-4306-af96-33854f04fbc6)
I tried this and just replaced the pool and wallet. Maybe I should change the pool? Which one do you use, if it's not a secret? What does GPU mining do in Advance?

**Comment by UnamSanctam** [comment]
Yes selecting RandomX and then changing the wallet and pool to both a Zephyr wallet and a Zephyr pool is what you should do, right now I'm mining on https://zephyr.miningocean.org/. "GPU Mining" is an option to enable mining on the GPU, but RandomX is an algorithm designed to only be profitable on CPUs so GPU mining RandomX is not recommended. For GPU mining one should mine a GPU coin using an algorithm designed to be profitable on GPUs.

**Comment by Lastik2288** [comment]
Got it! Thanks a lot! Looking forward to the update!
