### ISSUE TITLE
Zephyr Coin

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1882]
Hello Unam. Can you tell me how to switch Zephyr on on the NiceHash website. They wrote that they added this algorithm to their miner. I can’t understand whether I can switch my workers to this algorithm through the web panel?

**Comment by UnamSanctam** [comment]
Zephyr uses the RandomX algorithm (same as Monero). If you're already selling RandomX hashrate on NiceHash then you're most likely already selling it to buyers mining Zephyr.
