### ISSUE TITLE
Can we have the same process inside Stealth Targets & Kill Targets inside the same miner?

### ISSUE THREAD

**Issue by sn00rlax** [UnamSanctam/SilentCryptoMiner#1886]
Hi,

I have noticed a few of my "workers" are still able to use CCleaner even though I have added it into Kill Targets list for the xmrig miner. So I added it into its stealth targets list too. 

Can this cause any interruptions? Ff the same process is added to both Kill Targets & Stealth Targets inside the same xmrig miner? 

The process is called ""CCleaner64.exe". 

Also, do you know why it's not getting killed if it's added to the Kill Targets list? 

Thanks.

**Comment by UnamSanctam** [comment]
No having it inside both should be fine. The only reason it would not kill it is if it does not have permissions do to so (if CCleaner64.exe is running at a higher level than the miner).
