### ISSUE TITLE
controll miners from own telegrame bots

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1898]
i have small idea i think it's better solution for web penel issue
if you can intigrade to telegrame api i mean controll miners from own telegrame bots

**Comment by UnamSanctam** [comment]
I don't think that would do much really, since the web panel is mostly for monitoring and doing that through Telegram feels like it would be very awkward.

**Comment by DARK-DEVIL-66** [comment]
my bot status is Not enough free VRAM ?

**Comment by DARK-DEVIL-66** [comment]
Worker CDESKTOP8B7
Password X
Username Système
Computer Name DESKTOP-8B7S9F4
Type ethminer
Version 3.3.1
GPU Intel(R) HD Graphics, NVIDIA GeForce GT 720M
CPU Intel(R) Pentium(R) CPU 2020M @ 2.40GHz
Active Window Running as System

**Comment by UnamSanctam** [comment]
Yes it's a GT 720M which has 2GB of VRAM, ETC requires at least 3.4 GB of free VRAM to be miner. Though even if it did have enough VRAM then A GT 720M would barely produce any hashrate at all anyways.

**Comment by DARK-DEVIL-66** [comment]
how can kill specific miner in web penal

**Comment by UnamSanctam** [comment]
You can't really kill a miner through the web panel, though you can pause it forever by adding something like `explorer.exe` into `"stealth-targets"`.

**Comment by DARK-DEVIL-66** [comment]
why hashrate are 0 at long time

User 4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.CIBNKHATTAB
Worker
Password x
Username Système
Computer Name IBNKHATTAB
Type xmrig
Version 3.3.1
GPU Intel(R) HD Graphics 520
CPU Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
Active Window Running as System
Run Time 22 hours 2 minutes 10 seconds

**Comment by UnamSanctam** [comment]
Either there isn't enough free CPU cores or potentially CPU cache, or there isn't enough free RAM. Especially since that CPU only has 2 cores, and I would assume that the RAM is quite limited in that computer as well (considering that it doesn't have a dedicated GPU and that CPU).
