### ISSUE TITLE
Bot / client in panel shows no mining hash

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#19]
So there is this NVIDIA GeForce GTX 1050 miner 

but is mining nothing also not a stealth issue i assume

https://i.imgur.com/6KpdP26.png

but others are mining

**Comment by Brainshot** [comment]
others are mining but this one isnt weirdly

**Comment by UnamSanctam** [comment]
It could be a 1050 3GB in which case it would have too little VRAM to mine.

**Comment by UnamSanctam** [comment]
And how many do you currently have in the panel? Is it working well?

**Comment by Brainshot** [comment]
> 
> 
> It could be a 1050 3GB in which case it would have too little VRAM to mine.

Yeah but why are they registered on the panel?

**Comment by Brainshot** [comment]
> 
> 
> And how many do you currently have in the panel? Is it working well?

well in this new panel i only have 2 currently

1 that is mining is a amd user the other isnt mining currently

**Comment by UnamSanctam** [comment]
> Yeah but why are they registered on the panel?

Why wouldn't it? It's just waiting until it has enough VRAM to mine but since the GPU doesn't have enough it will technically wait forever or until they get a new GPU, it won't close down just because it doesn't currently have enough VRAM.

**Comment by Brainshot** [comment]
> 
> 
> > Yeah but why are they registered on the panel?
> 
> Why wouldn't it? It's just waiting until it has enough VRAM to mine but since the GPU doesn't have enough it will technically wait forever or until they get a new GPU, it won't close down just because it doesn't currently have enough VRAM.

Oh now i understand how it works with the VRAM thing anyways thanks i was a little worried
