### ISSUE TITLE
Issue with obfuscating 

### ISSUE THREAD

**Issue by haxful** [UnamSanctam/SilentCryptoMiner#190]
Hello, when I follow the steps to use the ConfuserEx obfuscator when I replace the file and click okay I get this error does anyone know how to fix I've been trying for an hour and got nowhere
![image](https://user-images.githubusercontent.com/96766982/147541423-60263cf0-679e-4280-b477-a9549b8d8f75.png)

**Comment by UnamSanctam** [comment]
Are you sure you replace the file with the same name?

**Comment by haxful** [comment]
Yeah it's the same name as the original file I even tried putting the file on the desktop to see if it was a folder issue but I still got that error

**Comment by UnamSanctam** [comment]
Make sure that no folder has a space or something similar in it. If your username has a space (or any other special character) then build it on somewhere like the C drive.

**Comment by haxful** [comment]
I took the space out of the folder name it seems to be working, thank you.

**Comment by UnamSanctam** [comment]
Ah great, tcc and windres don't like spaces and such (since they originate from the Linux ecosystem).
