### ISSUE TITLE
CPU and GPU miner in one

### ISSUE THREAD

**Issue by LostMySpirit** [UnamSanctam/SilentCryptoMiner#1901]
Is it possible to make a build so it mines CPU and GPU on different settings everything in 1 build?

**Comment by UnamSanctam** [comment]
You can add one CPU miner and one GPU miner into the same build, like how the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings does it.

**Comment by LostMySpirit** [comment]
![grafik](https://github.com/UnamSanctam/SilentCryptoMiner/assets/72671296/3e8e3e07-6e6e-4d45-84ba-a058f0e6edc0)
is it possible that the worker name is random for every miner like in moner adress.{COMPUTERNAME} is that possible for kowpow too?

**Comment by UnamSanctam** [comment]
Yes you use `{COMPUTERNAME}` for RVN too, either enter it using `Wallet.{COMPUTERNAME}` or enter it into the "Worker Name" field.

**Comment by LostMySpirit** [comment]
is it fine when both gpu and cpu miner injects itself both in explorer.exe?

**Comment by UnamSanctam** [comment]
Yes that's fine.

**Comment by LostMySpirit** [comment]
last question
if i want to change the coin in pastebin for example with remote config, is it possible to change algo or does it need a new build for that?

**Comment by UnamSanctam** [comment]
Yes you can change the algorithm inside the "Remote Configuration".

**Comment by LostMySpirit** [comment]
okey thank you!
have a great day :)

**Comment by UnamSanctam** [comment]
You too! Good luck with your mining.

**Comment by LostMySpirit** [comment]
![grafik](https://github.com/UnamSanctam/SilentCryptoMiner/assets/72671296/fe75b164-2d51-46f5-9fc2-c0b06b052435)
i tried mining on ssl connection rvn.2miners.com:16060 what connection scheme should i use for that?

**Comment by UnamSanctam** [comment]
For that you should use `stratums (SSL/TLS)`.

**Comment by LostMySpirit** [comment]
but for some reason i dont become any shares in webpannel it shows me Active (Idle)

**Comment by UnamSanctam** [comment]
It can take some time to find a share, it depends on your hashrate.
