### ISSUE TITLE
Active but idle

### ISSUE THREAD

**Issue by LostMySpirit** [UnamSanctam/SilentCryptoMiner#1907]
![grafik](https://github.com/UnamSanctam/SilentCryptoMiner/assets/72671296/93cd1355-6e40-4a25-adbc-e1c2b357be2c)
What does that exactly mean like its mining but has no shares in a couple of minutes?
And is there a way to reduce that like turning the mining speed higher or something?

**Comment by UnamSanctam** [comment]
Active (Idle) is the "Idle Mining" state, normally when mining it will use the CPU/GPU amount set in "Max CPU"/"Max GPU", but when the user has not touched the mouse or keyboard for the "Idle Wait" amount of minutes then it will start using the set "Idle CPU"/"Idle GPU" amount of minutes. The feature is primarily used to be able to make it use more CPU/GPU when the user isn't using the computer.

**Comment by LostMySpirit** [comment]
Ah okey makes sense should knwo that my bad
ty anyway!
