### ISSUE TITLE
Possible to change silentcryptominer detection by windows?

### ISSUE THREAD

**Issue by LostMySpirit** [UnamSanctam/SilentCryptoMiner#1908]
Would it be possible to change the silent crypto miner detection by windows when i use your downloader or binder?
I basicly want to change the detection to another one would that be possible with on of your programs?

**Comment by UnamSanctam** [comment]
Not really, though you can add an extension exclusion for `.exe` into those programs and it should bypass that I'm pretty sure.

**Comment by LostMySpirit** [comment]
what exactly is that and how can i do it?

**Comment by UnamSanctam** [comment]
>what exactly is that and how can i do it?

You would change the source code to add the extension exclusion into the Windows Defender command and then build the builder.

>i made a dropper doing this but i having trouble with SettingsModifier:Win32/PossibleHostsFileHijack on file: C:\Windows\System32\drivers\etc\hosts

Make sure that you're not adding things like microsoft.com into the hosts file.

**Comment by flockedsolid** [comment]
what you mean?

**Comment by UnamSanctam** [comment]
>what you mean?

When you add things into the hosts file (like the "Block Websites" feature) then make sure there aren't any blacklisted URLs in it, like microsoft.com.

**Comment by LostMySpirit** [comment]
okey thank you!
i saw a issue here where someone mentioned zergpool with that feature of mining 1 coin and getting paid in another, so i wanted to add this feature for the gpu's. Is there any coin or algo which supports 2gb vram and 11gb that is worth switching on and getting good paid?

**Comment by LostMySpirit** [comment]
btw they're currently set on ravencoin i would know if that method with zergpool would be more profiable

**Comment by UnamSanctam** [comment]
Yes Zergpool is a coin-switching pool, meaning it switches automatically to the most profitable coin for a specific algorithm, so if you set it to mine KawPow then it will automatically mine whatever KawPow coin is the most profitable. And yes when mining to Zergpool it will exchange whatever you're mining and pay you in the cryptocurrency you want (like XMR). I believe that most KawPow coins (not things like RVN though of course) all have a DAG size of under 2GB.

**Comment by LostMySpirit** [comment]
so i would be the best opion o choose kawpow on zerg 
![grafik](https://github.com/UnamSanctam/SilentCryptoMiner/assets/72671296/8bc81aef-6abb-4d28-88ff-225f06e60854)
and i choose all of these coins so it can change between them right?

**Comment by UnamSanctam** [comment]
Yes, and you don't need to choose all the coins, if you don't choose any then it will use all of them. Though if you want it to only mine coins with a small DAG then only choose those ones.

**Comment by LostMySpirit** [comment]
do you know were is a good list of all kawpow algo coins listed with dag?

**Comment by UnamSanctam** [comment]
Sadly you usually have to just search online to try and find it for each individual coin, this site does have the DAG sizes of some coins: https://minerstat.com/dag-size-calculator.

**Comment by LostMySpirit** [comment]
-a kawpow -o stratum+tcp://kawpow.eu.mine.zergpool.com:3638 -u <WALLET_ADDRESS> --timeout 120 -p c=XMR,mc=CLORE/FREN/GPN/MEWC/NEOX/PAPRY/SATOX/XNA

so i found all this coins listed on zerg for kawpow, but how do i add it into json cfg?

**Comment by UnamSanctam** [comment]
It would be something like this 
```
"url": "stratums://WALLET_ADDRESS:c=XMR,mc=CLORE/FREN/GPN/MEWC/NEOX/PAPRY/SATOX/XNA@kawpow.eu.mine.zergpool.com:13638"
```

**Comment by LostMySpirit** [comment]
Okey thank you!
Is it possble like in 2 miners that the worker will be displayed with their computer names?

**Comment by UnamSanctam** [comment]
In Zergpool I believe each miner appears as its own worker automatically but if you want them to have the computer name then you can do this:
```
"url": "stratums://WALLET_ADDRESS:c=XMR,mc=CLORE/FREN/GPN/MEWC/NEOX/PAPRY/SATOX/XNA,ID={COMPUTERNAME}@kawpow.eu.mine.zergpool.com:13638"
```

**Comment by LostMySpirit** [comment]
![grafik](https://github.com/UnamSanctam/SilentCryptoMiner/assets/72671296/4d92dfb6-c87a-4792-aeab-288b3d1bc464)
14h for a share is kinda long right?

**Comment by UnamSanctam** [comment]
I believe the TTF there means how long it takes on average for the pool to find a block for that specific cryptocurrency, so for Neoxa Zergpool find on average a block every 14 hours.

**Comment by LostMySpirit** [comment]
okey i just let them mine now
I wanted to thank you that you share your time and knowledge i learned really much from you!

**Comment by UnamSanctam** [comment]
No problem, good luck with your mining!
