### ISSUE TITLE
Remote Config

### ISSUE THREAD

**Issue by MeowScripts** [UnamSanctam/SilentCryptoMiner#1918]
For connecting back to web panel, what exactly do i put in remote configuration? Nothing? http://ipaddress/path_to_unam/? http://ipaddress ?  

For API I did: http://ipaddress/api/endpoint.php

But I don't understand exactly what I'm meant to be putting for remote configuration? Thanks in advance.

**Comment by UnamSanctam** [comment]
The option is `"api-endpoint": "http://ipaddress/api/endpoint.php"`

**Comment by MeowScripts** [comment]
Yes, I'm aware of that option and I filled it accordingly, but the option above it "remote configuration". What's meant to go there? Or do I simply leave it unchecked?

**Comment by UnamSanctam** [comment]
What goes into that field is the URL where your "Remote Configuration" text is located, usually Pastebin or other paste sites are used for it. The "Remote Configuration" is a good backup in case something ever happens to your web panel.
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration

**Comment by MeowScripts** [comment]
Oh, I see. So basically just paste the json from builder into pastebin, copy the raw access link and paste that into remote configuration, eh?

**Comment by UnamSanctam** [comment]
Yes exactly, and you can have multiple backup URLs by separating the URLs with a comma (,).

**Comment by MeowScripts** [comment]
Wow, super nice. Thank you for your help and your shockingly fast response! :P I'll close this for now and make a new issue with appropriate topic title if I have any other issues.
