### ISSUE TITLE
Workers on Panel

### ISSUE THREAD

**Issue by MeowScripts** [UnamSanctam/SilentCryptoMiner#1919]
On 2miners my wallet shows that I have 1 worker, however, that worker is not appearing on my web panel for some reason.

I set up the panel in http://ipaddress/unam/ 

In API setting I did: http://ipaddress/unam/api/endpoint.php

Is the issue because some sort of config is expecting the path to be in /var/www/html/ root instead of /var/www/html/someotherpath/  ?

**Comment by UnamSanctam** [comment]
No that should be fine, but try adding a new configuration inside the "Configurations" tab to see if your database is writeable.

**Comment by MeowScripts** [comment]
Configuration successfully added. Also I chmod 777 the entire unam directory before hand. Could it be the line in endpoint.php pointing to localhost instead of my server IP? 

$hostaddress = $_SERVER["REMOTE_ADDR"] ?? '127.0.0.1';

**Comment by UnamSanctam** [comment]
No that's just a safeguard for if your PHP isn't returning an IP for the request. And if you reload the configuration is it there in the list? Are you able to reach the http://ipaddress/unam/api/endpoint.php page from your browser?

**Comment by UnamSanctam** [comment]
If your configuration isn't being added to the list then most likely the database isn't writeable, please check the permissions of both the `db` folder and also the `unamwebpanel.db` file inside it. And also of course the `unam` directory itself.

**Comment by MeowScripts** [comment]
Ah, you know what... my permission changes from earlier weren't acknowledged because I hadn't restarted the apache2 service. lol Thanks again! Workers show now, configs work. Cheers.
