### ISSUE TITLE
Problem with the new version

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1921]
Hello Unam. Thanks for releasing the new version and for your work. I have the following problem. After starting the miner, it does everything and creates itself in the folder ProgramData creates a service - I restart the computer but the miner does not start. I find his service and start it manually and I get an error - The service "Service Name" could not be started on the local computer. Error 1053: The service did not respond to the request in a timely manner. What could be the reason?

**Comment by UnamSanctam** [comment]
That's how it's supposed to be since the miner isn't a real service program (the miner itself should still start), though it's strange that it doesn't start for you. When you start it manually it should still start the miner program, if you check the service properties does it point correctly towards where the miner is installed?

**Comment by masterjek** [comment]
I already found the reason, although it is a little strange. My miner does not start if injection into is selected conhost.exe

**Comment by UnamSanctam** [comment]
Hmm, maybe there's something weird with that conhost then, though normally it should always be fine since conhost is such a necessary program. It could possibly be some protection on it but I didn't experience that in any of my test VMs, I'll have to see if anyone else reports that.

**Comment by masterjek** [comment]
I'm testing on my main computer. And I also have a computer where 8 copies of Windows and different antiviruses are installed. So on the computer where there are 8 copies it runs, but on my main one it doesn’t.

I have another question: why now the finished file does not have a run as administrator icon? Although this option is enabled in the builder?
![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/eabfa87f-17f7-4de0-8cfd-ffb6d662478a)

**Comment by masterjek** [comment]
And also tell me if I want to remove the creation and unpacking of the file - WinRing0x64.sys - How to do it? I tried to remove this file before, but if I simply remove it from the app, I get errors when building the project.

**Comment by UnamSanctam** [comment]
You just need to remove these two lines and it should remove that file:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/c61e842d5ec04e2493a83f54f096ba2f3b95687d/SilentCryptoMiner/Resources/Code/miner.cpp#L209
https://github.com/UnamSanctam/SilentCryptoMiner/blob/c61e842d5ec04e2493a83f54f096ba2f3b95687d/SilentCryptoMiner/Forms/Builder.cs#L293

**Comment by UnamSanctam** [comment]
Yes because if the program takes too long to start then SCM (the Service Manager) will kill it.

**Comment by masterjek** [comment]
Please tell us a question that is a little off topic. There are ways to easily protect a finished file by hash Md5 What if someone changes the EXE file, it becomes inoperable and gives an error upon startup?

**Comment by UnamSanctam** [comment]
Depends on how you change it, if you just add some empty bytes at the end of the file then it will work just fine. The miner did that during one minor version (added a byte when installing) but the problem was that since the MD5 was different when it installed then antiviruses like Avast started sandboxing it again after it installed and users could see that.

**Comment by masterjek** [comment]
This is what I meant, if I add various junk bytes to a file so that its size exceeds the size allowed for total virus scanning. And what if someone cut out these bytes and made a file of the size for uploading to a total virus, it became inoperable, it simply did not start.

**Comment by UnamSanctam** [comment]
The file will always work again after removing the junk bytes, except if the bytes were improperly removed.
