### ISSUE TITLE
i using rvn coin  so i pasted config detiles in Default Etherium Tab it's Correct or wrong ?

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1924]
i using rvn coin  so i pasted config detiles in Default Etherium Tab it's Correct or wrong ?

_Originally posted by @DARK-DEVIL-66 in https://github.com/UnamSanctam/SilentCryptoMiner/issues/1914#issuecomment-1807227337_

**Comment by UnamSanctam** [comment]
Yes that is correct, Ravencoin is mined using ethminer so "Default ethminer" is the correct configuration.
