### ISSUE TITLE
it;'s config correct or wrong

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1925]
{
    "url": "stratums://`0xbE23529837A2D706D5be0eE51f558Cb63B3f168E`.{COMPUTERNAME}@etc.2miners.com:11010",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 5,
    "idle-gpu": 90,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}

**Comment by UnamSanctam** [comment]
That is correct.

**Comment by DARK-DEVIL-66** [comment]
"url": "'stratums://0xbE23529837A2D706D5be0eE51f558Cb63B3f168E'.{COMPUTERNAME}@etc.2miners.com:11010",

your builder json section showen like this

**Comment by DARK-DEVIL-66** [comment]
> "url": "'stratums://0xbE23529837A2D706D5be0eE51f558Cb63B3f168E'.{COMPUTERNAME}@etc.2miners.com:11010",
> 
> your builder json section showen like this

i simply copy json section config and past it to webconfig and remote config i am rigth ?

**Comment by DARK-DEVIL-66** [comment]
extra comma showing before and after wallet address it's Rigth ?

**Comment by UnamSanctam** [comment]
Yes that's right but it's not a comma, it's this sign \` and everything inside of it gets encoded but you can simply remove that normally if you want.
