### ISSUE TITLE
pssword is necessry or optional for 2miners.com etc pool

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1927]
i never input password x for etc miner build time it's lead error?

**Comment by DARK-DEVIL-66** [comment]
and it's rigth or wrong https://rentry.co/599nb/raw

**Comment by UnamSanctam** [comment]
The password is not required, and the miner will insert and x automatically as the password if the password is empty. That Rentry configuration looks correct and should work.
