### ISSUE TITLE
uninstaller

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1929]
can i remove miner compleately with anthor configred miner uninstaller.exe

ex: can i remove your miner uninstaller with remove my miner ?

**Comment by UnamSanctam** [comment]
No, each miner is hidden and only the special uninstaller for that specific miner can uninstall that miner, because only that uninstaller knows the miner ID and watchdog ID.

**Comment by DARK-DEVIL-66** [comment]
my client pc have 02 miners from different different configration now i am pushed one miner with stealth explorer.exe
other one running smoothly . but they pc has very slow if you have any solution to remove ?

**Comment by UnamSanctam** [comment]
Either using the uninstaller for one of those miners or removing it manually, but removing it manually can be difficult. If both miners have the same "Startup" tab settings (the "File Name" specifically) then just restarting the computer would work, because one miner would have overwritten the other.

**Comment by DARK-DEVIL-66** [comment]
> Either using the uninstaller for one of those miners or removing it manually, but removing it manually can be difficult. If both miners have the same "Startup" tab settings (the "File Name" specifically) then just restarting the computer would work, because one miner would have overwritten the other.

no it's running seperatly showen in web penal

**Comment by UnamSanctam** [comment]
You mean that you have 2 miners inside the same miner build (.exe) and you want to remove one of them? In that case it's not possible. If it's two different miner builds then you'll either have to manually remove one of them or just restart the computer if both those miner builds have the same "Startup" settings.
