### ISSUE TITLE
Issue with miner working

### ISSUE THREAD

**Issue by haxful** [UnamSanctam/SilentCryptoMiner#193]
Hello, I have made my monero miner and when I've been trying to test them either on myself or another computer it doesn't work at all I have taken stealth and idle mining off to see if that's why but even after I wait and watch nothing happens I will attach my config to see if that could help but I'm at a dead end with what to try
[Monero.txt](https://github.com/UnamSanctam/SilentCryptoMiner/files/7787287/Monero.txt)

**Comment by UnamSanctam** [comment]
SupportXMR requires a password as the worker name.

**Comment by haxful** [comment]
So i just add a random password and it should run fine?

**Comment by UnamSanctam** [comment]
Yes, they require a worker name entered in the password field or they will deny the connection.

**Comment by haxful** [comment]
Perfect, I'll try now thank you.

**Comment by haxful** [comment]
It seems to be fixed thanks, one more quick question what is your recommended max CPU usage for making miners last longer while making a decent amount

**Comment by UnamSanctam** [comment]
Usually 20%-40% Max CPU and 80% Idle CPU is the standard. Usually 20% never really gets detected by the user.

**Comment by haxful** [comment]
Perfect, thank you once again. Have a nice day!
