### ISSUE TITLE
Inject into

### ISSUE THREAD

**Issue by paraskovyarudnoia19983911** [UnamSanctam/SilentCryptoMiner#1939]
what's better conhost.exe or explorer.exe.
I just downloaded Builder, it’s there default explorer.exe, but _Changed default "Inject Into" program to conhost.exe instead of explorer.exe due to explorer.exe now triggering detections when running under System_

**Comment by UnamSanctam** [comment]
For me conhost.exe was better but for another person they got specific heuristic detection when using conhost.exe so I temporarily changed the default back to explorer.exe just to be safe. I really don't know which one is the best, on my virtual machines conhost.exe is giving less detections but it seems like conhost.exe might possibly give some more serious heuristic detections for others. The detections I got from using explorer.exe weren't as serious (they could be bypassed with "Add Defender Exclusions") while the reported heuristic detections can't. https://github.com/UnamSanctam/SilentCryptoMiner/issues/1935.
