### ISSUE TITLE
new feature we waiting for, for simplicity

### ISSUE THREAD

**Issue by zanatechnology** [UnamSanctam/SilentCryptoMiner#194]
i hope you add a new features to the next release that we can extract a copy of what we built in JSON model so if we wanted to change a miner settings we do it simply :)
thank you for reading my idea :)

**Comment by UnamSanctam** [comment]
Well you can already get the settings in the "Main" tab by pressing "Save" and then load it by using "Load", but if you mean getting the settings for things like "Remote Configuration" then yes there will be a JSON exporter for the "Remote Configuration" settings in the next version.

**Comment by zanatechnology** [comment]
good thnx am waitting the update by full patience
