### ISSUE TITLE
Question about the new miner

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#1940]
Hello Unam. The previous version of the miner simply started after rebooting the computer and that’s it. The new version starts after a restart, but some antiviruses show a window that the program is trying to start; the file name and the full path to it are indicated. Could the reason be that the file does not have the run as administrator sign that was in the previous version?

**Comment by UnamSanctam** [comment]
No that won't change anything, maybe the difference is that the new one is a service and the old one was a Task? Do you have a screenshot of that window?

**Comment by masterjek** [comment]
I didn't take a screenshot of the window because it only appears after the first reboot of the computer. But I remember what it says there, a potentially dangerous program has been detected, we will check it and additionally send it to our laboratory for analysis, if the program is safe it will run. And after about a minute the miner starts. Although this window is shown once, the user can fully see where the miner is located.

**Comment by UnamSanctam** [comment]
Does your crypter (if you use one for that test) change the MD5 (any bytes) of the miner after install? That's the thing I mentioned in an email previously, normally antiviruses save the MD5 the first time they scan (sandbox) it (before installation) and thus shouldn't scan (sandbox) them again after reboot.

**Comment by masterjek** [comment]
I didn't quite understand the question. After the ransomware, the miner has another md5. And it starts with this hash, after a reboot, it’s just that the old version did this without warnings from the antivirus even on the first launch, and the new version does this with a warning on the first launch.

**Comment by masterjek** [comment]
And as I understand it, this is due to the fact that the miner is launched as a service.

**Comment by UnamSanctam** [comment]
Hmm weird, the old one should technically also do that. That was one of the reasons I didn't implement any feature like that, because in my tests they were getting sandboxed again after install.

>And as I understand it, this is due to the fact that the miner is launched as a service.

Yes probably, but in this case it actually shouldn't matter. Or do you have "Run after install" disabled?

**Comment by masterjek** [comment]
I will now try to launch the new miner not as a service, but from the scheduler. I will change the hash for him again so that the antivirus will consider it as a new file and tell him whether a warning window will appear or not.

**Comment by masterjek** [comment]
I checked that I also receive a notification from the antivirus from the scheduler. To check, I also took the old version of the miner, and re-encrypted it, that there was a different hash, and from it I did not receive any warnings from the antivirus. I think the lack of a Manifest file on the new miner is to blame. I also want to experiment, is it difficult for a new miner to revert back the creation of a Manifest file with the sign to run as administrator?

**Comment by UnamSanctam** [comment]
If you replace the Resources/Compilers/resource.rcf file with this one [resource.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/13378106/resource.zip) (it's inside the .zip) then it should add a manifest. But theoretically a manifest file should never cause that unless it's your crypter that's doing something which causes it.

**Comment by masterjek** [comment]
Thanks a lot. When I reverted the manifest file back, everything now starts silently and without additional windows or warnings.

**Comment by masterjek** [comment]
Unam I want to know for myself whether I can run previous versions of the miner using the service? Is there anything you need to change in the code? I create the service with another program if anything.

**Comment by UnamSanctam** [comment]
That should work fine, any version should work as a service.

**Comment by masterjek** [comment]
I forgot to ask. I can use Xmrig from the new version in previous versions?

**Comment by UnamSanctam** [comment]
Yes that is fine, everything with it should be backwards compatible (mainly because there are other miner builders which use my xmrig and ethminer and I want to make it easy to use).
