### ISSUE TITLE
Unable to mining 

### ISSUE THREAD

**Issue by Mateusz779** [UnamSanctam/SilentCryptoMiner#1942]
Emprt miners list in checker, same when open api

![Bez nazwy](https://github.com/UnamSanctam/SilentCryptoMiner/assets/73058906/2bf18253-4b71-4332-a31a-969df0651a82)
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/73058906/6a3463c2-f079-4b25-ad5b-4443488f0094)
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/73058906/822af89b-7f4c-4c94-bbcc-96083b315610)

**Comment by UnamSanctam** [comment]
Hmm interesting, it shouldn't be an injection issue since the watchdog is running, can you try rebuilding the miner and see if it works? If that still doesn't work then please try changing the "Inject Into" to `conhost.exe`. If that still doesn't work try changing the pool and see if that works.

**Comment by Mateusz779** [comment]
Nope. I changed to `connhost.exe `and change pool to nanopool and same issue, yes i disabled remote config with old data

**Comment by UnamSanctam** [comment]
Hmm that's really strange, the ETC miner should of course not start (since you don't have a GPU) but the XMR miner should. What happens if you use the pre-built release of the builder: https://github.com/UnamSanctam/SilentCryptoMiner/releases?

**Comment by Mateusz779** [comment]
Prebuild works. I know ETC miner cannot start. But i used self moded xmrig whitch working when i started it from parametrs .

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/73058906/3e03b520-a008-42b0-88a0-c80e3f054f4f)

**Comment by UnamSanctam** [comment]
It works by reading the PEB ShellInfo or did you change the injector to pass it through the command line? Does it correctly set the Mutex that the miner passes to the xmrig? The checker and uninstaller (and watchdog) uses the Mutex to check if it's running. The reason why it's not showing up is most likely that.

**Comment by Mateusz779** [comment]
Previous photo is screenshot of working my xmrig who starts from exe with paramets without builder

**Comment by UnamSanctam** [comment]
By default the miner injector starts the miner by passing a miner ID (which is used for the Mutex) and also an encrypted string of the command line parameters:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/c61e842d5ec04e2493a83f54f096ba2f3b95687d/SilentCryptoMiner/Forms/Builder.cs#L218
So you will need to modify your xmrig to get the miner ID from the passed command line and then create a Global mutex using CreateMutexW with the passed miner ID. You will also need to decrypt the passed command line arguments inside your xmrig or remove the encryption inside the builder.

**Comment by Mateusz779** [comment]
Okay, I understand, for now I will stick to this ready-made xmrig when I have more time I may play with it, thanks a lot
