### ISSUE TITLE
miner starts - cpu usage goes up to 80% but after 1h it still didnt mine nothing

### ISSUE THREAD

**Issue by bartoszx1312** [UnamSanctam/SilentCryptoMiner#1945]
exactly as in title, i have the miner on about 4-5 computers but it doesnt mine the XMR, any idea?

**Comment by UnamSanctam** [comment]
Can you run the checker and post a screenshot?

**Comment by bartoszx1312** [comment]
> Can you run the checker and post a screenshot?

![Uploading obraz_2023-11-18_114700943.png…]()

**Comment by bartoszx1312** [comment]
> Can you run the checker and post a screenshot?

![obraz_2023-11-18_114712042](https://github.com/UnamSanctam/SilentCryptoMiner/assets/146990062/34735032-0978-4e47-8599-9f89503e59c9)
