### ISSUE TITLE
Rootkit bug

### ISSUE THREAD

**Issue by Nobellium1** [UnamSanctam/SilentCryptoMiner#195]
There's a problem with rootkit. Everytime you use it and launch miner once, it will not start, ever. 
You need to launch miner for 2nd time and it'll work with the rootkit. I also disabled watchdog while using rootkit but it seems that didn't help.

**Comment by UnamSanctam** [comment]
Hmm, haven't heard this one before, a lot of things (on the rootkit side) will be different in the next version so most likely that will be fixed as well.

**Comment by Nobellium1** [comment]
When is the next version gonna be published?

**Comment by UnamSanctam** [comment]
New version has been released now.
