### ISSUE TITLE
if you delete a miner then the miner id does not get updated ( unam web panel )

### ISSUE THREAD

**Issue by Mustwey** [UnamSanctam/SilentCryptoMiner#1952]
i deleted a miner, then added it back and its miner id was 2 even though it was the only miner i had, how can i reset?

**Comment by UnamSanctam** [comment]
That's how databases work, since otherwise there would be inconsistencies in the data. Either open up the database and edit the table that keeps track of the auto-increment fields or replace your database file with a fresh one.

**Comment by Mustwey** [comment]
thanks
