### ISSUE TITLE
Uninstall questions

### ISSUE THREAD

**Issue by tempdatadoslocs** [UnamSanctam/SilentCryptoMiner#1955]
If someone who has no idea that this github repo exists, and they just so happened to install a program made from the repo would there be any chance of an uninstall, and if so what measures would they have to go through to uninstall the program? Could they just factory reset or would they have to use the regedit?

**Comment by UnamSanctam** [comment]
Usually a factory reset or downloading some more advanced antivirus is the only ways of removing it. You can remove it manually but if the watchdog is running then it's quite difficult.

**Comment by tempdatadoslocs** [comment]
thank you, I also wanted to know if there's a way to tell if a computer is just offline, or if they have uninstalled it from their computer.

**Comment by UnamSanctam** [comment]
Not really, since when the computer is offline then it's usually powered off, at which point  it would look the same as if it was uninstalled.

**Comment by tempdatadoslocs** [comment]
alright thank you,

**Comment by tempdatadoslocs** [comment]
alright thank you,
