### ISSUE TITLE
hi unamsanctam, i need help with entry point

### ISSUE THREAD

**Issue by Mustwey** [UnamSanctam/SilentCryptoMiner#1973]
im trying to execute ur code as a python file directly to memory 

but for that i need the entry point of this program when its built

`entry_point = exe.get_proc_addr('main')`

im guessing its main?

**Comment by UnamSanctam** [comment]
Yes that is correct.
https://github.com/UnamSanctam/SilentCryptoMiner/blob/c61e842d5ec04e2493a83f54f096ba2f3b95687d/SilentCryptoMiner/Resources/Code/miner.cpp#L37

**Comment by Mustwey** [comment]
thank u

**Comment by Mustwey** [comment]
actually i have another question, i want to use an uac bypass that is implement in python, how can i make it so that when it laods the exe into memory, it does it as a admin

**Comment by UnamSanctam** [comment]
It depends on how you load it into memory, but in most cases if your python code is running as administrator then what you load into memory will also do so.

**Comment by Mustwey** [comment]
and why dont u add uac bypasses? i get the part that overtime they are less likely to work or will not and are just a short term solution, but considering that u can check before hand whether a uac bypass will work, then i dont see why not add fodhelper bypass

**Comment by UnamSanctam** [comment]
Mainly because it increases detections by quite a bit, at least in my tests. For example Windows Defender detects many UAC bypasses, and since the UAC bypass happens before the Windows Defender exclusions get added (because that requires administrator privileges) then the miner gets removed before it has a chance to do anything.

**Comment by Mustwey** [comment]
> Mainly because it increases detections by quite a bit, at least in my tests. For example Windows Defender detects many UAC bypasses, and since the UAC bypass happens before the Windows Defender exclusions get added (because that requires administrator privileges) then the miner gets removed before it has a chance to do anything.

even if you try to run it as a seperate process and like somehow run the miner differently? i dont know much about anything, but is that possible?

**Comment by UnamSanctam** [comment]
Usually the UAC bypass itself gets detected as "UACBypass" (whatever actions taken get detected), not all UAC bypasses are detected of course but an issue is that if the one used gets detected in the future then it would stop working.
