### ISSUE TITLE
why not running in windows 11

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1980]
miner is not running in windows 11

**Comment by UnamSanctam** [comment]
It should work fine, I do most of my testing on Windows 11. Try building a new build and see if there is something wrong with your specific build.

**Comment by DARK-DEVIL-66** [comment]
i am using 3.1.1 builder 3.4.0 is have some bugs (hashrate are 0 always)

**Comment by DARK-DEVIL-66** [comment]
ok bro ill try to build new vertion

**Comment by DARK-DEVIL-66** [comment]
it's working but hidden from webpenal
it's showing in 2miners.com dashboard

**Comment by UnamSanctam** [comment]
Is the web panel URL correct?
