### ISSUE TITLE
Feature Question

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#1981]
Feature in mind: 
- Changed administrator "Startup" installation procedure from using the Task Scheduler to instead install as a Service

I remember me asking you that is using a service better than task scheduler for startup and you said no cause it's more monitored or something. What changed (cause you now implemented it)?

**Comment by UnamSanctam** [comment]
Because I changed many things in the miner code which now made it viable to use a Windows Service instead of a Task.

**Comment by UnamSanctam** [comment]
You can see all the changes here: https://github.com/UnamSanctam/SilentCryptoMiner/commit/c61e842d5ec04e2493a83f54f096ba2f3b95687d. I changed most of the code.
