### ISSUE TITLE
No worker name but mining

### ISSUE THREAD

**Issue by Nobellium1** [UnamSanctam/SilentCryptoMiner#199]
I am mining on my PC and I called myself in Worker name Aorus2
On nanopool I can see that I'm mining but there are no active/inactive workers at all, everybody is just invisible. I believe I did it wrong on rentry so what format should I use?
![image](https://user-images.githubusercontent.com/96837088/147712305-b530903d-3d06-45de-9c66-477006d532ff.png)

**Comment by UnamSanctam** [comment]
Nanopools ETC pool is bugged (on their side, only for worker names) and has been for quite some time, so if you want a worker name I would recommend some other pool like ethermine, 2miner or any other.
