### ISSUE TITLE
web penal showing miner offline but miner appear in pool dashboa\rd

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#1994]
i am using vps hosting for webpenal prevoiusly work wel but nowaday some miners are showing offline 1day ago in web penal but the miner will appear in pooldashboard

**Comment by DARK-DEVIL-66** [comment]
but they do it sucessfullly how is that possible ?

https://xmr.2miners.com/account/45Z1MDx9yFwFicj8j2aPmd7rmqAgTeiNuK8RiCcgfaZge7cHFMoe4iGcPFX11AdPHa8arnq4mRGjBYjQhaBd2hcKSKk8F8i#farms

**Comment by UnamSanctam** [comment]
They might not be able to connect to it for some reason, or is the VPS somehow maxing in CPU or RAM or something?

**Comment by DARK-DEVIL-66** [comment]
no i think it's have some bug i mean hashrate are shwing 0 in web penal 
but sometime miners are appear in pool dashboard 1kh/s or 2kh/s

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/a4b90ea3-0507-4e77-a6a3-74dc8a4f851a)

**Comment by DARK-DEVIL-66** [comment]
can i use miners withour assign in web penal only using remote config ?

**Comment by UnamSanctam** [comment]
The auto-refresh is the same as if you were to just refresh the page manually, it's only a client-side script that runs. It can never have any impact on the web panel. You can use miners without a web panel just fine, it's just an option feature.

**Comment by DARK-DEVIL-66** [comment]
https://xmr.2miners.com/account/45Z1MDx9yFwFicj8j2aPmd7rmqAgTeiNuK8RiCcgfaZge7cHFMoe4iGcPFX11AdPHa8arnq4mRGjBYjQhaBd2hcKSKk8F8i#farms


they use web penal

**Comment by UnamSanctam** [comment]
Possibly yes, we can't really know but they do indeed use my miner.

**Comment by UnamSanctam** [comment]
>but without using web penal when user click duble time our miner will run 02 seperate miners in their pc so we need to puse one miner ?

If it's the same miner build then it doesn't matter how many times they run it, it will only start one miner.

**Comment by UnamSanctam** [comment]
That is in all versions, so no matter how many times a user runs the miner build only one miner will start.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/956e311e-51cf-424b-b14b-dd7cc89fa70b)


![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/94b861e3-012c-4d81-ac3a-bcb98d5cf5f3)


why logng time diff
why hashrate diff(i think is gentrallly happen but share submiting time)

**Comment by DARK-DEVIL-66** [comment]
offtopic:-

you can add rootkit options in your binder ?

**Comment by DARK-DEVIL-66** [comment]
> > why logng time diff
> > why hashrate diff(i think is gentrallly happen but share submiting time)
> 
> Yes pools calculate the hashrate based on the amount of shares submitted over some interval, since 2miners have such a high share difficult now then their statistics won't be too accurate.
> 
> > you can add rootkit options in your binder ?
> 
> That wouldn't really make too much sense, since it wouldn't hide the bound files.

but it's will hide before added Diler in payload name i am rigth ?
so service64 drop to startup and binding time change file name to Dailerpayload.exe

**Comment by DARK-DEVIL-66** [comment]
i want to know onethink ex:
i run service64.exe in my pc it will have auto startup futrue ?
payload will hidden in startup folder so how is running at the restart time 
i mean payload are hidden and how is task sheduler are execute the exe

**Comment by DARK-DEVIL-66** [comment]
do you know any telegram based windows rat/botnet for spreding miners ?
i mean controll windows from telegram without server ?

**Comment by UnamSanctam** [comment]
>but it's will hide before added Diler in payload name i am rigth ?
so service64 drop to startup and binding time change file name to Dailerpayload.exe

Yes but that won't do much since the bound files will still be dropped normally.

>i want to know onethink ex:
i run service64.exe in my pc it will have auto startup futrue ?
payload will hidden in startup folder so how is running at the restart time
i mean payload are hidden and how is task sheduler are execute the exe

No Service64.exe does not install automatically, that's why the miner injects it on every startup. Because for the miner it's much better for it to be done that way. The r77-rootkit does have an install feature though the miner does not use that since it's usually detected.

>do you know any telegram based windows rat/botnet for spreding miners ?
i mean controll windows from telegram without server ?

Not that I know of no.

**Comment by DARK-DEVIL-66** [comment]
whats your spreding method 
whare you spreding it's help for me 
you are the boss!

**Comment by UnamSanctam** [comment]
I'm mainly only on the development side, but spreading through real or fake program cracks and game cheats/hacks wherever there's a demand for them is still one of the most popular methods.

**Comment by DARK-DEVIL-66** [comment]
do you know dummy or fake antivirus proggrame it's easy for binding
users are upset uninstalling ther av 
we have fake av it's help to full fill ther maind.

**Comment by UnamSanctam** [comment]
Not that I know of, there are probably some on GitHub but generally you'd have to build something like that on your own.
