### ISSUE TITLE
What to use to crypt miner?

### ISSUE THREAD

**Issue by Miner-User** [UnamSanctam/SilentCryptoMiner#1995]
I'm not very experienced in the field of file crypt, but I don't want to resort to someone else's services. Recently I came across an archive with 28 programs for this. Could you please advise which of these should I use and in what order? I will also be very glad if you tell me what settings to use.

- ASPack_v2.42
- ASProtect.SKE.v2.51.build.09.22.beta-RES-incl-kg
- Code.Virtualizer.v1.3.8.0
- Code_Virtualizer_x32_x64_v2.2.2.0_Retail_Licensed
- Code_Virtualizer_x32_x64_v3.1.4.0_Retail_Licensed
- Obsidium v1.3.6.4_Full_License
- Obsidium_v1.5.2_Build_11
- Obsidium_v1.6.7_Build_1_Retail_Licensed
- Obsidium_v1.6.9_Build_1_Company_License_with_NetworkLicensing
- PECompact_v3.02.2_Final
- The_Enigma_Protector_v6.70_x32
- The_Enigma_Protector_v6.80_x64
- Themida_x32_x64_v2.4.6.30_Retail_Licensed
- Themida_x32_x64_v3.0.4.0_Repacked
- Themida_x32_x64_v3.1.4.18_Retail_Licensed
- UPX_v4.2.1_x32
- UPX_v4.2.1_x64
- Virtualizer_v2.0.8.0
- VMProtect.Ultimate.V2.12.3.RETAIL.BY-1ST
- VMProtect_Professional_v2.13.8
- VMProtect_Ultimate_v3.0.9_Build_695_WebLM_v2.4.2.21
- VMProtect_Ultimate_v3.4.0_x32_x64_Build_1155_Retail_Licensed
- VMProtect_Ultimate_v3.5.0_x32_Build_1213_Retail_Licensed
- VMProtect_Ultimate_v3.6.0_Build_1406_Retail_Licensed
- WinLicense_x32_x64_v2.4.6.30_Retail_Licensed
- WinLicense_x32_x64_v3.1.2.0_Retail_Licensed
- WinLicense_x32_x64_v3.1.3.0_Retail_Licensed
- ZProtect.1.4.9.0.Preview.2.RETAIL.INCL_KEYGEN-FFF

**Comment by Miner-User** [comment]
I would also like to ask about obfuscation. As far as I understand, this function is already built into the builder, but I’m wondering whether it makes sense to use third-party obfuscators and how to do it. I know that in some versions of such builders there is a pause for obfuscation, but I didn’t find it here.

**Comment by UnamSanctam** [comment]
You would have to test each one in the list anyways to see how detected the versions you have are. As long as it supports 64-bit native programs it will work. For settings you can base them upon the example settings: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings

>I would also like to ask about obfuscation. As far as I understand, this function is already built into the builder, but I’m wondering whether it makes sense to use third-party obfuscators and how to do it. I know that in some versions of such builders there is a pause for obfuscation, but I didn’t find it here.

The "Pause for Obfuscation" option was there when the miner was built in C#, it's now (since version 3.0.0) built in C++ which is why you'd use a crypter or protector instead of an obfuscator (these are just the general terms used).

**Comment by Miner-User** [comment]
Thanks for the answer
