### ISSUE TITLE
DON'T TEST IT WITH VIRUSTOTAL

### ISSUE THREAD

**Issue by ssk666** [UnamSanctam/SilentCryptoMiner#2]
USE THESE
https://avcheck.net/
https://kleenscan.com/

**Comment by NoMeansNowastaken** [comment]
yes please dont use virustotal

**Comment by emuChitE** [comment]
> 
> 
> USE THESE https://avcheck.net/ https://kleenscan.com/

Explain why you should not use virustotal?

**Comment by UnamSanctam** [comment]
It distributes your program and all the code to all antivirus companies, meaning the detections for all builds will gradually increase the more submissions there are.
