### ISSUE TITLE
Zergpool

### ISSUE THREAD

**Issue by GkyEla** [UnamSanctam/SilentCryptoMiner#2004]
Hello Unam, Isetted up kawpow zergpool with a payment method to my xmr adress. My miners are working for 2 days with compataible gpus and even now idont see the miners in zergpool wallet section. How can i solve this problem .

Also i asked this before but iwant to be sure sorry Unam
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/60583610/a97a520d-4b30-4bba-9f6c-08b7f2d71beb)
how should ifill this or should i change pool? maybe swap pools with xmr payout is not working or problem is on my side 
-a kawpow -o stratum+tcp://kawpow.eu.mine.zergpool.com:3638 -u 45HdRNnPbSZJHH4zL3bdTX5qTFd9Aco9XX24EBeKFzdWbRjuEcXoegCMGc4dDwAeiBZsMXyapbciSMGZzRzPkooF7YPa8W --timeout 120 -p c=XMR

**Comment by GkyEla** [comment]
![Screenshot 2023-12-06 194800](https://github.com/UnamSanctam/SilentCryptoMiner/assets/60583610/48797e85-b363-4fc0-8577-b5c373cbb888)
also ihave a computer with 1660 and 1070 but no a movement in zergpool

**Comment by GkyEla** [comment]
![Screenshot 2023-12-06 194800](https://github.com/UnamSanctam/SilentCryptoMiner/assets/60583610/78227ca4-4cc3-4ffc-8a8a-c5d7ee617573)
also ihave a computer with 1660 and 1070 but no a movement in zergpool

**Comment by GkyEla** [comment]
Also, can you tell me a different option for multi-algo pools for gpu Kawpow,  cpu  Monero, and Zephyr?
Thanks for everything, Unam

**Comment by GkyEla** [comment]
yes iwant a zergpool alternative and want to cashout in xmr thanks for everything,

**Comment by UnamSanctam** [comment]
There is MoneroOcean if you want to try that.

**Comment by GkyEla** [comment]
ichecked it and moneroocean is very cool. can it mine kawpow?

**Comment by UnamSanctam** [comment]
Yes it can mine the KawPow coins CLORE, RVN and XNA so that should be fine. And yes MoneroOcean works with my miner.

**Comment by GkyEla** [comment]
okay thank you soo much also its the same setup with zergpool right?

**Comment by UnamSanctam** [comment]
Almost, it's similar.

For the KawPow miner:
Connection Scheme: `stratums`
Pool: `gulf.moneroocean.stream:443`
Wallet: `YourXMRWallet`
Password: `kawpow`

For the RandomX (Monero/Zephyr) miner:
Pool: `gulf.moneroocean.stream:443`
Wallet: `YourXMRWallet`
Password: `rx/0`

And also enable the "SSL/TLS" option.

**Comment by GkyEla** [comment]
Really really thank you so much you are the best! ilearnt alot from you

**Comment by UnamSanctam** [comment]
Yes CLORE requires 3.4GB, though MoneroOcean does mine Zephyr.
