### ISSUE TITLE
help

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2005]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/a3e9283b-bc99-4744-8222-f9564e43729f)

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/ce7fe66b-fc15-4e35-9a31-9ea18c041c65)

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/fa1a64d3-aad9-48cc-bbf4-021eb561ecef)

why shares appear some colores anything suspices ?

**Comment by DARK-DEVIL-66** [comment]
https://zephyr.herominers.com/#

**Comment by DARK-DEVIL-66** [comment]
they will ban me ?

**Comment by DARK-DEVIL-66** [comment]
why idle time never mining ?

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/03e634b6-1271-4dbe-82ce-fd8b693c2246)

pool are showing online but web penal are showing offline


![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/ef3f6615-89f1-467c-b0eb-c73514ba9921)

**Comment by UnamSanctam** [comment]
>why shares appear some colores anything suspices ?

The percentage is the amount of effort that has been put in, since mining is probability/luck based. 

>why idle time never mining ?

Make sure that both "Idle Wait" and "Idle CPU" is set to some values, the computer could also have something that causes it the mouse or keyboard to be moving.

>why idle time never mining ?

Either they cannot connect to your web panel or you haven't directed it to the URL with the "Remote Configuration" or what you use to set the web panel.

**Comment by DARK-DEVIL-66** [comment]
i am set up api endpoint url from remote config
but recently i changed xmr to zehpy coin and pool in web config

**Comment by DARK-DEVIL-66** [comment]
actually i builded xmr for miner after clients excute the miner i will change xmr to zhap coin config from web penal but i keep xmr config in remotte config it's the issue reason for 0h/s ?

**Comment by DARK-DEVIL-66** [comment]
but i switching web config same config(little chages change {computer name } to x now increseing hashrate 0 to 400)

**Comment by DARK-DEVIL-66** [comment]
how long after web penal show miners are offline ?

**Comment by UnamSanctam** [comment]
It shows after they haven't connected for 3 minutes. They can get a hashrate if there previously wasn't enough resources after which at the new pool connection there was enough.

**Comment by DARK-DEVIL-66** [comment]
actual problem is fallowing somes:
01.miner active in webpenal hashrate also 300 or 500h/s but pool say it's offline long time like 30 or 40 min some houres

02.always sitt hashrate 0h/s same issue in pool like 01

but i noticed one 

everytime starting my clients miner exe

it's say status stoped in web penal after some miniutes it's will changed to active it's happen recently 3.4.0

**Comment by UnamSanctam** [comment]
1. That's a problem with the pool, the web panel shows the real hashrate directly reported by the miner.
2. Usually due to not enough resources, mostly with 2 core CPUs or really low RAM.
Stopped is either due to the pool not responding or due to them not being able to contact your "Remote Configuration" or web panel, but the timeout is quite low so that should not be the case.

There are hundreds of thousands of miners running 3.4.0 without issue so that should not be the problem.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/eaafc204-64b4-4d6f-abf9-cadeb7b06965)


how many core have this cpu and how to find out that checking like 2.50 it's mean 2core i am correct ?

**Comment by DARK-DEVIL-66** [comment]
actually i have one sister she is 25 year old so i need to build our own home for her merrage 
so i try to fast up my mining process i belive it's help to make money faster 


do you know any legit exe install seller or any method?

**Comment by DARK-DEVIL-66** [comment]
i tryed to many method like binding with crack and games many more everyting very hard with someone IQ so i planned to resovle the issue buying exe installs

**Comment by UnamSanctam** [comment]
Not really, most install sellers don't sell any good installs, because if they were good they wouldn't be selling it. And instead would just be mining on them or something similar.

**Comment by DARK-DEVIL-66** [comment]
do you know any paid methods to spreding our country cafe have low end cpus like xenon / pentium so it's not use full  ?>



actually i executed in one cafe pc after execute appeared blue  screen restart i know it's happen low configration

**Comment by UnamSanctam** [comment]
Paid methods usually aren't any better than the methods one can think up on their own. How many miners are you aiming for? Since it seems what you're aiming for might be quite costly.

**Comment by DARK-DEVIL-66** [comment]
i airm 1000 miners enough for lifetime

**Comment by DARK-DEVIL-66** [comment]
waaa my  miner hashrate are going 2kh/s to 6kh/s how is possible bro i canoont imagin that ?
very very thank's bro every credit own you !

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/8fc04849-edaa-4625-8ccc-d55c96f035db)

**Comment by UnamSanctam** [comment]
In the web panel or the pool? If in the web panel then either it switched from Idle mining to normal mining, or it's possible that the computer started doing something that requires more of the CPU. If it's in the pool then the pool calculates the hashrate based on the amount of shares that have been submitted over some interval, this means that to see the accurate hashrate on the pool you have to check the hashrate as the average over some time, like 1 hour or 6 hours.

**Comment by DARK-DEVIL-66** [comment]
one houre 
3.68 kH/s

**Comment by DARK-DEVIL-66** [comment]
i fixed try to spred 17 11 gen cpu  bro

**Comment by DARK-DEVIL-66** [comment]
who will use the most of case like this cpu photoshop editor & gamers i am correct ?

**Comment by UnamSanctam** [comment]
Yes things like that. 3.68 kH/s for that CPU is pretty good (I assume you're not mining at 100%), at 100% CPU (with the proper tuning and RAM types) an Intel® Core™ i7-11700 @ 2.50GHz will hash at 6.78 kH/s.

**Comment by DARK-DEVIL-66** [comment]
actually i neverenter to web or pool just 2 houres now i checked how much hashrate are generating my miners suddenly it's increase afterward i checked in webpenal it's showing onehoure hashrate  3.68 kH/s i think idle minig is work sometime yasterday i checked same miner at idel hashrate are 800h/s how is possible today ?

**Comment by UnamSanctam** [comment]
I'm not fully sure what you're asking, but some computers might have things running which lower the hashrate (because other things are using the CPU).

**Comment by DARK-DEVIL-66** [comment]
> Yes things like that. 3.68 kH/s for that CPU is pretty good (I assume you're not mining at 100%), at 100% CPU (with the proper tuning and RAM types) an Intel® Core™ i7-11700 @ 2.50GHz will hash at 6.78 kH/s.


sure bro i used max cpu 20%
idle cpu 80 %

**Comment by UnamSanctam** [comment]
Alright then that should be pretty good numbers.

**Comment by DARK-DEVIL-66** [comment]
blaaaa today happen magig me bro wonderfull


pls tell me how much hashrate are generating in 
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/3eadbe44-e35c-40b3-88b7-f784423b3ee6)

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/6dc8c5c8-50f9-4cad-a259-39a51e384478)


previusly it's mining hasrate are 800 or 500

**Comment by UnamSanctam** [comment]
>previusly it's mining hasrate are 800 or 500

You can find many RandomX benchmarks here: https://xmrig.com/benchmark (those are at 100% with optimal tuning and RAM). That CPU at 100% should only have 673 H/s, but it might have been very lucky and found a lot of shares.

**Comment by DARK-DEVIL-66** [comment]
do you know bro i never sleeped long 07 days reasarching silent miners 

i sucsessfully readed your all github closed and opened issue s so today i am going to sleep with happy -mining bye bro thank's agin ---------------------keep it up!
