### ISSUE TITLE
laptop freezing MINING XMR

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2010]
Hii bro i testing my client pc everytime freeezing laptop mining xmr \i know the issue is consume more resource for xmr mining now i am switched to zhpey coin but the issue same issue in  some laptops
how can i prevent that issue ?

but the remote config still xmr config

**Comment by UnamSanctam** [comment]
Zephyr and Monero use the same algorithm (RandomX) so that won't change anything, do you have the CPU set to 20%? And are you sure you're only running one miner?

**Comment by UnamSanctam** [comment]
GhostRider and most of the variations of CryptoNight don't use as much resources.

**Comment by DARK-DEVIL-66** [comment]
> GhostRider and most of the variations of CryptoNight don't use as much resources.


i know you early suggest ghost rider algo for someone and i confiused how is work and more?

i already readed your coin switching closed issue in your project

**Comment by UnamSanctam** [comment]
It's possible to mine GhostRider using coin-switching if you want that, or you can just mine a GhostRider coin (like how you're currently mining a RandomX coin). If you want to mine it using coin-switching then you would use something like Zergpool, here's some example settings that I think will work:
```
{
	"algo": "gr",
	"pool": "ghostrider.mine.zergpool.com",
	"port": 15354,
	"wallet": "YourXMRWallet",
	"password": "c=XMR",
	"ssltls": true
}
```

**Comment by DARK-DEVIL-66** [comment]
Zergpool is have fixed share diff

**Comment by UnamSanctam** [comment]
Yes most coin-switching pools do, since coin-switching itself is quite complicated. You can read about difficulty configurations on the front page under "Mining Difficulty Configuration".

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/475a24ee-51a9-4d5f-af0a-dcbb80ee0346)

0.5h/s why this happen i think never issues on my side ?

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/e01f6074-7d08-4177-a03d-f57921547322)

i switched xmr and zhepy still same hashrate

**Comment by DARK-DEVIL-66** [comment]
i switched pools also still same 


have c letter in font of worker name so no issues in miner
remoteconfig work well
server side no limitation or firewall
i think victem side have fire wall enabled or any av i am correct or etc

**Comment by DARK-DEVIL-66** [comment]
> It's offline.

yes it's comming randomly online when it's comming online i tryed best of my side but still 0.5

anything was wrong in my side ?

**Comment by DARK-DEVIL-66** [comment]
when i switching coin or pool it's incresed to 0.5 and not enugh vram

**Comment by UnamSanctam** [comment]
If it's not able to connect to some pool then the pool might be blocked in some way on the user side.

>yes it's comming randomly online when it's comming online i tryed best of my side but still 0.5
anything was wrong in my side ?

No the issue would be on their side. It's a laptop so that's not unexpected.

>when i switching coin or pool it's incresed to 0.5 and not enugh vram

Yes it doesn't have enough VRAM (because it doesn't have a dedicated GPU) and it has 0 hashrate either because of not enough RAM or the laptop could be set to power saving or something similar.
