### ISSUE TITLE
help

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2013]
was wrong i tested xmrig comparized to silent miner (check why 0h/s)

xmrig.exe --donate-level 0 -o sg.zephyr.herominers.com:1123 -u ZEPHYR2s5bnTUHNSTKfG9Gc6eC88LFNpEcHjChP2HTi1Wt1pry5XXqBWrLeUUYzzurC22ySZHLwvRgmSAvNcDXsZKm3K9uKBVD33w=120000 -p {COMPUTERNAME} --tls -k -a rx/0 -B --background --cpu-max-threads-hint=20

**Comment by DARK-DEVIL-66** [comment]
and --cpu-max-threads-hint=20 is ignored it's use 100% cpu ?

**Comment by UnamSanctam** [comment]
On the same computer?

**Comment by DARK-DEVIL-66** [comment]
yes i i pused silent miner

**Comment by DARK-DEVIL-66** [comment]
i try to run xmrig for debug why always hashrate are 0

xmrig can get idea  ?

**Comment by DARK-DEVIL-66** [comment]
> was wrong i tested xmrig comparized to silent miner (check why 0h/s)
> 
> xmrig.exe --donate-level 0 -o sg.zephyr.herominers.com:1123 -u ZEPHYR2s5bnTUHNSTKfG9Gc6eC88LFNpEcHjChP2HTi1Wt1pry5XXqBWrLeUUYzzurC22ySZHLwvRgmSAvNcDXsZKm3K9uKBVD33w=120000 -p {COMPUTERNAME} --tls -k -a rx/0 -B --background --cpu-max-threads-hint=20



it's was wrong ?

**Comment by UnamSanctam** [comment]
Remove `-B --background` and see what the xmrig says while running.

**Comment by DARK-DEVIL-66** [comment]
ok i will try and why ignoring cpu usage 20

**Comment by DARK-DEVIL-66** [comment]
and i deleted SHA256SUMS file it's necessry ?

**Comment by UnamSanctam** [comment]
You can remove that, only the xmrig.exe file should be necessary.

**Comment by DARK-DEVIL-66** [comment]
it's working
silentminer 800h/s  cpumax=20,idle=80
xmrig 1.60kh/s  --cpu-max-threads-hint=20


but i want to know how long keep conected to pool ?

**Comment by UnamSanctam** [comment]
The miners should always be connected to the pool as long as they are mining, if they aren't connected then they can't mine (they can't have any hashrate).

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/f6745487-dfa7-4a33-bf89-be6737de3763)


but wwhy it not use self computer name

**Comment by UnamSanctam** [comment]
Do you have the xmrig console visible? You should be able to see what it says, and how high the share difficulty is.

**Comment by DARK-DEVIL-66** [comment]
i used background mode 
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/2e3d93dd-9251-4c8b-ad91-2bc9f2608f98)

**Comment by DARK-DEVIL-66** [comment]
actuually one thing happen pool to miner connection have long gap in our silent miners

actually i don't know why happen that 

compairezed to xmrig have differend gaps bro

**Comment by UnamSanctam** [comment]
If it has a hashrate then it also has a pool connection, the difference should be in the share difficulty somehow.

**Comment by DARK-DEVIL-66** [comment]
i think it's happen 

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/2e50b0ab-3dab-4756-82b9-e4c47df71298)


xmrig version

**Comment by UnamSanctam** [comment]
They are the same version (6.20.0), the version number just isn't changed. I check all the changes using WinMerge.
