### ISSUE TITLE
hashrate issue

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2018]
build time i used xmr 
remote config still remain xmr configs
recenly i switched xmr to zephyr

but

at the miners starting period stay hashrate are 0 long time (2Houres)
zephyr config 
but it's appeared 2miner dashboard 
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/70283faa-c5e0-4f55-976c-181da8c139e5)

after i switched to 2miner config it's incresing hashrate 0 to 2.2kh
xmr config

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/fc49914a-f561-4118-9a0c-18ac82fdcdc6)

again i switched 2miner xmr to zephyr config it's work normal actully whats happen i can't realise the issue anything falt in my side

**Comment by UnamSanctam** [comment]
I can't really help you much since I don't have a full understanding of your situation, Do you mean that the same happens for all your miners?

**Comment by DARK-DEVIL-66** [comment]
no  it's happen--->  11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz

do you remember ? 6.40 KH/s previously we Discussed About That ?

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/bbb02137-110f-4e64-88aa-dd8bfe69a768)


actual issue is

1st proarity given for remote config / build time config

it's require daily when come to online we need to switch manually again and again

**Comment by UnamSanctam** [comment]
The priority is as follows:
1) Web panel configuration
2) "Remote Configuration"
3) Builder configuration

**Comment by DARK-DEVIL-66** [comment]
but 3.4.0 have something issues 

i will show when next restarting peiriod web penal are showing assined zephy coin config but wallet address is sowing xmr(2miner)   miners are appear in 2miner dashboard 


any way miners work well it's big Helpfull !

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/728290f5-6d94-42c6-9c1f-4f7d574f3041)


most of miners say not enough vram

sso we can mine anthor coin low end gpu based ?

**Comment by UnamSanctam** [comment]
>but 3.4.0 have something issues
i will show when next restarting peiriod web penal are showing assined zephy coin config but wallet address is sowing xmr(2miner) miners are appear in 2miner dashboard
any way miners work well it's big Helpfull !

Could be that it wasn't able to connect to the Zephyr pool at that time, if it's not able to connect then it will move to the next pool configuration and test if that one works. After some time it will retry the pools again. So if the web panel configuration doesn't work (or doesn't exist) then it tries the "Remote Configuration", and if that one doesn't work (or doesn't exist) then it will try the builder configuration.

>most of miners say not enough vram
sso we can mine anthor coin low end gpu based ?

That computer doesn't actually have a dedicated GPU. What's shown in the GPU field is the integrated CPU graphics.
