### ISSUE TITLE
checker runs, errors then quits

### ISSUE THREAD

**Issue by peepopoggers** [UnamSanctam/SilentCryptoMiner#202]
```
Unhandled Exception: System.MissingMethodException: Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'.
   at hnmkpwowqjpa.Main()
```
Any idea what this is?
Thanks.

Also I did not run it as admin. Do I need to?

**Comment by UnamSanctam** [comment]
Looks like you have some other program that also gets found by the checker but isn't a miner so when it tries to get the command line arguments it fails. So probably you're just unlucky enough that the random identification string generated also coincides with some other program you have running. I would recommend just rebuilding the miner.

**Comment by peepopoggers** [comment]
Hmm.
I built the .exe using wine on linux, so that may be an issue? But I do not see why, wine is pretty good. Also when i run the same .exe on wine the checker runs (miner field is blank though) so I don't think it is a problem with my compiler, however, I may be wrong. I will keep trying and I will let you know if I find a solution.

**Comment by peepopoggers** [comment]
Alright, so building inside the VM itself instead of wine seems to work now, the checker runs.

**Comment by peepopoggers** [comment]
However, seperate issue but I will discuss it here because I am lazy: the miner list shows xmr only when i enabled wownero for cpu. I did not specify a pool because I heard wownero was solo mine. Am I missing something?

**Comment by UnamSanctam** [comment]
If it shows `--algo=rx/wow` then it's mining Wownero correctly, you should specify your node/proxy that you will mine to as the pool.

**Comment by peepopoggers** [comment]
Ah, so to solo mine I need to give permissions? May that be a danger giving a secret spend key inside the .exe?

**Comment by UnamSanctam** [comment]
Yes anyone that gets the key can spend the funds you have, so it's better to use a proxy (xmrig-proxy) between the node and your miners. It's also best to have a different mining wallet that you send everything from into a real wallet periodically just to be safe.
