### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2020]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/2c490ef0-d3f1-4722-b898-296f7714d9ed)

this pc showing offline 14m but it's online

**Comment by UnamSanctam** [comment]
That means that it cannot connect to your web panel.

**Comment by DARK-DEVIL-66** [comment]
all security has been permanetly killed by me (diffender,firewall etc)
data speed fine
no more process running
active 2-3 houres but now it's showing offline

**Comment by DARK-DEVIL-66** [comment]
> That means that it cannot connect to your web panel.

server side no fire wall and it's vps unlimited band wegith and etc

**Comment by DARK-DEVIL-66** [comment]
nad laptop has been freezed laptop have in my font of eye i know miners running i hear fan sound little fast

**Comment by UnamSanctam** [comment]
It's either one of these three reason:
1) The miner isn't running.
2) The computer cannot connect to your web panel server.
3) Your web panel server cannot accept the connection.
