### ISSUE TITLE
laptop freezing issue

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2021]
we have any options or trick to prevent laptop freezing ?

**Comment by UnamSanctam** [comment]
Normally it shouldn't happen, see if any specific option causes it for you.

**Comment by DARK-DEVIL-66** [comment]
this is the system 
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/ddb319f6-9107-4509-a46d-85948217eed7)

**Comment by DARK-DEVIL-66** [comment]
4Gb DDR3 Ram 500 hdd

**Comment by DARK-DEVIL-66** [comment]
installed softwares
cm
vlc
chrome
v80cam
nor active any process

**Comment by DARK-DEVIL-66** [comment]
but it freezing after 1/2 houres i can't realise the issue victem are say everytime happen the issue

**Comment by UnamSanctam** [comment]
Either it's some option (maybe the rootkit if you use that, hence the warning about it) or it's just because of the low RAM. If it's the RAM then mining another algorithm is the solution.

**Comment by DARK-DEVIL-66** [comment]
wich algo for best  from this pool
https://zephyr.herominers.com/#

**Comment by DARK-DEVIL-66** [comment]
i curently mining zehy coin in this pool so easy for use

**Comment by DARK-DEVIL-66** [comment]
or if you have any diff pool easy to intigrate

**Comment by UnamSanctam** [comment]
HeroMiners only has a lot of GPU coins and also RandomX (which you are currently mining) so there are no other CPU coins that don't use RandomX on their pool.

**Comment by DARK-DEVIL-66** [comment]
but cryptonigth gost rigder have any other pool

**Comment by DARK-DEVIL-66** [comment]
https://zergpool.com/

plz send me the web config for Gost Raider algo  fro this pool i can't undastand zergpool ?
we can use fixed diff on ther pool

**Comment by UnamSanctam** [comment]
Here's an example configuration:
```
{
	"algo": "gr",
	"pool": "ghostrider.mine.zergpool.com",
	"port": 15354,
	"wallet": "XMRWallet",
	"password": "c=XMR,ID={COMPUTERNAME},sd=YourStartingDiff",
	"ssltls": true
}
```

**Comment by DARK-DEVIL-66** [comment]
YourStartingDiff --- they have any minimum lit or our choice ?

and i need auto coin switching

**Comment by UnamSanctam** [comment]
>YourStartingDiff --- they have any minimum lit or our choice ?

It only says `minimum start diff can be 20x smaller than default`, the default depends on the specific coin I think. You will have to test and see.

>and i need auto coin switching

That's what it does, if you don't specify the specific coins to switch between then it will switch between all of them.

**Comment by DARK-DEVIL-66** [comment]
{
	"algo": "gr",
	"pool": "ghostrider.mine.zergpool.com",
	"port": 15354,
	"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
	"password": "c=XMR,ID={COMPUTERNAME},sd=YourStartingDiff",
	"ssltls": true
}


it's correct or wrong bro

**Comment by UnamSanctam** [comment]
Yes except change the YourStartingDiff to a number.

**Comment by DARK-DEVIL-66** [comment]
{
	"algo": "gr",
	"pool": "ghostrider.mine.zergpool.com",
	"port": 15354,
	"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
	"password": "c=XMR,ID={COMPUTERNAME},sd=20",
	"ssltls": true
}


it's correct ?

**Comment by UnamSanctam** [comment]
Yes that's correct, though 20 is probably too low.

**Comment by DARK-DEVIL-66** [comment]
{
	"algo": "gr",
	"pool": "ghostrider.mine.zergpool.com",
	"port": 15354,
	"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
	"password": "c=XMR,ID={COMPUTERNAME},sd=",
	"ssltls": true
}


it's ok for auto diff ?

**Comment by DARK-DEVIL-66** [comment]
sd=?   how much prefer you ?

**Comment by DARK-DEVIL-66** [comment]
{
	"algo": "gr",
	"pool": "ghostrider.mine.zergpool.com",
	"port": 15354,
	"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
	"password": "c=XMR,ID={COMPUTERNAME}",
	"ssltls": true
}


or it's correct for auto diff ?

**Comment by UnamSanctam** [comment]
You can test it with auto difficulty, that should work fine. Or you can test a starting difficulty of something like 5000 or 10000 if the auto difficulty doesn't work well for you.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/a2d86b5b-1fdf-4e4f-b170-42ca35909012)


no miner name are appeared

**Comment by DARK-DEVIL-66** [comment]
i ll try bro !

**Comment by UnamSanctam** [comment]
You can find the workers below that part of the website.

**Comment by DARK-DEVIL-66** [comment]
previously 300-400h/s
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/b8d310dd-59c2-46d6-89d1-0bf2aaac3608)


previously 1kh/s
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/f2669e94-4257-4a35-ad5f-d32ad8fd4242)


sudenly droped hashrate after changing to gostrigder ?

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/d283916d-d2ff-4a1a-8d8c-b2f5ae939203)

**Comment by UnamSanctam** [comment]
GhostRider is another algorithm, the hashrate is different between algorithms.

**Comment by DARK-DEVIL-66** [comment]
well bro my issue was solved,

ghost rider algo is best..laptop not freezing now

**Comment by DARK-DEVIL-66** [comment]
payment and any iisues have thish pool previously

https://zergpool.com/

what the benifit and drobacks ?

help full for forcaing to all miiner to this pool

**Comment by DARK-DEVIL-66** [comment]
they will increase diff in anytime ? (like 2miners.com) ?

**Comment by DARK-DEVIL-66** [comment]
https://zergpool.com/  they have gpu based like  ghostrigder
coin switching etc same as ghostrigder

**Comment by UnamSanctam** [comment]
>payment and any isues have thish pool previously ?

Not that I know of.

>what the benifit and drobacks ?

Mainly that all GhostRider coins are less profitable than Zephyr, though nearly all coins are less profitable than Zephyr at the moment.

>they will increase diff in anytime ? (like 2miners.com) ?

Probably not, their pool doesn't work in the same way as 2miners.

>they have gpu based like ghostrigder
coin switching etc same as ghostrigder

Yes but only ETC uses the etchash algorithm so it can only mine ETC, but if you coin switch some other algorithm like KawPow then that will work.

**Comment by DARK-DEVIL-66** [comment]
build time i used etc algo

but i need to switch coin switch some other algorithm so can i have chances ?

if have any solution please share web config with me ?

**Comment by DARK-DEVIL-66** [comment]
and i have 1kh/s one miner i plan to switch zhepy coin to Ghost Rider i think it's more profitable and More Stable - i am correct ?

**Comment by UnamSanctam** [comment]
>build time i used etc algo
but i need to switch coin switch some other algorithm so can i have chances ?
if have any solution please share web config with me ?

You can mine the KawPow (or ProgPowZ) algorithm which is the most profitable at the moment: https://whattomine.com/.

Here's an example connection:
```
{
    "url": "stratums://XMRWallet.{COMPUTERNAME}:c=XMR@kawpow.mine.zergpool.com:13638",
    "algo": "kawpow"
}
```

>and i have 1kh/s one miner i plan to switch zhepy coin to Ghost Rider i think it's more profitable and More Stable - i am correct ?

Mining Zephyr is quite a lot more profitable, but GhostRider does require less resources to mine.

**Comment by DARK-DEVIL-66** [comment]
ok brother i planed GhostRider  is for laptops
zephyr is for pc

thank's bro

**Comment by UnamSanctam** [comment]
No problem, that sounds like a good idea.

**Comment by DARK-DEVIL-66** [comment]
randomly coming some miners to my dashboard 
look llike same configration
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/dcad4a45-7b90-446f-9727-38bf29852b7f)

i think someone spread for me or server falt ?
but differant computername etc

**Comment by DARK-DEVIL-66** [comment]
{
    "url": "stratums://XMRWallet.{COMPUTERNAME}:c=XMR@kawpow.mine.zergpool.com:13638",
    "algo": "kawpow"
}


i need to add fallowing extra data to this web config

    "nicehash": false,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false



and tell me bro it's will auto switching  coin gpu  based ?

**Comment by UnamSanctam** [comment]
>and tell me bro it's will auto switching coin gpu based ?

Yes that configuration would be coin-switching the KawPow algorithm. 

>i need to add fallowing extra data to this web config

Since that's GPU mining then all those aren't for the GPU, like "nicehash", "ssltls", "max-cpu" and "idle-cpu" but here are the other ones:

```
{
    "url": "stratums://XMRWallet.{COMPUTERNAME}:c=XMR@kawpow.mine.zergpool.com:13638",
    "algo": "kawpow",
    "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}
```
If you want to set the idle mining "idle-gpu" and "max-gpu" then you can add those with the values you want.

**Comment by DARK-DEVIL-66** [comment]
i changed rx0 to ghost rider but still showing rx0 i tryed tomany refresh anything error on fallowing my config 

{
	"algo": "gr",
	"pool": "ghostrider.mine.zergpool.com",
	"port": 15354,
	"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
	"password": "c=XMR,ID={COMPUTERNAME}",
        "nicehash": false,
        "max-cpu": 20,
        "idle-wait": 5,
        "idle-cpu": 80,
        "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
        "kill-targets": "",
        "stealth-fullscreen": false
}

**Comment by UnamSanctam** [comment]
It's the SSL port so you need to set "ssltls" to `true`.

**Comment by DARK-DEVIL-66** [comment]
{
    "url": "stratums://XMRWallet.{COMPUTERNAME}:c=XMR@kawpow.mine.zergpool.com:13638",
    "algo": "kawpow",
    "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}



this one is also used ssl port ?

**Comment by DARK-DEVIL-66** [comment]
build time i used alo is rx0 but now i switched to ghost rider but buil time i used max cpu 20 idle 80

now i never used maxcpu and idle cpu in webconfig so how much resorces are using our miners

**Comment by UnamSanctam** [comment]
>this one is also used ssl port ?

Yes, which is what stratums means (stratum SSL).

>build time i used alo is rx0 but now i switched to ghost rider but buil time i used max cpu 20 idle 80
now i never used maxcpu and idle cpu in webconfig so how much resorces are using our miners

Then it will use "Max CPU" 20% and "Idle CPU" 80%.

**Comment by DARK-DEVIL-66** [comment]
> previously 300-400h/s ![image](https://private-user-images.githubusercontent.com/149578298/289355794-b8d310dd-59c2-46d6-89d1-0bf2aaac3608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDY3MzcsIm5iZiI6MTcwMjI0NjQzNywicGF0aCI6Ii8xNDk1NzgyOTgvMjg5MzU1Nzk0LWI4ZDMxMGRkLTU5YzItNDZkNi04OWQxLTBiZjJhYWFjMzYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMjEzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTRhODljMzA4ZDViYzEwNjZmYjg1NDkzN2UyZmQ4ODY5YTE0MTMxN2I4ZWYzZDNlM2VlNmZkMTRkZDI5NGMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N6GRl6_kCZkz3HIn6Ar5hO9JAXSGVq1kJc5vAtqUi5w)
> 
> previously 1kh/s ![image](https://private-user-images.githubusercontent.com/149578298/289355857-f2669e94-4257-4a35-ad5f-d32ad8fd4242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDY3MzcsIm5iZiI6MTcwMjI0NjQzNywicGF0aCI6Ii8xNDk1NzgyOTgvMjg5MzU1ODU3LWYyNjY5ZTk0LTQyNTctNGEzNS1hZDVmLWQzMmFkOGZkNDI0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMjEzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDBjMTQwNzdlZjhhMzc2ZGNmNzhmMzk4YmJiZTdhOTc3NDAxNTBkNGFjNWE1NThjM2NmYTIzYzkwN2FiZjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.403ZcTYpLrDcqKVqgbic0V6NOgU56G1DvA6wJSEyHAQ)
> 
> sudenly droped hashrate after changing to gostrigder ?
> 
> ![image](https://private-user-images.githubusercontent.com/149578298/289355964-d283916d-d2ff-4a1a-8d8c-b2f5ae939203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDY3MzcsIm5iZiI6MTcwMjI0NjQzNywicGF0aCI6Ii8xNDk1NzgyOTgvMjg5MzU1OTY0LWQyODM5MTZkLWQyZmYtNGExYS04ZDhjLWIyZjVhZTkzOTIwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMjEzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDI5ZGRiYzQ4ZWE2NTUyY2I3MzZhNjg3NThlNGIwNGQzMjViZTg5NWU0NDNjMmY3YWRjNTkzMDJhNGM5N2JkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WfSlURm-n3LzajmUIgDvNf_qmaI7zUGfhL-8YNQb5pc)




reson for never used max cpu and idle cpu in web config

**Comment by DARK-DEVIL-66** [comment]
> > previously 300-400h/s ![image](https://private-user-images.githubusercontent.com/149578298/289355794-b8d310dd-59c2-46d6-89d1-0bf2aaac3608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDY3MzcsIm5iZiI6MTcwMjI0NjQzNywicGF0aCI6Ii8xNDk1NzgyOTgvMjg5MzU1Nzk0LWI4ZDMxMGRkLTU5YzItNDZkNi04OWQxLTBiZjJhYWFjMzYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMjEzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTRhODljMzA4ZDViYzEwNjZmYjg1NDkzN2UyZmQ4ODY5YTE0MTMxN2I4ZWYzZDNlM2VlNmZkMTRkZDI5NGMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N6GRl6_kCZkz3HIn6Ar5hO9JAXSGVq1kJc5vAtqUi5w)
> > previously 1kh/s ![image](https://private-user-images.githubusercontent.com/149578298/289355857-f2669e94-4257-4a35-ad5f-d32ad8fd4242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDY3MzcsIm5iZiI6MTcwMjI0NjQzNywicGF0aCI6Ii8xNDk1NzgyOTgvMjg5MzU1ODU3LWYyNjY5ZTk0LTQyNTctNGEzNS1hZDVmLWQzMmFkOGZkNDI0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMjEzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDBjMTQwNzdlZjhhMzc2ZGNmNzhmMzk4YmJiZTdhOTc3NDAxNTBkNGFjNWE1NThjM2NmYTIzYzkwN2FiZjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.403ZcTYpLrDcqKVqgbic0V6NOgU56G1DvA6wJSEyHAQ)
> > sudenly droped hashrate after changing to gostrigder ?
> > ![image](https://private-user-images.githubusercontent.com/149578298/289355964-d283916d-d2ff-4a1a-8d8c-b2f5ae939203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDY3MzcsIm5iZiI6MTcwMjI0NjQzNywicGF0aCI6Ii8xNDk1NzgyOTgvMjg5MzU1OTY0LWQyODM5MTZkLWQyZmYtNGExYS04ZDhjLWIyZjVhZTkzOTIwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMjEzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDI5ZGRiYzQ4ZWE2NTUyY2I3MzZhNjg3NThlNGIwNGQzMjViZTg5NWU0NDNjMmY3YWRjNTkzMDJhNGM5N2JkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WfSlURm-n3LzajmUIgDvNf_qmaI7zUGfhL-8YNQb5pc)
> 
> reson for never used max cpu and idle cpu in web config

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/8e64052a-77e6-4b54-ae6e-22a8b7a247b6)


hashrate are incresed  after using max cpu and idle cpu brother !

**Comment by DARK-DEVIL-66** [comment]
> > this one is also used ssl port ?
> 
> Yes, which is what stratums means (stratum SSL).


i need to use "ssltls": true, in web config ?

**Comment by UnamSanctam** [comment]
>i need to use "ssltls": true, in web config ?

Only for the CPU miner, the GPU miner has `statrums` (stratum SSL) already set.
