### ISSUE TITLE
The file does not work when renaming and moving

### ISSUE THREAD

**Issue by odiboi** [UnamSanctam/SilentCryptoMiner#2025]
When I move the exe or change its name it doesn't work. Can you help?
before move ![Screenshot_2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/153538829/39a3691c-34bd-422e-8279-a45e666bc347)
after move ![Screenshot_3](https://github.com/UnamSanctam/SilentCryptoMiner/assets/153538829/05def36d-71b8-4cd9-9eef-d6e96d2a7291)

**Comment by UnamSanctam** [comment]
Can you try with the latest version of the miner?

**Comment by odiboi** [comment]
> Can you try with the latest version of the miner?

Actually, this problem occurred when I used the latest version, now I am trying again with version 3.3.1, thank you for the quick response, I am grateful

**Comment by UnamSanctam** [comment]
Hmm the program shouldn't have the shield if you're using version 3.4.0 (it does it using the code instead now). What is the different names you had? Or if you can't tell is there some special character in the new name? And does your user have any special characters inside the name (since the second try was on the desktop)?

**Comment by UnamSanctam** [comment]
Depends on if both have the same "Startup" settings since they would be overwriting each other. After the move does it not appear in the checker after it's done installing?

**Comment by odiboi** [comment]
> Depends on if both have the same "Startup" settings since they would be overwriting each other. After the move does it not appear in the checker after it's done installing?

no it doesn't appear and yes they are both saving to appdata, any ideas what should I do?

**Comment by UnamSanctam** [comment]
Interesting, does it open the UAC window (the window that asks you to allow it to run as administrator) when you run it on the desktop? And does it open that if you run it in the build folder? Can you try to build another build and see if the same thing happens with that?

**Comment by odiboi** [comment]
> İlginç, masaüstünde çalıştırdığınızda UAC penceresini (yönetici olarak çalışmasına izin vermenizi isteyen pencere) açıyor mu? Ve onu derleme klasöründe çalıştırdığınızda açılıyor mu? Başka bir yapı inşa etmeyi deneyebilir misiniz ve onda da aynı şeyin olup olmadığını görebilir misiniz? Adında boşluk olmadan deneyebilir misiniz ve işinize yarayıp yaramayacağını görebilir misiniz? `Alan sahibi olmak benim için işe yarar ama belki de bilgisayarlar arasında bu konuda bazı farklar vardır.

**Comment by Prince-classic** [comment]
> When I move the exe or change its name it doesn't work. Can you help?
> before move ![Screenshot_2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/153538829/39a3691c-34bd-422e-8279-a45e666bc347)
> after move ![Screenshot_3](https://github.com/UnamSanctam/SilentCryptoMiner/assets/153538829/05def36d-71b8-4cd9-9eef-d6e96d2a7291)
> 

Please kindly can you help me with aviator predictor

**Comment by Prince-classic** [comment]
Please help with aviator predictor please
