### ISSUE TITLE
auto switching config

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2026]
recently i  think you know i switched pool 2miners.com to herominer zephy 
simply i switched rx0 to zephy config from web penal 
work well recent 2-3 days

but now the particuler miner was switching to 2miner(rx0) 
but still same in web penal are showing zephy coin config
but miner are appear to randomly herominer and 2miner dashboard when i switching the config it will going to offline

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/d715459a-c3fa-4d32-aa73-d606a9122e43)

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/f427a510-c9fa-448f-b9e7-46e29158583c)

**Comment by DARK-DEVIL-66** [comment]
but onethink i noticed before never going to hashrate 6/7KH/s in 2miners dashboard today it's appeared to 7KH/s i think it's possible to used zhepy coin fixed diff 150000

**Comment by UnamSanctam** [comment]
Most likely it wasn't able to contact the Zephyr pool, so it moved on to the next connection which was 2miners.

**Comment by DARK-DEVIL-66** [comment]
sorry bro i finded the issue was on my side i previously used hacked cpenal so forweded all miner into my vps(API END point) issue is the old cpenal have web penal 
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/316adb85-6253-4699-8cf5-1386db82c297)
