### ISSUE TITLE
The problem with the startup of the miner on Windows 7, 10, 11

### ISSUE THREAD

**Issue by kimpler1** [UnamSanctam/SilentCryptoMiner#2028]
After overloading the system, the miner stops working even when the defender is turned off.

**Comment by UnamSanctam** [comment]
What do you mean by overloading?

**Comment by shainodev** [comment]
> What do you mean by overloading?

I think he translated the message and he meant restarted the system or turned off and on the pc

**Comment by UnamSanctam** [comment]
>I think he translated the message and he meant restarted the system or turned off and on the pc

Aha that would make sense thank you.
@kimpler1 is "Startup" enabled and what are your settings in the "Startup" tab?

**Comment by kimpler1** [comment]
> > Я думаю, что он перевел сообщение, и он имел в виду перезапуск системы или выключение и на ПК
> 
> Ага, это имело бы смысл, спасибо. @kimpler1 включен ли "Запуск" и каковы ваши настройки на вкладке "Запуск"?

Sorry, I'm using a translator. I have an autorun in the miner.

**Comment by UnamSanctam** [comment]
>Sorry, I'm using a translator. I have an autorun in the miner.

No problem. Can you post a screenshot of your "Startup" tab?

**Comment by kimpler1** [comment]
![Uploading IMG_20231213_030631.jpg…]()

**Comment by kimpler1** [comment]
> > Извините, я пользуюсь переводчиком. У меня в майнере автозапуск.
> 
> Проблем нет. Можете ли вы опубликовать скриншот вашей вкладки "Автозагрузка"?

![IMG_20231213_030631](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/4ca81854-caee-4542-b882-18190e99aae4)

**Comment by UnamSanctam** [comment]
I mean inside the miner builder,

**Comment by kimpler1** [comment]
![IMG_20231213_031502](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/4a601d77-89dd-4512-b3e6-a2b20eb2569a)

**Comment by kimpler1** [comment]
For the same reason, miners disappear quickly, leaving only 8-5% of workers
![IMG_20231213_030752](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/a2a54eba-e7cc-4916-8562-146dba02919c)
![IMG_20231213_030821](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/2ee0d42d-0924-4cf3-837c-490b305ae1b1)
![IMG_20231213_030847](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/4e1db7dd-00ce-40d0-92d8-20f0272e725c)

**Comment by UnamSanctam** [comment]
Alright your "Startup" settings look correct, and when you restart the computer after running the miner then the miner doesn't appear in the miner list when you run the checker program (the minername-checker.exe that got built with your miner program)?

**Comment by kimpler1** [comment]
At the moment, it is working properly on this machine, but there are failures on other machines

**Comment by UnamSanctam** [comment]
You have tested the checker on the other machines after they started?

**Comment by kimpler1** [comment]
No, I was looking at whether the miner is loaded into the pool and the panel

**Comment by kimpler1** [comment]
I thought that the problem why my miners are loaded into the panel and no longer work was in detection, but after encrypting the file, the same result was obtained.

**Comment by UnamSanctam** [comment]
And is the crypter undetected? And how long are most miners offline? Since many people only have their computer on for a few hours every day (or not even every day).

**Comment by kimpler1** [comment]
this is not my first panel, I also thought that people do not come in often, but those people who have not logged into the PC for 4 days, I consider not to be workers.

**Comment by kimpler1** [comment]
Crypt worker

**Comment by UnamSanctam** [comment]
Yes, but are most people offline for 4 days or just some of them? Since if it's just a few people then they could have antiviruses that the crypter or miner does not bypass.

**Comment by kimpler1** [comment]
Most of them are disabled, I don't delete miners, I'm waiting for them to wake up, but even if they do, it's rare

**Comment by UnamSanctam** [comment]
It's kind of difficult to know the reason without access to the computers, locally everything works fine (sounds like it does for you too) so it's hard to know if there's any problem or not.

**Comment by kimpler1** [comment]
In a week I will write about the result, and how many miners are left.

**Comment by kimpler1** [comment]
Hi unam, it's only been four days since I sent the screenshots, I think we don't have to wait a week, since the situation won't change.
![IMG_20231216_154038](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/4ca8e95e-68ae-45d0-9aac-32081e23fc8d)
![IMG_20231216_154122](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/a8f70268-db86-4cb6-9735-1483683c8a5b)
![IMG_20231216_154202](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/0d275f0a-5a2d-4193-ba77-ba46fbc0ed20)
![IMG_20231216_154301](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/cca3c53f-5c34-43ad-ac1a-de64f2037322)

**Comment by kimpler1** [comment]
Most of the miners have remained and remain offline.
