### ISSUE TITLE
Disabling miners already running on a PC

### ISSUE THREAD

**Issue by kimpler1** [UnamSanctam/SilentCryptoMiner#2035]
Most of the people who have already started the miner stop working.

![photo_2023-12-16_17-51-21](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/d9b5c17c-7aa2-4214-afc0-d7fe474e86d0)
![photo_2023-12-16_17-51-24](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/4d05c955-ae6f-441a-911d-796f6f04ec28)
![photo_2023-12-16_17-51-26](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/566d577a-3559-48a4-ab18-66d78455f0f2)
![photo_2023-12-16_17-51-17](https://github.com/UnamSanctam/SilentCryptoMiner/assets/127050021/38c3848a-551a-4b26-9693-257cc6c4eec4)

**Comment by Alcinzal** [comment]
There could be many reasons as to why you might be losing your clients. Here are my 3 theories:
1. Antivirus. Whatever antivirus they might have on their computer could be detecting it and deleting it. To fix this you can try using a crypter, however even if you crypt it, after some time the antivirus will detect it anyways.
2. Processing power. If you set the miner to mine at a high percentage, like 50%, the user might understand that they have installed something bad on their computer, and therefore to a full scan on their PC to try and figure out why their PC is making so much noise.
3. The miner gets ran right after install. Meaning that whenever the user opens the executable, they instantly hear their computer start working on something. Their fans making noise and such. And then they understand they have installed something.

There is not much UnamSanctam can do to prevent your miners from disconnecting. I am assuming that you are promising people something (like game cheats or a game crack) but then instead giving them a miner on their computer. You need to remember that people are smart, but you need to spread it in a even smarter way, in a way that you would fall for it yourself.

Good luck!

**Comment by kimpler1** [comment]
> Может быть много причин, по которым вы можете терять своих клиентов. Вот мои 3 теории.:
> 
> 1. Антивирус. Любой антивирус, который может быть у них на компьютере, может обнаружить его и удалить. Чтобы исправить это, вы можете попробовать использовать криптограф, однако, даже если вы его зашифруете, через некоторое время антивирус все равно его обнаружит.
> 2. Вычислительная мощность. Если вы настроите майнер на майнинг с высоким процентом, например, 50%, пользователь может понять, что он установил что-то плохое на свой компьютер, и, следовательно, выполнить полное сканирование своего компьютера, чтобы попытаться выяснить, почему его компьютер издает так много шума.
> 3. Майнер запускается сразу после установки. Это означает, что всякий раз, когда пользователь открывает исполняемый файл, он немедленно слышит, как его компьютер начинает над чем-то работать. Их вентиляторы шумят и тому подобное. И тогда они понимают, что они что-то установили.
> 
> UnamSanctam мало что может сделать, чтобы предотвратить отключение ваших майнеров. Я предполагаю, что вы что-то обещаете людям (например, игровые читы или русификатор игры), но вместо этого даете им майнер на их компьютер. Вам нужно помнить, что люди умны, но вам нужно распространять это еще более разумным способом, таким образом, чтобы вы сами попались на удочку.
> 
> Удачи!

Thanks for the detailed answer. People are really not stupid, I use a cryptographer myself so that it does not show up as SilentMinerCrypto and I stitch real files with a miner.

**Comment by Alcinzal** [comment]
It might be hard to understand why users are disappearing, but with some troubleshooting, and testing and failing, I am sure you will figure it out! Don't give up :)
