### ISSUE TITLE
issues occured some miners

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/SilentCryptoMiner#2052]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/d07b9384-1492-464e-bb9a-7354a55f6a4f)

it's previously worked fine but now it's giving fallowing error

**Comment by DARK-DEVIL-66** [comment]
i am waiting your response

**Comment by UnamSanctam** [comment]
It means that it couldn't connect to the pool when it was online.

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/149578298/909798af-58d0-4db3-b0b7-0f91ab0baab3)
