### ISSUE TITLE
Security breach 🚩🚩🚩

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#2057]
Hello brother. Thanks for providing this awesome software. 🙏🙏🙏

2 days ago, new miner is added to my unam web panel. However it isn't a miner. It is a message and clear security breach . Take a look the screenshot.

![Screenshot_20231224-144532_1.jpg](https://github.com/UnamSanctam/SilentCryptoMiner/assets/101794261/e88e8056-f71c-49d0-84ba-ab37d784fdad)

As u can see, the attacker successfully added his message as a miner in the database. I say this certainly because the time difference between first connection and last connection of the miner is ~6 sec. So the attacker was working around with the database penetration.

For now, there is no problem happened on me, but it is a good sign.

Feel free to ask me any details to investigate the situation 👍

**Comment by UnamSanctam** [comment]
Yes they only need to connect to the web panel just like the miner does. They just imitated a miner connection with their own data. That's normal behavior, as long as they send the correct JSON format then it will be added: https://github.com/UnamSanctam/UnamWebPanel/blob/master/UnamWebPanel/api/endpoint.php

**Comment by DerXanRam** [comment]
> Yes they only need to connect to the web panel just like the miner does. They just imitated a miner connection with their own data. That's normal behavior, as long as they send the correct JSON format then it will be added: https://github.com/UnamSanctam/UnamWebPanel/blob/master/UnamWebPanel/api/endpoint.php

Yes. They are imitated the miner connection. But it can be an attack for fun. Like flooding the database with fake miner connections. It is good to add a filter for the endpoint. 👍

**Comment by UnamSanctam** [comment]
Well, depends on the filter. There's not really any way to verify that a connection is legitimate, and even then the person can still imitate that as well since they know of your miner connection (hence how they could imitate it).

**Comment by DerXanRam** [comment]
> Well, depends on the filter. There's not really any way to verify that a connection is legitimate, and even then the person can still imitate that as well since they know of your miner connection (hence how they could imitate it).

Yes. That's correct. For now, i whitelisted my miners IP on my host and that's a good solution 👍

**Comment by DerXanRam** [comment]
I'm closing the issue for now. If new thing happened, i will reopen it👍
