### ISSUE TITLE
RootKit

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2059]
Hello Unam. I have a couple of questions:
1. Is it possible to run a rootkit separately from the miner as an executable file, and in this case will it work and hide the miner?
2. Is there an easy way to change the file name and the process itself which the rootkit will hide?

**Comment by UnamSanctam** [comment]
1. Yes that should work fine.
2. Only by compiling your own version for the rootkit I believe https://github.com/bytecode77/r77-rootkit.

**Comment by masterjek** [comment]
1. If I use the rootkit separately. I disable it in the builder, but how can I select the miner injection into the dialer?
2. If I assemble the rootkit myself, can you tell me the part of the code responsible for the name of the file and the injection process itself, which will be hidden? Or is there a lot of things that need to be changed?

**Comment by UnamSanctam** [comment]
1. The miner injections are chosen here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/c61e842d5ec04e2493a83f54f096ba2f3b95687d/SilentCryptoMiner/Classes/Codedom.cs#L332
https://github.com/UnamSanctam/SilentCryptoMiner/blob/c61e842d5ec04e2493a83f54f096ba2f3b95687d/SilentCryptoMiner/Forms/Builder.cs#L217
2. You only really need to change the prefix here (in mine the prefix is dialer):
https://github.com/bytecode77/r77-rootkit/blob/master/r77api/r77def.h
And
https://github.com/bytecode77/r77-rootkit/blob/master/Global/R77Const.cs
And then you should also add the program you're injecting the watchdog into, into PROCESS_EXCLUSIONS.

**Comment by masterjek** [comment]
> 2\. You only really need to change the prefix here (in mine the prefix is dialer):
>     https://github.com/bytecode77/r77-rootkit/blob/master/r77api/r77def.h
>     And
>     https://github.com/bytecode77/r77-rootkit/blob/master/Global/R77Const.cs

This is what I found thanks.

I can't find in what part of the code to change the process that will be hidden. For example, I implement it on the command line. I do not use a watchdog timer in the miner.
