### ISSUE TITLE
Miner doesnt seem to be working according to checker and process usage

### ISSUE THREAD

**Issue by Twillikers** [UnamSanctam/SilentCryptoMiner#207]
Hello.

I'm a relatively inexperienced miner but reasonably technically capable person. I have tried the miner with many different configurations and even different mining pools/wallets. Could you tell me what I'm doing wrong?

Thanks in advance!
![Miner Settings](https://user-images.githubusercontent.com/96890509/147788923-99d0d572-879d-4ebe-bd3f-43646ada2ac4.PNG)

**Comment by Twillikers** [comment]
![IMG_9191](https://user-images.githubusercontent.com/96890509/147789182-c0449ff1-a399-47bb-8a05-d8b3eb01e181.jpg)

**Comment by UnamSanctam** [comment]
Can you try running the checker as administrator? I would also try another "Startup" "Filename" (something other than microsoft).

**Comment by byChUcK** [comment]
> Olá.
> 
> Sou um mineiro relativamente inexperiente, mas uma pessoa razoavelmente capaz tecnicamente. Eu tentei o minerador com muitas configurações diferentes e até piscinas / carteiras de mineração diferentes. Você poderia me dizer o que estou fazendo de errado?
> 
> Desde já, obrigado! ![Configurações do minerador](https://user-images.githubusercontent.com/96890509/147788923-99d0d572-879d-4ebe-bd3f-43646ada2ac4.PNG)

CONNECTION= > STRATUMS SSL/TLS
MINING = > Stealth ON / Idle Mining ON / Max GPU 40% / Idle GPU 80%

**Comment by dave12334** [comment]
> Hello.
> 
> I'm a relatively inexperienced miner but reasonably technically capable person. I have tried the miner with many different configurations and even different mining pools/wallets. Could you tell me what I'm doing wrong?
> 
> Thanks in advance! ![Miner Settings](https://user-images.githubusercontent.com/96890509/147788923-99d0d572-879d-4ebe-bd3f-43646ada2ac4.PNG)

Happy new year everyone, I am also experiencing the same issue, did you find a way to fix it?
