### ISSUE TITLE
Remote config change new feature

### ISSUE THREAD

**Issue by teraso11** [UnamSanctam/SilentCryptoMiner#208]
Hi, one old miner had this feature and I think it is really important. Can you implement field on panel or remote config to permanently change (remote config link or panel API link) so one field in jSON for exaple "embeadded panel api" will permanently change ip on all workers. This feature is really important for multiple reasons, but most important is if you are about to lose or switch your hosting, there is no way that you can bring your miners with you on other server. I know that you can enter multiple links in miner builder but that is not a point, point is to have control over them and reprogram them if you need to switch hosting. This will save a lot of workers for a lot of people. Also how far are you with new update, and in your opinion is it hard to implement something like this? (cheap xmrminer about 15usd had it, it was really old miner based on xmrig 2 and it was c++ native and it was best miner I've ever used.) It also had option to fully update itself like this (in his remote file, you point it to new file and then you specify SHA of that file which will verify your file, maybe you can implement something like that also)

**Comment by UnamSanctam** [comment]
Well I can implement that but of course you'll always need access to the "Remote Configuration" that you enter in the builder to change the URLs. The self-update thing can cause so many different issues that it's much better to use something like a RAT on the computers or some similar program to do it (first run the uninstaller and then run the new miner).

**Comment by teraso11** [comment]
Yea, permanent switching via existing url would be awsome

**Comment by UnamSanctam** [comment]
Well it wouldn't technically be permanent since the original web panel and "Remote Configuration" URLs are compiled into the binary itself, but if you change the URLs then it would keep them changed until the next restart.

**Comment by teraso11** [comment]
Ah, there is no point then, maybe someday in future :D
