### ISSUE TITLE
xmr miner dont work on guest accounts

### ISSUE THREAD

**Issue by giorgi1999** [UnamSanctam/SilentCryptoMiner#21]
![miner222](https://user-images.githubusercontent.com/28823656/141089414-1f4e84a7-28be-446c-9477-2d94c79ffe30.png)
i tryed many rdp guest accounts but dont working

**Comment by UnamSanctam** [comment]
That line has to do with the miner and GPU check, it's possible that WMI can't run on guest accounts, generally you don't really mine on guest accounts since they are only guest accounts and not real accounts.
