### ISSUE TITLE
i can't download it    virus&trheats found  (pls help asap)

### ISSUE THREAD

**Issue by JinakfromLi** [UnamSanctam/SilentCryptoMiner#2101]
i can't download the silentcryptominer and the binder since windows say it got a virus and a suspicious code  (virus&trheats found) i turned it off but it still wont let me download how can i install the builder?

![Screenshot (94)](https://github.com/UnamSanctam/SilentCryptoMiner/assets/156385872/dd6b391b-add0-4366-967b-38bff777be69)

**Comment by UnamSanctam** [comment]
Add an exclusion to the folder you're downloading into.

**Comment by JinakfromLi** [comment]
it worked, i appreciate the fast reaction!


ty
