### ISSUE TITLE
Is this really not a virus?

### ISSUE THREAD

**Issue by BlackDiamond2108** [UnamSanctam/SilentCryptoMiner#2108]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/113206131/b3a9b0e4-9a6e-4c64-99c6-4a932f2ff550)

26 flags on virus total is crazy
(the same result with the zipped source code)

Can you explain this?

**Comment by UnamSanctam** [comment]
It's a miner builder so of course it's going to be detected, and the code is open source so you can read it yourself.

**Comment by BlackDiamond2108** [comment]
Can you tell me what exactly virustotal marks as a virus in miner builder? Because I don't understand why the builder itself would be flagged.

**Comment by UnamSanctam** [comment]
It considers both the miners included and the builder itself as potential malware, you can even see that some antiviruses have their own special detections just for my builder. Nearly all antiviruses considers mining itself to be "malware", you can try scanning xmrig (https://github.com/xmrig/xmrig, the most popular CPU miner by far) and see its detections. And things don't to have to be actually malicious the marked as malware, only that they exhibit some behaviors which could potentially be malicious in nature, or just share some aspects with actually maliware.

**Comment by UnamSanctam** [comment]
Here's the detections for xmrig (msvc-win) (which obviously isn't malware):
<img src="https://github.com/UnamSanctam/SilentCryptoMiner/assets/10323655/b851ada7-94f2-4e14-9b78-8eb05c769f00">

**Comment by BlackDiamond2108** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/113206131/70565817-c90d-48f1-992e-181aadf9a1bb)
Thanks, my antivirus is also flagging xmrig in your file as a miner.

**Comment by gabjohn3** [comment]
ppl like this one its the reason that unam should make silent crypto miner a private repo
Come on @BlackDiamond2108  Go back to school and leave this tool  alone and stop messing with tools u dont know  go learn first C#
