### ISSUE TITLE
Remote config

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2109]
Hello Unam. I'm looking for additional sites for remote configuration and many of them, when generating a link, do not have a prefix in the link "/raw" Is this prefix important for a miner? Without it, will he be able to contact this remote configuration?

**Comment by Alcinzal** [comment]
The prefix itself is not important for the miner, you just need to make sure that the remote configuration link is raw text, meaning if you visit the site the only thing you see it the text and nothing else. Here are some examples:

This does not work: https://rentry.co/39ofx/
This does work: https://rentry.co/39ofx/raw

This does not work: https://pastebin.com/mpRWix6f
This does work: https://pastebin.com/raw/mpRWix6f

If you visit those sites you can see that the ones that work only include the text. Hope you understand 🙂

**Comment by masterjek** [comment]
> The "raw" part of the link itself is not important for the miner, you just need to make sure that the remote configuration link is raw text, meaning if you visit the site the only thing you see it the text and nothing else. Here are some examples:
> 
> This does not work: https://rentry.co/39ofx/ This does work: https://rentry.co/39ofx/raw
> 
> This does not work: https://pastebin.com/mpRWix6f This does work: https://pastebin.com/raw/mpRWix6f
> 
> If you visit those sites you can see that the ones that work only include the text. So if the additional sites you use has this option, where you can view the configuration text as raw text, then it should work. Hope you understand 🙂

Thank you very much for the explanation.
