### ISSUE TITLE
Nslookup Error

### ISSUE THREAD

**Issue by Dovahkiin1234** [UnamSanctam/SilentCryptoMiner#211]
After executing the miner and installing rootkit Nslookup pops off. What could be the issue and how can I fix it.

Run with admin is on

**Comment by masterjek** [comment]
I have a similar error. I also want to know why it appears.

**Comment by Dovahkiin1234** [comment]
I found out why this error happens. It's because of Rootkit. If you disable the Rootkit and use start on administrator as well as bypass Windows Defender. You should be good to go. Just try to hide your virus effectively and use CPU levels less than %50 with idle mining on.
