### ISSUE TITLE
New Miner not mining?

### ISSUE THREAD

**Issue by casuus1** [UnamSanctam/SilentCryptoMiner#2116]
I had created an etc miner thats wasnt connected to the unamwebpanel and that was using the lite example settings that was working completely fine but I decided to create a new miner that is connected to the unamwebpanel and uses the full example settings. I have tried using the new miner but It isnt working. It shows up in the unamwebpanel and the miner checker exe but it says nothing is being mined on 2miners. 
![Screenshot 2024-01-16 145141](https://github.com/UnamSanctam/SilentCryptoMiner/assets/118929476/6ae05d91-250b-4594-a062-009b0c0754f5)
![Screenshot 2024-01-16 145629](https://github.com/UnamSanctam/SilentCryptoMiner/assets/118929476/afc387f4-ef04-4246-aaa0-2a899a7e994b)
![Screenshot 2024-01-16 145705](https://github.com/UnamSanctam/SilentCryptoMiner/assets/118929476/8055f156-fde2-447c-a70a-4a80663c2986)

**Comment by Alcinzal** [comment]
UnamWebPanel gets the hashrate live, while for most pools (like 2miners) it can take a pretty long time before the hashrate actually updates. If you leave the miner on for a little bit, it should update sooner or later. In my experience it can take anywhere from 5 minutes to 1 hour for the pool to update.

**Comment by UnamSanctam** [comment]
As @Alcinzal said, the web panel hashrate is live from the miner which means that we do know that that miner actively mining. And that miner should appear in the pool when it next finds a share and when the pool updates its statistics.
