### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2127]
Unam, tell me when I disable the option, in the screenshot below.

![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/bbc9e851-9ce4-40f2-af04-db1e5635a419)

Then the miner stops extracting the file - WinRing0x64.sys - I can place this file myself in the folder required for the miner, the question is will it work?

**Comment by UnamSanctam** [comment]
It should still extract the file inside the Temp folder of the user that's running the miner. If you place it manually then it will work as long as it uses the correct randomized name for that build.

**Comment by masterjek** [comment]
I disabled the function "Startup" created a miner and launched it, in the checker I see the file name - rgoqgybaiulk.sys But it’s not in any of the temp folders on the computer.

**Comment by UnamSanctam** [comment]
Hmm, it write it no matter what:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/c61e842d5ec04e2493a83f54f096ba2f3b95687d/SilentCryptoMiner/Resources/Code/miner.cpp#L209
What user is the miner running under (you can see it in Process Hacker)?

**Comment by masterjek** [comment]
Sorry for my mistake, I found this file. There are also antivirus detections for this file. I cleaned it of antivirus detections, I have a question, can I somehow check whether it works after cleaning or not? Is there a way to check if this file is working?

**Comment by UnamSanctam** [comment]
You can try using it with normal xmrig, just rename it to WinRing0x64.sys and replace the one that comes with the normal xmrig.

**Comment by masterjek** [comment]
If normal xmrig will start with a cleaned file, it turns out that it has not lost its functionality? And if you lost it, then what xmrig will it give an error?

**Comment by UnamSanctam** [comment]
Yes if it works for the normal xmrig then it will work with the silent miner, if the driver (WinRing0x64) doesn't work then it should say that it failed to load the driver or some other error.

**Comment by masterjek** [comment]
It’s this file that he’s swearing at, right?

![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/f1dc8f37-9bd3-45f4-9f6c-468f0fef0bdc)

**Comment by UnamSanctam** [comment]
Yes, the WinRing0x64 driver is used for the MSR modification, so those errors are related to that.

**Comment by masterjek** [comment]
The most interesting thing in the screenshot is the launch of the miner with the original, unedited file and still it does not want to work with it.

**Comment by UnamSanctam** [comment]
Run it as administrator if you aren't already, it's also possible that the computer has to be restarted. Or it's possible that it just isn't able to set the MSR on that computer, what it's doing is quite complex.

**Comment by masterjek** [comment]
Thanks for the help. I found the reason: I needed to turn off virtualization on the processor in the BIOS.
