### ISSUE TITLE
All miners gone offline 

### ISSUE THREAD

**Issue by haxful** [UnamSanctam/SilentCryptoMiner#213]
hello, all my miners were going fine for a few days now they're all now offline after they were perfectly fine and I'm not sure what to do I have attached a screenshot to try to assist 
![15bc237fb08516efb02c05841fde2245](https://user-images.githubusercontent.com/96766982/147856289-2f09303d-3588-4d37-b5e0-12619c4ae8a7.png)

**Comment by UnamSanctam** [comment]
Since they're XMR miners thus not very user detectable unless you use something like 50%-80% CPU I would assume that they are not user detections. In that case they are either all offline naturally (computers are off) or something else has happened, did you enable "Bypass Windows Defender"?

**Comment by haxful** [comment]
I changed it to 50% now and I did enable bypass windows defender on all the miners and i will attach the screenshots of the last time and the config 
![image](https://user-images.githubusercontent.com/96766982/147856833-f168febc-cf84-4215-9765-156ff0de5374.png)
![image](https://user-images.githubusercontent.com/96766982/147856856-c8d47c73-cb41-4209-a7fa-05e12d2e1523.png)

**Comment by UnamSanctam** [comment]
It only went offline a few hours ago so I would guess that it's most likely natural (computer is offline).

**Comment by haxful** [comment]
Most of them went down yesterday apparently I'm not sure why 
![image](https://user-images.githubusercontent.com/96766982/147856910-57d8f757-2c0a-4ef0-84ad-86bcc72d5971.png)
![image](https://user-images.githubusercontent.com/96766982/147856913-962b09de-1abe-4bd0-9aff-df2e9fec5f3b.png)
![image](https://user-images.githubusercontent.com/96766982/147856919-c207b6a5-51a3-47b4-a51c-1e06b87f2854.png)

**Comment by UnamSanctam** [comment]
Probably because it's new years and a weekend.

**Comment by haxful** [comment]
Yeah it could just be i don't have that many miners so they're all just actually offline and i changed the config to 50% CPU and saved it so when the miners come back on it will be at 50% right?

**Comment by UnamSanctam** [comment]
Yes it will be at 50%, best option is to wait to see if any comes online.

**Comment by haxful** [comment]
Alright I'll just wait for a few days and see what happens, also if theoretically, you was aiming for 50000 miners in total what would be the best course of action to get there? theoretically of course

**Comment by UnamSanctam** [comment]
Well, for those kinds of numbers hypothetically the best way would be to have a large online presence in some form (fake cheats, fake hacks, fake cracks or real ones of any of those would most likely be the "easiest") and utilize that but that can be hard.

**Comment by haxful** [comment]
Yeah if I was to be in that field that's what I would be doing already theoretically of course. I'll wait a few days and see if they come back online thanks for your time.
