### ISSUE TITLE
Remote Configuration

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2132]
Unam Please tell me I accidentally deleted the miner configuration on the pastebin website. There, each configuration has a set of letters and numbers at the end of the link, can I create a new paste, but indicate the character set that was in the paste that I deleted?

**Comment by UnamSanctam** [comment]
Sadly I don't believe you can.

**Comment by masterjek** [comment]
I had two remote configuration links in the miner. I was able to restore one link with the same prefix at the end of the link as it was, but the second cannot be restored. Now it turns out miners will again be able to communicate with only one link, right?

**Comment by UnamSanctam** [comment]
Yes they will communicate with the one that's still working.
