### ISSUE TITLE
hi, when i press the build button i get this error

### ISSUE THREAD

**Issue by UnsavorySpirit** [UnamSanctam/SilentCryptoMiner#2133]
hi, when i press the build button i get this error 
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/81800320/1ce36937-a6f7-4e2a-a52b-c704aa304d50)
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/81800320/73bb650a-3d63-4506-b878-bcb2ee4b1a4b)

**Comment by UnamSanctam** [comment]
Try adding the folder you're building in into your antivirus exclusions, it's possible that your antivirus is removing some compiler files.

**Comment by UnsavorySpirit** [comment]
I’ll try it

**Comment by UnsavorySpirit** [comment]
still doesn't work

> Try adding the folder you're building in into your antivirus exclusions, it's possible that your antivirus is removing some compiler files.

**Comment by UnamSanctam** [comment]
Try using the example settings (don't change them) to see if it's caused by some combination of setting you have or something else: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite

**Comment by UnsavorySpirit** [comment]
> Try using the example settings (don't change them) to see if it's caused by some combination of setting you have or something else: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite

i tried but it doesn't work neither
i even downloaded the whole thing another time
and i get a new error 
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/81800320/6db8ec8d-e113-49b5-936c-0822dbe65418)

**Comment by UnamSanctam** [comment]
Something on your computer is removing files or preventing them from being written, make sure that your antivirus exclusion is correct (if you're using Windows Defender then just turning it off doesn't work, since it will still run in the background). You can also try running the builder as administrator and see if that works, in case your permissions are messed up.

**Comment by UnamSanctam** [comment]
Can you take a screenshot of your added exclusion? Or do you have any other computer you can build it on? Sadly I can't really know what's specifically wrong on your computer.

**Comment by UnsavorySpirit** [comment]
Ok, tomorrow I will take the screenshot but what if I run it on sandbox or vm

**Comment by UnamSanctam** [comment]
>Ok, tomorrow I will take the screenshot but what if I run it on sandbox or vm

That should work fine.

**Comment by UnsavorySpirit** [comment]
don't know why but now it works
