### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PH03N1X1000** [UnamSanctam/SilentCryptoMiner#2136]
Does the Hashrate gets cutoff or gets low while using this miner ? because it seems that like it get less hashrate according to the miner page as well as the web server. Please Let me know if this is some condition.

**Comment by UnamSanctam** [comment]
Depends on what you set the "Max GPU" (or "Idle GPU" if it's idle mining) to.

**Comment by PH03N1X1000** [comment]
i have disabled GPU mining and idle mining as well as that i have set MAX CPU to 100% is it fine then ?

**Comment by UnamSanctam** [comment]
Aha, then yes that's fine, are you running it as administrator? You should get the same hashrate in the silent miner as you would if you run a normal xmrig miner.

**Comment by PH03N1X1000** [comment]
Ya i figured it out i was running it as admin i was having many CPU bounded processes running which caused the miner to bottleneck. BTW thanks for this project its awesome it has helped me in so many projects i would donate to you as soon as it is feasible to me thanks. Keep Up the Good Work
