### ISSUE TITLE
Miner not working

### ISSUE THREAD

**Issue by Duy0104** [UnamSanctam/SilentCryptoMiner#214]
Hello Unam. I have an problem that the miner doesn't working. I had turn off stealth and i'm using ethermine pool so i didn't fill in the worker space. But when running the miner and run the checker it showing up at Miner blank space. Hope you will reply this, thanks you alot

**Comment by UnamSanctam** [comment]
What GPU does it say you have in the checker?

**Comment by Duy0104** [comment]
It doesn't say anything. It just show like this 
Watchdog Running: No
Miners:
GPUS:
NVIDA GeForce GTX 1060 6GB

**Comment by UnamSanctam** [comment]
Do you have "Install Rootkit" enabled? If so then it won't show up in the list (since it's hidden), also check that your GPU drivers are somewhat updated.

**Comment by Duy0104** [comment]
xD i didn't install Rootkit. Imma try right now. If it work i will reply this. Again thanks for your help Unam

**Comment by UnamSanctam** [comment]
Yeah try updating your drivers, it's the most likely unless the settings are wrong of course. You can post a screenshot of the settings you entered here.

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147866132-f644463f-d49b-4a2b-a2c4-5d340598662e.png)
![image](https://user-images.githubusercontent.com/96539207/147866133-822dd456-e723-46cf-93fb-c6aceeeaf7f8.png)
![image](https://user-images.githubusercontent.com/96539207/147866137-6d59abd4-9a0f-4df0-85d3-33d050606970.png)
![image](https://user-images.githubusercontent.com/96539207/147866146-2c357658-7d70-4151-b71c-65e6528c903e.png)
this is my setup for miner but when i run it. In Task Manager i can see the Miner ( but the CPU and GPU still normal )
Here my check on my laptop
![image](https://user-images.githubusercontent.com/96539207/147866180-d39b5f23-ddc8-4aa4-adcd-b6ddb3651e52.png)

**Comment by UnamSanctam** [comment]
Don't use "Install Rootkit" if you want to see it mining, you also can't see the miners GPU usage in the Task Manager, you have to use something like MSI Afterburner or something similar. You can also check the web panel you linked to see if it shows any mining hashrate.

**Comment by Duy0104** [comment]
I had check on msiburner and my nitro sense but it’s seems like doesn’t work. Both the pool and my webpanel doesn’t show the worker. But when i’m building it. It’s said “ has found watchdog payload... “ eventhough it was the first time i build on my PC or laptop. Do i need to do anything about the watchdog payload

**Comment by UnamSanctam** [comment]
No, but I would recommend that you change the "Startup" tabs "Filename" field from the default file path to something else.

**Comment by Duy0104** [comment]
It's still not working :(

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147867226-53801457-5223-4f49-a4f8-34a8197c0d48.png)
i found out it's still have a miner eventhough i had delete them

**Comment by UnamSanctam** [comment]
That doesn't look like the miner, go to the "Main" tab, press the "Save" button and then zip that file and post it here.

**Comment by Duy0104** [comment]
[ETH.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7798614/ETH.zip)
Here my miner

**Comment by UnamSanctam** [comment]
Here: [ETH2.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7798622/ETH2.zip) I changed the "Startup" tabs "Filename", load that file (inside the zip) by pressing the "Load" button, then build the miner and start it, then after a while (30 seconds maybe) start the checker.
,

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147867538-cdcc19e4-c733-4be2-9ef5-6c74bd340105.png)
And nothing happen sir

**Comment by UnamSanctam** [comment]
Here: [TEST.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7798632/TEST.zip), first try to run TEST1 that will not install ("Startup" is disabled) just to see if you can run it, if you can then uninstall it and then try TESTINSTALL.

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147867639-7189897f-7fac-49db-af0e-9cfa6a3b8db7.png)
The test1 return nothing
![image](https://user-images.githubusercontent.com/96539207/147867674-9daf6d9b-2d53-4b4d-a991-bb2317c6e068.png)
The testinstall too

**Comment by UnamSanctam** [comment]
And you have updated your graphics card drivers as a said above?

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147867710-77791722-a434-4f01-897d-bc3061132fec.png)
Here the Test1
![image](https://user-images.githubusercontent.com/96539207/147867764-d7cea6a9-b529-4179-9925-83c4d067a3d0.png)
Here Testinstall
Yes. I had update my card drivers

**Comment by UnamSanctam** [comment]
Try and XMR miner then: [XMR.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7798660/XMR.zip), could also be that svchost.exe (what you chose to inject the miner into) can't be injected into on your computer.

**Comment by Duy0104** [comment]
it worked 
![image](https://user-images.githubusercontent.com/96539207/147868069-5d71fe4d-1b21-4b89-8370-69d400fd4f42.png)

**Comment by UnamSanctam** [comment]
Then it's possible that you can't inject into svchost on your computer, I changed the settings in the one you sent to inject into explorer.exe here (and disabled "Startup"): [ETHexplorer.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7798665/ETHexplorer.zip) try running it and see if it runs, if it does run then svchost.exe was the problem.

**Comment by Duy0104** [comment]
> Then it's possible that you can't inject into svchost on your computer, I changed the settings in the one you sent to inject into explorer.exe here (and disabled "Startup"): [ETHexplorer.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7798665/ETHexplorer.zip) try running it and see if it runs, if it does run then svchost.exe was the problem.

But this doesn't work. So weird
![image](https://user-images.githubusercontent.com/96539207/147868252-356f80e7-8535-4e9e-b3b9-3ec334835ca8.png)

**Comment by UnamSanctam** [comment]
Then that sounds like a driver issue, what Nvidia driver version do you have?

**Comment by Duy0104** [comment]
it's 30.0.14.9729

**Comment by UnamSanctam** [comment]
Yeah then that should be fine, I have the same version and just ran that miner file on my RTX 2070 successfully. Can you open CMD and then run `ping asia2.ethermine.org` and then post here what it returns?

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147868374-5649bbcf-6150-412d-b9e5-05226f263aac.png)
Here

**Comment by UnamSanctam** [comment]
Yeah then the pool should probably work fine. It's possible that since you have a laptop the GPU gets disabled when no program in the Nvidia control panel list is running and thus there's no GPU to run it on but usually it will still be able to start fine, can you try extracting this [Test5.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7798683/Test5.zip) and running any of the `start test` bat files to see if a miner can run at all?

.

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147868519-f0e1ce41-1eb8-4c9e-92c2-ebd775fd6ea5.png)
i think it's because of my RAM
![image](https://user-images.githubusercontent.com/96539207/147868529-fc63cc4f-8efd-4049-90ec-ad5688583bff.png)
Here at phoenix miner

**Comment by UnamSanctam** [comment]
Yes it looks like it, though my miner shouldn't really fully exit if there's not enough VRAM, but I've seen it happen on laptops which in this case would be correct.

**Comment by Duy0104** [comment]
Imma try on PC. If it works i will reply this. Thanks you alot for helping me

**Comment by Duy0104** [comment]
Guess what Uman xD. It's because my laptop doesn't have enough RAM. But on PC it works perfectly xD. Thanks you, when i'm rich i won't forget u lol

**Comment by NeGoblin1** [comment]
Hi, I do not work eth miner, but it works monero. I have a computer. 16 gigs of RAM, a 1070 8 gigs video card, and an I5 processor. here is my config
[CFG.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/10338356/CFG.zip)

English is not my native language, so there may be errors

**Comment by UnamSanctam** [comment]
>Hi, I do not work eth miner, but it works monero. I have a computer. 16 gigs of RAM, a 1070 8 gigs video card, and an I5 processor. here is my config
[CFG.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/10338356/CFG.zip)
I'm asking for help because I don't know what the problem is.
English is not my native language, so there may be errors

You mean that it's not using 20% (your current setting) if you check in something like MSI Afterburner? Try putting it to 50% (to make it easier to see) and then check the GPU usage in MSI Afterburner.

**Comment by NeGoblin1** [comment]
The virus loads the video card 100% but no hash rate. I checked if I entered the wallet Eth correctly. Here's my modified config
[CFG.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/10338655/CFG.zip)

**Comment by UnamSanctam** [comment]
>The virus loads the video card 100% but no hash rate. I checked if I entered the wallet Eth correctly. Here's my modified config
[CFG.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/10338655/CFG.zip)

Well I can see in the pool that you found shares 3 minutes ago, when it's using 100% then it's mining correctly, you just need to find a share before it will appear in the pool.

**Comment by NeGoblin1** [comment]
I ran NBMiner with the same pool and purse to check whether the pool works at all

**Comment by UnamSanctam** [comment]
You use the same worker name for both?
