### ISSUE TITLE
What are the necessary requirements for connecting to the Web Panel?

### ISSUE THREAD

**Issue by Alcinzal** [UnamSanctam/SilentCryptoMiner#2144]
I got very confused while testing the miner on different versions of windows, because everything, except connecting to the web panel, worked. It connected to the pool, it started mining, the checker file told me everything was working well. But it did not want to connect to the web panel. However, after installing Visual Studio it actually managed to connect to the web panel, which means it needs a dependency or requirement? Do you know which one?

**Comment by Alcinzal** [comment]
Alright I figured it out. [vc_redist](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) is required. If you have the executable you can install it like this from cmd:
`vc_redist.x64.exe /install /quiet /norestart`
And to check if it already exists on the system you can check if one of these keys exist:
64-bit
`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64`
32-bit
`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x86`

However I assume 32-bit is not necessary because the miner only works on 64 bit right?

**Comment by UnamSanctam** [comment]
Visual Studio redistributable should never be required, unless there's something specifically "wrong" with that computer.

**Comment by Alcinzal** [comment]
So far I have tried with 4 fresh installs of windows inside a VM (QEMU/KVM), 2 of Win11 and 2 of Win10, all different iso files. Everything about the miner works except for the connection to the web panel, however when I install vc_redist, then the miner successfully connects. Are you sure that the way the miners connect to the web panel does not require anything from the redistributable?

**Comment by Alcinzal** [comment]
Nevermind. I am extremely confused. If I do a fresh install of windows and the first program I open is the miner, 90% of the time it does not want to connect to the web panel (everything else works though), however whenever I download anything else, like a browser, or visual studio, or epic games, literally anything, it works... most of the time? I really am puzzled. At first I thought it was maybe that windows works on something in the background, and it just takes time for the OS to finalize and then allow the miner to send and receive web requests, but I left the miner on idle for 30 minutes, and it did not want to connect, however the second I installed "winmerge" (I simply wanted to compare a few folders) it connected to the webpanel instantly!

But anyways, assuming the people that install this miner have other programs on their computer, it should work.
