### ISSUE TITLE
Remote config and uninstaller issue

### ISSUE THREAD

**Issue by toxic4a** [UnamSanctam/SilentCryptoMiner#2157]
Is everything ok with this remote config :  ``` https://rentry.co/v6y68mcp/raw ```
NOTE : The uninstaller doesn't completely remove the installation folder from programdata, only the watchdog & miner process is killed and the service removed.

**Comment by UnamSanctam** [comment]
Yes that configuration is correct. And yes the uninstaller doesn't remove any base folders.
