### ISSUE TITLE
RDP/VPS provider reccomendation for xmrig proxy?

### ISSUE THREAD

**Issue by SkidSkid08** [UnamSanctam/SilentCryptoMiner#2164]
Hi Unam what RDP/VPS provider do you reccomend for xmrig proxy
due to the problem of miners disconnecting from pool

im considering https://crazyrdp.com/
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/121647725/64589c87-9693-4d2f-8482-68d62a930cee)

**Comment by UnamSanctam** [comment]
I'm not sure, I always host things myself so I haven't tried any VPS/RDP providers. You will probably have to test it out, some people have reported their CrazyRPD getting taken down but that was with the web panel and not an xmrig-proxy. If you enter a normal pool through the builder, and then enter your xmrig-proxy IP and port through the "Remote Configuration" then you can always change it later if something happens.

**Comment by SkidSkid08** [comment]
Ok thanks i will do that, btw what linux OS is the best for xmrig proxy

**Comment by UnamSanctam** [comment]
Any will work really, most use Ubuntu since it's one of easiest to work with.

**Comment by SkidSkid08** [comment]
Hi im done setting up the proxy and its working
I just installed the release and ran this:
./xmrig-proxy -o de.zephyr.herominers.com:1123 -b (**my ip**):(**port**) -m nicehash -u (**my address**) -p MYRIG -a randomx -k

Will my slaves still use the SilentCryptoMiner settings such as CPU % or will the proxy change it? also for difficulty they still use the pools VarDiff

**Comment by UnamSanctam** [comment]
Yes the proxy will only be for the pool settings, the other settings (like CPU usage) will still be controlled by the miner.
