### ISSUE TITLE
Hashrate high but share count decrease with proxy

### ISSUE THREAD

**Issue by SkidSkid08** [UnamSanctam/SilentCryptoMiner#2168]
Hi, after setting up proxy my hashrate has increased but i am getting less shares, is this normal? will it affect my earnings

**Comment by UnamSanctam** [comment]
Yes it's normal, the amount of shares depends on the share difficulty, so 100 shares at a difficulty of 100 is the same as 1 share at a difficulty of 10000.

**Comment by SkidSkid08** [comment]
Understood, thanks

**Comment by UnamSanctam** [comment]
>Hi, how do you set up a proxy? Trough a web panel or configuration code somehow?
I haven't seen a proxy option inside this miner
Thanks

xmrig-proxy can be found here: https://github.com/xmrig/xmrig-proxy, you can host that somewhere to act as a proxy between the pool and the miners.
