### ISSUE TITLE
Need help uninstalling

### ISSUE THREAD

**Issue by GustavoCodesAgain** [UnamSanctam/SilentCryptoMiner#217]
Hello, i tested a new config with the miner in a computer, everything works great, but i cannot uninstall it, i cannot find the rootkit service to delete it and the uninstaller doesn't work. I have the stealth enabled.

**Comment by UnamSanctam** [comment]
How do you know the uninstaller doesn't work? What are you checking? But you can uninstall it manually as well by first running the rootkit uninstaller https://github.com/UnamSanctam/SilentCryptoMiner/raw/master/SilentCryptoMiner/Resources/rootkit-u.zip and then following: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner

**Comment by GustavoCodesAgain** [comment]
thank you!

**Comment by GustavoCodesAgain** [comment]
![image](https://user-images.githubusercontent.com/84887837/147968372-6a4fb62d-6584-4a55-97f9-c03ec1302792.png)
im runnning the uninstaller but it doesn't uninstall it

**Comment by UnamSanctam** [comment]
It doesn't remove the miner if that's what you mean, it only uninstalls it.

**Comment by GustavoCodesAgain** [comment]
I understand, but isn't uninstalling it
![image](https://user-images.githubusercontent.com/84887837/147968653-8781d265-172f-4876-bf32-a77666d3377c.png)

and i still can see the conhost.exe
![image](https://user-images.githubusercontent.com/84887837/147969042-fdb5ccfa-2484-4dbf-ba27-51d8a914908e.png)

even when i tried to kill it multiple times

**Comment by UnamSanctam** [comment]
The web panel endpoint can't know if it's uninstalled so how it does it is that will say "Offline" if the miner hasn't contacted the endpoint for 5 minutes.

Conhost.exe is a real Windows program so make sure that it's actually the miner you're checking/killing and not just the normal Windows process.
