### ISSUE TITLE
Getting many login errors in proxy

### ISSUE THREAD

**Issue by SkidSkid08** [UnamSanctam/SilentCryptoMiner#2170]
Hi Unam, I stumbled upon debug mode for xmrig-proxy by pressing d and its showing many login errors like this
![Screenshot 2024-02-13 09 17 03](https://github.com/UnamSanctam/SilentCryptoMiner/assets/121647725/637267fe-ff2b-405c-8491-ca98784a0b79)
What is the reason for this

**Comment by SkidSkid08** [comment]
It seems to be a pool side error i switched pools and that error stopped

**Comment by SkidSkid08** [comment]
nvm its started happening again

**Comment by UnamSanctam** [comment]
It normally happens with xmrig-proxy, even with the normal xmrig). I don't think anyone knows the reason.
