### ISSUE TITLE
Miner just disappears from taskmanager and no CPU usage shown 

### ISSUE THREAD

**Issue by Stuntah14** [UnamSanctam/SilentCryptoMiner#218]
When I run the miner for CPU mining, it will show up on task manager under the disguised program and it will make the usage go up but then 5 seconds later it disappears and the usage goes back down. Antiviruses are all off and I even tried on virtual machines and changed settings but same thing happens.

**Comment by UnamSanctam** [comment]
And "Stealth" is disabled? What does it say when you run the checker?

**Comment by Stuntah14** [comment]
Yes stealth is disabled, when I run the checker it says watchdog running and shows the information correctly under miner section

**Comment by UnamSanctam** [comment]
Can you post what the checker returns?

**Comment by Stuntah14** [comment]
![unknown](https://user-images.githubusercontent.com/96040517/147900349-7178c6a5-f7cd-4b8f-9ca9-8e5ad340526a.png)

**Comment by Stuntah14** [comment]
![image](https://user-images.githubusercontent.com/96040517/147900383-d1f5ded1-2785-4bac-a63a-5072812f46f8.png)

This just popped up on taskmanager, I think it is the miner but it hasn't appeared until now so I will quickly inspect anything I did different this time

**Comment by UnamSanctam** [comment]
Yes that looks like the miner, the settings in the checker look correct as well.
