### ISSUE TITLE
ETH and miner name not working on web panel

### ISSUE THREAD

**Issue by Mezekk** [UnamSanctam/SilentCryptoMiner#219]
I started the miner on a PC and when i access the web panel i can see it mining xmr at about 700 G/s, but i can't see it mining ETH even tho the PC has a GPU.

Other problem is that i can't see the miner name, where on the setup i put {COMPUTERNAME}

**Comment by Mezekk** [comment]
I'll leave you here the miners so you can tell me if i did something wrong
[miners.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7801959/miners.zip)
.

**Comment by Mezekk** [comment]
@UnamSanctam 🐱‍👤

**Comment by UnamSanctam** [comment]
What GPU does the computer have? And for the worker name ({COMPUTERNAME}) you put it in the wrong location, nanopool does not use the password field. You should put it in the "Wallet Address" field in this format `WalletAddress.WorkerName`

**Comment by Mezekk** [comment]
his GPU is called Microsoft Hyper-V Video.
For modifying the {COMPUTERNAME} location do i have to setup the whole thing again?

**Comment by UnamSanctam** [comment]
That's not a real GPU but just what it says when you host a VM (Virtual Machine) in Hyper-V so that's why it does not start the ETH miner. And yes you'd either have to setup it again or change the configuration with the web panel or "Remote Configuration".

**Comment by Mezekk** [comment]
ok thanks
