### ISSUE TITLE
Windows Defender stops the built miner executable

### ISSUE THREAD

**Issue by realsyssel** [UnamSanctam/SilentCryptoMiner#2190]
I am sorry, but I want to ask you for help. The file gets marked when getting downloaded, and the WD just deletes it from the downloads folder. How can I prevent this?

**Comment by realsyssel** [comment]
How do I add an exclusion before the miner is downloaded on an another computer then? Wouldn't I need a separate program that first adds an exclusion and then downloads the miner?

**Comment by jimchrist-x** [comment]
The only solution to this would be to try to lower the detections as mentioned in the FAQ. Initially, I thought you wanted to install the tool itself.

**Comment by realsyssel** [comment]
Yea I noticed lol, that's why I changed the title. Sorry for that, could you help me out and point me in the right direction. I read the FAQ section but still feel lost.

**Comment by jimchrist-x** [comment]
I don't think there is anything else to add. I believe, the steps mentioned in the FAQ are pretty self explanatory.

**Comment by realsyssel** [comment]
Yea I figured it out, I wrote a program that adds exclusions to the computer and then downloads the miner from a URL. So there is no detections now.

**Comment by sea256** [comment]
> Yea I figured it out, I wrote a program that adds exclusions to the computer and then downloads the miner from a URL. So there are no detections now.

hey I was using this technique too but a few days ago windows started asking for additional uac 
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/165706984/7ec90997-5b0f-48a4-8e31-fab2a8f7a1c3)
Do you have this kind of issue?

**Comment by sea256** [comment]
btw app has admin rights

**Comment by UnamSanctam** [comment]
Hmm I don't think they've added something like that yet, are you sure you didn't have the Windows Defender app open when testing? Since then it can ask for things like that.
