### ISSUE TITLE
connect error: operation cancelled when using proxy

### ISSUE THREAD

**Issue by SkidSkid08** [UnamSanctam/SilentCryptoMiner#2193]
Hi Unam, this happened to me twice today
![Screenshot 2024-02-19 12 28 57](https://github.com/UnamSanctam/SilentCryptoMiner/assets/121647725/9069da83-7619-49ca-a934-47c1320d749c)

it results in a burst of invalid shares when they connect again

**Comment by UnamSanctam** [comment]
As you said it means that you lost connection to the pool, which results in some invalid shares when it connects (since it's probably the wrong job at that point).

**Comment by SkidSkid08** [comment]
What can cause me to lose connection is it problem from pool side or proxy side

**Comment by UnamSanctam** [comment]
It can be either one, it's quite difficult to diagnose.
