### ISSUE TITLE
Suggestion - Warn people when feature requires Administrator but have not enabled Run As Administrator

### ISSUE THREAD

**Issue by suckma420** [UnamSanctam/SilentCryptoMiner#22]
This would be very helpful to people new to the miner or who haven't read the wiki.

**Comment by UnamSanctam** [comment]
Sure that's possible I guess.

**Comment by Toxenskiy** [comment]
if I'm not mistaken next to such functions, the elevated rights icon is

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/141128971-f090df49-1901-422a-9f07-dc361c308c14.png)
