### ISSUE TITLE
hello unam

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#2200]
its possible to create exe file with out fill this form Miners and make it EMpty and just go give Remote Configuration Only and the Host API ?? it should work ?? or there will be any problem because i face always problems when i switch from pool  to another pool some miners stuck in old pool so this solation it will be good for this ?

**Comment by UnamSanctam** [comment]
Not really, but if some miners stay in the old pool then it means that they weren't able to connect to the new pool so they temporarily go to the backup pool until they try again the next time.
