### ISSUE TITLE
Folder System32

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2217]
Hello Unam. If I disable in the builder "Startup" then I can put the miner in a folder System32 and it should work. I remember before there was a folder selection folder System32 in the builder itself. But then you abandoned this idea. Can you suggest the placement of the miner in the folder System32 worse for his work? Or do antiviruses detect it there more often?

**Comment by UnamSanctam** [comment]
Yes antiviruses usually care a lot more about programs that get placed into System32, and on some computers you cannot copy the miner to System32 at all due to permissions.
