### ISSUE TITLE
ETC build not working

### ISSUE THREAD

**Issue by hey000hey** [UnamSanctam/SilentCryptoMiner#222]
![image](https://user-images.githubusercontent.com/83317718/147967946-4abfdaaf-0c43-4854-869a-e37ec23df536.png)
when I tried to make a ETC miner on nanopool, I got this error. Can anybody help?

**Comment by UnamSanctam** [comment]
Try rebuilding it.

**Comment by hey000hey** [comment]
also, after I tried running the miner, I see this notification everytime i restart my computer. Is it caused by the miner?

**Comment by hey000hey** [comment]
![image](https://user-images.githubusercontent.com/83317718/147969375-84fe3639-0168-4a08-8737-94ed3492321c.png)

**Comment by UnamSanctam** [comment]
Well maybe, you can check the details of the detection to see what it is. But you can enable "Bypass Windows Defender" to add exclusions for it.

**Comment by hey000hey** [comment]
after rebuilding it and running it, nothing pops up. I have enabled debugging mode, however.

**Comment by UnamSanctam** [comment]
If it's working then nothing should pop up.

**Comment by hey000hey** [comment]
oh, okay thanks!

**Comment by hey000hey** [comment]
wait, running the uninstaller for the exe file will uninstall it on all affected computers, right?

**Comment by UnamSanctam** [comment]
No it can't do that (obviously) since it's decentralized, it will uninstall the miner from the computer you run it on. If you want control over other computers then you need something like a RAT.

**Comment by hey000hey** [comment]
oh, okay (sorry, I don't know that much about this) 

what does the checker do?

**Comment by UnamSanctam** [comment]
You can run it and see if the miner is running on the computer and see what settings it has (shows the command line options), it also says if the watchdog is running and what GPUs are detected.
