### ISSUE TITLE
Cant download the SilentCryptoMiner v3.4.0

### ISSUE THREAD

**Issue by Tamshi27** [UnamSanctam/SilentCryptoMiner#2221]
So i wanted to download the Pre-Compiled SilentCryptoMiner v3.4.0 but chrome detect it as a virus and dont allow me to keep the file, tried it with edge too but same problem

**Comment by UnamSanctam** [comment]
You can allow it on the downloads page, if what's removing it is actually Windows Defender then you can add an exclusion to the folder that you're downloading it into. And Edge is Chromium so it will act similarly.
