### ISSUE TITLE
The program does not mine XMR when it is not connected to a webpanel

### ISSUE THREAD

**Issue by delphoir** [UnamSanctam/SilentCryptoMiner#2222]
Hello. Whether if I connect or do not connect it to my webpanel website in builder exe, the miner does not mine on pool if I shutdown my webpanel. How do I solve this? I can see the hashrate on xmr pool an I can see that the miner on my computer is active and it looks like it's mining but actually it isn't mining. So when I close my webpanel the miner does not exactly mine (I guess) and when I reopen the webpanel, it actully mines without a problem. I want to mine without a website. How do I do that, dear Unam

**Comment by UnamSanctam** [comment]
Whether you have a web panel or not doesn't make a difference since the miner only sends some information to it and nothing more, though it could make a difference if you're using a different configuration in the web panel.

**Comment by delphoir** [comment]
I made a test yesterday, closed my webpanel and left my PC open for the entire day, and sometimes checked the monero pool. In total I mined literally zero XMR with 900 H/s. Today I reopened my webpanel and I mined 0.00006 XMR for each hour without a problem. I did not changed much things in configuration. What do you think about this? because I'm almost sure that somehow it does not work when I close my webpanel

**Comment by UnamSanctam** [comment]
Does it show any shares submitted on the pool, i.e any hashrate?

**Comment by delphoir** [comment]
Yes, yesterday (also today) the pool was showing hashrate and submitted shares. almost every hour it was updating

**Comment by UnamSanctam** [comment]
And does it show any hashrate (submitted shares) when the web panel is offline?

**Comment by delphoir** [comment]
yes, it does. No matter what if it is offline or online

**Comment by UnamSanctam** [comment]
Alright then it's mining, the hashrate (submitted shares) on the pool is everything that's used to reward you on the pool, so if you have that then it's working.

**Comment by delphoir** [comment]
Just for the record: It was definitely about system clock being out of sync. It is now minig without a problem and it's showing recently mined XMR amount in pool without a problem.
