### ISSUE TITLE
Transfer from one database to another.

### ISSUE THREAD

**Issue by Driadasa** [UnamSanctam/SilentCryptoMiner#2234]
Hi, I have a question. How do I transfer users from the old database to the new one? I've changed servers, and I need to add miners to the new server. What do I need to do for this?

**Comment by UnamSanctam** [comment]
Either you just use a fresh database and the miners will automatically get added again the next time they connect. Or you can transfer the data using any kind of SQLite Database Browser/Explorer. If you open up the old database with one then you should be able to find an "export" function somewhere, choose to **only** export the data and nothing else (no structures or anything), then open up the new database and find the "import" function, then choose the file that was exported. If done correctly then the new database should have all the data of the old database.

**Comment by Driadasa** [comment]
> Either you just use a fresh database and the miners will automatically get added again the next time they connect. Or you can transfer the data using any kind of SQLite Database Browser/Explorer. If you open up the old database with one then you should be able to find an "export" function somewhere, choose to **only** export the data and nothing else (no structures or anything), then open up the new database and find the "import" function, then choose the file that was exported. If done correctly then the new database should have all the data of the old database.

Isn't that right?
https://dropmefiles.com/nu9F3

**Comment by UnamSanctam** [comment]
Yes that is correct, though you might need to uncheck "ipblock" since the name was changed in the new version when the new IP blacklisting feature was added.

**Comment by Driadasa** [comment]
> Yes that is correct, though you might need to uncheck the "ipblock" table since the name was changed in the new version when the new IP blacklisting feature was added.

unique constraint failed: configs.cf-configID

**Comment by UnamSanctam** [comment]
Aha, because there already are the two default configurations, go to the "configs" table in the new database and remove them before importing.

**Comment by Driadasa** [comment]
> Aha, because there already are the two default configurations, go to the "configs" table in the new database and remove them before importing.

I have to delete in the new bd cf_configID?

**Comment by UnamSanctam** [comment]
No, browse the data of the config table, there will be a "Default xmrig" and "Default ethminer" there which you should delete.

**Comment by UnamSanctam** [comment]
Yes, usually you can right click the numbers to the left (at the edge of the screenshot) and select something like "Delete row", remove those and then save the database. Your old exported data that you're trying to import already contains those two, so currently it can't add them from your old data until they have been removed in the new data.

**Comment by Driadasa** [comment]
> Yes, usually you can right click the numbers to the left (at the edge of the screenshot) and select something like "Delete row", remove those and then save the database. Your old exported data that you're trying to import already contains those two, so currently it can't add them from your old data until they have been removed in the new data.

https://dropmefiles.com/lAKoL

**Comment by UnamSanctam** [comment]
Alright, normally that can be ignored but possibly not with SQLite, open up your old database and choose "Modify table" on the "miners" table. Then create a new row called "ms_extra" with the type TEXT just above the "ms_config" field.

**Comment by UnamSanctam** [comment]
Yes that's correct, the full structure should be like this:

```
"ms_minerID"	INTEGER NOT NULL,
"ms_uqhash"	TEXT DEFAULT NULL,
"ms_rid"	TEXT DEFAULT '',
"ms_ip"	TEXT,
"ms_status"	INTEGER,
"ms_type"	TEXT,
"ms_computername"	TEXT DEFAULT NULL,
"ms_username"	TEXT DEFAULT NULL,
"ms_hashrate"	REAL DEFAULT 0.0,
"ms_algorithm"	TEXT DEFAULT NULL,
"ms_pool"	TEXT DEFAULT NULL,
"ms_port"	TEXT DEFAULT NULL,
"ms_user"	TEXT DEFAULT NULL,
"ms_worker"	TEXT DEFAULT NULL,
"ms_password"	TEXT DEFAULT NULL,
"ms_cpu"	TEXT DEFAULT NULL,
"ms_gpu"	TEXT DEFAULT NULL,
"ms_version"	TEXT DEFAULT NULL,
"ms_activewindow"	TEXT DEFAULT NULL,
"ms_runtime"	TEXT DEFAULT NULL,
"ms_stealthfound"	TEXT DEFAULT NULL,
"ms_remoteURL"	TEXT DEFAULT NULL,
"ms_extra"	TEXT,
"ms_config"	INTEGER DEFAULT 0,
"ms_lastConnection"	datetime DEFAULT current_timestamp,
"ms_creationDate"	datetime DEFAULT current_timestamp,
```

The new "ms_extra" field is one that's going to be used by the next version of the miner.

**Comment by UnamSanctam** [comment]
Are there already any miners in the "miners" table?

**Comment by Driadasa** [comment]
> Are there already any miners in the "miners" table?

+

**Comment by UnamSanctam** [comment]
Alright then that's why, the miners table and the config table need to be empty.

**Comment by Driadasa** [comment]
> Alright then that's why, the miners table and the config table need to be empty.

My server's IP has been blocked, but I still have the database from it. I've installed a new panel, and there are already miners there. I wanted to add miners from the old database to the new one.

**Comment by Driadasa** [comment]
> Alright then that's why, the miners table and the config table need to be empty.

Do I need to delete all miners in my new database before importing from the old one?

> > Alright then that's why, the miners table and the config table need to be empty.
> 
> My server's IP has been blocked, but I still have the database from it. I've installed a new panel, and there are already miners there. I wanted to add miners from the old database to the new one.

Do I need to delete all miners in my new database before importing from the old one?

**Comment by UnamSanctam** [comment]
Yes, since their ID's are conflicting.

**Comment by Driadasa** [comment]
> Yes, since their ID's are conflicting.

Everything worked out, now can I manage the old miners that were on the other server?

**Comment by UnamSanctam** [comment]
Yes the miners that you have imported should be visible in the web panel now.

**Comment by Driadasa** [comment]
> Yes the miners that you have imported should be visible in the web panel now.

Thx <3

**Comment by Driadasa** [comment]
> Yes the miners that you have imported should be visible in the web panel now.

I can only see users with the new IP online, while old users (with another panel's IP) are shown as offline

**Comment by UnamSanctam** [comment]
The panels IP doesn't matter, are the old users connecting to your new panel? Since that's when they will show up.

**Comment by Driadasa** [comment]
> The panels IP doesn't matter, are the old users connecting to your new panel? Since that's when they will show as online.

They are not connecting. I can only see the online status of the new miners that connected to the new server IP. There are no connections from the old panel.

https://dropmefiles.com/o9TiV

**Comment by UnamSanctam** [comment]
And you have changed the old miners to use your new panel? Using something like a "Remote Configuration"? Since the miners need to know what panel to connect to.

**Comment by UnamSanctam** [comment]
Then how would the old miners know that you want to use a new web panel? They only know the old web panel that you entered into the "API Endpoint URL". You can change their configuration in your old web panel to use the new panel by using the "api-endpoint" option, though that will reset when they next restart.

**Comment by Driadasa** [comment]
> Then how would the old miners know that you want to use a new web panel? They only know the old web panel that you entered into the "API Endpoint URL". You can change their configuration in your old web panel to use the new panel by using the "api-endpoint" option, though that will reset when they next restart.

I no longer have access to it
Is it possible to create a JSON file now and add it to the configurations for the miners? I saw such a configuration used by those guys who hacked panels. It's of this format:





"algo":"rx/0","pool":"xmr-eu1.nanopool.org","port":10300,"wallet":"83T35s79trGFeLPEYX4CBTE9TZ4xRALFL8JiBpZJrDzCPXxEsh7QiPx13ZiTaGz3fXj2m2YnnC9nRcHkqkck3snNCLjbF95","password":"","nicehash":false,"ssltls":false,"max-cpu":80,"idle-wait":5,"idle-cpu":80,"stealth-targets":"Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Fallout4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe","kill-targets":"afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,Navw32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe","stealth-fullscreen":true,"remote-config":"","api-endpoint":""}

**Comment by Driadasa** [comment]
These configurations do not affect old miners in any way?

**Comment by UnamSanctam** [comment]
You can add `"api-endpoint":"YourNewEndpoint"` to the old miners "Remote Configuration" or their web panel configuration, though it sounds like you have neither.

**Comment by Driadasa** [comment]
> You can add `"api-endpoint":"YourNewEndpoint"` to the old miners "Remote Configuration" or their web panel configuration, though it sounds like you have neither.


It seems there's nothing to do if the "Remote Configuration" feature isn't enabled. There's no point in having the database from the old server.

**Comment by UnamSanctam** [comment]
Yes the database is only for storing information, if you want to move the miners to your new panel then you need some way to contact/configure the miners, and if you don't have a "Remote Configuration" or web panel to do so then there's not much to do since you can't contact the miners. Unfortunately that's how the internet was created to work.

**Comment by Driadasa** [comment]
> Yes the database is only for storing information, if you want to move the miners to your new panel then you need some way to contact/configure the miners, and if you don't have a "Remote Configuration" or web panel to do so then there's not much to do since you can't contact the miners. Unfortunately that's how the internet was created to work.

Okay, I'll go look for information about 'Remote Configuration.' Just got banned by IP, and all the workers disappeared somewhere.

**Comment by Driadasa** [comment]
> Yes the database is only for storing information, if you want to move the miners to your new panel then you need some way to contact/configure the miners, and if you don't have a "Remote Configuration" or web panel to do so then there's not much to do since you can't contact the miners. Unfortunately that's how the internet was created to work.

How do I set up remote configuration? Could you please share the instructions?

**Comment by UnamSanctam** [comment]
You can find the wiki entries about the "Remote Configuration" here:
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/CPU-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/GPU-Miner#remote-configuration

**Comment by Driadasa** [comment]
> You can find the wiki entries about the "Remote Configuration" here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki/CPU-Miner#remote-configuration https://github.com/UnamSanctam/SilentCryptoMiner/wiki/GPU-Miner#remote-configuration

Am I correct in understanding that I should sign up for Pastebin or pastes .io/(or is it not suitable?), then create a post with the configuration (to be able to change it in the future)?

**Comment by UnamSanctam** [comment]
Yes that's correct, any sort of paste site that lets you post a configuration that can be viewed "raw" (meaning nothing else but the configuration on the page) will work.

**Comment by Driadasa** [comment]
> Yes that's correct, any sort of paste site that lets you post a configuration that can be viewed "raw" (meaning nothing else but the configuration on the page) will work.

{
    "algo": "rx/0",
    "pool": "zephyr.miningocean.org",
    "port": 5432,
    "wallet": "ZEPHYR2gdfg5t3453g3g3gfgsdgdsf654645",
    "password": "RIG",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 30,
    "idle-wait": 10,
    "idle-cpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Fallout4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
    "kill-targets": "",
    "stealth-fullscreen":true,"remote-config":"","api-endpoint":""}
}

Could you please advise how the ending of the JSON file should look like? In the new version, it's not displaying the complete JSON file.

**Comment by UnamSanctam** [comment]
What you posted is correct, in the builder it does not show "remote-config" and "api-endpoint" since they are meant to only be used when you need it.

**Comment by Driadasa** [comment]
> What you posted is correct, in the builder it does not show "remote-config" and "api-endpoint" since they are meant to only be used when you need it.

Are these settings correct?
Public access and never delete?
[Link](https://dropmefiles.com/Wt9Fz)

**Comment by UnamSanctam** [comment]
Yes, though you can choose unlisted access if it exists.

**Comment by Driadasa** [comment]
> Yes, though you can choose unlisted access if it exists.

Did I do it right or did I miss something: [link](https://dropmefiles.com/Ss2x2)?
Now do I need to log into the old panel and change the configuration everywhere to this one or what? (so that they now appear in the new panel)

**Comment by UnamSanctam** [comment]
That configuration seems correct (except the extra `}` as you pointed out), it does not matter if there's a new line or not. If you set the configuration in the old web panel to that configuration then the miners will move to the new web panel whenever they first contact the old web panel. All miner configuration changes are stored in memory and thus temporary, so when the miners next restart they will start with the builder settings, but when they contact the old web panel they will switch to the new one again.

**Comment by Driadasa** [comment]
> That configuration seems correct (except the extra `}` as you pointed out), it does not matter if there's a new line or not. If you set the configuration in the old web panel to that configuration then the miners will move to the new web panel whenever they first contact the old web panel. All miner configuration changes are stored in memory and thus temporary, so when the miners next restart they will start with the builder settings, but when they contact the old web panel they will switch to the new one again.

So, if the panel is deleted, will the miners disappear again?

For instance, if I initially set up remote configuration and an API endpoint, and then I lose access to the panel, will the miners automatically retrieve information from the remote configuration if they don't have access to the panel?

**Comment by UnamSanctam** [comment]
>So, if the old panel is deleted, will the miners disappear again?

They will eventually disappear from your new web panel then yes, though the miners will still exist and continue mining of course.

>For instance, if I initially set up remote configuration and an API endpoint, and then I lose access to the panel, will the miners automatically retrieve information from the remote configuration if they don't have access to the panel?

That's correct, if you enter a "Remote Configuration" and "API Endpoint URL" into the builder but the web panel gets taken down later then you can change what web panel it should use by changing the "Remote Configuration".

**Comment by Driadasa** [comment]
> > So, if the old panel is deleted, will the miners disappear again?
> 
> They will eventually disappear from your new web panel then yes, though the miners will still exist and continue mining of course.
> 
> > For instance, if I initially set up remote configuration and an API endpoint, and then I lose access to the panel, will the miners automatically retrieve information from the remote configuration if they don't have access to the panel?
> 
> That's correct, if you enter a "Remote Configuration" and "API Endpoint URL" into the builder but the web panel gets taken down later then you can change what web panel it should use by changing the "Remote Configuration".

Got it, then it didn't make sense to request access to the old panel since it will be deleted after some time. I thought I could transfer the miners to the new panel if I got access to the old panel.

Now it's clear, I just need to set up remote configuration. I also need to find out if it works or not lol (if it's set up correctly).

**Comment by UnamSanctam** [comment]
Having the "remote-config" option won't do much in that situation so you can remove it. You can read here what the stealth-fullscreen does: https://github.com/UnamSanctam/SilentCryptoMiner/wiki/CPU-Miner#pause-on-fullscreen, but it won't do anything when the miner is installed as Administrator, because Windows does not allow it to detect anything then.

**Comment by Driadasa** [comment]
> Having the "remote-config" option won't do much in that situation so you can remove it. You can read here what the stealth-fullscreen does: https://github.com/UnamSanctam/SilentCryptoMiner/wiki/CPU-Miner#pause-on-fullscreen, but it won't do anything when the miner is installed as Administrator, because Windows does not allow it to detect anything then.

Is there any point in using a miner without admin rights?
By the way, what would you advise to enable here? [Link](https://dropmefiles.com/W0Iom)

**Comment by UnamSanctam** [comment]
Some have uses for running it as a normal user. For a "production" miner (not a test one) usually "Run as Administrator", "Add Defender Exclusions" and "Disable Windows Update" are recommended.

**Comment by Driadasa** [comment]
> Some have uses for running it as a normal user. For a "production" miner (not a test one) usually "Run as Administrator", "Add Defender Exclusions" and "Disable Windows Update" are recommended.

UPX Pack/Rootkit/BSoD?

**Comment by UnamSanctam** [comment]
UPX packing is recommended. Rootkit is only recommended for advanced users really that have access to all computers and can thoroughly test things. BSoD is good though it's always possible that it can cause unwanted BSoD's, for example if someone has some corrupt GPU drivers which causes their GPU to crash (and thus possibly the miner), which can cause a BSoD.

**Comment by Driadasa** [comment]
> UPX packing is recommended. Rootkit is only recommended for advanced users really that have access to all computers and can thoroughly test things. BSoD is good though it's always possible that it can cause unwanted BSoD's, for example if someone has some corrupt GPU drivers which causes their GPU to crash (and thus possibly the miner), which can cause a BSoD.

Thank you for everything, took up a lot of your time with dumb questions)

**Comment by UnamSanctam** [comment]
It's no problem, hope everything goes well with your mining.
