### ISSUE TITLE
Operating system Ubuntu 22.04

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2248]
Hello Unam. I decided to fully learn how to use the operating system on Ubuntu. Today I bought a test server and decided to set everything up on it from the very beginning. Configured Xmig Proxy to work. Based on all the tips on the Internet, I made a list of what I did. I configured both the graphical interface and remote connection and tcp connections.
1. sudo apt-get update
2. sudo apt-get upgrade
3. sudo apt install ubuntu-desktop
4. sudo apt install lightdm
5. sudo service lightdm start
6. sudo ufw allow 3389
7. sudo apt install xrdp
8. sudo systemctl enable xrdp
9. sudo apt install xfce4
10. sudo systemctl start xrdp
11. sysctl -w net.ipv4.tcp_max_syn_backlog=50000
In the end, I was surprised when I was able to connect to the server and saw the graphical interface. I even launched Xmrig Proxy there and connected not most of the workers there, they seem to connect.
What do I want to know from you? Did I miss anything important in the completed list that affects the operation of the server?
Test server characteristics:
RAM - 4 Gb
CPU - 3 Core
SSD - 50 Gb
Why did I write the characteristics, the graphical interface is very slow, is it that there is not enough power?
And based on your experience, advise what characteristics will be sufficient for using Xmrig Proxy so that the server does not slow down. And does it matter which country's IP address to use?

**Comment by UnamSanctam** [comment]
That all looks fine, for the slowness I would guess that either your xfce4 is slow or possibly something with xrdp. Those server specifications should be more than good enough for 20 000 miners (might temporarily be slow whenever they first all connect at once when you restart but that's not a problem).

**Comment by masterjek** [comment]
Unam, that Ubuntu server that you set up, now in their data center the power has turned off and the server has completely shut down. I had to move all the workers to this test server that I was setting up. And for some reason I see that not all the workers switched to the new server. I have two assumptions, it takes time for them to switch or I incorrectly discovered the number of tcp ip. Is there a reliable way to exclude tcp ip?

![2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/2d38655a-4865-4d81-b37f-5ad9bf02cab9)

**Comment by UnamSanctam** [comment]
Changing the sysctl and /etc/security/limits.conf (and enabling pam_limits) should be enough.

**Comment by masterjek** [comment]
I haven't changed the values on the server yet. I took screenshots, so I can ask since these are the correct changes in the screenshots?

![1](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/70362d2b-52f6-4d6f-a51b-60d9daf52d76)

![2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/c1fc5442-b292-4674-9a27-2039ea6584eb)

**Comment by UnamSanctam** [comment]
Yes those are correct, also remember that you might need run the xmrig-proxy using `sudo ./xmrig-proxy` since you set the open files to the root user. You can set it to higher than 100000 as well. Though since you do get 17 000 miners likely a open files limit isn't the problem.

**Comment by masterjek** [comment]
![3](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/b96067e6-369c-46a0-9e15-1e8883f34f9b)

**Comment by UnamSanctam** [comment]
Are you in the folder with the xmrig-proxy?

**Comment by masterjek** [comment]
No, I just typed the command in the terminal. Or can you do it like this?
![4](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/04bfba07-bf57-4256-a897-744345ee5c9e)

**Comment by UnamSanctam** [comment]
Possibly, I don't use bash much, though you shouldn't need to use ulimit anymore since you've set that globally now.

**Comment by masterjek** [comment]
I understood everything, launched it as you wrote above using the right mouse button and went to the terminal, everything seems to be working fine now.
I also want to know, is there a command to monitor if there are any problems with half-open connections? Suddenly something will arise in the future.
And also, above, does it matter in which country the server is located?

**Comment by UnamSanctam** [comment]
>I understood everything, launched it as you wrote above using the right mouse button and went to the terminal, everything seems to be working fine now.
I also want to know, is there a command to monitor if there are any problems with half-open connections? Suddenly something will arise in the future.
And also, above, does it matter in which country the server is located?

No there's no real monitoring like that that I know of. The country mostly only matter for the ping/latency and whether the IP if the server is blocked anywhere (some countries tend to be blocked more than others due to several different reasons).

**Comment by masterjek** [comment]
Thanks for your help
