### ISSUE TITLE
HELP! 0 Reported hash on nanopool on silent miner

### ISSUE THREAD

**Issue by DMP99** [UnamSanctam/SilentCryptoMiner#225]
Hi can you help me

i got 0 reported hashrate on nanopool on silent miner worker, only reported my nanominer worker
but my balance is growing, but different from calculated worker on my nanominer worker

thx

**Comment by UnamSanctam** [comment]
Yes that's normal, reported hashrate is a specific feature that has to be enabled.

**Comment by DMP99** [comment]
okay thank you
