### ISSUE TITLE
Online download

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#2253]
Is it still a good idea to bring back the online download feature myself? (the xmrig and ethminer downloading from website). or is encrypting the resources doing the same thing?

**Comment by shainodev** [comment]
> You can though since you'd need to add some kind of http(s) library (like cpp-httplib) then the file size would still be semi-large.

No? wouldn't winhttp.h be enough for it?

**Comment by UnamSanctam** [comment]
Sure you can always try, though making things work in winhttp is always a struggle.

>Also the file-size wasnt the issue i was talking about detections, would it decrease the detections if i were to do online download or would it be unneccesary since resource encryption already does that?

Hard to say, theoretically it might (though it's possible that the Windows API calls and the download itself might cause detections), you can really only know by implementing it and testing it. But the file size also has to do with detections.
