### ISSUE TITLE
Mining But Hashrate Doesn't Come

### ISSUE THREAD

**Issue by Dovahkiin1234** [UnamSanctam/SilentCryptoMiner#226]
I'm mining ethereum classic and monero on nanopool. I've been doing this for months so I am sure that my pool and address is correct (I even checked it). Ethereum Classic starts to mine but after 10 mins it stops completely. What could be the issue?

**Comment by DMP99** [comment]
Hi we might have the same issue is your balance grow?

**Comment by UnamSanctam** [comment]
What do you mean stops completely? Your GPU usage goes down on?

**Comment by alexxxxxxxxxxxxxxxxxxxxxxxxxxx** [comment]
if i look in taks manger first few minutes it run on 40% but after 10min it drops to 0-2% my hash rate is 400H/S so very low

**Comment by UnamSanctam** [comment]
> if i look in taks manger first few minutes it run on 40% but after 10min it drops to 0-2% my hash rate is 400H/S so very low i mine xmr only with a cpu

That sounds like a pool issue but 400H/s isn't low depending on the CPU.

**Comment by Dovahkiin1234** [comment]
I use nanopool sometimes it doesn't register for like 20 mines but gives me the shares after that. Just make sure that antiviruses doesn't remove the miner and always use disable windows defender.

**Comment by UnamSanctam** [comment]
Yeah nanopool has a high share difficulty and their statistics updates slow because of it so visually shares come in large batches, if you don't want it that way then you'll have to find a pool with a lower share difficulty.
