### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#2262]
,

**Comment by shainodev** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/77803435/d32c7223-3d25-4ab5-a5b5-9bb9785ee7ce)
i "fixed" it by doing this. will this change anything in the miner itself?

**Comment by UnamSanctam** [comment]
It's likely because GitHub converts all new lines to Linux formatting, your way is one solution and shouldn't mess with anything.

**Comment by shainodev** [comment]
Oh okay, is it also possible to create 2 cpu miners and 1 gpu miner, with 1 cpu miner mining at 10% active and 20% idle and 1 cpu miner mining at 30% active and 60% idle? or is there some sort of problem with that?

**Comment by UnamSanctam** [comment]
You can do that without problem, though if you mine something like RandomX then they'll both have to create their own datasets (about 2GB of RAM, they can't share resources).

**Comment by shainodev** [comment]
oh well. what could i mine then? one would mine randomx definetly but what could the other mine that doesnt take alot of ram

**Comment by UnamSanctam** [comment]
Either a GhostRider coin or some CryptoNight variation coin would be your best bet.

**Comment by shainodev** [comment]
would i get the same amount of profit?

**Comment by UnamSanctam** [comment]
No, since Zephyr is the most profitable to mine.

**Comment by shainodev** [comment]
does it clear the ram when it isnt mining (ill put the 2nd miner to only work on idle)

**Comment by UnamSanctam** [comment]
Yes it clears the ram.

**Comment by shainodev** [comment]
so would that work good? or how much profit do i lose by mining ghostrider instead of zephyr or monero

**Comment by UnamSanctam** [comment]
It would work, not sure what the current profitability of GhostRider coins are at the moment, but it would likely be much less than Zephyr (Zephyr is a lot more profitable than every other coin).

**Comment by shainodev** [comment]
is it less profitable than monero?

**Comment by UnamSanctam** [comment]
Yes any GhostRider coin should be less profitable than Monero. And Zephyr is like three times as profitable as Monero, at it's peak it was something like eleven times more profitable.

**Comment by shainodev** [comment]
hmmm. should i just mine zephyr only while idle then?

**Comment by UnamSanctam** [comment]
Possibly, depends on how often the computers will be in idle.

**Comment by shainodev** [comment]
will it be noticable when 4gb ram is taken from pc

**Comment by UnamSanctam** [comment]
Depends fully on how much RAM the computer has, and how much whatever else is being done needs, though when idle it shouldn't matter much.

**Comment by shainodev** [comment]
on xmr moneroocean arguments --pass=\"Worker~rx/0\" this is the pass does the ~rx/0 have to be there?

**Comment by UnamSanctam** [comment]
Usually yes, that's how you tell MoneroOcean what algorithm you want to mine.
