### ISSUE TITLE
syscalls

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#2264]
when putting the syscalls.h into a seperate project in visual studio,

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/77803435/d56e0593-242d-4c55-96a9-6914d0d190a7)
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/77803435/1bafda9e-dc65-4fd3-9184-beb75a0a6b20)

why does it do this? how do i fix this?

**Comment by UnamSanctam** [comment]
The inline asm format might not work for your compiler depending on what you're using (maybe MSVC?). strip.exe is used to remove unused symbols and other things from a program.
