### ISSUE TITLE
please throw off the source code of Etherium + etc (the miner itself)

### ISSUE THREAD

**Issue by HIDDEN-MINER** [UnamSanctam/SilentCryptoMiner#227]
please throw off the source code of Etherium + etc (the miner itself)

**Comment by HIDDEN-MINER** [comment]
Please send Tg reclamanames1231

**Comment by HIDDEN-MINER** [comment]
bro

**Comment by HIDDEN-MINER** [comment]
please Help

**Comment by UnamSanctam** [comment]
I've posted about this a few times, I used to share some code, though not anymore, here is one post about it: #136 (comment) but I really don't have enough time to maintain two more repositories as might be apparent due to the update delay.

**Comment by HIDDEN-MINER** [comment]
Bro please  - no #136 help

**Comment by UnamSanctam** [comment]
https://github.com/UnamSanctam/SilentETHMiner/issues/136

**Comment by HIDDEN-MINER** [comment]
https://github.com/ethereum-mining/ethminer/releases/tag/v0.19.0-alpha.0 UPD sourse please

**Comment by HIDDEN-MINER** [comment]
please throw off the resources of ETH ETC miner (C++) not compiled

**Comment by HIDDEN-MINER** [comment]
I'll send you a reward

**Comment by UnamSanctam** [comment]
I already linked what I've said before about it (UnamSanctam/SilentETHMiner#136), currently I don't have time with more repositories since I'm already behind on the updates I want to do for the 4 actives ones I have right now.

**Comment by HIDDEN-MINER** [comment]
Yes bro please I'll send you a reward btc

**Comment by HIDDEN-MINER** [comment]
well, it's not long to throw off the surses of an ETH miner

**Comment by HIDDEN-MINER** [comment]
Please Bro

**Comment by HIDDEN-MINER** [comment]
300$ в btc I'll throw it off if you give me surs

**Comment by UnamSanctam** [comment]
I don't care about rewards but it's not nearly that simple, all libraries and everything will need to be compiled as well, because the miner needs to be compiled statically all the libraries need to be compiled manually. And a ton of things are hardcoded so a lot of code (mainly CMake code) would have to be changed as well.

**Comment by HIDDEN-MINER** [comment]
☹
