### ISSUE TITLE
GPU not work when i set both GPU + CPU. But it work when i set only GPU

### ISSUE THREAD

**Issue by thesunofme** [UnamSanctam/SilentCryptoMiner#2274]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/14963227/db4b1b6a-4650-4a2a-be8f-65d671d6d5d3)
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/14963227/84a249f1-28a6-439c-a5cb-fd93729270be)
If I set the loader to only mine on the GPU it will work, but if I also add the CPU then only the CPU will work and the GPU will be in STOP state, is this an error or not? or I did something wrong somewhere

**Comment by UnamSanctam** [comment]
Hmm, they shouldn't impact each other in any way, are you using something like the rootkit? And can you try changing the GPU pool to using SSL instead? Change the connection scheme to "stratums" (SSL) and change the port to `11010`

**Comment by thesunofme** [comment]
> Hmm, they shouldn't impact each other in any way, are you using something like the rootkit? And can you try changing the GPU pool to using SSL instead? Change the connection scheme to "stratums" (SSL) and change the port to `11010`

wow, when i change pool to SSL, that work perfectly. thanks sir <3
