### ISSUE TITLE
Some Idea

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2287]
Hello Unam. I noticed on powerful processors, even if the CPU utilization is set to 20%, you can still very much hear how the miner starts, since a powerful processor quickly heats up even at 20% load, and then the noise from the fan decreases, and everything works quietly, but the very moment of start very audible.
I don’t know if this can be implemented as a smooth start of the miner, so that it does not immediately load by 20%, but gradually allow it to load by 5%, then 10%, and so on up to the load that is set in the configuration.

**Comment by masterjek** [comment]
I agree, when I tested on an i9 -13900k processor, when after startup a couple of minutes pass, the processor temperature reaches a maximum of 36-40 degrees, but at the moment of startup the temperature jumps to 60 and this is very audible from the fans. That's why I asked whether it was possible to implement a smooth start with a gradual increase in load.

**Comment by UnamSanctam** [comment]
Hmm, don't know if I can stagger the xmrig dataset generation, I could try though I can't really test if it makes any difference since my CPU doesn't really heat up when starting the miner.

**Comment by masterjek** [comment]
> Hmm, don't know if I can stagger the xmrig dataset generation, I could try though I can't really test if it makes any difference since my CPU doesn't really heat up when starting the miner.

I just asked this as an idea, but if it is technically difficult to do, then I think it’s better not to try it.
