### ISSUE TITLE
Important question

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#229]
Basically if i set the pool and wallet address different in the silent builder and then change it with configuration in the webpanel will it stay forever? even if my webpanel gets taken down?

**Comment by Brainshot** [comment]
Unam please answer this its very important for me

**Comment by Brainshot** [comment]
@UnamSanctam

**Comment by Brainshot** [comment]
Like if my webpanel is shutdown and i aleardy changed the miners with configuration, will they still run with the configuration i set them?

**Comment by UnamSanctam** [comment]
No it will stay until the next restart when it will try to reconnect to the web panel and/or "Remote Configuration" again, I would advice getting a bulletproof domain so that even if your host gets taken down you can just redirect the domain to some other host and everything would still work.
