### ISSUE TITLE
api-endpoint CPU not working

### ISSUE THREAD

**Issue by FrenzyMan8** [UnamSanctam/SilentCryptoMiner#2295]
Hey, when in the builder I put a URL that doesn't work and in the remote config I put a URL that works with the panel only the GPU miner is displayed in the panel while the CPU miner is not displayed but on the pool it is online.

Here are my configs:

CPU:
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/124939784/89a59c04-abe6-4c56-aa5d-7bd49f4b8836)
GPU
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/124939784/f73344df-e553-4129-bd29-23005739ffd2)

**Comment by UnamSanctam** [comment]
You'e missing a comma (,) after the "max-cpu" line.

**Comment by FrenzyMan8** [comment]
Oh yes I hadn't paid attention, that makes sense, thank you very much for your quick response and for this project

**Comment by FrenzyMan8** [comment]
while I'm here, I wanted to know if it was possible to put a rentry.co raw link in API Endpoint URL in the builder to avoid changing it in the 2 configs?

**Comment by UnamSanctam** [comment]
The "API Endpoint URL" is for the web panel URL, the "Remote Configuration" field is for the rentry link. You can put your web panel URL into the "API Endpoint URL" field and then only add the "api-endpoint" later in the future if you ever need to change it.

**Comment by FrenzyMan8** [comment]
Do you know obfucator to protect the exe and bypass certain antiviruses? free if possible :)

**Comment by UnamSanctam** [comment]
No, there likely aren't any good ones that are free since they need to be constantly updated. But things like cracked protectors like Themida and others can help, just make sure you do any of that on a virtual machine or sandbox.

**Comment by FrenzyMan8** [comment]
ok thank you, I opened a miner but I deleted the exe which allows it to be deleted, how can I remove it? with the panel there is a "Remove Miner" button but does that stop mining?

**Comment by UnamSanctam** [comment]
No, you will have to manually remove it: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner
