### ISSUE TITLE
Mining Issue with Older OS Systems

### ISSUE THREAD

**Issue by Dovahkiin1234** [UnamSanctam/SilentCryptoMiner#230]
Miners can not be run at Systems like Windows 7 and Windows 8. I'm making this Issue cause this could be a bug.
Thanks.

**Comment by UnamSanctam** [comment]
It should work fine on Windows 7 and 8, I run all my tests on my Windows 7 VM before any release.

**Comment by Dovahkiin1234** [comment]
Oh alright then. Just wanted to make sure you know.
