### ISSUE TITLE
WatchDog compiling error ig

### ISSUE THREAD

**Issue by DumbDannyLol** [UnamSanctam/SilentCryptoMiner#231]
![image](https://user-images.githubusercontent.com/60897810/148132282-e9d58cc2-e39f-4ded-bac9-a696d11a4972.png)
This happens when i tru to compile it.

**Comment by UnamSanctam** [comment]
Make sure that your antivirus isn't removing the file that gets built and that you have .NET Framework 4.5 installed.

**Comment by HIDDEN-MINER** [comment]
Bro
