### ISSUE TITLE
Remote Config

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2317]
Hello Unam. On the site pastebin there is a choice Paste Exposure: There are two suitable options:
1. Public
2. Unlisted
Does it matter to a miner which item to choose?

**Comment by UnamSanctam** [comment]
No but unlisted would be the best, since then it can only be seen by others if they have the direct link.

**Comment by masterjek** [comment]
I’ll ask you in this one so as not to open a new one. What could be the reason that when Xmrig Proxy is running, the RAM gradually fills up? At first, when starting up, 1GB of RAM is used; after a day, it’s already 5-6GB.

**Comment by UnamSanctam** [comment]
There used to be a memory leak in xmrig-proxy though that should have been fixed a few versions ago. Does it stay at some level eventually?

**Comment by gabjohn3** [comment]
> > There used to be a memory leak in xmrig-proxy though that should have been fixed a few versions ago. Does it stay at some level eventually?
> 
> I'll check. because when it got to 6GB, I just restarted the program and everything starts to load again. Now that I have 6GB, I’ll check and won’t restart.

Bro to prevent high ram usage disable worker option on config.json on proxy in the end of file put 
      },
    "user-agent": null,
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": false
}

workers in false for prevent high ram usage
