### ISSUE TITLE
nicehash pool

### ISSUE THREAD

**Issue by LostMySpirit** [UnamSanctam/SilentCryptoMiner#2318]
does anyone have experience with nicehash? or if you get banned for too much workers

**Comment by masterjek** [comment]
> does anyone have experience with nicehash? or if you get banned for too much workers

I have experience. As the number of workers increases, this is what awaits you in your personal account: Active moratorium. Temporary suspension of activities until restrictions are lifted. Reason: other. Time of lifting the moratorium: 20 January 2034

**Comment by LostMySpirit** [comment]
xD alright thank you. I wont switch to nicehash
