### ISSUE TITLE
Remote Config

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2322]
Hello Unam. I have an idea, I want to implement it, but I need to find out some details from you. The miner connects to a remote configuration, and upon receiving data from it, it immediately disconnects and waits 100 minutes, right? I just want to try to create my own personal website, with functionality like Pastebin or similar ones. And place it on Linux via Apache. So I’m wondering whether the limit of TCP connections will interfere with me too much, I understand that the limit can be increased, but there is still a connection limit.

**Comment by UnamSanctam** [comment]
Yes that's correct it connects once during start and then once every 100 minutes after that, and any limit would be in Apache itself but you should never really be able to reach the limit for the "Remote Configuration" since it connects so rarely.

**Comment by masterjek** [comment]
I have a question. The antivirus blocks the miner’s access to the web panel and every second a blocking notification is shown on the screen. This worker has a remote configuration, he can connect to the remote configuration and the antivirus does not block this access for him to work. Can I turn off requests to the web panel for this worker?

**Comment by UnamSanctam** [comment]
You can set "api-endpoint" to "" in the "Remote Configuration" but then that will apply for all miners using that "Remote Configuration".

**Comment by masterjek** [comment]
Do I understand correctly, all miners who use this remote configuration will simply disconnect from the web panel and work on the remote configuration?
And after rebooting the computer, will the miner still try to contact the web panel again?

**Comment by UnamSanctam** [comment]
Yes `"api-endpoint": ""` would instruct the miners to not contact any web panel, the miner should not try to contact the web panel on startup since it checks the "Remote Configuration" first before the web panel.

**Comment by masterjek** [comment]
Here is a piece of code, did I specify it correctly?
"kill-targets": "",
"stealth-fullscreen": false,
"api-endpoint": ""
}

**Comment by UnamSanctam** [comment]
Yes that would be correct.
