### ISSUE TITLE
Inserting Code into Final .exe Execution

### ISSUE THREAD

**Issue by 65anon** [UnamSanctam/SilentCryptoMiner#2323]
I want to modify the project to make the final .exe of my Monero miner run some code beforehand, which file should I modify to insert my code?

**Comment by UnamSanctam** [comment]
The main program is miner.cpp
https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/miner.cpp

**Comment by 65anon** [comment]
> The main program is miner.cpp https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/miner.cpp

Thanks!
