### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2325]
Unam tell me, is there a difference which version to choose from the list?

![2](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/dc624def-f840-4c0e-b903-ab795709331e)

**Comment by UnamSanctam** [comment]
No, it just changes compatibility, normally it's set to 4.5.

**Comment by masterjek** [comment]
And it’s normal that I can’t choose release 4.5. It’s not on the list, there’s only 4.5.2. And it doesn’t let me install 4.5, it says it already comes with the operating system.

**Comment by UnamSanctam** [comment]
I believe you manually need to fix 4.5 since Microsoft messes it up, here's a StackOverflow question with many different solutions https://stackoverflow.com/questions/70022194/open-net-framework-4-5-project-in-vs-2022-is-there-any-workaround.

**Comment by masterjek** [comment]
Thanks a lot. The instructions were helpful.
