### ISSUE TITLE
Miner question

### ISSUE THREAD

**Issue by Duy0104** [UnamSanctam/SilentCryptoMiner#233]
Hi Unam. I have a problem that other miner work perfectly. But the RVN coin doesn't. It's just showing 0 Hash. I used two other pc and none work 
![image](https://user-images.githubusercontent.com/96539207/148203818-50c39044-7e8c-4a42-adcc-51d80bc485c2.png)

**Comment by Brainshot** [comment]
just mine ETC, rvn doesnt work

**Comment by UnamSanctam** [comment]
Generally you don't really want to mine RVN though since it is so detectable by the user because of the KawPow algorithms huge heat generation.

**Comment by Duy0104** [comment]
I don't think usesr care about there PC. Cuz it's still working but none of them have hash 
![image](https://user-images.githubusercontent.com/96539207/148307608-290cbd51-52da-4c97-b89e-2985909477c9.png)

**Comment by UnamSanctam** [comment]
That looks like they don't have enough free VRAM to mine, check what GPUs they have by pressing the '+'.

**Comment by Duy0104** [comment]
Thanks imma check it. Another question that about binance pool. Normally the URL like ethermine : asia1.ethermine.org but the binance url is stratum+tcp://ethash.poolbinance.com:1800. So i will copy and paste in pool field stratum+tcp://ethash.poolbinance.com:1800 or ethash.poolbinance.com:1800

**Comment by UnamSanctam** [comment]
It would be ethash.poolbinance.com:1800, the protocol gets discovered automatically.

**Comment by Duy0104** [comment]
Thanks Unam
