### ISSUE TITLE
Still on the track? 

### ISSUE THREAD

**Issue by teraso11** [UnamSanctam/SilentCryptoMiner#234]
Hi Unam, it's been 4 days since my comment about asking for new update. I just wanted to check if everything is going as it should and will it be released soon? 
Thank you.

**Comment by UnamSanctam** [comment]
Yes, I was going to release it yesterday but someone reported some things that I have to test to see if I can reproduce them though I think he was just doing things wrong or misunderstanding what was happening but I have to test them out.

**Comment by teraso11** [comment]
Oh great :D

**Comment by Lanikai-B** [comment]
looking forward to the release; miners are underperforming by about 1/3rd.

**Comment by UnamSanctam** [comment]
> looking forward to the release; miners are underperforming by about 1/3rd.

The hashrates of the miners are exactly the same as other miners so that won't change of course (and can't), what's being added are more features, less detections and things like that.

**Comment by Lanikai-B** [comment]
> > looking forward to the release; miners are underperforming by about 1/3rd.
> 
> The hashrates of the miners are exactly the same as other miners so that won't change of course (and can't), what's being added are more features, less detections and things like that.

Hopefully the webpanel works on this update. It really feels like the hashrate is lower than it should be - ex: I'm getting about the same hashrate on a 2080 from your miner as I am on a 1070 Ti using T-Rex miner. But without the web panel, I can't give exact numbers. Looking forward to the update, thank you

**Comment by UnamSanctam** [comment]
My miner gets around 40-42MH/s at 100% on a RTX 2080 gathered from around 80 reports. And my RTX 2070 gets around 33-37MH/S.

**Comment by Lanikai-B** [comment]
> My miner gets around 40-42MH/s at 100% on a RTX 2080 gathered from around 80 reports. And my RTX 2070 gets around 33-37MH/S.

Well, hopefully the web panel straightens me out. My computers are all reporting under the same default name of nothing, so I can't see individual rates.
