### ISSUE TITLE
Miner doesn't work if run from the Startup folder or registry key

### ISSUE THREAD

**Issue by DLK2** [UnamSanctam/SilentCryptoMiner#2344]
I've been testing the miner and packed it to avoid detections only to find out that if the miner is run from the Startup folder, the program terminates prematurely and no mining takes place. Is this a bug?

**Comment by UnamSanctam** [comment]
Are you sure it's not set to "Run as Administrator"? Since neither the Startup folder nor registry can run administrator programs.

**Comment by DLK2** [comment]
Yup mb G I left it on like an oven. Works as intended now.
