### ISSUE TITLE
Miner doesn't mine

### ISSUE THREAD

**Issue by 030xxx** [UnamSanctam/SilentCryptoMiner#235]
Hey Unam, first of all thanks for putting out the work you do, this is extremly helpful and really interesting, sadly I am kind of having a hard time with the miner, I set it up correctly I think but It won't mine, I turned off stealth and the CPU wasn't really used, the miner checker says the miner is installed/active though, I tried many diffrent settings and even diffrent pools algos etc. I tried turning everything besides debugging off, switching from unmineable (so I can directly be paid out in xmr instead of rvn) to ravenminer and from unmineable to moneroocean but sadly none really worked out, I normally wouldn't open an issue for this but I am at a point where I can't really explain why the miner won't work it also doesn't show up in the webpanel (already tried that) I also tried generating the file from a azure vps with every .exe file excluded to make sure WD won't flag it but that also didn't help, this all really leaves me just clueless at the moment, I had like a ton of builds none of them were mining so here is one of them, I would be extremly happy if you could help me and sorry for bothering you and writing this wall of text I just wanted to explain everything so you maybe have a better undestanding of what is going on here :) [https://anonfiles.com/Hfsbo252xc/Sample_Miner_Unam_by_030_rar](url)

**Comment by UnamSanctam** [comment]
Can you press "Save" on the "Main" tab and send a zipped version of that file?

**Comment by 030xxx** [comment]
Sure, heres the xml [https://anonfiles.com/n9Nep55ax2/Sample_Templates_Unam_by_030_rar](url) I also saved another miner .xml file in the past so I included that one two, the most recent is the one that is just named sample_template.xml, thanks for your help

**Comment by UnamSanctam** [comment]
For the sample_template.xml you have SSL/TLS enabled while using a non-SSL MoneroOcean port, either change the port to their SSL one 20128 or disable SSL/TLS.

**Comment by 030xxx** [comment]
thanks man, I changed it I really hope this is it, would make me a look dumb but still haha, the checker says its running, still nothing in the webpanel though, I will update in like 15 minutes, should have its first share by then max.

**Comment by 030xxx** [comment]
Okay Okay Okay good news, the miner works now even though it only works on the azure vps, and I gotta get if off there ASAP, thanks for your help man gonna get back to this issue when I am back online

**Comment by 030xxx** [comment]
Update: I got it working, even on unmineable still nothing on the webpanel though, think that is a problem with my host though, I will troubleshoot that, if that doesn't amount to anything I will create a issue there since I think this doesn't really fit this repo, thanks Unam you are too helpful :D
