### ISSUE TITLE
What is wusa and mrt.exe?

### ISSUE THREAD

**Issue by Alcinzal** [UnamSanctam/SilentCryptoMiner#2358]
Hey, I am reading your code and I have a few questions regarding DefWDExclusions and DefDisableWindowsUpdate.
### DefWDExclusions
I understand the first part about "Add-MpPreference", but what does the rest do? What is wusa, and why are you uninstalling, and why that specific build "/kb:890830"? And MRT.exe, I know that it stands for "Malicious Software Removal", but does it have the ability to remove malware even after exclusions are set? And what is "DontOfferThroughWUAU"?

### DefDisableWindowsUpdate
In the code I see you are stopping the services and renaming some keys, but what are those keys, and what does _bkp stand for? Is it "backup"?

And if I only have WDExclusions enabled, is it possible that the miner gets removed if the user updates their computer? So I assume you would recommend having both these enabled?

**Comment by UnamSanctam** [comment]
>I understand the first part about "Add-MpPreference", but what does the rest do? What is wusa, and why are you uninstalling, and why that specific build "/kb:890830"? And MRT.exe, I know that it stands for "Malicious Software Removal", but does it have the ability to remove malware even after exclusions are set? And what is "DontOfferThroughWUAU"?

wusa is a Windows program used to control updates, kb890830 is the update for MRT. I remove the update and file, and then also add a registry key ("DontOfferThroughWUAU") to not download it again. MRT does not care at all about exclusions and will remove anything it finds whenever it is run.

>In the code I see you are stopping the services and renaming some keys, but what are those keys, and what does _bkp stand for? Is it "backup"?

They are Windows Update services, and _bkp is backup as you say and is done so that the uninstaller can restore them to a working condition.

>And if I only have WDExclusions enabled, is it possible that the miner gets removed if the user updates their computer? So I assume you would recommend having both these enabled?

Yes it's possible, using both is recommended.

**Comment by Silentsniper1** [comment]
> Hey, I am reading your code and I have a few questions regarding DefWDExclusions and DefDisableWindowsUpdate.
> 
> ### DefWDExclusions
> I understand the first part about "Add-MpPreference", but what does the rest do? What is wusa, and why are you uninstalling, and why that specific build "/kb:890830"? And MRT.exe, I know that it stands for "Malicious Software Removal", but does it have the ability to remove malware even after exclusions are set? And what is "DontOfferThroughWUAU"?
> 
> ### DefDisableWindowsUpdate
> In the code I see you are stopping the services and renaming some keys, but what are those keys, and what does _bkp stand for? Is it "backup"?
> 
> And if I only have WDExclusions enabled, is it possible that the miner gets removed if the user updates their computer? So I assume you would recommend having both these enabled?

Contact me on discord if u are interested in the FUD my username is Silentsniper0

**Comment by Alcinzal** [comment]
Thank you so much
