### ISSUE TITLE
Custom order

### ISSUE THREAD

**Issue by Nobellium1** [UnamSanctam/SilentCryptoMiner#236]
Hello Unam.

I might have a custom order for you. Current budget is 1200$.
Please leave me any contact where I can contact you without everybody reading this.
I'd need http based generator made in python (or whatever suits you but I believe python would be the easiest)

**Comment by Nobellium1** [comment]
If you got no telegram, leave me any email, I'll give you telegram account for free to use and explain how to protect it from anybody.
I'm the guy you helped with keydrop parser and I'll never forget how much you helped me

**Comment by UnamSanctam** [comment]
Biggest problem with Telegram is that if someone gets access to the phone number in any way then they can hijack the account which has happened to people not using their real phone numbers before.

**Comment by Nobellium1** [comment]
Even if he gets the access to the phone number, you can set up additional authentication and make sure to close all other sessions. So even if he tries to log in again with the same number, it'll ask him for additional password.

**Comment by UnamSanctam** [comment]
But can't he still reset everything? I've seen it happen before which is why I'm hesitant, only thing I have right now is a Hugin account though since I have some people added there (and the messages are fully private).

**Comment by teraso11** [comment]
> But can't he still reset everything? I've seen it happen before which is why I'm hesitant, only thing I have right now is a Hugin "account" though since I have some people added there (and the messages are fully private).

What about Tox? (QTox/UTox) I think it is most secure for communication, just set up tor as proxy because it leaks your ip (it is P2P so it needs to leak your ip with someone you communicate) there is no server or anything in between and all traffic is really good encrypted

**Comment by Nobellium1** [comment]
Tbh I don't think it's that important to keep it untrackable, it's not like we're all here FBI agents or such :D 
I know it's always better to stay safe but I believe it would help everyone here to have your contact like your discord was instead of spamming in this repository

**Comment by Nobellium1** [comment]
Anyways I've set up Utox, lemme add you if it's not a problem

**Comment by teraso11** [comment]
Yea, I also have tox, please share your ID if you create it. Thank you.

**Comment by Nobellium1** [comment]
0FC3FA77BCF1FD9C30894B4D4B9E2789465725D57ACD16195212C69DB433A679D84A484BBA98

**Comment by UnamSanctam** [comment]
Feel free to add me: 4DDBD461F9A6A61F25ACAE4D6B34EF8343692EBACF87BB253B1B9F540A9954406B6C06874759
