### ISSUE TITLE
Xmrig-Proxy

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2369]
Hello Unam. I often see an entry in Xmrig Proxy - Ip Adress - "Wrong hash 595c7d5ce219c8bd5c96e706886905429f458dc35dad7fdd526fba1af556d18c e49f37873b64ad12a5691d07116c7598f7609bd7443dca2774bb04bbcf150000"
And every time it is the same IP, it repeats itself very often and rejects the balls every couple of seconds. As I understand it, this worker has connection problems. I don't use the web panel right now. Only remote configuration. Is there any way to disable or block this IP's access to Xmrig Proxy? Because it still doesn’t work, but it sends out bad balls very quickly and only spoils the statistics.

**Comment by UnamSanctam** [comment]
You can block the IP address in your firewall, for Linux you can use `ufw` and for Windows the Windows Firewall.

**Comment by masterjek** [comment]
> You can block the IP address in your firewall, for Linux you can use `ufw` and for Windows the Windows Firewall.

Exactly Unam you are a genius, how could I forget for this method, thank you very much.

But there is a second question. Where there are few workers, I can see it with my own eyes, there the statistics are moving slowly. But where there are a lot of workers, the statistics go very quickly, is there a way in Xmrig Proxy to enable recording workers with errors in a text file?

**Comment by UnamSanctam** [comment]
You can print out everything into a text file but not only the errors as far as I know.

**Comment by masterjek** [comment]
> Насколько я знаю, в текстовый файл можно распечатать всё, но не только ошибки.

Is this done using this command? - "access-log-file": null,

**Comment by UnamSanctam** [comment]
This is the two log options descritpions:
```
  -l, --log-file=FILE           log all output to a file
  -A  --access-log-file=FILE    log all workers access to a file
```

**Comment by masterjek** [comment]
I did everything, added the IP to the blocking, rebooted the server.
![3](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/ec1d2933-2268-462e-a485-fb8e8b695473)
In the screenshot I underlined that his access is denied.
But according to the logs, it continues to connect and send incorrect hashes.
proxy    0000 rejected (36/4+0) diff 480045 ip 184.66.24.211 "Wrong hash 2e75bde0ef4eda491a5f151536a4b93203a51aec96a3f7a1144fc8444f648381 86d0728ad67b4638b3b770e1c22380953c2e011c3bd58f97a66bebc876030000" (55 ms)

**Comment by UnamSanctam** [comment]
I believe it might have to be at the top, since the other port allows might be overwriting the block.

**Comment by UnamSanctam** [comment]
Remove the current deny rule, then enter something like `sudo ufw insert 1 deny from 184.66.24.211` and it should probably add it at the top.

**Comment by masterjek** [comment]
> Remove the current deny rule, then enter something like `sudo ufw insert 1 deny from 184.66.24.211` and it should probably add it at the top.

Yes it worked, it places the rule above the rest. Now I will monitor whether access for this IP is completely blocked. I also want to ask, after adding the rules, do I have to restart the server?

**Comment by UnamSanctam** [comment]
Alright great, and no you shouldn't have to restart anything for the rules to apply.

**Comment by masterjek** [comment]
> Alright great, and no you shouldn't have to restart anything for the rules to apply.

I was immediately happy, but now I watch and understand that in the screenshot you can see a list of blocked IPs, it blocks access only to the first address, but it has disappeared and I don’t see it, it cannot connect, everything below it continues to connect successfully.

![4](https://github.com/UnamSanctam/SilentCryptoMiner/assets/36513967/ff71bcc1-b133-490a-b1b9-97684e09eea7)

**Comment by masterjek** [comment]
Unam, can you tell me how to allow IP in Ubuntu but immediately in the range from and to - 86.21.200.0 - 86.21.207.255
