### ISSUE TITLE
Some observations

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#2381]
Hello Unam. 
1. I have several VPS servers. Miners version 3.2.0 work on one server; there is no remote configuration; they work through a web panel. Xmrig Proxy uses the latest version 6.21.1.
2. On the second VPS server. Miners of the new version 3.4.0 are already working, and they use only the remote configuration. Xmrig -Proxy also version 6.21.1
What I noticed. Miners of version 3.2.0 sent almost no rejected shares per day, maybe a maximum of 2 per day. Miners of version 3.4.0 sent 200, sometimes 300, or even more rejected shares per day.
Both versions of miners use the same configuration, the same CPU load, and the same stealth goals.

**Comment by dlsofree** [comment]
The new xmrig version will be much more stable than the old xmrig version
