### ISSUE TITLE
sad rootkit

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#2387]
rootkit begin blocked totally from WD Windows 11

**Comment by UnamSanctam** [comment]
Alright, I'll try updating the rootkit in the next version. Was it blocked in a new update in Windows 11?

**Comment by tarekxxx** [comment]
Yea Totally (Blocked In WD windows 11 Only) Windows 10 Is Fine  with WD
its Not Let Program Run and Get Blocked Once Remove Rootkit You Can See pool hashrate coming
its looking installing infact even file exe in his place but nah not working with rootkit

**Comment by tarekxxx** [comment]
try batch this sir please most of my miner get killed
