### ISSUE TITLE
more than one miners config in the single build and one possible bug

### ISSUE THREAD

**Issue by zaromarco** [UnamSanctam/SilentCryptoMiner#242]
hi , i was wondering if i can setup more than 1 miners config that runs at the same time , for example one config for monero with max cpu 15% + idle cpu 30% and another config for another crypto minable with cpu with max cpu 15% + idle cpu 30 % , so the total amout of the cpu will be 30% and 60% when idle
a possible bug is this:
i setup to mine at startup but if i save the config into xml , close the builder , reopen the builder and load the saved config i get this:
![immagine](https://user-images.githubusercontent.com/13431840/148289126-a1661162-0cfc-472f-bc83-41f67b599381.png)
which say disable with the option flagged , the same for Assembly...
let me know

**Comment by UnamSanctam** [comment]
Yes you can technically set up multiple just fine. 

The form serializer doesn't save the text states for the toggle buttons which is why the text stays the same but the functionally won't change so it will still work as normal.
