### ISSUE TITLE
create a app

### ISSUE THREAD

**Issue by KOHnani1** [UnamSanctam/SilentCryptoMiner#245]
when i create file exe , it just also create a complier and includes file so when i install the silentcryptominer , is it necessary to take that 2 file to install ?

**Comment by UnamSanctam** [comment]
No they are just there to compile (build/create) the final .exe, you can delete them if you want, they just don't get deleted automatically so that the folders doesn't have to get recreated on every build. Only the final .exe is required to run the miner.
