### ISSUE TITLE
Silent Miner group on Tox! 

### ISSUE THREAD

**Issue by teraso11** [UnamSanctam/SilentCryptoMiner#247]
Hi people, we will create group on tox for unam miner, so everyone who have tox, add me to send them invites! 
6B21BF94DFEE7376479B269816E3841A10AC22DD11E06B9C1D2E25452DF8F45FDCE06C969260

**Comment by teraso11** [comment]
I've rejected some by accident, send requests again

**Comment by lunar12a** [comment]
hey is this online ?
