### ISSUE TITLE
Can you answer me on Tox?

### ISSUE THREAD

**Issue by Nobellium1** [UnamSanctam/SilentCryptoMiner#253]
Can you respond on tox please? (ROOT)

**Comment by Stuntah14** [comment]
Dude stop fucking posting about this

**Comment by Nobellium1** [comment]
How about you gtfo if you don't like a post?

**Comment by Nobellium1** [comment]
Why did you post something that you could search on google? Any .net crypters would work but you're lazy af to find any.
Unlike you, I'm willing to pay for the help he will provide.

**Comment by Stuntah14** [comment]
You’re literally a script kiddie be quiet 😂

**Comment by Nobellium1** [comment]
If you're a coder, why are you here then? Asking for a crypter?

**Comment by Nobellium1** [comment]
Couldn't you crypt it yourself? Oh shit, are you a script kiddie?

**Comment by Stuntah14** [comment]
Making a crypter yourself takes years of learning advanced obfuscation and cryptography, you are clearly a script kiddie you understand nothing haha

**Comment by Nobellium1** [comment]
First of all, you don't have to be smart to know that you can do any .net crypter. 
Second of all, dude no shit, you're just a fuckin lowlife trying to get here something for free. 
Third of all, I understand nothing? Says guy who asked why is CRYPTO MINER (opensource project) detected by a windows defender? How stupid are you?
Just crawl back to the hole from where you came from and let's not act like you're anything more than just a newbie. ha-ha

**Comment by UnamSanctam** [comment]
Haha there's a bit of a fight here but seems like my Tox has gotten stuck or something, I don't seem to be receiving new messages nor does it seem like any of my messages are being sent. Could be my proxy or something but it looks like it connecting properly though it's a bit difficult to see.

**Comment by Nobellium1** [comment]
Couldn't you use QTox? I believe its more stable than Utox

**Comment by UnamSanctam** [comment]
Yeah I have both, seems to happen with both of them, could maybe be my VPN or something.

**Comment by Nobellium1** [comment]
Do you have any other way?

**Comment by Nobellium1** [comment]
Maybe email or something at least

**Comment by Nobellium1** [comment]
I mean even email should be fine and you wouldn't get like mass spammed I guess

**Comment by Nobellium1** [comment]
@UnamSanctam Can you give me your E-Mail address or something at least

**Comment by UnamSanctam** [comment]
@Nobellium1 Do you know any good place to get numbers for Telegram? I intend to have Hugin (most private), Tox (if I can get it fixed, semi-private) and then Telegram (least private) as the methods of communication.

**Comment by Nobellium1** [comment]
Send me email, will send buy you account and send it

**Comment by Nobellium1** [comment]
@UnamSanctam Or get you the number

**Comment by Nobellium1** [comment]
But sim-activate.ru should do the job

**Comment by Nobellium1** [comment]
You can buy ready made accounts there where you get portable version of telegram with current session. Just set up 2fa and you're good to go, even if they have mobile number, they wont be able to log in again

**Comment by UnamSanctam** [comment]
Yeah I'll try and buy one.

**Comment by teraso11** [comment]
@UnamSanctam you can use "wickr me" it is most secure centrilized messaging app

**Comment by Nobellium1** [comment]
@UnamSanctam Also I can give telegram for free if you want, I got over 8000 accounts in total

**Comment by teraso11** [comment]
Or you can use Jami which is even more secure. You only need username and that's it. Because Amazon now owns wickr me

**Comment by Nobellium1** [comment]
Yup, agreed. Jami is a good one tho.

**Comment by UnamSanctam** [comment]
> @UnamSanctam Also I can give telegram for free if you want, I got over 8000 accounts in total

Sure, I'm still waiting for a verification mail from them but I don't think it'll ever arrive. You can contact me at unams@protonmail.com

**Comment by teraso11** [comment]
Yea, Jami is connencted via blockchain and everything is encrypted and decentrilized so I think we all need to switch there

**Comment by teraso11** [comment]
https://security.stackexchange.com/questions/137937/how-does-jami-formerly-ring-cx-really-work-and-how-secure-is-it

**Comment by UnamSanctam** [comment]
Problem is that Jami (from my knowledge) like Tox of course exposes IP addresses so everyone has to use proxies and/or Tor to use it.

**Comment by teraso11** [comment]
Yea but that is only option for decentrilized messaging app

**Comment by teraso11** [comment]
Every decentrrilized p2p messaging app needs to expose ip

**Comment by teraso11** [comment]
Also there is a Session which does not exposes ip and also is almost as secure as tox/Jami

**Comment by teraso11** [comment]
https://www.youtube.com/watch?v=rPp4rQnrG44 Yea, Session is deffinitly the best.

**Comment by UnamSanctam** [comment]
Hugin is what I'll probably use as the main method of communication for those that want the most privacy since it purely uses a blockchain, but I will have some others like Telegram and such as well (maybe session).

**Comment by Nobellium1** [comment]
Using Hugin, lemme add you

**Comment by Nobellium1** [comment]
@UnamSanctam

**Comment by Stuntah14** [comment]
Why is this kid being so annoying lol  script kiddies these days smh

**Comment by UnamSanctam** [comment]
> Using Hugin, lemme add you

I'm migrating over my communications to another VM and then I'll list the addresses in todays release.

**Comment by Nobellium1** [comment]
@Stuntah14 Are you retarded? Why are you even stalking my posts, get a life.
