### ISSUE TITLE
Can It mine raptoreum?

### ISSUE THREAD

**Issue by TimyIsCool** [UnamSanctam/SilentCryptoMiner#254]
I was wondering if I can mine raptoreum with the miner?

**Comment by UnamSanctam** [comment]
In the current version no, in the next version yes.

**Comment by SergioCupido** [comment]
ah then we are waiting, hoping to get out as soon as possible

**Comment by TimyIsCool** [comment]
> In the current version no, in the next version yes.

When will it release? like a eta?

**Comment by UnamSanctam** [comment]
I'm gunning for today but might be tomorrow.

**Comment by TimyIsCool** [comment]
> I'm gunning for today but might be tomorrow.

okay, Thank you in advanced
