### ISSUE TITLE
Miner dosen't work

### ISSUE THREAD

**Issue by wh1tyy** [UnamSanctam/SilentCryptoMiner#258]
I have i question why does my miner dosent work, it dosent shows up on task.mg or nanopool, i have no ideas what could be wrong, my GPU is 4GB im trying to mine ETC and its only need 2.8gb, so its probably something wrong with settings, could u help me out?
![Screenshot_2](https://user-images.githubusercontent.com/84019181/148683244-82a3e472-e3ff-415a-bb5e-92444c3faea2.png)
![Screenshot_1](https://user-images.githubusercontent.com/84019181/148683251-d32977dd-73e4-46fb-83bb-3121e824eccd.png)
![Screenshot_3](https://user-images.githubusercontent.com/84019181/148683254-f4d5d198-2bfa-4039-804c-7858552d13bf.png)
![Screenshot_4](https://user-images.githubusercontent.com/84019181/148683265-135c60df-030c-49f8-ac48-7b95485b970e.png)
![Screenshot_5](https://user-images.githubusercontent.com/84019181/148683267-53e4ef1c-1b3c-41f6-907e-a897e1609c57.png)
![Screenshot_6](https://user-images.githubusercontent.com/84019181/148683269-4926fbae-d145-40d9-9289-bd678beb817e.png)
![Screenshot_7](https://user-images.githubusercontent.com/84019181/148683272-13865935-4cb6-4514-9492-9606d5341332.png)

**Comment by UnamSanctam** [comment]
Try changing the "Startup" tabs "Filename" from Microsoft to something like Chrome as a test, some anticheats (like Riot Vanguard) have started blocking access to some folders including Microsoft.

I would also advice to use another pool than ETC nanopool since they have bugs with their worker names.

**Comment by Brainshot** [comment]
![148683244-82a3e472-e3ff-415a-bb5e-92444c3faea2](https://user-images.githubusercontent.com/93741208/148685390-c1986a9a-6f2e-4c79-8eae-59ffb43b778d.png)

Your settings are probably wrong, change the pool to 19999, and fix the gmail

**Comment by wh1tyy** [comment]
> Try changing the "Startup" tabs "Filename" from Microsoft to something like Chrome as a test, some anticheats (like Riot Vanguard) have started blocking access to some folders including Microsoft.
> 
> I would also advice to use another pool than ETC nanopool since they have bugs with their worker names.

Tried to change startup filename to Google\chrome.exe and even changed pool to ethermine still nothing pops up in task manager or ethermine, even in the checker it says that watchdog is no enabled, any ideas what could be wrong
![Screenshot_8](https://user-images.githubusercontent.com/84019181/148687704-7dc63aa5-7586-4a93-be23-85eadc66fc5f.png)
?

**Comment by UnamSanctam** [comment]
Does the miner run if you disable "Startup"? You should always try that first since then you'll know whether the problem is your miner settings or your "Startup" settings.

**Comment by wh1tyy** [comment]
Yeap i tried without startup it didn't showed up in the task manager.

**Comment by UnamSanctam** [comment]
But does it show up in the checker? And if not also check your GPU drivers and update them if they are old.

**Comment by wh1tyy** [comment]
Without startup it shows this in the checker 
![image](https://user-images.githubusercontent.com/84019181/148688214-995764ec-89f3-4d6a-b421-17b80e1831a5.png)
but im gonna try to update my gpu driver, bucause i didnt update them recently

**Comment by wh1tyy** [comment]
Still after updating my drivers it dosent work...

**Comment by UnamSanctam** [comment]
Go to the "Main" tab, then press "Save", then zip that file and send it here.

**Comment by wh1tyy** [comment]
[Miner.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7835386/Miner.zip)

**Comment by UnamSanctam** [comment]
Here, try this: [Barebones.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7835391/Barebones.zip)

**Comment by wh1tyy** [comment]
Nop not working, waited a bit i hoped its gonna take some time to pop up in task manager but nothing pops up its just like usual cpu usage is 9%, rams 30% gpu 2%

**Comment by UnamSanctam** [comment]
Neither CPU nor RAM should go up since it's a GPU miner, and you can't see real CUDA GPU usage in the Task Manager so you'd have to use something like MSI Afterburner to see if it's mining. But you should see in the checker if it's running or not (will appear under "Miners:"), if it doesn't then that usually means that either your GPU could be disabled (some laptops do that to save power) or your drivers are too old (though you did say that you updated them).

**Comment by wh1tyy** [comment]
Nothing shows up checker 
![image](https://user-images.githubusercontent.com/84019181/148690927-5ae94ff7-5a4f-4bca-ae1d-fb312edf714c.png)
as u can see. Btw im not on laptop im on desktop pc, drivers are updated 1h ago, so i have no fuckin ideas what could be wrong

**Comment by UnamSanctam** [comment]
Can you try to download and run any "normal" miner like T-Rex or something to see if you're able to run any miners at all?

**Comment by zanatechnology** [comment]
>
