### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SergioCupido** [UnamSanctam/SilentCryptoMiner#262]
Should we activate the rootkit with the new update?

**Comment by UnamSanctam** [comment]
It should be fully stable yes, but of course I don't have an unlimited amount of computers to test on so it's always possible that it doesn't work for some.

**Comment by SergioCupido** [comment]
When we open the rootkit, will we be able to see that it works with checker?

**Comment by UnamSanctam** [comment]
In the new version yes.

**Comment by SergioCupido** [comment]
this is great news 😁

**Comment by SergioCupido** [comment]
I congratulate you, you are perfect 👌

**Comment by SergioCupido** [comment]
Also, is it possible to mine 3 different coins with different rates?

**Comment by CarloPonxi** [comment]
I want to join that congratulation, thanks for your hard work and all the hours you spend working on this project @UnamSanctam

**Comment by SergioCupido** [comment]
eg monero 15% ghost rider 15% and etc 100%

**Comment by UnamSanctam** [comment]
It's possible yes, as long as the computer has enough resources for it (which it usually does for 2 CPU coins, especially Raptoreum/Ghost Rider since it doesn't use much RAM compared to Monero).

**Comment by SergioCupido** [comment]
So do you think it makes sense to do something like this or can it break the miner?

**Comment by UnamSanctam** [comment]
You should be able to do that just fine but usually it's better to test which coin is the most profitable for the computer (usually with the web panel) and then just mine that one. Currently I think Raptoreum is the most profitable CPU coin (and is better at stealth compared to Monero since it uses barely any RAM).

**Comment by SergioCupido** [comment]
I agree, thank you for everything.

**Comment by UnamSanctam** [comment]
No problem, and good luck.

**Comment by SergioCupido** [comment]
and also is there a site you can recommend for ghost rider (I know I ask a lot of questions)

**Comment by SergioCupido** [comment]
😁😁😁

**Comment by UnamSanctam** [comment]
You can find all pools here: https://miningpoolstats.stream/raptoreum but https://flockpool.com/ is the most common one by far but you can also use https://moneroocean.stream/ if you want to be paid in XMR directly instead.

**Comment by SergioCupido** [comment]
Thanks again, take care

**Comment by UnamSanctam** [comment]
You too.

**Comment by SergioCupido** [comment]
ah also do you know any wallet app for ghostrider i looked for exodus but couldn't find it again sorry

**Comment by UnamSanctam** [comment]
You can either use the Raptoreum Core Wallet https://github.com/Raptor3um/raptoreum/releases or something like ZelCore as well https://zelcore.io/.

**Comment by SergioCupido** [comment]
i think i will use zelcore sorry if i bothered thanks again

**Comment by UnamSanctam** [comment]
Yeah I use it as well for a few cryptocurrencies and has worked well for me.
