### ISSUE TITLE
Didnt Work For me

### ISSUE THREAD

**Issue by SergioCupido** [UnamSanctam/SilentCryptoMiner#265]
it didn't work even though I did everything right but it came to the beginning

**Comment by SergioCupido** [comment]
[SkyRase.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7836040/SkyRase.zip)

**Comment by SergioCupido** [comment]
I activated the rootkit

**Comment by UnamSanctam** [comment]
Can you send the configuration by pressing "Save" on the "Main" tab and then zipping that file and then sending it? And it what way didn't it work?

**Comment by SergioCupido** [comment]
[GhostriderEtc.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7836046/GhostriderEtc.zip)

**Comment by SergioCupido** [comment]
I opened the miner but it didn't open. When I looked at the task scheduler, I saw it there, but it wasn't visible in the checker.

**Comment by SergioCupido** [comment]
When I look with process hacker, conhost.exe comes up but then closes

**Comment by UnamSanctam** [comment]
It will show as nslookup.exe when the rootkit is installed, but it's hidden from Process Hacker so you can't see it there no matter what. You can download and run this [TestConsole.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7836059/TestConsole.zip) and it will show all processes, you can also press "Detach" next to Process Hacker to detach the rootkit from Process Hacker so that you can see the miner.
.

**Comment by SergioCupido** [comment]
i don't know if it works or not

**Comment by UnamSanctam** [comment]
You can start TestConsole, then open Process Hacker, then in the TestConsole press "Detach" next to Process Hacker, then search for `nslookup.exe` in the top-right to see if it's running.

**Comment by SergioCupido** [comment]
its not working

**Comment by SergioCupido** [comment]
nslookup force closing

**Comment by SergioCupido** [comment]
wait ill send video for you

**Comment by SergioCupido** [comment]
[bandicam 2022-01-10 01-10-27-917.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7836076/bandicam.2022-01-10.01-10-27-917.zip)

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148703107-5ceab3f6-07d5-4e2d-b851-0a17de978c01.mp4

**Comment by SergioCupido** [comment]
am i doing something wrong

**Comment by SergioCupido** [comment]
🤔🤔🤔

**Comment by UnamSanctam** [comment]
That one should close down, that was just the miner installer, can you enable "DEBUG" in the builder and run one with that? It looks like it can't install correctly maybe.

**Comment by SergioCupido** [comment]
sure

**Comment by SergioCupido** [comment]
Even though I debug and run it, nothing happened.

**Comment by UnamSanctam** [comment]
Yes then that sounds like that's working, have you tried without the rootkit yet?

**Comment by SergioCupido** [comment]
No

**Comment by SergioCupido** [comment]
I will try now

**Comment by SergioCupido** [comment]
its not work too

**Comment by SergioCupido** [comment]
I closed the rootkit and reinstalled explorer.exe came up but then it closed again

**Comment by SergioCupido** [comment]
do you want me to send the video again

**Comment by UnamSanctam** [comment]
Yes though send me a longer video, in the video you sent you ended it right when it finished installing.

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148703614-0ea45b09-1905-40c9-b498-a2b4efb48158.mp4

**Comment by SergioCupido** [comment]
now after the video the miner reopened by itself and closed again just like in the video

**Comment by SergioCupido** [comment]
> now after the video the miner reopened by itself and closed again just like in the video

I think it's from watchdog

**Comment by UnamSanctam** [comment]
Hmm interesting, looks like your miners are crashing, not sure what's causing that since I haven't seen it before.

**Comment by SergioCupido** [comment]
what should i do i didn't have this problem before

**Comment by SergioCupido** [comment]
It is a pity that after a long time waiting for the update and not working for me

**Comment by UnamSanctam** [comment]
Hmm your settings you sent works fine for me. Does this minimalized build work for you? [Release.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7836117/Release.zip)
.

**Comment by SergioCupido** [comment]
same problem occurred when i opened it for the first time but when i opened it for the second time it worked normally

**Comment by SergioCupido** [comment]
![image](https://user-images.githubusercontent.com/97339303/148703978-1acac57f-a540-4e2c-a20a-d83c877942a1.png)

**Comment by SergioCupido** [comment]
no actually one of them still works when i open it

**Comment by SergioCupido** [comment]
now both work normally

**Comment by UnamSanctam** [comment]
Hmm, one second, I'll use another RunPE that I know to see if it's the actual injection that crashes it for you.

**Comment by SergioCupido** [comment]
so weird

**Comment by SergioCupido** [comment]
![image](https://user-images.githubusercontent.com/97339303/148704059-bf6e2cf9-6809-4095-888e-4e34318d5d37.png)

**Comment by SergioCupido** [comment]
I open the uninstaller and delete the miner and then open it again and sometimes it works and sometimes it doesn't.

**Comment by SergioCupido** [comment]
![image](https://user-images.githubusercontent.com/97339303/148704103-ce8245db-0c42-4be9-86a3-e3dd586b85b6.png)

**Comment by SergioCupido** [comment]
![image](https://user-images.githubusercontent.com/97339303/148704106-1e28d669-8bad-4330-89bb-08c4838190da.png)

**Comment by SergioCupido** [comment]
and now checker force closing

**Comment by SergioCupido** [comment]
![image](https://user-images.githubusercontent.com/97339303/148704185-daa94758-e80f-4518-9217-99545a1064df.png)

**Comment by UnamSanctam** [comment]
Run all the uninstallers for all your old builds.

**Comment by SergioCupido** [comment]
i did

**Comment by UnamSanctam** [comment]
Check that only the normal explorer.exe is running and that no nslookup.exe are running.

**Comment by SergioCupido** [comment]
![image](https://user-images.githubusercontent.com/97339303/148704315-41ec7b81-0f88-4b15-9d44-ec5153dba350.png)

**Comment by UnamSanctam** [comment]
Yes that's the normal one, now try running the file I sent you before and see if it starts both miners.

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148704379-5a46da1d-548a-424d-93ee-e8697f7fa2dc.mp4

**Comment by SergioCupido** [comment]
sounds work

**Comment by SergioCupido** [comment]
I guess it worked normally this time

**Comment by UnamSanctam** [comment]
Yeah, uninstall/kill those and try rebuilding a miner with the settings you sent me, then wait maybe 1 minute (to allow it to fully install) and then use the checker.

**Comment by SergioCupido** [comment]
should i open rootkit ?

**Comment by UnamSanctam** [comment]
Try it without rootkit first so that you can see what's happening.

**Comment by SergioCupido** [comment]
okey

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148704576-3f286a81-a13f-475a-b7c4-94fe9e07b3dd.mp4

**Comment by SergioCupido** [comment]
my ghostrider miner work but etc crashing

**Comment by SergioCupido** [comment]
😅

**Comment by SergioCupido** [comment]
i think i have to go out now i will come back here when i wake up in the morning sorry for interrupting i hope we can solve the problem together

**Comment by UnamSanctam** [comment]
Yeah sounds good, could be some bug but the hardest part is that it doesn't happen for me at all so it's a bit of a weird one.

**Comment by SergioCupido** [comment]
thank you for your effort good night

**Comment by SergioCupido** [comment]
I'll be here when I wake up in the morning see you

**Comment by UnamSanctam** [comment]
Good night.

**Comment by Gopnitsa** [comment]
> I'll be here when I wake up in the morning see you

I solve this problem

**Comment by Nobellium1** [comment]
@UnamSanctam Can you leave any contact? Wanna ask you something in private
