### ISSUE TITLE
Build the project

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#267]
Please tell me. When I build the miner with the builder that I downloaded here. Everything works fine. File JSON looks correct.
![1](https://user-images.githubusercontent.com/36513967/148708225-a0089ac0-0c63-42b3-a9dd-60f32e43b2ca.jpg)
But when I'm in Visual Studio 2019 build a project.
![3](https://user-images.githubusercontent.com/36513967/148708264-c9bad205-a76a-4881-aee9-8e8b309769b7.jpg)
Then the miner builder starts, but but the file JSON displayed incorrectly. And the assembled miner does not work with the builder.
![2](https://user-images.githubusercontent.com/36513967/148708347-f142ddc4-cb8b-453a-ab7d-aef5fe88391c.jpg)
What am I in Visual Studio 2019 What am I doing wrong when building the project?

**Comment by UnamSanctam** [comment]
Good question but looks like the code is maybe getting squished together or something.

**Comment by masterjek** [comment]
Can you tell me where to look at the compression of the code? Because I built the previous version in the same way and everything worked fine. Stopped working in this version.

**Comment by UnamSanctam** [comment]
Your Visual Studio is probably doing it, you can see all the code changed here: https://github.com/UnamSanctam/SilentCryptoMiner/commit/e7d01c6c5ba7e9fd88e9cbcadd25c64c02773939 and there's nothing that would stop it from working.

**Comment by masterjek** [comment]
Do you also use Visual Studio to build? Or another program?

**Comment by UnamSanctam** [comment]
Yes I use Visual Studio as well, try redownloading the code and reopening the solution.

**Comment by masterjek** [comment]
I have already disabled code optimization. Disabled code compression, but still everything breaks during assembly and does not work as expected. Tell me which version Visual Studio you are using? My Version Visual Studio 2019. Maybe I just need a younger version.

**Comment by UnamSanctam** [comment]
I use Visual Studio 2019, I'll try and download the code and compiled it as well to see if I can reproduce it.

**Comment by masterjek** [comment]
My project is being assembled. Just all the parameters of the file JSON are displayed on one line. After the assembly, I run the miner, it appears in the folder completely, but it does not mine and the checker shows that it does not work. I have already suffered, I can not understand what is the reason.

**Comment by UnamSanctam** [comment]
The JSON being on one line doesn't really matter (since it's still fully valid), but the built miner should still work completely fine. Can you press the "Save" button on the "Main" tab and then zip that file and send it here?

**Comment by masterjek** [comment]
Ok here is the file.
[1.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7837416/1.zip)

**Comment by UnamSanctam** [comment]
Yes those settings seem to work fine, does it appear on the checker if you disable the rootkit?

**Comment by masterjek** [comment]
After my build, the miner starts unpacking into a folder, but does not start. To start it, you need to run it again from the unpacked folder. And only then it starts and works. It's a mystery to me why, after my project build, this behavior.

**Comment by UnamSanctam** [comment]
Does it do that for you when using the pre-compiled builder as well? Sounds like the `cmd /c "YOURMINERLOCATION"` that runs after installing the miner might not be successfully starting the miner.

**Comment by masterjek** [comment]
Yes, when using your build, everything starts without problems. When I compile the build without changing anything, then to start it, you first need to start the miner, and then run it again from the folder already on the C drive. Miner names and installation path are the same in both cases.

**Comment by masterjek** [comment]
I just suffer for why. I always took resources and encrypted the miner myself, rootkit up to 0 detections. And then, with the changed files, I assembled the assembly and everything worked fine. But in this update, without even changing anything in the resources, I simply collect the assembly on my computer and it does not work fully. This has never happened with all previous builds.

**Comment by masterjek** [comment]
The only difference is that I previously assembled the assembly on the maniche with Windows 10 version 1809 and Visual studio 2019. Windows has now been updated to version 20H2, and Visual studio 2019 I have not updated.
