### ISSUE TITLE
Miner not working

### ISSUE THREAD

**Issue by Fuzeeee** [UnamSanctam/SilentCryptoMiner#268]
The miner is showing no CPU or GPU usage on process hacker, I am using Monero and will send me .xml belo
[miner-config.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7836352/miner-config.zip)
![Screenshot_1](https://user-images.githubusercontent.com/75581746/148708649-78d65f88-0ba5-4db1-9e20-d76f4fd4dddd.png)
![Screenshot_3](https://user-images.githubusercontent.com/75581746/148708652-f87c6fda-47d1-4da7-a6dd-65c2b37c0072.png)
w

**Comment by Fuzeeee** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/75581746/148708663-dd78e02b-8f8e-4941-bc90-f323eb962ce1.png)

**Comment by UnamSanctam** [comment]
You have "Stealth" enabled so yes it won't show any, I also think MineXMR requires a password (worker name).

**Comment by Fuzeeee** [comment]
Do i make up the miner name or does it not matter

**Comment by UnamSanctam** [comment]
You can put anything in the password field (as long as it's alphanumerical and doesn't have any spaces), you can just enter `Worker` as the worker name.

**Comment by Fuzeeee** [comment]
I have turned off stealth and added a password called "worker" and it is still using no cpu % at all

**Comment by Fuzeeee** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/75581746/148839927-4576d064-d90f-4f2d-88af-af79dcc22120.png)

**Comment by UnamSanctam** [comment]
Run the checker and post here what it returns.

**Comment by Fuzeeee** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/75581746/148852189-d5977d80-507e-4ce1-9e20-26e2bd6119ba.png)

Config used for this:
[myMiner.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7842398/myMiner.zip)

**Comment by UnamSanctam** [comment]
Hmm, I would recommend using another pool anyways since MineXMR is quite ban happy as you can see at the bottom of this page: https://minexmr.com/miningguide
