### ISSUE TITLE
Problem with RootKit

### ISSUE THREAD

**Issue by teraso11** [UnamSanctam/SilentCryptoMiner#269]
Hi, there is a problem when rootkit is enabled. I get nslookup.exe crash. But I don't think it is connected to rootkit, problem is that nslookup injection never worked on 30% on my computers ( most win 8.1 industry pro ). So I think it is a easy fix, just not inject in nslookup.exe, inject in explorer.exe

**Comment by UnamSanctam** [comment]
Then the miner can't be hidden because if I change the rootkit to hide explorer.exe instead of nslookup.exe (or some similar not very commonly used program) then things would stop working in your computer.

**Comment by UnamSanctam** [comment]
So in that case (if nslookup.exe doesn't always work for you) I would have to find some other not commonly used program that exists on all Windows versions to use instead.

**Comment by teraso11** [comment]
Ah, that could be a problem. I will try to find something windows default and send so you can see can you use that for injection

**Comment by teraso11** [comment]
maybe print.exe or something like that?

**Comment by teraso11** [comment]
or iexpress.exe

**Comment by teraso11** [comment]
Alo I have one additional question not connected to this. What do you think about ZelCore wallet?

**Comment by UnamSanctam** [comment]
I generally like it, I use it to store my Kadena, Flux and Rapteoreum and it works well.
