### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by SergioCupido** [UnamSanctam/SilentCryptoMiner#270]
Hey İm Back now i created a new miner and tried again but the situation is still not working

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148744827-37319830-55a8-472b-ba75-ce683d0fb59e.mp4

**Comment by SergioCupido** [comment]
nslookup still opens and closes even though rootkit is not turned on

**Comment by UnamSanctam** [comment]
Did you have rootkit enabled? In that case then it disappearing from the Process Hacker is what's supposed to happen.

**Comment by UnamSanctam** [comment]
> nslookup still opens and closes even though rootkit is not turned on

You chose nslookup.exe manually in the builder?

**Comment by SergioCupido** [comment]
> > nslookup still opens and closes even though rootkit is not turned on
> 
> You chose nslookup.exe manually in the builder?

no both explorer.exe

**Comment by SergioCupido** [comment]
Do you want me to open the debug and try it?

**Comment by UnamSanctam** [comment]
So if it's starting as nslookup.exe when you chose explorer.exe then that build you are running does have rootkit enabled, make sure that you're running the correct builds.

**Comment by SergioCupido** [comment]
Ah now I checked again yes rootkit is on sorrry

**Comment by SergioCupido** [comment]
I will close and reinstall

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148745865-1f4c7edf-c76e-4001-ab20-94ac135b0913.mp4

**Comment by UnamSanctam** [comment]
Looks like it couldn't start your installed file at %AppData%\services.exe, go there manually and check if it's there.

**Comment by SergioCupido** [comment]
![image](https://user-images.githubusercontent.com/97339303/148746453-906d5c06-e144-41e8-9b57-831f24393d55.png)

**Comment by SergioCupido** [comment]
are you here

**Comment by UnamSanctam** [comment]
I would try to change the "Filename" in the "Startup" tab (and test that) and see what happens.

**Comment by SergioCupido** [comment]
Do you want to close and try first or should I just change the name?

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148748052-e5dfff6d-9dec-43a2-af51-688311619571.mp4

**Comment by UnamSanctam** [comment]
Yeah there everything worked fine.

**Comment by SergioCupido** [comment]
no

**Comment by SergioCupido** [comment]
my etc miner didn't work

**Comment by SergioCupido** [comment]
only ghostrider worked

**Comment by UnamSanctam** [comment]
Can you try and disable "Stealth" in both your miners?

**Comment by SergioCupido** [comment]
sure

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148748826-8cff121b-5c6c-4172-a5a8-fe5052799540.mp4

**Comment by SergioCupido** [comment]
It works at 90% even though I set it to 50%It works at 90% even though I set it to 50%

**Comment by SergioCupido** [comment]
and still etc not working

**Comment by UnamSanctam** [comment]
The CPU it uses depends on how many cores your CPU has. Can you send the configuration of your latest miner ("Save" on "Main" tab).

**Comment by SergioCupido** [comment]
Try turning off process killer and still the same

**Comment by SergioCupido** [comment]
> The CPU it uses depends on how many cores your CPU has. Can you send the configuration of your latest miner ("Save" on "Main" tab)?

okey

**Comment by SergioCupido** [comment]
[unam.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7838103/unam.zip)

**Comment by UnamSanctam** [comment]
Can you try running this [TestInstall.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7838132/TestInstall.zip)? Though of course first run all the uninstallers you have from before.

**Comment by SergioCupido** [comment]
sure

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148750873-8abc0641-e661-4b8f-9f46-6ad2788350d3.mp4

**Comment by SergioCupido** [comment]
I think this worked for me but why doesn't it work for what I do, what's the problem?

**Comment by UnamSanctam** [comment]
Ok so that works fine, I think the problem might've been that your "Stealth Targets" + "Kill Targets" lists combined are too long for Windows command lines, Windows has a limit of how long it can be which I referenced in the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#stealth-targets

**Comment by SergioCupido** [comment]
I don't remember turning both of these off and doing it, I'll try again

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148751823-690845e2-104f-466c-b1a9-db386839e23b.mp4

**Comment by SergioCupido** [comment]
the etc miner i made is not working hahaha

**Comment by SergioCupido** [comment]
your miner works but why does mine not?

**Comment by UnamSanctam** [comment]
Try with these settings: [TestSettings.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7838222/TestSettings.zip).

**Comment by SergioCupido** [comment]
Is ssl/tls available for etc? because i have selected ssl/tls but there is no option to turn it on

**Comment by SergioCupido** [comment]
okey

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148752696-d387ef43-0b5c-40ac-9d63-417ab24b7c0f.mp4

**Comment by SergioCupido** [comment]
still same

**Comment by UnamSanctam** [comment]
This then [TestSettings2.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7838251/TestSettings2.zip)? I disabled your web panel "API Endpoint URL".

**Comment by SergioCupido** [comment]
okey

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148753576-0a9f73ae-146f-4d5e-8b7c-a5a40e7efeab.mp4

**Comment by SergioCupido** [comment]
I think the problem is caused by "API Endpoint URL"

**Comment by SergioCupido** [comment]
I was using this panel before, why is it not working now?

**Comment by UnamSanctam** [comment]
Good question, I'm using mine just fine and using yours manually seems to work fine as well.

**Comment by SergioCupido** [comment]
https://user-images.githubusercontent.com/97339303/148755114-0195bc1a-6500-4d05-8257-ead0b4c2dc70.mp4

**Comment by SergioCupido** [comment]
I have to have breakfast I've been dealing with this since I got up

**Comment by SergioCupido** [comment]
i think the problem is rootkit and i have to use them without opening them in panel i hope in next update this problem will go away for me

**Comment by SergioCupido** [comment]
I translated all the speeches by looking at translate, I hope I didn't tell you anything wrong, thanks for everything

**Comment by UnamSanctam** [comment]
If the problem was the rootkit then the RTM miner wouldn't work but since it does then it's something else. I'll have to check more I guess.

**Comment by SergioCupido** [comment]
I guess I will wait for you to fix this problem

**Comment by SergioCupido** [comment]
if i need help or need to open anything just send it to me thank you for wasting your time

**Comment by SergioCupido** [comment]
also i have a question i want to ask you, do you think i should add panel to rtm miner?

**Comment by SergioCupido** [comment]
And since the problem is from the panel, can I turn on stealth and process killers?

**Comment by SergioCupido** [comment]
the only thing i know now is if we enter the panel in etc it doesn't work but if we just add the panel to rtm, both work

**Comment by SergioCupido** [comment]
and when i boot the rootkit only rtm works

**Comment by SergioCupido** [comment]
etc gives such an error (in process hacker)

**Comment by SergioCupido** [comment]
![image](https://user-images.githubusercontent.com/97339303/148780187-fca23aea-84ce-4fda-bc88-255ca7675e4f.png)

**Comment by SergioCupido** [comment]
hey can you find any solution for this problem

**Comment by UnamSanctam** [comment]
Bit hard to fix since I haven't been able to reproduce the problem nor have I seen anyone else with the same problem either.

**Comment by SergioCupido** [comment]
Won't you fix it because I'm the only one experiencing this?

**Comment by UnamSanctam** [comment]
I don't know what to fix yet since we don't know the exact issue yet or why it's happening.

**Comment by SergioCupido** [comment]
In general, after every update, there is a problem with Turkish computers.

**Comment by UnamSanctam** [comment]
Yes true but it shouldn't really be the issue here since it seems like the miner process actually crashes for some reason.

**Comment by SergioCupido** [comment]
So are you not going to do anything about this situation right now?

**Comment by UnamSanctam** [comment]
I can't do anything right now before I've investigated more because I have no idea what or why is happening for you and thus can't fix it until I've found that out. Can you send the latest settings you used (send the file from pressing "Save") that didn't work so that I can experiment with them?

**Comment by SergioCupido** [comment]
Is there a place where I can reach you privately?

**Comment by SergioCupido** [comment]
When you message from github, I don't get notification and sometimes it doesn't even matter.

**Comment by SergioCupido** [comment]
If we can talk privately I would like to help you more about this.

**Comment by SergioCupido** [comment]
Also everyone can see the messages here 😨😨😨

**Comment by SergioCupido** [comment]
can you open a discord account again or if there is something you use it doesn't matter to me

**Comment by SergioCupido** [comment]
also i found some useful information i think this problem only happens when i run it with ghostrider

**Comment by SergioCupido** [comment]
When I do it with monero, both work, but with ghost rider only ghostrider works

**Comment by SergioCupido** [comment]
Is there a place where I can reach you

**Comment by SergioCupido** [comment]
[crashsettings.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7848823/crashsettings.zip)

**Comment by SergioCupido** [comment]
When I create a miner with these settings, I get an crash

**Comment by UnamSanctam** [comment]
Hmm interesting, sounds like it might be your computer doing it then which would explain why I can't reproduce it on my computer or any of my VMs.

I have a Telegram now at: @UnamSanctam

**Comment by SergioCupido** [comment]
ah i never used telegram unam sanctam is your name in telegram or haha
