### ISSUE TITLE
Problem with etc miner

### ISSUE THREAD

**Issue by teraso11** [UnamSanctam/SilentCryptoMiner#271]
Hi, when I've tried ETC miner, it ocupated 3.09GB of RAM memory. That pc does not have enough VRAM but why it ocupates RAM memory?

**Comment by UnamSanctam** [comment]
Some integrated GPUs (GPUs inside CPUs) use RAM instead of VRAM (since they don't have any).

**Comment by teraso11** [comment]
Any yea, you are right. This is ryzen so it done that
