### ISSUE TITLE
Can you leave a contact?

### ISSUE THREAD

**Issue by Nobellium1** [UnamSanctam/SilentCryptoMiner#273]
Can you leave a contact?

**Comment by UnamSanctam** [comment]
Ah sorry forgot to press "Comment".

Sure my Hugin is:
```
SEKReXYcNHnKs2QP5fT9AiHrpjdy485SWEd75y6XYdXxDFEH3eJpMYqaZRLStifqBFJtP167KETffZW2MFCCg9NtS8LJ6a9yJyy4d6acb32a7f6cd59fdd8efb232b056e94c783b06f2212a88ad20cef0cd352775
````
But it seems like my communications VM is acting up, I keep getting error messages all the time much I've been trying to fix.

Also, can't figure out the cloud password (to reset it) to the Telegram you sent me, tried the hint but that didn't work unfortunately.

**Comment by Nobellium1** [comment]
@UnamSanctam It seems it requires XRK to send the message. However, I'll send you new telegram to your email.
