### ISSUE TITLE
automatic miner for 4gb and 6gb ?

### ISSUE THREAD

**Issue by Sh4r3cat** [UnamSanctam/SilentCryptoMiner#274]
is it possible that it can automatic choose the miner for vram?

**Comment by UnamSanctam** [comment]
No since the miner doesn't know how much VRAM is required for whatever coin you are trying to mine before the miner has already started and has connected to the pool. Only other solution would be for people to enter it manually in the builder but that would have its set of challenges as well. It's much better to just use the web panel for it instead (check what GPU the computer has and apply another configuration to the miner).

**Comment by UnamSanctam** [comment]
Depends what GPUs they are, you can add the GPUs you have here: https://whattomine.com/coins, select the GPUs so they are green/red and enter how many there are of each in front of them and it will then say the optimal combined hashrate under "Ethash".

**Comment by Sh4r3cat** [comment]
Yeah I did it already but since I use pureminer i have very low hashrates with 8 6gb+ gpus and i used your eth miner years ago and it worked more stable and better hashrates

**Comment by UnamSanctam** [comment]
Sure, reasonably 8 6GB+ GPUs should have a higher hashrate, anywhere from 100-400MH/s if mining at 100%. I have heard that pureminer takes a lot of hashrate as a dev fee (or something similar) from what people have told me when they have compared miners but it's hard to know. 68MH/s could maybe be reasonable if the GPUs are mining at something like 20%.

**Comment by Sh4r3cat** [comment]
What a dev fee ?! That means they get some of my hashrates ?

**Comment by UnamSanctam** [comment]
Yes some have claimed that (by comparing miners to see the difference in hashrate) and from looking at some of the hashrates people get with it it seems fully possible .

**Comment by UnamSanctam** [comment]
Some have claimed that (by comparing miners to see the difference in hashrate) and from looking at some of the hashrates people get with it it seems possible but of course I don't know if they really do have one. But it could also be that pureminer uses less GPU or something to avoid user detection or anything similar.
