### ISSUE TITLE
Errors when working with Web Panel

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#275]
The miner has a very strange behavior when working with the Web Panel. The miner is installed starts mining. His work can be seen on the panel.
![4](https://user-images.githubusercontent.com/36513967/148845971-2ded983e-1bfd-4b12-8410-7ef8b1f506bc.jpg)
After a while, the miner completely resets the speed to 0 and literally after another couple of seconds starts again.

https://user-images.githubusercontent.com/36513967/148847380-b6956369-21f8-47cc-9d61-fcbd981ae39f.mp4

The video shows how one core is loaded at 100% This is a miner working. After that, there is a reset to 0 and again to 100, and so on all the time. The rootkit is disabled, and the Watchdog timer is also disabled. If build a miner without a web panel, everything works fine without interruption.
During interruptions, the Web Panel shows that the miner is running all the time.

**Comment by UnamSanctam** [comment]
Do you use some kind of configuration in the web panel?

**Comment by masterjek** [comment]
There is no remote configuration. I only used data from JSON
![5](https://user-images.githubusercontent.com/36513967/148848816-56319cf1-02dc-4499-9bd6-fb41c6d49d9f.jpg)
Maybe this is causing this behavior?

**Comment by UnamSanctam** [comment]
Firstly maybe remove the empty "kill-targets" unless you're just trying to clear the ones you have from the builder. Also where's your "wallet" field to specify your nicehash wallet?

**Comment by masterjek** [comment]
In the builder, I indicate the wallet. Why is it not carried over to JSON I do not know.

**Comment by UnamSanctam** [comment]
Hmm, it might've been lost when Visual Studio corrupted some of the code just before release (happens occasionally with Visual Studio).

**Comment by masterjek** [comment]
I will use version 2.0.1 for now. It works fine for me. Because version 2.1.0 does not want to work for me without errors. Thank you for your help and your efforts.

**Comment by masterjek** [comment]
Yes, I checked it again, I build miner in version 2.0.1. Everything works stably. The web panel shows everything and the wallet as well. I also took the panel 1.3 version.
![1](https://user-images.githubusercontent.com/36513967/148854976-602ec2ff-ad6a-43ae-80fb-002213a07854.jpg)
And the miner works without a single interruption.

https://user-images.githubusercontent.com/36513967/148855018-850c95e7-5157-4683-8c0d-1680432fdf30.mp4

And the project in Visual Studio I put it together without any problem.
So you are right. Most likely, in the new version, something Visual Studio messed up in the code.
Or just the new version does not work for me normally.

**Comment by UnamSanctam** [comment]
Add the "wallet" into the configuration and see what happens if you haven't already.

**Comment by UnamSanctam** [comment]
Should be `"wallet": "WalletAddress",`

**Comment by masterjek** [comment]
I added to JSON wallet. 
![1](https://user-images.githubusercontent.com/36513967/148904822-5ca539f2-26fc-4e73-91cc-a853f84ece1c.jpg)
When trying to add to the webpanel
![2](https://user-images.githubusercontent.com/36513967/148904933-18c596ed-cccf-47fe-be3d-e72a4ab33d91.jpg)
I mine on NiceHash there is a wallet format BTC.
But I also tried creating a config with monero wallet as well. The mistakes are the same.

**Comment by masterjek** [comment]
Although Webpanel does not accept Json with wallet adress. Miner after adding the wallet to JSON in builder now works stably without speed drops. And the webpanel is displayed normally. I also want to ask why this folder is being created - Telemetry - It is empty. Rootkit disabled, watchdog disabled.

**Comment by UnamSanctam** [comment]
It's where the watchdog is usually placed.

**Comment by masterjek** [comment]
Thank you
