### ISSUE TITLE
GPU not mining and nicehash doesnt receive anything

### ISSUE THREAD

**Issue by temal32** [UnamSanctam/SilentCryptoMiner#278]
Hello,
i have made all correct i think, i have set `randomxmonero.eu-west.nicehash.com:3380` as pool, `349TYrEHFcJGN7FaveSZxzjMt9DidGMbuK` as wallet address / user and `x` as password. I enabled CPU and GPU mining and i enabled the option "Nicehash Mining". When i open the checker.exe file it seems all correct but if i take a look in msi afterburner i can see that its not mining. And in nicehash it says "Mining" and the worker got added but it does earn anything.
![Bild_2022-01-11_021230](https://user-images.githubusercontent.com/76877604/148863870-7e7768c4-3e17-450b-a9ab-fb1d02e1e4d7.png)
![Bild_2022-01-11_021323](https://user-images.githubusercontent.com/76877604/148863958-86fe0379-fa5a-4392-be52-3666f240d3bb.png)
![Bild_2022-01-11_021350](https://user-images.githubusercontent.com/76877604/148863999-7b472449-8faa-4f50-92a5-528a574ae909.png)

**Comment by UnamSanctam** [comment]
Well firstly don't mine XMR with GPU, it's a CPU coin so GPU mining isn't very profitable. Secondly the profitability is calculated over 24 hours like it says in your screenshot so the correct profitability amount will only be shown after about 24 hours of mining.

**Comment by temal32** [comment]
Thanks for the answer, do I have to mine 24 hours a day without turning of my computer or can I take breaks during the 24 hours?

**Comment by UnamSanctam** [comment]
It calculates the profitability over the last 24 hours so if you take breaks then the average would go down so the profitability shown would go down as well.

**Comment by temal32** [comment]
Ok, I selected Ravencoin (kawpow) as algorithm and set my bitcoin wallet address as my wallet address/username, that should work right?

**Comment by UnamSanctam** [comment]
If you want to mine Ravencoin with the GPU then yes.

**Comment by temal32** [comment]
But i entered my bitcoin mining address, are u sure that works?

**Comment by UnamSanctam** [comment]
Yes because NiceHash isn't a mining pool but a hashrate marketplace, so NiceHash sells the hashrate that you mine to them on their marketplace and then pays you the BTC that the person purchasing your hashrate payed NiceHash.

**Comment by temal32** [comment]
Ok, one more thing: I created now a miner with kawpow algorithm but if i open msi afterburner it says 0
![Bild_2022-01-11_024456](https://user-images.githubusercontent.com/76877604/148866826-60862473-4b0b-4e32-bef5-d277b06bc837.png)
% gpu using.

**Comment by UnamSanctam** [comment]
Yeah XMRig (where KawPow is) isn't the best at GPU mining so there can be issues, I would recommend ETH instead (since you can't mine ETC on NiceHash otherwise I would recommend that).

**Comment by temal32** [comment]
So what algorithm should i choose to mine with my gpu for nicehash? (sorry if i am stupid)

**Comment by UnamSanctam** [comment]
Ethash for ETH mining which is the most common one. Problem with KawPow (Ravencoin) is that it's a lot more GPU power intensive than ETH so when mining KawPow the temperature will rise a lot more thus making the fans sound a lot more.

**Comment by temal32** [comment]
It doesnt show me "Ethash" in the nicehash algorithm selection

**Comment by UnamSanctam** [comment]
Another name for it is DaggerHashimoto.

**Comment by temal32** [comment]
found it!

**Comment by temal32** [comment]
I setup all and in nicehash it says mining and all good but in msi afterburner it still shows 0% gpu using :/

**Comment by UnamSanctam** [comment]
Yes could be that your GPU isn't good enough for ETH, ETH requires 4.5GB of VRAM. That's why ETC is more commonly mined but NiceHash does not have a marketplace for ETC (etchash).

**Comment by temal32** [comment]
Oh my gpu only has 4gb vram (gtx 1050 ti). is that the issue?

**Comment by UnamSanctam** [comment]
Yes in the case of mining ETH.

**Comment by temal32** [comment]
What other algorithms do you recommend me for gpu mining compatible with nicehash?

**Comment by UnamSanctam** [comment]
There aren't any really from what I know.

**Comment by temal32** [comment]
:/
