### ISSUE TITLE
Combining miners please help

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#280]
So i want to mine ETC and raptoreum

But they have same startup names will that affect anything? also using inject explorer.exe for both of them

**Comment by Brainshot** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
Yeah just add both in the "Miners" list, doesn't matter if they have the same injection program.

**Comment by Brainshot** [comment]
> Yeah just add both in the "Miners" list, doesn't matter if they have the same injection program.

causes bad lag even though i have the cpu mining on 10 - 20%

and gpu one at 10%

**Comment by UnamSanctam** [comment]
You're most likely running out of VRAM then.
