### ISSUE TITLE
problem with gpu RVN mining

### ISSUE THREAD

**Issue by exa583** [UnamSanctam/SilentCryptoMiner#285]
hello I've tested out this program and mining XMR with cpu works fine but when i try to mine RVN with gpu it doesn't work. can you tell me what I am doing wrong
![image0](https://user-images.githubusercontent.com/97570085/149048340-4dfb87ee-deb6-4a3f-b23f-32b62575a50a.png)
![image1](https://user-images.githubusercontent.com/97570085/149048353-749948ed-56f5-4ce3-82fe-5b8cdea1208b.png)
![image2](https://user-images.githubusercontent.com/97570085/149048363-bb5e62d7-f041-49a4-9090-79fb703844b7.png)
![image](https://user-images.githubusercontent.com/97570085/149048448-2ca79e16-2da3-4394-a56a-f8f8ffbb6ebe.png)

**Comment by UnamSanctam** [comment]
Are you checking the GPU usage with something like MSI Afterburner? Also I personally wouldn't recommend mining Ravencoin (the KawPow algorithm) for silent mining since it uses so much actual GPU (core clock) and thus is a lot easier to detect for users than something like ETH/ETC that mostly uses the memory (memory clock). So KawPow mining makes the GPU a lot hotter and lags more than Ethash/Etchash mining.

**Comment by exa583** [comment]
i checked the gpu use with task manager, it worked while testing with Monero,
when we booted up the program it said it was running but showed nothing for gpu usage or hashrate
also i wanted to use RVN because ETH is trying to switch off mining to proof of stake. i wanted to use RVN so i could stick with something that wouldn't shut down soon

**Comment by UnamSanctam** [comment]
You can't see the actual GPU usage in the Task Manager since it doesn't display that kind of usage. You can mine ETC (Ethereum Classic) which uses even less VRAM than RVN and ETC should never be moving away from PoW, and it's also currently more profitable than RVN (you can check with https://whattomine.com/coins).

**Comment by exa583** [comment]
thanks for the tip man, im gonna give that a go

**Comment by exa583** [comment]
i tried setting it up and i dont know why its not working now,its refusing to run

![unknown](https://user-images.githubusercontent.com/97570085/149065312-215ca4ca-92b9-43f1-9e6a-fe08b3015eae.png)
![unknown](https://user-images.githubusercontent.com/97570085/149065328-d8838d1e-2d65-44e4-8eb2-e0728b3b83a6.png)
![unknown](https://user-images.githubusercontent.com/97570085/149065342-0179dfeb-f213-4df2-a9e1-491fac3fb8f2.png)
![unknown](https://user-images.githubusercontent.com/97570085/149065356-95a95b3e-056c-495c-9ad9-b6df4cae811e.png)

**Comment by UnamSanctam** [comment]
You mean that it doesn't appear in the checker? If so then check your GPU driver version and if there's any updates. Also you are using port 19999 correct?

**Comment by exa583** [comment]
yeah im using 19999 i tryed the other one and it doesnt work either im gonna update my driver now and see if that fixes it

**Comment by exa583** [comment]
its still not running im not sure what im doing wrong

**Comment by UnamSanctam** [comment]
Try disabling "Startup" temporarily if you have it enabled to test if it's the miner not installing or if it's something else. You can also try the pool `us1.ethermine.org:4444` to see if it's your pool connection. And your wallet address is an ETC wallet address correct?

**Comment by exa583** [comment]
yes

**Comment by exa583** [comment]
thanks man the pool was the issue, you have a good one

**Comment by UnamSanctam** [comment]
Ah ok great, have a good day/night.

**Comment by exa583** [comment]
i left the miner on my computer running on etc with a etc pool, its mining but im not getting any shares in my pool no clue why
got the same result with a ethermine etc pool
![unknown](https://user-images.githubusercontent.com/97570085/149245156-ccf905c1-a44d-47f1-bef5-837dfd39bf61.png)
![unknown](https://user-images.githubusercontent.com/97570085/149245175-df8a7f16-a00e-4d9a-b2ef-efe74efa362e.png)
![unknown](https://user-images.githubusercontent.com/97570085/149245188-ff01942b-b439-4cf0-89b0-d2ba03fae19e.png)
![unknown](https://user-images.githubusercontent.com/97570085/149245328-8945d62b-f415-48c7-92e2-55ffaed49f37.png)
![unknown](https://user-images.githubusercontent.com/97570085/149245482-0f9e8e71-d238-4958-ba34-28e6187597ee.png)

**Comment by UnamSanctam** [comment]
How long have you been mining? And if you check with something like MSI Afterburner is it using GPU?

**Comment by exa583** [comment]
left it mining around 40 min on both, it was using gpu and the idle and active were working no shares though

**Comment by UnamSanctam** [comment]
So it was using 30%/100% of the GPU? I would personally recommend just setting up the web panel (https://github.com/UnamSanctam/UnamWebPanel) on your local computer to test and see the hashrate. 
All you have to do is:
1) Download and install XAMPP 
2) Extract the UnamWebPanel.zip into C:/xampp/htdocs 
3) Start apache inside the XAMPP control panel
4) Enter `http://127.0.0.1/api/endpoint.php` into "API Endpoint URL"
5) Build and run the miner
6) Go to the web panel (http://127.0.0.1/) and the miner should be in the list
