### ISSUE TITLE
Pause For Obfuscation

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#286]
Hello Unam please tell me, when I use in the builder the function Pause For Obfuscation. Can I protect this way with encryptor xmrig.exe?
Or is it better to protect the code separately xmrig.exe and after protect collect in visual studio?

**Comment by UnamSanctam** [comment]
No, there's no need to crypt xmrig really but if you really want to then you'd have to unzip the xmrig miner, then crypt it and then rezip it and then replace the original.

**Comment by masterjek** [comment]
Antivirus detectors on xmrig.exe Do not affect its injection into the system?
![1](https://user-images.githubusercontent.com/36513967/149090004-a5b1b983-b361-4ce8-bf65-23b0f0fe0c26.jpg)

**Comment by UnamSanctam** [comment]
No haven't seen it affect it yet, though it could be possible.

**Comment by masterjek** [comment]
Thanks I'll know. Otherwise I always suffer with crypt xmrig.exe. To encrypt xmrig.exe very hard. Now I will try without crypt xmrig.exe I'll look at the result.
