### ISSUE TITLE
Web panel

### ISSUE THREAD

**Issue by Yara-web** [UnamSanctam/SilentCryptoMiner#287]
Dear UnamSanctam, I am a beginner web developer, please give detailed instructions on how to set up a web panel. P.S. (Your product is very good)

**Comment by UnamSanctam** [comment]
You can just extract all the files from the latest release https://github.com/UnamSanctam/UnamWebPanel/releases into your webserver and then it will work. You can find more detailed instructions here: https://github.com/UnamSanctam/UnamWebPanel#setup if needed.
