### ISSUE TITLE
Accidently

### ISSUE THREAD

**Issue by KOHnani1** [UnamSanctam/SilentCryptoMiner#288]
i just do something pretty bad is i just delete the uninstaller of the app i just install , i wonder how can i remove that without the uninstaller , is it possible ?

**Comment by WilleD70** [comment]
rip

**Comment by zanatechnology** [comment]
if you did saved your settings try load them and create same name and data miner again

**Comment by UnamSanctam** [comment]
You should be able to follow this: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner and get it removed.
