### ISSUE TITLE
WebPanel Database

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#291]
I downloaded WebPanel and opened the database file with notepad. I see this piece of code there.
![3](https://user-images.githubusercontent.com/36513967/149209398-2ce42159-3710-4395-912d-affde493721f.jpg)
These are not my settings at all, and so on. Is that how it should be?

**Comment by UnamSanctam** [comment]
Looks like residue data from the wiki example, can clean it but shouldn't affect anything.

**Comment by UnamSanctam** [comment]
Or could be the settings from the guy who helped me find the null hashrate error as well, none of that shows up in any database explorer.

**Comment by masterjek** [comment]
Understood thanks. I also want to ask you, I opened the Web panel database on the hosting. There, half is displayed as in the screenshot.
![4](https://user-images.githubusercontent.com/36513967/149215730-7291645b-28ac-4231-8bc5-a2976e81396d.jpg)
This is fine?

**Comment by UnamSanctam** [comment]
Yes that's fine, here's a cleaned database if you want that: [unamwebpanel.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7857566/unamwebpanel.zip)

**Comment by masterjek** [comment]
Thank you)
