### ISSUE TITLE
reported hashrate

### ISSUE THREAD

**Issue by KAMLEGENDZ** [UnamSanctam/SilentCryptoMiner#292]
why in nanopool and ethermine there isn't Last Reported Hashrate

**Comment by UnamSanctam** [comment]
You'd have to enable it, it's not enabled by default since it takes more performance from the pool and isn't always reliable.

**Comment by KAMLEGENDZ** [comment]
which option should be checked

**Comment by UnamSanctam** [comment]
Enable "Advanced Parameters" and then enter `--report-hr` into the field. Keep in mind that reported hashrate can be a bit deceiving depending on the pool.

**Comment by KAMLEGENDZ** [comment]
i can change this directly in the web panel

**Comment by UnamSanctam** [comment]
No because I would have to create my own logic just for that which I haven't.

**Comment by KAMLEGENDZ** [comment]
ok and i want use antpool but i dont know how to replace in the json config
![image](https://user-images.githubusercontent.com/86577993/149338331-e8d6023e-3b0c-4846-af00-56504cce7543.png)

**Comment by UnamSanctam** [comment]
No since if you did not have it enabled then the GPU library files have not been embedded into the miner, so if it "GPU Mining" was disabled then the files required for XMRig CUDA mining doesn't exist.

**Comment by UnamSanctam** [comment]
Monero and Raptoreum mining personally has never given me any lag. Ravencoin (KawPow) is an intensive GPU coin to mine which is why it causes a lot of lag.

**Comment by KAMLEGENDZ** [comment]
ok and if I activate GPU mining when creating the mine, I could deactivate it later on the webpanel ?

**Comment by KAMLEGENDZ** [comment]
a miner can be put on pause ?

**Comment by UnamSanctam** [comment]
You can add explorer.exe into "stealth-targets" and it will be paused forever or until you remove it from "stealth-targets".

**Comment by KAMLEGENDZ** [comment]
genius
