### ISSUE TITLE
Question about web api

### ISSUE THREAD

**Issue by zhimiyouwu33** [UnamSanctam/SilentCryptoMiner#293]
HI buddy.

Thank you for sharing the project.

When I run it on a server with system privileges, the miner and watchdog run smoothly, but the API doesn't. When running with Administrator privileges, the API works fine again. I tested on windows2012+. I did not check the Administrator option. How can this problem be improved?

**Comment by UnamSanctam** [comment]
Is the web panel hosted on an external server on locally on the same server?

**Comment by zhimiyouwu33** [comment]
Yes, the web panel is on the same VPS as my xmr-porxy.

> Web 面板是否托管在同一服务器上本地的外部服务器上？
Yes, the web panel is on the same VPS as my xmr-porxy.

**Comment by UnamSanctam** [comment]
Is the web panel on the same VPS as the miner you're running?

**Comment by zhimiyouwu33** [comment]
Run miner check.exe
miner: YES
watchdog: YES
check other:
xmr-proxy-webpanel: YES
UnamWebPanel v1.4.1: Only other ones online as Administrator

> Is the web panel on the same VPS as the miner you're running?

**Comment by UnamSanctam** [comment]
Could be that the firewall on the server that the miner is running on could be blocking the web requests. Try temporarily disabling the firewall. If it's not that then I'd need more information on how it's set up to know where the problem could be.

**Comment by zhimiyouwu33** [comment]
> Could be that the firewall on the server that the miner is running on could be blocking the web requests. Try temporarily disabling the firewall. If it's not that then I'd need more information on how it's set up to know where the problem could be.

It seems to be a firewall problem, I tried the virtual machine Win2012R2 and Win2016 can go online, other machines on the RAT can not. I will try to test bypass with other loader.
