### ISSUE TITLE
Question about ZelCore

### ISSUE THREAD

**Issue by teraso11** [UnamSanctam/SilentCryptoMiner#294]
Hi, I have one question, how can I mine Raptoreum in this wallet when it changes adress all the time?

**Comment by teraso11** [comment]
Now for some reason it give me same address. Before this, whenever I've started my wallet it gave me a different address

**Comment by teraso11** [comment]
thank you btw

**Comment by teraso11** [comment]
Did you started using Session?

**Comment by UnamSanctam** [comment]
No currently only Telegram and Hugin. But for ZelCore make sure that you're entering the same Username and Password, they are what dictate your private key so if they're different then you will have another private key (another wallet).
