### ISSUE TITLE
Question : What would be the best pool

### ISSUE THREAD

**Issue by dingodingo2** [UnamSanctam/SilentCryptoMiner#295]
What would be the best monero pool to avoid ban ?

**Comment by UnamSanctam** [comment]
Nanopool never bans but they do have quite a high share difficulty which can be annoying. There's also 2miners which is widely used as well.

**Comment by dingodingo2** [comment]
Oh okay. And do you have any experience with minexmr.com ?

**Comment by UnamSanctam** [comment]
Yes but don't use MineXMR or SupportXMR, they are the two worst pool for silent mining, they have quite strict ban policies.

**Comment by dkroen17** [comment]
What are banning policies?

**Comment by UnamSanctam** [comment]
Their policies for banning miners, you can find MineXMR's policy at the bottom of this page: https://minexmr.com/miningguide
