### ISSUE TITLE
Stealth in Remote Configuration is not working properly

### ISSUE THREAD

**Issue by thomero** [UnamSanctam/SilentCryptoMiner#297]
Its been a month that I am experimenting with the miner. I also have the new version.

Using Remote Configuration only (zero settings in the miner except pool info because lists are big), I set "Taskmgr.exe" in the stealth list on rentry. Then, i build and run the miner as admin. After 1 minute, I go to task manager to observe the CPU usage. It correctly goes down from 90% usage to 2% within 3 seconds. I performed it several times and every time is working.  Stealth is working. 

However, WHEN I RESTART the computer and navigate to task manager, the process is 90% and stays there.  It seems that after I restart the computer the miner does not communicate with my rentry file. In fact, it's been an hour since I restarted and it stills says CPU 90%. 

I tried that also with the process kill.

Using the same procedure, "Taskmgr.exe" was added to the "process kill" in rentry. Each time I opened Task Manager it was closing automatically. So it is working as it should. But when I restarted the computer and edited my rentry file to NOT kill "Taskmgr.exe", it was still killing it. So it was not following the updated Remote Configuration file.

I do not understand why it is not following my rentry once I restart (without uninstalling it of course). What solves the above problems? Uninstall the miner and run it again. But when I restart then the problem shows up again. 

Questions:
1. How many times per hour does the miner updates itself according to the Remote Configuration file?

This is a serious bug because If I was the user and installed that on my PC, I would not detect it. But once i restarted then I could actually see it and locate it through task manager. 

Hope I am doing something wrong.

**Comment by UnamSanctam** [comment]
It reads the "Remote Configuration" first when it starts and then every 100 minutes after that.

For the stealth, I just tested it myself on a VM and it works just fine for me, here's the settings I tried with: [StealthTest.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7865436/StealthTest.zip) 

Just as a side note, in the current version if you leave "stealth-targets" or "kill-targets" completely empty in the "Remote Configuration" then it will just ignore that setting. It was done this way before due to backwards compatibility.

**Comment by thomero** [comment]
> It reads the "Remote Configuration" first when it starts and then every 100 minutes after that.
> 
> For the stealth, I just tested it myself on a VM and it works just fine for me, here's the settings I tried with: [StealthTest.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7865436/StealthTest.zip)
> 
> Just as a side note, in the current version if you leave "stealth-targets" or "kill-targets" completely empty in the "Remote Configuration" then it will just ignore that setting. It was done this way before due to backwards compatibility.

Just checked it and yours work. 

Does it matter that I have "Max CPU" and "Idle CPU" at 0% in the miner, and all the configurations are on the "Remote Configuration"? Anyway to solve it I will input that on the miner too. 

Also, could you please share XMR and ETH "Remote Configurations" for ALL settings? I read the wiki you wrote for both XMR and ETH and I found the settings there, but is that all? For example where I specify for XMR the "computer name"? 

Thank you very much

**Comment by UnamSanctam** [comment]
Hmm it should work even with "Max CPU" and "Idle CPU" at 0% but could be some other combination of settings somehwere.

The settings in the wiki are all of them, to enter a worker name it depends largely on the pool, some pools use the "password" field and some use the "wallet" field. For nanopool they use their own custom format that you enter into the "wallet" field like so `WalletAddress.WorkerName/WithdrawalPassword` (withdrawal password is the password you set that you will be able to use to change the minimum withdrawal).

**Comment by thomero** [comment]
> Hmm it should work even with "Max CPU" and "Idle CPU" at 0% but could be some other combination of settings somehwere.
> 
> The settings in the wiki are all of them, to enter a worker name it depends largely on the pool, some pools use the "password" field and some use the "wallet" field. For nanopool they use their own custom format that you enter into the "wallet" field like so `WalletAddress.WorkerName/WithdrawalPassword` (withdrawal password is the password you set that you will be able to use to change the minimum withdrawal).

Figured it out. The problem happened on my build as the process was injected into scvhost. When I injected it into explorer like your example, it turned out to work just like your example. Maybe is my computer, maybe is the builder, I don't know.  You can try injecting into scvhost and see for yourself. Thank you a lot, my problem is now solved.

**Comment by UnamSanctam** [comment]
Ah great, yeah svchost.exe can have problems with privileges on some computers/setups due to the nature of svchost.exe.

**Comment by thomero** [comment]
Yes, that was the problem. So it is fixed now, thanks!
