### ISSUE TITLE
Can't build the miner

### ISSUE THREAD

**Issue by CesarSGZ** [UnamSanctam/SilentCryptoMiner#298]
I am getting this error: https://i.gyazo.com/e04b54f2bb2d1a3d7f9a609b409f8bb1.png
In the log I see this: "H:\Silent.Crypto.Miner.Builder\Silent.Crypto.Miner.Builder" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
H is an external USB device but I also tried doing it in my own computer with the same result.

**Comment by UnamSanctam** [comment]
Build it in another less complicated folder (name/path), windres is quite sensitive. So for example build it in a single simple folder on the desktop.

**Comment by UnamSanctam** [comment]
Yes like I said
>Build it in another less complicated folder (name/path), windres is quite sensitive. So for example build it in a single simple folder on the desktop.

The problem is most likely the (1) part of your path.

Just install it in a folder on your desktop called "Miner".

**Comment by CesarSGZ** [comment]
> 

I've already tried this bro that's what I am trying to say

**Comment by UnamSanctam** [comment]
Post the full path of the folder your trying to build to.

**Comment by CesarSGZ** [comment]
Okey I've just solved it. It was the Windows SmartScreen or Windows Defender or something like that, that was blocking the file to be created. I deactivated everything and it finally created the miner. Thanks anyway bro!
