### ISSUE TITLE
encryption

### ISSUE THREAD

**Issue by cscscsf** [UnamSanctam/SilentCryptoMiner#299]
Hi bro.
I will use google translate.
First of all, I would like to thank you for this work on the software. Could you elaborate on how to encrypt correctly? So that the person who does this understands. After
encryption with a pause watchdog timer + miner, the program does not work. If you encrypt without a pause, run-time bypass does not work. Sorry for google translate. thank you.

**Comment by Gopnitsa** [comment]
+1 up up up up

**Comment by UnamSanctam** [comment]
Sorry for missing this one, if you still need it you can find more information here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-can-i-decrease-detections. Some obfuscations or crypters can sometimes break things, such as resource encryptions since the miner already does that.
