### ISSUE TITLE
Problem with rootkit

### ISSUE THREAD

**Issue by teraso11** [UnamSanctam/SilentCryptoMiner#300]
Hi, problem is not only present on Win 8, it is also on win 10. Two nslookup.exe CMD windows pop up but it works, on win 8 it get nslookup crashed and miner stops working.

**Comment by teraso11** [comment]
And only etc miner are working, monero does not on win 10. Same build without rootkit does not have any of those problems

**Comment by UnamSanctam** [comment]
How are you checking if they work? The checker?

**Comment by teraso11** [comment]
Via my proxy and panel. I didn't get connection to xmrig proxy nor panel

**Comment by teraso11** [comment]
And also checker reports only etc miner

**Comment by UnamSanctam** [comment]
Hmm, so most likely the problem is something with how the computers are set up then (or if there are any corrupt files). When it test it (the rootkit) I use a few different VMs all on different Windows versions and updates. I have one Windows 11, four Windows 10 VMs, my normal main Windows 10 computer, two Windows 8 and two Windows 7 and the rootkit works flawlessly for me on all of them. So most likely the problem has something to do with how the computer is set up, problem is just finding what the difference is.

**Comment by teraso11** [comment]
I know how you will get a problem 100% of the time. Download windows 8.1 industry pro. https://www.microsoft.com/en-gb/download/details.aspx?id=40745 On every installation it make problems. Also it can't inject in nslookup on this and simillar windows versions

**Comment by teraso11** [comment]
You will need this serial key when installing: NMMPB-38DD4-R2823-62W8D-VXKJB

**Comment by UnamSanctam** [comment]
Ok, I guess nslookup could maybe be corrupt on some computers or something, could you try disabling the rootkit and choosing `nslookup.exe` as the "Inject Into" in your miners to see if they can run normally at all as nslookup?

**Comment by teraso11** [comment]
Yea, when I inject it crashes. On every build of this windows, even the clean one. You will find a lot of problems with this build of windows. I don't know why I never reported to you. Most likely because explorer.exe injection worked all the time so I didn't bothered, but now when there is rootkit which is incredible, I think it is worth it

**Comment by teraso11** [comment]
Also I've created build on this version of win so maybe that creates a problem on win 10?

**Comment by UnamSanctam** [comment]
Hmm, I just tried installing a miner with the rootkit on a VM with the Windows 8 ISO you sent above and everything works completely fine for me. The miner is running and it's all hidden by the rootkit.

**Comment by teraso11** [comment]
wow strange, can it be hardware based?

**Comment by UnamSanctam** [comment]
Maybe I'm not sure, since everything is working fine for me it could be a possibility. If you inject into any other program from the "Inject Into" selection does it work?

**Comment by teraso11** [comment]
I will try now

**Comment by teraso11** [comment]
svchost.exe work without any problem

**Comment by teraso11** [comment]
now when I've mixed injections it injects even nslookup.exe

**Comment by teraso11** [comment]
<img width="582" alt="Screenshot 2022-01-14 at 11 32 17" src="https://user-images.githubusercontent.com/96477056/149501400-cc3ad68a-4fde-41f6-a038-f42a8b59c56e.png">

**Comment by teraso11** [comment]
with rootkit I get this

**Comment by teraso11** [comment]
But now only nslookup.exe injection seems to work fine without rootkit

**Comment by UnamSanctam** [comment]
Hmm, really bizarre. Seems like injection is failing maybe but I've never seen that before.
