### ISSUE TITLE
How about adding a mining ton? 

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentCryptoMiner#301]
?

**Comment by UnamSanctam** [comment]
Ton?

**Comment by Toxenskiy** [comment]
+

**Comment by Toxenskiy** [comment]
yes

**Comment by UnamSanctam** [comment]
You mean the cryptocurrency Toncoin?

**Comment by UnamSanctam** [comment]
Not sure if I will add MintoaurX (what Toncoin uses for CPU mining) but if I will then it will probably take a month or two.
