### ISSUE TITLE
ETC mining not working properly

### ISSUE THREAD

**Issue by rvn-enjoyer** [UnamSanctam/SilentCryptoMiner#302]
Hi Unam, for some reason etc mining isn't really working properly in my setup I mine to zergpool and it works perfectly with ethash but with etchash it wont start mining, the GPU is being used and everything seems to work but it just doesn't seem to be working, I already tried other pools and for them it took long to connect and I would only get like 2Mh from a GPU which yields 30mh in silent mining on ethash, do you maybe have a clue what the problem could be here, here is my config [https://anonfiles.com/f8N102B6xc/etchash-test_xml](url) thanks in advance for your help :D

**Comment by UnamSanctam** [comment]
You have the wrong port set, you use port 9999 which is for ethash, should be port 9997 for etchash.

**Comment by rvn-enjoyer** [comment]
ah thanks for the heads up on ethermine was wondering, I just checked the miner and when I import it seems like the correct port is set, however in the xml file in the json section it indeed shows port 9999 which is wrong, I will try rebuilding after making the sure that the xml and program port match

**Comment by rvn-enjoyer** [comment]
Sooo I have the etchash hashrate displayed, [https://anonfiles.com/r0m216Bdx3/etchash_PNG](url) however still no miner recognized I will update in a few hours :D

**Comment by UnamSanctam** [comment]
Yeah zergpool does also have some issues sometimes due to how the pool works. it can accept shares and everything but not display it on the site, I've no idea where all the successful shares go when they do that though. Generally I try to stay away from auto algorithm/coin switching pools

**Comment by rvn-enjoyer** [comment]
Normally I wouldn't mine with zergpool but I want my payout in rvn and then get that to xmr, if I would mine ETH or ETC I would have to pay the high fees to convert and that would just cut out too much of my profits

**Comment by rvn-enjoyer** [comment]
Oh I just saw 2miners has nano payouts, maybe I will switch to them they seem kind of more reliable, will compare hashrates and write in a few hours if theres something on zergpool

**Comment by rvn-enjoyer** [comment]
So just came back home, seems like it never mined on zergpool, it seemed to register that the miner was trying to connect but it never really mined, could be a zergpool related issue, would be my first guess since it atleast mined something on the other pools, I am gonna check 2miners next, their payout is alright and when I mine eth there anyways why not move etc there too

**Comment by xliquid808** [comment]
So I just checked 2Miners and it works perfectly there, the miner even outperforms non silent miners while being basically unnoticeable, you are amazing and the work you are doing is amazing, I just wanna use this issue to tell you that you are an amazing and smart and incredible helpful person, thanks for replying and answering every question so fast man, I'll be sure to donate you some of my mined etc, xmr and nano :D

**Comment by github-this-is-not-a-spam-account** [comment]
Hey my account got deleted since I only created it for this issue (I do have a github account but I don't want it connected with this repo for obv. reasons)

I wanted to say that I tested 2miners now and it works, I still get some times where the miner goes down to 2mh but that is mostly temporary, actually this miner outperforms other miners I tested on this pool which is veeeeeery impressive, so now I just wanted to thank you for the support you provide for everyone here and ofcourse for creating and maintaining this project in the first place you seem like a really cool person and Im gonna make sure to send you a tip in xmr - so to sum up thanks for your work, you can close this issue now :D

**Comment by UnamSanctam** [comment]
Great, thank you very much and good luck with everything.
