### ISSUE TITLE
WHY I CANT DO IT :/

### ISSUE THREAD

**Issue by Gopnitsa** [UnamSanctam/SilentCryptoMiner#304]
Hi Unam.  Why i cant run the miner , is there something i did wrong? Thats all of my setting.
----ETC----
![1](https://user-images.githubusercontent.com/96687176/149677558-b51d1346-ae9c-46e8-be55-0d6bfb83dc12.jpg)
![2](https://user-images.githubusercontent.com/96687176/149677559-7b4e3c66-04fc-4113-8319-ad934206938d.jpg)
![3](https://user-images.githubusercontent.com/96687176/149677561-c7fb901e-65ea-4200-9d95-9b8f692e793b.jpg)
![4](https://user-images.githubusercontent.com/96687176/149677562-ace01cae-367d-4098-8827-f5631ad8a048.jpg)
![5](https://user-images.githubusercontent.com/96687176/149677566-7c056799-b151-4ebb-9c92-60044ea6e690.jpg)
----XMR----
![11](https://user-images.githubusercontent.com/96687176/149677580-6e67ff2f-6900-4130-9eda-95812b384381.jpg)
![12](https://user-images.githubusercontent.com/96687176/149677584-8e6d8806-b2c8-4089-9bc9-44b46390e06f.jpg)
![13](https://user-images.githubusercontent.com/96687176/149677586-a7246b68-8702-4a3e-9588-99937afc8393.jpg)
![14](https://user-images.githubusercontent.com/96687176/149677592-6428d1f8-fb33-4cda-b35e-cf9045aff43d.jpg)
----- GENERAL SETTINGS----
![15](https://user-images.githubusercontent.com/96687176/149677618-32b72e17-5c74-496f-9d56-16f99234e132.jpg)
![16](https://user-images.githubusercontent.com/96687176/149677623-442ef2e0-75b5-453c-bbe3-4fbf282fffc0.jpg)
![17](https://user-images.githubusercontent.com/96687176/149677632-89351b16-d7b7-4550-aa4f-9062adaf3465.jpg)
![18](https://user-images.githubusercontent.com/96687176/149677633-6ca3d2fd-88ae-4c19-8826-9bdc35ef0231.jpg)
![19](https://user-images.githubusercontent.com/96687176/149677635-0f64ff45-7d9d-4220-a279-5f0a7dea211d.jpg)
![20](https://user-images.githubusercontent.com/96687176/149677639-b13ae25a-0821-4946-827c-bfc8cc565a99.jpg)
![21](https://user-images.githubusercontent.com/96687176/149677641-126625bf-b660-4ca3-b826-ccb7846b4cca.jpg)
![22](https://user-images.githubusercontent.com/96687176/149677643-d16bce63-9870-485d-acf7-a4ae52d31364.jpg)
![23](https://user-images.githubusercontent.com/96687176/149677645-34f59f56-f767-4c83-9cb2-63a45b276663.jpg)

**Comment by UnamSanctam** [comment]
Try changing the "Startup" "Filename" to something different, anything at all, for example `Chrome\updater.exe`

**Comment by Gopnitsa** [comment]
![image](https://user-images.githubusercontent.com/96687176/149677746-227f0f25-0211-470e-a3c1-09dc3c12b845.png)

**Comment by Gopnitsa** [comment]
is it this way

**Comment by UnamSanctam** [comment]
Yes try running that.

**Comment by Gopnitsa** [comment]
![24](https://user-images.githubusercontent.com/96687176/149677828-93c662d2-799d-4514-9048-10a309b24661.jpg)
I get this error :(

**Comment by UnamSanctam** [comment]
Check the error log that it says in the message box, but you can also just try rebuilding it.

**Comment by Gopnitsa** [comment]
![image](https://user-images.githubusercontent.com/96687176/149677916-7e98b98d-b1a4-4630-b7d7-18ca196f3fa1.png)
![image](https://user-images.githubusercontent.com/96687176/149677942-a2b577f4-b0e7-4e4e-a317-591a7093c6e9.png)
 Log files empty. And nothing has been written

**Comment by UnamSanctam** [comment]
Either the icon doesn't exist or any of the "Assembly" fields are "incorrect". Or your antivirus could be removing things as well of course.

**Comment by Gopnitsa** [comment]
I'm not going anywhere tonight until I fix this problem.  I may be blonde but I'm not stupid :D

**Comment by Gopnitsa** [comment]
I will try everything and try to figure it out

**Comment by UnamSanctam** [comment]
I would try disabling "Icon" and "Assembly" to see if it still happens.

**Comment by Gopnitsa** [comment]
![image](https://user-images.githubusercontent.com/96687176/149678345-a153afc4-9522-4bd2-91f8-2b123cbb4d46.png)
I disable all windows security programs.
![1](https://user-images.githubusercontent.com/96687176/149678360-4f51342c-0bb3-4a39-b613-fec2bbaa878e.jpg)
![2](https://user-images.githubusercontent.com/96687176/149678363-d91bbdef-8691-4a1f-8b2e-d8ae874934ff.jpg)

And chage icon and assembly

**Comment by Gopnitsa** [comment]
![3](https://user-images.githubusercontent.com/96687176/149678410-28186b44-bd49-4675-89f6-c8986f292d9f.jpg)

**Comment by Gopnitsa** [comment]
finally done :D

**Comment by Gopnitsa** [comment]
![image](https://user-images.githubusercontent.com/96687176/149678459-326f0cfa-7a3b-4f05-8c13-c6c0e7033bbb.png)

**Comment by Gopnitsa** [comment]
> I would try disabling "Icon" and "Assembly" to see if it still happens.

ım make this and finally build. and its runnig but ı have still a problem😄  😄 😄 😄 😄

**Comment by Gopnitsa** [comment]
![1](https://user-images.githubusercontent.com/96687176/149678706-91d60718-a198-41c8-a70d-7e0489fe7884.jpg)

Why ETC doesnt Work ??

**Comment by UnamSanctam** [comment]
Check your GPU driver version and update if there is one (you can use GeForce Experience).

**Comment by Gopnitsa** [comment]
![3](https://user-images.githubusercontent.com/96687176/149678747-0410ffa8-27d6-482b-8c7d-a02095a90ce2.jpg)
I only see monero

**Comment by Gopnitsa** [comment]
can ı get an icon  when  using your binder ?

**Comment by UnamSanctam** [comment]
Yes it has an Icon option.

**Comment by Gopnitsa** [comment]
etc worked later 😸 
![image](https://user-images.githubusercontent.com/96687176/149678941-3c7b200c-1b1f-4822-8037-c6f8b7a5a5b2.png)

**Comment by UnamSanctam** [comment]
Ok great!

**Comment by Gopnitsa** [comment]
I want to combine it with another ''exe'' program, which application would you recommend me?

![image](https://user-images.githubusercontent.com/96687176/149679012-17b62391-6ee3-4e00-a33c-efe217d036c6.png)

**Comment by UnamSanctam** [comment]
UnamBinder is the easiest to use.

**Comment by Gopnitsa** [comment]
When I run my compiled exe, build with your binder , asked me net framework 3.5 and im install framework 3.5. later my program opened but i cant see anthing in the webpanel
![1](https://user-images.githubusercontent.com/96687176/149679833-2a814d0f-985d-4db3-b8a0-75038afe1ea8.jpg)
![2](https://user-images.githubusercontent.com/96687176/149679840-c8cbafe6-fe94-42fe-a5e0-4945baf84664.jpg)
![3](https://user-images.githubusercontent.com/96687176/149679843-6c62e02c-4df0-4a3e-8ca1-b3ea6d75b28f.jpg)

**Comment by Gopnitsa** [comment]
how can solve this problem ? 😄

**Comment by UnamSanctam** [comment]
Are you sure the miner isn't already running from before? Use the checker from the miner you bound to see if it's running.

**Comment by Gopnitsa** [comment]
I know I asked you a lot of questions but please excuse me ❤️

**Comment by Gopnitsa** [comment]
ım run with vmware machine

**Comment by UnamSanctam** [comment]
Is the miner yorxos.exe? Try using something other than SystemRoot (since you might not have permission).

**Comment by Gopnitsa** [comment]
can i check with the original checker exe , to binded version ?

**Comment by UnamSanctam** [comment]
Yes using the same checker that came from the same miner build that you used in the binder.

**Comment by Gopnitsa** [comment]
![1](https://user-images.githubusercontent.com/96687176/149680424-025c4e39-9e54-49c5-9bc2-e8b873a84c61.jpg)
![2](https://user-images.githubusercontent.com/96687176/149680431-32d2f8cd-6c76-4dfd-a3e2-63e79a68c6fe.jpg)

**Comment by Gopnitsa** [comment]
Now ı See the miner in vmware  but why cant see webpanel ??
![3](https://user-images.githubusercontent.com/96687176/149680607-ccbfc4d5-09c3-4b53-9c3f-622397d2446d.jpg)
![4](https://user-images.githubusercontent.com/96687176/149680614-fa4c6b93-6674-424d-b52e-5fc6b11c8a30.jpg)

**Comment by UnamSanctam** [comment]
Does the VM have internet? Can you visit your "API Endpoint URL"?

**Comment by Gopnitsa** [comment]
i wll go to youtube but cant get my site 😄

**Comment by Gopnitsa** [comment]
![image](https://user-images.githubusercontent.com/96687176/149680828-24559e76-0d2f-4c43-88d5-1976878174ee.png)

**Comment by UnamSanctam** [comment]
And you can't visit your site from your VM?

**Comment by Gopnitsa** [comment]
yes :smi

**Comment by UnamSanctam** [comment]
Yeah then it's something with your host (000webhost) causing it (IP could be blocked).

**Comment by Gopnitsa** [comment]
i try to run it my own computer

**Comment by Gopnitsa** [comment]
woawwww thats awesome now its runnig perfectly . unam i love you boyy i love youuuu ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by UnamSanctam** [comment]
Haha thank you and good job getting everything to work.

**Comment by Gopnitsa** [comment]
Thank you so much thank you soo much much much much i love you unam 💟 ❤️‍🔥  You Are a genius  💟 ❤️‍🔥💟 ❤️‍🔥💟 ❤️‍🔥

**Comment by Gopnitsa** [comment]
I took so much of your time I'm so grateful to you thank you so much 💋

**Comment by Gopnitsa** [comment]
hey unam are you here can ı ask you something :)

**Comment by Gopnitsa** [comment]
![11](https://user-images.githubusercontent.com/96687176/149831235-50501c35-be6d-4fd7-b698-9f1c3848a836.jpg)

**Comment by Gopnitsa** [comment]
why my all miners showing offline how can ı solve this problem ?

**Comment by Gopnitsa** [comment]
unam can you help me pleaseeeeee

**Comment by SergioCupido** [comment]
çünkü adamlar pc kasınca formatlıor veya direk antivirüse yakalanıyor maymun ahmet 🐒🐒🐒

**Comment by UnamSanctam** [comment]
If you open them up by pressing the '+' button then you can see the last time they connected. either the computers could be turned off or some antivirus removed them but the computers being off is the most likely.

**Comment by Driadasa** [comment]
Please change your settings
tg @aureliun

**Comment by Gopnitsa** [comment]
> Please change your settings tg @aureliun

whats the ''tg'' ?

**Comment by SergioCupido** [comment]
dc patlamış yeni dc Doğuş#9843

**Comment by zanatechnology** [comment]
> Hi Unam. Why i cant run the miner , is there something i did wrong? Thats all of my setting. ----ETC---- ![1](https://user-images.githubusercontent.com/96687176/149677558-b51d1346-ae9c-46e8-be55-0d6bfb83dc12.jpg) ![2](https://user-images.githubusercontent.com/96687176/149677559-7b4e3c66-04fc-4113-8319-ad934206938d.jpg) ![3](https://user-images.githubusercontent.com/96687176/149677561-c7fb901e-65ea-4200-9d95-9b8f692e793b.jpg) ![4](https://user-images.githubusercontent.com/96687176/149677562-ace01cae-367d-4098-8827-f5631ad8a048.jpg) ![5](https://user-images.githubusercontent.com/96687176/149677566-7c056799-b151-4ebb-9c92-60044ea6e690.jpg) ----XMR---- ![11](https://user-images.githubusercontent.com/96687176/149677580-6e67ff2f-6900-4130-9eda-95812b384381.jpg) ![12](https://user-images.githubusercontent.com/96687176/149677584-8e6d8806-b2c8-4089-9bc9-44b46390e06f.jpg) ![13](https://user-images.githubusercontent.com/96687176/149677586-a7246b68-8702-4a3e-9588-99937afc8393.jpg) ![14](https://user-images.githubusercontent.com/96687176/149677592-6428d1f8-fb33-4cda-b35e-cf9045aff43d.jpg) ----- GENERAL SETTINGS---- ![15](https://user-images.githubusercontent.com/96687176/149677618-32b72e17-5c74-496f-9d56-16f99234e132.jpg) ![16](https://user-images.githubusercontent.com/96687176/149677623-442ef2e0-75b5-453c-bbe3-4fbf282fffc0.jpg) ![17](https://user-images.githubusercontent.com/96687176/149677632-89351b16-d7b7-4550-aa4f-9062adaf3465.jpg) ![18](https://user-images.githubusercontent.com/96687176/149677633-6ca3d2fd-88ae-4c19-8826-9bdc35ef0231.jpg) ![19](https://user-images.githubusercontent.com/96687176/149677635-0f64ff45-7d9d-4220-a279-5f0a7dea211d.jpg) ![20](https://user-images.githubusercontent.com/96687176/149677639-b13ae25a-0821-4946-827c-bfc8cc565a99.jpg) ![21](https://user-images.githubusercontent.com/96687176/149677641-126625bf-b660-4ca3-b826-ccb7846b4cca.jpg) ![22](https://user-images.githubusercontent.com/96687176/149677643-d16bce63-9870-485d-acf7-a4ae52d31364.jpg) ![23](https://user-images.githubusercontent.com/96687176/149677645-34f59f56-f767-4c83-9cb2-63a45b276663.jpg)
