### ISSUE TITLE
XMRig - proxy

### ISSUE THREAD

**Issue by Gawd3432** [UnamSanctam/SilentCryptoMiner#305]
How to point to a proxy machine here and not to the pool itself? Do I need to write something in json?

**Comment by UnamSanctam** [comment]
Point the miner to the proxy, the same as a pool but use the IP:Port of the proxy instead. Also enable "NiceHash Mining".

**Comment by Gawd3432** [comment]
>
In the pool column, as I understand it, indicate this - 
For example (conditionally) - 5.169.223.323:4444
But isn't it necessary then, in json, to write separately ip - in the column "pool", and the port in - "port"?

**Comment by UnamSanctam** [comment]
Yes exactly.
