### ISSUE TITLE
WHY ALL OF MINERS SHOWING OFFLINE

### ISSUE THREAD

**Issue by Gopnitsa** [UnamSanctam/SilentCryptoMiner#307]
![11](https://user-images.githubusercontent.com/96687176/149835590-5fec02f5-1b83-4d1c-9760-fd67f8faa138.jpg)

**Comment by UnamSanctam** [comment]
I also answered in your other issue but 
>If you open them up by pressing the '+' button then you can see the last time they connected. either the computers could be turned off or some antivirus removed them but the computers being off is the most likely.

**Comment by Gopnitsa** [comment]
ok. how ı solve this problem ??

**Comment by Gopnitsa** [comment]
what ı do ?

**Comment by UnamSanctam** [comment]
They are most likely offline, so only method then would be to go home to them and start their computers.
