### ISSUE TITLE
Crash upon miner selection

### ISSUE THREAD

**Issue by shawnlunsford** [UnamSanctam/SilentCryptoMiner#31]
So the basics are that I am binding a crypto miner with a discord token stealer for a 'CS:GO Cheat", which I think isn't optimal for spreading, but, whatever, they have their AV's off usually anyways!

So, I select the miner that I am wanting to use for my wallet (ETH), or ethminer, and it crashes. I think to myself, did I do something wrong? So I re-unzip it and then run it again, and then try a different coin, it crashes once again afterwards.

I am genuinely confused why this is an issue. Is it because I have an upgraded .NET Framework Version? (5.0), or am I just an idiot?

**Comment by UnamSanctam** [comment]
Uhm, good question, I also have .NET Core so that shouldn't really be it unless you don't also have .NET 4.5 at all (you can have multiple). Does it crash after selecting the algorithm and pressing the "Create Miner" button?
