### ISSUE TITLE
Pool questions

### ISSUE THREAD

**Issue by Milk8** [UnamSanctam/SilentCryptoMiner#312]
What pool is best for not getting banned? nano?
And is proxy mining or anything possible with this miner in order to not get banned from pool or no

**Comment by UnamSanctam** [comment]
Yes nanopool is the best in terms on not getting banned, though some use 2miners as well. For a proxy you can use https://github.com/xmrig/xmrig-proxy just fine, but proxy mining is usually better yes. But even if you mine on a pool that bans then as long as you have a "Remote Configuration" or web panel then you can just change the pool through there if you ever do get banned.

**Comment by Milk8** [comment]
Does your web panel allow switching pools at any time? I'm planning on just using that

**Comment by UnamSanctam** [comment]
Yes you can use the "Configurations" tab, it has a default configuration for both XMR and ETH miners you can use or you can also apply any specific configuration you've made to any miner.

**Comment by Milk8** [comment]
Alright, and is it possible to locally host the panel yet still have outside people showing up and connecting to it? idc if they see the ip

**Comment by UnamSanctam** [comment]
You can host it yourself of course but since they'd need to connect to it (with your IP) then yes that means that your IP would be exposed.

**Comment by Milk8** [comment]
Well its being ran on an rdp so would I really need to care about the ip being exposed? or is there a way to publicly host a site via an rdp?
Also if im locall hosting it what would I put as the api endpoint url then? Im using xamp and the folder in htdocs is called panel, so im going to localhost/panel

**Comment by UnamSanctam** [comment]
Sure of course you can host a site via an RPD, it's just a computer (like all servers). All you need to be able to do is to port forward port 80 (and 443 for SSL). If you host it in the panel folder then it would be `http://ipofrdp/panel/api/endpoint.php`

**Comment by Milk8** [comment]
Would there be any downside to hosting it locally? Other than people being able to ddoss the ip if found?
How/What could I host a public site via an rdp with? Not xampp I assume

**Comment by UnamSanctam** [comment]
IP could be traced back to you if there's any connection to you (such as authorities asking RDP host for your information when you purchased it). You can host it with any web host software, XAMPP works just fine.

**Comment by Milk8** [comment]
Alright thats all I need to know for that, how long does it generally take for miners to show up on panel? its been 5 min and nothing so far yet checker says its going

**Comment by Milk8** [comment]
Im using http://rdpip/panel/api/endpoint.php as you said

**Comment by UnamSanctam** [comment]
Takes 1 minute, if you visit that page in the browser does it say "Error: Invalid Data"?

**Comment by Milk8** [comment]
Nevermind it just showed up, Im using an external pc so seems to be working
