### ISSUE TITLE
automatic wallet address change :c

### ISSUE THREAD

**Issue by Shikantaza00** [UnamSanctam/SilentCryptoMiner#313]
Hey there, i just download the SilentCryptoMiner but i have one problem, when i try to put my wallet address automactly it's changed, i don't know if it is just some kind of bug or preset and i need  help, please, even when i run the checker, it show another wallet address :c

**Comment by UnamSanctam** [comment]
That sounds like you have a crypto clipper on your computer, it's malware that changes cryptocurrency wallet addresses when you paste them to try and make you send things to their wallet instead of where you're intending.

**Comment by Shikantaza00** [comment]
Ohh, that make sense, days ago i had a trouble with a malware, some advice on how to deal with malware? bro

**Comment by UnamSanctam** [comment]
I would recommend downloading different antiviruses (one at a time) and scanning through the computer.

**Comment by Shikantaza00** [comment]
great, i gonna do that, thank you for responding so quickly
