### ISSUE TITLE
How do I get this to work for each user that logs on and not just my one administrator account

### ISSUE THREAD

**Issue by edwinnunez** [UnamSanctam/SilentCryptoMiner#316]
I would prefer to have it mine for all users instead of just one account, however I do not know if this is possible. I completely understand if you cannot help me with this, and sorry for being a nuisance.

**Comment by UnamSanctam** [comment]
It's technically possible but it does "break" the idle detection system due to how Windows works because it has to run as the "System" user to be able to do that.
