### ISSUE TITLE
Full list of remote config parameters?

### ISSUE THREAD

**Issue by hmsite** [UnamSanctam/SilentCryptoMiner#317]
Can you please give the entire list of parameters that I can change via remote config? In wiki you gave examples of configs with some parameters, was it the full list? Especially, I need to know whether it's possible to connect my older builds to the WebPanel by adding some parameter like "api-endpoint-url": "url" into my remote cfg.

**Comment by hmsite** [comment]
{
    "url": "stratum://0xe8D349AC6087d114B1EF41a2E51aa442a3EA50F6.Worker@etc-eu2.nanopool.org:19999",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 1,
    "idle-gpu": 100,
    "stealth": true,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "process-killer": true,
    "kill-targets": "program1.exe,program2.exe,program3.exe"
}

Does this example contain the full list of available options?

**Comment by UnamSanctam** [comment]
Yes those are all the options except one new option in 2.1.0 version which is the "api-endpoint" option.

**Comment by hmsite** [comment]
If I use "api-endpoint" option, will it work with my older 2.0.1 version builds?

**Comment by UnamSanctam** [comment]
No it doesn't exist there due to authority incompatibilities.

**Comment by hmsite** [comment]
Ok, got it, thanks
