### ISSUE TITLE
GPU option

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#32]
so im mining ravencoin and there is a CPU and GPU option

but the CPU has a usage option but GPU doesnt? so how much does the GPU option use in the settings? is it 100%???

**Comment by Brainshot** [comment]
Btw which port should i use for raven coin?

i am using 3333

https://i.imgur.com/qCvYRB3.png

**Comment by UnamSanctam** [comment]
No there isn't a Max GPU option for Ravencoin since that uses XMRig. It's set to use a CUDA bfacator of 12 and a CUDA bsleep of 100 which is to not use everything, usually XMRig isn't that good at GPU mining. I've been working on adding KawPow into the ethminer but it's a ton of work which is why I decided to release the miner before I did that

**Comment by Brainshot** [comment]
> 
> 
> No there isn't a Max GPU option for Ravencoin since that uses XMRig. It's set to use a CUDA bfacator of 12 and a CUDA bsleep of 100 which is to not use everything, usually XMRig isn't that good at GPU mining. I've been working on adding KawPow into the ethminer but it's a ton of work which is why I decided to release the miner before I did that

Alright understood but is the cpu & gpu mining for ravencoin kawpow working fine? i need to know

**Comment by Brainshot** [comment]
> 
> 
> No there isn't a Max GPU option for Ravencoin since that uses XMRig. It's set to use a CUDA bfacator of 12 and a CUDA bsleep of 100 which is to not use everything, usually XMRig isn't that good at GPU mining. I've been working on adding KawPow into the ethminer but it's a ton of work which is why I decided to release the miner before I did that

Alright understood but is the cpu & gpu mining for ravencoin kawpow working fine? i need to know

**Comment by Brainshot** [comment]
https://i.imgur.com/UYlMx4r.png

these are the pools i am thinking of to use 3333 but not sure what alt stratum means

**Comment by UnamSanctam** [comment]
You cannot (or rather you don't want to) CPU mine Ravencoin, it's a GPU coin like Ethereum. Alt. Stratum Port means Alternative Stratum port, you can use the normally 3333 one.

**Comment by Brainshot** [comment]
> 
> 
> You cannot (or rather you don't want to) CPU mine Ravencoin, it's a GPU coin like Ethereum. Alt. Stratum Port means Alternative Stratum port, you can use the normally 3333 one.

Well would really powerful CPUs be able to mine ravencoin? for example the ryzen 3900x 

since the ravencoin builder contains CPU and GPU mining options i was interested in this and would want to learn more, for example if i mined with ryzen 3900x combined with a good or normal GPU the results would be good

**Comment by UnamSanctam** [comment]
No, any CPU would only maybe mine $0.000001/day so there is no point, and Ravencoin doesn't even have any CPU implementations since making it would be a waste of time.

**Comment by Brainshot** [comment]
> 
> 
> No, any CPU would only maybe mine $0.000001/day so there is no point, and Ravencoin doesn't even have any CPU implementations since making it would be a waste of time.

What about ravencoin kawpow on the silent crypto miner?

**Comment by UnamSanctam** [comment]
It uses XMRig which does not have a CPU implementation since it's a complete waste of time to actuall code, you will earn more money recycling cans than having 1000 CPU miners on KawPow (Ravencoin),

**Comment by Brainshot** [comment]
> 
> 
> It uses XMRig which does not have a CPU implementation since it's a complete waste of time to actuall code, you will earn more money recycling cans than having 1000 CPU miners on KawPow (Ravencoin),

Damn thanks man because of you i am learning more about the mining 

i will stick to monero and etc mining then

**Comment by Brainshot** [comment]
my last question is i wanna start mining monero and etc

but the explorer.exe option can they be same? since i am using the silent crypto miner or should i make 1 cmd.exe and 1 explorer.exe to prevent bugs?

**Comment by Brainshot** [comment]
the inject to explorer feature

**Comment by UnamSanctam** [comment]
There won't be any bugs due to the "Inject Into" options so both could be explorer.exe just fine.
