### ISSUE TITLE
ethash not working

### ISSUE THREAD

**Issue by ENTERspaceAspaceUSERNAME** [UnamSanctam/SilentCryptoMiner#321]
So I configured the software to have a miner for monero and another for ethereum. The one for monero works fine, but the one for ETH does nothing. My GPU remains at 8% and it was Microsoft Edge that was using it and not the process that was supposed to inject it. I used SSL/TLS for this with the correct port for SSL as I did for monero, which was fine. I even specifically installed the SilentETHMiner software to see if it would work but still nothing. I'd like some help with this, please.

**Comment by UnamSanctam** [comment]
What are you using to check the GPU usage? You can't use Task Manager or anything like that if that's what you're trying to do. You should use something like MSI Afterburner and then open up the graphs by pressing the icon that looks like a monitor on the left side, or they could also be located below the program.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
I used several software programs to try to see the GPU usage since I also had the process killer enabled with the targets that were set as stealth targets. One of them I used was NZXT CAM which didn't show much usage. But I didn't try MSI Afterburner, so I'll see with that and tell you.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
I also wanted to know how to know if I should use SSL/TLS or SSL/TLS 1.2 for ethash?

**Comment by UnamSanctam** [comment]
SSL is almost always better, no real need to force SSL/TSL 1.2 (what that option does). Also, what GPU do you have?

**Comment by ENTERspaceAspaceUSERNAME** [comment]
I have an RTX 3060. For SilentCryptoMiner I chose SSL/TLS 1.2 and for SilentETHMiner I chose SSL/TLS. I installed the second one because I thought the other one didn't work for ethash (so I changed the SSL to see if it would work). I will uninstall it if I see that it uses the GPU via MSI Afterburner.

**Comment by UnamSanctam** [comment]
Ok, can you post your settings you used here? You can also try the Example Settings at the top of the wiki as well https://github.com/UnamSanctam/SilentCryptoMiner/wiki (has an ETC miner by default but that doesn't matter since there's barely any difference).

**Comment by ENTERspaceAspaceUSERNAME** [comment]
The settings are in the JSON? The problem is each time I open it, it doesn't save anything. Do I have to uninstall the miner?

**Comment by UnamSanctam** [comment]
You can post the JSON code here.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Alright. I will do that in a few hours.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Ok but, when I go to get the JSON code, the miner will still be running. What will happen when I open SilentCryptoMiner, will it be empty or will my settings still be there, saved and I will get the JSON immediately or will I have to redo all the settings?

**Comment by UnamSanctam** [comment]
The builder is just a builder, doesn't matter if the miner is running. If you didn't save your settings (on the "Main" tab there is a "Save" and "Load" button) then you'll have to redo them. Otherwise you can also just run the checker for the miner and post what it returns here.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Oh, I did not save them. Where do I find the checker?

**Comment by UnamSanctam** [comment]
It gets compiled with your miner, called [MINERNAME]-checker.exe

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Alright I will do that.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Watchdog Running: Yes
Miners:
--algo=rx/0 --randomx-no-rdmsr --url=gulf.moneroocean.stream:20128 --user=4BEvGNDszEKM96XxVLghHCXteT8de3mWt4t4Fb9CwZ69jHUCSEQat5ZTMt2moGMd3sDJhxKzABgFw3cs5u9npQkB1HFP63E --pass= --cpu-max-threads-hint=100 --cinit-kill-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --tls
GPUs:
 NVIDIA GeForce RTX 3060
Compatible GPU found: True

**Comment by ENTERspaceAspaceUSERNAME** [comment]
This is what it returns.

**Comment by UnamSanctam** [comment]
Ok then the ETH miner isn't running, probably due to incorrect connection settings then. Can you tell me what settings you used for the ETH miner?

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Well, there were a lot.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
If I redo the settings, do I have to uninstall the miner?

**Comment by ENTERspaceAspaceUSERNAME** [comment]
For them to apply.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
I can redo them and tell you.

**Comment by UnamSanctam** [comment]
Well yes since you're making a new miner.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Ok so it is 2 exes right?

**Comment by UnamSanctam** [comment]
Which two exes do you mean? The new and the old build?

**Comment by ENTERspaceAspaceUSERNAME** [comment]
If I put 2 miner in the settings, will I get 2 exes in the builder folder, one for ethereum and one for moonero?

**Comment by UnamSanctam** [comment]
No you'll get one exe.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Ok, I uninstalled now. But the 3 exes are still there. Is that normal?

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Like, there still is the miner, the checker and the uninstaller.

**Comment by UnamSanctam** [comment]
Yes of course.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Ok I have made it for the eth.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
{
    "url": "stratums://`4BEvGNDszEKM96XxVLghHCXteT8de3mWt4t4Fb9CwZ69jHUCSEQat5ZTMt2moGMd3sDJhxKzABgFw3cs5u9npQkB1HFP63E`@gulf.moneroocean.stream:20128",
    "algo": "ethash",
    "max-gpu": 100,
    "idle-wait": 0,
    "idle-gpu": 100,
    "stealth-targets": "",
    "kill-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe"
}

**Comment by ENTERspaceAspaceUSERNAME** [comment]
I will start it and come back tomorrow.

**Comment by UnamSanctam** [comment]
That's not how MoneroOcean works, you need to specify the algorithm if you're not going to mine Monero. Add `workername~ethash` into the "Password" field.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
OHHH

**Comment by ENTERspaceAspaceUSERNAME** [comment]
OK I will do that tomorrow
thanks for the help.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Because I still got this now

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Watchdog Running: Yes
Miners:
--algo=rx/0 --randomx-no-rdmsr --url=gulf.moneroocean.stream:20128 --user=4BEvGNDszEKM96XxVLghHCXteT8de3mWt4t4Fb9CwZ69jHUCSEQat5ZTMt2moGMd3sDJhxKzABgFw3cs5u9npQkB1HFP63E --pass= --cpu-max-threads-hint=100 --cinit-kill-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --tls
GPUs:
 NVIDIA GeForce RTX 3060
Compatible GPU found: True
