### ISSUE TITLE
is it possible to mine ton with xmr miner? 

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentCryptoMiner#322]
is it possible to mine ton with xmr miner?

**Comment by UnamSanctam** [comment]
No it's not, Ton uses the MinotaurX algorithm to mine which isn't supported by my miner (or by barely any other miners either).

**Comment by Toxenskiy** [comment]
Will there be any update in the near future, if so what?

**Comment by UnamSanctam** [comment]
Maybe, it will most likely take a ton of work to implement. Biggest problem is that Ton is not a PoW coin but a PoS coin, the reason that PoW exists in Ton is that they have giver smart contracts that you can "mine" to for funds but those funds will run out in about 200 days. Scroll down to "Givers Bleed Rate" here https://ton.org/mining.

**Comment by Toxenskiy** [comment]
What are the chances of the cryptocurrency "ton" of cells?

**Comment by Toxenskiy** [comment]
Can you give me your contacts where we could talk in person?

**Comment by UnamSanctam** [comment]
> What are the chances of the cryptocurrency "ton" of cells?

Can you retranslate that?

> Can you give me your contacts where we could talk in person?

I have a Telegram now at @UnamSanctam
