### ISSUE TITLE
can i put 0% GPU max and 40% GPU idle? and the same with the CPU

### ISSUE THREAD

**Issue by serjooga** [UnamSanctam/SilentCryptoMiner#324]
can i put 0% GPU max and 40% GPU idle? and the same with the CPU

**Comment by UnamSanctam** [comment]
Yes you can, then it will pause (use no resources) the miner until it's idle and then use 40%. Though that usually isn't necessary for CPU since it's already really difficult to notice at for example something like 20%.

**Comment by serjooga** [comment]
OK, thanks. what is the benefit to you to help each person? Do you have any percentage of infections?

**Comment by UnamSanctam** [comment]
Well it's fun to see people use my project, especially since I put much time into it. It's a hobby project and doesn't cost me any money directly to develop so making any money from it isn't a priority or a need. Currently there's no dev fee (the XMR miner technically has one at 0.1%-1% but it's not "enabled").

**Comment by serjooga** [comment]
Respect dude!!

I have been distributing the miner for some time now. I want to ask about lowering the threshold for payments. I am using the NanoPool site. I understood correctly that for CPU XMR on rentry.co I should add to (password: "my password")

![image](https://user-images.githubusercontent.com/98273913/150688059-eec8760d-3111-4fe6-9002-ce294e8dcc60.png)

and For ETC GPU
"stratum://0x6f2Dc51B66ee5BDF9D680eB094E4ede65905308E.Worker/password@etc-eu2.nanopool.org:19999",

![image](https://user-images.githubusercontent.com/98273913/150688513-e1924733-dd52-4cf5-87ef-41ba21b08135.png)

And how long do I have to wait to change the withdrawal amount?

**Comment by UnamSanctam** [comment]
For XMR you should change "wallet" to this format:
```
Wallet.Worker/Password
``` 
and for ETC it would be:
```
stratum://`0x6f2Dc51B66ee5BDF9D680eB094E4ede65905308E.Worker/password`@etc-eu2.nanopool.org:19999
```
note the \` (accent sign) that are around the `Wallet.Worker/Password` since they are important.

When all the workers use the same password then you'll be able to change the withdrawal amount.

**Comment by serjooga** [comment]
right?
![image](https://user-images.githubusercontent.com/98273913/150689554-33582855-47ef-4650-913a-743e8ad4b511.png)

![image](https://user-images.githubusercontent.com/98273913/150689433-3c388190-e0fb-4944-9588-9c1073415834.png)

Do I need to put the same accent marks on XMR?

Also does nanopool count only online users?
Thank you so much for your help!!

**Comment by UnamSanctam** [comment]
Yes that should work, you don't need the accent marks for XMR. You also don't need a real email if you don't want to use one, you can use something like Password123 instead.

Nanopool counts all workers that are in the workers list no matter if they're online or not, but after being offline for 2 days that worker will get removed from the worker list.
