### ISSUE TITLE
Wtf hashrate on pool is showed as 0

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#325]
so it was mining for days and was at 4k hashrate which are 100 miners, but i look at the pool it went brutally down and shows 0 now
![egqgq](https://user-images.githubusercontent.com/93741208/150690612-3b78dce5-cb8c-42aa-a78a-4c48fd265658.PNG)

![fqwqwcqwc](https://user-images.githubusercontent.com/93741208/150690632-a5720e3b-8107-4e27-a358-5e7f0ae87d01.PNG)

am i banned from the pool wtf is happening? on the webpanel it shows mining and good hashrates

**Comment by Brainshot** [comment]
is this a glitch in flockpool ?

**Comment by Brainshot** [comment]
nvm its normal now lmao

**Comment by UnamSanctam** [comment]
Haha yes flockpool has been having issues today (site was done for some hours as well).

**Comment by Brainshot** [comment]
> Haha yes flockpool has been having issues today (site was done for some hours as well).

Fucking hell man this scared me, i thought some hacker stole all my hashrate or got banned but now the hashrate is going up real high even at 5kh
