### ISSUE TITLE
Error compiling Miner loader!

### ISSUE THREAD

**Issue by BlackSanta24** [UnamSanctam/SilentCryptoMiner#328]
![image](https://user-images.githubusercontent.com/98222548/151038145-02d3aa8e-1ccb-491b-87d3-4dc81d2d5821.png)
![image](https://user-images.githubusercontent.com/98222548/151038780-2809c0c7-0122-494e-8fa8-e255e5ab5606.png)
Please, help me

**Comment by UnamSanctam** [comment]
It says the error there (though didn't list the specific characters), you have Cyrillic characters in your build path, build it inside a folder path that only has alphanumeric characters.

**Comment by BlackSanta24** [comment]
Dude, you are a god! Thank you:)

**Comment by BlackSanta24** [comment]
![image](https://user-images.githubusercontent.com/98222548/151040538-c8e138ed-822d-4f65-a9b3-e9eaf906af8e.png)
One more thing
Is this file enough to work?

**Comment by UnamSanctam** [comment]
Yes you only need that one, the two folders are only there for building/compiling it and the checker and uninstaller are only optional tools for checking if the miner is running and uninstalling it.

**Comment by BlackSanta24** [comment]
Thank you!

**Comment by Gopnitsa** [comment]
> Thank you!

hey comrade. You have discord adress ?
