### ISSUE TITLE
Simply not mining.

### ISSUE THREAD

**Issue by ayswift** [UnamSanctam/SilentCryptoMiner#329]
I installed it, and set everything up correctly but it's not using any of my CPU and when I check the checker it simply doesn't show anything.

I was told that it may have an issue with encrypting/decrypting.. Could u please check it? Thx

**Comment by ayswift** [comment]
https://prnt.sc/26jbzi8
https://prnt.sc/26jbzlz

 i got these 2 errors when i clicked debug

if its worth knowing, i used the rootkit

**Comment by ayswift** [comment]
I found the issue, having startup option enabled makes it not mine at all.

**Comment by UnamSanctam** [comment]
Yes looks like it couldn't install it, mainly it couldn't find `debug.exe`. Is your antivirus removing it?

**Comment by ayswift** [comment]
> 

Hi! No, my antivirus is completely turned off, including firewall. I also sent the exe to a friend and it didn't work either.

**Comment by UnamSanctam** [comment]
He gets the same two error messages?

**Comment by ayswift** [comment]
> 

When i turn on debug mode, i believe so..

**Comment by ayswift** [comment]
> He gets the same two error messages?

Do you have a Discord by any chance? Maybe we can try to resolve it faster there.

**Comment by UnamSanctam** [comment]
Can you try with the Example Settings at the top of the wiki: https://github.com/UnamSanctam/SilentCryptoMiner/wiki? And my Discord got banned (for helping people with the miner) but I have a Telegram now at: @UnamSanctam.
