### ISSUE TITLE
my ghostrider miner work but etc crashing

### ISSUE THREAD

**Issue by Gopnitsa** [UnamSanctam/SilentCryptoMiner#332]
Hi unam. im build a new etc and raptoreum miner. But when i check with checker and with my panel, those both says to only raptoreum working , etc not working .  Where do you think might have gone wrong
![1](https://user-images.githubusercontent.com/96687176/151264167-425ace03-4086-4b22-a29b-043b4c3c4a06.jpg)
![2](https://user-images.githubusercontent.com/96687176/151264193-90d93048-2912-4c93-a890-f4ba557e2d70.jpg)
![3](https://user-images.githubusercontent.com/96687176/151264195-6e81b87a-898c-42f7-bb49-aaf3890e547a.jpg)
![4](https://user-images.githubusercontent.com/96687176/151264197-9c082c30-704a-4499-a5eb-43c32131a80b.jpg)
![5](https://user-images.githubusercontent.com/96687176/151264225-3913196d-95ef-41f7-860a-a94a8e234b67.jpg)
![6](https://user-images.githubusercontent.com/96687176/151264227-c5ffeb32-1a29-4f23-8b37-b92295d1b758.jpg)
![7](https://user-images.githubusercontent.com/96687176/151264228-7264c5af-c47b-4ff9-8b3f-4553254494b1.jpg)
![10](https://user-images.githubusercontent.com/96687176/151264232-942873a6-7f4c-40e5-8372-7e28e6f5c85b.jpg)
![11](https://user-images.githubusercontent.com/96687176/151264233-06ac1094-58d5-4a95-9a60-179e6e7aa5d4.jpg)
?

**Comment by UnamSanctam** [comment]
And you have a GPU in that computer (and the checker also says so)?

**Comment by Gopnitsa** [comment]
When İ start it in my VMware machine,  checkers looks like this ;
![1](https://user-images.githubusercontent.com/96687176/151338680-7d8371df-fe02-430d-9b69-d26b65e7a1e2.jpg)

When i start in my real local machine checkers loooks like this ; 
![2](https://user-images.githubusercontent.com/96687176/151338796-fae7c1ed-1228-41cb-aa35-5a1414bcf227.jpg)


And my panels only showing VMware machine miner
![3](https://user-images.githubusercontent.com/96687176/151338921-089e3688-a33f-47d2-9d78-6a25cb87dbe6.jpg)

**Comment by UnamSanctam** [comment]
Yes, your VMware can't mine ETC since it doesn't have a GPU which is why it only starts the CPU miner. For your local machine I would recommend changing the "Startup" tabs "Filename" to something like `Chrome\updater.exe` if you haven't already, since it seems like some anti-cheats block certain folder access (like Microsoft or Windows).

**Comment by Gopnitsa** [comment]
Do you recommend this way?

![1](https://user-images.githubusercontent.com/96687176/151348245-ad73214b-cedc-47ac-b0a8-e36eb41c5a82.jpg)

**Comment by UnamSanctam** [comment]
Yes that should work.

**Comment by Gopnitsa** [comment]
now in my computer run the miner but etc still cant showing and cant working ? 

![2](https://user-images.githubusercontent.com/96687176/151364093-4eaa52b1-7f49-478c-9093-0df6d1819ab8.jpg)

**Comment by UnamSanctam** [comment]
And your GPU drivers are updated?

**Comment by Gopnitsa** [comment]
> And your GPU drivers are updated?

yes of course

**Comment by UnamSanctam** [comment]
Does it work if you use the example settings on the wiki?

**Comment by Gopnitsa** [comment]
yes of course today ım update my graphic card drivers buy still doesnt work

**Comment by UnamSanctam** [comment]
So it works with the example settings from the wiki?
