### ISSUE TITLE
Miners going offline after a while whilst their PC is on.

### ISSUE THREAD

**Issue by ayswift** [UnamSanctam/SilentCryptoMiner#334]
Hey, I have about 10 miners currently and I notice that after 30m-1hr most miners simply go offline even though I confirmed their PC is on and running and they have WD completely disabled.

Any idea???

**Comment by UnamSanctam** [comment]
Hmm it's hard since I can't see their computers but do you experience the same when you mine on your own computer?

**Comment by pianist1912** [comment]
Hi
My problem is like this. I have the same problem when I do it on my own computer. Could it be that the virus is deleting the programs?

**Comment by UnamSanctam** [comment]
> Hi My problem is like this. I have the same problem when I do it on my own computer. Could it be that the virus is deleting the programs?

They go offline in the web panel for you after a while? Are they still running if you use the checker?

**Comment by pianist1912** [comment]
yes, they go offline on the web panel after a certain period of time and I check the https://moneroocean.stream/ site and they go offline.

**Comment by UnamSanctam** [comment]
> yes, they go offline on the web panel after a certain period of time and I check the https://moneroocean.stream/ site and they go offline.

Then most likely you don't have the same problem, run the checker to see if the miner is still running.

**Comment by pianist1912** [comment]
> > yes, they go offline on the web panel after a certain period of time and I check the https://moneroocean.stream/ site and they go offline.
> 
> Then you might not have the same problem, run the checker to see if the miner is still running.

After the last update, such problems occurred. We'll find another solution now. It would be funny to knock on everyone's door and say can I try the inspector

**Comment by UnamSanctam** [comment]
> > > yes, they go offline on the web panel after a certain period of time and I check the https://moneroocean.stream/ site and they go offline.
> > 
> > 
> > Then you might not have the same problem, run the checker to see if the miner is still running.
> 
> After the last update, such problems occurred. We'll find another solution now. It would be funny to knock on everyone's door and say can I try the inspector

Run the checker yourself to test it and see if it happens to you. You don't test your miner?

**Comment by pianist1912** [comment]
> > > > yes, they go offline on the web panel after a certain period of time and I check the https://moneroocean.stream/ site and they go offline.
> > > 
> > > 
> > > Then you might not have the same problem, run the checker to see if the miner is still running.
> > 
> > 
> > After the last update, such problems occurred. We'll find another solution now. It would be funny to knock on everyone's door and say can I try the inspector
> 
> Run the checker yourself to test it and see if it happens to you. You don't test your miner?

I do not have a problem on my own computer, I have this problem on other computers

**Comment by UnamSanctam** [comment]
Yes then it's most likely their antivirus (if you have high usage settings then they can download new ones if they lag), or their computers are off.

**Comment by pianist1912** [comment]
> Yes then it's most likely their antivirus (if you have high usage settings then they can download new ones if they lag), or their computers are off.

I use it in the range of 40%, but most likely, virus programs should be converted into 0 viruses and injected.

**Comment by Gopnitsa** [comment]
ı had same problem bro can you see my miners 

![image](https://user-images.githubusercontent.com/96687176/151602887-7274c076-d120-481c-9c4a-54dec12bc584.png)

**Comment by Gopnitsa** [comment]
i have too many offline how we can solve this problem. when i publishing my miner i cant use any extra obfuscator or cryption programs. Whats your advice ?

**Comment by pianist1912** [comment]
> i have too many offline how we can solve this problem. when i publishing my miner i cant use any extra obfuscator or cryption programs. Whats your advice ?

Can you share your settings?

**Comment by UnamSanctam** [comment]
> ı had same problem bro can you see my miners

Well, I don't really know if their computers are turned off or if the miners are removed, most people only have their computers on for a few hours a day though.

> i have too many offline how we can solve this problem. when i publishing my miner i cant use any extra obfuscator or cryption programs. Whats your advice ?

You mean you can't use them or that you can't afford any good ones?

**Comment by UnamSanctam** [comment]
> Can you share your settings?

You can try using the Example Settings at the top of the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki to see if it works.
