### ISSUE TITLE
Cpu usage goes to 40% but goes 0% after 5 sec

### ISSUE THREAD

**Issue by akargokay4** [UnamSanctam/SilentCryptoMiner#335]
I am running the miner file and everything is okey. But the CPU usage goes to 0% after 5 sec. What is the problem with it ? Could you help me ? Thx :)

**Comment by UnamSanctam** [comment]
Do you have stealth enabled?

**Comment by akargokay4** [comment]
I tried it enabled and disabled still same issue

**Comment by UnamSanctam** [comment]
Run the checker and post what it returns here.

**Comment by akargokay4** [comment]
i think i found the issue. I just disbled the pause for obfuscation. Is it really needed or not ?

**Comment by UnamSanctam** [comment]
If you want to obfuscate all the files then yes, otherwise no.

**Comment by akargokay4** [comment]
I want to obfuscate but if i enable it miner is not working.

**Comment by akargokay4** [comment]
doesn't it work untill has been obfuscated if i enable the pause for obfuscation ?

**Comment by Gopnitsa** [comment]
> doesn't it work untill has been obfuscated if i enable the pause for obfuscation ?

hi bro your problem still goes on ?

**Comment by akargokay4** [comment]
yes

**Comment by Gopnitsa** [comment]
> yes

kanka ekle beni bro add me on discord Gopnitsa#0 116

**Comment by akargokay4** [comment]
ekledim
