### ISSUE TITLE
not mining

### ISSUE THREAD

**Issue by Milk8** [UnamSanctam/SilentCryptoMiner#337]
A new issue, the miner works on my own pc and has on a few other pcs though most I execute on never start mining or come up on the web panel? I am remotely executing the files and see they are being installed to the right place, though when I open task manager and check the process I injected into, theres nothing for the miner and never see anything on the panel about them.
I have also manually made sure all exe are excluded in there wd.
What could be the issue when the process never actually starting or mining even when I execute it?

**Comment by Milk8** [comment]
Does it not work on radeon gpus? I just tried it on someone with a 6700 and didnt work, tried on someone with a 1660 and it is mining rn

**Comment by Milk8** [comment]
Well i see it says it mines on both but idk, randomly dosent work on some people, he has 12gb of vram

**Comment by UnamSanctam** [comment]
If you run the checker does it display the miner as running there? Does the one it doesn't work for have old drivers or updated ones? Also, as a side note if it doesn't install on some people then change the "Startup" tabs "Filename" to something else since some anticheats now blocks access to the Windows (and Microsoft) folder.

**Comment by Milk8** [comment]
Just re executed it and it randomly worked on one of the people it wasent working on, says he has not enough vram so was pointless though guy with a 6700xt still not working on.
Ill try the checker in a min and lyk

**Comment by Milk8** [comment]
I re executed the miner on the 6700xt guy just now. I can see the executable file and the file it made in appdata. I also tried running the file it installed it directly on his pc. Then I ran the checker and it still says no miner is going but his gpu is comptatible
At first it was in a microsoft folder with other shit in it which didnt work but I deleted it and made a new one just called "hosting" and a random file name. Still same exact error
Miner simply wont start

**Comment by UnamSanctam** [comment]
Do you have a CPU miner as well or just a GPU miner?

**Comment by Milk8** [comment]
No, im only mining eth and never anything else

**Comment by UnamSanctam** [comment]
Then it could be his drivers, either they are old or they could've installed (or registered) OpenCL incorrectly which can happen.

**Comment by Milk8** [comment]
Any easy way to reinstall them then? or no

**Comment by Milk8** [comment]
seems his drivers are up to date 
![image](https://user-images.githubusercontent.com/77039660/151655635-68a1da7a-3eea-403d-b8b9-9b8943915f1e.png)

**Comment by UnamSanctam** [comment]
Can you try running this (a normal miner) to see what it says [Test5.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7963398/Test5.zip) in the console? Just run any of the bat files.

**Comment by Milk8** [comment]
says this 
![image](https://user-images.githubusercontent.com/77039660/151656325-1dc5aeca-e64b-46f5-ac66-54ddcbf140be.png)

**Comment by UnamSanctam** [comment]
Extract all the files out somewhere first.

**Comment by Milk8** [comment]
I did

**Comment by Milk8** [comment]
I extracted then on my own pc then sent them to him via a message, downloaded off the msg on his pc and ran it

**Comment by UnamSanctam** [comment]
And ethminer.exe and the bat file you're running are in the same folder?

**Comment by Milk8** [comment]
No I was just running bat file, hes offline now
Just executed on a 2070 and its working as it should so idk just randomly wont work on people once in awhile 
Also what is the exact amount of vram needed to mine etc vs eth?

**Comment by UnamSanctam** [comment]
ETC currently requires 2.9GB while ETH currently requires 4.7GB, you can find the DAG required for a lot of GPU coins here: https://minerstat.com/dag-size-calculator

**Comment by Milk8** [comment]
Alright thanks,
Ill do in depth testing tonight but ive had a few others the miner hasn't worked on, all happen to have radeon gpus im pretty sure
Ill try remotely running ethminer later on them

**Comment by Milk8** [comment]
Also another question, is there any way to efficiently have the best coin start mining on someone? (ETH>ETC, though if it can't mine ETH have it mine ETC if 4+gb) Like if I binded etc and an eth miner together would it just mine whatever coins miner executed last? I'm looking for a way to do this since I don't have the knowledge to make a program look at the victims vram and execute whichever based off that atm so was looking if theres any other possibilities thought I couldn't find any.

**Comment by UnamSanctam** [comment]
No not really since you technically don't choose ETH but actually the Ethash algorithm which can be any coin that uses the Ethash algorithm, meaning the VRAM required can be anything. The easiest is just to set it to ETC by default and change it to ETH in the web panel if the computer has a good GPU.

**Comment by Milk8** [comment]
Another question, would you happen to have a list of popular game processes or know where to get name, like Rust.exe, Fortnite.exe etc

**Comment by UnamSanctam** [comment]
There are some here: https://github.com/UnamSanctam/SilentCryptoMiner/discussions/30

**Comment by Milk8** [comment]
Alright thanks, miner has been working good since the last issues
Also is unam#0550 your discord? Can't tell if its random scammer or u Lol

**Comment by UnamSanctam** [comment]
Haha no that isn't me, my Discord got banned and haven't made a new one.

**Comment by Milk8** [comment]
Is this what I would do for making a new config? Just putting settings into the miner app and pasting the json into the web panel? Then changing the config on people ofc
Though when I change the config the pool on the dashboard dosent change, only the config name does? Does it not change or am I doing it wrong

**Comment by Milk8** [comment]
![image](https://user-images.githubusercontent.com/77039660/153530313-854c80e7-c2e4-479e-a17a-afcc06aaff30.png)

**Comment by Milk8** [comment]
Nevermind it just changed to the ETH pool, looks like its working

**Comment by UnamSanctam** [comment]
They use a custom format, enter `WalletAddress.WorkerName/WithdrawalPassword` as the wallet address.

**Comment by Milk8** [comment]
Ok so 0x313DAD2b104CFB5F9d4C8B53be2e1b021Bbb97C1.Milk/password would be acceptable? am gonna try and register that rn

**Comment by UnamSanctam** [comment]
Yes that would work, you should probably also surround it with ` (accent marks) like so:
```
`0x313DAD2b104CFB5F9d4C8B53be2e1b021Bbb97C1.Milk/password`
```
So that it gets encoded.

**Comment by Milk8** [comment]
changed some users to eth config 30+ min ago, I have several mining eth yet nothing coming up on dashboard, the dashboard on nanopool is already activated just havent used in a week since switching to etc
![image](https://user-images.githubusercontent.com/77039660/153534221-d9a6fec4-8715-48a0-9f9b-4cbe008779fd.png)

**Comment by UnamSanctam** [comment]
Most likely nanopool hasn't updated yet then (or you haven't found a share though that's unlikely). Though that's not the one you set a withdrawal password for right? Since then it would show in the "Wallet" column.

**Comment by Milk8** [comment]
Yep this is just a normal build with no password, ill wait another 10 min

**Comment by Milk8** [comment]
Also the password is not working, my username has come up on the dashboard and it still says invalid password

**Comment by UnamSanctam** [comment]
It will disappear after being offline for 2 days, you might also be able to "overwrite" it by mining with that worker name but with the same password as the other worker.

**Comment by Milk8** [comment]
I fixed mining issues, though losing bots sometimes
Is it physically possible to make a miner 32 bit and not 64 bit? Most crypters cant do 64 bit

**Comment by UnamSanctam** [comment]
Not at the moment no though it's planned, there are a lot of things that have to be changed. No one really makes 32-bit miners (normal miners) anymore since it can possibly cause some issues (which xmrig has sometimes if you manually build it as 32-bit).

**Comment by Milk8** [comment]
Im trying to chance the minimum payout amount again, it still just says invalid password every time, though the worker is showing up and is the only visible worker, heres what my address looks like in the miner `0x313DAD2b104CFB5F9d4C8B53be2e1b021Bbb97C1.Milk/********@protonmail.com`

**Comment by Milk8** [comment]
I put in the email as the password, says invalid

**Comment by Milk8** [comment]
Would I have to wait two days now for that worker to disappear in order to try a new password?

**Comment by UnamSanctam** [comment]
Yes or try mining with the same worker name, I believe it might overwrite the password if you do.
