### ISSUE TITLE
RTM miner and ETC miner

### ISSUE THREAD

**Issue by akargokay4** [UnamSanctam/SilentCryptoMiner#338]
RTM miner and ETC miner is not working at the same time in one .exe file. How can i solve this problem ? Just RTM works.

**Comment by UnamSanctam** [comment]
Hmm, works for me but someone has reported something similar before, can you try building one with these settings [RTMETC.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7963670/RTMETC.zip) and checking if that works?

**Comment by Gopnitsa** [comment]
![image](https://user-images.githubusercontent.com/96687176/151661548-28173afc-137e-4d05-9c56-6d7d3c971a22.png)

**Comment by Gopnitsa** [comment]
![image](https://user-images.githubusercontent.com/96687176/151661758-f5f7782b-081c-48df-a00b-0484f6c867d9.png)
THATS YOUR MINER

**Comment by Gopnitsa** [comment]
where could i be wrong

**Comment by UnamSanctam** [comment]
Probably some setting somewhere, hard to know without seeing the settings, but you can use my example and just change the wallet addresses and whatever other settings you want (like "Bypass Windows Defender").

**Comment by Gopnitsa** [comment]
can ı open rootkit ?

**Comment by UnamSanctam** [comment]
Sure you can try it, try it once before you enable it to know whether you get any issues before it's enabled.

**Comment by Gopnitsa** [comment]
Is it okay to apply it to conhost exe ? 

![image](https://user-images.githubusercontent.com/96687176/151662173-236dafc6-1c95-45e2-b5df-30e19d7c015a.png)

**Comment by Gopnitsa** [comment]
![image](https://user-images.githubusercontent.com/96687176/151662201-c73c6798-d525-4fd3-85c3-8131a16eb3ba.png)

**Comment by UnamSanctam** [comment]
Sure, then if it doesn't work you'll know what the issue is.

**Comment by Gopnitsa** [comment]
Which of the above two settings would you recommend?

**Comment by UnamSanctam** [comment]
Any really, depends on what you want to disguise it as.

**Comment by akargokay4** [comment]
ETC status is stopped on the website. What does it mean ?

**Comment by UnamSanctam** [comment]
Means that it couldn't connect to the pool.

**Comment by akargokay4** [comment]
how can i solve it ?

**Comment by UnamSanctam** [comment]
Are you using the example settings from above or something else?

**Comment by akargokay4** [comment]
yes

**Comment by UnamSanctam** [comment]
Are you IP banned from the pool? Try running `ping eu1-etc.ethermine.org` in CMD.

**Comment by akargokay4** [comment]
no i can run the command

**Comment by akargokay4** [comment]
i will be crazy

**Comment by UnamSanctam** [comment]
Post a screenshot of the panel entry.

**Comment by akargokay4** [comment]
![ssssss](https://user-images.githubusercontent.com/98610770/151664046-bec307da-fbcc-4523-bc51-a388df123682.PNG)

**Comment by akargokay4** [comment]
i cant find the issue

**Comment by UnamSanctam** [comment]
And you only changed the "API Endpoint URL" and nothing else? Not the wallet address?

**Comment by akargokay4** [comment]
i changed the wallet address too

**Comment by UnamSanctam** [comment]
Load my example back and only change the "API Endpoint URL", then you'll know if you messed something up with the wallet address.

**Comment by Gopnitsa** [comment]
unam i have very big problem. İ have too many miners but only 8 miners running how i solve it problem ?

**Comment by UnamSanctam** [comment]
> unam i have very big problem. İ have too many miners but only 8 miners running how i solve it problem ?

Problem is that you don't know if their computer is off or not. Only things you can do are, use better obfuscation/crypter for the file, ensure that you have "Bypass Windows Defender" enabled and make sure that your settings aren't causing lag or anything else for the user (for example don't use 100% Max CPU or something like that).

**Comment by Gopnitsa** [comment]
https://user-images.githubusercontent.com/96687176/151664905-f1f9b09e-90a9-4539-9c0f-136da4147633.mp4

**Comment by akargokay4** [comment]
what is your suggestions for max cpu idle cpu and max gpu idle gpu @UnamSanctam

**Comment by UnamSanctam** [comment]
> OPEN AUDİO

Haha, but we don't know if most of those have been offline for a few minutes or days (you'd have to check all of them or zoom out enough to see the "Last Connection" just by scrolling). You should always expect at least like half to be offline at any given time since people turn off their computers during the night and everyone's timezones differ, so for a lot of people it's currently nighttime.

> what is your suggestions for max cpu idle cpu and max gpu idle gpu @UnamSanctam

Usually 20% Max CPU - 80% Idle CPU and 50% Max GPU and 100% Idle GPU. Then you should also include as many games as you can into the "Stealth Targets" for the GPU miner so you (Windows has a limit for the command line so if you have thousands of games you should use the "Remote Configuration" or the web panels configuration to add them instead) can pause the miner and stop it from using VRAM during any games.

**Comment by akargokay4** [comment]
Can i change the algorithm of miner from the configuration setting on website remoteley ? Or what can i do from which i said section

**Comment by UnamSanctam** [comment]
Yes you can change the algorithm using the "Configurations" in the web panel using the same format as "Remote Configuration": https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration, https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration, which you can also get from the JSON tab in the builder.

**Comment by akargokay4** [comment]
So should i enable the remote configuration section while i am setting the miner properties to do it right ?

**Comment by UnamSanctam** [comment]
You can either use the "Remote Configuration" which is settings you host on something like pastebin/rentry or you can use the "Configurations" that exists on the panel.

**Comment by akargokay4** [comment]
So i can do changes to miner remoteley if i dont enable remote configuration while setting the miner ?

**Comment by UnamSanctam** [comment]
Yes you can do it in the web panel as well (without enabling "Remote Configuration" in the builder).

**Comment by akargokay4** [comment]
Okey thank you so much my friend. God bless you !!

**Comment by Gopnitsa** [comment]
> Yes you can do it in the web panel as well (without enabling "Remote Configuration" in the builder).

whats the different between rentry.com - without enable in the miner ?

**Comment by UnamSanctam** [comment]
> > Yes you can do it in the web panel as well (without enabling "Remote Configuration" in the builder).
> 
> whats the different between rentry.com - without enable in the miner ?

Not sure what you mean, if you want to use the "Remote Configuration" settings where you host settings on some paste site like pastebin or rentry then you need to enable that option and enter your paste URL. But you can also use the web panels built-in "Configurations" feature which does the same thing as the "Remote Configuration" but is just directly built into the panel instead.

**Comment by Gopnitsa** [comment]
> > > Yes you can do it in the web panel as well (without enabling "Remote Configuration" in the builder).
> > 
> > 
> > whats the different between rentry.com - without enable in the miner ?
> 
> Not sure what you mean, if you want to use the "Remote Configuration" settings where you host settings on some paste site like pastebin or rentry then you need to enable that option and enter your paste URL. But you can also use the web panels built-in "Configurations" feature which does the same thing as the "Remote Configuration" but is just directly built into the panel instead.

Oh okay now ı understand thank you so much

**Comment by Gopnitsa** [comment]
> can ı open rootkit ?

When i build with the rootkit miner cant work but build without rootkit miner run. Do you have any idea in this situation ?

**Comment by UnamSanctam** [comment]
You mean that the miners aren't showing in the checker when rootkit is enabled? The rootkit is quite intrusive and complex so it can have different effects on different computers, on mine and all my VMs everything works flawlessly but that won't necessarily be the case for all other computers.

**Comment by Gopnitsa** [comment]
can you see on your vm's etc ?

**Comment by Gopnitsa** [comment]
in my vm's i  only seeing rtm  with rootkit

**Comment by UnamSanctam** [comment]
Yes it works on my VMs (though not the ETC miner since my VMs don't have GPUs) and on my main computer.

**Comment by UnamSanctam** [comment]
> in my vm's i only seeing rtm with rootkit

Yes in your VM you shouldn't see ETC since it doesn't have a GPU to mine on.

**Comment by Gopnitsa** [comment]
can you send me a ss how seeing in your vm

**Comment by UnamSanctam** [comment]
On the VMs it shows only the RTM miner while on my main computer it shows both the ETC and RTM miner, like how it should be. The VMs doesn't have GPUs so the ETC miner can't mine and as such doesn't start.

**Comment by Gopnitsa** [comment]
ok thank you so much unam ı solve the problem 😄  have a good day thank you so much much 😄
