### ISSUE TITLE
Just lost 1 Worker

### ISSUE THREAD

**Issue by ENTERspaceAspaceUSERNAME** [UnamSanctam/SilentCryptoMiner#340]
I lost my ETH miner. It stopped working when I am looking at the graphics in the pool. Only the XMR one is running.

**Comment by UnamSanctam** [comment]
You mean that it's not showing up in the checker?

**Comment by ENTERspaceAspaceUSERNAME** [comment]
I didn't run the checker, so I don't know about that. But like in the statistics in the pool, only the XMR one is running I don't know why.

**Comment by UnamSanctam** [comment]
Which pool and how long has it not been running for? Is it on your computer or another one?

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Another one. It ran for about 1 day and 7 hours.

**Comment by UnamSanctam** [comment]
But it's XMR miner is still running?

**Comment by ENTERspaceAspaceUSERNAME** [comment]
It was running yesterday, but now it probably does not have wifi, because it shows 7 hours ago, it stopped at 1:55 am. The XMR miner was still running and stayed 6 hours more than the ETH one.

**Comment by UnamSanctam** [comment]
Yeah then it could be a laptop, did you see what GPU it had? Since laptops can "disable" the GPU while it doesn't think it needs to be used https://www.nvidia.com/en-us/geforce/technologies/optimus/technology/, because if it wasn't "disabled" then the watchdog should've started the miner again if anything happened (if you have watchdog enabled).

**Comment by ENTERspaceAspaceUSERNAME** [comment]
It was not a laptop and it had a RTX 3060. And yes, I had watchdog enabled.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
I will wait until monday to see if it goes back up.

**Comment by UnamSanctam** [comment]
Sounds good, though with an RTX 3060 it could be a laptop since a lot of them have that unless you know that it isn't a laptop from somewhere else.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
No, I go physically to the computer, that's how I installed the miner and ran the checker last time. It's a desktop computer.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Oh bro, it's back up with the 2 workers. Wifi probably went on. By the way is it normal that ethash mining gave me so much than mining monero directly?

**Comment by ENTERspaceAspaceUSERNAME** [comment]
I am doing both but like I get a lot more with ethash.

**Comment by UnamSanctam** [comment]
Yes GPU mining is much much more profitable than CPU mining but it also has much higher requirements and impacts the user experience a lot more. So while you're able to CPU mine on nearly any computer you can't GPU mine on all computers.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Oh alright.
