### ISSUE TITLE
Tutorial video

### ISSUE THREAD

**Issue by Kolhax** [UnamSanctam/SilentCryptoMiner#344]
I fully know how to use it personnally,

But a Tutorial Video Could be **GREAT** for peoples who dont know how to use it 😀

**Comment by Ukimud** [comment]
agree

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Unam, if you plan to make one, make sure it can't be removed by Youtube or don't put it on that platform or else it would be a waste of time.

**Comment by Brainshot** [comment]
> I fully know how to use it personnally,
> 
> But a Tutorial Video Could be **GREAT** for peoples who dont know how to use it 😀

What prevents you from making a tutorial and helping the owner post it here?

**Comment by Kolhax** [comment]
I ask to the community, I personally know I will do an bad job, if owner want to make a video, could be cool, he maybe can show us somes hidden options idk, who knows,

- Kepar
________________________________

**Comment by FireHack7z** [comment]
Vidéo tutorial make all script kiddie use it..

**Comment by Kolhax** [comment]
effectively 🤣🤣

- Kepar
________________________________

**Comment by terrorboy2021** [comment]
here II made a video about this: https://youtu.be/K3okxcnr0TE

**Comment by Kolhax** [comment]
I'll make one soon

- Kepar
________________________________

**Comment by b1g-Red** [comment]
haha anyone end up making one? Would be helpful

**Comment by Kolhax** [comment]
I cab try make one as soon as I out the hospital if u really want so
