### ISSUE TITLE
Miners dying out

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#345]
its bothering me really bad i aleardy have 200 miners on webpanel but alot of them stop mining after some time

i cant understand whats causing this, i have a long list of process killer and enabled windows defender bypass, also have watchdog and stealth on

why would so many factory reset? i dont get it

**Comment by Brainshot** [comment]
i am stuck at 2KH on raptoreum its really annoying

**Comment by Brainshot** [comment]
Does the CPU mining cause so much lag?

**Comment by UnamSanctam** [comment]
No CPU mining doesn't cause a lot of lag, do you mean that the "Last Connection" of them was a long time ago?

**Comment by Brainshot** [comment]
> No CPU mining doesn't cause a lot of lag, do you mean that the "Last Connection" of them was a long time ago?

Yes thats what i meant basically dead or disconnected, it bothers me alot

**Comment by Brainshot** [comment]
@UnamSanctam Or is it because raptoreum mining needs good luck? most of my miners are CPU but i have

i have 70 amd CPU miners, but the really good CPU ones just go away

**Comment by UnamSanctam** [comment]
No but what's your Max CPU set to? Most miners that disappear are usually due to some other user using the computer instead or because they download a new antivirus.

**Comment by Brainshot** [comment]
> No but what's your Max CPU set to? Most miners that disappear are usually due to some other user using the computer instead or because they download a new antivirus.

I set to 50% and when idle at 100%, i also have a big process killer list which kills most antiviruses that users use

Just dont know why they would go for a shady antivirus or factory reset all the time, raptoreum mining seems to not be that profitable i got 220 miners and yet my mining hashrate is still at 2KH average

**Comment by Brainshot** [comment]
> Then your settings are wrong in some way, post the settings you use here.

My settings are right i even checked many times, could you tell me if GPU mining is any laggier than cpu? would GPU mining be laggy when it comes to gaming only ?

**Comment by UnamSanctam** [comment]
Yes GPU mining is a lot laggier than CPU mining due to how GPUs work. But CPU mining generally doesn't really lag anything, though at 50% it will most likely cause the fans to spin more of course (due to a higher temperatures).

**Comment by Brainshot** [comment]
> Yes GPU mining is a lot laggier than CPU mining due to how GPUs work. But CPU mining generally doesn't really lag anything, though at 50% it will most likely cause the fans to spin more of course (due to a higher temperatures).
> 
> And what pool are you using?

Flockpool

**Comment by UnamSanctam** [comment]
Should be more I think at least, in your web panel try adding this into the "Default xmrig" configuration:
```
{
    "algo": "gr",
    "pool": "eu.flockpool.com",
    "port": 5555,
    "wallet": "YOURRTMWALLET.{COMPUTERNAME}",
    "ssltls": true,
}
```

**Comment by Brainshot** [comment]
> Should be more I think at least, in your web panel try adding this into the "Default xmrig" configuration:
> 
> ```
> {
>     "algo": "gr",
>     "pool": "eu.flockpool.com",
>     "port": 5555,
>     "wallet": "YOURRTMWALLET.{COMPUTERNAME}",
>     "ssltls": true,
> }
> ```

Ok i am gonna do this but i didnt have ssltls enabled in the builder will it still work if i use these settings?

**Comment by UnamSanctam** [comment]
Yes, and if you use the SSL port 5555 you need SSL/TLS enabled, the non-SSL port is 4444.

**Comment by Brainshot** [comment]
> Yes, and if you use the SSL port 5555 you need SSL/TLS enabled, the non-SSL port is 4444.

I aleardy use these settings, port is 4444 pool is same, the only thing i dont have is the worker name and the 5555 port

i didnt have the SSL/TLS enabled in the builder, should i still try using the settings you gave me?

**Comment by UnamSanctam** [comment]
Yes enter my settings into the "Default xmrig" configuration to see if your hashrate eventually increases. You can also try MoneroOcean to see if anything changes though it does pay out in XMR directly. MoneroOcean will show the RTM hashrate converted into XMR hashrate by default so you'll have to select "Raw Hashrate" to see the RTM hashrate.
```
{
    "algo": "rx/0",
    "pool": "gulf.moneroocean.stream",
    "port": 20032,
    "wallet": "YourXMRWallet",
    "password": "worker~ghostrider"
    "ssltls": true
}
```

**Comment by Brainshot** [comment]
@UnamSanctam 

https://user-images.githubusercontent.com/93741208/151833811-a71ea335-3413-4033-80f0-bd92485366c6.mp4

as you see so many are offline, so i suppose its removed

**Comment by Brainshot** [comment]
Also when i try to enter your json settings it tells me invalid json

{
    "algo": "gr",
    "pool": "eu.flockpool.com",
    "port": 5555,
    "wallet": "Hidingmywallet.Workers",
    "ssltls": true,
}

**Comment by UnamSanctam** [comment]
> Also when i try to enter your json settings it tells me invalid json

Yes remove the last comma after "ssltls".

> as you see so many are offline, so i suppose its removed

Yes or the computers are offline, since most people only have their computers running for a few hours a day (and maybe not every day). It depends on the "Last Connection" time, usually you can count on computers who haven't been online for a week to be removed.

**Comment by Brainshot** [comment]
> 

Alright understood, also how exactly does enabling ssltls increase hashrates?

**Comment by UnamSanctam** [comment]
It doesn't really, though it will make the connection secure, I just wanted you to try that to make sure that all settings were correct.

**Comment by Brainshot** [comment]
> It doesn't really, though it will make the connection secure, I just wanted you to try that to make sure that all settings were correct.

making the connection secure makes it so that hackers cant steal hash?

**Comment by Brainshot** [comment]
Ok thanks for help
