### ISSUE TITLE
WATCHDOG PROBLEM

### ISSUE THREAD

**Issue by akargokay4** [UnamSanctam/SilentCryptoMiner#346]
Checker says watchdog no if i obfuscate the miner file. Obfuscating decrease my detections but it doesnt allow to work watchdog. What should i do?

**Comment by UnamSanctam** [comment]
Sounds like you broke the watchdog during obfuscation.

**Comment by akargokay4** [comment]
Yeah i think so bcs i cant find a good obfuscator for this miner and you dont suggest me anythind and normay i broke it xd

**Comment by UnamSanctam** [comment]
There are a lot here if you want to find them a bit easier: https://github.com/NotPrab/.NET-Obfuscator, but the most important thing to turn off in the obfuscator is usually "Resource Encryption" since the miners resources are already encrypted so double encryption can cause some issues.

**Comment by akargokay4** [comment]
I need a crypter too bcs im using your downloader and binder too and i cant obfuscate them i think.

**Comment by UnamSanctam** [comment]
Yes they are purely written in C so they're native programs so yes you're correct in that you'll need a crypter for them.
