### ISSUE TITLE
Help code

### ISSUE THREAD

**Issue by monerrrr123** [UnamSanctam/SilentCryptoMiner#347]
Guys, please write the injection code to another application that the miner is injecting into explorer.exe

**Comment by UnamSanctam** [comment]
The injection code is right here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/e7d01c6c5ba7e9fd88e9cbcadd25c64c02773939/SilentCryptoMiner/Resources/Code/Program.cs#L454 if that's what you want.
