### ISSUE TITLE
Add please TON coin mining

### ISSUE THREAD

**Issue by VanekMorello** [UnamSanctam/SilentCryptoMiner#354]
Right now TON coin is the best coin for mining GPU with less than 4Gb, please and this coin for your program. This will be perfect solution for cards that are less than 4GB

**Comment by UnamSanctam** [comment]
Currently I'm not planning to add it but I believe Ton coin can only be mined for about 200 days more until the smart contracts run out of funds (unless they replenish them).

**Comment by VanekMorello** [comment]
thx for answer

**Comment by VanekMorello** [comment]
> Currently I'm not planning to add it right now since I barely have time but I believe Ton coin can only be mined for about 200 days more until the smart contracts run out of funds (unless they replenish them).

Excuse what is on the topic, please tell me which is the best obusifier to use, I use ConfuserEx it works badly - or I don’t set it up correctly, help me, tell me how to set it up - I tried it - after that the miner did not start
