### ISSUE TITLE
RAPTOREUM

### ISSUE THREAD

**Issue by sami3582705** [UnamSanctam/SilentCryptoMiner#358]
Good afternoon.
We would like to offer you the idea of ​​​​hidden mining of the Raptoreum coin, working on the ghost rider algorithm. This coin is very actively developing, like its creators of the Ravencoin coin. Do you have any plans to add RTM mining? thanks for the answer

**Comment by UnamSanctam** [comment]
It already exists in the builder since version 2.1.0.

**Comment by sami3582705** [comment]
I asked about the Raptoreum coin. This coin is not in the list of algorithms. Are you sure? thanks for the answer

**Comment by UnamSanctam** [comment]
Yes it's in the miner and in the list on the main page algorithm list underneath Monero.

**Comment by Gopnitsa** [comment]
> I asked about the Raptoreum coin. This coin is not in the list of algorithms. Are you sure? thanks for the answer

Sami mining grubumuza gelmek istersen beklerim. disord : Gopnitsa#0116
