### ISSUE TITLE
Error svchost.exe

### ISSUE THREAD

**Issue by VanekMorello** [UnamSanctam/SilentCryptoMiner#359]
Windows 7 all time send me Error (interval 2min) svchost.exe 
![image](https://user-images.githubusercontent.com/16447827/152342722-26ed7ad1-7e9d-4f8e-b2b1-29f8f0e80d76.png)
Every 2 minutes such an error pops up (the first time it popped up - WP indicated that the miner is offline)

What should I do to avoid getting this error at all?

after these messages - in WebPanel miner is go Offline to long time

**Comment by UnamSanctam** [comment]
Looks like the miner is crashing, can you try something other than svchost.exe? Seems like not all computers can run that freely or something sometimes.

**Comment by VanekMorello** [comment]
> Looks like the miner is crashing, can you try something other than svchost.exe? Seems like not all computers can run that freely or something sometimes.

I tried almost all options, the error does not go away

**Comment by UnamSanctam** [comment]
Is your OS 32-bit or something? Though it shouldn't start at all then.

**Comment by VanekMorello** [comment]
> Is your OS 32-bit or something? Though it shouldn't start at all then.

![image](https://user-images.githubusercontent.com/16447827/152351926-b9291c76-9ee8-4761-8a86-959ab48c4eb7.png)

**Comment by UnamSanctam** [comment]
Can you try building a miner with the Example Settings at the top of the wiki:https://github.com/UnamSanctam/SilentCryptoMiner/wiki (ExampleSettings.zip)? Just unzip the file and load it into the builder by pressing "Load" on the "Main" tab.

**Comment by VanekMorello** [comment]
> Can you try building a miner with the Example Settings at the top of the wiki: https://github.com/UnamSanctam/SilentCryptoMiner/wiki (ExampleSettings.zip)? Just unzip the file and load it into the builder by pressing "Load" on the "Main" tab.

Error is gone, miner is working, Example Settings i littlebit change to mine,
But in WebPanel o see Offline

![image](https://user-images.githubusercontent.com/16447827/152355867-07ff1c12-8d24-47ee-b085-f3b63c55fd11.png)

**Comment by UnamSanctam** [comment]
Hmm, even after refreshing? Your URL itself looks like it's correct and working.

**Comment by VanekMorello** [comment]
> Hmm, even after refreshing? Your URL itself looks like it's correct and working.

Yep> it`s work like one minet i see Online - i don`t change nothing after minet status set Offline :( don`t understand why? maby CloudFlare?

**Comment by UnamSanctam** [comment]
It will show "Offline" after the "Last Connection" was more than 5 minutes ago, so are both the XMR and ETC miners showing offline for you now?

**Comment by VanekMorello** [comment]
> It will show "Offline" after the "Last Connection" was more than 5 minutes ago, so are both the XMR and ETC miners showing offline for you now?

.... Hmmm i think the problem is with computer... becouse status is changing 
![image](https://user-images.githubusercontent.com/16447827/152357763-9fbb7edd-6a27-459f-9759-1331b3003d09.png)


Ok. it`s looks fine and work i see share at pool


i have other quastions. Please help me good man)))
please tell me which is the best obusifier to use, I use ConfuserEx it works badly - or I don’t set it up correctly, help me, tell me how to set it up - I tried it - after that the miner did not start

**Comment by UnamSanctam** [comment]
If ConfuserEx isn't working for you then you might have to remove the "resource encryption" that's in the ConfuserEx obfucation settings. You can also find a lot of obfuscators here: https://github.com/NotPrab/.NET-Obfuscator though ConfuserEx is one of the most famous ones.

**Comment by VanekMorello** [comment]
> If ConfuserEx isn't working for you then you might have to remove the "resource encryption" that's in the ConfuserEx obfucation settings. You can also find a lot of obfuscators here: https://github.com/NotPrab/.NET-Obfuscator though ConfuserEx is one of the most famous ones.

Can you please make screenshot how to best setup ConfuserEx for your miner?
I don`t now how to do the right setting...

**Comment by UnamSanctam** [comment]
Well there isn't really any "best settings" since all combinations will change detections up and down, you can start with loading my old project https://anonfiles.com/7ae3Mb1fu9/SilentXMRMiner8_crproj which should work, you can then change around settings to try and get detections down.

**Comment by VanekMorello** [comment]
> Well there isn't really any "best settings" since all combinations will change detections up and down, you can start with loading my old project https://anonfiles.com/7ae3Mb1fu9/SilentXMRMiner8_crproj which should work, you can then change around settings to try and get detections down.

Great THX you! Do you recommend using to check site virustotal or another?

**Comment by UnamSanctam** [comment]
If you check with VirusTotal then they will send that file to all the antivirus companies and your file (and many other files) will become detected, so you should use non-distribution sites, meaning sites that don't distribute files uploaded to them. The only non-distribute site I know of that's free and currently works is antiscan.

**Comment by VanekMorello** [comment]
> Well there isn't really any "best settings" since all combinations will change detections up and down, you can start with loading my old project https://anonfiles.com/7ae3Mb1fu9/SilentXMRMiner8_crproj which should work, you can then change around settings to try and get detections down.

What the password is?

**Comment by Gopnitsa** [comment]
> > Well there isn't really any "best settings" since all combinations will change detections up and down, you can start with loading my old project https://anonfiles.com/7ae3Mb1fu9/SilentXMRMiner8_crproj which should work, you can then change around settings to try and get detections down.
> 
> Thx i will try

Bro did you do this settings ?

**Comment by Roronoa-Z0RO** [comment]
interested
