### ISSUE TITLE
xmr

### ISSUE THREAD

**Issue by obamaklan** [UnamSanctam/SilentCryptoMiner#36]
![image](https://user-images.githubusercontent.com/84593653/141483584-7264e668-29d3-47fc-a42e-b3bd8bb7b64c.png)
hello, the ETC miner is working, that is, I will be selected in the pool, but the miner monero is not displayed

**Comment by UnamSanctam** [comment]
Why do you have `/Worker` in you wallet address (user)? For SupportXMR the worker names is entered in the password field like you've already done.

**Comment by obamaklan** [comment]
figured it out, thanks for the quick reply
