### ISSUE TITLE
taskkill

### ISSUE THREAD

**Issue by akargokay4** [UnamSanctam/SilentCryptoMiner#360]
I'm adding the kaspersky process name to kill targets but it cant kill the kaspersky. What should i do ?

**Comment by UnamSanctam** [comment]
Maybe you don't have permissions to kill it? Most antiviruses are installed as drivers so they are mostly unkillable by any normal means.

**Comment by akargokay4** [comment]
Yeah it says you dont have permission to kill it but what should i do for it i cant find any solution

**Comment by UnamSanctam** [comment]
Then you can't really kill it, to kill it you would need to either run what needs to kill it (in this case the miner) with the same permissions/elevation as the antivirus (most likely not possible) or you can uninstall the antivirus.

**Comment by akargokay4** [comment]
i cant uninstall the virus from target's computer xd ohh

**Comment by akargokay4** [comment]
antivirus*

**Comment by UnamSanctam** [comment]
Yes and neither can the miner (usually), which is the problem. What you can do though is probably to kill the Kaspersky GUI that the user can open to do scans and such.

**Comment by akargokay4** [comment]
yeah im trying to kill GUI process but i cant find it

**Comment by akargokay4** [comment]
i found it but still cant terminate

**Comment by UnamSanctam** [comment]
Can you kill it in the Task Manager?

**Comment by akargokay4** [comment]
no i definetely cant

**Comment by UnamSanctam** [comment]
Yes then the miner can't do so either, the miner can only do what you can (since it runs under your user).
