### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by spplew** [UnamSanctam/SilentCryptoMiner#361]
Does require admin option will prompt "Do you allow to make changes.." when miner start each time?

**Comment by UnamSanctam** [comment]
When you start it manually yes but not when it starts with Windows when you have "Startup" enabled, then it won't ask for anything.

**Comment by spplew** [comment]
And one more question. Where I can view constants like #REGADD?

**Comment by UnamSanctam** [comment]
They are inside the ReplaceGlobals function here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/e7d01c6c5ba7e9fd88e9cbcadd25c64c02773939/SilentCryptoMiner/Classes/Codedom.cs#L575

**Comment by spplew** [comment]
Thank you!
