### ISSUE TITLE
Dev protection

### ISSUE THREAD

**Issue by FireHack7z** [UnamSanctam/SilentCryptoMiner#362]
Hello, tell me can I convert the miner to a dll?? I would like to use in an assembly.invoke(obj new object[ { "URL API ENDPOINT " } ]. Invoke which is in a proxy dll , injected in explorer.exe , injected with hijack thread ^^

**Comment by DoCmAL1** [comment]
That isn't usually free information haha.

**Comment by UnamSanctam** [comment]
> Hello, tell me can I convert the miner to a dll?? I would like to use in an assembly.invoke(obj new object[ { "URL API ENDPOINT " } ]. Invoke which is in a proxy dll , injected in explorer.exe , injected with hijack thread ^^

Hmm depends on how exactly you're going to load it but either make it build as a DLL inside Codedom.cs or you can also just invoke the .exe, you don't necessarily need it to be a DLL to invoke a method in the assembly.

**Comment by FireHack7z** [comment]
YOU are a best programmer (SHARE, HELPING,DEVLOPING,CONTRIBUTING)..
thanks for this

**Comment by Roronoa-Z0RO** [comment]
interested
