### ISSUE TITLE
miner killer

### ISSUE THREAD

**Issue by 1aminov** [UnamSanctam/SilentCryptoMiner#365]
Is it possible to add the function of removing other people's hidden miners?

**Comment by UnamSanctam** [comment]
Not really, it can be difficult to find the miner hence why each build creates its own uninstaller and checker, because a universal uninstaller and checker wouldn't really work very well if at all.

**Comment by 1aminov** [comment]
and own uninstaller can remove another build?

**Comment by UnamSanctam** [comment]
No, there's no real easy way to know where a miner is installed, the uninstaller only knows since it got told where the miner is by the builder.
