### ISSUE TITLE
could not find loader.bin

### ISSUE THREAD

**Issue by jacklolidk** [UnamSanctam/SilentCryptoMiner#367]
yea so the zip file only came with the .exe

**Comment by jacklolidk** [comment]
build stopped on watchdog loader complie

**Comment by UnamSanctam** [comment]
Yes loader.bin gets generated by donut during the build, make sure that your antivirus isn't removing any files, you can also try to build it in another folder such as a simple folder on your Desktop.

**Comment by jacklolidk** [comment]
works
