### ISSUE TITLE
Watchdog timer

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#37]
The watchdog file appears in the folder after the file is started, it has certain antivirus detections, or can you take this file separately to clean it from antivirus detections, then add it to the project and compile the project with the modified file? I just did not find this file in the project.

**Comment by UnamSanctam** [comment]
It gets compiled with the miner, you can find it in the Resources: https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/Watchdog.cs
