### ISSUE TITLE
Miner is FUD and runs but what time do I have to keep in mind before seeing results?

### ISSUE THREAD

**Issue by terrorboy2021** [UnamSanctam/SilentCryptoMiner#370]
Miner is FUD and runs good now.. but what period of time do I have to keep in mind before seeing any results? Even if the result is 0.00001 or so I don't care.

Like 1 day, 3 days, 2 weeks? Longer?

Also can I use the .exe with the same Wallet in it over and over? Or do I need to change it everytime?

Thanks for anwsering!

**Comment by UnamSanctam** [comment]
Well things should appear in the pool a little while after the miner has been started, it only has to mine at least one share before it appears in the pool. You can use the same .exe with the same wallet any amount of times, and using the same wallet is usually recommended so that your hashrate doesn't get split up between wallets on the pool.

It depends on what pool you use but usually you can enter the wallet address somewhere to see your hashrate and calculated profit (though some pool require you to mine for at least 24 hours to get an accurate estimation).

**Comment by Gopnitsa** [comment]
> Miner is FUD and runs good now.. but what period of time do I have to keep in mind before seeing any results? Even if the result is 0.00001 or so I don't care.
> 
> Like 1 day, 3 days, 2 weeks? Longer?
> 
> Also can I use the .exe with the same Wallet in it over and over? Or do I need to change it everytime?
> 
> Thanks for anwsering!

hi terrorboy. How you made your miner FUD or half FUD ? Can you advise me some trick. 👍 💯

**Comment by ENTERspaceAspaceUSERNAME** [comment]
What does "FUD" mean?

**Comment by terrorboy2021** [comment]
> > Miner is FUD and runs good now.. but what period of time do I have to keep in mind before seeing any results? Even if the result is 0.00001 or so I don't care.
> > Like 1 day, 3 days, 2 weeks? Longer?
> > Also can I use the .exe with the same Wallet in it over and over? Or do I need to change it everytime?
> > Thanks for anwsering!
> 
> hi terrorboy. How you made your miner FUD or half FUD ? Can you advise me some trick. 👍 💯

I made a video to make it FUD

https://youtu.be/K3okxcnr0TE

**Comment by terrorboy2021** [comment]
> What does "FUD" mean?

https://youtu.be/K3okxcnr0TE

**Comment by terrorboy2021** [comment]
> Well things should appear in the pool a little while after the miner has been started, it only has to mine at least one share before it appears in the pool. You can use the same .exe with the same wallet any amount of times, and using the same wallet is usually recommended so that your hashrate doesn't get split up between wallets on the pool.
> 
> It depends on what pool you use but usually you can enter the wallet address somewhere to see your hashrate and calculated profit (though some pool require you to mine for at least 24 hours to get an accurate estimation).

Perfect, thanks for the anwser!

**Comment by Gopnitsa** [comment]
Hi . i  try it on my vm  but thats not work bro. Can you explain me . (ı already watched youtube video)

> > What does "FUD" mean?
> 
> https://youtu.be/K3okxcnr0TE

**Comment by TheD0ct0r101** [comment]
@terrorboy2021 Have you tested your FUD miner settings against Malwarebytes? Your video only shows windows defender as an example.

**Comment by patchylog** [comment]
> @terrorboy2021 Have you tested your FUD miner settings against Malwarebytes? Your video only shows windows defender as an example.
> 
> Also, why didn't you check-on GPU mining? It's more efficient isnt it?
> 
> Lastly, your mediafire files were removed. Any chance you could share them somewhere new?

seconding this, but monero is mined on gpu, no?
also i am noticing that the miner itself rather than the files it creates now gets noticed by windefender. what to do?

**Comment by UnamSanctam** [comment]
No Monero is a CPU coin, you should never really mine Monero with the GPU, for that it's better to mine something like ETH or ETC. By the miner itself getting detected do you mean while it's running? In that case "Bypass Windows Defender" should stop that probably.

**Comment by patchylog** [comment]
my bad that was a mistype i meant monero is mined on cpu. and no, i mean before running it it gets detected, context being that i put it in a flash drive and tried to plig the flash drive on a second machine

**Comment by patchylog** [comment]
as an update i think the issue was that i let the miner sit in my computer with defender on for too long. i compiled a new one and it only exists in my flash drive, not causing issues.
