### ISSUE TITLE
Can I pause / resume  mining with cmd or another process?

### ISSUE THREAD

**Issue by sunqibuhuake** [UnamSanctam/SilentCryptoMiner#375]
：）A great project ! 

I have a program writen in golang,Is there any way to pause / resume the miner with my program after the miner is installed?

Currently I have to uninstall the miner to stop and reinstall it to start mining again.

**Comment by UnamSanctam** [comment]
No you'd have to find and kill it or add some program into "Stealth Targets" that you start with your program when you want to pause it.

**Comment by sunqibuhuake** [comment]
> No you'd have to find and kill it or add some program into "Stealth Targets" that you start with your program when you want to pause it.

super thanks!!! I just created another program as a pausing signal
