### ISSUE TITLE
high consume ram xmr stealth mode on

### ISSUE THREAD

**Issue by derzbot2002** [UnamSanctam/SilentCryptoMiner#378]
Hello, i have an issue when i infect my pc and I open task manager, i could see the process consuming high ram like 2gb and the steath mode is on with task manager 
![image](https://user-images.githubusercontent.com/98950427/153272060-e571be89-0435-43d9-9118-9c86ba99ffec.png)

**Comment by UnamSanctam** [comment]
Yes it's due to RandomX (clearing the RAM doesn't always work when paused), you could try another algorithm/coin like GhostRider/Raptoreum (which is also more profitable than XMR at the moment) that doesn't use as much RAM.
