### ISSUE TITLE
miner records with same computer name were overwritten in web panel

### ISSUE THREAD

**Issue by sunqibuhuake** [UnamSanctam/SilentCryptoMiner#379]

**Comment by UnamSanctam** [comment]
They should only be overwritten if they have the same computer name and CPU,
https://github.com/UnamSanctam/UnamWebPanel/blob/e77456f9a54e8abccc435ec0107c16b07c706ef6/UnamWebPanel/api/endpoint.php#L16

**Comment by sunqibuhuake** [comment]
Unfortunately, it does ... xddd.

Thanks for your guiding,I have modified this line and.
