### ISSUE TITLE
Crypto miner not working

### ISSUE THREAD

**Issue by Akane124** [UnamSanctam/SilentCryptoMiner#382]
When I ran the XMR miner on debug mode (no stealth) nothing happened, my cpu didn't go up, but an intresting fact is that the checker showed my specs even when I didn't run the miner. Just to clarify, for supportxmr.com, I don't need a password/worker name, right? all I need is the wallet.

**Comment by Akane124** [comment]
I turned every option off except cpu mining up to 90%, and debug mode on.

**Comment by UnamSanctam** [comment]
No, SupportXMR requires a password (worker name) otherwise they will reject the connection.
