### ISSUE TITLE
api connection webhook discord

### ISSUE THREAD

**Issue by derzbot2002** [UnamSanctam/SilentCryptoMiner#384]
How I showld connect to my API and create a discord webhook or some advisor?

**Comment by UnamSanctam** [comment]
The "API Endpoint URL" is for the web panel https://github.com/UnamSanctam/UnamWebPanel if that's what you mean, for a Discord hook you'd have to add code that does that yourself into Program.cs, here is code for a Discord webhook that someone made in the Discord server before: https://pastebin.com/chCw8jjQ.

**Comment by Roronoa-Z0RO** [comment]
interested
