### ISSUE TITLE
What if install a new build before uninstalling the last installed?

### ISSUE THREAD

**Issue by sunqibuhuake** [UnamSanctam/SilentCryptoMiner#386]
Currently I update the miner by uninstalling the last installed and then install the new build .

I just wanna know that is it ok to update by always installing and never  uninstalling?

**Comment by sunqibuhuake** [comment]
Looks like that the new miner and old miner will run in parallel
Is that right

**Comment by UnamSanctam** [comment]
Depends, if the "Startup" settings are the same then it will theoretically replace it, but the new miner that gets installed can't kill the old miners running (because there's no way to find them) so the computer would need a restart probably.

**Comment by sunqibuhuake** [comment]
Thx,I know :)
