### ISSUE TITLE
Several miners

### ISSUE THREAD

**Issue by torche14654** [UnamSanctam/SilentCryptoMiner#392]
Hello, thank you very much for your work :)

I had a question if I put several miners for example:
ETC
ETH
XMR

If I launch it (the miner) I will mine the 3 crypto or the miner will choose the most adapted?

I also have the webpanel

Thanks in advance and have a great day!

**Comment by UnamSanctam** [comment]
No it will start all three of them. Usually the best is to add one XMR (CPU) and one ETH/ETC (GPU), since you have the web panel then you can do XMR and ETC and then change any miner to ETH through the web panel if you think they have a good enough GPU.

**Comment by torche14654** [comment]
Thank you for your advice, so if I put XMR (cpu) and ETH (gpu) and that the miner has both compatible it will mine both? and another question on my web panel it will be marked only XMR?

And last question do you accept donations on the polygon network (matic)?

**Comment by UnamSanctam** [comment]
Yes exactly it will mine both if it can, on the web panel it would show both the XMR and ETH miners (you can see the type by expanding a miner, or by checking the wallet address format).

And yes I accept donations on the polygon network with my ETH address here: https://github.com/UnamSanctam/SilentCryptoMiner#donate
