### ISSUE TITLE
[Request] Set 'p2pool' as the default XMR pool. (no fees)

### ISSUE THREAD

**Issue by benhall847** [UnamSanctam/SilentCryptoMiner#393]
On behalf of the Monero Community,
I ask that 'p2pool' is set as the default XMR pool for this app.

p2pool will benefit your users - 
there are **no % payout fees** 
& **no minimum withdraw limit**.

p2pool is a decentralized pool that will help strengthen the Monero network.

The Monero community has been concerned with the growth & centralization of mining hashrate in the 'minexmr' pool
https://www.reddit.com/r/Monero/comments/st40o0/psa_informational_thread_regarding_the_minexmr/
https://www.reddit.com/r/Monero/comments/sti1um/monero_51_attack_dodged_thank_god_because_all_of/
https://www.reddit.com/r/Monero/comments/stekvw/minexmr_hashrate_drops_from_50_to_38_after_monero/
https://www.reddit.com/r/Monero/comments/sse4b1/stop_minexmr_p2pool_guide_how_to_mine_xmr_using/

If you could help us grow the p2pool by making it default (with the option to edit pools), it would be a huge contribution to the Monero Project.
Please let me know if there is anything I can do to help or answer any questions.

Thank you for your time & consideration.

**Comment by UnamSanctam** [comment]
Currently I don't intend to have a default pool, especially p2pool since all users have to set up their own p2pool and I don't believe most are able to do that but I do definitely recommend using it, might add it into the wiki in some way. But most that use my miner don't use MineXMR which does help a bit.
