### ISSUE TITLE
Having issues setting up panel

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#4]
https://i.imgur.com/SDGHDcp.png

I am using 000webhost i put all files into public_html and changed the config.php password

but i dont understand the second step

**Comment by UnamSanctam** [comment]
Change the 000webhost PHP version, it's at 7.0 by default. I'm also about to upload a new version soon that makes it a bit easier.

**Comment by Brainshot** [comment]
> 
> 
> Change the 000webhost PHP version, it's at 7.0 by default. I'm also about to upload a new version soon that makes it a bit easier to set it up.

What webhosting website should i use ?

also heres a pic of my settings https://i.imgur.com/djsii3i.png

**Comment by UnamSanctam** [comment]
https://www.000webhost.com/forum/t/how-to-change-upgrade-or-downgrade-php-version-of-my-website, follow this and change the PHP version to PHP 8.

**Comment by Brainshot** [comment]
> 
> 
> https://www.000webhost.com/forum/t/how-to-change-upgrade-or-downgrade-php-version-of-my-website, follow this and change the PHP version to PHP 8.

Thanks alot i got into my webpanel

should i use https:// in the API ENDPOINT URL?

**Comment by UnamSanctam** [comment]
Yes if you can, I believe the 000webhost sites do have https. So you can enter `https://websiteurl.com/api/endpoint.php` into the miner (replace websiteurl.com with your URL).

**Comment by Brainshot** [comment]
> 
> 
> Yes if you can, I believe the 000webhost sites do have https. So you can enter `https://websiteurl.com/api/endpoint.php` into the miner (replace websiteurl.com with your URL).

Weird i did everything perfect but there is nothing showing on in my panel

**Comment by UnamSanctam** [comment]
Wait one minute after starting the miner so that it can submit some data.

**Comment by Brainshot** [comment]
> 
> 
> Wait one minute after starting the miner so that it can submit some data.

Its working now, btw can the panel show what GPU someone has?

**Comment by UnamSanctam** [comment]
Yes it shows the GPU, you can expand the miner in the datable by pressin the + if you have a smaller screen.

**Comment by Brainshot** [comment]
> 
> 
> Yes it shows the GPU, you can expand the miner in the datable by pressing the + if you have a smaller screen.

But it doesnt show CPU for monero? i cant find it

**Comment by Brainshot** [comment]
Alright big thanks to you man 

My last question is how do i use the Configurations? for what are they and what json can i add ?

**Comment by suckma420** [comment]
1 question please, does the server have to be 24/7 or I just need XAMPP to host it in my windows machine whenever I need it?

**Comment by UnamSanctam** [comment]
> Alright big thanks to you man
> 
> My last question is how do i use the Configurations? for what are they and what json can i add ?

It's the same as the "Remote Configuration" but instead it can be set directly in the panel. You can create configurations based on these https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration and https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration.



> 1 question please, does the server have to be 24/7 or I just need XAMPP to host it in my windows machine whenever I need it?

It doesn't need to be on 24/7, if it can't connect to the panel then it will just skip it. It will keep mining on with the current settings it has until it's told something else.

**Comment by suckma420** [comment]
OK, thanks man
