### ISSUE TITLE
gluing two files 

### ISSUE THREAD

**Issue by wiqsap** [UnamSanctam/SilentCryptoMiner#40]
Tell me, is it possible to sew it with administrator rights (bypassing Windows defender) into a file with administrator rights so that you do not have to confirm administrator rights twice?

**Comment by UnamSanctam** [comment]
Yes my binder can do that though I still have to update it to bypass the new Windows Defender detections that were added like a few days ago.

**Comment by wiqsap** [comment]
That is, when you activate obfuscation. at the first stage I have to make Crypt, and at the second stage I have to glue the files? If so, in which program can you advise to work.

Could you please correct me if I misunderstood?

**Comment by UnamSanctam** [comment]
What are you binding it with? Some other file? You can just build the miner and then use some binder to combine the two files.

**Comment by wiqsap** [comment]
For example, I have a miner that asks to run itself on behalf of the administrator.

and there is a program installer that asks to run itself on behalf of the administrator.

how can I glue them together so that there is no double confirmation. (just after gluing, he asks to run on behalf of the administrator twice and it looks strange)

**Comment by UnamSanctam** [comment]
Just use a binder that has the option to run as administrator, if the binder runs as administrator then it will also run the files bound as administrator.
