### ISSUE TITLE
When both eth miner and xmr miner are included, the eth miner sometimes fails to start

### ISSUE THREAD

**Issue by sunqibuhuake** [UnamSanctam/SilentCryptoMiner#402]
I added both xmr miner and eth miner while building.
When running, the eth miner always starts after the xmr miner starts and sometimes doesn't even start.
Both miners are configured with remote config.

**Comment by sunqibuhuake** [comment]
Just to add, there is no problem with startup when there is only eth miner

**Comment by UnamSanctam** [comment]
Well the miners start sequentially from your miners list in the builder, do you mean that it sometimes doesn't start the ETH miner on the same computer? Does it do the same if you try the example settings from the top of the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki?

**Comment by sunqibuhuake** [comment]
Eth miner is the first and xmr miner is the second in my list.
This issue will happen when remote config is configured

**Comment by UnamSanctam** [comment]
Is your "Remote Configuration" correct then?

**Comment by sunqibuhuake** [comment]
I'm sure  it's correct couse I use it in the single miner build and it works well.

One more thing is that even though the both miner started, xmr miner (second one in the miner list) cannot submit data to it's own endpoint address.

Only when I disable the eth miner's endpoint config, the xmr miner's endpoint config will take effect smoothly.

**Comment by UnamSanctam** [comment]
What host are you using? It works on my local computer (have the panel running on a local XAMPP).
