### ISSUE TITLE
Couple of questions before I test this out.

### ISSUE THREAD

**Issue by TheD0ct0r101** [UnamSanctam/SilentCryptoMiner#403]
When the builder makes a miner.exe, am I able to;

- Put that miner.exe on a USB stick,
- Run it from said stick
- After I run it from a USB stick on a new computer, can I unplug the USB stick? Or do I need to copy the miner.exe from the stick to a permanant place on the computer?

**Comment by UnamSanctam** [comment]
Yes you can do that, when you run it if you have "Startup" enabled then it will copy itself to a permanent place.

**Comment by TheD0ct0r101** [comment]
Sweet. Loving how you thought of everything

**Comment by Roronoa-Z0RO** [comment]
well step dude
