### ISSUE TITLE
Somehow the miner is not working 

### ISSUE THREAD

**Issue by Marvv4n** [UnamSanctam/SilentCryptoMiner#404]
![image](https://user-images.githubusercontent.com/100006279/154813563-962d91a0-2a1e-43c7-90e7-ea0d10bf6675.png)

thank you for your great crypto miner but can you please tell me if its working once i make a new config and edit it in cp ?
as well as i dont see gpu only cpu and its not even blocking in the pool .. please help

**Comment by UnamSanctam** [comment]
That means your configuration settings are wrong, post them here.

**Comment by Marvv4n** [comment]
thank you for ur replay ( {
    "algo": "rx/0",
    "pool": "nodes.hashvault.pro",
    "port": 18081,
    "wallet": "8BQAzQwVETtFWGmAFZjAwNSYA7M4EczfocpPa2kZ6AiC1tVQuAhJTRjLG5Nkk4QqFWHxiKBdi6RuUFjC5zMhvhUyK7tatMA",
    "password": "",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 3,
  "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}  ) this is my defult i want to change it to ( {
    "algo": "rx/0",
    "pool": "nodes.hashvault.pro",
    "port": 18081,
    "wallet": "8BQAzQwVETtFWGmAFZjAwNSYA7M4EczfocpPa2kZ6AiC1tVQuAhJTRjLG5Nkk4QqFWHxiKBdi6RuUFjC5zMhvhUyK7tatMA",
    "password": "",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 3,
  "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
} )

i made mistake in my wallet i hit save but it never saves .. as well as my eth is ( {
    "url": "stratums://`0xecd57d4449a9efbd5483889f0432f7dc9ea6fccf`.Services32@eu1.ethermine.org:5555",
    "algo": "ethash",
    "max-gpu": 40,
    "idle-wait": 6,
    "idle-gpu": 90,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "mbam.exe,mbamgui.exe,mbamservice.exe"
} )
please help me to set them up remotly

**Comment by Marvv4n** [comment]
as well as i relly have a problem with hashwault pool idk how to do it... the eth is ok but xmr is giving me a headeche

**Comment by UnamSanctam** [comment]
You pool is incorrect, it should be `pool.hashvault.pro` and the port for that should be something like `443`

**Comment by Marvv4n** [comment]
should i re do everything or make it remotly ? 
thank you so muchh

**Comment by Marvv4n** [comment]
wallet is not connecting to this port only on 18080... is it normal to use diff port for wallet and 80 for my miner ?

**Comment by Marvv4n** [comment]
![image](https://user-images.githubusercontent.com/100006279/154814158-987ab5a5-d78c-44d1-83e9-bfb3e52585a2.png)
my wallet only connect to this one ... anyway thank you soo much i will join tele server now

**Comment by UnamSanctam** [comment]
Yes miners connects to pools while wallets connects to nodes.
