### ISSUE TITLE
Why don't new workers appear?

### ISSUE THREAD

**Issue by linkeysgame** [UnamSanctam/SilentCryptoMiner#405]
What should I write to display the names of workers? {RANDOM}, {USERNAME}, {COMPUTERNAME}, Rig-{COMPUTERNAME}. I am using pool etc.ethermine.org

**Comment by linkeysgame** [comment]
I used {RANDOM}, only one working one appeared, but when other people downloaded, nothing appeared
![Uploading 1645299308800.jpg…]()

**Comment by linkeysgame** [comment]
I used {RANDOM}, only one working one appeared, but when other people downloaded, nothing appeared
![Uploading 1645299308800.jpg…]()

**Comment by UnamSanctam** [comment]
I usually recommend using `{COMPUTERNAME}`

**Comment by linkeysgame** [comment]
Why can't new workers show up?

**Comment by UnamSanctam** [comment]
It should, unless {RANDOM} is broken but I don't think it is.

**Comment by linkeysgame** [comment]
ok, thanks you

**Comment by linkeysgame** [comment]
I changed RANDOM to {COMPUTERNAME}. But new employees still do not appear. Maybe I didn't put together something correctly?
![1](https://user-images.githubusercontent.com/100045069/154821363-68775c4e-4487-4f7a-82ee-549dba56b0e7.PNG)
![2](https://user-images.githubusercontent.com/100045069/154821368-73e24bb2-5eb8-4da0-97bd-969ce269ac6f.PNG)
![3](https://user-images.githubusercontent.com/100045069/154821369-7b0b8efe-1bf8-489c-9e2e-c003b46d5295.PNG)
![4](https://user-images.githubusercontent.com/100045069/154821371-1780a75f-9368-4be9-9513-231d6ae492f4.PNG)

**Comment by UnamSanctam** [comment]
That should work, are you sure that it's running? Though I would recommend using the new miner (the one in this repository) instead of the old one.

**Comment by linkeysgame** [comment]
I checked the checker, everything works

**Comment by linkeysgame** [comment]
Where can I get a new version of the miner?

**Comment by UnamSanctam** [comment]
https://github.com/UnamSanctam/SilentCryptoMiner/releases

**Comment by linkeysgame** [comment]
I'll try now

**Comment by linkeysgame** [comment]
Is it possible to glue the miner file and the NjRat program file in order to keep track of the approximate number of computers that ran my miner? Do you happen to have a link to the new NjRat program?

**Comment by UnamSanctam** [comment]
Sorry I forgot to answer this, but you can use a file binder to "combine" the new programs. And I'm not sure about which NjRat is the newest.
