### ISSUE TITLE
How do I hide the .exe in other programs?

### ISSUE THREAD

**Issue by brettypooh** [UnamSanctam/SilentCryptoMiner#406]
i made the .exe miner, how do I set it up so that if you run a certain program itll also run the miner?

**Comment by UnamSanctam** [comment]
You would have to use a file binder to bind the miner and the program you want it to run together into one file.

**Comment by brettypooh** [comment]
thank you for a reply, im new to this whole thing, do you know where I can learn how to do that?

**Comment by UnamSanctam** [comment]
You can search for file binders online (there are quite a lot), I also have one at https://github.com/UnamSanctam/UnamBinder that you can try as well.

**Comment by DoCmAL1** [comment]
> You can search for file binders online (there are quite a lot), I also have one at https://github.com/UnamSanctam/UnamBinder that you can try as well.

will this be updated?
