### ISSUE TITLE
Miner is getting detected by Windows Defender and other AVs immediately.

### ISSUE THREAD

**Issue by TheD0ct0r101** [UnamSanctam/SilentCryptoMiner#407]
I've toggled pretty much every stealth feature that exists and ran encrypters on the watchdog and miner, but nothing seems to make the miner FUD. What am I doing wrong?

**Comment by TheD0ct0r101** [comment]
cough

**Comment by UnamSanctam** [comment]
Ah sorry I didn't press "Comment", you'd have to find a good enough obfuscator (or crypter) that does it, though you probably won't be able to find a crypter/obfuscator that makes any complex enough program fully FUD without spending a lot of money (depending on perspective). I also work on reducing detection all the time for new releases but things gets detected really quickly (obviously).
