### ISSUE TITLE
it has an address changer written in it!!!!

### ISSUE THREAD

**Issue by hdirtyfinger** [UnamSanctam/SilentCryptoMiner#408]
no matter what address u input it changes it to his payment address! running this program is litterally spreading a distributed crypto-jacker for him!!! and he didnt even do that good of a gob, he only has 300h/s check it out its on monero.hashvault.pro, although hell probably switch pools now... nice try goofball!

**Comment by DoCmAL1** [comment]
look at the code and show us where it has an address changer

**Comment by sunqibuhuake** [comment]
Well...maybe there is a bit of  dev fee but I'm sure it won't overwrite your address totally

**Comment by sunqibuhuake** [comment]
xmrig has a default dev fee. Maybe the xmr miner and eth miner  execuable file used in this project were both compiled by the author.

Build the miner from the souce code  then replace the miner in this repo, and build this project from source, In this case there will be absolutely  no dev fee.

**Comment by Roronoa-Z0RO** [comment]
show the code where you found that , shortly prove your speech

**Comment by TheD0ct0r101** [comment]
> no matter what address u input it changes it to his payment address! running this program is litterally spreading a distributed crypto-jacker for him!!! and he didnt even do that good of a gob, he only has 300h/s check it out its on monero.hashvault.pro, although hell probably switch pools now... nice try goofball!

You could at least prove what you are saying... If you dont it makes you look bad.

**Comment by UnamSanctam** [comment]
It sounds like you have a crypter clipper on your computer, run an antivirus to remove it.

**Comment by Marvv4n** [comment]
No its not its just clipper from out source but the miner is gd
