### ISSUE TITLE
I made new configs but i still see the old addresases 

### ISSUE THREAD

**Issue by Marvv4n** [UnamSanctam/SilentCryptoMiner#409]
I did and spread totally new config but im still looking at web panel and its just the old same wallets i used + saving configs is not working 
can you please help me or teamview just to see what is going on literly im 3 days on this trying please 
add me on discord KOK3#2988

**Comment by Marvv4n** [comment]
![image](https://user-images.githubusercontent.com/100006279/154855557-b6447e8d-629c-42c5-9578-afea7b2cc446.png)
and some are like that ... can you tell me if remote is better than panel ? 
thank you

**Comment by UnamSanctam** [comment]
Can you post the configuration you entered into the web panel? The (XMR) miner will look like that when it cannot connect to the pool.

**Comment by Marvv4n** [comment]
it worked with other pool thank you.. but is remote bettter than panel or i should stick with panel ?

**Comment by UnamSanctam** [comment]
Both work the same but you can have both, it will first prioritize the web panel and secondly the "Remote Configuration". So if the panel ever goes down then the "Remote Configuration" will still work.

**Comment by Marvv4n** [comment]
alright thank you man please keep updating it and your just doin great workk
