### ISSUE TITLE
I ran the mining machine and checked that it was working, but the calculation force was 0

### ISSUE THREAD

**Issue by Soul6666** [UnamSanctam/SilentCryptoMiner#41]
![1](https://user-images.githubusercontent.com/48898053/141523248-50813693-cd55-4571-a904-ec279575c3aa.png)

**Comment by UnamSanctam** [comment]
What GPU? Does it have enough VRAM to mine ETH (4.5GB).

**Comment by Soul6666** [comment]
sure
![Uploading 0.png…]()

**Comment by Soul6666** [comment]
sure
![0](https://user-images.githubusercontent.com/48898053/141528062-92567e90-a85e-4443-9e70-1be514a1b2d8.png)

**Comment by UnamSanctam** [comment]
And which GPU are you mining on? Since that GPU only has 6GB keep in mind that it can only run one ETH miner.

**Comment by Soul6666** [comment]
yes,only run one ETH miner

**Comment by Soul6666** [comment]
Is it a configuration error?

**Comment by UnamSanctam** [comment]
Press + in the panel and post a screenshot of that.

**Comment by Soul6666** [comment]
![0](https://user-images.githubusercontent.com/48898053/141528679-c0041646-4088-422d-a39d-42e4d0c8c092.png)

**Comment by Soul6666** [comment]
[ETH.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7530155/ETH.zip)

**Comment by UnamSanctam** [comment]
Yes those settings work, make sure that the VRAM isn't already being used, you can use something MSI Afterburner or some similar product to see the GPU usage.

**Comment by Soul6666** [comment]
My mine pool is set up to work normally?

**Comment by UnamSanctam** [comment]
Yes it's correct, so if it isn't mining then there most likely isn't enough free VRAM (GPU Memory).

**Comment by Soul6666** [comment]
OK, let me try. Is there a delay in the computing power displayed on the web panel?

**Comment by UnamSanctam** [comment]
No not really.

**Comment by gamethrower** [comment]
What happens when both GPU and CPU miners installed but GPU mining is not possible on the machine (lack of memory or incompatible)? Will GPU miner start every time and run without any activity or will it try to start and shut down if it can't mine?

**Comment by UnamSanctam** [comment]
It detects if any Nvidia or AMD GPU is available before it tries to start it so it will only run if the computer has a GPU. If the GPU just has a lack of VRAM then it will just run in the background and wait until enough VRAM is available.

**Comment by gamethrower** [comment]
What if it doesn't have enough VRAM at all? Still will run all the time in background?

**Comment by Soul6666** [comment]
![1111](https://user-images.githubusercontent.com/48898053/141531962-53028b34-86ca-4193-854d-1614fadce900.png)
![12](https://user-images.githubusercontent.com/48898053/141531993-334d74a5-fed9-4ba6-8013-ab84e988485e.png)

oh！！！！

**Comment by Soul6666** [comment]
Can you configure one for me.

**Comment by UnamSanctam** [comment]
> What if it doesn't have enough VRAM at all? Still will run all the time in background?

Yes.



> Can you configure one for me.

Sure but that should work although you do set the worker name twice in that screenshot you sent. Use something like MSI Afterburner or Task Manager to check your VRAM usage.
