### ISSUE TITLE
Please Consider F2Pool CFX

### ISSUE THREAD

**Issue by Coin238u** [UnamSanctam/SilentCryptoMiner#414]
### Hi, I have been using your programs for awhile now, sadly profitability has dropped off so much it feels like I need to do twice the work to get an equal amount compared to a month or two ago, and than 6 months before that.

I was looking at the mining profitability statistics per gpu on minerstat.com,
everything looks pretty bad with eth mainly topping everything, however it looks like mining cfx to f2pool gives really high profits compared to eth: https://minerstat.com/coin/F2POOL-CFX with the octopus mining algorithm 
Would you please consider adding support for this coin with this algo in the future?

**Comment by Coin238u** [comment]
I could be wrong but it looks like its 5x more profitable? I am probably missing something but I am just comparing the calculators

**Comment by Coin238u** [comment]
i think im wrong about something because eth is just as profitable on this pool, do you know why?

**Comment by Coin238u** [comment]
I'm not sure if its just this specific pool, can you please explain this: here is a site calculator link as well: https://www.f2pool.com/calculator?miner_id=91&currency=eth

**Comment by UnamSanctam** [comment]
CFX isn't more profitable than ETH on any card I believe, you can use https://whattomine.com/. Remember that every algorithm produces different hashrates (which is what it shows at the top of whattomine).

At the moment ETH is still the most profitable GPU coin.

**Comment by Coin238u** [comment]
> CFX isn't more profitable than ETH on any card I believe, you can use https://whattomine.com/. Remember that every algorithm produces different hashrates (which is what it shows at the top of whattomine).
> 
> At the moment ETH is still the most profitable GPU coin.
![Screenshot_50](https://user-images.githubusercontent.com/100127800/154946392-363a8028-f4ca-46fa-a223-03eca3d701ba.png)
![Screenshot_49](https://user-images.githubusercontent.com/100127800/154946400-872b731c-58ef-4d10-9f3a-53faf367b486.png)
I don't understand this then?

**Comment by UnamSanctam** [comment]
It's only the current profitability for that pool calculated by the current block rewards, difficulty and price of CFX, it could change at any time. But yes higher end cards can be momentarily more profitable for other algorithms (looks like currently only the RTX 3000 series is more profitable for CFX). Though for other cards it's the opposite.

**Comment by Coin238u** [comment]
> It's only the current profitability for that pool calculated by the current block rewards, difficulty and price of CFX, it could change at any time. But yes higher end cards can be momentarily more profitable for other algorithms (looks like currently only the RTX 3000 series and maybe the 2080TI is more profitable for CFX). Though for other cards it's the opposite.

Ah I understand, thank you. If it continues this way for a bit, will you consider adding a miner for this?

**Comment by UnamSanctam** [comment]
Yes then it's possible.
