### ISSUE TITLE
Issues giving miners id's in pools

### ISSUE THREAD

**Issue by Kidblunder** [UnamSanctam/SilentCryptoMiner#417]
Title

**Comment by UnamSanctam** [comment]
You mean worker names? What did you enter as a worker name? By default miners just group together under whatever worker name you set (or under none/default if you don't enter any at all). If you want each miner to have its own worker name then enter something like `{COMPUTERNAME}` as the worker name.

**Comment by Kidblunder** [comment]
Sorry where would I enter a worker name, I'm not great at this lmao

**Comment by UnamSanctam** [comment]
Depends on the pool, in most pools it's done by entering it into the "Wallet Address" field in the format: `WalletAddress.WorkerName`
