### ISSUE TITLE
help bro

### ISSUE THREAD

**Issue by 1234567898765432345678** [UnamSanctam/SilentCryptoMiner#419]
Bro in which file is the size of the commission for the developer?

**Comment by Roronoa-Z0RO** [comment]
interested, i dont think he gonna tell you

**Comment by UnamSanctam** [comment]
For XMRig (the XMR miner) the default is 1% (or 0%, might've changed it to that) and it can be changed by adding `--donate-level=1` (for 1%) into "Advanced Parameters", for the ETH miner there shouldn't be a dev fee.

**Comment by 1234567898765432345678** [comment]
okay. if i change the donation for example by 50% then where can i change the wallet for donat

**Comment by Roronoa-Z0RO** [comment]
> For XMRig (the XMR miner) the default is 1% (or 0%, might've changed it to that) and it can be changed by adding `--donate-level=1` (for 1%) into "Advanced Parameters", for the ETH miner there shouldn't be a dev fee.

can you specifiy the donation field in the source code please

**Comment by UnamSanctam** [comment]
There's no such thing inside the builder code, you'd have to compile your own custom XMRig.
