### ISSUE TITLE
Getting issues with binding

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#42]
so silent crypto miner lets you add many miners i added a monero and etc

the etc miner works but monero miner shows 0 hashes on webpanel

**Comment by UnamSanctam** [comment]
Then the settings are wrong. Which pool are you trying to connect to?

**Comment by Brainshot** [comment]
> 
> 
> Then the settings are wrong. Which pool are you trying to connect to?

gulf.moneroocean.stream:10128

but it should be right

**Comment by UnamSanctam** [comment]
Make sure that the XMR address is correct.

**Comment by Brainshot** [comment]
> 
> 
> Make sure that the XMR address is correct.

its right

**Comment by UnamSanctam** [comment]
Can you expand it by pressing the '+' and then screenshot and post it?

**Comment by Brainshot** [comment]
> 
> 
> Can you expand it by pressing the '+' and then screenshot and post it?

Wait i think i know the issue now i used password as a worker name

Should i keep it emtpy?

**Comment by UnamSanctam** [comment]
No the password field is for worker names on MoneroOcean so that is fine.

**Comment by Brainshot** [comment]
> 
> 
> No the password field is for worker names on MoneroOcean so that is fine.

all my settings are right those are the ones i used when i used silent xmr miner

i guess it could be the cmd.exe issue but not sure

**Comment by UnamSanctam** [comment]
No but sometimes pools can bug, can you send a screenshot from the web panel (after expanding it and censoring things if you want to)?

**Comment by Brainshot** [comment]
> 
> 
> No but sometimes pools can bug, can you send a screenshot from the web panel (after expanding it and censoring things if you want to)?

https://i.imgur.com/Fc3qWkd.png

**Comment by UnamSanctam** [comment]
And the "User" only has your XMR address and nothing else at all?

**Comment by Brainshot** [comment]
> 
> 
> And the "User" only has your XMR address and nothing else at all?

Dont understand what you mean my settings are the pool, port, my xmr address and password

**Comment by Brainshot** [comment]
> 
> 
> And the "User" only has your XMR address and nothing else at all?

no the user is also mining on ETC for me

**Comment by UnamSanctam** [comment]
I mean the "User" field in the web panel, also called the "Wallet Address" field. If it only has the XMR address and nothing more then either that person is blocked by MoneroOcean (if using some VPN) or the pool connection got bugged (from the pools side) in which case restarting it can help, or setting some other connection using the "Configuration".

**Comment by Brainshot** [comment]
> 
> 
> I mean the "User" field in the web panel, also called the "Wallet Address" field. If it only has the XMR address and nothing more then either that person is blocked by MoneroOcean (if using some VPN) or the pool connection got bugged (from the pools side) in which case restarting it can help, or setting some other connection using the "Configuration".

Alr big thanks how do i set other connection using configuration? btw the etc mining works for them but not xmr

**Comment by UnamSanctam** [comment]
In the "Configurations" page you can add a new configuration formatted like the "Remote Configuration" https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration and then you can apply it on that miner (the dropdown).

**Comment by Brainshot** [comment]
> 
> 
> In the "Configurations" page you can add a new configuration formatted like the "Remote Configuration" https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration and then you can apply it on that miner (the dropdown).

How do i stop the xmr mining? with configuration

**Comment by UnamSanctam** [comment]
You don't "stop" it, you create a new configuration and use that (you can use the same configuration), then it will create a new connection with those settings.

**Comment by Brainshot** [comment]
> 
> 
> You don't "stop" it, you create a new configuration and use that (you can use the same configuration), then it will create a new connection with those settings. Or it will probably just work without you doing anything on the next restart as well.

Do you have the configuration settings for Ethereum classic? i aleardy got the xmr one

**Comment by UnamSanctam** [comment]
Yes in the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration

**Comment by Brainshot** [comment]
Btw what happens if i change the configuration to none?

**Comment by UnamSanctam** [comment]
Then it will just return nothing and use whatever current settings it has.
