### ISSUE TITLE
The miner is installed once

### ISSUE THREAD

**Issue by maksblak777** [UnamSanctam/SilentCryptoMiner#420]
The miner was tested on 2 computers on each of them, it should work 100%. one works, the other doesn't. also when rebuilt it worked for 2, but I'm afraid it's getting worse because out of 500 downloads a couple of workers in total can be 40 maximum, I doubt that this is a coincidence. Is it possible to fix this somehow I really look forward to your help (assemblies work 100%)

**Comment by UnamSanctam** [comment]
Try the example settings at the top of the wiki: https://github.com/UnamSanctam/SilentCryptoMiner/wiki and see if it always works with those. That doesn't really say much so I can't know if that's a bug for you or not.

**Comment by maksblak777** [comment]
settings all identical no errors

**Comment by maksblak777** [comment]
in total 1220 downloads, yes, probably 200 pools and so on for the test, but it doesn’t matter where they fail, it’s nice that it could be that the video cards are weak, etc., but out of 1220, so little can you give some recommendations

**Comment by UnamSanctam** [comment]
Is your miner completely FUD? Since otherwise some of those downloads could've been removed by whatever antivirus they have.

**Comment by maksblak777** [comment]
all antiviruses for workers are disabled

**Comment by UnamSanctam** [comment]
Does the build you've shared use "Microsoft\services.exe" as the "Startup" "Filename" or something else? Since certain game anticheats can block access to certain folders including the "Microsoft" folder.

**Comment by maksblak777** [comment]
we use classic
.but the meaning is a little different, but that it is installed or launched every other time

**Comment by UnamSanctam** [comment]
Sorry I didn't really understand, do you use "Microsoft\services.exe" (the default/classic)? In that case use something else like it's done in the example settings ("Chrome\updater.exe). Programs like Riot Vanguard seem to block access to the Microsoft folder meaning that it can't install then.

The code for the installation can be found here ttps://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/Program.cs from line 28 to line 122, but I haven't really found any bugs or problems related to installation.

**Comment by maksblak777** [comment]
in principle, everything works as it should, this is not the case in the file path, well, we found a way out of the situation, we update it every day and so everything seems to be working, maybe we will of course hurt a little that we update every day, do you recommend updating the miner like this or it makes no sense ?thank you very much in advance you help us a lot )

**Comment by UnamSanctam** [comment]
If you still have some issues you can try the new version.
