### ISSUE TITLE
Web Dashboard showing only one miner on same network

### ISSUE THREAD

**Issue by aerocover55** [UnamSanctam/SilentCryptoMiner#428]
Hello,

First of all i really apreciate your efforts, i have two miners on the same local wifi network and both are mining when i check with the miner-checker, but on the web dashboard only one is showing, if i add another miner on a different network it shows on a new line but from the two miners on different computers on the same network only one is showing, i have tried generating new miners and deployed them on two different networks and it works, but the issue stays with two miners on the same network, can it be due to the IP adress ? thanks,

**Comment by UnamSanctam** [comment]
The unique ID is currently generated from the computer name CPU name (https://github.com/UnamSanctam/UnamWebPanel/blob/e77456f9a54e8abccc435ec0107c16b07c706ef6/UnamWebPanel/api/endpoint.php#L16), so if both of those are the same then both will appear as one, but there's not really anything with the IP.
