### ISSUE TITLE
cant mine

### ISSUE THREAD

**Issue by doener2323** [UnamSanctam/SilentCryptoMiner#429]
I dont know why, but my miner is not working.
Then I compared your JSON examples with mine and found out that, there is a '`' after 'stratum://'
Is that the reason why my miner is not working?
If so, how do I fix that?

![image](https://user-images.githubusercontent.com/79750105/155887322-e24c2255-288d-4dc0-b375-e8989ef97725.png)

**Comment by doener2323** [comment]
with "not working" i mean that i dont get showed as a worker in my dashboard

**Comment by UnamSanctam** [comment]
No the ` before and after the wallet address should be there (encodes what's in it in case of any special characters), what's the pool address that you've entered? Also, is the miner running if you run the checker?
