### ISSUE TITLE
No mining states or shares 

### ISSUE THREAD

**Issue by loadeddypper** [UnamSanctam/SilentCryptoMiner#436]
I am testing the latest version of the miner in a VMWare machine but can't get any shares, this is my json miner config
```
{
    "algo": "rx/0",
    "pool": "xmr.2miners.com",
    "port": 2222,
    "wallet": "",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 80,
    "idle-wait": 0,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}
```
the miner is left running for 4 hours and still no shares while in another vm with different miner but using the same pool i got some shares 
I ran the `checker` and got this output 
```
Watchdog Running: Yes
Miners:
--algo=rx/0 --randomx-no-rdmsr --url=xmr.2miners.com:2222 --user=<xmr-wallet>--pass=<password>--cpu-max-threads-hint=80 --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-idle-wait=0 --cinit-idle-cpu=80
--algo=kawpow --randomx-no-rdmsr --url=rvn.2miners.com:6060 --user=<rvn-wallet> --pass=<password>--cpu-max-threads-hint=80 --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --no-cpu --cuda --opencl --cinit-idle-wait=0 --cinit-idle-cpu=80
GPUs:
 Microsoft Basic Display Adapter
Compatible GPU found: False
```
using TMX taskmanager i can see some cpu usage up tp 75% but didn't get any shares

**Comment by shainodev** [comment]
> 

Compatible GPU found: False

I'm really sure you cant mine with a non-compatible gpu.

**Comment by UnamSanctam** [comment]
If the miner is using CPU (check if the injected miner process is using CPU) then it's mining, then most likely you haven't found any shares due to bad luck and low hashrate.

**Comment by Nobellium1** [comment]
Are there gonna be any updates / new projects on your github?

**Comment by UnamSanctam** [comment]
Yes of course, I'm always working on updates, I've finished most of the difficult work for the next miner version (custom system wide idle detection for example).

**Comment by Nobellium1** [comment]
That's perfect, glad to see this is still going on because I'm personally using it. Thanks for all the time and effort you put into this project!
