### ISSUE TITLE
Error: An error occured while building the file: Could not load file or assembly 'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Не удается найти указанный файл.

### ISSUE THREAD

**Issue by sainteoff** [UnamSanctam/SilentCryptoMiner#44]
Hi, when creating a build, it gives this error
Error: An error occured while building the file: Could not load file or assembly 'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Не удается найти указанный файл.

**Comment by UnamSanctam** [comment]
Install .NET Framework 4.5.
