### ISSUE TITLE
Question about the uninstaller

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#443]
After using the miner uninstaller do you have to restart your PC?

**Comment by UnamSanctam** [comment]
No you don't have to restart.

**Comment by Brainshot** [comment]
> No you don't have to restart.

Then why did it only work for me after restarting?

Or is it because my miner isnt working? my settings are all correct and have startup enabled.

**Comment by UnamSanctam** [comment]
You can see what the uninstaller does here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/Uninstaller.cs, on some computers it's possible that the uninstaller isn't allowed to kill the miner but it still gets installed.

**Comment by Brainshot** [comment]
> You can see what the uninstaller does here: https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/Uninstaller.cs, on some computers it's possible that the uninstaller isn't allowed to kill the miner but it still gets installed.

Yes but it was uninstalled for me only after restarting i dont understand.

**Comment by Brainshot** [comment]
I also cant download anymore and when i drag silentcryptominer to my desktop it just doesnt do anything

**Comment by Brainshot** [comment]
I get access denied

**Comment by UnamSanctam** [comment]
Then there's something with your computer.

**Comment by Brainshot** [comment]
> 

Yes it wasnt like this, i accidently opened my own miner and uninstalling it only worked after restarting it.

After restarted it was gone but my silencryptominer couldnt open anymore and gave me access denied even redownloaded

**Comment by UnamSanctam** [comment]
You can try to remove the miner manually: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner and also run the rootkit uninstaller manually if you enabled that: https://github.com/UnamSanctam/SilentCryptoMiner/raw/master/SilentCryptoMiner/Resources/rootkit-u.zip.
