### ISSUE TITLE
Few general questions

### ISSUE THREAD

**Issue by CantFindMe1337** [UnamSanctam/SilentCryptoMiner#444]
So I spent a bit testing out the silentcryptominer and webpanel but I couldn't get it to work. I would clikc the build and it would just have a little loading icon then nothing, It didnt start the miner, could it because I was testing it on a VPS?, I used miner pool us-west.minexmr.com:4444 but no workers would show up on the panel or pool

**Comment by UnamSanctam** [comment]
Don't use MineXMR, use another pool. But if you run the checker then you should see if the miner is running.

**Comment by CantFindMe1337** [comment]
Oh okay thanks, will test in a bit with new pool, and what would the checker say to confirm the miner is running? All i was seeing is no compatible GPU found and watchdog on

**Comment by UnamSanctam** [comment]
It will show the command line options for your running miners under the "Miners:" text.
