### ISSUE TITLE
random workername

### ISSUE THREAD

**Issue by doener2323** [UnamSanctam/SilentCryptoMiner#448]
how can i make it always having a random worker name?

in ethermine you cant mine with the same worker name if there is already a worker name with the worker name you are trying to mine with

**Comment by UnamSanctam** [comment]
You can mine to any pool with the same worker name just fine, it will just combine the hashrate under that worker name. But if you want separate worker names there's this in the wiki:
>The miner also supports dynamic worker names by using either {COMPUTERNAME}to use the computers name,{RANDOM}to generate a new random worker name every run or {USERNAME} to use the username as the worker name. Keep in mind that it's possible that some pools might have worker limits although it seems like it is often not enforced.

So for that I would recommend {COMPUTERNAME}
