### ISSUE TITLE
Miner doesnt show up in the panel

### ISSUE THREAD

**Issue by Ywly23** [UnamSanctam/SilentCryptoMiner#449]
Yes the miner appears to be running
![image](https://user-images.githubusercontent.com/92166830/156932666-4ce76d86-fa3b-49e7-a2d3-45b0f3a4df7a.png)
But there isn't any working miners in the web panel
![image](https://user-images.githubusercontent.com/92166830/156932707-350e9048-6762-409c-a5d2-1fc4f44098ac.png)
Is there any things I missed or does it take time to update?
@UnamSanctam

**Comment by UnamSanctam** [comment]
Make sure that unamwebpanel.db and its parent folder has write permissions, also make sure that your webserver isn't forcing https (which some do). Also, if you visit the endpoint.php webpage do you get the "Error: Invalid data" page (what you should get)?

**Comment by Ywly23** [comment]
They have write permissions and when I visit endpoint.php i get the error (https://cdn.upload.systems/uploads/JaQkHxRn.png)
And how can I tell if its forcing https

**Comment by Ywly23** [comment]
If its "Force HTTPS Redirect" then its off

**Comment by UnamSanctam** [comment]
Can you try going to the "Configurations" tab and creating a new configuration? Then if you reload the page and the configuration is still there in the list then writing to the database works (meaning it's something else).

**Comment by Ywly23** [comment]
https://cdn.upload.systems/uploads/UP8mbqno.png

**Comment by UnamSanctam** [comment]
The problem is most likely that the database doesn't have enough permissions to write or the PHP version is too old (should be 7.4 or newer). Go to __UNAM_LIB\Logs and see if there are any error files there, alternatively check if you have any error.log files anywhere.

**Comment by Ywly23** [comment]
No logs except "dummy"
And the php version was 7.2 and I changed it to 7.4 
Still doesnt work though

**Comment by Ywly23** [comment]
also it has all perms what I can give it.


Read User, Group, World
Write User, Group, World
Execute User, Group, World

**Comment by UnamSanctam** [comment]
Does the parent folder have write permissions as well?

**Comment by Ywly23** [comment]
ye i think so

**Comment by Ywly23** [comment]
https://cdn.upload.systems/uploads/Ht25LENZ.png

**Comment by Ywly23** [comment]
+ everything inside

**Comment by UnamSanctam** [comment]
Check all the folders for an error.log file, since any error should write one to either __UNAM_LIB\Logs or the standard PHP error.log. Unless something doesn't have permission to write the error log or if the webserver has disabled it completely.

**Comment by Ywly23** [comment]
I searched and it didn't say I had any error.log files

**Comment by Ywly23** [comment]
There was these logs
ssl_log-Mar-2022
log-Mar-2022

**Comment by Ywly23** [comment]
Wait do I need to reboot the webserver after changing versions?

**Comment by UnamSanctam** [comment]
Maybe, depends on how the webserver is set up.

**Comment by Ywly23** [comment]
so what can I do now?

**Comment by Ywly23** [comment]
Does it normally take some time to show up in the panel?

**Comment by UnamSanctam** [comment]
The miner contacts the panel every minute, but you might have to change your "API Endpoint URL" to https (from http) since you have a certificate and everything.

**Comment by Ywly23** [comment]
the xml I have https://pastebin.com/raw/F4tbbLUr

**Comment by UnamSanctam** [comment]
Yes, and try changing the http to https in your endpoint URLs. Also, can you now successfully save a configuration in the "Configurations" tab?

**Comment by Ywly23** [comment]
Not with the xml above

**Comment by Ywly23** [comment]
nvm im retarded i gotta get the other config file

**Comment by Ywly23** [comment]
http > https works
