### ISSUE TITLE
Would {COMPUTERNAME} work if i put it in the builder not the remote configuration 

### ISSUE THREAD

**Issue by Werloo** [UnamSanctam/SilentCryptoMiner#452]
I dont want to get a remote config. 
Would it work if i put {COMPUTERNAME} in the builder

**Comment by UnamSanctam** [comment]
Yes of course, you can put {COMPUTERNAME} in any pool/wallet/password field and it will replace it.

**Comment by Werloo** [comment]
Thanks for the response.
