### ISSUE TITLE
Miner not turning on

### ISSUE THREAD

**Issue by yrgroup692** [UnamSanctam/SilentCryptoMiner#453]
I am testing the latest version of the miner, it does not run no CPU load, this is my json miner config. 
{
    "algo": "rx/0",
    "pool": "pool.supportxmr.com",
    "port": 3333,
    "wallet": "42iNFtaBgeMWETMHN66ectF1AxPxkPMbTF8HtC5GvmhmEhE4r1uW3EDdDryLzdNfJ4eYzhvdm6A11Zgbw94KHd3B26PzkoK",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 50,
    "idle-wait": 0,
    "idle-cpu": 80,
    "stealth-targets": "",
    "kill-targets": ""
}

The miner first appears, and then turns off. I disabled my antivirus
I ran the checker and got this output:

Not run as Administrator, only non-administrator miners can be searched for.
Watchdog Running: No
Miners:
--algo=rx/0 --randomx-no-rdmsr --url=pool.supportxmr.com:3333 --user=42iNFtaBgeMWETMHN66ectF1AxPxkPMbTF8HtC5GvmhmEhE4r1uW3EDdDryLzdNfJ4eYzhvdm6A11Zgbw94KHd3B26PzkoK --pass= --cpu-max-threads-hint=50
GPUs:
 AMD Radeon(TM) R4 Graphics
Compatible GPU found: True

**Comment by UnamSanctam** [comment]
SupportXMR requires a password as the worker name.

**Comment by yrgroup692** [comment]
thank you
