### ISSUE TITLE
which part of code 

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#454]
which part of code i should obfuscation

for not detected from anti viurs 

program.cs ?

or libs.zip ??

**Comment by UnamSanctam** [comment]
Program.cs since it's the miner installer/injector, then you can also obfuscate Watchdog.cs.

**Comment by tarekxxx** [comment]
obfuscate  Program.cs and Program.cs anything else ?

**Comment by UnamSanctam** [comment]
Ah sorry I missed the notification for this issue, but yes Program.cs and Watchdog.cs are the main parts of the code.
