### ISSUE TITLE
country ban question (ethermine)

### ISSUE THREAD

**Issue by parabola20** [UnamSanctam/SilentCryptoMiner#456]
*using google translator*

Hi. Today I saw this title on ethermine, does this mean that all working miners from the "red countries" will stop working?
I mean, is it worth switching to another pool, or will miners from blocked countries continue to allocate hashrate?
I also use remote configuration

![photo_2022-03-07_23-46-13](https://user-images.githubusercontent.com/94918344/157107283-1fe625f5-2515-44ec-a3fb-2e275732253f.jpg)

**Comment by UnamSanctam** [comment]
It's a bit unclear but it sounds like you will not be able to "connect" to the site (including mining) from any of those countries, so changing to another pool might be required to continue mining from any of those countries.

**Comment by parabola20** [comment]
> It's a bit unclear but it sounds like you will not be able to "connect" to the site (including mining) from any of those countries, so changing to another pool might be required to continue mining from any of those countries.

if you manage to figure it out later, I will be grateful if you answer here

**Comment by UnamSanctam** [comment]
Sure, but most likely you will be unable to mine from any of those countries.

**Comment by parabola20** [comment]
> Sure, but most likely you will be unable to mine from any of those countries.

it's a pity. what pool would you recommend for the transition? I heard flexpool also introduces restrictions

**Comment by UnamSanctam** [comment]
Yes I think flexpool (and many others) is doing the same thing as well, I don't think 2miners is doing that though so you could try using them.

**Comment by golxd** [comment]
> _using google translator_
> 
> Hi. Today I saw this title on ethermine, does this mean that all working miners from the "red countries" will stop working? I mean, is it worth switching to another pool, or will miners from blocked countries continue to allocate hashrate? I also use remote configuration
> 
> ![photo_2022-03-07_23-46-13](https://user-images.githubusercontent.com/94918344/157107283-1fe625f5-2515-44ec-a3fb-2e275732253f.jpg)

**what is this pool?**

**Comment by UnamSanctam** [comment]
> **what is this pool?**

It's Ethermine (and Flexpool).
