### ISSUE TITLE
Is this one working?

### ISSUE THREAD

**Issue by Smurfboi007** [UnamSanctam/SilentCryptoMiner#46]
[Test.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7533787/Test.zip)

Hello! I'm just wondering if this one work. I can't test it myself (Not good enough GPU).

**Comment by UnamSanctam** [comment]
Can you send the save file instead so I can check the options?

**Comment by Smurfboi007** [comment]
Sorry for not understanding but what do you mean with the save file?

**Comment by UnamSanctam** [comment]
Go to the "Main" tab and press the "Save" file to save the configuration.

**Comment by Smurfboi007** [comment]
Will do

**Comment by Smurfboi007** [comment]
[Test.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7533785/Test.zip)

**Comment by UnamSanctam** [comment]
Yes that works, though the nanopool password should be set like that but like this: [Test2.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7533796/Test2.zip)

**Comment by Smurfboi007** [comment]
Oh ok, but the remote config will overwrite that right?

**Comment by UnamSanctam** [comment]
Yes the "Remote Configuration" will become the main connection and the builder settings will become the backup connection.

**Comment by Smurfboi007** [comment]
Alright, sounds good! Thanks once again!
