### ISSUE TITLE
are you able to add a feature to pause the miner?

### ISSUE THREAD

**Issue by Azzerzz** [UnamSanctam/SilentCryptoMiner#460]
in the next update is there a way you can add a way to pause the miner so people dont have to uninstall it and reinstall it? possibly from the web panel.

**Comment by UnamSanctam** [comment]
You can just add explorer.exe into the "stealth-targets" in the configuration and it would be permanently paused.

**Comment by Azzerzz** [comment]
> You can just add explorer.exe into the "stealth-targets" in the configuration and it would be permanently paused.

what if people dont want it perm paused? i sometimes want to stop the miner for a while to let my pc cool down, or if i am trying to do something that i didnt add to the stealth target list and dont want to limit preformance

**Comment by UnamSanctam** [comment]
Then you can just remove it from the list, or you can even have multiple configurations in the "Configurations" tab, one of which can be a pause configuration that you can apply to whatever miner you want when you want it paused. If I added a pause feature then it would do the exact same thing as if you were to add explorer.exe into the "stealth-targets". Not sure what you mean by the second part.
