### ISSUE TITLE
Remove Action from webpanel does not work

### ISSUE THREAD

**Issue by NightFuryPrime** [UnamSanctam/SilentCryptoMiner#461]
Hello There,

Just right from the begining i really love your hard work, keep it up

Case: When i remove bot from the panel, it goes away for 1minute and than comes back again. Also i checked the proceses and it is still running.
Settings: NO setting except pool setup are set (watchdog off, startup off basicaly everything off)

Any ideas how to fix ?

**Comment by UnamSanctam** [comment]
Yes you are removing the miner from the panel, but the miner will just get re-added the next minute when it contacts the web panel again, the remove button does not blacklist the miner from connecting to the web panel.

The web panel is not a RAT so it will of course not uninstall (or kill) the miner in any way (nor does the miner contain any code for uninstallation inside it so it wouldn't be possible anyways), to do that you would have to run the uninstaller.

**Comment by NightFuryPrime** [comment]
i do not consider this as a rat :) but simple management for workers.. will there be any posibility in the future to add removal from device and panel as well?

**Comment by UnamSanctam** [comment]
No it's not really possible to do, for that it would have to be a RAT. Since you'd have to send your uninstall file that gets generated with the miner to the computer and then run that file. The miners itself (xmrig and ethminer) contains no uninstallation code at all (and can't really contain it either).

**Comment by NightFuryPrime** [comment]
okay, thank you for your time and help, #closerequest
