### ISSUE TITLE
An error occurred while creating the file

### ISSUE THREAD

**Issue by welltom233** [UnamSanctam/SilentCryptoMiner#462]
the path is indicated in English letters
error:
An error occurred while creating the file: Could not load file or assembly 'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The specified file was not specified.

What could be the problem?

**Comment by UnamSanctam** [comment]
Sounds like you might not have .NET Framework 4.5 (or 4) installed, try installing it first.

**Comment by welltom233** [comment]
> Sounds like you might not have .NET Framework 4.5 (or 4) installed, try installing it first.

thanks
