### ISSUE TITLE
No Injection option and Remote Url

### ISSUE THREAD

**Issue by NightFuryPrime** [UnamSanctam/SilentCryptoMiner#463]
Hello There,

I would like to ask if its possible to set for NO injection?
and what are the settings for Advanced Parametres? and in WebGui what remote url represents?

Thank you

**Comment by UnamSanctam** [comment]
No, if it had no injection then it would have to extract the miners (xmrig.exe and ethminer.exe) somewhere and run them which isn't a very good idea. The "Advanced Parameters" is a field if you want to enter any command line settings from xmrig or ethminer. "Remote URL" shows the "Remote Configuration" URL.

**Comment by UnamSanctam** [comment]
Yes of course, the most effective is to mine something like Monero or Raptoreum with the CPU and then Ethereum or Ethereum Classic with the GPU. So create two miners in the list, I have some example settings at the top of the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki that you can load into the builder as an example.

**Comment by NightFuryPrime** [comment]
thanks, gona try :)
