### ISSUE TITLE
Binance Pool ETH setup

### ISSUE THREAD

**Issue by NightFuryPrime** [UnamSanctam/SilentCryptoMiner#464]
Hello,

I have trouble setting up binance mining pool. 

i am using pool ethash.poolbinance.com:25
worker name: myprivateethminer.001
password: 123456
wallet: nothing
extra data: nothing
algo: ethash
after running miner for 15min my worker does not show up in binance pool and my gpu is at 0% utilization

Any ideas how to fix?

**Comment by UnamSanctam** [comment]
You should put the mining account username in the wallet field: https://www.binance.com/sv/support/faq/9bd21a9536d74d1fb65c83f8e60ded93. otherwise binance won't know to what account you're mining.

**Comment by NightFuryPrime** [comment]
--cinit-algo=ethash --pool=stratum://`myprivateethminer`.myprivateethminer.001:123456@ethash.poolbinance.com:25  --cinit-max-gpu=100

still the same problem, gpu utilization at 0%

**Comment by UnamSanctam** [comment]
I don't think that's a valid configuration, shouldn't it be `stratum://myprivateethminer.001@ethash.poolbinance.com:25`? Since `myprivateethminer` in that case is the "Mining Account" name you chose when you created your account and `001` is the worker name. There also isn't a need for a password I think since Binance (and most other pools) ignore that field, they just have one in the example.

Also, what GPU do you have and how are you checking GPU utilization?

**Comment by NightFuryPrime** [comment]
i am using gpu-z and checking the performance of my gpu.

--cinit-algo=ethash --pool=stratum://`myprivateethminer.001`@ethash.poolbinance.com:25  --cinit-max-gpu=100

same issue, even if i use/don't use password

**Comment by UnamSanctam** [comment]
Run the checker and post all that it returns here, you do have at least 5GB of free VRAM as well right (since that's what Ethereum requires)?

**Comment by NightFuryPrime** [comment]
Not run as Administrator, only non-administrator miners can be searched for.
Watchdog Running: No
Miners:
--cinit-algo=ethash --pool=stratum://`myprivateethminer.001`@ethash.poolbinance.com:25  --cinit-max-gpu=100
GPUs:
 NVIDIA GeForce GTX 1660 SUPER
Compatible GPU found: True

**Comment by UnamSanctam** [comment]
Make sure that you have enough free VRAM, Ethereum currently requires at least 4.7GB https://minerstat.com/dag-size-calculator. Since you probably only have 6GB of VRAM in total you might not have enough free VRAM.

**Comment by NightFuryPrime** [comment]
tested with different pool and its working 

Not run as Administrator, only non-administrator miners can be searched for.
Watchdog Running: No
Miners:
--cinit-algo=ethash --pool=stratum://`0x016C9F51CCca544e36903f1076Baf5Df79Df5DB3`.0x016C9F51CCca544e36903f1076Baf5Df79Df5DB3:x@eth.2miners.com:2020  --cinit-max-gpu=100 --cinit-api="https://********.cz/api/endpoint.php"
GPUs:
 NVIDIA GeForce GTX 1660 SUPER
Compatible GPU found: True

**Comment by UnamSanctam** [comment]
Yeah then it's something with the pool settings, I've never used Binance pool before though I've helped someone once with it but  it worked for them then.
