### ISSUE TITLE
Error running exe

### ISSUE THREAD

**Issue by RealKolasi** [UnamSanctam/SilentCryptoMiner#467]
![image](https://user-images.githubusercontent.com/78981984/158079870-06b89b54-460a-4475-8b1b-5d4d0b4f2161.png)

**Comment by RealKolasi** [comment]
i also have the latest .net framework installed 🤔

**Comment by UnamSanctam** [comment]
I would try rebuilding it and see.

**Comment by RealKolasi** [comment]
i've rebuilt it about 4 times same error

**Comment by UnamSanctam** [comment]
Try restarting the builder (you can Save/Load the configuration on the Main page), could be something with some encryption key or something.

**Comment by RealKolasi** [comment]
will try now thanks

**Comment by RealKolasi** [comment]
![image](https://user-images.githubusercontent.com/78981984/158214992-c596c754-dede-4f72-9fbf-6b20706be7f5.png)

**Comment by RealKolasi** [comment]
I will try compiling my own builder with the src code

**Comment by UnamSanctam** [comment]
It sounds like your antivirus is removing things.

**Comment by RealKolasi** [comment]
> It sounds like your antivirus is removing things.

aha didnt realise it was on 😌

**Comment by RealKolasi** [comment]
![image](https://user-images.githubusercontent.com/78981984/158216479-df78387a-9a97-4d74-9c37-3cf8e4595b94.png)
still the same issue 🤔

**Comment by UnamSanctam** [comment]
Try saving it in another folder, especially with no special characters. It sounds like it cannot find the miner payload (either gets removed or can't find it).

**Comment by RealKolasi** [comment]
> Try saving it in another folder, especially with no special characters. It sounds like it cannot find the miner payload (either gets removed or can't find it).

compilation is fine now just the initial error

![image](https://user-images.githubusercontent.com/78981984/158218004-edbf5c6d-8bae-4482-881c-e63fb72ab70b.png)

**Comment by UnamSanctam** [comment]
Hmm, it's unable to decrypt something but not sure what, can you post your save file? Can you also test the example settings from the top of the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki and see if it happens with those settings?

**Comment by RealKolasi** [comment]
[ufectnano.txt](https://github.com/UnamSanctam/SilentCryptoMiner/files/8246893/ufectnano.txt)
my own settings

**Comment by RealKolasi** [comment]
default setting are working so something is up with my settings, :?

**Comment by UnamSanctam** [comment]
And are the URLs you enter correct?

**Comment by RealKolasi** [comment]
![image](https://user-images.githubusercontent.com/78981984/158248697-50ae06bf-96f9-4aa6-a794-2534c2a35017.png)

all i need?

**Comment by RealKolasi** [comment]
do i need both or one

**Comment by RealKolasi** [comment]
![image](https://user-images.githubusercontent.com/78981984/158255213-4337306a-f71a-4ae4-89db-14c71edac5ec.png)

**Comment by UnamSanctam** [comment]
Yes but that's not the URL you entered in the builder.

**Comment by RealKolasi** [comment]
thanks man
