### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by FixPrimee** [UnamSanctam/SilentCryptoMiner#469]
I propose to make the possibility of automatic selection of a coin for mining. For example, if the system requirements are not suitable for eth, then etc will be mined, then xmr

**Comment by UnamSanctam** [comment]
Well my miner/builder is very dynamic so that wouldn't really be possible without making another completely new builder, because my miner is not limited to ETH/ETC/XMR but you can mine any coin you want with any of the supported algorithms.
