### ISSUE TITLE
Adding manual input for the "Inject into" option

### ISSUE THREAD

**Issue by aerocover55** [UnamSanctam/SilentCryptoMiner#470]
Good evening,

Can you please consider making the "inject into" option support manual input ? i for example want to bind the miner with a certain process which isn't available on the predefined list, would be a very nice feature if it's feasable ofcourse, thanks !

Kind regards,

**Comment by UnamSanctam** [comment]
Wouldn't really work that well since you'd need the dynamic location of that file. That program would also need to exist on the computer that it's running on (and would have to be in the location you entered) and it would also have to be a 64-bit program.

**Comment by FireHack7z** [comment]
Download source code and add it manually it's easy.. (1 min work)
