### ISSUE TITLE
gt 1030 

### ISSUE THREAD

**Issue by Zeevsq1** [UnamSanctam/SilentCryptoMiner#472]
what can i mine on gt 1030

**Comment by Zeevsq1** [comment]
and on gtx 1060 3gb video cards that you can mine on them (the classic doesn’t work, not enough memory)

**Comment by UnamSanctam** [comment]
Nothing for the GT 1030 really. You can find DAG sizes for different coins here: https://minerstat.com/dag-size-calculator, none of the <2GB coins are either worth anything or not mineable anymore. On the GTX 1060 3GB you can maybe mine something like EXP.
