### ISSUE TITLE
New update? 

### ISSUE THREAD

**Issue by 1mavricks1** [UnamSanctam/SilentCryptoMiner#474]
Hi, are you planning any new futures or anything? Will you update panel also, it still have problems with sorting and that stuff? Ty

**Comment by 1mavricks1** [comment]
Oh wow, that is great. Is there any ETA or % how much is done?

**Comment by 1mavricks1** [comment]
It will be huge update?

**Comment by UnamSanctam** [comment]
Most of it is done just not the new features that have been requested like a website blocker (using hosts) and such. It's quite a big update yes in terms of code.
