### ISSUE TITLE
startup as local user

### ISSUE THREAD

**Issue by ampf27** [UnamSanctam/SilentCryptoMiner#475]
When I build the miner choosing the installation path on the Temp folder I get installed on the folder AppData\Roaming\Windows the minet too. I dont have any record on the scheduled task (because I'm not running is as admin) neither on the registry neither on AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup.

Is this file on AppData\Roaming\Windows that you refer on your WIKI to be created as startup when we run it without bein admin or should something be on the AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup folder?

**Comment by UnamSanctam** [comment]
If you don't run it as administrator then it will add it into the startup registry at "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run".

**Comment by ampf27** [comment]
but thats not happening. on the registry I have no added key

**Comment by UnamSanctam** [comment]
And you have "Startup" enabled in the builder? You can see the command that adds the registry key here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/e7d01c6c5ba7e9fd88e9cbcadd25c64c02773939/SilentCryptoMiner/Classes/Codedom.cs#L575
Which is run in the miner here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/e7d01c6c5ba7e9fd88e9cbcadd25c64c02773939/SilentCryptoMiner/Resources/Code/Program.cs#L100
So it will be added there, can you screenshot both that registry location and your Task Scheduler?

**Comment by ampf27** [comment]
![REGISTRY](https://user-images.githubusercontent.com/42299613/158472936-b552370d-cec5-44fd-ae3b-f7e8db60337d.PNG)
![scheduled tasks](https://user-images.githubusercontent.com/42299613/158472942-fb9a2561-c855-402a-ad4b-b13d929647a3.PNG)
I don't see that key on the registry and there is nothing on the scheduled tasks

**Comment by UnamSanctam** [comment]
Is the miner shown as running if you run the checker? If you have something like Riot Vanguard then you might have to change the "Windows" folder in the "Filename" to something else since it seems that they might block that folder from being accessed.

**Comment by ampf27** [comment]
I already see it on registry. Every thing seems fine now. Thank you very much
