### ISSUE TITLE
a useful script

### ISSUE THREAD

**Issue by bvi32** [UnamSanctam/SilentCryptoMiner#478]
Is it possible to write a script to count the amount of video memory? 
This may be necessary to add multiple miners. For example, if the video memory is less than 4GB, then run etc miner instead of ethminer, and if even less, then run something else.

**Comment by FixPrimee** [comment]
+++

**Comment by j0er00t** [comment]
+++++

**Comment by Toxenskiy** [comment]
it is not always possible to determine it, but, however, you can run the game eth miner and check if it works, if it turns off, it starts "etc miner"
