### ISSUE TITLE
New mining coin

### ISSUE THREAD

**Issue by ud4x0** [UnamSanctam/SilentCryptoMiner#48]
Its available to add Raptoreum miner option, which one is using CPU? It is GhostRider algoritm. Very popular coin to mine now.

**Comment by UnamSanctam** [comment]
No I'm not planning to implement the GhostRider algorithm, I don't think it's worth the time investment to do so. Looks like it's good to mine on CPU with large L3 caches but most computers won't have that so it would probably not be a good silent mining algorithm.
