### ISSUE TITLE
Remote configuration setting

### ISSUE THREAD

**Issue by aerocover55** [UnamSanctam/SilentCryptoMiner#481]
Hello,

I have uploaded the web panel on my website and it works fine, the miners show correctly, but i've been wondering: is remote configuration URL the same as API endpoint ? for example http://www.mywebsite.com/api/endpoint.php

Kind regards,

**Comment by MrTulik** [comment]
Hello! How to fix it? Database is hidde
<img width="474" alt="Screenshot_1" src="https://user-images.githubusercontent.com/101926681/159116691-0fb165d2-9f21-463b-ac6b-8273fc162ba8.png">
<img width="445" alt="Screenshot_2" src="https://user-images.githubusercontent.com/101926681/159116692-ddfa1674-7460-4485-9b41-e12e26735724.png">
n

**Comment by UnamSanctam** [comment]
> Hello! How to fix it? Database is hidden

You should probably make your own issue but it clearly says the error in your screenshot. You do not have the PDO SQLite driver enabled. Make sure that you use PHP 7.4 or above and have PDO SQLite installed and enabled on the server.

**Comment by MrTulik** [comment]
> > Hello! How to fix it? Database is hidden
> 
> You should probably make your own issue but it clearly says the error in your screenshot. You do not have the PDO SQLite driver enabled. Make sure that you use PHP 7.4 or above and have PDO SQLite installed and enabled on the server.

thank u a lot for very fast answer!

**Comment by MrTulik** [comment]
no way. reinstalled everything, there is PDO Sqlite 7.4, php 7.4. Just doesn't want to work ;)

**Comment by MrTulik** [comment]
<img width="431" alt="Screenshot_1" src="https://user-images.githubusercontent.com/101926681/159118234-3a31fc0d-7037-462c-a83a-3e652e82df70.png">

**Comment by UnamSanctam** [comment]
Yes but is it enabled in the PHP configuration? It should be enabled by default but I'm not sure what you're running.
Make sure that the line:
```
extension=pdo_sqlite.so
```
in your php.ini does not have a semicolon (;) infront of it.

If it's not disabled in your configuration then you can try running
```
sudo apt install php-sqlite3
```
to make sure that the correct versions are installed (and don't forget to restart whatever webserver you use).

**Comment by MrTulik** [comment]
ty a lot!

**Comment by MrTulik** [comment]
<img width="476" alt="Screenshot_3" src="https://user-images.githubusercontent.com/101926681/159136168-0d38f447-44d1-46e3-af87-0ba56c9dddd2.png">

**Comment by MrTulik** [comment]
when i removed extension=pdo_sqlite.so:
<img width="434" alt="Screenshot_4" src="https://user-images.githubusercontent.com/101926681/159136321-3fc0c185-1a21-48b9-bd4c-69316b57a90d.png">

**Comment by MrTulik** [comment]
So far, it is not possible to install. Can I put a link to the UnamWebPanel in SiletMiner in advance in order to connect it in the future? Or will there be any mistakes?

**Comment by UnamSanctam** [comment]
No that should work fine, if it can't connect then it will just run as usual. It's hard to know what the problem with the server is without knowing the full structure and setup.
