### ISSUE TITLE
process kill and stealth list for XMR?

### ISSUE THREAD

**Issue by Azzerzz** [UnamSanctam/SilentCryptoMiner#488]
i found the ETH stealth settings.  but im wondering if theres any list for XMR since it uses CPU

**Comment by UnamSanctam** [comment]
I haven't made one really since it's not usually really necessary. CPU mining is a lot less demanding than GPU mining so usually it doesn't matter much.

**Comment by Azzerzz** [comment]
> I haven't made one really since it's not usually really necessary. CPU mining is a lot less demanding than GPU mining so usually it doesn't matter much.

so i dont really need a stealth list for games?

**Comment by UnamSanctam** [comment]
Not really, Though if you have it set to like 80% Max CPU then maybe adding CSGO, WoW, LoL and similar games could be beneficial. To be honest I've forgotten to kill XMR miners for long times sometimes when testing and I didn't notice any impact on performance at all.
