### ISSUE TITLE
nslookup.exe opens up after a few minutes after running the file with a rootkit

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentCryptoMiner#49]
i was trying to run the file without rootkit for a while, it worked for a split second when the minercheck said it had shares coming through.
i rebuilt the miner because it was not working and tried it with the rootkit, few minutes after system32 nslookup cmd bar appeared, i did not inject it into nslookup i injected it into explorer and it still will not work
got it working with no rootkit enabled after rebooting but im not getting any shares, even though the checker says theres a miner

**Comment by suckma420** [comment]
It's an issue with the rootkit
