### ISSUE TITLE
I have a way to get C# to load C++ bytes directly. I can bypass av by loading xmrig in memory. Can you add this feature?

### ISSUE THREAD

**Issue by nonomoney** [UnamSanctam/SilentCryptoMiner#495]
I have a way to get C# to load C++ bytes directly. I can bypass av by loading xmrig in memory.
Can you add this feature?

**Comment by UnamSanctam** [comment]
The miner already does this (and always has), it uses RunPE unless you're talking about another technique.

**Comment by nonomoney** [comment]
我的办法是加载重编译过的xmrig的dlll 并且不需要管理员权限

**Comment by UnamSanctam** [comment]
Right now it loads xmrig into memory directly using Process Hollowing here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/e7d01c6c5ba7e9fd88e9cbcadd25c64c02773939/SilentCryptoMiner/Resources/Code/Program.cs#L454

I haven't really seen any detections with my miner that relates to xmrig yet, usually it's other things that gets detected.
