### ISSUE TITLE
what are the best pools for Xmr with a low payout rate?

### ISSUE THREAD

**Issue by Azzerzz** [UnamSanctam/SilentCryptoMiner#496]
i tried ones like monroestream and minexmr but they give me like 50 k/hs each
do you recommend any pools that have a payout lower than 10 or 5$?
also im having trouble setting up my configuration
i put the website   https://my-website.000webhostapp.com/api/endpoint.php
in the advanced parameters section but when i run the miner nothing shows up, it worked last time i tried it but now few weeks later it wont

**Comment by FixPrimee** [comment]
2miners :)

**Comment by UnamSanctam** [comment]
You can lower the payout on MoneroOcean but yeah you can try 2miners, I believe the minimum payout you can set is 0.01 XMR which is about $2.

Make sure that the PHP version on the site is PHP 7.4 or above, here's how you change it:
https://www.000webhost.com/forum/t/how-to-change-upgrade-or-downgrade-php-version-of-my-website/39336

**Comment by Azzerzz** [comment]
> 

thx, but the miner still wont show up in the panel even after updating it

**Comment by Azzerzz** [comment]
> You can lower the payout on MoneroOcean but yeah you can try 2miners, I believe the minimum payout you can set is 0.01 XMR which is about $2.
> 
> Make sure that the PHP version on the site is PHP 7.4 or above, here's how you change it: https://www.000webhost.com/forum/t/how-to-change-upgrade-or-downgrade-php-version-of-my-website/39336

miner still wont show up
