### ISSUE TITLE
Question about the stopped miners

### ISSUE THREAD

**Issue by sunqibuhuake** [UnamSanctam/SilentCryptoMiner#498]
I have about 20 percent of the miners in the stopped state...
Will the stopped miners keep trying to reconnect to the pool? If yes, what is the time interval?

**Comment by UnamSanctam** [comment]
If they're "Stopped" then it means that they can't connect to the pool, they will try to reconnect quite often but generally miners should never be in the "Stopped" state. Keep in mind that some pools like Ethermine and a few others I believe has banned all users from countries like Russia from mining to their pool.

**Comment by sunqibuhuake** [comment]
Actually I have 100+ miners, some will stop for 30 minutes to several hours.
I think it should be the problem of the mining pool.
Today I will try another mining pool.

**Comment by UnamSanctam** [comment]
It gets the "Remote Configuration" on startup and then every 100 minutes after that. If it can't reach the "Remote Configuration" then it will just keep mining with the settings it  currently has.
