### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#501]
Will there be a new update? if so when will it be. Also, thank you for your programs.

**Comment by UnamSanctam** [comment]
Yes now I'm just changing the language system a bit, should probably only be the last thing left (except full testing).

**Comment by DogusCyk** [comment]
ah, that's great news. There was also a problem that I thought was caused by me. When I wrote the webpanel in the etc part, the miner was not working, I hope it will be fixed with this update.

**Comment by DogusCyk** [comment]
Only for Etc And Rtm

**Comment by UnamSanctam** [comment]
Can you recreate that and send the save file (from pressing "Save" in the builder) for it so I can test myself as well? I have some saves from others with their own possible bugs but more would help.

**Comment by DogusCyk** [comment]
ah right now i just formatted my computer i didn't install anything i can't upload it now but i can upload it later

**Comment by DogusCyk** [comment]
The problem is that when I selected etc and rtm as miner, when I typed webpanel in etc part, the miner was not working.

**Comment by UnamSanctam** [comment]
Yeah thank you for reporting it, if you're able to recreate it when and if you have any time then I'd appreciate it.

**Comment by DogusCyk** [comment]
I will try when the new update comes

**Comment by DogusCyk** [comment]
I will write if the problem persists, I am waiting for the new update for now

**Comment by DogusCyk** [comment]
ah I hope I wrote it wrong, I'm waiting for the new update, sorry if I messed up
