### ISSUE TITLE
Hosting And Control Panel.

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#503]
Good evening. Immediately I apologize for the English I write through a translator. Hosting has this option - Number of processes (NPROC). The NPROC parameter controls the total number of processes running as a user. Once the limit is reached, no new process can be created (until the other one dies). In this case, you may see 500 or 503 errors on the site. There can be many reasons for exceeding the limit - a large number of running PHP processes, hung cron scripts, simultaneous connection of a large number of email users, ftp users, etc.
Periodically, an 80% figure appears there and I lose access to the panel. I am deleting  unamwebpanel from hosting. And then re-upload the file unamwebpanel.  All miners are restored and then everything works fine for a couple of days. After that there is again a quick spike up to 80% and I lose access to the panel. I want to ask what can cause such sharp spikes up to 80%?

**Comment by UnamSanctam** [comment]
Hmm, well the endpoint that the miners contact is just a simple PHP endpoint (https://github.com/UnamSanctam/UnamWebPanel/blob/master/UnamWebPanel/api/endpoint.php) that finishes in a few milliseconds usually, after which the PHP process closes down (as always). So there isn't really anything which would keep the process open after that. I just tried it on my own web server and the connection (and PHP process) closes down almost instantly, have you tested if that happens on any other host (like maybe a self-hosted one)? 

Also, what is the NPROC parameter set to? And how many miners do you have in the web panel?

**Comment by masterjek** [comment]
Unfortunately, I don't have my own hosting. NPROC - has a value from 0 to 100. Miners - 5438 But of these, only half are active almost always. Value NPROC - even with so many miners, it stays around 4-6. And then it can jump sharply up to 80 and the panel does not open. As I wrote above, I delete unamwebpanel and immediately load the same file back. All 5438 miners are restored, even new ones appear. And value NPROC becomes again 4-6.

**Comment by UnamSanctam** [comment]
In that case it sounds like it's caused by the host, if the host is "lagging" (like maybe opening the database or something is taking long) then the connections/processes when the miners connect would all stay open at the same time while it's loading.

**Comment by masterjek** [comment]
Understood. Thanks for the help.
