### ISSUE TITLE
Web panel not working + 2miners laggy detection

### ISSUE THREAD

**Issue by djmessaoud** [UnamSanctam/SilentCryptoMiner#504]
![image](https://user-images.githubusercontent.com/23726021/160230640-a0b3051f-12e1-4828-b4c5-ba65bf47ec6b.png)

Hello brother, you may see that the miner is working but it is not being detected in the web panel.

Also, it's very laggy with the 2miners pool. 
Getting detected one time in 10 minutes.

Any advices? all is good with configuration.

**Comment by UnamSanctam** [comment]
Check that you have PHP 7.4 or above, also check that you can write to the database. You can check that easily by going to the "Configuration" tab in the web panel and then create a new configuration, if it works and is still there after a refresh then the database is writable.

It's not laggy, that's how mining works, you can read https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining for an explanation on how shares work. It will only show something in the pool whenever you submit a share to it.

**Comment by djmessaoud** [comment]
Thanks for the answer.

PHP version is higher than 7.4 + the db is editable and saveable. 

What could be the issue? 
I'm using infinityfree host btw

**Comment by UnamSanctam** [comment]
And the endpoint.php page returns "Error: Invalid data" if you visit it (what it's supposed to show)? Some hosts could be blocking traffic since it's not done by a browser but instead by a program.

**Comment by djmessaoud** [comment]
I will try another one and update you, thanks for your efforts
