### ISSUE TITLE
I get an error when opening Miner

### ISSUE THREAD

**Issue by YOTYTeaM** [UnamSanctam/SilentCryptoMiner#507]
I get an error when opening Miner:

![image](https://user-images.githubusercontent.com/72147356/160367647-d5701785-6ae6-4db7-b988-e1327a62c486.png)

and another question 
Does Miner support bitcoin?

**Comment by UnamSanctam** [comment]
Looks like it's trying to copy the miner somewhere else while the miner is running, I haven't ever seen that happen though. When exactly does that happen?

No you don't mine Bitcoin with normal computers, no one has for the last few years since it would not be profitable in any way. Bitcoin is mined by specialized ASICs.

**Comment by YOTYTeaM** [comment]
I used vmware.. windows 10

This happened in the first run
It was detected by Microsoft Antivirus but could not close Miner completely
I opened Checker, Watchdog was off and showed a miner (I had watchdog enabled)

**Comment by UnamSanctam** [comment]
Oh, then Windows Defender could be "locking" the file while scanning or removing it which would explain the message. The miner can still get injected before it gets removed.

**Comment by YOTYTeaM** [comment]
Is there a solution?

**Comment by UnamSanctam** [comment]
For the antivirus detection you mean? In your case "Bypass Windows Defender" would help but that only helps if you're able to run it, if it gets removed before that then you can either use a crypter, an obfuscator or both to decrease detections (https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-can-i-decrease-detections).

**Comment by YOTYTeaM** [comment]
I also opened Miner, even though the antivirus was turned off, it still happened like this

**Comment by UnamSanctam** [comment]
Change the "Filename" in the "Startup" tab, the file in the normal install location could still be there "locked".
