### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#509]
I want to use proxy setting in parameter field using proxy=HOST:PORT . But the proxy ips i bought uses password for authentication. So can i use the format proxy=HOST:PORT:PASSWORD or is there any way i can do these? and can i add multiple proxys by separating using comma(,)? Thanks🙏

**Comment by UnamSanctam** [comment]
No XMRig only supports HOST:PORT and only one proxy from what I know https://xmrig.com/docs/miner/command-line-options

**Comment by DerXanRam** [comment]
> No XMRig only supports HOST:PORT and only one proxy from what I know https://xmrig.com/docs/miner/command-line-options

if that isn't possible can i use [this](https://xmrig.com/docs/miner/tor) on your miner? if yes, how? 

thanks

**Comment by UnamSanctam** [comment]
What is described in that link is how to proxy xmrig through the Tor Browser, so yes if the computer has the Tor Browser installed then you can proxy through that with --proxy=127.0.0.1:9150. If you just want to proxy the traffic for some reason then you can always host your own https://github.com/xmrig/xmrig-proxy.

**Comment by DerXanRam** [comment]
ok thanks i will try tor proxy and i will return back for results. And I am little bit confused about xmrig-proxy. what is these and can you give me a little bit clue. Thanks

**Comment by UnamSanctam** [comment]
XMRig-proxy is a proxy you can host (run somwhere) that proxies the traffic from the miners to the pool, you use the xmrig-proxy to control what pool to mine to and such.

**Comment by DerXanRam** [comment]
> What is described in that link is how to proxy xmrig through the Tor Browser, so yes if the computer has the Tor Browser (or any Tor proxy) installed then you can proxy through that with --proxy=127.0.0.1:9150. If you just want to proxy the traffic for some reason then you can always host your own https://github.com/xmrig/xmrig-proxy.

can i install xmrig-proxy on my cpanel(website server)?
