### ISSUE TITLE
Donut application being picked up by antivirus

### ISSUE THREAD

**Issue by GoldenSkyRunner** [UnamSanctam/SilentCryptoMiner#51]
When loading my exe onto a flashdrive and inserting it into a new computer, antivirus picks up on it immediately and won't let it run?

**Comment by UnamSanctam** [comment]
A newly built miner? Since it has been 6 days since release it would be reasonable that it has become detected (like any other program).

**Comment by GoldenSkyRunner** [comment]
Yeah I made it literally yesterday. Is there anything I can do?

**Comment by UnamSanctam** [comment]
Create a new build (until it's undetected), crypt it with a crypter or wait for a new release.

**Comment by j0er00t** [comment]
> Create a new build (until it's undetected), crypt it with a crypter or wait for a new release.

which crypter is good any recommendation???

**Comment by UnamSanctam** [comment]
No I haven't tested any in a few years since I never need one.
