### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by ExdmundZ** [UnamSanctam/SilentCryptoMiner#511]
whats the best way to setup the proxy i have many miners with  low hashrate i would like to merge them as one single worker?

**Comment by UnamSanctam** [comment]
Well having multiple miners mining or proxying them into one usually doesn't make too much of a difference (though it can depend on the pool). But if you want to set up an https://github.com/xmrig/xmrig-proxy then you'd need to either have some sort of VPS to host it on or host it yourself (but maybe behind some sort of VPN to not expose your real IP).

**Comment by ExdmundZ** [comment]
Yeah i have a ubuntu vps is it worth setting up xmrrig proxy? i have 50+ miners connected but none of them give shares our rarely using hashvault pool monero

**Comment by ExdmundZ** [comment]
Ok thank you :)
