### ISSUE TITLE
How to start Mining?

### ISSUE THREAD

**Issue by PandoricGalaxy** [UnamSanctam/SilentCryptoMiner#512]
I am wanting to make a miner using randomX/Monero.
Im using nanopool with SSL/TLS on

What do i have to put in pool,walletaddress/user and password?
Ive read the wiki but still unsure.

What does this mean?
![image](https://user-images.githubusercontent.com/86944806/160649567-049aad5f-57d2-4992-9dae-8af2881c45ef.png)

**Comment by UnamSanctam** [comment]
For the pool address you would just do something like: `xmr-eu1.nanopool.org:14433`

For the wallet address you'd put for example: `8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N.Main/Password123`
In which case it would mine to that wallet address with the worker name "Main" and you'd also be able to change the minimum payment amount by using `Password123`

For nanopool you should leave the password field in the builder empty.

**Comment by PandoricGalaxy** [comment]
can i use it instead to be:
8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N.{COMPUTERNAME}/Password123

**Comment by UnamSanctam** [comment]
Yes exactly, then each miner would have it's own worker. 

You can change the minimum withdrawal amount on your wallets nanopool page by pressing the "Settings" button, there you can enter the password (Password123 in the example I sent) to change what the minimum XMR payment amount should be (for example 0.01 XMR).

**Comment by PandoricGalaxy** [comment]
settings? can you tell me what website (url) you reffering to? cause on nanopool.org there is no account section

**Comment by UnamSanctam** [comment]
In the top right of the nanopool (XMR) site you can enter your wallet address and then press "Search", if will be quite empty at first but after you have mined your first share you will get access to statistics and such.

**Comment by PandoricGalaxy** [comment]
> Here as an example: https://xmr.nanopool.org/account/8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N, there is a button called "Settings" where the minimum withdrawal can be changed.

I cant find it so i replaced the address in the link u gave with mine and it gave this:
![image](https://user-images.githubusercontent.com/86944806/160654191-93047acd-f99a-40be-9bf0-05a8046f1512.png)
I have signed up by going to help.nanopool.org/login

**Comment by UnamSanctam** [comment]
What's just the help desk, you can't sign up to nanopool itself. You only use your wallet address, https://xmr.nanopool.org/account/YourWalletHere

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by PandoricGalaxy** [comment]
> Yes exactly.

oh ok ill do it thanks!
btw approx how much time would it take to mine 1 share?

**Comment by UnamSanctam** [comment]
It depends on your hashrate, nanopool has a fixed difficulty of 400 000 so if you mine at lets say 400 H/s then it would take on average 400 000/400=1000 seconds. Nanopools high fixed difficulty has both upsides and downsides.

**Comment by PandoricGalaxy** [comment]
> It depends on your hashrate, nanopool has a fixed difficulty of 400 000 so if you mine at lets say 400 H/s then it would take on average 400 000/400=1000 seconds. Nanopools high fixed difficulty has both upsides and downsides.

![image](https://user-images.githubusercontent.com/86944806/160794879-e5081c9c-a58b-4b45-a8fb-dbd850bd3309.png)
Idk the password what to do?

**Comment by PandoricGalaxy** [comment]
The min payout is high for me so should i use minexmr.com?  If yes then how on it?

**Comment by UnamSanctam** [comment]
If you used what I sent before then the password would be `Password123`, but you can use another pool if you want a lower minimum payout, but never use MineXMR. You can try MoneroOcean or maybe 2miners.

**Comment by PandoricGalaxy** [comment]
Moneroocean gives apu error

**Comment by UnamSanctam** [comment]
You should always check the documentation for each pool to see how to connect. For MoneroOcean you should only have the wallet address inside the "Wallet Address/User" field and then put the worker name inside the "Password" field.

**Comment by PandoricGalaxy** [comment]
> You should always check the documentation for each pool to see how to connect if you haven't already. For MoneroOcean you should only have the wallet address inside the "Wallet Address/User" field and then put the worker name inside the "Password" field.

Do i use old.moneroocean.stream?
cause moneroocean.stream sas api error

**Comment by UnamSanctam** [comment]
Where does it say API error? On the website?

You should put {COMPUTERNAME} in the "Password" field when using MoneroOcean.

**Comment by UnamSanctam** [comment]
It's something with your connection, try it in incognito mode. Otherwise I guess your IP could be blocked or something as well (though probably not).
