### ISSUE TITLE
About the remote configuration

### ISSUE THREAD

**Issue by ExdmundZ** [UnamSanctam/SilentCryptoMiner#516]
How and what should i do to set it up? How does it work?

**Comment by UnamSanctam** [comment]
You can find the formatting and such on the wiki:
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration
It allows you to dynamically change the options by editing the pastebin/rentry or whatever you choose to use.
