### ISSUE TITLE
problem with remote config  and pausing the miner 

### ISSUE THREAD

**Issue by elraiqq** [UnamSanctam/SilentCryptoMiner#517]
hello bro 
I really need help with this
I need some way to pause and run the miner please any update or advice from you
I tried to activate remote config and then add "explorer.exe" to stealth target
But unfortunately, didn't work with me on pastebin does not affect the miner
I think I didn't set the remote config well
Since any modifications to the pastbin do not work
Take a look and correct me 

https://pastebin.com/raw/PNQWnqZJ

**Comment by elraiqq** [comment]
did not work
Is this an effective way to stop and start or is there a better way?

**Comment by elraiqq** [comment]
did not work
Is this an effective way to stop and start or is there a better way?

**Comment by UnamSanctam** [comment]
Well it's the easiest way, though the web panel configuration is the most effective (but you need to host that compared to the "Remote Configuration"). You configuration is correct now but keep in mind that the miner checks the "Remote Configuration" on every start and then every 100 minutes to reduce spam (because otherwise they'd remove your paste).

**Comment by elraiqq** [comment]
I don't think I can use the web panel
But now I created a new miner like this to make sure
It shouldn't work and it should work now
![11](https://user-images.githubusercontent.com/86991260/160927039-cefc1fc6-a292-4d52-a6cc-dc3ec675e310.PNG)
![22](https://user-images.githubusercontent.com/86991260/160927048-1203fef6-f976-4f1d-bd2b-6a08f9f276ba.PNG)

**Comment by UnamSanctam** [comment]
With those settings it should pause it forever.

**Comment by elraiqq** [comment]
Did not paused 
i am looking to gpu memory usage and heat

**Comment by UnamSanctam** [comment]
And if you kill the miner the GPU memory usage goes down greatly?

**Comment by elraiqq** [comment]
yes sure

**Comment by elraiqq** [comment]
i testing this now on laptop Could this be the reason?

**Comment by UnamSanctam** [comment]
Does the laptop have a good enough GPU to mine Ethereum in the first place (since otherwise it won't and can't even begin mining)? Ethereum requires at least 4.8GB of VRAM.

**Comment by elraiqq** [comment]
yes its enough 
1660 ti 6 gb

**Comment by UnamSanctam** [comment]
How much VRAM is being used before the miner is started and how much VRAM is being used after the miner is started?

**Comment by elraiqq** [comment]
this is after miner is started 
![tskmngr](https://user-images.githubusercontent.com/86991260/160930765-2cb75bb2-0c14-45f7-83a9-e5f8a0a9752a.PNG)

**Comment by elraiqq** [comment]
this is first build i make setting stealth only is pastbin

**Comment by UnamSanctam** [comment]
Can you show a screenshot of the VRAM after you've killed the miner?

**Comment by UnamSanctam** [comment]
Ok, can you now start the miner, then run the checker and screenshot that?

**Comment by elraiqq** [comment]
![checker](https://user-images.githubusercontent.com/86991260/160931847-8ad1ca80-3e50-480c-95b2-1675d134e979.PNG)

**Comment by UnamSanctam** [comment]
I think it should be `--report-hr`

**Comment by elraiqq** [comment]
I have already been using this for a while as I read it from the wiki
But also I changed the address in the pastbin and it did not change in the checker

**Comment by UnamSanctam** [comment]
I don't think I say anywhere in the wiki about --report-hashrate (or --report-hr). The checker checks the command line arguments, so they won't of course change if anything changes inside the program (such as the "Remote Configuration"). Try changing it to `--report-hr` instead and see what happens.

**Comment by elraiqq** [comment]
i am sorry that was in issue ticket i open and you tell me 
https://github.com/UnamSanctam/SilentETHMiner/issues/127 
but I will try it now and change it

**Comment by UnamSanctam** [comment]
Ah ok, --report-hashrate could be correct but it's not listed where I checked. Can you save your configuration and send it here?

**Comment by elraiqq** [comment]
Should I turn off the stealth ?
or open it
and Should explorer.exe be added to the stealth target?

**Comment by UnamSanctam** [comment]
Either try it with the pastebin only, or disable the pastebin and try only with the builder options. So you can know which one is affecting it.

**Comment by elraiqq** [comment]
i disabled remote config 
miner running but not working
gpu ram usage is 0 
but  laptop ram is used by miner and  every thing is lag As if the miner is trying to work

**Comment by UnamSanctam** [comment]
It could be your CPU doing that, if you have an integrated GPU in the CPU then your CPU can use RAM as the VRAM. Integrated GPUs are perfectly valid GPUs though not very strong ones.

**Comment by elraiqq** [comment]
I'll try tomorrow on PC to make sure more
But what is the best way to make sure that the pastbin actually works?

**Comment by UnamSanctam** [comment]
Easiest would probably be to add maybe `"kill-targets": "notepad.exe"` and see if notepad gets closed down when you open it.

**Comment by elraiqq** [comment]
ok I'll try and tell you 
thank u very much

**Comment by elraiqq** [comment]
ok now any  change applied in the miner only in start 
when i start the miner Works with settings in pastebin
But when i change the settings in pastebin when the miner working
no changes happened  I waited more than 2 hours (120 minutes)
I have to kill the miner and start it again

**Comment by UnamSanctam** [comment]
How did you try it? Best method is to start the miner without `"kill-targets": "notepad.exe"` and then after the miner has started you add `"kill-targets": "notepad.exe"` into the pastebin, after 100 minutes has passed it should read the pastebin again and start killing notepad.

**Comment by elraiqq** [comment]
but when i kill miner and restart it working normally that mean miner read pastbin setting

**Comment by elraiqq** [comment]
but not automatically when miner is running i have to kill miner and start it again to read pastbin setting

**Comment by UnamSanctam** [comment]
Yes that should work (and does work), try it with the method I gave, it's easier to see if it works by doing that since you'll see that it starts killing notepad.exe after 100 minutes.

**Comment by elraiqq** [comment]
should i build new miner with this setting or just make it in pastbin

**Comment by UnamSanctam** [comment]
You can do it in the pastebin you already have, just add `"kill-targets": "notepad.exe"` into it **after** you have already started the miner. Then after 100 minutes the miner should start killing notepad if you have it open.

**Comment by UnamSanctam** [comment]
You also need a comma (,) after the "stealth-targets" line since you added a new key-value after it.

**Comment by elraiqq** [comment]
It took me a lot of time to check because I had to wait two hours or more
More than once 
And now everything is working fine
thanks a lot to you
But if you find a way to add a pause  that works faster, it will definitely be better
But of course your work is great, thank you and sorry for the inconvenience

**Comment by UnamSanctam** [comment]
Great job getting it to work.

**Comment by elraiqq** [comment]
Unfortunately I think it only worked a few times
It is not working automatically now again I have to kill the miner and restart it like before
I think there is nothing wrong with the settings

Really sorry to bother you🙏

**Comment by UnamSanctam** [comment]
What are you trying to do?

**Comment by elraiqq** [comment]
"kill-targets": "notepad.exe"

"stealth-targets": "explorer.exe",

I'm  trying the two, one at a time

**Comment by elraiqq** [comment]
https://pastebin.com/raw/PNQWnqZJ

https://pastebin.com/raw/wVD5GqTP

**Comment by UnamSanctam** [comment]
And you wait 100 minutes when testing?

**Comment by elraiqq** [comment]
Yes, of course, and more than that

**Comment by UnamSanctam** [comment]
And it doesn't kill notepad (or kills) whatever it shouldn't do after waiting the 100 minutes?

**Comment by elraiqq** [comment]
It only happened twice and then it didn't happen again in 5 attempts

**Comment by UnamSanctam** [comment]
Hmm, it's hard to know, you can set up a local web panel https://github.com/UnamSanctam/UnamWebPanel and connect the miner to that, it would then show in the panel if the miner is paused or not.

**Comment by elraiqq** [comment]
I already tried using the webpanel but I don't have any experience or knowledge

**Comment by elraiqq** [comment]
![Capture](https://user-images.githubusercontent.com/86991260/161376626-f51d2aee-cb2a-4658-9bff-4a246f8f4223.PNG)

**Comment by elraiqq** [comment]
Finally I set up the webpanel
 but almost the same problem when i put explorer.exe like this

![dssdsd](https://user-images.githubusercontent.com/86991260/165881637-9880caf8-c111-4a39-b0ba-e404b8b4ef4c.PNG)
 
its paused in webpanel but in pc It does not stop completely
It keeps stopping and running every minute like this

![Capture](https://user-images.githubusercontent.com/86991260/165881808-1307c9b3-4cbf-4321-bd6d-61431cbecd98.PNG)

**Comment by elraiqq** [comment]
Remote config is not working As I wrote in this issue above 
Believe me, I tried all the settings and built many miners with different settings, they all have the same problem
I just need the ability to stop the miner and run it from anywhere webpanel or remote config
Unfortunately it does not work
Is there any other way besides adding explorer.exe inside stealth

**Comment by UnamSanctam** [comment]
"Remote Configuration" is working, I've checked with multiple large-scale miners since the issue was opened, but you can also set the "Max GPU"/"Max CPU" (and "Idle GPU/CPU") to 0 to make it stop. If I added an option just for that then that's exactly what it would do, so there wouldn't be much difference.

**Comment by elraiqq** [comment]
Yes remote config working but only when i start miner like before 
Now i this problem in webpanel is that is normal ? 
I found a way, but it's not practical enough
By adding explorer.exe and then modifying the settings for the miner itself from here

It works fully But I have to adjust it for all the miners one by one
If in the next update you can add a way to select all and choose the Configuration because it is difficult to do this method for more than 100

**Comment by elraiqq** [comment]
Yes remote config working but only when i start miner like before
Now i this problem in webpanel is that is normal ?
I found a way, but it's not practical enough
By adding explorer.exe and then modifying the settings for the miner itself from here
![20220429_205238.jpg](https://user-images.githubusercontent.com/86991260/165998218-5e9913d9-058b-4c3c-99d8-80ea396f1140.jpg)
It works fully But I have to adjust it for all the miners one by one
If in the next update you can add a way to select all and choose the Configuration because it is difficult to do this method for more than 100

**Comment by UnamSanctam** [comment]
Well adding selection for multiple things would be quite difficult to make but if you just want to pause all of them then just use the "Default xmrig" or the "Default ethminer" configuration.

**Comment by elraiqq** [comment]
Yes i do this i added explorer in default etherminer config and then change it to none  from miners Without making any modifications to it
It works I don't know how but it works

**Comment by UnamSanctam** [comment]
"None" means that it won't use any "Configuration", so then it will only use the last web panel settings (before you changed to "None") after that, until the next "Remote Configuration" when it will use that.

**Comment by elraiqq** [comment]
I dont use remote config just use webpanel

**Comment by UnamSanctam** [comment]
Yes then that will technically work, you can also just remove the JSON array from your "Default ethminer"/"Default xmrig" and it would do the same.

**Comment by elraiqq** [comment]
I am not sure if you understand me well because of my poor language
But when I add explorer.exe in the settings of the webpanel, it does not stop completely and is like this
![165881808-1307c9b3-4cbf-4321-bd6d-61431cbecd98.png](https://user-images.githubusercontent.com/86991260/166007703-317639cd-aada-4d11-af84-d097a5d47576.png)
Until i chose just none for each miner to stop completely 
So if I use this method I need to select all so that I can change to none quickly
Also, in the update, it will be good to specify that the boxes are shown and hidden on the miners' page

**Comment by UnamSanctam** [comment]
Yes, it does stop completely but it seems like in your instance the pool connection gets recreated on each call to the API when it gets the configuration. That's what is causing your VRAM spikes because it's recreating the DAG when it recreates the pool connection. What happens when you choose "None" is that it stops recreating the pool connection on each call since there's no settings to apply, the same thing would happen if you added the JSON into "Default ethminer", waited for it to apply and then removed the JSON from "Default ethminer".

In the next version I'm releasing today or tomorrow it's going to work a bit differently, then it won't recreate any connections unless it needs to (though it does also usually do that in the current version with some exceptions).

**Comment by elraiqq** [comment]
That's great 
But will it work with the current one or create a new miner?

**Comment by UnamSanctam** [comment]
It's a new miner update, it doesn't happen due to the web panel.

**Comment by elraiqq** [comment]
Aha I get it I was thinking a web update

**Comment by UnamSanctam** [comment]
Yeah I should've specified, though there will also be a web update since a few new things are added into the miner such as an "Active Window" that shows the currently active window title (in the web panel).

**Comment by elraiqq** [comment]
thanks a lot pausing is working good now in webpanel 
And I was wondering if it is possible to use remote config with the webpanel as a backup without conflict

**Comment by UnamSanctam** [comment]
Hmm, there haven't been any changes to `--report-hashrate` so it should be working fine, make sure that you enter it correctly.

Doesn't the Game Center management software "reset" the computer on each startup or something? If so then that's not a problem with the miner.

Yes you can use the "Remote Configuration" with the web panel as a backup just fine.

**Comment by elraiqq** [comment]
I was using a very old miner and --report-hashrate was working with me I don't know about the latest updates
Now is that right
![rebort](https://user-images.githubusercontent.com/86991260/166447257-6e08592b-e12b-428e-aeb3-e0f5f14bc85d.PNG)
?

**Comment by elraiqq** [comment]
and management software I think I know the problem
It prevents any program from running at or after booting It also blocks the startup
It's not a big problem, but I wanted to let you know
program name smartlaunch
thanks a lot for you boss

**Comment by UnamSanctam** [comment]
> I was using a very old miner and --report-hashrate was working with me I don't know about the latest updates Now is that right ![rebort](https://user-images.githubusercontent.com/86991260/166447257-6e08592b-e12b-428e-aeb3-e0f5f14bc85d.PNG) ?

Yes any of these `-R,--report-hashrate,--report-hr` should work, maybe there's been some change in some library or something, I'll see if I can reproduce it (I don't use it normally since it can be quite decieving).
