### ISSUE TITLE
Random worker name

### ISSUE THREAD

**Issue by ud4x0** [UnamSanctam/SilentCryptoMiner#519]
IF there is any way to past wallet address with random worker name, every time another name when i will turn on miner first time ??

**Comment by UnamSanctam** [comment]
Sure, though getting a random one on each start can be annoying. But you should be able to use {RANDOM} as the worker name to randomize it.

**Comment by ud4x0** [comment]
If there is any global variables to set yet, like computer name? not including {RANDOM}

**Comment by ud4x0** [comment]
{COMPUTERNAME}, i guess but some global variables did you implement yet?

**Comment by UnamSanctam** [comment]
There is {COMPUTERNAME}, {USERNAME} and {RANDOM} at the moment, there aren't really any others that would be good to use.

**Comment by hidden-69** [comment]
How is {RANDOM} generated and when is it generated, once for each user/system or after each reboot?

**Comment by UnamSanctam** [comment]
On each start of the miner, it's supposed to be temporary so that with {RANDOM} each session has its own worker name.

**Comment by hidden-69** [comment]
Any way to do {COMPUTERNAME} but encrypt it with a private key? Or RANDOM but persistent per computer. I would like to keep status of my workers but not have the computernames public available.

**Comment by UnamSanctam** [comment]
No there's currently no way to do that in the current version but computer names are just randomly generated anyways so it's not like them being public really matters.

**Comment by hidden-69** [comment]
That's not the case for corporate devices or for servers.

**Comment by UnamSanctam** [comment]
Sure but does it really matter? It's not like those corporate devices and servers use completely unique computer names, and it's not like anyone is going to be looking at your worker names (probably). And even then {RANDOM} would work just fine in those situations, especially if combined with the web panel (since you can see the worker names there as well).

**Comment by hidden-69** [comment]
It would be a good insight if I would know if 30% of my workers would go offline and not have done a reboot. So RANDOM is just not good enough and COMPUTERNAME I prefer not to use. Some sort of hash would be best.
