### ISSUE TITLE
I can't mine on other people's PC

### ISSUE THREAD

**Issue by gresmax** [UnamSanctam/SilentCryptoMiner#52]
When i run the miner on my pc everything works. But when i run it on my friend's pc the pool doesn't see it. Miners work via checker on both PCs. What could be the problem?

**Comment by UnamSanctam** [comment]
You need to mine and submit a share to the pool before it will appear. Depending on the algorithm, the pools share difficulty, the hashrate and luck it can take anywhere between 1-30 minutes to find a share. That's how pools work, sometimes the pools are also slow to update with some updating with 10-30 minute intervals.

**Comment by gresmax** [comment]
Pool can't see even an hour later. I tried it on 3 pc but it was unsuccessful.

**Comment by UnamSanctam** [comment]
Can you post what the checker returns?

**Comment by gresmax** [comment]
https://user-images.githubusercontent.com/64851092/141998110-8886ecc2-d3ba-43b5-8b52-f701fc350fc8.png

**Comment by UnamSanctam** [comment]
Those settings are correct so if they aren't mining then there are 3 main possible reasons: 1) They have a "Stealth Targets" program open. 2) Their GPU is too bad to mine ETC or they are using their GPU for something else. 3) Their drivers are too old.

**Comment by UnamSanctam** [comment]
As long as the miner is running but not using any GPU those are really the only things it can be, unless their IPs are banned from the pool but I doubt it. https://github.com/UnamSanctam/SilentCryptoMiner/wiki#what-gpu-requirements-are-there-for-the-gpu-miners-to-work

**Comment by gresmax** [comment]
SilentCryptoMiner works with XMR, but not for any pools with ETC.

**Comment by UnamSanctam** [comment]
It works fine, I have someone on Discord with 1300 ETC/ETH miners so far and he can see that everything works on the web panel. I would recommend you to try the web panel to fully see what is happening on each miner.

**Comment by gresmax** [comment]
Сan you give me a link? I'm a beginner and don't really understand what you mean.

**Comment by UnamSanctam** [comment]
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#api-endpoint-url

**Comment by gresmax** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/64851092/142489268-e0771bc1-1223-42f2-be80-872a18fbaf12.png)
._. GPU - 0%

**Comment by UnamSanctam** [comment]
Have you checked their GPU (by pressing the '+')?

**Comment by gresmax** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/64851092/142489591-c91566ab-8692-49f1-855a-6b6b4d0d4cf7.png)

**Comment by UnamSanctam** [comment]
When it shows 0H/s then 99% of the time it's because too much GPU memory is already being used (so the miner can't use it).

**Comment by gresmax** [comment]
If I put the minimum gpu in the miner 50% and not 80%, then this can help?
It's strange, after all, when I run something to the miner, it is indifferent to it.

**Comment by UnamSanctam** [comment]
No the miner has to use whatever DAG size the coin has: https://minerstat.com/dag-size-calculator. That's how the algorithms work and no less VRAM than the DAG size can be used.  So for ETC if the GPU has less than 2.8GB of VRAM free then it cannot mine.

**Comment by gresmax** [comment]
It's too weird. A friend had 20% of the GPU loaded from 6 GB, but the miner did not work hard.

**Comment by gresmax** [comment]
Of course I will try to find people with other GPUs, but this is certainly not very cool.

**Comment by UnamSanctam** [comment]
Well that's how all nearly all GPU coins work. Usually people check the VRAM used wrongly, I haven't seen any confirmations of it not working when there is enough VRAM since the first release (of the ETH miner, about 8 months ago), usually people check it incorrectly.
