### ISSUE TITLE
Uninstaller?

### ISSUE THREAD

**Issue by KindaDumb4** [UnamSanctam/SilentCryptoMiner#521]
This is running on my machine and I have no clue how to stop it.
I have tried running the uninstaller 5+ times and multiple restarts and nothing has happened.
Please help.

**Comment by UnamSanctam** [comment]
If you run the uninstaller then it removes everything, you can also then try to find it in the Task Manager and kill it (by default it's injected into explorer.exe), you can also follow the manual guide: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner

**Comment by KindaDumb4** [comment]
thx
