### ISSUE TITLE
Which is the prior to give a new configuration for the miner????

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#522]
I have many miners and, when I build them, I entered both "Remote Configuration URL" and "API Endpoint URL".  So if I input different configuration on my "pastebin" and on my  "website", which configuration does the miner gives priority? or does it just keeps run using the defaults that are entered at the time of building?

Thanks :)

**Comment by UnamSanctam** [comment]
Highest priority: Web panel
Medium priority: Remote Configuration
Lowest priority: Builder settings

**Comment by DerXanRam** [comment]
Thanks very much. One more question.... If I remove the miner on my web panel does that mean it will also removes from the computer?

**Comment by UnamSanctam** [comment]
No it just removes it from the web panel list (mostly used to remove old miner), there's no uninstallation code inside the miner itself so you'd have to run the uninstallation program to remove it from the computer.

**Comment by DerXanRam** [comment]
Ok thanks very much.
