### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by TheIlyaSteep** [UnamSanctam/SilentCryptoMiner#525]
What to do with such an error?
![N3prmoqzIxs](https://user-images.githubusercontent.com/42769532/161318604-7d10d2a6-0653-4816-8532-ed1663690092.jpg)

**Comment by UnamSanctam** [comment]
Some file it's trying to read is missing, are you using "Pause for Obfuscation"?

**Comment by TheIlyaSteep** [comment]
yes

**Comment by UnamSanctam** [comment]
Make sure that you don't rename things from the original filenames.

**Comment by TheIlyaSteep** [comment]
Which ones?

**Comment by UnamSanctam** [comment]
The files generated during "Pause for Obfuscation".

**Comment by TheIlyaSteep** [comment]
Thank you everything worked
