### ISSUE TITLE
Connect to controlpanel over proxy

### ISSUE THREAD

**Issue by nexon33** [UnamSanctam/SilentCryptoMiner#526]
I want to configure this to connect to the controlpanel over a proxy (socks5, but can easily be converted to http).

I've taken a short look at the files but I can't seem to find where I can configure this. I want the connection to the panel over the proxy and the connection to the pools over clearnet (or not if thats not easily configurable).

**Comment by UnamSanctam** [comment]
There's currently no way to set a proxy for the cpp-httplib traffic (which the web panel traffic is), don't think the library has support for it either.
