### ISSUE TITLE
made a miner with etc, minercheck says its working, but no worker but i have shares

### ISSUE THREAD

**Issue by Azzerzz** [UnamSanctam/SilentCryptoMiner#53]
i made a etc miner and tried using it, and minercheck says its working, but the worker is not on nanopool but i have 2 shares https://etc.nanopool.org/account/0xec6842175d655091d4298bfcf3a0aa26e969271d
miner is also using all my gpu and memory so id assume it would be mining
also if i enable rootkit should i disable watchdog because is saw you saying it will open the watchdogs repeatedly

**Comment by UnamSanctam** [comment]
Did you enter a worker name? Worker names are purely optional. It's mining (as you can see from the shares) but just no worker name is shown. If you have entered a worker name but it isn't showing up then ETC nanopool does have a few bugs so I would try something like ethermine to see.

>also if i enable rootkit should i disable watchdog because is saw you saying it will open the watchdogs repeatedly

Yes on some computers the watchdog seems to be unable to find the miners (since they are hidden by the rootkit) and thus starts them up over and over again. I would personally not use the rootkit except for testing since that's what it is currently implemented for (hence the red text just like DEBUG has).

**Comment by Azzerzz** [comment]
> 
> 
> Did you enter a worker name? Worker names are purely optional and won't show any if none is entered. It's mining (as you can see from the shares) but just no worker name is shown. If you have entered a worker name but it isn't showing up then ETC nanopool does have a few bugs so I would try something like ethermine to see.
> 
> > also if i enable rootkit should i disable watchdog because is saw you saying it will open the watchdogs repeatedly
> 
> Yes on some computers the watchdog seems to be unable to find the miners (since they are hidden by the rootkit) and thus starts them up over and over again. I would personally not use the rootkit except for testing since that's what it is currently implemented for (hence the red text just like DEBUG has).

i put myaddress.{COMPUTERNAME}/mypassword  in the worker name field
would the miner still work if watchdog was disabled? or would a simple reboot or delete of the file remove the miner alltogether

**Comment by UnamSanctam** [comment]
In the worker name field? If you put myaddress.{COMPUTERNAME}/mypassword then try and put it in the "Wallet Address" field instead (and leave the "Worker Name" field empty) and test that. 

>would the miner still work if watchdog was disabled? or would a simple reboot or delete of the file remove the miner alltogether

The miner works fine without the watchdog (hence why you can disable it) but without the watchdog it won't place back the miner if removed or started if killed (since there is nothing to watch over the miners then) https://github.com/UnamSanctam/SilentCryptoMiner/wiki#watchdog.

**Comment by Azzerzz** [comment]
> 
> 
> In the worker name field? If you put myaddress.{COMPUTERNAME}/mypassword then try and put it in the "Wallet Address" field instead (and leave the "Worker Name" field empty) and test that.
> 
> > would the miner still work if watchdog was disabled? or would a simple reboot or delete of the file remove the miner alltogether
> 
> The miner works fine without the watchdog (hence why you can disable it) but without the watchdog it won't place back the miner if removed or started if killed (since there is nothing to watch over the miners then) https://github.com/UnamSanctam/SilentCryptoMiner/wiki#watchdog.

sorry i mistook address field for the worker name field
i put myaddress.{COMPUTERNAME}/mypassword   in the address field.  i checked with minercheck and it said it was mining, i looked at nanopool and there was only 2 shares and no workers, even though the miner was full blast i did not get any more shares

**Comment by UnamSanctam** [comment]
Yes if it's using GPU then it's working without issue. Mining shares can take a while depending on the hashrate, share difficulty and luck, for nanopool the share difficulty is 10GH (10 000MH) so if you have a 10MH/s hashrate then the average time to find a share would be 10 000/10=1000 seconds. 

For the worker name issue there are a few bugs with the nanopool ETC pool so I would recommend trying another pool like ethermine or something similar and it should appear (only put the wallet address in the "Wallet Address" field and the worker name in the "Worker Name" field for ethermine).

**Comment by Azzerzz** [comment]
> 
> 
> Yes if it's using GPU then it's working without issue. Mining shares can take a while depending on the hashrate, pool share difficulty and luck, for nanopool the share difficulty is 10GH (10 000MH) so if you have a 10MH/s hashrate then the average time to find a share would be 10 000/10=1000 seconds.
> 
> For the worker name issue there are a few bugs with the nanopool ETC pool so I would recommend trying another pool like ethermine or something similar and it should appear (only put the wallet address in the "Wallet Address" field and the worker name in the "Worker Name" field for ethermine).

do i have to put {computername} in the worker name or can i just put whatever

**Comment by UnamSanctam** [comment]
Yes if you want it to use the computer name as the worker name then put `{COMPUTERNAME}`

**Comment by Azzerzz** [comment]
> 
> 
> Yes if you want it to use the computer name as the worker name then put `{COMPUTERNAME}`

the miner is now not using GPU  it was working fine when i first made it

**Comment by UnamSanctam** [comment]
Can you send a screenshot of the checker?

**Comment by Azzerzz** [comment]
> 
> 
> Can you send a screenshot of the checker?

Watchdog Running: Yes
Miners:
--cinit-algo=etchash --pool=stratum://`0xeC6842175D655091D4298BFcf3a0aA26E969271d`.{COMPUTERNAME}@etc-us-us1-etc.ethermine.org:14444  --cinit-max-gpu=40 --cinit-idle-wait=5 --cinit-idle-gpu=60
GPUs:
 Intel(R) UHD Graphics 630
 NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Compatible GPU found: True

**Comment by UnamSanctam** [comment]
You pool URL is wrong, you have one `us` too much.

**Comment by Azzerzz** [comment]
> 
> 
> Your pool URL is wrong, you have one `us` too much.

my bad i double clicked and thought it highlighted the whole line of text
but now it keep fluctuating between 100% and 0%  it will fluctuate to 100% for a few minutes then to 0% for few minutes
--cinit-algo=etchash --pool=stratum://`0xeC6842175D655091D4298BFcf3a0aA26E969271d`.{COMPUTERNAME}@us1-etc.ethermine.org:14444  --cinit-max-gpu=40 --cinit-idle-wait=5 --cinit-idle-gpu=100   still no shares

**Comment by UnamSanctam** [comment]
Yes that's how you use 40% on a GPU is to use 100% then sleep for 40% of the time (of lets say 100ms), so you mine for 100% for 40ms and then you use 0% for 60ms thus averaging 40%.

**Comment by Azzerzz** [comment]
thanks

**Comment by JayCrax** [comment]
> thanks

https://github.com/gupr0x4/HWID-Spoofer-for-Fortnite-and-Valorant/issues/2#issuecomment-979677311

And apparently, I'm the "fucking ape". You are literally leeching off open-source malware and then re-uploading the compiled versions to Github LOL

Touch some grass or get a 9-5. Who knows, you might even get a girlfriend.... or boyfriend?
