### ISSUE TITLE
Task Manager

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#530]
Good afternoon. After 2 reboots of the computer, the following line appears in the task scheduler on the way to the miner - system32\config\systemprofile. The scheduler, accordingly, cannot complete the task and writes a file was not found at the specified path. Accordingly, the miner does not start.

**Comment by UnamSanctam** [comment]
Hmm, it can do that but it should still work fine, it should be copying it to that location as well.

**Comment by masterjek** [comment]
Thanks for the answer. Understood the problem.
