### ISSUE TITLE
How does "DEBUG" work?

### ISSUE THREAD

**Issue by zozidalom** [UnamSanctam/SilentCryptoMiner#531]

**Comment by UnamSanctam** [comment]
It causes the miner to display a message box if there's an error.

**Comment by zozidalom** [comment]
Thx any way to show the console windows or logs of the miners?

**Comment by UnamSanctam** [comment]
No they're compiled without any of that.

**Comment by zozidalom** [comment]
I am also facing this issue here: https://github.com/UnamSanctam/SilentCryptoMiner/issues/532
And not sure how to debug it.
