### ISSUE TITLE
unMineable

### ISSUE THREAD

**Issue by alix1011** [UnamSanctam/SilentCryptoMiner#533]
Hello my friend, in the pool that unMineable how to configure the miner, for example TRX

****TRX**:YourAddress.YourWorkerName**

How to add the first coin of the address or add it to ... in the miner

https://support.unmineable.com/how-to-setup-xmrig-for-cpu-mining

**Comment by UnamSanctam** [comment]
What unmineable does is exchange whatever you mine into what you want (for example TRX). So if you want to mine RandomX (Monero) and swap that for TRX then enter rx.unmineable.com:3333 as the pool, then enter `TRX:YourAddress.YourWorkerName` as the wallet. You will then mine XMR and get payed in TRX.

**Comment by alix1011** [comment]
My friend, for unmineable configuration I have to add the currency name, in which part of the miner should I add the name at the beginning of the wallet or password

**Comment by alix1011** [comment]
TRX 

Where to add?

**Comment by UnamSanctam** [comment]
You add it all into the "Wallet Address/User" field, like `TRX:YourTRXWallet.YourWorkerName` just replace YourTRXWallet with your wallet address and YourWorkerName with the worker name you want.
