### ISSUE TITLE
Workers

### ISSUE THREAD

**Issue by TheIlyaSteep** [UnamSanctam/SilentCryptoMiner#536]
Hello, can you tell me which pools, besides https://etc.ethermine.org this, show workers?

**Comment by DogusCyk** [comment]
{WORKERNAME}

**Comment by DogusCyk** [comment]
{COMPUTERNAME}

**Comment by DogusCyk** [comment]
ah it was one of the two but i forgot

**Comment by TheIlyaSteep** [comment]
No, I was talking about websites. What other sites are there?

**Comment by UnamSanctam** [comment]
The majority of pool supports workers.
