### ISSUE TITLE
Entry Name ?

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#537]
hey what exactly is the initial entry name

**Comment by UnamSanctam** [comment]
It's the entry name that will be shown in the registry or Task Scheduler, if you open the Task Scheduler then it's the first field to the left of a task.

**Comment by DogusCyk** [comment]
ah, whatever I write there will appear in the task scheduler, right?

**Comment by DogusCyk** [comment]
I'll also see if the problem is fixed now.

**Comment by UnamSanctam** [comment]
> ah, whatever I write there will appear in the task scheduler, right?

Yes exactly, it's the actual name of the task so that any user who reads it can know what it is.

**Comment by DogusCyk** [comment]
I wrote the panel to both miners and it worked fine, thank you for solving the problem

**Comment by UnamSanctam** [comment]
Ah, great that it worked.

**Comment by DogusCyk** [comment]
but when i boot the rootkit the problem is still the same
