### ISSUE TITLE
How to start it

### ISSUE THREAD

**Issue by blend47** [UnamSanctam/SilentCryptoMiner#54]
Bro any tip how to start this program,i have no idea

**Comment by UnamSanctam** [comment]
Download the builder: https://github.com/UnamSanctam/SilentCryptoMiner/releases (or compile it yourself).

**Comment by blend47** [comment]
![image](https://user-images.githubusercontent.com/80127355/141861537-6feb171f-9f57-42f8-8bae-39f490e2e379.png)

Is this right till there,if so what do i do now ?

**Comment by blend47** [comment]
![image](https://user-images.githubusercontent.com/80127355/141861626-70dbe5af-0889-48a4-b3bb-06cd336ef6d2.png)
is this right till there,if so what to do now ?

**Comment by UnamSanctam** [comment]
You can download the precompiled builder on the page I linked called `Silent_Crypto_Miner_Builder.zip`

**Comment by blend47** [comment]
I already downloaded it as a zip and it sent me there

**Comment by UnamSanctam** [comment]
You downloaded the source code and not the precompiled builder.

**Comment by UnamSanctam** [comment]
Depends on what you mean by virus check.

**Comment by blend47** [comment]
![image](https://user-images.githubusercontent.com/80127355/142073087-359437ce-d9e7-476d-a34e-c432d1f724b5.png)

**Comment by UnamSanctam** [comment]
Exclude the folder from your Windows Defender, the builder is unobfuscated since otherwise it would be impossible to check the integrity of it.

**Comment by blend47** [comment]
Installed it and using Hashvalut,pro (is it a good pool ?),also can i use more than 1 pc

**Comment by UnamSanctam** [comment]
Hashvault does say on their front page (of most coins) that if you do not have have proxy (xmrig-proxy) you will get banned, so I would not use hashvault. But the miner can mine on any amount of computers, there are no limits.

**Comment by blend47** [comment]
What pool do you suggest ?

**Comment by UnamSanctam** [comment]
For XMR you can use things like 2miners, nanopool, MoneroOcean or similar pools.

**Comment by blend47** [comment]
Okay bro,i pasted GUI XMR wallet adress,is it better to use it or from binance adress

**Comment by UnamSanctam** [comment]
It's always better to use the Monero GUI Wallet or any similar than Binance or any other exchange.

**Comment by blend47** [comment]
Thanks bro
