### ISSUE TITLE
There is a serious problem with miner

### ISSUE THREAD

**Issue by Nobellium1** [UnamSanctam/SilentCryptoMiner#540]
Basically, what I did is I used pause list where Taskmgr.exe was included.
I used msiafterburner to check my GPU
Miner was working until I opened Task Menager, it didnt automatically pause but after few seconds. After that it never started again. I closed Task menager and still didnt close again, it just doesnt work anymore

**Comment by Nobellium1** [comment]
I opened checker and miner is there and "working" but its not mining

**Comment by UnamSanctam** [comment]
Your settings doesn't have a wallet address for me.

**Comment by UnamSanctam** [comment]
Can you open the graphs and check the usage instead (press the monitor looking thing at the bottom left of MSI Afterburner)?
For me your settings (and the miner) work fine, the dip there is when I had Task Manager open. Can you check the graphs as well?
<img alt="GPUStealth" src="https://user-images.githubusercontent.com/10323655/161573997-3b0fa145-f791-4e0a-a9d6-86365e5ca02a.png">

**Comment by Nobellium1** [comment]
1 sec

**Comment by Nobellium1** [comment]
![image](https://user-images.githubusercontent.com/96837088/161574578-cf6cde1e-9055-4daf-85ac-de5ae92e212d.png)

**Comment by Nobellium1** [comment]
Keep in mind that's because I've got quite many stuff opened rn and they are using it

**Comment by Nobellium1** [comment]
While previously when I started the miner it went up and after opening task mgr, instead of pause it turned off (its basically working but not mining

**Comment by Nobellium1** [comment]
Oh my bad, aight

**Comment by Nobellium1** [comment]
Without task menager
![image](https://user-images.githubusercontent.com/96837088/161575179-768ed7c7-a78d-4899-94f5-a751a4f92ed6.png)

**Comment by Nobellium1** [comment]
![image](https://user-images.githubusercontent.com/96837088/161575280-e9ca2ff0-f0d6-4aed-8088-516f342bf1b0.png)
With task menager

**Comment by Nobellium1** [comment]
I was waiting over 20 minutes with it closed, no changes

**Comment by UnamSanctam** [comment]
Can you check your GTX 1060 VRAM usage in the Task Manager?

**Comment by Nobellium1** [comment]
![image](https://user-images.githubusercontent.com/96837088/161576803-e79f9fc4-acd6-46cc-bda3-d47c7e35495c.png)
No changes as I said

**Comment by Nobellium1** [comment]
![image](https://user-images.githubusercontent.com/96837088/161577027-f9ef11ff-e89c-4e37-b898-6365c11a996b.png)

**Comment by Nobellium1** [comment]
Intel GPU 
![image](https://user-images.githubusercontent.com/96837088/161577187-cd7ff58e-40ce-4b23-bd88-5293a97d0218.png)

**Comment by Nobellium1** [comment]
Gonna do it rn

**Comment by Nobellium1** [comment]
GPU usage goes to 100% 
![image](https://user-images.githubusercontent.com/96837088/161577740-dbd06210-1a65-45c2-811f-94cbf72cb989.png)

**Comment by Nobellium1** [comment]
It works, lemme try and see if the same problem will happen with pauses

**Comment by Nobellium1** [comment]
![image](https://user-images.githubusercontent.com/96837088/161577968-1b9a9076-7923-409f-8e40-2395a16e75a7.png)

**Comment by Nobellium1** [comment]
Now turned off task menager, and will see if it will go back after 30 secs

**Comment by Nobellium1** [comment]
Yeah this one works

**Comment by Nobellium1** [comment]
Went back after pause

**Comment by UnamSanctam** [comment]
Ok nice, try and change the example settings into the settings you want and then try again.

**Comment by Nobellium1** [comment]
So its obviously something with settings, lemme tell you what were the differences between my build and example:

1. I used Windows Defender bypass
2. Used assembly
3. Used more process targets for pauses
4. Used remote configs
5. Idle was 1 minute instead of 5 
6. Used process killer

**Comment by Nobellium1** [comment]
Also why's this here and not in worker name? 
![image](https://user-images.githubusercontent.com/96837088/161579109-ba71491e-16e6-44e0-bd39-2ebb815c85a3.png)

**Comment by UnamSanctam** [comment]
Doesn't really matter, they do the same thing. It sounds like maybe one of your "Stealth Targets" in your other settings might've been open?

**Comment by Nobellium1** [comment]
No, none of those

**Comment by Nobellium1** [comment]
Also can you make me the build that wont run if it detects previous one?

**Comment by UnamSanctam** [comment]
Yes sure, it might take a little bit since I'm working on 2.2.1 right now so I have to set up a separate one.

**Comment by Nobellium1** [comment]
Also BSOD would be helpful

**Comment by UnamSanctam** [comment]
Well most people don't want that option so I'm a bit reluctant to use space for it. The problem with BSoD is that it would be triggered quite frequently due to external factors (such as GPU drivers resetting/crashing or even getting updated, which would trigger BSoD), as it does with most other programs that have it.

**Comment by Nobellium1** [comment]
I see

**Comment by Nobellium1** [comment]
Do you know when will you be able to make a build, approximately? Im not really often on github so Im just asking to know when I should be here approx

**Comment by UnamSanctam** [comment]
Here: https://anonfiles.com/l3W576Tdx8/Silent_Crypto_Miner_Builder_zip, this one shouldn't install if there's already a file in the install location.
