### ISSUE TITLE
VirTool:Win32/ExcludeProc.D

### ISSUE THREAD

**Issue by YOTYTeaM** [UnamSanctam/SilentCryptoMiner#541]
![image](https://user-images.githubusercontent.com/72147356/161604830-41f4ddc3-b559-49f8-a6e5-20817f52d9f6.png)
wheres the problem from?

**Comment by UnamSanctam** [comment]
It's a new detection for the "Add Defender Exclusions", at least it first appeared yesterday for me.

**Comment by masterjek** [comment]
> It's a new detection for the "Add Defender Exclusions", at least it first appeared yesterday for me.

It turns out now the function to bypass the defender does not work?

**Comment by UnamSanctam** [comment]
It's a new detection so I have to change the obfuscation of the command again.

**Comment by masterjek** [comment]
> It's a new detection so I have to change the obfuscation of the command again.

I checked on my computer with the defender turned on, after detecting the threat and removing it, the miner continues to work normally and also starts without problems after subsequent reboots of the computer.

**Comment by UnamSanctam** [comment]
Yes it doesn't remove or stop the miner, it usually just warns it, back in 2.0.0 they started detecting the unencoded command.
