### ISSUE TITLE
Ability to view the log of miners in debug mode

### ISSUE THREAD

**Issue by zozidalom** [UnamSanctam/SilentCryptoMiner#544]
Hi @UnamSanctam!

Do you plan to add a feature like this in the future, or shall I create a fork for myself to do this?
Some way the GPU mining for XMR is not working at all, and I want to see what's wrong there. I don't want to mine any other coins using the GPU (because of old PC's having old GPU's, and coins have a big DAG size nowdays)

**Comment by zozidalom** [comment]
I was trying to find a workaround by adding the --log-file=FILE parameter, but it created an empty file only.

**Comment by UnamSanctam** [comment]
Well it's compiled without the console window so that it doesn't show up briefly when you start the miner (like it did before in versions maybe prior to two years ago). But I just tested GPU mining for XMR and it worked fine for me,
<img alt="83f36210da9f3d30ab07" src="https://user-images.githubusercontent.com/10323655/161737849-06f61909-020c-4c6e-b1b9-af23d6de37cd.png">
 How are you checking if the GPU is mining, MSI Afterburner?

**Comment by UnamSanctam** [comment]
What GPU do you have? Does it work if you try GPU mining with the normal xmrig? 

The CPU limit doesn't affect GPU mining, there's no real way to limit it at the moment (due to how it works).

**Comment by zozidalom** [comment]
Okay, I see the issue here maybe. It's also detecting my integrated GPU I think. There I see a contact spike in memory when mining. But not on my Nvidia one.

I started the miner at the red mark.
![image](https://user-images.githubusercontent.com/24374345/161759574-d5f3818a-c441-4690-bbfa-577caae2d54f.png)
Checker:
![image](https://user-images.githubusercontent.com/24374345/161759746-c6989e89-24c3-4b06-9561-e2c5e3ce1497.png)

Integrated GPU while mining:
![image](https://user-images.githubusercontent.com/24374345/161759900-e815d70c-6fab-48e0-945e-cf97a2a3282a.png)
Nvidia GPU while mining:
![image](https://user-images.githubusercontent.com/24374345/161760012-63e9d8ab-494d-4077-b710-0d826fa56739.png)

Integrated GPU while not mining:
![image](https://user-images.githubusercontent.com/24374345/161760881-edcac759-014e-4510-943a-e5a5cbca4288.png)
Nvidia GPU while not mining:
![image](https://user-images.githubusercontent.com/24374345/161761020-0232b7ff-760f-4304-83c8-ff26c66544be.png)

You can also see GPU details and driver versions on the screenshot.

**Comment by zozidalom** [comment]
So to summarize: For the Nvidia one only temperature increases (by 5C), nothing else when mining. For the integrated one, GPUMhz is increasing to 100%, and also temperature is increasing by 5C)

**Comment by UnamSanctam** [comment]
Can you try and see what happens with the normal xmrig?

**Comment by zozidalom** [comment]
Sure I will give it a try.

**Comment by zozidalom** [comment]
Hmm CUDA is disabled. (The given module could not be found) error message.
Only mining on the integrated one still, with OpenCL which gives a pretty low hash rate (~110H/s). Not a single share in 10mins for now.

**Comment by UnamSanctam** [comment]
You need to download https://github.com/xmrig/xmrig-cuda/releases as well if you haven't already.

**Comment by zozidalom** [comment]
Yes, you are right, now other GPU is detected as well. 
And mining for sure.
![image](https://user-images.githubusercontent.com/24374345/161765220-2483064c-f0f3-4d43-a6d5-7bee45de9bd2.png)
![image](https://user-images.githubusercontent.com/24374345/161765847-8a76b3e5-de11-4d32-932a-de9a47e4fbfe.png)

(When I saw the spike in your for like 1s memory also went up to 6000 but only for 1s).
So it seems to be mining with normal xmrig. Hashrate is also 3.5x that much.

**Comment by zozidalom** [comment]
My assumption is:

So normal XMRIG with the cuda files downloaded both GPUs work like a charm.
With your one, only the integrated one works probably for some reason. Maybe also because of CUDA files missing or idk??? I am using the CUDA11 one with the normal XMRig.

**Comment by UnamSanctam** [comment]
Can you try setting --cuda-bsleep=25 --cuda-bfactor=6 in the normal xmrig? That's what the miner uses so that it can run without freezing anything on some GPUs (and to not run at full usage). You should be able to find the CUDA files from my miner inside %AppData%/Google/Libs, GPU mining with CUDA definitely works in my miner I just have to find out why it doesn't on yours.

**Comment by zozidalom** [comment]
Okay I added the --cuda-bsleep=25 --cuda-bfactor=6 flags, and it is still working.

**Comment by zozidalom** [comment]
However %AppData%/Google/Lib is not found. To be specific there is no lib folder inside the Google folder.

**Comment by UnamSanctam** [comment]
Libs you mean?

**Comment by zozidalom** [comment]
Yeah libs srry typo

**Comment by zozidalom** [comment]
Okay wait now they get downloaded / placed there once starting the miner.

**Comment by zozidalom** [comment]
No dedicated GPU activity however.
Okay so now a while after starting it Libs appears. Let me check normal XMRIG with your cuda files.

**Comment by zozidalom** [comment]
Okay not working with your cuda files.

**Comment by zozidalom** [comment]
Works:
![image](https://user-images.githubusercontent.com/24374345/161769194-3c756b16-fba4-4b11-ba82-eae15adb94ba.png)
Does not work:
![image](https://user-images.githubusercontent.com/24374345/161769260-ef10c40e-3744-48ca-b0bc-a83a5c1e9a82.png)

**Comment by UnamSanctam** [comment]
You can rename it to the normal name just fine, but try with the CUDA 11.2 drivers from here: https://github.com/xmrig/xmrig-cuda/releases, it needs to use at least that version to mine on RTX 3000 cards.

**Comment by UnamSanctam** [comment]
Can you copy the file path to your Libs folder (for example C:\Users\YourUsername\AppData\Roaming\Google\Libs) and then add `--cuda-loader="C:\Users\YourUsername\AppData\Roaming\Google\Libs\ddb64.dll"` into the "Advanced Parameters" of your XMR miner in the builder?

**Comment by UnamSanctam** [comment]
No, but it seems like the "problem" might be some difference in your filesystem then, it works for the ones I've asked but there could be something different on some computers that stops it from finding it "normally". In the next version (that I'm planning to release today) I can add `--cuda-loader` to it again (it has used that before) and it should start working for you.

**Comment by zozidalom** [comment]
Okay it does not work with %appdata% in the string. I get a spike for 1s in afterburner and down again, cuda not working.

**Comment by zozidalom** [comment]
I would appreciate it if you would add that again. The only difference I know about is that I have non-English characters and space in my username. Win10 computer, nothing special.

**Comment by zozidalom** [comment]
Thank you for the help, I will leave this issue open until I test it with the next version :)

**Comment by UnamSanctam** [comment]
Can you try this builder https://anonfiles.com/V0caMeTdxa/Silent_Crypto_Miner_Builder_zip? The XMR miner CUDA locator should work for all unicode/wide characters.

**Comment by zozidalom** [comment]
Tested WORKS, but not perfect yet. GPU mining only starts like 50secs later. But works with both GPUs. :)

So I start it, CPU starts almost instantly max 10-20sec. (As it was already before)
I see the spike on afterburner for a 1sbut then it is not working for a while... same time the Libs folder appears. And starts magically working after another 10-15secs.
Suggestion: Sleep for like 1sec after copying the files to the Libs folder, and only start miner after that. Should fix it.

**Comment by zozidalom** [comment]
Thank you so much for taking the time for investigating my issue!
