### ISSUE TITLE
Miner update needed

### ISSUE THREAD

**Issue by Driadasa** [UnamSanctam/SilentCryptoMiner#545]
![photo_2022-04-04_00-31-54](https://user-images.githubusercontent.com/86801280/161728901-ee8ed53b-d3f4-4477-8156-dd925616732a.jpg)

**Comment by UnamSanctam** [comment]
Yes it's a new detection that appeared the day after I released it.

**Comment by Zeevsq1** [comment]
on version 2.1 there is no such thing?

**Comment by UnamSanctam** [comment]
Yes there is, Microsoft just added a static detection of the exact exclusion string that the miner uses, in 2.2.1 the string will morph itself on each build to avoid static detection.

**Comment by 1mavricks1** [comment]
@UnamSanctam Do you have any timeframe for 2.2.1 release? Thank you.

**Comment by UnamSanctam** [comment]
All the things except the potential rootkit update (I'm testing things on my Windows 8 VM right now) and some other things that I might not add into 2.2.1 are done, right now I'm just trying to see if I can replicate some of the issues some have said that they have with the rootkit.

**Comment by Driadasa** [comment]
> Все вещи, кроме потенциального обновления руткита (я тестирую вещи на моей виртуальной машине Windows 8 прямо сейчас) и некоторые другие вещи, которые я не мог бы добавить в 2.2.1, сделаны, прямо сейчас я просто пытаюсь увидеть, могу ли я воспроизвести некоторые из проблем, которые некоторые сказали, что у них есть с руткитом.

Where to download version 2.2.1?

**Comment by UnamSanctam** [comment]
I haven't released 2.2.1 yet, I'm still experimenting with the rootkit to see if I can replicate some peoples issues (and fix them) before I do.

**Comment by Driadasa** [comment]
<img width="678" alt="Screenshot_1" src="https://user-images.githubusercontent.com/86801280/161761075-e56d67d4-f57d-496c-8ce8-3801b21976ce.png">

Here the defender will not swear?
> Я еще не выпустил 2.2.1, я все еще экспериментирую с руткитом, чтобы увидеть, смогу ли я воспроизвести некоторые проблемы людей (и исправить их), прежде чем я это сделаю.

**Comment by UnamSanctam** [comment]
It will detect it in that version as well, the command line string is what has been detected so I have to change it which will be done in the next update which will hopefully be done today.

**Comment by Driadasa** [comment]
> Он также обнаружит его в этой версии, строка командной строки-это то, что было обнаружено, поэтому я должен изменить ее, что будет сделано в следующем обновлении, которое, надеюсь, будет сделано сегодня.

When will the update be approximately?

**Comment by UnamSanctam** [comment]
Hopefully later today.
