### ISSUE TITLE
want ask 

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#546]
it can work Cryptominer2.2.0  builder with UnamWebPanel v1.4.1 ?

and old version XMRSILENT have options to can change to Raptoreum Coin  ?

**Comment by UnamSanctam** [comment]
Yes you can use version 2.2.0 with any version of the UnamWebPanel. The GhostRider algorithm (Raptoreum) was added in SilentCryptoMiner 2.1.0 so as long as your miner is from that version or above you can mine Raptoreum.

**Comment by tarekxxx** [comment]
thanks for answer but i think its was XMRSilent Version

**Comment by UnamSanctam** [comment]
You mean SilentXMRMiner? Then no it doesn't have Raptoreum (neither did most other big miners at that time).
