### ISSUE TITLE
UKRAINE

### ISSUE THREAD

**Issue by 1234567898765432345678** [UnamSanctam/SilentCryptoMiner#547]
З огляду на нагальні умови в Україні, ми не можемо стояти осторонь і не просити вас підтримати українську армію. Ця ситуація не про гроші, а про життя і свободу. Давайте підтримаємо Україну.Чимало талановитих розробників зараз в Україні! Громадська ініціатива «АРМІЯ SOS» координує зусилля людей з надання допомоги воїнам України. Закуповуємо необхідні боєприпаси, щити, домофонну та розвідувальну техніку, уніформу та продукти харчування. Весь вантаж ми доставляємо безпосередньо до місця установки підрозділу і передаємо безпосередньо в руки наших воїнів. Будь ласка, допоможіть поширити!

Considering the urgent conditions in Ukraine, we can’t stay away and ask you to support the Ukrainian army. This situation is not about money, this is about lives and freedom. Let’s support Ukraine. Many talented developers are now in Ukraine! Army SOS Citizens Initiative coordinates people's efforts to help soldiers of Ukraine. We manage purchases of necessary ammunition, shields, intercommunication and reconnaissance facilities, uniforms, and food supply. We deliver all goods directly to the unit`s emplacement and pass them right to the hands of our warriors. Please help spread!

Donate: Bitcoin: bc1qfmgfffne93lz7llhk5yf2kjgkh7eg5vapwupy4
Ethereum: 0xDEfFc29C662AA2945ee156Ac774be2A96b70D0EF
USDT (TRC-20): TC4u4ha7tnrimieg7iQ2FDMoqvP3REY6Rt
Solana: 8P8wnDb2g9GeUGyNNgTAMKouqUQeJVFgWpV4XFNdii9T

**Comment by UnamSanctam** [comment]
This is most likely a possible "scam" (addresses most likely don't belong to any "official" origination), so if anyone does want to donate I would advice them to donate to any real "official" organization, some of which can be found here: https://crystalblockchain.com/verified-ukraine-donation-programs-list/. I will therefore close this issue.

**Comment by 1234567898765432345678** [comment]
Hello. Thanks for the reply. You're right, we really aren't an official
organization! We are volunteers who are not indifferent to the fate of our
country! Moreover, official organizations are another way to officially
fill the pockets of power!!! Any help is useful to us. All funds will go to
help the military of Ukraine! We will provide a report!

вт, 5 апр. 2022 г., 16:11 UnamSanctam ***@***.***>:
