### ISSUE TITLE
 No worker name on nanopool

### ISSUE THREAD

**Issue by gresmax** [UnamSanctam/SilentCryptoMiner#55]
![Screenshot_4](https://user-images.githubusercontent.com/64851092/142033795-ec4544ce-fc0c-4f01-b4a6-787cdb272acd.png)
checker:
![Screenshot_2](https://user-images.githubusercontent.com/64851092/142034426-da0105d2-0883-4d07-873c-53e4da7211e5.png)

**Comment by UnamSanctam** [comment]
Yes nanopools ETC pool is always a bit bugged and they haven't fixed that in quite a long time which is why I usually recommend other pools for ETC

**Comment by gresmax** [comment]
can you recommend any?

**Comment by UnamSanctam** [comment]
Usually ethermine or ezil are the "best", though their hashrate calculations have very long intervals which can be misleading. For example ehtermines "Current Hashrate" is actually the average hashrate over 1 hour. Both pools do say that they ban you for mining with botnets though honestly I haven't seen it happen yet.

**Comment by gresmax** [comment]
I suspect that my problem with non-rooted miners on other computers is related to the ethermines pool. Could this be true?

**Comment by UnamSanctam** [comment]
It shouldn't really since the ethermine pool is the biggest pool but it's not impossible.

**Comment by gresmax** [comment]
then I have no explanation why it works for me and others do not
