### ISSUE TITLE
remote configuration

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentCryptoMiner#550]
which option is correct? need or not ` `
1) "url": "stratum://0xe8D349AC6087d114B1EF41a2E51aa442a3EA50F6@eth-eu2.nanopool.org:9999"
2) "url": "stratum://`0xe8D349AC6087d114B1EF41a2E51aa442a3EA50F6`@eth-eu2.nanopool.org:9999"

**Comment by UnamSanctam** [comment]
Both will work, the second option only encodes everything within it in case you have something special in there.

**Comment by golxd** [comment]
fast) thx, I always use 1 option, everything works. Just saw on **Wiki** `` and it got interesting

**Comment by Abdulrhmanbk** [comment]
> Either will work, the second option only encodes everything within it in case you have something special in there.

Can i use the UnamPanel in localhost to control my bots with port frowding OFC like a RAT

**Comment by UnamSanctam** [comment]
> Can i use the UnamPanel in localhost to control my bots with port frowding OFC like a RAT

Yes, you can just run a web server on your computer/server and host it like you do anything else.
