### ISSUE TITLE
Weird

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#553]
Hi, when I open the rootkit, only one of my 2 miners works, then the other works after a while, do you think this is a problem?

**Comment by DogusCyk** [comment]
when i open it for the first time, it gives ver fault error and only one of them works, then i guess it works in the other miner thanks to the watchdog

**Comment by DogusCyk** [comment]
rip translate

**Comment by DogusCyk** [comment]
I hope you understand what I want to say

**Comment by DogusCyk** [comment]
ah also when i open it to my friend, the dialer.exe is not hidden but the process appears in hacker

**Comment by UnamSanctam** [comment]
Yeah I think those are problem with the r77 toolkit, it doesn't always "activate" until the next restart. For those I might have to wait until he releases r77 toolkit 2.0.0 to be "fixed".

**Comment by DogusCyk** [comment]
ah i see when can you fix this

**Comment by UnamSanctam** [comment]
When r77 toolkit 2.0.0 is finished and released probably.

**Comment by DogusCyk** [comment]
when do you think it will come out

**Comment by UnamSanctam** [comment]
I have not idea, though the developer is actively working on it which is promising.
