### ISSUE TITLE
Defender detect miner

### ISSUE THREAD

**Issue by ssszzzka** [UnamSanctam/SilentCryptoMiner#555]
Im use confuser and on antiscan get 1/26 detect, but defender detect

**Comment by ssszzzka** [comment]
Category: Tool

Description: This program is used to create viruses, worms or other malware.

Recommended action: Remove this software immediately.

Items:
file:C:\Windows\Tasks\dialersvc32.job
file:C:\Windows\Tasks\dialersvc64.job
taskscheduler:C:\Windows\Tasks\dialersvc32.job
taskscheduler:C:\Windows\Tasks\dialersvc64.job

Get more information about this item online

**Comment by UnamSanctam** [comment]
Antiscan doesn't scan everything, for example it doesn't scan with cloud protection which means that your detection most likely comes from the Windows Defender "Cloud Protection". That detection comes from the rootkit, can you post your settings?

**Comment by ssszzzka** [comment]
yes, https://dropmefiles.com/D6Lrb

**Comment by UnamSanctam** [comment]
It looks like your exclusions aren't being added then, don't forget to run it as administrator.

**Comment by ssszzzka** [comment]
i add admin rights separately

**Comment by UnamSanctam** [comment]
Are you sure that it works correctly? Check your Windows Defender exclusions to see if they are there: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by ssszzzka** [comment]
when I test on the server, it detects hiding under processes, and not the miner itself

**Comment by ssszzzka** [comment]
when it is turned off and does not detect anything, filters are set

**Comment by UnamSanctam** [comment]
Are the exclusions there? Can you screenshot them? If they are then it's the rootkit that's getting detected (your detection at least is from the rootkit), then you'd probably have to disable it.

**Comment by ssszzzka** [comment]
If you turn off the rootkit, then it is not silent, because when you open the task manager for 5-10 seconds, it works 100 percent under a different svchost
![image](https://user-images.githubusercontent.com/103114718/161963329-b1b802a5-27ce-4a3d-a2ca-0d31e567cd86.png)

**Comment by ssszzzka** [comment]
exclusions

**Comment by UnamSanctam** [comment]
It's still silent even when you don't have the rootkit enabled, it checks for things like "Stealth Targets" every 2.5 seconds so it usually pauses before the Task Manager has time to load, not to mention all the other features.

But yeah then it looks like the rootkit is detected on your computer, it's still an experimental feature (hence why it's red and the warning) and I'm not the developer of it either so it will always have it's issues.
<img alt="6367ecd6c8f9fe4a5b04" src="https://user-images.githubusercontent.com/10323655/161963992-851cf97c-fac2-4799-9579-183fd6c7f978.png">

**Comment by ssszzzka** [comment]
I launched without a rootkit, there is no detection

**Comment by ssszzzka** [comment]
the problem is in it

**Comment by UnamSanctam** [comment]
Yes it looks like it's due to the fileless persistence that the r77 rootkit uses, maybe he is changing something in the 2.0.0 release that he is working on. I'd rather not have to change it to normal file startup myself.

**Comment by ssszzzka** [comment]
miner again detected Category: Tool

Description: This program is used to create viruses, worms or other malware.

Recommended action: Remove this software immediately.

Items: 
file:C:\Windows\Tasks\dialersvc32.job
file:C:\Windows\Tasks\dialersvc64.job
regkey:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks\{38659E22-CF49-49A0-AB80-A9CCACE04F6C}
regkey:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks\{E0901C81-2C1D-46B1-8C6D-C92924CBF9C7}
regkey:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\dialersvc32
regkey:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\dialersvc64
taskscheduler:C:\Windows\Tasks\dialersvc32.job
taskscheduler:C:\Windows\Tasks\dialersvc64.job

Get more information about this item online.

**Comment by UnamSanctam** [comment]
Yes the rootkit is detected, that's what we said above.
