### ISSUE TITLE
Miner doesn`t appear

### ISSUE THREAD

**Issue by LiquidTeaMaker** [UnamSanctam/SilentCryptoMiner#557]
I built gpu miner, builder made 3 exe files and I started exe running file. Unfortunately checker doesn`t show me my miner. Only one time i saw what should be in "Miners" line, but after restarting checker miner disappeared again.

**Comment by UnamSanctam** [comment]
Sounds like your pool connection settings are wrong, can you post them here?

**Comment by LiquidTeaMaker** [comment]
![Pool](https://user-images.githubusercontent.com/102413206/162034541-7a5c3f61-e0a7-4d4a-9814-cc84008d1479.png)

**Comment by UnamSanctam** [comment]
Can you start the checker and take a screenshot? Also, can you try the example settings at the top of the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki? Since then we'll know if it's because of any of your settings or not.

**Comment by LiquidTeaMaker** [comment]
![owner_panel](https://user-images.githubusercontent.com/102413206/162038085-a2c9e466-ac95-4a41-ac95-1829f1aa2ce4.png)
There is your settings, but you can see that GPU miner is not working(
![my_panel](https://user-images.githubusercontent.com/102413206/162038287-80d35e88-03dd-47ec-b363-f5184ee0a1ee.png)
I set only GPU miner so there is nothing

**Comment by UnamSanctam** [comment]
Yes that would be the easiest.
