### ISSUE TITLE
Hello. I want to ask a couple of questions.

### ISSUE THREAD

**Issue by bvi32** [UnamSanctam/SilentCryptoMiner#559]
a) Could you recommend an open source wallet for etc/eth?
b) If there is not enough vram on the computer, the miner simply won't start? Or will it start and take up the entire vram?
c) I have several devices running older versions of your miner (xmr only), does it make sense for me to update them so that people download the updated version?

I understand that it is difficult to listen to a lot of questions everyday and answer them. For my part, I will transfer you a couple of bucks (to the xmr wallet) to show others an example and cheer you up a little.

**Comment by UnamSanctam** [comment]
a) I guess MetaMask is the only open source one I know.
b) Then it simple won't start (or wait until there's enough VRAM).
c) Maybe, the XMR hashrate will be about the same but if you add a GPU miner then it would be more profitable. Though GPU miners are more noticeable than CPU miners by the nature of how they work which could be a downside if you want to add that. Usually as long as the miner is working for you there's no need to update unless you want to use some of the new features.

**Comment by UnamSanctam** [comment]
Adding the ETC chain into MetaMask is really easy, just follow this guide: https://metamask.zendesk.com/hc/en-us/articles/360058809292, you only have to add a custom RPC with the ETC network settings and then you can select the network in the menu.

I have the ETC usage set to Max GPU 50% and Idle GPU 100%, it will have less profit than always mining at 100% of course but it will also interfere less with the person using the computer and the GPU won't heat up as much.

>By the way, I translated 0.01 xmr yesterday, even if you wouldn't have answered my questions. I think that at least a little bit, but everyone needs to support their favorite free software developers.

Thank you very much, I appreciate it friend.

**Comment by bvi32** [comment]
> Adding the ETC chain into MetaMask is really easy, just follow this guide: https://metamask.zendesk.com/hc/en-us/articles/360058809292, you only have to add a custom RPC with the ETC network settings and then you can select the network in the menu.

> I have the ETC usage set to Max GPU 50% and Idle GPU 100%, it will have less profit than always mining at 100% of course but it will also interfere less with the person using the computer and the GPU won't heat up as much.

Thank you, I will do so.

> Thank you very much, I appreciate it friend.

In fact, this is not as much as I would like, I have no experience in mining and I do not know all the subtleties. Besides, I don't use cryptors, so the income is even less than it could be. But I don't care, I just have fun doing it.
But it is necessary to support in any case.
