### ISSUE TITLE
REALLY LOW HASHRATE 3000 SERIES

### ISSUE THREAD

**Issue by nobodyguard** [UnamSanctam/SilentCryptoMiner#56]
![image](https://user-images.githubusercontent.com/94497749/142087213-f732f9d9-001d-4524-9df8-bc452b7d3691.png)
How it's possibile a 3060 mining only 10MH/S ?

Max gpu it's 100%

**Comment by UnamSanctam** [comment]
An RTX 3060 (non LHR) has about 30MH/s at max but either they could be using the GPU so it can only use 30% or that could be something like an LHR (low hashrate) card. Or they could also have some sort of other limit set on their card which is possible as well.
