### ISSUE TITLE
i have installed in MY VPS

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#561]
After i install my Program i Disabled Anti Virus Totally And allow port to firewall

and seems active already front of me and calc hashrate 
but nothing sees in nanopool no worker no anything
![Screenshot (59)](https://user-images.githubusercontent.com/20240556/162088609-fb6b4d5f-ff84-46f4-9351-620cd98b5e43.png)

**Comment by Brainshot** [comment]
nanopool is broken it doesnt show workers for this builder

**Comment by tarekxxx** [comment]
Also Not calc The Hash Rate ???

**Comment by UnamSanctam** [comment]
You probably just had to find a share first, has it appeared yet?

**Comment by tarekxxx** [comment]
not appear with new version with i7 7700 Intel wait 1 hour then totally even worker not shown i delete new version from my vps and install 2.1.0 is working fine and appears share

**Comment by UnamSanctam** [comment]
Are you sure you're using version 2.2.1? Is no hashrate showing on the pool or just the worker (you can have hashrate without a worker)?

**Comment by tarekxxx** [comment]
no both not working with same settings i put in 2.2.1 same settings i put in 2.1.0 

yea no worker no hashrate added

**Comment by UnamSanctam** [comment]
Hmm weird, I'm mining to nanopool just fine right now, can you post your settings here?

**Comment by tarekxxx** [comment]
Sure 
![Screenshot (60)](https://user-images.githubusercontent.com/20240556/162195987-9a067f3c-dba8-4811-88dc-86cd8c10d5fa.png)

and i got another problem i have 2 VPS one working fine and another was have sophos anti virus i ddelete sophos to can make my app running but seems nothing i install in an other VPS but nothing working in task manager explorer.exe but nothing rated can you help me in this too i allow firewalls ports but same totally

**Comment by UnamSanctam** [comment]
Well you have "Stealth" enabled with the Task Manager so it shouldn't be using any CPU while you have the Task Manager open. But you also have "Remote Configuration" enabled so I'd have to see that configuration as well.

**Comment by tarekxxx** [comment]
even when i close it Bro i open task manager just now it idle from yestarday all day long even not calc 1 hashrate

**Comment by UnamSanctam** [comment]
How many CPU cores and RAM do you have on that? Also remember that you have your worker name set to "Hacked" as well. Isn't that miner showing up on the web panel?

**Comment by tarekxxx** [comment]
No Not showin from yestarday and All Miner with Hacked Yes But i dont see this PC 
and also CPU Is 
![Screenshot (63)](https://user-images.githubusercontent.com/20240556/162198559-d2b43041-4fa5-4bd5-9ba2-09fdc2997f1a.png)

but with Another VPS usally i see Miner At least take 2 Gigs of ram but there nothing Bro like Nothing and i keep editing in firewall allows nothing restart VPS after delete sophos Nothing even not appear in webpanel at all

**Comment by UnamSanctam** [comment]
On the VPS it isn't working can you open CMD and run `ping xmr-eu1.nanopool.org` and post what it returns? Alternatively can you try mining with a normal xmrig on that VPS? You can use this if you don't want to set it up yourself: [standard_xmrig.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8442844/standard_xmrig.zip) just run `start nanopool.bat`.

**Comment by tarekxxx** [comment]
![Screenshot (64)](https://user-images.githubusercontent.com/20240556/162202376-48126578-82e8-4323-af5c-530f41ccbc3a.png)
its not pingable how i can fix this change dns now its 8.8.8.8

**Comment by UnamSanctam** [comment]
Are you able to access websites using your browser? But try running `ipconfig /flushdns` , also check your hosts file at `C:\WINDOWS\system32\drivers\etc\hosts` (it's hidden) in case it contains something weird.

**Comment by tarekxxx** [comment]
![Screenshot (65)](https://user-images.githubusercontent.com/20240556/162203993-39454546-e122-4460-907e-e125e09ac352.png)

for here i think nothing all #comments like you see something really weird

**Comment by UnamSanctam** [comment]
Your hosts file is normal so it's nothing with that at least. It's probably either your DNS settings, your firewall or some antivirus that's preventing your from connecting to anything. Try disabling your firewall and see if it starts working. I'm not about the circumstances with your VPS but you can try running these commands in order and then restart the VPS:
```
ipconfig /flushdns
ipconfig /registerdns
ipconfig /release
ipconfig /renew
netsh winsock reset
```

**Comment by tarekxxx** [comment]
![Screenshot (66)](https://user-images.githubusercontent.com/20240556/162205804-4f3390d8-4ef9-4483-ad67-4b7032a3f8d8.png)

i found some ports added in protocols file should i delete my port ?

**Comment by UnamSanctam** [comment]
No you shouldn't have to do anything like that.

**Comment by tarekxxx** [comment]
> Try doing what I said in the earlier post if you haven't already, but have you had internet access before on that VPS?
> 
> > Your hosts file is normal so it's nothing with that at least. It's probably either your DNS settings, your firewall or some antivirus that's preventing your from connecting to anything. Try disabling your firewall and see if it starts working. I'm not about the circumstances with your VPS but you can try running these commands in order and then restart the VPS:
> 
> ```
> ipconfig /flushdns
> ipconfig /registerdns
> ipconfig /release
> ipconfig /renew
> netsh winsock reset
> ```

yea ofc i do and restart PC also 
and yea have internet its VPS connection 1 Giga but filtered ports or some websites whos only work for database and etc just need allow myself with this apps
