### ISSUE TITLE
what the error

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentCryptoMiner#563]
![image](https://user-images.githubusercontent.com/81568432/162220708-93eda1ec-11a3-4488-8c4f-193123488f02.png)

**Comment by golxd** [comment]
I accidentally installed the miner on my laptop, I will delete it now. But what is this mistake? And why does it show up every 2-3 minutes

**Comment by UnamSanctam** [comment]
Your OpenCL drivers (AMD GPU) aren't correct or you have some sort of version without OpenCL.
