### ISSUE TITLE
Wtf hashrate

### ISSUE THREAD

**Issue by FreeM1ne** [UnamSanctam/SilentCryptoMiner#565]
Hashrate dropped three times
![image](https://user-images.githubusercontent.com/83845767/162230233-dc6100f3-a8f7-4266-98f8-1aebd9ad081c.png)

**Comment by FreeM1ne** [comment]
Since you still add the entire disk to the exclusions, maybe you should just kill Windows Defender?

**Comment by UnamSanctam** [comment]
Not really possible to do easily and it wouldn't even matter in this situation since the Windows Update reinstalls Windows Defender and resets all the settings.

**Comment by FreeM1ne** [comment]
I saw in my opinion a couple of options when even an update does not help

**Comment by Brainshot** [comment]
> Not really possible to do easily and it wouldn't even matter in this situation since that Windows Update "reinstalled" Windows Defender and reset all the settings.

You could try and disable windows updates, cant you add this in your next update?

**Comment by UnamSanctam** [comment]
> You could try and disable windows updates, cant you add this in your next update?

Yes I'm already doing that (and have already finished that part).

**Comment by Brainshot** [comment]
> > You could try and disable windows updates, cant you add this in your next update?
> 
> Yes I'm already doing that (and have already finished that part).

Yeah thanks, i used your test version where there is option for disable windows updates

has anyone else used that test version?

**Comment by FreeM1ne** [comment]
?

**Comment by FreeM1ne** [comment]
where is this version?
