### ISSUE TITLE
Does run time detection will case if...

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#566]
Hello bro. Thanks for this amazing miner. I have a question. Does the miner become detected at run time if i didn't turn on "ran as administrator" and/or "add win defender exclusion"?
Thanks

**Comment by UnamSanctam** [comment]
Yes usually unless you have some obfuscator for it that reduces it, .NET Reactor used to make it undetected before by running it in a VM, though it eventually got detected since so many used it.

**Comment by DerXanRam** [comment]
So if i obsfucate it the detaction may be dcreased?

**Comment by UnamSanctam** [comment]
Yes, it depends on what the obfuscator does (how it obfuscates it).

**Comment by DerXanRam** [comment]
Ok... but due to the reason i am installing the miner on public computers, admin access is locked. Is there any program or do u have any suggestion to pass this problem(by pass admin or UAC)?

**Comment by UnamSanctam** [comment]
You might be able to use something like https://github.com/hfiref0x/UACME to bypass UAC, so you'd download that and run something like `akagi64 61 c:\path\to\miner` with `c:\path\to\miner` leading to wherever your miner is located. Though usually those kinds of programs are detected as well.

**Comment by DerXanRam** [comment]
Ok.... what is if i obsfucate the non admin miner with best obsfucatores over 1 time? Does this crash the miner?

**Comment by UnamSanctam** [comment]
No but you probably can't obfuscate multiple times if that's what you're wondering.

**Comment by DerXanRam** [comment]
Ok thanks very much🙏🙏
