### ISSUE TITLE
obsfucator setting

### ISSUE THREAD

**Issue by Zeevsq1** [UnamSanctam/SilentCryptoMiner#569]
what settings to include for this obsfukator
![Annotation 2022-04-08 052023](https://user-images.githubusercontent.com/101643042/162350614-199f04eb-e9b4-47c3-954b-f644b352ac11.png)
?

**Comment by UnamSanctam** [comment]
It's best to experiment around with them and create multiple builds and test, some settings could increase detections while some could decrease them.

**Comment by hidden-69** [comment]
What obfuscator is this?

**Comment by tarekxxx** [comment]
> what settings to include for this obsfukator ![Annotation 2022-04-08 052023](https://user-images.githubusercontent.com/101643042/162350614-199f04eb-e9b4-47c3-954b-f644b352ac11.png) ?

what name this application bro ?
