### ISSUE TITLE
Unambinder with silentcryptominer

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#57]
How can i use unambinder without it giving me any bugs?

For example that it can actually work when a PC is restarted , what should the Filename be? just tell me how you used your unambinder with a miner if you ever did.

**Comment by UnamSanctam** [comment]
The binder will just drop it and execute it, the filename can be anything as long as it isn't the same as any other file in the folder you choose to drop it in and as long as the "Filename" in the miners "Startup" settings are different.

**Comment by Brainshot** [comment]
> 
> 
> The binder will just drop it and execute it, the filename can be anything as long as it isn't the same as any other file in the folder you choose to drop it in and as long as the "Filename" in the miners "Startup" settings are different from the binders "Filename".

So lets say in the builder the name is services.exe, i should just name it anything else in the unambuilder?

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by Brainshot** [comment]
> 
> 
> Yes exactly.

Thanks

**Comment by Brainshot** [comment]
> 
> 
> Yes exactly.

Also if they keep reopening my binded file will it add too many miners? or it will keep being 1 miner

**Comment by Brainshot** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
It will always keep being 1 miner.
