### ISSUE TITLE
Generated JSON

### ISSUE THREAD

**Issue by hidden-69** [UnamSanctam/SilentCryptoMiner#570]
KILL Targets is not generated in json while it is entered in the settings. API Settings as well, but that is known I think.

Are the Stealth & KILL targets case sensitive?

**Comment by UnamSanctam** [comment]
Hmm, kill targets work fine for me. Are you sure you have "Process Killer" enabled? And yes the API settings isn't in the builder since people kept disconnecting their web panels with it.

Yes they are case sensitive (the default behavior).

**Comment by hidden-69** [comment]
Yes that was it 🤦‍♂️ 

Thanks for the info
