### ISSUE TITLE
Can i use UnamBinder still?

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#573]
for the new updated silentbuilder

like is it gonna break anything?

**Comment by UnamSanctam** [comment]
No it should work fine, you should be able to use the binder for any file really.

**Comment by Brainshot** [comment]
> No it should work fine, you should be able to use the binder for any file really.

Alright thank you, if i remember right it just drops the file in temp and opens it correctly

Will it open the miner as administrator?

**Comment by UnamSanctam** [comment]
Yes it just drops the file where you chose and executes it. If you select "Run as Administrator" in the binder then it will also start the files as administrator.
