### ISSUE TITLE
How to get clients

### ISSUE THREAD

**Issue by arnaud2s3** [UnamSanctam/SilentCryptoMiner#574]
Hey, I was wondering what your methods are to get clients.
Can you help me?

Feel free to contact me on discord: raptorGamer#6765

If someone can explain me a good method, I'm willing to give him between 2% and 5% of the income each month.

**Comment by Nobellium1** [comment]
Nobody cant guarantee you'd give % each month so if I was you, I wouldn't expect for such info

**Comment by ahmedjafari** [comment]
i did add you my name is jafari
