### ISSUE TITLE
Hashrate keeps going down even with WD Update turned off

### ISSUE THREAD

**Issue by Nobellium1** [UnamSanctam/SilentCryptoMiner#576]
Okay so basically I've got over 400MH/S in a day. Over 100 people ran it. It was 400MH/s for almost entire day and now it's 0. I didnt change anything, it just completely dissapeared

**Comment by Nobellium1** [comment]
Keep in mind I was using the version you sent me with WD Update turn off option

**Comment by UnamSanctam** [comment]
Did it not install correctly? Can you try running it and see if it gets added into the Task Scheduler?

**Comment by Nobellium1** [comment]
Can you log via Team viewer and check it cus Im not too sure where am I supposed to see it in task scheduler

**Comment by UnamSanctam** [comment]
I'm currently not at the computer for some time, if you open the Task Scheduler and press the library on the left side then you should get a lot of entries, there should be an entry with the name chosen in the builder ("Entry Name") there.

**Comment by Nobellium1** [comment]
Entry name is: GoogleUpdateTaskMachineQC
However there is already GoogleUpdateTaskMachineQC in my PC and Im kinda sure I uninstalled the miner

**Comment by UnamSanctam** [comment]
The GoogleUpdateTaskMachineQC is the miner, but if you have that then it should be installed. The weird part is that it went to 0 hashrate, at least someone shouldn't have turned off their computer. It's more likely that it's something else, can you post the settings of those miners? And how slowly did it go down, can you post a screenshot?

**Comment by Nobellium1** [comment]
Settings: https://file.io/0QiXGk3jKqBp

**Comment by Nobellium1** [comment]
![image](https://user-images.githubusercontent.com/96837088/162574443-7c35b5f4-cd4f-47a0-9704-25a165ac7854.png)

**Comment by Nobellium1** [comment]
Note that miner was way more than 90mhs as it says there, but its from last x hours

**Comment by UnamSanctam** [comment]
Oh, I don't think you can use ":" inside entry names like you did for your "Entry Name".

**Comment by Nobellium1** [comment]
What do you mean?

**Comment by Nobellium1** [comment]
Oh I see

**Comment by Nobellium1** [comment]
You think that's the actual problem?

**Comment by UnamSanctam** [comment]
Yes probably, it might not be able to add the task with an illegal name.

**Comment by Nobellium1** [comment]
Would it be possible to make any notification server to make sure everything is okay with miner, for example 

"Miner installed successfully"
"PC Started - Starting miner successfully"
"Miner stops working - pause"
But not with webpanel because hosting is banning it quite often

**Comment by Nobellium1** [comment]
I know you don't really like webhooks, but any solution like that would be good

**Comment by UnamSanctam** [comment]
No I don't really plan to implement any APIs for external services (most services need entirely different structures). But if your web panel is getting banned you can always host it on a VPS or by yourself behind a VPN or something.

**Comment by Brainshot** [comment]
@UnamSanctam  I have task scheduler on process killer, will it still add it there?

**Comment by UnamSanctam** [comment]
Depends on what you're killing, the `schtasks.exe` program is mainly used to add tasks so if you're not killing that then it should work. It also depends on how fast it finishes adding the task, even if you kill schtasks then the command to add a task might finish faster than it gets killed.
