### ISSUE TITLE
name

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentCryptoMiner#577]
I use xmr and eth at the same time, I understand so "**File name**" should be different. "**Entry name**" also need to be different?

**Comment by UnamSanctam** [comment]
Well they don't have to be different but you can change them if you want to (make sure that you entered everything correctly and then also test it to be certain). "File Name" is the actual path of the file while "Entry Name" is the name in the startup list.

**Comment by golxd** [comment]
okey, thx. Tell pls, will it new version miner with disabling Windows Updates?

**Comment by Nobellium1** [comment]
@UnamSanctam Btw the previous build you sent me will not install over previous miners if its in same directory or it will? I dont know if you did it so just asking

**Comment by UnamSanctam** [comment]
> @UnamSanctam Btw the previous build you sent me will not install over previous miners if its in same directory or it will? I dont know if you did it so just asking

Hmm, don't really remember. I think it will install over previous ones. I've been deliberating what I should call that option, currently it's "Don't overwrite old miners" which might be clear enough what it does.

**Comment by Nobellium1** [comment]
Yeah, that sounds totally fine
