### ISSUE TITLE
Where can I watch watchdog in version 2.2.2?

### ISSUE THREAD

**Issue by Driadasa** [UnamSanctam/SilentCryptoMiner#578]
I don’t see sihost67 in the processes, how can I check the miner’s work now?

**Comment by UnamSanctam** [comment]
The watchdog gets injected into conhost.exe, if you can list all your conhost.exe processes then the watchdog should have "randomcharacters" in its command line.

**Comment by Driadasa** [comment]
> The watchdog gets injected into conhost.exe, if you can list all your conhost.exe processes then the watchdog should have "randomcharacters" in its command line. Or you can run the checker.

What folder is it unpacked into?
Where can I find the file itself?

**Comment by UnamSanctam** [comment]
Are you using the 2.2.2 beta or the 2.2.1 release on GitHub?

**Comment by Driadasa** [comment]
> Are you using the 2.2.2 beta or the 2.2.1 release on GitHub?

2.2.2

**Comment by UnamSanctam** [comment]
Then if you have "Run Watchdog in Memory" (enabled by default) then it won't unpack/extract anywhere, it exists only in the memory. This quite greatly reduces possible detections since there's no watchdog file to detect.

**Comment by Driadasa** [comment]
> Then if you have "Run Watchdog in Memory" (enabled by default) then it won't unpack/extract anywhere, it exists only in the memory. This quite greatly reduces possible detections since there's no watchdog file to detect.

How can I remove it from my computer?
Remover doesn't help.

**Comment by UnamSanctam** [comment]
The watchdog or the miner? The uninstaller should remove it just fine but otherwise you can just remove it manually https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner. All you need to do to remove the watchdog is to kill the process.
