### ISSUE TITLE
uninstaller problem

### ISSUE THREAD

**Issue by devil1110111** [UnamSanctam/SilentCryptoMiner#579]
uninstaller wont remove miners its the first time something like this happen

**Comment by UnamSanctam** [comment]
Seems like it doesn't remove the startup task, you can remove it manually https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner.

**Comment by devil1110111** [comment]
> Seems like it doesn't remove the startup task, you can remove it manually https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner.

hi unam there is any way i can connect and talk with you in private?

**Comment by UnamSanctam** [comment]
Not currently, the new hard drives I ordered (to replace my broken ones) haven't arrived for maybe 2-3 months. I'll probably need to order them from somewhere else.

**Comment by devil1110111** [comment]
> Not currently, the new hard drives I ordered (to replace my broken ones) haven't arrived for maybe 2-3 months. I'll probably need to order them from somewhere else.

not even discord?

**Comment by UnamSanctam** [comment]
My Discord was banned before (for helping with the miner I guess), then I got Telegram but my hard drives hosting the VM it was on broke. So I'm waiting for my new ones to set up Telegram again.

**Comment by devil1110111** [comment]
> My Discord was banned before (for helping with the miner I guess), then I got Telegram but my hard drives hosting the VM it was on broke. So I'm waiting for my new ones to set up Telegram again.

telegram would be great do you announce when you got telegram account or i ask you again later?

**Comment by UnamSanctam** [comment]
My Telegram is @UnamSanctam, I just can't access it before I get my hard drives (don't have any disk space right now for new VMs).
