### ISSUE TITLE
Usage issues

### ISSUE THREAD

**Issue by Jackeyone23** [UnamSanctam/SilentCryptoMiner#58]
Man, I'm a little unclear, is it only necessary to use this one software to use it, no need to download the others? Seeing that you have a binder and a downloader, I'm a little unsure of how to use it, haha

**Comment by UnamSanctam** [comment]
Yes only this, the binder is used to bind several files together and the downloader is to do the same but downloading the files instead. They aren't connected to the miner in any way.

**Comment by Jackeyone23** [comment]
OK
