### ISSUE TITLE
remote config

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentCryptoMiner#580]
sorry, where can i read what they mean
 "keepalive" "rig-id"

**Comment by UnamSanctam** [comment]
KeepAlive keeps the connection alive with the pool (so it never times out) but not all pools support it, usually pools don't say that they support it so you have to test it yourself and see. Nanopool does not support keepalive.

RigID is special (optional) field for worker names that some pools support,

**Comment by golxd** [comment]
its ok?
c:39: warning: assignment makes integer from pointer without a cast

**Comment by UnamSanctam** [comment]
Yes it doesn't really matter.
