### ISSUE TITLE
0 workers Ethermine

### ISSUE THREAD

**Issue by poulty** [UnamSanctam/SilentCryptoMiner#59]
![image](https://user-images.githubusercontent.com/94555255/142245134-2f96d059-6104-46a5-9d3b-bf3ab5cb7496.png)
![image](https://user-images.githubusercontent.com/94555255/142243979-b6cc55b7-ad60-4811-81c9-48f6100255a6.png)
It seems like I did everything right, but there are 0 workers on ethermine
![image](https://user-images.githubusercontent.com/94555255/142244357-b85e83e9-95a1-474e-99e9-c48caab87d38.png)

**Comment by UnamSanctam** [comment]
For how long has it been mining? The miner needs to find a share first and then submit it for it to appear on the pool (that's how all pools work).

**Comment by poulty** [comment]
> For how long has it been mining? The miner needs to find a share first and then submit it for it to appear on the pool (that's how all pools work).

It's been working for 2 hours already

**Comment by UnamSanctam** [comment]
You have the wrong algorithm, it's set to etchash but Ethereum uses ethash.

**Comment by poulty** [comment]
> You have the wrong algorithm, it's set to etchash but Ethereum uses ethash.

I've already tried ethash, but it still gives out 0 workers :(

**Comment by UnamSanctam** [comment]
No it will work with ethash, put it to ethash and wait, it can take 1-30 minutes for a miner to find a share.

**Comment by poulty** [comment]
Changed to ethash, waited 30 minutes, but still 0 workers
![image](https://user-images.githubusercontent.com/94555255/142252318-923cd4be-f6d3-4258-ad4d-40a99b114da7.png)
![image](https://user-images.githubusercontent.com/94555255/142252386-a6640cc9-114b-45df-93bf-bd8aec83883e.png)
![image](https://user-images.githubusercontent.com/94555255/142252437-a92c8bd2-aedc-4eb6-9c75-5c58e67c84ed.png)


> No it will work with ethash, put it to ethash and wait, it can take 1-30 minutes for a miner to find a share.
