### ISSUE TITLE
Kill Targets

### ISSUE THREAD

**Issue by Zeevsq1** [UnamSanctam/SilentCryptoMiner#591]
I couldn't check "Kill Targets" on the virtual machine (because the processes I specified are running) and wanted to know. If I specify the "regedit.exe" process, the user will not be able to enter and edit the registry to remove the miner?

**Comment by UnamSanctam** [comment]
Yes (as long as the user you're running the miner as has enough permissions to kill it), though regedit.exe might be used by other things as well.
