### ISSUE TITLE
Xmrig

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#592]
Tell me please. I can use xmrig from version 2.2.1 in version 2.3.0?

**Comment by UnamSanctam** [comment]
Yes of course, why would you though?

**Comment by masterjek** [comment]
I just really liked the version 2.2.1 - And with each new version, as I understand it, it is updated and Xmrig. So I want to transfer from the new version Xmrig.

**Comment by UnamSanctam** [comment]
Well there aren't any downsides of just using 2.3.0 that I'm aware of, but yes that should work.

**Comment by masterjek** [comment]
I just can't encrypt - RunPE.dll to make full use of the version 2.3.0, and in the version 2.2.1 I can encrypt everything together and everything works fine.

**Comment by UnamSanctam** [comment]
You don't need to obfuscate RunPE.dll, obfuscating the full version of 2.2.1 gives more detections than not obfuscating RunPE.dll in 2.3.0. And even then you can always obfuscate RunPE.dll if that's what you want to do, but it's not really necessary either just like you don't need to crypt xmrig.exe and ethminer.exe.

**Comment by masterjek** [comment]
Thanks more for your help. Then I'll try version 2.3.0.
