### ISSUE TITLE
Block Windows Update site with host file?

### ISSUE THREAD

**Issue by lllminus3** [UnamSanctam/SilentCryptoMiner#593]
Since there is a possiblity to block website, cannot we block just all microsoft websites/ip which are responsible for windows updates?
Or does windows ignore the hosts file for updates?

**Comment by UnamSanctam** [comment]
Windows Defender usually gives a lot of notifications and things when blacklisted sites (like microsoft.com) gets added into the hosts file. It also sometimes blocks them from being added.

**Comment by lllminus3** [comment]
But this feature can be used to mass block AV sites that they cannot reach for help

**Comment by UnamSanctam** [comment]
Yes exactly (which is its main purpose),
