### ISSUE TITLE
hello i can get exe?

### ISSUE THREAD

**Issue by minde3000** [UnamSanctam/SilentCryptoMiner#594]
hello can i get the xmr etc miner generated exe file?

**Comment by UnamSanctam** [comment]
What exactly do you mean? You can get an XMR/ETC miner by creating one in the builder https://github.com/UnamSanctam/SilentCryptoMiner/releases.

**Comment by minde3000** [comment]
maybe i can get an already done miner menu?i can't do it /

**Comment by UnamSanctam** [comment]
Well you'll need to set it up with your wallet address and everything, have you at least gotten the builder opened? If so you can find some example settings here: https://github.com/UnamSanctam/SilentCryptoMiner/files/7893976/ExampleSettings.zip, if you unzip that then you can load the .xml file into the builder by pressing the "Load" button.

**Comment by minde3000** [comment]
https://imgur.com/7C33hYh
https://imgur.com/telfrpW
what am i doing wrong

**Comment by UnamSanctam** [comment]
Did you enter any of these: ` into the "Wallet Address"? If so then remove them, it adds them automatically.

**Comment by minde3000** [comment]
thanks maybe you can get the eth far settings? and how to delete an old miner from an client?

**Comment by UnamSanctam** [comment]
> thanks maybe you can get the eth far settings? and how to delete an old miner from an client?

Not sure what you mean by the first question, but to remove an old client from a computer you can run the uninstaller. If you want to remove it from the web panel list then there's a button in the miner list for that (press the '+' button), but that button doesn't remove it from the computer. You can also just create an ETH configuration inside the "Configurations" tab (you can use the "Default ethminer" configuration) that works and that client will start using it.

**Comment by UnamSanctam** [comment]
It's because you use XMR "GPU mining", you need the xmrig CUDA libraries then.

**Comment by minde3000** [comment]
but for some reason digging with gpu doesn't work

**Comment by UnamSanctam** [comment]
GPU mining works in both the XMR and ETC miners, what doesn't work for you?

**Comment by UnamSanctam** [comment]
> when i turn on the gpu it makes no difference or with gps Xmr

You'll have to check for GPU usage with something like MSI Afterburner if you aren't already, you can't see GPU usage in the Task Manager or similar things. But mining XMR with the GPU is not really recommended, Monero (XMR) is a CPU coin so mining with the GPU is not very profitable.

> I'm sorry I'm scared. my english is not good

Haha it's no problem.
