### ISSUE TITLE
Visual Studio

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#595]
Good afternoon. Tell me please. When I build a project there is a menu item. Binary Analyzers. Binary parsers are deprecated.
Run on build - This item is inactive.
Exclude results from generated code - This item is active - Should it be left active when building the project or is it better to turn it off?

**Comment by UnamSanctam** [comment]
Where are you seeing that? To build you just have to press the "Build" menu at the top of Visual Studio and press "Build Solution".

**Comment by masterjek** [comment]
I see it in - Project - Properties Silent Crypto Miner Builder - Code Analysis

**Comment by UnamSanctam** [comment]
Oh, well those are irrelevant, you can ignore all those.

**Comment by masterjek** [comment]
As I understand it, when building a project, I should not touch the project settings at all?

**Comment by UnamSanctam** [comment]
Yes there's no need to.

**Comment by masterjek** [comment]
Thanks for the help.
