### ISSUE TITLE
What About Port

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#596]
why not application put his self to allows port in firewall ?

**Comment by UnamSanctam** [comment]
Well it gets injected into explorer.exe or whatever else you choose so at least in my tests even if you add those to allowed programs it doesn't really do anything. But usually on the majority of computers you don't even need to allow it in the first place, and if you do then you can just use a pool (or xmrig-proxy) with port 443 or 80.

**Comment by tarekxxx** [comment]
yea bro i understand you ever told me in pool who allow this ports but my problem still in nanopool because my payout nnot until now not reach 0.11
so it's ok just was ask for like options in program 

bythe way Bro you did great work in last version Full respect

**Comment by UnamSanctam** [comment]
Thank you, yeah I've been considering some option like that but haven't figured out a good way to do it so it's not a bad idea.

**Comment by golxd** [comment]
> Thank you, and yeah I've been considering some option like that but haven't figured out a good way to do it but it's not a bad idea.

I agree, latest version is good. tell pls, is there a list somewhere applications for "Kill Targets"

**Comment by UnamSanctam** [comment]
> I agree, latest version is good. tell pls, is there a list somewhere applications for "Kill Targets"

There are some user submitted lists/programs here: https://github.com/UnamSanctam/SilentCryptoMiner/discussions/28
