### ISSUE TITLE
Rootkit option may be breaking build?

### ISSUE THREAD

**Issue by manves** [UnamSanctam/SilentCryptoMiner#6]
Hello just testing this out. Does the rootkit feature hide the processes from even appearing? I run the file as admin and after 15 sec it just ends the process as far as I can tell. Is this what it is supposed to do?

**Comment by UnamSanctam** [comment]
Yes the rootkit completely hides the processes, it would definitely look like they were ended although they would still be running.

**Comment by manves** [comment]
nvm I read the wiki

**Comment by manves** [comment]
Thank you I will close this
