### ISSUE TITLE
Raptoreum Mining

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#60]
Are you gonna add this coin?

**Comment by UnamSanctam** [comment]
No not really, I don't think the huge amount of time required is worth it.

**Comment by Brainshot** [comment]
> 
> 
> No not really, I don't think the huge amount of time required is worth it.

Huge amount of time? 

But raptoreum is going up and mining it is more profitable right now

**Comment by UnamSanctam** [comment]
I will have to code an implementation of the algorithm and everything else. I guess it would easily take 100 hours, and if more people will start to mine it then the mining rewards will also go down (of course).

**Comment by Brainshot** [comment]
> 
> 
> I will have to code an implementation of the algorithm and everything else. I guess it would easily take 100 hours, and if more people will start to mine it then the mining rewards will also go down (of course).

So wait if people from monero switch to RTM, and i am still mining monero i will profit more?

**Comment by UnamSanctam** [comment]
If people switch to RTM then the difficulty will go up and thus the amount you get from your hashrate becomes lower.

**Comment by Brainshot** [comment]
> 
> 
> If people switch to RTM then the difficulty will go up and thus the amount you get from your hashrate becomes lower.

what about mining rewards

**Comment by UnamSanctam** [comment]
The block rewards stay the same, but if the difficulty increases (increases with the total hashrate of miners) then your chance of finding a block becomes lower, and thus the amount you earn for your hashrate becomes lower.

**Comment by Brainshot** [comment]
> 
> 
> The block rewards stay the same, but if the difficulty increases (increases with the total hashrate of miners) then your chance of finding a block becomes lower, and thus the amount you earn for your hashrate becomes lower.

Please consider making a ghostrider algorithm, but anyways i still respect what you have to say.

Just wish you made it

**Comment by UnamSanctam** [comment]
Sure I can consider it, though it would probably take maybe a month or so to implement it if I decide to.

**Comment by Brainshot** [comment]
> 
> 
> Sure I can consider it, though it would probably take maybe a month or so to implement it if I decide to.

I can wait a month no problem.
