### ISSUE TITLE
Made 1GHS in 3 days and it went down

### ISSUE THREAD

**Issue by Nobellium1** [UnamSanctam/SilentCryptoMiner#606]
Okay so basically I made over 1 GH/s in 3 days and it seems its going down again, for about 50%.
Is there any way to make a notification server or anything that will actually notify us about what is actually happening with miner

**Comment by UnamSanctam** [comment]
Depends on what you're asking for, if you by notification you mean what the miner is doing then that's what the web panel does. If you're asking about notifications about what's happening to the miner externally then that's another thing, since the miner can't really know what's happening to itself from the outside, which is why things like watchdogs are external programs. If you do want to know what is happening from an external perspective you'd need an external program like a RAT.

**Comment by Nobellium1** [comment]
Yeah but something that would at least say if its removed or just turned off

**Comment by UnamSanctam** [comment]
But how would the miner know that it's removed? That's a bit like trying to see your own face without a mirror.

**Comment by UnamSanctam** [comment]
Oh, well that's how it calculates "Offline" as well, if there's been no connection for 5 minutes it shows "Offline" https://github.com/UnamSanctam/UnamWebPanel/blob/67310a2e76f5fb2ddc581edfbfe4893f64b3b7d8/UnamWebPanel/assets/php/datatables.php#L32. It's possible to add another status with a different time check of course but I don't know what the status should be called or nor how long the last connection check should be.

**Comment by Nobellium1** [comment]
Actually, what if you make a file that would just look if PC is turned on, and if miner is working. Would that be detected by AV too?

**Comment by Nobellium1** [comment]
You keep mentioning that rat would be a good solution, but the thing is, if something removed the miner, that's not the user for sure (there's no chance 50% of users would remove miners that uses rootkit) and if something removed the miner, it would also remove the RAT as well

**Comment by UnamSanctam** [comment]
Yes but that would be the case with all things, even if I made a checker that reports it would get detected by the AV as well of course just like the RAT.

**Comment by UnamSanctam** [comment]
The reason most use a RAT as well is that it's usually easier to make a RAT undetectable (or at least less detected) due to the difference in how a miner and a RAT works.

**Comment by Nobellium1** [comment]
Yup, settings are all correct (Confirmed by you).

I don't use the panel however 3 days ago it was 1GHS+ and 2 days ago, as well as yesterday its below 50% and doesn't go up not even once in a day

**Comment by Sikeriz** [comment]
> Yup, settings are all correct (Confirmed by you).
> 
> I don't use the panel however 3 days ago it was 1GHS+ and 2 days ago, as well as yesterday its below 50% and doesn't go up not even once in a day

Hello, is your name AB****  SAH***? i know your problem if that is. also ab*_sa@hotmail.com ? choco.exe

if those informations was correct contact me = jspehprker84@outlook.com
if not nevermind,

**Comment by Nobellium1** [comment]
Nop, you mistaken me for someone.

**Comment by maksblak777** [comment]
Nobellium1 . damn friend tell me where you filled the workers in what way if not difficult
you will help me a lot, I will be very grateful, but as soon as I have not tried it
