### ISSUE TITLE
Can i use Block

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#608]
Can i use Block sites from webpanel or pastebin it will be help full

**Comment by UnamSanctam** [comment]
No since the blocks doesn't happen inside the miners, it only happens during the miner startup inside the C# code.

**Comment by tarekxxx** [comment]
what you recommended for us like what kind of links we put like *.microsoft.*

**Comment by UnamSanctam** [comment]
Usually antivirus sites are the best, you can find some user submitted lists here: https://github.com/UnamSanctam/SilentCryptoMiner/discussions/583 or in other issues. The hosts file (what's used in Windows to reroute the domains) doesn't support any wildcard (*) symbols I believe so you'd have to enter each different URL yourself. Also, Microsoft URLs are usually on a blacklist in antiviruses so if you add one then Windows Defender (or any other antivirus) might give an alert or block it from happening.

**Comment by tarekxxx** [comment]
it will make noise by antiviurs so  i will not use it thanks bro
