### ISSUE TITLE
Detection Autorun

### ISSUE THREAD

**Issue by Zem0rt** [UnamSanctam/SilentCryptoMiner#610]
hello👋.  I noticed After infection and reboot, the virus tries to start, and a window pops up about the launch of the virus. And the user may suspect something that he is infected with something.

Photo warning:
![main](https://user-images.githubusercontent.com/99068726/163011883-7a626d0d-04ca-4533-9d44-72c2a2dd99cf.png)
(I did something and now I don’t have it, but I forgot to take a picture. This is a sample.)
OS testing: Window Server 2008 R2 Standard (build 7601: SP1)
End.

**Comment by UnamSanctam** [comment]
No that's not the installed miner, as you can see from the file path.
