### ISSUE TITLE
remote raw

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentCryptoMiner#612]
I only know pastebin, what other site can i use?

**Comment by UnamSanctam** [comment]
There are many, rentry, ghostbin and maybe pastee (from what people have told me they use). I'm not 100% that you can edit your pastes on the last two so it's best to test it first. You can just search for pastebin alternatives on Google and find many.

**Comment by golxd** [comment]
(_google translate_), interesting, if i use together xmr and eth miner, I can in one miner use settings "Kill target" "stealth target"
or must be specified in xmr and eth. or doesn't matter?

**Comment by UnamSanctam** [comment]
Yes you can have multiple backups with a comma, and you should specify "Stealth Targets" at least in both miners, usually ETH miners want more of them (for example games). Technically you only need "Kill Targets" in one miner (best to use in the XMR miner since that one should always be running).
