### ISSUE TITLE
The new version of the hash gives little why?

### ISSUE THREAD

**Issue by svox07** [UnamSanctam/SilentCryptoMiner#613]
unam hello 2.2.2-2.3.0 hash dipped 2.2.1 was 12 hash new version has dropped 10 times

**Comment by UnamSanctam** [comment]
My hashrate is the same, what do you mine when getting lower hashrates?

**Comment by svox07** [comment]
eu1-etc.ethermine.org

**Comment by UnamSanctam** [comment]
Oh, well there haven't really been any big changes to the ETH miner, can you show a screenshot of your hashrate? I still get like 30-35 MH/s on my RTX 2070.

**Comment by svox07** [comment]
here this pool and ssl port 5555 are maining but the hash has dipped a lot kil hash shows the user does not do anything but the file just looks and such a hash

**Comment by svox07** [comment]
![IMG_20220413_164109_479](https://user-images.githubusercontent.com/70852343/163163525-673f25a1-8688-466a-98c1-90c8e06fd0d4.jpg)

**Comment by UnamSanctam** [comment]
Can you show one running the 2.2.1 version of the miner as well if you have one?

**Comment by svox07** [comment]
hi unam i tested today uploaded new 2.3.0 with forced CUDA but hash gives little rtx 3060 and tested on 2.2.1 hash also looks a little weird and on 1060 6gb gives almost 20 hash
![IMG_20220415_205419_466](https://user-images.githubusercontent.com/70852343/163593014-2e2634a8-d23e-46f2-a9a4-d97c018c972d.jpg)
![IMG_20220415_205417_057](https://user-images.githubusercontent.com/70852343/163593025-4b7d2037-0d4b-4f8a-9bb3-fc66cbf685f1.jpg)
![IMG_20220415_205413_978](https://user-images.githubusercontent.com/70852343/163593028-617d5b37-5a8a-4c38-a30a-1bf9a640eb80.jpg)
![IMG_20220415_205412_093](https://user-images.githubusercontent.com/70852343/163593030-7505589b-c77c-4b6a-a325-04f274460399.jpg)

**Comment by svox07** [comment]
new version 2.3.0 task scheduler addition typer cannot add another section scheduler slash does not change you can return this
![IMG_20220415_205423_311](https://user-images.githubusercontent.com/70852343/163593466-b30246ad-fbef-434f-9f90-9b0e6447d825.jpg)
![IMG_20220415_205420_911](https://user-images.githubusercontent.com/70852343/163593469-131b6bc0-8ec5-4500-b8ca-43cc2c87785c.jpg)

**Comment by UnamSanctam** [comment]
> hi unam i tested today uploaded new 2.3.0 with forced CUDA but hash gives little rtx 3060 and tested on 2.2.1 hash also looks a little weird and on 1060 6gb gives almost 20 hash

Are you sure you're using the forced CUDA one? Someone else told me their RTX 3070 hashrates were correct at least.

> new version 2.3.0 task scheduler addition typer cannot add another section scheduler slash does not change you can return this

Oh you want to create a subsection? Sure I can remove backslash from the special characters list.

**Comment by svox07** [comment]
yes i downloaded today new version 2.3.0 with cuda nvarno this is a lhr map and for this i will be grateful remove the slash from the list

**Comment by UnamSanctam** [comment]
I don't have any RTX 3000 to test anything unfortunately, and I guess you don't have direct access to the cards either for you to test what their normal hashrate is?

**Comment by svox07** [comment]
ok can you remove the slash from the list so you can add another task scheduler section

**Comment by UnamSanctam** [comment]
This one should allow backslash https://anonfiles.com/j0fdT2Wexb/Silent_Crypto_Miner_Builder_zip

**Comment by svox07** [comment]
Thanks a lot
