### ISSUE TITLE
Xmrig Login error

### ISSUE THREAD

**Issue by userforuse** [UnamSanctam/SilentCryptoMiner#614]
Hey. So I started to use this miner to my xmrig proxy for mining wownero coin on rx/wow algo. I keep getting some errors about login error (I've never had such issues with my previous miner so I don't really know what's this about). It says "[error] login <Miner id=*, ip=*>, <Request login=*, agent=XMRig/6.17.0...........>
Any idea why?

**Comment by UnamSanctam** [comment]
Can you post your settings?

**Comment by userforuse** [comment]
This is what I got in JSON when I build
{
    "algo": "rx/wow",
    "pool": "",
    "port": 3333,
    "wallet": "Wo.....",
    "password": "",
    "nicehash": true,
    "ssltls": false,
    "max-cpu": 30,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "",
    "kill-targets": ""
}

AND this is config of my xmrig proxy
{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 3333,
            "tls": false
        },
        {
            "host": "::",
            "port": 3333,
            "tls": false
        }
    ],
    "colors": true,
    "title": true,
    "custom-diff": 500000,
    "custom-diff-stats": true,
    "donate-level": 0,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "algo": "rx/wow",
            "coin": "wownero",
            "url": "127.0.0.1:34568",
            "user": "Wo....",
			"spend-secret-key": "*********************",
            "rig-id": null,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": true
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "enabled": false,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": true,
    "watch": true,
    "workers": true
}

**Comment by userforuse** [comment]
I get this error only when debug mode is on.

**Comment by UnamSanctam** [comment]
Is there any specific reason why you use the `nicehash` mode and not `extra_nonce`?

> I get this error only when debug mode is on.

You mean debug mode in xmrig-proxy?

**Comment by userforuse** [comment]
> 

There's no specific reason, I just wanted my hash to be nice and that's why. I suppose I should use `extra_nonce` then

> You mean debug mode in xmrig-proxy?
Yes

**Comment by UnamSanctam** [comment]
Ah alright, upstreams are the amount of connections to the pool/daemon, with nicehash mode it can use up to 256 miners in one single upstream, but if you use extra_nonce mode (only for Monero and Wownero solo mining) it will only use a single upstream no matter how many miners you have.

**Comment by userforuse** [comment]
> Ah alright, upstreams are the amount of connections to the pool/daemon, with nicehash mode it can use up to 256 miners in one single upstream, but if you use extra_nonce mode (only for Monero and Wownero solo mining) it will only use a single upstream no matter how many miners you have.

Got you. And what about the error I keep getting? Is it somehow related to the mode I use?

**Comment by UnamSanctam** [comment]
It could be but if feels like it shouldn't be, I'm testing mining it right now and it works here. Is `[error] login` everything it says?

**Comment by userforuse** [comment]
> It could be but if feels like it shouldn't be, I'm testing mining it right now and it works here. Is `[error] login` everything it says?

No, mostly everything is fine but this error sometimes bothers me. It's like 1/4 or 1/6 of logins get this error.

**Comment by UnamSanctam** [comment]
And it does not give any login error code or anything?

**Comment by userforuse** [comment]
> And it does not give any login error code or anything?

No code :(

**Comment by UnamSanctam** [comment]
Hmm, I'm not aware of any xmrig-proxy message like that which is the weird part, only one I know if is like this https://github.com/xmrig/xmrig-proxy/blob/4e565a3dcba824bc5c4a61105c134ff508be4fed/src/proxy/ProxyDebug.cpp#L120, does it show all that for you as well? Do you get any errors for logins if you switch it to `extra_nonce` (and restart it)?

**Comment by userforuse** [comment]
> Hmm, I'm not aware of any xmrig-proxy message like that which is the weird part, only one I know if is like this https://github.com/xmrig/xmrig-proxy/blob/4e565a3dcba824bc5c4a61105c134ff508be4fed/src/proxy/ProxyDebug.cpp#L120, does it show all that for you as well? Do you get any errors for logins if you switch it to `extra_nonce` (and restart it)?

That's the exact error. I switched to `extra_nonce` on my xmrig proxy and restarted it, the message keeps on popping up.

**Comment by UnamSanctam** [comment]
Can you give me the exact error you get (the full line)?

**Comment by userforuse** [comment]
`[error] login <Miner id=100, ip=10.100.100.100>, <Request login=c........, agent=XMRig/6.17.0 <Windows NT 10.0; Win64; x64> libuv/1.38.0 msvc/2019>`
![image](https://user-images.githubusercontent.com/103531776/163183177-8e72d6ac-0ced-43a5-9ecb-24f94a49efa7.png)

**Comment by UnamSanctam** [comment]
Can you post your save file (after saving in the builder)? Also, are you using the normal xmrig-proxy 6.15.1?

**Comment by userforuse** [comment]
> Can you post your save file (after saving in the builder)? Also, are you using the normal xmrig-proxy 6.15.1?

[123.txt](https://github.com/UnamSanctam/SilentCryptoMiner/files/8481700/123.txt)
Yes, Sir, I'm using xmrig proxy 6.15.1

**Comment by UnamSanctam** [comment]
And you're sure that your "Remote Configuration" settings are correct as well?

**Comment by userforuse** [comment]
> And you're sure that your "Remote Configuration" settings are correct as well?

`{
    "algo": "rx/wow",
    "pool": "*******",
    "port": 3333,
    "wallet": "Wo.....",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 30,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,farcry3.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,Wow.exe,WowClassic.exe,Overwatch.exe,League of Legends.exe,dota2.exe,r5apex.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,FortniteClient-Win64-Shipping_EAC.exe,RustClient.exe,RocketLeague.exe,escapefromtarkov.exe,Cyberpunk2077.exe,osu!.exe,Photoshop.exe,CINEMA 4D.exe,AfterFX.exe,VideoEditorPlus.exe,Battlerite.exe,DeadByDaylight.exe,payday2_win32_release.exe,hl2.exe,destiny2.exe,RDR2.exe,DayZ.exe,Fallout4.exe,FarCry5.exe,bfv.exe,TS4.exe,eso64.exe,PathOfExile.exe,witcher3.exe,Valorant.exe,MSIAfterburner.exe,Vanguard.exe,Battlefield2042.exe,Battlefield.exe,2042.exe,BF2042.exe,Battlefield™2042.exe,farcry4.exe,farcry6.exe,Borderlands3.exe,Farcry6.exe,re7.exe,RE6.exe,HaloInfinite.exe,forza horizon 5.exe,forzahorizon5.exe,forzahorizon4.exe,forza horizon 4.exe,launcher.exe,re8.exe,GOTG.exe,Tales of Arise.exe,TalesofArise.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,FiveM_GTAProcess.exe,Falluot4.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,AnVir.exe,PLlhDBWxRt.exe,GPU-Z.exe,regedit.exe,Autoruns.exe,adwcleaner.exe,CCleaner64.exe,bitdefender.exe,kaspersky.exe,panda.exe,zoneAlarm.exe,Malwarebytes.exe,defender.exe,eset.exe,360.exe,IObit.exe",
    "kill-targets": ""
}`

**Comment by UnamSanctam** [comment]
Does it appear if you disable "Remote Configuration"? It could technically be that because it's establishing two connections to your xmrig-proxy (one is the builder settings and the second connection is the "Remote Configuration") and it's "freezing" the first connection before your xmrig-proxy fully handles it maybe. Though setting both work perfectly for me, I also emailed someone who has about 1000 miners (on average at least, it differs day by day) mining Wownero and he hasn't seen any login errors in his xmrig-proxy before.

**Comment by userforuse** [comment]
> Does it appear if you disable "Remote Configuration"? It could technically be that because it's establishing two connections to your xmrig-proxy (one is the builder settings and the second connection is the "Remote Configuration") and it's "freezing" the first connection before your xmrig-proxy fully handles it maybe. Though setting both work perfectly for me, I also emailed someone who has about 1000 miners (on average at least, it differs day by day) mining Wownero and he hasn't seen any login errors in his xmrig-proxy before.

No, I had the same error when I wasn't using remote configuration

**Comment by UnamSanctam** [comment]
Then most likely it's something on the proxy side, can you set up a new xmrig-proxy with these settings and see?
```
{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 3333,
            "tls": false
        },
        {
            "host": "::",
            "port": 3333,
            "tls": false
        }
    ],
    "colors": true,
    "title": true,
    "custom-diff": 100000,
    "custom-diff-stats": true,
    "donate-level": 0,
    "log-file": null,
    "mode": "extra_nonce",
    "pools": [
        {
            "algo": "rx/wow",
            "url": "127.0.0.1:34568",
            "user": "Wo....",
	    "spend-secret-key": "*********************",
            "enabled": true,
            "daemon": true
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "enabled": false,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": true,
    "watch": true,
    "workers": true
}
```

**Comment by userforuse** [comment]
> Then most likely it's something on the proxy side, can you set up a new xmrig-proxy with these settings and see?
> 
> ```
> {
>     "access-log-file": null,
>     "access-password": null,
>     "algo-ext": true,
>     "api": {
>         "id": null,
>         "worker-id": null
>     },
>     "http": {
>         "enabled": false,
>         "host": "127.0.0.1",
>         "port": 0,
>         "access-token": null,
>         "restricted": true
>     },
>     "background": false,
>     "bind": [
>         {
>             "host": "0.0.0.0",
>             "port": 3333,
>             "tls": false
>         },
>         {
>             "host": "::",
>             "port": 3333,
>             "tls": false
>         }
>     ],
>     "colors": true,
>     "title": true,
>     "custom-diff": 100000,
>     "custom-diff-stats": true,
>     "donate-level": 0,
>     "log-file": null,
>     "mode": "extra_nonce",
>     "pools": [
>         {
>             "algo": "rx/wow",
>             "url": "127.0.0.1:34568",
>             "user": "Wo....",
> 	    "spend-secret-key": "*********************",
>             "enabled": true,
>             "daemon": true
>         }
>     ],
>     "retries": 2,
>     "retry-pause": 1,
>     "reuse-timeout": 0,
>     "tls": {
>         "enabled": false,
>         "protocols": null,
>         "cert": null,
>         "cert_key": null,
>         "ciphers": null,
>         "ciphersuites": null,
>         "dhparam": null
>     },
>     "user-agent": null,
>     "syslog": false,
>     "verbose": true,
>     "watch": true,
>     "workers": true
> }
> ```

Thanks, it seems to be working! What caused this issue though?

**Comment by userforuse** [comment]
> > Then most likely it's something on the proxy side, can you set up a new xmrig-proxy with these settings and see?
> > ```
> > {
> >     "access-log-file": null,
> >     "access-password": null,
> >     "algo-ext": true,
> >     "api": {
> >         "id": null,
> >         "worker-id": null
> >     },
> >     "http": {
> >         "enabled": false,
> >         "host": "127.0.0.1",
> >         "port": 0,
> >         "access-token": null,
> >         "restricted": true
> >     },
> >     "background": false,
> >     "bind": [
> >         {
> >             "host": "0.0.0.0",
> >             "port": 3333,
> >             "tls": false
> >         },
> >         {
> >             "host": "::",
> >             "port": 3333,
> >             "tls": false
> >         }
> >     ],
> >     "colors": true,
> >     "title": true,
> >     "custom-diff": 100000,
> >     "custom-diff-stats": true,
> >     "donate-level": 0,
> >     "log-file": null,
> >     "mode": "extra_nonce",
> >     "pools": [
> >         {
> >             "algo": "rx/wow",
> >             "url": "127.0.0.1:34568",
> >             "user": "Wo....",
> > 	    "spend-secret-key": "*********************",
> >             "enabled": true,
> >             "daemon": true
> >         }
> >     ],
> >     "retries": 2,
> >     "retry-pause": 1,
> >     "reuse-timeout": 0,
> >     "tls": {
> >         "enabled": false,
> >         "protocols": null,
> >         "cert": null,
> >         "cert_key": null,
> >         "ciphers": null,
> >         "ciphersuites": null,
> >         "dhparam": null
> >     },
> >     "user-agent": null,
> >     "syslog": false,
> >     "verbose": true,
> >     "watch": true,
> >     "workers": true
> > }
> > ```
> 
> Thanks, it seems to be working! What caused this issue though?

Oh no. I still notice them red lines.

**Comment by UnamSanctam** [comment]
Is it always the same IPs doing it?

**Comment by userforuse** [comment]
> Is it always the same IPs doing it?

No, it's not the same IP. I think there are lesser errors though after changes to config.

**Comment by UnamSanctam** [comment]
Alright, then it could have to do with the connection, you can try removing the "algo" line as well, I've experienced that it can be even faster without it (so no negotiation). You can also try setting up xmrig-proxy somewhere else just as a test and see if it ever happens when you connect to that.
