### ISSUE TITLE
Hashrate issue

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#615]
The issue is the hashrate is stuck at 0 sometimes on my webpanel and sometimes it mining and shows mhs, same thing with other miners.

**Comment by Brainshot** [comment]
This cant be because of out of ram, if it was then it would show on panel

**Comment by Brainshot** [comment]
![fwqdqx](https://user-images.githubusercontent.com/93741208/163203310-38bc4090-1bdb-47a4-baef-4069df8da49a.PNG)


GPU NVIDIA GeForce RTX 3060 Ti

**Comment by UnamSanctam** [comment]
Well there are three possibilities I can think of really, 1) it has lost connection to the pool in some manner, 2) most of the GPU is being used by some other program so the miner yields to it (because otherwise it would lag), 3) it has run out of VRAM but not "officially" (GPUs aren't really very straight forward).

**Comment by Brainshot** [comment]
> Well there are three possibilities I can think of really, 1) it has lost connection to the pool in some manner, 2) most of the GPU is being used by some other program so the miner yields to it (because otherwise it would lag), 3) it has run out of VRAM but not "officially" (GPUs aren't really very straight forward).

So he could be gaming?? i dont get it on my old miners i didnt have this issue with older version silent builder.

**Comment by UnamSanctam** [comment]
Yes he could be (he is idle so he could have a game open but be AFK), the ETH/ETC mining itself hasn't really changed anything since version 2.1.0 (or even 2.0.0). Does the hashrate go up sometimes (that's what it sounded like) to normal? in that case most likely the GPU is being used by something.

**Comment by Brainshot** [comment]
> Yes he could be (he is idle so he could have a game open but be AFK), the ETH/ETC mining itself hasn't really changed anything since version 2.1.0 (or even 2.0.0). Does the hashrate go up sometimes (that's what it sounded like) to normal? in that case most likely the GPU is being used by something.

Just had another question in my mind, when someone is for example playing a video game that uses the GPU pretty well, will the miner just wait till the person shuts the game off? basically not mine but still be active.

**Comment by UnamSanctam** [comment]
Unless the game is in the "Stealth Targets" then it will still "mine" so the VRAM will still be used, but the miner will yield the GPU usage to whatever else needs it. Then when they close the game it would go up again since it doesn't need to yield to anything.

**Comment by Brainshot** [comment]
> Unless the game is in the "Stealth Targets" then it will still "mine" so the VRAM will still be used, but the miner will yield the GPU usage to whatever else needs it. Then when they close the game it would go up again since it doesn't need to yield to anything.

So its possible to have 0mhs when they are gaming for example? because it gets back to normal and sometimes gets to 0.

**Comment by UnamSanctam** [comment]
Yes if they play something demanding like CoD: Warzone (just an example) that usually uses 100% of the GPU then it's possible to go to 0 H/s.

**Comment by Brainshot** [comment]
> Yes if they play something demanding like CoD: Warzone (just an example) that usually uses 100% of the GPU then it's possible to go to 0 H/s.

Ok thank you so much for answering
