### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Driadasa** [UnamSanctam/SilentCryptoMiner#618]
I put the old settings in the new version, for the sake of testing, but they do not work. Crypt not use
<img width="1083" alt="Screenshot_1" src="https://user-images.githubusercontent.com/86801280/163330521-b177a7a0-5c1a-4426-bf87-b71cfca2cf4d.png">
d

**Comment by Driadasa** [comment]
What could be the problem?

**Comment by Zeevsq1** [comment]
Run as Administrator - ON

**Comment by UnamSanctam** [comment]
Yeah an only those tabs doesn't say much the more important ones, the more important tabs are "Startup" and then all the miner settings.

**Comment by Driadasa** [comment]
> Yeah an only those tabs doesn't say much the more important ones, the more important tabs are "Startup" and then all the miner settings.

Old settings not working?

**Comment by Driadasa** [comment]
> Run as Administrator - ON

lol

**Comment by Driadasa** [comment]
It used to be normal, now the hashrate grows very weakly and disappears

**Comment by Driadasa** [comment]
> Ну, любые старые настройки должны работать и в новом, конечно, когда "раньше было нормально"? Версия 2.1.0?

2 0 0 - 2 1 0

The checker does not see the miner, I showed the settings

**Comment by UnamSanctam** [comment]
Those are only 10% of the settings. It looks like it can't install (since the watchdog isn't running). You'd probably have to post the save file for the best help.
