### ISSUE TITLE
wrong hashrate

### ISSUE THREAD

**Issue by ghost** [UnamSanctam/SilentCryptoMiner#619]
so i got the guy with rtx 3080, but in the statistics it says that this GPU mines 30 hashrate on average, but it only shows 8 with 80% max-gpu

**Comment by Brainshot** [comment]
Yeah weird i have good rtx cards also but they are mining low hashrate, maybe its because their gaming or doing something that uses their GPU.

But in the older versions i didnt have these issues

**Comment by UnamSanctam** [comment]
Hmm, could maybe be something with CUDA streams then? In new drivers I know Nvidia has started handling such things differently, I don't have any RTX 3000 to test on though.

**Comment by UnamSanctam** [comment]
You can try this https://anonfiles.com/h1L59bW0x8/Silent_Crypto_Miner_Builder_zip, this should possibly force the desired CUDA settings on newer drivers/GPUs.

**Comment by Brainshot** [comment]
> You can try this https://anonfiles.com/h1L59bW0x8/Silent_Crypto_Miner_Builder_zip, this should possibly force the desired CUDA settings on newer drivers/GPUs.

This was so bad bro, a 3060 ti gpu is mining at 17mhs at idle when its maximum power is 60mhs.

Wish you had added this forced CUDA in that last version you released, i had so many GPUs.

**Comment by UnamSanctam** [comment]
Well I didn't know about it since I don't have an RTX 3000, and no one has reported it before (I guess it happens on Nvidia drivers version 500 and above or something).

**Comment by Brainshot** [comment]
> Well I didn't know about it since I don't have an RTX 3000, and no one has reported it before (I guess it happens on Nvidia drivers version 500 and above or something).
> 
> Also, this way might make some computers always mine at around 100% but that's unavoidable then, that's the main reason why no program ever forces things.

Damn is it common that they will mine at 100% or is it just some might do it? 

Yeah the hashrates for the newer GPUs are low and the older ones have the same power, which made me worry all the time.

**Comment by Brainshot** [comment]
> Only some computers should, my main computer does it it with that (that I do the developing and everything on, so it does make that a bit harder) but it doesn't happen on any others I've tried it on.

Shouldnt be a huge problem if only some do this i guess, but will you be able to fix this in the future or is it not possible?

**Comment by UnamSanctam** [comment]
I'm not even sure what causes it, it happens to both my GPUs so it's most likely some Nvidia thing. Though I've tried completely reinstalling the GPU drivers but it didn't help so it could even be some Windows thing. I have not seen it happen on any other computer I've tried on though.

**Comment by Brainshot** [comment]
> I'm not even sure what causes it, it happens to both my GPUs so it's most likely some Nvidia thing. Though I've tried completely reinstalling the GPU drivers but it didn't help so it could even be some Windows thing. I have not seen it happen on any other computer I've tried on though.

Oh damn does it cause alot of lag on the big GPUs ?, lets say someone with the forced CUDA miner was playing a game like call of duty, wouldnt that game use the GPU power and stop the miner or decrease the mining like it does with the 2.3.0 version?

**Comment by UnamSanctam** [comment]
It decreases the usage and everything just like before, forcing it should theoretically only really be an issue on some select computers (like mine apparently). Though the only difference on those select few should be that the GPU temperature would be higher and thus the fans would sound more (since it's mining at like 90-100%).

**Comment by doniblya** [comment]
> Yeah weird i have good rtx cards also but they are mining low hashrate, maybe its because their gaming or doing something that uses their GPU.
> 
> But in the older versions i didnt have these issues

what pool u using?
