### ISSUE TITLE
Built in Obfuscation

### ISSUE THREAD

**Issue by pebu1337** [UnamSanctam/SilentCryptoMiner#62]
Will there ever be a built in obfuscator to try and combat the high detections by virustotal?

**Comment by UnamSanctam** [comment]
It already does some obfuscation and always has, the problem is that so many use it that it becomes detected. So if any full featured obfuscator ever gets built-in then if wouldn't help much due to that, which is why I leave the obfuscation/crypting part up to the user.

**Comment by masterjek** [comment]
Virustotal uses virtual machines to launch an application that has come to them. And therefore it is very difficult to bypass it, since it scans not only the file in statics, but also in dynamics. Therefore, it is better not to throw the miner there once again for scan.
