### ISSUE TITLE
Stub Size ? 

### ISSUE THREAD

**Issue by Ninja133** [UnamSanctam/SilentCryptoMiner#620]
is there is way to make the Stub size less than 4MB 
like 1 MB

**Comment by UnamSanctam** [comment]
Not really, that's the size of miners. You could use something like a downloader though.

**Comment by t4tai** [comment]
what are the minimum  CPU or GPU or PC config and RAM requirements, please?
Thank you

**Comment by UnamSanctam** [comment]
Depends fully on what algorithm/coin you're mining.
