### ISSUE TITLE
etc pool

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentCryptoMiner#621]
what pool recommend for mining etc? i like nanopool, but etc doesn't show workers (its problem). Need good pool who doesn't ban

**Comment by UnamSanctam** [comment]
You can try 2miners, it's the only real other alternative I know of (that doesn't have some other problems).

**Comment by golxd** [comment]
thx

**Comment by golxd** [comment]
sry) 1 question, SSL or standart?

**Comment by UnamSanctam** [comment]
It's better to use SSL, so set it to "stratums" and use the SSL port.
