### ISSUE TITLE
Unofficial Telegram Community

### ISSUE THREAD

**Issue by Redkits02** [UnamSanctam/SilentCryptoMiner#622]
Unofficial telegram server for Unam's miner / silent mining:
https://t.me/MinersCommunity

Для русских / For russians:
https://t.me/MinersCommunityRu

Check the wiki.txt in the pinned messages before posting, it contains some basic info to get started ( work in progress) hopefully answering most basic questions about mining.

If you have any other questions feel free to @ me (@Ankits12345) or talk with the community

the community is growing, but due to the anonymous nature of it, don't trust any member offering you services not verified by the admins/always ask the admins.

**Comment by bvi32** [comment]
Hello, telegram as a means of communication cannot be considered, due to its full control by the FBI. XMPP or Matrix is better suited for your purposes

**Comment by hidden-69** [comment]
Isn't Telegram Russian?

**Comment by Redkits02** [comment]
> Isn't Telegram Russian?

yes and no, it is made by a russian, tho one that butts heads with the russian goverment misinformation and propoganda, it as was made as a free anonymous messaging platform to avoid goverment censorship, if you'd like to learn more, just google it

**Comment by Redkits02** [comment]
> Hello, telegram as a means of communication cannot be considered, due to its full control by the FBI. XMPP or Matrix is better suited for your purposes

''Telegram
Telegram is also highly secure. The FBI can’t obtain any message content or contact information. Telegram may give them IP addresses and phone numbers, but only for confirmed terrorist investigations.''

with that said,  just use a vpn (i suggest mullvad) when using telegram and use a phone number from sms-activate.org
for bonus points, do that all inside a dedicated virtual machine

**Comment by bvi32** [comment]
Hi, reading your reasoning is funny. If "something" requires a phone number, then this "something" cannot be secure. Please read your answer again. You in it, in all seriousness, suggest spending money and using virtual machines, instead of just using a secure messaging tool.

>Telegram is also highly secure. The FBI can’t obtain any message content or contact information

Don't take me for a fool. Do you seriously think that people who have full control of the server can't get what they need? I don't know who told you this nonsense, you should think about whether you can trust him in the future.

**Comment by Redkits02** [comment]
> Hi, reading your reasoning is funny. If "something" requires a phone number, then this "something" cannot be secure. Please read your answer again. You in it, in all seriousness, suggest spending money and using virtual machines, instead of just using a secure messaging tool.
> 
> > Telegram is also highly secure. The FBI can’t obtain any message content or contact information
> 
> Don't take me for a fool. Do you seriously think that people who have full control of the server can't get what they need? I don't know who told you this nonsense, you should think about whether you can trust him in the future.

i'm just saying, if you're worried about that, use a vpn (which you're gonna use anyway if u plan doing mining), create a virtual machine ( which is free btw ) and buy a phone number (for 0.10$) to activate telegram with on that virtual machine.
everyone uses telegram, why use something obscure if telegram already works and can be 100% anonymous with only the most basic precautions.

and on top of that, if you're gonna be serious about silent mining, you're gonna end spending money on a crypter anyways, it just sounds like you're here:
1. for the sake of arguing about a problem when there isn't one trying to push your argument like some web3 elitist
2. a kid who can't afford a few $ for the most basic setup you should already be using anyways since you're so worried about privacy

trying to argue that it requiring a phone = unsecure is just stupid when you can just buy one with crypto on sms-activate.org for 0.10$, thus rectifying that safety concern

and one last thing, sure, there are more privacy focused messaging apps, but you're overlooking 1 thing:

telegram is widely used, everyone in the scene has one, and programs we use often have webhooks that can report straight to telegram, there's a ton of communities like that there, bots to use, etc AND all the safety concerns can easily be fixed with things you'll be using anyway

Mullvad vpn
vmware
sms-activate.org
that's all you need, hope that answered your question, as well as anyone's who's thinking the same thing

**Comment by culatos** [comment]
Has the Telegram server been banned or removed? I can't seem to join it. Since I can't seem to find a working community server based around silent mining, I am thinking of creating my own using element.io (a Matrix client). This should be anonymous and I am very certain it will not get banned or removed.
