### ISSUE TITLE
NOT IMPORTANT

### ISSUE THREAD

**Issue by A3ima** [UnamSanctam/SilentCryptoMiner#624]
does anyone know which file in the miner src holds the writing on the ui? im trying to change where it says Silent Crypto Miner Builder 2.3.0

**Comment by UnamSanctam** [comment]
It's the builder forms designer file
https://github.com/UnamSanctam/SilentCryptoMiner/blob/d10c7d9f40995caa3cddc38ad7c0b6548af36862/SilentCryptoMiner/Forms/Builder.Designer.cs#L154

**Comment by A3ima** [comment]
thanks
