### ISSUE TITLE
i got my VPS

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#626]
i make it usage 100% all the time and nothing starting like taskmanager or any stealth option opened
and hashrate keep down to 0% for 20 mins i dont know what problem i allow ports and stop defender and do everything right

and priority to webpanel unam or pastebin config ?
![Capture](https://user-images.githubusercontent.com/20240556/163595737-40a48e3f-310e-4caa-9d3b-023c495b6173.PNG)

**Comment by UnamSanctam** [comment]
Then it's usually because it cannot connect to the pool, the web panel has higher priority.

**Comment by tarekxxx** [comment]
there internet and i can ping nanopool its working not working but after 1 hour he keep 0H/s for 20 or 30 mins 
internet connection like you knew 1GB so there no request time out or something  there anything i can modifiy it ?
