### ISSUE TITLE
WD updates still working

### ISSUE THREAD

**Issue by Nobellium1** [UnamSanctam/SilentCryptoMiner#628]
Even tho I had enabled stuff to disable windows updates etc.. Windows defender still updated and removed many miners again.

**Comment by UnamSanctam** [comment]
Can you check if Windows Update is disabled on those? On all my computers I've tested it on Windows Update has completely stopped working unless you do something like a Windows repair and troubleshoot,

**Comment by Nobellium1** [comment]
Its not

**Comment by Nobellium1** [comment]
Basically, it was disabled (killed) by miner

**Comment by Nobellium1** [comment]
And NO repairs were ran or anything it just re-enabled itself

**Comment by Nobellium1** [comment]
![image](https://user-images.githubusercontent.com/96837088/163678672-e42f4242-6701-4cba-b57b-9f996f5caebf.png)
It also auto-checked for updates today

**Comment by Nobellium1** [comment]
That's on a friend's pc, and pic below is on my main PC where it was disabled too

**Comment by Nobellium1** [comment]
![image](https://user-images.githubusercontent.com/96837088/163678707-7fec620c-12a4-4389-977c-2228e20211b7.png)

**Comment by UnamSanctam** [comment]
Yes then it could've run a repair, they do that sometimes (which is also what I say in the wiki). I'm also experimenting with blocking Windows Update services in the firewall.

**Comment by Nobellium1** [comment]
It ran repair on all PCs at once probably

**Comment by Nobellium1** [comment]
Also noticed that even if windows updated, it didnt repair defender
![image](https://user-images.githubusercontent.com/96837088/163679049-608542fa-a6ea-42c5-9c5e-c7f1dc4495ba.png)

**Comment by Nobellium1** [comment]
So I think it might be worth having windows defender killer inside it

**Comment by UnamSanctam** [comment]
What I've been experimenting with is either to add firewall rules so that the processes can't contacts the internet, or that the "Watchdog" runs the disabling commands about every minute (though I don't really want to spam since the commands aren't "fast").

**Comment by Nobellium1** [comment]
Well you can add both and test em, Im sure both would work fine because even if first method breaks and process somehow contacts the internet, it would still run the command so yeah

**Comment by Sikeriz** [comment]
You say, you getting 400mhs daily.
and you crying for everyting..
thats unbelieveble.
