### ISSUE TITLE
Cool update!

### ISSUE THREAD

**Issue by FreeM1ne** [UnamSanctam/SilentCryptoMiner#629]
I hope there won't be too many mistakes.

**Comment by maksblak777** [comment]
oh you don’t want to give a percentage to the creator, how shameful for such labors and to act and ask, I would put a commission for such 99%

**Comment by Sikeriz** [comment]
You idiot, ask question which different account that you didnt try leech his application.
you made all those things, and you peek for his donation only little thing.
donate a little before asking him decode strings..

me? i made more than 100 usd donation. even there lot of application more cheaper.
because i made profit because of this guy.
fuck off or delete your repo before ask.

**Comment by FreeM1ne** [comment]
I just wanted to check the string for the presence of parameters that may affect the operation of the miner.

**Comment by FreeM1ne** [comment]
I appreciate what this person does and don't try to change the commission, etc.

**Comment by Sikeriz** [comment]
https://github.com/FreeM1ne/ring0/tree/main/inc
remove your question, this is so absurt. 
he will see and will be sad because of this,
dont try break his things.

we all own lot of thing to  his guy.

**Comment by Sikeriz** [comment]
i know this repo what means.

**Comment by Sikeriz** [comment]
remove your messages so im i.

**Comment by FreeM1ne** [comment]
This is what I tried to do remote setup earlier when it was in beta test

**Comment by Sikeriz** [comment]
when it was dont have REMOTE, its for only backup to donate.
and its only like %10

**Comment by Sikeriz** [comment]
and you tried to leech him, and i look your wallets empty.

**Comment by Sikeriz** [comment]
you can do what ever you can,
my point. if you doing those all things.
you can write his repo with this idiot account
have a nice day.

**Comment by Sikeriz** [comment]
close thread, edit your comment also
