### ISSUE TITLE
does not work on windows 11

### ISSUE THREAD

**Issue by gresmax** [UnamSanctam/SilentCryptoMiner#63]
explorer.exe - Application Error

Error starting application 0xc0000037b. To exit the application, click the "OK" button

**Comment by gresmax** [comment]
and Watchdog works

**Comment by UnamSanctam** [comment]
Hmm, it works fine in my Windows 11 VMs.

**Comment by gresmax** [comment]
Does it seem to me or do not understandable errors happen only to me?

**Comment by UnamSanctam** [comment]
Haha yeah it seems like it, that error usually means that it couldn't inject the miner but I haven't seen that happen before.
