### ISSUE TITLE
hashrate drop

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#630]
hashrate keep drop in same time even PC idle and no one touch it and even many PCs in same time i dont know why this happen this makes me getting crazy lol how and why keep do like this for 30 mins i think and sometimes 1 hr 1 PC or 2 PC drop in same time even idle no task manager totally idle
![Screenshot (82)](https://user-images.githubusercontent.com/20240556/163695115-fef4901c-6dd9-481b-a1cc-119c5d2e7cec.png)
in this  case stopped 3 PCS in same time

must 2 or 3 PC drop hashrate to 0 and keep doing like this until i restart PC then work fine after 5 or 8 hours repeat

**Comment by UnamSanctam** [comment]
What pool are you using? And what CPUs do those computers have?

**Comment by tarekxxx** [comment]
CPUS is AMD EPYC Processor (with IBPB) and pool is nanopool HTTPS

**Comment by UnamSanctam** [comment]
Those 0H/s are AMD EPYC processors as well?

**Comment by tarekxxx** [comment]
yea

**Comment by tarekxxx** [comment]
they keep idle but suddenly stop to 0 even idle

**Comment by UnamSanctam** [comment]
Usually the only reason for xmrig going to 0 H/s is, 1) losing connection to the pool, 2) all CPU cores being used by something else. The second alternative doesn't seem likely at all since they're AMD EPYC processors, and the first reason doesn't really seem too likely either. I'm guessing you don't have direct access to those computers to check? Are you able to save down the table data and send it here (if possible you can use one of those delete after download sites)? You can alternatively try another pool temporarily (create a new configuration in the "Configurations" tab and apply that to the 0 H/s miner).

**Comment by tarekxxx** [comment]
i have access in PC  what should i do what table data mean Configurations ?

**Comment by UnamSanctam** [comment]
If you have access to the PC then can you try downloading a normal xmrig (or use this [standard_xmrig.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8502636/standard_xmrig.zip), if you use this then run "start nanopool.bat" after extracting) to see if that works?

**Comment by tarekxxx** [comment]
![Screenshot (83)](https://user-images.githubusercontent.com/20240556/163741183-a5edf347-522b-424e-9c87-7b361feca9ec.png)

here result

**Comment by tarekxxx** [comment]
its keep working and stop even idle that's why i post not stable keep stop even idle and no one touch it maybe stuck for 30 mins or more

**Comment by UnamSanctam** [comment]
If you press the 'h' button in that console does it show any hashrate (since currently that screenshot doesn't show that)?

**Comment by tarekxxx** [comment]
and sometimes when i restart PC the miner not working mean not autostart up i dont see it in task manager in new build

**Comment by UnamSanctam** [comment]
Run the checker that was built with your miner to see if it's running, since it runs as System (if you have it enabled) it can be hard to find it.

**Comment by tarekxxx** [comment]
310 H/s

> If you press the 'h' button in that console does it show any hashrate (since currently that screenshot doesn't show that)?

**Comment by UnamSanctam** [comment]
It's because it's mining with one core and with no huge pages in your console there.

**Comment by tarekxxx** [comment]
i think

> Run the checker that was built with your miner to see if it's running, since it runs as System (if you have it enabled) it can be hard to find it.

yea when restart pc and when boot up i don t see miner getting start and dont know when this work because turn off line in webpanel 
![Screenshot (84)](https://user-images.githubusercontent.com/20240556/163742279-c3068f04-8c6a-4667-ac01-d0a8d409913c.png)

**Comment by tarekxxx** [comment]
> It's because it's mining with one core and with no huge pages in your console there.

so there wway to fix it ?

**Comment by UnamSanctam** [comment]
> i think
> 
> > Run the checker that was built with your miner to see if it's running, since it runs as System (if you have it enabled) it can be hard to find it.
> 
> yea when restart pc and when boot up i don t see miner getting start and dont know when this work because turn off line in webpanel ![Screenshot (84)](https://user-images.githubusercontent.com/20240556/163742279-c3068f04-8c6a-4667-ac01-d0a8d409913c.png)

In that screenshot the miner is running correctly at least.

> > It's because it's mining with one core and with no huge pages in your console there.
> 
> so there wway to fix it ?

That's only the test xmrig, the miner itself (SilentCryptoMiner) runs like normal with more cores and huge pages, that was only for a test.

You don't have Task Manager or anything like that open on the computers that have 0 H/s correct?

**Comment by tarekxxx** [comment]
> > i think
> > > Run the checker that was built with your miner to see if it's running, since it runs as System (if you have it enabled) it can be hard to find it.
> > 
> > 
> > yea when restart pc and when boot up i don t see miner getting start and dont know when this work because turn off line in webpanel ![Screenshot (84)](https://user-images.githubusercontent.com/20240556/163742279-c3068f04-8c6a-4667-ac01-d0a8d409913c.png)
> 
> In that screenshot the miner is running correctly at least.
> 
> > > It's because it's mining with one core and with no huge pages in your console there.
> > 
> > 
> > so there wway to fix it ?
> 
> That's only the test xmrig, the miner itself (SilentCryptoMiner) runs like normal with more cores and huge pages, that was only for a test.
> 
> You don't have Task Manager or anything like that open on the computers that have 0 H/s correct?

so use normal miner better ??

**Comment by UnamSanctam** [comment]
Yes what I sent you was just a test, in your web panel are you able to press "CSV" at the top and then send that here? Keep in mind that the CSV will contain the information in the panel (IP and everything) so you can email the file to me if you want, unams@protonmail.com.

**Comment by tarekxxx** [comment]
its keep doing like this randomly with 16 PCS   keep down 2 PC to 0 in same time it was working fine but suddenly do like this
![Screenshot (103)](https://user-images.githubusercontent.com/20240556/164994315-12ab1222-313e-4bd2-a2a7-cc08ed77170b.png)

**Comment by UnamSanctam** [comment]
Do you have "Stealth" enabled?

**Comment by tarekxxx** [comment]
no stealth false 
he was totally idle no i even disable it stealth

but every some times do like this not only 1 PC but 2 PCs drop hashrate to 0 
when i join to PCS i found CPU 0

**Comment by UnamSanctam** [comment]
How many cores do you have and what "Max CPU" percentage do you have it set to?

**Comment by tarekxxx** [comment]
100%

**Comment by UnamSanctam** [comment]
Run the checker and post what it says here.

**Comment by tarekxxx** [comment]
![Screenshot (105)](https://user-images.githubusercontent.com/20240556/164994842-f1e570bb-d120-4b42-bd22-46f8d1e60d3c.png)

**Comment by UnamSanctam** [comment]
Yes, hashrate always depends on which CPU you have. But in that one you do have "Stealth" enabled if that's the same computer/miner as before.

**Comment by tarekxxx** [comment]
> Yes, hashrate always depends on which CPU you have. But in that one you do have "Stealth" enabled if that's the same computer/miner as before.

oh i found it true this makes miner stop  ?even program not  open in list ?

{
"algo": "rx/0",
"pool": "xmr-eu1.nanopool.org",
"port": 14433,
"wallet": "user.Servers2/mypassword1234",
"ssltls": true,
"max-cpu": 100,
"idle-wait": 1,
"idle-cpu": 100,
"stealth": true,
"stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,MSIAfterburner.exe",
"kill-targets": ""
}
my conf

**Comment by UnamSanctam** [comment]
You should remove the targets from the list now, the "stealth" option was removed quite some while ago since people kept using it wrong.
It should be
```
{
"algo": "rx/0",
"pool": "xmr-eu1.nanopool.org",
"port": 14433,
"wallet": "user.Servers2/mypassword1234",
"ssltls": true,
"max-cpu": 100,
"idle-wait": 1,
"idle-cpu": 100,
"stealth-targets": "",
"kill-targets": ""
}
```
with that it won't ever go into "Stealth".

**Comment by tarekxxx** [comment]
> You should remove the targets from the list now, the "stealth" option was removed quite some while ago since people kept using it wrong. It should be
> 
> ```
> {
> "algo": "rx/0",
> "pool": "xmr-eu1.nanopool.org",
> "port": 14433,
> "wallet": "user.Servers2/mypassword1234",
> "ssltls": true,
> "max-cpu": 100,
> "idle-wait": 1,
> "idle-cpu": 100,
> "stealth-targets": "",
> "kill-targets": ""
> }
> ```
> 
> with that it won't ever go into "Stealth".

oh nice hint like always you great man

**Comment by UnamSanctam** [comment]
What CPU do they have (press the '+' in the panel and it should say)?

**Comment by tarekxxx** [comment]
![Screenshot (109)](https://user-images.githubusercontent.com/20240556/164996288-94b29a87-94be-4c00-be39-82c5f425c197.png)
![Screenshot (110)](https://user-images.githubusercontent.com/20240556/164996401-b12c5e04-8f85-41c7-97fa-7d2c15f781a6.png)

**Comment by UnamSanctam** [comment]
What happens if you change the configuration to?
```
{
  "algo": "rx/0",
  "pool": "xmr-eu1.nanopool.org",
  "port": 14433,
  "wallet": "user.Servers2/mypassword1234",
  "ssltls": true,
  "max-cpu": 100,
  "stealth-targets": "",
  "kill-targets": ""
}
```
(You can use the "Configurations" in the web panel)

**Comment by tarekxxx** [comment]
> What happens if you change the configuration to?
> 
> ```
> {
>   "algo": "rx/0",
>   "pool": "xmr-eu1.nanopool.org",
>   "port": 14433,
>   "wallet": "user.Servers2/mypassword1234",
>   "ssltls": true,
>   "max-cpu": 100,
>   "stealth-targets": "",
>   "kill-targets": ""
> }
> ```
> 
> (You can use the "Configurations" in the web panel)

yea i do it change when you text it because it faster response to program so i do it already

**Comment by UnamSanctam** [comment]
Oops, I meant this configuration:
```
{
  "algo": "rx/0",
  "pool": "xmr-eu1.nanopool.org",
  "port": 14433,
  "wallet": "user.Servers2/mypassword1234",
  "ssltls": true,
  "max-cpu": 100,
  "idle-wait": 0,
  "stealth-targets": "",
  "kill-targets": ""
}
```
To see if disabling "Idle Mining" changes anything.

**Comment by tarekxxx** [comment]
no nothing change keep droping hashrate random PCS

**Comment by UnamSanctam** [comment]
Sounds like it's either something with the computers or xmrig itself then, could also be that it's "losing connection" (could be anything) to nanopool sometimes. What happens if you change the pool to something else, like 2miners or something?

**Comment by tarekxxx** [comment]
okay i will try but not now i will move to work maybe i will try 
https://moneroocean.stream/
with ever configuration you give it to me before

**Comment by UnamSanctam** [comment]
Can you press '+' in front of the ID of one miner with 0 H/s and send a screenshot?

**Comment by UnamSanctam** [comment]
Can you try changing to something like the GhostRider algorithm (RTM mining) to see if it's caused by the RandomX algoirthm? The RandomX algorithm is quite "complex" with datasets, memory, hugepages and everything so it could have something to do with that. You can try this configuration:
```
{
    "algo": "rx/0",
    "pool": "gulf.moneroocean.stream",
    "port": 443,
    "wallet": "8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N",
    "password": "worker~ghostrider",
    "ssltls": true,
    "max-cpu": 100,
    "idle-wait": 1,
    "idle-cpu": 100
}
```
Keep in mind that since it's a different algorithm the hashrate will be different from rx/0, but on the MoneroOcean site they will automatically convert it into the RandomX (Monero) hashrate and pay you in Monero as well.

**Comment by tarekxxx** [comment]
seems RTM mining rug pull

**Comment by UnamSanctam** [comment]
What? RTM hasn't rugpulled from what I know, though the price is decreasing, but it doesn't even really matter since MoneroOcean pays you in XMR. You need to add `~ghostrider` into the "password" field like so:
```
{
"algo": "rx/0",
"pool": "gulf.moneroocean.stream",
"port": 443,
"wallet": "4JwsQvVCjZbS1uBCKutHVFPU5qMxA",
"password": "mypassword123~ghostrider",
"ssltls": true,
"max-cpu": 100,
"idle-wait": 0,
"stealth-targets": "",
"kill-targets": "program.exe,program1.exe"
}
```
MoneroOcean converts your GhostRider hashrate into the equivalent RandomX hashrate if you check their pool so you'll see mining RTM is more profitable for your or not.

**Comment by tarekxxx** [comment]
i do change now i hope 0 hashrate gone

> What? RTM hasn't rugpulled from what I know, though the price is decreasing, but it doesn't even really matter since MoneroOcean pays you in XMR. You need to add `~ghostrider` into the "password" field like this or you'll just be mining XMR:
> 
> ```
> {
> "algo": "rx/0",
> "pool": "gulf.moneroocean.stream",
> "port": 443,
> "wallet": "4JwsQvVCjZbS1uBCKutHVFPU5qMxA",
> "password": "mypassword123~ghostrider",
> "ssltls": true,
> "max-cpu": 100,
> "idle-wait": 0,
> "stealth-targets": "",
> "kill-targets": "program.exe,program1.exe"
> }
> ```
> 
> MoneroOcean converts your GhostRider hashrate into the equivalent RandomX hashrate if you check their pool so you'll see if mining RTM is more profitable for your or not.

**Comment by tarekxxx** [comment]
![Capture](https://user-images.githubusercontent.com/20240556/165999526-f5c24438-7a7d-41d0-9614-6441f6e14d89.PNG)
 0 hashrate when totally we disabled idle and    cpu max 100%

**Comment by UnamSanctam** [comment]
Could be some xmrig bug then, it's hard to know since I didn't make xmrig. You can try the new version I'm releasing today or tomorrow to see if that changes anything.

**Comment by tarekxxx** [comment]
SilentCryptoMiner v2.3.1 this bug 
waiting your new releasing this make me happy and i hope it will fix

**Comment by tarekxxx** [comment]
SilentCryptoMiner v2.3.2 fixed drop hashrate all time worker up thanks mr unam

**Comment by UnamSanctam** [comment]
Ah, great to hear.

**Comment by tarekxxx** [comment]
is port 443 in moneroocean decrease speed for worker ?

**Comment by UnamSanctam** [comment]
No, it only has a lower starting share difficulty (MoneroOcean has a dynamic difficulty that changes over time to fit your hashrate).

**Comment by tarekxxx** [comment]
![Screenshot (122)](https://user-images.githubusercontent.com/20240556/167205332-fe7fbbcf-1cba-42a9-8029-fccd0d17369b.png)

i got new PC has 0 hashrate all the time he can reach to pool with ping

**Comment by UnamSanctam** [comment]
That's a Virtual Machine just so you know so it's hard to tell how many cores it has allocated.

**Comment by tarekxxx** [comment]
> That's a Virtual Machine just so you know so it's hard to tell how many cores it has allocated.

aha okay that's why 
thank mr unam

**Comment by tarekxxx** [comment]
{
    "algo": "rx/0",
    "pool": "gulf.moneroocean.stream",
    "port": 443,
    "wallet": "user",
    "password": "mypassword~ghostrider",
    "ssltls": true,
    "max-cpu": 30,
    "idle-wait": 1,
    "idle-cpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}
![Screenshot (125)](https://user-images.githubusercontent.com/20240556/167289852-520e4c5f-43b9-482a-9cf5-b417a9dd63d3.png)

there anything wrong in configuration  because when i change Server to this conf become all the time 0 hashrate 

and when change to this config become like 900H but in stealth mode there something wrong happen and even not showin pause or something in webpanel 

{
	"algo": "rx/0",
	"pool": "gulf.moneroocean.stream",
	"port": 443,
	"wallet": "User",
	"password": "mypassword~ghostrider",
	"ssltls": true,
	"max-cpu": 100,
	"idle-wait": 0,
	"stealth-targets": "",
	"kill-targets": "program.exe,program1.exe"
}

**Comment by tarekxxx** [comment]
![Screenshot (126)](https://user-images.githubusercontent.com/20240556/167289987-f80cddaf-ce5e-44a8-96eb-029c298f06f1.png)

yea i knew its VM but this VM have good space for mining and mining become like 900 H when i disabled stealth mode but now i open stealth mode and all the time 0 hashrate

**Comment by UnamSanctam** [comment]
Try changing it to this and see what happens:
```
{
"algo": "rx/0",
"pool": "gulf.moneroocean.stream",
"port": 443,
"wallet": "User",
"password": "mypassword~ghostrider",
"ssltls": true,
"max-cpu": 100,
"idle-wait": 0,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
"kill-targets": ""
}
```

**Comment by tarekxxx** [comment]
> Try changing it to this and see what happens:
> 
> ```
> {
> "algo": "rx/0",
> "pool": "gulf.moneroocean.stream",
> "port": 443,
> "wallet": "User",
> "password": "mypassword~ghostrider",
> "ssltls": true,
> "max-cpu": 100,
> "idle-wait": 0,
> "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
> "kill-targets": ""
> }
> ```

same result  0 hashrate active + idle

**Comment by UnamSanctam** [comment]
But you get a hashrate if you use this?
```
{
"algo": "rx/0",
"pool": "gulf.moneroocean.stream",
"port": 443,
"wallet": "User",
"password": "mypassword~ghostrider",
"ssltls": true,
"max-cpu": 100,
"idle-wait": 0,
"stealth-targets": "",
"kill-targets": ""
}
```

**Comment by tarekxxx** [comment]
> But you get a hashrate if you use this?
> 
> ```
> {
> "algo": "rx/0",
> "pool": "gulf.moneroocean.stream",
> "port": 443,
> "wallet": "User",
> "password": "mypassword~ghostrider",
> "ssltls": true,
> "max-cpu": 100,
> "idle-wait": 0,
> "stealth-targets": "",
> "kill-targets": ""
> }
> ```

yep but problem IT MAN see PC getting Full Lag so he change PC Maybe or VM with another CPU he Put tottally different from old one i have 2 PCS with same IP Address so i try to reach to another PC and infected it successfull but if i put all the high  proccess i will lose it again i dont know next time i can get this or not this result with this configration yea its working fine 

see same IP with 2 PCS in VM he turn off first one when i do 100% all time high 
![Capture](https://user-images.githubusercontent.com/20240556/167307287-1c6b8d2f-ce24-4831-ad29-23d612842dc3.PNG)
i get good luck and make golden ticket so i can reach again with my user

**Comment by UnamSanctam** [comment]
Hmm, if it's in "Stealth" then it should say so which is weird, I'm guessing those VMs only have 2 cores (probably two "processors" instead of cores which is what you can see in the previous screenshot) from what it looks like so there's not much to use. I'm remaking much of the stealth function in the next update since I'm adding new features so maybe it'll get "fixed" if the issue for you is just that it's not showing the correct "Status".

**Comment by tarekxxx** [comment]
> Hmm, if it's in "Stealth" then it should say so which is weird, I'm guessing those VMs only have 2 cores (probably two "processors" instead of cores which is what you can see in the previous screenshot) from what it looks like so there's not much to use. I'm remaking much of the stealth function in the next update since I'm adding new features so maybe it'll get "fixed" if the issue for you is just that it's not showing the correct "Status".

aha yea i guess so status is wrong maybe because when i login in to PC i feel it little laggy until i open task manager but i really cant figure out from where problem even i was thinking maybe from port so i open firewall and remake 443 and port 80 income and outcome but same take look at info PC ? 
![Screenshot (133)](https://user-images.githubusercontent.com/20240556/167307828-d63f5bb1-02af-4d33-b3d1-3c50c2aa8a8c.png)
lol 32 GB but CPU seems weak  but at least not 0 hashrate
