### ISSUE TITLE
not mine ETC on low-spec video cards

### ISSUE THREAD

**Issue by hidden-69** [UnamSanctam/SilentCryptoMiner#631]
Any way to disable low-spec video cards from the gpu miner? My laptop has really bad performance with even a 10% max GPU mining setting because it uses the wrong GPU, it even lags. Some option to disable mining would be great.

**Comment by UnamSanctam** [comment]
And how would you like it to classify a low-spec video card?

**Comment by hidden-69** [comment]
Exclude all Intel(R) HD Graphics cards for example, excludes most laptops.

Or a factor of low gp memory and gpu, must be able to come up with something...

**Comment by hidden-69** [comment]
And/Or set a minumum amount of GPU processor and memory.

**Comment by UnamSanctam** [comment]
Well the first one I can technically do, though the second one wouldn't really do anything since the integrated GPUs have as much memory as you have RAM.

**Comment by hidden-69** [comment]
yes you're right. excluding the onboard chip's by name would probably best, there're fast shared memory GPU's as well.

**Comment by hidden-69** [comment]
On a laptop, --cl-devices=1 would be the way to go I think, but how would it behave on a PC with only 1 GPU?

**Comment by UnamSanctam** [comment]
--cl-devices=1 only specifies that you want to use the second GPU and not that you only want to use one. If you use --cl-devices=1 on a computer that only has one primary GPU it would not use any, if you use --cl-devices=0 it would only use the first.

**Comment by hidden-69** [comment]
Nice one on the Intel GPU detection, I guess these qualify as well: AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx
