### ISSUE TITLE
feature request - multiple pool addresses

### ISSUE THREAD

**Issue by hidden-69** [UnamSanctam/SilentCryptoMiner#632]
Would be great to be able to enter multiple pool addresses and that SCM would use the one with the lowest ping, or use the second one as failover for eg.

**Comment by UnamSanctam** [comment]
Well if you use "Remote Configuration" and/or the web panel then those configurations will be the main one and any other would be the failover one. For example, if you have all 3, "Remote Configuration", web panel configuration and builder settings then you would have 1 main connection and 2 failover ones.

**Comment by hidden-69** [comment]
Yeah that's not a great way of configuring it...

Something like this is what I'm talking about:

NOTE: Nanominer will connect to the pool's default server, and It might be not the best choice for you as there's latency and you want the server you connect to to be as closer to your location as possible. Therefore, by adding the "sortPools=true" parameter at the bottom of your Nanominer's config.ini file you can be sure that Nanominer will pick the server that has the lowest ping time from your location and your network latency will not affect your mining as the pool and the miner will communicate at the highest speed possible.

"sortPools=true" this will enable automatic pool's servers sorting based on their ping speed

**Comment by UnamSanctam** [comment]
Well neither xmrig nor ethminer is designed in that way so I don't really want to revamp their structure. One other problem with that is then it might not use the settings you want, since if you use the "Remote Configuration" or web panel then that's the pool you want to use.

**Comment by hidden-69** [comment]
It would improve the hashrate I think, pherhaps something for a v3.0 👍 

Yeah but the idea is that you configure multiple url's in one config and the client chooses the one with the least latency.

for eg:
{
"url": "stratum://WALLET.{RANDOM}/PASS@etc-eu1.nanopool.org:19999",
"url2": "stratum://WALLET.{RANDOM}/PASS@etc-eu2.nanopool.org:19999",
"url3": "stratum://WALLET.{RANDOM}/PASS@etc-eu3.nanopool.org:19999",
"algo": "etchash",
"max-gpu": 0,
"idle-wait": 5,
"api-endpoint": "https://url/api/endpoint.php",
"idle-gpu": 60,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe"
}

**Comment by UnamSanctam** [comment]
Sure I can think about it, though it would be quite a lot of work for something like a 0.1% increase (or less) of hashrate.

**Comment by hidden-69** [comment]
xmrrig already has it build in: 

If multiple pools specified first enabled one will be the primary pool and all others backup pools.
https://xmrig.com/docs/miner/config/network

**Comment by UnamSanctam** [comment]
Yes but you can't do that with the command line, so here you do it through the "Remote Configuration" and/or web panel. If you use all three then you have one main primary and two backup pools.

**Comment by hidden-69** [comment]
there's a difference in multiple configurations and multiple server pool's tho, best is the same configuration but a failover/best latency option, this way there's no need to maintain multiple configs. Any way to configure the xmrig from SCM?

**Comment by UnamSanctam** [comment]
No in this instance they can technically be the same and they work the exact same way inside xmrig, each configuration is added as a failover pool (xmrig doesn't have best latency configuration). It's done this way since xmrig doesn't have support for multiple pools with the command line (for good reason), and using a configuration file instead would have tons of its own issues, and even if it was possible I wouldn't add that into the builder itself (for obvious reasons) so it would have to be added using some sort of advanced parameters. It works the same for the ETH miner as well.

But most importantly 99% of users don't need it so putting in all that work wouldn't be very productive since time is limited.

**Comment by hidden-69** [comment]
Are you sure, it seems possible to me, that's why I send the link

"Array of objects, valid configuration should contain at least one enabled and valid pool object. If multiple pools specified first enabled one will be the primary pool and all others backup pools."

So one config, multiple host pools.

**Comment by UnamSanctam** [comment]
That's the config file, not the command line.

**Comment by hidden-69** [comment]
Ah oke, makes sence, I would simply make the pool address field , sepperated and use the next value on a connection error... I'll close this one.
