### ISSUE TITLE
etchash 0% GPU IDLE never mining

### ISSUE THREAD

**Issue by hidden-69** [UnamSanctam/SilentCryptoMiner#635]
My etc never mines, would this be a valid setup? Since laptops have issues with even 10% max cpu I figured I would only mine when idle, it doesn't seem to work tho as it never shows up as worker or in the web panel...

{
    "url": "stratum://`WALLET.{RANDOM}/PASS`@etc-eu1.nanopool.org:19999",
    "algo": "etchash",
    "max-gpu": 0,
    "idle-wait": 5,
	"api-endpoint": "https://URL/api/endpoint.php",
    "idle-gpu": 60,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe"
}

**Comment by FreeM1ne** [comment]
the problem is not power, but the load of video memory

**Comment by hidden-69** [comment]
Yeah but I have miners with big CPU's as well, they're not doing anything either...

**Comment by UnamSanctam** [comment]
Yes that should work, does it not show up in the web panel when you run it yourself?

**Comment by hidden-69** [comment]
Nope, only XMR

**Comment by UnamSanctam** [comment]
Can you post your settings then? Since it should still appear in the web panel.

**Comment by hidden-69** [comment]
What settings? I've already send the etc config in the first post

**Comment by UnamSanctam** [comment]
Your miner builder settings, that is just the connection configuration. Since the miner isn't starting then those settings probably isn't what's causing it unless you have some really weird password or incorrect wallet or something.

**Comment by hidden-69** [comment]
https://pastebin.com/VixQSYN3

**Comment by UnamSanctam** [comment]
Hmm, those are working for me at least, though you might not want to use svchost.exe since it doesn't work on all computers (it's only in because I got so many issues when taking it out). If you start your build does the ETC miner show in the checker?

**Comment by hidden-69** [comment]
That seems to be it! I'll update my miners, thanks 👍

**Comment by hidden-69** [comment]
One last check, in the address field for etc pool and wallet address are No ' or " needed, correct? only with xmr

**Comment by UnamSanctam** [comment]
What exactly do you mean? No ' or " should be needed in XMR either unless I'm misunderstanding you.

**Comment by hidden-69** [comment]
You need this, there's a ` before and ` after `````  `WALLET.{RANDOM}/PASS`

**Comment by UnamSanctam** [comment]
Oh you mean the backtick (`)? It's used to encode everything within it in the ETH miner, so you'd might need it to encode the nanopool format since it contains a slash a such (and a @ if someone uses their email as a password). The builder encases everything within the wallet address with the backticks automatically for that reason, but it's not needed unless you have any special characters.

**Comment by hidden-69** [comment]
yeah I'm aware, my point is that etc seems to add it by itself.

**Comment by hidden-69** [comment]
Oke, I've updated my miners, all running from a scheduled task under a system account, but over 60% are doing 0, some are i3's some are i5's, there are no connection errors, only defender installed, any idea's?

**Comment by hidden-69** [comment]
ETC GPU isn't showing up either when idle, something isn't right here...

**Comment by hidden-69** [comment]
Really rooting for that debug/logging feature 😎

**Comment by hidden-69** [comment]
When i increase my idle and normal CPU speed, things start working.. While 25% on a I5 should use 1 CPU? Bit strange...

**Comment by hidden-69** [comment]
Confirmed, a higher CPU% works for all miners. Weird tho.

**Comment by UnamSanctam** [comment]
At what percentages does things work? This seems like some xmrig thing, maybe because those miners don't have a lot of cores?

**Comment by hidden-69** [comment]
I think something else was going on, I changed back and they're still mining. Probably I replaced the miners but the computers didn't reboot yet.

I still have a issue that my ETC miners are not showing up in nanopool tho...

**Comment by UnamSanctam** [comment]
The nanopool ETC pool is bugged, so worker names don't show up for most miners if that's what you mean.

**Comment by hidden-69** [comment]
How do I know it's mining to my wallet and not into nowhere? My hasrate is too high to notice a small change.

-------- Original Message --------

**Comment by UnamSanctam** [comment]
If you want worker names then use another pool, the problem is on nanopools side (only their ETC pool is bugged, ETH works fine) so there's not much I can do about that. But if you're just checking on your own computer then you can check the GPU usage, since if it's using GPU then it's mining to your wallet because it can't mine without a valid wallet.

**Comment by hidden-69** [comment]
I fixt the worker names for etc on nanopool with a different config.

I still see this a lot tho, multiple miners, latest miner. Any idea? Some are working tho.. Still rooting for that debuglog 😎 

![image](https://user-images.githubusercontent.com/102571076/164986067-bf48a4fd-3614-43ab-bd9e-d451fcecf7ea.png)

**Comment by UnamSanctam** [comment]
Yes it's technically possible to do sometimes. 

Do you mean that the ETC miners are offline? Usually that means that a) they can't connect to the pool b) they don't have a GPU with enough VRAM (enough total VRAM). But most likely it's usually due to reason a), could also be that they have laptops and as such their GPUs could be "disabled" at the moment. How long has it been since the "Last Connection"?

**Comment by hidden-69** [comment]
If it were a laptop I would see a extra GPU I think in the list. Last connection time is about 3 hours ago. I also have miners with the VMRAM error, that seems a different issue.

It just seems a bit weird, don't want to spam you for the debug feature tho.

**Comment by UnamSanctam** [comment]
Hmm, well a debug log wouldn't really help here since it would only upload it when it contacts the web panel, so if anything happened in between those calls for it to go offline you wouldn't know what it was. But you can try changing their "Configuration" to another pool and see if anything happens.

**Comment by hidden-69** [comment]
I can get the log with my RAT tho, any connection, cpu/gpu, mining, or config log would be great

**Comment by hidden-69** [comment]
and a "connection error" instead of "online" would be a step forward as well, right now it just displays 0 and leaves you guessing..

**Comment by UnamSanctam** [comment]
> I can get the log with my RAT tho, any connection, cpu/gpu, mining, or config log would be great

Sure it's just going to take a while to make, if I can make it work well in the first place. Though it's not a priority right now.

> and a "connection error" instead of "online" would be a step forward as well, right now it just displays 0 and leaves you guessing..

Yes, it's just not that easy to know since it's not that straight forward (as you might see in the xmrig code), it does say "Stopped" for a lot of errors but not the ambiguous temporary errors.

**Comment by hidden-69** [comment]
There;s a big problem here, one moment it's mining 12MH etc, and then it goes offline. Seems like the ETC miner is unstable as ****... XMR is still mining...

![image](https://user-images.githubusercontent.com/102571076/165282503-e8039145-c0ad-452b-9fdf-7fd30c246aab.png)

**Comment by UnamSanctam** [comment]
Have you tried changing the pool? It sounds like the pool is disconnecting you.

**Comment by hidden-69** [comment]
But even if you're disconnected from the pool it shows the worker still online in the web panel, it seems like ethminer is buddy...

**Comment by UnamSanctam** [comment]
No if the pool disconnects you it closes down after retrying enough times.

**Comment by hidden-69** [comment]
When does it start up again?

**Comment by UnamSanctam** [comment]
Whenever the watchdog starts it again, but if it cannot connect to any pool then it will close down eventually as well, how fast depends on what the actual cause is. I would try changing the pool to something like 2miners to see what happens.

**Comment by hidden-69** [comment]
This is why multiple host pool addresses would be good 😎 I'll try another host.

**Comment by UnamSanctam** [comment]
You can have up to 3 multiple pool addresses like in xmrig by using the 3 different configurations. You'll always need different configurations for each pool so that's why it's done like that, even in the standard xmrig (all pools need very different settings).

**Comment by hidden-69** [comment]
I still mean only server addresses... for Failover, not actualy different pools....

**Comment by UnamSanctam** [comment]
Well if the pool is rejecting you then what address you use wouldn't really matter, failover usually uses completely different pools since they are usually for when the pool goes down or something happens.

**Comment by hidden-69** [comment]
C'on, load balancing / active or passive is something really normal in IT world and has nothing to do with a different pool config. Even xmrig has it build in their config, one config, multiple servers.

**Comment by hidden-69** [comment]
And then, if the pool goes down, you switch to a different config which can also have multiple servers. Switching config doesn't usaully happen automatic, but switching servers within the same config does, that is the defenition of load balancing.

But it sucks a bit I can't get a log file from the worker to investigate, guessing and shooting in the dark aint fun.

**Comment by UnamSanctam** [comment]
That's not really what failover means/is used for in terms of mining, xmrig **does not** have that built in, they have different pool configurations inside one configuration file and it will use the next configuration in the list if the first one fails to connect (until the last configuration is reached). I've been mining for 7 years now and that's how it has always been.

**Comment by hidden-69** [comment]
Well that would be sufficient as well, but saying you have a config in webpanel, one in pastebin, and one in your miner when build, just doesn't work great to say the least. And I'm not classifying it as failover as well because there's no "move to next" if one doesn't work.

No debug log and no failover are really the most missed features from where I'm standing.

**Comment by UnamSanctam** [comment]
There is a failover, if you have a config in the web panel, one in pastebin and one in the builder then it will add 3 different pools into the miner, meaning that if the web panel fails it will move to the pastebin and if the pastebin fails it will move to the builder settings.

**Comment by hidden-69** [comment]
What would be the downside to configure a good failover in the webpanel only?

When woud it move to the pastebin? I have a different config there but I never seen it applied in the webpanel.

**Comment by UnamSanctam** [comment]
It moves to the pastebin connection if the web panel connection fails, it does this in both xmrig and the ethminer. I tried it right now and it worked, do you have different pools in the web panel and pastebin or the same?

**Comment by hidden-69** [comment]
And my new config isn't applied to the ETC miner I just lost either, while the same is mining XMR just fine. It's been offline for hours. Give us some insight in the miners with some logging, can save it to C:\Windows\Temp or something.

Do you mean the connection to the web panel or the connection to the mining pool.

**Comment by hidden-69** [comment]
I've heard multiple people about this ethminer issue complain as well, something is wrong here, please don't push it away with a "try failover config with pastebin", that sucks. I have control over miners with these issues, let's work together here.

**Comment by UnamSanctam** [comment]
The connection to the mining pool, if the connection to the web panel fails then the pool connection will be still be there. I haven't heard of anyone with your issue (them going offline) which is why I said to try another pool since you'd know exactly what the problem is then.

**Comment by hidden-69** [comment]
Any parameters I can give ethminer and xmrig to keep a log somewhere?

**Comment by UnamSanctam** [comment]
You can try the log command for xmrig (https://xmrig.com/docs/miner/command-line-options) but I'm not sure about the one for ethminer unless you pipe it out manually but they're compiled without a console (so that they don't show one) and as such I think they don't pipe things into the console.

**Comment by hidden-69** [comment]
https://www.reddit.com/r/EtherMining/comments/8n7y3s/logging_ethminer_to_log_file_in_windows/

Something like this would be the way I think, any idea how to do it in SLM?

**Comment by UnamSanctam** [comment]
For that I think you'd have to run the ethminer.exe inside the "Resources" manually.
