### ISSUE TITLE
Have you accidentally raised the hashrate of 12.04? For me, it grew by 3 times for a day and fell again by 3 times

### ISSUE THREAD

**Issue by Vaflya123** [UnamSanctam/SilentCryptoMiner#636]
Have you accidentally raised the hashrate of 12.04? For me, it grew by 3 times for a day and fell again by 3 times

**Comment by UnamSanctam** [comment]
No (not sure how that would work) but mining is based on luck so your hashrate also depends on luck, it could be that.

**Comment by Vaflya123** [comment]
No, other users did not have such anomalies

**Comment by UnamSanctam** [comment]
Not sure what you mean, can you post a screenshot or anything?

**Comment by Vaflya123** [comment]
![image](https://user-images.githubusercontent.com/103882336/163712739-818e27ac-7a8e-4439-85b9-b1f86840edee.png)

**Comment by Vaflya123** [comment]
There was no traffic at that time.

**Comment by UnamSanctam** [comment]
Could be luck, could be some error in the statistics. I don't have control of anyone's miners so I can't really do anything.

**Comment by Vaflya123** [comment]
yes
