### ISSUE TITLE
The procedure entry point "K32GetProcessMemoryInfo"

### ISSUE THREAD

**Issue by Zem0rt** [UnamSanctam/SilentCryptoMiner#637]
I launched the miner in 'window server 2008 r2 standard (x64)' and after 3-4 seconds it crashes, whatever I tried, it doesn't start and I wanted to test it in xmrig and an error came out (the entry point to the procedure "k32getprocessmemoryinfo " was not found in the dll "kernel 32.dll".) and maybe the miner can't be loaded due to this error?
![IMG_20220417_152039](https://user-images.githubusercontent.com/99068726/163716188-f008d273-d23a-4cf5-8b1c-5d49013bb649.jpg)

**Comment by UnamSanctam** [comment]
Can you try update 2.1.0 or 2.0.0? Just to see if it's due to an xmrig update that maybe made it stop working on Windows XP.

**Comment by Zem0rt** [comment]
> Can you try (just test it) update 2.1.0 or 2.0.0? Just to see if it's due to an xmrig update that maybe made it stop working on Windows XP.

version 2.0.0 works successfully, but 2.1.0 does not work.

**Comment by UnamSanctam** [comment]
Ok, sounds like maybe some xmrig update did that then, I'll try and see if I can rework whatever they did so that xmrig can work on Windows XP. I just have to find an ISO for Windows XP 64-bit first, it's not that easy to find one.

**Comment by Nobellium1** [comment]
@UnamSanctam  Btw do you know when will that windows update  disabler be done
