### ISSUE TITLE
inject into

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentCryptoMiner#638]
technically anyway where "inject into"? works the same
![a](https://user-images.githubusercontent.com/81568432/163721667-2115fdb6-efb7-4ce7-be30-5def7cda678c.png)

**Comment by UnamSanctam** [comment]
Yes all the options work the same, they are just there so you can choose what it will disguise itself as. Though some options like svchost.exe might not work on all computers, it's just there since there were so many requests for it.

**Comment by golxd** [comment]
I'm sorry to bother you, I have a lot of archives on the old version, I'm thinking of updating now to the latest version. in the coming days new version will not? (so that do not update archives again)

**Comment by UnamSanctam** [comment]
Maybe, I have done some changes but currently I'm trying to reliably disable Windows Update, which is quite difficult since that's one thing that Microsoft has been working hard to prevent for many years. So I'm not sure how long it will take, I'm mostly done with the other things I was working on.

**Comment by golxd** [comment]
Yes, all right, thank you

**Comment by golxd** [comment]
I'm sorry to bother you) question about idle GPU, I understood, he anyway uses the required amount of VRAM, doesn't matter, 10% or 100%. if at 100% he produces 100 m/hs, 10% will 10 m/hs? or it doesn't work like that

**Comment by UnamSanctam** [comment]
Yes that's how it works.

**Comment by golxd** [comment]
thx
