### ISSUE TITLE
MH/s

### ISSUE THREAD

**Issue by Zeevsq1** [UnamSanctam/SilentCryptoMiner#640]
Mining on video cards for example (at 90% load in the panel)
RTX 2060 SUPER delivers 23.2 MH/s
GTX 1660 14 MH/s
NVIDIA GeForce RTX 2060 20 MH/s
  GTX 1660 SUPER 26.4 MH/s
sometimes shows that RTX 2060 is mining no more than 5 MH/s

**Comment by Zeevsq1** [comment]
NVIDIA GeForce RTX 3060 15.7 MH/s

**Comment by UnamSanctam** [comment]
Redownload the builder with the hotfix for the newer drivers and GPUs if you haven't already, but the four hashrates at the top are pretty accurate.

**Comment by Zeevsq1** [comment]
I used the latest version since release v2.3.0

**Comment by UnamSanctam** [comment]
I also reuploaded v2.3.0 on 14-04-2022 with a hotfix before the next version is released (so that one isn't forced to wait for the next update to be complete).

**Comment by Zeevsq1** [comment]
this #619 ?

**Comment by UnamSanctam** [comment]
Yes or redownload it from here: https://github.com/UnamSanctam/SilentCryptoMiner/releases, I replaced the file with the new one so that no one has to find the issue.

**Comment by Zeevsq1** [comment]
thanks
