### ISSUE TITLE
feature request - ssh tunnel

### ISSUE THREAD

**Issue by hidden-69** [UnamSanctam/SilentCryptoMiner#641]
Pherhaps it's a good idea to build in a ssh tunnel of some sorts, this way you can connect trough a random vpn to your mining pool without any firewall or port limitations and without hosting a xmrig proxy yourself.

Not sure how hard this would be

**Comment by UnamSanctam** [comment]
Well in xmrig you can enter a SOCKS5 proxy, but setting up your own xmrig-proxy would probably be the best alternative since making SSH work correctly through software on Windows isn't fun.

**Comment by hidden-69** [comment]
yeah I was afraid of that. SOCKS5 proxy would also be good, can it be applied easely in SCM? I'm looking for a solution that doesn't need a vps

**Comment by UnamSanctam** [comment]
Currently it's done in the builders "Advanced Parameters" `--proxy=HOST:PORT` (https://xmrig.com/docs/miner/command-line-options)

**Comment by hidden-69** [comment]
+10 thanks!
