### ISSUE TITLE
Ethereum/Monero

### ISSUE THREAD

**Issue by Programmer1603** [UnamSanctam/SilentCryptoMiner#643]
If i wanted to mine Ethereum on Moneroocean so i get paid in monero, would i have to build a monero miner or a ethereum miner?
Pls help ty

**Comment by UnamSanctam** [comment]
Ethereum miner, enter everything like normal but add `~ethash` into the "Password" field after your worker name.

**Comment by Programmer1603** [comment]
Nice Ty
