### ISSUE TITLE
Have you abandoned your telegram or are you just not responding to my messages?

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentCryptoMiner#644]
Have you abandoned your telegram or are you just not responding to my messages?

**Comment by UnamSanctam** [comment]
Two of my hard drives have died, one of them had my non-testing VMs which included Telegram. I don't really have any space left on the other drives I have. I ordered new ones maybe 2-3 months ago or something (maybe longer) but they're still stuck in Germany from what it looks like.
