### ISSUE TITLE
miner launch

### ISSUE THREAD

**Issue by Zeevsq1** [UnamSanctam/SilentCryptoMiner#645]
You can make it so that the miner starts after rebooting the PC.
So that at the first start the miner does not start mining

**Comment by svox07** [comment]
By the way, I also notice this, even though it’s worth autoloading all the checkboxes and paths, but after a reboot it doesn’t start

**Comment by UnamSanctam** [comment]
> You can make it so that the miner starts after rebooting the PC. So that at the first start the miner does not start mining

It's possible to do of course but since the majority of people won't use that I'll have to hide it somewhere, probably in the "Advanced Options". The biggest problem will be that people will enable that and complain that their miners aren't starting on the first run.

> By the way, I also notice this, even though it’s worth autoloading all the checkboxes and paths, but after a reboot it doesn’t start

What do you mean? The miner doesn't have any problems with the installation that I know of if that's what you mean.

**Comment by svox07** [comment]
it installs but after restarting the pc some bots don't start and have to restart

**Comment by UnamSanctam** [comment]
Can you show me it? I mean a screenshot of the Task Scheduler/registry to see that it isn't there. Also since it starts as "System" it can be hard to find it if you're looking for it manually, so you should use the checker for it.

**Comment by svox07** [comment]
Unam can add web panel toggle online and offline toggle

**Comment by UnamSanctam** [comment]
> ![IMG_20220419_231508_129](https://user-images.githubusercontent.com/70852343/164059220-5e2f7dcb-a151-43bf-9b82-bc9b9d5162a0.jpg)

Is that the miner entry? And it's not starting? If you run the checker does it say the miner isn't running?

> Unam can add web panel toggle online and offline toggle

What do you mean? A toggle to hide offline miners?

**Comment by svox07** [comment]
switch for web panel to remove offline users toggle switch you can add this

**Comment by UnamSanctam** [comment]
Sure, it's just quite a bit of work to create a dynamic exclusionary filtering system since the current one is only inclusionary I think (been a while since I made it).

**Comment by svox07** [comment]
something like in the screenshot such a switch can add a web panel
![Screenshot_20220419-232254](https://user-images.githubusercontent.com/70852343/164060772-07f3bc7c-c8c3-4376-81a0-d0781d27bb8a.jpg)

**Comment by Zeevsq1** [comment]
and further. The user leaves the task manager open for more than 5 minutes, then it closes and continues to mine

**Comment by UnamSanctam** [comment]
> and further. The user leaves the task manager open for more than 5 minutes, then it closes and continues to mine

Sorry I don't quite understand what you're trying to say, you want a feature where it to close the Task Manager after 5 minutes of being opened?

**Comment by Zeevsq1** [comment]
> > and further. The user leaves the task manager open for more than 5 minutes, then it closes and continues to mine
> 
> Sorry I don't quite understand what you're trying to say, you want a feature where it to close the Task Manager after 5 minutes of being opened?

Yes, if you leave the task manager open, it would close after 5 minutes

**Comment by tarekxxx** [comment]
i have same problem when bots restart i lose victims no longer online
