### ISSUE TITLE
Remote Config.

### ISSUE THREAD

**Issue by userforuse** [UnamSanctam/SilentCryptoMiner#647]
Hello! I'm trying to build a miner with remote configuration. I built a couple on pastebin (with a proper raw link) and own web server (link ends with /config.json) but neither of them work. The miner still loads from the regular config.

**Comment by UnamSanctam** [comment]
Are you sure your JSON is valid? And how are you checking what that it doesn't load them?

**Comment by userforuse** [comment]
> Are you sure your JSON is valid? And how are you checking what that it doesn't load them?

Yes, I used the same JSON in the builder itself. I check it with checker and notice that the pool is not one from my remote configuration.

**Comment by UnamSanctam** [comment]
Of course, the checker shows the command line options that the process was started with, they will never change no matter what (that's how Windows works). You can check your (new) pool to see if it's mining with your "Remote Configuration", or you can use the web panel of course.

**Comment by userforuse** [comment]
> Of course, the checker shows the command line options that the process was started with, they will never change no matter what (that's how Windows works). You can check your (new) pool to see if it's mining with your "Remote Configuration", or you can use the web panel of course.

Yeah... But I changed settings in my remote configuration and the using pool doesn't seem to be changed. Link for remote was something like this http://website.com/config/config.json

**Comment by UnamSanctam** [comment]
You mean that you don't see any activity in the new pool? Are the pool settings correct?

**Comment by userforuse** [comment]
> You mean that you don't see any activity in the new pool? Are the pool settings correct?

They're correct. 
![image](https://user-images.githubusercontent.com/103531776/164283403-e08799d6-b41e-4bf6-b02a-ebbef630693b.png)

**Comment by UnamSanctam** [comment]
And you don't see any mining on ethermine under that wallet address and worker name?

**Comment by userforuse** [comment]
However one build that I used with remote configuration on pastebin changed pool. Could it be that there's problem with the link I use for my own web server?

**Comment by UnamSanctam** [comment]
Keep in mind that the miners reads the "Remote Configuration" on every start and then every 100 minutes after that. Make sure that you use http unless you have a certificate and make sure that no traffic is being blocked.

**Comment by userforuse** [comment]
> Keep in mind that the miners reads the "Remote Configuration" on every start and then every 100 minutes after that. Make sure that you use http unless you have a certificate and make sure that no traffic is being blocked.

100 minutes already passed. I use http (and I have SSL certificate also, so right now http redirects to https). I don't think that traffic is being blocked.

**Comment by UnamSanctam** [comment]
Remove the http to https redirect or build it with https and see what happens.

**Comment by userforuse** [comment]
> Remove the http to https redirect or build it with https and see what happens.

Just removed redirect and also ran a new build with https to see if the remote config would work.

**Comment by userforuse** [comment]
So my new miner is listed in my workers on that 2miners pool, but nothing on the pool that is set in the remote configuration.

**Comment by UnamSanctam** [comment]
Try it with pastebin and see if it works, then we'll know if it's something with your site.

**Comment by userforuse** [comment]
> Try it with pastebin and see if it works, then we'll know if it's something with your site.

It worked with pastebin. What possible issues can cause it to my own address? Can it be that it's link to a file with .json extension?

**Comment by UnamSanctam** [comment]
You can try calling it with some API tester and see what it returns when you call it.

**Comment by userforuse** [comment]
> You can try calling it with some API tester and see what it returns when you call it.

![image](https://user-images.githubusercontent.com/103531776/164296835-49edb2eb-913d-4278-970d-a99fa59fa9f6.png)

**Comment by userforuse** [comment]
> Can you try inputting that into a JSON validator (to make sure)? If you try placing the JSON array into a page instead does it work? Personally I can contact my site (.json file) and use it just fine so I don't really think that's it but can't hurt to try.

I don't really know how to do so, to make a link like that without extension. And somehow I need to recover access to this particular .json link cause I got miners that use this remote config. It's strange, guess there's no way to resolve it?

**Comment by UnamSanctam** [comment]
Well you can just place the JSON array inside a .html file like so:
```
<html>
<head></head>
<body>
JSON ARRAY HERE
</body>
</html>
```
and it should work. Do you have Cloudflare or anything that could be blocking something?

**Comment by userforuse** [comment]
> Well you can just place the JSON array inside a .html file like so:
> 
> ```
> <html>
> <head></head>
> <body>
> JSON ARRAY HERE
> </body>
> </html>
> ```
> 
> and it should work. Do you have Cloudflare or anything that could be blocking something?

No, I don't have Cloudflare. I will try that thing with JSON Array later and post about it here
