### ISSUE TITLE
Worker accepted then disconnect

### ISSUE THREAD

**Issue by harry133712** [UnamSanctam/SilentCryptoMiner#649]
i was wondering why my workers get accepted but after 10mins they get disconnected without accepting any shares could this by do the av or is there something wrong with the settings i use?

**Comment by UnamSanctam** [comment]
Well if you're looking at the pool statistics then it will only show hashrate when it submits a share, so if the time between share submissions is high (for example due to a high share difficulty) then there will be gaps in the graph but the average will still be the same as if the time between shares was low. Not sure if that's what you mean, some pools have a very high share difficulty so with a "normal" hashrate you might only find a share every 10 minutes or more, and even then some pools are very slow at updating/registering their statistics.

**Comment by harry133712** [comment]
i use hashvault for the quick stream they provide if i test it on vm it works just fine but on normall hardware i get the issue above provided

**Comment by harry133712** [comment]
also i  have a low difficulty for the miners on port 80 also tested on 443

**Comment by UnamSanctam** [comment]
Well I wouldn't recommend HashVault unless you're running an xmrig-proxy since otherwise you'll get banned if you have a lot of miners. But do you have a web panel or something that you can check with?

**Comment by harry133712** [comment]
used to had it but it had the same problem they where coming online hashrate was showing and after 10mins they where offline but i was on minexmr pool at that time

**Comment by harry133712** [comment]
also if the miners connect and disconnect on hashvault do those count as miners or is it only with active miners where you can get banned

**Comment by UnamSanctam** [comment]
Probably active miners, usually from sites like MineXMR, SupportXMR and HashVault you can get banned from having over around 100 miners. When the XMR miner is running then nothing will really stop it unless the computer gets turned off or if something kills the miner.

**Comment by harry133712** [comment]
okay got it then it gets probablty killed by av or something thanks for ur help anyway !

**Comment by harry133712** [comment]
sorry to come back on this but i was thinking could it be the procces killer list i give it that makes them disconnect so fast ? 

afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MsMpEng.exe,NortonSecurity.exe,nsWscSvc.exe,ccSvcHst.exe,MRT.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe

**Comment by UnamSanctam** [comment]
No it shouldn't really, the process killer runs all the time so if that was it then I think it would disconnect long before 10 minutes.

**Comment by harry133712** [comment]
yea some are way faster and some take some time it was weird but dunno

**Comment by harry133712** [comment]
but thanks for u time anyway !
