### ISSUE TITLE
profitable coin

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#650]
What do you think are the most profitable coins as coins, I dig rtm and etc. do you know better?

**Comment by UnamSanctam** [comment]
Yes those are probably the most profitable "mainstream" coins.

**Comment by UnamSanctam** [comment]
Most CPU coins have about the same profitability unless they do something special, for example I think Wownero has the highest profitability but you can only solo mine it.

**Comment by DogusCyk** [comment]
do you think i should do wownero instead of rtm

**Comment by DogusCyk** [comment]
Also, what do you mean when you say solo mine?

**Comment by UnamSanctam** [comment]
Only if you have enough hashrate and is willing to set up your own node and such (since you can only solo mine). Solo mining means that there are no pools, you can only try and find blocks on your own.

**Comment by DogusCyk** [comment]
ah so i can only dig wownero myself right?

**Comment by UnamSanctam** [comment]
Yes, that's also why it's more profitable (it's harder to mine than other coins).

**Comment by DogusCyk** [comment]
ah got it but i prefer not to dig on my own computer haha ​​thanks for the help
