### ISSUE TITLE
sugestion

### ISSUE THREAD

**Issue by rnesheik** [UnamSanctam/SilentCryptoMiner#657]
would you like to put the crypto grabber in the miner and on the web?

**Comment by UnamSanctam** [comment]
What do you mean? You want a crypto clipper in the miner or something?

**Comment by Nobellium1** [comment]
Crypto grabber is considered as a stealer that would upload all the crypto wallets client has

**Comment by Nobellium1** [comment]
So yeah, he's pretty much asking about the stealer, however I think it might be nice to make one for sure

**Comment by rnesheik** [comment]
> O que você quer dizer? Você quer um clipper de criptografia no minerador ou algo assim?

it will replace his wallet, on ctrl + c and when ctrl + v my wallet will appear, or get email and password and appear on the panel.. is one of the two possible?

**Comment by Nobellium1** [comment]
Use clipper for that.
