### ISSUE TITLE
New function Problems

### ISSUE THREAD

**Issue by AlienJ555** [UnamSanctam/SilentCryptoMiner#658]
Have a problem, when I enable "Don't run miner after install" after I restart the computer, the miner is working, but the watchdog is not working. (p.s. I have enabled the watchdog)

So the watchdog can't coexist with "Don't run miner after install"?

**Comment by UnamSanctam** [comment]
It will work with "Don't run miner after install" just fine, all that does is stop it from running directly after installation. If you run the checker does it say that the watchdog is running or not?

**Comment by AlienJ555** [comment]
When I enable "Don't run miner after install", I use checker and watchdog is No, but I disable "Don't run miner after install", it shows Yes.

**Comment by UnamSanctam** [comment]
Hmm well all it does is disable this line in this if:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/a0732ef1015515c405d343a29fc4f5faac5e3dbb/SilentCryptoMiner/Resources/Code/Program.cs#L136
So it shouldn't have anything to do with the watchdog. Do you have "Run Watchdog in Memory" disabled or something?

**Comment by AlienJ555** [comment]
I enable "Run Watchdog in Memory".

**Comment by UnamSanctam** [comment]
Oh, I guess it might not be able to find the miner or something? Since it runs as System. Though it does work for me in my tests mysteriously.

**Comment by UnamSanctam** [comment]
Can you try with this and see https://anonfiles.com/t6k1t5Zax4/Silent_Crypto_Miner_Builder_zip? That will reinstall it as the System user on reboot so you might have to reboot it twice (since it reinstalls on first reboot).

**Comment by AlienJ555** [comment]
> Can you try with this and see https://anonfiles.com/t6k1t5Zax4/Silent_Crypto_Miner_Builder_zip? That will reinstall it as the System user on reboot so you might have to reboot it twice (since it reinstalls on first reboot).

Yes, It works well now. Thank you For your help!

**Comment by golxd** [comment]
> Can you try with this and see https://anonfiles.com/t6k1t5Zax4/Silent_Crypto_Miner_Builder_zip? That will reinstall it as the System user on reboot so you might have to reboot it twice (since it reinstalls on first reboot).

I didn't understand, why watchdog didn't work? this is an isolated case or need use this version https://anonfiles.com/t6k1t5Zax4/Silent_Crypto_Miner_Builder_zip

**Comment by UnamSanctam** [comment]
It's because the "Run as System" and the new code to prevent reinstallation interfered with the watchdog code to find the miner, since it uses the current user to find the location. For me the normal one works fine (hence why it was released) but you can try that as well, I also updated the builder in the "Release" in the meantime.
