### ISSUE TITLE
startup 

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#659]
new version sometimes when restart PC just not working anymore in this case i lose PC

there any version fix it this from version 2.3.0 also

maybe there bug or gelitch i really dont know but there something wrong

**Comment by UnamSanctam** [comment]
The installation code is the same in all the versions except the "Run as System" feature, so you could try disabling that.

**Comment by tarekxxx** [comment]
> The installation code is the same in all the versions except the "Run as System" feature, so you could try disabling that.

**Comment by tarekxxx** [comment]
i try it same not open in startup

**Comment by UnamSanctam** [comment]
Try it with the example settings then (at the top of the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki), I've installed it thousands of times in my tests and it has always worked.

**Comment by tarekxxx** [comment]
in old versions i dont have any problems with start up or anything in program
but new version there something wrong like startup not enabled in program

**Comment by UnamSanctam** [comment]
You'd probably have to show a video of it happening, not once has that ever happened to me so there's nothing really for me to fix unless I can see it happening.

**Comment by tarekxxx** [comment]
![Screenshot (96)](https://user-images.githubusercontent.com/20240556/164949026-97b5a8ef-3880-463b-a35c-8f6a4bf165f1.png)

here we go after restart and been waiting 15 mins

**Comment by UnamSanctam** [comment]
Run the checker and post what it returns.

**Comment by tarekxxx** [comment]
![Screenshot (97)](https://user-images.githubusercontent.com/20240556/164949573-81f9ba5c-ff91-46fd-b9d0-1a840a3a58eb.png)

**Comment by UnamSanctam** [comment]
Are you installing it as administrator or not? And if not are you on the same account as when you installed it?

**Comment by tarekxxx** [comment]
> Are you installing it as administrator or not? And if not are you on the same account as when you installed it?

i turn off start up run as administrator and yea  in same user i installed it

**Comment by tarekxxx** [comment]
i turn off it because you say try with turn off 

> > The installation code is the same in all the versions except the "Run as System" feature, so you could try disabling that.

**Comment by UnamSanctam** [comment]
I mean disable "Run as System" not "Run as Administrator".

**Comment by tarekxxx** [comment]
![Screenshot (98)](https://user-images.githubusercontent.com/20240556/164950129-93ab86e5-099e-45a8-93d8-7456f4464847.png)
 i do

**Comment by UnamSanctam** [comment]
Can you check the registry and the Task Scheduler to see if you can find the startup entries?
You can find the regsitry entries here. `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`
And in the Task Scheduler they are just in the first library on the left.

**Comment by tarekxxx** [comment]
i cant get current place for Task Scheduler

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run i see this directory empty
![Uploading Screenshot (99).png…]()

**Comment by tarekxxx** [comment]
i cant get current place for Task Scheduler

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run i see this directory empty
![Screenshot (99)](https://user-images.githubusercontent.com/20240556/164976102-8ad1e6d3-152b-4242-b70e-bf4388e62046.png)

**Comment by UnamSanctam** [comment]
Are you running the miner as administrator or as a normal user? If you run it as an administrator then it will be in the Task Scheduler and if not then it will be in the registry.

**Comment by tarekxxx** [comment]
> ![Screenshot (98)](https://user-images.githubusercontent.com/20240556/164950129-93ab86e5-099e-45a8-93d8-7456f4464847.png) i do

run as system off then run it normal 

and i dont see anything there
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run

**Comment by UnamSanctam** [comment]
Hmm it added it just fine for me. Are you sure you're not starting the file as an administrator.
<img src="https://user-images.githubusercontent.com/10323655/164978234-1c20781c-f568-4d46-9af0-2cb7b2b3e5d3.png">

**Comment by tarekxxx** [comment]
> Hmm it added it just fine for me. Are you sure you're not starting the file as an administrator. ![](https://user-images.githubusercontent.com/10323655/164978234-1c20781c-f568-4d46-9af0-2cb7b2b3e5d3.png)

yea i run double click sir let me remove miner with anti viurs and reinstall it

**Comment by tarekxxx** [comment]
![Screenshot (102)](https://user-images.githubusercontent.com/20240556/164978470-22b7a6a1-604f-498a-a182-d669bb5ea247.png)

oh finally after remove it with anti viurs even webpanel working god sorry my fault i was need to remove it completely then reinstall it
