### ISSUE TITLE
my panel is connected correctly but  

### ISSUE THREAD

**Issue by ahmedjafari** [UnamSanctam/SilentCryptoMiner#660]
my panel is connected correctly but  only XMR hashrate showing not ETH 
i cant see the  eth miner on my panel i dont know why

**Comment by UnamSanctam** [comment]
If you check the XMR miner (press '+' next to them) what GPUs do they have? Do any of them have a GPU that can mine? Since if they don't then the ETH/ETC miner won't start (since there's no CUDA/OpenCL to use).

**Comment by ahmedjafari** [comment]
only Type xmrig showing in my panel 
my test gpu is 1660 super ( working fine but not showing in panel but  showing in pool )

**Comment by ahmedjafari** [comment]
unam i am your fan and friend from very long time ago what did happin to our discord server and is there is newer one ?

**Comment by UnamSanctam** [comment]
> only Type xmrig showing in my panel my test gpu is 1660 super ( working fine but not showing in panel but showing in pool )

Can you start the checker on your test computer and post it here? So that I can make sure that you entered the endpoint URL into the ETH miner as well (sometimes people forget or enter into the wrong field)?

> unam i am your fan and friend from very long time ago what did happin to our discord server and is there is newer one ?

I got banned from Discord so I don't know what happened to the server. Some have made a Telegram server but currently I can't access my Telegram.

**Comment by ahmedjafari** [comment]
https://ibb.co/nDnyxnN

**Comment by ahmedjafari** [comment]
am mining at the moment  it showin in my pool  but not in the panel

**Comment by UnamSanctam** [comment]
Does the XMR miner on that specific computer show in the panel?

**Comment by ahmedjafari** [comment]
its same api link working 200%  i tried once with https and one without http  

yes its showing  when i mine xmr  and showing the hashrate all fine with xmr

**Comment by UnamSanctam** [comment]
Hmm, the API code for both miners are the same. I just tried mining to your panel with my computer, does the miners show up?

**Comment by ahmedjafari** [comment]
it did show up as  XMR only 
https://ibb.co/j80cdcp

**Comment by ahmedjafari** [comment]
is the issue something with hosting ?

**Comment by UnamSanctam** [comment]
Could be, I just tried it myself on my panel and both of them appear in mine.

**Comment by ahmedjafari** [comment]
alright done i will try to change some setting file permissions or php version in the web hosting and i might try other one   ;) and get back with feedback

**Comment by ahmedjafari** [comment]
can you tell me the php version and file permissions

**Comment by ahmedjafari** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
It's PHP 8.0 and file permissions haven't been changed from the default (can't check right now). But most likely that's not the issue, can you try making a miner with **only** an ETH miner? In case maybe your hosting has some limit on connections (since the miners will usually call the API at about the same time since they were started at the same time).

**Comment by ahmedjafari** [comment]
i did make it eth but only mining  not showing in panel

**Comment by Redkits02** [comment]
> unam i am your fan and friend from very long time ago what did happin to our discord server and is there is newer one ?

https://t.me/MinersCommunity
there's the unofficial/official telegram server, made by people from the old discord server, come and say "hi"
but as unam mentioned, he doesn't have access to telegram at the moment, so the only way to stay in touch is github
