### ISSUE TITLE
Show process causing stealth in the panel

### ISSUE THREAD

**Issue by zozidalom** [UnamSanctam/SilentCryptoMiner#661]
I think it would be great to show the process causing the miner to be in stealth mode in the panel, what do you think?

**Comment by UnamSanctam** [comment]
It's technically possible, though it would require another JSON field for that which isn't fun. And you could have multiple stealth programs open but it will  only check until one is found and return though that's not too bad. I'm currently implementing it showing the name of the currently focused window which could serve a similar purpose as well.

**Comment by zozidalom** [comment]
Okay, thank you for your reply.
