### ISSUE TITLE
SILENT BTC MINER

### ISSUE THREAD

**Issue by MJMODZZ** [UnamSanctam/SilentCryptoMiner#662]
Whats about a silent bitcoin miner? Bitcoin is used as Payment really often and the most famous crypto righ now.

**Comment by rrrroo** [comment]
Btc isn't mined efficiently by cpu or gpu, it need to be mined by dedicated hardware (ASICS). The average computer will not mine any significant amount of btc. A silent btc miner doesn't make a lot of sense.
