### ISSUE TITLE
Most profitable?

### ISSUE THREAD

**Issue by Programmer1603** [UnamSanctam/SilentCryptoMiner#663]
Does smb know what the most profitable supported coin is to mine on gpu/cpu?
Any suggestions?

**Comment by rnesheik** [comment]
ergo is easy to mine with gpu, but in silent miner there is no

**Comment by UnamSanctam** [comment]
For GPU the best in terms of profit is ETH but that's if you have a lot of good GPUs, so generally ETC is better to mine. For CPU most coins have a similar profitability, so most people just mine XMR or RTM unless they want to find some altcoin they like.
