### ISSUE TITLE
Miner active in the panel but no hashrate

### ISSUE THREAD

**Issue by zozidalom** [UnamSanctam/SilentCryptoMiner#664]
![image](https://user-images.githubusercontent.com/24374345/165000429-9268695c-76e1-40a5-b717-dbca16bd0184.png)
What might cause this?

**Comment by UnamSanctam** [comment]
Many things could cause it, a) a CPU with a low core amount and a low enough "Max CPU" or "Idle CPU" percentage b) some problem in the connection to herominers c) some problem in xmrig. I would first try changing the pool in the "Configurations", it's the easiest thing to test before doing anything else.
