### ISSUE TITLE
Add Scala token to minable list

### ISSUE THREAD

**Issue by fl1ckert** [UnamSanctam/SilentCryptoMiner#667]
Sup, Unam, could you please add new token to the minable list. Here is link https://pool.scalaproject.io/?#getting_started
Looking forward to hearing from you, have a great day :)

**Comment by fl1ckert** [comment]
What do you think about this?

**Comment by UnamSanctam** [comment]
I'm not really planning to add the Panthera algorithm at the moment but I can look into adding it.
