### ISSUE TITLE
Help me set it up pls

### ISSUE THREAD

**Issue by Proffesionalez** [UnamSanctam/SilentCryptoMiner#668]

**Comment by Proffesionalez** [comment]
i dont know where to get my pool,  and whats the point of remtoe configuration, + should i change smth in json?

**Comment by UnamSanctam** [comment]
It depends on what pool you want to use, there are tons of them such as 2miners, nanopool, ethermine, MoneroOcean, etc. The point of "Remote Configuration" is that you can change the configuration even after building the miner. Let's say you have 10 miners, then if you want to change the pool you'd have to rebuild the miner with that pool and reinstall it on those computers, but if you have a "Remote Configuration" for them then you can just change the pool there and it will change in all the miners as well.

**Comment by Proffesionalez** [comment]
> It depends on what pool you want to use, there are tons of them such as 2miners, nanopool, ethermine, MoneroOcean, etc. The point of "Remote Configuration" is that you can change the configuration even after building the miner. Let's say you have 10 miners, then if you want to change the pool you'd have to rebuild the miner with that pool and reinstall it on those computers, but if you have a "Remote Configuration" for them then you can just change the pool there and it will change in all the miners as well.

Nice, so if i want to have a etherium and a monero miner in 1 file i just click add miner x2 times and choose what for?

**Comment by UnamSanctam** [comment]
Yes there are some example settings at the top of the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki you can download and check to see how it's set up.

**Comment by Proffesionalez** [comment]
> Yes there are some example settings at the top of the wiki https://github.com/UnamSanctam/SilentCryptoMiner/wiki you can download and check to see how it's set up.

thx, everything is working 1 thing is not tho? in the website it says it stopped? status: stopped.. but i didnt close the miner in any way

**Comment by UnamSanctam** [comment]
It means that it couldn't connect to the pool, which one does it say that for?

**Comment by Proffesionalez** [comment]
and . why does it say 0h/s

**Comment by Proffesionalez** [comment]
another problem just now, my friends miner has suddenly stopped as well?

**Comment by Proffesionalez** [comment]
![image](https://user-images.githubusercontent.com/102620830/165544488-fff42c17-b22e-4004-9a0d-5c49fb3022b7.png)

here

**Comment by UnamSanctam** [comment]
You forgot to specify the port for the pool. It should be eu1.ethermine.org:4444 for non-SSL and eu1.ethermine.org:5555 for SSL.

**Comment by Proffesionalez** [comment]
OH holly shit thanks!¨

**Comment by Proffesionalez** [comment]
Yo, what port do i use for stratum connection

**Comment by UnamSanctam** [comment]
Stratum is non-SSL so it would be 4444.

**Comment by Proffesionalez** [comment]
for all pools?

**Comment by UnamSanctam** [comment]
No it depends on the pool, they always say somewhere on their websites.

**Comment by Proffesionalez** [comment]
yo, what do i write in remote configuration? 

-ps it told me in website it was 4444 so ye thx.

**Comment by UnamSanctam** [comment]
You can use the JSON from the builder, if you enter all your settings then you can find it in the "JSON".

**Comment by Proffesionalez** [comment]
ye but waht does remote configuration do? when i click the button it gives me a line to enter some characters?

**Comment by UnamSanctam** [comment]
It allows you to change the settings remotely https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration, you'd enter some sort of URL to something like pastebin where your configuration is stored.

**Comment by Proffesionalez** [comment]
yo why is the hashrate still 0

**Comment by Proffesionalez** [comment]
got it working

**Comment by UnamSanctam** [comment]
It's running fine now? Otherwise send a screenshot, preferably after pressing the '+' before the miner ID (so that all the data is visible).

**Comment by Nobellium1** [comment]
@UnamSanctam 2miners or ethermine? Which one do you recommend? Also what's the best pool in your opinion?

**Comment by UnamSanctam** [comment]
> got it working just fine! should i be worried about any of the settings? like windows updater is red or smth, oh and what about start on startup ik like 5 months ago it wasnt working.

"Disable Windows Update" is red due to the effects of it being irreversible, so it's red to warn users from recklessly enabling it https://github.com/UnamSanctam/SilentCryptoMiner/wiki#disable-windows-update. Startup should work just fine, the problem before was that people weren't changing the default "File Name" in the "Startup" tab and the default one had been blocked by some anticheats (the "Microsoft" folder) for whatever reason.

> @UnamSanctam 2miners or ethermine? Which one do you recommend? Also what's the best pool in your opinion?

At the moment 2miners since ethermine has banned so many countries, to be fair there's not really any pool I like at the moment but 2miners have become a lot better from what I've seen. Previously there used to be some issues with their servers but I haven't seen any of that for a few months now.

**Comment by Proffesionalez** [comment]
last question i think before am set to the road, is ethermine a good pool and, it directly gives $ to my wallet? and if i use eu.pool what than can a person from asia still use it?

**Comment by UnamSanctam** [comment]
Sure they're good though lately they've been banning some countries like Russia so some have switched to others like 2miners, it sends you the ETH after you reach the minimum payout, you can also choose to get payed on the polygon network for reduced fees and minimum payout threshold. And yes miners from Asia can still use the EU pool, only difference should be some more latency.

**Comment by Proffesionalez** [comment]
damn thx
