### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#67]
If we bind both ETC and ETH And if the person running it has, for example, 5gb gpus, which will work?

**Comment by UnamSanctam** [comment]
Both, but most likely only ETC will be able to mine (since Windows takes 10-20% of the VRAM). It's a lot more recommended to just do something like ETC (since it uses the least amount of VRAM of ETH/ETC) and then change any good GPU to ETH with the web panel.

**Comment by DogusCyk** [comment]
both will work but will it just mine etc ?

**Comment by UnamSanctam** [comment]
Both will be running but since it only has 5GB then only one would be able to mine. But if someone had 12GB then both would mine, which is why it's better to use the web panel to change any miner to miner whatever coin you want it to.
