### ISSUE TITLE
watchdog no running

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentCryptoMiner#670]
watchdog no running

**Comment by Toxenskiy** [comment]
when found in memory

**Comment by UnamSanctam** [comment]
Try redownloading the builder, I reuploaded it maybe 5-10 minutes after first release due to a Visual Studio bug (it cached some wrong code that caused the watchdog to not find the miner).

**Comment by Toxenskiy** [comment]
the problem is that the watchdog does not replace the memory after restarting the pc

**Comment by UnamSanctam** [comment]
What do you mean?

**Comment by Toxenskiy** [comment]
when you first start the miner, the "watchdog" function works properly, but after rebooting, "watchdog" does not start

**Comment by UnamSanctam** [comment]
Yes, are you compiling it yourself or using the pre-built builder?

**Comment by Toxenskiy** [comment]
+

**Comment by Toxenskiy** [comment]
I create it myself, but there were no errors
