### ISSUE TITLE
Not an Issue just want to ask something

### ISSUE THREAD

**Issue by kinggskral** [UnamSanctam/SilentCryptoMiner#671]
Hey Unam first off al this is not an issue but here is the only way I can contact you so this is why I am opening this.
Do you have any information about FatRat, I am not familiar with linux systems etc. If i understood correctly it makes rats(its called metasploit i guess) with 90% ud rate. I am now thinking first downloading fatrat, then executing miner from it. Do you have any idea? Does fatrat make 90% ud files?

**Comment by UnamSanctam** [comment]
You can try it but most likely it's not undetected anymore, due to it being public it's probably detected.

**Comment by kinggskral** [comment]
I dont know if its any different than windows made viruses but, when I create the exe in kali could it be making hashed codes for every person or so? Because I think its still been used now, and I havent seen any issue saying its detected. If you want to have a quick look here is the github
https://github.com/screetsec/TheFatRat

**Comment by kinggskral** [comment]
Hahahah, i was wrong about that sorry. But it might be an option instead of crypting it maybe. Do you have any experince of Kali applications?

**Comment by UnamSanctam** [comment]
Well sure, but try choosing option 2 in the backdoor creator and see what detections you get with that.
