### ISSUE TITLE
Virus in Builder?

### ISSUE THREAD

**Issue by ValeraKamenshik** [UnamSanctam/SilentCryptoMiner#678]
Hello, I am studying this program and having familiarized myself with the principle of operation, I decided to check the designer for viruses before launching it and the popular VirusTotal service detected a trojan... Please explain this

**Comment by ValeraKamenshik** [comment]
I'll leave this topic open so people with similar questions can see the answer.

**Comment by Zeevsq1** [comment]
You're an idiot. You download a hidden miner to distribute to other PCs and check if there are viruses there. If you need a miner for yourself, download a regular miner. If you do not understand, each of you who will upload the miner to virustotal increases its number of detections and makes it ineffective as a hidden miner. WHY DO YOU NEED HIM?

**Comment by Zeevsq1** [comment]
you really Valera.
use these sites
https://antiscan.me https://kleenscan.com
