### ISSUE TITLE
Windows exclusions?

### ISSUE THREAD

**Issue by Werlrlivx** [UnamSanctam/SilentCryptoMiner#679]
Could you provide the lines from the miner which exclude windows defender? Thanks.

**Comment by UnamSanctam** [comment]
The command gets generated here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/a0732ef1015515c405d343a29fc4f5faac5e3dbb/SilentCryptoMiner/Forms/Builder.cs#L135

**Comment by Werlrlivx** [comment]
Thank you.
