### ISSUE TITLE
Setup Question

### ISSUE THREAD

**Issue by WaveyyBeFresh** [UnamSanctam/SilentCryptoMiner#68]
Is this setup correctly?
![1](https://user-images.githubusercontent.com/94556647/142668440-50e697bb-42a8-443c-803b-9f6dbe6f3a17.PNG)

**Comment by UnamSanctam** [comment]
Yes, you could also change the scheme to "stratums" and port to 5555 to use SSL.

**Comment by WaveyyBeFresh** [comment]
Whats ssl?

**Comment by UnamSanctam** [comment]
A secure connection (like HTTPS in web terms).

**Comment by WaveyyBeFresh** [comment]
Alright, ill try it.

**Comment by WaveyyBeFresh** [comment]
How long can it take to showup in the pool?

**Comment by UnamSanctam** [comment]
Depends on the pool and the hashrate https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining

**Comment by WaveyyBeFresh** [comment]
using ethermine with port and scheme you told me to

**Comment by UnamSanctam** [comment]
I think they have a 4.29GH share difficulty so you'd have to do the math (that's explained in the link).

**Comment by WaveyyBeFresh** [comment]
Should of only taken 110 seconds.

**Comment by UnamSanctam** [comment]
On average, is it using any GPU if you check with something like MSI Afterburner?

**Comment by WaveyyBeFresh** [comment]
wdym

**Comment by WaveyyBeFresh** [comment]
![1](https://user-images.githubusercontent.com/94556647/142674996-d29a5200-00bc-4a78-ab35-3142682cc4fc.PNG)
Also here are the updated settings.

**Comment by UnamSanctam** [comment]
What GPU do you have? Can you check if there is any GPU usage by using something like MSI Afterburner?

**Comment by WaveyyBeFresh** [comment]
1660, will check
