### ISSUE TITLE
I’m using ethermine.org and it showing 0/0 workers

### ISSUE THREAD

**Issue by Virtualmachine39** [UnamSanctam/SilentCryptoMiner#680]
Another issue. But I’m using ethermine.org and I’m looking at the dashboard and it shows 0/0 workers. I did a test run on a virtual machine and it still didn’t show any workers. Is because my gpu isn’t mining/working on anything?

**Comment by Werlrlivx** [comment]
on a virtual machine you probaly dont have a gpu and workers appear after about 10-30minutes

**Comment by UnamSanctam** [comment]
Yes like @Werlrlivx said you most likely don't have a GPU in your Virtual Machine, the pool will only show a miner when it finds a share (and thus it requires a GPU).
