### ISSUE TITLE
Is there a cpu silent miner

### ISSUE THREAD

**Issue by Virtualmachine39** [UnamSanctam/SilentCryptoMiner#681]
I've seen videos on a cpu silent miner but I do not see where it is. I need help. If you can link it that would be appreciated!

**Comment by UnamSanctam** [comment]
This has both CPU and GPU miners, if you select something like RandomX (Monero) or something similar then that is a CPU miner (though it optionally also has GPU support).

**Comment by Virtualmachine39** [comment]
I do not see a cpu option for the silent miner. I might be blind lol
