### ISSUE TITLE
old ver

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentCryptoMiner#682]
Remote configuration ETC on the old version
right?

[main]
connection=stratums://0x68f20f70a42cb37276b57e7cabe99065c596c701.name@etc.2miners.com:11010
etc=true

**Comment by UnamSanctam** [comment]
Depends which version, in all versions of the "SilentCryptoMiner" you use `"algo": "etchash"` but in the old "SilentETHMiner" you use `etc= true`.

**Comment by golxd** [comment]
ty

**Comment by golxd** [comment]
yes, old "SilentETHMiner" works for me ETH
```
[main]
connection=stratum://***************************************.work@eth-eu1.nanopool.org:9999
etc=false
```

but not working etc
```
[main]
connection=stratums://*************************************.name@etc.2miners.com:11010
etc=true
```

maybe something else needs to be added?

**Comment by golxd** [comment]
tell me pls name obfuscator which you have recommended 1+- year ago

**Comment by UnamSanctam** [comment]
ConfuserEx2?

**Comment by golxd** [comment]
no, you then found a crack for it, I don't remember name

**Comment by UnamSanctam** [comment]
Oh, .NET Reactor?

**Comment by golxd** [comment]
yes) thanks
