### ISSUE TITLE
How can I merge this virus?

### ISSUE THREAD

**Issue by exaless** [UnamSanctam/SilentCryptoMiner#684]
I created the virus, but how can I put it in an application?

**Comment by UnamSanctam** [comment]
If you want to merge the miner with another program then use a file binder, there are many free ones online.

**Comment by exaless** [comment]
I couldn't find the program, can you help me? Thank u.

**Comment by UnamSanctam** [comment]
There are many different file binder programs just search for `file binder github` on Google, you can try different ones until you find one that works well for you.

**Comment by exaless** [comment]
Thank u very much!

**Comment by ahmedjafari** [comment]
https://github.com/UnamSanctam/UnamBinder 
is the best

**Comment by exaless** [comment]
@ahmedjafari thank u bro. i will use it

**Comment by exaless** [comment]
Is there a bypass you recommend to hide the virus?
