### ISSUE TITLE
install as

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentCryptoMiner#686]
`Changed miner to install into Program Files if installed with "Run as System" enabled`
does this mean that the miner will not be installed in temp/approfile/appdata?

**Comment by UnamSanctam** [comment]
When "Run as System" is enabled yes, because AppData depends on the user which isn't good for that.

**Comment by golxd** [comment]
in that case function "Add Defender Exclusions" won't add our miner in "Program Files" ?

**Comment by UnamSanctam** [comment]
"Add Defender Exclusions" also excludes the SystemDrive folder so it will still add an exclusion for the miner, though `$env:ProgramFiles` could be added as well into the exclusion list.

**Comment by golxd** [comment]
tell me please, in terms of detections and work doesn't matter "Run as System" or not

**Comment by UnamSanctam** [comment]
No it won't matter, though "Run as System" will make it harder for the user to find it.
