### ISSUE TITLE
Ravencoin Question

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#69]
So im trying to use RVN kawpow in the silent crypto miner but it doesnt show the GPU usage but only CPU usage, i thought mining it on CPU was useless?

**Comment by UnamSanctam** [comment]
You can't mine RVN with CPU, it's not implemented so if it's using CPU then you have the wrong algorithm selected.

**Comment by Brainshot** [comment]
https://i.imgur.com/Eyo9oBB.png

**Comment by Brainshot** [comment]
https://i.imgur.com/je8GcpC.png

**Comment by Brainshot** [comment]
I am using your silent crypto miner, but your GPU option has no usage to change just like for ETC or ETH miners

**Comment by Brainshot** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
You don't have GPU enabled but it cannot use any CPU (since it doesn't exist). You cannot change the GPU usage since it's using XMRig.

**Comment by Brainshot** [comment]
> 

I dont understand please check the imgur images your silent crypto miner RVN Kawpow i am trying to mine RVN

also if its using XMRig will it still be able to mine normal ? for example if i have a 2060 will it still mine 16.33 MH/s ?

**Comment by UnamSanctam** [comment]
Enable GPU mining, but if it's saying that it's using CPU then it's wrong. A 2060 will get 18MH/s with the KawPow algorithm, you can use https://whattomine.com/coins to see what hashrate and profit you get for each different GPU.

**Comment by Brainshot** [comment]
> Enable GPU mining, but if it's saying that it's using CPU then it's wrong. A 2060 will get 18MH/s with the KawPow algorithm, you can use https://whattomine.com/coins to see what hashrate and profit you get for each different GPU.

Alright thanks alot brother for answering the questions! i was just worried, but will the GPU option use 100% ? i am just worried they wont be even move their computer mouse O_O

**Comment by UnamSanctam** [comment]
Shouldn't use 100% (default settings is to use less) but I can't be sure about AMD since I don't have an AMD card.
