### ISSUE TITLE
Miner Eror

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#695]
Good afternoon Unam. In the web panel, I see some miners with the inscription Eror, i create a configuration with a different pool and the miner with an error starts working fine, but after a while it returns to the default configuration and the message appears again Eror.
I want to know why miners that work with an error, after switching through the configuration created in the web panel, they work normally for a certain time, and then return to the previous configuration again and work with an error?

**Comment by UnamSanctam** [comment]
Error means that they currently don't have an active pool so they could've lost connection, only reason it would ever "return" to the default configuration is if they lose connection with the pool in the web panel configuration (they go to the failover pool which is the builder pool). It could also be moving to the "Remote Configuration" pool if you use that.

**Comment by masterjek** [comment]
I understand correctly that the reason may even be the hosting on which the panel is installed. If, for example, hosting slows down and the miner cannot communicate with the panel normally, then it switches to the default configuration.

**Comment by UnamSanctam** [comment]
No it won't switch the configuration away from the web panel configuration if it can't connect, that's to prevent that sort of thing from happening, the web panel configuration will just stay in the miner until the next restart. But the "Remote Configuration" (if you have one) will eventually "take priority" over the web panel if it can't connect to it for long enough.

**Comment by masterjek** [comment]
Thanks for the help.
