### ISSUE TITLE
Miner error

### ISSUE THREAD

**Issue by Boggylol** [UnamSanctam/SilentCryptoMiner#699]
Hi, whenever I run the miner with debug mode on these errors show:

![image](https://user-images.githubusercontent.com/94930450/166231048-8e93f3c8-2b50-492f-a11a-ce982e50be6b.png)

![image](https://user-images.githubusercontent.com/94930450/166231064-f1d965be-cad6-4367-a3e0-66bd8b50f43e.png)

Any help would be appreciated

**Comment by UnamSanctam** [comment]
Sounds like maybe the WMI scope can't be connected to on your computer, can you try rebuilding it and try again?

**Comment by Boggylol** [comment]
I've tried that, but it still doesn't seem to work

**Comment by UnamSanctam** [comment]
Do you use some special kind of Windows? I have never heard of the namespace "\root\cimv2" being invalid.

**Comment by Boggylol** [comment]
No, its just a normal windows install. I might try resetting it

**Comment by UnamSanctam** [comment]
You can try restarting the builder and then build one with these settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite (and enable DEBUG) to see if it still happens. Otherwise repairing/resetting Windows might be a good idea.

**Comment by Boggylol** [comment]
The settings still don't work, I'll try running it on my laptop

**Comment by tarekxxx** [comment]
![Capture](https://user-images.githubusercontent.com/20240556/166970372-d5a395a6-3f18-4c0d-b109-3b5d8002b293.PNG)
i faced this problem and miner not working in this PC i dont knnow why i enabled rootkit

**Comment by tarekxxx** [comment]
> That error doesn't really matter, the Watchdog just saying that it can't write the miner to the disk since it's already running. If it's not launching then some setting is wrong, you can always test if it's your settings that are the problem by using the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings, if it does work with the example settings then the problem is your own settings.

i can do worker name like this with {COMPUTERNAME}~ghostrider ?

**Comment by UnamSanctam** [comment]
Yes that should work.
