### ISSUE TITLE
I don't know this error

### ISSUE THREAD

**Issue by suckma420** [UnamSanctam/SilentCryptoMiner#7]
Hey, can you help me with this? The miner won't load on my PC
![Capture](https://user-images.githubusercontent.com/70838931/140851939-68537698-d583-427d-9f64-79e3c1284702.PNG)

**Comment by suckma420** [comment]
And I chosen explorer but don't know why it's nslookup

**Comment by UnamSanctam** [comment]
Yes that has to do with the "Hide File" option I believe that I removed in the new version v2.0.1, can you update it and test? It's injecting as nslookup since you have the rootkit enabled, it will hide all rootkit processes from everything.

**Comment by suckma420** [comment]
This is the latest version

**Comment by suckma420** [comment]
I'm using a xmrig-proxy if you wanted to know, dunno if its causing this

**Comment by UnamSanctam** [comment]
Are you sure that file isn't left from a previous version? It's a hidden file, can you go to %AppData%\Microsoft and then open CMD? After opening CMD type `del services.exe /a:h` and that file should disappear.

**Comment by suckma420** [comment]
It's says cannot find the file because I only built the miner with version 2.0.1, or I think that the miner haven't been extracted

**Comment by suckma420** [comment]
If you wanted, I can give you the miner file
https://anonfiles.com/Fcu6KdT8u8/test_exe

**Comment by UnamSanctam** [comment]
No and old miner is there from a previous version, which is why it gives the error that it cannot be changed. Can you start a CMD as administrator and run `del "%AppData%\Microsoft\services.exe" /a:h` ?

**Comment by suckma420** [comment]
Could Not Find C:\Users\...\AppData\Roaming\Microsoft\services.exe

**Comment by suckma420** [comment]
Let me check in that folder to find anything sus

**Comment by suckma420** [comment]
hmm, why is there services there but I can't delete it in cmd?

**Comment by UnamSanctam** [comment]
Run all the uninstallers from all your older builds if you haven't already.

**Comment by suckma420** [comment]
![Uploading Capture.PNG…]()

**Comment by UnamSanctam** [comment]
Remove the /a:h, that is only for hidden files but it looks like that file isn't hidden. That error could have just appeared if you were unlucky (the watchdog tried to write the file while it's already in progress of starting) I suppose.

**Comment by suckma420** [comment]
hmm, i ran the uninstaller but services.exe is still there

**Comment by suckma420** [comment]
And also, does the windows defender bypass works?

**Comment by UnamSanctam** [comment]
Yes it works well.

**Comment by suckma420** [comment]
Does the downloader have the bypass because I planned to bind it with the legit file so the viewer don't ask me why it won't work

**Comment by suckma420** [comment]
I have ran the checker and still nothing

**Comment by suckma420** [comment]
Can you help me setup the proxy if maybe that's the culprit?

**Comment by UnamSanctam** [comment]
No the proxy doesn't have anything to do with it. Both the downloader and the binder has the bypass built-in though you should also enable it on the miner in that case. I'm going to update the binder and downloader now since the miner is "done".

If you have rootkit enabled then it's not possible to use the checker or anything else to see if it's mining, since it has hooked into everything and is hiding those processes. The best method to see if it's mining with the rootkit enabled is to use the web panel.

**Comment by suckma420** [comment]
oh, and I am using tls

**Comment by suckma420** [comment]
Do I have to do anything to the proxy?

**Comment by suckma420** [comment]
Do I have to do anything to the proxy?

**Comment by UnamSanctam** [comment]
No, in the miner just enter the proxy IP and port as the pool and then enable "Nicehash Mining" in the "Mining" settings and then enable SSL/TLS if you use that in the proxy.

**Comment by suckma420** [comment]
yeah, i have done all of that but the proxy isn't reporting any hashes

**Comment by suckma420** [comment]
* ABOUT        xmrig-proxy/6.15.0-mo1 gcc/9.3.0
 * LIBS         libuv/1.34.2 OpenSSL/1.1.1f
 * MODE         nicehash
 * POOL #1      gulf.moneroocean.stream:10128 coin DERO
 * BIND #1      0.0.0.0:10128
 * BIND #2      0.0.0.0:10032
 * COMMANDS     hashrate, connections, verbose, workers
[2021-11-09 03:10:23.404]  proxy    speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s
[2021-11-09 03:10:46.615]  proxy    speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s
[2021-11-09 03:11:09.265]  proxy    0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 0 (max 0) +0/-0
[2021-11-09 03:11:34.640]  proxy    speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s
[2021-11-09 03:12:09.327]  proxy    0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 0 (max 0) +0/-0
[2021-11-09 03:12:28.733]  proxy    speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s
[2021-11-09 03:13:09.386]  proxy    0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 0 (max 0) +0/-0
[2021-11-09 03:13:10.349]  proxy    speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s
[2021-11-09 03:13:11.103]  proxy    speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s
[2021-11-09 03:13:12.230]  proxy    speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s
[2021-11-09 03:14:09.446]  proxy    0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 0 (max 0) +0/-0

**Comment by UnamSanctam** [comment]
Is the xmrig-proxy on the same computer as you're mining on? If it is then try entering `127.0.0.1:10128` as the pool in the miner.

**Comment by suckma420** [comment]
No, its on another one

**Comment by suckma420** [comment]
and the TLS port 10032

**Comment by UnamSanctam** [comment]
Have you port forwarded everything correctly? Can you try connecting with a normal xmrig and see if it works?

**Comment by suckma420** [comment]
OK, wait me a bit

**Comment by suckma420** [comment]
hmm, the proxy is saying [2021-11-09 03:26:45.200]  net      gulf.moneroocean.stream:10128 error: "Unauthenticated", code: -1 with ["astrobwt","cn-heavy/xhv","cn/half"] algo and {"astrobwt":1000.0,"cn/half":1.0,"cn-heavy/xhv":10.0} algo_perf
[2021-11-09 03:26:45.200]  net      0000 no active pools, stop
So its prob me, can you help me fix?

**Comment by UnamSanctam** [comment]
If it says that then your connection settings to the pool are incorrect.

**Comment by suckma420** [comment]
But I think its correct

**Comment by suckma420** [comment]
I'm running it in an VPS

**Comment by suckma420** [comment]
Do I have to use tls if I wanted to connect to the pool?

**Comment by UnamSanctam** [comment]
No, since you are using the non-SSL port, but since you are trying to mine with the AstroBWT algorithm have you added that algorithm to the end of your worker name as it is specified on their website? In the password field for the pool add `WorkerName~astrobwt` if you haven't already

**Comment by suckma420** [comment]
In the proxy setting I have chosen astrobwt and dero as coin already

**Comment by UnamSanctam** [comment]
And you have added it into the password field like I said above as well?

**Comment by suckma420** [comment]
ok, I will check again

**Comment by suckma420** [comment]
It still says connection canceled

**Comment by suckma420** [comment]
`[2021-11-09 10:55:27.081]  net      140.238.54.60:10032 connect error: "operation canceled"
[2021-11-09 10:55:52.273]  net      140.238.54.60:10032 connect error: "operation canceled"`

**Comment by UnamSanctam** [comment]
To the pool from the proxy or from a miner to your proxy?

**Comment by suckma420** [comment]
It's me to the proxy and nothing its in the proxy

**Comment by UnamSanctam** [comment]
Can you send all the configurations (you can censor the wallet addresses and such if you want to)?

**Comment by suckma420** [comment]
Which configuration? The proxy?

**Comment by UnamSanctam** [comment]
Yes.

**Comment by suckma420** [comment]
`{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 10032,
            "tls": true
        },
        {
            "host": "::",
            "port": 10032,
            "tls": true
        }
    ],
    "colors": true,
    "title": true,
    "custom-diff": 0,
    "custom-diff-stats": false,
    "donate-level": 0,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "algo": "astrobwt",
            "coin": "dero",
            "url": "gulf.moneroocean.stream:10128",
            "user": "...",
            "pass": "WorkerName~astrobwt",
            "rig-id": null,
            "keepalive": true,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "algo-perf-same-threshold": 50,
    "tls": {
        "enabled": true,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": true
}
`

**Comment by UnamSanctam** [comment]
Yes that should work, have you been able to connect to the proxy with the normal xmrig at all?

**Comment by suckma420** [comment]
No, I can't

**Comment by suckma420** [comment]
` * ABOUT        XMRig/6.15.3 gcc/10.1.0
 * LIBS         libuv/1.42.0 OpenSSL/1.1.1l hwloc/2.5.0
 * HUGE PAGES   permission granted
 * 1GB PAGES    unavailable
 * CPU
 * MEMORY      
 * MOTHERBOARD  ...
 * DONATE       1%
 * ASSEMBLY     auto:intel
 * POOL #1      140.238.54.60:10032 coin DERO
 * COMMANDS     hashrate, pause, resume, results, connection
 * OPENCL       disabled
 * CUDA         disabled
[2021-11-09 11:05:41.617]  net      140.238.54.60:10032 connect error: "operation canceled"
[2021-11-09 11:06:06.803]  net      140.238.54.60:10032 connect error: "operation canceled"
[2021-11-09 11:06:32.028]  net      140.238.54.60:10032 connect error: "operation canceled"
[2021-11-09 11:06:57.217]  net      140.238.54.60:10032 connect error: "operation canceled"
[2021-11-09 11:07:22.456]  net      140.238.54.60:10032 connect error: "operation canceled"`

**Comment by UnamSanctam** [comment]
Is the port 10032 port forwarded/open on the VPS?

**Comment by suckma420** [comment]
LOL, I'm such a retard, forgot that this vps don't have iptables-persistance
