### ISSUE TITLE
Uninstall Question

### ISSUE THREAD

**Issue by pebu1337** [UnamSanctam/SilentCryptoMiner#70]
What do I do if the uninstaller won't work? File is still present in roaming/Microsoft and my computer is still acting weird with various windows programs malfunctioning and anticheats having issues. It's not actively mining on the computer.

**Comment by pebu1337** [comment]
And please don't ask why I thought it would be a good idea to run it on my pc 😂

**Comment by UnamSanctam** [comment]
Make sure that you run the same uninstaller as the miner build you ran. You can also just run every uninstaller you have. The miner won't really affect any programs unless you maybe have something like the rootkit enabled.

**Comment by pebu1337** [comment]
Thank you, it was because I had the rootkit installed. Just had to delete the service, I was being stupid.
