### ISSUE TITLE
Silent mining community (telegram)

### ISSUE THREAD

**Issue by Redkits02** [UnamSanctam/SilentCryptoMiner#701]
Since the loss of the discord community, a new telegram server has been set up:
https://t.me/MinersCommunity

Для русских / For russians:
https://t.me/MinersCommunityRu

Check the wiki in the pinned message before posting. (includes most often asked questions for newbies)
for any question not answered in the wiki, feel free to ask the community for help and someone will respond.
The community is actively growing, feel free become a part of it.

if you want to ask something directly to unam, he still can't access his telegram, so for now the only way is to open a new issue here.

**Comment by bvi32** [comment]
get out of here

**Comment by pcflux** [comment]
> Since the loss of the discord community, a new telegram server has been set up: https://t.me/MinersCommunity
> 
> Для русских / For russians: https://t.me/MinersCommunityRu
> 
> Check the wiki in the pinned message before posting. (includes most often asked questions for newbies) for any question not answered in the wiki, feel free to ask the community for help and someone will respond. The community is actively growing, feel free become a part of it.
> 
> if you want to ask something directly to unam, he still can't access his telegram, so for now the only way is to open a new issue here.

It does not work, is there a new group?
