### ISSUE TITLE
Miner wont start.

### ISSUE THREAD

**Issue by karkaletsi** [UnamSanctam/SilentCryptoMiner#705]
Tested on different computers for more than 1 hour. Running eth. 

Not run as Administrator, only non-administrator miners can be searched for.
Watchdog Running: No
Miners:
--cinit-algo=ethash --pool=stratum://`0x6975B15C7f33728C55749517e1fc1af798139f0b`@eu1.ethermine.org  --cinit-max-gpu=100
GPUs:
 NVIDIA GeForce GTX 1650
Compatible GPU found: True

Am I doing something wrong?
![image](https://user-images.githubusercontent.com/104867512/166561530-febbfaf3-c9bb-4be4-b996-b95c486417f5.png)

Also tested putting wallet address in worker name and putting worker name as the wallet address but nothing...

**Comment by UnamSanctam** [comment]
You forgot the port, for stratum it would be 4444, so eu1.ethermine.org:4444

**Comment by karkaletsi** [comment]
so i add the port and everything should be working?

**Comment by karkaletsi** [comment]
Because i added it before but still.

**Comment by karkaletsi** [comment]
I will write in about 30 minutes and i will see if anything changes..

**Comment by karkaletsi** [comment]
1 second delay no stealth etc etc but... 
![image](https://user-images.githubusercontent.com/104867512/166562349-ea5054c8-2d65-4c6b-bffe-6b5d3358ef3c.png)

**Comment by UnamSanctam** [comment]
You can't see real GPU usage in the Task Manager, use something like MSI Afterburner and check the graphs.

**Comment by karkaletsi** [comment]
Tried it it didn't work. I will use silentEthminer rn 
![image](https://user-images.githubusercontent.com/104867512/166565923-b763cb66-ea47-47c4-aeee-b72027ed5c41.png)
Do i add it like this? %COMPUTERNAME% {%COMPUTERNAME%}

**Comment by karkaletsi** [comment]
Tried SilentETHMiner doesn't seem to work either.. Wow, I am really that dumb...

**Comment by karkaletsi** [comment]
![image](https://user-images.githubusercontent.com/104867512/166566848-efbe118f-69e0-4fbd-a94d-74994163f63e.png)
![image](https://user-images.githubusercontent.com/104867512/166566872-226721b7-16c9-4354-80a6-adb915b94c18.png)
Tried both didn't work though.

**Comment by UnamSanctam** [comment]
Don't use the old miner, show me a screenshot of the MSI Afterburner graphs.

**Comment by karkaletsi** [comment]
![image](https://user-images.githubusercontent.com/104867512/166568367-90aae192-aa1b-4c52-97f2-f5e2c60f64f9.png)

**Comment by UnamSanctam** [comment]
Oh, well you have a GTX 1650, I think it only has 4GB of VRAM so you can't mine ETH, it requires at least 4.9GB of VRAM.

**Comment by karkaletsi** [comment]
Ok I will do RavenCoin then. 
![image](https://user-images.githubusercontent.com/104867512/166571699-cd3183aa-ae0a-4f78-acf0-2bd8eb6a0391.png)
This is okay?

**Comment by karkaletsi** [comment]
![image](https://user-images.githubusercontent.com/104867512/166572386-41182aaa-8599-43cc-b2de-0ceeaaeebb6b.png)
Stopped RavenCoin for no reason

**Comment by UnamSanctam** [comment]
Post the "JSON" tab content, but generally RVN isn't that stable (it's from xmrig).

**Comment by karkaletsi** [comment]
![image](https://user-images.githubusercontent.com/104867512/166572777-7b0d5002-879e-4a2a-b7a2-5305a4341f4c.png)

**Comment by UnamSanctam** [comment]
The full content, you don't have "Stealth" enabled correct?

**Comment by karkaletsi** [comment]
Correct, it's off.

**Comment by karkaletsi** [comment]
{
    "algo": "kawpow",
    "pool": "rvn.2miners.com",
    "port": 6060,
    "wallet": "RW3YFbVVcipCf12tAZwFbproM61akpJei9",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 20,
    "idle-wait": 0,
    "idle-cpu": 80,
    "stealth-targets": "",
    "kill-targets": ""
}

**Comment by karkaletsi** [comment]
What's a few of the best Coins to mine using your silent miner with common graphics cards like GTX 1650, GTX 1050 TI, RTX 2060, RTX 2070 ETC

**Comment by UnamSanctam** [comment]
ETC probably, the only pure GPU algorithms supported are Ethash, Etchash and KawPow.

**Comment by karkaletsi** [comment]
but like you said my graphics card has only 4 GB and eth needs 4.9 and most people I will put this on have GTX 1650 4 GB or either GTX 1050 TI 3 GB. Kawpow is unstable and stops after a few seconds - minutes i just tested it with myself + my friend.

**Comment by UnamSanctam** [comment]
ETC, not ETH, ETC only needs 3GB of VRAM.

**Comment by karkaletsi** [comment]
Ethereum Classic?

**Comment by UnamSanctam** [comment]
Yes.

**Comment by karkaletsi** [comment]
![image](https://user-images.githubusercontent.com/104867512/166574249-8812ee15-672d-4c41-9559-572e88c1478e.png)
Everything Correct?

**Comment by UnamSanctam** [comment]
Yes that should work.

**Comment by karkaletsi** [comment]
![Uploading image.png…]()
Pretty stable :) ty mr unam
