### ISSUE TITLE
Watchdog does not work

### ISSUE THREAD

**Issue by Jackeyone23** [UnamSanctam/SilentCryptoMiner#71]
![1637387906(1)](https://user-images.githubusercontent.com/93905385/142716284-9734380d-c0ea-4513-b433-802b6c33e606.png)

Hey man, could you please check if I have the xrm settings correct? What is the problem that shows that my watchdog is not working?

**Comment by UnamSanctam** [comment]
Seems like the "Watchdog Running" is not always 100% correct due to difference in user privileges or something like that so it could be running but just not saying it. But you have no miners running so some settings could be wrong, could you save the configuration (press "Save" on the "Main" tab) and post it here so I can check it (you can censor the wallet address inside the file if you want to)?

**Comment by Jackeyone23** [comment]
![06ff16ca21265f5b0ca29aa90d016dd](https://user-images.githubusercontent.com/93905385/142716548-a2fd691![3c2841801b1c5506f0a5f8d88b319c8](https://user-images.githubusercontent.com/93905385/142716550-0e6233a1-9c57-49ee-92d8-8bfbdc7b6c31.png)9ff1-4fb4-b6b8-871bec34b84b.png)
![ecfc15a7078c2cf503dda6e907e3025](https://user-images.githubusercontent.com/93905385/142716549-bc4e80a3-5697-48b3-b58c-eb35392fc1e2.png)
Then it seems to be a problem for you, you are really friendly, thanks

**Comment by UnamSanctam** [comment]
That's an ETH wallet address (or something similar) and not an XMR wallet address.

**Comment by Jackeyone23** [comment]
I'll try again, if I remember correctly he is okex collection address

**Comment by Jackeyone23** [comment]
![a63afbf6703457c3ce46e17360f50fa](https://user-images.githubusercontent.com/93905385/142716982-01fa2aab-246a-4c32-8a54-15bbabd2042b.png)
Are you referring to this app?

**Comment by UnamSanctam** [comment]
That is one wallet you can use yes, there are many different Monero wallets you can use.

**Comment by Jackeyone23** [comment]
![1637390701(1)](https://user-images.githubusercontent.com/93905385/142717412-16c1a24f-bc0f-4a79-8bea-dfe557b03e04.png)
By the way, I'm using a miner, so it's different to download the official Nano Miner, right?

**Comment by UnamSanctam** [comment]
Yes you shouldn't download the Nanopool miner, first get your XMR wallet address from any Monero wallet and then in the builder you should enter `WalletAddress.WorkerName/Password` into the "Wallet Address" field. The `Password` is used to change the minimum payout amount on nanopool.

Here is an example of a fully working "Wallet Address" configuration (with my XMR address):
`8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N.{COMPUTERNAME}/Password123`

**Comment by Jackeyone23** [comment]
![286182aa81cffd8d9c7189748e0d6e1](https://user-images.githubusercontent.com/93905385/142718965-31cbe176-eff3-4c6d-9707-25babe8363e1.jpg)
![1637394262(1)](https://user-images.githubusercontent.com/93905385/142718966-604e1cf2-08b8-488a-afc9-10919c03d61d.png)
This time there are two questions to ask you, the first is to set up the Monroe interface I want to choose that exe file it? The other one is how do I configure Remote Configuration? Do I copy the version of the file behind me? Please give me some advice!

**Comment by UnamSanctam** [comment]
You can choose any "Inject Into" file, it shouldn't really matter. For the "Remote Configuration" those settings should work yes, you should upload the configuration to something like rentry (https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration) and then enter the "raw" link into the "Remote Configuration" field. Don't forget to save the "edit code" when you create a paste if you do use rentry.

**Comment by Jackeyone23** [comment]
Man, I have to say, the miner is a bit pow
![image](https://user-images.githubusercontent.com/93905385/142853284-449fbdde-81af-4a1b-b459-a740330397d6.png)
erful, I want to delete his run in my computer how to do it？
I used 360 antivirus to remove it but it didn't completely stop him from working

**Comment by UnamSanctam** [comment]
Run the uninstaller, it will remove everything about the miner.

**Comment by ColinChau123** [comment]
Also I can't run the uninstaller cuase its cs, how do I fix that . I opened it as note pad and now I got problems with it. Any ehlp would be greatly appreciated thanks

**Comment by UnamSanctam** [comment]
Build the miner with the builder (https://github.com/UnamSanctam/SilentCryptoMiner/releases) it will compile an uninstaller together with the miner.
