### ISSUE TITLE
run as system

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentCryptoMiner#712]
if i use "run as system", and if i use together xmr+eth, they will be installed in the same folder?

**Comment by UnamSanctam** [comment]
There is only one miner file, doesn't matter if you have 1 miner or 200 miners added into it.

**Comment by golxd** [comment]
just wondering, if i use the miner name "Google\Chrome\miner.exe" the google\chrome folders will be created in ProgramFiles?

**Comment by UnamSanctam** [comment]
Yes they will.
