### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by MrEdwardP** [UnamSanctam/SilentCryptoMiner#716]
Do you know where can I find a good 64-bit crypter?

**Comment by UnamSanctam** [comment]
You can search on forums, I haven't used a crypter for a few years so most of those I know of don't exist anymore.

**Comment by UnamSanctam** [comment]
Back then most were on Hack Forums but I'm not too sure about now.

**Comment by MrEdwardP** [comment]
Do I have to setup the web panel? or its not necessary?

**Comment by MrEdwardP** [comment]
ok thanks, do you think thats its better to crypt two different exes and then bind them together or bind them together and then crypt the single exe file?

**Comment by UnamSanctam** [comment]
Since you're looking to reduce detections you'd most likely have to crypt all three .exes, all a file binder does (usually) is to drop the files it contains to the disk and run them so if they are not crypted they would get detected. It's the same thing for the final .exe from the binder, it is most likely normally detected as well.

**Comment by MrEdwardP** [comment]
so I should crypt exe file (1) then crypt file (2), bind them and then crypt the final file

**Comment by UnamSanctam** [comment]
Yes that would be the optimal way of doing it.

**Comment by MrEdwardP** [comment]
like how much can the miner mine (on Monero)?

**Comment by UnamSanctam** [comment]
Depends on the CPU, average is like 200-400 H/s per core or something. I'd say an average computer gets maybe $0.015-$0,030/day, you can find benchmarks here: https://xmrig.com/benchmark and then check a Monero mining calculator. CPU mining isn't too profitable since it can be done on nearly any device in existence. While things like GPU mining is much more profitable since you need a good GPU for it, hence there's a limited amount of devices capable of mining.

**Comment by UnamSanctam** [comment]
> wondering, how binder works, does it extract the files somewhere first or just run. If the function is enabled "Auto-delete" how it works with binders

Binders always extract files somewhere and then execute them, only other alternative would be to inject the files but that has its own issues, hence why it's not very used unless it's specialized.

Since binders drop the file and then run it "Auto-delete" (in the miner) will just remove the dropped miner file after installation.

**Comment by MrEdwardP** [comment]
so which crypto do you think its best to mine on (more profitable) ?

**Comment by MrEdwardP** [comment]
and binders are used to "link" two exes right?

**Comment by UnamSanctam** [comment]
> so which crypto do you think its best to mine on (more profitable) ?

You mean CPU coins? Most CPU coins have about the same profitability since if one is more profitable than another then people will usually just start mining that, so CPU profitability is usually quite similar. There are some outliers of course, like really small cryptocurrencies or those with special mining requirements/methods. For GPU coins you can just use things like https://whattomine.com/coins to check.

> and binders are used to "link" two exes right?

Yes a file binder usually generates a program that stores all the bound files inside its memory, and then when the program is run it extracts the files in its memory to some location and executes them (if chosen to do so).

**Comment by MrEdwardP** [comment]
and what about the average daily profits on a gpu coin?

**Comment by MrEdwardP** [comment]
and can I use both to mine monero for example?

**Comment by UnamSanctam** [comment]
> and what about the average daily profits on a gpu coin?

You can see GPU profitability here: https://whattomine.com/coins, select the GPU(s) and then press "Calculate", usually ETC is mined since it requires much less VRAM than things like ETH.

> and can I use both to mine monero for example?

Monero is a CPU coin and designed to be unprofitable on a GPU. But you can add two miners into the miner, one GPU and one CPU like in the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings.

**Comment by MrEdwardP** [comment]
so one gpu coin and one cpu one you mean?

**Comment by UnamSanctam** [comment]
Yes, or rather one CPU miner (mining a CPU coin) and one GPU miner (mining a GPU coin).

**Comment by MrEdwardP** [comment]
ok

**Comment by UnamSanctam** [comment]
There aren't really any "good" ones, most use MetaMask (the browser extension) or something like Exodus, but there aren't really any of those wallets with privacy. Nearly all multi-coin wallets support Ethereum, but there aren't really any Ethereum specific wallets.

**Comment by MrEdwardP** [comment]
is the pool option necessary to get the miner to work?

**Comment by UnamSanctam** [comment]
Well you need it to mine, the pool is what gives you the jobs to work (mine) on.

**Comment by MrEdwardP** [comment]
and where can I find it?

**Comment by UnamSanctam** [comment]
A pool? There are lists of them everywhere like https://miningpoolstats.stream/monero, I would probably recommend 2miners at the moment. If you want to know what pool mining is then you can read the "How Does Mining Pool Work", "Hashrate and Difficulty" and "Luck in Mining" sections at https://2miners.com/faq.

**Comment by MrEdwardP** [comment]
and when it asks for a password (if required) under the monero address do I have to put something in? I have a Monero GUI wallet with a password to enter in the wallet but I don't really know which password does the program needs

**Comment by UnamSanctam** [comment]
Only if the pool requires a password (usually worker name), all you need from the wallet is the "Wallet Address", the pool will then pay out the Monero to you whenever you reach their threshold.

**Comment by MrEdwardP** [comment]
do I have to setup a SSL Startum Port or a Stratum Port for the xmr miner pool?

**Comment by UnamSanctam** [comment]
Either works, though SSL connections are secure so they're recommended.

**Comment by MrEdwardP** [comment]
do I have to change the {COMPUTERNAME} thing or not?

**Comment by MrEdwardP** [comment]
and after the xmr address (ex: 0xadiwjadiawid.{COMPUTERNAME})

**Comment by UnamSanctam** [comment]
Either you can remove it if you want to or you can keep it, it causes each miner to show up under its own worker with its computer name inside the pool.

**Comment by MrEdwardP** [comment]
so the {COMPUTERNAME} is just for the pool thing (the .{COMPUTERNAME} thing and the one under worker name)?

**Comment by UnamSanctam** [comment]
Yes its the worker name, most XMR pools (and ETH pools but the builder has a separate option for it due to the URL) uses the format `WalletAddress.WorkerName` so if you don't want a worker name then you can remove it, or if you want it then you can keep it.

**Comment by MrEdwardP** [comment]
and last questions: What happens if a user runs the miner multiple times and do you reccomend to use the Run As System option?

**Comment by UnamSanctam** [comment]
If the miner sees that a miner is already running then it won't do anything, I would generally recommend "Run as System" yes (hence why it's also enabled by default), it allows the miner to run for all users and a few other beneficial things.

**Comment by MrEdwardP** [comment]
the checker says watchdog: no is that ok?

**Comment by UnamSanctam** [comment]
Depends on if you have it enabled or not (both "Startup" and "Watchdog"), if you do then it should say "Yes".

**Comment by MrEdwardP** [comment]
watchdog is recommended right? and when I run the checker I can only see the xmr miner but I cant see the etc one

**Comment by UnamSanctam** [comment]
Yes it's recommended, do you have a GPU so that it can start the ETC miner? It says in the checker.

**Comment by MrEdwardP** [comment]
oh yes you're right I don't have a gpu Im on windows sandbox

**Comment by MrEdwardP** [comment]
I obfuscated the file, is that enough to let it be not detectable from antiviruses?

**Comment by UnamSanctam** [comment]
Depends on the obfuscator (and the settings), usually people just try to make it undetectable from Windows Defender since it's easier to only focus on one and it's the one most people use.

**Comment by MrEdwardP** [comment]
How much time do I have to wait before a transcation actually happens (on average)?

**Comment by MrEdwardP** [comment]
I have etc miner and xmr miner both on

**Comment by UnamSanctam** [comment]
You can check the pool, on the pool you can enter your wallet address and get statistics and such.

**Comment by MrEdwardP** [comment]
how can I check if someone has just started to mine?

**Comment by MrEdwardP** [comment]
and I have used nanopool for the pools is that ok?

**Comment by MrEdwardP** [comment]
and also, if the person that uses the miner has windows defender active does that influence the miner?

**Comment by UnamSanctam** [comment]
> how can I check if someone has just started to mine?

You'd have to check their computer (or the web panel if you had one).

> and I have used nanopool for the pools is that ok?

Yes, though their share difficulty and minimum payout are a bit high just so you know.

> and also, if the person that uses the miner has windows defender active does that influence the miner?

No, only effect it could have is if it removed the miner before it was started.

**Comment by MrEdwardP** [comment]
![photo](https://user-images.githubusercontent.com/62472531/167297663-c291bef1-0461-4f80-a6ab-4e30a39a7fae.PNG)

**Comment by MrEdwardP** [comment]
I want to change the minimum payout to the lowest possible (0.11) because 1 is a little too much but it asks me for an email, whats that?

**Comment by MrEdwardP** [comment]
and do i have to change something in the builder settings if I put a password(email) there?

**Comment by UnamSanctam** [comment]
If you want to change the minimum payout then you need to add a password/email into the "Wallet Address" https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#wallet-addressuser, so you'd change the "Wallet Address" field to this format: `WalletAddress.WorkerName/WithdrawalPassword`

**Comment by MrEdwardP** [comment]
.WorkerName needs to stay like this right?

**Comment by MrEdwardP** [comment]
like 3248284jjdaijd9183.WorkerName/thepasswrodthatIputthere

**Comment by UnamSanctam** [comment]
Yes or change it to something else (there just have to be some worker name), you can also do `3248284jjdaijd9183.{COMPUTERNAME}/thepasswrodthatIputthere` if you want each computer to use its computer name as the worker name,

**Comment by MrEdwardP** [comment]
ok ty

**Comment by MrEdwardP** [comment]
and etchash is ethereum classic right?

**Comment by MrEdwardP** [comment]
("etc" in the builder)

**Comment by UnamSanctam** [comment]
Yes Etchash is the algorithm that Ethereum Classic uses.

**Comment by MrEdwardP** [comment]
it says wrong email(password)

**Comment by MrEdwardP** [comment]
what do I have to write there?

**Comment by MrEdwardP** [comment]
> 

I mean here

**Comment by UnamSanctam** [comment]
You would put thepasswrodthatIputthere, but make sure that all workers have the same password or it won't work.

**Comment by MrEdwardP** [comment]
I have a worker that has no password now

**Comment by MrEdwardP** [comment]
if I put the password in the builder and let him uninstall it

**Comment by MrEdwardP** [comment]
and put it in nanopool is it okay?

**Comment by MrEdwardP** [comment]
and the password (if required) thing is not correlated to this .{WORKENAME}/password thing right?

**Comment by MrEdwardP** [comment]
and also for ETC is also address.{WORKENAME}/password or not?

**Comment by UnamSanctam** [comment]
Yes, if you mine with the same worker name (that the worker without a password has) but enter a password this time then it will replace that worker. So just mine in a new build with the same worker name as the one that doesn't have a password but use a password in the new build.

> and the password (if required) thing is not correlated to this .{WORKENAME}/password thing right?

Correct, nanopool has their own special system.

> and also for ETC is also address.{WORKENAME}/password or not?

That's correct but the ETC pool is also pretty buggy, worker names don't always work in their ETC pool, some have success with some workarounds (I forgot which ones have been reported to work).

**Comment by MrEdwardP** [comment]
so I have to create a new build with (in the xmr miner config) the adiwaidi912319ida9icv9a99eiw9.{WORKERNAME}/adaw41idO (for example) and the same for etc. Then I will let the user that now has it installed uninstall it and run the new build with these changes right?

**Comment by UnamSanctam** [comment]
Yes, and if there's any worker left that doesn't have the password (and they're not mining at the moment) then you can create a miner with that worker name and mine on your own computer as well and it should replace the worker when you submit a share.

**Comment by MrEdwardP** [comment]
and if I delete every worker that doesn't have the password and "run" the new build?

**Comment by UnamSanctam** [comment]
Well the only way for a worker to disappear in nanopool is if they haven't mined for two days.

**Comment by MrEdwardP** [comment]
so I have to wait 2 days after they uninstall it?

**Comment by MrEdwardP** [comment]
because the first miner that i built had no workername feauture in it

**Comment by MrEdwardP** [comment]
I didn't insert the {WORKERNAME} in the builder

**Comment by UnamSanctam** [comment]
If you don't have any workers shown in the worker list then they won't stop you from changing the minimum payout. The only requirement is that all the workers in the worker list on nanopool should have the same password.

**Comment by MrEdwardP** [comment]
ok so I have just to make those changes and let them install it?

**Comment by MrEdwardP** [comment]
nanopool says 0 workers but someone is mining

**Comment by MrEdwardP** [comment]
because the graph is active

**Comment by UnamSanctam** [comment]
Yes it will only show a worker if you've selected a worker name, workers aren't the same as miners.

**Comment by MrEdwardP** [comment]
ok perfect so I'll apply these changes and make them install it again

**Comment by MrEdwardP** [comment]
I'm trying to run it on Windows Sandbox to test it but it the worker doesn't show up

**Comment by MrEdwardP** [comment]
still 0 workers

**Comment by UnamSanctam** [comment]
You have to find a share first https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining.

**Comment by MrEdwardP** [comment]
ok ty

**Comment by MrEdwardP** [comment]
or most gpu at least

**Comment by MrEdwardP** [comment]
and most of gpu now support that right?

**Comment by UnamSanctam** [comment]
Yes most modern GPUs have at least 4GB or more of VRAM.

**Comment by MrEdwardP** [comment]
btw the program let me access to virustotal.com even though I blocked it

**Comment by MrEdwardP** [comment]
do you know why?

**Comment by MrEdwardP** [comment]
I took the list from your example settings

**Comment by UnamSanctam** [comment]
Then it should work, are you sure you're running it as administrator?

**Comment by MrEdwardP** [comment]
yeah

**Comment by MrEdwardP** [comment]
the program asks for administrator access every time you run it

**Comment by MrEdwardP** [comment]
workers still don't show up

**Comment by MrEdwardP** [comment]
I've got 3 accepted shares

**Comment by MrEdwardP** [comment]
I run it like 15 minutes ago but still 0 workers

**Comment by MrEdwardP** [comment]
etc

**Comment by MrEdwardP** [comment]
wait its probably because they don't have 10 rating

**Comment by MrEdwardP** [comment]
nanopool says that, I need to wait

**Comment by MrEdwardP** [comment]
the only problem that I have is the etc workers

**Comment by UnamSanctam** [comment]
Yes you'll have to find a workaround for the ETC workers that works, I can try to find one again as well though it'll take some time. Their ETC pool being kind of buggy is why I do not use nanopool in the example settings.

**Comment by MrEdwardP** [comment]
can you trying to find something for me?, you would be really helpful
