### ISSUE TITLE
Bug report Bypass Windows Defender

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentCryptoMiner#72]
Why "Bypass Windows Defender" excludes the C drive and user folder, and the .exe and .dll extensions?

**Comment by UnamSanctam** [comment]
To ensure that it doesn't detect the miner.

**Comment by Toxenskiy** [comment]
Then rename the function to "Disabler Windows Defender". True, in this way you skip not only the miner, but everything else.

**Comment by UnamSanctam** [comment]
Well it doesn't really disable it since a lot of the functions that ignore the exclusions are still enabled and running.

**Comment by Toxenskiy** [comment]
You give permission to all files, do whatever you want ..
