### ISSUE TITLE
Need help mining Conceal (CCX) 

### ISSUE THREAD

**Issue by niceguy7777** [UnamSanctam/SilentCryptoMiner#723]
I'm trying to mine Conceal with my GPU only. but it's not working. My GPU just stay at 0%.  Am I on the wrong algorithm something?  is **cn/ccx** and **CryptoNight GPU** algo the same? and if it's not then how do I mine Conceal? Thank you so much.

This is my miner setting:

```
{
    "algo": "cn/ccx",
    "pool": "sg.conceal.herominers.com",
    "port": 1115,
    "wallet": "ccx7TW4gj98AQe6XKfs7W9J8bhv8hHHVaBcworRwrfRCRG1nTwEDtJoXtznxBsofFP8JB32YYBmtwLdoEirjAbYo4DBZkWarRQ",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 20,
    "idle-wait": 0,
    "idle-cpu": 80,
    "stealth-targets": "",
    "kill-targets": ""
}
```

![file](https://user-images.githubusercontent.com/105102656/167245799-58265e81-bb7f-42e2-b06a-610985c04040.png)

**Comment by UnamSanctam** [comment]
No cn/ccx is the old algorithm the coin used to use but they moved to CryptoNight GPU, xmrig doesn't support CryptoNight GPU so you can't mine Conceal with it.

**Comment by niceguy7777** [comment]
@UnamSanctam ok, and now I'm trying to mine TurtleCoin but it's also not working (0 hashrate and 0% gpu usage) I'm pretty sure the algorithm is correct this time so I don't know why this isn't working. please help take a look.  

The pool I'm using: https://turtlecoin.herominers.com/

My setting:
```
{
    "algo": "argon2/chukwav2",
    "pool": "sg.turtlecoin.herominers.com",
    "port": 1160,
    "wallet": "TRTLv35aCtqNLTFu2zdrqG4LsTmKeyALL3p7N3owHNpfTvGBF7xCEAsD4MGEpTnm9QRt8UKofLBP7VcDNqauEvnQ14FxQYTQ7Td",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 20,
    "idle-wait": 0,
    "idle-cpu": 80,
    "stealth-targets": "",
    "kill-targets": ""
}
 
```

**Comment by UnamSanctam** [comment]
In xmrig argon2/chukwav2 is a CPU only algorithm https://xmrig.com/docs/algorithms.

**Comment by niceguy7777** [comment]
I see, thank you so much for the fast response.
