### ISSUE TITLE
Task Scheduler Fix

### ISSUE THREAD

**Issue by lmaojaja** [UnamSanctam/SilentCryptoMiner#724]
Can you disable all of this in task scheduler for better startup?
Because if my computer is not plugged in, the miner will not start.
![image](https://user-images.githubusercontent.com/80899007/167259480-9eb23d3c-9c78-4af4-9690-4994f8853894.png)

**Comment by UnamSanctam** [comment]
It's not possible to do so with CMD so I'd probably have to switch to powershell or using an XML file to do that, I can experiment around with it I guess.
