### ISSUE TITLE
crypter 2/26

### ISSUE THREAD

**Issue by Zeevsq1** [UnamSanctam/SilentCryptoMiner#726]
I managed to crypt the miner and got 2/26 detections. The crypter I used was found on the forum. Does anyone have other cryptors?
The crypter himself, if someone needs it https://anonfiles.com/t9Zfc0e0y5/crypter_rar

**Comment by tarekxxx** [comment]
can give me name your crypter you used ?

**Comment by Zeevsq1** [comment]
> can give me name your crypter you used or link ?

https://www.mediafire.com/file/h9qes7s04jrwh4b/CRYPTER.rar/file

**Comment by gleborgs** [comment]
Банить Вас надо (идите уроки учите)

**Comment by v3nd1** [comment]
> I managed to crypt the miner and got 2/26 detections. The crypter I used was found on the forum. Does anyone have other cryptors? The crypter himself, if someone needs it https://anonfiles.com/t9Zfc0e0y5/crypter_rar

stupid romanian
