### ISSUE TITLE
Problem When Build Solution

### ISSUE THREAD

**Issue by lmaojaja** [UnamSanctam/SilentCryptoMiner#727]
![image](https://user-images.githubusercontent.com/80899007/167278285-3c5471c1-4405-4d6f-a7d5-2a56f3c615cb.png)
I got these error when I trying to build solution
(I'm using Visual Studio 2017)

**Comment by UnamSanctam** [comment]
Try building it in Visual Studio 2019 or above, that's what it's built in.

**Comment by lmaojaja** [comment]
ok I will try it

**Comment by lmaojaja** [comment]
It worked
Thank you very much!
