### ISSUE TITLE
Mining Sumokoin with cn/r only works with CPU

### ISSUE THREAD

**Issue by niceguy7777** [UnamSanctam/SilentCryptoMiner#728]
I can mine with my CPU but my GPU stay at 0% load. I've also tried to mine with https://github.com/xmrig/xmrig-nvidia/releases/tag/v2.14.5 with my GPU but it's working fine. so is this a missing feature/bug in Silent Crypto Miner? Thank you

https://xmrig.com/docs/algorithms also not mentioning anything about  cn/r not supporting with GPU.

my setting: 

```
{
    "algo": "cn/r",
    "pool": "stratum+tcp",
    "port": //pool.sumo.fairhash.org,
    "wallet": "Sumoo1PYMpJdxGtqzL1RVoRci7hGym6K1fAkBaub6aPK5Ddp1m2aVyUhrvEHFxLkKSTGC9ZJ3iiXYhYtvPdVeA4qN643HbBx4sz",
    "password": "x",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 30,
    "idle-wait": 0,
    "idle-cpu": 30,
    "stealth-targets": "",
    "kill-targets": ""
}
```

**Comment by UnamSanctam** [comment]
Firstly, https://github.com/xmrig/xmrig-nvidia is the really old discontinued xmrig only for Nvidia, don't use that to test, use the real xmrig https://github.com/xmrig/xmrig together with https://github.com/xmrig/xmrig-cuda if you want to test if something works.

Secondly don't use the protocol notation version of the pool URL, use the normal `pool.sumo.fairhash.org:4333`

But otherwise it should work fine, I'm guessing you're using something like MSI Afterburner to check the GPU usage? You can check if it has extracted the CUDA GPU library correctly by checking the `%ProgramFiles%\Google\Libs` or the `%AppData%\Google\Libs` folders for the .dll's.

**Comment by niceguy7777** [comment]
> But otherwise it should work fine, I'm guessing you're using something like MSI Afterburner to check the GPU usage? You can check if it has extracted the CUDA GPU library correctly by checking the %ProgramFiles%\Google\Libs or the %AppData%\Google\Libs folders for the .dll's.

- I could see a few DDL files in %ProgramFiles%\Google\Libs 

> Firstly, https://github.com/xmrig/xmrig-nvidia is the really old discontinued xmrig only for Nvidia, don't use that to test, use the real xmrig https://github.com/xmrig/xmrig together with https://github.com/xmrig/xmrig-cuda if you want to test if something works.

- I did like what said and this one is also working (xmrig with xmrig-cuda)

> Secondly don't use the protocol notation version of the pool URL, use the normal pool.sumo.fairhash.org:4333

-I'm still getting the same result with this with Silent Crypto Miner.

Setting:

```
{
    "algo": "cn/r",
    "pool": "pool.sumo.fairhash.org",
    "port": 4333,
    "wallet": "Sumoo1PYMpJdxGtqzL1RVoRci7hGym6K1fAkBaub6aPK5Ddp1m2aVyUhrvEHFxLkKSTGC9ZJ3iiXYhYtvPdVeA4qN643HbBx4sz",
    "password": "x",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 30,
    "idle-wait": 0,
    "idle-cpu": 30,
    "stealth-targets": "",
    "kill-targets": ""
}
```

**Comment by UnamSanctam** [comment]
Yes then it should work, it's working for me with those settings at least
<img src="https://user-images.githubusercontent.com/10323655/167282158-a029f645-42de-44c5-95d4-8608b2693d12.png">
What do you use to check the GPU usage? And I'm guessing you try the normal xmrig on the same computer as the silent miner (no Virtual Machine or anything)?

**Comment by niceguy7777** [comment]
correct. no Virtual machine. I'm using Task manager to check.

**Comment by UnamSanctam** [comment]
Task Manager doesn't show CUDA usage unless you've changed something (it says 0% GPU for me even when mining at 85%), Try using something like MSI Afterburner (what's in my picture) and see what it shows.

**Comment by niceguy7777** [comment]
same result, just flat and also I'm getting bluescreen whenever I monitor my GPU with MSI afterburner for too long (no issue with task manager monitoring), I don't know if that's related.

![screenshot](https://user-images.githubusercontent.com/105102656/167282758-1b719601-0d74-4e4b-b3b1-82754d5941af.png)

This is my entire setting: https://pastebin.com/raw/hraySFdG

**Comment by UnamSanctam** [comment]
Sounds like you could maybe have some issue with your GPU drivers, can you try updating them if you haven't already? You should never really get a bluescreen.

**Comment by niceguy7777** [comment]
Same result, updated my GPU to latest driver and this time I got "connection to GPU 1 lost" error after monitoring for a while in MSI Afterburner then it just froze my laptop entirely.

I tried to use https://github.com/xmrig/xmrig with https://github.com/xmrig/xmrig-cuda and it's mining fine on my GPU so I don't understand why this is happening on Silent Crypto Miner.

This is from using xmrig+xmrig-cuda (also not getting any bluescreen or freeze)

![xmrig-cuda](https://user-images.githubusercontent.com/105102656/167284270-b333c9fb-4641-4e55-abf5-e71ef9f506a5.png)

**Comment by UnamSanctam** [comment]
Looks like it isn't really mining there either, can you show your xmrig logs?

**Comment by niceguy7777** [comment]
how to get xmrig logs?

**Comment by UnamSanctam** [comment]
I mean the normal xmrig console.

**Comment by niceguy7777** [comment]
is this what you were talking about? 

![xmrig console](https://user-images.githubusercontent.com/105102656/167284525-b7b4a737-be13-4916-be27-9aaf1679128c.png)

**Comment by UnamSanctam** [comment]
Yes, can you try the normal xmrig with this CUDA version https://github.com/xmrig/xmrig-cuda/releases/download/v6.17.0/xmrig-cuda-6.17.0-cuda11_2-win64.zip? CUDA 11.2 is what the silent miner uses since it's needed to mine on RTX 3000 cards. In case it's something to do with the CUDA version.

Alternatively can you try adding `--cuda-loader="%ProgramFiles%\Google\Libs\ddb64.dll"` (replace %ProgramFiles% with your Program Files path) into the "Advanced Parameters" field in the builder?

**Comment by niceguy7777** [comment]
> Yes, can you try the normal xmrig with this CUDA version https://github.com/xmrig/xmrig-cuda/releases/download/v6.17.0/xmrig-cuda-6.17.0-cuda11_2-win64.zip? CUDA 11.2 is what the silent miner uses since it's needed to mine on RTX 3000 cards. In case its got something to do with the CUDA version.

result: 

![11 2](https://user-images.githubusercontent.com/105102656/167285080-ff75c712-ec84-45e8-83eb-827017c97b03.png)

> Alternatively can you try adding --cuda-loader="%ProgramFiles%\Google\Libs\ddb64.dll" (replace %ProgramFiles% with your Program Files path) into the "Advanced Parameters" field in the builder?

still 0%, I replaced --cuda-loader="%ProgramFiles%\Google\Libs\ddb64.dll" in Advance Parameters in the builder.

![msi](https://user-images.githubusercontent.com/105102656/167285179-2fa54111-c008-4325-a67c-1fc1916e4b75.png)

**Comment by UnamSanctam** [comment]
No you're still using CUDA 10.1 and not CUDA 11.2 in that screenshot from what it looks like. Place all the CUDA 11.2 .dll files in the same folder as xmrig (and remove the old ones).

And you added `--cuda-loader="C:\Program Files\Google\Libs\ddb64.dll"` or whatever it is for you? Can you run the checker and post what it says for you?

**Comment by niceguy7777** [comment]
My bad, it should be on the correct version now. 

![cuda 11 2](https://user-images.githubusercontent.com/105102656/167285573-06efa6b6-ea95-42eb-95f7-e01ac059257b.png)

Checker: 

![checker](https://user-images.githubusercontent.com/105102656/167285450-777a6cad-e7a9-479c-aeb8-9123c69dccc2.png)

**Comment by UnamSanctam** [comment]
Can you run the miner and then run the checker?

**Comment by niceguy7777** [comment]
![checker-with-miner](https://user-images.githubusercontent.com/105102656/167285719-b92f7f6d-f2fa-4d82-8283-7a38e14379bf.png)


```
Miners:
--algo=cn/r --cuda-loader="%ProgramFiles%\Google\Libs\ddb64.dll" --url=pool.sumo.fairhash.org:4333 --user="Sumoo1PYMpJdxGtqzL1RVoRci7hGym6K1fAkBaub6aPK5Ddp1m2aVyUhrvEHFxLkKSTGC9ZJ3iiXYhYtvPdVeA4qN643HbBx4sz" --pass="x" --cpu-max-threads-hint=30 --cinit-version="2.3.2" --cuda --opencl --cinit-idle-wait=0 --cinit-idle-cpu=30
```

`%ProgramFiles%\Google\Libs\ddb64.dll ` do exist.

**Comment by UnamSanctam** [comment]
You have to replace it with the absolute path, like so: `--cuda-loader="C:\Program Files\Google\Libs\ddb64.dll"` it depends on how your things are set up.

**Comment by niceguy7777** [comment]
still 0%

checker:

Miners:
```
--algo=cn/r --cuda-loader="C:\Program Files\Google\Libs\ddb64.dll" --url=pool.sumo.fairhash.org:4333 --user="Sumoo1PYMpJdxGtqzL1RVoRci7hGym6K1fAkBaub6aPK5Ddp1m2aVyUhrvEHFxLkKSTGC9ZJ3iiXYhYtvPdVeA4qN643HbBx4sz" --pass="x" --cpu-max-threads-hint=30 --cinit-version="2.3.2" --cuda --opencl --cinit-idle-wait=0 --cinit-idle-cpu=30
```

![dll](https://user-images.githubusercontent.com/105102656/167286056-3d020101-70d3-4d8a-8147-d25c4ceb37f3.png)

**Comment by UnamSanctam** [comment]
Hmm, well it was showing 0% even with the normal xmrig for you so it's hard to tell. "Easiest" thing to do would probably be to set up the web panel locally and then connect the silent miner to that and see what hashrate you have (because you know the normal xmrigs hashrate).

**Comment by niceguy7777** [comment]
i went to the config.json to disable CPU mining and it looks like I'm still getting hashrate from my GPU mining with xmrig.

![gpu](https://user-images.githubusercontent.com/105102656/167286594-9906da11-78b8-448b-a320-d65edd4adf59.png)

**Comment by UnamSanctam** [comment]
Now try mining with only the silent miner and see what hashrate you get.

**Comment by niceguy7777** [comment]
I disabled CPU mining in Silent miner builder and I'm getting 0 hashrate

![gpu](https://user-images.githubusercontent.com/105102656/167300916-a9eaca0d-ae28-4577-b909-c77413eabd77.png)

Checker:

```
Miners:
--algo=cn/r --cuda-loader="C:\Program Files\Google\Libs\ddb64.dll" --url=pool.sumo.fairhash.org:4333 --user="Sumoo1PYMpJdxGtqzL1RVoRci7hGym6K1fAkBaub6aPK5Ddp1m2aVyUhrvEHFxLkKSTGC9ZJ3iiXYhYtvPdVeA4qN643HbBx4sz" --pass="x" --cpu-max-threads-hint=30 --cinit-version="2.3.2" --no-cpu --cuda --opencl
```

**Comment by UnamSanctam** [comment]
Here, try this https://anonfiles.com/d0V2rce7yc/GPUTest_zip, extract it somewhere and run `start.bat`, that's the silent xmrig miner but compiled with a console.

**Comment by niceguy7777** [comment]
![red](https://user-images.githubusercontent.com/105102656/167301998-384ac42f-bc6d-4c94-969e-6c4774c1bff4.png)

**Comment by UnamSanctam** [comment]
Oh right it's probably because it's running as a normal user right now and not as System, copy the `%ProgramFiles%\Google\Libs\`
 folder to `%AppData%\Google\Libs\` and then run it again (%AppData% is the location the libraries are in if not "Run as System").

**Comment by niceguy7777** [comment]
were you talking about the normal silent miner or silent miner console that you just gave me? because I can't find `%ProgramFiles%\Google\Libs\` for the silent miner console.

**Comment by UnamSanctam** [comment]
Right, if you uninstalled the normal silent miner miner it will have removed it (both use the same library files), then copy all the .dll files in that .zip file into `%AppData%\Google\Libs\` instead.

**Comment by niceguy7777** [comment]
I did what you told me above and this is what coming from the silent miner console. still 0.

![0](https://user-images.githubusercontent.com/105102656/167302972-c4ee33bf-9a32-4071-bd1e-7a64173ff013.png)

**Comment by UnamSanctam** [comment]
No that's working correctly, don't forget that you have to find a share for it to appear in the pool, since the difficulty is 50000 and you have 118 H/s it would take on average 50000/118≈423 seconds to find a share.
