### ISSUE TITLE
Ravencoin UPDATE

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#73]
https://i.imgur.com/oRAzVdq.png

No mining with a 1650 Gtx, using silent crypto miner kawpow Ravencoin mining

XMRrig thing only GPU enabled, cpu disabled

**Comment by UnamSanctam** [comment]
Ravencoin requires around 3.1GB-3.3GB of free VRAM so it's definately possible that there isn't enough VRAM free to be able to mine (since GTX 1650 is a 4GB card).

**Comment by Brainshot** [comment]
> Ravencoin requires around 3.1GB-3.3GB of free VRAM so it's definately possible that there isn't enough VRAM free to be able to mine (since GTX 1650 is a 4GB card).

Yeah i thought about that you are right

**Comment by j0er00t** [comment]
> https://i.imgur.com/oRAzVdq.png
> 
> No mining with a 1650 Gtx, using silent crypto miner kawpow Ravencoin mining
> 
> XMRrig thing only GPU enabled, cpu disabled

which hosting you use for panel ??
