### ISSUE TITLE
What is rootkit?

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#74]
I dont understand this option can you explain to me what this is or does?

**Comment by UnamSanctam** [comment]
https://github.com/UnamSanctam/SilentCryptoMiner/wiki#install-rootkit

**Comment by Brainshot** [comment]
> https://github.com/UnamSanctam/SilentCryptoMiner/wiki#install-rootkit

So how i understand once installed there is no way to remove the miner? only with factory reset

since it hides everything
