### ISSUE TITLE
True Hashrates?

### ISSUE THREAD

**Issue by Sh4r3cat** [UnamSanctam/SilentCryptoMiner#745]
Hey, i had used ur miner before but now i use Pureminer is this true that i should have 2,9 gh/s ? I used https://2cryptocalc.com/ and put exact all my gpusi have in it and should get 2,9 gh/s! Im mining on 2miners and get exact 1,45 gh/s its only 50% of my hashrates i should get. This hashes are for ETH only and all 6gb+ gpus are mining without stealth.

**Comment by Nobellium1** [comment]
Did the hashrate dropped with Pureminer or this miner?

**Comment by UnamSanctam** [comment]
> Hey, i had used ur miner before but now i use Pureminer is this true that i should have 2,9 gh/s ? I used https://2cryptocalc.com/ and put exact all my gpusi have in it and should get 2,9 gh/s! Im mining on 2miners and get exact 1,45 gh/s its only 50% of my hashrates i should get. This hashes are for ETH only and all 6gb+ gpus are mining without stealth.

Do you have "Max GPU" set to 100%?

**Comment by Sh4r3cat** [comment]
I use Pureminer so its on = 100%

**Comment by UnamSanctam** [comment]
Ah, theirs is always on 100%? Maybe they use less to reduce lag or something? Do you know the individual GPUs and their hashrates (from Pureminer)? Since that would be the easiest way to know if something is wrong.
