### ISSUE TITLE
Using Remote Configuration

### ISSUE THREAD

**Issue by Popinbob** [UnamSanctam/SilentCryptoMiner#746]
I didn't really understand how to use Remote Configuration. Can I, for example, save the miner settings to an .xml file, copy them from there to Pastebin and paste the raw link in builder?

**Comment by UnamSanctam** [comment]
Yes but the configuration format for the "Remote Configuration" can either be found here https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration (or here for ethminer https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration) or you can find it inside the "JSON" tab in the builder.

**Comment by StandyUwU** [comment]
Thank you for fast answer. As always :)
