### ISSUE TITLE
Low Hashrate

### ISSUE THREAD

**Issue by floodday** [UnamSanctam/SilentCryptoMiner#749]
I am getting low hashrates (1.2MH/s) on a 1660 Super with ethash (Ethermine Pool). I set max GPU to 70% and Idle to 100% - any Idea what I can do to fix that?

**Comment by UnamSanctam** [comment]
Are you calculating the hashrate using the web panel or the pool?

**Comment by floodday** [comment]
Yeah that could be possible, the longest time a worker was running was about 2hrs -> the hashrate jumped to 8mh/s then, thanks
