### ISSUE TITLE
ETH Miner 0h/s 

### ISSUE THREAD

**Issue by 1mavricks1** [UnamSanctam/SilentCryptoMiner#750]
Hi, there is a huge problem with eth miner. 70% of my miners reposrts Active or Active (IDLE) 0h/s and no it is not GUI bag, they don't submit shares. Worst thing is that almost all Nvidia cards are affected. 2070, all 3000 series, all 1660 SUPER and similar. I didn't noticed this on AMD but I have very little 6 GB AMD cards so I don't know about them. Tried switching pools and methods (stratumss/stratums/stratum+tcp) I was thinking about making proxy on my vps and see if it helps but after changing almost all pools with no effect, I think I can't do anything and most likely problem with eth miner.

**Comment by UnamSanctam** [comment]
Try disabling "Stealth", it's possible that they are in stealth but are just reporting the wrong status.

**Comment by 1mavricks1** [comment]
How can I disable that via panel?

**Comment by 1mavricks1** [comment]
I removed stealth targets with no effect

**Comment by 1mavricks1** [comment]
is there like  "stealth-targets" : false or something like that?

**Comment by UnamSanctam** [comment]
If you leave the "stealth-targets" empty then it will disable it.

**Comment by 1mavricks1** [comment]
{
    "url": "stratum://address.GPU@eth-eu1.nanopool.org:9999",
    "algo": "ethash",
    "max-gpu": 50,
    "idle-wait": 1,
    "idle-gpu": 100,
    "stealth-targets": "",
    "kill-targets": ""
}

This is my config right now, will I try to mine ETC instead?

**Comment by 1mavricks1** [comment]
Also tried 2miners/ ethermine and now nanopool

**Comment by 1mavricks1** [comment]
But I didn't tried mining ETC

**Comment by UnamSanctam** [comment]
Try the exact configuration I sent but just change the wallet address to your own.

**Comment by 1mavricks1** [comment]
Ok, I will report soon

**Comment by UnamSanctam** [comment]
Yes, then it will only replace those settings. ETC is the lower memory coin (etchash algorithm) so it uses a lot less VRAM than ETH.

**Comment by 1mavricks1** [comment]
<img width="1076" alt="Screenshot 2022-05-16 at 15 57 18" src="https://user-images.githubusercontent.com/101669533/168609503-96ea9c9d-464d-4fdb-bb41-f0e1db2567c6.png">

Still same :/

**Comment by UnamSanctam** [comment]
Hmm, what if you do something like this:
```
{
  "url": "stratums://Wallet@etc.2miners.com:11010",
  "algo": "etchash",
  "max-gpu": 50,
  "idle-wait": 100,
  "idle-gpu": 90,
  "stealth-targets": ""
}
```
Just to see if it could have something to do with idle.
It's working just fine on my RTX 2070, GTX 970 and GTX 1070 which is why it's weird, only thing I can think of is that their VRAM might be full due to something (and the out of VRAM status hasn't been triggered) but it usually won't happen for too many at once (full VRAM is usually due to gaming).

**Comment by 1mavricks1** [comment]
{
"url":
"stratums://adress.GPU@etc.2miners.com:11010",
  "algo": "etchash",
  "max-gpu": 60,
  "idle-wait": 100,
  "idle-gpu": 90,
  "stealth-targets": ""
}
I think this made it better, but still waiting for half to update. But for example ID:326 started mining and submitting shares..

**Comment by 1mavricks1** [comment]
Yea, strange. Can it be that my build.exe is defected or something? Xmrig is working flawless but ethminer does some strange things..

**Comment by UnamSanctam** [comment]
No that shouldn't be it, though if the miner can't connect to the pool set in the web panel then it will use the "Remote Configuration" or builder pool instead until the connection rotates again. And those (in the screenshot at least) are also the older miner with the older APIs.

**Comment by CryptService** [comment]
🔥Buy crypt files for the miner or for your virus https://t.me/Crypt_Service 
@Cryptex777 🔥

**Comment by sp3c1al** [comment]
hi 
i face the same problem with many gpe 
0h
i try everything you said in this thread to fix it without succeed
any help please 
all my gpe are 0h
and there is no worker in the pool
![7b61d5cf-d4bf-4932-a990-c70d482bb2c6](https://user-images.githubusercontent.com/108318564/176093715-2a6de253-2306-4260-88e2-c78f4f953bb5.jpg)

**Comment by UnamSanctam** [comment]
> hi i face the same problem with many gpe 0h i try everything you said in this thread to fix it without succeed any help please all my gpe are 0h and there is no worker in the pool

Try changing it to another coin that requires less VRAM (like ETC), usually it's due to there not being enough free VRAM to mine (ETH requires 4.9GB of VRAM). Currently my 8GB GPU is using 3.9GB while I don't really have much running.
