### ISSUE TITLE
setting up the miner

### ISSUE THREAD

**Issue by BigGod12** [UnamSanctam/SilentCryptoMiner#758]
i have been watching the silentcryptominer for some couple of days now..i`m new to this..please i help to run this tool or a tutorial i could look in to. that will mean a lot to me..thank you

**Comment by UnamSanctam** [comment]
You can read the wiki on what all the different options do https://github.com/UnamSanctam/SilentCryptoMiner/wik, there are also premade example settings which work https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings=.
