### ISSUE TITLE
Exclusions

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentCryptoMiner#759]
"Add Defender Exclusions". I installed miner (Run as System) and see what folders are added Exclusions. its `C:/users/name` (where the miner is not installed) and `C:` just disk C, is that how it should be? why the whole disk, not the folder `program files` etc

**Comment by UnamSanctam** [comment]
Yes it excludes the whole disk so that nothing gets detected (and also so you don't get some clue what program added it), the reason that the user profile also gets excluded is that the folders for it doesn't necessarily have to be in the C: folder.
