### ISSUE TITLE
Web panel for miners

### ISSUE THREAD

**Issue by Jackysmiths** [UnamSanctam/SilentCryptoMiner#76]
Hello!
Just wondering if you test to mine on your own pc should it show on the web panel?

**Comment by UnamSanctam** [comment]
Yes it should show as long as the "API Endpoint URL" is correct.

**Comment by Jackysmiths** [comment]
You mean the eu1.ethermine.org:4444 ?

**Comment by Jackysmiths** [comment]
because if I try to mine on my pc it doesn't show in the web panel. It shows on the checker only.

**Comment by UnamSanctam** [comment]
No, this: https://github.com/UnamSanctam/UnamWebPanel?

**Comment by Jackysmiths** [comment]
yes I downloaded that

**Comment by Jackysmiths** [comment]
but it doesn't show any of the miners
.

**Comment by UnamSanctam** [comment]
And you input the correct `http://yourwebsite.com/api/endpoint.php` into the "API Endpoint URL" in the miners?

**Comment by Jackysmiths** [comment]
emm not sure

**Comment by Jackysmiths** [comment]
can I still check it?

**Comment by UnamSanctam** [comment]
Yes, if you run the miner and then run the checker it will display the settings.

**Comment by Jackysmiths** [comment]
oh ok ssec

**Comment by Jackysmiths** [comment]
im on laptop currently but should work on this too.

**Comment by Jackysmiths** [comment]
Do I need to cover smth?

**Comment by UnamSanctam** [comment]
Cover?

**Comment by Jackysmiths** [comment]
like blur parts of the text : D

**Comment by Jackysmiths** [comment]
eww idk whats happening. after I open checker it closes it automatically

**Comment by Jackysmiths** [comment]
ohh it closes when i press windows + shift + s. which I use to take screenshot :/

**Comment by UnamSanctam** [comment]
Yes, console programs (that have finished running) close when you press any button. You can censor any wallet address and domain names.

**Comment by Jackysmiths** [comment]
--cinit-algo=ethash --pool=stratum://`wallet address`@eu1.ethermine.org:4444  --cinit-max-gpu=50 --cinit-remote-config="Remote" --cinit-idle-wait=2 --cinit-idle-gpu=80

**Comment by Jackysmiths** [comment]
its like that

**Comment by UnamSanctam** [comment]
Then you didn't enter any URL to your web panel ("API Endpoint URL") so obviously it won't show on the panel.

**Comment by Jackysmiths** [comment]
oh : D. Where should I have placed it

**Comment by UnamSanctam** [comment]
It's beneath the "Remote Configuration" field in the miners, https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#api-endpoint-url.

**Comment by Jackysmiths** [comment]
Right. So do I need to make new one now?

**Comment by UnamSanctam** [comment]
Yes, you can also save and load everything on the "Main" tab of the builder so you don't have to remake all the settings every time.

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142772728-92553d1a-bbb7-4de3-b09e-139e5f2f2ab2.png)
should it show here?

**Comment by Jackysmiths** [comment]
well its not a big work create new so I'll make

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142772862-5414814c-9d5b-4a30-acd7-9f25786e8c0e.png)
so what do I write in them ? : D

**Comment by UnamSanctam** [comment]
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#api-endpoint-url
The "Remote Configuration" is an online configuration hosted with something like pastebin or rentry while "API Endpoint URL" is the URL for something like the UnamWebPanel.

**Comment by Jackysmiths** [comment]
ohh so in the API Endpoint URL I write the Unam  web panel whole URL?

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by Jackysmiths** [comment]
is the remote configuration useful? also what does it do?

**Comment by Jackysmiths** [comment]
oh you sent what it does already

**Comment by Jackysmiths** [comment]
is the remote control just for changing miner settings for example : stealth & kill targets? Or can you also change the crypto type?

**Comment by UnamSanctam** [comment]
You can change all the things listed in the wiki, algorithm, pool, wallet and other miner settings.

**Comment by Jackysmiths** [comment]
ohh okay thanks

**Comment by Jackysmiths** [comment]
how about "save path" which of them is best? Temp, user profile, Appdata?

**Comment by UnamSanctam** [comment]
Any should really work, though AppData is the most common I think.

**Comment by Jackysmiths** [comment]
what is the difference?

**Comment by UnamSanctam** [comment]
None really, though Temp can sometimes be cleared (since it's Temporary) though the watchdog would place it back.

**Comment by Jackysmiths** [comment]
ohh okay thanks

**Comment by Jackysmiths** [comment]
well the web panel still doesn't show the miners there even I set the URL in the box...

**Comment by UnamSanctam** [comment]
If you visit that URL in the browser does it say "Error: Invalid data"? Then it's working.

**Comment by Jackysmiths** [comment]
if I visit my site it just looks normal. There jujst reads "dangerous" before the url

**Comment by UnamSanctam** [comment]
When you visit http://yourwebsite.com/api/endpoint.php?

**Comment by Jackysmiths** [comment]
oh I didn't add these api endpoint.phps

**Comment by Jackysmiths** [comment]
if I add them it says site can't be reached

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142778995-2621f60a-4df0-4f39-90f7-cc776afa666d.png)

this is the look but nothing shows there

**Comment by UnamSanctam** [comment]
Of course not, you haven't connected any miners to it. What exactly do you mean by "can't be reached"? What's the error?

**Comment by Jackysmiths** [comment]
the can't be reached was because I typed https// I meant to write https://

**Comment by Jackysmiths** [comment]
but how do I connect accounts there?

**Comment by UnamSanctam** [comment]
Enter the endpoint into "API Endpoint URL" (hence the name), like `http://yourwebsite.com/api/endpoint.php` ensure that you only use https if you actually have a certificate since otherwise it will be an insecure connection.

**Comment by Jackysmiths** [comment]
if I use http it is not secure site, but if I use https it is secure site. Anways none of them shows my own miner what I am currently running

**Comment by UnamSanctam** [comment]
And you entered the correct URL into the "API Endpoint URL"? If you visit that site in the browser does it say "Error: Invalid data"?

**Comment by Jackysmiths** [comment]
yes I did. I am using 000webhost can it be bad for this site?

**Comment by Jackysmiths** [comment]
the browser doesn't say "Error: Invalid data" either

**Comment by UnamSanctam** [comment]
No 000webhost works, though if you have too many miners (too many connections) on a free site then it can get taken down (because it's free and they don't want to spend much bandwidth on a free site).

**Comment by Jackysmiths** [comment]
well there can't be many since I just created new and there should be just mine which I run on this device.

**Comment by UnamSanctam** [comment]
Yes of course I'm just giving a warning that it can happen, make sure that you have upgraded the PHP version as well https://www.000webhost.com/forum/t/how-to-change-upgrade-or-downgrade-php-version-of-my-website/39336 (might as well change it to PHP 8). W

**Comment by Jackysmiths** [comment]
I created the webhost just like 3 or 4 days ago : D

**Comment by Jackysmiths** [comment]
did I need to add /api/endpoint.php In the API endpoint URL box in miner

**Comment by Jackysmiths** [comment]
or just the site name you created with 000webhost?

**Comment by UnamSanctam** [comment]
Yes /api/endpoint.php needs to be added into the "API Endpoint URL".

**Comment by Jackysmiths** [comment]
ahh Im not pro at this kind of stuff so lets say for example my site is "Minerx000webhostapp.com"

In the miner settings I write "Minerx000webhostapp.com/api/endpoint.php" on API Endpoint URL

Is it correct like that?

**Comment by UnamSanctam** [comment]
`https://Minerx000webhostapp.com/api/endpoint.php` would be correct.

**Comment by Jackysmiths** [comment]
so if I type all that in miner settings how do I see the workers on the webpanel? what do I type in chrome?

**Comment by UnamSanctam** [comment]
You see it on the page that you sent the last screenshot of.

**Comment by Jackysmiths** [comment]
yes but the site which I open is https://Minerx000webhostapp.com/api/endpoint.php or https://Minerx000webhostapp.com?

**Comment by UnamSanctam** [comment]
`https://Minerx000webhostapp.com`, the URL  `https://Minerx000webhostapp.com/api/endpoint.php` is the endpoint that the miners connect to.

**Comment by Jackysmiths** [comment]
Ok I think I did all correct. Let me try 1 more time with mining on my own device and see if it shows there

**Comment by Jackysmiths** [comment]
--cinit-algo=ethash --pool=stratum://`My wallet address`@eu1.ethermine.org:4444  --cinit-max-gpu=50 --cinit-api="https://Mysite.000webhostapp.com/api/endpoint.php" --cinit-idle-wait=2 --cinit-idle-gpu=90

is this all good?
Mysite is the site name but I just changed it

**Comment by UnamSanctam** [comment]
Yes that should work.

**Comment by Jackysmiths** [comment]
so now I go to https://Mysite.000webhostapp.com and the miner should show there?

**Comment by UnamSanctam** [comment]
Yes.

**Comment by Jackysmiths** [comment]
well now I opened the miner on this device. and see if it appears there

**Comment by Jackysmiths** [comment]
Last time it didn't

**Comment by Jackysmiths** [comment]
the website adds index.html/?page=miners&id= in the end of the site. Is t wrong or correct?

**Comment by UnamSanctam** [comment]
That's correct, it's used to be able to distinguish between pages since everything is done with AJAX.

**Comment by Jackysmiths** [comment]
ohh okay. Any idea when my miner should appear there? its still empty.

**Comment by UnamSanctam** [comment]
As long as the URL is correct and the miner is running it will appear after 1 minute of running.

**Comment by Jackysmiths** [comment]
well miner has been running now 10 minutes and url is correct. Still doesn't show there.

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142782425-f60bfa4a-037c-4e6b-871c-abf22e047c0c.png)
Do you have any idea what has went wrong?

**Comment by UnamSanctam** [comment]
Make sure that it's actually running by running the checker. But if it's running make sure that you have upgraded the PHP version (like I linked before) and the URL shown is the checker is correct (copy it from the console and paste it in the browser).

**Comment by Jackysmiths** [comment]
the url in checker is https://Mysite.000webhostapp.com/api/endpoint.php

**Comment by Jackysmiths** [comment]
if I paste that in browser it says site not found

**Comment by Jackysmiths** [comment]
because my site name is https://(Mysite).000webhostapp.com NOT  https://(Mysite).000webhostapp.com/api/endpoint.php

**Comment by UnamSanctam** [comment]
Then you have entered the wrong https://(Mysite).000webhostapp.com. In your example https://(Mysite).000webhostapp.com and https://(Mysite).000webhostapp.com/api/endpoint.php is the same site only a different page.

**Comment by Jackysmiths** [comment]
what if they clearly match on my eyes :/

**Comment by Jackysmiths** [comment]
![Screenshot 2021-11-22 011940](https://user-images.githubusercontent.com/94769120/142782902-a8e03f97-9c48-49e1-8985-e3bf74fe6271.png)
![Screenshot 2021-11-22 012011](https://user-images.githubusercontent.com/94769120/142782911-74846d9c-5377-44ce-8aa6-13001c58f4ec.png)

There is now both sites. The part which I cencored is 100% same on both

**Comment by UnamSanctam** [comment]
Are you sure that you uploaded all the files? If you check the file manager then there should be an `api` folder with `endpoint.php` inside it.

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142782996-c4b8e928-014a-472b-823f-55f833c47de5.png)
right?

**Comment by UnamSanctam** [comment]
No, you have placed all the files inside a folder called index.html. Place all the files in the root folder `public_html`.

**Comment by Jackysmiths** [comment]
🤦

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142783654-94135b0a-78d1-4035-9b02-4678c14f87b6.png)
eh why it looks like this?

**Comment by UnamSanctam** [comment]
Go to https://(Mysite).000webhostapp.com

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142783733-4917fcc3-39f4-4a91-8a65-3bd2156da7dc.png)
yes this is the whole site : D

**Comment by Jackysmiths** [comment]
should there be something in Index.html folder?

**Comment by UnamSanctam** [comment]
No, remove the index.html folder. Everything should be inside the `public_html` folder.

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142783840-79383586-3770-4e82-a6df-e6f33b8c00f6.png)
now its like this and it says "site not found"

**Comment by UnamSanctam** [comment]
Right now it's inside the UnamWebPanel folder, so either move everything from that folder or you can go to `https://(Mysite).000webhostapp.com/UnamWebFolder` and then use `https://(Mysite).000webhostapp.com/UnamWebFolder/api/endpoint.php` inside the miner

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142784080-69ca50c6-3306-4761-8b43-54d6b9042f1d.png)
now its like this and site still not found

**Comment by UnamSanctam** [comment]
If you navigate to `https://(Mysite).000webhostapp.com/api/endpoint.php` now you still get an 404 error?

**Comment by Jackysmiths** [comment]
![Screenshot 2021-11-22 015836](https://user-images.githubusercontent.com/94769120/142784326-809ed813-231e-4348-b1e7-076de92fb0f2.png)
now it says this

**Comment by UnamSanctam** [comment]
Did you upgrade the PHP version?

**Comment by Jackysmiths** [comment]
what should it be? its 7.2 currently

**Comment by UnamSanctam** [comment]
Usually 7.4 or 8, though using 8 is always the best option.

**Comment by Jackysmiths** [comment]
ok I changed to 8 and still says same error

**Comment by UnamSanctam** [comment]
That's usually the only thing that could really be causing the error.

**Comment by Jackysmiths** [comment]
so what should I do now?

**Comment by UnamSanctam** [comment]
Make sure that it's actually changed for that site.

**Comment by Jackysmiths** [comment]
oh yes. I did that already

**Comment by UnamSanctam** [comment]
And you're sure it says PHP 8 for that site?

**Comment by Jackysmiths** [comment]
if I search my site with /index.html/ it says "site not found" but with "/api/endpoint.php" it says the error

**Comment by UnamSanctam** [comment]
Yes shouldn't use index.html, you made a folder called that before, it will do everything automatically when you just browse to the URL. You can enable errors https://www.000webhost.com/forum/t/where-are-the-server-logs-and-php-logs-and-can-i-access-them/66879/2 though it can be a bit difficult since you need to get the HOME_PATH.

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142868203-f1717d48-7a7a-441f-aba3-dfbd2f4fe63f.png)

**Comment by Jackysmiths** [comment]
should I be able to edit someting here?

**Comment by Jackysmiths** [comment]
or do I just type under it?

**Comment by UnamSanctam** [comment]
Yes you should add this under what you sent:
```
php_flag log_errors on
php_value error_log HOME-PATH/public_html/domain/PHP_errors.log
```
And replace HOME-PATH with your 000webhost "Home Root" that you can probably find in the “Account Information” from when you open the domain settings.

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142869723-a1770197-5553-4579-9e5b-adfbbd36e8f5.png)

I wrote the text under it now. Is the HOME-PATH this? it still contiues with few numbers

**Comment by UnamSanctam** [comment]
Yes I believe so, so it would be `/storage/ssd2/606/public_html/domain/PHP_errors.log`

**Comment by Jackysmiths** [comment]
Yeah I wrote that in the HOME-PATH already. Now on what site I see the errors?

**Comment by UnamSanctam** [comment]
First browse to /api/endpoint.php so that you get the error, then open the file manager and see if you can find `PHP_errors.log`

**Comment by Jackysmiths** [comment]
Where should I find PHP_errors.log?

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142871034-5b3d3f4f-7e0e-4d14-9c99-2c0510867c67.png)
on this site I can't find PHP_errors.log if you meant this.

**Comment by UnamSanctam** [comment]
Yes it would be there, honestly you can try just removing all the files and reuploading it all again.

**Comment by Jackysmiths** [comment]
all in publichtml or like all?

**Comment by Jackysmiths** [comment]
also if I reupload everything do I type "php_flag log_errors on
php_value error_log HOME-PATH/public_html/domain/PHP_errors.log" again in .htaccess

**Comment by UnamSanctam** [comment]
No you don't need to, just upload the entirety of the UnamWebPanel folder into `public_html`

**Comment by Jackysmiths** [comment]
after reuploaded all it says now this 
![image](https://user-images.githubusercontent.com/94769120/142873013-3dd6e7bf-413d-4ade-be32-609fae603867.png)

**Comment by UnamSanctam** [comment]
Yes that's correct, then it's working.

**Comment by Jackysmiths** [comment]
ehh? So how I see anything

**Comment by UnamSanctam** [comment]
Like normal, visit the web panel by going to the normal URL. Your miners should appear now if they have that `/api/endpoint.php` that you just visited in them.

**Comment by Jackysmiths** [comment]
its full white
![image](https://user-images.githubusercontent.com/94769120/142873872-3d190214-90b7-4c92-a7dd-666f7890a705.png)

**Comment by Jackysmiths** [comment]
ohh normal url without /api/endpoint.php

**Comment by Jackysmiths** [comment]
ehhhhh then it says "page not found 404"

**Comment by UnamSanctam** [comment]
When you visit the base URL?

**Comment by UnamSanctam** [comment]
Show a screenshot of the file manager.

**Comment by Jackysmiths** [comment]
![image](https://user-images.githubusercontent.com/94769120/142874874-8bd9439a-1caa-4fc0-87be-ea0b3c258018.png)

**Comment by UnamSanctam** [comment]
Then going to your URL should work fine, you could also add /index.php at the end.

**Comment by Jackysmiths** [comment]
ohh yeah there was /index.htm :D thanks

**Comment by Jackysmiths** [comment]
yesss finally it shows there. Thanks alot!

**Comment by UnamSanctam** [comment]
Great, good job.

**Comment by Jackysmiths** [comment]
One more question. Should it show on ethermine.org dashboard instantly?

**Comment by UnamSanctam** [comment]
No, https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining.

**Comment by Jackysmiths** [comment]
ohh right. Thanks again.
