### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by Raqxnd** [UnamSanctam/SilentCryptoMiner#760]
Back then when only windows 10 was available the miner worked completely fine. Now I´m trying to set it up again on my main windows 11 setup and trying to test the file on my 2nd windows 11 setup. The file is not appearing in appdata where the installation should be located. Aswell as the miner is not running the background. Any solutions? Is it caused by windows 11?

**Comment by masterjek** [comment]
The new version of the miner is installed in the folder Program Files.

**Comment by UnamSanctam** [comment]
As @masterjek said if you're installing it as System then it will be in the "Program Files" directory, since AppData depends on the user so installing it into AppData wouldn't work in that case.
