### ISSUE TITLE
Is it ok to start miner multiple times?

### ISSUE THREAD

**Issue by Bartixxx32** [UnamSanctam/SilentCryptoMiner#763]
Hey, im asking about that what in topic becouse, if i do bind miner with app, and this app would be used regular, does it matter to binder? can instalation be corrupted somehow? or should miner be started only once?

**Comment by UnamSanctam** [comment]
It's fine to run it as many times as you want, it will reinstall when you do though the miners doing the mining will still continue to mine uninterrupted. You could also disable https://github.com/UnamSanctam/SilentCryptoMiner/wiki#overwrite-old-miners and it will just exit if a miner is already installed.
