### ISSUE TITLE
Windows Defender detected exclusions after 12h

### ISSUE THREAD

**Issue by Nobellium1** [UnamSanctam/SilentCryptoMiner#764]
![image](https://user-images.githubusercontent.com/96837088/169656291-abe55eb0-1813-4381-941d-f74c66ec1c74.png)
 
So basically I used a crypter with a downloader where miner was added, on both of these "windows exclusions" were enabled, and they were successfully added. Crypter bypassed WD so easily and everything was quite fine until now. 
After 12 hours, windows defender started spamming (3 times) that it detected exclude script. 

ALL the exclusions are removed from WD, both Downloader's and Miner's.

**Comment by Nobellium1** [comment]
I just noticed that crypt is no longer working and file is detected by WD, but still don't get it why did it even scan the file when exclusions were added for both .exe and .dll extensions

**Comment by UnamSanctam** [comment]
That's a really old (detected) exclude script so that's why it gets detected (you can't exclude command line detections).

**Comment by Nobellium1** [comment]
I can understand that Downloader is using an old script, but Miner is using a newer one and those exclusions were removed as well.

**Comment by UnamSanctam** [comment]
Both use the same exclusion paths (SystemRoot and UserProfile) so it wouldn't matter, but the newest UnamDownloader uses the newer undetected commands if you're using UnamDownloader.

**Comment by Nobellium1** [comment]
I did use the newest one tho

**Comment by Nobellium1** [comment]
And those are the commands from the newest unam downloader (menaged .net)

**Comment by UnamSanctam** [comment]
No those commands are from the old one (new one doesn't even use CMD).

**Comment by Nobellium1** [comment]
Only the latest update has Menaged .NET right?

**Comment by Nobellium1** [comment]
That's the one I'm using right now.

**Comment by Nobellium1** [comment]
Because the build I made with it is .NET

**Comment by Nobellium1** [comment]
![image](https://user-images.githubusercontent.com/96837088/169660365-40170287-744d-4db6-9552-3cc039f0a133.png)

**Comment by UnamSanctam** [comment]
Yes but that detection is not from the new UnamDownloader version, you most likely have an old version as well.

**Comment by Nobellium1** [comment]
Look, I am 1000% sure I used newest miner, that's like 1000% true, the only thing Im wondering is that those exclusions might be from the miner because I'm using exclusions there too, however downloader should still add the newest ones

**Comment by UnamSanctam** [comment]
No neither the miner (no version of the miner) nor the downloader (since v1.6.0) has that command in them, only the current binder or the old downloader has that command.

**Comment by Nobellium1** [comment]
Really dont know, as I said Im 100% sure downloader is 1.6.0 because I needed .net build, and I dont use binder at all

**Comment by UnamSanctam** [comment]
Then the detection has to come from some previous build if you have one, the newest downloader can't even have that command in it, it wouldn't work.

**Comment by Nobellium1** [comment]
But why did it delete all miner's exclusions if miner is using newer exclusion script too

**Comment by UnamSanctam** [comment]
I'm guessing Windows Defender might clear out all the exclusions when it detects that (Windows Defender bypass detection), so it wouldn't matter.

**Comment by Nobellium1** [comment]
Understood, will make a build again

**Comment by Nobellium1** [comment]
Should it make exclusions for C and C/user only?

**Comment by UnamSanctam** [comment]
Yes, can be quite slow at adding exclusions (can take between 1-60 second(s) per entry) so I've chosen to reduce how many it adds, C: encompasses everything anyways (UserProfile can technically be on another drive so it adds that too).

**Comment by Nobellium1** [comment]
Look, I ran the same (crypted) build again and exclusions are exactly same (I removed them and this re-added em and they're still only C and C/userprofiles)

**Comment by Nobellium1** [comment]
But the WD detection appeared when I tried to remove that file later (downloader) and it was with the text I've shown you in the first pic

**Comment by UnamSanctam** [comment]
Yes it should only be the SystemDrive and UserProfiles, the new downloader version (and the miner) only adds those two. The command in the original picture only exists in UnamDownloader v1.5.1 and below https://github.com/UnamSanctam/UnamDownloader/blob/55067bf6288b1dc6f930a5e35cbb3695090e887c/UnamDownloader/Builder.cs#L169.

**Comment by Nobellium1** [comment]
So the only thing I can think of is that old binder/downloader was used on the same pc and it somehow triggered those detections when I tried to remove the last build

**Comment by UnamSanctam** [comment]
Yeah it's most likely something like that.
