### ISSUE TITLE
Miner wont connect to HTTPS endpoint

### ISSUE THREAD

**Issue by Bartixxx32** [UnamSanctam/SilentCryptoMiner#768]
Hello, i have added 2 api endpoint to miner config 
`https://xxxx.ct8.pl/api/endpoint.php,http://xxxx.5v.pl/api/endpoint.php`

for obvious reason i hided the url above

both are on other providers,  and before installing cert it was connecting fine to this first xxx.ct8.pl, after i generated cert and tested, (i can access endpoint.php locally
![image](https://user-images.githubusercontent.com/16412925/169707368-2cb58e6f-901b-458b-90ab-f419b8edbfd1.png)

But miner anyways choose second url without https and using it, im doing somentig wrong? becouse i dont think it picking api endpoint randomly, i guess it considered first as down and switched to second endpoint.

**Comment by UnamSanctam** [comment]
It will go to the second one if it's unable to contact the first one, since you said it worked before you added the certificate then something with that is probably the issue.

**Comment by Bartixxx32** [comment]
LetsEncrypt

**Comment by Bartixxx32** [comment]
can i directly contact to you or email? i can give you url for tests etc if want

**Comment by UnamSanctam** [comment]
Sure you can contact me at unams@protonmail.com.

**Comment by Bartixxx32** [comment]
ok i have sended email, idk where you want to conversate about it, here or on email. I think here is easier

**Comment by ahsanzahid3** [comment]
I am also facing the same issue. Let me know if it was resolved.

**Comment by Bartixxx32** [comment]
tbh i do not have any ideas for it, i can only provide php logs to you if you want

**Comment by UnamSanctam** [comment]
That URL should work fine (and I use Let's Encrypt for me test servers as well), what happens if you build it with only the first URL?

**Comment by Bartixxx32** [comment]
I tired it before, just mining, and i dont saw it on panel

**Comment by UnamSanctam** [comment]
Does it work if you use `http`?

**Comment by Bartixxx32** [comment]
> Does it work if you use `http`?

Sorry for delay, yes using http does work, i can access panel through https as me as user but miner cannot

**Comment by UnamSanctam** [comment]
No you can run it on any port, it's technically just a web request. If you're getting error 500 then you have an error somewhere on the server, check if you can see any errors inside the nginx error log file or if there are any error files inside `__UNAM_LIB\Logs`.

But my builds can contact your https just fine, you should be able to see my miner in the web panel (will show "Unam Sanctam Test").

**Comment by Bartixxx32** [comment]
> No you can run it on any port, it's technically just a web request. If you're getting error 500 then you have an error somewhere on the server, check if you can see any errors inside the nginx error log file or if there are any error files inside `__UNAM_LIB\Logs`.
> 
> But my builds can contact your https just fine, you should be able to see my miner in the web panel (will show "Unam Sanctam Test").

Yeah, i see it, maybe cartificate got applied after time?, im gonna check it out, maybe somehow my router is blocking traffic, will look at it

**Comment by Bartixxx32** [comment]
ok, i still connot connect to it via https, but gonna look at my router settings

**Comment by Bartixxx32** [comment]
oh, nvm it connected, but for first time it connected to second enpoint without https, and it was as "starting" there, now i see it active on https one

**Comment by Bartixxx32** [comment]
Ok nvm i think thats provider issue or so, sometimes it works, sometimes it just forcing http and would not use https even after reinstall miner, i will just stuck with http then
