### ISSUE TITLE
Working only for 2 seconds

### ISSUE THREAD

**Issue by BloodHunter321** [UnamSanctam/SilentCryptoMiner#769]
I have setup the miner for RTM algo, when i run the program as administrator it starts but only for 1-2 seconds (CPU gets to 30-50%) and then it closes,
I disabled windows defender, firewall,... and also added exception no threat detected on windows defender
the farmer actually worked for few seconds so i can see it on my flockpool address so the ports are fine, i just don't know why it shuts down.
The first miner i got is from this guy who is a scammer but it works (50% CPU is used all the time) i deleted everything from this guy and downloaded original newest version
https://www.youtube.com/watch?v=F-ePyb5naSM&t=1s&ab_channel=MJopak

**Comment by UnamSanctam** [comment]
If you run the checker does it say the miner is running?

**Comment by BloodHunter321** [comment]
i got the same message on the scammer's and original version when i run checker,.. will setup a new PC tomorrow and try it again, can i contact you via mail?

**Comment by UnamSanctam** [comment]
Well sure (unams@protonmail.com) but are you sure it closes? Are you sure that you just don't have "Stealth" enabled so that it pauses the miner when you check the CPU usage?

**Comment by BloodHunter321** [comment]
I think i have "Stealth" enabled, will turn it off and see if its just that i always had task manager opened,... will contact you via mail if i run into a problem, thank you very much :)
