### ISSUE TITLE
There are no parameters, but everything works correctly

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentCryptoMiner#770]
![image](https://user-images.githubusercontent.com/55586522/169712570-ca954142-f0b0-4203-9b07-8f330e0c6a10.png)
![image](https://user-images.githubusercontent.com/55586522/169712559-55e323ff-d917-4baa-88b9-51566ec7ac7e.png)

**Comment by Toxenskiy** [comment]
but that's only on first run.

**Comment by UnamSanctam** [comment]
Since the miner is probably running as administrator you also need to start Process Hacker as administrator or it doesn't have permission to check the parameters.
