### ISSUE TITLE
I have 3 same miners mining on webpanel

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#772]
is this a glitch or what is this ??

**Comment by UnamSanctam** [comment]
You'll have to show their information, that can happen if they change the computer name or CPU since that's what's used to determine their ID.

**Comment by Brainshot** [comment]
> You'll have to show their information, that can happen if they change the computer name or CPU since that's what's used to determine their ID.

its all same

**Comment by UnamSanctam** [comment]
You'll have to post a screenshot of their information.

**Comment by UnamSanctam** [comment]
I guess that would only ever happen if somehow the database wasn't returning things correctly, it will only add a new miner if it can't find one with that ID and type already present.
https://github.com/UnamSanctam/UnamWebPanel/blob/3426eb84034163dba22a955f37158e524109bfb8/UnamWebPanel/api/endpoint.php#L19
So it could maybe happen if somehow your database was temporarily returning things incorrectly, do multiple reappear if you remove the miners?
