### ISSUE TITLE
Pool

### ISSUE THREAD

**Issue by 6stitch9** [UnamSanctam/SilentCryptoMiner#773]
I am useing portmap.io, do i just put the adress, and then : and port exapmle(urmom8765-50196.portmap.io:50196) but also i wanna be listening on port 8080, how do i control which one i am listening on?

**Comment by UnamSanctam** [comment]
Yes you should enter it in the URL:PORT format, are you running your own xmrig-proxy trying to mine to that? Portmap only allows you to set a custom port (like 8080) if you have premium.

**Comment by UnamSanctam** [comment]
`asurmom8765-50196.portmap.io:50196` means that it will use port 50196 (and not port 8080), I believe your portmap only has 50196 open so in that case you probably can't use 8080 (port is most likely closed).

**Comment by 6stitch9** [comment]
![image](https://user-images.githubusercontent.com/86562545/169851218-f6fb7770-7978-4499-871a-f516aecbad62.png)
![image](https://user-images.githubusercontent.com/86562545/169851290-e83c1a1c-c08d-4f53-a4c8-2ec7562fae2f.png)
and it works, like i can connect to pple via quasar with listening on port 8080, but it is formated or whjatever with :50196, thats whats makeing me confused, and sorry for all the inconvince

**Comment by UnamSanctam** [comment]
Most likely it could be overwriting port 50196 with port 8080 when you do that, so you can try using port 8080 in the miner as well.

**Comment by 6stitch9** [comment]
alright, i'll try that and if not i might have to change how i port forward thank u for ur help, mybe consider adding the secondary listener port option in the miner, but up to u thank u for your time
