### ISSUE TITLE
When i download it says its a virus and when i scan my pc it says theres a trojan.

### ISSUE THREAD

**Issue by 6xrs** [UnamSanctam/SilentCryptoMiner#775]

**Comment by UnamSanctam** [comment]
You mean the builder? If so then the builder contains miners (and all the tools) so of course it will be detected, the builder is open source so you can even check the source code and build it yourself. If you mean that a miner you've built is getting detected then you'll most likely need an obfuscator/crypter to reduce detections https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-can-i-decrease-detections.
