### ISSUE TITLE
Miner does not show by ip in the panel.

### ISSUE THREAD

**Issue by minerdj** [UnamSanctam/SilentCryptoMiner#776]
It's not the first time I've seen this problem. When in ip loger it shows the start of the miner. There is an ip address. I go to the server log. I also see a request from this ip to my panel. I go to the panel, add this ip for search. And writes nothing found. See screenshots.

IPLOGGER

Server log

WEB PANEL 1.5.0
![image](https://user-images.githubusercontent.com/102881386/170132998-77c4f514-7164-4104-ae08-50fdd9f1b0a0.png)

**Comment by UnamSanctam** [comment]
Try logging the requests, add `file_put_contents('request.log', file_get_contents('php://input'), FILE_APPEND);` into line 4 inside endpoint.php.

**Comment by UnamSanctam** [comment]
The panel checks both POST and GET requests, that's not what that line is for. Now all requests will be written out into the `/api/request.log` file, check for the request from that IP and post it here.

**Comment by minerdj** [comment]
> The panel checks both POST and GET requests, that's not what that line is for. Now all requests will be written out into the `/api/request.log` file, check for the request from that IP and post it here.

1. It is not in this file.
/api/regist.log
There is not even the word ip here. I didn’t even see a single ip that is in the panel here.
2. You wrote that IP and post it here. I do not understand. What did you write about. I have to post something here. So the panel automatically records all the data itself.

**Comment by UnamSanctam** [comment]
The line you have added (line 4) will cause all requests to the web panel to be written out into the request.log file inside the api folder, post your request.log file here and I'll check it.

**Comment by minerdj** [comment]
> The line you have added (line 4) will cause all requests to the web panel to be written out into the request.log file inside the api folder, post your request.log file here and I'll check it.

How do you download the file now. Write immediately what you downloaded. I will remove it.
[request.log](https://github.com/UnamSanctam/SilentCryptoMiner/files/8770079/request.log)

**Comment by minerdj** [comment]
> > The line you have added (line 4) will cause all requests to the web panel to be written out into the request.log file inside the api folder, post your request.log file here and I'll check it.
> 
> 
After downloading the file now. Write immediately what you downloaded. I will remove it. [request.log](https://github.com/UnamSanctam/SilentCryptoMiner/files/8770079/request.log)

**Comment by UnamSanctam** [comment]
Just got home and have downloaded it, you can remove the replies.

**Comment by Bartixxx32** [comment]
For me using https on panel fixed ip addresses itself, without https i see 127.0.0.1 but when using https (not endpoint just a panel) it displays correctly
