### ISSUE TITLE
You 0 H/s, pls fix

### ISSUE THREAD

**Issue by DuyLvzy123** [UnamSanctam/SilentCryptoMiner#779]
What happened?? 
![image](https://user-images.githubusercontent.com/99333895/170649990-2cd2a296-e233-49f1-9a64-65eb9246dca9.png)

**Comment by UnamSanctam** [comment]
Maybe you haven't found a share yet? That's not giving me a lot of information.

**Comment by DuyLvzy123** [comment]
> Maybe you haven't found a share yet? That's not giving me a lot of information.

Hello?

**Comment by UnamSanctam** [comment]
Post your settings here, but otherwise these FAQ answers might also be relevant
- https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining
- https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-the-hashrate-shown-on-the-pool-different-from-what-i-expect-or-from-what-is-shown-in-the-web-panel

**Comment by DuyLvzy123** [comment]
> Post your settings here, but otherwise these FAQ answers might also be relevant
> 
> * https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining
> * https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-the-hashrate-shown-on-the-pool-different-from-what-i-expect-or-from-what-is-shown-in-the-web-panel

Thanks man but do I need to disable "stealth"?.

**Comment by UnamSanctam** [comment]
If you have "Stealth" enabled then it will pause the miner while you have any of the "Stealth Targets" programs open (for example by default Task Manager), so if you want to have Task Manager open while the miner runs for testing then disable "Stealth", but for "production" builds "Stealth" is good to have enabled of course.

**Comment by DuyLvzy123** [comment]
> If you have "Stealth" enabled then it will pause the miner while you have any of the "Stealth Targets" programs open (for example by default Task Manager), so if you want to have Task Manager open while the miner runs for testing then disable "Stealth", but for "production" builds "Stealth" is good to have enabled of course.

ah, I'm from vietnam so i have to choose asia server or any server?

**Comment by UnamSanctam** [comment]
Any should work, the server only really changes your ping/latency which isn't always too important. Can you run the checker (that gets built with the miner) and post what it says here? To make sure that the settings are correct.

**Comment by DuyLvzy123** [comment]
> Any should work, the server only really changes your ping/latency which isn't always too important. Can you run the checker (that gets built with the miner) and post what it says here? To make sure that the settings are correct.

Do I need to change the settings?

**Comment by UnamSanctam** [comment]
If those are from the example settings then all you really need to change is the wallet address.

**Comment by DuyLvzy123** [comment]
> If those are from the example settings then all you really need to change is the wallet address (to your own).

<img width="153" alt="image" src="https://user-images.githubusercontent.com/99333895/170694650-dd5688be-4820-4f9d-ad2c-aa9641514664.png">
uhhh

**Comment by DuyLvzy123** [comment]
> If those are from the example settings then all you really need to change is the wallet address (to your own).

....

**Comment by UnamSanctam** [comment]
Did you start it? And how long did you wait? It takes a little while to install to avoid getting removed by Windows Defender.

Also, is that from the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings or your own?

**Comment by DuyLvzy123** [comment]
> Did you start it? And how long did you wait? It takes a little while to install to avoid getting removed by Windows Defender.
> 
> Also, is that from the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings or your own?

I just started, yes. I'm using the example settings

**Comment by DuyLvzy123** [comment]
> Did you start it? And how long did you wait? It takes a little while to install to avoid getting removed by Windows Defender.
> 
> Also, is that from the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings or your own?

These are actually harder than I thought

**Comment by UnamSanctam** [comment]
Try running the checker again now and see what it says since it's been a little while. Otherwise just load the example settings and build the miner without changing any settings to see if it works since then you'll know if it's due to something you changed (if you changed anything).

**Comment by DuyLvzy123** [comment]
> Try running the checker again now and see what it says since it's been a little while. Otherwise just load the example settings and build the miner without changing any settings to see if it works since then you'll know if it's due to something you changed (if you changed anything).

ok

**Comment by DuyLvzy123** [comment]
> Try running the checker again now and see what it says since it's been a little while. Otherwise just load the example settings and build the miner without changing any settings to see if it works since then you'll know if it's due to something you changed (if you changed anything).

yesterday I tried for 5 hours but still showing 0 hashrate but this time I will try again

**Comment by DuyLvzy123** [comment]
> Try running the checker again now and see what it says since it's been a little while. Otherwise just load the example settings and build the miner without changing any settings to see if it works since then you'll know if it's due to something you changed (if you changed anything).

It seems that the port of the example setting is wrong, right?

**Comment by UnamSanctam** [comment]
No it's correct, it's using the SSL port which you can find at the bottom of the page.

**Comment by DuyLvzy123** [comment]
> > Try running the checker again now and see what it says since it's been a little while. Otherwise just load the example settings and build the miner without changing any settings to see if it works since then you'll know if it's due to something you changed (if you changed anything).
> 
> It seems that the port of the example setting is wrong, right?



> No it's correct, it's using the SSL port which you can find at the bottom of the page.

What is worker name?

**Comment by UnamSanctam** [comment]
A name that you can group miners under in a pool. You can also use a separate worker name for each miner (for example `{COMPUTERNAME}`) which will cause each miner to appear separately in the statistics.

**Comment by DuyLvzy123** [comment]
> No it's correct, it's using the SSL port which you can find at the bottom of the page.

I built it without changing anything to see if it works (bad english)

**Comment by DuyLvzy123** [comment]
> A name that you can group miners under in a pool. You can also use a separate worker name for each miner (for example `{COMPUTERNAME}`) which will cause each miner to appear separately in the statistics.

AYO , 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/99333895/170699603-7fe40bec-4382-4593-8206-2e05bbb9249b.png">
what wallet are you using please let me know

**Comment by DuyLvzy123** [comment]
> A name that you can group miners under in a pool. You can also use a separate worker name for each miner (for example `{COMPUTERNAME}`) which will cause each miner to appear separately in the statistics.

It’s not working

**Comment by UnamSanctam** [comment]
> what wallet are you using please let me know

For Monero I use the Monero GUI Wallet (https://web.getmonero.org/downloads/) and for ETC I use MetaMask, Zelcore and/or Exodus.

> It’s not working

You'll have to post your settings that you're changing, go to the "JSON" tab and paste it here. If you use `{COMPUTERNAME}` as the worker name then it will use the computers name as the worker name just like in the previous screenshot.

**Comment by DuyLvzy123** [comment]
> > what wallet are you using please let me know
> 
> For Monero I use the Monero GUI Wallet (https://web.getmonero.org/downloads/) and for ETC I use MetaMask, Zelcore and/or Exodus.
> 
> > It’s not working
> 
> You'll have to post your settings that you're changing, go to the "JSON" tab and paste it here. If you use `{COMPUTERNAME}` as the worker name then it will use the computers name as the worker name just like in the previous screenshot.

alr

**Comment by DuyLvzy123** [comment]
> > what wallet are you using please let me know
> 
> For Monero I use the Monero GUI Wallet (https://web.getmonero.org/downloads/) and for ETC I use MetaMask, Zelcore and/or Exodus.
> 
> > It’s not working
> 
> You'll have to post your settings that you're changing, go to the "JSON" tab and paste it here. If you use `{COMPUTERNAME}` as the worker name then it will use the computers name as the worker name just like in the previous screenshot.

{
    "algo": "rx/0",
    "pool": "xmr.2miners.com",
    "port": 12222,
    "wallet": "48um6m25GYgUK92xADoHZw6qo6AVABSfiFmgudrccTAp2ggYifdsY8pDKV6NnSWeGt2VBStKiWCgWP5rUUsvA3RH6RVd8V9",
    "password": "",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}

**Comment by DuyLvzy123** [comment]
> > what wallet are you using please let me know
> 
> For Monero I use the Monero GUI Wallet (https://web.getmonero.org/downloads/) and for ETC I use MetaMask, Zelcore and/or Exodus.
> 
> > It’s not working
> 
> You'll have to post your settings that you're changing, go to the "JSON" tab and paste it here. If you use `{COMPUTERNAME}` as the worker name then it will use the computers name as the worker name just like in the previous screenshot.

{
    "url": "stratums://`0x180713865722f681501Da8E52E309F5AfD859F34`.Miner@etc.2miners.com:11010",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 5,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
    "kill-targets": ""
}

**Comment by UnamSanctam** [comment]
That should work, build the miner, start the miner, wait a minute or two and then run the checker to see what it shows.

**Comment by UnamSanctam** [comment]
Alright good, then it's running (ETC miner isn't running since you don't have a GPU to mine with), then you only have to wait until you find a share, don't forget to close the Task Manager if you have that open (since "Stealth" is enabled).

**Comment by DuyLvzy123** [comment]
S

> Alright good, then it's running (ETC miner isn't running since you don't have a GPU to mine with), then you only have to wait until you find a share, don't forget to close the Task Manager if you have that open (since "Stealth" is enabled).

<img width="479" alt="image" src="https://user-images.githubusercontent.com/99333895/170702939-190c8d16-7830-4ede-b6c1-462a4cbed79e.png">
Can you explain it to me?

**Comment by UnamSanctam** [comment]
I mean close down (exit) Task Manager so it isn't open otherwise it won't mine (to hide itself).

**Comment by DuyLvzy123** [comment]
> I mean close down (exit) Task Manager so it isn't open otherwise it won't mine (to hide itself).

damn thx again man hmmm so  have to turn on the gpu for etc miner?
an i get this miner virus bind to another file?, and trick others?

**Comment by UnamSanctam** [comment]
Yes you'll need a GPU with at least 3GB of VRAM to mine ETC. You can bind the miner to another file and send it to others and it will install and start mining.
