### ISSUE TITLE
Remote configuration URL

### ISSUE THREAD

**Issue by fx03d** [UnamSanctam/SilentCryptoMiner#781]
What URL should be for the config file if I created it via UnamWebPanel?

**Comment by UnamSanctam** [comment]
There's no endpoint to display configurations by name in the web panel, if you have the web panel in the "API Endpoint URL" then when a miner contacts the web panel it will get the configuration for that miner (by default "Default ethminer" or "Default xmrig" but you can change it on every individual miner).

**Comment by fx03d** [comment]
Thanks!
