### ISSUE TITLE
still 0 hasrate, I waited a long time but

### ISSUE THREAD

**Issue by DuyLvzy123** [UnamSanctam/SilentCryptoMiner#782]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/99333895/170708803-9d220624-2bd8-408a-9ae3-3f087a0bb8a8.png">
should I wait more?

**Comment by UnamSanctam** [comment]
It depends on your hashrate https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining.

**Comment by DuyLvzy123** [comment]
> It depends on your hashrate https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining.

thx u again;-;
