### ISSUE TITLE
Nicehash Mining

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#784]
Please tell me Unam. Builder has a function Nicehash Mining, what is the effect of this feature? If I'm going to mine on pools Nicehash does it need to be enabled?

**Comment by UnamSanctam** [comment]
NiceHash mining is there to support subjobs (jobs that have been split into multiple ones), notably the NiceHash "pool" and xmrig-proxy uses this, but for normal pools "NiceHash Mining" should be disabled.

**Comment by masterjek** [comment]
Thanks for the quick response and help.
