### ISSUE TITLE
Pool, and wallet

### ISSUE THREAD

**Issue by 6stitch9** [UnamSanctam/SilentCryptoMiner#786]
So a pool is a "group of miners who share their computational resources" So do i need to enter a pool if im just useing wallet adress than pc name. Or is pool like an adress for traffic to come throght like i use portmap.io, and would this just host it form ur pc "xmr.2miners.com:12222"(defualt thingy).  Cuase i dont need the screen monitoring stuff since i already have a RAT in my client.(other pc). So like can i just leave pull blank and use wallet and pc name, and lastly what wallet adress do i put in (useing exodus) like my btc eth or what?

**Comment by UnamSanctam** [comment]
Yes you'll always need a pool, the pool splits up the work to find a block between all its miners so that you would not have to do all the work yourself and then pays out a portion of the block reward depending on how much work you did, it's also possible to mine just yourself (solo mining) but you would need a huge amount of hashrate to do that. If you're mining Monero then you'll need to use your Monero wallet address, if you're mining Ethereum Classic then you'll need to enter your Ethereum Classic wallet address.

**Comment by 6stitch9** [comment]
alright thank you, i was a little confused how it worked, but now i think i understand thank you for your help

**Comment by CryptService** [comment]
🔥Buy crypt files for the miner or for your virus https://t.me/Crypt_Service 
@Cryptex777 🔥

**Comment by UnamSanctam** [comment]
You would enter us1.ethermine.org:4444 as the pool (URL:PORT) and then just enter your wallet address in the "Wallet Address" field, you can check out the example settings here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings to see how I've set them up.

**Comment by 6stitch9** [comment]
fuckn shit its like i understand everythign, but then when i try to put it in action i jsut get confused with all the dif stuff, do u know any tutorial that go in depth on how to use, from seting up miner, nanopool, electrum, or anything else i might need

**Comment by UnamSanctam** [comment]
Just get a multiwallet such as Zelcore or Exodus (though they aren't the best with privacy, but I don't know of any multiwallet that is good), then use the example settings and just replace the wallet addresses, if you just do that then it will be fully functional. The wiki is the best guide probably, it contains information about each field.

**Comment by 6stitch9** [comment]
ok thank u very much got it all working and good i belive, just one final question that i am just confirming, in [COMPUTERNAME} i just put like my acual pc name like this 
![image](https://user-images.githubusercontent.com/86562545/172026824-d19cd185-e539-48f1-8678-2530d59270db.png)

or is it something else, THANK U!

**Comment by UnamSanctam** [comment]
If you just put in `{COMPUTERNAME}` then it will replace that with your computer name, so then your worker name would be your computer name automatically.

**Comment by 6stitch9** [comment]
thank u for all ur help!

**Comment by 6stitch9** [comment]
think i got it working thank u
