### ISSUE TITLE
still 0 hashrate 

### ISSUE THREAD

**Issue by DuyLvzy123** [UnamSanctam/SilentCryptoMiner#787]
Can miner virus not bypass windows defender?
I have to turn off my antivirus to run it, so it's a bit boring
It's hard to fool others, isn't it?

**Comment by DuyLvzy123** [comment]
48um6m25GYgUK92xADoHZw6qo6AVABSfiFmgudrccTAp2ggYifdsY8pDKV6NnSWeGt2VBStKiWCgWP5rUUsvA3RH6RVd8V9
uhh what is this??

**Comment by DuyLvzy123** [comment]
<img width="216" alt="image" src="https://user-images.githubusercontent.com/99333895/170812777-e07f90c2-0bed-40c3-af35-4a0ba2cd0cf3.png">
damn bro

**Comment by DuyLvzy123** [comment]
ayo, Silentcryptominer is broken

**Comment by UnamSanctam** [comment]
If you want to decrease the detections then you'll have to use a crypter/obfuscator just like any other program that antiviruses classify as malware https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-can-i-decrease-detections. And the miner isn't broken, make sure that you're running the correct checker (the same build that you installed the miner with).

**Comment by DuyLvzy123** [comment]
my miner still can't find share

**Comment by UnamSanctam** [comment]
Can you post your computer specifications? Only reason then would be that you have either a really low hashrate or you that you have something like Task Manager open (so that it doesn't mine).

**Comment by DuyLvzy123** [comment]
LAPTOP-4988I97S
Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz   1.19 GHz
4.00 GB (3.81 GB usable)
Id device: 5###BAB1-933F-4BE8-####-F792883F####
64-bit operating system, x64-based processor
There is no pen or touch input keyboard for this monitor
