### ISSUE TITLE
Bypass window defender

### ISSUE THREAD

**Issue by DuyLvzy123** [UnamSanctam/SilentCryptoMiner#789]
Can you tell me is there any free crypter/obfuscator that can make miner virus undetectable?

**Comment by DuyLvzy123** [comment]
I don't know if confuserEX can do that

**Comment by DuyLvzy123** [comment]
<img width="158" alt="image" src="https://user-images.githubusercontent.com/99333895/170825175-7c19f671-d673-438b-b229-6138aae354ab.png">
damn it

**Comment by UnamSanctam** [comment]
Depends on what you mean by undetectable, if you just mean Windows Defender then trying every obfuscator option combination in any obfuscator can usually reduce the detections (depends on what the detections are), if you mean undetectable as in fully undetectable then no free program can usually do that.

> <img alt="image" width="158" src="https://user-images.githubusercontent.com/99333895/170825175-7c19f671-d673-438b-b229-6138aae354ab.png">
> 
> damn it

Are you running the correct checker program? Since the miner is "hidden" only the checker from the build you have installed can find anything.

**Comment by DuyLvzy123** [comment]
> Depends on what you mean by undetectable, if you just mean Windows Defender then trying every obfuscator option combination in any obfuscator can usually reduce the detections (depends on what the detections are), if you mean undetectable as in fully undetectable then no free program can usually do that.
> 
> > <img alt="image" width="158" src="https://user-images.githubusercontent.com/99333895/170825175-7c19f671-d673-438b-b229-6138aae354ab.png">
> > damn it
> 
> Are you running the correct checker program? Since the miner is "hidden" only the checker from the build you have installed can find anything.

yes, Im sure

**Comment by UnamSanctam** [comment]
Then you must've run the uninstaller to remove it, that's not a problem with the miner but something you did (not even Windows Defender kills the miner and/or watchdog if it gets detected)..

**Comment by DuyLvzy123** [comment]
> Depends on what you mean by undetectable, if you just mean Windows Defender then trying every obfuscator option combination in any obfuscator can usually reduce the detections (depends on what the detections are), if you mean undetectable as in fully undetectable then no free program can usually do that.
> 
> > <img alt="image" width="158" src="https://user-images.githubusercontent.com/99333895/170825175-7c19f671-d673-438b-b229-6138aae354ab.png">
> > damn it
> 
> Are you running the correct checker program? Since the miner is "hidden" only the checker from the build you have installed can find anything.

it also depends on the mining site?

**Comment by UnamSanctam** [comment]
No.

**Comment by DuyLvzy123** [comment]
> No.

a few hours ago it worked but now i try again it doesn't work

**Comment by DuyLvzy123** [comment]
> No.

I'm sure I'm the only one having this problem

**Comment by UnamSanctam** [comment]
Press "Save" on the "Main" tab, then zip the .xml file and post it here.

**Comment by DuyLvzy123** [comment]
[WTF WHY.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8791135/WTF.WHY.zip)

**Comment by DuyLvzy123** [comment]
> Press "Save" on the "Main" tab, then zip the .xml file and post it here.

It took me more than 4 days because of this problem

**Comment by DuyLvzy123** [comment]
I will never give up until I solve this problem

**Comment by UnamSanctam** [comment]
Those settings should work just fine as long as your Windows Defender isn't removing it while installing (since you don't have "Add Defender Exclusions" enabled). If you can, take a video of building it, starting it, waiting for a while and then running the checker.

**Comment by DuyLvzy123** [comment]
> Those settings should work just fine as long as your Windows Defender isn't removing it while installing (since you don't have "Add Defender Exclusions" enabled). If you can, take a video of building it, starting it, waiting for a while and then running the checker.



> Those settings should work just fine as long as your Windows Defender isn't removing it while installing (since you don't have "Add Defender Exclusions" enabled). If you can, take a video of building it, starting it, waiting for a while and then running the checker.

alr, I'll do it

**Comment by DuyLvzy123** [comment]
> Those settings should work just fine as long as your Windows Defender isn't removing it while installing (since you don't have "Add Defender Exclusions" enabled). If you can, take a video of building it, starting it, waiting for a while and then running the checker.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/99333895/170826052-51eeff38-b782-4c0b-b774-bd0543b1dd9f.png">
What the fk??, bruh how
If I don't know what causes it, I won't stop.

**Comment by DuyLvzy123** [comment]
> Those settings should work just fine as long as your Windows Defender isn't removing it while installing (since you don't have "Add Defender Exclusions" enabled). If you can, take a video of building it, starting it, waiting for a while and then running the checker.

!It finally worked but still showing 0 hashrate, i don't like waiting

**Comment by UnamSanctam** [comment]
Check your web panel, you should see your hashrate on the web panel.

**Comment by DuyLvzy123** [comment]
> Check your web panel, you should see your hashrate on the web panel.

AYO DUDDE
<img width="686" alt="image" src="https://user-images.githubusercontent.com/99333895/170826717-9bfb35c6-c8a6-4861-964a-93af512c3310.png">

**Comment by DuyLvzy123** [comment]
> > Check your web panel, you should see your hashrate on the web panel.
> 
> AYO DUDDE <img alt="image" width="686" src="https://user-images.githubusercontent.com/99333895/170826717-9bfb35c6-c8a6-4861-964a-93af512c3310.png">

What happened bruhh

**Comment by UnamSanctam** [comment]
Means that it cannot connect with your pool settings.

**Comment by DuyLvzy123** [comment]
> Means that it cannot connect with your pool settings.

xmr.2miners.com:2222 ....

**Comment by UnamSanctam** [comment]
No you're trying to connect to pool.hashvault.pro:80 as you can see in the screenshot.

**Comment by DuyLvzy123** [comment]
> No you're trying to connect to pool.hashvault.pro:80 as you can see in the screenshot.

wdym?

**Comment by DuyLvzy123** [comment]
I'm quite confused

**Comment by DuyLvzy123** [comment]
I will try another portal or other miner sites

**Comment by DuyLvzy123** [comment]
> No you're trying to connect to pool.hashvault.pro:80 as you can see in the screenshot.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/99333895/170827042-bfaecae3-12d5-4a5d-b4d9-b9e6118e711b.png">
when will it start?

**Comment by DuyLvzy123** [comment]
> No you're trying to connect to pool.hashvault.pro:80 as you can see in the screenshot.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/99333895/170827222-fb86aae1-f9ee-47a6-a615-466d15939ee3.png">
alr finally, thx u again
