### ISSUE TITLE
Kawpow GPU MINING

### ISSUE THREAD

**Issue by Exdmunds** [UnamSanctam/SilentCryptoMiner#79]
Hello i have a question about gpu mining ravencoin with kawpow, how to max gpu usage?

Thanks!

**Comment by UnamSanctam** [comment]
You mean making it use the maximum amount of GPU usage? Then you should look at XMRig CUDA bfactor and bsleep settings.

**Comment by zanatechnology** [comment]
Why I cant use GPU in KawPow anytime I make it and creat it it just use CPU note that I apply the function of GPU too while creating the program, can you help me @UnamSanctam 
Thank you previously 🙏🏻

**Comment by UnamSanctam** [comment]
KawPow cannot mine with the CPU since it's not implemented it's impossible, make sure that you have "GPU Mining" enabled for it to be able to use the GPU.

**Comment by zanatechnology** [comment]
![1](https://user-images.githubusercontent.com/89279699/143374980-dbdfd8b9-5cf4-4e69-aa21-b9c007a1c6ef.png)
![2](https://user-images.githubusercontent.com/89279699/143374983-b111ac02-a247-43db-a6a2-13cc93c674c3.png)
its not working dude can you try it and tell me the steps please

**Comment by UnamSanctam** [comment]
Should work fine, are you checking it with something like MSI Afterburner (since things like the Task Manager doesn't display CUDA usage).

**Comment by zanatechnology** [comment]
Yes I did using OMEN manager

**Comment by UnamSanctam** [comment]
Run the checker and post what it returns here (you can censor the wallet address).

**Comment by zanatechnology** [comment]
![3](https://user-images.githubusercontent.com/89279699/143460381-30c9e37d-64ee-40ff-8f95-0d8158df86f4.png)
look since the morning am waitting it
the wallet is empty and its not runing

**Comment by UnamSanctam** [comment]
Can you check how much VRAM you have free?

**Comment by zanatechnology** [comment]
how i can do check?

**Comment by UnamSanctam** [comment]
I would recommend MSI Afterburner but you can use the Task Manager as well, go to the second tab in the Task Manager, then scroll down to your GPU, then click the GPU and you should see something called "Dedicated GPU Memory Usage".

**Comment by zanatechnology** [comment]
![4](https://user-images.githubusercontent.com/89279699/143478136-b5db5e79-8c86-4a34-840d-9cf97fdc8f6c.png)

**Comment by zanatechnology** [comment]
that while am using the ETC miner too
am testing it

**Comment by UnamSanctam** [comment]
Yeah, the GPU memory is full, you only have 0.9GB of VRAM left while Ravencoin requires 3.1GB of VRAM. https://minerstat.com/dag-size-calculator

**Comment by zanatechnology** [comment]
@UnamSanctam bro can you do a favor for me and teach me the method to spread it I'll be thank full to you 🙏🏻
