### ISSUE TITLE
Switch all workers to another configuration

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#790]
Good afternoon Unam. Please tell me there is a method to quickly switch a large number of workers to another configuration in the web panel? I understand it can be done in the database - unamwebpanel - I installed browser - DB Browser (SQLite) - Opening database in browser and I can’t find workers there to switch them all to another configuration at once.

**Comment by UnamSanctam** [comment]
In the DB Browser first open the "configs" table, find the "cf_configID" of whatever configuration you want to use. Then open the "miners" table and replace "ms_config" with the "cf_configID" found in the earlier step on whatever miners you want to change it on.

**Comment by masterjek** [comment]
Thanks a lot for your help.
