### ISSUE TITLE
victim

### ISSUE THREAD

**Issue by DuyLvzy123** [UnamSanctam/SilentCryptoMiner#793]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/99333895/170852665-a88f64c2-68c6-46c2-9874-04c08806d54a.png">
Why does the victim's computer lose connection??

**Comment by DuyLvzy123** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/99333895/170853450-bfd686d5-9243-40fa-bee3-75cdcbdd5654.png">
How can I remove this virus??, I used builder-uninstaller.exe but it doesn't work??.

**Comment by DuyLvzy123** [comment]
ayo bro

**Comment by UnamSanctam** [comment]
They could've turned off their computer, most people don't have their computers on all the time. And the uninstaller should work fine, alternatively you can remove it manually https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner.

**Comment by DuyLvzy123** [comment]
> They could've turned off their computer, most people don't have their computers on all the time. And the uninstaller should work fine, alternatively you can remove it manually https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner.

watch dog running doesn't work and miner doesn't work either.
I created a lot and it still doesn't work even though I tried many times.

**Comment by UnamSanctam** [comment]
Take a video of building, running and checking the miner and post it here.

**Comment by DuyLvzy123** [comment]
> Take a video of building, running and che

https://user-images.githubusercontent.com/99333895/170859467-c6a777d1-39ee-49ae-928e-28045a4d6379.mp4

here

https://user-images.githubusercontent.com/99333895/170859494-261a5550-93fa-4999-9842-bb7e722f3e93.mp4




> Take a video of building, running and checking the miner and post it here.

**Comment by DuyLvzy123** [comment]
https://user-images.githubusercontent.com/99333895/170859577-b420a98e-ecb7-4bf7-9ddc-3721e3442d5a.mp4

**Comment by UnamSanctam** [comment]
Try it without the rootkit, the rootkit is still experimental (since it's quite a complex and invasive program.

**Comment by DuyLvzy123** [comment]
> Try it without the rootkit, the rootkit is still experimental (since it's quite a complex and invasive program.

alright

**Comment by DuyLvzy123** [comment]
> Try it without the rootkit, the rootkit is still experimental (since it's quite a complex and invasive program.

<img width="172" alt="image" src="https://user-images.githubusercontent.com/99333895/170860022-1a399853-5824-42de-9614-f68f813375bf.png">
Just because it doesn't work sometimes doesn't mean it never works

**Comment by DuyLvzy123** [comment]
maybe my computer has something wrong that i don't know😟

**Comment by UnamSanctam** [comment]
I'm now running the final tests for the new version (version 2.4.0, maybe an hour left until it's done), you can try the new version when I release it and see if there's any difference for you.

**Comment by DuyLvzy123** [comment]
> I'm now running the final tests for the new version (version 2.4.0, maybe an hour left until it's done), you can try the new version when I release it and see if there's any difference for you.

I hope the new version will solve this problem

**Comment by DuyLvzy123** [comment]
> I'm now running the final tests for the new version (version 2.4.0, maybe an hour left until it's done), you can try the new version when I release it and see if there's any difference for you.

I will wait, I never give up cause I found what I need now.
