### ISSUE TITLE
Thx u again brooo

### ISSUE THREAD

**Issue by DuyLvzy123** [UnamSanctam/SilentCryptoMiner#795]
HELL YEAH, IT FINALLY WORKS.

**Comment by UnamSanctam** [comment]
Great, tell me if it stops working for you.

**Comment by DuyLvzy123** [comment]
> Great, tell me if it stops working for you.

Wait, stealth at fullscreen how does it work? I have read the changelogs only understand a little

**Comment by UnamSanctam** [comment]
I have now added an explanation for it here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#pause-on-fullscreen.

**Comment by DuyLvzy123** [comment]
> I have now added an explanation for it here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#pause-on-fullscreen.

FullScreenDetection.zip??, I didn't expect you to be so detailed

**Comment by UnamSanctam** [comment]
Haha, it's if anyone wants to test what triggers "Fullscreen" mode in Windows for them so they don't have to guess.

**Comment by DuyLvzy123** [comment]
> Haha, it's if anyone wants to test what triggers "Fullscreen" mode in Windows for them so they don't have to guess.

Does the webpanel automatically update?

**Comment by UnamSanctam** [comment]
No, when I upload the new web panel release (doing tests now) then just replace all the files (best to remove all the old ones and upload the new ones) with the new ones.

**Comment by DuyLvzy123** [comment]
> No, when I upload the new web panel release (doing tests now) then just replace all the files (best to remove all the old ones and upload the new ones) with the new ones.

I'm really excited now so I'll do it again, cya.

**Comment by DuyLvzy123** [comment]
> No, when I upload the new web panel release (doing tests now) then just replace all the files (best to remove all the old ones and upload the new ones) with the new ones.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/99333895/170869165-7610560e-1bad-45e5-be67-2c6bb9c24e9a.png">
Did you update or is it faulty?

**Comment by DuyLvzy123** [comment]
> No, when I upload the new web panel release (doing tests now) then just replace all the files (best to remove all the old ones and upload the new ones) with the new ones.

oh ok
