### ISSUE TITLE
Rootkit issue

### ISSUE THREAD

**Issue by DuyLvzy123** [UnamSanctam/SilentCryptoMiner#797]
When  turned on the rootkit and created it had the same problem as before, I turned it off and it worked( I think the rootkit isn't done, right?)

**Comment by UnamSanctam** [comment]
Yeah the rootkit isn't made by me so it might not work on every computer, though the miner should usually still work even if the rootkit doesn't unless you have some problems with the dialer.exe program (which it uses to run).

**Comment by DuyLvzy123** [comment]
> Yeah the rootkit isn't made by me so it might not work on every computer, though the miner should usually still work even if the rootkit doesn't unless you have some problems with the dialer.exe program (which it uses to run).

<img width="645" alt="image" src="https://user-images.githubusercontent.com/99333895/170871156-b4b8ef0c-c80d-4a36-a480-c170530f0136.png">
<img width="694" alt="image" src="https://user-images.githubusercontent.com/99333895/170871170-42a54435-09c4-43a3-a311-9642d389b642.png">
forget those sentences, I'm confused again. So is it still normal?

**Comment by UnamSanctam** [comment]
If the web panel says it's running then yes the miner is running.

**Comment by DuyLvzy123** [comment]
> If the web panel says it's running then yes the miner is running.

alright, lmaoXD
