### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#798]
Does stealth on full screen feature also work for apps like google?

**Comment by UnamSanctam** [comment]
You can see an explanation for it here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#pause-on-fullscreen, you'd have to test whether any individual programs change the notification state to busy.

**Comment by Ninja133** [comment]
so it dose consider full screen if watching move or open video on full screen
as far as i tested it

**Comment by UnamSanctam** [comment]
Yes exactly, doing that will trigger the "busy" notification state in Windows (what they consider "Fullscreen").

**Comment by Ninja133** [comment]
its genius option to add and help us for not wary about Stealth and games 
but the only thing is when watching movies etc ,,
