### ISSUE TITLE
What's Next? 

### ISSUE THREAD

**Issue by Dex0xm** [UnamSanctam/SilentCryptoMiner#8]
Will you add onion support in this unified miner?

**Comment by UnamSanctam** [comment]
Maybe, the solutions I have found are not very reliable when installing them automatically. The think I'd like the most is to reduce detections even more than now though for me it avoids Windows Defender quite well.

**Comment by Dex0xm** [comment]
you shouldn't worry about detections.
Detections can be reduced always
no matter what you do people will always upload samples to virustotal
so there's nothing you can do about that
