### ISSUE TITLE
64 bit or 32 bit?

### ISSUE THREAD

**Issue by wanz3ru** [UnamSanctam/SilentCryptoMiner#80]
Hey! The question is, does the program create a 32-bit miner or a 64-bit one?

**Comment by UnamSanctam** [comment]
A 64-bit one.

**Comment by wanz3ru** [comment]
Is it possible to somehow make it 32-bit?

**Comment by UnamSanctam** [comment]
Both XMRig and ethminer and all of their libraries would have to be converted and compiled to 32-bit (if even possible). Then the RunPE function and a bit more would also have to be converted to it. 32-bit miners usually have lower hashrates on some systems though from all my tests (about maybe 3 years ago right before XMRig discontinued 32-bit support) so I won't be changing it to 32-bit.
