### ISSUE TITLE
Donate 

### ISSUE THREAD

**Issue by FireHack7z** [UnamSanctam/SilentCryptoMiner#805]
Now I donate 10$ / 20$ per month for your work ❤️

**Comment by UnamSanctam** [comment]
Thank you very much, I really appreciate it.

**Comment by JosepP2** [comment]
> 

Nice people here also, i donated more than 100$ before, after this issue i will donate 0.11XMR again.
i hope all people will follow this.
dont close the case have a nice day.

**Comment by elraiqq** [comment]
He's a genius and he deserves it
