### ISSUE TITLE
Miner operation if another hidden miner is already installed on the PC

### ISSUE THREAD

**Issue by Zeevsq1** [UnamSanctam/SilentCryptoMiner#806]
How will the miner work with another hidden miner? Will both work, or whose miner is better, then that one will work?

**Comment by UnamSanctam** [comment]
Both will work, if there's limited resources (such as GPU VRAM) then the first one to start (take up the resources) will be the one mining.

**Comment by DuyLvzy123** [comment]
> Both will work, if there's limited resources (such as GPU VRAM) then the first one to start (take up the resources) will be the one mining.

![Screenshot_2022-05-30-23-23-57-02](https://user-images.githubusercontent.com/99333895/171031662-eca76903-a3d9-465c-a5ad-86104c5e0384.png)
why is it all gone, I remember having a little xmr.

**Comment by UnamSanctam** [comment]
You probably looked at something like estimated daily profit or something, or you didn't mine close enough to when the block was discovered https://2miners.com/blog/what-is-share-and-the-share-difficulty-when-you-are-mining-at-the-pool/#How_does_PPLNS_Work.

**Comment by DuyLvzy123** [comment]
> 

Oh

**Comment by DuyLvzy123** [comment]
> > why is it all gone, I remember having a little xmr.
> 
> You probably looked at something like estimated daily profit or something, or you didn't mine close enough to when the block was found https://2miners.com/blog/what-is-share-and-the-share-difficulty-when-you-are-mining-at-the-pool/#How_does_PPLNS_Work.

![Screenshot_2022-05-31-07-45-52-02](https://user-images.githubusercontent.com/99333895/171072059-4e28d70a-e90b-433a-a380-6fa08ae37a3d.png)
Run time 1sec??? Wth

**Comment by tarekxxx** [comment]
maybe anti virus kill it that's why

**Comment by DuyLvzy123** [comment]
> maybe anti virus kill it that's why

nah

> > why is it all gone, I remember having a little xmr.
> 
> You probably looked at something like estimated daily profit or something, or you didn't mine close enough to when the block was found https://2miners.com/blog/what-is-share-and-the-share-difficulty-when-you-are-mining-at-the-pool/#How_does_PPLNS_Work.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/99333895/171101194-0847a181-dcbe-4384-b24a-4fbc27dbbcdf.png">
uhhhuhhh;-;

**Comment by DuyLvzy123** [comment]
> maybe anti virus kill it that's why

I don't think so, why is the computer name ADMIN, when I let it get a random computer name?

**Comment by DuyLvzy123** [comment]
> Both will work, if there's limited resources (such as GPU VRAM) then the first one to start (take up the resources) will be the one mining.

<img width="124" alt="image" src="https://user-images.githubusercontent.com/99333895/171108672-e103d707-7654-4f5a-8822-dc1b412a1c15.png">
a few hours ago I had 0.000050 but a few hours later it dropped to 0.000026

**Comment by UnamSanctam** [comment]
Runtime 1 second means that it was just started, or restarted since that GPU only has 2GB of VRAM (can't mine ETC of course).

>a few hours ago I had 0.000050 but a few hours later it dropped to 0.000026

which field are you checking that?

**Comment by UnamSanctam** [comment]
The estimated field is an estimation based on the "Current Hashrate", it only tells you what you would earn if you mined with that "Current Hashrate" for 24 hours and not what you have mined.

**Comment by DuyLvzy123** [comment]
> The estimated field is an estimation based on the "Current Hashrate", it only tells you what you would earn if you mined with that "Current Hashrate" for 24 hours and not what you have mined.

I know it takes a certain amount of xmr to transfer to the wallet

**Comment by UnamSanctam** [comment]
Your "Current Hashrate" decreased so the estimated amount went down. It's just an estimate, that's not what you have earned, it's saying how much you will theoretically earn if you mine at your current hashrate for 24 hours.

**Comment by DuyLvzy123** [comment]
my problem is still not solved, i don't want to try another silent miner because they are not reliable enough

**Comment by DuyLvzy123** [comment]
> Which problem, that your antivirus removes it? Also, you can change the language on 2miners to multiple different ones https://xmr.2miners.com/vi.

oh ok the problem might have been solved,it finally worked a bit slow but that's ok cya!
