### ISSUE TITLE
XMR help

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#81]
So i have a 2070 GPU and intel i7 cpu mining 3kh for monero, but would it be possible to switch it to Ravencoin with json configuration?

Since its a XMRig miner

https://i.imgur.com/cRij6vy.png but randomx and not kawpow algorithm.

**Comment by UnamSanctam** [comment]
Not unless you also had "GPU Mining" enabled since if you didn't then the XMRig CUDA libraries aren't there.

**Comment by Brainshot** [comment]
> Not unless you also had "GPU Mining" enabled since if you didn't then the XMRig CUDA libraries aren't there.

So a Intel(R) Core(TM) i7-10750H is mining at 3kh but when i lookup how much it can actually go its 2.1kh

is it possible for a GPU to be there?

**Comment by UnamSanctam** [comment]
What do you mean?

**Comment by Brainshot** [comment]
> What do you mean?

https://www.betterhash.net/Intel(R)-Core(TM)-i7-10750H-CPU-@-2.60GHz-mining-profitability-33978861.html

it shows 2.1kh mining is only possible with a i7-10750H but its mining at 3kh in my webpanel so could it be that a GPU is involved? the 20760 rtx

**Comment by Brainshot** [comment]
Is it worth it just try out the json code? if so do you have one for ravencoin?

**Comment by UnamSanctam** [comment]
No, if "GPU Mining" was disabled then the GPU isn't mining (and can't mine since the CUDA libraries aren't there). Those websites usually aren't very accurate.

**Comment by UnamSanctam** [comment]
> Is it worth it just try out the json code? if so do you have one for ravencoin?

I don't have one for Ravencoin but all you have to do is change the algorithm, pool, port and wallet address to Ravencoin (and algorithm to kawpow).

**Comment by Brainshot** [comment]
> > Is it worth it just try out the json code? if so do you have one for ravencoin?
> 
> I don't have one for Ravencoin but all you have to do is change the algorithm, pool, port and wallet address to Ravencoin (and algorithm to kawpow).

{
"algo": "kawpow",
"pool": "rvn.2miners.com",
"port": 6060,
"wallet": "MyWallet",
"password": "Worker",
"ssltls": true
}



this the json i used is it right?

**Comment by UnamSanctam** [comment]
Use `rig-id` instead of `password` and use port 16060 since you use SSL but yes other than that it should work.

**Comment by Brainshot** [comment]
thanks
