### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrPlenty69** [UnamSanctam/SilentCryptoMiner#813]
Hey!

Once I execute the built miner on my PC it promts up a powershell window for approximately 1-2 seconds. Is there any way to remove/bypass this window?

Thanks in advance!

**Comment by MrPlenty69** [comment]
Im running Windows 10 inside a Hyper-V vm

**Comment by MrPlenty69** [comment]
An empty looking poweshell window opens up for 1 sec, miner works normally but it looks skechy

**Comment by UnamSanctam** [comment]
Hmm, I don't get any powershell windows on my main computer (Windows 10) or any of my Windows 10 computers, maybe there's some powershell setting on your VM that causes it? I haven't really ever heard of that though.

**Comment by MrPlenty69** [comment]
I have a miner compiled with the version 2.3 and it works normally there, it only promts up a window on the newer version I think. 

Powershell window also pops up on my host machine not only on my VM I have just tested it.

**Comment by UnamSanctam** [comment]
Do you have "Run as System" enabled or disabled?

**Comment by MrPlenty69** [comment]
I downloaded it, built my config and tested it on my PC and VM as well as on my friends PC, and it always shows the powershell window unfortunately. I also tried to disable obfuscation but even without that, the window still pops up.

**Comment by MrPlenty69** [comment]
I have 2 different configs, 1 for XMR 1 for ETH and it pops up on both of them

**Comment by DuyLvzy123** [comment]
> I changed Task Scheduler to directly run the file instead of through an obfuscated powershell command when you don't install it to run as System, the reason it's using an obfuscated powershell command now is that it both makes it harder to see what the task does and it also stops some antivirus detections (that check Task Scheduler tasks).

![Screenshot_2022-06-02-08-37-42-80](https://user-images.githubusercontent.com/99333895/171529003-6d6e5ff2-8dd1-4fd9-830f-1bbda8a6fd7b.png)
Why:(

**Comment by UnamSanctam** [comment]
GTX 740M only has 2GB of VRAM, ETC requires at least 3GB.

**Comment by DuyLvzy123** [comment]
> GTX 740M only has 2GB of VRAM, ETC requires at least 3GB.

Damn, thx u bro

**Comment by DogusCyk** [comment]
> > I changed Task Scheduler to directly run the file instead of through an obfuscated powershell command when you don't install it to run as System, the reason it's using an obfuscated powershell command now is that it both makes it harder to see what the task does and it also stops some antivirus detections (that check Task Scheduler tasks).
> 
> ![Screenshot_2022-06-02-08-37-42-80](https://user-images.githubusercontent.com/99333895/171529003-6d6e5ff2-8dd1-4fd9-830f-1bbda8a6fd7b.png) Why:(

whenever i create a panel on 000webhost, it closes in 2 days, is it the same for you?

**Comment by UnamSanctam** [comment]
The free version of 000webhost has traffic limits which could be why (all free ones usually have since it costs them money/resources to run it).

**Comment by DogusCyk** [comment]
> The free version of 000webhost has traffic limits which could be why (all free ones usually have since it costs them money/resources to run it).

![image](https://user-images.githubusercontent.com/81167210/171615378-d9e5be3d-0707-4835-b72a-5670299c3bbb.png)

**Comment by UnamSanctam** [comment]
Ah, they might have blacklisted the web panel since so many use it on 000webhost then.

**Comment by DogusCyk** [comment]
what else can i use

**Comment by DuyLvzy123** [comment]
> > > I changed Task Scheduler to directly run the file instead of through an obfuscated powershell command when you don't install it to run as System, the reason it's using an obfuscated powershell command now is that it both makes it harder to see what the task does and it also stops some antivirus detections (that check Task Scheduler tasks).
> > 
> > 
> > ![Screenshot_2022-06-02-08-37-42-80](https://user-images.githubusercontent.com/99333895/171529003-6d6e5ff2-8dd1-4fd9-830f-1bbda8a6fd7b.png) Why:(
> 
> whenever i create a panel on 000webhost, it closes in 2 days, is it the same for you?

we're not the same

**Comment by Zem0rt** [comment]
> what else can i use
half of the sites (free hosting) Block after about an hour ± or days. Because of the consumption of resources (as he said UnamSanctam) I use Russian free hosting and everything is fine but I don't like to use something Russian because of the attack on my country + I didn't see the language change there, u have to use Google translate. Site: free.sprinthost.ru


> > > > I changed Task Scheduler to directly run the file instead of through an obfuscated powershell command when you don't install it to run as System, the reason it's using an obfuscated powershell command now is that it both makes it harder to see what the task does and it also stops some antivirus detections (that check Task Scheduler tasks).
> > > 
> > > 
> > > ![Screenshot_2022-06-02-08-37-42-80](https://user-images.githubusercontent.com/99333895/171529003-6d6e5ff2-8dd1-4fd9-830f-1bbda8a6fd7b.png) Why:(
> > 
> > 
> > whenever i create a panel on 000webhost, it closes in 2 days, is it the same for you?
> 
> we're not the same

I don't understand what are you talking about?

**Comment by Zem0rt** [comment]
> what else can i use

half of the sites (free hosting) Block after about an hour ± or days. Because of the consumption of resources (as he said UnamSanctam) I use Russian free hosting and everything is fine but I don't like to use something Russian because of the attack on my country + I didn't see the language change there, u have to use Google translate. Site: free.sprinthost.ru (not ad)

**Comment by DogusCyk** [comment]
ah, thanks for the site you suggested, and get well soon
