### ISSUE TITLE
Offtopic question

### ISSUE THREAD

**Issue by varysuzuki** [UnamSanctam/SilentCryptoMiner#815]
I added /ru System to my task scheduler startup on my quasarrat and now it opens 2 rat clients on 1 pc, one being admin level and another being system. And now im curious how does the rat being ran as system bypass the mutex?

**Comment by UnamSanctam** [comment]
You'd need to prefix the mutex with `Global\` for it to apply to all users which I'm guessing they don't do.

**Comment by shainodev** [comment]
Thank you, Oh and also since the miner runs as system, couldn't you make the watchdog or miner a service/start from a service?

**Comment by shainodev** [comment]
> You'd need to prefix the mutex with `Global\` for it to apply to all users which I'm guessing they don't do.

and also do you know what server signature/server certificate is used for? or is it needed if i rat cause asyncrat and quasar has it, like if i wanted to create my own rat do i have to add it?

**Comment by UnamSanctam** [comment]
> Thank you, Oh and also since the miner runs as system, couldn't you make the watchdog or miner a service/start from a service?

It could theoretically run as a service but there needs to be a lot of testing first, and I'm not sure it would actually be beneficial.

> and also do you know what server signature/server certificate is used for? or is it needed if i rat cause asyncrat and quasar has it, like if i wanted to create my own rat do i have to add it?

Probably it's used to encrypt the traffic between the client and the server, it isn't necessary but can be good to have.

**Comment by shainodev** [comment]
> Probably it's used to encrypt the traffic between the client and the server, it isn't necessary but can be good to have.
so i dont risk anything if i dont use it?

**Comment by shainodev** [comment]
and also if u do know, how do i know if my rat is stable or not

**Comment by UnamSanctam** [comment]
> so i dont risk anything if i dont use it?

Well the connection would just be unencrypted.

> and also if u do know, how do i know if my rat is stable or not

You'd just have to test it a lot, just like how I do for the miner, I just have VMs for every Windows version and test everything multiple times as much as I can.

**Comment by shainodev** [comment]
> 

YO AND ALSSOOOOOOO do you know why they use like a dll file to hande packets and that like Quasar.Common and Async uses some messagehandler other than just making it directly read commands and stuff

**Comment by UnamSanctam** [comment]
I haven't checked their projects in quite some time but isn't it so that the client and server can use the same code without having to maintain it in two places?

**Comment by shainodev** [comment]
> I haven't checked their projects in quite some time but isn't it so that the client and server can use the same code without having to maintain it in two places?

no with that thing they have to maintain it in 3 places

**Comment by UnamSanctam** [comment]
No it looks like Quasar.Common contains the common methods between the server and client so that it only has to be maintained once and then both the client and server reference it.

**Comment by shainodev** [comment]
> No it looks like Quasar.Common contains the common methods between the server and client so that it only has to be maintained once and then both the client and server reference it.

thats harder to do tho no?

**Comment by UnamSanctam** [comment]
Not necessarily. It's a bit different but it's also a big reason why I combined the miners into SilentCryptoMiner, maintaining two projects (much like the client and server) with large chunks of identical code is difficult to do.

**Comment by shainodev** [comment]
u should make a simple rat loader that only has a run file in disk and run file in memory. that would be a great addon
