### ISSUE TITLE
I have accidentally downloaded and ran my own exe during tests and don't have the uninstaller. What are my options?

### ISSUE THREAD

**Issue by XcentricX** [UnamSanctam/SilentCryptoMiner#816]

**Comment by golxd** [comment]
https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner

**Comment by XcentricX** [comment]
Thanks, but this didn't fully work. I have a few problems that I think would be better solved in a voice call. Anyway I can do that?

**Comment by UnamSanctam** [comment]
Following that wiki page will fully remove the miner, if you also had the rootkit then run https://github.com/UnamSanctam/SilentCryptoMiner/raw/master/SilentCryptoMiner/Resources/rootkit-u.zip.

**Comment by XcentricX** [comment]
Thanks, It's just that
1. process killer did not actually end the processes. It ended the conhost.exe files but the svchost.exe files did not get removed. I counted them after ending about 10 of them and it didnt change.
2. I opened up my registry editor and the HKEY_CURRENT_USER didnt display any information except a single file named (default)
What am I doing wrong?

**Comment by XcentricX** [comment]
Just to add to that, I went on process killer and ended the bottom svchost process, but the bottom one had the same id everytime, so it wasnt being deleted

**Comment by UnamSanctam** [comment]
1. You just need to first find the conhost.exe with the short random string after it and kill that one. Then find the injected miner processes (by default explorer.exe but sounds like you chose svchost.exe) with a very large encrypted string after them and kill those.
2. Did you install it as administrator or not? If you did then you fill find the startup task inside the Task Scheduler.

**Comment by Bartixxx32** [comment]
I just wonder, if its not easier to build same miner again with name and config and disable startup on boot then run it and use uninstaller? I think it should atleast remove it from install dir and autorun

**Comment by UnamSanctam** [comment]
Technically yes, but you'd still have to kill the watchdog and the miners yourself since the hidden key for them will be different in the new version.
