### ISSUE TITLE
What is the code of the miner? What is the code of the miner.exe??

### ISSUE THREAD

**Issue by Anonymoussssssy** [UnamSanctam/SilentCryptoMiner#817]
The only code I can find is the settings code. I need to know the code of the miner so I can mix it with another malware to create a hybrid malware.

**Comment by UnamSanctam** [comment]
I don't have time to manage two more repositories and the responsibilities thereof (and a few other reasons I've answered in previous issues but I'm on my phone so typing it out is a bit hard) so there aren't any repositories for them. You can find the base miners here though: https://github.com/xmrig/xmrig, https://github.com/ethereum-mining/ethminer.

**Comment by suckmybig** [comment]
He doesnt show his code because you see his wallet and his rootkits.

The miner is backdoored you idiots. ;D

**Comment by UnamSanctam** [comment]
> He doesnt show his code because you see his wallet and his rootkits.
> 
> The miner is backdoored you idiots. ;D

Can you stop your trolling posts? People might actually believe you and I don't want to block you (or anyone).

**Comment by Anonymoussssssy** [comment]
> 

I searched them and all the files contain code some javascript here and there, I need a specific code that I can simply put my wallet nicehash in then put into my malware

**Comment by UnamSanctam** [comment]
> I searched them and all the files contain code some javascript here and there, I need a specific code that I can simply put my wallet nicehash in then put into my malware

No those are the full xmrig and ethminer miners, you'd need to code your wallets into them and then compile them.

**Comment by Anonymoussssssy** [comment]
> > I searched them and all the files contain code some javascript here and there, I need a specific code that I can simply put my wallet nicehash in then put into my malware
> 
> No those are the full xmrig and ethminer miners, you'd need to code your wallets into them and then compile them.

The question is, after I compile them how can I mix their code with my already existing malware so I can also make the malware mine in the background while doing an attack in the vm somewhere else

**Comment by XGhostONE** [comment]
> > > I searched them and all the files contain code some javascript here and there, I need a specific code that I can simply put my wallet nicehash in then put into my malware
> > 
> > 
> > No those are the full xmrig and ethminer miners, you'd need to code your wallets into them and then compile them.
> 
> The question is, after I compile them how can I mix their code with my already existing malware so I can also make the malware mine in the background while doing an attack in the vm somewhere else

Lol bro, dumb or something?
