### ISSUE TITLE
Can someone give some examples of both ETH and XMR Pools? I think mine are incorrect.

### ISSUE THREAD

**Issue by joshtanner2132** [UnamSanctam/SilentCryptoMiner#82]
Currently mine are
XMR: xmr-us-east1.nanopool.org:14433
ETH: eth-us-east1.nanopool.org:9999
I've mined for around 30 minutes with a test build on my machine, and no workers showing on nanopool, or in the Web Panel.

**Comment by UnamSanctam** [comment]
Can you "Save" your configuration and post it here?

**Comment by joshtanner2132** [comment]
Here you go. Had to add it to a zip because github doesn't allow you to attach xml files
[Test Build 2.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/7579317/Test.Build.2.zip)
s

**Comment by joshtanner2132** [comment]
Also I have stealth disabled because it is a test build, yet whenever i open task manager i can see, for example svchost.exe at the top of my task manager before it quickly disappears for some reason

**Comment by joshtanner2132** [comment]
Also if you have a moment could you look at my pastebin and make sure my remote config is correct? It's in the test build

**Comment by UnamSanctam** [comment]
Both of those miners work fine, remember that you have "Stealth" enabled in your "Remote Configuration".
