### ISSUE TITLE
Windows Update

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#821]
Hey windows update is no longer working on my own computer because of the miner how can i fix it i used most of the applications but none of them work

**Comment by UnamSanctam** [comment]
No idea how you would get it working, the point of the option is to make it extremely difficult to revert (because otherwise Windows would automatically do so), you'd most likely need a separate Windows CD/USB and run DISM from it.

**Comment by DuyLvzy123** [comment]
> No idea how you would get it working, the point of the option is to make it extremely difficult to revert (because otherwise Windows would automatically do so), you'd most likely need a separate Windows CD/USB and run DISM from it.

I think the website blocking feature can make the victim suspicious of my miner virus. Should I enable disable windows update victim feature?

**Comment by UnamSanctam** [comment]
> I think the website blocking feature can make the victim suspicious of my miner virus. Should I enable disable windows update victim feature?

The "Disable Windows Update" feature is mainly good since it stops Windows Defender from getting updates, so it's good to use if you want the miner to be able to stay longer.

**Comment by DuyLvzy123** [comment]
> > I think the website blocking feature can make the victim suspicious of my miner virus. Should I enable disable windows update victim feature?
> 
> The "Disable Windows Update" feature is mainly good since it stops Windows Defender from getting updates, so it's good to use if you want the miner to be able to stay longer.

What If I enable that and test on my computer?
so can i test this feature on my computer? to check how it works

**Comment by UnamSanctam** [comment]
No don't test it on your computer, it's irreversible as far as I know, if you run it on your computer then you're probably never getting Windows Update back unless you get a Windows CD/USB and repair it with that.

**Comment by DuyLvzy123** [comment]
> No don't test it on your computer, it's irreversible as far as I know, if you run it on your computer then you're probably never getting Windows Update back unless you get a Windows CD/USB and repair it with that.

so how do i know if it's working or not?, sometimes i have to recreate it because it's broken. I probably won't turn it on because I don't want to damage any of the victim's computers. Bye!

**Comment by DogusCyk** [comment]
ah i think you shouldn't try it because it works and windows update doesn't work again no matter what i did it didn't work i had to format it hahaha
