### ISSUE TITLE
FullscreenDetection 

### ISSUE THREAD

**Issue by Ninja133** [UnamSanctam/SilentCryptoMiner#823]
first of all thank you for your work 
my questions is there is any way to make FullscreenDetection  QUNS_BUSY
for our old bot miners

**Comment by UnamSanctam** [comment]
Not sure what you mean, are you wondering if you can use "Stealth on Fullscreen" in the old miners? In that case no since there's no code for that in them. If you mean the FullscreenDetection program then I'm not sure what you mean, the program just reports what notification state Windows is in.

**Comment by Ninja133** [comment]
yes i mean notification state in task manger maybe but that is not the case right 
thank you anyway
