### ISSUE TITLE
etc-eth

### ISSUE THREAD

**Issue by Zeevsq1** [UnamSanctam/SilentCryptoMiner#824]
It takes a very long time to change the etc configuration to eth. I used the latest version

**Comment by UnamSanctam** [comment]
It won't change while it's loading things, changing the configuration will always take between 1-10 minutes at max.

**Comment by Zeevsq1** [comment]
> Он не изменится во время загрузки, изменение конфигурации всегда будет занимать от 1 до 10 минут (максимум во всех версиях). Если вы говорите об «Удаленной настройке», то она выполняется каждые 100 минут.



> It won't change while it's loading things, changing the configuration will always take between 1-10 minutes at max (it's the same in all version). If you're talking about the "Remote Configuration" then it gets it every 100 minutes.

I use a web panel and the configuration does not change after a day on some miners. Before that, the shift took 5 minutes, but now I'm following some miners, from the beginning of the day and the configuration remains on the ETC

**Comment by UnamSanctam** [comment]
Maybe it isn't applying it on the first configuration check (first time it populates the cache), if you change it again (something in the "url", you can add like an `X` before your worker name) does it change?

**Comment by Zeevsq1** [comment]
![Annotation 2022-06-06 070943](https://user-images.githubusercontent.com/101643042/172074407-cf57ebce-bedd-4bf6-924a-92b385a06978.png)
i changed settings for xmr from set to 0 mining load, but etc doesn't change. (I changed the name of the miner)

**Comment by UnamSanctam** [comment]
You changed the worker name in the ETH configuration and it didn't switch connection?

**Comment by UnamSanctam** [comment]
Looks like it wasn't activating the new configuration on the first change, any other changes after that will active the new pool. In my testing the configuration gets prepopulated so I never noticed but I've changed it in the new version to active the new pool connection when added (it's a bit more complicated than that but that's the simple explanation).

**Comment by Zeevsq1** [comment]
> Looks like it wasn't activating the new configuration on the first change, any other changes after that will active the new pool. In my testing the configuration gets prepopulated so I never noticed but I've changed it in the new version to active the new pool connection when added (it's a bit more complicated than that but that's the simple explanation).

thanks
