### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by Bartixxx32** [UnamSanctam/SilentCryptoMiner#826]
I have and idea for feature (idk if its easy to do but)

Displaying GPU Temperature on webpanel and FAN speed, it may be good to tweak settings of miner remotley to make it less obvious for user that he is minning becouse of reading temps and fan speed, we can imagine how loud gpu may be.

The miner would be less obvius when gpu is at 60C and 30% fan speed, other than 80C and 90% fan speed :P

Or maybe some kind of temp limit? or fan limit? to set for example if fan is =>50% pause, or throttle miner down by for example 2x. Im not talking about implementing advanced logic for auto tune miner, but just 0/1 if fan is at some point just go stealh or for example divide current max gpu by half.

**Comment by UnamSanctam** [comment]
Yes I'm planning to eventually create some sort of resources field that shows RAM, VRAM, etc but there's quite a lot to do for it. But in the current miner there is a temperature start/stop function that you can enable by adding `--HWMON=1 --tstart=60 --tstop=80` into the "Advanced Parameters" of the ETH miner, with those settings it would pause the miner when the GPU reaches 80°C and then resume it again when it goes back down to 60°C.

**Comment by Bartixxx32** [comment]
yeah, but in this case were not talking about power usage, just basics, im pretty sure every card can report atleast temp, i know that with amd may be issues, becouse i have radeon rx480 and as i remember in some miners, i did not get fan/temp reports saying 0C/0% anyway i will wait patiently following your work.
