### ISSUE TITLE
miner don't work unless the computer restart 

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#841]
Miner don't appear on web panel and don't mine unless the computer restarts after opening the  miner file. Checker file screenshot is attached for more details. 
![d](https://user-images.githubusercontent.com/101794261/172910350-129ccc61-e19a-47db-8fb4-9b801d3dfe94.png)

**Comment by UnamSanctam** [comment]
Could be the rootkit, try disabling it.

**Comment by DerXanRam** [comment]
> Miner don't appear on web panel and don't mine unless the computer restarts after opening the miner file. Checker file screenshot is attached for more details. ![d](https://user-images.githubusercontent.com/101794261/172910350-129ccc61-e19a-47db-8fb4-9b801d3dfe94.png)

oooo...sorry it worked after 8 min and 23 sec
