### ISSUE TITLE
Error, mining not activated

### ISSUE THREAD

**Issue by kevincrafturu2** [UnamSanctam/SilentCryptoMiner#842]
So, hi to all, im trying to mining to a popular cyber cafe in my location,  so i created the miner and to test i executed in my PC (processor i3-2100 8gb ram integrated grapichs) and the miner Just dont start,  im using Ethermine pool, and im using the debug mode to try it again but the first time it dosent work i will make a vid to show the error

**Comment by kevincrafturu2** [comment]
Like it "starts" but in the checker there no appears anything and in the panel dosent appear anything too

**Comment by UnamSanctam** [comment]
Are you only trying to mine ETH? And do you have a GPU to test with (it will ignore integrated graphics as best it can to avoid lag)?

**Comment by kevincrafturu2** [comment]
Yes i was trying to mine ETHEREUM the normal, and i dont have GPU i have integrated

**Comment by kevincrafturu2** [comment]
Because my wallet (TrustWallet) dosent have XMR and its the one that i ussualy use

**Comment by UnamSanctam** [comment]
Then it won't start the GPU miner, since you don't have a real GPU to mine on.

**Comment by kevincrafturu2** [comment]
Ooooh yea, its there an other miner like to TRON? or somthing to mine that it dosent use GPU???

**Comment by kevincrafturu2** [comment]
maybe can i test the program in  the cyber in a couple of hours,  but thanks for the fast response

**Comment by kevincrafturu2** [comment]
Well that would explain everything since the watchdog if it opens through the checker shows that it is open and says that there is no GPU available, forgive my ignorance hehe, I'm new to all this but thank you very much sir!

**Comment by kevincrafturu2** [comment]
Ye, so i will make a lot of miners to mine a lot , thanks for the help men.

**Comment by kevincrafturu2** [comment]
And an ultimate thing and i close the comment, it will be soo goood if u make a tron miner, tron its a crypto with the ethereum net but more good i guest, i own like 4 bucks of that so have a nice day bro!
