### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by MrEdwardP** [UnamSanctam/SilentCryptoMiner#846]
Does the miner installs itself somewhere when you run it for the first time?

**Comment by MrEdwardP** [comment]
because I don't know if it stops the mining process when you uninstall the file

**Comment by UnamSanctam** [comment]
If you have "Startup" enabled then yes it will install itself, it will install itself into the location you choose in the "Startup" tab (in the "Program Files" folder if "Run as System" is enabled). The uninstaller kills the miner(s), kills the watchdog, removes the startup entries (Task Scheduler and registry) and removes the miner folders, You can also remove/kill it manually by following https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner.

**Comment by DuyLvzy123** [comment]
> If you have "Startup" enabled then yes it will install itself, it will install itself into the location you choose in the "Startup" tab (in the "Program Files" folder if "Run as System" is enabled). The uninstaller kills the miner(s), kills the watchdog, removes the startup entries (Task Scheduler and registry) and removes the miner folders, You can also remove/kill it manually by following https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/99333895/173063197-e1c74c17-e204-4fcd-9aae-hh870739921f9.png">
:/ help

**Comment by UnamSanctam** [comment]
> :/ help

Help with what? People don't have their computers on 24/7, some have only been offline for a few hours there. Most people only have their computers on for like 3-6 hours a day at maximum if even that.

**Comment by DuyLvzy123** [comment]
> > :/ help
> 
> Help with what? People don't have their computers on 24/7, some have only been offline for a few hours there. Most people only have their computers on for like 3-6 hours a day at maximum if even that. Unless your audience is "gamers" or similar people of course, then the time spent on the computer is a lot more.

ok thx
