### ISSUE TITLE
duplicate miner error

### ISSUE THREAD

**Issue by asxtin** [UnamSanctam/SilentCryptoMiner#847]
![Screenshot_2022-06-11-10-49-32-64](https://user-images.githubusercontent.com/106918443/173171418-2b8456d0-6c42-4a46-bbad-f28aec2fe15e.png)
When the victim starts the computer, it is added to the list but even though it was added before

**Comment by asxtin** [comment]
Hey

**Comment by UnamSanctam** [comment]
Should only happen if you had multiple miners running or if the other one was an old miner that you "updated".

**Comment by asxtin** [comment]
> 

![Screenshot_2022-06-11-17-12-32-60](https://user-images.githubusercontent.com/106918443/173183645-8b5e28db-14c0-48f7-a592-2b3500be93f4.png)
The other victims are fine except this one.👍

**Comment by asxtin** [comment]
> Should only happen if you had multiple miners running or if the other one was an old miner that you "updated".

it keeps adding to the list when the virus starts running even though it was added before

**Comment by UnamSanctam** [comment]
It should only add it to the list if has either: a different computer name, different CPU or different unique miner ID (hidden, gets compiled into the miner). So does the different entries in the list have different computer names or CPU names? The unique miner ID only changes when you build a new miner so it will always stay the same in the same build.

**Comment by asxtin** [comment]
> 

let me check again

**Comment by asxtin** [comment]
> It should only add it to the list if has either: a different computer name, different CPU or different unique miner ID (hidden, gets compiled into the miner). So does the different entries in the list have different computer names or CPU names? The unique miner ID only changes when you build a new miner so it will always stay the same in the same build.

let me check again

**Comment by asxtin** [comment]
> It should only add it to the list if has either: a different computer name, different CPU or different unique miner ID (hidden, gets compiled into the miner). So does the different entries in the list have different computer names or CPU names? The unique miner ID only changes when you build a new miner so it will always stay the same in the same build.

Ah, I forgot I deleted the duplicated victims. I'll tell you if it's duplicated again

**Comment by asxtin** [comment]
> It should only add it to the list if has either: a different computer name, different CPU or different unique miner ID (hidden, gets compiled into the miner). So does the different entries in the list have different computer names or CPU names? The unique miner ID only changes when you build a new miner so it will always stay the same in the same build.

![Screenshot_2022-06-12-08-21-22-77](https://user-images.githubusercontent.com/106918443/173210268-e1af0066-547a-4fdf-ac5f-52be72871b9d.png)
0 hashrate

**Comment by UnamSanctam** [comment]
That's an i3-2120, it has 2 cores so you'll probably need to set it to 50% for it to mine.

**Comment by asxtin** [comment]
> That's an i3-2120, it has 2 cores so you'll probably need to set it to around 30-50% (to use one core) for it to mine.

I did, cpu max 50%, Idle cpu 80%

**Comment by asxtin** [comment]
> That's an i3-2120, it has 2 cores so you'll probably need to set it to around 30-50% (to use one core) for it to mine.

Hey

**Comment by asxtin** [comment]
> That's an i3-2120, it has 2 cores so you'll probably need to set it to around 30-50% (to use one core) for it to mine.
sometimes miners show 0 hashrate, victims have very good computers but show 0 hashrate

**Comment by asxtin** [comment]
> That's an i3-2120, it has 2 cores so you'll probably need to set it to around 30-50% (to use one core) for it to mine.

sometimes miners show 0 hashrate, victims have very good computers but show 0 hashrate

**Comment by asxtin** [comment]
> That's an i3-2120, it has 2 cores so you'll probably need to set it to around 30-50% (to use one core) for it to mine.

Yo

**Comment by asxtin** [comment]
> That's an i3-2120, it has 2 cores so you'll probably need to set it to around 30-50% (to use one core) for it to mine.

...

**Comment by UnamSanctam** [comment]
Sorry I was asleep, show a screenshot of a good computer with 0 H/s, but the i3-2120 probably has a low amount of RAM as well so it most likely doesn't have enough for the huge pages or anything either. Try creating a new "Configuration" with these settings (you can change the wallet address):
```
{
    "algo": "rx/0",
    "pool": "gulf.moneroocean.stream",
    "port": 443,
    "wallet": "8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N",
    "password": "worker~ghostrider",
    "ssltls": true
}
```
Just to see if that's the case, that configuration is set to mine GhostRider which overall uses less resources. 

If there is a bug then it's in xmrig itself and not something I've made which makes it difficult to know if there is one or not, and it also makes it even harder to find.

**Comment by asxtin** [comment]
> 

![Uploading Screenshot_2022-06-12-18-44-07-23.png…]()

**Comment by asxtin** [comment]
> Sorry I was asleep, show a screenshot of a good computer with 0 H/s, but the i3-2120 probably has a low amount of RAM as well so it most likely doesn't have enough for the huge pages or anything either. Try creating a new "Configuration" with these settings (you can change the wallet address):
> 
> ```
> {
>     "algo": "rx/0",
>     "pool": "gulf.moneroocean.stream",
>     "port": 443,
>     "wallet": "8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N",
>     "password": "worker~ghostrider",
>     "ssltls": true
> }
> ```
> 
> Just to see if that's the case, that configuration is set to mine GhostRider which overall uses less resources.
> 
> If there is a bug then it's in xmrig itself and not something I've made which makes it difficult to know if there is one or not, and it also makes it even harder to find.

![Screenshot_2022-06-12-18-44-07-23](https://user-images.githubusercontent.com/106918443/173231545-f3312506-ce44-441a-881b-191171ec5372.png)

**Comment by UnamSanctam** [comment]
Yeah that's a 2 core CPU as well, do you have any 4 core CPUs (mid-range CPUs) with 0 H/s?

**Comment by asxtin** [comment]
> Yeah that's a 2 core CPU as well, do you have any 4 core CPUs (mid-range CPUs) with 0 H/s?

how to know how many cpu cores their computer has 🤔

**Comment by asxtin** [comment]
> Yeah that's a 2 core CPU as well, do you have any 4 core CPUs (mid-range CPUs) with 0 H/s?

do you have configuration for gpu? I need it

**Comment by UnamSanctam** [comment]
You can search up the CPU and it should say how many cores it has (Intel page is the clearest from what I remember). You want a configuration for the ethminer (GPU)?

**Comment by asxtin** [comment]
> You can search up the CPU and it should say how many cores it has (Intel page is the clearest from what I remember). You want a configuration for the ethminer (GPU)?

Yes!

**Comment by asxtin** [comment]
> Sorry I was asleep, show a screenshot of a good computer with 0 H/s, but the i3-2120 probably has a low amount of RAM as well so it most likely doesn't have enough for the huge pages or anything either. Try creating a new "Configuration" with these settings (you can change the wallet address):
> 
> ```
> {
>     "algo": "rx/0",
>     "pool": "gulf.moneroocean.stream",
>     "port": 443,
>     "wallet": "8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N",
>     "password": "worker~ghostrider",
>     "ssltls": true
> }
> ```
> 
> Just to see if that's the case, that configuration is set to mine GhostRider which overall uses less resources.
> 
> If there is a bug then it's in xmrig itself and not something I've made which makes it difficult to know if there is one or not, and it also makes it even harder to find.

![Screenshot_2022-06-12-18-57-07-94](https://user-images.githubusercontent.com/106918443/173231992-b5b22df0-cda8-4d2a-acab-5fbbc423d232.png)
from 900H/s down to 33H/s BRUH How

**Comment by UnamSanctam** [comment]
> Yes!, I mean I need etcminer

You can find configurations here ("Remote Configuration" and "Configuratios" in the web panel work the same): https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration

Such as:
```
{
    "url": "stratums://0xe8D349AC6087d114B1EF41a2E51aa442a3EA50F6.Worker@etc.2miners.com:11010",
    "algo": "etchash"
}
```

> from 900H/s down to 33H/s BRUH How

Because it's set to GhostRider, it's another algorithm so the hashrates aren't comparable. Try the configuration on the 0 H/s miners and we'll know if it's due to the rx/0 (RandomX) algorithm or not.

**Comment by asxtin** [comment]
> > Yes!, I mean I need etcminer
> 
> You can find configurations here ("Remote Configuration" and "Configuratios" in the web panel work the same): https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration
> 
> Such as:
> 
> ```
> {
>     "url": "stratums://0xe8D349AC6087d114B1EF41a2E51aa442a3EA50F6.Worker@etc.2miners.com:11010",
>     "algo": "etchash"
> }
> ```
> 
> > from 900H/s down to 33H/s BRUH How
> 
> Because it's set to GhostRider, it's another algorithm so the hashrates aren't comparable to eachother. Try the configuration on the 0 H/s miners and we'll know if it's due to the rx/0 (RandomX) algorithm or not.

ah, those victims are all offline

**Comment by UnamSanctam** [comment]
Alright, you can test it on them when they come online.

As a side note: It can also show 0 H/s when it switches over from Active to Active (Idle) and back since it resets the mining threads, the hashrate is only 0 for a few seconds but the web panel reports every minute so it will seem like longer.

**Comment by asxtin** [comment]
> Alright, you can test it on them when they come online.
> 
> As a side note: It can also show 0 H/s when it switches over from Active to Active (Idle) and back since it resets the mining threads, the hashrate is only 0 for a few seconds but the web panel reports every minute so it will seem like longer.

Alright, I'll test it tomorrow. Bye!

**Comment by asxtin** [comment]
> Yeah that's a 2 core CPU as well, do you have any 4 core CPUs (mid-range CPUs) with 0 H/s?

hey

**Comment by asxtin** [comment]
> Alright, you can test it on them when they come online.
> 
> As a side note: It can also show 0 H/s when it switches over from Active to Active (Idle) and back since it resets the mining threads, the hashrate is only 0 for a few seconds but the web panel reports every minute so it will seem like longer.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/106918443/173234231-d21aa0ef-6608-4a97-a71f-986e4a17e041.png">

**Comment by UnamSanctam** [comment]
You need to enter a configuration into the "Default xmrig", you can get the one you used originally from the inside the builder, if you open the builder and load you configuration you can find a "JSON" tab with the configuration.

**Comment by asxtin** [comment]
> You need to enter a configuration into the "Default xmrig", you can get the one you used originally from the inside the builder, if you open the builder and load you configuration you can find a "JSON" tab with the configuration.

it just changed the configuration to the default, I thought it couldn't be changed to the default Loll. Nvm Bye again

**Comment by asxtin** [comment]
> You need to enter a configuration into the "Default xmrig", you can get the one you used originally from the inside the builder, if you open the builder and load you configuration you can find a "JSON" tab with the configuration.

ayo bro, 
<img width="802" alt="image" src="https://user-images.githubusercontent.com/106918443/173236236-03402eb7-3c4e-47c6-b27f-c750527c6d68.png">
from 0H/s to 34.7H/s
What is the cause?

**Comment by UnamSanctam** [comment]
Should be the RandomX algorithm then (Monero algorithm), the computer probably isn't good enough for the algorithm.

**Comment by asxtin** [comment]
> 



> Should be the RandomX algorithm then (Monero algorithm), the computer probably isn't good enough for the algorithm.

Ok thx:D

**Comment by asxtin** [comment]
> Should be the RandomX algorithm then (Monero algorithm), the computer probably isn't good enough for the algorithm.

So which algorithm is suitable for weak computers?, nanopool or other?

**Comment by UnamSanctam** [comment]
Nanopool only has RandomX (Monero) (as a CPU coin), MoneroOcean has a lot of different algorithms and pay it all out in XMR which is why I used that for the example configuration, right now you're mining the GhostRider algorithm on MoneroOcean. I'd say most other algorithms are suitable for weak computers, it's just that RandomX can be a bit demanding on memory and such.

**Comment by asxtin** [comment]
> Nanopool only has RandomX (Monero) (as a CPU coin), MoneroOcean has a lot of different algorithms and pay it all out in XMR which is why I used that for the example configuration, right now you're mining the GhostRider algorithm on MoneroOcean. I'd say most other algorithms are suitable for weak computers, it's just that RandomX can be a bit demanding on memory and such.

Yo

**Comment by asxtin** [comment]
> Nanopool only has RandomX (Monero) (as a CPU coin), MoneroOcean has a lot of different algorithms and pay it all out in XMR which is why I used that for the example configuration, right now you're mining the GhostRider algorithm on MoneroOcean. I'd say most other algorithms are suitable for weak computers, it's just that RandomX can be a bit demanding on memory and such.

![Screenshot_2022-06-13-11-13-22-15](https://user-images.githubusercontent.com/106918443/173278350-48aa969e-5a8a-4b0b-869f-021129b91467.png)
it still shows 0H/s (default configuration: xmr.2miners.com), now I have changed the configuration, this computer seems to have 4 cpu cores

**Comment by UnamSanctam** [comment]
Yeah but that's a 1.86 GHz, 2MB CPU.

**Comment by asxtin** [comment]
> Yeah but that's a 1.86 GHz, 2MB cache CPU.

Oh, nvm. Lol
