### ISSUE TITLE
Monero Ocean

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/SilentCryptoMiner#849]
Good afternoon Unam. Please tell me, some of my workers mine Monero through Xmrig Proxy. And very often in Xmrig Proxy I see the following warnings:
1. rejected "Unauthenticated" no active pools, stop
2. Throttled down share submission (please increase difficulty)
These errors may be related to the settings Xmrig Proxy?

**Comment by UnamSanctam** [comment]
You need to increase the difficulty, choose a higher port.

**Comment by masterjek** [comment]
Thanks for the answer.
