### ISSUE TITLE
query

### ISSUE THREAD

**Issue by steelstealer** [UnamSanctam/SilentCryptoMiner#85]
what is ssl/tsl used for in the miner ?
how does it benefits us if we choose ssl/tsl ports for mining and enable in the builder?

**Comment by UnamSanctam** [comment]
https://en.wikipedia.org/wiki/Transport_Layer_Security, if you use SSL then the connection to the pool will be secure, meaning reading the traffic is really difficult and it's harder to block.

**Comment by DogusCyk** [comment]
> https://en.wikipedia.org/wiki/Transport_Layer_Security, if you use SSL then the connection to the pool will be secure, meaning reading the traffic is really difficult and it's harder to block.

Will the ssl option work on every computer?

**Comment by UnamSanctam** [comment]
Yes, as long as the pool supports SSL it should work.
