### ISSUE TITLE
Getting a file not found error when I press build after inputting all the settings I'd like, is there something I'm missing?

### ISSUE THREAD

**Issue by Raviolioil** [UnamSanctam/SilentCryptoMiner#852]
Getting a file not found error when I press build after inputting all the settings I'd like, is there something I'm missing?
![image](https://user-images.githubusercontent.com/106945817/173283043-1f476f97-081c-4707-a58d-7dda7bdd92ac.png)

**Comment by UnamSanctam** [comment]
The watchdog couldn't find the miner file, but that's not an error from when you press build, that's an error from when the watchdog runs.
