### ISSUE TITLE
using ConfuserEX but when I scan for viruses it has 33 viruses

### ISSUE THREAD

**Issue by asxtin** [UnamSanctam/SilentCryptoMiner#854]
![FB_IMG_16551626852220115](https://user-images.githubusercontent.com/106918443/173463628-bdd3d15d-7284-4791-9b13-e10de1a4341a.jpg)
is there any way to reduce detection?:(

**Comment by asxtin** [comment]
....

**Comment by asxtin** [comment]
...

**Comment by DuyLvzy123** [comment]
hello?

**Comment by UnamSanctam** [comment]
Well you shouldn't really scan with VirusTotal, but if you want even lower detection then you'll need to find another obfuscator or change around the obfuscator settings, all really good obfuscators are paid ones though of course.

**Comment by asxtin** [comment]
> 

i need good free or paid obfuscator, crypter too. Do you know anyone selling?

**Comment by asxtin** [comment]
> Well you shouldn't really scan with VirusTotal, but if you want even lower detection then you'll need to find another obfuscator or change around the obfuscator settings, all really good obfuscators are paid ones though of course.

i need good free or paid obfuscator, crypter too. Do you know anyone selling?( bad english )

**Comment by asxtin** [comment]
> Well you shouldn't really scan with VirusTotal, but if you want even lower detection then you'll need to find another obfuscator or change around the obfuscator settings, all really good obfuscators are paid ones though of course.

...

**Comment by oanna500** [comment]
> ![FB_IMG_16551626852220115](https://user-images.githubusercontent.com/106918443/173463628-bdd3d15d-7284-4791-9b13-e10de1a4341a.jpg) is there any way to reduce detection?:(

thanks for using VirusTotal, idiot...

**Comment by UnamSanctam** [comment]
> i need good free or paid obfuscator, crypter too. Do you know anyone selling?( bad english )

Not right now, it's been quite a while since I last tried/bought a paid obfuscator/crypter, as a commercial obfuscator .NET Reactor is generally quite good but I don't know of its current detection rates for potential malware.

**Comment by asxtin** [comment]
> > i need good free or paid obfuscator, crypter too. Do you know anyone selling?( bad english )
> 
> Not right now, it's been quite a while since I last tried/bought a paid obfuscator/crypter, as a commercial obfuscator .NET Reactor is generally quite good but I don't know of its current detection rates for potential malware.

ohhh:/

**Comment by asxtin** [comment]
> > i need good free or paid obfuscator, crypter too. Do you know anyone selling?( bad english )
> 
> Not right now, it's been quite a while since I last tried/bought a paid obfuscator/crypter, as a commercial obfuscator .NET Reactor is generally quite good but I don't know of its current detection rates for potential malware.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/106918443/173586614-feb16604-4a9b-41cb-b2cf-0d408464bfa9.png">
why when i switch to another server(mining pool) it shows 0H/s

**Comment by asxtin** [comment]
> > why when i switch to another server(mining pool) it shows 0H/s
> 
> Could be the GPU either being out of VRAM when creating the new connection or it could be "disabled"/idle (since it's a laptop). Try changing back the settings to the previous one since it could be one of your settings as well of course.

![Screenshot_2022-06-15-08-49-59-32](https://user-images.githubusercontent.com/106918443/173719640-96f24df3-4653-4b20-8e0a-ef530535e74d.png)
This victim machine has a gpu and cpu, the cpu runs normally, the gpu is added to the list but has a duplicate error in the list

**Comment by asxtin** [comment]
> > why when i switch to another server(mining pool) it shows 0H/s
> 
> Could be the GPU either being out of VRAM when creating the new connection or it could be "disabled"/idle (since it's a laptop). Try changing back the settings to the previous one since it could be one of your settings as well of course.



> > why when i switch to another server(mining pool) it shows 0H/s
> 
> Could be the GPU either being out of VRAM when creating the new connection or it could be "disabled"/idle (since it's a laptop). Try changing back the settings to the previous one since it could be one of your settings as well of course.

![Screenshot_2022-06-15-09-48-01-77](https://user-images.githubusercontent.com/106918443/173726176-019a410d-0db1-4940-be95-bfa97b2ed3e1.png)
dude..

**Comment by asxtin** [comment]
> > why when i switch to another server(mining pool) it shows 0H/s
> 
> Could be the GPU either being out of VRAM when creating the new connection or it could be "disabled"/idle (since it's a laptop). Try changing back the settings to the previous one since it could be one of your settings as well of course.

Uhhh

**Comment by UnamSanctam** [comment]
>This victim's computer has a gpu and a cpu, the cpu runs normally, the gpu is added to the list but has a duplicate error in the list

That's because he has AMD Radeon HD 7500, look it up on Google and you'll see wht, though it shouldn't be added multiple times. Show screenshots of the other entries as well.

>dude..

You just need to wake it up, 000webhost has 1 hour of sleep for all free sites from what I know.

**Comment by asxtin** [comment]
> > This victim's computer has a gpu and a cpu, the cpu runs normally, the gpu is added to the list but has a duplicate error in the list
> 
> That's because he has AMD Radeon HD 7500, look it up on Google and you'll see wht, though it shouldn't be added multiple times. Show screenshots of the other entries as well.
> 
> > dude..
> 
> You just need to wake it up, 000webhost has 1 hour of sleep for all free sites from what I know.

![Screenshot_2022-06-15-15-53-15-46](https://user-images.githubusercontent.com/106918443/173786805-3e71a949-d15e-4a9e-bc08-1ea0b06ca583.png)
maybe my site got banned due to Terms of Service Violation, is there any way to backup?

**Comment by UnamSanctam** [comment]
From your screenshot it doesn't look like you can access the files (to backup it), hosting any sort of panel (that could be used maliciously) could be a violation of their terms of services, I haven't read their terms so I'm just guessing. 

There is someone I know of that's planning to set up a public panel that anyone can use (for free from what I understand) though I don't know how much of it he has completed, and it using it wouldn't be fully safe of course since he controls the website but can be good for anyone who can't buy or find a good host.

**Comment by asxtin** [comment]
> 

does that mean I have to create a new website?, do I have to start over?, maybe I'll have to wait

**Comment by asxtin** [comment]
> 

i tried the remote configuration, i used it but the victim's computer stopped and moved to another server (minexmr.com)

**Comment by asxtin** [comment]
> Yes most likely you'd have to make a new one since it looks like they have "banned" your site, the miners will still be mining as normal though. Do you have a "Remote Configuration" set? Doesn't look like it from the screenshot but if you do then you can change the web panel URL via that.

though miners will work fine but miners won't be on the list if i create a new site, right?

**Comment by UnamSanctam** [comment]
> i tried the remote configuration, i used it but the victim's computer stopped and moved to another server (minexmr.com)

Yes it will use whatever configuration you put into the "Remote Configuration", and if the configuration is incorrect then it will use the pool that you entered inside the builder.

> though miners will work fine but miners won't be on the list if i create a new site, right?

Yes since you will have a new URL and the miners don't know the new URL.

**Comment by asxtin** [comment]
> 

so if i create new site and i will get banned again?, is there any way to not get banned anymore?🤔

**Comment by UnamSanctam** [comment]
Depends on the host, for 000webhost I'd guess so. To not get banned you'll have to find a webhost that doesn't ban or get a bulletproof domain (which you then point towards some webhost).

**Comment by asxtin** [comment]
> Depends on the host, for 000webhost I'd guess so. To not get banned you'll have to find a webhost that doesn't ban or get a bulletproof domain (which you then point towards some webhost).

if finding paid websites is too easy, but free is not. I found a very good website called awardspace dot com. I don't know how to properly upload files to my site

**Comment by asxtin** [comment]
> Depends on the host, for 000webhost I'd guess so. To not get banned you'll have to find a webhost that doesn't ban or get a bulletproof domain (which you then point towards some webhost).

<img width="960" alt="image" src="https://user-images.githubusercontent.com/106918443/173841793-ea81de8b-4182-4e87-a4f4-16a95f3affa8.png">
awardspace.com i have uploaded files to my site, but not in bulk, i upload files one by one. It took me about 2 hours to complete, my site may have problems because I don't know if this webhost is the same as 000webhost.

**Comment by UnamSanctam** [comment]
They might have supported uploading a .zip file and extracting it, but since you've logged in it's working so far, try connecting building a miner and connecting to it now. As long as the webhost as PHP 7.4 or above and SQLite support then it should work without issue on the technical side.

**Comment by asxtin** [comment]
> They might have supported uploading a .zip file and extracting it, but since you've logged in it's working so far, try connecting building a miner and connecting to it now. As long as the webhost as PHP 7.4 or above and SQLite support then it should work without issue on the technical side.

Awardspace probably doesn't support zip files, let me search on youtube.

**Comment by UnamSanctam** [comment]
You can just connect with an FTP client like Filezilla or WinSCP and upload via that from what it looks like.

**Comment by UnamSanctam** [comment]
No problem, have a great day.
