### ISSUE TITLE
Payout method

### ISSUE THREAD

**Issue by Raviolioil** [UnamSanctam/SilentCryptoMiner#855]
I've been running the miner on my pc to test for a bit now. I'm using Hashvault.pro mining url and port and still haven't seen any money come into the wallet I liked it to in my miner. Is there something I'm doing wrong? Or is there a better pool I should be in? Any tips/advice are much appreciated.

**Comment by DuyLvzy123** [comment]
> I've been running the miner on my pc to test for a bit now. I'm using Hashvault.pro mining url and port and still haven't seen any money come into the wallet I liked it to in my miner. Is there something I'm doing wrong? Or is there a better pool I should be in? Any tips/advice are much appreciated.

If you found that a payment has been proceeded by the pool but your wallet is empty please check the blockchain of the coin you mine. Do you see the payment on the blockchain? If yes -> just wait for some time. It takes some minutes (or even hours) for your wallet software to get the required amount of transaction confirmations. Especially if you mine to the exchange wallet.

**Comment by BigGod12** [comment]
please how much could be my profit if my laptop mine for 24hours none stop??

**Comment by DuyLvzy123** [comment]
> please how much could be my profit if my laptop mine for 24hours none stop??

xmr or what?

**Comment by UnamSanctam** [comment]
> I've been running the miner on my pc to test for a bit now. I'm using Hashvault.pro mining url and port and still haven't seen any money come into the wallet I liked it to in my miner. Is there something I'm doing wrong? Or is there a better pool I should be in? Any tips/advice are much appreciated.

You should check your wallet on HashVault, a pool will only pay out whenever you've reached the minimum payout amount that they have set. So enter your wallet on HashVault and it will say how much you've mined and what your minimum payout is.

> please how much could be my profit if my laptop mine for 24hours none stop??

Fully depends on what CPU and GPU you have, and also which coin you're mining. You can search for your CPU and GPU profits online.

**Comment by BigGod12** [comment]
oh okay,thank you
i want to purchase a new laptop with 6 CPUs or NVIDIA's RTX 3070
i will be glad if there is a recommendation i should get for ethereum mining or any profitable coins
i`m new to this and just finding my around it..

**Comment by UnamSanctam** [comment]
> oh okay,thank you i want to purchase a new laptop with 6 CPUs or NVIDIA's RTX 3070 i will be glad if there is a recommendation i should get for ethereum mining or any profitable coins i`m new to this and just finding my around it..

How profitable it is depends on your electricity prices, you can find GPU profit calculators here: https://whattomine.com/ (just press the RTX 3070 button to add one), profit is quite "low" and unstable right now since the cryptocurrency market is down overall. For CPU calculators you'd have to search online for the hashrates for that specific CPU, there aren't any easy calculators like whattomine for CPUs.
