### ISSUE TITLE
About algorithm

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#859]
Hello bro.  I need some suggestions from u. I have/under control computers(>100) that have the spec of  intel i7 8700k 3.20Ghz and 8GB RAM. The miner with algorithms `randomx` or` ghost rider` works. But i want to know which algorithm is best for my specfications. And sorry for rasing issue for asking this type of question.

Thanks🙏
Big respect

**Comment by UnamSanctam** [comment]
For those computers RandomX should be more profitable.

**Comment by DerXanRam** [comment]
Thanks bro🙏
