### ISSUE TITLE
Need help to change the code

### ISSUE THREAD

**Issue by Pooo0ky** [UnamSanctam/SilentCryptoMiner#86]
Hi, 
I was trying to implement the rootkit https://github.com/bytecode77/r77-rootkit binding this togheter with the miner and make only adjustment on the injection part / configuration.

Where i can find the part of the code where i can add the "$77-" to the process name so i can hide it?
Thank you very much!

**Comment by UnamSanctam** [comment]
Well, the miner already has a r77 toolkit in it that hides `nslook` instead of `$77` though it's still in beta.

**Comment by Brainshot** [comment]
> Well, the miner already has a r77 toolkit in it that hides `nslook` instead of `$77` though it's still in beta. Since the miners are injected into for example explorer.exe you won't be able to change the process name to include $77, which is why the rootkit in the miner changes the injection process to nslookup.exe and uses that.

So i am considering enabling the rootkit, but has there been any downs using it? issues, problems

**Comment by Brainshot** [comment]
> Yes on some computers the watchdog doesn't seem to be able to find the miners (since they are hidden, though it works fine for me).

Alright i also have a question about process killer

lets say for example if i added a avast process name to it and we aleardy know when you try to end Avast process it shows you a Error like denied, not allowed, would it also do the same with process killer? like constantly show errors trying to end avast?

**Comment by UnamSanctam** [comment]
I don't think so, since it's not really the same kind of "kill" as a normal user but I haven't tried it. The kinds of programs I kill are usually Windows Defender notifications and such.

**Comment by Brainshot** [comment]
> I don't think so, since it's not really the same kind of "kill" as a normal user but I haven't tried it. The kinds of programs I kill are usually Windows Defender notifications and such.

Because if someone who uses avast or nod disabled the settings enabling them to end the process, the end process would work forever.

**Comment by Brainshot** [comment]
@UnamSanctam lets say it keeps trying to end the process, would it lag really bad?

**Comment by UnamSanctam** [comment]
No, it shouldn't affect anything.

**Comment by Pooo0ky** [comment]
Thank you very much! I will try to test the rootkit version then. thank you
