### ISSUE TITLE
worker name: (empty)

### ISSUE THREAD

**Issue by asxtin** [UnamSanctam/SilentCryptoMiner#860]
![image](https://user-images.githubusercontent.com/106918443/174069986-61904e40-1543-4750-afa2-d2cd49af2a8e.png)
I'm testing miner virus on VM, but apparently I put worker name at the end of wallet address : {RANDOM} but when I check the list it doesn't show worker name.

**Comment by UnamSanctam** [comment]
It's at the end of the "User" in your screenshot, it should show up on your pool with that worker name if that's how the pool formats things (that's how many pools does it).

**Comment by asxtin** [comment]
> It's at the end of the "User" in your screenshot, it should show up on your pool with that worker name if that's how the pool formats things (that's how many pools does it).

should I tweak from 50% to over 80% max cpu usage? and Idle miner is 100%?

**Comment by UnamSanctam** [comment]
Depends on the computer, 80% would probably be very noticeable if someone is using the computer.
