### ISSUE TITLE
arguments for modules

### ISSUE THREAD

**Issue by sadaxx221** [UnamSanctam/SilentCryptoMiner#861]
arguments(command) for modules xmr/etc/eth
Where are they in the project?

**Comment by UnamSanctam** [comment]
You mean the command line options for them? You can find all the custom commands (starts with `--cinit`) below here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/21401c56710ba3f49bdaef0fd51b39c078bd8c9d/SilentCryptoMiner/Forms/Builder.cs#L142
You can find all the command line options for xmrig here:
https://xmrig.com/docs/miner/command-line-options
And you can find all the command line options for ethminer here:
https://github.com/ethereum-mining/ethminer/blob/8eaf50ab3baad9a1747e04dc295793d46740dcae/ethminer/main.cpp#L763
