### ISSUE TITLE
Shutting down Google and YouTube search engines

### ISSUE THREAD

**Issue by sadaxx221** [UnamSanctam/SilentCryptoMiner#862]
I have seen a clipper that closes the browser if you type in google or youtube "how to remove the clipper". It is possible to do this for the miner so that he would close the browser (by keywords) when the user would try to download the antivirus

**Comment by UnamSanctam** [comment]
You mean reading the window titles and terminating them if the titles contains a certain word? It's definitely possible from what I know though I don't know how efficient it is.
