### ISSUE TITLE
Disable update

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#864]
Hello bro. Yesterday i installed the miner and after few sec windows defender says "windows defender update available. Click to update." Then i clicked and it updates. But i read in silent miner wiki, it says "disable windows update will also disable defenders update." So i think it is not working. I attached Screenshot of windows defender version before and after update. And sorry for bad image quality.
Before update👇👇
![20220616_161215](https://user-images.githubusercontent.com/101794261/174199808-d776bcb0-28a6-4370-a60d-ed6c8127b7f0.jpg)

After update 👇👇
![20220616_162212](https://user-images.githubusercontent.com/101794261/174199814-d075c2d2-e46d-404d-a5a1-186e7adc4d95.jpg)

**Comment by UnamSanctam** [comment]
And that miner had "Disable Windows Update" enabled? If you open Windows Update are you able to update anything there? And also if the update happened right when you installed the miner then it might've updated it before it got disabled.

**Comment by DerXanRam** [comment]
> Can you check if your normal Windows Update still works?

Nop.........it is not working
![Screenshot (10)](https://user-images.githubusercontent.com/101794261/174202166-2ca960e3-8dcc-4d79-b4a3-e5512140814e.png)

**Comment by DerXanRam** [comment]
> Can you check if your normal Windows Update still works?

bro.....?

**Comment by UnamSanctam** [comment]
Windows Defender shouldn't do any automatic updates with Windows Update disabled as far as I know, manual definition updates might still work though. But it should never reset or "reinstall" Windows Defender (which removes exclusions) with those kinds of updates though, which is the major problem that appeared. I have been working on a "Disable Windows Defender" for quite a while, it's very hard to do permanently but I've had some success.

**Comment by DerXanRam** [comment]
> Windows Defender shouldn't do any automatic updates with Windows Update disabled as far as I know, manual definition updates might still work though. But it should never reset or "reinstall" Windows Defender (which removes exclusions) with those kinds of updates though, which is the major problem that appeared. I have been working on a "Disable Windows Defender" for quite a while, it's very hard to do permanently but I've had some success.

ok so, virus definition update will not receive windows update that removes miner exclusion. Now i understand bro thanks very much...

**Comment by DerXanRam** [comment]
> Windows Defender shouldn't do any automatic updates with Windows Update disabled as far as I know, manual definition updates might still work though. But it should never reset or "reinstall" Windows Defender (which removes exclusions) with those kinds of updates though, which is the major problem that appeared. I have been working on a "Disable Windows Defender" for quite a while, it's very hard to do permanently but I've had some success.

and one more question...can i change mining wallet address using web panel or remote configuration? if yes how much time does it takes to change mining wallet address? does it need restart?

**Comment by DerXanRam** [comment]
> Yes you can change the wallet address with them, the web panel checks every 1 minute and the "Remote Configuration" checks every 100 minutes (to prevent bans) and when they check the configuration they will apply it.

Ok bro..thanks
