### ISSUE TITLE
Service suspension 

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#867]
Hello bro. I hosted your web panel on 000webhost and results in service suspension. And i tried another free hosting and agian service suspended. Now i decided to buy hosting but i wanna know if there is any hosting service u know that doesn't suspend ut pannel.

Thanks🙏

**Comment by slubz** [comment]
> Hello bro. I hosted your web panel on 000webhost and results in service suspension. And i tried another free hosting and agian service suspended. Now i decided to buy hosting but i wanna know if there is any hosting service u know that doesn't suspend ut pannel.
> 
> Thanks🙏

bro, use webhosting awardspace.com

**Comment by DerXanRam** [comment]
> 

Thnaks🙏..but can u tell me hosting sites that receive crypto payment and don't block unam web panel?

**Comment by slubz** [comment]
> > 
> 
> Thnaks🙏..but can u tell me hosting sites that receive crypto payment and don't block unam web panel?

Unfortunately, there is no such website

**Comment by UnamSanctam** [comment]
Not sure but bulletproof webhosts would support it, but I can't remember which ones there are since I don't use any (I only use bulletproof domains and host things myself). You can otherwise find a bulletproof VPS and host it on there, or host it yourself behind a VPN (with port forwarding).

**Comment by DerXanRam** [comment]
> Not sure but bulletproof webhosts would support it, but I can't remember which ones there are since I don't use any (I only use bulletproof domains and host things myself). You can otherwise find a bulletproof VPS and host it on there, or host it yourself behind a VPN (with port forwarding).

You gave me the idea bulletproof hosting and i found these list of bulletproof hostings....and am sharing this cause may help someone like me

https://hostings.info/hostings/rating/bulletproof-hosting

**Comment by DerXanRam** [comment]
> > Hello bro. I hosted your web panel on 000webhost and results in service suspension. And i tried another free hosting and agian service suspended. Now i decided to buy hosting but i wanna know if there is any hosting service u know that doesn't suspend ut pannel.
> > Thanks🙏
> 
> bro, use webhosting awardspace.com

Veryyyyy bad web hosting ....don't try it guyes.
