### ISSUE TITLE
Remote config raw (self hosted)

### ISSUE THREAD

**Issue by Programmer1603** [UnamSanctam/SilentCryptoMiner#868]
Am i able to host my own remote config website? (Something like Pastebin, on a vps or a website service like heroku)

If so is there an opensource project you know of which i could use?

Do i need a domain or would a IP work aswell?

I am sorry if this question already has been answered... however i didnt find any issue like this.

Ty

**Comment by UnamSanctam** [comment]
Yes you can set up one yourself, if you only need to host a "paste" for yourself then you only really need to host a simple HTML file with a configuration inside, but if you do want to set up one then you can set up something like https://github.com/PrivateBin/PrivateBin. You can use an IP to connect to just fine.

**Comment by Programmer1603** [comment]
Thank you 👍🏻👍🏻👍🏻

**Comment by Programmer1603** [comment]
Would this html code work? 
It looks fine, however does the backend need to use a special API or smth so it can interact with the miner?
Should i change smth in my code?

Thank you in advance


<html><head><meta name="color-scheme" content="light dark"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
	"algo": "lorem ipsum",
	"pool": "lorem ipsum",
	"port": lorem ipsum,
	"wallet": "lorem ipsum",
	"password": "lorem ipsum",
	"rig-id": "lorem ipsum",
	"keepalive": lorem ipsum,
	"nicehash": lorem ipsum,
	"ssltls": lorem ipsum,
	"max-cpu": lorem ipsum,
	"idle-wait": lorem ipsum,
	"idle-cpu": lorem ipsum,
	"stealth": lorem ipsum,
	"stealth-targets": "lorem ipsum"
}</pre></body></html>

**Comment by UnamSanctam** [comment]
Yes, for the "Remote Configuration" you would only need something like:
```
<html>
<head></head>
<body>
{
	"algo": "lorem ipsum",
	"pool": "lorem ipsum",
	"port": lorem ipsum,
	"wallet": "lorem ipsum",
	"password": "lorem ipsum",
	"rig-id": "lorem ipsum",
	"keepalive": lorem ipsum,
	"nicehash": lorem ipsum,
	"ssltls": lorem ipsum,
	"max-cpu": lorem ipsum,
	"idle-wait": lorem ipsum,
	"idle-cpu": lorem ipsum,
	"stealth-targets": "lorem ipsum"
}
</body>
</html>
```
And nothing else.

**Comment by Programmer1603** [comment]
Ok, thank yopu very much for the quick response!!!

**Comment by Programmer1603** [comment]
> 

does this work fine? Because as soon as i open this html code the text gets displayed, but all of it is squeezed into one line of text....

**Comment by UnamSanctam** [comment]
Yes, the formatting itself doesn't matter, it ignores everything but the actual characters.

**Comment by Programmer1603** [comment]
👍🏻👍🏻
