### ISSUE TITLE
Mining question.

### ISSUE THREAD

**Issue by unameddev** [UnamSanctam/SilentCryptoMiner#869]
### hello unam, sorry for bothering, i would like to know if it is possible and how to implement a function in the miner for a project, I need the miner to mine for two addresses at the same time, two of eth and two of xmr, and it would be divided a percentage of 70 or 80% to one wallet and the rest to another. I look forward to hearing from you and thank you very much.

**Comment by UnamSanctam** [comment]
It would have to be handled on the pool side, you can use MoneroOcean to split profits into two wallets and you can mine both XMR and ETH on MoneroOcean. Check their "Help" page and you can find it in the FAQ.

**Comment by unameddev** [comment]
Nice, thanks very much for the help!
