### ISSUE TITLE
Eth error

### ISSUE THREAD

**Issue by j0er00t** [UnamSanctam/SilentCryptoMiner#87]
i have this error

https://i.imgur.com/2JUPBJU.png
https://i.imgur.com/QcIHBy6.png
https://i.imgur.com/4CU0nnm.png

**Comment by UnamSanctam** [comment]
There's something wrong with the drivers, usually that they're really old.

**Comment by j0er00t** [comment]
> There's something wrong with the drivers, usually that they're really old.

which driver bro ?? windows driver??

**Comment by UnamSanctam** [comment]
The GPU drivers.

**Comment by j0er00t** [comment]
okay sir thanks i fix it
