### ISSUE TITLE
how to add Microsoft.Win32.dll in program.cs?

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentCryptoMiner#870]
how to add Microsoft.Win32.dll in program.cs?

**Comment by UnamSanctam** [comment]
Add another line like this here with that DLL instead:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/21401c56710ba3f49bdaef0fd51b39c078bd8c9d/SilentCryptoMiner/Classes/Codedom.cs#L46
