### ISSUE TITLE
web panel

### ISSUE THREAD

**Issue by saaxwwe2** [UnamSanctam/SilentCryptoMiner#872]
how to update the web panel? Should I just delete all files and upload new ones?

**Comment by UnamSanctam** [comment]
Yes, if you delete all files and upload the new ones then the miners will be re-added when they connect again.

**Comment by saaxwwe2** [comment]
503 Service Temporarily Unavailable
I sometimes had this error on the old version, now it constantly appears and does not allow me to open the site. I deleted all files and uploaded a new version, but it also appears

**Comment by UnamSanctam** [comment]
Either your webserver is down, the PHP on your webserver are crashing or it could be something else like file permissions on your webserver are wrong.
