### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Raviolioil** [UnamSanctam/SilentCryptoMiner#873]
Does the miner auto start when the .exe file is downloaded?
What files need to go on the other persons device or do you just need the one .exe file?

**Comment by UnamSanctam** [comment]
No, files won't autostart on Windows (and all browsers unless told to do so) since that would be a huge security hole. The only file that's needed is the final .exe file that's named exactly as you chose when you built it.

**Comment by Raviolioil** [comment]
How do people manage to get so many miners out and running then?

**Comment by Nigward8174** [comment]
We found the ways to make em download and run it, not just download it obviously

**Comment by Raviolioil** [comment]
how do you do that per say?

**Comment by asxtin** [comment]
> how do you do that per say?

Use rat🤔

**Comment by Raviolioil** [comment]
> > how do you do that per say?
> 
> 
> 
> Use rat🤔

is there a way to use rats without them being traced back to your ip? If so what are the best methods
