### ISSUE TITLE
Remote Config/Unam Panel TOR

### ISSUE THREAD

**Issue by Programmer1603** [UnamSanctam/SilentCryptoMiner#876]
Is it somehow possible to host the remote config or the unam panel on a TOR hidden service?

If so how can i accomplish this?

Best regards

**Comment by UnamSanctam** [comment]
> github.io is a web hosting?, does it support php and MySQL?

No it's not a webhosting, and supports neither PHP or MySQL.

**Comment by UnamSanctam** [comment]
Not really, because you have to install and set up the proxy (Tor Browser is the most common),

**Comment by Programmer1603** [comment]
> Not really, because you have to install and set up the proxy (Tor Browser is the most common),

Ok sadly

No problem thank you for your fast response!
