### ISSUE TITLE
Miner not working

### ISSUE THREAD

**Issue by aoki233** [UnamSanctam/SilentCryptoMiner#879]
hello i tested the miner on my vm ware machine when i run the miner the checker said no compatibale gpu and it's just not minig for your information an older version of this miner worked perfectly but this one idk what's the problem i tried both cpu mining and gpu mining could u tell me what's the problem ?

**Comment by UnamSanctam** [comment]
I'll need some more information, build miner with the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite, then start it and wait a minute for it to install, then start the checker and post what it says.

**Comment by aoki233** [comment]
sorry but how do i use that file ?

**Comment by UnamSanctam** [comment]
Download it, extract the .zip file and you will get a .xml file, you can open the builder and press "Load" in the "Main" tab and then choose that .xml file to load the settings.

**Comment by aoki233** [comment]
okay the xmr is working but the gpu is not is it because i am testing it on laptopo that have an integrated gpu with cpu ?

**Comment by UnamSanctam** [comment]
Yes it will only mine on dedicated GPUs (as best it can, mining on integrated GPUs would only cause lag and nothing more).

**Comment by aoki233** [comment]
thank u for the guide would please leave your etc wallet adress?

**Comment by UnamSanctam** [comment]
You can find my wallet addresses on the main page here: https://github.com/UnamSanctam/SilentCryptoMiner#donate, and if you're basing your settings of the example settings don't forget to change the example addresses to your own wallet addresses since people sometimes forget.
