### ISSUE TITLE
unable to connect with webpanel

### ISSUE THREAD

**Issue by sadandnab** [UnamSanctam/SilentCryptoMiner#881]
Hello Unam 

it's nice to write you again 
i am trying SilentCryptoMiner for mine XMR or ETC but i don't see any CPU/GPU control optionin this Builder like we have in XMRBuilder and there is no option to connect webpanel please let me know about it i can share screenshot if you want

**Comment by UnamSanctam** [comment]
If you want to mine XMR then you'll have to add an XMR (RandomX) miner inside the builder first (on the "Main" tab).

**Comment by sadandnab** [comment]
> If you want to mine XMR then you'll have to add an XMR (RandomX) miner inside the builder first (on the "Main" tab).

yes i know that i am talking about CPU or GPU maximum use option in (SilentCryptoMiner) it's not there and there is no remote configuration option there is (Block Websites) only but not any remote configuration

**Comment by sadandnab** [comment]
![Capture](https://user-images.githubusercontent.com/87695790/175103743-cb763cb9-9764-4dde-9504-d29bf205048e.PNG)

**Comment by sadandnab** [comment]
![2](https://user-images.githubusercontent.com/87695790/175103853-3525aa87-372e-493c-81dd-5f055f8fbd1e.PNG)

**Comment by UnamSanctam** [comment]
You need to create a miner in the builder first, in the "Main" tab you can create an XMR miner if that's what you want. Press the "Add" button, select "Monero" in the list and press "Create Miner".

**Comment by sadandnab** [comment]
can i use binance ETC address ??

**Comment by UnamSanctam** [comment]
Yes you should be able to use any ETC address as long as it's valid and the pool accepts it (most pools don't accept exchange wallets but if it's not an exchange wallet then there should be no problem).
