### ISSUE TITLE
Fallback API

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#882]
I fill API 3 websites(2 backup domains)..... before 1 week ago the first one closed(service suspended ).... then i bought my backup domain name(second one) and today(after 1 week) i setup the web pannel....now it passed 10 min and the miners are not connected. Does something i do wrong or does it take time?

**Comment by UnamSanctam** [comment]
No it will connect to the fallback URLs if it does not get any valid JSON response from the previous URL, if you entered https in the builder for the fallback URL make sure that you have a certificate.

**Comment by DerXanRam** [comment]
Ya i fill https url but mine is http only....so i must purchase certificate too

**Comment by DerXanRam** [comment]
I bought ssl certificate and still not working.

**Comment by UnamSanctam** [comment]
Run the checker and post a screenshot of what it returns.

**Comment by DerXanRam** [comment]
> Run the checker and post a screenshot of what it returns.

Ok i will

**Comment by DerXanRam** [comment]
Here it is
![Uploading 20220626_191728.jpg…]()

**Comment by UnamSanctam** [comment]
And you mean that it doesn't connect to https://www.kapilapiii.com/?

**Comment by DerXanRam** [comment]
Yes....it doesn't connect

**Comment by UnamSanctam** [comment]
Make sure that you have PHP 7.4 or newer.

**Comment by DerXanRam** [comment]
> And you mean that it doesn't connect to https://www.kapilapiii.com/?

Yes...it doesn't connect

**Comment by DerXanRam** [comment]
> Make sure that you have PHP 7.4 or newer.

Yes i have
![Screenshot_20220626-194117_Chrome](https://user-images.githubusercontent.com/101794261/175824764-dcc5b999-3a36-4f74-bf4e-da441eb0b644.jpg)

**Comment by UnamSanctam** [comment]
Make a build with only that website in "API Endpoint URL" and nothing else and see what happens.

**Comment by DerXanRam** [comment]
> Make a build with only that website in "API Endpoint URL" and nothing else and see what happens.

Still doesn't connect
![20220626_195551](https://user-images.githubusercontent.com/101794261/175825306-d4fae10d-f812-422b-8bc8-b08784bcbc80.jpg)

**Comment by UnamSanctam** [comment]
Make sure that the database file permissions are correct, you can test if they are by creating a new test configuration in "Configurations" inside the web panel.

**Comment by DerXanRam** [comment]
> Make sure that the database file permissions are correct, you can test if they are by creating a new test configuration in "Configurations" inside the web panel.

I created test config successfully ....

**Comment by DerXanRam** [comment]
> Make sure that the database file permissions are correct, you can test if they are by creating a new test configuration in "Configurations" inside the web panel.

Hay bro i found that the web server is blocking the miner requiest ... wait let me send the log files

**Comment by DerXanRam** [comment]
> Make sure that the database file permissions are correct, you can test if they are by creating a new test configuration in "Configurations" inside the web panel.

here are logs...
[error logs.txt](https://github.com/UnamSanctam/SilentCryptoMiner/files/8987095/error.logs.txt)

**Comment by DerXanRam** [comment]
> Make sure that the database file permissions are correct, you can test if they are by creating a new test configuration in "Configurations" inside the web panel.

I turned off the website security and now its all fine

**Comment by DerXanRam** [comment]
Thanks bro for helping...have a nice time
