### ISSUE TITLE
This guy is on fire!

### ISSUE THREAD

**Issue by SuperSnake802** [UnamSanctam/SilentCryptoMiner#889]
Hello! Brother, you’re genius! Your products are super awesome and helpful. Will you make Unam RAT?

**Comment by UnamSanctam** [comment]
Thank you, I was working on a RAT before but it was paused due to not having enough time.

**Comment by SuperSnake802** [comment]
> Thank you, I was working on a RAT before but it was paused due to not having enough time.

Hello again! You can modify open source RATs like Async, Quasar and NJ to save your time. I honestly took a look at NJ source, it seems easy to understand and modify it. 
URL : https://github.com/AliBawazeEer/RAT-NjRat-0.7d-modded-source-code

I appreciate your work!

**Comment by UnamSanctam** [comment]
Yes that version was based on Async, I've been deliberating which one to use.

**Comment by Nigward8174** [comment]
Would surely like to use your rat, all the projects you were working on till now were better than perfect

**Comment by SuperSnake802** [comment]
Closed.

**Comment by SuperSnake802** [comment]
Closed.
