### ISSUE TITLE
Does the uninstaller only uninstall the current build of the miner or also older ones?

### ISSUE THREAD

**Issue by xEnething** [UnamSanctam/SilentCryptoMiner#89]
I created a miner tested it, and build it again with watchdog, rootkit etc., but I never opened the uninstaller from the "test" miner and I called the file name of the new miner the same thing as the old one and the uninstaller etc got deleted. If I use the uninstaller from the new miner, will the old miner be uninstalled?

**Comment by UnamSanctam** [comment]
It can only uninstall the current build since there is no way to automatically find old miners or watchdogs. But things like the rootkit will still be uninstalled.
