### ISSUE TITLE
LHR GPU

### ISSUE THREAD

**Issue by aoki233** [UnamSanctam/SilentCryptoMiner#890]
is the hashrate of GPUs in minerstat.com with LHR locked or unlocked ?

**Comment by UnamSanctam** [comment]
Most likely unlocked.

**Comment by aoki233** [comment]
and what about the miner ?

**Comment by UnamSanctam** [comment]
The miner doesn't unlock LHR since there's no public method of doing so (that I'm aware of). The miners that have LHR unlocks would be losing money in dev fees if it was made public so it's understandable why it's not made public.

**Comment by aoki233** [comment]
so how much would the hashrate would drop ?

**Comment by UnamSanctam** [comment]
From what I know it's usually 40-50%.

**Comment by aoki233** [comment]
one last question is LHR affecting nvida only or amd too ?

**Comment by UnamSanctam** [comment]
No only Nvidia makes LHR cards.

**Comment by aoki233** [comment]
thanks alot
