### ISSUE TITLE
BotKiller option

### ISSUE THREAD

**Issue by sa6ta6ni6c** [UnamSanctam/SilentCryptoMiner#892]
Hello! I think it would be great to add a function to the miner to remove other malware when installed. I have seen this feature in many paid miners.

**Comment by UnamSanctam** [comment]
Sure but it would need some method to find the malware, I'm not sure how the paid miners do it but I guess you'd have to find out how each malware works/installs and find some sort of way to identify each one (since just deleting registry entries or Tasks won't do much if they have things against that). If you know of any methods then you're free to post them.

**Comment by sa6ta6ni6c** [comment]
Maybe you can use open source miner killers (from GitHub) or I can send you miner I bought recently with builder that has botkiller option

**Comment by UnamSanctam** [comment]
There aren't really any online that I can found that actually works well, for example none that I could find would be able to kill my miner from what I can see. But have you tried out the botkiller in the miner you bought? If you install my miner and maybe some RAT does your bought miner kill and remove them?

**Comment by sa6ta6ni6c** [comment]
It only kills malware that present on system when private miner is installed. However I would like to test it but have no clue how to remove it after

**Comment by UnamSanctam** [comment]
You could maybe install it on a Virtual Machine and test unless the private miner has an anti-VM protection.

**Comment by sa6ta6ni6c** [comment]
Ok ill try it now

**Comment by sa6ta6ni6c** [comment]
Can I test it in Windows 7?

**Comment by asxtin** [comment]
> Can I test it in Windows 7?
U cant

**Comment by sa6ta6ni6c** [comment]
> Can I test it in Windows 7?
> U cant

miner doesn't work in windows 7?

**Comment by UnamSanctam** [comment]
It works on Windows 7 so you can test with that.

**Comment by sa6ta6ni6c** [comment]
Ok, as soon as I download windows 7 Ill record a video and send it here

**Comment by asxtin** [comment]
> It works on Windows 7 so you can test with that.

I thought windows 10 and above worked:/

**Comment by UnamSanctam** [comment]
> I thought windows 10 and above worked:/

The miner is tested and works on Windows 7, Windows 8, Windows 10 and Windows 11, and also the corresponding Windows Server versions.

**Comment by sa6ta6ni6c** [comment]
Sadly, I can't get my virtual machine on MacBook working and my windows pc is not in service.

**Comment by SuperSnake802** [comment]
> Sure but it would need some method to find the malware, I'm not sure how the paid miners do it but I guess you'd have to find out how each malware works/installs and find some sort of way to identify each one (since just deleting registry entries or Tasks won't do much if they have things against that). If you know of any methods then you're free to post them.

I know one method, kill all .exe or .vbs in %appdata%, %temp%, %userprofile% and %windir%. That should work fine.

**Comment by UnamSanctam** [comment]
> I know one method, kill all .exe or .vbs in %appdata%, %temp%, %userprofile%, %windir% and startup folder.

But many are injected (so then original file is not running), and even then they may have watchdogs or similar things. So this would only really work for the basic malware and not any advanced ones. I know some that also have repeating tasks, so that for example a task runs in the Task Scheduler every hour to make sure that it's running. That's what makes it difficult, it's possible to search through all processes to try and find the injected ones and kill those but nowadays many are more complex than that.

(and you can't kill all in %WINDIR% since the computer would close down the majority of Windows processes)

**Comment by sa6ta6ni6c** [comment]
I think I know one method, maybe you can make it so miner removes other stuff except itself from windows defender exclusions list (when ran with administrator) As I know, windows defender is updated a lot, so it can be a great “BotKiller”

**Comment by UnamSanctam** [comment]
> I think I know one method, maybe you can make it so miner removes other stuff except itself from windows defender exclusions list (when ran with administrator) As I know, windows defender is updated a lot, so it can be a great “BotKiller”

Yeah that's possible though currently it excludes everything and not a specific location so that you can't really figure out what added the exclusions, since for example if it excluded `AppData` then that would probably reveal that whatever added the exclusions is inside `AppData`.

**Comment by SuperSnake802** [comment]
> I think I know one method, maybe you can make it so miner removes other stuff except itself from windows defender exclusions list (when ran with administrator) As I know, windows defender is updated a lot, so it can be a great “BotKiller”

Great idea! But what if malware was FUD?

**Comment by sa6ta6ni6c** [comment]
> > I think I know one method, maybe you can make it so miner removes other stuff except itself from windows defender exclusions list (when ran with administrator) As I know, windows defender is updated a lot, so it can be a great “BotKiller”
> 
> Yeah that's possible though currently it excludes everything and not a specific location so that you can't really figure out what added the exclusions, since for example if it excluded `AppData` then that would probably reveal that whatever added the exclusions is inside `AppData`.

What if it deletes everything there first and then adds itself to exclusions?

**Comment by sa6ta6ni6c** [comment]
> > I think I know one method, maybe you can make it so miner removes other stuff except itself from windows defender exclusions list (when ran with administrator) As I know, windows defender is updated a lot, so it can be a great “BotKiller”
> 
> Great idea! But what if malware was FUD?

They usually fail runtime check and windefender gets smarter

**Comment by blincc1031** [comment]
> 也许你可以使用开源矿工杀手（来自GitHub），或者我可以给你发送我最近购买的矿工，使用具有botkiller选项的构建器

Do you have telegram, can I add your buddy?

**Comment by sa6ta6ni6c** [comment]
> You could maybe install it on a Virtual Machine and test unless the private miner has an anti-VM protection.

Hello again! I finally fixed my laptop, so here is the video link: https://www.youtube.com/watch?v=hFNi3jcSoaY

**Comment by sa6ta6ni6c** [comment]
@UnamSanctam

**Comment by UnamSanctam** [comment]
Oh so it kills the miner but not the watchdog (so the miner will just start up again after a minute or two). Interesting, maybe it kills processes with long command lines, since it didn't kill the watchdog which is also injected.

**Comment by sa6ta6ni6c** [comment]
> Oh so it kills the miner but not the watchdog (so the miner will just start up again after a minute or two). Interesting, maybe it kills processes with long command lines, since it didn't kill the watchdog which is also injected.

I don’t know how it works, I can send private miners builder and stub if that helps

**Comment by blincc1031** [comment]
I need a miner who supports Linux systems, please ask where to buy

**Comment by sa6ta6ni6c** [comment]
> I need a miner who supports Linux systems, please ask where to buy

Hello! I recommend xss.is

**Comment by blincc1031** [comment]
xss.is registration failed, are there any other recommendations?

**Comment by sa6ta6ni6c** [comment]
> xss.is registration failed, are there any other recommendations?

Administrator should approve you, just wait

**Comment by blincc1031** [comment]
My account has been declined

**Comment by sa6ta6ni6c** [comment]
> My account has been declined

Try another browser or don’t use vpn, also try different email. If doesn’t help, use LOLZ forum

**Comment by sa6ta6ni6c** [comment]
> I need a miner who supports Linux systems, please ask where to buy

Hi! If you are interested I currently sell my own private miner, written in Rust. Win only for now, but I can add linux support for your liking. We also can discuss non payment, but as a % from your profit from machines.
