### ISSUE TITLE
question

### ISSUE THREAD

**Issue by aoki233** [UnamSanctam/SilentCryptoMiner#895]
i tested my etc miner on my laptop just to see if it working but since it have an integrated gpu it won't work anyways the cheker said the miner it is runnig but it deosn't shows up in the web pannel could that be due it couldn't mine ? 
and another question how can i see the hashrate on the web panel? cause i tested a cpu miner it did shows up on the webpanel but it giving basic info such ip adress and stuff

**Comment by UnamSanctam** [comment]
Yes the ETC miner won't appear in the web panel if it doesn't start (due to no GPU). It says the hashrate on the web panel, if you have a smaller screen then press the '+' in front of the miner ID to expand the entry.
