### ISSUE TITLE
Problem with ETC

### ISSUE THREAD

**Issue by Durakbalbes** [UnamSanctam/SilentCryptoMiner#896]
Hello, i made build with 2 miners (xmr and etc), xmr works good but etc doesn't. Uses pool ethermine.org, settings - https://imgur.com/a/2iEO1Aj . How can i fix it? Thanks

**Comment by UnamSanctam** [comment]
Run the checker and post what it returns here.

**Comment by Durakbalbes** [comment]
> Run the checker and post what it returns here.

Ok, but if i can't, cause i doesn't check build on my PC there is other methods to check it / fix it?

**Comment by UnamSanctam** [comment]
No well you'd need to test it to be able to test it, the reason I wanted to know what it returns is to know if you even had a GPU that could mine ETC. But I would advice you against using `Farming (1)` as the worker name, usually **only** alphanumeric (plus some others) are allowed as worker names.

**Comment by Durakbalbes** [comment]
> No well you'd need to test it to be able to test it, the reason I wanted to know what it returns is to know if you even had a GPU that could mine ETC. But I would advice you against using `Farming (1)` as the worker name, usually **only** alphanumeric (plus some others) are allowed as worker names (meaning no spaces and usually no parentheses). So most likely the reason is the worker name you entered.

Ok, thank you. I'll fix, for first, worker name and after, if it will not working, i'll test. (tested 5 users with 2060+ gpus, exactly were 3 - 2060 (6gb) and 2 - 3060 (12gb). Monero works well, but problem only with ETC.

**Comment by Durakbalbes** [comment]
Problem was resolved, as you said problem was in worker name. Thank you.

**Comment by ShadowDevONE** [comment]
Today you fixed my problem with etc too, thanks you so much, your projects are really great (my username was XGhostONE, problem with start Up name, currently banned for spread1ng lol)
