### ISSUE TITLE
Remote config UBQ 

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/SilentCryptoMiner#897]
Mining on video cards 2 gigabytes

I can't understand how to correctly configure a remote configuration

{
    "url": "stratum://wallet.{COMPUTERNAME}@eu.crazypool.org",
    "algo": "ubqhash",
    "port": 3335,
    "max-gpu": 50,
    "idle-wait": 5,
    "idle-gpu": 80,
    "stealth": false,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe"
}

most likely my configuration is not true

**Comment by UnamSanctam** [comment]
Yes you need a port as well, for example `"url": "stratum://wallet.{COMPUTERNAME}@eu.crazypool.org:3333",`
