### ISSUE TITLE
eth mining 0h/s

### ISSUE THREAD

**Issue by sp3c1al** [UnamSanctam/SilentCryptoMiner#898]
hi
i face the same problem with many gpe
0h
i try everything you said in this thread to fix it without succeed
any help please
all my gpe are 0h
and there is no worker in the pool
![7b61d5cf-d4bf-4932-a990-c70d482bb2c6](https://user-images.githubusercontent.com/108318564/176094734-6eb7ad30-f237-4bd8-ac7f-e98446a0f0b2.jpg)
sorry  i opened new issue cuz i am not sure if you will reply to my comment in this issue 
https://github.com/UnamSanctam/SilentCryptoMiner/issues/750

**Comment by UnamSanctam** [comment]
Haha sure, I'll quote what I said in the other one:
>Try changing it to another coin that requires less VRAM (like ETC), usually it's due to there not being enough free VRAM to mine (ETH requires 4.9GB of VRAM). Currently my 8GB GPU is using 3.9GB while I don't really have much running.

If you get a hashrate when you change the coin/algorithm then it's due to the VRAM.

**Comment by sp3c1al** [comment]
My card have 16gb ram
Etc is ok
Eth 0h/s
Its almost 20 gpu with 16gb ram or more with 0h/s

**Comment by UnamSanctam** [comment]
16GB? What kind of card do you have? But run the checker on your computer and post it here.

**Comment by sp3c1al** [comment]
I cant run the check test cuz iam try it on other pc
This is the card with info

**Comment by sp3c1al** [comment]
![11](https://user-images.githubusercontent.com/108318564/176097025-7d8ab88f-37c5-4bbc-95c5-3ca31e83d720.jpg)

**Comment by UnamSanctam** [comment]
RTX 2080 Ti is an 11GB card, but try changing it to ETC, if ETC works then the reason you get 0H/s is either that your pool connection settings are wrong or that there's not enough VRAM.
