### ISSUE TITLE
Dialer

### ISSUE THREAD

**Issue by Karmatic9** [UnamSanctam/SilentCryptoMiner#900]
Is there more way to have it not say dialer when mining? I thoguht i saw it running before without dialer but now all my tests say dialer. Am I doing it wrong?

**Comment by Karmatic9** [comment]
Ohhh, is this a good thing to have? I want to be stealthy!

**Comment by UnamSanctam** [comment]
Yes but it's experimental and might not work on all computers (from what people report at least).

**Comment by Karmatic9** [comment]
Does dialer mean that it is not working then? Thankful for your patience lol

**Comment by UnamSanctam** [comment]
If you can see dialer.exe in things like Task Manager then it's not currently getting hidden yes, but from experience that's a "semi-common" problem with the r77-rootkit that it's based of.
