### ISSUE TITLE
Doesn't work on other PCs

### ISSUE THREAD

**Issue by NSDhazard** [UnamSanctam/SilentCryptoMiner#902]
Hello, I wanted to know about my problem. When I run the build on my PC, everything works fine, but when I run the build on PC of my friends, there are no mining and there is no connection to the pool either, but the checker shows that mining is active, I use https://monero.hashvault.pro/en/dashboard as a pool, for build took build took your file ExampleSettings_Full

**Comment by UnamSanctam** [comment]
How do you know if there's no mining or connection to the pool? If you want worker names for HashVault you will need to enter it into the "Password" field if you haven't already. You also shouldn't use HashVault if you're planning to have a lot of workers:
<img src="https://user-images.githubusercontent.com/10323655/176509194-e6907c27-6a01-497c-87cf-221339503d27.png">
