### ISSUE TITLE
No startup

### ISSUE THREAD

**Issue by karkaletsi** [UnamSanctam/SilentCryptoMiner#903]
basically i run the exe and then it doesnt make the exe file at temp google/chrome/updater.exe. it mines though

**Comment by karkaletsi** [comment]
ok ty now it has created the exe. in task manager its undetectable but it starts again right?

**Comment by UnamSanctam** [comment]
You can run the checker to see if it's running, if you were to restart the computer and run the checker it should say that it's running.

**Comment by karkaletsi** [comment]
ok ty
