### ISSUE TITLE
changing API url

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#906]
Hello bro....I have a question....can I change or add another API url to already deployed miners using remote configuration(pastbin)? If yes, can u send the format please? I asked these because the firewall of the institution I installed the miner is blocking my API url and miners cannot reach the endpoint. I say this because when I try to access my API url using the institution's WiFi, it says 

```
Web Page Blocked
The application is blocked by a ******** Security policy rule.
User: 1*.***.1.6*
URL: *******ii.com/
Category: phishing
```

**Comment by UnamSanctam** [comment]
Yes you can change it by adding `"api-endpoint": "API Endpoint URL",` to it (remove the comma if it's on the last line)

**Comment by DerXanRam** [comment]
> Yes you can change it by adding `"api-endpoint": "API Endpoint URL",` to it (remove the last comma if it's on the last line).

does these line remove other API i fill for back up then input the new one? or does it just add another API url?

**Comment by UnamSanctam** [comment]
It replaces the URLs.

**Comment by DerXanRam** [comment]
> It replaces the URLs.

ok thanks very much......one more question....... can i replace remote config url using API url with the same mechanism like above? if yes, please send the format

**Comment by UnamSanctam** [comment]
Sure, you can add `"remote-config": "Remote Configuration URL",` and it will change the "Remote Configuration" URLs instead.

**Comment by DerXanRam** [comment]
> Sure, you can add `"remote-config": "Remote Configuration URL",` and it will change the "Remote Configuration" URLs instead.

means it replace it??

**Comment by UnamSanctam** [comment]
Yes it will replace the URLs.

**Comment by DerXanRam** [comment]
ok.... thanks very much for your help
