### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by xsxon** [UnamSanctam/SilentCryptoMiner#912]
I tested the build on my own PC and everything worked well, XMR and ETC were mined, but when I ran the build on my other two laptops, the pool showed that 0 workers online and nothing was mined, there was no load on the cpu either, although the checker showed " Watchdog Running: Yes", in the virtual machine the same problem. Because of what the build may not work on other PC than mine?

**Comment by UnamSanctam** [comment]
You'll have to post what the checker say.

**Comment by shainodev** [comment]
> I tested the build on my own PC and everything worked well, XMR and ETC were mined, but when I ran the build on my other two laptops, the pool showed that 0 workers online and nothing was mined, there was no load on the cpu either, although the checker showed " Watchdog Running: Yes", in the virtual machine the same problem. Because of what the build may not work on other PC than mine?

I dont know if im right but i think xmrig cant run in a vm

**Comment by UnamSanctam** [comment]
> I dont know if im right but i think xmrig cant run in a vm

XMRig should run fine in a VM but if it's a VM with very little resources allocated then it might not use any resources (since then the computer would most likely freeze).

**Comment by xsxon** [comment]
> You'll have to post what the checker say.
![IMG_0683](https://user-images.githubusercontent.com/108555249/177023038-a7decbbc-0503-459a-89b7-bbe5bca9c146.jpg)

**Comment by UnamSanctam** [comment]
Is that your main PC you first tested it on or your laptops?

**Comment by xsxon** [comment]
> 
Its laptop
![image](https://user-images.githubusercontent.com/108555249/177028828-607fa3cc-9278-4986-b995-619d6588b09f.png)
here is the main

**Comment by xsxon** [comment]
> Is that your main PC you first tested it on or your laptops?
Its laptop
![image](https://user-images.githubusercontent.com/108555249/177028870-35b1de0e-f327-4dbf-928c-eb47462c0eee.png)
here is the main

**Comment by UnamSanctam** [comment]
Then it's mining, though a GTX 1050 can't mine ETC since it's only 2GB so your laptop will only mine XMR. Keep in mind that you're not using worker names so you can't distinguish between different computers in the pool interface.

**Comment by xsxon** [comment]
> Then it's mining, though a GTX 1050 can't mine ETC since it's only 2GB so your laptop will only mine XMR. Keep in mind that you're not using worker names so you can't distinguish between different computers in the pool interface.

The problem is that XMR is not mined when I run it on a laptop, and the pool does not see that there are workers when I run it on a laptop

**Comment by UnamSanctam** [comment]
You mean that the pool is reporting 0 H/s? For how long did you wait since you started mining? Also make sure that Task Manager and such aren't open since you have "Stealth" enabled.

**Comment by xsxon** [comment]
> You mean that the pool is reporting 0 H/s? For how long did you wait since you started mining? Also make sure that Task Manager and such aren't open since you have "Stealth" enabled.

yes, there are 0 H/s in the pool, I waited about 15 minutes and it was also 0, although when I start it on the main PC, the hashes appear after a minute of waiting

**Comment by UnamSanctam** [comment]
And you're sure nothing such as Task Manager, Process Hacker or Performance Monitor are open? What CPU do you have? If you have a bad CPU then you might have to increase the "Max CPU" for it to use at least 1 core (RandomX, the Monero algorithm also wants around 2GB of RAM).

**Comment by xsxon** [comment]
> And you're sure nothing such as Task Manager, Process Hacker or Performance Monitor are open? What CPU do you have? If you have a bad CPU then you might have to increase the "Max CPU" for it to use at least 1 core (RandomX, the Monero algorithm also wants around 2GB of RAM).

I closed similar programs, on one laptop i5xxx, on the second 9gen, on both RAM more than 2, but I'll try to increase max cpu and see what happens

**Comment by xsxon** [comment]
> And you're sure nothing such as Task Manager, Process Hacker or Performance Monitor are open? What CPU do you have? If you have a bad CPU then you might have to increase the "Max CPU" for it to use at least 1 core (RandomX, the Monero algorithm also wants around 2GB of RAM).

When I run it on a laptop, I checked with MSI Afterburner, the miner is working and there is CPU load, but the pool shows 0 workers and there is no mining, and when I start it on the main PC, the pool sees 1 worker and still works well, why does the pool not see workers other than my pc? i use 2miners

**Comment by UnamSanctam** [comment]
How long did you try mining? How long it will take to appear depends on your hashrate, 2miners has a 120 000 share difficulty so for example if you only have something like 100 H/s (low-end CPU) then it will take on average 120 000/100=1200 seconds to find a share.
