### ISSUE TITLE
hmmm

### ISSUE THREAD

**Issue by asxtin** [UnamSanctam/SilentCryptoMiner#914]
how can i hide miner virus in image file?

**Comment by UnamSanctam** [comment]
And have it executable? Then you'd have to change the image to an image icon and then use something like an extension spoofer.

**Comment by asxtin** [comment]
> And have it executable? Then you'd have to change the image to an image icon and then use something like an extension spoofer.

what!?, I thought this was a joke

**Comment by asxtin** [comment]
> And have it executable? Then you'd have to change the image to an image icon and then use something like an extension spoofer.

![image](https://user-images.githubusercontent.com/106918443/177041552-1ec3779d-daf3-4d1b-a34d-d8d019186a5a.png)
uhhh...
