### ISSUE TITLE
Question about conversion!

### ISSUE THREAD

**Issue by unameddev** [UnamSanctam/SilentCryptoMiner#915]
### Hello unam, I would like to ask a simple question, in the pool '2miners' there is a conversion option to nano or btc before cashing ETH, for this, is effected the exchange of the address of the wallet, in this case the ETH wallet for a nano wallet, I could make this exchange on your miner? Or could this exchange cause it not to mine properly?

**Comment by UnamSanctam** [comment]
You can use that, if you enter a nano address then 2miners will automatically exchange your ETH to NANO at the end of each day and send it to you.

**Comment by unameddev** [comment]
Okay, thank you very much for the help!
