### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by Werlrlivx** [UnamSanctam/SilentCryptoMiner#918]
Does the uninstaller make any sort of gui? Will it show a popup or some other thing when executing?

**Comment by shainodev** [comment]
open it and find out

**Comment by Werlrlivx** [comment]
U dumb or something I'm asking this for a reason I don't have my pc atm and can't access my RDP

**Comment by UnamSanctam** [comment]
No there's no GUI or popup, it will run in the background.
