### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by Samwadihol** [UnamSanctam/SilentCryptoMiner#919]
It's not a problem, it's just a question, what should I write as a port for moneroocean?

**Comment by Samwadihol** [comment]
nvm i found 20128 right ?

**Comment by Samwadihol** [comment]
Also, where exactly should I write {COMPUTERNAME} at the end of the wallet address or the Password?

**Comment by Samwadihol** [comment]
for monero

**Comment by UnamSanctam** [comment]
MoneroOcean uses the "Password" field for worker names, so enter it there.

**Comment by Samwadihol** [comment]
Thank you !
