### ISSUE TITLE
Dont works

### ISSUE THREAD

**Issue by MJMODZZ** [UnamSanctam/SilentCryptoMiner#921]
I already wrote a comment like that, but it dont works. I tryed like everything, I also rode the whole WIKI and used yours example settings. I didnt got any money yet and it never mined. Here are my settings, im using the Monero Wallet GUI for wallet. Thanks for every help

https://pastebin.com/g13x65iQ

**Comment by MJMODZZ** [comment]
> First of all you have a newline (enter) in your "Wallet Address/User" that you need to remove, then you also have the wrong port, you're using port 2222 (non-SSL port) while having SSL/TLS enabled, change it to port 12222.

I changed these settings but its also not working. Im mining for 1 Day now didnt got something

**Comment by UnamSanctam** [comment]
Run the checker and post a screenshot here.

**Comment by MJMODZZ** [comment]
![image](https://user-images.githubusercontent.com/95315627/178098803-aac785be-8d60-4126-80d9-352d1c5738fa.png)


> Run the checker and post a screenshot here.

**Comment by UnamSanctam** [comment]
The post your XML settings again, I'm guessing you did not remove your "newline" in the "Wallet Address/User" field.

**Comment by MJMODZZ** [comment]
> The post your XML settings again, I'm guessing you did not remove your "newline" in the "Wallet Address/User" field.

True but there was no new-line, the line was just too long for pastebin so it made a newline. The final XML file has no newline.
https://github.com/MJMODZZ/Silent-Miner-Config/blob/main/Config.xml
Uploaded it on github

**Comment by UnamSanctam** [comment]
I see, enable "DEBUG" then build it and run it again, it hasn't installed for you (as seen in the checker) so we'll have to know why that is. Also update the builder if you haven't already.

**Comment by MJMODZZ** [comment]
> I see, enable "DEBUG" then build it and run it again, it hasn't installed for you (as seen in the checker) so we'll have to know why that is. Also update the builder if you haven't already.

I misstakely run the Miner with "Disable Windows Updates" enabled 

I made a Debug miner now this appears
![image](https://user-images.githubusercontent.com/95315627/178099965-c52a01b6-0baa-4deb-9dbb-5fad762439af.png)

**Comment by UnamSanctam** [comment]
Then it works, you can uninstall that miner, compile one without "DEBUG" and then run it and it will work.

**Comment by MJMODZZ** [comment]
> Then it works, you can uninstall that miner, compile one without "DEBUG" and then run it and it will work.

After i setup the miner like the upper one and infected some PCs with it, I didnt got any oney yet. My wallet is emty like before

**Comment by UnamSanctam** [comment]
Check your pool, the pool will only send you anything when you reach the minimum withdrawal amount.

**Comment by MJMODZZ** [comment]
> Check the pool, the pool will only send you anything when you reach the minimum withdrawal amount.
[This is what it says. Idk what that actually means](https://xmr.2miners.com/account/48Q5r42DnshBCULPq73bNXLwdJ2jng8QdDq6TZba79TGXL6Z4UNe61A2HUxqnNpUqn1JBZpm1Vv4XNxL28RBQUeR2RwVAGu/)

**Comment by UnamSanctam** [comment]
You currently have one computer mining and some offline as you can also tell by the hashrate (most people don't have their computer on all day) and you have earned 0.001066 XMR so far and your estimated daily mining amount based on your average hashrate is 0.000396 XMR.

**Comment by MJMODZZ** [comment]
> You currently have one computer mining and some offline as you can also tell by the hashrate (most people don't have their computer on all day) and you have earned 0.001066 XMR so far and your estimated daily mining amount based on your average hashrate is 0.000396 XMR.

how long do I need to wait until it sends me money and how much money do you make from it?

**Comment by UnamSanctam** [comment]
As it says on the pool the minimum amount for withdrawal is 0.01 XMR and you have reached 10% of it, and at your current hashrate it looks like you'll reach the minimum in about 18 days. It says the dollar amount underneath each XMR amount in the fields.

**Comment by MJMODZZ** [comment]
> As it says on the pool the minimum amount for withdrawal is 0.01 XMR and you have reached 10% of it, and at your current hashrate it looks like you'll reach the minimum in about 18 days. It says the dollar amount underneath each XMR amount in the fields.

ok thanks. Do you recomment to mine XMR or ETH?

**Comment by UnamSanctam** [comment]
XMR is less profitable (by quite a bit since you mine with the CPU) but can run on almost any computer and doesn't impact the user much since it's using the CPU. ETH (or ETC/UBQ) is a lot more profitable but can only be mined by GPUs, and also requires a certain amount of VRAM to be available (depends on the coin you're mining) so not as many computers can mine it, and it also impacts the user more since it uses their GPU. Generally people mine both XMR and ETH/ETC at the same time because they don't really interfere with each other.

**Comment by MJMODZZ** [comment]
> XMR is less profitable (by quite a bit since you mine with the CPU) but can run on almost any computer and doesn't impact the user much since it's using the CPU. ETH (or ETC/UBQ) is a lot more profitable but can only be mined by GPUs, and also requires a certain amount of VRAM to be available (depends on the coin you're mining) so not as many computers can mine it, and it also impacts the user more since it uses their GPU. Generally people mine both XMR and ETH/ETC at the same time because they don't really interfere with each other.

If i do add 2 miners (one XMR, one ETH) and if i open it will it mine both cryptos at the same time or only one and if ETH is not minable will it mine XMR? 
And secound thing is should i better go to mine ETH or ETC? And should i use Atomic or Exodus wallet for it?

**Comment by UnamSanctam** [comment]
It will mine both (not really much reason not to) unless a GPU isn't available in which case it will only mine XMR. Personally I prefer ETC since it's close to ETH but requires much less VRAM. ETH requires 5GB of VRAM now to be mined while ETC requires 3GB, meaning that many more GPUs can mine ETC than ETH while also impacting the user less (since there's more free VRAM available for the user to use).

**Comment by MJMODZZ** [comment]
> It will mine both (not really much reason not to) unless a GPU isn't available in which case it will only mine XMR. Personally I prefer ETC since it's close to ETH but requires much less VRAM. ETH requires 5GB of VRAM now to be mined while ETC requires 3GB, meaning that many more GPUs can mine ETC than ETH while also impacting the user less (since there's more free VRAM available for the user to use).

ok other thing can you add a function which makes play this sound when opening the miner? [This](https://cdn.discordapp.com/attachments/1004457224921432134/1004468760725434478/videoplayback_1.mp3)

**Comment by UnamSanctam** [comment]
You'd have to code that into it yourself, you can probably use the `System.Media.SoundPlayer` class if you convert your file into `.wav`.

**Comment by MJMODZZ** [comment]
Donut.exe get detected by antivirus, is there a source code  so I can see that its 100% safe?

**Comment by UnamSanctam** [comment]
Here's the project https://github.com/TheWover/donut.

**Comment by MJMODZZ** [comment]
> Here's the project https://github.com/TheWover/donut.

But why is yours version detected by antivirus?

**Comment by UnamSanctam** [comment]
The normal one is as well, the detection itself is literally called "Donut" in most antiviruses.
