### ISSUE TITLE
Mining 100%

### ISSUE THREAD

**Issue by IHasCheeks** [UnamSanctam/SilentCryptoMiner#922]
hello, i want it to mine at max gpu 50 or 65 percent but i have changed the json file it still mines at 100%. What can i do about that? I know i can enable idle mining but I want it to mine regularly at 65%.

**Comment by UnamSanctam** [comment]
Change "Max GPU" to 65%, the JSON is just so that you can copy paste configurations for those that use "Remote Configuration" or the web panel configuration.

**Comment by IHasCheeks** [comment]
![image](https://user-images.githubusercontent.com/107488604/177583417-517216ac-23e0-4ef6-ad49-b7ad125003ea.png)

Still the same

**Comment by IHasCheeks** [comment]
Should I turn on Idle mining and put the minutes to 0 and make both values 60% or not?

**Comment by UnamSanctam** [comment]
No, that wouldn't make a difference, if you want it to mine 65% at all times then setting the "Max GPU" combo box to 60% will do that.

**Comment by IHasCheeks** [comment]
For example how many minutes will it take to generate the DAG approximately ? If a user has 4GB VRAM GPU for example GTX 1650.

**Comment by UnamSanctam** [comment]
30 seconds maybe, it can also be at 100% if you have something wrong with your Windows, GPU drivers or GPU settings, I used to have that problem before and had to completely reset Windows to fix it.

**Comment by IHasCheeks** [comment]
Works fine as fuck, idk how you manage to be this good but i will donate after i get my miners :)
