### ISSUE TITLE
Not Mining

### ISSUE THREAD

**Issue by Amedex** [UnamSanctam/SilentCryptoMiner#923]
Hello, i have a problem with the miner, or the panel, i don't know for sure. The thing is that after someone installs the miner, it works for 1-2 minutes maximum, then it just gets offline forever. I have this problem for every single person, and i ever tryied to reinstall the whole thing, the web panel and the miner, remade the config, anything.

**Comment by UnamSanctam** [comment]
Can you post your settings (go to the "Main" tab, press "Save", zip the file and then post it here)?

**Comment by Amedex** [comment]
[plt.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9067260/plt.zip)
here you go

**Comment by Amedex** [comment]
yes, i had it on, on this config that i sent and even the older one.

**Comment by Amedex** [comment]
i am so dumb... How did i forget this..

**Comment by UnamSanctam** [comment]
Haha yeah it can happen, I would recommend the https://github.com/UnamSanctam/SilentCryptoMiner/wiki#full settings for a production build (but with your own pool and wallets and such), though keep in mind that "Disable Windows Update" is irreversible so don't test it on any important computer.
