### ISSUE TITLE
Only miners with only cpu last long time

### ISSUE THREAD

**Issue by Pooo0ky** [UnamSanctam/SilentCryptoMiner#93]
Hi Unam, watching my panel i figured out that only the old miner with only a cpu without GPU they will last a lot longer than the computer with Gpu.
It's seems like the GPU computers fail to startup again after restart.
Can you please check? Because i'm having only xmr workers and the eth/etc ones they last only one day, and it's the same with their xmr.

**Comment by UnamSanctam** [comment]
No that's not a problem with the miners, if that's happening then it's the users who are detecting it (probably by lag or fan sound), you should probably lower your settings (like Max GPU) and adding things like games to "Stealth Targets".

**Comment by Pooo0ky** [comment]
I already use the old miner and with and with the same settings the results was really really good. 
I use stealth target and all.
Possible killer process:
SecHealthUI.exe,MsMpEng.exe,NisSrv.exe,mbam.exe,mbamtray.exe,avp.exe,avpui.exe,AVGSvc.exe,afwServ.exe,avgnt.exe,ProductAgentUI.exe,MMSSHOST.exe,McShield.exe,mcafee.exe,afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe
Maybe this?

**Comment by UnamSanctam** [comment]
Well the old miner and this one are the same in that way so there is no real difference (this is just a unification of the two miners with extra features). Try it without the "Process Killer" I guess though that shouldn't really affect anything.

**Comment by MR81726** [comment]
ye im pretty sure the cpu miner is less detected by the pc and the user
