### ISSUE TITLE
is working like this ?

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#933]
![Screenshot (25)](https://user-images.githubusercontent.com/20240556/178466367-dffe77e9-985e-4b0c-87b1-e2b0437a35c1.png)

miner working like this ?

**Comment by UnamSanctam** [comment]
Yes that looks like it works.

**Comment by tarekxxx** [comment]
yea i do

**Comment by UnamSanctam** [comment]
On MoneroOcean it says that you're mining.

**Comment by tarekxxx** [comment]
![image](https://user-images.githubusercontent.com/20240556/178468459-5f38cc07-25e3-448d-9d29-f0f3754f8b90.png)
and like this not mining ?
