### ISSUE TITLE
Would it be possible to mine pulsarcoin?

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#935]
Or would you have to add some algorithm to it?

**Comment by Brainshot** [comment]
its curvehash

**Comment by UnamSanctam** [comment]
Looks like it's a completely different algorithm so it would have to be added, I can't really find any newer written isolated implementations of it though.

**Comment by Brainshot** [comment]
> Looks like it's a completely different algorithm so it would have to be added, I can't really find any newer written isolated implementations of it though.

Btw i see many people stopped mining, isnt this a good thing for us that use mining botnets?

**Comment by UnamSanctam** [comment]
Yes less competition means that you get more for your hashrate, but prices have also gone down (which is also why less people mine) so in terms of dollars it might not be too different. But if you're intending to save what you mine to sell later then it's  very good.

**Comment by Brainshot** [comment]
> Yes less competition means that you get more for your hashrate, but prices have also gone down (which is also why less people mine) so in terms of dollars it might not be too different. But if you're intending to save what you mine to sell later (if/when prices go up again) then it's very good.

What do you think will ETC go up again?

**Comment by UnamSanctam** [comment]
Probably, all cryptocurrencies are down right now so if the market ever recovers then so will (most likely) ETC as well.
