### ISSUE TITLE
Nicehash

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/SilentCryptoMiner#940]
Hello bro.... as u know my number of miners are over 90 and they are increasing. When i search about xmr mining, collaborating many working miners is good using xmrig proxy. But when i dive into setting up it, it says `⚠️ ⚠️ ⚠️ Nicehash support must be enabled on miner side, it mandatory. ⚠️ ⚠️ ⚠️`

the problem is .... when i build my miner i use ur recommended settings and i disabled Nicehash. So is there a way i enable Nicehash using API or remote config?

And my second question is when i make config for xmrig proxy using their recommended way(Which is using this site https://config.xmrig.com/xmrig), i got confused when i choose algo.... i mean when i build the miner i choose to use `randomx` algo.....but xmrig proxy provides different one .....look the screenshot

![Screenshot_20220715-201542_Chrome](https://user-images.githubusercontent.com/101794261/179275945-72fbf765-3ae9-473f-acd7-5973cbeee4a2.jpg)

So which algo i must use.... in my case, i use by switching `randomx` and `ghost rider` algos based on some situation ..... so can u tell me please which one is suitable for both🙏? Thanks bro....

**Comment by UnamSanctam** [comment]
Yes you can enable NiceHash mining (job splitting) by adding `"nicehash": true` to the configuration, it will then enable NiceHash mining for the pool (xmrig-proxy in this case) connection. The configuration wizard on xmrig.com is really outdated so I wouldn't recommend using it, it's better to edit the config.json file and adding/changing the settings yourself.

**Comment by DerXanRam** [comment]
> Yes you can enable NiceHash mining (job splitting) by adding `"nicehash": true` to the configuration, it will then enable NiceHash mining for the pool (xmrig-proxy in this case) connection. The configuration wizard on xmrig.com is really outdated so I wouldn't recommend using it, it's better to edit the config.json file and adding/changing the settings yourself.

Ok ..... so these means i can add randomx and ghost rider algo by editing config.json? I mean do xmrig proxy accept them? Tnx

**Comment by UnamSanctam** [comment]
>Ok ..... so these means i can add randomx and ghost rider algo by editing config.json? I mean do xmrig proxy accept them?

Sure though xmrig-proxy only uses one pool connection, so if you set it to RandomX then all will use RandomX and if you set it to GhostRider then all will use GhostRider.

>And when i enable nicehash does the miner establish connection with other source i.e stratum+ssl://randomxmonero.auto.nicehash.com:443 ?

No it only connects to your xmrig-proxy, NiceHash is just what the "protocol" is called, what it does is that it supports splitting a single job from the pool into a maximum of 256 subjobs, this means that you can theoretically have 256 miners on a single pool connection.

**Comment by DerXanRam** [comment]
> > Ok ..... so these means i can add randomx and ghost rider algo by editing config.json? I mean do xmrig proxy accept them?
> 
> Sure though xmrig-proxy only uses one pool connection, so if you set it to RandomX then all will use RandomX and if you set it to GhostRider then all will use GhostRider.
> 
> > And when i enable nicehash does the miner establish connection with other source i.e stratum+ssl://randomxmonero.auto.nicehash.com:443 ?
> 
> No it only connects to your xmrig-proxy, NiceHash is just what the "protocol" is called, what it does is that it supports splitting a single job from the pool into a maximum of 256 subjobs, this means that you can theoretically have 256 miners on a single pool connection.

Ok tnx bro.... 🙏

**Comment by DerXanRam** [comment]
Thanks man after many tries i finally setuped the proxy perfectly. And now am gaining 2 times larger hash rate compared to the previous one.
