### ISSUE TITLE
What to mine with GPU after ETH merge

### ISSUE THREAD

**Issue by corsair550** [UnamSanctam/SilentCryptoMiner#942]
as u know eth merge is at the door so are u guys going to mine etc after eth merge do we have another profitable option what is the downsides of etc mining tho ?

**Comment by UnamSanctam** [comment]
You can check GPU mining profits here: https://whattomine.com/coins, there isn't really any downsides of ETC mining, technically ETC mining is usually more profitable overall compared to ETH depending on what GPUs you have.

**Comment by corsair550** [comment]
is etc's dag size passed 2gb gpu's vram size ?

**Comment by UnamSanctam** [comment]
Yes nearly all viable coins have that, https://minerstat.com/dag-size-calculator, only real viable coin below 2GB is probably UBQ.

**Comment by corsair550** [comment]
oh thx and do u also recommend nanopool for etc ?

**Comment by UnamSanctam** [comment]
Not really, their worker system is a bit bugged.

**Comment by corsair550** [comment]
what do u recommend than have u ever tried other ones ethermine 2miners etc...

**Comment by UnamSanctam** [comment]
Sure both Ethermine and 2miners work great, usually I recommend 2miners since Ethermine has banned a lot of countries now.

**Comment by corsair550** [comment]
thx m8 thank u for ur hard work

**Comment by corsair550** [comment]
since i couldnt connect to 2miners with ssl port i will go for nanoopol i also cant change Minimum Payout Value on 2miner because  "To change the setting, please supply the external IP address of your worker with the highest average hashrate"

**Comment by corsair550** [comment]
> Sure both Ethermine and 2miners work great, usually I recommend 2miners since Ethermine has banned a lot of countries now.

since i couldnt connect to 2miners with ssl port i will go for nanoopol i also cant change Minimum Payout Value on 2miner because "To change the setting, please supply the external IP address of your worker with the highest average hashrate"
