### ISSUE TITLE
Nicehash issue

### ISSUE THREAD

**Issue by tkpeluri** [UnamSanctam/SilentCryptoMiner#943]
Idk if this is issue or not, but all the miners connect to same rig. And when I open 2 miners on different pcs only one of them shows up at time in "active workers" place. 
I think both of them are mining but can I get it so all of the miners connect to different rig or show up as different worker?

**Comment by tkpeluri** [comment]
yes ty, got other question tho about ethermine.org. I tried using ethermine.org in this but it doesn't even show up any workers in website..

**Comment by UnamSanctam** [comment]
Run the checker and post what it returns here so that I can know which settings you used.
