### ISSUE TITLE
Ravencoing 0 hashes

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/SilentCryptoMiner#945]
I dont understand my settings are right and it says Active, the GPU is also 1650 super

**Comment by UnamSanctam** [comment]
Not sure, Ravencoin doesn't work on my computer with any miner (I've tested all miners that support KawPow) so I can't really test it, but since Ravnecoin needs 3.46GB of VRAM so it could be due to not enough VRAM, since Windows and other programs also take VRAM.

**Comment by Brainshot** [comment]
> Not sure, Ravencoin doesn't work on my computer with any miner (I've tested all miners that support KawPow) so I can't really test it, but since Ravnecoin needs 3.46GB of VRAM so it could be due to not enough VRAM, since Windows and other programs also take VRAM.

Bro i 1650 has way above that

**Comment by UnamSanctam** [comment]
The GTX 1650 Super only has a 4GB version as a far as I remember.
