### ISSUE TITLE
Rootkit

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentCryptoMiner#946]
how can i delete a miner with rootkit i lost uninstaller

**Comment by UnamSanctam** [comment]
First download the rootkit uninstaller from here: https://github.com/UnamSanctam/SilentCryptoMiner/raw/master/SilentCryptoMiner/Resources/Rootkit/rootkit-u.zip and run it, then follow https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner to remove the miner itself.
