### ISSUE TITLE
0 hashes on etc

### ISSUE THREAD

**Issue by aoki233** [UnamSanctam/SilentCryptoMiner#949]
any idea why miners are active and reporting 0 hashes with rtx 2060 and gtx 1065 super on ETC ?

**Comment by UnamSanctam** [comment]
You can post the settings but usually that would be due to not enough free VRAM or high GPU usage by another program. For example if a game is running.

**Comment by aoki233** [comment]
i mean it shows me when it's posed when a program is used but it says it is active and the hash rate is 0

**Comment by aoki233** [comment]
some rtx 2060 work and some don't

**Comment by UnamSanctam** [comment]
Well you don't have all games in your "Stealth Targets" I assume so it wouldn't pause if they have something else opened, if they have had a hashrate before but doesn't now then it's almost certainly the VRAM. You can change it to mine UBQ temporarily which only requires 1.6GB of VRAM, if that works then the GPU doesn't have enough free VRAM at the moment to mine ETC.

**Comment by aoki233** [comment]
i think you right since now it is minig again

**Comment by aoki233** [comment]
what deose it means when it's in green and it sayin active (inactive) ?

**Comment by UnamSanctam** [comment]
Do you mean `Active (Idle)`? Then it's using the "Idle GPU" amount of GPU load.
