### ISSUE TITLE
etc 0 hashrate

### ISSUE THREAD

**Issue by qxzusero** [UnamSanctam/SilentCryptoMiner#952]
i'm used dev full settings but if i can mine monero i can't mine etc, i correctly put my etc adress

**Comment by qxzusero** [comment]
man just viewing anime no game is running vram is enough

**Comment by qxzusero** [comment]
i tried etherium etherium classic ravencoin but gpu mining is not working idk why

**Comment by UnamSanctam** [comment]
How are you checking? Can you run the checker and post what it returns here?

**Comment by qxzusero** [comment]
idk what i did but now it working
