### ISSUE TITLE
.

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#953]

**Comment by UnamSanctam** [comment]
No there's no `x` manually needed, most miners do that automatically if the password is left empty. The "Worker Name" field places it as `.WorkerName` after the wallet address automatically. Either enter `Wallet.WorkerName` into the "Wallet Address" or enter `Wallet` into "Wallet Address" and `WorkerName` into "Worker Name".

**Comment by shainodev** [comment]
> No there's no `x` manually needed, most miners do that automatically if the password is left empty. The "Worker Name" field places it as `.WorkerName` after the wallet address automatically. Either enter `Wallet.WorkerName` into the "Wallet Address" or enter `Wallet` into "Wallet Address" and `WorkerName` into "Worker Name".

i see. will bitbucket ban or ever remove my files?

**Comment by UnamSanctam** [comment]
Probably not, I hosted the miner .exe's there when the "Online Download" feature existed and even after around probably 100 000 downloads they were still up.

**Comment by shainodev** [comment]
how should i do it?
![image](https://user-images.githubusercontent.com/77803435/180822130-17f57bf2-f13b-40aa-b097-02e5be370794.png)
upload the 2 text files there?

**Comment by UnamSanctam** [comment]
No I created a repository and uploaded it there, when I did it I had to upload it all via Git, you can use this guide if you don't know how to use Git https://zapier.com/blog/how-to-push-to-bitbucket/.

**Comment by shainodev** [comment]
> No I created a repository and uploaded it there, when I did it I had to upload it all via Git, you can use this guide if you don't know how to use Git https://zapier.com/blog/how-to-push-to-bitbucket/.

yeah but the problem with that is when u edit it the raw link changes

**Comment by UnamSanctam** [comment]
You can replace the raw URLs commit ID with `master` for it to download the latest version.

**Comment by shainodev** [comment]
> You can replace the raw URLs commit ID with `master` for it to download the latest version.

it says 404 not found

**Comment by UnamSanctam** [comment]
> it says 404 not found
> `https://bitbucket.org/USERNAME/main/raw/1928339120903281809231912398012/.gitignore`

Just browse to your file normally in your repository and then replace `src` with `raw`.

**Comment by shainodev** [comment]
> > it says 404 not found
> > `https://bitbucket.org/USERNAME/main/raw/1928339120903281809231912398012/.gitignore`
> 
> Just browse to your file normally in your repository and then replace `src` with `raw`.

oh thank you, also im making the shellexecutea() do a assemby.load instead of downloadfile and ive created the powershell and added sleep randomized strings and then made the link it downloads from reversed and base64'd and all the [System.Convert]::FromBase64String("") to $oads = 'FromBase64String (imagine this is reversed)' $oads.reverse() [System.Convert]::$oads("") and then do that with assemby.load and downloadstring etc and then i made the payload base64d base64d reversed and now im thinking is this too much will it get really detected cause its obviously like suspicious?

**Comment by UnamSanctam** [comment]
Sounds good, powershell detection is quite difficult for antiviruses, especially if you use something like https://github.com/danielbohannon/Invoke-Obfuscation on the command.

**Comment by shainodev** [comment]
> Sounds good, powershell detection is quite difficult for antiviruses, especially if you use something like https://github.com/danielbohannon/Invoke-Obfuscation on the command.

hmm, my text file is 30 mb so i cant really upload it to bitbucket by just pasting it i think i have to still use the downloads page and switch downloadstring to downloaddata

**Comment by UnamSanctam** [comment]
I have the libs (xmrig CUDA library) .zip uploaded to a BitBucket repository and it's 26MB so that should be fine, from what I remember the "Downloads" page isn't reachable by the public and only privately.

**Comment by shainodev** [comment]
nono like i cant even upload a .txt file i have to paste it so pasting 38 million characters will not work and it will say bad request 404

**Comment by UnamSanctam** [comment]
Just upload a file without an extension with Git.

**Comment by shainodev** [comment]
how do i do that

**Comment by UnamSanctam** [comment]
Just follow this guide https://zapier.com/blog/how-to-push-to-bitbucket/ or any other guide about it. The file extension you can change to anything you want (or remove it), a file extension is only there to advice the operating system what program the file should be opened with so you can change it to anything without issue (so that BitBucket does not know what sort of file it is incase they have have some sort of scan).

**Comment by shainodev** [comment]
> Just follow this guide https://zapier.com/blog/how-to-push-to-bitbucket/ or any other guide about it. The file extension you can change to anything you want (or remove it), a file extension is only there to advice the operating system what program the file should be opened with so you can change it to anything without issue (so that BitBucket does not know what sort of file it is incase they have have some sort of scan).

i got it to work, now the strings are xor-d should i also use the cipher (in loader.c )to encode stuff or would it make it more detected

**Comment by shainodev** [comment]
yeah but the string is there any way XorStr("open") if u string search it its still gonna say that "open" is there, no?

**Comment by UnamSanctam** [comment]
You should XOR cipher the string before inputting it into there, then when it runs it will decipher the text depending on how your XOR works.

**Comment by varysuzuki** [comment]
nono my xor just xors it ig it doesnt encrypt the string in the code

**Comment by shainodev** [comment]
your cipher doesnt work with 3661 length string it puts some bad character there so it gives a error that the string didnt close
