### ISSUE TITLE
hi can i get xmr etc eth example?

### ISSUE THREAD

**Issue by minde3000** [UnamSanctam/SilentCryptoMiner#954]
hi can i get xmr etc eth example?

**Comment by minde3000** [comment]
because it seems to me that I'm making bad settings, thanks

**Comment by UnamSanctam** [comment]
Well here are the example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings. You should make either one XMR+ETC or an XMR+ETH and not all three combined.

**Comment by minde3000** [comment]
You used to give me just the file, maybe I can get it again?
ETH xmr

**Comment by UnamSanctam** [comment]
Sure, here's the ExampleSettings_Lite modified to mine ETH instead of ETC: [ExampleSettings_Lite_XMRETH.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9183590/ExampleSettings_Lite_XMRETH.zip)

**Comment by minde3000** [comment]
aciu
