### ISSUE TITLE
ETC Offline

### ISSUE THREAD

**Issue by Xeneht** [UnamSanctam/SilentCryptoMiner#959]
I have been using the miner quite a bit and the settings work correctly, it has been about a week working perfectly but now they are mostly disconnected and I don't know why. With the one that is now connected, it appeared offline and I made it run the miner again, the startup, watchdog, run as administrator, and add windows defender exclusions settings are enabled
![image](https://user-images.githubusercontent.com/99096857/181225034-b06af802-7e86-4060-af4f-d788dd8e1fc0.png)

The problem is not the web panel, the pool doesn't show that I have been mining for the last week either

**Comment by UnamSanctam** [comment]
Sounds like they were removed (most probably by an antivirus), since otherwise the watchdog would just start it up again.
