### ISSUE TITLE
Miner not running

### ISSUE THREAD

**Issue by WorksTab** [UnamSanctam/SilentCryptoMiner#961]
Hello, i am using the (lite) settings which is present in the wiki for testing, but as i used the mine checker it says watchdog is not running, it seems i am clearly missing something, i having been trying to solve this for a day solutions like turning on debug but it did not work, and reinstalling the miner , i would appreciate any assistance!

![Image](https://user-images.githubusercontent.com/110152825/181523668-03c657c6-c713-4076-9df0-e34e8f7a06bd.jpg)

**Comment by UnamSanctam** [comment]
Can you do it in this order specifically:
1. Download https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite
2. Load ExampleSettings_Lite.xml into the builder and don't change anything
3. Press "Build"
4. Run the built miner
5. Wait a minute or two and then run the checker

And then post what the checker says in the last step?

**Comment by WorksTab** [comment]
Hi, Yes sure , i still got the same error but i have documented the process incase i made a mistake i was not aware of

![Untitled](https://user-images.githubusercontent.com/110152825/181571043-cf9e1d82-07a4-499a-863e-1248452b67cb.png)

https://user-images.githubusercontent.com/110152825/181570985-c67ac404-9aca-413f-a9a4-f367da0ef7ba.mp4

**Comment by UnamSanctam** [comment]
Hmm that's really weird, I haven't seen that before, can you try disabling "Run as Administrator" and also enable "DEBUG" and then try and build and run it?

**Comment by WorksTab** [comment]
Ohh i see ,yeah sure, after doing that , this is the result i had received 


![image](https://user-images.githubusercontent.com/110152825/181589698-fe553598-3a11-44e0-8761-dd2956804279.png)


https://user-images.githubusercontent.com/110152825/181591474-c3297fca-96b2-4815-a48e-522826409799.mp4

**Comment by UnamSanctam** [comment]
Since you have 15 seconds "Start Delay" it might not have finished installing so try running the checker now, but if you disable "Startup" and build and run it does it work? In case it's something with the installation.

**Comment by WorksTab** [comment]
So i implemented the changes you asked me to

1.disabling startup and build 
2.waiting a little longer before checking the miner after running it

now the miner checker has changed display to this

![Untitled](https://user-images.githubusercontent.com/110152825/181594617-03a97998-1048-4853-846a-e71c36c2a314.png)
!

**Comment by UnamSanctam** [comment]
Hmm so it doesn't run at all, can you download Process Hacker and sort it by the "Start time" column and then run the miner (and record it)? Then we'll be able to see what happens after the program is started. Here's a guide on how to add the "Start time" column since it's not there by default:
[Process Hacker - Adding Start Time Column.webm](https://user-images.githubusercontent.com/10323655/181602382-ee29c257-eef6-4969-9bd2-999828e2e531.webm)

**Comment by WorksTab** [comment]
It seems that the miner starts for a few seconds and automatically stops

https://user-images.githubusercontent.com/110152825/181614763-98dfc113-5788-45aa-ba59-06f057589095.mp4

**Comment by UnamSanctam** [comment]
Does that build have startup enabled or not? If not then it looks like the injection might be "crashing"/failing for you, can you try downloading .NET Framework 4.5 from the internet? Sometimes it can be corrupted. Also, is your OS 64-bit? It shouldn't be able to run if not I believe but I have to ask.

**Comment by WorksTab** [comment]
I have checked, the startup is on, i tried installing the net framework 4.5 but its already installed , Yes correct it is OS 64-bit


https://user-images.githubusercontent.com/110152825/181765263-ea32ff42-7444-4526-b391-70e6f328c506.mp4

**Comment by UnamSanctam** [comment]
Hmm, really weird, either your antivirus is blocking it from being installed or there's something weird with your computer. Can you check if you can find the installed file inside `%ProgramFiles%\Google\Chrome`? Easiest way is to press Win+R and then enter `%ProgramFiles%\Google\Chrome` and then pressing enter. Also check for the Task Scheduler entry inside your Task Scheduler to see if it was able to add that (open Task Scheduler and then press the first folder named something like Library to the left).

**Comment by WorksTab** [comment]
i encountered some error as i ran the program and i  had also open the task scheduler and found 2 folder in the library ,what should i do now

https://user-images.githubusercontent.com/110152825/181772297-72d6097d-ec13-40a1-b04e-d85063af26ab.mp4

m

**Comment by UnamSanctam** [comment]
Try entering "%ProgramFiles%\Google\Chrome" in the "Run" and then in the Task Scheduler check the "Task Scheduler Library" folder for the entry and not the other folders, not one of the other folders. But it looks like you might have Avast installed so your antivirus could just be blocking/removing it.

**Comment by WorksTab** [comment]
it appears that the entry was not recorded in the folder, shall i try to uninstall avast first now?

https://user-images.githubusercontent.com/110152825/181782755-5ac120ac-4148-4381-9ec9-af28d40e372a.mp4

t

**Comment by UnamSanctam** [comment]
Yes or go into Avast and turn off all the core "Shields" (called something like that) temporarily and then test it.

**Comment by WorksTab** [comment]
I have uninstalled avast but as i wanted to run the program i found a new type of error,not sure what caused it


https://user-images.githubusercontent.com/110152825/181790601-c68dd2e1-5abf-438b-947f-4e58c2c5ec2d.mp4

**Comment by UnamSanctam** [comment]
When you uninstalled Avast it most likely activated your Windows Defender again which probably deletes the files while they are getting built.

**Comment by WorksTab** [comment]
ohh okay i see, shall i delete everything and install again

**Comment by UnamSanctam** [comment]
Temporarily disable the different Windows Defender protections and try building it again.

**Comment by UnamSanctam** [comment]
Alright then it was the antivirus removing it, if you have "Startup" enabled then it will automatically start it with Windows, you should be able to find the entry in the Task Scheduler now (called `GoogleUpdateTaskMachineQC` by default).

**Comment by WorksTab** [comment]
2 files called "donut" and "coin miner" got flagged as virus by windows defender and after these two were deleted,the program miner cant run again when i check the miner checker,did i delete somthing importamt by mistke

**Comment by UnamSanctam** [comment]
Your antivirus removed two of the compiler files for compiling parts of the miner, those files will be recreated if you try building it again but you'll have to add an antivirus exclusion to the folder you're building to to stop them from being removed again.

**Comment by WorksTab** [comment]
i think it seems to be working now, thankyou , i have 2 final questions 

1. iam going to have 50 workers, what pools do you recommend that is good to use for massive workers 
2. when the mine.exe , mine-checker.exe is removed,will the miner stop running or it will keep on going

Thanks for taking your time to respond and helping me 

![ns](https://user-images.githubusercontent.com/110152825/181866763-6ecafbbc-bdc8-454b-8715-451174333d79.png)

**Comment by UnamSanctam** [comment]
1. 2miners, nanopool and MoneroOcean work for massive amounts (not certain about MoneroOcean though).
2. Since it has been installed on the computer then it will keep going if those files are removed. Only the `mine.exe` is required to install it, after `mine.exe` has been started then it will install itself and after that `mine.exe` is free to be removed.

**Comment by WorksTab** [comment]
Great, thank you so much

really appreciate your support
