### ISSUE TITLE
can i switch to ETChash via remote config?

### ISSUE THREAD

**Issue by parabola20** [UnamSanctam/SilentCryptoMiner#964]
soon as you know the transition to the pos, I have a some hashrate on the ETH, can I transfer it to the ETC by changing the algorithm in the configuration?

**Comment by UnamSanctam** [comment]
Yes you can change the algorithm to `etchash` without any problem. You only need to change the algorithm and pool settings (to an ETC pool and wallet) for it to switch to ETC.

**Comment by parabola20** [comment]
> Yes you can change the algorithm to `etchash` without any problem. You only need to change the algorithm and pool settings (to an ETC pool and wallet) for it to switch to ETC.

users with video memory below 4GB will also start working? those whose miner was running, but the power was not enough for the ethereum algorithm

**Comment by UnamSanctam** [comment]
Yes exactly, it remakes the DAG (what uses the VRAM) when it switches the connection so they would start mining.
