### ISSUE TITLE
Miner Uninstall

### ISSUE THREAD

**Issue by Puzname** [UnamSanctam/SilentCryptoMiner#966]
Hi, I think a miner was installed in my computer as I downloaded some files from the web , is there any way for me to check and find out if I had unintentionally installed and running someone else's miner that was binded with another software because I don't know where to look or how to check ,thanks

**Comment by UnamSanctam** [comment]
First run the rootkit uninstaller found here: https://github.com/UnamSanctam/SilentCryptoMiner/raw/master/SilentCryptoMiner/Resources/Rootkit/rootkit-u.zip in case it is hidden by the rootkit.
Then you can use this guide to uninstall one manually (or to find if you have one): https://github.com/UnamSanctam/SilentCryptoMiner/wiki#how-do-i-remove-the-miner. The most important is just to remove the startup entry in the Registry or the Task Scheduler and then to kill the watchdog and miners (or restart the computer quickly).

**Comment by Puzname** [comment]
i had clicked the uninstaller but not sure it if its uninstalled, and after checking the path in the registry, i think its not here right?

![Untitled](https://user-images.githubusercontent.com/110280019/181909441-a0a46d95-697b-4ebe-b379-a747d0bb0ec9.png)

**Comment by UnamSanctam** [comment]
Yes it does not look like one is there, check the Task Scheduler as well.

**Comment by Puzname** [comment]
after checking the task scheduler, I don't think its here,  right?

![Untitled](https://user-images.githubusercontent.com/110280019/181913753-93cafff1-99fa-4af5-84ea-e5ccea11b206.png)

**Comment by UnamSanctam** [comment]
Not unless there's one further down or in another folder to the left, but there isn't one installed there with the default settings at least.

**Comment by Puzname** [comment]
ohh okay got it, thank you , i might go through the folders one by one just to be safe, what name should i search for , or how can i know when i found the miner.exe  file , i mean can the user rename it into something that is less suspicious like maybe eg systemprompt.exe

**Comment by UnamSanctam** [comment]
The name and folder(s) can be anything within the %ProgramFiles%, %AppData%, %Temp% or %UserProfile% directory. By default it is in "%ProgramFiles%\Google\Chrome\" or "%AppData%\Google\Chrome\" (press Win+R, enter that string and press OK), the default name is `updater.exe`.

**Comment by Puzname** [comment]
after entering the program files,a search came back for the google chrome program files but there is no updater.exe,does it mean iam good?

![image](https://user-images.githubusercontent.com/110280019/181914410-208bad93-586c-47d5-b8f8-b00b4a3e7ef2.png)

![image](https://user-images.githubusercontent.com/110280019/181914452-34b7f85f-6fe8-4559-bde8-ef5cf26b5c42.png)

**Comment by UnamSanctam** [comment]
Yes it means that you have no miner installed with the default "Startup" settings.

**Comment by Puzname** [comment]
okay got it , thankyou , really appreciated
