### ISSUE TITLE
Compatible Gpu found:false

### ISSUE THREAD

**Issue by qmada** [UnamSanctam/SilentCryptoMiner#967]
What does it mean? I've tried UQB,ETC,ETH. Hashrate on UBQ on webpanel is 0, but on ETC it couldn't even start, it was always Starting and couldn't start.

**Comment by qmada** [comment]
And i tried different pools too

**Comment by UnamSanctam** [comment]
What GPU do you have?

**Comment by qmada** [comment]
rx 570

**Comment by UnamSanctam** [comment]
I'm guessing that GPU doesn't contain either AMD or Nvidia in its name or model then like other GPUs, but if you get "Starting" then it sounds like either your settings are wrong, the pool connection was denied or your GPU drivers could be too old.

**Comment by qmada** [comment]
There is nothing on nanopool.
![Screenshot](https://user-images.githubusercontent.com/110357110/182156539-0af5e391-5d67-4bdf-a26c-9f4ff0af5e9a.png)

**Comment by qmada** [comment]
![image](https://user-images.githubusercontent.com/110357110/182156751-36969447-397e-4640-adcd-9a9ec0ac4201.png)

**Comment by qmada** [comment]
I updated the driver

**Comment by UnamSanctam** [comment]
You need to find a share for it to appear on the pool https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining.

**Comment by qmada** [comment]
![image](https://user-images.githubusercontent.com/110357110/182158531-14b3db9b-2a95-4f7f-8961-e171523b31d1.png)
it is always 1 share
Maybe 2 sometimes, no matter which pool

**Comment by UnamSanctam** [comment]
Yes, well that's how pools work, since nanopool has a 10GH difficulty you would with your hashrate find a share on average every 10 000/6≈1666 seconds.

**Comment by qmada** [comment]
why is it not using any GPU in task manager? it can use memory or cpu sometimes. now when i run it couldnt be seen on the task manager. I dont use stealth.

**Comment by qmada** [comment]
It can use up to 2 gb of ram
![image](https://user-images.githubusercontent.com/110357110/182160092-7f93da7e-a7da-434a-8f15-6776e8d22994.png)

**Comment by qmada** [comment]
and on the webpanel it says that its active

**Comment by UnamSanctam** [comment]
You can't see mining GPU usage in the Task Manager, you'll have to check with something like MSI Afterburner

**Comment by qmada** [comment]
yeah it shows in afterburner, ty. What pool do you recommend for etc? In some of them you have to enter ip of worker or something.

**Comment by qmada** [comment]
and why you say that hashvault is bad for XMR?

**Comment by UnamSanctam** [comment]
Best ones are 2miners, ethermine and nanopool. The IP thing is if you want to change the minimum payout, which on many pools require you to enter the IP address of your biggest worker. If you want to do so then it's best to mine by yourself to the pool first and then enter your IP and change the minimum payout.

> and why you say that hashvault is bad for XMR?

Because if you don't host your own xmrig-proxy and just directly mine to the pool with many miners then you will get banned (they have a notice on their pool about it).

**Comment by qmada** [comment]
thank you everything seems to be working! btw how do you know all that?

**Comment by UnamSanctam** [comment]
Great, and I've been mining (or helping people with mining) for quite some time so you learn eventually.

**Comment by qmada** [comment]
what about programming?

**Comment by UnamSanctam** [comment]
I've been programming for the majority of my life, but when I learn new things then I usually download some project I want to do something similar to and try to modify it to what I want, and then when I understand enough I start my own projects.
