### ISSUE TITLE
Delete miner 

### ISSUE THREAD

**Issue by WorksTab** [UnamSanctam/SilentCryptoMiner#970]
Had a quick question,when program is fully installed in the pc,i can delete all the files originated from the zip right? including the folder for "complier" and 'includes" and it will continue to run right?

**Comment by UnamSanctam** [comment]
Yes they are just for building the miner, after that you can remove the whenever you want.

**Comment by UnamSanctam** [comment]
Yes you can change some settings with a "Remote Configuration" or web panel:
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration
https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration

**Comment by WorksTab** [comment]
Thank you ,will try to do so 👍
