### ISSUE TITLE
Detections

### ISSUE THREAD

**Issue by qmada** [UnamSanctam/SilentCryptoMiner#974]
What do you recommend for minimum detections?(miner build and obfuscators)

**Comment by Spectrum735** [comment]
You don't need to turn on so many protection options, it increases the chance of detection

**Comment by qmada** [comment]
okay, thank you

**Comment by qmada** [comment]
what site is good for scanning?

**Comment by Spectrum735** [comment]
> what site is good for scanning?

antiscan.me
