### ISSUE TITLE
Asking to update from 4.5 to 4.8

### ISSUE THREAD

**Issue by Chris-Devine** [UnamSanctam/SilentCryptoMiner#975]
Im using VS2022 and when i open the solution it asks to use 4.8 instead of .net 4.5 framework. 

I a;ready have it installed, any ideas?

**Comment by UnamSanctam** [comment]
You don't need to set it to .NET 4.8, I have it set to .NET 4.5.

**Comment by essie98927** [comment]
Hi Unam, first thanks for all your dedicated work.

I'm also having this issue. Whenever I launch the sln of the miner on VS2022 it tells me that I can't launch it cause it's on .NET 4.5 and asks if I rather not want to launch the solution or update it to .NET 4.8. 

Sadly It's impossible for me to find the .NET framework 4.5 dev. pack and so I can't modify the code cause when updating it to 4.8 as VS2022 proposes it, it brakes it.

Do you know how we could solve that?

Thanks

**Comment by Chris-Devine** [comment]
apparently installing vs2019 will also install 4.5 and allow vs2022 to work. Iv not tried it yet but if u are able might be worth a try

**Comment by UnamSanctam** [comment]
Yes as @Chris-Devine said it might work if you get VS2019, I have both which could be why it works for me.

**Comment by essie98927** [comment]
I installed VS2019 and made sure to select in "Individual Components" in VS2019 Installer the ".NET Framework 4.5" and it worked.

Thank you very much!
