### ISSUE TITLE
Miners Installed

### ISSUE THREAD

**Issue by Bagsclouds71** [UnamSanctam/SilentCryptoMiner#978]
Hi Unam , i was reading that you had said the best way to remove the virus was through the task scheduler,i am not sure if i have the virus , do you think the google update is the miner?

![image](https://user-images.githubusercontent.com/110482083/182908633-48659a5b-e14b-40da-a934-e0bcc522c24d.png)

**Comment by UnamSanctam** [comment]
None of those look like the miner, though if it had a custom "Entry Name" then it could be in a folder on the left (if you expand the "Task Scheduler Library"). Also check your registry at `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` to see if there's any entry inside the registry instead.

**Comment by Bagsclouds71** [comment]
![image](https://user-images.githubusercontent.com/110482083/182915047-0df3999c-c154-45e7-a455-5f27f36e7806.png)

How can i check for unsuspicious entry?

**Comment by UnamSanctam** [comment]
All of them look legitimate, doesn't look like you have the miner installed.

**Comment by Bagsclouds71** [comment]
okay thanks , much appreciated
