### ISSUE TITLE
Error when opening any file in the "Forms" folder on Visual Studio

### ISSUE THREAD

**Issue by essie98927** [UnamSanctam/SilentCryptoMiner#979]
Hi

Whenever I try to open any file in the "Forms folder", for example "AdvancedOptions.cs" I have a ton of errors...

For example: 

![image](https://user-images.githubusercontent.com/110569734/182908930-b0bef029-ae5a-4963-bb41-ab20b766fc01.png)

![image](https://user-images.githubusercontent.com/110569734/182912834-cfdd225a-8551-4636-8637-8d9643b770ca.png)

I don't understand why it's happening... I had the same error when opening the files with VS2022 and a different framework, though the framework was the problem so went on VS2019 and another framework but still the same errors.

Tried changing the platform to any of the possible options, but nothing works, still getting all these errors.

![image](https://user-images.githubusercontent.com/110569734/182910560-c3a90689-a5ee-4684-b4c9-f4acc820feea.png)

If anyone has already encountered these issues or has any ideas how to solve them it would be much appreciated.

Thanks

**Comment by UnamSanctam** [comment]
You need to build the project first, the VS designer only works after a project has been built once.

**Comment by essie98927** [comment]
When I build the project I have these warnings: https://pastebin.com/medxdmhU will that affect the project? It still says that the Build succeeded tho...

But I can now open the forms files thanks.

**Comment by UnamSanctam** [comment]
No the warnings are just since there's no XML comments above each function for documentation, you can ignore them.

**Comment by essie98927** [comment]
Thank you very much for your help!
