### ISSUE TITLE
Spyware

### ISSUE THREAD

**Issue by Bagsclouds71** [UnamSanctam/SilentCryptoMiner#980]
i want to install some miners in victims computer , how to check if victim has spyware that tells warms them about who does what to their computers , any tips or suggestions is greatly appreciated, the victim has 15 computers , but i just wanna be make sure they dont have spyware or take proper precautions if they do

**Comment by UnamSanctam** [comment]
What kind of spyware? You mean some kind of monitoring software on the computers? Most people don't have that, and even then to avoid it you would have to know what specific spyware they have to be able to clean logs and everything afterwards.

**Comment by Bagsclouds71** [comment]
i think you are right, but if such a spyware is installed,it will just be installed like a normal program right or if it is installed in the memory ,can i check from registry startup that you mentioned if the spyware is present or not

**Comment by UnamSanctam** [comment]
Totally depends on what kind of spyware/monitoring software it is, normal commercial software will be installed just like any other program and can usually be found in the "Uninstall program" list in the control panel, other monitoring software is usually installed by placing the .exe somewhere and adding an entry into the Registry, Task Scheduler or Startup folder.

**Comment by Bagsclouds71** [comment]
ohh wow, thankyou so much unam,very much appreciated!
