### ISSUE TITLE
where can i find no distribute scanner?

### ISSUE THREAD

**Issue by qmada** [UnamSanctam/SilentCryptoMiner#981]

**Comment by essie98927** [comment]
scantime scanners: antiscan.me / kleenscan.com / checkzilla.io

runtime scanners: kleenscan.com (in beta) / checkzilla.io

**Comment by qmada** [comment]
antiscan is not distributing?

**Comment by essie98927** [comment]
The 3 website I gave you don't distribute results. 

Little tips for antiscan, once you ran out of free scans just clear the cookies (and if possible change your ip) and you'll get all the free scans back.
