### ISSUE TITLE
Rename XMR Miners

### ISSUE THREAD

**Issue by Bagsclouds71** [UnamSanctam/SilentCryptoMiner#982]
Is it possible to rename XMR miners Workers, I saw the rename option for eth miners but pardon me if i have missed it but i did not see the option for XMR miners

**Comment by UnamSanctam** [comment]
It depends on the pool, XMR and ETH uses different "protocols" so for XMR miners it fully depends on the pool, many pools use the `WalletAddress.WorkerName` format to add workers, some use the "Password" field, then the rest uses their own variations but those two are the most common. You'll have to check the pool documentation.

**Comment by Bagsclouds71** [comment]
ohh alright got it,thanks unam
