### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentCryptoMiner#984]
Hey, I wanna use a c++ loader/rat to ShellExecuteA the miner but to also have control like remote desktop and stuff, and I wanted to ask you is it a good idea to code my own rat with the ShellExecuteA feature or use something old but stable like Ozone rat or babylon rat or buy remcos rat? or should I make the rat C#? that will make defeat the purpose kinda, cause ShellExecuteA makes it like. if the powershell command is detected it closes powershell or doesnt do the command, but for c# i feel like it'll catch on to the c# app and close it. What should i do?

**Comment by UnamSanctam** [comment]
Using premade RATs will be more stable which is usually what you want, but it shouldn't really matter since what's important is only that it's undetected. If you can code an undetected RAT yourself then it would be better but that's quite difficult so usually stable RATs are used and then crypted (if not undetected already in case of some paid RATs).

**Comment by shainodev** [comment]
> Using premade RATs will be more stable which is usually what you want, but it shouldn't really matter since what's important is only that it's undetected. If you can code an undetected RAT yourself then it would be better but that's quite difficult so usually stable RATs are used and then crypted (if not undetected already in case of some paid RATs).

thanks. oh also one question, bitrat got cracked and inside was found a file searcher and it was interesting i've never seen this before it takes common words i guess that wallet phrases use and i thought that its weird its the only thing it does. do you only need to put a wallet phrase in any wallet and u get in the wallet? i thought u need passwords and stuff and how does he know which wallet is used?

**Comment by shainodev** [comment]
now i know the answer, im making a file grabber now and im curious what folders should i search for, i have already delt with the Access Denied exception when i getfiles from every directory starting from C:\ and now idk if i should add all these keywords to make the search if the file name has these "discord", "pass", "acc", "backup" cause backup may be the name of some log files anywhere that windows may have created and if the file contains "discord", "pass", "acc", "backup" or any of these
![image](https://user-images.githubusercontent.com/77803435/183246390-42c10e56-e75e-4e55-8e77-1d36f7513389.png)
![image](https://user-images.githubusercontent.com/77803435/183246400-1105c8dd-aa90-42ce-a37f-d3fac8231876.png)

but still any log files that windows or 3rd party app has created may contain "modify" or "discord" for example discord itself, what should i do?

**Comment by UnamSanctam** [comment]
> thanks. oh also one question, bitrat got cracked and inside was found a file searcher and it was interesting i've never seen this before it takes common words i guess that wallet phrases use and i thought that its weird its the only thing it does. do you only need to put a wallet phrase in any wallet and u get in the wallet? i thought u need passwords and stuff and how does he know which wallet is used?

If you get the seed phrase then you can import the wallet into any program or website you want.

> but still any log files that windows or 3rd party app has created may contain "modify" or "discord" for example discord itself, what should i do?

You can't really do anything about it except create different exceptions such as excluded folders or words, but most file searchers (that I've seen) take all files within the search parameters and then it's up to the person who ran the file searcher to look through the files.

**Comment by shainodev** [comment]
> > thanks. oh also one question, bitrat got cracked and inside was found a file searcher and it was interesting i've never seen this before it takes common words i guess that wallet phrases use and i thought that its weird its the only thing it does. do you only need to put a wallet phrase in any wallet and u get in the wallet? i thought u need passwords and stuff and how does he know which wallet is used?
> 
> If you get the seed phrase then you can import the wallet into any program or website you want.
> 
> > but still any log files that windows or 3rd party app has created may contain "modify" or "discord" for example discord itself, what should i do?
> 
> You can't really do anything about it except create different exceptions such as excluded folders or words, but most file searchers (that I've seen) take all files within the search parameters and then it's up to the person who ran the file searcher to look through the files.

should i make it only look thru desktop, documents and recent files and what keywords do u suggest to search?

also what if it grabs too many files and the zip file is gonna be more than 8 mb?
