### ISSUE TITLE
Miners do not show up on NanoPool - ETC

### ISSUE THREAD

**Issue by LokeYourLord** [UnamSanctam/SilentCryptoMiner#99]
So this issue pertains to ONLY NanoPool ETC, not NanoPool ETH.

For the SCM, it does show the mining clients in the "Workers" list (and other relevant data. Ignore the "0" rating, I've basically only been using all miners for ETC atm, but I did try one on ETH and it showed up after finding the first share already, as seen in this picture)
![image](https://user-images.githubusercontent.com/5807595/143528821-690ead87-84df-4848-8089-751b2a9dee87.png)

The problem is, that with the exact same config for ETC, the miners do not show up under "Workers" on the ETC page. Which is really bad if I want to change the payout minimum. See here:
![image](https://user-images.githubusercontent.com/5807595/143528898-765ff23f-4abd-43b2-a944-4850fa793ccb.png)

It has been this way ever since I started this endeavour yesterday. Any ideas as to why?

**Comment by UnamSanctam** [comment]
Yes the Nanopool ETC pool has always been bugged, worker names usually don't work there. There isn't really that much to do since the problem is on the pool side.

**Comment by LokeYourLord** [comment]
I see, so there's no workaround I can do with the donfigs or such I assume? Shame, but nothing to do then.
Any other, better pool for ETC you can recommend?

**Comment by UnamSanctam** [comment]
Some people have had some successes but for others it haven't worked. Usually I recommend Ezil or Ethermine for ETC. Though just a "warning", Ethermines statistics can be deceiving since their "Current Hashrate" actually displays the average over 1 hour which makes a lot of people falsely believe that the hashrate on Ethermine is lower than on other pools.

**Comment by LokeYourLord** [comment]
> Some people have had some successes but for others it haven't worked. Usually I recommend Ezil or Ethermine for ETC. Though just a "warning", Ethermines statistics can be deceiving since their "Current Hashrate" actually displays the average over 1 hour which makes a lot of people falsely believe that the hashrate on Ethermine is lower than on other pools.

Yeah I am aware of the averages that are displayed, that is fine with me, I can see the actual hashrate in the panel anyways so they will always vary a little. Thanks then, gotta setup Ethermine then I guess *sigh*
