### ISSUE TITLE
question about profitability

### ISSUE THREAD

**Issue by parabola20** [UnamSanctam/SilentCryptoMiner#992]
I mine ETC, I recently noticed that with the same hashrate, fewer coins are mined than before. does it make sense to try other algorithms like Ravencoin? with the same hashrate, will there be changes in profits?

*using translator*

**Comment by UnamSanctam** [comment]
It's because the ETC price increased so more people started mining, but the amount in dollars mined has increased about 70% compared to before. So mining ETC is currently more profitable than it was previously.
