### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/SilentCryptoMiner#996]
can you put Persistence like bluescreen death like dcrat when anti virus delete it make bluescreen or after select delete in anti virus he ask you restart then dcrat startup again it will be so good option in your next update

**Comment by UnamSanctam** [comment]
I probably won't add a bluescreen on exit since it will trigger on other things than getting killed, and BSoD wouldn't really do much for persistence in the miner anyways since you can delete the miner without killing it because everything is injected. The watchdog already exists for persistence and adding a BSoD would stop the watchdog from working since the computer would crash before the watchdog could restore the miner if it's killed or deleted.

**Comment by UnamSanctam** [comment]
I could potentially investigate adding BSoD for the watchdog though.

**Comment by Spectrum735** [comment]
You can addthe BSoD function to watchdog. But you should add start Delay before watchdog's main loop, like this:
`...`
`_rxm_ = _rAESMethod_(File.ReadAllBytes(_rplp_), true);`
`Thread.Sleep(startDelay * 1000 + 2000); //this delay`
` _rWDLoop_();`
`...`
and to call bsod you should run `powershell` with `wininit` argument.

**Comment by UnamSanctam** [comment]
> You can add the BSoD function to watchdog. But you should add start Delay before watchdog's main loop, like this: `...` `_rxm_ = _rAESMethod_(File.ReadAllBytes(_rplp_), true);` `Thread.Sleep(startDelay * 1000 + 2000); //this delay` ` _rWDLoop_();` `...` and to call bsod you should run `powershell` with `wininit` argument.

I can add a delay though is it needed? Since the watchdog checks if the miners are started for a minimum of 3 loops before trying to start them again. Unless you want a delay to maybe get around some AV sandboxing.

**Comment by Spectrum735** [comment]
> Unless you want a delay to maybe get around some AV sandboxing.

PC crash without this delay, if you add bsod function, because watchdog ran before miner

**Comment by UnamSanctam** [comment]
But since it runs the loop 3 times before doing anything about it (meaning it does `Thread.Sleep` 3 times) wouldn't that not matter no?

**Comment by Spectrum735** [comment]
> wouldn't that not matter no?
I checked it out. Miner starts later anyway. Maybe I'm running it wrong somehow.

**Comment by UnamSanctam** [comment]
Yes the miners gets injected after the watchdog but it shouldn't really matter, since the watchdog currently waits `2 * startDelay * 1000 + 20000` on the first start before trying to start the miners again, and the miners will definitely get injected before that.

**Comment by Spectrum735** [comment]
> since the watchdog currently waits `2 * startDelay * 1000 + 20000`
My bad, i was delete 20 secs at nested rwd loop delay. I wanted to create the second watchdog, that will be monitor for the first. Because user can delete or rename main miner file and create folder with the same miner's name. And the main watchdog can't create it back.

**Comment by shainodev** [comment]
> I probably won't add a bluescreen on exit since it will trigger on other things than getting killed, and BSoD wouldn't really do much for persistence in the miner anyways since you can delete the miner without killing it because everything is injected. The watchdog already exists for persistence and adding a BSoD would stop the watchdog from working since the computer would crash before the watchdog could restore the miner if it's killed or deleted.
> 
> It feels like BSoD only really makes sense if you don't have your program injected, since then you can not remove it because it's running and you can not kill it because you will BSoD, but since the miners are injected that wouldn't work.

it technically still can be removed by antivirus, by the antivirus deleting the startup key, no?

**Comment by UnamSanctam** [comment]
> it technically still can be removed by antivirus, by the antivirus deleting the startup key, no?

Yes which is my point, a bluescreen wouldn't prevent that and could even stop the watchdog from re-adding the miner as well.

**Comment by tarekxxx** [comment]
just ask for this option because i use dcrat with edit version so good they trying everything i think to remove my rat but they cant because when av catch it and user delete it ask to restart then nothing happen my rat keep alive again and they even tired from alot of restarts they not mind anymore lol
