### ISSUE TITLE
Small question about settings

### ISSUE THREAD

**Issue by Bagsclouds71** [UnamSanctam/SilentCryptoMiner#999]
![image](https://user-images.githubusercontent.com/110482083/183296525-c9d93cd6-500b-4e97-956c-f9ef6b501bcb.png)

Hi unam,i have a little question, i have used the builter and made the miners, i forgot to save my settings of this build,is there anyway to save settings of this build or should i create the miner again and save it then

**Comment by UnamSanctam** [comment]
You'll have to create it again and save the settings.
